import '../tes_seleksi_model.dart';

List<QuestionItem> getIlmuKomunikasiQuestions() {
  return const [
    QuestionItem(
      id: 'kom_001',
      questionText: 'Bapak Ilmu Komunikasi Dunia yang merumuskan fungsi komunikasi dan pendiri studi komunikasi massal adalah:',
      options: ['Wilbur Schramm', 'Harold Lasswell', 'Marshall McLuhan', 'David Berlo'],
      correctOptionIndex: 0,
      explanation: 'Wilbur Schramm dianggap sebagai bapak pendiri ilmu komunikasi modern.',
    ),
    QuestionItem(
      id: 'kom_002',
      questionText: 'Formula komunikasi Lasswell yang terkenal merangkum unsur komunikasi dengan kalimat:',
      options: ['Who says What in Which Channel to Whom with What Effect', 'Source, Message, Channel, Receiver', 'Sender, Encoder, Decoder, Receiver', 'Input, Process, Output, Feedback'],
      correctOptionIndex: 0,
      explanation: 'Harold Lasswell (1948) merumuskan formula 5 unsur komunikasi.',
    ),
    QuestionItem(
      id: 'kom_003',
      questionText: 'Model komunikasi SMCR (Source, Message, Channel, Receiver) dirumuskan oleh:',
      options: ['David K. Berlo', 'Wilbur Schramm', 'Shannon & Weaver', 'Barnlund'],
      correctOptionIndex: 0,
      explanation: 'Berlo merumuskan model linier SMCR.',
    ),
    QuestionItem(
      id: 'kom_004',
      questionText: 'Model matematis komunikasi yang memperkenal konsep Gangguan (Noise) dan Entropi dikembangkan oleh:',
      options: ['Claude Shannon dan Warren Weaver', 'Lasswell', 'Schramm', 'Gerbner'],
      correctOptionIndex: 0,
      explanation: 'Model Shannon-Weaver (1949) merupakan dasar teori informasi matematis.',
    ),
    QuestionItem(
      id: 'kom_005',
      questionText: 'Segala sesuatu yang merusak, mengganggu, atau menyimpangkan penerimaan pesan komunikasi dinamakan:',
      options: ['Gangguan (Noise)', 'Feedback', 'Entropy', 'Redundancy'],
      correctOptionIndex: 0,
      explanation: 'Noise memicu hambatan penyampaian pesan.',
    ),
    QuestionItem(
      id: 'kom_006',
      questionText: 'Tanggapan atau respon balik yang dikirim penerima pesan kepada pengirim pesan dinamakan:',
      options: ['Umpan Balik (Feedback)', 'Noise', 'Encoding', 'Decoding'],
      correctOptionIndex: 0,
      explanation: 'Feedback menjadikan komunikasi berlanjut interaktif sirkuler.',
    ),
    QuestionItem(
      id: 'kom_007',
      questionText: 'Proses penerjemahan pikiran/gagasan oleh komunikator menjadi simbol/sandi pesan dinamakan:',
      options: ['Enkodifikasi (Encoding)', 'Dekodifikasi (Decoding)', 'Transmisi', 'Resepsi'],
      correctOptionIndex: 0,
      explanation: 'Encoding merubah pesan gagasan abstrak menjadi simbol verbal/non-verbal.',
    ),
    QuestionItem(
      id: 'kom_008',
      questionText: 'Proses penerjemahan dan penginterpretasian simbol/sandi pesan oleh komunikan dinamakan:',
      options: ['Dekodifikasi (Decoding)', 'Enkodifikasi (Encoding)', 'Persepsi', 'Sensasi'],
      correctOptionIndex: 0,
      explanation: 'Decoding mengolah makna simbol pesan yang diterima.',
    ),
    QuestionItem(
      id: 'kom_009',
      questionText: 'Komunikasi yang terjadi dengan diri sendiri (seperti merenung atau solilokui) dinamakan komunikasi:',
      options: ['Intrapersonal', 'Interpersonal', 'Kelompok', 'Massa'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Intrapersonal terjadi dalam pemrosesan pikiran diri sendiri.',
    ),
    QuestionItem(
      id: 'kom_010',
      questionText: 'Komunikasi tatap muka antara dua orang secara langsung dinamakan komunikasi:',
      options: ['Interpersonal (Antarpribadi)', 'Intrapersonal', 'Organisasi', 'Publik'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Interpersonal terjadi langsung antar pribadi.',
    ),
    QuestionItem(
      id: 'kom_011',
      questionText: 'Teori Penetrasi Sosial (Social Penetration Theory) yang mengibaratkan pembukaan diri seperti mengupas lapisan bawang dipelopori oleh:',
      options: ['Altman dan Taylor', 'Berger dan Calabrese', 'Watzlawick', 'Thibaut dan Kelley'],
      correctOptionIndex: 0,
      explanation: 'Altman & Taylor mengibaratkan pembukaan diri (self-disclosure) seperti mengupas kulit bawang.',
    ),
    QuestionItem(
      id: 'kom_012',
      questionText: 'Teori Pengurangan Ketidakpastian (Uncertainty Reduction Theory) dalam awal hubungan diajukan oleh:',
      options: ['Berger dan Calabrese', 'Altman dan Taylor', 'Festinger', 'Mead'],
      correctOptionIndex: 0,
      explanation: 'URT menjelaskan motivasi individu mengurangi ketidakpastian saat berkenalan.',
    ),
    QuestionItem(
      id: 'kom_013',
      questionText: 'Teori Pertukaran Sosial (Social Exchange Theory) menyatakan hubungan dipertahankan jika:',
      options: ['Ganjaran (Rewards) lebih besar daripada Biaya (Costs)', 'Biaya lebih besar', 'Sama dengan nol', 'Tidak ada feedback'],
      correctOptionIndex: 0,
      explanation: 'Thibaut & Kelley merumuskan evaluasi hubungan berbasis perbandingan Cost & Benefit.',
    ),
    QuestionItem(
      id: 'kom_014',
      questionText: 'Jendela Johari (Johari Window) membagi kesadaran komunikasi diri ke dalam 4 kuadran yaitu:',
      options: ['Open, Blind, Hidden, Unknown', 'Public, Private, Secret, Silent', 'Self, Other, Both, Neither', 'Known, Unknown, Shared, Masked'],
      correctOptionIndex: 0,
      explanation: 'Luft & Ingham merumuskan Johari Window (Open, Blind, Hidden, Unknown).',
    ),
    QuestionItem(
      id: 'kom_015',
      questionText: 'Kuadran Johari Window yang menggambarkan hal-hal yang diketahui oleh diri sendiri dan juga diketahui orang lain adalah:',
      options: ['Wilayah Terbuka (Open Area)', 'Wilayah Buta (Blind Area)', 'Wilayah Tersembunyi (Hidden Area)', 'Wilayah Tak Dikenal (Unknown Area)'],
      correctOptionIndex: 0,
      explanation: 'Open Area adalah transparansi komunikasi publik.',
    ),
    QuestionItem(
      id: 'kom_016',
      questionText: 'Kuadran Johari Window yang menggambarkan hal-hal yang diketahui orang lain tetapi tidak disadari diri sendiri dinamakan:',
      options: ['Wilayah Buta (Blind Area / Blind Spot)', 'Open Area', 'Hidden Area', 'Unknown Area'],
      correctOptionIndex: 0,
      explanation: 'Blind Area mencakup kebiasaan unik yang tidak disadari diri pribadi.',
    ),
    QuestionItem(
      id: 'kom_017',
      questionText: 'Penggunaan gerakan tubuh, ekspresi wajah, dan gestur dalam komunikasi non-verbal dinamakan:',
      options: ['Kinesik (Kinesics)', 'Proksemik', 'Parabahasa', 'Haptik'],
      correctOptionIndex: 0,
      explanation: 'Kinesik menguji bahasa tubuh dan gerakan fisik.',
    ),
    QuestionItem(
      id: 'kom_018',
      questionText: 'Studi penggunaan jarak ruang antar individu dalam komunikasi non-verbal dikembangkan Edward T. Hall dinamakan:',
      options: ['Proksemik (Proxemics)', 'Kinesik', 'Kronemik', 'Paralinguistik'],
      correctOptionIndex: 0,
      explanation: 'Proksemik membagi zona jarak (Intim, Pribadi, Sosial, Publik).',
    ),
    QuestionItem(
      id: 'kom_019',
      questionText: 'Unsur nada suara, intonasi, kecepatan bicara, dan jeda vokal dalam komunikasi non-verbal dinamakan:',
      options: ['Parabahasa / Paralinguistik', 'Kinesik', 'Haptik', 'Artefak'],
      correctOptionIndex: 0,
      explanation: 'Paralinguistik mengkaji aspek vokal di luar kata-kata.',
    ),
    QuestionItem(
      id: 'kom_020',
      questionText: 'Penggunaan komunikasi berbasis sentuhan fisik (seperti berjabat tangan atau merangkul) dinamakan:',
      options: ['Haptik (Haptics)', 'Kinesik', 'Proksemik', 'Olfatik'],
      correctOptionIndex: 0,
      explanation: 'Haptik menguji makna sentuhan fisik.',
    ),
    QuestionItem(
      id: 'kom_021',
      questionText: 'Penggunaan waktu (seperti ketepatan waktu atau kelambatan) dalam komunikasi non-verbal dinamakan:',
      options: ['Kronemik (Chronemics)', 'Proksemik', 'Kinesik', 'Haptik'],
      correctOptionIndex: 0,
      explanation: 'Kronemik mengukur pesan implisit dari manajemen waktu.',
    ),
    QuestionItem(
      id: 'kom_022',
      questionText: 'Teori Agenda Setting (Pengaturan Agenda Media) yang mengemukakan media tidak memberi tahu apa yang dipikirkan tapi memengaruhi apa yang dipikirkan dipelopori oleh:',
      options: ['Maxwell McCombs dan Donald Shaw', 'Noelle-Neumann', 'Gerbner', 'Bandura'],
      correctOptionIndex: 0,
      explanation: 'McCombs & Shaw (1972) merumuskan Teori Agenda Setting media massa.',
    ),
    QuestionItem(
      id: 'kom_023',
      questionText: 'Teori Spiral Keheningan (Spiral of Silence) yang menyatakan orang enggan menyuarakan pendapat minoritas dikemukakan oleh:',
      options: ['Elisabeth Noelle-Neumann', 'McCombs', 'Gerbner', 'Hall'],
      correctOptionIndex: 0,
      explanation: 'Noelle-Neumann menjelaskan ketakutan akan isolasi sosial membungkam suara minoritas.',
    ),
    QuestionItem(
      id: 'kom_024',
      questionText: 'Teori Kultivasi (Cultivation Theory) yang mengemukakan dampak paparan televisi jangka panjang (Mean World Syndrome) dikembangkan oleh:',
      options: ['George Gerbner', 'McLuhan', 'Schramm', 'Lasswell'],
      correctOptionIndex: 0,
      explanation: 'Gerbner membuktikan penonton setia TV mempersepsikan dunia lebih berbahaya daripada kenyataan.',
    ),
    QuestionItem(
      id: 'kom_025',
      questionText: 'Ungkapan terkenal "Medium is the Message" (Media adalah Pesan itu sendiri) dikemukakan oleh pakar komunikasi:',
      options: ['Marshall McLuhan', 'Wilbur Schramm', 'Walter Lippmann', 'Neil Postman'],
      correctOptionIndex: 0,
      explanation: 'McLuhan mengemukakan bahwa saluran media itu sendiri mengubah pola pikir manusia.',
    ),
    QuestionItem(
      id: 'kom_026',
      questionText: 'Konsep McLuhan bahwa teknologi media massa membuat dunia seperti desa global yang saling terhubung dinamakan:',
      options: ['Global Village (Desa Global)', 'Cyber World', 'Information Superhighway', 'Digital Utopia'],
      correctOptionIndex: 0,
      explanation: 'Global Village memprediksi keterhubungan dunia via media elektronik.',
    ),
    QuestionItem(
      id: 'kom_027',
      questionText: 'Teori Kegunaan dan Gratifikasi (Uses and Gratifications Theory) menekankan bahwa audiens media bersifat:',
      options: ['Aktif dan selektif memilih media sesuai kebutuhannya', 'Pasif menerima pesan', 'Tergantung penuh', 'Mudah terhipnosis'],
      correctOptionIndex: 0,
      explanation: 'Katz, Blumler, & Gurevitch menganggap audiens aktif memanfaatkan media.',
    ),
    QuestionItem(
      id: 'kom_028',
      questionText: 'Model Jarum Hipodermik (Magic Bullet Theory) mengasumsikan efek media massa terhadap audiens bersifat:',
      options: ['Langsung, seragam, dan sangat kuat seperti suntikan jarum', 'Lemah', 'Tidak berdampak', 'Bertahap'],
      correctOptionIndex: 0,
      explanation: 'Magic Bullet Theory menganggap audiens pasif tak berdaya menerima pesan media.',
    ),
    QuestionItem(
      id: 'kom_029',
      questionText: 'Model Aliran Dua Tahap (Two-Step Flow Theory) menyatakan bahwa pesan media mengalir terlebih dahulu kepada:',
      options: ['Pemimpin Opini (Opinion Leader)', 'Masyarakat Luas', 'Pemerintah', 'Anak-anak'],
      correctOptionIndex: 0,
      explanation: 'Lazarsfeld & Katz membuktikan pesan media disaring oleh Pemimpin Opini.',
    ),
    QuestionItem(
      id: 'kom_030',
      questionText: 'Proses pemilihan, penekanan, dan pembingkaian realitas berita oleh media dinamakan:',
      options: ['Framing (Pembingkaian Berita)', 'Priming', 'Gatekeeping', 'Sensasionalisme'],
      correctOptionIndex: 0,
      explanation: 'Framing (Entman) membentuk sudut pandang pembaca atas berita.',
    ),
    QuestionItem(
      id: 'kom_031',
      questionText: 'Proses penyaringan berita oleh editor dan jurnalis menentukan berita mana yang layak tayang dinamakan:',
      options: ['Gatekeeping (Penjagaan Gawang Berita)', 'Framing', 'Priming', 'Filtering'],
      correctOptionIndex: 0,
      explanation: 'David Manning White merumuskan fungsi Gatekeeper media.',
    ),
    QuestionItem(
      id: 'kom_032',
      questionText: 'Efek media dalam mengaktifkan kesadaran konsep pemikiran tertentu sebelum mengevaluasi isu dinamakan:',
      options: ['Priming', 'Framing', 'Kultivasi', 'Agenda Setting'],
      correctOptionIndex: 0,
      explanation: 'Priming memicu memori awal yang mempengaruhi penilaian isu berikutnya.',
    ),
    QuestionItem(
      id: 'kom_033',
      questionText: 'Ilmu yang mempelajari tentang tanda, makna, dan sistem lambang dinamakan:',
      options: ['Semiotika (Semiotics)', 'Hermeneutika', 'Linguistik', 'Semantik'],
      correctOptionIndex: 0,
      explanation: 'Semiotika menganalisis struktur tanda dan makna.',
    ),
    QuestionItem(
      id: 'kom_034',
      questionText: 'Bapak Semiotika Modern yang membagi tanda menjadi Penanda (Signifier) dan Petanda (Signified) adalah:',
      options: ['Ferdinand de Saussure', 'Charles Sanders Peirce', 'Roland Barthes', 'Umberto Eco'],
      correctOptionIndex: 0,
      explanation: 'Saussure merumuskan model trikotomi dikotomi Penanda & Petanda.',
    ),
    QuestionItem(
      id: 'kom_035',
      questionText: 'Model Semiotika Peirce membagi triadik tanda ke dalam tiga elemen yaitu:',
      options: ['Representamen (Sign), Object, dan Interpretant', 'Signifier, Signified, Meaning', 'Text, Context, Subtext', 'Icon, Index, Symbol'],
      correctOptionIndex: 0,
      explanation: 'C.S. Peirce merumuskan model triadik tanda (Sign-Object-Interpretant).',
    ),
    QuestionItem(
      id: 'kom_036',
      questionText: 'Tanda yang memiliki hubungan kemiripan fisik langsung dengan objek yang diwakilinya (seperti foto) dinamakan:',
      options: ['Ikon (Icon)', 'Indeks', 'Simbol', 'Isyarat'],
      correctOptionIndex: 0,
      explanation: 'Ikon meniru wujud fisik asli objek.',
    ),
    QuestionItem(
      id: 'kom_037',
      questionText: 'Tanda yang memiliki hubungan sebab-akibat langsung dengan objeknya (seperti asap menandakan api) dinamakan:',
      options: ['Indeks (Index)', 'Ikon', 'Simbol', 'Kode'],
      correctOptionIndex: 0,
      explanation: 'Indeks menunjukkan kaitan kausal eksistensial.',
    ),
    QuestionItem(
      id: 'kom_038',
      questionText: 'Tanda yang maknanya ditentukan oleh kesepakatan konvensi sosial masyarakat (seperti bendera) dinamakan:',
      options: ['Simbol (Symbol)', 'Ikon', 'Indeks', 'Isyarat'],
      correctOptionIndex: 0,
      explanation: 'Simbol bergantung pada konvensi sosial yang dipelajari.',
    ),
    QuestionItem(
      id: 'kom_039',
      questionText: 'Tingkatan makna konotasi dan mitos dalam analisis semiotika dikembangkan oleh teoritikus:',
      options: ['Roland Barthes', 'Saussure', 'Peirce', 'Foucault'],
      correctOptionIndex: 0,
      explanation: 'Roland Barthes mengembangkan semiotika Denotasi, Konotasi, dan Mitos.',
    ),
    QuestionItem(
      id: 'kom_040',
      questionText: 'Makna harfiah kamus dari sebuah kata atau tanda tanpa asosiasi emosional dinamakan makna:',
      options: ['Denotasi', 'Konotasi', 'Mitos', 'Kiasan'],
      correctOptionIndex: 0,
      explanation: 'Denotasi adalah makna objektif eksplisit.',
    ),
    QuestionItem(
      id: 'kom_041',
      questionText: 'Makna kiasan subjektif atau emosional yang menyertai suatu tanda dinamakan makna:',
      options: ['Konotasi', 'Denotasi', 'Literal', 'Struktural'],
      correctOptionIndex: 0,
      explanation: 'Konotasi melibatkan asosiasi nilai budaya emosional.',
    ),
    QuestionItem(
      id: 'kom_042',
      questionText: 'Fungsi Utama Hubungan Masyarakat (Public Relations / PR) adalah membangun:',
      options: ['Saling pengertian, citra positif, dan reputasi organisasi', 'Penjualan langsung', 'Iklan murah', 'Propaganda'],
      correctOptionIndex: 0,
      explanation: 'PR mengelola komunikasi strategis menciptakan hubungan saling menguntungkan (mutual understanding).',
    ),
    QuestionItem(
      id: 'kom_043',
      questionText: 'Bapak Public Relations Modern yang merintis konsultasi PR pertama adalah:',
      options: ['Ivy Lee dan Edward Bernays', 'Philip Kotler', 'David Ogilvy', 'Lasswell'],
      correctOptionIndex: 0,
      explanation: 'Ivy Lee & Edward Bernays adalah pelopor profesi Public Relations.',
    ),
    QuestionItem(
      id: 'kom_044',
      questionText: 'Empat Model Komunikasi PR menurut Grunig dan Hunt yang paling ideal dan etis adalah model:',
      options: ['Two-Way Symmetrical (Dua Arah Simetris)', 'Press Agentry', 'Public Information', 'Two-Way Asymmetrical'],
      correctOptionIndex: 0,
      explanation: 'Model Simetris Dua Arah berfokus pada dialog seimbang pemecahan masalah.',
    ),
    QuestionItem(
      id: 'kom_045',
      questionText: 'Dokumen tertulis resmi yang dikirim praktisi PR kepada jurnalis pers memuat berita acara dinamakan:',
      options: ['Press Release (Siaran Pers)', 'Press Conference', 'Press Kit', 'Media Advisory'],
      correctOptionIndex: 0,
      explanation: 'Press Release memuat rilis berita organisasi bagi media.',
    ),
    QuestionItem(
      id: 'kom_046',
      questionText: 'Acara tatap muka praktisi PR di hadapan para wartawan untuk memberikan pernyataan resmi dinamakan:',
      options: ['Press Conference (Konferensi Pers)', 'Press Tour', 'Media Gathering', 'Interview'],
      correctOptionIndex: 0,
      explanation: 'Konferensi Pers mengumpulkan jurnalis untuk pengumuman penting.',
    ),
    QuestionItem(
      id: 'kom_047',
      questionText: 'Manajemen komunikasi yang dirancang khusus saat organisasi mengalami ancaman krisis reputasi dinamakan:',
      options: ['Crisis PR / Crisis Communication', 'Marketing PR', 'Internal PR', 'CSR'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Krisis bertindak cepat menangani respon darurat reputasi.',
    ),
    QuestionItem(
      id: 'kom_048',
      questionText: 'Tanggung jawab sosial perusahaan terhadap lingkungan dan masyarakat sekitar dikenal dengan istilah:',
      options: ['CSR (Corporate Social Responsibility)', 'PR', 'Sponsorship', 'Branding'],
      correctOptionIndex: 0,
      explanation: 'CSR adalah kontribusi keberlanjutan ekonomi-sosial-lingkungan perusahaan.',
    ),
    QuestionItem(
      id: 'kom_049',
      questionText: 'Penyampaian informasi persuasif secara masif berprasangka untuk memengaruhi ideologi massa dinamakan:',
      options: ['Propaganda', 'Public Relations', 'Jurnalistik', 'Edukasi'],
      correctOptionIndex: 0,
      explanation: 'Propaganda memanfaatkan manipulasi emosional memengaruhi pandangan publik.',
    ),
    QuestionItem(
      id: 'kom_050',
      questionText: 'Prinsip utama jurnalistik untuk mengonfirmasi kebenaran berita dari kedua belah pihak secara seimbang dinamakan:',
      options: ['Cover Both Sides (Cover Both Story)', 'Sensasionalisme', 'Clickbait', 'Check and Recheck'],
      correctOptionIndex: 0,
      explanation: 'Cover Both Sides mewajibkan keberimbangan konfirmasi narasumber.',
    ),
    QuestionItem(
      id: 'kom_051',
      questionText: 'Struktur penulisan berita piramida terbalik (Inverted Pyramid) menempatkan informasi paling penting pada bagian:',
      options: ['Teratas / Teras Berita (Lead)', 'Tengah', 'Paling Bawah', 'Lampiran'],
      correctOptionIndex: 0,
      explanation: 'Piramida Terbalik menempatkan fakta 5W+1H paling krusial di paragraf awal (Lead).',
    ),
    QuestionItem(
      id: 'kom_052',
      questionText: 'Rumus dasar kelengkapan fakta unsur berita berita mencakup:',
      options: ['5W + 1H (What, Who, Where, When, Why, How)', '3W + 2H', '4W + 1H', '6W'],
      correctOptionIndex: 0,
      explanation: '5W+1H adalah standar kelengkapan berita jurnalistik.',
    ),
    QuestionItem(
      id: 'kom_053',
      questionText: 'Jurnalisme mendalam yang membongkar kejahatan terselubung atau penyimpangan publik dinamakan jurnalisme:',
      options: ['Investigasi (Investigative Journalism)', 'Presisi', 'Kuning', 'Sastrawan'],
      correctOptionIndex: 0,
      explanation: 'Jurnalistik Investigasi membutuhkan riset mendalam dan verifikasi kerahasiaan.',
    ),
    QuestionItem(
      id: 'kom_054',
      questionText: 'Praktik jurnalistik yang mengutamakan judul sensasional berlebihan dan berita mengejutkan dinamakan jurnalisme:',
      options: ['Kuning (Yellow Journalism)', 'Presisi', 'Damai', 'Advokasi'],
      correctOptionIndex: 0,
      explanation: 'Yellow Journalism memicu sensasionalisme demi oplah/klik.',
    ),
    QuestionItem(
      id: 'kom_055',
      questionText: 'Hak narasumber untuk meminta jurnalis merahasiakan namanya dalam berita dinamakan:',
      options: ['Off the Record', 'Embargo', 'Hak Tolak', 'Hak Jawab'],
      correctOptionIndex: 0,
      explanation: 'Off the Record mengikat jurnalis tidak menyiarkan informasi/identitas narasumber.',
    ),
    QuestionItem(
      id: 'kom_056',
      questionText: 'Hak seseorang untuk memberikan tanggapan kekeliruan pemberitaan yang merugikan nama baiknya dinamakan:',
      options: ['Hak Jawab', 'Hak Koreksi', 'Hak Tolak', 'Hak Cipta'],
      correctOptionIndex: 0,
      explanation: 'Hak Jawab dijamin UU Pers untuk memulihkan kekeliruan berita.',
    ),
    QuestionItem(
      id: 'kom_057',
      questionText: 'Undang-Undang Pers di Indonesia yang menjamin kebebasan pers tanpa pembredelan adalah UU No. 40 Tahun:',
      options: ['1999', '1945', '2008', '2002'],
      correctOptionIndex: 0,
      explanation: 'UU No. 40 Tahun 1999 menjamin kebebasan pers Indonesia pasca reformasi.',
    ),
    QuestionItem(
      id: 'kom_058',
      questionText: 'Lembaga independen yang mengawasi penegakan Kode Etik Jurnalistik di Indonesia adalah:',
      options: ['Dewan Pers', 'KPI', 'KPU', 'Kominfo'],
      correctOptionIndex: 0,
      explanation: 'Dewan Pers mengawasi kepatuhan pers terhadap kode etik jurnalistik.',
    ),
    QuestionItem(
      id: 'kom_059',
      questionText: 'Lembaga independen yang mengawasi penyiaran radio dan televisi di Indonesia adalah:',
      options: ['KPI (Komisi Penyiaran Indonesia)', 'Dewan Pers', 'LPI', 'ATSI'],
      correctOptionIndex: 0,
      explanation: 'KPI mengawasi P3SPS konten siaran TV dan radio.',
    ),
    QuestionItem(
      id: 'kom_060',
      questionText: 'Integrasi berbagai saluran komunikasi pemasaran (Iklan, PR, Promosi, Sales) secara selaras dinamakan:',
      options: ['IMC (Integrated Marketing Communication)', 'Direct Marketing', 'Branding', 'ATL/BTL'],
      correctOptionIndex: 0,
      explanation: 'IMC menyatukan seluruh pesan pemasaran agar konsisten.',
    ),
    QuestionItem(
      id: 'kom_061',
      questionText: 'Strategi periklanan media massa berjangkauan luas seperti TV, Radio, dan Baliho dinamakan kegiatan:',
      options: ['Above The Line (ATL)', 'Below The Line (BTL)', 'Through The Line (TTL)', 'Personal Selling'],
      correctOptionIndex: 0,
      explanation: 'ATL berfokus pada jangkauan media massa luas.',
    ),
    QuestionItem(
      id: 'kom_062',
      questionText: 'Kegiatan promosi pemasaran langsung seperti pembagian sampel, event pameran, dan spanduk dinamakan:',
      options: ['Below The Line (BTL)', 'Above The Line (ATL)', 'Mass Media', 'Sponsorship'],
      correctOptionIndex: 0,
      explanation: 'BTL menargetkan audiens terbatas lewat kontak langsung.',
    ),
    QuestionItem(
      id: 'kom_063',
      questionText: 'Gaya komunikasi antarpribadi yang tegas menyatakan hak pribadi tanpa melanggar hak orang lain dinamakan komunikasi:',
      options: ['Asertif (Assertive)', 'Agresif', 'Pasif', 'Pasif-Agresif'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Asertif adalah gaya paling sehat dan menghargai kedua belah pihak.',
    ),
    QuestionItem(
      id: 'kom_064',
      questionText: 'Gaya komunikasi menekan dan memaksakan kehendak dengan menyerang pribadi orang lain dinamakan gaya:',
      options: ['Agresif', 'Asertif', 'Pasif', 'Submisif'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Agresif mendominasi orang lain secara sepihak.',
    ),
    QuestionItem(
      id: 'kom_065',
      questionText: 'Gaya komunikasi mengalah dan memendam perasaan sendiri karena takut konflik dinamakan gaya:',
      options: ['Pasif / Submisif', 'Asertif', 'Agresif', 'Dominan'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi Pasif menekan kebutuhan diri demi menghindari perselisihan.',
    ),
    QuestionItem(
      id: 'kom_066',
      questionText: 'Kecenderungan menilai budaya kelompok lain berdasarkan standar dan nilai budayanya sendiri dinamakan:',
      options: ['Etnosentrisme', 'Relativisme Budaya', 'Akulturasi', 'Asimilasi'],
      correctOptionIndex: 0,
      explanation: 'Etnosentrisme menganggap budayanya sendiri superior dibanding budaya lain.',
    ),
    QuestionItem(
      id: 'kom_067',
      questionText: 'Perasaan cemas dan bingung ketika seseorang memasuki lingkungan budaya asing yang sangat berbeda dinamakan:',
      options: ['Culture Shock (Gegar Budaya)', 'Culture Lag', 'Acculturation', 'Enculturation'],
      correctOptionIndex: 0,
      explanation: 'Culture Shock dipicu disorientasi norma budaya baru.',
    ),
    QuestionItem(
      id: 'kom_068',
      questionText: 'Proses perpaduan dua budaya menghasilkan budaya baru tanpa menghilangkan kepribadian budaya asli dinamakan:',
      options: ['Akulturasi (Acculturation)', 'Asimilasi', 'Enkulturasi', 'Difusi'],
      correctOptionIndex: 0,
      explanation: 'Akulturasi menyerap budaya baru tanpa melenyapkan budaya asal.',
    ),
    QuestionItem(
      id: 'kom_069',
      questionText: 'Proses peleburan dua budaya yang menghasilkan budaya baru sama sekali sehingga budaya asli memudar dinamakan:',
      options: ['Asimilasi (Assimilation)', 'Akulturasi', 'Etnosentrisme', 'Amalgamasi'],
      correctOptionIndex: 0,
      explanation: 'Asimilasi meleburkan ciri budaya asal.',
    ),
    QuestionItem(
      id: 'kom_070',
      questionText: 'Proses pewarisan dan pembelajaran budaya sendiri sejak kecil dalam masyarakat dinamakan:',
      options: ['Enkulturasi (Enculturation)', 'Akulturasi', 'Sosialisasi', 'Sosio-Kultural'],
      correctOptionIndex: 0,
      explanation: 'Enkulturasi mengajari anak nilai-nilai budaya lokal keturunannya.',
    ),
    QuestionItem(
      id: 'kom_071',
      questionText: 'Studi komunikasi budaya yang membedakan budaya High-Context (Pesan Implisit) dan Low-Context (Pesan Eksplisit) dipelopori oleh:',
      options: ['Edward T. Hall', 'Geert Hofstede', 'Fons Trompenaars', 'Clifford Geertz'],
      correctOptionIndex: 0,
      explanation: 'Edward T. Hall membedakan budaya konteks tinggi dan rendah.',
    ),
    QuestionItem(
      id: 'kom_072',
      questionText: 'Budaya di mana pesan disampaikan secara tidak langsung, kiasan, dan sangat bergantung pada konteks (seperti budaya Jawa/Jepang) dinamakan:',
      options: ['High-Context Culture (Budaya Konteks Tinggi)', 'Low-Context Culture', 'Direct Culture', 'Individualis'],
      correctOptionIndex: 0,
      explanation: 'High-Context Culture mengandalkan isyarat non-verbal dan etika terselubung.',
    ),
    QuestionItem(
      id: 'kom_073',
      questionText: 'Budaya yang menyampaikan pesan secara langsung, lugas, eksplisit, dan tertulis (seperti budaya AS/Jerman) dinamakan:',
      options: ['Low-Context Culture (Budaya Konteks Rendah)', 'High-Context Culture', 'Implicit Culture', 'Kolektivis'],
      correctOptionIndex: 0,
      explanation: 'Low-Context Culture mengutamakan kejelasan kata-kata verbal eksplisit.',
    ),
    QuestionItem(
      id: 'kom_074',
      questionText: 'Dimensi Budaya Hofstede yang mengukur sejauh mana anggota masyarakat menerima ketimpangan kekuasaan dinamakan:',
      options: ['Power Distance (Jarak Kekuasaan)', 'Individualism', 'Uncertainty Avoidance', 'Masculinity'],
      correctOptionIndex: 0,
      explanation: 'Power Distance mengukur toleransi hirarki kekuasaan.',
    ),
    QuestionItem(
      id: 'kom_075',
      questionText: 'Dimensi Hofstede yang mengukur preferensi kerja mandiri individual dibanding ikatan kelompok kolektif dinamakan:',
      options: ['Individualism vs Collectivism', 'Power Distance', 'Long-term Orientation', 'Indulgence'],
      correctOptionIndex: 0,
      explanation: 'Individualisme memprioritaskan hak individu di atas kelompok.',
    ),
    QuestionItem(
      id: 'kom_076',
      questionText: 'Teori Konstruksi Sosial atas Realitas (Social Construction of Reality) yang mengemukakan realitas diciptakan lewat interaksi bahasa dikembangkan oleh:',
      options: ['Peter L. Berger dan Thomas Luckmann', 'Mead', 'Blumer', 'Goffman'],
      correctOptionIndex: 0,
      explanation: 'Berger & Luckmann merumuskan eksternalisasi, obyektivasi, dan internalisasi.',
    ),
    QuestionItem(
      id: 'kom_077',
      questionText: 'Pendekatan Dramaturgi yang mengibaratkan interaksi sosial seperti pertunjukan teater (Front Stage dan Back Stage) dikembangkan oleh:',
      options: ['Erving Goffman', 'George Herbert Mead', 'Herbert Blumer', 'Harold Garfinkel'],
      correctOptionIndex: 0,
      explanation: 'Erving Goffman mengemukakan pengelolaan kesan (Impression Management) panggung depan dan panggung belakang.',
    ),
    QuestionItem(
      id: 'kom_078',
      questionText: 'Panggung depan (Front Stage) dalam teori Dramaturgi Goffman merupakan tempat di mana individu:',
      options: ['Menampilkan performa terbaik di hadapan penonton audiens', 'Bersantai santai', 'Menjadi diri sendiri', 'Beristirahat tanpa riasan'],
      correctOptionIndex: 0,
      explanation: 'Front Stage adalah area penampilan publik teratur.',
    ),
    QuestionItem(
      id: 'kom_079',
      questionText: 'Panggung belakang (Back Stage) Goffman merupakan tempat di mana individu:',
      options: ['Lepas dari peran publik dan dapat menjadi diri sendiri', 'Tampil di pers', 'Berpidato', 'Mengajar'],
      correctOptionIndex: 0,
      explanation: 'Back Stage tempat rahasia melepas topeng peran.',
    ),
    QuestionItem(
      id: 'kom_078_kom',
      questionText: 'Teori Interaksionisme Simbolik yang menekankan pemaknaan melalui simbol kata "Mind, Self, and Society" dipelopori oleh:',
      options: ['George Herbert Mead dan Herbert Blumer', 'Goffman', 'Cooley', 'Baudrillard'],
      correctOptionIndex: 0,
      explanation: 'Mead & Blumer mendasarkan makna simbolik lahir dari interaksi sosial.',
    ),
    QuestionItem(
      id: 'kom_081',
      questionText: 'Konsep "Looking-Glass Self" (Cermin Diri) di mana gambaran diri terbentuk dari persepsi pandangan orang lain dikemukakan oleh:',
      options: ['Charles Horton Cooley', 'George Herbert Mead', 'Erving Goffman', 'Freud'],
      correctOptionIndex: 0,
      explanation: 'Cooley mengemukakan individu membayangkan bagaimana dirinya terlihat di mata orang lain.',
    ),
    QuestionItem(
      id: 'kom_082',
      questionText: 'Fenomena konvergensi saluran media massa konvensional dan media digital ke dalam platform tunggal internet dinamakan:',
      options: ['Konvergensi Media (Media Convergence)', 'Divergensi Media', 'Digitalisasi', 'Sinergi Media'],
      correctOptionIndex: 0,
      explanation: 'Henry Jenkins menjelaskan konvergensi media menggabungkan platform berita.',
    ),
    QuestionItem(
      id: 'kom_083',
      questionText: 'Audiens yang tidak hanya mengonsumsi konten tetapi juga aktif memproduksi konten dinamakan:',
      options: ['Prosumer (Producer + Consumer)', 'Audience', 'User', 'Follower'],
      correctOptionIndex: 0,
      explanation: 'Prosumer (Alvin Toffler) merangkum peran produsen sekaligus konsumen.',
    ),
    QuestionItem(
      id: 'kom_084',
      questionText: 'Ruang publik tempat warga berdiskusi bebas masalah politik tanpa intimidasi menurut Jurgen Habermas dinamakan:',
      options: ['Public Sphere (Ruang Publik)', 'Civic Space', 'Agora', 'Forum'],
      correctOptionIndex: 0,
      explanation: 'Habermas merumuskan Public Sphere sebagai pilar demokrasi deliberatif.',
    ),
    QuestionItem(
      id: 'kom_085',
      questionText: 'Penyebaran informasi palsu atau hoaks dengan sengaja untuk menyesatkan publik dinamakan:',
      options: ['Disinformasi', 'Misinformasi', 'Malinformasi', 'Propaganda'],
      correctOptionIndex: 0,
      explanation: 'Disinformasi diproduksi sengaja dengan niat jahat menyesatkan.',
    ),
    QuestionItem(
      id: 'kom_086',
      questionText: 'Penyebaran informasi salah atau tidak akurat tanpa ada niat jahat untuk menyesatkan dinamakan:',
      options: ['Misinformasi', 'Disinformasi', 'Malinformasi', 'Hoaks'],
      correctOptionIndex: 0,
      explanation: 'Misinformasi adalah kekeliruan tak disengaja karena ketidaktahuan.',
    ),
    QuestionItem(
      id: 'kom_087',
      questionText: 'Penyebaran informasi riil yang akurat namun digunakan untuk merugikan atau menyerang seseorang dinamakan:',
      options: ['Malinformasi', 'Disinformasi', 'Misinformasi', 'Doxxing'],
      correctOptionIndex: 0,
      explanation: 'Malinformasi membocorkan privasi riil dengan niat merusak reputasi.',
    ),
    QuestionItem(
      id: 'kom_088',
      questionText: 'Tindakan menyebarkan informasi dokumen identitas pribadi seseorang di internet tanpa izin dinamakan:',
      options: ['Doxxing', 'Phishing', 'Spamming', 'Cyberbullying'],
      correctOptionIndex: 0,
      explanation: 'Doxxing mempublikasikan data pribadi korbannya.',
    ),
    QuestionItem(
      id: 'kom_089',
      questionText: 'Ruang gema di media sosial di mana pengguna hanya terpapar opini yang sejalan dengan pandangannya dinamakan:',
      options: ['Echo Chamber (Ruang Gema)', 'Filter Bubble', 'Algorithm', 'Social Bias'],
      correctOptionIndex: 0,
      explanation: 'Echo Chamber mengisolasi pemikiran dari sudut pandang berbeda.',
    ),
    QuestionItem(
      id: 'kom_090',
      questionText: 'Algoritma mesin pencari/media sosial yang membatasi informasi sesuai riwayat pencarian pengguna dinamakan:',
      options: ['Filter Bubble (Gelembung Filter)', 'Echo Chamber', 'Cyber Bubble', 'Data Mining'],
      correctOptionIndex: 0,
      explanation: 'Eli Pariser merumuskan Filter Bubble akibat personalisasi algoritma.',
    ),
    QuestionItem(
      id: 'kom_091',
      questionText: 'Kemampuan mengakses, menganalisis, mengevaluasi, dan mengomunikasikan pesan dalam berbagai bentuk media dinamakan:',
      options: ['Literasi Media (Media Literacy)', 'Literasi Digital', 'Literasi Informasi', 'Edukasi Media'],
      correctOptionIndex: 0,
      explanation: 'Literasi Media membekali daya kritis menyikapi konten media.',
    ),
    QuestionItem(
      id: 'kom_092',
      questionText: 'Analisis teks media untuk membongkar ideologi tersembunyi dan relasi kuasa di balik bahasa dinamakan:',
      options: ['AWK (Analisis Wacana Kritis / CDA)', 'Analisis Isi', 'Semiotika', 'Framing'],
      correctOptionIndex: 0,
      explanation: 'Analisis Wacana Kritis (Fairclough / van Dijk) membongkar dominasi kekuasaan dalam teks.',
    ),
    QuestionItem(
      id: 'kom_093',
      questionText: 'Metode penelitian kuantitatif untuk menghitung frekuensi kemunculan kata/kategori dalam media dinamakan:',
      options: ['Analisis Isi (Content Analysis)', 'Analisis Wacana', 'Etnografi', 'Semiotika'],
      correctOptionIndex: 0,
      explanation: 'Content Analysis mengukur secara kuantitatif manifestsasi isi teks.',
    ),
    QuestionItem(
      id: 'kom_094',
      questionText: 'Metode kualitatif studi lapangan mengamati perilaku budaya kelompok dalam konteks alaminya dinamakan:',
      options: ['Etnografi (Ethnography)', 'Survei', 'Eksperimen', 'Analisis Isu'],
      correctOptionIndex: 0,
      explanation: 'Etnografi melibatkan observasi partisipatif intensif di lapangan.',
    ),
    QuestionItem(
      id: 'kom_095',
      questionText: 'Riset etnografi yang dilakukan khusus di lingkungan komunitas virtual maya internet dinamakan:',
      options: ['Netnografi (Netnography)', 'Cyber-Etnografi', 'Digital Etnografi', 'Web Analysis'],
      correctOptionIndex: 0,
      explanation: 'Robert Kozinets merintis Netnography untuk mengamati budaya online.',
    ),
    QuestionItem(
      id: 'kom_096',
      questionText: 'Etika berkomunikasi dan berinteraksi secara sopan di dunia maya internet dikenal dengan istilah:',
      options: ['Neticette (Netiket / Net Etiquette)', 'Cyber Law', 'Digital Ethics', 'Social Norm'],
      correctOptionIndex: 0,
      explanation: 'Netiket mengatur kesopanan adab berinteraksi di ruang virtual.',
    ),
    QuestionItem(
      id: 'kom_097',
      questionText: 'Fenomena penggunaan istilah hiperbola berlebihan dalam judul konten untuk menarik klik dinamakan:',
      options: ['Clickbait (Umpan Klik)', 'Hoaks', 'Spam', 'Viral'],
      correctOptionIndex: 0,
      explanation: 'Clickbait memicu rasa penasaran berlebihan memancing lalu lintas tayangan.',
    ),
    QuestionItem(
      id: 'kom_098',
      questionText: 'Penyebaran pesan yang sangat cepat di internet dari mulut ke mulut antarpengguna dinamakan:',
      options: ['Viral Marketing / Pemasaran Viral', 'Word of Mouth', 'Buzz Marketing', 'Direct Sales'],
      correctOptionIndex: 0,
      explanation: 'Pemasaran Viral memanfaatkan prinsip eksponensial pembagian pesan media sosial.',
    ),
    QuestionItem(
      id: 'kom_099',
      questionText: 'Mitos atau realitas buatan simulasi yang tampak lebih nyata dibanding kenyataan asli menurut Jean Baudrillard dinamakan:',
      options: ['Hiperrealitas (Hyperreality)', 'Simulakra', 'Virtual Reality', 'Disonansi'],
      correctOptionIndex: 0,
      explanation: 'Baudrillard merumuskan Hiperrealitas di mana simbol simulasi menggantikan realitas asli.',
    ),
    QuestionItem(
      id: 'kom_100',
      questionText: 'Undang-Undang Informasi dan Transaksi Elektronik di Indonesia yang mengatur kejahatan siber adalah UU ITE Nomor:',
      options: ['UU No. 11 Tahun 2008 (jo UU No. 19 Tahun 2016)', 'UU No. 32 Tahun 2002', 'UU No. 40 Tahun 1999', 'UU No. 14 Tahun 2008'],
      correctOptionIndex: 0,
      explanation: 'UU ITE mengontrol kepatuhan hukum transaksi digital dan konten ruang siber di Indonesia.',
    ),
  ];
}
