import '../tes_seleksi_model.dart';

List<QuestionItem> getHukumQuestions() {
  return const [
    QuestionItem(
      id: 'hkm_001',
      questionText: 'Asas fundamental Hukum Pidana yang menyatakan "tidak ada pidana tanpa aturan hukum yang mendahuluinya" dinamakan:',
      options: ['Nullum delictum nulla poena sine praevia lege poenali', 'Lex Specialis Derogat Legi Generali', 'Pacta Sunt Servanda', 'Presumption of Innocence'],
      correctOptionIndex: 0,
      explanation: 'Asas Legalitas tercantum dalam Pasal 1 ayat (1) KUHP.',
    ),
    QuestionItem(
      id: 'hkm_002',
      questionText: 'Asas hukum yang menyatakan bahwa undang-undang yang khusus menyampingkan undang-undang yang bersifat umum dinamakan:',
      options: ['Lex Specialis Derogat Legi Generali', 'Lex Superior Derogat Legi Inferiori', 'Lex Posterior Derogat Legi Priori', 'Equality Before the Law'],
      correctOptionIndex: 0,
      explanation: 'Lex Specialis memprioritaskan aturan hukum khusus.',
    ),
    QuestionItem(
      id: 'hkm_003',
      questionText: 'Asas hukum yang menyatakan bahwa undang-undang yang baru menyampingkan undang-undang yang lama dinamakan:',
      options: ['Lex Posterior Derogat Legi Priori', 'Lex Specialis Derogat Legi Generali', 'Lex Superior Derogat Legi Inferiori', 'Asas Restoratif'],
      correctOptionIndex: 0,
      explanation: 'Lex Posterior berlaku jika terjadi pertentangan aturan pada hierarki yang sederajat.',
    ),
    QuestionItem(
      id: 'hkm_004',
      questionText: 'Asas hukum yang menyatakan bahwa undang-undang yang lebih tinggi derajatnya menyampingkan yang lebih rendah dinamakan:',
      options: ['Lex Superior Derogat Legi Inferiori', 'Lex Specialis Derogat Legi Generali', 'Lex Posterior Derogat Legi Priori', 'Asas Legalitas'],
      correctOptionIndex: 0,
      explanation: 'Lex Superior mengacu pada hierarki perundang-undangan.',
    ),
    QuestionItem(
      id: 'hkm_005',
      questionText: 'Asas yang menyatakan bahwa setiap orang yang mengikatkan diri dalam perjanjian wajib menepati kesepakatannya dinamakan:',
      options: ['Pacta Sunt Servanda', 'Consensualisme', 'Abuse of Rights', 'Good Faith'],
      correctOptionIndex: 0,
      explanation: 'Pacta Sunt Servanda menegaskan perjanjian mengikat sebagai undang-undang bagi para pihak (Pasal 1338 KUHPerdata).',
    ),
    QuestionItem(
      id: 'hkm_006',
      questionText: 'Asas di mana seseorang dianggap tidak bersalah sebelum ada putusan pengadilan yang berkekuatan hukum tetap dinamakan:',
      options: ['Presumption of Innocence (Praduga Tak Bersalah)', 'In Dubio Pro Reo', 'Ne Bis In Idem', 'Equality Before the Law'],
      correctOptionIndex: 0,
      explanation: 'Praduga Tak Bersalah menjamin hak-hak tersangka/terdakwa.',
    ),
    QuestionItem(
      id: 'hkm_007',
      questionText: 'Asas hukum pidana yang menyatakan jika ada keraguan, hakim harus menjatuhkan keputusan yang menguntungkan terdakwa dinamakan:',
      options: ['In Dubio Pro Reo', 'Ne Bis In Idem', 'Ultra Vires', 'Error in Persona'],
      correctOptionIndex: 0,
      explanation: 'In Dubio Pro Reo meminimalisir kesalahan vonis atas keraguan pembuktian.',
    ),
    QuestionItem(
      id: 'hkm_008',
      questionText: 'Asas yang melarang seseorang diadili atau dihukum untuk kedua kalinya atas perbuatan yang sama dinamakan:',
      options: ['Ne Bis In Idem', 'In Dubio Pro Reo', 'Nemo Judex In Causa Sua', 'Audi Alteram Partem'],
      correctOptionIndex: 0,
      explanation: 'Ne Bis In Idem diatur dalam Pasal 76 KUHP.',
    ),
    QuestionItem(
      id: 'hkm_009',
      questionText: 'Tiga unsur perbuatan pidana yang wajib dipenuhi untuk dapat dijatuhi sanksi pidana adalah:',
      options: ['Perbuatan Melawan Hukum, Kemampuan Bertanggung Jawab, dan Kesalahan (Mens Rea)', 'Motif, Uang, Saksi', 'Niat, Rencana, Senjata', 'Tuduhan, Laporan, BAP'],
      correctOptionIndex: 0,
      explanation: 'Unsur pidana melingkupi perbuatan lahiriah (Actus Reus) dan niat batiniah (Mens Rea).',
    ),
    QuestionItem(
      id: 'hkm_010',
      questionText: 'Istilah latin yang menggambarkan perbuatan fisik kejahatan secara lahiriah dinamakan:',
      options: ['Actus Reus', 'Mens Rea', 'Dolus', 'Culpa'],
      correctOptionIndex: 0,
      explanation: 'Actus Reus adalah wujud perbuatan fisik jahat.',
    ),
    QuestionItem(
      id: 'hkm_011',
      questionText: 'Istilah latin yang menggambarkan niat batin jahat atau sikap batin pelaku dinamakan:',
      options: ['Mens Rea', 'Actus Reus', 'Locus Delicti', 'Tempus Delicti'],
      correctOptionIndex: 0,
      explanation: 'Mens Rea menunjukkan unsur kesengajaan atau kelalaian sikap batin.',
    ),
    QuestionItem(
      id: 'hkm_012',
      questionText: 'Bentuk kesengajaan pidana di mana pelaku memang menghendaki akibat tindakannya dinamakan kesengajaan:',
      options: ['Dolus Directus (Kesengajaan sebagai Maksud)', 'Dolus Eventualis', 'Culpa Lata', 'Culpa Levis'],
      correctOptionIndex: 0,
      explanation: 'Dolus Directus adalah kesengajaan murni sebagai tujuan utama pelaku.',
    ),
    QuestionItem(
      id: 'hkm_013',
      questionText: 'Kesengajaan di mana pelaku menyadari kemungkinan timbulnya akibat dilarang dan tetap membayangkannya dinamakan:',
      options: ['Dolus Eventualis (Kesengajaan dengan Kesadaran Kemungkinan)', 'Dolus Directus', 'Culpa', 'Noodweer'],
      correctOptionIndex: 0,
      explanation: 'Dolus Eventualis menerima risiko kemungkinan akibat perbuatan.',
    ),
    QuestionItem(
      id: 'hkm_014',
      questionText: 'Bentuk kelalaian atau kealpaan berat dalam hukum pidana dinamakan:',
      options: ['Culpa Lata', 'Culpa Levis', 'Dolus Eventualis', 'Noodweer Exces'],
      correctOptionIndex: 0,
      explanation: 'Culpa Lata adalah kealpaan sangat kasar/berat.',
    ),
    QuestionItem(
      id: 'hkm_015',
      questionText: 'Alasan penghapus pidana berupa pembelaan darurat untuk diri sendiri atau orang lain dari ancaman serangan dinamakan:',
      options: ['Noodweer (Pembelaan Darurat - Pasal 49 ayat 1 KUHP)', 'Noodweer Exces', 'Overmacht', 'Dwangsom'],
      correctOptionIndex: 0,
      explanation: 'Noodweer menghapuskan sifat melawan hukum dari perbuatan pembelaan.',
    ),
    QuestionItem(
      id: 'hkm_016',
      questionText: 'Pembelaan darurat melampaui batas yang dipicu oleh keguncangan jiwa hebat dinamakan:',
      options: ['Noodweer Exces (Pasal 49 ayat 2 KUHP)', 'Overmacht', 'Noodweer', 'Ambtelijk Bevel'],
      correctOptionIndex: 0,
      explanation: 'Noodweer Exces menghapuskan kesalahan pelaku karena shock jiwa.',
    ),
    QuestionItem(
      id: 'hkm_017',
      questionText: 'Kondisi keadaan memaksa di mana seseorang terdorong melakukan pidana akibat daya paksa dinamakan:',
      options: ['Overmacht (Pasal 48 KUHP)', 'Noodweer', 'Dolus', 'Revisi'],
      correctOptionIndex: 0,
      explanation: 'Overmacht merupakan alasan pemaaf penghapus pidana.',
    ),
    QuestionItem(
      id: 'hkm_018',
      questionText: 'Empat syarat sahnya perjanjian perdata menurut Pasal 1320 KUHPerdata adalah:',
      options: ['Kesepakatan, Kecakapan, Hal Tertentu, dan Causa yang Halal', 'Saksi, Materai, Notaris, Uang DP', 'Tanda Tangan, Pasfoto, KTP, Alamat', 'Tertulis, Pengadilan, Pajak, Izin'],
      correctOptionIndex: 0,
      explanation: 'Pasal 1320 membagi syarat subjektif (sepakat, cakap) dan syarat objektif (hal tertentu, causa halal).',
    ),
    QuestionItem(
      id: 'hkm_019',
      questionText: 'Apabila syarat subjektif perjanjian (kesepakatan atau kecakapan) tidak terpenuhi, akibat hukumnya adalah perjanjian:',
      options: ['Dapat Dibatalkan (Voidable)', 'Batal Demi Hukum (Null and Void)', 'Tetap Sah', 'Mengikat Sebagian'],
      correctOptionIndex: 0,
      explanation: 'Syarat subjektif yang melanggar menyebabkan perjanjian Dapat Dibatalkan atas permintaan pihak.',
    ),
    QuestionItem(
      id: 'hkm_020',
      questionText: 'Apabila syarat objektif perjanjian (hal tertentu atau causa yang halal) tidak terpenuhi, akibat hukumnya adalah perjanjian:',
      options: ['Batal Demi Hukum (Null and Void)', 'Dapat Dibatalkan', 'Sah Sebagian', 'Menjadi Pidana'],
      correctOptionIndex: 0,
      explanation: 'Syarat objektif yang tidak terpenuhi membuat perjanjian batal sejak awal demi hukum.',
    ),
    QuestionItem(
      id: 'hkm_021',
      questionText: 'Kondisi tidak dipenuhinya kewajiban atau ingkar janji dalam debitur perdata dinamakan:',
      options: ['Wanprestasi', 'Perbuatan Melawan Hukum (PMH)', 'Overmacht', 'Default Risk'],
      correctOptionIndex: 0,
      explanation: 'Wanprestasi terjadi jika kelalaian melanggar isi pasal klausa kontrak.',
    ),
    QuestionItem(
      id: 'hkm_022',
      questionText: 'Gugatan perdata atas perbuatan yang melanggar hukum dan menimbulkan kerugian bagi pihak lain diatur dalam KUHPerdata Pasal:',
      options: ['Pasal 1365 KUHPerdata (PMH / Onrechtmatige Daad)', 'Pasal 1320', 'Pasal 1338', 'Pasal 1131'],
      correctOptionIndex: 0,
      explanation: 'Pasal 1365 KUHPerdata mengatur tuntutan ganti rugi Perbuatan Melawan Hukum.',
    ),
    QuestionItem(
      id: 'hkm_023',
      questionText: 'Ganti rugi dalam wanprestasi mencakup tiga komponen utama yaitu:',
      options: ['Biaya, Rugi, dan Bunga (Cost, Loss, and Interest)', 'Denda, Penjara, Pajak', 'Sita Jaminan, Eksekusi, Kurator', 'Pokok, Pokok Tambahan, Fee'],
      correctOptionIndex: 0,
      explanation: 'Kompensasi wanprestasi mengganti biaya operasional, kerugian nyata, dan bunga kehilangan keuntungan.',
    ),
    QuestionItem(
      id: 'hkm_024',
      questionText: 'Hierarki Peraturan Perundang-undangan tertinggi di Republik Indonesia menurut UU No. 12 Tahun 2011 adalah:',
      options: ['UUD NRI Tahun 1945', 'Ketetapan MPR', 'Undang-Undang / Perppu', 'Peraturan Presiden'],
      correctOptionIndex: 0,
      explanation: 'UUD 1945 merupakan hukum dasar tertinggi di Indonesia.',
    ),
    QuestionItem(
      id: 'hkm_025',
      questionText: 'Lembaga tinggi negara yang berwenang menguji Undang-Undang terhadap UUD 1945 (Judicial Review UU) adalah:',
      options: ['Mahkamah Konstitusi (MK)', 'Mahkamah Agung (MA)', 'Komisi Yudisial (KY)', 'DPR'],
      correctOptionIndex: 0,
      explanation: 'MK berwenang melakukan hak uji materiil atas UU terhadap UUD 1945.',
    ),
    QuestionItem(
      id: 'hkm_026',
      questionText: 'Lembaga yang berwenang menguji peraturan perundang-undangan di bawah Undang-Undang terhadap Undang-Undang adalah:',
      options: ['Mahkamah Agung (MA)', 'Mahkamah Konstitusi (MK)', 'Komisi Yudisial', 'Kejaksaan'],
      correctOptionIndex: 0,
      explanation: 'MA berwenang menguji Perpres, Permen, atau Perda terhadap UU.',
    ),
    QuestionItem(
      id: 'hkm_027',
      questionText: 'Lembaga negara independen yang bertugas mengusulkan pengangkatan Hakim Agung dan menjaga kehormatan hakim adalah:',
      options: ['Komisi Yudisial (KY)', 'Mahkamah Konstitusi', 'Kejaksaan Agung', 'KPK'],
      correctOptionIndex: 0,
      explanation: 'KY menjaga martabat, perilaku, dan kode etik kehakiman.',
    ),
    QuestionItem(
      id: 'hkm_028',
      questionText: 'Hukum yang mengatur organisasi negara, hubungan antar lembaga negara, dan hak-hak warga negara dinamakan:',
      options: ['Hukum Tata Negara (HTN)', 'Hukum Administrasi Negara (HAN)', 'Hukum Pidana', 'Hukum Perdata'],
      correctOptionIndex: 0,
      explanation: 'HTN mengurus kerangka kelembagaan struktur tata negara.',
    ),
    QuestionItem(
      id: 'hkm_029',
      questionText: 'Hukum yang mengatur tata cara instrumen pemerintah menjalankan fungsi administrasi pemerintahan sehari-hari dinamakan:',
      options: ['Hukum Administrasi Negara (HAN / HTN Materiil)', 'Hukum Dagang', 'Hukum Acara', 'Hukum Internasional'],
      correctOptionIndex: 0,
      explanation: 'HAN mengatur operasional birokrasi dan keputusan pejabat (KTUN).',
    ),
    QuestionItem(
      id: 'hkm_030',
      questionText: 'Keputusan Tertulis yang dikeluarkan oleh Badan atau Pejabat TUN yang bersifat konkret, individual, dan final dinamakan:',
      options: ['KTUN (Keputusan Tata Usaha Negara / Beschiking)', 'Regeling', 'Instruksi', 'Peraturan Daerah'],
      correctOptionIndex: 0,
      explanation: 'KTUN menjadi objek sengketa utama di pengadilan PTUN.',
    ),
    QuestionItem(
      id: 'hkm_031',
      questionText: 'Gugatan sengketa KTUN Pejabat Publik diajukan ke badan peradilan:',
      options: ['Pengadilan Tata Usaha Negara (PTUN)', 'Pengadilan Negeri', 'Pengadilan Agama', 'Pengadilan Niaga'],
      correctOptionIndex: 0,
      explanation: 'PTUN mengadili sengketa tata usaha negara.',
    ),
    QuestionItem(
      id: 'hkm_032',
      questionText: 'Perkara penghentian penyidikan pidana oleh Kejaksaan diterbitkan surat resmi dinamakan:',
      options: ['SKPP (Surat Penghentian Penuntutan Perkara)', 'SP3', 'BAP', 'P21'],
      correctOptionIndex: 0,
      explanation: 'SKPP diterbitkan Penuntut Umum untuk menghentikan penuntutan.',
    ),
    QuestionItem(
      id: 'hkm_033',
      questionText: 'Surat Perintah Penghentian Penyidikan yang dikeluarkan oleh kepolisian dinamakan:',
      options: ['SP3', 'P-21', 'BAP', 'SPDP'],
      correctOptionIndex: 0,
      explanation: 'SP3 diterbitkan penyidik kepolisian jika tidak cukup bukti.',
    ),
    QuestionItem(
      id: 'hkm_034',
      questionText: 'Kode berkas perkara pidana dari penyidik kepolisian yang dinyatakan lengkap oleh Kejaksaan adalah:',
      options: ['P-21', 'P-19', 'P-18', 'SP3'],
      correctOptionIndex: 0,
      explanation: 'P-21 menandakan berkas perkara pidana siap dilimpahkan ke sidang pengadilan.',
    ),
    QuestionItem(
      id: 'hkm_035',
      questionText: 'Lembaga pengawas independen pelayanan publik yang menerima aduan maladministrasi adalah:',
      options: ['Ombudsman Republik Indonesia', 'KPK', 'Komnas HAM', 'LPSK'],
      correctOptionIndex: 0,
      explanation: 'Ombudsman mengawasi penyelenggaraan pelayanan publik pemerintah.',
    ),
    QuestionItem(
      id: 'hkm_036',
      questionText: 'Lembaga independen yang bertugas memberikan perlindungan kepada saksi dan korban tindak pidana dinamakan:',
      options: ['LPSK (Lembaga Perlindungan Saksi dan Korban)', 'Komnas HAM', 'KPAI', 'LBH'],
      correctOptionIndex: 0,
      explanation: 'LPSK memberikan perlindungan fisik dan hukum saksi/korban.',
    ),
    QuestionItem(
      id: 'hkm_037',
      questionText: 'Proses pengujian keabsahan penangkapan, penahanan, atau penghentian penyidikan dinamakan lembaga:',
      options: ['Praperadilan', 'Kasasi', 'Banding', 'Peninjauan Kembali (PK)'],
      correctOptionIndex: 0,
      explanation: 'Praperadilan menguji wewenang kepolisan/kejaksaan atas hak asasi tersangka sebelum sidang utama.',
    ),
    QuestionItem(
      id: 'hkm_038',
      questionText: 'Upaya hukum biasa yang diajukan ke Pengadilan Tinggi atas putusan Pengadilan Negeri dinamakan:',
      options: ['Banding', 'Kasasi', 'Peninjauan Kembali', 'Grasi'],
      correctOptionIndex: 0,
      explanation: 'Banding memeriksa ulang fakta dan hukum perkara perdata/pidana.',
    ),
    QuestionItem(
      id: 'hkm_039',
      questionText: 'Upaya hukum biasa yang diajukan ke Mahkamah Agung atas putusan tingkat banding dinamakan:',
      options: ['Kasasi', 'Banding', 'Praperadilan', 'Revisi'],
      correctOptionIndex: 0,
      explanation: 'Kasasi di Mahkamah Agung berfokus pada penerapan hukum (Judex Juris).',
    ),
    QuestionItem(
      id: 'hkm_040',
      questionText: 'Upaya hukum luar biasa yang diajukan ke MA berdasarkan penemuan bukti baru (Novum) dinamakan:',
      options: ['Peninjauan Kembali (PK)', 'Kasasi Demi Hukum', 'Grasi', 'Amnesti'],
      correctOptionIndex: 0,
      explanation: 'PK diajukan jika ditemukan novum bukti baru yang belum pernah diperiksa.',
    ),
    QuestionItem(
      id: 'hkm_041',
      questionText: 'Pengampunan hukuman pidana yang diberikan Presiden dengan memperhatikan pertimbangan Mahkamah Agung dinamakan:',
      options: ['Grasi', 'Amnesti', 'Abolisi', 'Rehabilitasi'],
      correctOptionIndex: 0,
      explanation: 'Grasi menghapuskan/meringankan eksekusi pidana terdakwa.',
    ),
    QuestionItem(
      id: 'hkm_042',
      questionText: 'Pengampunan hukum tindak pidana tertentu kepada sekelompok orang (misal tahanan politik) oleh Presiden dinamakan:',
      options: ['Amnesti', 'Grasi', 'Remisi', 'Abolisi'],
      correctOptionIndex: 0,
      explanation: 'Amnesti menghapuskan akibat hukum pidana bagi sekelompok orang.',
    ),
    QuestionItem(
      id: 'hkm_043',
      questionText: 'Penghentian proses penuntutan pidana oleh Presiden dengan pertimbangan DPR dinamakan:',
      options: ['Abolisi', 'Amnesti', 'Grasi', 'Remisi'],
      correctOptionIndex: 0,
      explanation: 'Abolisi menghentikan proses penuntutan sebelum vonis.',
    ),
    QuestionItem(
      id: 'hkm_044',
      questionText: 'Pengurangan masa hukuman pidana yang diberikan kepada narapidana berkelakuan baik dinamakan:',
      options: ['Remisi', 'Grasi', 'Asimilasi', 'Pembebasan Bersyarat'],
      correctOptionIndex: 0,
      explanation: 'Remisi memotong jumlah durasi vonis penjara.',
    ),
    QuestionItem(
      id: 'hkm_045',
      questionText: 'Alat bukti sah dalam Hukum Acara Pidana menurut Pasal 184 KUHAP terdiri dari:',
      options: ['Keterangan Saksi, Keterangan Ahli, Surat, Petunjuk, dan Keterangan Terdakwa', 'Sumpah, Pengakuan, Janji', 'KTP, Rekaman HP, Foto', 'CCTV, Saksi Kunci, Jaksa'],
      correctOptionIndex: 0,
      explanation: 'Pasal 184 KUHAP membatasi 5 alat bukti sah pidana.',
    ),
    QuestionItem(
      id: 'hkm_046',
      questionText: 'Prinsip pembuktian minimum dalam hukum acara pidana mensyaratkan hakim memutuskan berdasarkan:',
      options: ['Sekurang-kurangnya 2 Alat Bukti Sah dan Keyakinan Hakim', '1 Alat Bukti', '3 Alat Bukti saja', 'Pengakuan Terdakwa saja'],
      correctOptionIndex: 0,
      explanation: 'Pasal 183 KUHAP mensyaratkan 2 alat bukti sah + keyakinan hakim.',
    ),
    QuestionItem(
      id: 'hkm_047',
      questionText: 'Alat bukti dalam hukum acara perdata menurut Pasal 164 HIR adalah:',
      options: ['Bukti Surat, Bukti Saksi, Persangkaan, Pengakuan, dan Sumpah', 'Surat dan Saksi saja', 'Keterangan Ahli', 'CCTV'],
      correctOptionIndex: 0,
      explanation: 'Bukti tulisan/surat menduduki hierarki utama pada perkara perdata.',
    ),
    QuestionItem(
      id: 'hkm_048',
      questionText: 'Hukum yang mengatur hubungan hukum antara negara-negara berdaulat atau subjek hukum internasional dinamakan:',
      options: ['Hukum Internasional Publik', 'Hukum Perdata Internasional', 'Hukum Pidana Internasional', 'Diplomasi'],
      correctOptionIndex: 0,
      explanation: 'Hukum Internasional Publik mengatur norma hubungan antarnegara dan organisasi internasional.',
    ),
    QuestionItem(
      id: 'hkm_049',
      questionText: 'Hukum yang mengatur hubungan hukum perdata antar warga negara yang berbeda kewarganegaraan dinamakan:',
      options: ['Hukum Perdata Internasional (HPI)', 'Hukum Publik Internasional', 'Hukum Dagang', 'Hukum Komersial'],
      correctOptionIndex: 0,
      explanation: 'HPI menentukan hukum nasional mana yang berlaku bagi sengketa antar individu lintas negara.',
    ),
    QuestionItem(
      id: 'hkm_050',
      questionText: 'Sumber-sumber Hukum Internasional utama menurut Pasal 38 Statuta Mahkamah Internasional (ICJ) adalah:',
      options: ['Perjanjian Internasional (Treaty), Kebiasaan Internasional, Prinsip Hukum Umum, Keputusan Pengadilan & Doktrin', 'Resolusi PBB saja', 'Konvensi Jenewa', 'Hukum Negara Adidaya'],
      correctOptionIndex: 0,
      explanation: 'Pasal 38 Statuta ICJ memuat 4 sumber primer dan sekunder hukum internasional.',
    ),
    QuestionItem(
      id: 'hkm_051',
      questionText: 'Prinsip norma imperatif tertinggi hukum internasional yang tidak boleh dilanggar oleh perjanjian apapun dinamakan:',
      options: ['Jus Cogens', 'Erga Omnes', 'Opinio Juris', 'Pacta Tertiis'],
      correctOptionIndex: 0,
      explanation: 'Jus Cogens adalah norma hukum internasional yang bersifat memaksa mutlak (perhabisan genosida/perbudakan).',
    ),
    QuestionItem(
      id: 'hkm_052',
      questionText: 'Keyakinan subjektif negara bahwa suatu tindakan kebiasaan dilakukan karena diwajibkan oleh hukum dinamakan:',
      options: ['Opinio Juris sive Necessitatis', 'Jus Cogens', 'State Practice', 'Soft Law'],
      correctOptionIndex: 0,
      explanation: 'Opinio Juris adalah syarat psikologis terbentuknya hukum kebiasaan internasional.',
    ),
    QuestionItem(
      id: 'hkm_053',
      questionText: 'Hak kebal hukum diplomatik perwakilan negara asing di negara penerima dinamakan hak:',
      options: ['Imunitas Diplomatik (Diplomatic Immunity)', 'Ekstradisi', 'Suaka', 'Ekstrateritorial'],
      correctOptionIndex: 0,
      explanation: 'Konvensi Wina 1961 menjamin imunitas diplomatik dari yurisdiksi pidana/perdata penerima.',
    ),
    QuestionItem(
      id: 'hkm_054',
      questionText: 'Gedung kedutaan besar negara asing dianggap tidak boleh dimasukin oleh aparat lokal tanpa izin dinamakan prinsip:',
      options: ['Inviolability (Kekebalan Gedung Misi Diplomatik)', 'Persona Non Grata', 'Suaka', 'Ex Gratia'],
      correctOptionIndex: 0,
      explanation: 'Inviolability melindungi gedung misi diplomatik dari penerobosan.',
    ),
    QuestionItem(
      id: 'hkm_055',
      questionText: 'Tindakan penolakan resmi atau pengusiran diplomat asing oleh negara penerima dinamakan penetapan:',
      options: ['Persona Non Grata', 'Persona Grata', 'Deportasi', 'Ekstradisi'],
      correctOptionIndex: 0,
      explanation: 'Persona Non Grata menyatakan diplomat tidak lagi disukai/diterima.',
    ),
    QuestionItem(
      id: 'hkm_056',
      questionText: 'Penyerahan buronan atau tersangka kejahatan oleh suatu negara kepada negara asal permohonan dinamakan:',
      options: ['Ekstradisi (Extradition)', 'Deportasi', 'Suaka Politik', 'Repatriasi'],
      correctOptionIndex: 0,
      explanation: 'Ekstradisi berdasarkan perjanjian timbal balik antarnegara.',
    ),
    QuestionItem(
      id: 'hkm_057',
      questionText: 'Perlindungan hukum yang diberikan suatu negara kepada warga asing yang melarikan diri dari penganiayaan politik dinamakan:',
      options: ['Suaka Politik (Asylum)', 'Imunitas', 'Deportasi', 'Amnesti'],
      correctOptionIndex: 0,
      explanation: 'Suaka politik diberikan atas pertimbangan kemanusiaan dan kebebasan.',
    ),
    QuestionItem(
      id: 'hkm_058',
      questionText: 'Empat kejahatan internasional yang menjadi yurisdiksi Mahkamah Pidana Internasional (ICC) adalah:',
      options: ['Genosida, Kejahatan Kemanusiaan, Kejahatan Perang, dan Agresi', 'Korupsi, Narkoba, Terorisme, Pirasi', 'Pencucian Uang, Cybercrime, Porno, Judi', 'Penyelundupan, Illegal Logging, Trafficking, Deforestasi'],
      correctOptionIndex: 0,
      explanation: 'Statuta Roma menggariskan 4 The Most Serious Crimes under International Law.',
    ),
    QuestionItem(
      id: 'hkm_059',
      questionText: 'Kejahatan dimusnahkannya seluruh atau sebagian kelompok bangsa, ras, etnis, atau agama dinamakan:',
      options: ['Genosida (Genocide)', 'Apartheid', 'Agresi', 'Kejahatan Perang'],
      correctOptionIndex: 0,
      explanation: 'Genosida bertujuan memusnahkan kelompok identitas tertentu.',
    ),
    QuestionItem(
      id: 'hkm_060',
      questionText: 'Pengadilan pidana internasional permanen yang berkedudukan di Den Haag dinamakan:',
      options: ['ICC (International Criminal Court)', 'ICJ', 'ITLOS', 'Permanent Court of Arbitration'],
      correctOptionIndex: 0,
      explanation: 'ICC mengadili individu atas kejahatan internasional berat.',
    ),
    QuestionItem(
      id: 'hkm_061',
      questionText: 'Badan kehakiman utama PBB yang mengadili sengketa antarnegara berkedudukan di Den Haag dinamakan:',
      options: ['ICJ (International Court of Justice)', 'ICC', 'UNHCR', 'Dewan Keamanan PBB'],
      correctOptionIndex: 0,
      explanation: 'ICJ mengadili kasus sengketa antarnegara.',
    ),
    QuestionItem(
      id: 'hkm_062',
      questionText: 'Batas wilayah laut teritorial suatu negara pantai menurut UNCLOS 1982 adalah sejauh:',
      options: ['12 Mil Laut dari garis pangkal', '200 Mil Laut', '24 Mil Laut', '3 Mil Laut'],
      correctOptionIndex: 0,
      explanation: 'Laut Teritorial mengukur kedaulatan penuh negara pantai sejauh 12 mil.',
    ),
    QuestionItem(
      id: 'hkm_063',
      questionText: 'Zona Ekonomi Eksklusif (ZEE) memberikan hak berdaulat mengeksploitasi sumber daya alam sejauh:',
      options: ['200 Mil Laut', '12 Mil Laut', '24 Mil Laut', '350 Mil Laut'],
      correctOptionIndex: 0,
      explanation: 'ZEE terbentang hingga 200 mil laut dari garis pangkal pantai.',
    ),
    QuestionItem(
      id: 'hkm_064',
      questionText: 'Sistem hukum yang berkembang di Inggris dan negara-negara persemakmuran berbasis yurisprudensi hakim dinamakan:',
      options: ['Common Law (Anglo-Saxon)', 'Civil Law (Eropa Kontinental)', 'Hukum Adat', 'Hukum Kanonik'],
      correctOptionIndex: 0,
      explanation: 'Common Law mengagungkan preseden putusan hakim sebelumnya (Stare Decisis).',
    ),
    QuestionItem(
      id: 'hkm_065',
      questionText: 'Sistem hukum Indonesia bertumpu pada kodifikasi hukum tertulis tradisi:',
      options: ['Civil Law (Eropa Kontinental / Tradisi Belanda)', 'Common Law', 'Anglo-Saxon', 'Nordic Law'],
      correctOptionIndex: 0,
      explanation: 'Indonesia mewarisi tradisi Civil Law Belanda (Kitab Undang-Undang Tertulis).',
    ),
    QuestionItem(
      id: 'hkm_066',
      questionText: 'Prinsip hukum Common Law di mana hakim wajib mengikuti keputusan hakim terdahulu untuk perkara serupa dinamakan:',
      options: ['Stare Decisis', 'Res Judicata', 'Obiter Dicta', 'Ratio Decidendi'],
      correctOptionIndex: 0,
      explanation: 'Stare Decisis (Preseden) menjadi pilar utama sistem hukum Anglo-Saxon.',
    ),
    QuestionItem(
      id: 'hkm_067',
      questionText: 'Landasan pertimbangan hukum utama dalam putusan hakim yang menjadi dasar amar putusan dinamakan:',
      options: ['Ratio Decidendi', 'Obiter Dicta', 'Amar Putusan', 'Konsiderans'],
      correctOptionIndex: 0,
      explanation: 'Ratio Decidendi adalah alasan inti filosofis dan juridis Hakim.',
    ),
    QuestionItem(
      id: 'hkm_068',
      questionText: 'Pernyataan pelengkap hakim di luar inti pertimbangan hukum utama dinamakan:',
      options: ['Obiter Dicta', 'Ratio Decidendi', 'Dissenting Opinion', 'Ketetapan'],
      correctOptionIndex: 0,
      explanation: 'Obiter dicta adalah pendapat sampingan hakim.',
    ),
    QuestionItem(
      id: 'hkm_069',
      questionText: 'Pendapat beda seorang anggota majelis hakim yang tidak menyetujui vonis mayoritas hakim lainnya dinamakan:',
      options: ['Dissenting Opinion', 'Concurring Opinion', 'Amicus Curiae', 'Ratio Decidendi'],
      correctOptionIndex: 0,
      explanation: 'Dissenting Opinion mencatat silang pendapat hakim minoritas secara resmi.',
    ),
    QuestionItem(
      id: 'hkm_070',
      questionText: 'Sahabat pengadilan yang memberikan pandangan pertimbangan opini tertulis independen bagi hakim dinamakan:',
      options: ['Amicus Curiae (Friends of the Court)', 'Pro Bono', 'Advokat', 'Paralegal'],
      correctOptionIndex: 0,
      explanation: 'Amicus Curiae menyerahkan dokumen pengamatan publik untuk pertimbangan hakim.',
    ),
    QuestionItem(
      id: 'hkm_071',
      questionText: 'Bantuan jasa hukum cuma-cuma yang diberikan advokat kepada masyarakat tidak mampu dinamakan layanan:',
      options: ['Pro Bono (Pro Bono Publico)', 'Pro Deo', 'Legal Aid', 'Consultation'],
      correctOptionIndex: 0,
      explanation: 'Pro Bono diwajibkan bagi advokat untuk kepentingan pengabdian masyarakat.',
    ),
    QuestionItem(
      id: 'hkm_072',
      questionText: 'Pembebasan biaya perkara pengadilan bagi masyarakat miskin yang ditanggung anggaran negara dinamakan:',
      options: ['Pro Deo', 'Pro Bono', 'Subsidi', 'Remisi'],
      correctOptionIndex: 0,
      explanation: 'Pro Deo membebaskan biaya panjar perkara pengadilan bagi warga tak mampu.',
    ),
    QuestionItem(
      id: 'hkm_073',
      questionText: 'Pemberian kuasa kewenangan pengurusan aset harta kepada pihak lain melalui akta notaris dinamakan:',
      options: ['Bijzondere Volmacht (Surat Kuasa Khusus)', 'Dwangsom', 'Fidusia', 'Hypotik'],
      correctOptionIndex: 0,
      explanation: 'Surat Kuasa Khusus disyaratkan untuk beracara di pengadilan.',
    ),
    QuestionItem(
      id: 'hkm_074',
      questionText: 'Jaminan hak kebendaan atas barang bergerak di mana penguasaan benda tetap pada debitur dinamakan:',
      options: ['Jaminan Fidusia', 'Gadai', 'Hipotek', 'Hak Tanggungan'],
      correctOptionIndex: 0,
      explanation: 'Fidusia mengalihkan hak kepemilikan atas kepercayaan sementara fisik benda tetap di tangan debitur.',
    ),
    QuestionItem(
      id: 'hkm_075',
      questionText: 'Jaminan hak atas tanah dan benda-benda yang berkaitan dengan tanah untuk pelunasan utang dinamakan:',
      options: ['Hak Tanggungan', 'Fidusia', 'Gadai', 'Hipotek Kapal'],
      correctOptionIndex: 0,
      explanation: 'UU No. 4/1996 mengatur Hak Tanggungan untuk agunan properti/tanah.',
    ),
    QuestionItem(
      id: 'hkm_076',
      questionText: 'Penyelesaian sengketa perdata di luar pengadilan umum melalui penunjukan wasit independen dinamakan:',
      options: ['Arbitrase (Arbitration)', 'Mediasi', 'Konsiliasi', 'Litigasi'],
      correctOptionIndex: 0,
      explanation: 'Arbitrase menghasilkan putusan arbitrase yang bersifat final dan mengikat (BANI).',
    ),
    QuestionItem(
      id: 'hkm_077',
      questionText: 'Proses perundingan penyelesaian sengketa dibantu oleh pihak ketiga netral yang tidak berwenang memutus dinamakan:',
      options: ['Mediasi', 'Arbitrase', 'Judicial Review', 'Litigasi'],
      correctOptionIndex: 0,
      explanation: 'Mediator mendampingi pemicu kesepakatan damai kedua pihak.',
    ),
    QuestionItem(
      id: 'hkm_078',
      questionText: 'Penyelesaian sengketa melalui jalur persidangan di badan peradilan resmi negara dinamakan penyelesaian secara:',
      options: ['Litigasi', 'Non-Litigasi', 'Mediasi', 'Arbitrase'],
      correctOptionIndex: 0,
      explanation: 'Litigasi adalah jalur formal pengadilan.',
    ),
    QuestionItem(
      id: 'hkm_079',
      questionText: 'Asas kepastian hukum yang menyatakan perkara perdata yang telah diputus dan berkekuatan hukum tetap tidak boleh digugat kembali dinamakan:',
      options: ['Res Judicata (Exceptio Rei Judicatae)', 'Ne Bis In Idem', 'Pacta Sunt Servanda', 'Ultra Vires'],
      correctOptionIndex: 0,
      explanation: 'Res Judicata menjamin kepastian hukum atas putusan perdata yang inkracht.',
    ),
    QuestionItem(
      id: 'hkm_080',
      questionText: 'Tindakan atau keputusan pejabat publik yang melebihi batas kewenangan yang diberikan undang-undang dinamakan:',
      options: ['Ultra Vires', 'Detournement de Pouvoir', 'Maladministrasi', 'Wanprestasi'],
      correctOptionIndex: 0,
      explanation: 'Ultra Vires adalah kewenangan melampaui batas formal undang-undang.',
    ),
    QuestionItem(
      id: 'hkm_081',
      questionText: 'Penyalahgunaan wewenang pejabat publik untuk tujuan selain yang ditetapkan undang-undang dinamakan:',
      options: ['Detournement de Pouvoir (Penyalahgunaan Wewenang)', 'Ultra Vires', 'Onrechtmatige Daad', 'Fidusia'],
      correctOptionIndex: 0,
      explanation: 'Detournement de Pouvoir menggunakan wewenang sah untuk maksud tidak sah.',
    ),
    QuestionItem(
      id: 'hkm_082',
      questionText: 'Penyitaan sementara oleh pengadilan atas barang milik tergugat untuk menjamin pelaksanaan eksekusi putusan kelak dinamakan:',
      options: ['Sita Jaminan (Conservatoir Beslag)', 'Sita Eksekusi', 'Sita Marital', 'Sita Pidana'],
      correctOptionIndex: 0,
      explanation: 'Conservatoir Beslag mencegah tergugat mengalihkan aset selama proses persidangan berlangsung.',
    ),
    QuestionItem(
      id: 'hkm_083',
      questionText: 'Denda paksa pembayaran berupa uang harian yang ditetapkan hakim atas keterlambatan melaksanakan hukuman perdata dinamakan:',
      options: ['Dwangsom (Uang Paksa)', 'Uang Ganti Rugi', 'Denda Pidana', 'Bunga Moratoir'],
      correctOptionIndex: 0,
      explanation: 'Dwangsom memaksa tergugat mematuhi prestasi non-uang.',
    ),
    QuestionItem(
      id: 'hkm_084',
      questionText: 'Hukum adat Indonesia yang menganut garis keturunan ditarik dari pihak ayah dinamakan sistem:',
      options: ['Patrilineal', 'Matrilineal', 'Parental / Bipartite', 'Bilateral'],
      correctOptionIndex: 0,
      explanation: 'Sistem Patrilineal dianut masyarakat Batak, Bali, dan Lampung.',
    ),
    QuestionItem(
      id: 'hkm_085',
      questionText: 'Sistem kekerabatan hukum adat Minangkabau yang menarik garis keturunan dari pihak ibu dinamakan:',
      options: ['Matrilineal', 'Patrilineal', 'Parental', 'Bilateral'],
      correctOptionIndex: 0,
      explanation: 'Masyarakat Minangkabau menganut garis keturunan Matrilineal.',
    ),
    QuestionItem(
      id: 'hkm_086',
      questionText: 'Sistem kekerabatan Jawa dan Sunda yang menarik garis keturunan dari kedua belah pihak orang tua dinamakan:',
      options: ['Parental / Bilateral', 'Patrilineal', 'Matrilineal', 'Komunal'],
      correctOptionIndex: 0,
      explanation: 'Parental/Bilateral memperlakukan hak keturunan ayah dan ibu secara seimbang.',
    ),
    QuestionItem(
      id: 'hkm_087',
      questionText: 'Hak persekutuan hukum adat untuk menguasai dan memanfaatkan tanah beserta ulayatnya dinamakan Hak:',
      options: ['Hak Ulayat', 'Hak Eigendom', 'Hak Opstal', 'Hak Erfpacht'],
      correctOptionIndex: 0,
      explanation: 'Hak Ulayat diakui UUPA sepanjang masih hidup dan sesuai prinsip NKRI.',
    ),
    QuestionItem(
      id: 'hkm_088',
      questionText: 'Undang-Undang Pokok Agraria (UUPA) yang menjadi landasan hukum pertanahan Indonesia disahkan pada UU No. 5 Tahun:',
      options: ['1960', '1945', '1974', '1999'],
      correctOptionIndex: 0,
      explanation: 'UU No. 5 Tahun 1960 tentang Peraturan Dasar Pokok-Pokok Agraria.',
    ),
    QuestionItem(
      id: 'hkm_089',
      questionText: 'Hak atas tanah tertinggi yang bersifat turun-temurun, terkuat, dan terpenuh yang hanya dimiliki WNI dinamakan:',
      options: ['Hak Milik', 'Hak Guna Bangunan (HGB)', 'Hak Guna Usaha (HGU)', 'Hak Pakai'],
      correctOptionIndex: 0,
      explanation: 'Hak Milik atas tanah hanya boleh dimiliki oleh Warga Negara Indonesia.',
    ),
    QuestionItem(
      id: 'hkm_090',
      questionText: 'Hak untuk mendirikan dan mempunyai bangunan di atas tanah milik orang lain/negara selama durasi tertentu dinamakan:',
      options: ['Hak Guna Bangunan (HGB)', 'Hak Guna Usaha (HGU)', 'Hak Sewa', 'Hak Milik'],
      correctOptionIndex: 0,
      explanation: 'HGB berlaku maksimal 30 tahun dan dapat diperpanjang.',
    ),
    QuestionItem(
      id: 'hkm_091',
      questionText: 'Hak mengusahakan tanah yang dikuasai langsung oleh negara untuk usaha pertanian/perkebunan dinamakan:',
      options: ['Hak Guna Usaha (HGU)', 'HGB', 'Hak Pakai', 'Hak Pengelolaan'],
      correctOptionIndex: 0,
      explanation: 'HGU diberikan untuk perkebunan, perikanan, atau peternakan skala besar.',
    ),
    QuestionItem(
      id: 'hkm_092',
      questionText: 'Tiga jenis korporasi badan hukum perdata yang kekayaan pemliknya terpisah dari kekayaan pribadi adalah:',
      options: ['Perseroan Terbatas (PT), Yayasan, dan Koperasi', 'CV, Firma, UD', 'BUMDes, UMKM, Warung', 'Kemitraan, Joint Venture, Konsorsium'],
      correctOptionIndex: 0,
      explanation: 'PT, Yayasan, dan Koperasi adalah Badan Hukum (Legal Entity) sah.',
    ),
    QuestionItem(
      id: 'hkm_093',
      questionText: 'Badan usaha persekutuan komanditer di mana terdapat sekutu aktif (pengurus) dan sekutu pasif (pemodal) dinamakan:',
      options: ['CV (Commanditaire Vennootschap)', 'Firma', 'PT', 'Perum'],
      correctOptionIndex: 0,
      explanation: 'CV membedakan sekutu komplementer (aktif) dan sekutu komanditer (pasif).',
    ),
    QuestionItem(
      id: 'hkm_094',
      questionText: 'Kondisi badan usaha perseroan yang ditetapkan oleh pengadilan tidak mampu membayar utang-utangnya yang jatuh tempo dinamakan:',
      options: ['Kepailitan (Pailit)', 'PKPU', 'Likuidasi', 'Insolvensi'],
      correctOptionIndex: 0,
      explanation: 'Kepailitan diatur dalam UU No. 37 Tahun 2004.',
    ),
    QuestionItem(
      id: 'hkm_095',
      questionText: 'Proses penundaan kewajiban pembayaran utang untuk memberikan kesempatan restrukturisasi usaha debitur dinamakan:',
      options: ['PKPU (Penundaan Kewajiban Pembayaran Utang)', 'Pailit', 'Sita Marital', 'Reorganisasi'],
      correctOptionIndex: 0,
      explanation: 'PKPU bertujuan mencapai kesepakatan perdamaian pembayaran utang.',
    ),
    QuestionItem(
      id: 'hkm_096',
      questionText: 'Perkara pengadilan niaga yang memutus sengketa merek, paten, dan hak cipta dinamakan perselisihan:',
      options: ['HKI (Hak Kekayaan Intelektual)', 'Kepailitan', 'Persaingan Usaha', 'Sengketa Pajak'],
      correctOptionIndex: 0,
      explanation: 'HKI melingkupi Hak Cipta dan Hak Kekayaan Industri (Merek, Paten, Desain Industri).',
    ),
    QuestionItem(
      id: 'hkm_097',
      questionText: 'Hak eksklusif pencipta yang timbul secara otomatis berdasarkan prinsip deklaratif atas ciptaan seni/literatur dinamakan:',
      options: ['Hak Cipta (Copyright)', 'Paten', 'Merek', 'Rahasia Dagang'],
      correctOptionIndex: 0,
      explanation: 'Hak Cipta timbul otomatis sejak ciptaan diwujudkan dalam bentuk nyata.',
    ),
    QuestionItem(
      id: 'hkm_098',
      questionText: 'Hak eksklusif yang diberikan negara kepada penemu atas hasil invensi teknologi di bidang teknologi dinamakan:',
      options: ['Paten (Patent)', 'Hak Cipta', 'Desain Industri', 'Merek'],
      correctOptionIndex: 0,
      explanation: 'Paten melindungi invensi teknis baru yang memiliki langkah inventif.',
    ),
    QuestionItem(
      id: 'hkm_099',
      questionText: 'Tanda berupa gambar, nama, kata, atau logo yang digunakan untuk membedakan produk barang/jasa dinamakan:',
      options: ['Merek (Trademark)', 'Paten', 'Desain Industri', 'Indikasi Geografis'],
      correctOptionIndex: 0,
      explanation: 'Merek memberikan hak monopoli penggunaan identitas komersial.',
    ),
    QuestionItem(
      id: 'hkm_100',
      questionText: 'Pendekatan hukum keadilan yang berfokus pada pemulihan kerugian korban dan pertanggungjawaban pelaku dinamakan:',
      options: ['Keadilan Restoratif (Restorative Justice)', 'Keadilan Retributif', 'Keadilan Distributif', 'Keadilan Legalis'],
      correctOptionIndex: 0,
      explanation: 'Restorative Justice mengedepankan pemulihan kedamaian sosial ketimbang sekadar pembalasan penjara.',
    ),
  ];
}
