import '../tes_seleksi_model.dart';

List<QuestionItem> getHubunganInternasionalQuestions() {
  return const [
    QuestionItem(
      id: 'hi_001',
      questionText: 'Peristiwa sejarah tahun 1648 yang menandai lahirnya sistem negara berdaulat modern dinamakan:',
      options: ['Perjanjian Westphalia (Peace of Westphalia)', 'Perjanjian Versailles', 'Konferensi Wina', 'Deklarasi Utrecht'],
      correctOptionIndex: 0,
      explanation: 'Perjanjian Westphalia 1648 meletakkan prinsip kedaulatan wilayah negara (sovereignty).',
    ),
    QuestionItem(
      id: 'hi_002',
      questionText: 'Perspektif teori HI yang menganggap negara sebagai aktor rasional utama dalam sistem internasional yang anarkis dinamakan:',
      options: ['Realisme (Realism)', 'Liberalisme', 'Konstruktivisme', 'Marxisme'],
      correctOptionIndex: 0,
      explanation: 'Realisme berfokus pada perebutan kekuasaan (power) dan kepentingan nasional.',
    ),
    QuestionItem(
      id: 'hi_003',
      questionText: 'Perspektif HI yang menekankan pentingnya kerja sama internasional, lembaga global, dan perdamaian dinamakan:',
      options: ['Liberalisme / Neoliberalisme', 'Realisme', 'Merkantilisme', 'Realpolitik'],
      correctOptionIndex: 0,
      explanation: 'Liberalisme mempercayai peran institusi dan ketergantungan ekonomi memicu perdamaian.',
    ),
    QuestionItem(
      id: 'hi_004',
      questionText: 'Teori HI yang menyatakan bahwa dunia politik internasional dikonstruksikan oleh norma, ideologi, dan identitas sosial dinamakan:',
      options: ['Konstruktivisme (Constructivism)', 'Realisme', 'Liberalisme', 'Strukturalisme'],
      correctOptionIndex: 0,
      explanation: 'Alexander Wendt merumuskan Konstruktivisme: "Anarchy is what states make of it".',
    ),
    QuestionItem(
      id: 'hi_005',
      questionText: 'Konsep dalam Realisme di mana upaya suatu negara meningkatkan keamanannya justru memicu kecemasan negara tetangga dinamakan:',
      options: ['Security Dilemma (Dilema Keamanan)', 'Balance of Power', 'Hegemonic Stability', 'Zero-Sum Game'],
      correctOptionIndex: 0,
      explanation: 'Security Dilemma memicu perlombaan senjata (arms race).',
    ),
    QuestionItem(
      id: 'hi_006',
      questionText: 'Strategi pencegahan perang dengan mengancam tindakan balasan pembalasan ekstrem dinamakan:',
      options: ['Deterrence (Penangkalan)', 'Preemptive Strike', 'Coercion', 'Appeasement'],
      correctOptionIndex: 0,
      explanation: 'Deterrence mencegah musuh menyerang dengan ancaman balasan mematikan.',
    ),
    QuestionItem(
      id: 'hi_007',
      questionText: 'Penggunaan kekuatan ekonomi, budaya, dan diplomasi untuk mempengaruhi negara lain dinamakan:',
      options: ['Soft Power', 'Hard Power', 'Smart Power', 'Coercive Power'],
      correctOptionIndex: 0,
      explanation: 'Joseph Nye merumuskan Soft Power sebagai daya tarik budaya/nilai bukan militer.',
    ),
    QuestionItem(
      id: 'hi_008',
      questionText: 'Penggunaan militer dan sanksi ekonomi untuk memaksa kepatuhan negara lain dinamakan:',
      options: ['Hard Power', 'Soft Power', 'Sharp Power', 'Normative Power'],
      correctOptionIndex: 0,
      explanation: 'Hard Power mengandalkan coercion kekuatan fisik dan tekanan ekonomi.',
    ),
    QuestionItem(
      id: 'hi_009',
      questionText: 'Kombinasi efektif antara Hard Power dan Soft Power dalam strategi luar negeri dinamakan:',
      options: ['Smart Power', 'Cyber Power', 'Relative Power', 'Absolute Power'],
      correctOptionIndex: 0,
      explanation: 'Smart Power memadukan kapabilitas militer dengan diplomasi budaya yang adaptif.',
    ),
    QuestionItem(
      id: 'hi_010',
      questionText: 'Kondisi ketidakberadaan otoritas pemerintahan pusat di atas negara-negara dalam sistem internasional dinamakan:',
      options: ['Anarki Internasional (Anarchy)', 'Hierarki', 'Monarki', 'Oligarki'],
      correctOptionIndex: 0,
      explanation: 'Anarki di HI mengacu pada ketiadaan pemerintahan global tunggal penyelesai sengketa.',
    ),
    QuestionItem(
      id: 'hi_011',
      questionText: 'Kondisi ketika satu negara adidaya mendominasi dan memimpin sistem global dinamakan:',
      options: ['Hegemoni (Unipolaritas)', 'Bipolaritas', 'Multipolaritas', 'Anarki'],
      correctOptionIndex: 0,
      explanation: 'Hegemoni memegang kekuasaan dominan menentukan aturan global.',
    ),
    QuestionItem(
      id: 'hi_012',
      questionText: 'Sistem internasional Perang Dingin di mana dua blok adidaya (AS dan Uni Soviet) saling bersaing dinamakan sistem:',
      options: ['Bipolaritas (Bipolarity)', 'Unipolaritas', 'Multipolaritas', 'Non-Blok'],
      correctOptionIndex: 0,
      explanation: 'Perang Dingin adalah contoh era struktur Bipolaritas.',
    ),
    QuestionItem(
      id: 'hi_013',
      questionText: 'Struktur politik internasional dengan tiga atau lebih pusat kekuatan utama negara dinamakan:',
      options: ['Multipolaritas (Multipolarity)', 'Bipolaritas', 'Unipolaritas', 'Tri polaritas'],
      correctOptionIndex: 0,
      explanation: 'Multipolaritas melibatkan persaingan beberapa kekuasaan besar.',
    ),
    QuestionItem(
      id: 'hi_014',
      questionText: 'Kemitraan pertahanan militer antar negara-negara Atlantik Utara yang dibentuk pada tahun 1949 adalah:',
      options: ['NATO (North Atlantic Treaty Organization)', 'Pakta Warsawa', 'SEATO', 'ANZUS'],
      correctOptionIndex: 0,
      explanation: 'NATO memegang asas pertahanan kolektif Pasal 5 (Collective Defense).',
    ),
    QuestionItem(
      id: 'hi_015',
      questionText: 'Pakta pertahanan militer blok timur pimpinan Uni Soviet untuk menandingi NATO dinamakan:',
      options: ['Pakta Warsawa (Warsaw Pact)', 'Cominform', 'Komintern', 'COMECON'],
      correctOptionIndex: 0,
      explanation: 'Pakta Warsawa didirikan 1955 oleh Uni Soviet dan sekutu eropa timur.',
    ),
    QuestionItem(
      id: 'hi_016',
      questionText: 'Organisasi internasional pendahulu PBB yang gagal mencegah Perang Dunia II adalah:',
      options: ['Liga Bangsa-Bangsa (LBB / League of Nations)', 'PBB', 'KTT Non-Blok', 'Komintern'],
      correctOptionIndex: 0,
      explanation: 'LBB dibentuk pasca Perang Dunia I namun gagal mencegah agresi perang.',
    ),
    QuestionItem(
      id: 'hi_017',
      questionText: 'PBB didirikan pada tanggal 24 Oktober 1945 berdasarkan piagam peresmian:',
      options: ['Piagam San Francisco (UN Charter)', 'Deklarasi Atlantik', 'Konferensi Yalta', 'Perjanjian Paris'],
      correctOptionIndex: 0,
      explanation: 'UN Charter ditandatangani di San Francisco tahun 1945.',
    ),
    QuestionItem(
      id: 'hi_018',
      questionText: 'Lima anggota tetap Dewan Keamanan PBB yang memiliki Hak Veto adalah:',
      options: ['AS, Inggris, Prancis, Rusia, dan Tiongkok', 'AS, Jerman, Jepang, Inggris, Rusia', 'AS, India, Tiongkok, Prancis, Inggris', 'Rusia, Tiongkok, Brazil, India, Afrika Selatan'],
      correctOptionIndex: 0,
      explanation: 'P5 (Permanent Five) DK PBB memegang hak veto putusan.',
    ),
    QuestionItem(
      id: 'hi_019',
      questionText: 'Lembaga PBB yang bertanggung jawab utama menjaga perdamaian dan keamanan internasional adalah:',
      options: ['Dewan Keamanan PBB (UN Security Council)', 'Majelis Umum PBB', 'ECOSOC', 'Mahkamah Internasional'],
      correctOptionIndex: 0,
      explanation: 'DK PBB berwenang menerbitkan resolusi sanksi dan pasukan perdamaian.',
    ),
    QuestionItem(
      id: 'hi_020',
      questionText: 'Sikap luar negeri bebas aktif Indonesia dicanangkan pertama kali oleh Mohammad Hatta pada tahun 1948 dengan pidato berjudul:',
      options: ['Mendayung di Antara Dua Karang', 'Indonesia Menggugat', 'Lahirnya Pancasila', 'Bebas Aktif Sejahtera'],
      correctOptionIndex: 0,
      explanation: 'Pidato "Mendayung di Antara Dua Karang" menegaskan posisi independen Indonesia dari blok barat/timur.',
    ),
    QuestionItem(
      id: 'hi_021',
      questionText: 'Konferensi Asia-Afrika (KAA) yang melahirkan Dasasila Bandung diselenggarakan di Bandung pada tahun:',
      options: ['1955', '1945', '1961', '1967'],
      correctOptionIndex: 0,
      explanation: 'KAA Bandung 1955 memperkuat solidaritas negara-negara berkembang.',
    ),
    QuestionItem(
      id: 'hi_022',
      questionText: 'Gerakan Non-Blok (GNB / NAM) didirikan secara resmi dalam KTT Beograd pada tahun:',
      options: ['1961', '1955', '1970', '1948'],
      correctOptionIndex: 0,
      explanation: 'KTT Beograd 1961 meresmikan GNB (Tito, Sukarno, Nehru, Nasser, Nkrumah).',
    ),
    QuestionItem(
      id: 'hi_023',
      questionText: 'Deklarasi penandatanganan pendirian ASEAN pada 8 Agustus 1967 berlangsung di kota:',
      options: ['Bangkok (Deklarasi Bangkok)', 'Jakarta', 'Kuala Lumpur', 'Manila'],
      correctOptionIndex: 0,
      explanation: 'Deklarasi Bangkok 1967 ditandatangani 5 menteri luar negeri pendiri ASEAN.',
    ),
    QuestionItem(
      id: 'hi_024',
      questionText: 'Lima tokoh menteri luar negeri pendiri ASEAN pada tahun 1967 adalah:',
      options: ['Adam Malik, Tun Abdul Razak, Thanat Khoman, S. Rajaratnam, Narciso Ramos', 'Sukarno, Mahathir, Lee Kuan Yew, Marcos, Thanat', 'Hatta, Razak, Lee, Ramos, Khoman', 'Ali Alatas, Mahathir, Goh Chok Tong, Ramos, Khoman'],
      correctOptionIndex: 0,
      explanation: '5 Menteri Luar Negeri meresmikan ASEAN di Bangkok.',
    ),
    QuestionItem(
      id: 'hi_025',
      questionText: 'Prinsip normatif tata cara ASEAN menghormati kedaulatan dan tidak campur tangan dinamakan:',
      options: ['ASEAN Way (Non-Interference)', 'Manila Accord', 'ZOPFAN', 'AFTA'],
      correctOptionIndex: 0,
      explanation: 'ASEAN Way mengedepankan konsultasi, konsensus, dan non-intervensi.',
    ),
    QuestionItem(
      id: 'hi_026',
      questionText: 'Deklarasi ASEAN menjadikan kawasan Asia Tenggara sebagai Zona Damai, Bebas, dan Netral dinamakan:',
      options: ['ZOPFAN (Zone of Peace, Freedom and Neutrality)', 'SEANWFZ', 'AFTA', 'AEC'],
      correctOptionIndex: 0,
      explanation: 'ZOPFAN dicanangkan di Kuala Lumpur 1971.',
    ),
    QuestionItem(
      id: 'hi_027',
      questionText: 'Traktat Kawasan Bebas Senjata Nuklir di Asia Tenggara dikenal dengan singkatan:',
      options: ['SEANWFZ (South East Asia Nuclear Weapon-Free Zone)', 'ZOPFAN', 'NPT', 'SALT'],
      correctOptionIndex: 0,
      explanation: 'Traktat SEANWFZ ditandatangani di Bangkok 1995.',
    ),
    QuestionItem(
      id: 'hi_028',
      questionText: 'Komunitas Ekonomi ASEAN (Masyarakat Ekonomi ASEAN) mulai diberlakukan secara efektif pada akhir tahun:',
      options: ['2015', '2010', '2020', '2005'],
      correctOptionIndex: 0,
      explanation: 'MEA (AEC) berlaku 31 Desember 2015 mengintegrasikan pasar barang dan tenaga kerja terampil.',
    ),
    QuestionItem(
      id: 'hi_029',
      questionText: 'Traktat Non-Proliferasi Nuklir untuk mencegah penyebaran senjata nuklir dinamakan:',
      options: ['NPT (Non-Proliferation Treaty)', 'CTBT', 'SALT', 'START'],
      correctOptionIndex: 0,
      explanation: 'NPT mengawasi kepemilikan dan transfer teknologi nuklir militer.',
    ),
    QuestionItem(
      id: 'hi_030',
      questionText: 'Perundingan pembatasan senjata strategis nuklir antara AS dan Uni Soviet pada era Perang Dingin dinamakan:',
      options: ['SALT (Strategic Arms Limitation Talks)', 'NPT', 'ABM Treaty', 'INF Treaty'],
      correctOptionIndex: 0,
      explanation: 'SALT I dan SALT II membatasi jumlah peluncur rudal balistik.',
    ),
    QuestionItem(
      id: 'hi_031',
      questionText: 'Doktrin pencegahan nuklir di mana serangan pertama akan memicu kehancuran total bagi kedua belah pihak dinamakan:',
      options: ['MAD (Mutually Assured Destruction)', 'Zero Option', 'First Strike Policy', 'Brinkmanship'],
      correctOptionIndex: 0,
      explanation: 'MAD menjamin pembalasan total menahan kedua adidaya menekan tombol nuklir.',
    ),
    QuestionItem(
      id: 'hi_032',
      questionText: 'Taktik diplomasi berbahaya mendorong situasi krisis hingga batas jurang peperangan dinamakan:',
      options: ['Brinkmanship', 'Appeasement', 'Deterrence', 'Detente'],
      correctOptionIndex: 0,
      explanation: 'Brinkmanship memandu krisis di tepi jurang konflik (contoh Krisis Rudal Kuba).',
    ),
    QuestionItem(
      id: 'hi_033',
      questionText: 'Masa pereda tegangan dan pelonggaran hubungan antar dua negara adidaya dinamakan periode:',
      options: ['Detente', 'Perang Dingin', 'Eskalasi', 'Embargo'],
      correctOptionIndex: 0,
      explanation: 'Detente terjadi di era 1970-an meredakan krisis AS-Soviet.',
    ),
    QuestionItem(
      id: 'hi_034',
      questionText: 'Kebijakan konsesi konsolidasi تنازل mengalah pada tuntutan agresor demi menghindari perang dinamakan:',
      options: ['Appeasement (Kebijakan Kompromi Pasif)', 'Deterrence', 'Containment', 'Isolationism'],
      correctOptionIndex: 0,
      explanation: 'Appeasement dipraktikkan Inggris pada Hitler di Perjanjian Munich 1938.',
    ),
    QuestionItem(
      id: 'hi_035',
      questionText: 'Strategi AS membendung perluasan pengaruh pengarah ideologi komunisme Soviet dinamakan strategi:',
      options: ['Containment Policy (Doktrin Truman)', 'Rollback', 'Marshall Plan', 'Open Door'],
      correctOptionIndex: 0,
      explanation: 'Containment Policy (George Kennan) membendung expansi Blok Timur.',
    ),
    QuestionItem(
      id: 'hi_036',
      questionText: 'Program bantuan modal ekonomi AS untuk membangun kembali Eropa Barat pasca Perang Dunia II dinamakan:',
      options: ['Marshall Plan', 'Truman Doctrine', 'Dawes Plan', 'Point Four'],
      correctOptionIndex: 0,
      explanation: 'Marshall Plan menyalurkan miliaran dolar membangun kembali eropa barat.',
    ),
    QuestionItem(
      id: 'hi_037',
      questionText: 'Diplomasi formal resmi yang dilakukan oleh pejabat pemerintah dinamakan diplomasi:',
      options: ['Track 1 Diplomacy', 'Track 2 Diplomacy', 'Track 3 Diplomacy', 'Back-channel'],
      correctOptionIndex: 0,
      explanation: 'Track 1 Diplomacy melibatkan diplomat resmi pemerintah.',
    ),
    QuestionItem(
      id: 'hi_038',
      questionText: 'Diplomasi tidak resmi yang melibatkan akademisi, LSM, dan tokoh masyarakat dinamakan:',
      options: ['Track 2 Diplomacy', 'Track 1 Diplomacy', 'Gunboat Diplomacy', 'Public Diplomacy'],
      correctOptionIndex: 0,
      explanation: 'Track 2 Diplomacy memfasilitasi dialog informal jalur non-pemerintah.',
    ),
    QuestionItem(
      id: 'hi_039',
      questionText: 'Diplomasi menggunakan ancaman unjuk kekuatan armada militer lautan dinamakan:',
      options: ['Gunboat Diplomacy (Diplomasi Kapal Perang)', 'Public Diplomacy', 'Ping-pong Diplomacy', 'Panda Diplomacy'],
      correctOptionIndex: 0,
      explanation: 'Gunboat Diplomacy menggertak lawan dengan kehadiran kapal perang.',
    ),
    QuestionItem(
      id: 'hi_040',
      questionText: 'Istilah "Ping-pong Diplomacy" mengacu pada awal pemulihan hubungan diplomasi pada tahun 1971 antara:',
      options: ['Amerika Serikat dan Tiongkok', 'AS dan Uni Soviet', 'Korea Utara dan Korea Selatan', 'Inggris dan Argentina'],
      correctOptionIndex: 0,
      explanation: 'Ping-pong Diplomacy membuka jalan kunjungan Presiden Nixon ke Beijing.',
    ),
    QuestionItem(
      id: 'hi_041',
      questionText: 'Penggunaan diplomasi publik Tiongkok dengan meminjamkan hewan panda ke negara mitra dinamakan:',
      options: ['Panda Diplomacy', 'Soft Diplomacy', 'Cultural Exchange', 'Green Diplomacy'],
      correctOptionIndex: 0,
      explanation: 'Panda Diplomacy meminjamkan panda sebagai simbol persahabatan kebudayaan.',
    ),
    QuestionItem(
      id: 'hi_042',
      questionText: 'Perjanjian iklim global tahun 2015 untuk menahan kenaikan suhu bumi di bawah 2 derajat Celsius dinamakan:',
      options: ['Paris Agreement (Persetujuan Paris)', 'Kyoto Protocol', 'Montreal Protocol', 'COP26'],
      correctOptionIndex: 0,
      explanation: 'Paris Agreement (COP21) mengikat komitmen pengurangan emisi karbon.',
    ),
    QuestionItem(
      id: 'hi_043',
      questionText: 'Protokol iklim 1997 yang mewajibkan negara maju menurunkan emisi gas rumah kaca dinamakan:',
      options: ['Protokol Kyoto', 'Paris Agreement', 'Protokol Montreal', 'Agenda 21'],
      correctOptionIndex: 0,
      explanation: 'Protokol Kyoto mengikat pengurangan emisi karbon industri.',
    ),
    QuestionItem(
      id: 'hi_044',
      questionText: 'Protokol 1987 yang berhasil melarang penggunaan zat bahan kimia perusak lapisan ozon (CFC) dinamakan:',
      options: ['Protokol Montreal', 'Protokol Kyoto', 'Basle Convention', 'Ramsar Convention'],
      correctOptionIndex: 0,
      explanation: 'Protokol Montreal sukses menghapus produksi chlorofluorocarbons (CFC).',
    ),
    QuestionItem(
      id: 'hi_045',
      questionText: 'Forum kerja sama ekonomi 21 negara anggota di lingkar Samudra Pasifik dinamakan:',
      options: ['APEC (Asia-Pacific Economic Cooperation)', 'ASEAN', 'ARF', 'CPTPP'],
      correctOptionIndex: 0,
      explanation: 'APEC mempromosikan perdagangan bebas di lingkar Pasifik.',
    ),
    QuestionItem(
      id: 'hi_046',
      questionText: 'Kelompok kerja sama ekonomi utama yang memadukan 19 negara ekonomi terbesar ditambah Uni Eropa dinamakan:',
      options: ['G20 (Group of Twenty)', 'G7', 'BRICS', 'G77'],
      correctOptionIndex: 0,
      explanation: 'G20 mewakili 85% PDB dunia dan 75% perdagangan global.',
    ),
    QuestionItem(
      id: 'hi_047',
      questionText: 'Kelompok 7 negara maju ekonomi utama (AS, Inggris, Prancis, Jerman, Italia, Kanada, Jepang) dinamakan:',
      options: ['G7 (Group of Seven)', 'G8', 'G20', 'OECD'],
      correctOptionIndex: 0,
      explanation: 'G7 mengoordinasikan kebijakan ekonomi negara maju.',
    ),
    QuestionItem(
      id: 'hi_048',
      questionText: 'Blok ekonomi berkembang pendiri (Brazil, Rusia, India, Tiongkok, Afrika Selatan) dinamakan:',
      options: ['BRICS', 'MINT', 'BASIC', 'Next Eleven'],
      correctOptionIndex: 0,
      explanation: 'BRICS mewakili kekuatan pasar berkembang tandingan Barat.',
    ),
    QuestionItem(
      id: 'hi_049',
      questionText: 'Organisasi negara-negara pengekspor minyak bumi terbesar dunia adalah:',
      options: ['OPEC (Organization of the Petroleum Exporting Countries)', 'IEA', 'APEC', 'OECD'],
      correctOptionIndex: 0,
      explanation: 'OPEC mengatur kuota kuantitas produksi minyak dunia.',
    ),
    QuestionItem(
      id: 'hi_050',
      questionText: 'Konsep dalam HI yang menyatakan bahwa negara-negara demokrasi hampir tidak pernah saling berperang dinamakan:',
      options: ['Democratic Peace Theory (Teori Perdamaian Demokrasi)', 'Liberal Peace', 'Kantian Peace', 'Commercial Peace'],
      correctOptionIndex: 0,
      explanation: 'Democratic Peace Theory (Michael Doyle / Kant) mengklaim sesama demokrasi cenderung damai.',
    ),
    QuestionItem(
      id: 'hi_051',
      questionText: 'Teori Ketergantungan (Dependency Theory) menyatakan bahwa kemiskinan negara berkembang (Periferi) disebabkan oleh:',
      options: ['Eksploitasi dan struktur ketimpangan oleh negara maju (Pusat / Core)', 'Kebodohan', 'Kurangnya modal', 'Perang saudara'],
      correctOptionIndex: 0,
      explanation: 'Dependency Theory (Prebisch, Frank) mengkritik struktur kapitalisme global yang menguntungkan negara Core.',
    ),
    QuestionItem(
      id: 'hi_052',
      questionText: 'Teori Sistem Dunia (World-Systems Theory) yang membagi dunia menjadi Core, Semi-Periphery, dan Periphery dirumuskan oleh:',
      options: ['Immanuel Wallerstein', 'Raul Prebisch', 'Andre Gunder Frank', 'Samir Amin'],
      correctOptionIndex: 0,
      explanation: 'Wallerstein membagi hirarki ekonomi kapitalis dunia.',
    ),
    QuestionItem(
      id: 'hi_053',
      questionText: 'Buku terkenal Samuel P. Huntington yang memprediksi konflik pasca Perang Dingin berbasis perbedaan peradaban agama dinamakan:',
      options: ['The Clash of Civilizations (Benturan Peradaban)', 'The End of History', 'The World is Flat', 'Soft Power'],
      correctOptionIndex: 0,
      explanation: 'Huntington memprediksi benturan peradaban budaya/agama menggantikan konflik ideologi.',
    ),
    QuestionItem(
      id: 'hi_054',
      questionText: 'Buku Francis Fukuyama yang menyatakan bahwa demokrasi liberal adalah bentuk akhir dari pemerintahan manusia dinamakan:',
      options: ['The End of History and the Last Man', 'The Clash of Civilizations', 'Tragedy of Great Power Politics', 'Neorealism'],
      correctOptionIndex: 0,
      explanation: 'Fukuyama memprediksi kemenangan mutlak demokrasi liberal pasca jatuhnya Uni Soviet.',
    ),
    QuestionItem(
      id: 'hi_055',
      questionText: 'Strategi prakarsa infrastruktur sabuk ekonomi global yang dicanangkan Tiongkok dinamakan:',
      options: ['BRI (Belt and Road Initiative / Jalur Sutra Baru)', 'Made in China 2025', 'String of Pearls', 'Go Out Policy'],
      correctOptionIndex: 0,
      explanation: 'BRI membiayai konektivitas pelabuhan dan jalan kereta lintas benua.',
    ),
    QuestionItem(
      id: 'hi_056',
      questionText: 'Krisis terusan laut tahun 1956 di Mesir yang melibatkan Inggris, Prancis, dan Israel dinamakan:',
      options: ['Krisis Terusan Suez', 'Krisis Selat Malaka', 'Krisis Teluk', 'Krisis Bab-el-Mandeb'],
      correctOptionIndex: 0,
      explanation: 'Krisis Suez memicu nasionalisasi terusan suez oleh Gamal Abdel Nasser.',
    ),
    QuestionItem(
      id: 'hi_057',
      questionText: 'Krisis senjata nuklir tahun 1962 yang hampir memicu perang dunia ketiga antara AS dan Uni Soviet dinamakan:',
      options: ['Krisis Rudal Kuba (Cuban Missile Crisis)', 'Krisis Berlin', 'Krisis Selat Taiwan', 'Krisis Korea'],
      correctOptionIndex: 0,
      explanation: 'Krisis Rudal Kuba dipicu penempatan rudal nuklir Soviet di Kuba.',
    ),
    QuestionItem(
      id: 'hi_058',
      questionText: 'Konflik perang antara Argentina dan Inggris pada tahun 1982 memperebutkan kepulauan di Samudra Atlantik dinamakan:',
      options: ['Perang Malvinas (Falklands War)', 'Perang Grenada', 'Perang Chaco', 'Perang Terusan'],
      correctOptionIndex: 0,
      explanation: 'Perang Falklands merebutkan kepulauan Malvinas.',
    ),
    QuestionItem(
      id: 'hi_059',
      questionText: 'Invasi AS ke Irak pada tahun 2003 didasari oleh klaim intelijen (yang belakangan tak terbukti) mengenai kepemilikan:',
      options: ['Senjata Pemusnah Massal (WMD / Weapons of Mass Destruction)', 'Rudal Balistik Antarbenua', 'Pabrik Nuklir', 'Laboratorium Virus'],
      correctOptionIndex: 0,
      explanation: 'Klaim WMD Irak menjadi dalih perang invasi AS 2003.',
    ),
    QuestionItem(
      id: 'hi_060',
      questionText: 'Prinsip normatif global PBB tahun 2005 bahwa masyarakat internasional berhak mengintervensi jika suatu negara gagal melindungi warganya dari genosida dinamakan:',
      options: ['R2P (Responsibility to Protect)', 'Humanitarian Intervention', 'Right of Self-Defense', 'Just War Theory'],
      correctOptionIndex: 0,
      explanation: 'R2P mewajibkan intervensi kemanusiaan saat terjadi kekejaman massal.',
    ),
    QuestionItem(
      id: 'hi_061',
      questionText: 'Doktrin Perang Adil (Just War Theory) mensyaratkan dua dimensi yaitu jus ad bellum (hak berperang) dan:',
      options: ['Jus in bello (etika tata cara bertempur)', 'Jus post bellum', 'Jus cogens', 'Jus soli'],
      correctOptionIndex: 0,
      explanation: 'Jus in bello mengatur etika pembatasan target sipil selama pertempuran.',
    ),
    QuestionItem(
      id: 'hi_062',
      questionText: 'Konvensi internasional yang mengatur perlindungan korban perang, tawanan perang, dan warga sipil dinamakan:',
      options: ['Konvensi Jenewa 1949 (Geneva Conventions)', 'Konvensi Den Haag', 'Konvensi Wina', 'Konvensi Roma'],
      correctOptionIndex: 0,
      explanation: 'Konvensi Jenewa membatasi kekejaman hukum humaniter internasional.',
    ),
    QuestionItem(
      id: 'hi_063',
      questionText: 'Badan PBB yang khusus mengurusi perlindungan pengungsi lintas negara adalah:',
      options: ['UNHCR (United Nations High Commissioner for Refugees)', 'UNICEF', 'UNESCO', 'UNDP'],
      correctOptionIndex: 0,
      explanation: 'UNHCR memberikan perlindungan dan bantuan penanganan pengungsi.',
    ),
    QuestionItem(
      id: 'hi_064',
      questionText: 'Badan PBB yang berfokus mendanai program anak-anak dan ibu di negara berkembang adalah:',
      options: ['UNICEF', 'UNHCR', 'UNFPA', 'WFP'],
      correctOptionIndex: 0,
      explanation: 'UNICEF mengurusi dana anak-anak PBB.',
    ),
    QuestionItem(
      id: 'hi_065',
      questionText: 'Organisasi Internasional yang membidangi sains, pendidikan, dan warisan budaya dunia adalah:',
      options: ['UNESCO', 'UNICEF', 'WHO', 'UNIDO'],
      correctOptionIndex: 0,
      explanation: 'UNESCO mendaftarkan situs Warisan Dunia (World Heritage).',
    ),
    QuestionItem(
      id: 'hi_066',
      questionText: 'Sengketa wilayah laut di Asia Tenggara atas sembilan garis putus-putus (Nine-Dash Line) melibatkan Tiongkok di kawasan:',
      options: ['Laut Tiongkok Selatan (South China Sea)', 'Laut Jawa', 'Laut Natuna Utara', 'Laut Andaman'],
      correctOptionIndex: 0,
      explanation: 'Klaim Nine-Dash Line memicu sengketa klaim maritim di Laut Tiongkok Selatan.',
    ),
    QuestionItem(
      id: 'hi_067',
      questionText: 'Sengketa perebutan wilayah Kashmir melibatkan konflik persenjataan dua negara pemilik nuklir yaitu:',
      options: ['India dan Pakistan', 'India dan Tiongkok', 'Pakistan dan Afganistan', 'Iran dan Irak'],
      correctOptionIndex: 0,
      explanation: 'Kashmir menjadi pemicu perang perbatasan India-Pakistan.',
    ),
    QuestionItem(
      id: 'hi_068',
      questionText: 'Perjanjian perdamaian bersejarah tahun 1978 antara Mesir dan Israel yang difasilitasi AS di bawah Presiden Jimmy Carter dinamakan:',
      options: ['Camp David Accords', 'Oslo Accords', 'Abraham Accords', 'Madrid Conference'],
      correctOptionIndex: 0,
      explanation: 'Camp David Accords normalisasi hubungan Mesir-Israel.',
    ),
    QuestionItem(
      id: 'hi_069',
      questionText: 'Perjanjian perdamaian tahun 1993 antara Palestina (PLO) dan Israel yang memberikan kewenangan otoritas terbatas di Tepi Barat dinamakan:',
      options: ['Oslo Accords (Persetujuan Oslo)', 'Camp David', 'Wye River Agreement', 'Abraham Accords'],
      correctOptionIndex: 0,
      explanation: 'Perjanjian Oslo ditandatangani Yasser Arafat dan Yitzhak Rabin.',
    ),
    QuestionItem(
      id: 'hi_070',
      questionText: 'Kebijakan reformasi keterbukaan politik (Glasnost) dan restrukturisasi ekonomi (Perestroika) di Uni Soviet dikemukakan oleh:',
      options: ['Mikhail Gorbachev', 'Nikita Khrushchev', 'Leonid Brezhnev', 'Boris Yeltsin'],
      correctOptionIndex: 0,
      explanation: 'Glasnost & Perestroika memicu runtuhnya Uni Soviet pada 1991.',
    ),
    QuestionItem(
      id: 'hi_071',
      questionText: 'Tembok yang menjadi simbol pemisah fisik perbatasan Blok Barat dan Blok Timur di Jerman runtuh pada tahun:',
      options: ['1989', '1991', '1975', '1985'],
      correctOptionIndex: 0,
      explanation: 'Runtuhnya Tembok Berlin November 1989 menandai berakhirnya Perang Dingin.',
    ),
    QuestionItem(
      id: 'hi_072',
      questionText: 'Uni Soviet secara resmi dibubarkan dan runtuh pada bulan Desember tahun:',
      options: ['1991', '1989', '1993', '1990'],
      correctOptionIndex: 0,
      explanation: 'Uni Soviet runtuh 25 Desember 1991 terpecah menjadi 15 negara merdeka.',
    ),
    QuestionItem(
      id: 'hi_073',
      questionText: 'Organisasi integrasi kawasan Uni Eropa (European Union) didirikan melalui Traktat Maastricht pada tahun:',
      options: ['1992', '1957', '1973', '2000'],
      correctOptionIndex: 0,
      explanation: 'Traktat Maastricht 1992 meresmikan pembentukan Uni Eropa dan mata uang Euro.',
    ),
    QuestionItem(
      id: 'hi_074',
      questionText: 'Mata uang tunggal resmi yang digunakan oleh mayoritas negara anggota Zona Euro dinamakan:',
      options: ['Euro', 'Pound sterling', 'Franc', 'Krona'],
      correctOptionIndex: 0,
      explanation: 'Euro diluncurkan sebagai mata uang tunggal transaksi Uni Eropa.',
    ),
    QuestionItem(
      id: 'hi_075',
      questionText: 'Peristiwa keluarnya Britania Raya (Inggris) secara resmi dari keanggotaan Uni Eropa dikenal dengan istilah:',
      options: ['Brexit (British Exit)', 'Grexit', 'Frexit', 'UK-Out'],
      correctOptionIndex: 0,
      explanation: 'Referendum Brexit 2016 memutuskan Inggris keluar dari Uni Eropa.',
    ),
    QuestionItem(
      id: 'hi_076',
      questionText: 'Kawasan bebas visa perjalanan antar 27 negara Eropa dinamakan Area:',
      options: ['Schengen Area (Zona Schengen)', 'Eurozone', 'Benelux', 'EEA'],
      correctOptionIndex: 0,
      explanation: 'Perjanjian Schengen menghapus paspor perbatasan antarnegara anggota.',
    ),
    QuestionItem(
      id: 'hi_077',
      questionText: 'Perjanjian Perdagangan Bebas Amerika Utara antara AS, Kanada, dan Meksiko dikenal dengan nama:',
      options: ['NAFTA (sekarang USMCA)', 'MERCOSUR', 'CAFTA', 'FTAA'],
      correctOptionIndex: 0,
      explanation: 'NAFTA mengintegrasikan pasar kawasan Amerika Utara.',
    ),
    QuestionItem(
      id: 'hi_078',
      questionText: 'Blok pasar bebas kawasan Amerika Selatan yang beranggotakan Argentina, Brazil, Paraguay, dan Uruguay adalah:',
      options: ['MERCOSUR', 'ALBA', 'CAN', 'CELAC'],
      correctOptionIndex: 0,
      explanation: 'MERCOSUR adalah aliansi integrasi ekonomi Amerika Selatan.',
    ),
    QuestionItem(
      id: 'hi_079',
      questionText: 'Organisasi persatuan kawasan 55 negara di benua Afrika dinamakan:',
      options: ['Uni Afrika (African Union / AU)', 'OAU', 'ECOWAS', 'SADC'],
      correctOptionIndex: 0,
      explanation: 'Uni Afrika mempromosikan integrasi dan keamanan benua Afrika.',
    ),
    QuestionItem(
      id: 'hi_080',
      questionText: 'Organisasi kerja sama regional 22 negara penutur bahasa Arab dinamakan:',
      options: ['Liga Arab (Arab League)', 'OKI', 'GCC', 'OPEC'],
      correctOptionIndex: 0,
      explanation: 'Liga Arab dibentuk di Kairo 1945.',
    ),
    QuestionItem(
      id: 'hi_081',
      questionText: 'Organisasi Kerja Sama Islam yang menghimpun 57 negara berpenduduk mayoritas Muslim berkedudukan di Jeddah adalah:',
      options: ['OKI (Organization of Islamic Cooperation)', 'Liga Arab', 'ISESCO', 'IDB'],
      correctOptionIndex: 0,
      explanation: 'OKI didirikan di Rabat 1969 memperjuangkan kepentingan solidaritas dunia Islam.',
    ),
    QuestionItem(
      id: 'hi_082',
      questionText: 'Fenomena penyebaran keterkaitan jaringan ekonomi, budaya, dan teknologi secara global dinamakan:',
      options: ['Globalisasi', 'Regionalisme', 'Nasionalisme', 'Proteksionisme'],
      correctOptionIndex: 0,
      explanation: 'Globalisasi mengikis batasan sekat antarnegara.',
    ),
    QuestionItem(
      id: 'hi_083',
      questionText: 'Fenomena penguatan kerja sama terintegrasi dalam blok kawasan regional geografis tertentu dinamakan:',
      options: ['Regionalisme', 'Globalisasi', 'Multilateralisme', 'Bilateralisme'],
      correctOptionIndex: 0,
      explanation: 'Regionalisme melembagakan integrasi regional (seperti ASEAN dan EU).',
    ),
    QuestionItem(
      id: 'hi_084',
      questionText: 'Hubungan perundingan diplomasi yang melibatkan dua negara saja dinamakan hubungan:',
      options: ['Bilateral', 'Multilateral', 'Trilateral', 'Unilateral'],
      correctOptionIndex: 0,
      explanation: 'Bilateral mengacu pada aliansi antar dua negara.',
    ),
    QuestionItem(
      id: 'hi_085',
      questionText: 'Hubungan diplomasi kerja sama yang melibatkan tiga negara atau lebih dinamakan hubungan:',
      options: ['Multilateral', 'Bilateral', 'Dualisme', 'Unilateral'],
      correctOptionIndex: 0,
      explanation: 'Multilateralisme mengoordinasikan diplomasi forum bersama.',
    ),
    QuestionItem(
      id: 'hi_086',
      questionText: 'Tindakan sepihak satu negara tanpa persetujuan atau kompromi dengan negara lain dinamakan tindakan:',
      options: ['Unilateral (Unilateralisme)', 'Bilateral', 'Multilateral', 'Netral'],
      correctOptionIndex: 0,
      explanation: 'Tindakan Unilateral dilakukan sendiri tanpa dukungan forum kolektif.',
    ),
    QuestionItem(
      id: 'hi_087',
      questionText: 'Tindakan embargo penghentian atau pembatasan perdagangan terhadap negara target dinamakan:',
      options: ['Sanksi Ekonomi (Economic Sanctions)', 'Intervensi', 'Boikot Budaya', 'Tarif'],
      correctOptionIndex: 0,
      explanation: 'Sanksi ekonomi menekan kepatuhan suatu negara melalui blokade keuangan/perdagangan.',
    ),
    QuestionItem(
      id: 'hi_088',
      questionText: 'Pendekatan keamanan nasional yang berfokus tidak hanya pada militer negara melainkan perlindungan individu warga dari kemiskinan dan kelaparan dinamakan:',
      options: ['Human Security (Keamanan Manusia)', 'National Security', 'State Security', 'Collective Security'],
      correctOptionIndex: 0,
      explanation: 'Human Security (UNDP 1994) mencakup bebas dari rasa takut (freedom from fear) dan bebas dari kekurangan (freedom from want).',
    ),
    QuestionItem(
      id: 'hi_089',
      questionText: 'Ancaman keamanan non-tradisional yang melampaui batas batas wilayah negara (seperti terorisme, cybercrime, pandemi) dinamakan:',
      options: ['Transnational Threats (Ancaman Transnasional)', 'Conventional War', 'Interstate Conflict', 'Territorial Dispute'],
      correctOptionIndex: 0,
      explanation: 'Ancaman transnasional memerlukan kerja sama penanganan lintas batas negara.',
    ),
    QuestionItem(
      id: 'hi_090',
      questionText: 'Keluarnya keputusan hak uji Arbitrase Permanen (PCA) tahun 2016 membatalkan klaim Nine-Dash Line Tiongkok diajukan oleh negara:',
      options: ['Filipina', 'Vietnam', 'Indonesia', 'Malaysia'],
      correctOptionIndex: 0,
      explanation: 'Filipina memenangkan gugatan arbitrase hukum laut UNCLOS melawan klaim Tiongkok.',
    ),
    QuestionItem(
      id: 'hi_091',
      questionText: 'Fenomena perang generasi baru yang memadukan militer konvensional, serangan siber, dan propaganda disinformasi dinamakan:',
      options: ['Perang Hibrida (Hybrid Warfare)', 'Perang Dingin', 'Perang Total', 'Perang Gerilya'],
      correctOptionIndex: 0,
      explanation: 'Perang Hibrida mengombinasikan taktik militer terstruktur dengan kejahatan siber dan pertempuran opini.',
    ),
    QuestionItem(
      id: 'hi_092',
      questionText: 'Perang terselubung menggunakan pihak ketiga atau kelompok pemberontak untuk mewakili kepentingan negara besar dinamakan:',
      options: ['Perang Veksa / Proxy War', 'Perang Saudara', 'Perang Terbuka', 'Perang Total'],
      correctOptionIndex: 0,
      explanation: 'Proxy War menghindari bentrokan militer langsung antar dua adidaya.',
    ),
    QuestionItem(
      id: 'hi_093',
      questionText: 'Istilah "Jalur Sutra Maritim" abad ke-21 mengacu pada konektivitas perdagangan laut yang dikembangkan oleh:',
      options: ['Tiongkok', 'India', 'Jepang', 'Amerika Serikat'],
      correctOptionIndex: 0,
      explanation: 'Jalur Sutra Maritim adalah komponen maritim program BRI Tiongkok.',
    ),
    QuestionItem(
      id: 'hi_094',
      questionText: 'Kerja sama empat negara (AS, Jepang, India, Australia) di kawasan Indo-Pasifik dikenal dengan istilah:',
      options: ['QUAD (Quadrilateral Security Dialogue)', 'AUKUS', 'ANZUS', 'APEC'],
      correctOptionIndex: 0,
      explanation: 'QUAD mengoordinasikan dialog keamanan 4 negara Indo-Pasifik.',
    ),
    QuestionItem(
      id: 'hi_095',
      questionText: 'Pakta keamanan trilateral tahun 2021 antara Australia, Inggris, dan AS untuk penyediaan kapal selam nuklir dinamakan:',
      options: ['AUKUS', 'QUAD', 'ANZUS', 'FIVE EYES'],
      correctOptionIndex: 0,
      explanation: 'AUKUS memfasilitasi akuisisi kapal selam bertenaga nuklir Australia.',
    ),
    QuestionItem(
      id: 'hi_096',
      questionText: 'Aliansi intelijen lima negara penutur bahasa Inggris (AS, Inggris, Kanada, Australia, Selandia Baru) dinamakan:',
      options: ['Five Eyes (FVEY)', 'Echelon', 'NATO', 'ANZUS'],
      correctOptionIndex: 0,
      explanation: 'Five Eyes adalah jejaring berbagi informasi intelijen rahasia terkuat.',
    ),
    QuestionItem(
      id: 'hi_097',
      questionText: 'Perjanjian perbatasan garis khayal yang membagi wilayah dunia antara Spanyol dan Portugal pada tahun 1494 dinamakan:',
      options: ['Perjanjian Tordesillas', 'Perjanjian Zaragoza', 'Perjanjian Paris', 'Perjanjian Utrecht'],
      correctOptionIndex: 0,
      explanation: 'Perjanjian Tordesillas membagi bumi penjelajahan Spanyol dan Portugal.',
    ),
    QuestionItem(
      id: 'hi_098',
      questionText: 'Studi diplomasi yang berfokus pada pencegahan konflik dan pembangunan perdamaian dinamakan:',
      options: ['Peacekeeping & Peacebuilding', 'War Studies', 'Strategic Studies', 'Geopolitics'],
      correctOptionIndex: 0,
      explanation: 'Peacekeeping (mencegah perang) & Peacebuilding (merekonstruksi kedamaian).',
    ),
    QuestionItem(
      id: 'hi_099',
      questionText: 'Pasukan perdamaian helm biru PBB dikenal sebagai pasukan:',
      options: ['UN Peacekeepers (Blue Helmets)', 'NATO Troops', 'UN Security Force', 'Green Berets'],
      correctOptionIndex: 0,
      explanation: 'Pasukan Baret/Helm Biru PBB dikirim di bawah mandat DK PBB.',
    ),
    QuestionItem(
      id: 'hi_100',
      questionText: 'Peran diplomasi Indonesia yang terkenal sebagai negara penengah jembatan perdamaian dinamakan:',
      options: ['Bridge Builder / Honest Broker', 'Hegemon', 'Agresor', 'Isolasionis'],
      correctOptionIndex: 0,
      explanation: 'Indonesia sering menjadi perantara jujur (Honest Broker) jembatan perdamaian konflik kawasan.',
    ),
  ];
}
