import '../tes_seleksi_model.dart';

List<QuestionItem> getPsikologiQuestions() {
  return const [
    QuestionItem(
      id: 'psi_001',
      questionText: 'Bapak Psikologi Modern yang mendirikan laboratorium psikologi eksperimental pertama di Leipzig (1879) adalah:',
      options: ['Wilhelm Wundt', 'Sigmund Freud', 'William James', 'Ivan Pavlov'],
      correctOptionIndex: 0,
      explanation: 'Wilhelm Wundt mendirikan laboratorium psikologi pertama pada tahun 1879 di Leipzig, Jerman.',
    ),
    QuestionItem(
      id: 'psi_002',
      questionText: 'Aliran psikologi yang dipelopori Sigmund Freud yang menyoroti peran alam bawah sadar (unconscious mind) dinamakan:',
      options: ['Psikoanalisis', 'Behaviorisme', 'Humanistik', 'Kognitivisme'],
      correctOptionIndex: 0,
      explanation: 'Psikoanalisis Freud berfokus pada dinamika ketidaksadaran dan dorongan libido.',
    ),
    QuestionItem(
      id: 'psi_003',
      questionText: 'Menurut Freud, struktur kepribadian manusia yang bekerja atas dasar prinsip kesenangan (pleasure principle) adalah:',
      options: ['Id', 'Ego', 'Superego', 'Ideal Ego'],
      correctOptionIndex: 0,
      explanation: 'Id beroperasi secara primitif impulsif mencari kepuasan instingtual instan.',
    ),
    QuestionItem(
      id: 'psi_004',
      questionText: 'Struktur kepribadian menurut Freud yang bertindak atas dasar prinsip realitas (reality principle) adalah:',
      options: ['Ego', 'Id', 'Superego', 'Libido'],
      correctOptionIndex: 0,
      explanation: 'Ego menyeimbangkan dorongan Id dengan tuntutan realitas dunia nyata.',
    ),
    QuestionItem(
      id: 'psi_005',
      questionText: 'Struktur kepribadian Freud yang merepresentasikan nilai moral, etika, dan nurani masayarakat dinamakan:',
      options: ['Superego', 'Ego', 'Id', 'Alter Ego'],
      correctOptionIndex: 0,
      explanation: 'Superego berfungsi sebagai kontrol moral eksternal yang diinternalisasi.',
    ),
    QuestionItem(
      id: 'psi_006',
      questionText: 'Mekanisme pertahanan diri (defense mechanism) di mana individu menekan dorongan tidak menyenangkan ke alam bawah sadar dinamakan:',
      options: ['Represi (Repression)', 'Proyeksi', 'Sublimasi', 'Rasionalisasi'],
      correctOptionIndex: 0,
      explanation: 'Represi mendorong memori traumatik ke luar dari kesadaran.',
    ),
    QuestionItem(
      id: 'psi_007',
      questionText: 'Mekanisme pertahanan diri di mana seseorang melimpahkan impuls negatif pribadi kepada orang lain dinamakan:',
      options: ['Proyeksi (Projection)', 'Pengalihan (Displacement)', 'Regresi', 'Reaksi Formasi'],
      correctOptionIndex: 0,
      explanation: 'Proyeksi memproyeksikan kelemahan/keinginan pribadi seolah milik orang lain.',
    ),
    QuestionItem(
      id: 'psi_008',
      questionText: 'Mekanisme pertahanan diri di mana dorongan naluri seksual/agresif disalurkan ke aktivitas sosial yang produktif dan diterima masyarakat dinamakan:',
      options: ['Sublimasi (Sublimation)', 'Rasionalisasi', 'Represi', 'Denial'],
      correctOptionIndex: 0,
      explanation: 'Sublimasi adalah mekanisme pertahanan paling matang/sehat (seperti menyalurkan agresivitas jadi olahragawan).',
    ),
    QuestionItem(
      id: 'psi_009',
      questionText: 'Mekanisme pertahanan diri di mana individu kembali ke tahap perkembangan emosional kanak-kanak saat tertekan dinamakan:',
      options: ['Regresi (Regression)', 'Fiksasi', 'Kompensasi', 'Sublimasi'],
      correctOptionIndex: 0,
      explanation: 'Regresi adalah perilaku mundur ke tingkat perkembangan emosi yang lebih muda.',
    ),
    QuestionItem(
      id: 'psi_010',
      questionText: 'Aliran psikologi yang menolak analisis alam bawah sadar dan hanya berfokus pada perilaku teramati (observable behavior) dinamakan:',
      options: ['Behaviorisme', 'Psikoanalisis', 'Gestalt', 'Eksistensialisme'],
      correctOptionIndex: 0,
      explanation: 'Behaviorisme (Watson, Skinner, Pavlov) mempelajari respons stimulus luar.',
    ),
    QuestionItem(
      id: 'psi_011',
      questionText: 'Eksperimen kondisioning klasik (Classical Conditioning) memasangkan bunyi bel dengan makanan pada anjing dilakukan oleh:',
      options: ['Ivan Pavlov', 'B.F. Skinner', 'John B. Watson', 'Edward Thorndike'],
      correctOptionIndex: 0,
      explanation: 'Ivan Pavlov menemukan pengondisian klasik refleks bersyarat pada anjing.',
    ),
    QuestionItem(
      id: 'psi_012',
      questionText: 'Dalam pengondisian klasik Pavlov, makanan yang secara alami memicu air liur anjing bertindak sebagai:',
      options: ['Unconditioned Stimulus (UCS)', 'Conditioned Stimulus (CS)', 'Unconditioned Response (UCR)', 'Conditioned Response (CR)'],
      correctOptionIndex: 0,
      explanation: 'UCS (Stimulus Tak Terkondisi) memicu respon alami tanpa latihan.',
    ),
    QuestionItem(
      id: 'psi_013',
      questionText: 'Aliran psikologi kondisioning operan (Operant Conditioning) menggunakan reinforcement dan punishment dipelopori oleh:',
      options: ['B.F. Skinner', 'Ivan Pavlov', 'Albert Bandura', 'Kurt Lewin'],
      correctOptionIndex: 0,
      explanation: 'Skinner mengemukakan penguatan (reinforcement) membentuk frekuensi perilaku.',
    ),
    QuestionItem(
      id: 'psi_014',
      questionText: 'Konsekuensi yang memperkuat dan meningkatkan kemungkinan pengulangan suatu perilaku dinamakan:',
      options: ['Penguatan (Reinforcement)', 'Hukuman (Punishment)', 'Extinction', 'Shaping'],
      correctOptionIndex: 0,
      explanation: 'Reinforcement (positif atau negatif) selalu memperkuat frekuensi perilaku.',
    ),
    QuestionItem(
      id: 'psi_015',
      questionText: 'Penghilangan perilaku secara bertahap akibat tidak lagi diberikannya penguatan reinforcement dinamakan:',
      options: ['Ekstingsi (Extinction / Pemadaman)', 'Habituasi', 'Diskriminasi', 'Generalisasi'],
      correctOptionIndex: 0,
      explanation: 'Extinction terjadi saat respons tidak lagi diikuti reinforcement.',
    ),
    QuestionItem(
      id: 'psi_016',
      questionText: 'Teori Pembelajaran Sosial (Social Learning Theory) yang menekankan belajar melalui observasi dan imitasi model (Bobo Doll Experiment) dipelopori oleh:',
      options: ['Albert Bandura', 'Jean Piaget', 'Lev Vygotsky', 'Carl Rogers'],
      correctOptionIndex: 0,
      explanation: 'Albert Bandura membuktikan pemodelan observational learning anak terhadap perilaku agresif.',
    ),
    QuestionItem(
      id: 'psi_017',
      questionText: 'Aliran Psikologi Humanistik yang mengedepankan potensi diri dan dorongan Aktualisasi Diri dipelopori oleh:',
      options: ['Abraham Maslow dan Carl Rogers', 'Freud dan Jung', 'Watson dan Skinner', 'Piaget dan Vygotsky'],
      correctOptionIndex: 0,
      explanation: 'Humanistik memandang manusia memiliki kehendak bebas dan potensi aktualisasi diri.',
    ),
    QuestionItem(
      id: 'psi_018',
      questionText: 'Puncak tertinggi dari Hirarki Kebutuhan Maslow (Maslow\'s Hierarchy of Needs) adalah kebutuhan:',
      options: ['Aktualisasi Diri (Self-Actualization)', 'Penghargaan (Esteem)', 'Kasih Sayang (Belonging)', 'Keamanan (Safety)'],
      correctOptionIndex: 0,
      explanation: 'Aktualisasi Diri adalah tingkatan puncak pencapaian pemenuhan potensi pribadi.',
    ),
    QuestionItem(
      id: 'psi_019',
      questionText: 'Kebutuhan paling dasar di tingkatan terbabawah Hirarki Maslow yang harus dipenuhi terlebih dahulu adalah kebutuhan:',
      options: ['Fisiologis (Makan, Minum, Tidur)', 'Keamanan', 'Sosial', 'Esteem'],
      correctOptionIndex: 0,
      explanation: 'Kebutuhan Fisiologis mendasari penopang kelangsungan hidup biologis.',
    ),
    QuestionItem(
      id: 'psi_020',
      questionText: 'Konsep Terapi Berpusat pada Klien (Client-Centered Therapy) dan Unconditional Positive Regard dikembangkan oleh:',
      options: ['Carl Rogers', 'Abraham Maslow', 'Fritz Perls', 'Victor Frankl'],
      correctOptionIndex: 0,
      explanation: 'Carl Rogers mengembangkan pendekatan terapi humanistik berpusat pada klien.',
    ),
    QuestionItem(
      id: 'psi_021',
      questionText: 'Pendekatan Logoterapi yang berfokus pada pencarian makna hidup (Man\'s Search for Meaning) dikembangkan oleh psikiatris:',
      options: ['Viktor Frankl', 'Carl Jung', 'Alfred Adler', 'Rollo May'],
      correctOptionIndex: 0,
      explanation: 'Viktor Frankl merumuskan Logoterapi dari pengalamannya selamat di kamp konsentrasi Nazi.',
    ),
    QuestionItem(
      id: 'psi_022',
      questionText: 'Tokoh Psikologi Analitis yang mengemukakan konsep Ketidaksadaran Kolektif (Collective Unconscious) dan Arketipe adalah:',
      options: ['Carl Gustav Jung', 'Sigmund Freud', 'Alfred Adler', 'Karen Horney'],
      correctOptionIndex: 0,
      explanation: 'Carl Jung memisahkan unconscious pribadi dan ketidaksadaran kolektif warisan leluhur manusia.',
    ),
    QuestionItem(
      id: 'psi_023',
      questionText: 'Tokoh Psikologi Individual yang mengemukakan teori tentang Perasaan Inferioritas (Inferiority Complex) dan Striving for Superiority adalah:',
      options: ['Alfred Adler', 'Carl Jung', 'Wilhelm Reich', 'Erich Fromm'],
      correctOptionIndex: 0,
      explanation: 'Alfred Adler memfokuskan dorongan kompensasi atas rasa inferioritas.',
    ),
    QuestionItem(
      id: 'psi_024',
      questionText: 'Teori perkembangan kognitif anak yang membagi tahap sensorimotor hingga operasional formal dikembangkan oleh:',
      options: ['Jean Piaget', 'Lev Vygotsky', 'Erik Erikson', 'Lawrence Kohlberg'],
      correctOptionIndex: 0,
      explanation: 'Piaget merumuskan 4 tahapan kembangan kognitif anak (Sensorimotor, Pra-operasional, Operasional Konkret, Operasional Formal).',
    ),
    QuestionItem(
      id: 'psi_025',
      questionText: 'Tahap perkembangan kognitif Piaget di mana anak berusia 7-11 tahun mampu berpikir logis atas benda konkrit dinamakan:',
      options: ['Tahap Operasional Konkret', 'Tahap Sensorimotor', 'Tahap Pra-operasional', 'Tahap Operasional Formal'],
      correctOptionIndex: 0,
      explanation: 'Operasional Konkret ditandai dengan pemahaman prinsip konservasi volume/jumlah.',
    ),
    QuestionItem(
      id: 'psi_026',
      questionText: 'Kemampuan anak memahami bahwa kuantitas cairan tetap sama meski dipindahkan ke wadah beda bentuk dinamakan:',
      options: ['Konservasi (Conservation)', 'Egosentrisme', 'Centration', 'Object Permanence'],
      correctOptionIndex: 0,
      explanation: 'Prinsip Konservasi dikuasai pada tahap operasional konkret.',
    ),
    QuestionItem(
      id: 'psi_027',
      questionText: 'Pemahaman bayi bahwa benda tetap ada meskipun hilang dari pandangan mata dinamakan:',
      options: ['Object Permanence (Permanensi Objek)', 'Egocentrism', 'Assimilation', 'Accommodation'],
      correctOptionIndex: 0,
      explanation: 'Permanensi Objek berkembang pada tahap akhir Sensorimotorik (sekitar 8 bulan).',
    ),
    QuestionItem(
      id: 'psi_028',
      questionText: 'Teori Perkembangan Sosio-Kultural yang menekankan peran "Zone of Proximal Development" (ZPD) dan Scaffolding dikembangkan oleh:',
      options: ['Lev Vygotsky', 'Jean Piaget', 'Jerome Bruner', 'Albert Bandura'],
      correctOptionIndex: 0,
      explanation: 'Vygotsky menggarisbawahi pengaruh interaksi sosial dan intervensi Scaffolding pada ZPD.',
    ),
    QuestionItem(
      id: 'psi_029',
      questionText: 'Teori Perkembangan Psikososial yang membagi masa hidup manusia ke dalam 8 tahap krisis kembangan dikembangkan oleh:',
      options: ['Erik Erikson', 'Sigmund Freud', 'Gordon Allport', 'Raymond Cattell'],
      correctOptionIndex: 0,
      explanation: 'Erikson merumuskan 8 tahap krisis psikososial dari bayi hingga usia lanjut (seperti Identity vs Role Confusion).',
    ),
    QuestionItem(
      id: 'psi_030',
      questionText: 'Krisis perkembangan psikososial Erikson yang dialami remaja usia sekolah menengah adalah:',
      options: ['Identity vs Role Confusion (Identitas vs Kebingungan Peran)', 'Trust vs Mistrust', 'Autonomy vs Shame', 'Generativity vs Stagnation'],
      correctOptionIndex: 0,
      explanation: 'Masa remaja berjuang menemukan identitas diri yang utuh.',
    ),
    QuestionItem(
      id: 'psi_031',
      questionText: 'Teori Perkembangan Moral anak yang membagi tingkat Pre-konvensional, Konvensional, dan Pasca-konvensional dikembangkan oleh:',
      options: ['Lawrence Kohlberg', 'Carol Gilligan', 'Jean Piaget', 'Erik Erikson'],
      correctOptionIndex: 0,
      explanation: 'Kohlberg menguji dilema moral (Heinz Dilemma) untuk menilai tahap pertimbangan moral.',
    ),
    QuestionItem(
      id: 'psi_032',
      questionText: 'Tingkat penalaran moral Kohlberg di mana seseorang patuh pada aturan semata-mata demi menghindari hukuman atau mencari ganjaran dinamakan:',
      options: ['Pre-Konvensional', 'Konvensional', 'Pasca-Konvensional', 'Otonom'],
      correctOptionIndex: 0,
      explanation: 'Pre-konvensional berorientasi pada kepatuhan hukuman dan ganjaran egois.',
    ),
    QuestionItem(
      id: 'psi_033',
      questionText: 'Aliran psikologi Gestalt memiliki prinsip utama yang menegaskan bahwa:',
      options: ['Keseluruhan lebih besar daripada penjumlahan bagian-bagiannya (The whole is greater than the sum of its parts)', 'Perilaku adalah kumpulan refleks', 'Pikiran bersifat tidak sadar', 'Jiwa adalah tabula rasa'],
      correctOptionIndex: 0,
      explanation: 'Prinsip Gestalt menekankan persepsi pola utuh yang melampaui elemen terpisah.',
    ),
    QuestionItem(
      id: 'psi_034',
      questionText: 'Prinsip organisasi persepsi Gestalt di mana objek-objek yang berdekatan cenderung dikelompokkan bersama dinamakan hukum:',
      options: ['Proximity (Kedekatan)', 'Similarity (Kemiripan)', 'Continuity (Keberlanjutan)', 'Closure (Penutupan)'],
      correctOptionIndex: 0,
      explanation: 'Proximity mengelompokkan elemen berdasar jarak kedekatan fisik visual.',
    ),
    QuestionItem(
      id: 'psi_035',
      questionText: 'Kecenderungan persepsi otak untuk melengkapi pola gambar garis terputus menjadi bentuk utuh dinamakan hukum:',
      options: ['Closure (Penutupan)', 'Proximity', 'Similarity', 'Prägnanz'],
      correctOptionIndex: 0,
      explanation: 'Closure mengisi celah kosong untuk menciptakan sosok Gestalt utuh.',
    ),
    QuestionItem(
      id: 'psi_036',
      questionText: 'Istilah "Tabula Rasa" yang mengibaratkan jiwa bayi lahir seperti kertas putih kosong dikemukakan filosof:',
      options: ['John Locke', 'Rene Descartes', 'Immanuel Kant', 'Aristoteles'],
      correctOptionIndex: 0,
      explanation: 'John Locke mengusung pandangan empirisme kertas kosong Tabula Rasa.',
    ),
    QuestionItem(
      id: 'psi_037',
      questionText: 'Struktur sel saraf otak penyampai sinyal impuls listrik dinamakan:',
      options: ['Neuron', 'Sinapsis', 'Akson', 'Dendrit'],
      correctOptionIndex: 0,
      explanation: 'Neuron adalah unit dasar biologis sistem saraf.',
    ),
    QuestionItem(
      id: 'psi_038',
      questionText: 'Zat kimia penyampai pesan antar ujung sel neuron melintasi celah sinapsis dinamakan:',
      options: ['Neurotransmiter', 'Hormon', 'Enzim', 'Antibodi'],
      correctOptionIndex: 0,
      explanation: 'Neurotransmiter (seperti Dopamin, Serotonin) menyampaikan transmisi kimiawi.',
    ),
    QuestionItem(
      id: 'psi_039',
      questionText: 'Neurotransmiter yang berkaitan erat dengan perasaan senang, sistem ganjaran (reward), dan gerakan motorik adalah:',
      options: ['Dopamin', 'Serotonin', 'GABA', 'Asetilkolin'],
      correctOptionIndex: 0,
      explanation: 'Dopamin mengatur motivasi rasa senang dan kontrol gerakan.',
    ),
    QuestionItem(
      id: 'psi_040',
      questionText: 'Neurotransmiter yang berperan utama memenyesuaikan suasana hati (mood), tidur, dan selera makan adalah:',
      options: ['Serotonin', 'Dopamin', 'Adrenalin', 'Endorfin'],
      correctOptionIndex: 0,
      explanation: 'Defisiensi Serotonin sering dikaitkan dengan gangguan Depresi.',
    ),
    QuestionItem(
      id: 'psi_041',
      questionText: 'Neurotransmiter penghambat utama di otak (inhibitory) yang berfungsi mengurangi kecemasan dan merelaksasi emosi adalah:',
      options: ['GABA (Gamma-Aminobutyric Acid)', 'Glutamat', 'Norepinefrin', 'Dopamin'],
      correctOptionIndex: 0,
      explanation: 'GABA menenangkan aktivitas eksitasi sel saraf otak.',
    ),
    QuestionItem(
      id: 'psi_042',
      questionText: 'Bagian otak besar (Cerebrum) yang bertanggung jawab atas perencanaan, pengambilan keputusan, dan kontrol emosi adalah lobus:',
      options: ['Lobus Frontal', 'Lobus Parietal', 'Lobus Oksipital', 'Lobus Temporal'],
      correctOptionIndex: 0,
      explanation: 'Lobus Frontal mengendalikan fungsi eksekutif mental tertinggi.',
    ),
    QuestionItem(
      id: 'psi_043',
      questionText: 'Bagian otak belakang yang berfokus mengolah rangsangan persepsi visual penglihatan adalah lobus:',
      options: ['Lobus Oksipital', 'Lobus Temporal', 'Lobus Parietal', 'Lobus Frontal'],
      correctOptionIndex: 0,
      explanation: 'Lobus Oksipital mengolah visual sensori mata.',
    ),
    QuestionItem(
      id: 'psi_044',
      questionText: 'Struktur dalam sistem limbik yang memegang peran kunci mengolah ingatan memori jangka panjang adalah:',
      options: ['Hipokampus', 'Amigdala', 'Talamus', 'Hipotalamus'],
      correctOptionIndex: 0,
      explanation: 'Hipokampus vital untuk konsolidasi memori memori jangka panjang.',
    ),
    QuestionItem(
      id: 'psi_045',
      questionText: 'Struktur otak berbentuk almond yang berperan mengolah emosi rasa takut dan respons ancaman adalah:',
      options: ['Amigdala', 'Hipokampus', 'Serebelum', 'Medula'],
      correctOptionIndex: 0,
      explanation: 'Amigdala merespons bahaya dan memicu respons fight-or-flight.',
    ),
    QuestionItem(
      id: 'psi_046',
      questionText: 'Tes inteligensi individual standar buatan Alfred Binet yang dikembangkan Stanford University dinamakan tes:',
      options: ['Stanford-Binet Intelligence Scale', 'WAIS', 'WISC', 'Raven Progressive Matrices'],
      correctOptionIndex: 0,
      explanation: 'Skala Stanford-Binet merintis pengukuran skor IQ (Intelligence Quotient).',
    ),
    QuestionItem(
      id: 'psi_047',
      questionText: 'Formula klasik perhitungan IQ (Intelligence Quotient) menurut William Stern adalah:',
      options: ['IQ = (Usia Mental / Usia Kronologis) x 100', 'IQ = Usia Kronologis x Usia Mental', 'IQ = Skor Mentah / 100', 'IQ = Usia Mental + 100'],
      correctOptionIndex: 0,
      explanation: 'IQ = (MA / CA) * 100.',
    ),
    QuestionItem(
      id: 'psi_048',
      questionText: 'Tes inteligensi khusus orang dewasa yang dikembangkan oleh David Wechsler dikenal sebagai:',
      options: ['WAIS (Wechsler Adult Intelligence Scale)', 'WISC', 'WPPSI', 'CFIT'],
      correctOptionIndex: 0,
      explanation: 'WAIS diukur khusus untuk asesmen inteligensi dewasa.',
    ),
    QuestionItem(
      id: 'psi_049',
      questionText: 'Teori Kecerdasan Majemuk (Multiple Intelligences) yang membagi 8 tipe kecerdasan dikemukakan oleh:',
      options: ['Howard Gardner', 'Robert Sternberg', 'Charles Spearman', 'Daniel Goleman'],
      correctOptionIndex: 0,
      explanation: 'Howard Gardner memecah klaim kecerdasan tunggal menjadi 8 kecerdasan (Linguistik, Musikal, Logis, dsb).',
    ),
    QuestionItem(
      id: 'psi_050',
      questionText: 'Teori Triarkis Kecerdasan (Analitis, Kreatif, Praktis) dikemukakan oleh:',
      options: ['Robert Sternberg', 'Howard Gardner', 'Raymond Cattell', 'Louis Thurstone'],
      correctOptionIndex: 0,
      explanation: 'Sternberg merumuskan Triarchic Theory of Intelligence.',
    ),
    QuestionItem(
      id: 'psi_051',
      questionText: 'Konsep Kecerdasan Emosional (Emotional Intelligence / EQ) yang mencakup kesadaran diri dan empati dipopulerkan oleh:',
      options: ['Daniel Goleman', 'Howard Gardner', 'Carl Rogers', 'Martin Seligman'],
      correctOptionIndex: 0,
      explanation: 'Daniel Goleman mempopulerkan buku Emotional Intelligence.',
    ),
    QuestionItem(
      id: 'psi_052',
      questionText: 'Tes kepribadian proyektif yang menggunakan 10 kartu bercak tinta dinamakan tes:',
      options: ['Rorschach Inkblot Test', 'TAT (Thematic Apperception Test)', 'MMPI', 'MBTI'],
      correctOptionIndex: 0,
      explanation: 'Hermann Rorschach menciptakan tes proyektif bercak tinta.',
    ),
    QuestionItem(
      id: 'psi_053',
      questionText: 'Tes kepribadian proyektif yang menggunakan kartu gambar situasi sosial di mana subjek diminta membuat cerita dinamakan:',
      options: ['TAT (Thematic Apperception Test)', 'Rorschach', 'Baum Test', 'Draw-a-Person'],
      correctOptionIndex: 0,
      explanation: 'TAT dikembangkan oleh Henry Murray untuk merekam narasi fantasi proyektif.',
    ),
    QuestionItem(
      id: 'psi_054',
      questionText: 'Inventori kepribadian objektif inventori dengan ratusan pertanyaan benar/salah untuk mendeteksi psikopatologi adalah:',
      options: ['MMPI (Minnesota Multiphasic Personality Inventory)', 'MBTI', '16PF', 'NEO-PI'],
      correctOptionIndex: 0,
      explanation: 'MMPI adalah alat ukur kepribadian klinis baku paling luas digunakan.',
    ),
    QuestionItem(
      id: 'psi_055',
      questionText: 'Model Lima Besar Faktor Kepribadian (Big Five Personality Traits / OCEAN) terdiri dari dimensi:',
      options: ['Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism', 'Optimism, Creativity, Empathy, Adaptability, Nerve', 'Outgoing, Calm, Emotional, Active, Natural', 'Organization, Caring, Energetic, Analytical, Neutral'],
      correctOptionIndex: 0,
      explanation: 'Akronim OCEAN merangkum 5 kepribadian Big Five.',
    ),
    QuestionItem(
      id: 'psi_056',
      questionText: 'Karakteristik individu Big Five yang menunjukkan ketelitian, kedisiplinan, dan tanggung jawab kerja adalah:',
      options: ['Conscientiousness', 'Openness', 'Agreeableness', 'Extraversion'],
      correctOptionIndex: 0,
      explanation: 'Conscientiousness mencerminkan ketertiban dan dorongan berprestasi terencana.',
    ),
    QuestionItem(
      id: 'psi_057',
      questionText: 'Dimensi Big Five yang menunjukkan kecenderungan mengalami emosi negatif seperti kecemasan dan ketidakstabilan emosi adalah:',
      options: ['Neuroticism', 'Extraversion', 'Agreeableness', 'Openness'],
      correctOptionIndex: 0,
      explanation: 'Neuroticism tinggi menandakan kecenderungan instabilitas emosional.',
    ),
    QuestionItem(
      id: 'psi_058',
      questionText: 'Fenomena perubahan perilaku seseorang karena mengetahui dirinya sedang diamati dalam penelitian dinamakan:',
      options: ['Hawthorne Effect', 'Placebo Effect', 'Pygmalion Effect', 'Rosenthal Effect'],
      correctOptionIndex: 0,
      explanation: 'Hawthorne Effect meningkatkan kinerja akibat kesadaran diperhatikan peneliti.',
    ),
    QuestionItem(
      id: 'psi_059',
      questionText: 'Fenomena di mana harapan atau keyakinan tinggi atasan/guru meningkatkan kinerja bawahannya dinamakan:',
      options: ['Pygmalion Effect (Rosenthal Effect)', 'Hawthorne Effect', 'Barnum Effect', 'Halo Effect'],
      correctOptionIndex: 0,
      explanation: 'Pygmalion Effect adalah self-fulfilling prophecy atas ekspektasi positif.',
    ),
    QuestionItem(
      id: 'psi_060',
      questionText: 'Kecenderungan manusia percaya bahwa deskripsi kepribadian umum seolah-olah sangat spesifik cocok dengan dirinya dinamakan:',
      options: ['Barnum Effect (Forer Effect)', 'Halo Effect', 'Confirmation Bias', 'Dunning-Kruger Effect'],
      correctOptionIndex: 0,
      explanation: 'Barnum Effect mendasari kepercayaan pada ramalan horoskop/zodiak umum.',
    ),
    QuestionItem(
      id: 'psi_061',
      questionText: 'Bias kognitif di mana kesan positif awal pada satu sifat memengaruhi penilaian menyeluruh terhadap karakter seseorang dinamakan:',
      options: ['Halo Effect', 'Horns Effect', 'Primacy Effect', 'Recency Effect'],
      correctOptionIndex: 0,
      explanation: 'Halo Effect membuat satu kelebihan menutupi impresi sifat lainnya.',
    ),
    QuestionItem(
      id: 'psi_062',
      questionText: 'Bias kognitif di mana orang berpengetahuan rendah cenderung merasa sangat ahli dan percaya diri berlebihan dinamakan:',
      options: ['Dunning-Kruger Effect', 'Imposter Syndrome', 'Confirmation Bias', 'Hindsight Bias'],
      correctOptionIndex: 0,
      explanation: 'Dunning-Kruger terjadi akibat kurangnya metacognition mengevaluasi kelemahan diri.',
    ),
    QuestionItem(
      id: 'psi_063',
      questionText: 'Kondisi psikologis di mana seseorang yang sangat sukses merasa dirinya penipu dan ragu atas pencapaiannya dinamakan:',
      options: ['Imposter Syndrome (Sindrom Imposter)', 'Burnout', 'Dunning-Kruger Effect', 'Anhedonia'],
      correctOptionIndex: 0,
      explanation: 'Imposter Syndrome adalah ketakutan tidak rasional terungkap sebagai pembohong kompetensi.',
    ),
    QuestionItem(
      id: 'psi_064',
      questionText: 'Kondisi kelelahan fisik, mental, dan emosional secara kronis akibat stres pekerjaan yang berkepanjangan dinamakan:',
      options: ['Burnout', 'Depresi', 'PTSD', 'Fatigue'],
      correctOptionIndex: 0,
      explanation: 'Burnout ditandai kelelahan ekstrem, depersonalisasi, dan penurunan efikasi diri.',
    ),
    QuestionItem(
      id: 'psi_065',
      questionText: 'Keadaan ketidaknyamanan mental ketika seseorang memegang dua keyakinan/sikap yang saling bertentangan dinamakan:',
      options: ['Disonansi Kognitif (Cognitive Dissonance)', 'Konsonansi', 'Ambiguitas', 'Kognisi Ganda'],
      correctOptionIndex: 0,
      explanation: 'Leon Festinger merumuskan Disonansi Kognitif yang mendorong individu menyelaraskan sikap.',
    ),
    QuestionItem(
      id: 'psi_066',
      questionText: 'Eksperimen kepatuhan sosial yang meminta subjek memberikan kejutan listrik pada instruksi figur otoritas dilakukan oleh:',
      options: ['Stanley Milgram', 'Philip Zimbardo', 'Solomon Asch', 'Muzafer Sherif'],
      correctOptionIndex: 0,
      explanation: 'Milgram Experiment membuktikan kepatuhan buta manusia terhadap figur otoritas.',
    ),
    QuestionItem(
      id: 'psi_067',
      questionText: 'Eksperimen psikologi sosial konformitas kelompok menggunakan perbandingan panjang garis dilakukan oleh:',
      options: ['Solomon Asch', 'Stanley Milgram', 'Albert Bandura', 'Kurt Lewin'],
      correctOptionIndex: 0,
      explanation: 'Asch Experiment menguji konformitas individu terhadap pendapat salah mayoritas kelompok.',
    ),
    QuestionItem(
      id: 'psi_068',
      questionText: 'Eksperimen penjara buatan (Stanford Prison Experiment) yang menunjukkan dampak peran sosial ekstrem dipimpin oleh:',
      options: ['Philip Zimbardo', 'Stanley Milgram', 'John Watson', 'Martin Seligman'],
      correctOptionIndex: 0,
      explanation: 'Zimbardo memfasilitasi eksperimen penjara Stanford 1971.',
    ),
    QuestionItem(
      id: 'psi_069',
      questionText: 'Fenomena sosial di mana individu enggan menolong korban kejahatan karena merasa tanggung jawab terbagi dengan penonton lain dinamakan:',
      options: ['Bystander Effect (Efek Genovese / Difusi Tanggung Jawab)', 'Social Loafing', 'Groupthink', 'Deindividualisasi'],
      correctOptionIndex: 0,
      explanation: 'Bystander Effect dipicu oleh fenomena Diffusion of Responsibility saat kerumunan ramai.',
    ),
    QuestionItem(
      id: 'psi_070',
      questionText: 'Kecenderungan seseorang mengerahkan usaha lebih sedikit saat bekerja dalam kelompok daripada saat sendiri dinamakan:',
      options: ['Social Loafing (Kemalasan Sosial)', 'Social Facilitation', 'Groupthink', 'Free Riding'],
      correctOptionIndex: 0,
      explanation: 'Social Loafing menurunkan performa individu dalam tugas kelompok kolektif.',
    ),
    QuestionItem(
      id: 'psi_071',
      questionText: 'Kecenderungan kelompok mengambil keputusan buruk demi menjaga keharmonisan dan konsensus tanpa kritik adekuat dinamakan:',
      options: ['Groupthink (Pemikiran Kelompok)', 'Group Polarization', 'Deindividuation', 'Social Loafing'],
      correctOptionIndex: 0,
      explanation: 'Irving Janis merumuskan Groupthink yang menekan suara kritis.',
    ),
    QuestionItem(
      id: 'psi_072',
      questionText: 'Buku panduan diagnostik gangguan jiwa standar internasional terbitan American Psychiatric Association dinamakan:',
      options: ['DSM (Diagnostic and Statistical Manual of Mental Disorders)', 'PPDGJ', 'ICD', 'MMPI'],
      correctOptionIndex: 0,
      explanation: 'DSM (seperti DSM-5) adalah acuan utama klasifikasi klinis gangguan mental.',
    ),
    QuestionItem(
      id: 'psi_073',
      questionText: 'Ketakutan berlebihan dan tidak rasional terhadap situasi sosial atau keramaian terbuka dinamakan:',
      options: ['Agorafobia', 'Klaustrofobia', 'Arakrofobia', 'Sosiofobia'],
      correctOptionIndex: 0,
      explanation: 'Agorafobia memicu kecemasan saat berada di tempat terbuka yang sulit melarikan diri.',
    ),
    QuestionItem(
      id: 'psi_074',
      questionText: 'Gangguan jiwa yang ditandai pikiran obsesif berulang dan tindakan kompulsi ritualistik dinamakan:',
      options: ['OCD (Obsessive-Compulsive Disorder)', 'PTSD', 'ADHD', 'GAD'],
      correctOptionIndex: 0,
      explanation: 'OCD ditandai Obsesi kecemasan dan Kompulsi aksi penawarnya.',
    ),
    QuestionItem(
      id: 'psi_075',
      questionText: 'Gangguan kecemasan yang dipicu oleh pengalaman traumatik hebat (perang, bencana, penganiayaan) dinamakan:',
      options: ['PTSD (Post-Traumatic Stress Disorder)', 'Panic Disorder', 'GAD', 'Phobia'],
      correctOptionIndex: 0,
      explanation: 'PTSD memicu kilas balik (flashback) dan kecemasan tinggi atas trauma masa lalu.',
    ),
    QuestionItem(
      id: 'psi_076',
      questionText: 'Gangguan mood yang ditandai episode Mania (kegembiraan ekstrem) bergantian dengan episode Depresi berat dinamakan:',
      options: ['Gangguan Bipolar', 'Skizofrenia', 'Ditimia', 'SAD'],
      correctOptionIndex: 0,
      explanation: 'Bipolar Disorder memperlihatkan fluktuasi drastis antara fase mania dan depresi.',
    ),
    QuestionItem(
      id: 'psi_077',
      questionText: 'Gangguan psikotik berat yang ditandai halusinasi visual/auditori, delusi (waham), dan disorganisasi berpikir dinamakan:',
      options: ['Skizofrenia', 'Bipolar', 'Autisme', 'Borderline'],
      correctOptionIndex: 0,
      explanation: 'Skizofrenia melibatkan perpecahan hubungan dari realitas (psikosis).',
    ),
    QuestionItem(
      id: 'psi_078',
      questionText: 'Keyakinan salah dan tidak sesuai realitas yang dipertahankan secara kuat meski telah dibantah bukti dinamakan:',
      options: ['Delusi / Waham', 'Halusinasi', 'Ilusi', 'Obsesi'],
      correctOptionIndex: 0,
      explanation: 'Delusi adalah gangguan isi pikiran (seperti waham kebesaran atau waham kejaran).',
    ),
    QuestionItem(
      id: 'psi_079',
      questionText: 'Persepsi sensori tanpa adanya objek rangsangan fisik eksternal nyata dinamakan:',
      options: ['Halusinasi', 'Ilusi', 'Delusi', 'Aura'],
      correctOptionIndex: 0,
      explanation: 'Halusinasi mendengar suara tanpa ada sumber suara nyata.',
    ),
    QuestionItem(
      id: 'psi_080',
      questionText: 'Mispersepsi atau penginterpretasian salah terhadap rangsangan objek fisik nyata yang ada dinamakan:',
      options: ['Ilusi', 'Halusinasi', 'Delusi', 'Deja vu'],
      correctOptionIndex: 0,
      explanation: 'Ilusi adalah pengolahan persepsi yang keliru atas objek nyata (seperti melihat tali sebagai ular).',
    ),
    QuestionItem(
      id: 'psi_081',
      questionText: 'Terapi psikologi Cognitive Behavioral Therapy (CBT) dikembangkan oleh Aaron Beck berfokus mengubah:',
      options: ['Pikiran otomatis negatif dan distorsi kognitif', 'Mimpi alam bawah sadar', 'Struktur otak', 'Diet makanan'],
      correctOptionIndex: 0,
      explanation: 'CBT menyelaraskan restrukturisasi kognitif pikiran negatif untuk merubah emosi.',
    ),
    QuestionItem(
      id: 'psi_082',
      questionText: 'Kondisi pasrah di mana individu berhenti berusaha karena merasa tidak memiliki kontrol atas nasib buruknya dinamakan:',
      options: ['Learned Helplessness (Ketidakberdayaan yang Dipelajari)', 'Locus of Control External', 'Anhedonia', 'Depresi'],
      correctOptionIndex: 0,
      explanation: 'Martin Seligman merumuskan Learned Helplessness pada eksperimen anjing.',
    ),
    QuestionItem(
      id: 'psi_083',
      questionText: 'Keyakinan seseorang bahwa pusat kendali nasib keberhasilannya berada di dalam diri pribadi dinamakan:',
      options: ['Internal Locus of Control', 'External Locus of Control', 'Self-Efficacy', 'Self-Esteem'],
      correctOptionIndex: 0,
      explanation: 'Julian Rotter merumuskan konsep Internal vs External Locus of Control.',
    ),
    QuestionItem(
      id: 'psi_084',
      questionText: 'Keyakinan individu atas kemampuan spesifik dirinya untuk berhasil menyelesaikan suatu tugas dinamakan:',
      options: ['Self-Efficacy (Efikasi Diri)', 'Self-Esteem', 'Self-Concept', 'Self-Image'],
      correctOptionIndex: 0,
      explanation: 'Albert Bandura mendefinisikan Self-Efficacy sebagai rasa percaya atas kapasitas tindakan pribadi.',
    ),
    QuestionItem(
      id: 'psi_085',
      questionText: 'Penilaian evaluatif menyeluruh seseorang mengenai harga diri dan keberhargaan pribadinya dinamakan:',
      options: ['Self-Esteem (Harga Diri)', 'Self-Efficacy', 'Self-Awareness', 'Self-Regulation'],
      correctOptionIndex: 0,
      explanation: 'Self-Esteem mencerminkan rasa menghargai dan menyukai diri sendiri.',
    ),
    QuestionItem(
      id: 'psi_086',
      questionText: 'Kecenderungan seseorang mengingat informasi yang belum selesai dibanding tugas yang sudah selesai dinamakan:',
      options: ['Zeigarnik Effect', 'Ovsiankina Effect', 'Recency Effect', 'Primacy Effect'],
      correctOptionIndex: 0,
      explanation: 'Zeigarnik Effect membuktikan tugas yang interupsi lebih melekat di ingatan.',
    ),
    QuestionItem(
      id: 'psi_078_psi',
      questionText: 'Ketidakmampuan merasakan kenikmatan atau kesenangan pada aktivitas yang sebelumnya disukai dinamakan:',
      options: ['Anhedonia', 'Apatis', 'Avolisi', 'Alexithymia'],
      correctOptionIndex: 0,
      explanation: 'Anhedonia merupakan salah satu gejala inti klinis Depresi.',
    ),
    QuestionItem(
      id: 'psi_088',
      questionText: 'Ketidakmampuan seseorang mengidentifikasi dan mengungkapkan perasaan emosional dengan kata-kata dinamakan:',
      options: ['Alexithymia', 'Aphasia', 'Agnosia', 'Apraxia'],
      correctOptionIndex: 0,
      explanation: 'Alexithymia kesulitan mengenali bahasa emosi diri.',
    ),
    QuestionItem(
      id: 'psi_089',
      questionText: 'Gangguan komunikasi sosial dan perilaku repetitif yang muncul sejak usia dini dinamakan:',
      options: ['Autism Spectrum Disorder (ASD)', 'ADHD', 'Dyslexia', 'Conduct Disorder'],
      correctOptionIndex: 0,
      explanation: 'ASD mempengaruhi interaksi, komunikasi sosial, dan fleksibilitas minat.',
    ),
    QuestionItem(
      id: 'psi_090',
      questionText: 'Gangguan neuroperkembangan ditandai kesulitan fokus perhatian, impulsivitas, dan hiperaktivitas adalah:',
      options: ['ADHD (Attention-Deficit/Hyperactivity Disorder)', 'ASD', 'ODD', 'Tourette'],
      correctOptionIndex: 0,
      explanation: 'ADHD mengganggu rentang perhatian dan regulasi impulsif motorik.',
    ),
    QuestionItem(
      id: 'psi_091',
      questionText: 'Gangguan belajar spesifik yang mempengaruhi kemampuan membaca dan mengeja huruf dinamakan:',
      options: ['Disleksia', 'Disgrafia', 'Diskalkulia', 'Dispraksia'],
      correctOptionIndex: 0,
      explanation: 'Disleksia mengganggu pemrosesan fonologis bahasa bacaan.',
    ),
    QuestionItem(
      id: 'psi_092',
      questionText: 'Gangguan belajar spesifik yang mengganggu pemahaman matematika dan kalkulasi angka dinamakan:',
      options: ['Diskalkulia', 'Disleksia', 'Disgrafia', 'Aphasia'],
      correctOptionIndex: 0,
      explanation: 'Diskalkulia mengganggu konsep pengolahan bilangan numerik.',
    ),
    QuestionItem(
      id: 'psi_093',
      questionText: 'Gangguan makan ditandai pembatasan asupan makanan ekstrem karena takut gemuk dinamakan:',
      options: ['Anoreksia Nervosa', 'Bulimia Nervosa', 'Binge Eating', 'Pica'],
      correctOptionIndex: 0,
      explanation: 'Anoreksia Nervosa melibatkan persepsi distorsi citra tubuh berat.',
    ),
    QuestionItem(
      id: 'psi_094',
      questionText: 'Gangguan makan ditandai episode makan berlebihan diikuti tindakan pembersihan (muntah sengaja/pencahar) dinamakan:',
      options: ['Bulimia Nervosa', 'Anoreksia Nervosa', 'Binge Eating', 'Orthorexia'],
      correctOptionIndex: 0,
      explanation: 'Bulimia Nervosa melibatkan siklus purging (pembersihan paksa).',
    ),
    QuestionItem(
      id: 'psi_095',
      questionText: 'Gaya kelekatan (Attachment Style) anak yang merasa aman dan percaya pada pengasuh dinamakan kelekatan:',
      options: ['Secure Attachment', 'Anxious-Ambivalent', 'Avoidant', 'Disorganized'],
      correctOptionIndex: 0,
      explanation: 'Mary Ainsworth (Strange Situation Test) membedakan gaya kelekatan anak.',
    ),
    QuestionItem(
      id: 'psi_096',
      questionText: 'Pola pengasuhan orang tua yang otoriter, menuntut kepatuhan mutlak tanpa kehangatan dinamakan pola:',
      options: ['Authoritarian (Otoriter)', 'Authoritative (Otoritatif)', 'Permissive (Permisif)', 'Neglectful (Apatis)'],
      correctOptionIndex: 0,
      explanation: 'Diana Baumrind mengklasifikasikan pola asuh orang tua.',
    ),
    QuestionItem(
      id: 'psi_097',
      questionText: 'Pola asuh ideal yang menggabungkan tuntutan tinggi yang rasional disertai kehangatan dan komunikasi dinamakan:',
      options: ['Authoritative (Demokratis / Otoritatif)', 'Authoritarian', 'Permissive', 'Indulgent'],
      correctOptionIndex: 0,
      explanation: 'Authoritative menghasilkan anak dengan kemandirian dan efikasi diri tinggi.',
    ),
    QuestionItem(
      id: 'psi_098',
      questionText: 'Studi psikologi yang berfokus pada kekuatan karakter manusia, kebahagiaan, dan kesejahteraan dipelopori Martin Seligman dinamakan:',
      options: ['Psikologi Positif (Positive Psychology)', 'Psikologi Klinis', 'Psikologi Perkembangan', 'Psikologi Kognitif'],
      correctOptionIndex: 0,
      explanation: 'Psikologi Positif berfokus pada Flourishing dan kesadaran kebahagiaan manusia.',
    ),
    QuestionItem(
      id: 'psi_099',
      questionText: 'Keadaan mental di mana seseorang hanyut fokus sepenuhnya dalam aktivitas hingga lupa waktu dinamakan:',
      options: ['Flow State (Mihaly Csikszentmihalyi)', 'Mindfulness', 'Trance', 'Euphoria'],
      correctOptionIndex: 0,
      explanation: 'Flow terjadi saat tantangan seimbang dengan tingkat keterampilan tinggi.',
    ),
    QuestionItem(
      id: 'psi_100',
      questionText: 'Praktik kesadaran penuh mempertahankan perhatian saat ini tanpa memberikan penilaian judgmental dinamakan:',
      options: ['Mindfulness', 'Meditasi Transendental', 'Hipnosis', 'Relaksasi Otot'],
      correctOptionIndex: 0,
      explanation: 'Mindfulness melatih perhatian penuh atas pengalaman momen saat ini.',
    ),
  ];
}
