// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/beri_hadiah_mainan/beri_hadiah_mainan_dialog_npc.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class BeriHadiahMainanDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat diberi hadiah mainan berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Waaah! ( * $npcName memegang mainan gigitan baru lalu menggoyang-goyangkannya gembira * ) 🧸👶',
        'Bababa! ( * $npcName menepuk-nepuk mainan kerincingan dan tertawa mendengar bunyinya * )',
        'Gigaaa! ( * $npcName memeluk boneka kain beruang dengan erat-erat * )',
        'Ooooh! ( * $npcName menatap robot mainan lampu warna-warni dengan mata membelalak kagum * )',
        'Hehehe! ( * $npcName menjatuhkan mainan balok kayu lalu mengambilnya lagi sambil terkekeh * )',
        'Nyaaa! ( * $npcName mencium mainan barunya dengan menggemaskan * )',
        'Abuuu... ( * $npcName memutar-mutar roda mobil-mobilan plastik kecil di lantai * )',
        'Mammm! ( * $npcName memasukkan sudut mainan plastik ke mulutnya * )',
        'Dayaya! ( * $npcName menggoyangkan mainan bebek karet sampai berbunyi kwek-kwek * )',
        'Tetete! ( * $npcName menumpuk dua balok susun lalu menjatuhkannya sambil tertawa riang * )',
        'Kicukicu! ( * $npcName mengarahkan mainan barunya ke wajah $parentName seolah mau berbagi * )',
        'Ehhhe! ( * $npcName memeluk bola kain empuk dan merangkak memutari ruangan * )',
        'Agiii! ( * $npcName memegang mainan bentuk hewan dan mengoceh gembira * )',
        'Owooo! ( * $npcName memencet tombol mainan musik sampai berbunyi lagu anak * )',
        'Bubu! ( * $npcName menaruh mainan barunya di dalam tempat tidur bayinya * )',
        'Lalala! ( * $npcName menari-nari kecil sambil memegang mainan kerincingan * )',
        'Hummm! ( * $npcName mengamati tekstur mainan baru dengan rasa ingin tahu yang tinggi * )',
        'Cicu! ( * $npcName menyodorkan boneka barunya agar dicium oleh $parentName * )',
        'Nyaa-ha! ( * $npcName melempar bola empuk ke arah $parentName sambil tertawa ngakak * )',
        'Paapapa! ( * $npcName menepuk-nepuk mainan musik dengan kedua tangan mungilnya * )',
        'Glooogloo! ( * $npcName memasukkan mainan berbentuk bintang ke dalam wadahnya * )',
        'Oowgh! ( * $npcName mendusel di atas karpet bersama mainan empuk barunya * )',
        'Yaaaya! ( * $npcName tersenyum lebar menunjukkan dua gigi bawahnya yang lucu * )',
        'Wiii! ( * $npcName mengayun-ayunkan mainan gantung warna-warni * )',
        'Tatatata! ( * $npcName memeluk erat mainan barunya sampai tertidur lelap * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Horeeee! Mainan baru! Makasih banyak ya $parentName! Aku suka banget! 🚗🧸✨',
        'Wah! Ini mainan robot/boneka yang aku impikan dari kemarin! $parentName terbaik!',
        'Yeay! Ayo kita main bareng $parentName! Terima kasih hadiah mainannya!',
        'Makasih $parentName! Aku bakal rapihin mainan ini di kotak mainanku habis main!',
        'Uwah! Warnanya bagus banget! Makasih $parentName, aku sayang banget sama $parentName!',
        'Asyik! Mainan puzzle/legonya seru banget! Makasih $parentName!',
        'Makasih $parentName! Nanti aku pamerin mainan baru ini ke teman-teman TK aku!',
        'Hore! Boleh aku buka bungkus mainannya sekarang $parentName? Makasih ya!',
        'Waaah, mainannya bisa bunyi dan ada lampunya! Keren banget $parentName!',
        'Makasih $parentName! Ini jadi mainan favorit nomor satu aku mulai hari ini!',
        'Yeaaay! $parentName baik deh, beliin aku mainan sebagus ini!',
        'Makasih banyak $parentName! Nanti malam aku mau tidur sambil bawa mainan ini!',
        'Asyik! Aku mau susun balok-balok mainan ini jadi istana yang megah! Makasih $parentName!',
        'Makasih $parentName! Nanti mainan baruku ini aku kasih nama yang lucu ya!',
        'Uwah, makasih $parentName! Aku janji nggak bakal ngerusakin mainan ini!',
        'Yippie! Mainan dinosaurus/barbie baru! Makasih banyak $parentName tercinta!',
        'Makasih $parentName! Sini aku peluk kenceng-kenceng sebagai ucapan terima kasih!',
        'Hore! Akhirnya punya mainan ini! Makasih $parentName udah mewujudkan keinginanku!',
        'Waaah! Mobil-mobilannya bisa jalan cepat banget! Keren! Makasih $parentName!',
        'Makasih $parentName! Aku mau main rumah-rumahan/balap-balapan pakai mainan baru ini!',
        'Yeay! $parentName emang paling mengerti mainan yang paling aku sukai!',
        'Makasih banyak $parentName! Ayo kita main sama-sama di ruang tengah!',
        'Uwah, harum plastik mainan baru! Makasih $parentName sayang!',
        'Makasih $parentName! Aku janji bakal berbagi mainan ini sama teman-teman!',
        'Hore, makasih $parentName! Hari ini jadi hari paling membahagiakan!',
      ];
    } else if (childAge <= 11) {
      return [
        'Wah! Makasih banyak ya $parentName! Mainan/game konsol/board game ini keren banget! 🎮🧩✨',
        'Terima kasih $parentName! Aku udah lama banget ngidam mainan edukasi/action figure ini!',
        'Asyik! Makasih $parentName! Nanti kita main board game ini bareng-bareng sekeluarga ya!',
        'Alhamdulillah, terima kasih banyak $parentName! Ini hadiah mainan paling berkesan!',
        'Waaah! Kualitas mainan/model kit ini bagus banget! Terima kasih banyak $parentName!',
        'Makasih $parentName! Aku bakal rawat mainan ini baik-baik dan taro di rak kamar.',
        'Terima kasih $parentName! Mainan lego/puzzle ini bakal ngelatih kreativitas aku banget.',
        'Hore! Terima kasih $parentName! Ini makin motivasi aku buat makin rajin belajar!',
        'Wah, makasih ya $parentName! Teman-teman pasti takjub waktu lihat mainan ini!',
        'Terima kasih $parentName! Hadiah mainan dari $parentName selalu yang terbaik!',
        'Makasih banyak $parentName! Sayang $parentName banget!',
        'Asyik! Terima kasih $parentName! Akhirnya koleksi mainan favoritku makin lengkap.',
        'Terima kasih $parentName! Nanti habis selesai kerjain PR, aku langsung mainin ini!',
        'Makasih $parentName! Detail dan fitur mainan ini beneran canggih banget!',
        'Wah, senangnya! Terima kasih $parentName sudah selalu membuatku bahagia.',
        'Terima kasih $parentName! Aku bakal simpan dusnya juga biar tetap terawat rapi.',
        'Alhamdulillah, makasih $parentName! Kebahagiaan menerima mainan ini tak terlukiskan.',
        'Terima kasih banyak $parentName! Nanti kalau weekend kita rakit bareng ya!',
        'Makasih $parentName! Aku tidak akan membiarkan mainan ini berantakan di lantai.',
        'Wah makasih $parentName! Ini jadi hadiah kejutan terbaik bulan ini!',
        'Terima kasih $parentName! Semoga rezeki $parentName terus mengalir lancar.',
        'Asyik! Makasih $parentName! Aku siap jadi juara pas main game ini nanti!',
        'Terima kasih banyak $parentName! Senang banget punya orang tua se-supportif $parentName.',
        'Makasih $parentName! Pelukan hangat & mainan baru ini kombinasi kebahagiaan sempurna!',
        'Terima kasih $parentName! Aku langsung taruh di meja belajarku!',
      ];
    } else {
      return [
        'Wah, terima kasih banyak ya $parentName! Hadiah koleksi/merchandise/hobby kit ini bermakna banget! 🎁✨',
        'Alhamdulillah, terima kasih $parentName! Walau sudah remaja/dewasa, perhatian $parentName lewat hadiah ini bikin tersentuh.',
        'Terima kasih $parentName! Ini hobi/koleksi yang sangat saya dambakan. Makasih banyak ya!',
        'Wah, terima kasih banyak $parentName! Hadiah barang hobi ini benar-benar melepas stres saya.',
        'Terima kasih $parentName atas kejuatannya. Saya sangat menghargai barang pemberian $parentName ini.',
        'Makasih ya $parentName! $parentName selalu ingat barang hobi atau koleksi yang saya sukai.',
        'Terima kasih banyak $parentName! Ini bakal jadi pajangan/koleksi berharga di kamar saya.',
        'Alhamdulillah, terima kasih $parentName! Kebahagiaan mendapat perhatian seperti ini tiada taranya.',
        'Terima kasih $parentName. Saya janji akan merawat barang hadiah ini dengan sangat cermat.',
        'Wah, terima kasih $parentName! Ini benar-benar kejutan manis yang tidak saya sangka-sangka.',
        'Terima kasih banyak $parentName. Rasa sayang dan perhatian $parentName adalah hadiah terbesar sesungguhnya.',
        'Makasih ya $parentName! Nanti kita coba/gunakan barang hobi ini bersama-sama ya!',
        'Terima kasih $parentName! Barang ini akan selalu mengingatkan saya pada kebaikan orang tua.',
        'Alhamdulillah, makasih $parentName! Rasa syukur saya tak terhingga punya orang tua seistimewa ini.',
        'Terima kasih banyak $parentName! Semoga $parentName selalu diberikan kesehatan dan kebahagiaan.',
        'Wah, terima kasih $parentName! Ini sangat berguna buat mengisi waktu luang saya secara positif.',
        'Terima kasih $parentName atas kehangatan ini. Saya bangga menjadi anak $parentName.',
        'Makasih $parentName! Hadiah ini bakal saya jaga baik-baik sampai kapanpun.',
        'Terima kasih banyak $parentName. Setiap pemberian $parentName mengandung doa dan harapan indah.',
        'Alhamdulillah, makasih $parentName! Saya sangat menyukai desain dan fungsi hadiah ini.',
        'Terima kasih $parentName! Semoga Allah/Tuhan membalas kebaikan $parentName berlipat ganda.',
        'Wah, makasih banyak $parentName! Ini menambah motivasi saya untuk terus berkarya.',
        'Terima kasih $parentName! Momen pemberian hadiah ini sangat berkesan bagi saya.',
        'Makasih ya $parentName... Kasih sayang orang tua memang tiada tandingannya.',
        'Terima kasih $parentName! I love you so much $parentName!',
      ];
    }
  }
}
