// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/beri_hadiah_mainan/beri_hadiah_mainan_dialog_user.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class BeriHadiahMainanDialogUser {
  /// Mengembalikan list 100 variasi dialog User (Orang Tua) saat memberikan hadiah mainan
  static List<String> getUserDialogues({
    required String childName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Nih anak lucu $childName, $parentName beliin mainan kerincingan & gigitan baru buatmu! 🧸👶',
        'Lihat apa yang dibawakan $parentName! Mainan boneka empuk warna-warni khusus buat $childName!',
        'Sini sayang, ini mainan balok plastik aman buat anak bayi kesayangan $parentName!',
        'Nih buat diplaypen kamu! Mainan bebek karet yang bisa berbunyi kwek-kwek!',
        'Tadaaa! Mainan musik lampu warna-warni untuk menghibur hari-hari manis $childName!',
        'Ulian senangnya melihat matamu berbinar melihat mainan bola kain empuk ini!',
        'Ini mainan roda-rodaan aman dari $parentName, biar kamu makin lincah merangkak!',
        'Nih mainan gantung lucu buat dipasang di atas tempat tidur bayimu ya nak!',
        'Sensasi halus dari boneka beruang ini pasti bikin $childName nyaman mendekapnya.',
        'Ini mainan edukasi sensorik pertama dari $parentName untuk anak pintar $childName!',
        'Main dengan tenang ya sayang, mainan ini aman dan bebas dari bahan berbahaya.',
        'Nih $parentName belikan mainan susun balok plastik warna cerah buat melatih motorikmu!',
        'Anak bayi $parentName dapat hadiah mainan! Semoga kamu makin ceria setiap hari.',
        'Pegang baik-baik ya sayang, ini mainan spesial dari hasil kerja keras $parentName.',
        'Setiap mainan yang $parentName belikan dirancang untuk tumbuh kembang manismu.',
        'Aduh lucunya tangan kecilmu mencoba memeluk mainan baru yang besarnya hampir sama!',
        'Ini buat menemani saat-saat kamu bermain di karpet empuk bersama $parentName ya.',
        'Nanti kita main sama-sama ya nak, $parentName yang gerakkan mainan ini buat kamu!',
        'Teruslah tersenyum riang buah hatiku, melihat kebahagiaanmu adalah kepuasan $parentName.',
        'Ini hadiah mainan khusus dari $parentName, simpan di kotak mainan lucumu ya!',
        'Tangan mungilmu sangat menggemaskan saat mencoba meraih mainan baru ini.',
        'Semoga mainan ini merangsang imajinasi dan kecerdasanmu sejak dini ya sayang.',
        'Nanti kalau sudah selesai main, kita rapikan bersama ya anak pinter!',
        'Kasih sayang dan mainan ini tulus dari hati $parentName untuk anak tercinta.',
        'Semoga hadiah mainan ini membawa tawa dan kebahagiaan manis di rumah kita!',
      ];
    } else if (childAge <= 5) {
      return [
        'Buka matamu anak pintar $childName! $parentName punya hadiah mainan baru buatmu! 🚗🧸✨',
        'Ini mainan robot/boneka/lego yang kamu impikan kemarin! Spesial dari $parentName!',
        'Tadaaa! Mainan balap/rumah-rumahan baru buat anak penurut kesayangan $parentName!',
        'Nih $parentName belikan mainan puzzle warna-warni biar kamu makin cerdas dan kreatif!',
        'Anak rajin $childName berhak dapat hadiah mainan keren hari ini dari $parentName!',
        'Ini mainan khusus buat kamu bawa bermain di ruang tengah bersama keluarga ya nak.',
        'Nih hadiah mainan dari $parentName! Jangan lupa berbagi main bersama teman-temanmu ya.',
        'Senang ya dapat mainan baru? $parentName juga senang melihat binar bahagia di matamu.',
        'Mainan ini berkualitas dan bagus banget! Rawat baik-baik ya sayang.',
        'Nih buat menambah koleksi mainan di kamar kamu! Hadiah dari $parentName tercinta.',
        'Ini hadiah mainan harian untuk anak tercantik/tertampan kesayangan $parentName!',
        'Mainlah dengan gembira ya nak! Ini hadiah mainan dari $parentName untuk harimu.',
        'Semoga mainan ini bisa memicu daya imajinasi dan kreativitas anak hebat $childName!',
        'Nih hadiah anak baik! Mainan karakter favoritmu khusus dari $parentName!',
        'Gunakan buat main bersama teman-temanmu ya sayang, selalu akur dan ramah!',
        'Ini hadiah mainan untuk buah hati $parentName. Jaga baik-baik jangan sampai rusak ya!',
        'Nih simpan di tempat mainanmu! Hadiah manis dari orang tua tersayang.',
        'Bermainlah dengan cermat dan aman ya anak pinter! Ini hadiah mainan barumu.',
        'Semoga kamu makin semangat belajar dan ceria setiap hari dengan adanya mainan ini!',
        'Nih hadiah mainan dari $parentName! Boleh langsung kamu rakit atau buka bungkusnya.',
        'Ingat pesan $parentName, kalau sudah selesai bermain jangan lupa dirapikan kembali ya!',
        'Hadiah mainan ini bentuk kasih sayang dan apresiasi $parentName untuk anak penurut.',
        'Hati-hati saat merakit atau memainkannya ya $childName, $parentName bantu kalau kesulitan.',
        'Ayo bilang apa sama $parentName kalau diberi hadiah mainan? Hehehe ini mainannya!',
        'Semoga hadiah mainan ini membawa kebahagiaan tiada tara untuk harimu yang indah!',
      ];
    } else if (childAge <= 11) {
      return [
        'Ini hadiah mainan edukasi/board game/model kit baru buat kamu $childName! 🎮🧩✨',
        'Nih $parentName belikan mainan konsol/figure yang kamu idam-idamkan karena prestasimu!',
        'Gunakan mainan edukatif ini untuk mengasah kemampuan berpikir dan kreativitasmu ya $childName.',
        'Ini hadiah mainan tambahan dari $parentName karena kamu sudah rajin belajar dan berbakti!',
        'Simpan mainan ini dengan baik di rak kamarmu ya. Jaga kebersihan dan kelengkapannya.',
        'Nih hadiah spesial buat anak kesayangan $parentName! Selamat menikmati waktu luangmu.',
        'Selalu utamakan belajar dulu sebelum bermain dengan mainan baru ini ya sayang.',
        'Semoga hadiah mainan ini bisa menjadi sarana kebersamaan keluarga kita saat akhir pekan.',
        'Ini rezeki dari hasil kerja keras $parentName, gunakan hadiah ini dengan penuh tanggung jawab.',
        'Nih mainan keren buat $childName! Belajarlah merawat barang pribadi sejak dini ya anak hebat.',
        'Kamu sudah makin dewasa dan berbakat. Ini hadiah barang permainan dari $parentName.',
        'Jika ada bagian yang rumit dirakit, kita bisa rakit bersama-sama malam ini ya nak.',
        'Nih hadiah mainan buat kamu! Semangat belajarnya ya anak kebanggaan $parentName!',
        'Gunakan untuk mengisi waktu luang secara positif dan menyenangkan ya $childName sayang.',
        'Ini bentuk perhatian dan kasih sayang $parentName agar kamu merasa bahagia dan dihargai.',
        'Jangan lupa ajak saudara atau temanmu bermain bersama agar terasa lebih seru ya!',
        'Simpan di tempat yang aman ya! $parentName selalu mendoakan kebaikan dan kesuksesanmu.',
        'Nih hadiah barang permainan dari $parentName. Kalau butuh perlengkapan tambahan, cerita ke $parentName ya.',
        'Jadilah anak yang bersyukur dan tidak cepat bosan ya sayang. Ini hadiah dari $parentName.',
        'Semoga dengan mainan ini kamu makin kreatif dan terhindar dari rasa jenuh!',
        'Ini hadiah mainan dari $parentName. Selalu bersyukur atas setiap karunia dalam keluarga kita.',
        'Nih jatah hadiah mainanmu! Ingat untuk tetap disiplin mengatur waktu belajar dan bermain.',
        'Setiap hadiah yang $parentName berikan disertai doa tulus untuk kebaikan masa depanmu.',
        'Gunakan hadiah ini sebaik mungkin ya $childName, $parentName sangat bangga padamu.',
        'Nih hadiah permainan baru! Selamat bermain dan mengasah ketangkasanmu bersama keluarga!',
      ];
    } else {
      return [
        'Ini hadiah barang hobi/koleksi/merchandise impianmu $childName! Dari $parentName khusus buatmu. 🎁✨',
        'Nih $parentName belikan barang koleksi hobi ini. Semoga bisa mendukung passion dan minatmu.',
        'Gunakan hadiah hobi ini untuk menyalurkan bakat dan merilekskan pikiranmu ya $childName.',
        'Ini bentuk apresiasi dari $parentName atas kedewasaan, kerja keras, dan bakti yang kamu tunjukkan.',
        'Di usiamu yang makin dewasa, $parentName senang bisa memberikan barang hobi yang kamu sukai.',
        'Nih hadiah hobi dari $parentName. Jangan ragu cerita tentang proyek hobi kreatifmu pada $parentName.',
        'Selalu jaga dan rawat barang koleksi berharga ini dengan cermat ya $childName.',
        'Semoga hadiah ini memberikan kebahagiaan dan inspirasi baru dalam perjalanan hidupmu.',
        'Ini bentuk kasih sayang dan kebanggaan $parentName atas pencapaian dan kemandirianmu.',
        'Gunakan dengan rasa tanggung jawab ya nak. $parentName selalu mendukung hobi positifmu.',
        'Nih hadiah barang hobi spesial dari $parentName. Semoga bermanfaat dan menambah semangatmu.',
        'Selalu ingat untuk menjaga keseimbangan antara hobi, karir/studi, dan ibadah ya sayang.',
        'Hadiah ini adalah wujud rasa syukur $parentName memiliki anak yang berbakat dan santun.',
        'Semoga dengan dukungan ini kamu makin percaya diri mengejar cita-cita dan minatmu.',
        'Nih simpan baik-baik di kamar atau ruang hobimu ya $childName. Sukses selalu untukmu!',
        'Kasih sayang dan hadiah dari $parentName selalu mengiringi setiap langkah perjuanganmu.',
        'Gunakan untuk hal-hal yang produktif dan membawa manfaat bagi dirimu dan lingkungan sekitar.',
        'Nih tambahan barang koleksi favoritmu dari $parentName. Tetaplah menjadi pribadi yang rendah hati.',
        'Semoga kebaikan dan kegembiraan selalu menyertai setiap waktu luang yang kamu nikmati.',
        'Jadilah sosok yang bijak dan berkarakter kuat. Ini hadiah hobi dari $parentName untukmu.',
        'Nih buat kejutan kamu hari ini! Jangan lupa jaga kesehatan dan semangat berkaryamu ya.',
        'Terima kasih sudah menjadi anak yang berbakti dan membanggakan orang tua. Ini hadiah hobimu.',
        'Semoga barang pemberian ini membawa kedamaian dan keceriaan dalam ruang pribadimu.',
        'Nih hadiah barang favorit dari $parentName! Doa dan kasih sayang $parentName selalu bersamamu.',
        'Manfaatkan sebaik-baiknya ya nak. $parentName sangat mencintai dan membanggakanmu!',
      ];
    }
  }
}
