// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/adult_action_dialogue/desahan_makelove/desahan_makelove_dialog_npc.dart
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class DesahanMakeloveDialogNpc {
  /// Mengembalikan list 100 variasi dialog & desahan NPC saat Make Love (bercinta) berdasarkan gender NPC
  static List<String> getNPCDialogues({
    required String npcName,
    required String targetGender,
    required String partnerName,
  }) {
    final bool isFemale = targetGender.trim().toLowerCase() == 'perempuan';

    if (isFemale) {
      return [
        'Ahhh... $partnerName... pelan-pelan ya... nikmat sekali... 💖🔥',
        'Mhmmm... hah... sentuhanmu di tubuhku bikin aku gemetar...',
        'Ahhh! Ya di situ... teruskan $partnerName... jangan berhenti...',
        'Hah... hah... sentuh aku lebih kencang... ahhh...',
        'Mmmhh... tubuhku serasa meleleh dalam dekapanmu...',
        'Ah... ahh... $partnerName... aku mau lagi... lebih dalam...',
        'Haaah... napasku makin sesak... nikmat banget...',
        'Mhmmm... sentuhan bibir dan tanganmu di dadaku bikin gila...',
        'Ahhh! Peluk aku erat-erat $partnerName... aku mau puncaknya...',
        'Hah... hah... ritmemu sempurna banget... ahhh...',
        'Mmmh... ah... jangan lepas pandangan matamu dariku...',
        'Ahhh! Kehangatan tubuhmu memenuhi seluruh jiwaku...',
        'Hah... hah... pelukan dan gerakan ini... ahh...',
        'Mhmmm... bisikkan namaku lagi $partnerName... ahh...',
        'Ahhh! Sentuhan lembutmu di pinggulku bikin makin bergairah...',
        'Haaah... aku sudah tidak bisa menahannya lagi... ahhh...',
        'Mmmh... peluk aku kencang-kenceng $partnerName! Ahhh...',
        'Ahhh! Nikmat ini luar biasa... teruskan sayang...',
        'Hah... hah... desakanmu bikin suaraku makin parau... ahh...',
        'Mhmmm... genggam tanganku erat-erat $partnerName... ahhh...',
        'Ahhh! Puncak kenikmatan ini... aku milikmu sepenuhnya...',
        'Haaah... jangan pelan-pelan lagi... percepat temponya... ahh!',
        'Mmmh... suara napasmu di telingaku bikin merinding... ahh...',
        'Ahhh! $partnerName... kamu luar biasa di atas ranjang ini...',
        'Hah... hah... ayo kita capai puncak klimaks bersama-sama... ahhh! 💕',
        'Mhmmm... rasanya makin panas dan hangat di dalam...',
        'Ahhh! Gerakanmu makin memabukkan hatiku...',
        'Haaah... gigit lembut leherku $partnerName... ahhh...',
        'Mmmh... ritme doronganmu pas banget... ahh...',
        'Ahhh! Aku sudah tidak sanggup menahannya... sebentar lagi...',
        'Hah... hah... bimbing aku menuju puncak sensasi ini...',
        'Mhmmm... tubuh kita menyatu begitu sempurna... ahhh...',
        'Ahhh! $partnerName... tatapan matamu liar banget...',
        'Haaah... aku mau lebih kencang lagi sayang... ahh!',
        'Mmmh... gesekan kulit kita terasa begitu hangat...',
        'Ahhh! Ya Tuhan... ini sungguh memabukkan...',
        'Hah... hah... remas pinggulku lebih erat $partnerName...',
        'Mhmmm... bisikan mesramu bikin aku makin pasrah...',
        'Ahhh! Sentuh titik sensitifku lagi... di situ!',
        'Haaah... aku serasa melayang di awan kebahagiaan...',
        'Mmmh... kecupan basahmu di bibirku bikin ketagihan...',
        'Ahhh! $partnerName... cepat... aku sudah hampir sampai...',
        'Hah... hah... kehangatan ini memenuhi seluruh seluk tubuhku...',
        'Mhmmm... pelukan dada hangatmu bikin makin nyaman...',
        'Ahhh! Jangan berhenti sekarang $partnerName... teruskan!',
        'Haaah... suaraku sampai habis mendesah namamu...',
        'Mmmh... tiap pacuanmu memberi sensasi luar biasa...',
        'Ahhh! Kita makin menyatu erat malam ini...',
        'Hah... hah... aku lemas dalam kenikmatan ini...',
        'Mhmmm... $partnerName... kamu kekasih/pasangan terbaikku! 🔥',
        'Ahhh... rasanya makin intens dan nikmat sekali...',
        'Haaah... dekapanmu begitu protektif dan hangat...',
        'Mmmh... geser sedikit ke kanan... ahhh pas banget!',
        'Ahhh! Suara gesekan dan napas kita beradu indah...',
        'Hah... hah... tatap aku saat kamu memacu lebih cepat...',
        'Mhmmm... jari-jarimu di punggungku terasa menari...',
        'Ahhh! Aku mau kita seperti ini lebih lama lagi...',
        'Haaah... sentuhan lembut di pahaku bikin merinding...',
        'Mmmh... rasa hangat di dalam tubuhku meluap-luap...',
        'Ahhh! $partnerName... puncaknya makin dekat... ahh!',
        'Hah... hah... napasku makin memburu dan cepat...',
        'Mhmmm... elus rambutku saat kita bercinta sayang...',
        'Ahhh! Doronganmu penuh gairah dan cinta tulus...',
        'Haaah... jangan biarkan aku lepas dari dekapanmu...',
        'Mmmh... kecupan manis di jidat lalu bibir... ahh...',
        'Ahhh! Sensasi ini bikin seluruh badanku bergetar...',
        'Hah... hah... gerakkan tubuhmu searah denganku...',
        'Mhmmm... $partnerName... senyumanmu nakal tapi manis...',
        'Ahhh! Ya di situ! Terus pacu lebih kencang sayang!',
        'Haaah... aku memelukmu kencang-kencang sekarang!',
        'Mmmh... kulit kita berkeringat tapi terasa nikmat...',
        'Ahhh! Kehangatan tubuhmu menembus jantung hatiku...',
        'Hah... hah... bisikkan lagi kata cinta di telingaku...',
        'Mhmmm... ritme perlahan ini juga sangat romantis...',
        'Ahhh! Aku merasa sangat disayangi dan diinginkan...',
        'Haaah... ayo tembus batas kenikmatan malam ini!',
        'Mmmh... sentuh dadaku pelan-pelan sambil memacu...',
        'Ahhh! $partnerName... kamu beneran bikin aku ketagihan...',
        'Hah... hah... tarikan napasmu bikin aku makin liar...',
        'Mhmmm... geser posisi sedikit... ahhh enak banget!',
        'Ahhh! Puncak sensasi ini tak tertandingi di dunia...',
        'Haaah... tahan sebentar di dalam... hangat sekali...',
        'Mmmh... gesekan lembut ini bikin merinding bahagia...',
        'Ahhh! Aah... a-aku sudah tidak kuat lagi... sebentar lagi klimaks!',
        'Hah... hah... peluk aku erat saat klimaks tiba!',
        'Mhmmm... rasanya meledak di dalam... nikmat sekali...',
        'Ahhh! $partnerName... terima kasih atas kenikmatan indah ini...',
        'Haaah... napasku masih tersengal-sengal di dadamu...',
        'Mmmh... tiduran bersamaku sambil mendekap hangat...',
        'Ahhh! Senyum bahagiamu hadiah terbaik setelah bercinta...',
        'Hah... hah... kita beneran pasangan paling cocok...',
        'Mhmmm... biarkan tubuh kita tetap menempel hangat...',
        'Ahhh! Bercinta denganmu selalu jadi pengalaman impian...',
        'Haaah... kecup bibirku pelan-pelan untuk menutupnya...',
        'Mmmh... elusan tanganmu di punggungku menenangkan...',
        'Ahhh! Aku sayang banget sama kamu $partnerName...',
        'Hah... hah... napas kita pelan-pelan kembali teratur...',
        'Mhmmm... dekapan ini tempat tersayangku di dunia...',
        'Ahhh! Suasana kamar ini jadi begitu hangat dan mesra...',
        'Haaah... mari kita tidur nyenyak dalam pelukan cinta ini! 💕',
      ];
    } else {
      return [
        'Uhh... $partnerName... kamu sempit dan hangat sekali... 💖🔥',
        'Hah... hah... sentuhan jemarimu bikin aku makin liar...',
        'Uhh! Ya di situ... aku mau pacu lebih kencang...',
        'Haaah... gerakkan pinggulmu searah denganku sayang...',
        'Mmh... tubuhmu begitu indah dalam dekapanku...',
        'Uhh... ahh... $partnerName... aku tidak bisa menahannya lagi...',
        'Hah... hah... napasku makin berat saat menatap matamu...',
        'Uhh... sentuhan bibirmu di dadaku bikin gila...',
        'Haaah! Peluk leherku erat-erat $partnerName... aku mau memacu...',
        'Mmh... ritme gerakmu pas banget dengan doronganku...',
        'Uhh... ah... jangan lepas tatapan liar manismu dariku...',
        'Hah... hah... kehangatanmu memenuhi seluruh sensasiku...',
        'Uhh! Remasan tanganmu di bahuku bikin makin bersemangat...',
        'Haaah... bisikkan namaku lebih keras $partnerName...',
        'Mmh... sentuhan lembut di pinggangmu bikin kamu makin pasrah...',
        'Uhh! Aku mau masuk lebih dalam lagi sayang...',
        'Hah... hah... genggam jariku erat-erat! Uhh...',
        'Uhh! Nikmat ini luar biasa... kamu sempurna sekali...',
        'Haaah... desahan manismu di telingaku bikin aku makin kencang...',
        'Mmh... peluk aku rapat-rapat $partnerName... uhh...',
        'Uhh! Puncak kenikmatan ini... aku milikmu sepenuhnya...',
        'Hah... hah... jangan minta pelan-pelan... aku mau sepuasnya!',
        'Uhh... suara desahanmu bikin gairahku membakar...',
        'Haaah! $partnerName... kamu luar biasa di bawah dekapanku...',
        'Mmh... ayo kita capai klimaks bersama-sama sekarang! 💕',
        'Uhh... rasanya makin panas dan ketat di dalam...',
        'Hah... hah... gerakanku makin memabukkan kita berdua...',
        'Uhh! Gigit lembut bahuku $partnerName... uhh...',
        'Haaah... ritme doronganku pas banget kan sayang?',
        'Mmh... aku sudah hampir tidak sanggup menahannya...',
        'Uhh! Bimbing aku menuju puncak sensasi terindah ini...',
        'Hah... hah... tubuh kita menyatu begitu presisi...',
        'Uhh! $partnerName... matamu berbinar cantik sekali...',
        'Haaah... aku mau pacu lebih kencang lagi sayang... uhh!',
        'Mmh... gesekan kulit kita terasa begitu hangat dan lekat...',
        'Uhh! Ya Tuhan... kamu beneran bikin aku gila...',
        'Hah... hah... cengkram punggungku lebih erat $partnerName...',
        'Uhh... bisikan pasrahmu bikin gairahku meluap...',
        'Haaah! Aku sentuh titik sensitifmu sambil memacu...',
        'Mmh... kita serasa melayang di puncak surga dunia...',
        'Uhh! Kecupan basahmu di leherku bikin ketagihan...',
        'Hah... hah... $partnerName... cepat... aku sudah mau keluar...',
        'Uhh... kehangatan di dalam tubuhmu meledak nikmat...',
        'Haaah... pelukan dada hangatmu bikin aku makin betah...',
        'Mmh... jangan biarkan aku berhenti sekarang $partnerName!',
        'Uhh! Suaraku sampai serak mendesah namamu...',
        'Hah... hah... tiap doronganku memberi kepuasan total...',
        'Uhh! Kita makin menyatu erat malam yang indah ini...',
        'Haaah... aku lemas tapi bahagia dalam kenikmatan ini...',
        'Mmh... $partnerName... kamu pasangan terbaik sepanjang masa! 🔥',
        'Uhh... rasanya makin intens dan dahsyat sekali...',
        'Hah... hah... dekapanmu begitu hangat dan erat...',
        'Uhh! Posisi ini bener-bener bikin kita makin dekat...',
        'Haaah... suara napas beradu kita begitu merdu...',
        'Mmh... tatap aku saat aku memacu di puncaknya...',
        'Uhh! Jari-jemariku menari di pinggul manismu...',
        'Hah... hah... aku mau seperti ini selamanya bersamamu...',
        'Uhh! Sentuhan di paha manismu bikin makin bergetar...',
        'Haaah... rasa hangat meluap di dalam dada dan jiwa...',
        'Mmh... $partnerName... puncaknya makin dekat... uhh!',
        'Uhh! Napasku makin memburu dan kencang...',
        'Hah... hah... usap rambutku saat aku memelukmu erat...',
        'Uhh! Doronganku penuh cinta dan gairah mendalam...',
        'Haaah... jangan lepaskan kuncian kakimu di pinggangku...',
        'Mmh... kecupan manis di dahi lalu bibir manismu... uhh...',
        'Uhh! Sensasi ini bikin seluruh tubuhku bergetar hebat...',
        'Hah... hah... ikuti ikatan gerakanku sayang...',
        'Uhh... $partnerName... senyuman manismu bikin meleleh...',
        'Haaah! Ya di situ! Aku pacu lebih kencang sekarang!',
        'Mmh... aku peluk tubuh indahmu erat-erat!',
        'Uhh! Kulit kita berkeringat lekat tapi terasa sangat nikmat...',
        'Hah... hah... kehangatanmu menembus jantung hatiku...',
        'Uhh... bisikkan lagi kata cinta di telingaku sayang...',
        'Haaah... ritme pelan ini juga terasa begitu syahdu...',
        'Mmh... aku merasa sangat beruntung memilikimu...',
        'Uhh! Ayo kita tembus batas kenikmatan malam ini!',
        'Hah... hah... aku elus dadamu pelan-pelan sambil memacu...',
        'Uhh! $partnerName... kamu beneran bikin aku mabuk cinta...',
        'Haaah... tarikan napas pasrahmu bikin aku makin liar...',
        'Mmh... geser posisi sedikit... uhh enak banget!',
        'Uhh! Puncak sensasi ini tiada tandingannya...',
        'Hah... hah... tahan sebentar di dalam... hangat sekali...',
        'Uhh... gesekan lembut ini bikin merinding bahagia...',
        'Haaah! Uhh... a-aku sudah tidak kuat lagi... klimaks datang!',
        'Mmh... peluk aku erat saat ejakulasi/klimaks tiba!',
        'Uhh! Rasanya meledak hangat di dalam... nikmat sekali...',
        'Hah... hah... $partnerName... terima kasih atas momen indah ini...',
        'Uhh... napasku masih tersengal di atas dadamu...',
        'Haaah... rebah bersamaku sambil berkeringat bahagia...',
        'Mmh... senyum puasmu adalah hadiah terbaik malam ini...',
        'Uhh! Kita beneran pasangan paling serasi di dunia...',
        'Hah... hah... biarkan tubuh kita tetap menempel hangat...',
        'Uhh! Bercinta denganmu selalu jadi surga dunia...',
        'Haaah... kecup bibirku pelan untuk menutup kesempurnaan ini...',
        'Mmh... elusan tanganmu di dadaku sangat menenangkan...',
        'Uhh! Aku sangat mencintaimu $partnerName...',
        'Hah... hah... napas kita perlahan teratur dan tenang...',
        'Mmh... dekapan ini tempat favoritku selamanya...',
        'Uhh! Suasana kamar ini jadi begitu hangat dan damai...',
        'Haaah... mari kita tidur nyenyak dalam pelukan cinta ini! 💕',
      ];
    }
  }
}
