// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/adult_action_dialogue/desahan_makelove/desahan_makelove_dialog_user.dart
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class DesahanMakeloveDialogUser {
  /// Mengembalikan list 100 variasi narasi & desahan User saat Make Love (bercinta) berdasarkan gender User
  static List<String> getUserDialogues({
    required String playerName,
    required String playerGender,
    required String partnerName,
  }) {
    final bool isPlayerFemale = playerGender.trim().toLowerCase() == 'perempuan';

    if (isPlayerFemale) {
      return [
        'Ahhh... $partnerName... peluk aku erat-erat... rasanya begitu nikmat... 💖🔥',
        'Mhmmm... hah... sentuhan jemarimu di kulitku bikin merinding...',
        'Ahhh! Di situ sayang... teruskan pacuanmu... jangan berhenti...',
        'Hah... hah... dekatkan tubuhmu... aku mau lebih kencang... ahhh...',
        'Mmmhh... kecup bibirku sambil memacu tubuh kita...',
        'Ah... ahh... $partnerName... kamu membuatku melayang tinggi...',
        'Haaah... napasku tersengal-sengal dalam kenikmatan ini...',
        'Mhmmm... genggam tanganku erat-erat... ahh...',
        'Ahhh! Sentuhan bibir dan lidahmu di leherku bikin gila...',
        'Hah... hah... tempelkan dadamu di dadaku... ahhh...',
        'Mmmh... ah... tatap mataku dengan gairah cintamu...',
        'Ahhh! Kehangatan doronganmu memenuhi seluruh sensasiku...',
        'Hah... hah... ritme ini pas banget... jangan pelan-pelan lagi...',
        'Mhmmm... bisikkan kata-kata mesramu di telingaku... ahh...',
        'Ahhh! Sentuhan lembut di pinggulku bikin aku makin pasrah...',
        'Haaah... aku sudah tidak bisa menahan gelombang nikmat ini...',
        'Mmmh... peluk pinggangku kencang $partnerName! Ahhh...',
        'Ahhh! Nikmat ini luar biasa indah... teruskan sayang...',
        'Hah... hah... pacuanmu membuat suaraku makin parau... ahh...',
        'Mhmmm... aku menyatukan tanganku di lehermu... ahhh...',
        'Ahhh! Puncak kenikmatan ini... aku milikmu sepenuhnya...',
        'Haaah... dorong lebih dalam lagi $partnerName... ahh!',
        'Mmmh... detak jantungmu yang memburu terasa di dadaku...',
        'Ahhh! $partnerName... kamu kekasih terbaik di atas ranjang ini...',
        'Hah... hah... ayo kita jemput klimaks bersama-sama... ahhh! 💕',
        'Mhmmm... rasanya makin panas dan lekat di dalam...',
        'Ahhh! Gerakanmu makin memabukkan jiwaku...',
        'Haaah... bisikkan betapa kamu mencintaiku... ahhh...',
        'Mmmh... gesekan lembut ini bikin seluruh badanku gemetar...',
        'Ahhh! Aku sudah hampir sampai di puncaknya... sebentar lagi...',
        'Hah... hah... bimbing aku menuju surga dunia ini...',
        'Mhmmm... tubuh kita bersatu begitu harmonis dan presisi...',
        'Ahhh! $partnerName... gairahmu benar-benar membakar...',
        'Haaah... aku mau lebih kencang lagi sayang... ahh!',
        'Mmmh... peluh keringat kita menyatu hangat...',
        'Ahhh! Ya Tuhan... ini sungguh sensasi memabukkan...',
        'Hah... hah... cengkram pinggulku lebih erat $partnerName...',
        'Mhmmm... desahan pasrahku khusus untukmu seorang...',
        'Ahhh! Sentuh titik paling sensitifku lagi... di situ!',
        'Haaah... aku merasa melayang di awan kebahagiaan...',
        'Mmmh... kecupan basah hangatmu bikin ketagihan...',
        'Ahhh! $partnerName... cepat... aku sudah di ambang puncaknya...',
        'Hah... hah... kehangatan ini mengalir ke seluruh seluk tubuhku...',
        'Mhmmm... dekapan eratmu membuatku merasa aman dan nikmat...',
        'Ahhh! Jangan pernah berhenti memanjakanku $partnerName...',
        'Haaah... suaraku sampai habis mendesah namamu...',
        'Mmmh... tiap doronganmu memberi kepuasan tak terhingga...',
        'Ahhh! Kita makin menyatu erat malam ini...',
        'Hah... hah... aku lemas dan berserah dalam dekapanmu...',
        'Mhmmm... $partnerName... aku sangat mencintaimu! 🔥',
        'Ahhh... rasanya makin intens dan nikmat sekali...',
        'Haaah... dekapanmu begitu protektif dan hangat...',
        'Mmmh... geser posisi sedikit... ahhh pas banget!',
        'Ahhh! Suara gesekan dan napas kita beradu indah...',
        'Hah... hah... tatap aku saat kamu memacu lebih cepat...',
        'Mhmmm... jari-jariku meremas lembut bahumu...',
        'Ahhh! Aku mau kita seperti ini lebih lama lagi...',
        'Haaah... sentuhan lembut di pahaku bikin merinding...',
        'Mmmh... rasa hangat di dalam tubuhku meluap-luap...',
        'Ahhh! $partnerName... puncaknya makin dekat... ahh!',
        'Hah... hah... napasku makin memburu dan cepat...',
        'Mhmmm... usap rambutku saat kita bercinta sayang...',
        'Ahhh! Doronganmu penuh gairah dan cinta tulus...',
        'Haaah... jangan biarkan aku lepas dari dekapanmu...',
        'Mmmh... kecupan manis di jidat lalu bibir... ahh...',
        'Ahhh! Sensasi ini bikin seluruh badanku bergetar...',
        'Hah... hah... gerakkan tubuhmu searah denganku...',
        'Mhmmm... $partnerName... senyumanmu nakal tapi manis...',
        'Ahhh! Ya di situ! Terus pacu lebih kencang sayang!',
        'Haaah... aku memelukmu kencang-kencang sekarang!',
        'Mmmh... kulit kita berkeringat tapi terasa nikmat...',
        'Ahhh! Kehangatan tubuhmu menembus jantung hatiku...',
        'Hah... hah... bisikkan lagi kata cinta di telingaku...',
        'Mhmmm... ritme perlahan ini juga sangat romantis...',
        'Ahhh! Aku merasa sangat disayangi dan diinginkan...',
        'Haaah... ayo tembus batas kenikmatan malam ini!',
        'Mmmh... sentuh dadaku pelan-pelan sambil memacu...',
        'Ahhh! $partnerName... kamu beneran bikin aku ketagihan...',
        'Hah... hah... tarikan napasmu bikin aku makin liar...',
        'Mhmmm... geser posisi sedikit... ahhh enak banget!',
        'Ahhh! Puncak sensasi ini tak tertandingi di dunia...',
        'Haaah... tahan sebentar di dalam... hangat sekali...',
        'Mmmh... gesekan lembut ini bikin merinding bahagia...',
        'Ahhh! Aah... a-aku sudah tidak kuat lagi... sebentar lagi klimaks!',
        'Hah... hah... peluk aku erat saat klimaks tiba!',
        'Mhmmm... rasanya meledak di dalam... nikmat sekali...',
        'Ahhh! $partnerName... terima kasih atas kenikmatan indah ini...',
        'Haaah... napasku masih tersengal-sengal di dadamu...',
        'Mmmh... tiduran bersamaku sambil mendekap hangat...',
        'Ahhh! Senyum bahagiamu hadiah terbaik setelah bercinta...',
        'Hah... hah... kita beneran pasangan paling cocok...',
        'Mhmmm... biarkan tubuh kita tetap menempel hangat...',
        'Ahhh! Bercinta denganmu selalu jadi pengalaman impian...',
        'Haaah... kecup bibirku pelan-pelan untuk menutupnya...',
        'Mmmh... elusan tanganmu di punggungku menenangkan...',
        'Ahhh! Aku sayang banget sama kamu $partnerName...',
        'Hah... hah... napas kita pelan-pelan kembali teratur...',
        'Mhmmm... dekapan ini tempat tersayangku di dunia...',
        'Ahhh! Suasana kamar ini jadi begitu hangat dan mesra...',
        'Haaah... mari kita tidur nyenyak dalam pelukan cinta ini! 💕',
      ];
    } else {
      return [
        'Uhh... $partnerName... kamu sempit dan hangat sekali... 💖🔥',
        'Hah... hah... sentuhan jemarimu di dadaku bikin makin bersemangat...',
        'Uhh! Ya di situ... aku mau pacu lebih kencang sayang...',
        'Haaah... gerakkan pinggulmu mengikuti irama doronganku...',
        'Mmh... tubuhmu begitu indah dan lekat dalam dekapanku...',
        'Uhh... ahh... $partnerName... aku memelukmu kencang-kencang...',
        'Hah... hah... napasku makin berat saat menatap mata indahmu...',
        'Uhh... sentuhan kecupanmu di leherku bikin gila...',
        'Haaah! Peluk leherku erat-erat $partnerName... aku mau memacu...',
        'Mmh... ritme gerakmu pas banget dengan dorongan tubuhku...',
        'Uhh... ah... jangan lepas pandangan mata liarmu dariku...',
        'Hah... hah... kehangatanmu memenuhi seluruh sensasiku...',
        'Uhh! Remasan jemarimu di punggungku bikin makin bersemangat...',
        'Haaah... bisikkan namaku lebih keras $partnerName...',
        'Mmh... sentuhan lembut di pinggangmu bikin kamu makin pasrah...',
        'Uhh! Aku mau masuk lebih dalam lagi sayang...',
        'Hah... hah... genggam jariku erat-erat! Uhh...',
        'Uhh! Nikmat ini luar biasa... kamu sempurna sekali...',
        'Haaah... desahan manismu di telingaku bikin aku makin kencang...',
        'Mmh... peluk aku rapat-rapat $partnerName... uhh...',
        'Uhh! Puncak kenikmatan ini... aku milikmu sepenuhnya...',
        'Hah... hah... jangan minta pelan-pelan... aku mau sepuasnya!',
        'Uhh... suara desahanmu bikin gairahku membakar...',
        'Haaah! $partnerName... kamu luar biasa di bawah dekapanku...',
        'Mmh... ayo kita capai klimaks bersama-sama sekarang! 💕',
        'Uhh... rasanya makin panas dan ketat di dalam...',
        'Hah... hah... gerakanku makin memabukkan kita berdua...',
        'Uhh! Gigit lembut bahuku $partnerName... uhh...',
        'Haaah... ritme doronganku pas banget kan sayang?',
        'Mmh... aku sudah hampir tidak sanggup menahannya...',
        'Uhh! Bimbing aku menuju puncak sensasi terindah ini...',
        'Hah... hah... tubuh kita menyatu begitu presisi...',
        'Uhh! $partnerName... matamu berbinar cantik sekali...',
        'Haaah... aku mau pacu lebih kencang lagi sayang... uhh!',
        'Mmh... gesekan kulit kita terasa begitu hangat dan lekat...',
        'Uhh! Ya Tuhan... kamu beneran bikin aku gila...',
        'Hah... hah... cengkram punggungku lebih erat $partnerName...',
        'Uhh... bisikan pasrahmu bikin gairahku meluap...',
        'Haaah! Aku sentuh titik sensitifmu sambil memacu...',
        'Mmh... kita serasa melayang di puncak surga dunia...',
        'Uhh! Kecupan basahmu di leherku bikin ketagihan...',
        'Hah... hah... $partnerName... cepat... aku sudah mau keluar...',
        'Uhh... kehangatan di dalam tubuhmu meledak nikmat...',
        'Haaah... pelukan dada hangatmu bikin aku makin betah...',
        'Mmh... jangan biarkan aku berhenti sekarang $partnerName!',
        'Uhh! Suaraku sampai serak mendesah namamu...',
        'Hah... hah... tiap doronganku memberi kepuasan total...',
        'Uhh! Kita makin menyatu erat malam yang indah ini...',
        'Haaah... aku lemas tapi bahagia dalam kenikmatan ini...',
        'Mmh... $partnerName... kamu pasangan terbaik sepanjang masa! 🔥',
        'Uhh... rasanya makin intens dan dahsyat sekali...',
        'Hah... hah... dekapanmu begitu hangat dan erat...',
        'Uhh! Posisi ini bener-bener bikin kita makin dekat...',
        'Haaah... suara napas beradu kita begitu merdu...',
        'Mmh... tatap aku saat aku memacu di puncaknya...',
        'Uhh! Jari-jemariku menari di pinggul manismu...',
        'Hah... hah... aku mau seperti ini selamanya bersamamu...',
        'Uhh! Sentuhan di paha manismu bikin makin bergetar...',
        'Haaah... rasa hangat meluap di dalam dada dan jiwa...',
        'Mmh... $partnerName... puncaknya makin dekat... uhh!',
        'Uhh! Napasku makin memburu dan kencang...',
        'Hah... hah... usap rambutku saat aku memelukmu erat...',
        'Uhh! Doronganku penuh cinta dan gairah mendalam...',
        'Haaah... jangan lepaskan kuncian kakimu di pinggangku...',
        'Mmh... kecupan manis di dahi lalu bibir manismu... uhh...',
        'Uhh! Sensasi ini bikin seluruh tubuhku bergetar hebat...',
        'Hah... hah... ikuti ikatan gerakanku sayang...',
        'Uhh... $partnerName... senyuman manismu bikin meleleh...',
        'Haaah! Ya di situ! Aku pacu lebih kencang sekarang!',
        'Mmh... aku peluk tubuh indahmu erat-erat!',
        'Uhh! Kulit kita berkeringat lekat tapi terasa sangat nikmat...',
        'Hah... hah... kehangatanmu menembus jantung hatiku...',
        'Uhh... bisikkan lagi kata cinta di telingaku sayang...',
        'Haaah... ritme pelan ini juga terasa begitu syahdu...',
        'Mmh... aku merasa sangat beruntung memilikimu...',
        'Uhh! Ayo kita tembus batas kenikmatan malam ini!',
        'Hah... hah... aku elus dadamu pelan-pelan sambil memacu...',
        'Uhh! $partnerName... kamu beneran bikin aku mabuk cinta...',
        'Haaah... tarikan napas pasrahmu bikin aku makin liar...',
        'Mmh... geser posisi sedikit... uhh enak banget!',
        'Uhh! Puncak sensasi ini tiada tandingannya...',
        'Hah... hah... tahan sebentar di dalam... hangat sekali...',
        'Uhh... gesekan lembut ini bikin merinding bahagia...',
        'Haaah! Uhh... a-aku sudah tidak kuat lagi... klimaks datang!',
        'Mmh... peluk aku erat saat ejakulasi/klimaks tiba!',
        'Uhh! Rasanya meledak hangat di dalam... nikmat sekali...',
        'Hah... hah... $partnerName... terima kasih atas momen indah ini...',
        'Uhh... napasku masih tersengal di atas dadamu...',
        'Haaah... rebah bersamaku sambil berkeringat bahagia...',
        'Mmh... senyum puasmu adalah hadiah terbaik malam ini...',
        'Uhh! Kita beneran pasangan paling serasi di dunia...',
        'Hah... hah... biarkan tubuh kita tetap menempel hangat...',
        'Uhh! Bercinta denganmu selalu jadi surga dunia...',
        'Haaah... kecup bibirku pelan untuk menutup kesempurnaan ini...',
        'Mmh... elusan tanganmu di dadaku sangat menenangkan...',
        'Uhh! Aku sangat mencintaimu $partnerName...',
        'Hah... hah... napas kita perlahan teratur dan tenang...',
        'Mmh... dekapan ini tempat favoritku selamanya...',
        'Uhh! Suasana kamar ini jadi begitu hangat dan damai...',
        'Haaah... mari kita tidur nyenyak dalam pelukan cinta ini! 💕',
      ];
    }
  }
}
