import '../tes_seleksi_model.dart';

List<QuestionItem> getFilmTelevisiQuestions() {
  return const [
    QuestionItem(
      id: 'ftv_001',
      questionText: 'Tiga tahapan utama dalam alur proses produksi film secara urut adalah:',
      options: ['Pra-produksi, Produksi, dan Pasca-produksi', 'Penulisan, Syuting, dan Pemutaran', 'Casting, Editing, dan Promosi', 'Ideasi, Shooting, dan Distribusi'],
      correctOptionIndex: 0,
      explanation: 'Tahapan produksi film terbagi secara baku menjadi Pra-produksi (perencanaan), Produksi (syuting), dan Pasca-produksi (editing/finishing).',
    ),
    QuestionItem(
      id: 'ftv_002',
      questionText: 'Tahapan awal perencanaan film yang mencakup penulisan naskah, casting, lokasi, dan penganggaran dinamakan:',
      options: ['Pra-produksi', 'Produksi', 'Pasca-produksi', 'Eksibisi'],
      correctOptionIndex: 0,
      explanation: 'Pra-produksi adalah fase persiapan matang sebelum kegiatan pengambilan gambar dimulai.',
    ),
    QuestionItem(
      id: 'ftv_003',
      questionText: 'Ringkasan singkat cerita film dalam 1 atau 2 kalimat yang menjelaskan garis besar tokoh dan konflik utama dinamakan:',
      options: ['Logline', 'Sinopsis', 'Treatment', 'Slugline'],
      correctOptionIndex: 0,
      explanation: 'Logline menyampaikan gagasan dan inti konflik cerita film secara sangat singkat dan menarik.',
    ),
    QuestionItem(
      id: 'ftv_004',
      questionText: 'Ringkasan naratif alur cerita film dari awal hingga akhir dalam beberapa halaman dinamakan:',
      options: ['Sinopsis', 'Logline', 'Script Breakdown', 'Rundown'],
      correctOptionIndex: 0,
      explanation: 'Sinopsis merangkum keseluruhan jalannya cerita secara lebih jelas.',
    ),
    QuestionItem(
      id: 'ftv_005',
      questionText: 'Uraian babak cerita film adegan demi adegan secara mendalam sebelum dituangkan ke format naskah lengkap dinamakan:',
      options: ['Treatment', 'Logline', 'Storyboard', 'Drafting'],
      correctOptionIndex: 0,
      explanation: 'Treatment membedah perkembangan adegan dan karakter secara berurutan.',
    ),
    QuestionItem(
      id: 'ftv_006',
      questionText: 'Judul baris awal adegan pada naskah skenario yang menunjukkan lokasi (INT/EXT) dan waktu dinamakan:',
      options: ['Slugline / Scene Heading', 'Parenthetical', 'Action Line', 'Transition'],
      correctOptionIndex: 0,
      explanation: 'Slugline memberi keterangan petunjuk lokasi ruangan dan kondisi siang/malam adegan.',
    ),
    QuestionItem(
      id: 'ftv_007',
      questionText: 'Keterangan "INT." pada baris slugline naskah skenario film merupakan singkatan dari:',
      options: ['Interior (Dalam Ruangan)', 'Interactive', 'International', 'Interval'],
      correctOptionIndex: 0,
      explanation: 'INT. menandakan bahwa adegan berlangsung di dalam ruangan (interior).',
    ),
    QuestionItem(
      id: 'ftv_008',
      questionText: 'Keterangan "EXT." pada baris slugline naskah skenario film merupakan singkatan dari:',
      options: ['Exterior (Luar Ruangan)', 'Extension', 'Extra', 'External'],
      correctOptionIndex: 0,
      explanation: 'EXT. menandakan adegan bertempat di luar ruangan (eksterior).',
    ),
    QuestionItem(
      id: 'ftv_009',
      questionText: 'Petunjuk ekspresi emosi atau tindakan singkat dalam tanda kurung di bawah nama tokoh sebelum dialog dinamakan:',
      options: ['Parenthetical', 'Slugline', 'Action line', 'Cue point'],
      correctOptionIndex: 0,
      explanation: 'Parenthetical memberi panduan intonasi atau aksi mikro bagi aktor saat mengucapkan dialog.',
    ),
    QuestionItem(
      id: 'ftv_010',
      questionText: 'Proses menguraikan naskah adegan demi adegan untuk mencatat kebutuhan pemain, properti, kostum, dan efek dinamakan:',
      options: ['Script Breakdown', 'Storyboard', 'Casting Call', 'Location Scouting'],
      correctOptionIndex: 0,
      explanation: 'Script breakdown menginventarisasi seluruh kebutuhan teknis dan logistik per adegan.',
    ),
    QuestionItem(
      id: 'ftv_011',
      questionText: 'Penanggung jawab estetika visual sinematik film yang memimpin tata cahaya dan kamera dinamakan:',
      options: ['Director of Photography (DoP) / Penata Kamera', 'Sutradara', 'Produser', 'Art Director'],
      correctOptionIndex: 0,
      explanation: 'DoP (Sinematografer) merancang komposisi visual, kamera, dan tata cahaya.',
    ),
    QuestionItem(
      id: 'ftv_012',
      questionText: 'Pemimpin artistik tertinggi dalam produksi film yang mengarahkan visi cerita dan keaktoran pemain dinamakan:',
      options: ['Sutradara (Director)', 'Produser Executif', 'Editor', 'Penata Suara'],
      correctOptionIndex: 0,
      explanation: 'Sutradara adalah pemegang komando kreatif dan penterjemah skenario ke bentuk audio-visual.',
    ),
    QuestionItem(
      id: 'ftv_013',
      questionText: 'Kru yang bertanggung jawab mengelola pendanaan, legalitas, dan keseluruhan manajemen produksi film dinamakan:',
      options: ['Produser (Producer)', 'Sutradara', 'Gaffer', 'Script Supervisor'],
      correctOptionIndex: 0,
      explanation: 'Produser mengawasi manajemen finansial, jadwal, dan bisnis produksi film.',
    ),
    QuestionItem(
      id: 'ftv_014',
      questionText: 'Kru yang bertugas memantau kontinuitas pakaian, tata rias, properti, dan posisi pemain antar-take adegan dinamakan:',
      options: ['Script Supervisor / Pencatat Kontinuitas', 'Line Producer', 'Clapper Operator', 'Still Photographer'],
      correctOptionIndex: 0,
      explanation: 'Script supervisor menjaga kontinuitas keselarasan adegan agar tidak bocor atau tidak cocok saat diedit.',
    ),
    QuestionItem(
      id: 'ftv_015',
      questionText: 'Kru yang bertanggung jawab mengatur jadwal syuting harian di lapangan dan memimpin panggil adegan adalah:',
      options: ['Asisten Sutradara I (1st AD)', 'DoP', 'Sound Mixer', 'Location Manager'],
      correctOptionIndex: 0,
      explanation: '1st AD mengendalikan kelancaran alur waktu dan kedisiplinan jadwal syuting di lokasi.',
    ),
    QuestionItem(
      id: 'ftv_016',
      questionText: 'Lensa kamera dengan panjang fokus pendek yang menghasilkan cakupan sudut pandang sangat luas dinamakan:',
      options: ['Lensa Wide-Angle', 'Lensa Telephoto', 'Lensa Normal', 'Lensa Macro'],
      correctOptionIndex: 0,
      explanation: 'Lensa Wide memperluas bidang pandang visual serta memberi kesan ruang terasa luas.',
    ),
    QuestionItem(
      id: 'ftv_017',
      questionText: 'Lensa kamera dengan panjang fokus tetap (fixed) yang umumnya menghasilkan ketajaman gambar tinggi dinamakan:',
      options: ['Lensa Prime (Fix)', 'Lensa Zoom', 'Lensa Anamorphic', 'Lensa Fisheye'],
      correctOptionIndex: 0,
      explanation: 'Lensa Prime tidak memiliki fungsi zoom mekanis sehingga optiknya sangat tajam dan terang.',
    ),
    QuestionItem(
      id: 'ftv_018',
      questionText: 'Lensa kamera yang panjang fokusnya dapat diubah fleksibel dari sudut lebar ke telephoto dinamakan:',
      options: ['Lensa Zoom', 'Lensa Prime', 'Lensa Tilt-Shift', 'Lensa Pin'],
      correctOptionIndex: 0,
      explanation: 'Lensa Zoom memungkinkan perubahan focal length tanpa mengganti fisik lensa.',
    ),
    QuestionItem(
      id: 'ftv_019',
      questionText: 'Rasio standar perbandingan lebar dan tinggi layar pada format video televisi HD modern adalah:',
      options: ['16:9', '4:3', '21:9', '1:1'],
      correctOptionIndex: 0,
      explanation: '16:9 (widescreen) adalah standar aspek rasio internasional penyiaran HDTV.',
    ),
    QuestionItem(
      id: 'ftv_020',
      questionText: 'Standar kecepatan jumlah bingkai gambar per detik (frame rate) baku untuk estetika sinematik film bioskop adalah:',
      options: ['24 FPS', '30 FPS', '60 FPS', '12 FPS'],
      correctOptionIndex: 0,
      explanation: '24 FPS adalah standar motion blur sinematik film bioskop sejak era film pita.',
    ),
    QuestionItem(
      id: 'ftv_021',
      questionText: 'Tipe bidang pandang shot kamera yang menampilkan luasnya lanskap lokasi untuk memperkenalkan latar tempat adegan dinamakan:',
      options: ['Establishing Shot / Extreme Long Shot', 'Close-Up', 'Medium Shot', 'Over The Shoulder'],
      correctOptionIndex: 0,
      explanation: 'Establishing shot memberi konteks orientasi ruang tempat peristiwa adegan berlangsung.',
    ),
    QuestionItem(
      id: 'ftv_022',
      questionText: 'Tipe bidang pandang kamera yang menampilkan tubuh tokoh dari kepala hingga pinggang dinamakan:',
      options: ['Medium Shot', 'Long Shot', 'Extreme Close-Up', 'Full Shot'],
      correctOptionIndex: 0,
      explanation: 'Medium Shot menampilkan interaksi aksi tokoh sekaligus latar sekitar secara seimbang.',
    ),
    QuestionItem(
      id: 'ftv_023',
      questionText: 'Tipe bidang pandang kamera yang fokus membingkai dekat ekspresi wajah karakter dinamakan:',
      options: ['Close-Up', 'Extreme Long Shot', 'Medium Long Shot', 'Dutch Angle'],
      correctOptionIndex: 0,
      explanation: 'Close-Up menegaskan emosi dan ekspresi emosional karakter secara intens.',
    ),
    QuestionItem(
      id: 'ftv_024',
      questionText: 'Tipe shot kamera sangat dekat yang hanya menampilkan detail spesifik objek (seperti mata atau tulisan surat) dinamakan:',
      options: ['Extreme Close-Up (ECU)', 'Medium Shot', 'Bird Eye Shot', 'Wide Shot'],
      correctOptionIndex: 0,
      explanation: 'Extreme Close-Up memperbesar detail sangat mikro untuk perhatian dramatis.',
    ),
    QuestionItem(
      id: 'ftv_025',
      questionText: 'Pengambilan gambar dari balik bahu satu karakter mengarah ke lawan bicaranya dinamakan shot:',
      options: ['Over The Shoulder (OTS)', 'Point of View (POV)', 'Two Shot', 'Cutaway'],
      correctOptionIndex: 0,
      explanation: 'OTS memperlihatkan percakapan dialog dari sudut pandang pembicara di seberang bahu.',
    ),
    QuestionItem(
      id: 'ftv_026',
      questionText: 'Pergerakan menggelengkan kamera ke kanan atau ke kiri secara horizontal pada porosnya dinamakan:',
      options: ['Pan (Panning)', 'Tilt (Tilting)', 'Dolly', 'Zoom'],
      correctOptionIndex: 0,
      explanation: 'Panning adalah gerak horizontal kamera pada poros statis.',
    ),
    QuestionItem(
      id: 'ftv_027',
      questionText: 'Pergerakan mendongak atau menundukkan kamera secara vertikal pada porosnya dinamakan:',
      options: ['Tilt (Tilting)', 'Pan (Panning)', 'Pedestal', 'Roll'],
      correctOptionIndex: 0,
      explanation: 'Tilting adalah gerak vertikal mengangguk/mendongak kamera pada tempatnya.',
    ),
    QuestionItem(
      id: 'ftv_028',
      questionText: 'Pergerakan seluruh badan kamera mendekati atau menjauhi objek di atas roda/rel dinamakan:',
      options: ['Dolly (Dolly In / Dolly Out)', 'Zoom', 'Pan', 'Tilt'],
      correctOptionIndex: 0,
      explanation: 'Dolly fisik kamera bergerak secara nyata mendekat (Dolly In) atau menjauh (Dolly Out).',
    ),
    QuestionItem(
      id: 'ftv_029',
      questionText: 'Alat penyeimbang kamera mekanis berbahan rompi beban yang menjaga rekaman berjalan/berlari tetap mulus mulus bebas guncangan adalah:',
      options: ['Steadicam', 'Tripod', 'Monopod', 'Slider'],
      correctOptionIndex: 0,
      explanation: 'Steadicam meredam guncangan langkah kaki operator kamera saat bergerak.',
    ),
    QuestionItem(
      id: 'ftv_030',
      questionText: 'Pergerakan kamera melayang dari ketinggian menggunakan lengan tuas panjang dinamakan shot:',
      options: ['Crane / Jib Shot', 'Handheld Shot', 'Dolly Shot', 'Static Shot'],
      correctOptionIndex: 0,
      explanation: 'Crane/Jib menggerakkan kamera secara melayang bebas di udara.',
    ),
    QuestionItem(
      id: 'ftv_031',
      questionText: 'Teknik dasar penataan cahaya sinematografi "Three-Point Lighting" terdiri dari tiga lampu yaitu:',
      options: ['Key Light, Fill Light, dan Back Light', 'Spot Light, Flood Light, dan Strobe Light', 'Top Light, Side Light, dan Bottom Light', 'Red Light, Green Light, dan Blue Light'],
      correctOptionIndex: 0,
      explanation: 'Three-Point Lighting memanfaatkan Key Light (utama), Fill Light (pengisi bayangan), dan Back Light (pembatas latar).',
    ),
    QuestionItem(
      id: 'ftv_032',
      questionText: 'Sumber pencahayaan utama yang paling terang menyinari objek dalam Three-Point Lighting dinamakan:',
      options: ['Key Light', 'Fill Light', 'Back Light', 'Practical Light'],
      correctOptionIndex: 0,
      explanation: 'Key Light memberikan pencahayaan dominan dan menentukan sudut pencahayaan utama.',
    ),
    QuestionItem(
      id: 'ftv_033',
      questionText: 'Lampu sekunder yang digunakan untuk melembutkan atau mengurangi bayangan pekat ciptaan Key Light dinamakan:',
      options: ['Fill Light', 'Key Light', 'Rim Light', 'Kicker'],
      correctOptionIndex: 0,
      explanation: 'Fill Light menerangi area bayangan agar kontras tidak terlalu keras.',
    ),
    QuestionItem(
      id: 'ftv_034',
      questionText: 'Cahaya dari arah belakang objek yang berfungsi memberi garis batas terang untuk memisahkan objek dari latar belakang dinamakan:',
      options: ['Back Light / Hair Light', 'Fill Light', 'Ambient Light', 'Bounce Light'],
      correctOptionIndex: 0,
      explanation: 'Back Light menciptakan garis kilau (rim light) memisahkan subjek dari background.',
    ),
    QuestionItem(
      id: 'ftv_035',
      questionText: 'Temperatur warna cahaya matahari di siang hari (daylight) memiliki standar nilai sekitar:',
      options: ['5600 Kelvin', '3200 Kelvin', '2000 Kelvin', '8000 Kelvin'],
      correctOptionIndex: 0,
      explanation: 'Standard daylight bernilai 5600K dengan spektrum warna cenderung kebiruan netral.',
    ),
    QuestionItem(
      id: 'ftv_036',
      questionText: 'Temperatur warna pencahayaan lampu interior bohlam pijar (tungsten) memiliki standar nilai sekitar:',
      options: ['3200 Kelvin', '5600 Kelvin', '6500 Kelvin', '1200 Kelvin'],
      correctOptionIndex: 0,
      explanation: 'Tungsten berkisar pada 3200K dengan spektrum warna kekuningan/oranye hangat.',
    ),
    QuestionItem(
      id: 'ftv_037',
      questionText: 'Bahan tembus cahaya yang dipasang di depan lampu untuk melembutkan karakter pendaran cahaya dinamakan:',
      options: ['Diffuser (Softbox / Frost Filter)', 'Reflector', 'Gobo', 'Barn Door'],
      correctOptionIndex: 0,
      explanation: 'Diffuser menyebarkan berkas cahaya keras sehingga bayangan menjadi lembut.',
    ),
    QuestionItem(
      id: 'ftv_038',
      questionText: 'Papan pantul berbentuk bundar atau persegi yang memantulkan kembali cahaya ke arah subjek dinamakan:',
      options: ['Reflector', 'Diffuser', 'Snoot', 'C-stand'],
      correctOptionIndex: 0,
      explanation: 'Reflector memantulkan cahaya pendar alami atau lampu tanpa menambah lampu baru.',
    ),
    QuestionItem(
      id: 'ftv_039',
      questionText: 'Gaya pencahayaan kontras tinggi berkesan dramatis misterius dengan dominasi bayangan pekat dinamakan:',
      options: ['Low-Key Lighting', 'High-Key Lighting', 'Flat Lighting', 'Natural Lighting'],
      correctOptionIndex: 0,
      explanation: 'Low-Key Lighting didominasi area gelap dramatis (sering dipakai di film Noir/Horor).',
    ),
    QuestionItem(
      id: 'ftv_040',
      questionText: 'Gaya pencahayaan serba terang benderang dengan bayangan minimal yang sering dipakai pada komedi/sitkom TV dinamakan:',
      options: ['High-Key Lighting', 'Low-Key Lighting', 'Chiaroscuro', 'Silhouette Lighting'],
      correctOptionIndex: 0,
      explanation: 'High-Key Lighting meminimalisasi bayangan dan menghasilkan tampilan visual terang ceria.',
    ),
    QuestionItem(
      id: 'ftv_041',
      questionText: 'Perekaman tiruan efek suara fisik (seperti langkah kaki, derak pintu, gesekan baju) yang dibuat khusus di studio bunyi dinamakan:',
      options: ['Foley Sound', 'ADR', 'Room Tone', 'Score'],
      correctOptionIndex: 0,
      explanation: 'Foley artist menirukan efek rekaman gerak fisik tubuh untuk menghidupkan audio film.',
    ),
    QuestionItem(
      id: 'ftv_042',
      questionText: 'Proses perekaman ulang dialog pemain di studio untuk menggantikan trek audio lokasi yang bising dinamakan:',
      options: ['ADR (Automated Dialogue Replacement)', 'Foley', 'Dubbing Bahasa', 'Sound Mixing'],
      correctOptionIndex: 0,
      explanation: 'ADR merekam ulang dialog aktor secara presisi selaras dengan gerakan bibir di layar.',
    ),
    QuestionItem(
      id: 'ftv_043',
      questionText: 'Rekaman suara keheningan alami atmosfer lokasi syuting yang digunakan untuk menjembatani potongan audio editing dinamakan:',
      options: ['Room Tone / Ambient Sound', 'Foley', 'Sound Effect', 'Music Bed'],
      correctOptionIndex: 0,
      explanation: 'Room tone merekam suara atmosfer ruang agar transisi pemotongan suara tidak bocor mati.',
    ),
    QuestionItem(
      id: 'ftv_044',
      questionText: 'Mikrofon terarah panjang yang dipasang di ujung tongkat pengatur untuk merekam suara dialog dari jarak aman dinamakan:',
      options: ['Boom Mic / Shotgun Mic', 'Lavalier Mic', 'Boundary Mic', 'Dynamic Studio Mic'],
      correctOptionIndex: 0,
      explanation: 'Shotgun mic di atas boom pole menangkap suara fokus dari arah depan tanpa masuk bingkai kamera.',
    ),
    QuestionItem(
      id: 'ftv_045',
      questionText: 'Mikrofon kecil tanpa kabel yang disematkan di balik kerah baju aktor dinamakan:',
      options: ['Lavalier Mic (Clip-On)', 'Boom Mic', 'Condenser Studio Mic', 'Ribbon Mic'],
      correctOptionIndex: 0,
      explanation: 'Lavalier (clip-on) ditempelkan dekat mulut aktor secara tersembunyi.',
    ),
    QuestionItem(
      id: 'ftv_046',
      questionText: 'Suara yang sumbernya berasal dari dalam dunia cerita film (dapat didengar oleh karakter dalam scene) dinamakan:',
      options: ['Suara Diegetik (Diegetic Sound)', 'Suara Non-Diegetik', 'Voice Over', 'Background Score'],
      correctOptionIndex: 0,
      explanation: 'Diegetic sound adalah suara dari alam cerita (dialog antar-karakter, radio di lokasi, dll.).',
    ),
    QuestionItem(
      id: 'ftv_047',
      questionText: 'Suara musik latar atau suara narator narasi yang hanya didengar oleh penonton dan tidak didengar karakter dinamakan:',
      options: ['Suara Non-Diegetik (Non-Diegetic Sound)', 'Suara Diegetik', 'Foley Sound', 'Room Tone'],
      correctOptionIndex: 0,
      explanation: 'Non-diegetic sound hadir di luar dunia cerita (seperti ilustrasi musik pembangun mood).',
    ),
    QuestionItem(
      id: 'ftv_048',
      questionText: 'Kru yang bertanggung jawab merekam audio dan menjaga kualitas level suara selama syuting berlangsung dinamakan:',
      options: ['Sound Recordist / Production Sound Mixer', 'Boom Operator', 'Foley Artist', 'Sound Designer'],
      correctOptionIndex: 0,
      explanation: 'Production sound mixer mengontrol penerimaan rekaman suara di lokasi.',
    ),
    QuestionItem(
      id: 'ftv_049',
      questionText: 'Kru yang memegang dan mengarahkan tongkat pengatur mikrofon mengikuti posisi bergerak pemain dinamakan:',
      options: ['Boom Operator', 'Sound Mixer', 'Gaffer', 'Best Boy'],
      correctOptionIndex: 0,
      explanation: 'Boom operator mengarahkan posisi mikrofon tepat di atas pemain tanpa bocor ke gambar.',
    ),
    QuestionItem(
      id: 'ftv_050',
      questionText: 'Pemotongan dan penyambungan langsung dari akhir satu shot ke awal shot berikutnya tanpa efek dinamakan:',
      options: ['Cut', 'Dissolve', 'Fade Out', 'Wipe'],
      correctOptionIndex: 0,
      explanation: 'Cut adalah teknik transisi penyuntingan paling dasar dan paling sering digunakan.',
    ),
    QuestionItem(
      id: 'ftv_051',
      questionText: 'Transisi di mana gambar adegan perlahan meredup menjadi layar hitam penuh dinamakan:',
      options: ['Fade Out', 'Fade In', 'Dissolve', 'Cross-cut'],
      correctOptionIndex: 0,
      explanation: 'Fade Out mengakhiri atau menutup adegan menuju warna layar hitam.',
    ),
    QuestionItem(
      id: 'ftv_052',
      questionText: 'Transisi di mana shot pertama perlahan menghilang bersamaan dengan bertumpuk munculnya shot kedua dinamakan:',
      options: ['Dissolve', 'Cut', 'Jump Cut', 'Iris'],
      correctOptionIndex: 0,
      explanation: 'Dissolve meleburkan dua adegan secara halus untuk mengindikasikan berlalunya waktu.',
    ),
    QuestionItem(
      id: 'ftv_053',
      questionText: 'Pemotongan gambar pada objek yang sama dengan sudut pandang yang hampir serupa sehingga berkesan loncat patah dinamakan:',
      options: ['Jump Cut', 'Match Cut', 'Smash Cut', 'L-Cut'],
      correctOptionIndex: 0,
      explanation: 'Jump cut memotong durasi waktu pada sudut kamera yang hampir sama secara menghentak.',
    ),
    QuestionItem(
      id: 'ftv_054',
      questionText: 'Penyuntingan bolak-balik antara dua peristiwa adegan berbeda yang terjadi secara bersamaan di tempat terpisah dinamakan:',
      options: ['Cross-Cutting / Parallel Editing', 'Montage', 'Cutaway', 'Insert Cut'],
      correctOptionIndex: 0,
      explanation: 'Cross-cutting (Parallel Editing) membangun ketegangan dari 2 alur sejajar.',
    ),
    QuestionItem(
      id: 'ftv_055',
      questionText: 'Pemotongan adegan di mana akhir shot pertama dan awal shot kedua dihubungkan oleh kesamaan bentuk visual atau gerakan dinamakan:',
      options: ['Match Cut', 'Jump Cut', 'Fade', 'J-Cut'],
      correctOptionIndex: 0,
      explanation: 'Match Cut menyambung dua lokasi berlainan lewat kemiripan komposisi visual.',
    ),
    QuestionItem(
      id: 'ftv_056',
      questionText: 'Teori perakitan penyuntingan film asal Soviet yang menggabungkan dua shot bertolak belakang untuk melahirkan ide baru dinamakan:',
      options: ['Teori Montase (Montage Theory)', 'Continuity Editing', 'Realism Editing', 'Auteur Theory'],
      correctOptionIndex: 0,
      explanation: 'Teori Montase (dipelopori Sergei Eisenstein) benturan 2 gambar melahirkan makna baru.',
    ),
    QuestionItem(
      id: 'ftv_057',
      questionText: 'Tahap penyusunan potongan-potongan adegan awal film yang masih kasar sesuai urutan naskah dinamakan:',
      options: ['Rough Cut', 'Fine Cut', 'Picture Lock', 'Master Cut'],
      correctOptionIndex: 0,
      explanation: 'Rough Cut adalah editan pertama film sebelum dirapikan lebih rinci.',
    ),
    QuestionItem(
      id: 'ftv_058',
      questionText: 'Keputusan final di mana urutan dan durasi seluruh potongan gambar film sudah terkunci dan siap diisi sound/color dinamakan:',
      options: ['Picture Lock / Lock Picture', 'Offline Edit', 'Rough Cut', 'Final Render'],
      correctOptionIndex: 0,
      explanation: 'Picture Lock mengunci potongan visual agar pekerjaan tata suara dan penataan warna tidak berubah lagi.',
    ),
    QuestionItem(
      id: 'ftv_059',
      questionText: 'Proses penyesuaian nuansa warna, kontras, dan mood estetika warna visual seluruh adegan film dinamakan:',
      options: ['Color Grading', 'Color Correction', 'Chroma Key', 'White Balance'],
      correctOptionIndex: 0,
      explanation: 'Color grading memberikan sentuhan atmosfer gaya visual warna khas film.',
    ),
    QuestionItem(
      id: 'ftv_060',
      questionText: 'Papan petunjuk bertuliskan nomor scene dan take yang ditepuk di depan kamera untuk menyelaraskan audio dan gambar dinamakan:',
      options: ['Clapperboard / Slate', 'Cue Card', 'Storyboard', 'Marker'],
      correctOptionIndex: 0,
      explanation: 'Suara tepukan clapperboard membantu menyelaraskan (sync) gelombang audio dan bingkai gambar.',
    ),
    QuestionItem(
      id: 'ftv_061',
      questionText: 'Ruang kendali utama di stasiun TV di mana pengarah acara dan vision mixer mengendalikan kamera studio siaran langsung dinamakan:',
      options: ['Studio Control Room (SCR)', 'Master Control Room (MCR)', 'Editing Bay', 'Dubbing Room'],
      correctOptionIndex: 0,
      explanation: 'SCR tempat sutradara TV memandu siaran langsung dari kamera studio.',
    ),
    QuestionItem(
      id: 'ftv_062',
      questionText: 'Ruang kendali akhir stasiun TV yang menangani transmisi pemancaran sinyal siaran ke satelit/antena pemirsa dinamakan:',
      options: ['Master Control Room (MCR)', 'Studio Control Room (SCR)', 'Newsroom', 'VTR Room'],
      correctOptionIndex: 0,
      explanation: 'MCR mengawasi kualitas akhir sinyal siaran stasiun televisi.',
    ),
    QuestionItem(
      id: 'ftv_063',
      questionText: 'Petugas studio TV yang mengoperasikan mesin sakelar pemindah tampilan shot kamera siaran langsung dinamakan:',
      options: ['Vision Mixer / Switcher Operator', 'Floor Director', 'Audio Engineer', 'Lighting Director'],
      correctOptionIndex: 0,
      explanation: 'Vision Mixer mengeksekusi perpindahan gambar kamera atas instruksi sutradara siaran TV.',
    ),
    QuestionItem(
      id: 'ftv_064',
      questionText: 'Perangkat layar kaca di depan lensa kamera yang memantulkan teks skenario untuk dibaca oleh presenter berita TV dinamakan:',
      options: ['Teleprompter', 'Monitor Studio', 'Viewfinder', 'Teletext'],
      correctOptionIndex: 0,
      explanation: 'Teleprompter membantu presenter membaca berita sambil tetap menatap kamera.',
    ),
    QuestionItem(
      id: 'ftv_065',
      questionText: 'Lembar jadwal urutan susunan segmen tayangan beserta durasinya pada siaran langsung siaran TV dinamakan:',
      options: ['Rundown', 'Script Breakdown', 'Call Sheet', 'Cue Card'],
      correctOptionIndex: 0,
      explanation: 'Rundown memandu durasi menit demi menit siaran TV.',
    ),
    QuestionItem(
      id: 'ftv_066',
      questionText: 'Laporan berita siaran langsung oleh jurnalis/reporter yang disiarkan seketika dari lokasi kejadian dinamakan:',
      options: ['Live Report', 'Press Release', 'Voice Over', 'Talkshow'],
      correctOptionIndex: 0,
      explanation: 'Live report menyiarkan peristiwa berita langsung dari lapangan.',
    ),
    QuestionItem(
      id: 'ftv_067',
      questionText: 'Isyarat atau aba-aba tangan dari Floor Director kepada pembawa acara TV untuk memulai bicaranya dinamakan:',
      options: ['Cue', 'Clap', 'Prompt', 'Standby'],
      correctOptionIndex: 0,
      explanation: 'Cue memberikan tanda waktu mulainya aksi atau dialog.',
    ),
    QuestionItem(
      id: 'ftv_068',
      questionText: 'Sistem pengambikan gambar siaran acara TV menggunakan beberapa kamera dari pelbagai sudut bersamaan dinamakan:',
      options: ['Multi-Camera Setup', 'Single-Camera Setup', 'B-Roll Setup', 'POV Setup'],
      correctOptionIndex: 0,
      explanation: 'Multi-camera merekam sudut berbeda secara simultan untuk siaran TV.',
    ),
    QuestionItem(
      id: 'ftv_069',
      questionText: 'Penyiaran acara siaran televisi yang ditayangkan seketika bersamaan saat peristiwa berlangsung dinamakan:',
      options: ['Live Broadcast (Siaran Langsung)', 'Delayed Broadcast', 'Rerun', 'Off-air'],
      correctOptionIndex: 0,
      explanation: 'Live Broadcast menyiarkan tayangan secara waktu nyata (real-time).',
    ),
    QuestionItem(
      id: 'ftv_070',
      questionText: 'Genre film fiksi berkonsep misteri kriminal dengan atmosfer visual serba gelap dan sinis dinamakan:',
      options: ['Film Noir', 'Film Musikal', 'Slapstick', 'Docudrama'],
      correctOptionIndex: 0,
      explanation: 'Film Noir berciri khas visual kontras tinggi, kejahatan, dan atmosfer kelam.',
    ),
    QuestionItem(
      id: 'ftv_071',
      questionText: 'Kategori film yang menyajikan kisah rekaan berdasar fakta kenyataan kehidupan nyata tanpa aktor rekaan fiksi adalah:',
      options: ['Film Dokumen (Documentary)', 'Film Fiksi', 'Film Animasi', 'Film Eksperimental'],
      correctOptionIndex: 0,
      explanation: 'Film dokumenter merekam fakta dan realitas non-fiksi.',
    ),
    QuestionItem(
      id: 'ftv_072',
      questionText: 'Kategori pembuatan film yang membebaskan eksperimen seni visual tanpa terikat pola alur cerita konvensional dinamakan:',
      options: ['Film Eksperimental', 'Film Komersial', 'Film Mainstream', 'Film Serial'],
      correctOptionIndex: 0,
      explanation: 'Film eksperimental menantang narasi standar untuk mengeksplorasi estetika sinema.',
    ),
    QuestionItem(
      id: 'ftv_073',
      questionText: 'Tokoh bersaudara asal Prancis yang dianggap sebagai pelopor pemutaran film komersial pertama di dunia tahun 1895 adalah:',
      options: ['Lumière Brothers (Auguste & Louis)', 'Wright Brothers', 'Coen Brothers', 'Warner Brothers'],
      correctOptionIndex: 0,
      explanation: 'Lumière Brothers memutar film pertamanya "La Sortie de l\'usine Lumière à Lyon" tahun 1895.',
    ),
    QuestionItem(
      id: 'ftv_074',
      questionText: 'Sutradara Prancis pelopor penggunaan efek khusus visual trik sinema lewat filmnya "A Trip to the Moon" (1902) adalah:',
      options: ['Georges Méliès', 'Alice Guy-Blaché', 'D.W. Griffith', 'Thomas Edison'],
      correctOptionIndex: 0,
      explanation: 'Georges Méliès adalah bapak efek visual fiksi ilmiah pertama dalam film.',
    ),
    QuestionItem(
      id: 'ftv_075',
      questionText: 'Tokoh aktor dan sutradara legendaris film bisu komedi dunia dengan karakter khas ikonik "The Tramp" adalah:',
      options: ['Charlie Chaplin', 'Buster Keaton', 'Harold Lloyd', 'Stan Laurel'],
      correctOptionIndex: 0,
      explanation: 'Charlie Chaplin adalah maestro komedi sinema bisu.',
    ),
    QuestionItem(
      id: 'ftv_076',
      questionText: 'Sutradara legendaris berjuluk "Master of Suspense" yang menggarap film klasik "Psycho" dan "Rear Window" adalah:',
      options: ['Alfred Hitchcock', 'Stanley Kubrick', 'Francis Ford Coppola', 'Steven Spielberg'],
      correctOptionIndex: 0,
      explanation: 'Alfred Hitchcock memelopori teknik suspens dan ketegangan psikologis sinema.',
    ),
    QuestionItem(
      id: 'ftv_077',
      questionText: 'Sutradara muda pembuat film "Citizen Kane" (1941) yang mendobrak struktur cerita non-linear dan sudut kamera ekstrem adalah:',
      options: ['Orson Welles', 'Martin Scorsese', 'Akira Kurosawa', 'Federico Fellini'],
      correctOptionIndex: 0,
      explanation: 'Orson Welles menciptakan Citizen Kane yang dianggap salah satu karya sinema terbaik sepanjang masa.',
    ),
    QuestionItem(
      id: 'ftv_078',
      questionText: 'Tokoh Bapak Perfilman Indonesia yang menyutradarai film "Darah dan Doa" (1950) adalah:',
      options: ['Usmar Ismail', 'Djamaluddin Malik', 'Teguh Karya', 'Sumanjaya'],
      correctOptionIndex: 0,
      explanation: 'Usmar Ismail diakui sebagai Bapak Perfilman Nasional Indonesia.',
    ),
    QuestionItem(
      id: 'ftv_079',
      questionText: 'Hari Film Nasional Indonesia diperingati setiap tahunnya pada tanggal:',
      options: ['30 Maret', '17 Agustus', '28 Oktober', '2 Mei'],
      correctOptionIndex: 0,
      explanation: '30 Maret diperingati sebagai Hari Film Nasional bertepatan syuting hari pertama film Darah dan Doa.',
    ),
    QuestionItem(
      id: 'ftv_080',
      questionText: 'Lembaga independen di Indonesia yang bertugas menguji dan memutus kelayakan edar tayangan film dinamakan:',
      options: ['LSF (Lembaga Sensor Film)', 'KPI (Komisi Penyiaran Indonesia)', 'PARFI', 'KFT'],
      correctOptionIndex: 0,
      explanation: 'LSF bertugas menyensor dan memberikan klafikasi usia tayang film di Indonesia.',
    ),
    QuestionItem(
      id: 'ftv_081',
      questionText: 'Kategori klasifikasi usia penonton LSF untuk film yang aman ditonton oleh seluruh lapisan umur dinamakan:',
      options: ['SU (Semua Umur)', '13+', '17+', '21+'],
      correctOptionIndex: 0,
      explanation: 'Kode SU menandakan film dapat ditonton oleh semua umur tanpa batasan.',
    ),
    QuestionItem(
      id: 'ftv_082',
      questionText: 'Kategori klasifikasi usia LSF untuk penonton berumur 13 tahun ke atas dinamakan:',
      options: ['13+', 'SU', '17+', '21+'],
      correctOptionIndex: 0,
      explanation: 'Kode 13+ ditujukan untuk kelompok usia remaja.',
    ),
    QuestionItem(
      id: 'ftv_083',
      questionText: 'Kategori klasifikasi usia LSF untuk penonton dewasa berusia 17 tahun ke atas dinamakan:',
      options: ['17+', '13+', 'SU', 'BO'],
      correctOptionIndex: 0,
      explanation: 'Kode 17+ ditujukan untuk penonton tingkat dewasa.',
    ),
    QuestionItem(
      id: 'ftv_084',
      questionText: 'Proses perizinan legal untuk memakai karya lagu atau materi ciptaan pihak lain dalam film dinamakan:',
      options: ['Copyright Clearance', 'Public Domain', 'Fair Use Notice', 'Piracy Clearance'],
      correctOptionIndex: 0,
      explanation: 'Copyright Clearance memastikan penggunaan materi hak cipta telah berizin secara sah.',
    ),
    QuestionItem(
      id: 'ftv_085',
      questionText: 'Ajang pemutaran film independen untuk mempertemukan pembuat film dengan kurator, pengritik, dan distributor dinamakan:',
      options: ['Festival Film', 'Bioskop XXI', 'Pasar Malam', 'Press Conference'],
      correctOptionIndex: 0,
      explanation: 'Festival Film merupakan wadah apresiasi dan distribusi film independen.',
    ),
    QuestionItem(
      id: 'ftv_086',
      questionText: 'Penghargaan piala sinema tertinggi bagi perfilman Indonesia dalam Festival Film Indonesia (FFI) dinamakan:',
      options: ['Piala Citra', 'Piala Maya', 'Piala Oscar', 'Piala Vidia'],
      correctOptionIndex: 0,
      explanation: 'Piala Citra adalah anugerah penghargaan tertinggi industri film Indonesia.',
    ),
    QuestionItem(
      id: 'ftv_087',
      questionText: 'Ajang penghargaan sinema bioskop paling bergengsi di Amerika Serikat yang diselenggarakan oleh AMPAS dinamakan:',
      options: ['Academy Awards (Oscar)', 'Grammy Awards', 'Emmy Awards', 'Tony Awards'],
      correctOptionIndex: 0,
      explanation: 'Academy Awards (Piala Oscar) adalah anugerah film paling ternama di AS.',
    ),
    QuestionItem(
      id: 'ftv_088',
      questionText: 'Festival film internasional kelas dunia yang diselenggarakan setiap tahun di Prancis dinamakan:',
      options: ['Cannes Film Festival', 'Sundance Film Festival', 'Venice Film Festival', 'Berlin International Film Festival'],
      correctOptionIndex: 0,
      explanation: 'Cannes Film Festival merupakan festival film bergengsi dunia di Prancis.',
    ),
    QuestionItem(
      id: 'ftv_089',
      questionText: 'Penghargaan piala tertinggi untuk film terbaik di Festival Film Cannes dinamakan:',
      options: ['Palme d\'Or (Palma Emas)', 'Golden Bear', 'Golden Lion', 'Crystal Globe'],
      correctOptionIndex: 0,
      explanation: 'Palme d\'Or merupakan piala penghargaan tertinggi di Festival Film Cannes.',
    ),
    QuestionItem(
      id: 'ftv_090',
      questionText: 'Lembar jadwal detail harian untuk seluruh kru dan pemain yang memuat jam panggilan lokasi dinamakan:',
      options: ['Call Sheet', 'Rundown', 'Script Breakdown', 'Deal Memo'],
      correctOptionIndex: 0,
      explanation: 'Call sheet dibagikan setiap malam berisi jadwal lokasi dan jam syuting besoknya.',
    ),
    QuestionItem(
      id: 'ftv_091',
      questionText: 'Gambar denah susunan tata letak posisi kamera, lampu, dan pergerakan pemain di tempat syuting dinamakan:',
      options: ['Floor Plan', 'Storyboard', 'Aspect Ratio Diagram', 'Set Model'],
      correctOptionIndex: 0,
      explanation: 'Floor plan memetakan pemosisian peralatan dan pemain pada denah lokasi.',
    ),
    QuestionItem(
      id: 'ftv_092',
      questionText: 'Teknik pengisolasian warna layar (biasanya hijau atau biru) untuk digantikan gambar latar visual efek digital dinamakan:',
      options: ['Chroma Key (Green Screen)', 'Rotoscoping', 'Motion Capture', 'Matte Painting'],
      correctOptionIndex: 0,
      explanation: 'Chroma Key mengganti latar warna hijau/biru dengan latar belakang digital lain.',
    ),
    QuestionItem(
      id: 'ftv_093',
      questionText: 'Efek visual kamera di mana objek terdorong maju sementara latarnya meluas akibat kombinasi gerak dolly dan zoom dinamakan:',
      options: ['Dolly Zoom (Vertigo Effect)', 'Bullet Time', 'Whip Pan', 'Crash Zoom'],
      correctOptionIndex: 0,
      explanation: 'Dolly Zoom (Vertigo Effect) memberikan ilusi distorsi latar belakang yang spektakuler.',
    ),
    QuestionItem(
      id: 'ftv_094',
      questionText: 'Teknik perekaman video kecepatan tinggi yang saat diputar kembali memperlihatkan pergerakan sangat lambat dinamakan:',
      options: ['Slow Motion', 'Time-Lapse', 'Stop Motion', 'Hyperlapse'],
      correctOptionIndex: 0,
      explanation: 'Slow Motion merekam dengan FPS tinggi untuk memperlambat tempo gerakan.',
    ),
    QuestionItem(
      id: 'ftv_095',
      questionText: 'Teknik perekaman foto berinterval panjang yang disatukan sehingga gerakan awan/bintang tampak berjalan cepat dinamakan:',
      options: ['Time-Lapse', 'Slow Motion', 'Freeze Frame', 'Long Exposure'],
      correctOptionIndex: 0,
      explanation: 'Time-lapse mempercepat laju durasi waktu lama menjadi tayangan singkat.',
    ),
    QuestionItem(
      id: 'ftv_096',
      questionText: 'Istilah untuk satu pengambilan gambar adegan panjang secara utuh tanpa ada pemotongan editing dinamakan:',
      options: ['Long Take / One-Shot', 'Montage', 'Jump Cut', 'Insert Shot'],
      correctOptionIndex: 0,
      explanation: 'Long Take merekam seluruh rangkaian adegan terus-menerus dalam satu kali take.',
    ),
    QuestionItem(
      id: 'ftv_097',
      questionText: 'Istilah untuk pengulangan pengambilan rekaman shot kamera yang sama dinamakan:',
      options: ['Take / Retake', 'Shot', 'Scene', 'Sequence'],
      correctOptionIndex: 0,
      explanation: 'Take adalah variasi rekaman shot yang diulang hingga mendapatkan hasil terbaik.',
    ),
    QuestionItem(
      id: 'ftv_098',
      questionText: 'Kru yang memimpin perancangan estetika latar dekorasi, properti, dan perwarnaan set film dinamakan:',
      options: ['Penata Artistik (Art Director)', 'Penata Busana', 'Property Master', 'Set Dresser'],
      correctOptionIndex: 0,
      explanation: 'Art Director bertanggung jawab atas tampilan fisik visual latar dan dekorasi.',
    ),
    QuestionItem(
      id: 'ftv_099',
      questionText: 'Potongan gambar tambahan (seperti pemandangan kota atau objek reaksi) yang disisipkan untuk memperkaya adegan dinamakan:',
      options: ['B-Roll / Cutaway Shot', 'A-Roll', 'Master Shot', 'Establishing Shot'],
      correctOptionIndex: 0,
      explanation: 'B-Roll adalah rekaman pendukung yang disisipkan untuk melapisi narasi utama.',
    ),
    QuestionItem(
      id: 'ftv_100',
      questionText: 'Disiplin ilmu dan seni audio-visual yang mengintegrasikan penceritaan naratif gambar bergerak dan penyiaran dinamakan:',
      options: ['Film dan Televisi', 'Seni Musik', 'Fotografi Murni', 'Jurnalistik Cetak'],
      correctOptionIndex: 0,
      explanation: 'Film dan Televisi adalah cabang ilmu yang mempelajari seni naratif audio-visual sinema dan penyiaran.',
    ),
  ];
}
