import '../tes_seleksi_model.dart';

List<QuestionItem> getDkvQuestions() {
  return const [
    QuestionItem(
      id: 'dkv_001',
      questionText: 'Sistem warna RGB (Red, Green, Blue) paling tepat digunakan untuk media:',
      options: ['Digital dan layar monitor', 'Cetak majalah dan koran', 'Sablon kaos', 'Brosur dan pamphlet cetak'],
      correctOptionIndex: 0,
      explanation: 'RGB merupakan model warna berbasis cahaya (additive) yang digunakan pada perangkat digital/layar.',
    ),
    QuestionItem(
      id: 'dkv_002',
      questionText: 'Sistem warna CMYK (Cyan, Magenta, Yellow, Key/Black) digunakan untuk media:',
      options: ['Cetak (Printing)', 'Situs web dan aplikasi', 'Televisi dan monitor', 'Proyektor presentasi'],
      correctOptionIndex: 0,
      explanation: 'CMYK merupakan model warna subtractive yang digunakan untuk pencetakan fisik/tinta.',
    ),
    QuestionItem(
      id: 'dkv_003',
      questionText: 'Jarak spasial antar huruf secara individu dalam tipografi dinamakan:',
      options: ['Kerning', 'Tracking', 'Leading', 'Baseline'],
      correctOptionIndex: 0,
      explanation: 'Kerning adalah pengaturan jarak antar dua karakter huruf tertentu agar tampak seimbang.',
    ),
    QuestionItem(
      id: 'dkv_004',
      questionText: 'Jarak antar baris teks secara vertikal dalam tata letak tipografi dinamakan:',
      options: ['Leading', 'Kerning', 'Tracking', 'Alignment'],
      correctOptionIndex: 0,
      explanation: 'Leading (line spacing) mengontrol ruang vertikal antar baris teks.',
    ),
    QuestionItem(
      id: 'dkv_005',
      questionText: 'Penyesuaian jarak antar huruf secara serentak dalam satu kata atau blok teks disebut:',
      options: ['Tracking', 'Kerning', 'Leading', 'Padding'],
      correctOptionIndex: 0,
      explanation: 'Tracking memperlonggar atau memperketat jarak antar seluruh karakter dalam satu rentang teks.',
    ),
    QuestionItem(
      id: 'dkv_006',
      questionText: 'Jenis huruf yang memiliki sirip/kaitan kecil di setiap ujung guratan stroke dinamakan:',
      options: ['Serif', 'Sans-serif', 'Script', 'Monospace'],
      correctOptionIndex: 0,
      explanation: 'Huruf Serif ditandai dengan garis sirip/kaitan dekoratif di ujung stroke huruf.',
    ),
    QuestionItem(
      id: 'dkv_007',
      questionText: 'Font populer "Times New Roman" tergolong dalam kategori tipografi:',
      options: ['Serif', 'Sans-serif', 'Decorative', 'Script'],
      correctOptionIndex: 0,
      explanation: 'Times New Roman adalah salah satu font klasik kategori Serif.',
    ),
    QuestionItem(
      id: 'dkv_008',
      questionText: 'Font populer "Helvetica" dan "Arial" tergolong dalam kategori tipografi:',
      options: ['Sans-serif', 'Serif', 'Blackletter', 'Gothic Serif'],
      correctOptionIndex: 0,
      explanation: 'Helvetica dan Arial tidak memiliki sirip kaitan, sehingga tergolong Sans-serif (tanpa serif).',
    ),
    QuestionItem(
      id: 'dkv_009',
      questionText: 'Garis khayal tempat mendarat atau bertenggernya bagian bawah karakter huruf disebut:',
      options: ['Baseline', 'Meanline', 'Ascender line', 'Descender line'],
      correctOptionIndex: 0,
      explanation: 'Baseline adalah garis landasan utama di mana sebagian besar huruf duduk.',
    ),
    QuestionItem(
      id: 'dkv_010',
      questionText: 'Ketinggian huruf kecil (seperti x, a, e) tanpa bagian ascender maupun descender dinamakan:',
      options: ['X-height', 'Cap height', 'Font size', 'Em square'],
      correctOptionIndex: 0,
      explanation: 'X-height mengukur tinggi badan utama huruf kecil (non-ascending).',
    ),
    QuestionItem(
      id: 'dkv_011',
      questionText: 'Bagian huruf kecil yang menjulang ke atas melebihi x-height (seperti pada b, d, h) disebut:',
      options: ['Ascender', 'Descender', 'Serif', 'Counter'],
      correctOptionIndex: 0,
      explanation: 'Ascender adalah bagian huruf kecil yang melampaui garis meanline ke atas.',
    ),
    QuestionItem(
      id: 'dkv_012',
      questionText: 'Bagian huruf yang menjulur ke bawah melewati garis baseline (seperti pada p, q, y) disebut:',
      options: ['Descender', 'Ascender', 'Stem', 'Terminal'],
      correctOptionIndex: 0,
      explanation: 'Descender adalah bagian stroke huruf yang meluas di bawah baseline.',
    ),
    QuestionItem(
      id: 'dkv_013',
      questionText: 'Prinsip Gestalt yang menyatakan bahwa elemen-elemen yang letaknya berdekatan akan dipersepsikan sebagai satu kelompok adalah:',
      options: ['Proximity (Kedekatan)', 'Similarity (Kesamaan)', 'Closure (Penutupan)', 'Continuity (Keberlanjutan)'],
      correctOptionIndex: 0,
      explanation: 'Proximity menyatakan bahwa objek yang berdekatan secara spasial dianggap berhubungan.',
    ),
    QuestionItem(
      id: 'dkv_014',
      questionText: 'Prinsip psikologi Gestalt yang membedakan objek utama dari latar belakangnya dinamakan:',
      options: ['Figure-Ground', 'Proximity', 'Common Fate', 'Symmetry'],
      correctOptionIndex: 0,
      explanation: 'Figure-Ground membagi bidang visual menjadi objek fokus (figure) dan latar belakang (ground).',
    ),
    QuestionItem(
      id: 'dkv_015',
      questionText: 'Ruang kosong tanpa elemen visual pada desain yang berfungsi memberikan kejelasan dinamakan:',
      options: ['White Space / Negative Space', 'Bleed', 'Margin Offset', 'Dead Zone'],
      correctOptionIndex: 0,
      explanation: 'White Space (ruang negatif) adalah area kosong yang membantu fokus dan keterbacaan.',
    ),
    QuestionItem(
      id: 'dkv_016',
      questionText: 'Gambar grafis yang dibentuk dari rumus matematika (garis, kurva, dan titik) dinamakan:',
      options: ['Vektor', 'Raster / Bitmap', 'Voxel', 'Pixel Array'],
      correctOptionIndex: 0,
      explanation: 'Grafis vektor menggunakan titik koordinat matematika sehingga tidak pecah saat diperbesar.',
    ),
    QuestionItem(
      id: 'dkv_017',
      questionText: 'Keunggulan utama dari gambar berbasis vektor dibandingkan gambar bitmap adalah:',
      options: ['Dapat diperbesar tanpa kehilangan kualitas/pecah', 'Memiliki kedalaman warna foto realitis', 'Ukuran file selalu lebih besar', 'Hanya bisa dilihat di browser'],
      correctOptionIndex: 0,
      explanation: 'Grafis vektor bersifat resolution-independent (bebas skala resolusi).',
    ),
    QuestionItem(
      id: 'dkv_018',
      questionText: 'Gambar bitmap/raster tersusun dari sekumpulan titik warna kecil yang disebut:',
      options: ['Piksel (Pixel)', 'Node', 'Path', 'Vector point'],
      correctOptionIndex: 0,
      explanation: 'Bitmap terdiri dari grid piksel (picture element) berkepadatan tertentu.',
    ),
    QuestionItem(
      id: 'dkv_019',
      questionText: 'Satuan yang digunakan untuk mengukur resolusi kerapatan piksel pada layar digital adalah:',
      options: ['PPI (Pixels Per Inch)', 'DPI (Dots Per Inch)', 'LPI (Lines Per Inch)', 'FPS (Frames Per Second)'],
      correctOptionIndex: 0,
      explanation: 'PPI mengukur kerapatan piksel pada media layar digital.',
    ),
    QuestionItem(
      id: 'dkv_020',
      questionText: 'Satuan yang digunakan untuk mengukur kerapatan titik tinta pada mesin cetak/printer adalah:',
      options: ['DPI (Dots Per Inch)', 'PPI (Pixels Per Inch)', 'Hz (Hertz)', 'RPM'],
      correctOptionIndex: 0,
      explanation: 'DPI mengukur kepadatan titik tinta yang disemprotkan printer per inci persegi.',
    ),
    QuestionItem(
      id: 'dkv_021',
      questionText: 'Format file grafis vektor standar berbasis XML yang umum dipakai di web modern adalah:',
      options: ['SVG', 'JPEG', 'GIF', 'BMP'],
      correctOptionIndex: 0,
      explanation: 'SVG (Scalable Vector Graphics) adalah standar vektor web.',
    ),
    QuestionItem(
      id: 'dkv_022',
      questionText: 'Format file bitmap yang mendukung transparansi (alpha channel) tanpa kompresi merusak adalah:',
      options: ['PNG', 'JPEG', 'BMP', 'RAW'],
      correctOptionIndex: 0,
      explanation: 'PNG mendukung kompresi lossless dan transparansi piksel.',
    ),
    QuestionItem(
      id: 'dkv_023',
      questionText: 'Format file foto yang menggunakan kompresi lossy untuk memperkecil ukuran file adalah:',
      options: ['JPEG', 'PNG', 'SVG', 'EPS'],
      correctOptionIndex: 0,
      explanation: 'JPEG menggunakan kompresi lossy yang membuang sebagian detail foto agar file lebih kecil.',
    ),
    QuestionItem(
      id: 'dkv_024',
      questionText: 'Kombinasi warna yang letaknya saling berseberangan 180 derajat pada lingkaran warna dinamakan:',
      options: ['Komplementer', 'Analogis', 'Monokromatik', 'Triad'],
      correctOptionIndex: 0,
      explanation: 'Warna komplementer berseberangan langsung pada color wheel (misal: Merah & Hijau).',
    ),
    QuestionItem(
      id: 'dkv_025',
      questionText: 'Kombinasi warna yang letaknya berdampingan secara berurutan pada roda warna dinamakan:',
      options: ['Analogis (Analogous)', 'Komplementer', 'Tetrad', 'Split-komplementer'],
      correctOptionIndex: 0,
      explanation: 'Warna analogis berdampingan pada lingkaran warna (misal: Kuning, Oranye-Kuning, Oranye).',
    ),
    QuestionItem(
      id: 'dkv_026',
      questionText: 'Tiga warna pokok dalam lingkaran warna tradisional yang tidak dapat dibuat dari campuran warna lain adalah:',
      options: ['Merah, Kuning, Biru', 'Merah, Hijau, Biru', 'Cyan, Magenta, Black', 'Oranye, Hijau, Ungu'],
      correctOptionIndex: 0,
      explanation: 'Warna primer RYB tradisional meliputi Merah, Kuning, dan Biru.',
    ),
    QuestionItem(
      id: 'dkv_027',
      questionText: 'Pencampuran seimbang dua warna primer akan menghasilkan warna:',
      options: ['Sekunder', 'Tersier', 'Netral', 'Monokrom'],
      correctOptionIndex: 0,
      explanation: 'Warna sekunder (Hijau, Oranye, Ungu) merupakan hasil pencampuran dua warna primer.',
    ),
    QuestionItem(
      id: 'dkv_028',
      questionText: 'Pencampuran antara satu warna primer dan satu warna sekunder di sebelahnya menghasilkan warna:',
      options: ['Tersier', 'Kuarterner', 'Komplementer', 'Sekunder'],
      correctOptionIndex: 0,
      explanation: 'Warna tersier dihasilkan dari pencampuran warna primer dan sekunder.',
    ),
    QuestionItem(
      id: 'dkv_029',
      questionText: 'Model pencampuran warna RGB bersifat Additive, yang berarti jika ketiga warna primer digabung maksimal akan menghasilkan warna:',
      options: ['Putih', 'Hitam', 'Abu-abu', 'Cokelat'],
      correctOptionIndex: 0,
      explanation: 'Sistem Additive menggabungkan intensitas cahaya; gabungan maksimum RGB menghasilkan warna putih.',
    ),
    QuestionItem(
      id: 'dkv_030',
      questionText: 'Model pencampuran tinta CMYK bersifat Subtractive, di mana gabungan teori seluruh pigmen warna menghasilkan warna:',
      options: ['Hitam / Gelap', 'Putih', 'Kuning Cerah', 'Transparan'],
      correctOptionIndex: 0,
      explanation: 'Sistem Subtractive menyerap pantulan cahaya; pencampuran pigmen menghasilkan warna gelap/hitam.',
    ),
    QuestionItem(
      id: 'dkv_031',
      questionText: 'Variasi warna murni yang dicampur dengan warna PUTIH dinamakan:',
      options: ['Tint', 'Shade', 'Tone', 'Value'],
      correctOptionIndex: 0,
      explanation: 'Tint adalah warna murni yang ditambah warna putih sehingga tampak lebih muda/pastal.',
    ),
    QuestionItem(
      id: 'dkv_032',
      questionText: 'Variasi warna murni yang dicampur dengan warna HITAM dinamakan:',
      options: ['Shade', 'Tint', 'Tone', 'Chroma'],
      correctOptionIndex: 0,
      explanation: 'Shade adalah warna murni yang ditambah warna hitam sehingga tampak lebih gelap.',
    ),
    QuestionItem(
      id: 'dkv_033',
      questionText: 'Variasi warna murni yang dicampur dengan warna ABU-ABU dinamakan:',
      options: ['Tone', 'Tint', 'Shade', 'Hue'],
      correctOptionIndex: 0,
      explanation: 'Tone adalah warna murni yang ditambah warna abu-abu (gray).',
    ),
    QuestionItem(
      id: 'dkv_034',
      questionText: 'Istilah teknis yang merujuk pada nama atau keluarga warna dasar (seperti merah, hijau, biru) adalah:',
      options: ['Hue', 'Saturation', 'Brightness', 'Opacity'],
      correctOptionIndex: 0,
      explanation: 'Hue adalah identitas spektrum warna murni.',
    ),
    QuestionItem(
      id: 'dkv_035',
      questionText: 'Tingkat kejenuhan atau kemurnian suatu warna dinamakan:',
      options: ['Saturation (Saturasi)', 'Hue', 'Lightness', 'Contrast'],
      correctOptionIndex: 0,
      explanation: 'Saturation mengukur seberapa pekat atau redup intensitas warna.',
    ),
    QuestionItem(
      id: 'dkv_036',
      questionText: 'Prinsip desain yang memfokuskan perhatian penonton pada elemen paling penting dinamakan:',
      options: ['Emphasis / Focal Point', 'Balance', 'Proportion', 'Unity'],
      correctOptionIndex: 0,
      explanation: 'Emphasis menciptakan daya tarik utama (focal point) dalam komposisi.',
    ),
    QuestionItem(
      id: 'dkv_037',
      questionText: 'Pengulangan elemen visual secara teratur sehingga membimbing pandangan mata secara dinamis disebut:',
      options: ['Rhythm (Irama)', 'Alignment', 'Contrast', 'White space'],
      correctOptionIndex: 0,
      explanation: 'Rhythm atau irama visual tercipta lewat pola pengulangan elemen secara konsisten.',
    ),
    QuestionItem(
      id: 'dkv_038',
      questionText: 'Keseimbangan visual di mana sisi kiri dan kanan tidak simetris namun memiliki bobot visual setara dinamakan:',
      options: ['Asymmetrical Balance', 'Symmetrical Balance', 'Radial Balance', 'Grid Balance'],
      correctOptionIndex: 0,
      explanation: 'Asymmetrical Balance menggunakan elemen berbeda bentuk/ukuran tetapi berbobot seimbang.',
    ),
    QuestionItem(
      id: 'dkv_039',
      questionText: 'Jenis keseimbangan visual di mana elemen-elemen disusun melingkar memancar dari titik pusat dinamakan:',
      options: ['Radial Balance', 'Asymmetrical Balance', 'Linear Balance', 'Bilateral Balance'],
      correctOptionIndex: 0,
      explanation: 'Radial Balance menata elemen secara memancar mengelilingi satu titik tengah.',
    ),
    QuestionItem(
      id: 'dkv_040',
      questionText: 'Metode pembagian bidang gambar menjadi 9 kotak dengan 2 garis vertikal dan 2 garis horizontal dinamakan:',
      options: ['Rule of Thirds', 'Golden Ratio', 'Grid System', 'Fibonacci Series'],
      correctOptionIndex: 0,
      explanation: 'Rule of Thirds membagi bidang komposisi secara 3x3 untuk menentukan posisi objek estetik.',
    ),
    QuestionItem(
      id: 'dkv_041',
      questionText: 'Rasio proporsi matematika bernilai sekitar 1 : 1,618 yang sering dipakai dalam desain harmonis dinamakan:',
      options: ['Golden Ratio (Rasio Emas)', 'Rule of Thirds', 'Golden Angle', 'Pythagoras Ratio'],
      correctOptionIndex: 0,
      explanation: 'Golden Ratio (Phi = 1,618) digunakan sejak zaman klasik untuk komposisi ideal.',
    ),
    QuestionItem(
      id: 'dkv_042',
      questionText: 'Buku petunjuk baku mengenai standar penggunaan elemen visual suatu brand/perusahaan dinamakan:',
      options: ['Brand Guidelines / Brand Manual', 'Curriculum Vitae', 'Portfolio Booklet', 'SOP Perusahaan'],
      correctOptionIndex: 0,
      explanation: 'Brand Guidelines mengatur identitas visual, aturan logo, warna, dan font resmi perusahaan.',
    ),
    QuestionItem(
      id: 'dkv_043',
      questionText: 'Tipe logo yang seluruhnya berupa tulisan nama merek tanpa simbol ikon (contoh: Google, Sony) dinamakan:',
      options: ['Wordmark / Logotype', 'Lettermark', 'Pictorial Mark', 'Emblem'],
      correctOptionIndex: 0,
      explanation: 'Wordmark fokus pada tipografi khusus nama brand.',
    ),
    QuestionItem(
      id: 'dkv_044',
      questionText: 'Tipe logo yang terdiri atas singkatan atau inisial nama perusahaan (contoh: IBM, NASA, HBO) dinamakan:',
      options: ['Lettermark / Monogram', 'Wordmark', 'Mascot', 'Abstract Mark'],
      correctOptionIndex: 0,
      explanation: 'Lettermark menyederhanakan nama panjang menjadi inisial huruf.',
    ),
    QuestionItem(
      id: 'dkv_045',
      questionText: 'Tipe logo yang menggabungkan simbol ikon grafis dengan teks nama merek dinamakan:',
      options: ['Combination Mark', 'Wordmark', 'Monogram', 'Siluet Mark'],
      correctOptionIndex: 0,
      explanation: 'Combination Mark memadukan teks dan simbol ikon dalam satu kesatuan.',
    ),
    QuestionItem(
      id: 'dkv_046',
      questionText: 'Area lebih pada tepi latar cetakan yang akan terpotong pisau agar cetakan tidak menyisakan tepi putih dinamakan:',
      options: ['Bleed', 'Margin', 'Gutter', 'Padding'],
      correctOptionIndex: 0,
      explanation: 'Bleed adalah toleransi area lebih (biasanya 3-5mm) untuk potongan mesin cetak.',
    ),
    QuestionItem(
      id: 'dkv_047',
      questionText: 'Garis penanda tipis pada pojok halaman cetak yang menunjukkan batas pemotongan kertas dinamakan:',
      options: ['Crop Marks / Trim Marks', 'Registration Marks', 'Grid Lines', 'Safety Lines'],
      correctOptionIndex: 0,
      explanation: 'Crop Marks memberi instruksi bagi operator potong kertas.',
    ),
    QuestionItem(
      id: 'dkv_048',
      questionText: 'Garis tengah tempat lipatan atau jilidan pada buku/majalah dinamakan:',
      options: ['Gutter', 'Bleed', 'Margin', 'Slug'],
      correctOptionIndex: 0,
      explanation: 'Gutter adalah ruang ekstra atau area lipatan jilid di bagian dalam cetakan buku.',
    ),
    QuestionItem(
      id: 'dkv_049',
      questionText: 'Tahap pemeriksaan file desain digital sebelum dikirim ke mesin cetak cetak offset dinamakan:',
      options: ['Pre-press / Preflight', 'Post-production', 'Render Engine', 'Wireframing'],
      correctOptionIndex: 0,
      explanation: 'Preflight memeriksa keterhubungan font, mode CMYK, dan resolusi gambar sebelum dicetak.',
    ),
    QuestionItem(
      id: 'dkv_050',
      questionText: 'Visualisasi simulasi produk nyata untuk mempresentasikan rancangan desain secara realistis dinamakan:',
      options: ['Mockup', 'Wireframe', 'Blueprint', 'Moodboard'],
      correctOptionIndex: 0,
      explanation: 'Mockup adalah media presentasi visual skala nyata untuk klien.',
    ),
    QuestionItem(
      id: 'dkv_051',
      questionText: 'Rangkaian sketsa adegan dalam kolom berurutan untuk merencanakan alur cerita video dinamakan:',
      options: ['Storyboard', 'Moodboard', 'Styleframe', 'Wireframe'],
      correctOptionIndex: 0,
      explanation: 'Storyboard menggambarkan rangkaian visual adegan per adegan sebelum produksi video.',
    ),
    QuestionItem(
      id: 'dkv_052',
      questionText: 'Istilah yang menunjukkan banyaknya bingkai gambar bergerak yang diputar tiap satu detik adalah:',
      options: ['FPS (Frames Per Second)', 'DPI', 'PPI', 'BPM'],
      correctOptionIndex: 0,
      explanation: 'FPS menentukan kehalusan animasi atau gerakan video.',
    ),
    QuestionItem(
      id: 'dkv_053',
      questionText: 'Prinsip animasi di mana bentuk objek memipih dan memanjang untuk mengindikasikan kelenturan dan bobot adalah:',
      options: ['Squash and Stretch', 'Anticipation', 'Staging', 'Slow In and Slow Out'],
      correctOptionIndex: 0,
      explanation: 'Squash and Stretch memberikan kesan lentur dan beban fleksibel pada objek bergerak.',
    ),
    QuestionItem(
      id: 'dkv_054',
      questionText: 'Gerakan awal/persiapan sebelum melakukan aksi utama dalam gerakan animasi dinamakan:',
      options: ['Anticipation', 'Follow Through', 'Overlapping Action', 'Arc'],
      correctOptionIndex: 0,
      explanation: 'Anticipation menyiapkan penonton sebelum karakter melakukan aksi besar (misal menekuk lutut sebelum melompat).',
    ),
    QuestionItem(
      id: 'dkv_055',
      questionText: 'Proses pembuatan bingkai pergerakan otomatis antar dua gambar kunci (keyframe) dinamakan:',
      options: ['Tweening (Inbetweening)', 'Rigging', 'Rendering', 'Modeling'],
      correctOptionIndex: 0,
      explanation: 'Tweening mengisi frame transisi di antara keyframe awal dan akhir.',
    ),
    QuestionItem(
      id: 'dkv_056',
      questionText: 'Tiga elemen utama pembentuk pencahayaan foto yang dikenal sebagai "Exposure Triangle" adalah:',
      options: ['Aperture, Shutter Speed, ISO', 'Brightness, Contrast, Saturation', 'Hue, Value, Chroma', 'Focal Length, Zoom, Sensor'],
      correctOptionIndex: 0,
      explanation: 'Exposure Triangle terdiri dari Aperture (Bukaan), Shutter Speed (Kecepatan), dan ISO (Sensitivitas).',
    ),
    QuestionItem(
      id: 'dkv_057',
      questionText: 'Ukuran bukaan lensa kamera yang mengontrol jumlah cahaya masuk dan kedalaman ruang (DoF) dinamakan:',
      options: ['Aperture (Diafragma)', 'Shutter Speed', 'ISO', 'White Balance'],
      correctOptionIndex: 0,
      explanation: 'Aperture (diukur dalam f-stop) menentukan besarnya bukaan diafragma lensa.',
    ),
    QuestionItem(
      id: 'dkv_058',
      questionText: 'Pengaturan lamanya durasi sensor kamera terbuka menerima cahaya dipengaruhi oleh:',
      options: ['Shutter Speed', 'Aperture', 'ISO', 'Focal Length'],
      correctOptionIndex: 0,
      explanation: 'Shutter Speed mengukur durasi rana kamera membeku atau membiarkan gerakan masuk.',
    ),
    QuestionItem(
      id: 'dkv_059',
      questionText: 'Tingkat sensitivitas sensor kamera terhadap cahaya dinamakan:',
      options: ['ISO', 'Aperture', 'Aspect Ratio', 'Frame Rate'],
      correctOptionIndex: 0,
      explanation: 'Semakin tinggi nilai ISO, semakin sensitif sensor terhadap cahaya (namun berisiko nampak noise).',
    ),
    QuestionItem(
      id: 'dkv_060',
      questionText: 'Kondisi foto di mana objek fokus utama tampak sangat tajam sementara latar belakangnya buram (bokeh) disebut:',
      options: ['Shallow Depth of Field (DoF Dangkal)', 'Deep Depth of Field', 'High Contrast', 'Overexposure'],
      correctOptionIndex: 0,
      explanation: 'Shallow DoF dihasilkan dari aperture besar (nilai f kecil) untuk memisahkan objek dari latar.',
    ),
    QuestionItem(
      id: 'dkv_061',
      questionText: 'Sudut pengambilan foto/video dari bawah ke atas sehingga subjek tampak megah dan dominan dinamakan:',
      options: ['Low Angle / Frog Eye', 'High Angle', 'Eye Level', 'Bird Eye View'],
      correctOptionIndex: 0,
      explanation: 'Low Angle mengambil perspektif rendah untuk memberikan kesan kuat/besar pada subjek.',
    ),
    QuestionItem(
      id: 'dkv_062',
      questionText: 'Sudut pengambilan foto dari atas ke bawah yang membuat objek tampak lebih kecil dinamakan:',
      options: ['High Angle / Bird Eye View', 'Low Angle', 'Dutch Angle', 'Frog Eye'],
      correctOptionIndex: 0,
      explanation: 'High Angle memosisikan kamera lebih tinggi dari subjek.',
    ),
    QuestionItem(
      id: 'dkv_063',
      questionText: 'Gerakan poros kamera menoleh secara horizontal ke kiri atau ke kanan dinamakan:',
      options: ['Panning', 'Tilting', 'Dolly', 'Zooming'],
      correctOptionIndex: 0,
      explanation: 'Pan (Panning) adalah gerakan kamera menggeleng ke kiri-kanan secara horizontal.',
    ),
    QuestionItem(
      id: 'dkv_064',
      questionText: 'Gerakan poros kamera mendongak ke atas atau menunduk ke bawah dinamakan:',
      options: ['Tilting', 'Panning', 'Tracking', 'Roll'],
      correctOptionIndex: 0,
      explanation: 'Tilt (Tilting) adalah gerakan kamera mengangguk ke atas-bawah secara vertikal.',
    ),
    QuestionItem(
      id: 'dkv_065',
      questionText: 'Sketsa tata letak kasar struktur antarmuka aplikasi tanpa elemen visual rinci dinamakan:',
      options: ['Wireframe', 'High-fidelity Prototype', 'Mockup', 'Styleguide'],
      correctOptionIndex: 0,
      explanation: 'Wireframe adalah cetak biru struktural (low-fidelity) dari aplikasi/situs web.',
    ),
    QuestionItem(
      id: 'dkv_066',
      questionText: 'Model interaktif akhir dari antarmuka digital yang dapat diklik dan disimulasikan seperti aplikasi asli dinamakan:',
      options: ['Prototype', 'Wireframe', 'Flowchart', 'Mindmap'],
      correctOptionIndex: 0,
      explanation: 'Prototype memungkinkan pengujian alur pengguna dan interaksi sebelum tahap pengodean.',
    ),
    QuestionItem(
      id: 'dkv_067',
      questionText: 'Sekolah seni dan desain legendaris di Jerman yang berdiri tahun 1919 dan memelopori seni modern berprinsip "Form Follows Function" adalah:',
      options: ['Bauhaus', 'Art Nouveau', 'Memphis Group', 'De Stijl'],
      correctOptionIndex: 0,
      explanation: 'Bauhaus mendobrak batas seni rupa dan industri dengan menggabungkan fungsi dan estetika.',
    ),
    QuestionItem(
      id: 'dkv_068',
      questionText: 'Gaya seni visual akhir abad ke-19 yang bercirikan garis dekoratif meliuk organis terinspirasi tumbuhan adalah:',
      options: ['Art Nouveau', 'Art Deco', 'Minimalisme', 'Constructivism'],
      correctOptionIndex: 0,
      explanation: 'Art Nouveau menggunakan ornamen lengkung organis dan motif alam yang dinamis.',
    ),
    QuestionItem(
      id: 'dkv_069',
      questionText: 'Gaya desain era 1920-1930an yang mengedepankan bentuk geometris tegas, simetris, dan mewah dinamakan:',
      options: ['Art Deco', 'Art Nouveau', 'Pop Art', 'Dadaisme'],
      correctOptionIndex: 0,
      explanation: 'Art Deco terkenal dengan pola simetris murni, garis tegas, dan kesan megah era modernisme.',
    ),
    QuestionItem(
      id: 'dkv_070',
      questionText: 'Gerakan seni pertengahan abad ke-20 yang mempopulerkan budaya massa, produk komersial, dan komik adalah:',
      options: ['Pop Art', 'Surrealisme', 'Impresionisme', 'Kubisme'],
      correctOptionIndex: 0,
      explanation: 'Pop Art (dipelopori Andy Warhol, Roy Lichtenstein) memakai elemen budaya populer komersial.',
    ),
    QuestionItem(
      id: 'dkv_071',
      questionText: 'Gaya desain grafis yang lahir di Swiss pada 1950-an berkarakteristik grid ketat, bersih, dan font sans-serif dinamakan:',
      options: ['Swiss Style / International Typographic Style', 'Bauhaus', 'Pop Art', 'Psychedelic Art'],
      correctOptionIndex: 0,
      explanation: 'Swiss Style menekankan kerapihan grid, tipografi sans-serif (seperti Helvetica), dan objektivitas.',
    ),
    QuestionItem(
      id: 'dkv_072',
      questionText: 'Kesesuaian rasio kontras warna teks terhadap latar belakang sangat vital untuk memenuhi standar:',
      options: ['Aksesibilitas Visual (Accessibility / WCAG)', 'Kecepatan Server', 'Lisensi Copyright', 'Resolusi Cetak'],
      correctOptionIndex: 0,
      explanation: 'Kontras teks yang baik memastikan pembacaan nyaman bagi semua orang termasuk penderita gangguan penglihatan.',
    ),
    QuestionItem(
      id: 'dkv_073',
      questionText: 'Istilah yang merujuk pada kemudahan mata dalam mengenali dan membedakan bentuk karakter huruf individual adalah:',
      options: ['Legibility', 'Readability', 'Kerning', 'Alignment'],
      correctOptionIndex: 0,
      explanation: 'Legibility fokus pada kejelasan bentuk fisik tiap huruf individu.',
    ),
    QuestionItem(
      id: 'dkv_074',
      questionText: 'Istilah yang merujuk pada kenyamanan mata dalam membaca blok paragraf teks yang panjang adalah:',
      options: ['Readability', 'Legibility', 'Contrast', 'Serifness'],
      correctOptionIndex: 0,
      explanation: 'Readability berkaitan dengan kemudahan membaca keseluruhan paragraf/kalimat.',
    ),
    QuestionItem(
      id: 'dkv_075',
      questionText: 'Penataan elemen grafis berdasarkan urutan prioritas tingkat kepentingan informasi dinamakan:',
      options: ['Hierarki Visual (Visual Hierarchy)', 'Simetri', 'Grid alignment', 'Randomization'],
      correctOptionIndex: 0,
      explanation: 'Visual Hierarchy mengarahkan alur pandang pembaca dari pesan paling utama hingga pendukung.',
    ),
    QuestionItem(
      id: 'dkv_076',
      questionText: 'Komponen model ruang warna HSV terdiri atas singkatan dari:',
      options: ['Hue, Saturation, Value', 'High, Soft, Vibrant', 'Hex, Shade, Volume', 'Heavy, Solid, View'],
      correctOptionIndex: 0,
      explanation: 'HSV singkatan dari Hue (warna), Saturation (kejenuhan), Value (kecerahan).',
    ),
    QuestionItem(
      id: 'dkv_077',
      questionText: 'Proses mengubah gambar piksel bitmap menjadi bentuk vektor garis matematika dinamakan:',
      options: ['Image Tracing / Vectorization', 'Rasterization', 'Pixelation', 'Anti-aliasing'],
      correctOptionIndex: 0,
      explanation: 'Tracing mengonversi piksel bitmap menjadi kurva dan path vektor.',
    ),
    QuestionItem(
      id: 'dkv_078',
      questionText: 'Tinta warna khusus premix baku (bukan dari campuran 4 warna CMYK) dinamakan warna:',
      options: ['Pantone / Spot Color', 'RGB Color', 'Process Color', 'Hex Color'],
      correctOptionIndex: 0,
      explanation: 'Spot Color/Pantone adalah formula tinta warna konsisten presisi tinggi.',
    ),
    QuestionItem(
      id: 'dkv_079',
      questionText: 'Kemiringan huruf buatan yang dimiringkan secara mekanis oleh software dinamakan:',
      options: ['Oblique', 'Italic', 'Script', 'Cursive'],
      correctOptionIndex: 0,
      explanation: 'Oblique hanyalah versi tegak yang dimiringkan secara matematis, berbeda dari Italic asli.',
    ),
    QuestionItem(
      id: 'dkv_080',
      questionText: 'Gaya miring pada tipe huruf Serif/Sans-serif yang dirancang ulang khusus dengan guratan mengalir dinamakan:',
      options: ['Italic', 'Oblique', 'Bold', 'Condensed'],
      correctOptionIndex: 0,
      explanation: 'Italic dirancang khusus oleh desainer tipe dengan struktur karakter miring yang kaligrafis.',
    ),
    QuestionItem(
      id: 'dkv_081',
      questionText: 'Lisensi Creative Commons yang memperbolehkan karya digunakan secara bebas selama mencantumkan nama kreator adalah:',
      options: ['CC BY (Attribution)', 'CC NC (Non-Commercial)', 'CC ND (No-Derivatives)', 'CC SA (Share-Alike)'],
      correctOptionIndex: 0,
      explanation: 'CC BY mewajibkan pengakuan attribution kepada pencipta asli.',
    ),
    QuestionItem(
      id: 'dkv_082',
      questionText: 'Tindakan meniru atau mengambil karya desain orang lain tanpa izin lalu mengakuinya sebagai karya sendiri disebut:',
      options: ['Plagiarisme', 'Inspirasi', 'Parodi', 'Fair Use'],
      correctOptionIndex: 0,
      explanation: 'Plagiarisme adalah pelanggaran etika dan Hak Cipta dengan mencuri karya orang lain.',
    ),
    QuestionItem(
      id: 'dkv_083',
      questionText: 'Hak eksklusif pencipta yang timbul secara otomatis berdasarkan prinsip deklaratif setelah karya diwujudkan adalah:',
      options: ['Hak Cipta (Copyright)', 'Paten', 'Merek Dagang', 'Desain Industri'],
      correctOptionIndex: 0,
      explanation: 'Hak cipta melindungi karya seni, sains, dan sastra ciptaan kreator.',
    ),
    QuestionItem(
      id: 'dkv_084',
      questionText: 'Ujung stroke terbuka pada huruf yang tidak diakhiri oleh serif dinamakan:',
      options: ['Terminal', 'Spur', 'Barb', 'Beak'],
      correctOptionIndex: 0,
      explanation: 'Terminal adalah titik akhir stroke huruf tanpa sirip serif.',
    ),
    QuestionItem(
      id: 'dkv_085',
      questionText: 'Ruang area negatif yang tertutup penuh di dalam huruf (seperti pada huruf O, B, d, p) dinamakan:',
      options: ['Counter', 'Eye', 'Bowl', 'Aperture'],
      correctOptionIndex: 0,
      explanation: 'Counter adalah area tertutup di bagian dalam kurva huruf.',
    ),
    QuestionItem(
      id: 'dkv_086',
      questionText: 'Lengkungan penghubung halus antara kaki sirip serif dengan batang stroke utama huruf dinamakan:',
      options: ['Bracket', 'Spine', 'Crossbar', 'Ligature'],
      correctOptionIndex: 0,
      explanation: 'Bracket menghubungkan serif secara melengkung halus ke stem huruf.',
    ),
    QuestionItem(
      id: 'dkv_087',
      questionText: 'Garis vertikal utama pembentuk tubuh huruf (seperti pada huruf I, T, H, B) dinamakan:',
      options: ['Stem', 'Bar', 'Arm', 'Leg'],
      correctOptionIndex: 0,
      explanation: 'Stem adalah batang tegak lurus utama pada anatomi huruf.',
    ),
    QuestionItem(
      id: 'dkv_088',
      questionText: 'Teknik menggambar manual menggunakan garis-garis sejajar silang untuk membentuk bayangan dinamakan:',
      options: ['Cross-Hatching', 'Stippling', 'Blending', 'Smudging'],
      correctOptionIndex: 0,
      explanation: 'Cross-hatching membuat gradasi nilai gelap terang melalui tumpukan arsir garis bersilang.',
    ),
    QuestionItem(
      id: 'dkv_089',
      questionText: 'Sketsa kasar ukuran kecil yang dibuat cepat untuk mengeksplorasi banyak ide komposisi awal dinamakan:',
      options: ['Thumbnail Sketch', 'Rough Layout', 'Comprehensive Design', 'Final Art'],
      correctOptionIndex: 0,
      explanation: 'Thumbnail sketch digunakan desainer untuk brainstroming cepat di atas kertas.',
    ),
    QuestionItem(
      id: 'dkv_090',
      questionText: 'Kumpulan gambar, tekstur visual, dan skema warna yang ditempel pada satu papan inspirasi dinamakan:',
      options: ['Moodboard', 'Storyboard', 'Gridboard', 'Draftboard'],
      correctOptionIndex: 0,
      explanation: 'Moodboard berfungsi menyamakan persepsi arah gaya visual dan konsep kreatif proyek.',
    ),
    QuestionItem(
      id: 'dkv_091',
      questionText: 'Penggabungan beberapa potongan foto menjadi satu bentuk komposisi baru dinamakan:',
      options: ['Fotomontase', 'Tipografi', 'Siluet', 'Vektorilasi'],
      correctOptionIndex: 0,
      explanation: 'Fotomontase mengombinasikan elemen foto dari pelbagai sumber menjadi satu kesatuan visual.',
    ),
    QuestionItem(
      id: 'dkv_092',
      questionText: 'Cabang desain yang berfokus merancang bentuk visual wadah fisik pembungkus produk dinamakan:',
      options: ['Desain Kemasan (Packaging Design)', 'Desain Editorial', 'UI/UX Design', 'Signage Design'],
      correctOptionIndex: 0,
      explanation: 'Desain kemasan memadukan fungsi estetika visual, informasi, dan perlindungan fisik produk.',
    ),
    QuestionItem(
      id: 'dkv_093',
      questionText: 'Perancangan gambar simbol sederhana yang universal untuk memandu pandangan atau fungsi fitur dinamakan:',
      options: ['Ikonografi (Iconography)', 'Kaligrafi', 'Tipografi', 'Ornamen'],
      correctOptionIndex: 0,
      explanation: 'Ikonografi membuat bahasa visual berbentuk simbol intuitif.',
    ),
    QuestionItem(
      id: 'dkv_094',
      questionText: 'Gambar objek yang tampak gelap polos akibat pencahayaan kuat dari belakang (backlight) dinamakan:',
      options: ['Siluet (Silhouette)', 'High Key', 'Vignette', 'Macro'],
      correctOptionIndex: 0,
      explanation: 'Siluet menampilkan bentuk kontur luar objek hitam tegas dengan latar terang.',
    ),
    QuestionItem(
      id: 'dkv_095',
      questionText: 'Teknik menggambar perspektif di mana seluruh garis sejajar bertemu pada satu titik di garis horizon dinamakan:',
      options: ['Perspektif 1 Titik Hilang', 'Perspektif 2 Titik Hilang', 'Perspektif 3 Titik Hilang', 'Perspektif Isometrik'],
      correctOptionIndex: 0,
      explanation: 'Perspektif 1 titik hilang memiliki satu vanishing point pusat di garis horisontal.',
    ),
    QuestionItem(
      id: 'dkv_096',
      questionText: 'Metode pengujian langsung aplikasi kepada sampel calon pengguna untuk mengevaluasi kenyamanan dinamakan:',
      options: ['Usability Testing', 'A/B Testing', 'Beta Release', 'Stress Test'],
      correctOptionIndex: 0,
      explanation: 'Usability Testing menguji kegunaan dan interaksi aplikasi dengan pengguna langsung.',
    ),
    QuestionItem(
      id: 'dkv_097',
      questionText: 'Proses mengubah gambar buatan tangan di kertas menjadi berkas vektor digital lewat software dinamakan:',
      options: ['Digitalisasi / Tracing', 'Printing', 'Scanning', 'Rendering'],
      correctOptionIndex: 0,
      explanation: 'Digitalisasi/vector tracing mengubah gambar analog sketsa menjadi artwork digital.',
    ),
    QuestionItem(
      id: 'dkv_098',
      questionText: 'Pemberian efek bayangan lembut di bawah elemen tombol antarmuka aplikasi bertujuan menciptakan kesan:',
      options: ['Kedalaman visual (Elevation / Visual Depth)', 'Transparansi', 'Distorsi', 'Kelenturan'],
      correctOptionIndex: 0,
      explanation: 'Drop shadow memberikan ilusi elevasi/ketinggian objek melayang di atas latar.',
    ),
    QuestionItem(
      id: 'dkv_099',
      questionText: 'Elemen desain paling mendasar yang menghubungkan dua titik dan mengarahkan pandangan mata dinamakan:',
      options: ['Garis (Line)', 'Bentuk (Shape)', 'Tekstur (Texture)', 'Ruang (Space)'],
      correctOptionIndex: 0,
      explanation: 'Garis merupakan elemen dasar pertama yang memisahkan atau mengarahkan dalam tata letak.',
    ),
    QuestionItem(
      id: 'dkv_100',
      questionText: 'Disiplin ilmu yang mengolah elemen seni rupa dan bahasa visual untuk menyampaikan pesan informasi dinamakan:',
      options: ['Desain Komunikasi Visual (DKV)', 'Seni Rupa Murni', 'Arsitektur', 'Teknik Grafika'],
      correctOptionIndex: 0,
      explanation: 'DKV mengombinasikan seni visual, pemikiran kreatif, dan ilmu komunikasi untuk memecahkan masalah komunikasi.',
    ),
  ];
}
