import '../tes_seleksi_model.dart';

List<QuestionItem> getDesainModeQuestions() {
  return const [
    QuestionItem(
      id: 'fsh_001',
      questionText: 'Sketsa anatomi tubuh manusia khusus untuk ilustrasi fashion umumnya menggunakan proporsi tingginya sebesar:',
      options: ['9 hingga 10 kali tinggi kepala', '7 hingga 7,5 kali tinggi kepala', '5 kali tinggi kepala', '12 hingga 15 kali tinggi kepala'],
      correctOptionIndex: 0,
      explanation: 'Ilustrasi fashion memperpanjang proporsi tubuh manusia menjadi 9-10 kepala untuk memberi kesan jenjang dan elegan.',
    ),
    QuestionItem(
      id: 'fsh_002',
      questionText: 'Sketsa dasar bentuk tubuh manusia yang digunakan sebagai panduan menggambar rancangan busana dinamakan:',
      options: ['Croquis', 'Manekin', 'Passpop', 'Blueprint'],
      correctOptionIndex: 0,
      explanation: 'Croquis adalah sketsa atau templat postur tubuh fashion yang menjadi dasar menggambar baju.',
    ),
    QuestionItem(
      id: 'fsh_003',
      questionText: 'Serat tekstil alami berkilau yang berasal dari kepompong ulat sutra dinamakan:',
      options: ['Sutra (Silk)', 'Katun (Cotton)', 'Wol (Wool)', 'Linen'],
      correctOptionIndex: 0,
      explanation: 'Sutra diproduksi dari serat kepompong ulat sutra (Bombyx mori) yang bertekstur halus dan berkilau.',
    ),
    QuestionItem(
      id: 'fsh_004',
      questionText: 'Serat alami populer yang berasal dari tanaman kapas dan nyaman dipakai menyerap keringat adalah:',
      options: ['Katun (Cotton)', 'Polyester', 'Nylon', 'Rayon'],
      correctOptionIndex: 0,
      explanation: 'Katun berasal dari serat tanaman kapas yang memiliki daya serap tinggi dan adem.',
    ),
    QuestionItem(
      id: 'fsh_005',
      questionText: 'Serat alami hangat yang diperoleh dari bulu domba dinamakan:',
      options: ['Wol (Wool)', 'Sutra', 'Linen', 'Kapok'],
      correctOptionIndex: 0,
      explanation: 'Wol terbuat dari bulu domba yang diolah menjadi benang dan kain penghangat.',
    ),
    QuestionItem(
      id: 'fsh_006',
      questionText: 'Serat alami yang terbuat dari batang tanaman rami (flax) dan memiliki tekstur agak kaku berkilau adalah:',
      options: ['Linen', 'Katun', 'Jute', 'Sutra'],
      correctOptionIndex: 0,
      explanation: 'Linen diolah dari serat tanaman rami (flax) yang kuat, sejuk, dan ramah lingkungan.',
    ),
    QuestionItem(
      id: 'fsh_007',
      questionText: 'Serat buatan (sintetis) yang sangat elastis dan umum digunakan untuk baju renang dan pakaian olahraga adalah:',
      options: ['Spandex / Elastane', 'Polyester', 'Acrylic', 'Nylon'],
      correctOptionIndex: 0,
      explanation: 'Spandex (Elastane/Lycra) memiliki daya regang elastisitas sangat tinggi.',
    ),
    QuestionItem(
      id: 'fsh_008',
      questionText: 'Benang yang terpasang membujur sejajar dengan tepi kain pada mesin tenun dinamakan benang:',
      options: ['Lusi (Warp)', 'Pakan (Weft)', 'Obras', 'Jelujur'],
      correctOptionIndex: 0,
      explanation: 'Benang lusi (warp) adalah benang vertikal yang membentang sejajar dengan pinggiran kain.',
    ),
    QuestionItem(
      id: 'fsh_009',
      questionText: 'Benang yang disisipkan melintang tegak lurus melintasi benang lusi saat menenun kain dinamakan benang:',
      options: ['Pakan (Weft / Woof)', 'Lusi (Warp)', 'Border', 'Kelim'],
      correctOptionIndex: 0,
      explanation: 'Benang pakan (weft) disilangkan secara horizontal melintasi benang lusi.',
    ),
    QuestionItem(
      id: 'fsh_010',
      questionText: 'Teknik pembuatan kain dengan cara menyilangkan dua kelompok benang (lusi dan pakan) secara tegak lurus dinamakan:',
      options: ['Menenun (Weaving)', 'Merajut (Knitting)', 'Membatik', 'Menyulam'],
      correctOptionIndex: 0,
      explanation: 'Tenun (weaving) adalah metode pembuatan kain woven melalui persilangan benang lusi dan pakan.',
    ),
    QuestionItem(
      id: 'fsh_011',
      questionText: 'Teknik pembuatan kain dengan membuat jeratan-jeratan benang yang saling mengait dinamakan:',
      options: ['Merajut (Knitting)', 'Menenun (Weaving)', 'Membordir', 'Menatah'],
      correctOptionIndex: 0,
      explanation: 'Merajut (knitting) membentuk struktur kain fleksibel melalui jeratan benang kontinu.',
    ),
    QuestionItem(
      id: 'fsh_012',
      questionText: 'Struktur tenunan paling sederhana di mana benang pakan bergantian melewati atas dan bawah benang lusi dinamakan tenun:',
      options: ['Polos (Plain Weave)', 'Kepar (Twill Weave)', 'Satin (Satin Weave)', 'Jacquard'],
      correctOptionIndex: 0,
      explanation: 'Tenun polos adalah konstruksi kain paling mendasar (1 atas, 1 bawah).',
    ),
    QuestionItem(
      id: 'fsh_013',
      questionText: 'Jenis tenunan yang menghasilkan garis-garis miring diagonal pada permukaan kain (seperti bahan jeans/denim) dinamakan tenun:',
      options: ['Kepar (Twill Weave)', 'Polos (Plain Weave)', 'Satin', 'Velvet'],
      correctOptionIndex: 0,
      explanation: 'Tenun kepar (twill) membentuk pola alur miring murni yang kokoh seperti pada denim.',
    ),
    QuestionItem(
      id: 'fsh_014',
      questionText: 'Jenis tenunan yang menghasilkan permukaan kain berkilau licin dan halus di satu sisi dinamakan tenun:',
      options: ['Satin', 'Kepar', 'Polos', 'Kain Rajut'],
      correctOptionIndex: 0,
      explanation: 'Tenun satin meminimalkan persilangan benang di permukaan sehingga memantulkan cahaya dengan halus.',
    ),
    QuestionItem(
      id: 'fsh_015',
      questionText: 'Lipatan kain yang dijahit meruncing untuk menyesuaikan potongan baju dengan bentuk curve/lekuk tubuh dinamakan:',
      options: ['Kupnat (Dart)', 'Kelim', 'Kampuh', 'Pleats'],
      correctOptionIndex: 0,
      explanation: 'Kupnat (dart) berfungsi membentuk kain datar agar pas menempel pada bagian tubuh berlekuk.',
    ),
    QuestionItem(
      id: 'fsh_016',
      questionText: 'Metode pembuatan pola busana tiga dimensi langsung di atas manekin dinamakan:',
      options: ['Draping', 'Flat Pattern Drafting', 'Grading', 'Tracing'],
      correctOptionIndex: 0,
      explanation: 'Draping membentuk kain secara tiga dimensi langsung di atas passpop/manekin.',
    ),
    QuestionItem(
      id: 'fsh_017',
      questionText: 'Metode pembuatan pola busana dua dimensi di atas kertas kalkir berdasarkan ukuran badan seseorang dinamakan:',
      options: ['Pola Datar (Flat Pattern Drafting)', 'Draping', 'Fitting', 'Sketching'],
      correctOptionIndex: 0,
      explanation: 'Flat pattern drafting menggambar garis geometris pola di atas bidang datar.',
    ),
    QuestionItem(
      id: 'fsh_018',
      questionText: 'Lebar sisa kain di luar garis jahitan yang berguna untuk menyambung potongan busana dinamakan:',
      options: ['Kampuh (Seam Allowance)', 'Kelim', 'Gutter', 'Bleed'],
      correctOptionIndex: 0,
      explanation: 'Kampuh adalah jarak toleransi tepi kain untuk stik jahitan (biasanya 1-2 cm).',
    ),
    QuestionItem(
      id: 'fsh_019',
      questionText: 'Garis panah petunjuk arah serat benang kain yang digambar pada kertas pola busana dinamakan:',
      options: ['Grainline', 'Seamline', 'Dartline', 'Hemline'],
      correctOptionIndex: 0,
      explanation: 'Grainline menunjukkan arah serat kain (panjang lusi) agar jatuhnya busana tidak miring.',
    ),
    QuestionItem(
      id: 'fsh_020',
      questionText: 'Mesin jahit khusus yang berfungsi memotong dan merapikan tepi kain agar benangnya tidak terurai dinamakan mesin:',
      options: ['Obras (Overlock Machine)', 'Bordir', 'Lubang Kancing', 'Jahit Rantai'],
      correctOptionIndex: 0,
      explanation: 'Mesin obras merapikan pinggiran kampuh dengan jeratan benang pengunci.',
    ),
    QuestionItem(
      id: 'fsh_021',
      questionText: 'Bahan pelapis khusus (seperti viselin atau kain keras) yang ditempelkan di dalam kerah untuk memberi struktur kaku dinamakan:',
      options: ['Interfacing / Kain Keras', 'Lining / Furing', 'Padding', 'Bisban'],
      correctOptionIndex: 0,
      explanation: 'Interfacing dipasang di antara lapisan kain untuk memperkuat kerah, manset, dan belahan.',
    ),
    QuestionItem(
      id: 'fsh_022',
      questionText: 'Lipatan kain di bagian bawah baju atau rok yang dijahit rapi dinamakan:',
      options: ['Kelim (Hem)', 'Kampuh', 'Kupnat', 'Piping'],
      correctOptionIndex: 0,
      explanation: 'Kelim (hem) adalah penyelesaian tepi bawah busana.',
    ),
    QuestionItem(
      id: 'fsh_023',
      questionText: 'Siluet busana yang ramping di bagian atas lalu melebar bertahap ke bawah membentuk huruf A dinamakan:',
      options: ['Siluet A-Line', 'Siluet H', 'Siluet Hourglass', 'Siluet Empire'],
      correctOptionIndex: 0,
      explanation: 'Siluet A-Line menyempit di pinggang/dada dan mekar ke bawah seperti huruf A.',
    ),
    QuestionItem(
      id: 'fsh_024',
      questionText: 'Siluet busana berpotongan lurus dari bahu hingga bawah tanpa penekanan lekuk pinggang dinamakan:',
      options: ['Siluet H (Straight Silhouette)', 'Siluet Hourglass', 'Siluet Mermaid', 'Siluet Ball Gown'],
      correctOptionIndex: 0,
      explanation: 'Siluet H memberikan kesan lurus dan seragam tanpa lekukan pinggang.',
    ),
    QuestionItem(
      id: 'fsh_025',
      questionText: 'Siluet busana yang menekankan bentuk pinggang ramping dengan proporsi seimbang pada dada dan pinggul dinamakan:',
      options: ['Siluet Hourglass (Jam Pasir)', 'Siluet A-line', 'Siluet Empire', 'Siluet Tulip'],
      correctOptionIndex: 0,
      explanation: 'Siluet jam pasir (hourglass) menonjolkan kecantikan bentuk lekuk pinggang ramping.',
    ),
    QuestionItem(
      id: 'fsh_026',
      questionText: 'Siluet gaun pesta dengan bagian rok sangat mekar penuh didukung penopang petticoat dinamakan:',
      options: ['Siluet Ball Gown', 'Siluet Mermaid', 'Siluet Sheath', 'Siluet Peplum'],
      correctOptionIndex: 0,
      explanation: 'Ball gown adalah gaun pesta formal dengan rok sangat mekar mengembang.',
    ),
    QuestionItem(
      id: 'fsh_027',
      questionText: 'Siluet busana dengan garis pinggang dipotong tinggi tepat di bawah dada dinamakan:',
      options: ['Siluet Empire', 'Siluet Mermaid', 'Siluet Princess', 'Siluet A-line'],
      correctOptionIndex: 0,
      explanation: 'Empire waist meletakkan garis potongan di bawah dada dan menjuntai longgar ke bawah.',
    ),
    QuestionItem(
      id: 'fsh_028',
      questionText: 'Siluet gaun yang ketat membungkus tubuh hingga lutut lalu mekar mengembang ke bawah seperti ekor ikan dinamakan:',
      options: ['Siluet Mermaid (Putri Duyung)', 'Siluet Ball Gown', 'Siluet H', 'Siluet Wrap'],
      correctOptionIndex: 0,
      explanation: 'Siluet Mermaid melekat ketat dari dada hingga lutut, lalu mekar di bagian paling bawah.',
    ),
    QuestionItem(
      id: 'fsh_029',
      questionText: 'Busana eksklusif berkualitas super tinggi yang dijahit penuh dengan tangan khusus untuk pemesan dinamakan:',
      options: ['Haute Couture', 'Prêt-à-Porter', 'Fast Fashion', 'Mass Production'],
      correctOptionIndex: 0,
      explanation: 'Haute Couture merupakan adi busana adiluhung yang memenuhi standar ketat di Paris.',
    ),
    QuestionItem(
      id: 'fsh_030',
      questionText: 'Istilah Bahasa Prancis untuk koleksi busana siap pakai produksi pabrik dengan standar ukuran baku adalah:',
      options: ['Prêt-à-Porter (Ready-to-Wear)', 'Haute Couture', 'Bespoke Tailoring', 'Custom Made'],
      correctOptionIndex: 0,
      explanation: 'Prêt-à-Porter adalah busana siap pakai kualitas desainer untuk pasar luas.',
    ),
    QuestionItem(
      id: 'fsh_031',
      questionText: 'Industri pakaian yang memproduksi tren mode secara cepat dan murah namun menghasilkan limbah tekstil tinggi dinamakan:',
      options: ['Fast Fashion', 'Sustainable Fashion', 'Slow Fashion', 'Haute Couture'],
      correctOptionIndex: 0,
      explanation: 'Fast Fashion memproduksi tren terbaru secara masal dengan siklus sangat cepat.',
    ),
    QuestionItem(
      id: 'fsh_032',
      questionText: 'Gerakan desain mode yang memperhatikan dampak lingkungan, daur ulang, dan etika pekerja dinamakan:',
      options: ['Sustainable Fashion / Eco Fashion', 'Fast Fashion', 'Consumerism Fashion', 'Trendsetting'],
      correctOptionIndex: 0,
      explanation: 'Sustainable Fashion mengutamakan prinsip keberlanjutan lingkungan dan etika.',
    ),
    QuestionItem(
      id: 'fsh_033',
      questionText: 'Koleksi busana serbaguna berukuran ringkas yang terdiri dari item-item dasar yang mudah dipadupadankan dinamakan:',
      options: ['Capsule Wardrobe', 'Haute Collection', 'Seasonal Runway', 'Overstock Collection'],
      correctOptionIndex: 0,
      explanation: 'Capsule Wardrobe berisi beberapa pakaian esensial timeless yang fleksibel dikombinasikan.',
    ),
    QuestionItem(
      id: 'fsh_034',
      questionText: 'Desainer mode legendaris Prancis yang mempopulerkan busana santai wanita, "Little Black Dress", dan setelan tweed adalah:',
      options: ['Coco Chanel', 'Christian Dior', 'Elsa Schiaparelli', 'Donatella Versace'],
      correctOptionIndex: 0,
      explanation: 'Coco Chanel merevolusi mode wanita abad ke-20 dengan desain elegan dan praktis.',
    ),
    QuestionItem(
      id: 'fsh_035',
      questionText: 'Desainer mode Prancis yang meluncurkan gaya koleksi bersejarah "New Look" pada tahun 1947 adalah:',
      options: ['Christian Dior', 'Yves Saint Laurent', 'Hubert de Givenchy', 'Cristóbal Balenciaga'],
      correctOptionIndex: 0,
      explanation: 'Christian Dior menghadirkan "New Look" dengan rok mekar lebar dan pinggang ramping pascaperang.',
    ),
    QuestionItem(
      id: 'fsh_036',
      questionText: 'Desainer yang mempopulerkan setelan tuksedo maskulin khusus untuk wanita berjuluk "Le Smoking" pada tahun 1966 adalah:',
      options: ['Yves Saint Laurent', 'Giorgio Armani', 'Karl Lagerfeld', 'Gianni Versace'],
      correctOptionIndex: 0,
      explanation: 'Yves Saint Laurent menciptakan "Le Smoking", tuksedo modern khusus wanita.',
    ),
    QuestionItem(
      id: 'fsh_037',
      questionText: 'Wariskan budaya Indonesia berupa kain bermotif yang dibuat menggunakan teknik rintang warna wax/malam dinamakan:',
      options: ['Batik', 'Tenun Ikat', 'Ulos', 'Songket'],
      correctOptionIndex: 0,
      explanation: 'Batik dibuat dengan merintang warna menggunakan cairan lilin malam.',
    ),
    QuestionItem(
      id: 'fsh_038',
      questionText: 'Alat tradisional berbahan tembaga bercurat yang digunakan untuk menggoreskan cairan lilin malam pada batik tulis dinamakan:',
      options: ['Canting', 'Cap', 'Sutil', 'Pahat'],
      correctOptionIndex: 0,
      explanation: 'Canting digunakan pembatik untuk melukis cairan malam secara manual.',
    ),
    QuestionItem(
      id: 'fsh_039',
      questionText: 'Kain tradisional Indonesia yang pembuatan motifnya dilakukan dengan mengikat benang sebelum ditenun dinamakan:',
      options: ['Tenun Ikat', 'Batik Cap', 'Bordir', 'Renda'],
      correctOptionIndex: 0,
      explanation: 'Tenun ikat mengikat kelompok benang lusi/pakan sebelum dicelup warna.',
    ),
    QuestionItem(
      id: 'fsh_040',
      questionText: 'Pakaian atas tradisional wanita Indonesia dari bahan halus yang dipadukan dengan kain jarik dinamakan:',
      options: ['Kebaya', 'Baju Bodo', 'Baju Kurung', 'Kemben'],
      correctOptionIndex: 0,
      explanation: 'Kebaya adalah busana bagian atas khas wanita Indonesia.',
    ),
    QuestionItem(
      id: 'fsh_041',
      questionText: 'Dokumen lembar spesifikasi teknis lengkap (sketsa flat, ukuran, bahan, dan aksesoris) untuk panduan pabrik jahit dinamakan:',
      options: ['Tech Pack (Technical Pack)', 'Moodboard', 'Lookbook', 'Catalog'],
      correctOptionIndex: 0,
      explanation: 'Tech Pack berisi instruksi rinci bagi konveksi/pabrik untuk memproduksi busana.',
    ),
    QuestionItem(
      id: 'fsh_042',
      questionText: 'Papan inspirasi visual berisi kompilasi foto, swatch kain, dan sampel warna untuk merancang tema koleksi mode dinamakan:',
      options: ['Moodboard Mode', 'Storyboard', 'Styleguide', 'Color Wheel'],
      correctOptionIndex: 0,
      explanation: 'Moodboard memvisualisasikan tema dan nuansa koleksi busana.',
    ),
    QuestionItem(
      id: 'fsh_043',
      questionText: 'Pakaian sampel pertama yang dibuat untuk diuji kelayakannya sebelum memproduksi masal dinamakan:',
      options: ['Sample Garment (Prototipe Baju)', 'Master Pattern', 'Dummy', 'Fitting Garment'],
      correctOptionIndex: 0,
      explanation: 'Sample garment dibuat untuk memeriksa potongan, pas badan, dan kerapihan jahit.',
    ),
    QuestionItem(
      id: 'fsh_044',
      questionText: 'Proses memperbesar atau memperkecil ukuran pola busana dari ukuran standar (seperti dari S ke M, L, XL) dinamakan:',
      options: ['Grading Pola', 'Draping', 'Drafting', 'Altering'],
      correctOptionIndex: 0,
      explanation: 'Grading pola meningkatkan atau menurunkan proporsi pola ke pelbagai ukuran.',
    ),
    QuestionItem(
      id: 'fsh_045',
      questionText: 'Sesi pengujian dan pencobaan busana pada tubuh model untuk memastikan kerapihan dan kenyamanan dinamakan:',
      options: ['Fitting', 'Runway', 'Catwalk', 'Styling'],
      correctOptionIndex: 0,
      explanation: 'Fitting dilakukan untuk penyesuaian akhir kelayakan busana di badan model.',
    ),
    QuestionItem(
      id: 'fsh_046',
      questionText: 'Hiasan sulaman benang dekoratif berbentuk pola hias di atas permukaan kain dinamakan:',
      options: ['Bordir (Embroidery)', 'Payet', 'Plisret', 'Patchwork'],
      correctOptionIndex: 0,
      explanation: 'Bordir (embroidery) adalah hiasan sulam benang pada kain.',
    ),
    QuestionItem(
      id: 'fsh_047',
      questionText: 'Hiasan manik-manik berkilau yang dijahit pada permukaan kain untuk memberi kesan mewah dinamakan:',
      options: ['Payet (Beading / Sequin)', 'Ruffle', 'Fringe', 'Tassel'],
      correctOptionIndex: 0,
      explanation: 'Payet (beading/sequin) memberikan kilauan ornamen pada busana pesta.',
    ),
    QuestionItem(
      id: 'fsh_048',
      questionText: 'Lipatan-lipatan kain sejajar yang dipres secara permanen (seperti pada rok rok plisret) dinamakan:',
      options: ['Plisret (Pleats)', 'Ruffle', 'Gathering', 'Smocking'],
      correctOptionIndex: 0,
      explanation: 'Pleats (plisret) adalah lipatan rapi berurut pada kain.',
    ),
    QuestionItem(
      id: 'fsh_049',
      questionText: 'Kerutan kain meliuk bergelombang yang digunakan sebagai ornamen pemanis busana dinamakan:',
      options: ['Ruffle (Rempel Melingkar)', 'Pleats', 'Tuck', 'Dart'],
      correctOptionIndex: 0,
      explanation: 'Ruffle adalah lajur kain berkerut meliuk sebagai hiasan.',
    ),
    QuestionItem(
      id: 'fsh_050',
      questionText: 'Kerah baju berbentuk pita tegak melingkar di leher tanpa lipatan membalik dinamakan kerah:',
      options: ['Kerah Shanghai / Mandarin Collar', 'Kerah Kemeja', 'Kerah Revers', 'Kerah Peter Pan'],
      correctOptionIndex: 0,
      explanation: 'Mandarin collar berdiri tegak melingkari leher tanpa daun kerah membalik.',
    ),
    QuestionItem(
      id: 'fsh_051',
      questionText: 'Jenis lengan baju di mana garis sambungan bahunya melintang miring dari leher langsung ke ketiak dinamakan lengan:',
      options: ['Raglan', 'Set-in sleeve', 'Lengan Licin', 'Lengan Kimono'],
      correctOptionIndex: 0,
      explanation: 'Lengan Raglan tidak memiliki garis sambungan bahu atas melainkan menyambung dari leher.',
    ),
    QuestionItem(
      id: 'fsh_052',
      questionText: 'Lengan baju berkerut mekar menggelembung besar di bagian puncak atau bawah lengan dinamakan lengan:',
      options: ['Lengan Balon (Puff Sleeve)', 'Lengan Licin', 'Lengan Cap', 'Lengan Tulip'],
      correctOptionIndex: 0,
      explanation: 'Puff sleeve memikat kesan menggelembung mekar penuh volume.',
    ),
    QuestionItem(
      id: 'fsh_053',
      questionText: 'Label petunjuk simbol instruksi pencucian dan pencetrikaan pada bagian dalam baju dinamakan:',
      options: ['Care Label', 'Brand Tag', 'Price Tag', 'Size Label'],
      correctOptionIndex: 0,
      explanation: 'Care label berisi simbol petunjuk perawatan kain agar awet.',
    ),
    QuestionItem(
      id: 'fsh_054',
      questionText: 'Satuan berat ketebalan bahan kain dalam gram per meter persegi dinamakan:',
      options: ['GSM (Grams per Square Meter)', 'DPI', 'Denier', 'Thread Count'],
      correctOptionIndex: 0,
      explanation: 'GSM mengukur bobot dan ketebalan massa kain per meter persegi.',
    ),
    QuestionItem(
      id: 'fsh_055',
      questionText: 'Proses pembersihan jas atau baju sensitif menggunakan pelarut kimia tanpa menggunakan air dinamakan:',
      options: ['Dry Cleaning', 'Washing Machine', 'Bleaching', 'Steaming'],
      correctOptionIndex: 0,
      explanation: 'Dry cleaning menggunakan cairan pelarut organik khusus pengganti air.',
    ),
    QuestionItem(
      id: 'fsh_056',
      questionText: 'Istilah teknis untuk ketahanan warna bahan tekstil terhadap pengaruh luntur saat dicuci atau terpapar matahari dinamakan:',
      options: ['Colorfastness (Tahan Luntur)', 'Shrinkage', 'Gramasi', 'Tensile Strength'],
      correctOptionIndex: 0,
      explanation: 'Colorfastness mengukur seberapa kuat warna menempel pada serat kain tanpa mudah luntur.',
    ),
    QuestionItem(
      id: 'fsh_057',
      questionText: 'Kecenderungan menyusutnya ukuran kain setelah dilakukan proses pencucian pertama dinamakan:',
      options: ['Shrinkage (Penyusutan)', 'Elongation', 'Abrasion', 'Pilling'],
      correctOptionIndex: 0,
      explanation: 'Shrinkage adalah fenomena berkurangnya dimensi kain akibat pencucian.',
    ),
    QuestionItem(
      id: 'fsh_058',
      questionText: 'Komponen bagian busana yang melingkari leher dinamakan:',
      options: ['Kerah (Collar)', 'Manset', 'Lapel', 'Saku'],
      correctOptionIndex: 0,
      explanation: 'Kerah (collar) menutupi atau menghiasi bagian leher busana.',
    ),
    QuestionItem(
      id: 'fsh_059',
      questionText: 'Ban tepi yang merapikan atau mengunci ujung lengan kemeja dinamakan:',
      options: ['Manset (Cuff)', 'Lapel', 'Kelim', 'Kupnat'],
      correctOptionIndex: 0,
      explanation: 'Manset (cuff) menutup atau mengencangkan pergelangan lengan baju.',
    ),
    QuestionItem(
      id: 'fsh_060',
      questionText: 'Garis bahu baju yang sengaja dibuat jatuh lebih rendah dari titik puncak bahu asli dinamakan:',
      options: ['Dropped Shoulder', 'Raglan', 'Off-shoulder', 'Cap sleeve'],
      correctOptionIndex: 0,
      explanation: 'Dropped shoulder memberikan tampilan santai dengan sambungan bahu agak turun.',
    ),
    QuestionItem(
      id: 'fsh_061',
      questionText: 'Kain pelapis bagian dalam busana yang bertekstur halus dan bersentuhan langsung dengan kulit dinamakan:',
      options: ['Furing (Lining)', 'Interfacing', 'Padding', 'Tulle'],
      correctOptionIndex: 0,
      explanation: 'Lining (furing) melapisi bagian dalam pakaian agar nyaman dan rapi.',
    ),
    QuestionItem(
      id: 'fsh_062',
      questionText: 'Balan pelapis tebal berbentuk dakron atau busa yang disisipkan di dalam jaket/bahu dinamakan:',
      options: ['Padding / Busa Bahu', 'Viselin', 'Kelim', 'Furing halus'],
      correctOptionIndex: 0,
      explanation: 'Padding memberi struktur tebal atau ketahanan dingin pada pakaian.',
    ),
    QuestionItem(
      id: 'fsh_063',
      questionText: 'Garis leher busana berpotongan tajam menyerupai bentuk huruf V dinamakan:',
      options: ['V-Neck', 'Crew Neck', 'Scoop Neck', 'Sweetheart Neck'],
      correctOptionIndex: 0,
      explanation: 'V-neck membentuk sudut runcing di bagian dada.',
    ),
    QuestionItem(
      id: 'fsh_064',
      questionText: 'Garis leher baju melengkung lebar horizontal mendekati bahu menyerupai bentuk perahu dinamakan:',
      options: ['Sabrina / Boat Neck', 'V-neck', 'Halterneck', 'Turtle neck'],
      correctOptionIndex: 0,
      explanation: 'Boat neck (Sabrina) membentang lebar di sepanjang tulang selangka.',
    ),
    QuestionItem(
      id: 'fsh_065',
      questionText: 'Jenis retsleting yang gigi rel kancingnya tidak terlihat dari luar saat dikancingkan dinamakan:',
      options: ['Invisible Zipper (Retsleting Jepang)', 'Metal Zipper', 'Open-end Zipper', 'Two-way Zipper'],
      correctOptionIndex: 0,
      explanation: 'Invisible zipper tersembunyi di dalam lipatan jahitan.',
    ),
    QuestionItem(
      id: 'fsh_066',
      questionText: 'Tali isi kain dekoratif yang dijahit di sepanjang sambungan jahitan busana dinamakan:',
      options: ['Piping (Paspol)', 'Bisban', 'Renda', 'Ruffle'],
      correctOptionIndex: 0,
      explanation: 'Piping menyelipkan tali terbungkus kain sebagai pembatas tepi jahitan.',
    ),
    QuestionItem(
      id: 'fsh_067',
      questionText: 'Pita kain serong yang dipotong miring 45 derajat untuk merapikan tepi lingkaran kerung leher dinamakan:',
      options: ['Bisban (Bias Tape)', 'Kelim', 'Piping', 'Kampuh'],
      correctOptionIndex: 0,
      explanation: 'Bisban elastis mengikuti lengkungan karena dipotong serong (bias).',
    ),
    QuestionItem(
      id: 'fsh_068',
      questionText: 'Teknik pemotongan kain miring 45 derajat terhadap garis lusi untuk menghasilkan efek busana meliuk fleksibel dinamakan:',
      options: ['Bias Cut', 'Straight Cut', 'Cross Cut', 'Pattern Cut'],
      correctOptionIndex: 0,
      explanation: 'Bias cut memanfaatkan elastisitas alami sudut miring kain.',
    ),
    QuestionItem(
      id: 'fsh_069',
      questionText: 'Celana panjang wanita dengan potongan pipa sangat lebar menyerupai rok dinamakan:',
      options: ['Palazzo', 'Kulot', 'Jogger', 'Chino'],
      correctOptionIndex: 0,
      explanation: 'Celana Palazzo longgar dan sangat lebar memanjang hingga semata kaki.',
    ),
    QuestionItem(
      id: 'fsh_070',
      questionText: 'Celana panjang menggantung yang panjangnya di antara lutut dan betis dinamakan:',
      options: ['Culottes (Kulot)', 'Palazzo', 'Cargo', 'Legging'],
      correctOptionIndex: 0,
      explanation: 'Kulot adalah celana berkaki lebar dengan panjang tanggung.',
    ),
    QuestionItem(
      id: 'fsh_071',
      questionText: 'Jas resmi pria berwarna gelap dengan lapel berkilau yang dikenakan untuk acara perjamuan malam dinamakan:',
      options: ['Tuxedo', 'Blazer', 'Cardigan', 'Parka'],
      correctOptionIndex: 0,
      explanation: 'Tuxedo adalah busana malam resmi pria dengan detail satin pada kerah lapel.',
    ),
    QuestionItem(
      id: 'fsh_072',
      questionText: 'Penutup kepala terintegrasi yang menyatu pada bagian leher jaket dinamakan:',
      options: ['Hoodie / Kapuchon', 'Beret', 'Beanie', 'Fedora'],
      correctOptionIndex: 0,
      explanation: 'Hoodie (kapuchon) adalah tudung kepala yang menyatu pada baju/jaket.',
    ),
    QuestionItem(
      id: 'fsh_073',
      questionText: 'Istilah dunia mode untuk rancangan pakaian eksperimental yang tidak lazim dan mendobrak tradisi dinamakan:',
      options: ['Avant-Garde', 'Vintage', 'Classic', 'Casual'],
      correctOptionIndex: 0,
      explanation: 'Avant-Garde merupakan karya seni mode konseptual dan futuristik.',
    ),
    QuestionItem(
      id: 'fsh_074',
      questionText: 'Pagelaran peragaan busana di atas panggung oleh para model untuk memamerkan koleksi desainer dinamakan:',
      options: ['Fashion Show / Runway', 'Photoshoot', 'Exhibition', 'Bazaar'],
      correctOptionIndex: 0,
      explanation: 'Fashion show mempresentasikan koleksi rancangan terbaru desainer.',
    ),
    QuestionItem(
      id: 'fsh_075',
      questionText: 'Panggung memanjang tempat para model berjalan memperagakan busana dinamakan:',
      options: ['Catwalk', 'Stage', 'Backstage', 'Auditorium'],
      correctOptionIndex: 0,
      explanation: 'Catwalk adalah jalur panggung bagi peragaan model.',
    ),
    QuestionItem(
      id: 'fsh_076',
      questionText: 'Gaya berbusana klasik masa lalu yang dipopulerkan kembali di era modern dinamakan gaya:',
      options: ['Vintage / Retro', 'Futuristik', 'Minimalis', 'Bohemian'],
      correctOptionIndex: 0,
      explanation: 'Vintage merujuk pada gaya atau busana asli dari era terdahulu.',
    ),
    QuestionItem(
      id: 'fsh_077',
      questionText: 'Gaya berbusana santai sehari-hari yang berakar dari budaya jalanan dan komunitas perkotaan dinamakan:',
      options: ['Streetwear', 'Formalwear', 'Sleepwear', 'Activewear'],
      correctOptionIndex: 0,
      explanation: 'Streetwear tumbuh dari budaya skate, hip-hop, dan tren jalanan modern.',
    ),
    QuestionItem(
      id: 'fsh_078',
      questionText: 'Tren memadukan pakaian olahraga (seperti legging/sweatpants) dalam penampilan sehari-hari dinamakan:',
      options: ['Athleisure', 'Workwear', 'Loungewear', 'Preppy'],
      correctOptionIndex: 0,
      explanation: 'Athleisure menggabungkan kenyamanan atletik dengan gaya kasual.',
    ),
    QuestionItem(
      id: 'fsh_079',
      questionText: 'Lembaga atau spesialis yang memprediksi arah tren warna, bahan, dan gaya mode masa depan dinamakan:',
      options: ['Trend Forecaster', 'Fashion Police', 'Stylist', 'Buyer'],
      correctOptionIndex: 0,
      explanation: 'Trend Forecaster memprediksi preferensi konsumen dan tren mode tahun mendatang.',
    ),
    QuestionItem(
      id: 'fsh_080',
      questionText: 'Teknik pewarnaan kain celup rintang tradisional dari Jepang menggunakan ikatan dan lipatan benang dinamakan:',
      options: ['Shibori', 'Tie-Dye', 'Batik', 'Sashiko'],
      correctOptionIndex: 0,
      explanation: 'Shibori adalah seni celup rintang kain khas Jepang.',
    ),
    QuestionItem(
      id: 'fsh_081',
      questionText: 'Teknik pewarnaan kain celup rintang modern yang menghasilkan corak warna-warni spiral melingkar dinamakan:',
      options: ['Tie-Dye', 'Shibori', 'Bordir', 'Sablon Plastisol'],
      correctOptionIndex: 0,
      explanation: 'Tie-dye mengikat kain sebelum dicelupkan ke pewarna.',
    ),
    QuestionItem(
      id: 'fsh_082',
      questionText: 'Alat pemotong kain dengan mata pisau berbentuk gerigi zig-zag untuk mencegah tepi kain terurai dinamakan:',
      options: ['Gunting Bergerigi (Pinking Shears)', 'Gunting Benang', 'Cutter Tekstil', 'Pahat'],
      correctOptionIndex: 0,
      explanation: 'Pinking shears memotong tepi kain dalam bentuk zig-zag anti-terurai.',
    ),
    QuestionItem(
      id: 'fsh_083',
      questionText: 'Pita ukur fleksibel yang digunakan oleh penjahit untuk mengukur lingkar tubuh dinamakan:',
      options: ['Metlin (Tape Measure)', 'Penggaris Siku', 'Jangka', 'Micrometer'],
      correctOptionIndex: 0,
      explanation: 'Metlin adalah pita ukur lentur untuk mengukur kontur tubuh.',
    ),
    QuestionItem(
      id: 'fsh_084',
      questionText: 'Kapur khusus tekstil yang digunakan untuk memberi tanda pada kain dan mudah dihapus dinamakan:',
      options: ['Kapur Jahit (Tailor\'s Chalk)', 'Pensil Warna', 'Krayon', 'Spidol'],
      correctOptionIndex: 0,
      explanation: 'Kapur jahit memberi tanda sementara di permukaan kain.',
    ),
    QuestionItem(
      id: 'fsh_085',
      questionText: 'Alat beroda gigi kecil yang digunakan bersama kertas karbon untuk memindahkan garis pola ke kain dinamakan:',
      options: ['Rader (Tracing Wheel)', 'Canting', 'Jarum Pentul', 'Pendedel'],
      correctOptionIndex: 0,
      explanation: 'Rader menjiplak penandaan garis pola dari kertas ke kain.',
    ),
    QuestionItem(
      id: 'fsh_086',
      questionText: 'Jarum kecil berujung tajam berkepala plastik yang digunakan untuk menyematkan pola pada kain dinamakan:',
      options: ['Jarum Pentul (Pins)', 'Jarum Jahit', 'Jarum Kasur', 'Peniti'],
      correctOptionIndex: 0,
      explanation: 'Jarum pentul menahan posisi pola atau sambungan kain sementara sebelum dijahit.',
    ),
    QuestionItem(
      id: 'fsh_087',
      questionText: 'Boneka tiruan tubuh manusia yang digunakan untuk fitting dan draping busana dinamakan:',
      options: ['Passpop / Manekin (Dress Form)', 'Croquis', 'Dummy Sketsa', 'Hanger'],
      correctOptionIndex: 0,
      explanation: 'Passpop/manekin adalah patung bentuk tubuh untuk merancang baju.',
    ),
    QuestionItem(
      id: 'fsh_088',
      questionText: 'Alat jahit berkait kecil yang digunakan untuk melepas kembali jahitan yang salah dinamakan:',
      options: ['Pendedel (Seam Ripper)', 'Rader', 'Jarum Pentul', 'Tang jahit'],
      correctOptionIndex: 0,
      explanation: 'Pendedel (seam ripper) memotong dan melepas benang stik jahitan.',
    ),
    QuestionItem(
      id: 'fsh_089',
      questionText: 'Pakaian dalam penahan bentuk tubuh wanita agar postur tampak ramping dan tegak dinamakan:',
      options: ['Korset (Corset)', 'Kemben', 'Bustier', 'Shapewear'],
      correctOptionIndex: 0,
      explanation: 'Korset mengencangkan daerah pinggang dan menopang dada.',
    ),
    QuestionItem(
      id: 'fsh_090',
      questionText: 'Bagian kerah bajujas yang terlipat membalik ke arah dada dinamakan:',
      options: ['Lapel', 'Manset', 'Kelim', 'Notch'],
      correctOptionIndex: 0,
      explanation: 'Lapel adalah lipatan bagian dada kerah jas/blazer.',
    ),
    QuestionItem(
      id: 'fsh_091',
      questionText: 'Saku busana yang ditempelkan langsung di bagian luar kain (seperti pada kemeja kasual) dinamakan:',
      options: ['Saku Tempel (Patch Pocket)', 'Saku Bobok', 'Saku Sisi', 'Saku Rahasia'],
      correctOptionIndex: 0,
      explanation: 'Patch pocket dijahit di atas permukaan kain luar.',
    ),
    QuestionItem(
      id: 'fsh_092',
      questionText: 'Saku tersembunyi yang dibuat dengan membelah kain (seperti pada celana bahan atau jas) dinamakan:',
      options: ['Saku Bobok (Welt Pocket)', 'Saku Tempel', 'Saku Kanguru', 'Saku Cargo'],
      correctOptionIndex: 0,
      explanation: 'Welt pocket dibuat dengan bukaan belahan kain bercelah rapi.',
    ),
    QuestionItem(
      id: 'fsh_093',
      questionText: 'Kancing hiasan logam yang dipasang pada manset kemeja resmi pria dinamakan:',
      options: ['Cufflinks', 'Studs', 'Kancing Jepret', 'Brooch'],
      correctOptionIndex: 0,
      explanation: 'Cufflinks mengunci kedua sisi manset kemeja formal.',
    ),
    QuestionItem(
      id: 'fsh_094',
      questionText: 'Sabuk kain lebar berlipat yang melingkari pinggang saat mengenakan busana tuxedo dinamakan:',
      options: ['Cummerbund', 'Obi', 'Gesper', 'Suspender'],
      correctOptionIndex: 0,
      explanation: 'Cummerbund adalah pita pinggang kain khas busana malam tuxedo.',
    ),
    QuestionItem(
      id: 'fsh_095',
      questionText: 'Bahan tekstil berbahan kulit hewan yang telah melalui proses penyamakan dinamakan:',
      options: ['Kulit (Leather)', 'Suede', 'Velvet', 'Canvas'],
      correctOptionIndex: 0,
      explanation: 'Leather diolah dari kulit hewan melalui proses penyamakan.',
    ),
    QuestionItem(
      id: 'fsh_096',
      questionText: 'Jenis bahan kulit dengan permukaan berbulu halus lembut meniru bagian dalam kulit dinamakan:',
      options: ['Suede', 'Patent Leather', 'Nylon', 'Denim'],
      correctOptionIndex: 0,
      explanation: 'Suede memiliki tekstur menggebu halus berbulu pendek.',
    ),
    QuestionItem(
      id: 'fsh_097',
      questionText: 'Kain berbulu halus dan padat yang memberikan kesan sangat mewah dan hangat dinamakan:',
      options: ['Bludru (Velvet)', 'Satin', 'Organza', 'Tulle'],
      correctOptionIndex: 0,
      explanation: 'Velvet (bludru) memiliki serat jalinan rumbai berbulu halus dan mewah.',
    ),
    QuestionItem(
      id: 'fsh_098',
      questionText: 'Kain jala tipis berlubang-lubang kecil yang sering dipakai untuk gaun pengantin dan tutu dinamakan:',
      options: ['Tulle (Kain Tile)', 'Organza', 'Chiffon', 'Lace'],
      correctOptionIndex: 0,
      explanation: 'Tulle adalah kain jaring ringan yang memberikan volume pada gaun.',
    ),
    QuestionItem(
      id: 'fsh_099',
      questionText: 'Kain tipis menerawang yang sangat ringan dan sering dipakai untuk selendang atau gaun melayang adalah:',
      options: ['Chiffon (Sifon)', 'Denim', 'Drill', 'Canvas'],
      correctOptionIndex: 0,
      explanation: 'Chiffon adalah bahan menerawang yang sangat ringan dan lembut jatuhnya.',
    ),
    QuestionItem(
      id: 'fsh_100',
      questionText: 'Disiplin ilmu dan seni yang mengolah perancangan busana, estetika, dan pembuatan pakaian dinamakan:',
      options: ['Desain Mode (Fashion Design)', 'Desain Interior', 'Kriya Kayu', 'Tata Rias'],
      correctOptionIndex: 0,
      explanation: 'Desain Mode mengombinasikan kreativitas estetika busana dengan teknik pembuatan pakaian.',
    ),
  ];
}
