// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/marahi_anak/marahi_anak_dialog_npc.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class MarahiAnakDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat dimarahi orang tua berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Hwaaaaa! ( * $npcName menangis kencang sambil menutupi matanya yang basah * ) 😿👶',
        'Uuuu... ( * $npcName merembeskan air mata dan bersembunyi di belakang sudut sofa * )',
        'Bababa... ( * $npcName gemetaran ketakutan mendengarkan nada suara tegas $parentName * )',
        'Gigaaa... ( * $npcName menundukkan kepala mungilnya dengan bibir melengkung sedih * )',
        'Ooooh... ( * $npcName mengulurkan tangan kecilnya minta dipeluk sambil menangis sesenggukan * )',
        'Nyaaa... ( * $npcName menjatuhkan mainan yang dipegangnya lalu menunduk sedih * )',
        'Abuuu... ( * $npcName mengusap matanya yang merah dengan kepalan tangan mungil * )',
        'Mammm... ( * $npcName merangkak pelan mendekati $parentName sambil memohon ampun * )',
        'Dayaya... ( * $npcName terkejut dan memeluk boneka empuknya erat-erat * )',
        'Tetete... ( * $npcName menghentikan tangisnya sebentar lalu sesenggukan kembali * )',
        'Kicukicu... ( * $npcName menatap $parentName dengan mata bulat yang penuh air mata * )',
        'Ehhhe... ( * $npcName menggeleng-gelengkan kepalanya seolah berjanji tidak mengulanginya * )',
        'Agiii... ( * $npcName menyembunyikan wajahnya di lipatan baju bayinya * )',
        'Owooo... ( * $npcName merosot pelan di karpet sambil menangis pelan * )',
        'Bubu! ( * $npcName memejamkan mata ketakutan mendengarkan teguran * )',
        'Lalala... ( * $npcName mengeluarkan suara tangisan kecil yang memilukan * )',
        'Hummm... ( * $npcName mengusip hidung merahnya sambil menatap $parentName iba * )',
        'Cicu... ( * $npcName menggenggam ujung celana $parentName sambil meminta maaf * )',
        'Nyaa-ha... ( * $npcName tersedak tangisnya sendiri lalu merangkak minta pangku * )',
        'Paapapa... ( * $npcName menunjuk kesalahan kecilnya dengan wajah bersalah * )',
        'Glooogloo... ( * $npcName duduk terdiam dengan wajah sangat sedih * )',
        'Oowgh... ( * $npcName merapatkan kedua tangannya di dada seperti meminta ampun * )',
        'Yaaaya... ( * $npcName meneteskan air mata hangat di atas pipi tembemnya * )',
        'Wiii... ( * $npcName memeluk kaki $parentName sambil menangis pelan * )',
        'Tatatata... ( * $npcName tertidur lemas setelah lelah menangis dipukul/dimarahi * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Hwaaa! Maafin aku $parentName! Aku janji nggak bakal ngulangin lagi! 😿💔',
        'Aku minta maaf $parentName... Jangan marah lagi ya, aku takut...',
        'Huuu... Aku cuma bercanda tadi $parentName, maafin kesalahan aku ya...',
        'Jangan galak-galak $parentName... Hatiku sakit dimarahi kayak gini...',
        'Maaf $parentName! Nanti aku beresin mainan yang berantakan ini sekarang juga!',
        'Aku janji bakal jadi anak nurut $parentName... Tolong jangan bentak aku...',
        'Huuuaaa! Aku sayang $parentName, jangan benci aku ya...',
        'Maafin aku $parentName! Aku nggak sengaja numpahin makanan/ngerusak benda itu...',
        'Aku janji nggak bakal bohong atau nakal lagi $parentName...',
        'Iya $parentName, aku salah... Sini aku peluk $parentName biar nggak marah lagi...',
        'Huuu... Mata $parentName kalau marah seram banget, aku minta maaf ya...',
        'Maaf ya $parentName... Nanti aku turuti semua kata-kata $parentName...',
        'Jangan kunci aku di kamar $parentName! Aku takut... Maafin kesalahan aku...',
        'Aku janji bakal berbagi mainan sama teman $parentName, jangan marah ya...',
        'Maaf $parentName... Aku ngaku salah dan nggak bakal nakal lagi di TK...',
        'Huuuaaa! Peluk aku dong $parentName, aku udah minta maaf tulus nih...',
        'Iya $parentName, besok aku nggak bakal main HP/nonton TV kelamaan lagi...',
        'Maafkan aku $parentName... Aku mau jadi anak baik pilihan $parentName...',
        'Aku bakal minta maaf juga sama teman yang aku usilin $parentName...',
        'Jangan diemin aku $parentName... Bicara lagi sama aku dong, maaf ya...',
        'Huuu... Aku janji bakal mandi dan makan tepat waktu $parentName...',
        'Maaf $parentName! Tolong senyum lagi seperti biasa ya...',
        'Aku menyesal banget $parentName... Maafin aku ya...',
        'Iya $parentName, aku paham... Jangan marah-marah lagi ya $parentName...',
      ];
    } else if (childAge <= 11) {
      return [
        'Maafkan saya $parentName... Saya akuin saya salah dan teledor. 😿😞',
        'Saya minta maaf $parentName... Saya tidak akan mengulanginya lagi di masa depan.',
        'Jangan marah lagi ya $parentName... Saya janji bakal belajar lebih rajin dan disiplin.',
        'Saya paham alasan $parentName menegur saya. Maafkan atas kekecewaan yang saya buat.',
        'Maaf $parentName, saya Janji akan memperbaiki nilai dan kesalahan saya di sekolah.',
        'Saya tidak bermaksud membangkang $parentName... Tolong maafkan kekhilafan saya.',
        'Maafkan saya $parentName... Saya bakal langsung beresin tugas dan kewajiban saya.',
        'Teguran $parentName memang benar... Saya menyesal sudah bersikap tidak jujur/malas.',
        'Saya mohon maaf $parentName... Tolong beri saya kesempatan untuk memperbaiki diri.',
        'Maafkan saya $parentName... Saya janji akan lebih menghormati aturan di rumah.',
        'Saya tahu $parentName marah demi kebaikan saya... Maafkan sikap childish saya.',
        'Tolong jangan kecewa sama saya $parentName... Saya akan berubah jadi lebih baik.',
        'Maaf $parentName, saya janji tidak akan main game sampai larut malam lagi.',
        'Saya menerima konsekuensi kesalahan saya $parentName... Sekali lagi saya minta maaf.',
        'Maafkan saya $parentName... Saya sadar perbuatan saya sudah merugikan.',
        'Saya janji bakal lebih mendengarkan nasihat dan teguran dari $parentName.',
        'Tolong maafin saya $parentName... Bicara baik-baik lagi sama saya ya.',
        'Saya tidak akan mencari alasan lagi $parentName... Maaf atas kelakuan saya.',
        'Maafkan saya $parentName... Saya bersedia menjalani hukuman/disiplin yang diberikan.',
        'Saya sangat menyesal sudah membuat $parentName emosi dan sedih.',
        'Maaf $parentName... Beri saya waktu untuk membuktikan bahwa saya bisa berubah.',
        'Saya berjanji akan menjadi anak yang lebih bertanggung jawab dan jujur.',
        'Maafkan kekasaran atau pembangkangan saya tadi $parentName... Saya menyesal.',
        'Terima kasih sudah mengingatkan saya $parentName... Maafkan atas kesalahan saya.',
        'Saya janji tidak akan mengecewakan kepercayaan $parentName lagi!',
      ];
    } else {
      return [
        'Saya minta maaf yang sebesar-besarnya $parentName... Saya menyadari kesalahan saya. 😔💔',
        'Saya paham kekecewaan $parentName. Mohon maaf atas tindakan irasional saya.',
        'Teguran $parentName sangat masuk akal. Saya berjanji akan mengevaluasi diri saya.',
        'Mohon maaf atas sikap emosional atau pembangkangan saya tadi, $parentName.',
        'Saya sadar perbuatan saya telah melukai perasaan dan kepercayaan $parentName.',
        'Maafkan saya $parentName... Saya bertanggung jawab penuh atas konsekuensi kesalahan ini.',
        'Saya tidak akan membela diri lagi. Maafkan atas ketidakdewasaan sikap saya.',
        'Tolong beri saya maaf $parentName. Saya sangat menghargai nasihat ketegasan $parentName.',
        'Saya janji akan memperbaiki gaya hidup dan keputusan saya di masa mendatang.',
        'Mohon maaf $parentName... Saya bersedia menerima hukuman atau sanksi yang adil.',
        'Saya mengerti $parentName menegur demi kebaikan dan masa depan saya sendiri.',
        'Maafkan saya $parentName... Hubungan dan keharmonisan keluarga ini adalah yang utama bagi saya.',
        'Saya menyesal telah mengabaikan nasihat dan arahan yang $parentName berikan.',
        'Tolong jangan biarkan amarah ini merusak ikatan batin kita, $parentName. Saya minta maaf.',
        'Saya berjanji akan berubah menjadi pribadi yang lebih bijaksana dan mengontrol diri.',
        'Mohon maaf $parentName... Terima kasih telah menegur kesalahan saya secara terbuka.',
        'Saya sadar kesalahan ini tidak patut dilakukan oleh seseorang di usia saya. Maafkan saya.',
        'Saya akan berusaha keras merebut kembali kepercayaan $parentName yang sempat cedera.',
        'Maafkan saya $parentName... Bicara sejuk lagi dengan saya kalau amarah $parentName sudah reda.',
        'Saya sangat memohon ampunan atas khilaf dan kesombongan sikap saya tadi.',
        'Terima kasih telah menyadarkan saya dari jalan yang salah, $parentName. Maafkan saya.',
        'Saya janji akan menyelesaikan masalah ini secara dewasa dan bertanggung jawab.',
        'Mohon maaf atas beban pikiran yang saya munculkan bagi $parentName.',
        'Saya mencintai $parentName dan tidak ingin menjadi anak yang durhaka. Maafkan saya.',
        'Saya bertekad menjadi pribadi yang lebih membanggakan di masa depan!',
      ];
    }
  }
}
