// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/marahi_anak/marahi_anak_dialog_user.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class MarahiAnakDialogUser {
  /// Mengembalikan list 100 variasi dialog User (Orang Tua) saat memarahi/menegur anaknya
  static List<String> getUserDialogues({
    required String childName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Tidak boleh begitu $childName! Bahaya tau! $parentName tegur biar kamu selamat! 😠👶',
        'Jangan dimasukkan ke mulut barang kotor itu sayang! Nanti kamu sakit perut!',
        'Stop membanting mainan dan menangis tanpa sebab $childName! Dengarkan $parentName!',
        'Jangan coret-coret tembok dan lempar makanan ya nak! Itu perbuatan tidak baik!',
        'Sini diam dulu sayang! $parentName marahi sedikit biar kamu paham mana yang boleh dan tidak!',
        'Dengarkan kata-kata $parentName ya! Jangan asal memukul atau menggigit orang lain!',
        'Teguran ini demi kebaikan dan keselamatanmu sendiri buah hatiku!',
        'Jangan nakal ya $childName! $parentName tidak suka kalau kamu main air/listrik!',
        'Duduk manis dan berhenti menjerit-jerit sayang! $parentName ingin kamu bersikap tenang.',
        'Ini teguran penuh kasih dari $parentName agar kamu tidak tumbuh menjadi anak sembrono!',
        'Jangan menarik-narik ekor hewan atau benda tajam ya! Bahaya sekali anakku!',
        'Dengarkan baik-baik, perbuatan membangkang tidak akan membuatmu mendapatkan keinginanmu!',
        'Jangan makan sambil berlarian ya $childName! Nanti tersedak dan membahayakanmu!',
        'Nih $parentName rapikan barang yang kamu rusal, dan kamu harus berjanji tidak mengulangnya!',
        'Meskipun kamu masih bayi, kamu harus belajar disiplin dan sopan santun sejak kecil!',
        'Ayo hapus air matamu, $parentName menegur bukan karena benci tapi karena sangat menyayangimu.',
        'Jangan buang makanan ke lantai ya nak! Kita harus selalu menghargai rezeki.',
        'Nanti kalau kamu cedera karena tidak mendengarkan $parentName, siapa yang sedih? $parentName juga!',
        'Berhentilah mengamuk (tantrum) tanpa alasan yang jelas $childName! Tenangkan dirimu.',
        'Ini tindakan tegas dari $parentName demi membentuk pola perilaku yang sehat untukmu.',
        'Jangan rebut mainan teman dengan kasar ya sayang! Minta baik-baik atau bergantian.',
        'Semoga kamu memahami maksud baik dari teguran $parentName ini ya nak.',
        'Nanti kalau sudah tenang, baru $parentName peluk dan jelaskan lagi kesalahannya ya.',
        'Ketegasan $parentName hari ini adalah fondasi keselamatan dan kelangsungan tumbuh kembangmu.',
        'Ingat baik-baik nasihat $parentName, jangan diulangi lagi ya anak manis!',
      ];
    } else if (childAge <= 5) {
      return [
        'Kenapa kamu nakal & tidak nurut $childName?! $parentName marahi biar kamu paham aturan! 😠💔',
        'Kenapa mainan tidak dirapikan kembali setelah main?! Ayo beresin sekarang juga!',
        'Tidak boleh bohong atau membantah perkataan $parentName ya! Itu perbuatan tercela!',
        'Kenapa kamu usilin dan pukul teman di TK?! $parentName malu dan kecewa sama sikapmu!',
        'Jangan main HP / nonton TV seharian tanpa belajar dan makan tepat waktu $childName!',
        'Minta maaf sekarang juga kepada orang yang kamu rugikan/usili! Berperilakulah yang santun!',
        'Kalau kamu terus-terusan tantrum dan menjerit, $parentName tidak akan beri izin jajan!',
        'Dengarkan nasihat orang tua! Jangan asal lari-larian di jalan raya atau tempat berbahaya!',
        'Teguran keras ini $parentName berikan karena $parentName sangat peduli dengan masa depanmu!',
        'Kembalikan barang yang kamu ambil tanpa izin itu! Kejujuran nomor satu dalam keluarga kita!',
        'Jangan buang-buang makanan dan merajuk tanpa sebab ya $childName! Bersyukurlah!',
        'Ayo berdiri dan akui kesalahanmu dengan jujur! Anak berani harus bertanggung jawab!',
        'Kenapa kamu coret-coret tembok rumah pakai spidol?! Dinding rumah bukan buku gambar!',
        'Nih rasakan akibatnya kalau tidak mau pakai sepatu/baju hangat! Dengarkan $parentName!',
        'Jangan malas mandi dan gosok gigi ya! $parentName tegur biar kamu tidak kena penyakit!',
        'Ayo minta maaf dan janji tidak akan mengulangi perbuatan salah ini lagi!',
        'Ketegasan ini adalah bentuk pendidikan karakter agar kamu jadi anak yang tangguh dan santun.',
        'Jangan membangkang ketika dipanggil $parentName! Tatap mata $parentName kalau disebuti nasihat!',
        'Bila kamu tidak disiplin, $parentName akan sita mainan kesukaanmu untuk sementara waktu!',
        'Ingat ya $childName, perbuatan nakal akan membawa dampak buruk bagi dirimu sendiri!',
        'Ubah sikapmu menjadi lebih sopan dan ramah! $parentName ingin kamu jadi anak kebanggaan.',
        'Nasihat dan marahan dari $parentName ini tanda bahwa $parentName tidak ingin kamu tersesat.',
        'Tenangkan emosimu dan mulailah belajar mematuhi aturan keluarga yang ada di rumah.',
        'Ayo berdiri tegak, akui salah, dan berjanjilah menjadi anak yang patuh pada orang tua!',
        'Semoga teguran ini memberikan pelajaran berharga agar kamu tidak mengulanginya esok hari!',
      ];
    } else if (childAge <= 11) {
      return [
        'Kenapa kamu malas belajar & main game sampai larut $childName?! $parentName sangat kecewa! 😠🏫',
        'Kenapa nilai sekolahmu turun drastis dan tugas tidak dikerjakan?! Mana tanggung jawabmu?!',
        'Jangan sekali-kali bersikap tidak jujur atau bohong kepada orang tua dan gurumu!',
        'Kenapa kamu bersikap kasar dan membangkang saat diberi nasihat baik-baik?!',
        'Patuhi aturan jam belajar dan jam tidur di rumah ini! Jangan seenaknya sendiri $childName!',
        'Segera selesaikan kewajiban belajarmu sebelum menyentuh barang permainan atau gadget!',
        'Kenapa kamu melanggar janji yang sudah kamu sepakati bersama $parentName kemarin?!',
        'Ketegasan $parentName ini demi masa depan dan keberhasilan pendidikansmu kelak!',
        'Berfikirlah sebelum bertindak! Jangan terbawa pengaruh buruk teman sebayamu di luar!',
        'Tolong hargai usaha keras $parentName membiayai sekolah dan kebutuhanmu dengan disiplin!',
        'Minta maaf dan perbaiki kesalahanmu sekarang juga! Anak dewasa harus berani bertanggung jawab.',
        'Jika kamu terus-menerus malas dan membangkang, $parentName akan batasi uang jajan & gadgetmu!',
        'Jaga sopan santun dan etika komunikasimu! Jangan bicara dengan nada tinggi kepada orang tua!',
        'Perhatikan kebersihan kamar dan barang pribadi milikmu! Jangan biarkan berantakan!',
        'Kenapa kamu tidak mendengarkan pesan $parentName saat bepergian keluar rumah?!',
        'Belajarlah dari kesalahan ini dan jangan pernah mengulanginya lagi di kemudian hari!',
        'Ketegasan dan sanksi ini $parentName berikan agar kamu memahami arti sebuah tanggung jawab.',
        'Ingat ya $childName, disiplin waktu dan kejujuran adalah kunci utama kesuksesan hidup.',
        'Ayo renungkan perbuatanmu di dalam kamar dan pikirkan bagaimana cara memperbaikinya!',
        'Jangan mencari-cari alasan untuk membela kesalahan yang jelas-jelas kamu lakukan!',
        'Ubah pola hidupmu menjadi lebih teratur, rajin, dan menghormati sesama!',
        'Orang tua memarahi bukan karena benci, tapi karena ingin meluruskan jalanmu yang mulai bengkok.',
        'Fokuslah pada impian dan studimu! Jangan sia-siakan waktu mudamu dengan hal yang sia-sia.',
        'Ayo minta maaf atas pembangkanganmu dan tunjukkan perubahan nyata mulai hari ini!',
        'Semoga teguran keras ini menyadarkanmu untuk menjadi anak yang lebih dewasa dan bijaksana!',
      ];
    } else {
      return [
        'Kamu sudah remaja/dewasa $childName! Sikap ceroboh & tak bertanggung jawab ini tidak bisa ditoleransi! 😠💔',
        'Kenapa kamu melanggar nilai-nilai moral dan aturan keluarga yang sudah kita tanamkan?!',
        'Mana tanggung jawabmu sebagai seorang yang sudah berpendidikan dan dewasa?!',
        'Jangan menyia-nyiakan kepercayaan besar yang telah $parentName berikan padamu selama ini!',
        'Kenapa kamu mengambil keputusan tanpa memikirkan dampak panjang bagi dirimu dan keluarga?!',
        'Berpikirlah secara rasional dan matang! Jangan bertindak emosional dan merugikan masa depanmu!',
        'Tolong hargai jerih payah, keringat, dan doa orang tua yang telah membesarkanmu!',
        'Ketegasan ini $parentName utarakan karena $parentName tidak ingin melihatmu tersesat di jalan yang salah.',
        'Akui kesalahanmu dengan lapang dada dan selesaikan masalah ini secara bijaksana dan dewasa!',
        'Jangan menyalahkan lingkungan atau orang lain atas keputusan buruk yang kamu ambil sendiri!',
        'Jika kamu terus memelihara sikap egois dan enggan mendengarkan nasihat, kamu akan menyesal kelak.',
        'Perbaiki pola komunikasi dan komunikasikan masalahmu dengan jujur tanpa ada yang disembunyikan!',
        'Jaga nama baik keluarga dan kehormatan dirimu di mana pun kamu berada!',
        'Kembalikan fokus hidupmu pada tujuan utama, karir, pendidikan, dan ibadahmu yang benar!',
        'Sanksi dan teguran ini adalah wujud kasih sayang terdalam orang tua untuk menyelamatkanmu.',
        'Belajarlah mengendalikan emosi dan bersikap lebih rendah hati serta menghormati orang tua.',
        'Jangan biarkan pergaulan bebas atau kebiasaan buruk merusak potensi besar yang kamu miliki!',
        'Renungkan dengan jernih nasihat $parentName ini sebelum semuanya terlambat!',
        'Ayo bangun integritas dirimu kembali! Buktikan bahwa kamu sanggup memperbaiki kekhilafan ini.',
        'Tidak ada tempat untuk kesombongan atau rasa paling benar di tengah keharmonisan keluarga kita.',
        'Tunjukkan iktikad baik dan perubahan nyata dalam tindakan harianmu mulai detik ini!',
        'Orang tua hanya ingin melihatmu sukses, selamat, dan menjadi manusia yang berguna bagi dunia.',
        'Selesaikan kewajibanmu dengan tuntas dan bertanggung jawab sebagai sosok yang dewasa!',
        'Minta maaf dan mulailah lembaran baru yang lebih bersih, jujur, dan beradab!',
        'Semoga ketegasan ini menjadi titik balik pendewasaan diri bagi masa depanmu yang cemerlang!',
      ];
    }
  }
}
