import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPendidikanAgamaKatolikQuestions() {
  return const [
    QuestionItem(
      id: 'pkat_001',
      questionText: 'Kitab Suci Gereja Katolik terdiri dari Perjanjian Lama dan Perjanjian Baru. Berapa jumlah kitab Deuterokanonika dalam Perjanjian Lama Katolik?',
      options: ['7 Kitab', '10 Kitab', '5 Kitab', '12 Kitab'],
      correctOptionIndex: 0,
      explanation: 'Gereja Katolik mengakui 7 kitab Deuterokanonika (Tobit, Yudit, Tambahan Ester, 1-2 Makabe, Kebijaksanaan Salomo, Sirakh, Barukh).',
    ),
    QuestionItem(
      id: 'pkat_002',
      questionText: 'Total jumlah kitab dalam Alkitab Katolik adalah:',
      options: ['73 Kitab', '66 Kitab', '70 Kitab', '80 Kitab'],
      correctOptionIndex: 0,
      explanation: 'Alkitab Katolik terdiri dari 73 kitab (46 Perjanjian Lama + 27 Perjanjian Baru).',
    ),
    QuestionItem(
      id: 'pkat_003',
      questionText: 'Sakramen pertama yang diterima seorang Katolik sebagai gerbang masuk kehidupan beriman dinamakan:',
      options: ['Sakramen Baptis', 'Sakramen Krisma', 'Sakramen Ekaristi', 'Sakramen Tobat'],
      correctOptionIndex: 0,
      explanation: 'Sakramen Baptis adalah sakramen inisiasi pertama.',
    ),
    QuestionItem(
      id: 'pkat_004',
      questionText: 'Sakramen pendewasaan iman di mana Umat Katolik menerima kepenuhan Roh Kudus dinamakan:',
      options: ['Sakramen Krisma (Penguatan)', 'Sakramen Ekaristi', 'Sakramen Imamat', 'Sakramen Minyak Suci'],
      correctOptionIndex: 0,
      explanation: 'Sakramen Krisma memberikan karunia Roh Kudus untuk kedewasaan iman.',
    ),
    QuestionItem(
      id: 'pkat_005',
      questionText: 'Sakramen yang menjadi puncak dan sumber seluruh hidup Kristiani Katolik adalah:',
      options: ['Sakramen Ekaristi', 'Sakramen Baptis', 'Sakramen Tobat', 'Sakramen Perkawinan'],
      correctOptionIndex: 0,
      explanation: 'Ekaristi adalah puncak dan sumber kehidupan Kristiani.',
    ),
    QuestionItem(
      id: 'pkat_006',
      questionText: 'Perubahan hakiki substansi roti dan anggur menjadi Tubuh dan Darah Kristus dalam Perayaan Ekaristi disebut istilah:',
      options: ['Transubstansiasi', 'Konsubstansiasi', 'Transformasi', 'Transfigurasi'],
      correctOptionIndex: 0,
      explanation: 'Transubstansiasi adalah perubahan substansi roti & anggur menjadi Tubuh & Darah Kristus.',
    ),
    QuestionItem(
      id: 'pkat_007',
      questionText: 'Sakramen pemulihan hubungan dengan Allah dan Gereja setelah melakukan dosa dinamakan:',
      options: ['Sakramen Tobat (Rekonsiliasi)', 'Sakramen Minyak Suci', 'Sakramen Krisma', 'Sakramen Imamat'],
      correctOptionIndex: 0,
      explanation: 'Sakramen Tobat memberikan pengampunan dosa dari Allah melalui imam.',
    ),
    QuestionItem(
      id: 'pkat_008',
      questionText: 'Sakramen pengurapan orang sakit bertujuan untuk memberikan kekuatan rohani dan jasmani bagi yang menderita sakit berat dinamakan:',
      options: ['Sakramen Pengurapan Orang Sakit', 'Sakramen Tobat', 'Sakramen Ekaristi', 'Sakramen Krisma'],
      correctOptionIndex: 0,
      explanation: 'Pengurapan Orang Sakit memberi Rahmat penyembuhan dan kekuatan.',
    ),
    QuestionItem(
      id: 'pkat_009',
      questionText: 'Sakramen di mana seorang pria ditahbiskan menjadi Diakon, Imam (Romo), atau Uskup dinamakan:',
      options: ['Sakramen Imamat (Tahbisan)', 'Sakramen Perkawinan', 'Sakramen Krisma', 'Sakramen Tobat'],
      correctOptionIndex: 0,
      explanation: 'Sakramen Imamat memberikan wewenang pelayanan hirarkis gereja.',
    ),
    QuestionItem(
      id: 'pkat_010',
      questionText: 'Sakramen ikatan suci tak terputuskan antara seorang pria dan seorang wanita secara Katolik dinamakan:',
      options: ['Sakramen Perkawinan', 'Sakramen Tobat', 'Sakramen Imamat', 'Sakramen Krisma'],
      correctOptionIndex: 0,
      explanation: 'Sakramen Perkawinan bersifat monogam dan tak terceraikan.',
    ),
    QuestionItem(
      id: 'pkat_011',
      questionText: 'Pemimpin tertinggi Gereja Katolik Roma seluruh dunia yang berkedudukan di Vatikan adalah:',
      options: ['Paus (Papa / Bishop of Rome)', 'Kardinal', 'Uskup Agung', 'Pastur Kepala'],
      correctOptionIndex: 0,
      explanation: 'Paus adalah penerus Tahta Santo Petrus.',
    ),
    QuestionItem(
      id: 'pkat_012',
      questionText: 'Paus pertama Gereja Katolik menurut tradisi Apostolik adalah:',
      options: ['Santo Petrus', 'Santo Paulus', 'Santo Yohanes', 'Santo Yakobus'],
      correctOptionIndex: 0,
      explanation: 'Santo Petrus dianggap sebagai Paus pertama.',
    ),
    QuestionItem(
      id: 'pkat_013',
      questionText: 'Wewenang mengajar resmi Gereja Katolik yang dipegang oleh Paus dan Para Uskup dinamakan:',
      options: ['Magisterium', 'Liturgi', 'Kanon', 'Ensiklik'],
      correctOptionIndex: 0,
      explanation: 'Magisterium adalah kuasa mengajar autentik Gereja Katolik.',
    ),
    QuestionItem(
      id: 'pkat_014',
      questionText: 'Surat gembala resmi yang ditulis oleh Paus untuk seluruh umat Katolik di dunia mengenai isu iman atau sosial dinamakan:',
      options: ['Ensiklik (Encyclical)', 'Bull', 'Motu Proprio', 'Konstitusi'],
      correctOptionIndex: 0,
      explanation: 'Ensiklik adalah edaran ajaran Paus.',
    ),
    QuestionItem(
      id: 'pkat_015',
      questionText: 'Ensiklik pertama tentang Ajaran Sosial Gereja (ASG) yang ditulis Paus Leo XIII pada tahun 1891 tentang buruh adalah:',
      options: ['Rerum Novarum', 'Laudato Si\'', 'Pacem in Terris', 'Fratelli Tutti'],
      correctOptionIndex: 0,
      explanation: 'Rerum Novarum adalah tonggak awal Ajaran Sosial Gereja.',
    ),
    QuestionItem(
      id: 'pkat_016',
      questionText: 'Ensiklik Paus Fransiskus tentang perawatan lingkungan dan alam ciptaan ("Rumah Kita Bersama") dinamakan:',
      options: ['Laudato Si\'', 'Fratelli Tutti', 'Evangelii Gaudium', 'Amoris Laetitia'],
      correctOptionIndex: 0,
      explanation: 'Laudato Si\' membahas keadilan ekologis dan lingkungan.',
    ),
    QuestionItem(
      id: 'pkat_017',
      questionText: 'Tiga Pilar Kebenaran iman Katolik terdiri dari Kitab Suci, Magisterium, dan:',
      options: ['Tradisi Suci', 'Kanon Hukum', 'Statuta Gereja', 'Kredo Rasuli'],
      correctOptionIndex: 0,
      explanation: 'Kitab Suci, Tradisi Suci, dan Magisterium saling mendukung.',
    ),
    QuestionItem(
      id: 'pkat_018',
      questionText: 'Konsili ekumenis abad ke-20 yang memperbarui liturgi dan keterbukaan Gereja Katolik pada dunia modern adalah:',
      options: ['Konsili Vatikan II (1962-1965)', 'Konsili Trente', 'Konsili Nicea', 'Konsili Efesus'],
      correctOptionIndex: 0,
      explanation: 'Konsili Vatikan II membawa pembaruan besar (Aggiornamento).',
    ),
    QuestionItem(
      id: 'pkat_019',
      questionText: 'Devosi populer Katolik memohon doa Bunda Maria dengan memakai manik-manik dinamakan:',
      options: ['Doa Rosario', 'Doa Novena', 'Angelus', 'Coronka'],
      correctOptionIndex: 0,
      explanation: 'Doa Rosario adalah devosi marial dengan Peristiwa Sukacita, Sedih, Mulia, Cahaya.',
    ),
    QuestionItem(
      id: 'pkat_020',
      questionText: 'Bulan Mei dan Bulan Oktober dalam tradisi Katolik diperingati secara khusus sebagai:',
      options: ['Bulan Maria dan Bulan Rosario', 'Bulan Kitab Suci', 'Bulan Misi', 'Bulan Arwah'],
      correctOptionIndex: 0,
      explanation: 'Mei adalah Bulan Maria, Oktober adalah Bulan Rosario.',
    ),
    QuestionItem(
      id: 'pkat_021',
      questionText: 'Bulan September dalam Gereja Katolik Indonesia diperingati sebagai:',
      options: ['Bulan Kitab Suci Nasional (BKSN)', 'Bulan Rosario', 'Bulan Maria', 'Bulan Katekese'],
      correctOptionIndex: 0,
      explanation: 'BKSN diperingati setiap bulan September.',
    ),
    QuestionItem(
      id: 'pkat_022',
      questionText: 'Doa kenangan akan penjelmaan Putra Allah yang didoakan 3 kali sehari (jam 06.00, 12.00, 18.00) dinamakan:',
      options: ['Doa Malaikat Tuhan (Angelus)', 'Doa Rosario', 'Doa Kerahiman', 'Doa Penyerahan'],
      correctOptionIndex: 0,
      explanation: 'Doa Angelus didoakan pada pagi, siang, dan sore hari.',
    ),
    QuestionItem(
      id: 'pkat_023',
      questionText: 'Dogma Katolik yang menyatakan bahwa Bunda Maria dikandung tanpa noda dosa asal dinamakan:',
      options: ['Immaculata Conceptio (Maria Dikandung Tanpa Noda)', 'Assumpta', 'Virginitas', 'Theotokos'],
      correctOptionIndex: 0,
      explanation: 'Immaculata Conceptio adalah dogma keperawanan dan kemurnian Maria.',
    ),
    QuestionItem(
      id: 'pkat_024',
      questionText: 'Dogma Katolik yang menyatakan bahwa Bunda Maria diangkat ke surga dengan jiwa dan raganya dinamakan:',
      options: ['Assumpta (Maria Diangkat ke Surga)', 'Immaculata', 'Annuntiatio', 'Coronatio'],
      correctOptionIndex: 0,
      explanation: 'Assumpta diperingati setiap tanggal 15 Agustus.',
    ),
    QuestionItem(
      id: 'pkat_025',
      questionText: 'Gelar bagi Maria sebagai "Bunda Allah" ditetapkan dalam Konsili Efesus (431 M) dengan istilah Yunani:',
      options: ['Theotokos', 'Pantokrator', 'Christotokos', 'Kyrios'],
      correctOptionIndex: 0,
      explanation: 'Theotokos artinya Pembawa / Ibu Allah.',
    ),
    QuestionItem(
      id: 'pkat_026',
      questionText: 'Hari pertama Masa Prapaskah Katolik di mana dahi umat diolesi abu simbol pertobatan dinamakan:',
      options: ['Rabu Abu', 'Kamis Putih', 'Jumat Agung', 'Sabtu Santo'],
      correctOptionIndex: 0,
      explanation: 'Rabu Abu mengawali 40 hari masa Prapaskah.',
    ),
    QuestionItem(
      id: 'pkat_027',
      questionText: 'Tiga hari suci puncak Pekan Suci Paskah Katolik (Kamis Putih, Jumat Agung, Sabtu Santo/Vigili Paskah) disebut:',
      options: ['Triduum Sacrum (Tri Hari Suci)', 'Pekan Suci', 'Oktaf Paskah', 'Adven'],
      correctOptionIndex: 0,
      explanation: 'Triduum Sacrum adalah 3 hari suci Paskah.',
    ),
    QuestionItem(
      id: 'pkat_028',
      questionText: 'Ibadah peringatan sengsara Yesus melintasi 14 perhentian dinamakan:',
      options: ['Jalan Salib (Via Crucis)', 'Novena', 'Adorasi', 'Vesper'],
      correctOptionIndex: 0,
      explanation: 'Jalan Salib mengenang kisah sengsara Yesus hingga Golgota.',
    ),
    QuestionItem(
      id: 'pkat_029',
      questionText: 'Penyembahan dan penghormatan Umat Katolik di hadapan Sakramen Maha Kudus yang ditahtakan di Monstrans dinamakan:',
      options: ['Adorasi Sakramen Maha Kudus', 'Benediksy', 'Rosario', 'Litani'],
      correctOptionIndex: 0,
      explanation: 'Adorasi adalah doa menyembah Sakramen Maha Kudus.',
    ),
    QuestionItem(
      id: 'pkat_030',
      questionText: 'Pernyataan resmi Vatican yang menyatakan seseorang yang telah meninggal terbukti kudus dan berhak digelari "Santo/Santa" dinamakan:',
      options: ['Kanonisasi', 'Beatifikasi', 'Venerasi', 'Kolegialitas'],
      correctOptionIndex: 0,
      explanation: 'Kanonisasi adalah tahap akhir penetapan Santo/Santa.',
    ),
    QuestionItem(
      id: 'pkat_031',
      questionText: 'Tahap sebelum Kanonisasi di mana seorang calon santo diberi gelar "Beato / Beata" dinamakan:',
      options: ['Beatifikasi', 'Kanonisasi', 'Venerabilis', 'Servus Dei'],
      correctOptionIndex: 0,
      explanation: 'Beatifikasi memberikan gelar Beato/Beata (Yang Bahagia).',
    ),
    QuestionItem(
      id: 'pkat_032',
      questionText: 'Santo pelindung para pelajar dan kaum muda Katolik yang terkenal suci murni adalah:',
      options: ['Santo Aloysius Gonzaga', 'Santo Tarsisius', 'Santo Dominikus', 'Santo Fransiskus'],
      correctOptionIndex: 0,
      explanation: 'St. Aloysius Gonzaga adalah pelindung kaum muda & pelajar.',
    ),
    QuestionItem(
      id: 'pkat_033',
      questionText: 'Santo pelindung anak-anak miskin dan perintis Ordo Salesian (SDB) adalah:',
      options: ['Santo Yohanes Bosco (Don Bosco)', 'Santo Fransiskus Xaverius', 'Santo Antonius', 'Santo Benyamin'],
      correctOptionIndex: 0,
      explanation: 'Don Bosco adalah pelindung anak-anak muda dan kaum muda.',
    ),
    QuestionItem(
      id: 'pkat_034',
      questionText: 'Misionaris Katolik besar yang mewartakan Injil hingga ke Maluku Indonesia pada abad ke-16 adalah:',
      options: ['Santo Fransiskus Xaverius', 'Santo Ignatius Loyola', 'Santo Thomas Aquinas', 'Santo Bonaventura'],
      correctOptionIndex: 0,
      explanation: 'St. Fransiskus Xaverius menyebarkan Injil di Maluku.',
    ),
    QuestionItem(
      id: 'pkat_035',
      questionText: 'Pendiri Ordo Serikat Yesus (SJ / Yesuit) yang terkenal dengan Latihan Rohani adalah:',
      options: ['Santo Ignatius Loyola', 'Santo Fransiskus Asisi', 'Santo Benediktus', 'Santo Dominikus'],
      correctOptionIndex: 0,
      explanation: 'St. Ignatius Loyola mendirikan Serikat Yesus (SJ).',
    ),
    QuestionItem(
      id: 'pkat_036',
      questionText: 'Pendiri Ordo Saudara Hina Dina (OFM / Fransiskan) yang mencintai alam ciptaan adalah:',
      options: ['Santo Fransiskus Asisi', 'Santo Antonius Padua', 'Santo Klara', 'Santo Bernardus'],
      correctOptionIndex: 0,
      explanation: 'St. Fransiskus Asisi pendiri Ordo Fransiskan.',
    ),
    QuestionItem(
      id: 'pkat_037',
      questionText: 'Filsuf dan Pujangga Gereja Katolik terbesar penyusun karya mahakarya "Summa Theologiae" adalah:',
      options: ['Santo Thomas Aquinas', 'Santo Agustinus', 'Santo Anselmus', 'Santo Albertus Agung'],
      correctOptionIndex: 0,
      explanation: 'St. Thomas Aquinas menyusun Summa Theologiae.',
    ),
    QuestionItem(
      id: 'pkat_038',
      questionText: 'Uskup dan Pujangga Gereja yang menulis buku autobiografi "Confessiones" (Pengakuan) adalah:',
      options: ['Santo Agustinus dari Hippo', 'Santo Hieronimus', 'Santo Ambrosius', 'Santo Athanasius'],
      correctOptionIndex: 0,
      explanation: 'St. Agustinus menulis Confessiones dan De Civitate Dei.',
    ),
    QuestionItem(
      id: 'pkat_039',
      questionText: 'Pujangga Gereja yang menerjemahkan Alkitab ke dalam bahasa Latin (Vulgata) adalah:',
      options: ['Santo Hieronimus (Jerome)', 'Santo Yohanes Krisostomus', 'Santo Gregorius', 'Santo Beda'],
      correctOptionIndex: 0,
      explanation: 'St. Hieronimus menerjemahkan Alkitab Vulgata.',
    ),
    QuestionItem(
      id: 'pkat_040',
      questionText: 'Santa pendiri Misionaris Cinta Kasih yang melayani orang miskin dan sekarat di Kalkuta India adalah:',
      options: ['Santa Teresa dari Kalkuta (Ibu Teresa)', 'Santa Teresia Cilik', 'Santa Teresa dari Avila', 'Santa Faustina'],
      correctOptionIndex: 0,
      explanation: 'Ibu Teresa mendirikan Misionaris Cinta Kasih.',
    ),
    QuestionItem(
      id: 'pkat_041',
      questionText: 'Santa pembawa devosi Kerahiman Ilahi dan lukisan Yesus Kerahiman Ilahi adalah:',
      options: ['Santa Faustina Kowalska', 'Santa Bernadette', 'Santa Lucia', 'Santa Rita'],
      correctOptionIndex: 0,
      explanation: 'St. Faustina Kowalska adalah rasul Kerahiman Ilahi.',
    ),
    QuestionItem(
      id: 'pkat_042',
      questionText: 'Gadis desa yang mendapat penglihatan Bunda Maria di Lourdes Prancis pada 1858 bernama:',
      options: ['Santa Bernadette Soubirous', 'Santa Lucia', 'Santa Jacinta', 'Santa Agnes'],
      correctOptionIndex: 0,
      explanation: 'St. Bernadette mengalami penampakan di Lourdes.',
    ),
    QuestionItem(
      id: 'pkat_043',
      questionText: 'Tempat penampakan Bunda Maria kepada 3 anak gembala di Portugal pada tahun 1917 dinamakan:',
      options: ['Fatima', 'Lourdes', 'Guadalupe', 'Medjugorje'],
      correctOptionIndex: 0,
      explanation: 'Bunda Maria menampakkan diri di Fatima Portugal.',
    ),
    QuestionItem(
      id: 'pkat_044',
      questionText: 'Tempat penampakan Bunda Maria kepada Juan Diego di Meksiko yang meninggalkan citra ajaib di kain Tilma adalah:',
      options: ['Guadalupe', 'Fatima', 'Lourdes', 'La Salette'],
      correctOptionIndex: 0,
      explanation: 'Bunda Maria Guadalupe di Meksiko.',
    ),
    QuestionItem(
      id: 'pkat_045',
      questionText: 'Bapak Bangsa Katolik Indonesia dan Pahlawan Nasional yang menjadi Uskup Pribumi Pertama di Indonesia adalah:',
      options: ['Mgr. Albertus Soegijapranata, SJ', 'Mgr. Geise', 'Mgr. Willekens', 'Mgr. Suharyo'],
      correctOptionIndex: 0,
      explanation: 'Mgr. Soegijapranata adalah Uskup Pribumi Pertama Indonesia dengan semboyan "100% Katolik 100% Indonesia".',
    ),
    QuestionItem(
      id: 'pkat_046',
      questionText: 'Semboyan kebangsaan terkenal dari Mgr. Soegijapranata, SJ adalah:',
      options: ['100% Katolik, 100% Indonesia', 'Pro Deo et Patria', 'Ut Omnes Unum Sint', 'Ad Maiorem Dei Gloriam'],
      correctOptionIndex: 0,
      explanation: 'Semboyan legendaris "100% Katolik, 100% Indonesia".',
    ),
    QuestionItem(
      id: 'pkat_047',
      questionText: 'Semboyan Ordo Serikat Yesus (SJ) "AMDGL" merupakan singkatan dari:',
      options: ['Ad Maiorem Dei Gloriam (Demi Lebih Besarnya Kemuliaan Allah)', 'Ora et Labora', 'Caritas in Veritate', 'Pax et Bonum'],
      correctOptionIndex: 0,
      explanation: 'AMDGL = Ad Maiorem Dei Gloriam.',
    ),
    QuestionItem(
      id: 'pkat_048',
      questionText: 'Semboyan Ordo Benediktin "Ora et Labora" memiliki arti:',
      options: ['Berdoa dan Bekerja', 'Berdoa dan Belajar', 'Cinta dan Kebenaran', 'Damai dan Kebaikan'],
      correctOptionIndex: 0,
      explanation: 'Ora et Labora = Berdoa dan Bekerja.',
    ),
    QuestionItem(
      id: 'pkat_049',
      questionText: 'Semboyan Ordo Fransiskan "Pax et Bonum" memiliki arti:',
      options: ['Damai dan Kebaikan', 'Berdoa dan Bekerja', 'Kemuliaan bagi Allah', 'Kasih dan Keadilan'],
      correctOptionIndex: 0,
      explanation: 'Pax et Bonum = Damai dan Kebaikan.',
    ),
    QuestionItem(
      id: 'pkat_050',
      questionText: 'Warna liturgi yang digunakan pada Masa Adven dan Masa Prapaskah sebagai lambang pertobatan adalah:',
      options: ['Ungu', 'Putih', 'Hijau', 'Merah'],
      correctOptionIndex: 0,
      explanation: 'Warna Ungu melambangkan pertobatan dan penantian.',
    ),
    QuestionItem(
      id: 'pkat_051',
      questionText: 'Warna liturgi yang digunakan pada Hari Raya Natal, Paskah, dan pesta Bunda Maria sebagai lambang kesucian & sukacita adalah:',
      options: ['Putih / Emas', 'Ungu', 'Hijau', 'Merah'],
      correctOptionIndex: 0,
      explanation: 'Putih/Emas melambangkan kemuliaan dan kegembiraan.',
    ),
    QuestionItem(
      id: 'pkat_052',
      questionText: 'Warna liturgi yang digunakan pada Minggu Palma, Jumat Agung, Pentakosta, dan Pesta Para Martir adalah:',
      options: ['Merah', 'Hijau', 'Ungu', 'Merah Muda'],
      correctOptionIndex: 0,
      explanation: 'Merah melambangkan Roh Kudus dan darah pengorbanan martir.',
    ),
    QuestionItem(
      id: 'pkat_053',
      questionText: 'Warna liturgi yang digunakan pada Masa Biasa (Masa Harapan & Pertumbuhan Gereja) adalah:',
      options: ['Hijau', 'Putih', 'Ungu', 'Merah'],
      correctOptionIndex: 0,
      explanation: 'Hijau dipakai dalam Masa Biasa liturgi.',
    ),
    QuestionItem(
      id: 'pkat_054',
      questionText: 'Warna liturgi khusus yang boleh digunakan pada Minggu Gaudete (Adven III) dan Minggu Laetare (Prapaskah IV) adalah:',
      options: ['Merah Muda (Pink)', 'Hitam', 'Biru', 'Kuning'],
      correctOptionIndex: 0,
      explanation: 'Merah Muda melambangkan sukacita di tengah pertobatan.',
    ),
    QuestionItem(
      id: 'pkat_055',
      questionText: 'Cangkir piala suci yang digunakan untuk menampung Anggur Ekaristi saat Misa dinamakan:',
      options: ['Kalis (Chalice)', 'Paten', 'Sibori', 'Piksis'],
      correctOptionIndex: 0,
      explanation: 'Kalis adalah cangkir piala Ekaristi.',
    ),
    QuestionItem(
      id: 'pkat_056',
      questionText: 'Piringan kecil berlapis emas tempat meletakkan Roti Hostia Besar saat Misa dinamakan:',
      options: ['Paten', 'Kalis', 'Sibori', 'Ampul'],
      correctOptionIndex: 0,
      explanation: 'Paten meletakkan Hostia Besar.',
    ),
    QuestionItem(
      id: 'pkat_057',
      questionText: 'Wadah bertutup berbentuk piala yang digunakan untuk menyimpan Hostia Kudus untuk komuni jemaat dinamakan:',
      options: ['Sibori (Ciborium)', 'Paten', 'Kalis', 'Monstrans'],
      correctOptionIndex: 0,
      explanation: 'Sibori tempat menampung Hostia komuni.',
    ),
    QuestionItem(
      id: 'pkat_058',
      questionText: 'Wadah indah berbentuk sinar matahari yang digunakan untuk menahtakan Hostia Kudus dalam Adorasi dinamakan:',
      options: ['Monstrans (Monstrance)', 'Sibori', 'Paten', 'Relikuari'],
      correctOptionIndex: 0,
      explanation: 'Monstrans digunakan untuk tahta Sakramen Maha Kudus.',
    ),
    QuestionItem(
      id: 'pkat_059',
      questionText: 'Dua botol kecil penampung Air dan Anggur sebelum dicampur saat Misa dinamakan:',
      options: ['Ampul', 'Kalis', 'Paten', 'Turibulum'],
      correctOptionIndex: 0,
      explanation: 'Ampul menampung air dan anggur.',
    ),
    QuestionItem(
      id: 'pkat_060',
      questionText: 'Alat tempat pembakaran dupa yang diayunkan saat Misa Kudus dinamakan:',
      options: ['Turibulum (Wiruk)', 'Ampul', 'Kalis', 'Navikula'],
      correctOptionIndex: 0,
      explanation: 'Turibulum / Wiruk adalah wadah dupa.',
    ),
    QuestionItem(
      id: 'pkat_061',
      questionText: 'Pakaian jubah putih panjang yang dikenakan oleh Romo dan Putra-Putri Altar saat liturgi dinamakan:',
      options: ['Alba', 'Kasula', 'Stola', 'Singel'],
      correctOptionIndex: 0,
      explanation: 'Alba adalah jubah putih polos.',
    ),
    QuestionItem(
      id: 'pkat_062',
      questionText: 'Kain selempang yang dikalungkan di leher imam sebagai lambang kekuasaan dan tugas suci dinamakan:',
      options: ['Stola', 'Kasula', 'Alba', 'Kapa'],
      correctOptionIndex: 0,
      explanation: 'Stola adalah tanda martabat imamat.',
    ),
    QuestionItem(
      id: 'pkat_063',
      questionText: 'Pakaian terluar imam berwarna sesuai warna liturgi hari itu dinamakan:',
      options: ['Kasula (Chasuble)', 'Alba', 'Stola', 'Kolekte'],
      correctOptionIndex: 0,
      explanation: 'Kasula adalah jubah terluar selebran Misa.',
    ),
    QuestionItem(
      id: 'pkat_064',
      questionText: 'Meja suci tempat dilaksanakannya Kurban Ekaristi dinamakan:',
      options: ['Altare (Altar)', 'Mimbar (Ambo)', 'Tabernakel', 'Bejana Baptis'],
      correctOptionIndex: 0,
      explanation: 'Altar adalah meja kurban Ekaristi.',
    ),
    QuestionItem(
      id: 'pkat_065',
      questionText: 'Lemari suci tempat menyimpan Hostia Kudus yang telah dikonsekrasi dinamakan:',
      options: ['Tabernakel', 'Altar', 'Ambo', 'Sakristi'],
      correctOptionIndex: 0,
      explanation: 'Tabernakel menyimpan Sakramen Maha Kudus.',
    ),
    QuestionItem(
      id: 'pkat_066',
      questionText: 'Lampu minyak atau lilin merah yang selalu menyala di dekat Tabernakel menandakan keberadaan Kristus adalah:',
      options: ['Lampu Abadi (Lampu Tabernakel)', 'Lilin Paskah', 'Lilin Adven', 'Lilin Altar'],
      correctOptionIndex: 0,
      explanation: 'Lampu Abadi menandakan ada Hostia Kudus di Tabernakel.',
    ),
    QuestionItem(
      id: 'pkat_067',
      questionText: 'Lilin besar yang diberkati pada Malam Vigili Paskah sebagai lambang Kristus Cahaya Dunia adalah:',
      options: ['Lilin Paskah (Paschal Candle)', 'Lilin Adven', 'Lilin Baptis', 'Lilin Altar'],
      correctOptionIndex: 0,
      explanation: 'Lilin Paskah melambangkan Kristus yang Bangkit.',
    ),
    QuestionItem(
      id: 'pkat_068',
      questionText: 'Empat lilin (3 ungu, 1 merah muda) yang dinyalakan bertahap selama minggu-minggu penantian Natal ditaruh di:',
      options: ['Lingkaran Adven (Korona Adven)', 'Altar Utama', 'Tabernakel', 'Bejana Baptis'],
      correctOptionIndex: 0,
      explanation: 'Lingkaran Adven diisi 4 lilin Adven.',
    ),
    QuestionItem(
      id: 'pkat_069',
      questionText: 'Organisasi internasional Gereja Katolik yang bergerak di bidang kemanusiaan dan relief bencana adalah:',
      options: ['Caritas', 'CRS (Catholic Relief Services)', 'Kaum Muda Katolik', 'Legio Mariae'],
      correctOptionIndex: 0,
      explanation: 'Caritas adalah lembaga karitatif Katolik global.',
    ),
    QuestionItem(
      id: 'pkat_070',
      questionText: 'Organisasi kerosanian awam Katolik yang mendedikasikan doa dan pelayanan Marial dinamakan:',
      options: ['Legio Mariae', 'Komunitas Sant\'Egidio', 'Focolare', 'Opus Dei'],
      correctOptionIndex: 0,
      explanation: 'Legio Mariae fokus pada devosi marial dan kunjungan jemaat.',
    ),
    QuestionItem(
      id: 'pkat_071',
      questionText: 'Organisasi pemuda Katolik Indonesia yang didirikan pada tahun 1923 bernama:',
      options: ['Pemuda Katolik (PK)', 'PMKRI', 'WKRI', 'STT'],
      correctOptionIndex: 0,
      explanation: 'Pemuda Katolik adalah Ormas pemuda Katolik Indonesia.',
    ),
    QuestionItem(
      id: 'pkat_072',
      questionText: 'Perhimpunan Mahasiswa Katolik Republik Indonesia yang berdiri tahun 1947 adalah:',
      options: ['PMKRI', 'Pemuda Katolik', 'KMK', 'Pengurus Gereja'],
      correctOptionIndex: 0,
      explanation: 'PMKRI singkatan Perhimpunan Mahasiswa Katolik RI.',
    ),
    QuestionItem(
      id: 'pkat_073',
      questionText: 'Organisasi wanita Katolik Indonesia yang bergerak di bidang sosial dan kemasyarakatan adalah:',
      options: ['WKRI (Wanita Katolik Republik Indonesia)', 'Legio Mariae', 'Ibu-Ibu Paroki', 'KWI'],
      correctOptionIndex: 0,
      explanation: 'WKRI singkatan Wanita Katolik Republik Indonesia.',
    ),
    QuestionItem(
      id: 'pkat_074',
      questionText: 'Wadah musyawarah wali gereja (para uskup) se-Indonesia dinamakan:',
      options: ['KWI (Konferensi Waligereja Indonesia)', 'PGI', 'Kevikepan', 'Keuskupan'],
      correctOptionIndex: 0,
      explanation: 'KWI adalah Konferensi Waligereja Indonesia.',
    ),
    QuestionItem(
      id: 'pkat_075',
      questionText: 'Wilayah gerejawi Katolik yang dipimpin oleh seorang Uskup dinamakan:',
      options: ['Keuskupan (Diosez)', 'Paroki', 'Stasi', 'Kevikepan'],
      correctOptionIndex: 0,
      explanation: 'Keuskupan dipimpin Uskup.',
    ),
    QuestionItem(
      id: 'pkat_076',
      questionText: 'Komunitas Umat Katolik di tingkat lokal yang dipimpin oleh seorang Pastur Paroki dinamakan:',
      options: ['Paroki', 'Keuskupan', 'Stasi', 'Komunitas Basis'],
      correctOptionIndex: 0,
      explanation: 'Paroki dipimpin Pastor Paroki.',
    ),
    QuestionItem(
      id: 'pkat_077',
      questionText: 'Bagian dari wilayah paroki yang lebih kecil di pedesaan/daerah dinamakan:',
      options: ['Stasi', 'Lingkungan', 'Wilayah', 'Kevikepan'],
      correctOptionIndex: 0,
      explanation: 'Stasi adalah cabang gereja lokal di bawah Paroki.',
    ),
    QuestionItem(
      id: 'pkat_078',
      questionText: 'Kelompok Umat Katolik di tingkat rukun tetangga/pemukiman dinamakan:',
      options: ['Lingkungan / KBB (Kelompok Basis Gerejani)', 'Stasi', 'Paroki', 'Wilayah'],
      correctOptionIndex: 0,
      explanation: 'Lingkungan/KBB adalah komunitas dasar terkecil.',
    ),
    QuestionItem(
      id: 'pkat_079',
      questionText: 'Gereja katedral merupakan gereja pusat keuskupan tempat kedudukan tahta (Cathedra) dari seorang:',
      options: ['Uskup', 'Paus', 'Pastur Kepala', 'Diakon'],
      correctOptionIndex: 0,
      explanation: 'Katedral berisi tahta resmi (Cathedra) Uskup.',
    ),
    QuestionItem(
      id: 'pkat_080',
      questionText: 'Pertemuan dan pemilihan Paus baru oleh para Kardinal di Kapel Sistina dinamakan:',
      options: ['Konklaf (Conclave)', 'Konsistori', 'Konsili', 'Sinode'],
      correctOptionIndex: 0,
      explanation: 'Konklaf adalah sidang rahasia pemilihan Paus baru.',
    ),
    QuestionItem(
      id: 'pkat_081',
      questionText: 'Tanda asap yang keluar dari cerobong Kapel Sistina saat Paus baru TERPILIH adalah asap berwarna:',
      options: ['Putih', 'Hitam', 'Abu-Abu', 'Merah'],
      correctOptionIndex: 0,
      explanation: 'Asap putih (Habemus Papam) menandakan Paus baru telah terpilih.',
    ),
    QuestionItem(
      id: 'pkat_082',
      questionText: 'Tanda asap yang keluar saat pemungutan suara pemilihan Paus BELUM berhasil adalah asap berwarna:',
      options: ['Hitam', 'Putih', 'Biru', 'Kuning'],
      correctOptionIndex: 0,
      explanation: 'Asap hitam menandakan belum ada hasil pemilihan Paus.',
    ),
    QuestionItem(
      id: 'pkat_083',
      questionText: 'Pengumuman Latin terkenal "Habemus Papam!" saat Paus baru terpilih berarti:',
      options: ['Kita Memiliki Paus!', 'Paus Telah Datang!', 'Terima Kasih Tuhan!', 'Gereja Bersatu!'],
      correctOptionIndex: 0,
      explanation: 'Habemus Papam = We have a Pope!',
    ),
    QuestionItem(
      id: 'pkat_084',
      questionText: 'Persidangan dan musyawarah para uskup bersama Paus untuk membahas tema pastoral tertentu dinamakan:',
      options: ['Sinode (Synod)', 'Konklaf', 'Konsistori', 'Ensiklik'],
      correctOptionIndex: 0,
      explanation: 'Sinode Uskup membahas isu-isu pastoral.',
    ),
    QuestionItem(
      id: 'pkat_085',
      questionText: 'Dewan penasihat Paus yang terdiri dari para pimpinan dikasteri dan uskup agung senior dinamakan:',
      options: ['Dewan Kardinal (College of Cardinals)', 'Magisterium', 'Kuria Roma', 'KWI'],
      correctOptionIndex: 0,
      explanation: 'Kardinal bertugas menasihati Paus dan memilih Paus baru.',
    ),
    QuestionItem(
      id: 'pkat_086',
      questionText: 'Perangkat birokrasi pemerintahan pusat Gereja Katolik di Vatikan dinamakan:',
      options: ['Kuria Roma (Roman Curia)', 'Kanon', 'Kongregasi Imamat', 'Takhta Suci'],
      correctOptionIndex: 0,
      explanation: 'Kuria Roma membantu Paus mengelola Gereja Universal.',
    ),
    QuestionItem(
      id: 'pkat_087',
      questionText: 'Negara berdaulat terkecil di dunia yang menjadi pusat pimpinan Gereja Katolik Roma adalah:',
      options: ['Kota Vatikan (Vatican City State)', 'Monako', 'San Marino', 'Lichtenstein'],
      correctOptionIndex: 0,
      explanation: 'Kota Vatikan adalah negara independen terkecil.',
    ),
    QuestionItem(
      id: 'pkat_088',
      questionText: 'Perjanjian Lateran tahun 1929 antara Italia dan Takhta Suci mengesahkan kemerdekaan negara:',
      options: ['Kota Vatikan', 'Yerusalem', 'San Marino', 'Malta'],
      correctOptionIndex: 0,
      explanation: 'Perjanjian Lateran mendirikan Negara Kota Vatikan.',
    ),
    QuestionItem(
      id: 'pkat_089',
      questionText: 'Pengawal resmi Paus dan Kota Vatikan yang terkenal dengan seragam warna-warninya adalah:',
      options: ['Garda Swiss (Swiss Guard)', 'Garda Vatikan', 'Polisi Italia', 'Garda Katolik'],
      correctOptionIndex: 0,
      explanation: 'Swiss Guard bertugas mengawal Paus sejak 1506.',
    ),
    QuestionItem(
      id: 'pkat_090',
      questionText: 'Empat Sifat Gereja Katolik seperti dirumuskan dalam Syadat Nicea-Konstantinopel adalah:',
      options: ['Satu, Kudus, Katolik, Apostolik', 'Kudus, Kasih, Damai, Beriman', 'Ekaristi, Imamat, Paus, Alkitab', 'Setia, Taat, Murni, Kasih'],
      correctOptionIndex: 0,
      explanation: 'Sifat Gereja: Satu, Kudus, Katolik (Universal), Apostolik.',
    ),
    QuestionItem(
      id: 'pkat_091',
      questionText: 'Kata "Katolik" berasal dari bahasa Yunani Katholikos yang berarti:',
      options: ['Umum / Universal / Menyeluruh', 'Suci / Terpisah', 'Terpilih', 'Setia'],
      correctOptionIndex: 0,
      explanation: 'Katholikos berarti umum, terbuka untuk semua (universal).',
    ),
    QuestionItem(
      id: 'pkat_092',
      questionText: 'Sifat Gereja "Apostolik" berarti Gereja Katolik dibangun di atas dasar ajaran dan suksesi dari para:',
      options: ['Rasul (Apostel)', 'Nabi PL', 'Pangeran', 'Filsuf'],
      correctOptionIndex: 0,
      explanation: 'Apostolik berakar dari ajaran para Rasul.',
    ),
    QuestionItem(
      id: 'pkat_093',
      questionText: 'Doa Pengakuan Dosa dalam tradisi Katolik diawali dengan pengakuan "Saya mengaku kepada Allah Yang Maha Kuasa..." yang dinamakan:',
      options: ['Saya Mengaku (Confiteor)', 'Kyrie Eleison', 'Gloria', 'Credo'],
      correctOptionIndex: 0,
      explanation: 'Confiteor adalah doa Saya Mengaku.',
    ),
    QuestionItem(
      id: 'pkat_094',
      questionText: 'Seruan liturgi bahasa Yunani "Kyrie Eleison, Christe Eleison" memiliki arti:',
      options: ['Tuhan Kasihanilah Kami, Kristus Kasihanilah Kami', 'Kemuliaan Bagi Allah', 'Kuduslah Tuhan', 'Damai Bersamamu'],
      correctOptionIndex: 0,
      explanation: 'Kyrie Eleison = Lord, have mercy.',
    ),
    QuestionItem(
      id: 'pkat_095',
      questionText: 'Kidung Pujian Malaikat "Gloria in Excelsis Deo" dinyanyikan saat Misa berarti:',
      options: ['Kemuliaan kepada Allah di Tempat Yang Maha Tinggi', 'Kudus Kuduslah Tuhan', 'Terpujilah Kristus', 'Damai di Bumi'],
      correctOptionIndex: 0,
      explanation: 'Gloria in Excelsis Deo = Kemuliaan kepada Allah.',
    ),
    QuestionItem(
      id: 'pkat_096',
      questionText: 'Doa Pengakuan Iman Katolik yang diikrarkan saat Misa Minggu dinamakan:',
      options: ['Credo (Aku Percaya)', 'Sanctus', 'Agnus Dei', 'Pater Noster'],
      correctOptionIndex: 0,
      explanation: 'Credo adalah syadat pengakuan iman.',
    ),
    QuestionItem(
      id: 'pkat_097',
      questionText: 'Kidung "Agnus Dei" yang dinyanyikan sebelum pemecahan Roti Komuni berarti:',
      options: ['Anak Domba Allah', 'Tubuh Kristus', 'Darah Kristus', 'Roti Hidup'],
      correctOptionIndex: 0,
      explanation: 'Agnus Dei = Lamb of God (Anak Domba Allah).',
    ),
    QuestionItem(
      id: 'pkat_098',
      questionText: 'Doa "Pater Noster" dalam bahasa Latin adalah doa:',
      options: ['Doa Bapa Kami', 'Doa Salam Maria', 'Doa Kemuliaan', 'Doa Malaikat'],
      correctOptionIndex: 0,
      explanation: 'Pater Noster = Our Father / Doa Bapa Kami.',
    ),
    QuestionItem(
      id: 'pkat_099',
      questionText: 'Doa "Ave Maria" dalam bahasa Latin adalah doa:',
      options: ['Doa Salam Maria', 'Doa Bapa Kami', 'Doa Tobat', 'Doa Pagi'],
      correctOptionIndex: 0,
      explanation: 'Ave Maria = Salam Maria.',
    ),
    QuestionItem(
      id: 'pkat_100',
      questionText: 'Doa "Gloria Patri" dalam bahasa Latin adalah doa:',
      options: ['Doa Kemuliaan (Kepada Bapa, Putra, dan Roh Kudus)', 'Doa Salam Maria', 'Doa Malaikat Tuhan', 'Doa Makan'],
      correctOptionIndex: 0,
      explanation: 'Gloria Patri = Kemuliaan kepada Bapa...',
    ),
  ];
}
