import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPendidikanAgamaIslamQuestions() {
  return const [
    QuestionItem(
      id: 'pai_001',
      questionText: 'Kitab suci Al-Qur\'an diturunkan secara berangsur-angsur kepada Nabi Muhammad SAW selama kurang lebih:',
      options: ['22 tahun 2 bulan 22 hari', '20 tahun', '25 tahun', '15 tahun'],
      correctOptionIndex: 0,
      explanation: 'Al-Qur\'an diturunkan selama 22 tahun 2 bulan 22 hari.',
    ),
    QuestionItem(
      id: 'pai_002',
      questionText: 'Surah pertama yang diwahyukan kepada Nabi Muhammad SAW di Gua Hira adalah:',
      options: ['Surah Al-Fatihah', 'Surah Al-Alaq ayat 1-5', 'Surah Al-Baqarah', 'Surah Al-Ikhlas'],
      correctOptionIndex: 1,
      explanation: 'Wahyu pertama adalah Surah Al-Alaq ayat 1-5.',
    ),
    QuestionItem(
      id: 'pai_003',
      questionText: 'Rukun Islam yang ketiga adalah:',
      options: ['Mendirikan Shalat', 'Menunaikan Zakat', 'Berpuasa di bulan Ramadhan', 'Menunaikan Ibadah Haji'],
      correctOptionIndex: 1,
      explanation: 'Urutan Rukun Islam: Syahadat, Shalat, Zakat, Puasa, Haji.',
    ),
    QuestionItem(
      id: 'pai_004',
      questionText: 'Hukum bacaan Nun Sukun atau Tanwin apabila bertemu dengan huruf Alif/Hamzah dinamakan:',
      options: ['Izhar Halqi', 'Idgham Bigunnah', 'Iqlab', 'Ikhfa Haqiqi'],
      correctOptionIndex: 0,
      explanation: 'Izhar Halqi dibaca jelas tanpa dengung jika bertemu huruf halqiyah seperti Alif.',
    ),
    QuestionItem(
      id: 'pai_005',
      questionText: 'Khulafaur Rasyidin yang pertama dan memimpin umat Islam setelah wafatnya Rasulullah SAW adalah:',
      options: ['Umar bin Khattab', 'Abu Bakar Ash-Shiddiq', 'Utsman bin Affan', 'Ali bin Abi Thalib'],
      correctOptionIndex: 1,
      explanation: 'Khalifah pertama adalah Abu Bakar Ash-Shiddiq.',
    ),
    QuestionItem(
      id: 'pai_006',
      questionText: 'Jumlah Rukun Iman dalam ajaran Islam adalah:',
      options: ['5', '6', '7', '12'],
      correctOptionIndex: 1,
      explanation: 'Rukun Iman ada 6 (Iman kepada Allah, Malaikat, Kitab, Rasul, Hari Kiamat, Qada & Qadar).',
    ),
    QuestionItem(
      id: 'pai_007',
      questionText: 'Malaikat yang bertugas menyampaikan wahyu kepada para Nabi dan Rasul adalah:',
      options: ['Malaikat Mikail', 'Malaikat Jibril', 'Malaikat Israfil', 'Malaikat Izrail'],
      correctOptionIndex: 1,
      explanation: 'Malaikat Jibril bertugas membawa wahyu.',
    ),
    QuestionItem(
      id: 'pai_008',
      questionText: 'Shalat sunnah yang dikerjakan pada malam hari di bulan Ramadhan setelah shalat Isya dinamakan:',
      options: ['Shalat Tahajud', 'Shalat Tarawih', 'Shalat Dhuha', 'Shalat Istikharah'],
      correctOptionIndex: 1,
      explanation: 'Shalat Tarawih khusus dilaksanakan pada malam bulan Ramadhan.',
    ),
    QuestionItem(
      id: 'pai_009',
      questionText: 'Zakat yang wajib dikeluarkan setiap jiwa Muslim sebelum pelaksanaan shalat Idul Fitri disebut:',
      options: ['Zakat Maal', 'Zakat Fitrah', 'Zakat Profesi', 'Zakat Perniagaan'],
      correctOptionIndex: 1,
      explanation: 'Zakat Fitrah disucikan menjelang Idul Fitri.',
    ),
    QuestionItem(
      id: 'pai_010',
      questionText: 'Kitab Injil diturunkan oleh Allah SWT kepada Nabi:',
      options: ['Nabi Musa AS', 'Nabi Daud AS', 'Nabi Isa AS', 'Nabi Ibrahim AS'],
      correctOptionIndex: 2,
      explanation: 'Injil diturunkan kepada Nabi Isa AS.',
    ),
    QuestionItem(
      id: 'pai_011',
      questionText: 'Hukum dasar pelaksanaan ibadah shalat fardhu lima waktu bagi setiap Muslim baligh adalah:',
      options: ['Fardhu Kifayah', 'Fardhu \'Ain', 'Sunnah Muakkad', 'Sunnah Ghairu Muakkad'],
      correctOptionIndex: 1,
      explanation: 'Shalat 5 waktu hukumnya Fardhu \'Ain (wajib bagi tiap individu).',
    ),
    QuestionItem(
      id: 'pai_012',
      questionText: 'Peristiwa perjalanan malam Rasulullah SAW dari Masjidil Haram ke Masjidil Aqsa lalu ke Sidratul Muntaha dinamakan:',
      options: ['Hijrah', 'Isra Mi\'raj', 'Fathu Makkah', 'Perang Badar'],
      correctOptionIndex: 1,
      explanation: 'Peristiwa ini dikenal dengan Isra Mi\'raj.',
    ),
    QuestionItem(
      id: 'pai_013',
      questionText: 'Berikut ini yang BUKAN merupakan golongan penerima zakat (Mustahiq Zakat) menurut Surah At-Taubah ayat 60 adalah:',
      options: ['Fakir dan Miskin', 'Gharim (Orang berutang)', 'Orang Kaya', 'Ibnu Sabil'],
      correctOptionIndex: 2,
      explanation: 'Orang kaya tidak berhak menerima zakat.',
    ),
    QuestionItem(
      id: 'pai_014',
      questionText: 'Malaikat yang bertugas membagikan rezeki dan menurunkan hujan atas izin Allah SWT adalah:',
      options: ['Malaikat Jibril', 'Malaikat Mikail', 'Malaikat Israfil', 'Malaikat Atid'],
      correctOptionIndex: 1,
      explanation: 'Malaikat Mikail mengurus rezeki dan hujan.',
    ),
    QuestionItem(
      id: 'pai_015',
      questionText: 'Gelar "Ash-Shiddiq" yang diberikan kepada sahabat Abu Bakar memiliki arti:',
      options: ['Orang yang membedakan hak dan batil', 'Orang yang membenarkan perkataan Rasulullah', 'Orang yang memiliki dua cahaya', 'Pedang Allah yang terhunus'],
      correctOptionIndex: 1,
      explanation: 'Ash-Shiddiq berarti orang yang selalu membenarkan.',
    ),
    QuestionItem(
      id: 'pai_016',
      questionText: 'Batas minimal nisab emas wajib zakat maal jika telah mencapai haul 1 tahun adalah:',
      options: ['85 gram', '50 gram', '100 gram', '200 gram'],
      correctOptionIndex: 0,
      explanation: 'Nisab emas adalah 85 gram emas murni.',
    ),
    QuestionItem(
      id: 'pai_017',
      questionText: 'Kota tempat disyariatkannya pertama kali ibadah Puasa Ramadhan dan Zakat adalah:',
      options: ['Makkah', 'Madinah', 'Yerusalem', 'Thaqif'],
      correctOptionIndex: 1,
      explanation: 'Syariat puasa dan zakat diturunkan setelah Nabi hijrah ke Madinah.',
    ),
    QuestionItem(
      id: 'pai_018',
      questionText: 'Karakter utama Nabi Muhammad SAW yang berarti "Dapat Dipercaya" adalah:',
      options: ['Siddiq', 'Amanah', 'Tabligh', 'Fathanah'],
      correctOptionIndex: 1,
      explanation: 'Amanah artinya jujur dan dapat dipercaya.',
    ),
    QuestionItem(
      id: 'pai_019',
      questionText: 'Tayamum merupakan pengganti wudhu menggunakan media:',
      options: ['Air kelapa', 'Debu atau tanah yang suci', 'Kain basah', 'Minyak wangi'],
      correctOptionIndex: 1,
      explanation: 'Tayamum dilakukan dengan debu/tanah suci.',
    ),
    QuestionItem(
      id: 'pai_020',
      questionText: 'Perjanjian damai antara kaum Muslimin Madinah dan kaum Quraysh Makkah pada tahun 6 Hijriyah dinamakan:',
      options: ['Piagam Madinah', 'Perjanjian Hudaibiyah', 'Bai\'at Aqabah', 'Fathu Makkah'],
      correctOptionIndex: 1,
      explanation: 'Perjanjian ini dinamakan Perjanjian Hudaibiyah.',
    ),
    QuestionItem(
      id: 'pai_021',
      questionText: 'Kitab Zabur diturunkan oleh Allah SWT kepada Nabi:',
      options: ['Nabi Musa AS', 'Nabi Daud AS', 'Nabi Isa AS', 'Nabi Ibrahim AS'],
      correctOptionIndex: 1,
      explanation: 'Kitab Zabur diturunkan kepada Nabi Daud AS.',
    ),
    QuestionItem(
      id: 'pai_022',
      questionText: 'Kitab Taurat diturunkan oleh Allah SWT kepada Nabi:',
      options: ['Nabi Musa AS', 'Nabi Isa AS', 'Nabi Muhammad SAW', 'Nabi Ismail AS'],
      correctOptionIndex: 0,
      explanation: 'Taurat diturunkan kepada Nabi Musa AS.',
    ),
    QuestionItem(
      id: 'pai_023',
      questionText: 'Hukum bacaan Tajwid apabila Nun Sukun bertemu dengan huruf Ba (ب) dinamakan:',
      options: ['Izhar', 'Idgham', 'Iqlab', 'Ikhfa'],
      correctOptionIndex: 2,
      explanation: 'Iqlab terjadi jika Nun Sukun/Tanwin bertemu huruf Ba.',
    ),
    QuestionItem(
      id: 'pai_024',
      questionText: 'Sifat wajib bagi Nabi dan Rasul "Fathanah" memiliki arti:',
      options: ['Jujur', 'Cerdas / Bijaksana', 'Menyampaikan', 'Dapat dipercaya'],
      correctOptionIndex: 1,
      explanation: 'Fathanah berarti cerdas dan bijaksana.',
    ),
    QuestionItem(
      id: 'pai_025',
      questionText: 'Surah Al-Qur\'an yang tidak diawali dengan bacaan Basmalah adalah:',
      options: ['Surah At-Taubah', 'Surah Yasin', 'Surah Al-Kahfi', 'Surah Al-Baqarah'],
      correctOptionIndex: 0,
      explanation: 'Surah At-Taubah (Bara\'ah) tidak diawali Basmalah.',
    ),
    QuestionItem(
      id: 'pai_026',
      questionText: 'Imam Mazhab Fiqih Sunnah yang menyusun kitab Al-Muwatta adalah:',
      options: ['Imam Syafi\'i', 'Imam Malik', 'Imam Hanafi', 'Imam Ahmad bin Hanbal'],
      correctOptionIndex: 1,
      explanation: 'Imam Malik bin Anas adalah penyusun Al-Muwatta.',
    ),
    QuestionItem(
      id: 'pai_027',
      questionText: 'Penyusunan dan kodifikasi Al-Qur\'an menjadi satu Mushaf standar dilakukan pada masa Khalifah:',
      options: ['Abu Bakar Ash-Shiddiq', 'Umar bin Khattab', 'Utsman bin Affan', 'Ali bin Abi Thalib'],
      correctOptionIndex: 2,
      explanation: 'Mushaf Usmani dibukukan pada masa Khalifah Utsman bin Affan.',
    ),
    QuestionItem(
      id: 'pai_028',
      questionText: 'Sikap rela menerima keputusan dan ketentuan Allah SWT dinamakan:',
      options: ['Qana\'ah', 'Tawakal', 'Rida', 'Sabar'],
      correctOptionIndex: 2,
      explanation: 'Rida artinya rela dan lapang dada atas takdir Allah.',
    ),
    QuestionItem(
      id: 'pai_029',
      questionText: 'Prinsip berserah diri secara penuh kepada Allah SWT setelah berusaha maksimal dinamakan:',
      options: ['Ikhtiar', 'Tawakal', 'Qana\'ah', 'Zuhed'],
      correctOptionIndex: 1,
      explanation: 'Tawakal adalah menyerahkan hasil akhir kepada Allah.',
    ),
    QuestionItem(
      id: 'pai_030',
      questionText: 'Tindakan menyukuri nikmat Allah SWT dengan cara rendah hati dan membagikannya dinamakan akhlak:',
      options: ['Mahmudah', 'Mazmumah', 'Syirik', 'Riya'],
      correctOptionIndex: 0,
      explanation: 'Akhlak Mahmudah adalah akhlak terpuji.',
    ),
    QuestionItem(
      id: 'pai_031',
      questionText: 'Perbuatan memamerkan amalan ibadah agar mendapat pujian orang lain dinamakan:',
      options: ['Riya', 'Sum\'ah', 'Takabur', 'Hasad'],
      correctOptionIndex: 0,
      explanation: 'Riya adalah pamer amalan ibadah.',
    ),
    QuestionItem(
      id: 'pai_032',
      questionText: 'Perbuatan menceritakan amalan baik kepada orang lain agar namanya terkenal dinamakan:',
      options: ['Riya', 'Sum\'ah', 'Ujub', 'Dengki'],
      correctOptionIndex: 1,
      explanation: 'Sum\'ah adalah mencari pendengaran/pujian orang lain.',
    ),
    QuestionItem(
      id: 'pai_033',
      questionText: 'Dosa terbesar dalam Islam yang tidak diampuni jika dibawa mati adalah:',
      options: ['Mencuri', 'Syirik', 'Dusta', 'Ghibah'],
      correctOptionIndex: 1,
      explanation: 'Syirik (mempersekutukan Allah) adalah dosa paling besar.',
    ),
    QuestionItem(
      id: 'pai_034',
      questionText: 'Tahun kelahiran Nabi Muhammad SAW sering disebut sebagai Tahun Gajah karena peristiwa:',
      options: ['Serangan tentara bergajah Raja Abrahah ke Ka\'bah', 'Wabah penyakit gajah', 'Perdagangan gajah', 'Banjir besar di Makkah'],
      correctOptionIndex: 0,
      explanation: 'Abrahah memimpin pasukan gajah menyerang Ka\'bah.',
    ),
    QuestionItem(
      id: 'pai_035',
      questionText: 'Ibu kandung Nabi Muhammad SAW bernama:',
      options: ['Siti Khadijah', 'Siti Aminah', 'Halimah As-Sa\'diyah', 'Siti Aisyah'],
      correctOptionIndex: 1,
      explanation: 'Ibu Nabi Muhammad SAW adalah Siti Aminah.',
    ),
    QuestionItem(
      id: 'pai_036',
      questionText: 'Ayah kandung Nabi Muhammad SAW yang wafat sebelum Nabi lahir bernama:',
      options: ['Abu Talib', 'Abdullah', 'Abdul Muttalib', 'Hamzah'],
      correctOptionIndex: 1,
      explanation: 'Ayah Nabi bernama Abdullah bin Abdul Muttalib.',
    ),
    QuestionItem(
      id: 'pai_037',
      questionText: 'Wanita penyusui dan pengasuh masa kecil Nabi Muhammad SAW di dusun Bani Sa\'ad adalah:',
      options: ['Halimah As-Sa\'diyah', 'Ummu Aiman', 'Khadijah', 'Fatimah'],
      correctOptionIndex: 0,
      explanation: 'Halimah As-Sa\'diyah menyusui Nabi semasa kecil.',
    ),
    QuestionItem(
      id: 'pai_038',
      questionText: 'Istri pertama Rasulullah SAW yang mendukung penuh dakwah awal Islam adalah:',
      options: ['Siti Aisyah', 'Siti Khadijah binti Khuwailid', 'Hafshah', 'Zainab'],
      correctOptionIndex: 1,
      explanation: 'Khadijah binti Khuwailid adalah istri pertama Nabi.',
    ),
    QuestionItem(
      id: 'pai_039',
      questionText: 'Putri kesayangan Nabi Muhammad SAW yang menikah dengan Ali bin Abi Thalib adalah:',
      options: ['Ruqayyah', 'Ummu Kultsum', 'Fatimah Az-Zahra', 'Zainab'],
      correctOptionIndex: 2,
      explanation: 'Fatimah Az-Zahra menikah dengan Ali bin Abi Thalib.',
    ),
    QuestionItem(
      id: 'pai_040',
      questionText: 'Shalat sunnah yang dikerjakan saat memohon petunjuk pilihan terbaik dinamakan:',
      options: ['Shalat Hajat', 'Shalat Istikharah', 'Shalat Taubat', 'Shalat Tahajud'],
      correctOptionIndex: 1,
      explanation: 'Shalat Istikharah memohon petunjuk pilihan.',
    ),
    QuestionItem(
      id: 'pai_041',
      questionText: 'Shalat sunnah memohon ditimbulkannya hujan saat musim kemarau dinamakan:',
      options: ['Shalat Kusuf', 'Shalat Istisqa', 'Shalat Khusuf', 'Shalat Witir'],
      correctOptionIndex: 1,
      explanation: 'Shalat Istisqa meminta hujan.',
    ),
    QuestionItem(
      id: 'pai_042',
      questionText: 'Shalat sunnah gerhana matahari dinamakan:',
      options: ['Shalat Kusuf', 'Shalat Khusuf', 'Shalat Tarawih', 'Shalat Dhuha'],
      correctOptionIndex: 0,
      explanation: 'Shalat gerhana matahari disebut Shalat Kusuf.',
    ),
    QuestionItem(
      id: 'pai_043',
      questionText: 'Shalat sunnah gerhana bulan dinamakan:',
      options: ['Shalat Kusuf', 'Shalat Khusuf', 'Shalat Rawatib', 'Shalat Tahiyatul Masjid'],
      correctOptionIndex: 1,
      explanation: 'Shalat gerhana bulan disebut Shalat Khusuf.',
    ),
    QuestionItem(
      id: 'pai_044',
      questionText: 'Ayat Al-Qur\'an terkecil dan terpanjang berada pada Surah:',
      options: ['Surah Al-Baqarah', 'Surah Yasin', 'Surah Al-Imran', 'Surah An-Nisa'],
      correctOptionIndex: 0,
      explanation: 'Surah Al-Baqarah adalah surah terpanjang dalam Al-Qur\'an.',
    ),
    QuestionItem(
      id: 'pai_045',
      questionText: 'Jumlah Surah dalam Al-Qur\'an adalah:',
      options: ['114 Surah', '100 Surah', '66 Surah', '120 Surah'],
      correctOptionIndex: 0,
      explanation: 'Al-Qur\'an terdiri dari 114 Surah.',
    ),
    QuestionItem(
      id: 'pai_046',
      questionText: 'Jumlah Juz dalam Al-Qur\'an adalah:',
      options: ['10 Juz', '20 Juz', '30 Juz', '40 Juz'],
      correctOptionIndex: 2,
      explanation: 'Al-Qur\'an terbagi menjadi 30 Juz.',
    ),
    QuestionItem(
      id: 'pai_047',
      questionText: 'Surah Al-Qur\'an yang diturunkan sebelum Nabi Muhammad SAW hijrah ke Madinah disebut surah:',
      options: ['Madaniyah', 'Makkiyah', 'Jahiliyah', 'Qurayshiyah'],
      correctOptionIndex: 1,
      explanation: 'Surah Makkiyah turun sebelum hijrah.',
    ),
    QuestionItem(
      id: 'pai_048',
      questionText: 'Surah Al-Qur\'an yang diturunkan setelah Nabi Muhammad SAW hijrah ke Madinah disebut surah:',
      options: ['Makkiyah', 'Madaniyah', 'Ansar', 'Hijriyah'],
      correctOptionIndex: 1,
      explanation: 'Surah Madaniyah turun setelah hijrah.',
    ),
    QuestionItem(
      id: 'pai_049',
      questionText: 'Malaikat penanya di dalam kubur adalah:',
      options: ['Munkar dan Nakir', 'Raqib dan Atid', 'Malik dan Ridwan', 'Jibril dan Mikail'],
      correctOptionIndex: 0,
      explanation: 'Muka-nakir bertugas menanyai dalam kubur.',
    ),
    QuestionItem(
      id: 'pai_050',
      questionText: 'Malaikat pencatat amal baik manusia adalah:',
      options: ['Malaikat Raqib', 'Malaikat Atid', 'Malaikat Malik', 'Malaikat Ridwan'],
      correctOptionIndex: 0,
      explanation: 'Malaikat Raqib mencatat amal kebaikan.',
    ),
    QuestionItem(
      id: 'pai_051',
      questionText: 'Malaikat pencatat amal buruk manusia adalah:',
      options: ['Malaikat Raqib', 'Malaikat Atid', 'Malaikat Israfil', 'Malaikat Izrail'],
      correctOptionIndex: 1,
      explanation: 'Malaikat Atid mencatat keburukan.',
    ),
    QuestionItem(
      id: 'pai_052',
      questionText: 'Malaikat penjaga pintu surga adalah:',
      options: ['Malaikat Malik', 'Malaikat Ridwan', 'Malaikat Jibril', 'Malaikat Mikail'],
      correctOptionIndex: 1,
      explanation: 'Malaikat Ridwan adalah penjaga surga.',
    ),
    QuestionItem(
      id: 'pai_053',
      questionText: 'Malaikat penjaga pintu neraka adalah:',
      options: ['Malaikat Malik', 'Malaikat Ridwan', 'Malaikat Munkar', 'Malaikat Nakir'],
      correctOptionIndex: 0,
      explanation: 'Malaikat Malik adalah penjaga neraka.',
    ),
    QuestionItem(
      id: 'pai_054',
      questionText: 'Sahabat Nabi yang dijuluki "Al-Faruq" (Pembeda Hak dan Batil) adalah:',
      options: ['Abu Bakar', 'Umar bin Khattab', 'Utsman bin Affan', 'Ali bin Abi Thalib'],
      correctOptionIndex: 1,
      explanation: 'Umar bin Khattab dijuluki Al-Faruq.',
    ),
    QuestionItem(
      id: 'pai_055',
      questionText: 'Sahabat Nabi yang dijuluki "Dzun Nurain" (Pemilik Dua Cahaya) adalah:',
      options: ['Umar bin Khattab', 'Utsman bin Affan', 'Ali bin Abi Thalib', 'Zaid bin Tsabit'],
      correctOptionIndex: 1,
      explanation: 'Utsman dijuluki Dzun Nurain karena menikahi dua putri Nabi.',
    ),
    QuestionItem(
      id: 'pai_056',
      questionText: 'Sahabat Nabi yang dijuluki "Babul Ilmi" (Pintu Gerbang Ilmu) adalah:',
      options: ['Ali bin Abi Thalib', 'Abu Hurairah', 'Ibnu Abbas', 'Zaid bin Tsabit'],
      correctOptionIndex: 0,
      explanation: 'Ali bin Abi Thalib adalah pintu gerbang ilmu pengetahuan.',
    ),
    QuestionItem(
      id: 'pai_057',
      questionText: 'Hukum mengurus jenazah Muslim (memandikan, mengafani, menyhalatkan, memakamkan) adalah:',
      options: ['Fardhu \'Ain', 'Fardhu Kifayah', 'Sunnah Muakkad', 'Mubah'],
      correctOptionIndex: 1,
      explanation: 'Fardhu Kifayah gugur jika sudah diwakili oleh sebagian Muslim.',
    ),
    QuestionItem(
      id: 'pai_058',
      questionText: 'Berikut ini yang BUKAN merupakan rukun shalat jenazah adalah:',
      options: ['Niat', 'Empat kali takbir', 'Rukuk dan Sujud', 'Membaca Surah Al-Fatihah'],
      correctOptionIndex: 2,
      explanation: 'Shalat jenazah tidak memiliki rukuk dan sujud.',
    ),
    QuestionItem(
      id: 'pai_059',
      questionText: 'Masa tunggu bagi wanita Muslimah yang dicerai atau ditinggal mati suaminya dinamakan:',
      options: ['Rujuk', 'Iddah', 'Talak', 'Khulu\''],
      correctOptionIndex: 1,
      explanation: 'Masa penantian dinamakan Iddah.',
    ),
    QuestionItem(
      id: 'pai_060',
      questionText: 'Pelepasan ikatan perkawinan atas inisiatif dan permintaan istri dengan membayarkan ganti rugi disebut:',
      options: ['Talak', 'Khulu\' (Gugat Cerai)', 'Fasakh', 'Ila\''],
      correctOptionIndex: 1,
      explanation: 'Khulu\' adalah gugat cerai dari pihak istri.',
    ),
    QuestionItem(
      id: 'pai_061',
      questionText: 'Rukun Nikah dalam Islam terdiri dari Niat/Calon, Wali, Dua Saksi, dan:',
      options: ['Ijab Qabul', 'Mahar Besar', 'Resepsi Pesta', 'Surat Perjanjian'],
      correctOptionIndex: 0,
      explanation: 'Ijab Qabul adalah ikrar suci akad nikah.',
    ),
    QuestionItem(
      id: 'pai_062',
      questionText: 'Pemberian wajib dari calon suami kepada calon istri saat akad nikah dinamakan:',
      options: ['Hadiah', 'Mahar / Mas Kawin', 'Warisan', 'Zakat'],
      correctOptionIndex: 1,
      explanation: 'Mahar adalah hak mutlak pengantin wanita.',
    ),
    QuestionItem(
      id: 'pai_063',
      questionText: 'Ilmu yang mempelajari tata cara pembagian harta warisan dalam Islam dinamakan:',
      options: ['Ilmu Fiqih', 'Ilmu Faraidh / Mawaris', 'Ilmu Falaq', 'Ilmu Usul Fiqih'],
      correctOptionIndex: 1,
      explanation: 'Ilmu Faraidh mengurus hukum waris Islam.',
    ),
    QuestionItem(
      id: 'pai_064',
      questionText: 'Ilmu yang mempelajari perhitungan posisi benda langit untuk menentukan arah kiblat dan waktu shalat dinamakan:',
      options: ['Ilmu Falaq / Astronomi Islam', 'Ilmu Kalam', 'Ilmu Tajwid', 'Ilmu Hikmah'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Falaq menghitung posisi benda langit.',
    ),
    QuestionItem(
      id: 'pai_065',
      questionText: 'Pengartian kata "Hadits" secara bahasa adalah:',
      options: ['Lama / Kuno', 'Perkataan / Baru', 'Perintah', 'Kisah'],
      correctOptionIndex: 1,
      explanation: 'Hadits secara bahasa berarti perkataan atau kabar baru.',
    ),
    QuestionItem(
      id: 'pai_066',
      questionText: 'Struktur Hadits terdiri dari tiga bagian utama yaitu Sanad, Matan, dan:',
      options: ['Rawi (Perawi)', 'Tafsir', 'Sanad II', 'Hukum'],
      correctOptionIndex: 0,
      explanation: 'Tiga komponen: Sanad (Jalur), Matan (Isi), dan Rawi (Penyampai).',
    ),
    QuestionItem(
      id: 'pai_067',
      questionText: 'Tingkatan derajat Hadits yang paling tinggi kualitas keabsahannya adalah Hadits:',
      options: ['Shahih', 'Hasan', 'Da\'if', 'Maudhu\''],
      correctOptionIndex: 0,
      explanation: 'Hadits Shahih memenuhi syarat sanad bersambung dan perawi adil.',
    ),
    QuestionItem(
      id: 'pai_068',
      questionText: 'Hadits palsu yang dibuat-buat oleh seseorang dan dinisbatkan kepada Rasulullah SAW dinamakan Hadits:',
      options: ['Da\'if', 'Maudhu\'', 'Mursal', 'Mauquf'],
      correctOptionIndex: 1,
      explanation: 'Hadits Maudhu\' adalah hadits palsu.',
    ),
    QuestionItem(
      id: 'pai_069',
      questionText: 'Dua perawi hadits terpopuler yang dijuluki "Muttafaqun \'Alaih" jika keduanya menyepakati satu riwayat adalah:',
      options: ['Imam Bukhari dan Imam Muslim', 'Imam Abu Daud dan Tirmidzi', 'Imam Malik dan Ahmad', 'Imam An-Nasa\'i dan Ibnu Majah'],
      correctOptionIndex: 0,
      explanation: 'Muttafaqun \'Alaih adalah kesepakatan Shahih Bukhari & Shahih Muslim.',
    ),
    QuestionItem(
      id: 'pai_070',
      questionText: 'Surah Al-Qur\'an yang disepadankan dengan sepertiga Al-Qur\'an karena menegaskan tauhid murni adalah:',
      options: ['Surah Al-Fatihah', 'Surah Al-Ikhlas', 'Surah Al-Falaq', 'Surah An-Nas'],
      correctOptionIndex: 1,
      explanation: 'Surah Al-Ikhlas bernilai sepertiga Al-Qur\'an.',
    ),
    QuestionItem(
      id: 'pai_071',
      questionText: 'Induk dari Al-Qur\'an (Ummul Qur\'an) yang wajib dibaca pada setiap rakaat shalat adalah:',
      options: ['Surah Al-Fatihah', 'Surah Yasin', 'Surah Al-Baqarah', 'Surah Ayat Kursi'],
      correctOptionIndex: 0,
      explanation: 'Surah Al-Fatihah adalah Ummul Kitab.',
    ),
    QuestionItem(
      id: 'pai_072',
      questionText: 'Malam kemuliaan di bulan Ramadhan yang nilainya lebih baik dari 1.000 bulan dinamakan:',
      options: ['Nuzulul Qur\'an', 'Lailatul Qadar', 'Malam Isra Mi\'raj', 'Malam Nisfu Sya\'ban'],
      correctOptionIndex: 1,
      explanation: 'Lailatul Qadar lebih baik dari 1000 bulan.',
    ),
    QuestionItem(
      id: 'pai_073',
      questionText: 'Peristiwa pertama kali diturunkannya ayat Al-Qur\'an diperingati sebagai peristiwa:',
      options: ['Lailatul Qadar', 'Nuzulul Qur\'an', 'Tahun Baru Hijriyah', 'Maulid Nabi'],
      correctOptionIndex: 1,
      explanation: 'Nuzulul Qur\'an diperingati setiap 17 Ramadhan.',
    ),
    QuestionItem(
      id: 'pai_074',
      questionText: 'Sistem penanggalan Kalender Hijriyah didasarkan pada peredaran:',
      options: ['Matahari (Solar)', 'Bulan (Lunar)', 'Bintang (Stellar)', 'Bumi (Geosentrik)'],
      correctOptionIndex: 1,
      explanation: 'Kalender Hijriyah mengacu pada siklus Bulan (Komariyah).',
    ),
    QuestionItem(
      id: 'pai_075',
      questionText: 'Penetapan awal penanggalan Hijriyah (Tahun 1 H) dimulai pada masa Khalifah Umar bin Khattab merujuk peristiwa:',
      options: ['Kelahiran Nabi', 'Turunnya Wahyu Pertama', 'Hijrah Nabi dari Makkah ke Madinah', 'Wafatnya Rasulullah'],
      correctOptionIndex: 2,
      explanation: 'Tahun 1 Hijriyah dimulai dari peristiwa Hijrah Nabi.',
    ),
    QuestionItem(
      id: 'pai_076',
      questionText: 'Tempat berkumpulnya seluruh manusia setelah dibangkitkan dari alam kubur pada hari kiamat dinamakan:',
      options: ['Alam Barzakh', 'Padang Mahsyar', 'Sirath', 'Mizan'],
      correctOptionIndex: 1,
      explanation: 'Manusia dikumpulkan di Padang Mahsyar.',
    ),
    QuestionItem(
      id: 'pai_077',
      questionText: 'Timbangan amal perbuatan manusia di akhirat kelak dinamakan:',
      options: ['Sirath', 'Mizan', 'Mahsyar', 'Hisab'],
      correctOptionIndex: 1,
      explanation: 'Mizan adalah timbangan kebaikan & keburukan.',
    ),
    QuestionItem(
      id: 'pai_078',
      questionText: 'Jembatan yang membentang di atas neraka menuju surga dinamakan:',
      options: ['Mizan', 'Sirath', 'Barzakh', 'Araf'],
      correctOptionIndex: 1,
      explanation: 'Sirathal Mustaqim adalah jembatan penyeberangan.',
    ),
    QuestionItem(
      id: 'pai_079',
      questionText: 'Perhitungan dan pemeriksaan seluruh amalan manusia di akhirat dinamakan:',
      options: ['Hisab', 'Mizan', 'Ba\'ats', 'Jaza\''],
      correctOptionIndex: 0,
      explanation: 'Yaumul Hisab adalah hari perhitungan amal.',
    ),
    QuestionItem(
      id: 'pai_080',
      questionText: 'Hari kebangkitan seluruh manusia dari dalam kubur dinamakan:',
      options: ['Yaumul Ba\'ats', 'Yaumul Mahsyar', 'Yaumul Jaza\'', 'Yaumul Qiyamah'],
      correctOptionIndex: 0,
      explanation: 'Yaumul Ba\'ats adalah hari kebangkitan dari kubur.',
    ),
    QuestionItem(
      id: 'pai_081',
      questionText: 'Ibadah menyembelih hewan ternak (kambing/sapi) sebagai bentuk rasa syukur atas lahirnya seorang anak dinamakan:',
      options: ['Aqiqah', 'Kurban', 'Hadyu', 'Sedekah'],
      correctOptionIndex: 0,
      explanation: 'Aqiqah disyariatkan saat kelahiran bayi.',
    ),
    QuestionItem(
      id: 'pai_082',
      questionText: 'Jumlah kambing aqiqah untuk kelahiran anak laki-laki menurut sunnah adalah:',
      options: ['1 Ekor', '2 Ekor', '3 Ekor', '4 Ekor'],
      correctOptionIndex: 1,
      explanation: 'Bayi laki-laki 2 ekor kambing, perempuan 1 ekor.',
    ),
    QuestionItem(
      id: 'pai_083',
      questionText: 'Penyembelihan hewan kurban dilaksanakan pada Hari Raya Idul Adha dan Hari Tasyrik yaitu tanggal:',
      options: ['10, 11, 12, 13 Dzulhijjah', '1, 2, 3 Syawal', '15 Sya\'ban', '17 Ramadhan'],
      correctOptionIndex: 0,
      explanation: 'Kurban dilaksanakan 10 Dzulhijjah dan 11-13 Tasyrik.',
    ),
    QuestionItem(
      id: 'pai_084',
      questionText: 'Rukun Haji yang wajib dilaksanakan dengan mengelilingi Ka\'bah sebanyak 7 kali putaran dinamakan:',
      options: ['Sa\'i', 'Tawaf', 'Wukuf', 'Tahallul'],
      correctOptionIndex: 1,
      explanation: 'Tawaf mengelilingi Ka\'bah 7 kali.',
    ),
    QuestionItem(
      id: 'pai_085',
      questionText: 'Berlari-lari kecil antara bukit Shofa dan Marwah sebanyak 7 kali dalam ibadah Haji/Umrah dinamakan:',
      options: ['Tawaf', 'Sa\'i', 'Wukuf', 'Mabit'],
      correctOptionIndex: 1,
      explanation: 'Sa\'i bergerak dari Shofa ke Marwah.',
    ),
    QuestionItem(
      id: 'pai_086',
      questionText: 'Inti atau puncak pelaksanaan ibadah Haji yang dilaksanakan di Padang Arafah pada 9 Dzulhijjah adalah:',
      options: ['Sa\'i', 'Wukuf', 'Tawaf Wada\'', 'Mencukur rambut'],
      correctOptionIndex: 1,
      explanation: 'Al-Hajju Arafah (Haji adalah Wukuf di Arafah).',
    ),
    QuestionItem(
      id: 'pai_087',
      questionText: 'Memotong sekurang-kurangnya 3 helai rambut sebagai penanda selesainya rukun Haji/Umrah dinamakan:',
      options: ['Tahallul', 'Mabit', 'Ihram', 'Dam'],
      correctOptionIndex: 0,
      explanation: 'Tahallul melepaskan larangan Ihram dengan mencukur rambut.',
    ),
    QuestionItem(
      id: 'pai_088',
      questionText: 'Pakaian khusus tanpa jahitan yang dikenakan jamaah haji pria saat niat haji dinamakan:',
      options: ['Pakaian Ihram', 'Gamis', 'Jubah', 'Kain Sorban'],
      correctOptionIndex: 0,
      explanation: 'Pakaian Ihram pria berupa 2 helai kain putih tak berjahit.',
    ),
    QuestionItem(
      id: 'pai_089',
      questionText: 'Denda atau penalti yang harus dibayar jamaah haji karena melanggar larangan ihram dinamakan:',
      options: ['Fidyah', 'Dam', 'Kafarat', 'Zakat'],
      correctOptionIndex: 1,
      explanation: 'Dam adalah denda pelanggaran tata cara haji.',
    ),
    QuestionItem(
      id: 'pai_090',
      questionText: 'Pengganti puasa Ramadhan bagi orang tua renta atau sakit menahun yang tak sanggup puasa dinamakan:',
      options: ['Kafarat', 'Fidyah', 'Dam', 'Sedekah Sunnah'],
      correctOptionIndex: 1,
      explanation: 'Fidyah memberi makan orang miskin per hari puasa yang ditinggalkan.',
    ),
    QuestionItem(
      id: 'pai_091',
      questionText: 'Cendekiawan Muslim perintis ilmu Kedokteran modern penyusun kitab "Al-Qanun fi at-Tibb" (The Canon of Medicine) adalah:',
      options: ['Al-Khawarizmi', 'Ibnu Sina (Avicenna)', 'Al-Farabi', 'Ibnu Rusyd'],
      correctOptionIndex: 1,
      explanation: 'Ibnu Sina (Avicenna) adalah Bapak Kedokteran Modern.',
    ),
    QuestionItem(
      id: 'pai_092',
      questionText: 'Cendekiawan Muslim penemu konsep Aljabar dan angka Nol (0) adalah:',
      options: ['Al-Khawarizmi', 'Ibnu Al-Haitsam', 'Al-Biruni', 'Jabir bin Hayyan'],
      correctOptionIndex: 0,
      explanation: 'Al-Khawarizmi adalah matematikawan penemu Aljabar dan angka 0.',
    ),
    QuestionItem(
      id: 'pai_093',
      questionText: 'Cendekiawan Muslim perintis ilmu Optik dan kamera obscura adalah:',
      options: ['Ibnu Al-Haitsam (Alhazen)', 'Al-Kindi', 'Ibnu Khaldun', 'Al-Razi'],
      correctOptionIndex: 0,
      explanation: 'Ibnu Al-Haitsam adalah pelopor Optik modern.',
    ),
    QuestionItem(
      id: 'pai_094',
      questionText: 'Bapak Sosiologi Islam dan Sejarah Dunia penyusun kitab "Muqaddimah" adalah:',
      options: ['Ibnu Khaldun', 'Ibnu Batutah', 'Al-Ghazali', 'Al-Mawardi'],
      correctOptionIndex: 0,
      explanation: 'Ibnu Khaldun menulis karya legendaris Muqaddimah.',
    ),
    QuestionItem(
      id: 'pai_095',
      questionText: 'Ulama besar pengarang kitab keagamaan populer "Ihya Ulumuddin" adalah:',
      options: ['Imam Al-Ghazali', 'Imam An-Nawawi', 'Ibnu Taimiyah', 'Imam As-Suyuthi'],
      correctOptionIndex: 0,
      explanation: 'Hujjatul Islam Imam Al-Ghazali menyusun Ihya Ulumuddin.',
    ),
    QuestionItem(
      id: 'pai_096',
      questionText: 'Sikap saling menghargai dan menghormati perbedaan keyakinan beragama dalam Islam dinamakan:',
      options: ['Tasamuh (Toleransi)', 'Tawazun (Seimbang)', 'Tawasuth (Moderasi)', 'Ta\'awun (Tolong-menolong)'],
      correctOptionIndex: 0,
      explanation: 'Tasamuh artinya sikap saling menghargai & toleran.',
    ),
    QuestionItem(
      id: 'pai_097',
      questionText: 'Sikap moderat dan berada di tengah-tengah tanpa ekstremitas dalam beragama dinamakan:',
      options: ['Tawasuth', 'Tawazun', 'Tasamuh', 'Ta\'aruf'],
      correctOptionIndex: 0,
      explanation: 'Tawasuth adalah paham keberagamaan yang moderat.',
    ),
    QuestionItem(
      id: 'pai_098',
      questionText: 'Prinsip saling tolong-menolong dalam kebaikan dan ketakwaan dinamakan:',
      options: ['Ta\'awun', 'Ta\'aruf', 'Tafakur', 'Tadabbur'],
      correctOptionIndex: 0,
      explanation: 'Ta\'awun adalah prinsip saling menolong dalam kebaikan.',
    ),
    QuestionItem(
      id: 'pai_099',
      questionText: 'Prinsip saling mengenal dan membangun persaudaraan antarbangsa/suku dinamakan:',
      options: ['Ta\'aruf', 'Tafakur', 'Tadabbur', 'Tabayyun'],
      correctOptionIndex: 0,
      explanation: 'Ta\'aruf adalah saling mengenali antar sesama manusia.',
    ),
    QuestionItem(
      id: 'pai_100',
      questionText: 'Proses klarifikasi dan meneliti kebenaran berita atau informasi sebelum menyebarkannya dinamakan:',
      options: ['Tabayyun', 'Tadabbur', 'Tazkiyah', 'Tawakal'],
      correctOptionIndex: 0,
      explanation: 'Tabayyun adalah mengecek dan memverifikasi kebenaran informasi.',
    ),
  ];
}
