import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPendidikanAgamaBuddhaQuestions() {
  return const [
    QuestionItem(
      id: 'pab_001',
      questionText: 'Pendiri Agama Buddha adalah Pangeran Siddharta Gautama yang mencapai Pencerahan Sempurna menjadi Buddha di bawah pohon:',
      options: ['Pohon Bodhi', 'Pohon Banyan', 'Pohon Sal', 'Pohon Teratai'],
      correctOptionIndex: 0,
      explanation: 'Siddharta Gautama mendapat pencerahan di bawah Pohon Bodhi di Bodh Gaya.',
    ),
    QuestionItem(
      id: 'pab_002',
      questionText: 'Kitab Suci Agama Buddha dinamakan Tipitaka (Pali) / Tripitaka (Sanskerta) yang artinya:',
      options: ['Tiga Keranjang / Tiga Himpunan', 'Tiga Jalan Suci', 'Tiga Mahakarya', 'Tiga Hukum Suci'],
      correctOptionIndex: 0,
      explanation: 'Tipitaka terdiri dari 3 Pitaka (Keranjang/Himpunan ajaran).',
    ),
    QuestionItem(
      id: 'pab_003',
      questionText: 'Tiga bagian dalam Kitab Suci Tipitaka terdiri dari Vinaya Pitaka, Sutta Pitaka, dan:',
      options: ['Abhidhamma Pitaka', 'Dhammapada', 'Jataka', 'Visuddhimagga'],
      correctOptionIndex: 0,
      explanation: 'Tipitaka: Vinaya Pitaka, Sutta Pitaka, Abhidhamma Pitaka.',
    ),
    QuestionItem(
      id: 'pab_004',
      questionText: 'Bagian Tipitaka yang memuat aturan kedisiplinan dan tata tertib bagi para bhikkhu dan bhikkhuni dinamakan:',
      options: ['Vinaya Pitaka', 'Sutta Pitaka', 'Abhidhamma Pitaka', 'Paritta'],
      correctOptionIndex: 0,
      explanation: 'Vinaya Pitaka berisi peraturan tata tertib kebhikkhuan.',
    ),
    QuestionItem(
      id: 'pab_005',
      questionText: 'Bagian Tipitaka yang memuat khotbah-khotbah dan nasehat langsung Buddha Gautama dinamakan:',
      options: ['Sutta Pitaka', 'Vinaya Pitaka', 'Abhidhamma Pitaka', 'Niti'],
      correctOptionIndex: 0,
      explanation: 'Sutta Pitaka memuat himpunan khotbah Buddha.',
    ),
    QuestionItem(
      id: 'pab_006',
      questionText: 'Bagian Tipitaka yang memuat analisa metafisika, filsafat tinggi, dan psikologi Dhamma dinamakan:',
      options: ['Abhidhamma Pitaka', 'Sutta Pitaka', 'Vinaya Pitaka', 'Buddhacarita'],
      correctOptionIndex: 0,
      explanation: 'Abhidhamma Pitaka berisi doktrin filsafat murni dan analisis kesadaran.',
    ),
    QuestionItem(
      id: 'pab_007',
      questionText: 'Inti Kebenaran pertama ajaran Buddha "Empat Kebenaran Mulia" (Ariya Sacca) mengajarkan tentang kebenaran:',
      options: ['Dukkha (Penderitaan)', 'Samudaya (Asal Penderitaan)', 'Nirodha (Penghentian Penderitaan)', 'Magga (Jalan Penghentian Penderitaan)'],
      correctOptionIndex: 0,
      explanation: 'Empat Kebenaran Mulia diawali tentang Kebenaran Dukkha.',
    ),
    QuestionItem(
      id: 'pab_008',
      questionText: 'Akar penyebab utama timbulnya Dukkha (Samudaya Dukkha) menurut ajaran Buddha adalah:',
      options: ['Tanha (Keinginan Rendah / Keserakahan / Kelekatan)', 'Kemiskinan', 'Nasib Takdir', 'Takut Kematian'],
      correctOptionIndex: 0,
      explanation: 'Tanha (Kehausan/Keinginan yang tidak puas) adalah sumber penderitaan.',
    ),
    QuestionItem(
      id: 'pab_009',
      questionText: 'Tiga Akar Kejahatan (Triklesa / Akusala Mula) yang memicu penderitaan manusia adalah Lobha, Dosa, dan:',
      options: ['Moha (Kegelapan Batin / Kebodohan)', 'Krodha', 'Tanha', 'Upadana'],
      correctOptionIndex: 0,
      explanation: 'Lobha (Keserakahan), Dosa (Kebencian), Moha (Kegelapan batin).',
    ),
    QuestionItem(
      id: 'pab_010',
      questionText: 'Jalan bebas dari penderitaan dirumuskan dalam "Jalan Mulia Berunsur Delapan" (Atthangika Magga) yang terbagi dalam 3 kelompok:',
      options: ['Sila (Etika), Samadhi (Konsentrasi), Panna (Kebijaksanaan)', 'Karma, Dharma, Moksha', 'Cinta, Kasih, Damai', 'Murni, Suci, Agung'],
      correctOptionIndex: 0,
      explanation: 'Jalan Delapan terbagi menjadi Sila, Samadhi, dan Panna.',
    ),
    QuestionItem(
      id: 'pab_011',
      questionText: 'Manakah di bawah ini yang BUKAN merupakan unsur dari Jalan Mulia Berunsur Delapan?',
      options: ['Kekayaan Benar', 'Pandangan Benar', 'Ucapan Benar', 'Perbuatan Benar'],
      correctOptionIndex: 0,
      explanation: 'Kekayaan Benar bukan merupakan bagian dari Delapan Jalan Mulia.',
    ),
    QuestionItem(
      id: 'pab_012',
      questionText: 'Tiga Corak Umum Alam Semesta (Tilakkhana) meliputi Anicca, Dukkha, dan:',
      options: ['Anatta (Tanpa Inti / Tanpa Roh Permanen)', 'Nibbana', 'Karma', 'Samsara'],
      correctOptionIndex: 0,
      explanation: 'Tilakkhana: Anicca (ketidaktetapan), Dukkha (penderitaan), Anatta (tanpa diri/roh permanen).',
    ),
    QuestionItem(
      id: 'pab_013',
      questionText: 'Prinsip ketidaktetapan dan segala sesuatu selalu berubah dalam Tilakkhana dinamakan:',
      options: ['Anicca', 'Anatta', 'Dukkha', 'Kamma'],
      correctOptionIndex: 0,
      explanation: 'Anicca artinya segala sesuatu yang terkondisi itu tidak kekal.',
    ),
    QuestionItem(
      id: 'pab_014',
      questionText: 'Tujuan akhir dan kebahagiaan tertinggi umat Buddhis di mana api noda batin telah padam total dinamakan:',
      options: ['Nibbana / Nirvana', 'Surga Tusita', 'Moksha', 'Brahma Loka'],
      correctOptionIndex: 0,
      explanation: 'Nibbana / Nirvana adalah padamnya kebodohan dan klesha.',
    ),
    QuestionItem(
      id: 'pab_015',
      questionText: 'Hukum Sebab Akibat perbuatan dalam ajaran Buddha di mana perbuatan baik menghasilkan kebaikan dinamakan:',
      options: ['Hukum Kamma (Karma)', 'Hukum Niyama', 'Hukum Tilakkhana', 'Hukum Sutta'],
      correctOptionIndex: 0,
      explanation: 'Kamma (Pali) / Karma (Sanskerta) adalah hukum niat perbuatan.',
    ),
    QuestionItem(
      id: 'pab_016',
      questionText: 'Hukum sebab akibat yang saling bergantung terdiri dari 12 mata rantai sebab musabab dinamakan:',
      options: ['Paticcasamuppada', 'Atthangika Magga', 'Ariya Sacca', 'Catur Paramita'],
      correctOptionIndex: 0,
      explanation: 'Paticcasamuppada adalah Hukum Saling Menjaminkan/Terikat.',
    ),
    QuestionItem(
      id: 'pab_017',
      questionText: 'Empat Sifat Luhur / Keadaan Batin Agung (Brahma Vihara) terdiri dari Metta, Karuna, Mudita, dan:',
      options: ['Uppekha (Keseimbangan Batin)', 'Sila', 'Panna', 'Samadhi'],
      correctOptionIndex: 0,
      explanation: 'Metta (Cinta Kasih), Karuna (Kasih Sayang), Mudita (Simpati/Turut Bahagia), Uppekha (Keseimbangan batin).',
    ),
    QuestionItem(
      id: 'pab_018',
      questionText: 'Sifat Brahma Vihara "Metta" memiliki arti:',
      options: ['Cinta Kasih universal tanpa pamrih', 'Kasih Sayang kepada yang menderita', 'Turut bahagia atas keberhasilan orang', 'Ketenangan batin'],
      correctOptionIndex: 0,
      explanation: 'Metta adalah cinta kasih yang memancar kepada semua makhluk.',
    ),
    QuestionItem(
      id: 'pab_019',
      questionText: 'Sifat Brahma Vihara "Karuna" memiliki arti:',
      options: ['Kasih Sayang dan empati membantu yang menderita', 'Cinta kasih', 'Turut gembira', 'Keseimbangan batin'],
      correctOptionIndex: 0,
      explanation: 'Karuna adalah belas kasihan tergerak meringankan beban.',
    ),
    QuestionItem(
      id: 'pab_020',
      questionText: 'Sifat Brahma Vihara "Mudita" memiliki arti:',
      options: ['Turut bahagia atas keberhasilan dan kebahagiaan orang lain', 'Kasih sayang', 'Cinta kasih', 'Ketenangan'],
      correctOptionIndex: 0,
      explanation: 'Mudita adalah rasa gembira tanpa iri atas sukses orang.',
    ),
    QuestionItem(
      id: 'pab_021',
      questionText: 'Sifat Brahma Vihara "Uppekha" memiliki arti:',
      options: ['Keseimbangan batin dan tidak memihak (Ketenangan Batin)', 'Kasih sayang', 'Kegembiraan', 'Semangat'],
      correctOptionIndex: 0,
      explanation: 'Uppekha adalah batin seimbang tanpa benci/suka berlebihan.',
    ),
    QuestionItem(
      id: 'pab_022',
      questionText: 'Lima Pedoman Etika Moralitas harian bagi Umat Layak / Upasaka-Upasika dinamakan:',
      options: ['Pancasila Buddhis', 'Atthasila', 'Dasasila', 'Patimokkha'],
      correctOptionIndex: 0,
      explanation: 'Pancasila Buddhis adalah 5 latihan etika moral.',
    ),
    QuestionItem(
      id: 'pab_023',
      questionText: 'Sila pertama dalam Pancasila Buddhis mengajarkan latihan menghindari:',
      options: ['Pembunuhan makhluk hidup', 'Pencurian', 'Perbuatan asusila', 'Berbohong'],
      correctOptionIndex: 0,
      explanation: 'Sila 1: Panatipata Veramani (Menghindari pembunuhan).',
    ),
    QuestionItem(
      id: 'pab_024',
      questionText: 'Sila kedua dalam Pancasila Buddhis mengajarkan latihan menghindari:',
      options: ['Mencuri / mengambil yang tidak diberikan', 'Membunuh', 'Berbohong', 'Mabuk-mabukan'],
      correctOptionIndex: 0,
      explanation: 'Sila 2: Adinnadana Veramani (Menghindari mengambil barang yang tak diberikan).',
    ),
    QuestionItem(
      id: 'pab_025',
      questionText: 'Sila ketiga dalam Pancasila Buddhis mengajarkan latihan menghindari:',
      options: ['Perbuatan asusila / perzinahan', 'Membunuh', 'Mencuri', 'Minuman keras'],
      correctOptionIndex: 0,
      explanation: 'Sila 3: Kamesumicchacara Veramani (Menghindari perbuatan asusila).',
    ),
    QuestionItem(
      id: 'pab_026',
      questionText: 'Sila keempat dalam Pancasila Buddhis mengajarkan latihan menghindari:',
      options: ['Ucapan bohong / tidak benar', 'Membunuh', 'Mencuri', 'Mabuk'],
      correctOptionIndex: 0,
      explanation: 'Sila 4: Musavada Veramani (Menghindari ucapan tidak benar).',
    ),
    QuestionItem(
      id: 'pab_027',
      questionText: 'Sila kelima dalam Pancasila Buddhis mengajarkan latihan menghindari:',
      options: ['Minuman keras dan zat yang melemahkan kesadaran', 'Membunuh', 'Mencuri', 'Asusila'],
      correctOptionIndex: 0,
      explanation: 'Sila 5: Suramerayamajjapamadatthana Veramani (Menghindari pemabukan).',
    ),
    QuestionItem(
      id: 'pab_028',
      questionText: 'Delapan pedoman latihan etika yang dilaksanakan Umat Buddhis pada hari-hari Uposatha dinamakan:',
      options: ['Atthasila', 'Pancasila', 'Dasasila', 'Vinaya'],
      correctOptionIndex: 0,
      explanation: 'Atthasila adalah 8 sila latihan pada hari Uposatha.',
    ),
    QuestionItem(
      id: 'pab_029',
      questionText: 'Dua jenis latihan Meditasi dalam ajaran Buddha adalah Samatha Bhavana dan:',
      options: ['Vipassana Bhavana', 'Metta Bhavana', 'Anapanasati', 'Zazen'],
      correctOptionIndex: 0,
      explanation: 'Samatha (ketenangan) dan Vipassana (pandangan terang).',
    ),
    QuestionItem(
      id: 'pab_030',
      questionText: 'Meditasi untuk mencapai Ketenangan Batin (Samadhi) dinamakan:',
      options: ['Samatha Bhavana', 'Vipassana Bhavana', 'Metta Bhavana', 'Satipatthana'],
      correctOptionIndex: 0,
      explanation: 'Samatha Bhavana memfokuskan pikiran menuju ketenangan.',
    ),
    QuestionItem(
      id: 'pab_031',
      questionText: 'Meditasi untuk mencapai Pandangan Terang dan Kebijaksanaan memahami Tilakkhana dinamakan:',
      options: ['Vipassana Bhavana', 'Samatha Bhavana', 'Kasinati', 'Dhuta'],
      correctOptionIndex: 0,
      explanation: 'Vipassana Bhavana mengembangkan pandangan terang kesadaran murni.',
    ),
    QuestionItem(
      id: 'pab_032',
      questionText: 'Teknik meditasi populer yang mengamati keluar masuknya nafas dinamakan:',
      options: ['Anapanasati', 'Metta Bhavana', 'Maranasati', 'Buddhanussati'],
      correctOptionIndex: 0,
      explanation: 'Anapanasati adalah kesadaran pada pernapasan.',
    ),
    QuestionItem(
      id: 'pab_033',
      questionText: 'Hari Raya terbesar Umat Buddhis memperingati Tiga Peristiwa Agung (Tiga Trisuci) adalah Hari Raya:',
      options: ['Trisuci Waisak', 'Asadha', 'Kathina', 'Magha Puja'],
      correctOptionIndex: 0,
      explanation: 'Waisak memperingati Kelahiran, Pencerahan, dan Parinibbana Buddha Gautama.',
    ),
    QuestionItem(
      id: 'pab_034',
      questionText: 'Tiga Peristiwa Agung yang diperingati saat Hari Raya Trisuci Waisak terjadi pada saat bulan purnama di bulan:',
      options: ['Waisakha (Mei)', 'Asalha (Juli)', 'Kattika (Oktober)', 'Magha (Februari)'],
      correctOptionIndex: 0,
      explanation: 'Tiga peristiwa Waisak terjadi pada Bulan Purnama Waisak.',
    ),
    QuestionItem(
      id: 'pab_035',
      questionText: 'Hari Raya memperingati Khotbah Pertama Buddha (Dhammacakkappavattana Sutta) di Taman Rusa Isipatana dinamakan:',
      options: ['Asadha (Asalha Puja)', 'Waisak', 'Kathina', 'Magha Puja'],
      correctOptionIndex: 0,
      explanation: 'Asadha memperingati pemutaran Roda Dhamma pertama kali.',
    ),
    QuestionItem(
      id: 'pab_036',
      questionText: 'Khotbah Pertama Buddha Gautama tentang Empat Kebenaran Mulia dinamakan Sutta:',
      options: ['Dhammacakkappavattana Sutta', 'Anattalakkhana Sutta', 'Mangala Sutta', 'Karaniya Metta Sutta'],
      correctOptionIndex: 0,
      explanation: 'Dhammacakkappavattana Sutta = Pemutaran Roda Dhamma.',
    ),
    QuestionItem(
      id: 'pab_037',
      questionText: 'Hari Raya memperingati berkumpulnya 1.250 Arahat secara spontan tanpa diundang dihadapan Buddha adalah:',
      options: ['Magha Puja', 'Asadha', 'Waisak', 'Kathina'],
      correctOptionIndex: 0,
      explanation: 'Magha Puja memperingati perhimpunan 1.250 Arahat.',
    ),
    QuestionItem(
      id: 'pab_038',
      questionText: 'Prinsip ajaran ringkasan Dhamma "Ovada Patimokkha" dibacakan Buddha pada saat perayaan:',
      options: ['Magha Puja', 'Asadha', 'Waisak', 'Kathina'],
      correctOptionIndex: 0,
      explanation: 'Ovada Patimokkha disabdayakan saat Magha Puja.',
    ),
    QuestionItem(
      id: 'pab_039',
      questionText: 'Hari Raya persembahan jubah dan dana kebutuhan pokok kepada para Bhikkhu setelah selesai masa Vassa dinamakan:',
      options: ['Kathina', 'Waisak', 'Asadha', 'Uposatha'],
      correctOptionIndex: 0,
      explanation: 'Kathina adalah masa berderma jubah setelah Vassa.',
    ),
    QuestionItem(
      id: 'pab_040',
      questionText: 'Masa retret berdiam diri selama 3 bulan musim hujan bagi Sangha Bhikkhu dinamakan masa:',
      options: ['Vassa', 'Kathina', 'Pabbajja', 'Upasampada'],
      correctOptionIndex: 0,
      explanation: 'Vassa adalah retret 3 bulan musim hujan.',
    ),
    QuestionItem(
      id: 'pab_041',
      questionText: 'Tiga Perlindungan suci (Tiratana / Triratna) tempat Umat Buddhis bernaung terdiri dari Buddha, Dhamma, dan:',
      options: ['Sangha', 'Bodhisattva', 'Arhat', 'Sila'],
      correctOptionIndex: 0,
      explanation: 'Tiratana: Buddha (Guru), Dhamma (Ajaran), Sangha (Komunitas Suci).',
    ),
    QuestionItem(
      id: 'pab_042',
      questionText: 'Ungkapan penghormatan dan pembacaan formula Tisarana diawali dengan kalimat bahasa Pali:',
      options: ['Namo Tassa Bhagavato Arahato Samma Sambuddhasa', 'Buddham Saranam Gacchami', 'Sabbe Satta Bhavantu Sukhitatta', 'Sadhu Sadhu Sadhu'],
      correctOptionIndex: 0,
      explanation: 'Vandana diawali "Namo Tassa..."',
    ),
    QuestionItem(
      id: 'pab_043',
      questionText: 'Kalimat pemancar cinta kasih suci "Semoga Semua Makhluk Hidup Berbahagia" dalam bahasa Pali adalah:',
      options: ['Sabbe Satta Bhavantu Sukhitatta', 'Namo Buddhaya', 'Sadhu Sadhu', 'Ehipassiko'],
      correctOptionIndex: 0,
      explanation: 'Sabbe Satta Bhavantu Sukhitatta = Semoga semua makhluk berbahagia.',
    ),
    QuestionItem(
      id: 'pab_044',
      questionText: 'Ciri ajaran Buddha yang terbuka untuk dibuktikan dan diuji kebenarannya sendiri dinamakan:',
      options: ['Ehipassiko', 'Opanayiko', 'Paccattam', 'Sanditthiko'],
      correctOptionIndex: 0,
      explanation: 'Ehipassiko = "Datang dan Buktikanlah".',
    ),
    QuestionItem(
      id: 'pab_045',
      questionText: 'Seseorang yang telah mencapai kesucian batin tingkat tertinggi dan bebas dari reinkarnasi dinamakan:',
      options: ['Arahat (Arahat)', 'Bodhisattva', 'Anagami', 'Sakadagami'],
      correctOptionIndex: 0,
      explanation: 'Arahat telah memadamkan seluruh klesha dan mencapai Nibbana.',
    ),
    QuestionItem(
      id: 'pab_046',
      questionText: 'Calon Buddha yang menunda pencapaian Nibbana pribadi demi membantu semua makhluk mencapai pembebasan dinamakan:',
      options: ['Bodhisattva (Bodhisatta)', 'Arahat', 'Sotapanna', 'Paccekabuddha'],
      correctOptionIndex: 0,
      explanation: 'Bodhisattva bertekad menolong semua makhluk terlebih dahulu.',
    ),
    QuestionItem(
      id: 'pab_047',
      questionText: 'Tingkatan kesucian pertama (pemasuk arus) yang telah memotong 3 belenggu batin dinamakan:',
      options: ['Sotapanna', 'Sakadagami', 'Anagami', 'Arahat'],
      correctOptionIndex: 0,
      explanation: 'Sotapanna adalah pemasuk arus kesucian pertama.',
    ),
    QuestionItem(
      id: 'pab_048',
      questionText: 'Tingkatan kesucian kedua di mana seseorang hanya akan lahir kembali 1 kali lagi di alam manusia dinamakan:',
      options: ['Sakadagami', 'Sotapanna', 'Anagami', 'Arahat'],
      correctOptionIndex: 0,
      explanation: 'Sakadagami = Kembali satu kali lagi.',
    ),
    QuestionItem(
      id: 'pab_049',
      questionText: 'Tingkatan kesucian ketiga di mana seseorang tidak akan lahir kembali di alam indrawi dinamakan:',
      options: ['Anagami', 'Sotapanna', 'Sakadagami', 'Arahat'],
      correctOptionIndex: 0,
      explanation: 'Anagami = Tidak kembali lagi ke alam indrawi.',
    ),
    QuestionItem(
      id: 'pab_050',
      questionText: 'Orang yang mencapai pencerahan sendiri tanpa guru namun tidak mengajarkan ilmunya kepada orang lain disebut:',
      options: ['Paccekabuddha', 'Samma Sambuddha', 'Savakabuddha', 'Bodhisattva'],
      correctOptionIndex: 0,
      explanation: 'Paccekabuddha mencapai pencerahan sendiri tanpa membabarkan ajaran.',
    ),
    QuestionItem(
      id: 'pab_051',
      questionText: 'Buddha Agung yang mencapai Pencerahan Sempurna sendiri dan membabarkan ajaran Dhamma kepada dunia dinamakan:',
      options: ['Samma Sambuddha', 'Paccekabuddha', 'Savakabuddha', 'Arahat'],
      correctOptionIndex: 0,
      explanation: 'Samma Sambuddha adalah Buddha Yang Maha Sempurna.',
    ),
    QuestionItem(
      id: 'pab_052',
      questionText: 'Buddha masa depan yang akan datang membabarkan Dhamma di bumi dinamakan Buddha:',
      options: ['Maitreya (Metteyya)', 'Amitabha', 'Dipankara', 'Vipassi'],
      correctOptionIndex: 0,
      explanation: 'Buddha Maitreya adalah Buddha masa akan datang.',
    ),
    QuestionItem(
      id: 'pab_053',
      questionText: 'Dua mazhab / tradisi terbesar Agama Buddha di dunia adalah Theravada dan:',
      options: ['Mahayana', 'Vajrayana', 'Zen', 'Tantrayana'],
      correctOptionIndex: 0,
      explanation: 'Theravada dan Mahayana adalah dua tradisi utama.',
    ),
    QuestionItem(
      id: 'pab_054',
      questionText: 'Tradisi peninggalan ajaran para sesepuh kuno yang populer di Asia Tenggara (Thailand, Myanmar, Sri Lanka) adalah:',
      options: ['Theravada', 'Mahayana', 'Vajrayana', 'Zen'],
      correctOptionIndex: 0,
      explanation: 'Theravada mengacu pada Ajaran Para Sesepuh ( Elders ).',
    ),
    QuestionItem(
      id: 'pab_055',
      questionText: 'Tradisi "Kendaraan Besar" yang berkembang pesat di Tiongkok, Jepang, Korea, dan Vietnam adalah:',
      options: ['Mahayana', 'Theravada', 'Hinayana', 'Sthaviravada'],
      correctOptionIndex: 0,
      explanation: 'Mahayana berarti Kendaraan Besar.',
    ),
    QuestionItem(
      id: 'pab_056',
      questionText: 'Tradisi "Kendaraan Intan / Kilat" yang berkembang pesat di Tibet dan Nepal dinamakan:',
      options: ['Vajrayana / Tantrayana', 'Theravada', 'Mahayana', 'Zen'],
      correctOptionIndex: 0,
      explanation: 'Vajrayana adalah aliran kendaraan intan.',
    ),
    QuestionItem(
      id: 'pab_057',
      questionText: 'Kompleks Candi Buddha terbesar di dunia yang dibangun oleh Dinasti Syailendra di Magelang Indonesia adalah:',
      options: ['Candi Borobudur', 'Candi Prambanan', 'Candi Sewu', 'Candi Mendut'],
      correctOptionIndex: 0,
      explanation: 'Candi Borobudur dibangun abad ke-8/9 oleh Dinasti Syailendra.',
    ),
    QuestionItem(
      id: 'pab_058',
      questionText: 'Tiga tingkatan alam semesta menurut kosmologi Candi Borobudur terdiri dari Kamadhatu, Rupadhatu, dan:',
      options: ['Arupadhatu', 'Nirvana', 'Swargaloka', 'Bhur Loka'],
      correctOptionIndex: 0,
      explanation: 'Struktur Borobudur: Kamadhatu (bawah), Rupadhatu (tengah), Arupadhatu (atas).',
    ),
    QuestionItem(
      id: 'pab_059',
      questionText: 'Upacara pentahbisan seorang samanera/samaneri muda menjadi calon bhikkhu dinamakan upacara:',
      options: ['Pabbajja', 'Upasampada', 'Kathina', 'Waisak'],
      correctOptionIndex: 0,
      explanation: 'Pabbajja adalah pentahbisan menjadi Samanera.',
    ),
    QuestionItem(
      id: 'pab_060',
      questionText: 'Upacara pentahbisan penuh seorang Samanera menjadi seorang Bhikkhu dinamakan upacara:',
      options: ['Upasampada', 'Pabbajja', 'Visudhi', 'Uposatha'],
      correctOptionIndex: 0,
      explanation: 'Upasampada adalah pentahbisan penuh kebhikkhuan.',
    ),
    QuestionItem(
      id: 'pab_061',
      questionText: 'Pengikraran diri menjadi umat perumah tangga (Upasaka/Upasika) dinamakan upacara:',
      options: ['Visudhi / Upasaka-Upasika', 'Pabbajja', 'Upasampada', 'Katemba'],
      correctOptionIndex: 0,
      explanation: 'Visudhi adalah pengikraran janji setia pada Tiratana.',
    ),
    QuestionItem(
      id: 'pab_062',
      questionText: 'Perempuan yang menjalani kehidupan suci membiara dalam ajaran Buddha dinamakan:',
      options: ['Bhikkhuni', 'Samanera', 'Anagarini', 'Upasika'],
      correctOptionIndex: 0,
      explanation: 'Bhikkhuni adalah biarawati Buddhis.',
    ),
    QuestionItem(
      id: 'pab_063',
      questionText: 'Nama ibu kandung Pangeran Siddharta Gautama yang meninggal 7 hari setelah melahirkan adalah:',
      options: ['Ratu Maha Maya', 'Maha Pajapati Gotami', 'Yasodhara', 'Gopa'],
      correctOptionIndex: 0,
      explanation: 'Ratu Maha Maya adalah ibu kandung Siddharta.',
    ),
    QuestionItem(
      id: 'pab_064',
      questionText: 'Ibu asuh yang membesarkan Siddharta Gautama dan kemudian menjadi Bhikkhuni pertama adalah:',
      options: ['Maha Pajapati Gotami', 'Ratu Maya', 'Yasodhara', 'Patacara'],
      correctOptionIndex: 0,
      explanation: 'Maha Pajapati Gotami mendirikan Sangha Bhikkhuni.',
    ),
    QuestionItem(
      id: 'pab_065',
      questionText: 'Istri dari Pangeran Siddharta Gautama bernama:',
      options: ['Putri Yasodhara (Bhimba)', 'Ratu Maya', 'Gotami', 'Sujata'],
      correctOptionIndex: 0,
      explanation: 'Putri Yasodhara adalah istri Siddharta.',
    ),
    QuestionItem(
      id: 'pab_066',
      questionText: 'Putra tunggal dari Pangeran Siddharta Gautama bernama:',
      options: ['Rahula', 'Ananda', 'Devadatta', 'Nanda'],
      correctOptionIndex: 0,
      explanation: 'Rahula adalah putra Siddharta Gautama.',
    ),
    QuestionItem(
      id: 'pab_067',
      questionText: 'Empat Peristiwa Empat Penglihatan yang dilihat Pangeran Siddharta di luar istana adalah melihat orang tua, orang sakit, orang mati, dan:',
      options: ['Seorang Pertapa Suci', 'Seorang Raja', 'Seorang Bayi', 'Seorang Pedagang'],
      correctOptionIndex: 0,
      explanation: 'Penglihatan ke-4 adalah seorang pertapa tenang yang menginspirasi pembebasan.',
    ),
    QuestionItem(
      id: 'pab_068',
      questionText: 'Saudara sepupu Siddharta yang setia menjadi pembantu pribadi dan memiliki daya ingat luar biasa menghafal Sutta adalah:',
      options: ['Bhikkhu Ananda', 'Bhikkhu Sariputta', 'Bhikkhu Moggallana', 'Bhikkhu Kassapa'],
      correctOptionIndex: 0,
      explanation: 'Ananda adalah bendahara Dhamma dengan ingatan luar biasa.',
    ),
    QuestionItem(
      id: 'pab_069',
      questionText: 'Dua siswa utama Buddha Gautama yang terkenal paling bijaksana dan berkesaktian tinggi adalah:',
      options: ['Sariputta dan Moggallana', 'Ananda dan Upali', 'Kassapa dan Anuruddha', 'Kondanna dan Punna'],
      correctOptionIndex: 0,
      explanation: 'Sariputta (kebijaksanaan) dan Moggallana (kesaktian).',
    ),
    QuestionItem(
      id: 'pab_070',
      questionText: 'Siswa utama Buddha yang ahli dalam menghafal dan menguasai Vinaya (peraturan) adalah:',
      options: ['Bhikkhu Upali', 'Bhikkhu Ananda', 'Bhikkhu Sariputta', 'Bhikkhu Rahula'],
      correctOptionIndex: 0,
      explanation: 'Upali membacakan ulang aturan Vinaya pada Konsili Pertama.',
    ),
    QuestionItem(
      id: 'pab_071',
      questionText: 'Siswa pertama yang mencapai kesucian Arahat saat mendengar Khotbah Pertama Buddha adalah:',
      options: ['Kondanna (Anna Kondanna)', 'Bhaddiya', 'Vappa', 'Mahanama'],
      correctOptionIndex: 0,
      explanation: 'Anna Kondanna pertama memahami Dhamma.',
    ),
    QuestionItem(
      id: 'pab_072',
      questionText: 'Wanita dermawan penyedia bubur susu kental bagi Siddharta sebelum Pencerahan bernama:',
      options: ['Sujata', 'Visakha', 'Mallika', 'Amrapali'],
      correctOptionIndex: 0,
      explanation: 'Sujata mempersembahkan kheer/bubur susu.',
    ),
    QuestionItem(
      id: 'pab_073',
      questionText: 'Donatur perumah tangga wanita terbesar (Upasika) pada zaman Buddha bernama:',
      options: ['Visakha (Migaramata)', 'Sujata', 'Ksema', 'Uppalavanna'],
      correctOptionIndex: 0,
      explanation: 'Visakha membangun vihara Pubbarama.',
    ),
    QuestionItem(
      id: 'pab_074',
      questionText: 'Donatur perumah tangga pria terbesar (Upasaka) yang mempersembahkan Vihara Jetavana di Savatthi bernama:',
      options: ['Anathapindika (Sudatta)', 'Bimbisara', 'Pasenadi', 'Jivaka'],
      correctOptionIndex: 0,
      explanation: 'Anathapindika membelikan tanah Vihara Jetavana.',
    ),
    QuestionItem(
      id: 'pab_075',
      questionText: 'Tabib pribadi Buddha Gautama dan Sangha yang sangat terkenal adalah:',
      options: ['Jivaka Komarabhacca', 'Charaka', 'Susruta', 'Nagarjuna'],
      correctOptionIndex: 0,
      explanation: 'Jivaka adalah dokter terkenal di Magadha.',
    ),
    QuestionItem(
      id: 'pab_076',
      questionText: 'Raja penguasa Magadha yang menyokong penuh pergerakan awal ajaran Buddha dan mempersembahkan Hutan Bambu (Veluvana) adalah:',
      options: ['Raja Bimbisara', 'Raja Ajatasattu', 'Raja Asoka', 'Raja Milinda'],
      correctOptionIndex: 0,
      explanation: 'Raja Bimbisara menghadiahkan Veluvana Arama.',
    ),
    QuestionItem(
      id: 'pab_077',
      questionText: 'Raja Agung Maurya India yang menyebarkan ajaran Buddha ke seluruh Asia melalui Prasasti Pilar Batu adalah:',
      options: ['Raja Asoka (Ashoka the Great)', 'Raja Kanishka', 'Raja Chandragupta', 'Raja Harsha'],
      correctOptionIndex: 0,
      explanation: 'Raja Asoka menyebarkan Dhamma pasca Perang Kalinga.',
    ),
    QuestionItem(
      id: 'pab_078',
      questionText: 'Tempat wafat dan Parinibbana Buddha Gautama di antara dua pohon sal ikembar adalah di kota:',
      options: ['Kusinara (Kushinagar)', 'Lumbini', 'Bodh Gaya', 'Sarnath'],
      correctOptionIndex: 0,
      explanation: 'Buddha Parinibbana di Kusinara pada usia 80 tahun.',
    ),
    QuestionItem(
      id: 'pab_079',
      questionText: 'Tempat kelahiran Pangeran Siddharta Gautama adalah di taman:',
      options: ['Taman Lumbini', 'Sarnath', 'Gaya', 'Vesali'],
      correctOptionIndex: 0,
      explanation: 'Siddharta lahir di Taman Lumbini (Nepal).',
    ),
    QuestionItem(
      id: 'pab_080',
      questionText: 'Empat Tempat Suci Utama peziarahan Buddhis meliputi Lumbini, Bodh Gaya, Sarnath, dan:',
      options: ['Kusinara', 'Nalanda', 'Rajagaha', 'Savatthi'],
      correctOptionIndex: 0,
      explanation: 'Kusinara tempat Parinibbana Buddha.',
    ),
    QuestionItem(
      id: 'pab_081',
      questionText: 'Khotbah mengenai Nilai Berkah Utama dalam kehidupan sehari-hari terangkum dalam Sutta:',
      options: ['Mangala Sutta', 'Karaniya Metta Sutta', 'Ratana Sutta', 'Sigalovada Sutta'],
      correctOptionIndex: 0,
      explanation: 'Mangala Sutta memuat 38 Berkah Utama.',
    ),
    QuestionItem(
      id: 'pab_082',
      questionText: 'Khotbah wewanti etika hubungan perumah tangga dan masyarakat (Etika Sosial) terdapat dalam Sutta:',
      options: ['Sigalovada Sutta', 'Mangala Sutta', 'Metta Sutta', 'Metta Sutta'],
      correctOptionIndex: 0,
      explanation: 'Sigalovada Sutta adalah panduan etika sosial perumah tangga.',
    ),
    QuestionItem(
      id: 'pab_083',
      questionText: 'Pembacaan bait-bait doa perlindungan dan wacana suci dinamakan pembacaan:',
      options: ['Paritta / Sutra', 'Mantra', 'Sloka', 'Kidung'],
      correctOptionIndex: 0,
      explanation: 'Paritta adalah ayat-ayat perlindungan suci Pali.',
    ),
    QuestionItem(
      id: 'pab_084',
      questionText: 'Penyerahan jasa kebajikan amalan kepada para leluhur atau makhluk lain dinamakan:',
      options: ['Pattidana', 'Pattanumodana', 'Dana', 'Sila'],
      correctOptionIndex: 0,
      explanation: 'Pattidana adalah limpahan jasa kebajikan.',
    ),
    QuestionItem(
      id: 'pab_085',
      questionText: 'Sikap gembira menerima limpahan jasa kebajikan dari orang lain dinamakan:',
      options: ['Pattanumodana', 'Pattidana', 'Puja', 'Vandana'],
      correctOptionIndex: 0,
      explanation: 'Pattanumodana adalah merayakan/turut gembira atas limpahan jasa.',
    ),
    QuestionItem(
      id: 'pab_086',
      questionText: 'Struktur bangunan kubah relik suci peninggalan Buddha atau para Arahat dinamakan:',
      options: ['Stupa', 'Candi', 'Pagoda', 'Vihara'],
      correctOptionIndex: 0,
      explanation: 'Stupa menyimpan relik suci (Dhatu).',
    ),
    QuestionItem(
      id: 'pab_087',
      questionText: 'Sisa pembakaran jenazah Buddha atau Arahat berupa butiran kristal suci dinamakan:',
      options: ['Relik (Dhatu)', 'Stupa', 'Bija', 'Sarira'],
      correctOptionIndex: 0,
      explanation: 'Dhatu / Relik adalah sisa kristal suci peninggalan orang suci.',
    ),
    QuestionItem(
      id: 'pab_088',
      questionText: 'Simbol Roda Putaran Hukum Dhamma yang memiliki 8 jari-jari melambangkan:',
      options: ['Jalan Mulia Berunsur Delapan', 'Delapan Kebenaran', 'Delapan Sila', 'Delapan Lokadhamma'],
      correctOptionIndex: 0,
      explanation: '8 jari-jari Dhammacakka melambangkan Jalan Mulia Berunsur 8.',
    ),
    QuestionItem(
      id: 'pab_089',
      questionText: 'Simbol Bunga Teratai (Lotus) dalam ajaran Buddha melambangkan:',
      options: ['Kesucian batin yang tumbuh mekar dari lumpur duniawi', 'Keabadian', 'Kekayaan', 'Kekuatan'],
      correctOptionIndex: 0,
      explanation: 'Lotus tumbuh murni dan suci di atas lumpur.',
    ),
    QuestionItem(
      id: 'pab_090',
      questionText: 'Warna Bendera Buddhis (Enam Warna Sinar Buddha / Chabbannaransi) meliputi Biru, Kuning, Merah, Putih, Jingga, dan:',
      options: ['Kombinasi Kelima Warna', 'Hijau', 'Hitam', 'Cokelat'],
      correctOptionIndex: 0,
      explanation: 'Warna ke-6 adalah Prabhasvara (Gabungan lima warna).',
    ),
    QuestionItem(
      id: 'pab_091',
      questionText: 'Prinsip memberi persembahan tulus (Derma) tanpa pamrih dinamakan:',
      options: ['Dana (Dana Paramita)', 'Sila', 'Nekkhamma', 'Khanti'],
      correctOptionIndex: 0,
      explanation: 'Dana adalah kebajikan memberi/berderma.',
    ),
    QuestionItem(
      id: 'pab_092',
      questionText: 'Kesabaran yang tak tergoyahkan dalam menghadapi kesukaran dinamakan:',
      options: ['Khanti (Khanti Paramita)', 'Viriya', 'Panna', 'Saccha'],
      correctOptionIndex: 0,
      explanation: 'Khanti adalah kesabaran luhur.',
    ),
    QuestionItem(
      id: 'pab_093',
      questionText: 'Semangat pantang menyerah dan daya upaya benar dinamakan:',
      options: ['Viriya (Viriya Paramita)', 'Khanti', 'Adhitthan', 'Upekkha'],
      correctOptionIndex: 0,
      explanation: 'Viriya adalah keuletan dan semangat.',
    ),
    QuestionItem(
      id: 'pab_094',
      questionText: 'Pelepasan keduniawian dan kesenangan indrawi dinamakan:',
      options: ['Nekkhamma', 'Dana', 'Metta', 'Karuna'],
      correctOptionIndex: 0,
      explanation: 'Nekkhamma adalah pelepasan dari kemelekatan.',
    ),
    QuestionItem(
      id: 'pab_095',
      questionText: 'Ketetapan hati dan tekad bulat yang tak tergoyahkan dinamakan:',
      options: ['Adhitthana', 'Saccha', 'Metta', 'Khanti'],
      correctOptionIndex: 0,
      explanation: 'Adhitthana adalah tekad kuat membaja.',
    ),
    QuestionItem(
      id: 'pab_096',
      questionText: 'Kesetiaan pada kebenaran dan kejujuran dinamakan:',
      options: ['Saccha (Sacca)', 'Adhitthana', 'Dana', 'Sila'],
      correctOptionIndex: 0,
      explanation: 'Saccha adalah kebenaran/kejujuran.',
    ),
    QuestionItem(
      id: 'pab_097',
      questionText: 'Perhimpunan Sangha pertama di Indonesia pada masa modern dipelopori oleh Maha Upasaka / Bhikkhu Ashin Jinarakkhita dinamakan:',
      options: ['Maha Bhikkhu Ashin Jinarakkhita (Bante Tejapunno)', 'Bante Narada', 'Bante Uttamo', 'Bante Dhammiko'],
      correctOptionIndex: 0,
      explanation: 'Bante Ashin Jinarakkhita melopori kebangkitan kembali Buddhis Indonesia.',
    ),
    QuestionItem(
      id: 'pab_098',
      questionText: 'Tempat ibadah dan pertemuan kegiatan Umat Buddhis dinamakan:',
      options: ['Vihara / Cetiya', 'Pura', 'Klenteng', 'Gereja'],
      correctOptionIndex: 0,
      explanation: 'Vihara / Cetiya adalah tempat ibadah Buddhis.',
    ),
    QuestionItem(
      id: 'pab_099',
      questionText: 'Salam penghormatan antar Umat Buddhis yang berarti "Terpujilah Tuhan / Buddha" adalah:',
      options: ['Namo Buddhaya', 'Om Swastyastu', 'Salam Virtu', 'Namo Amitabha'],
      correctOptionIndex: 0,
      explanation: 'Namo Buddhaya = Terpujilah Buddha.',
    ),
    QuestionItem(
      id: 'pab_100',
      questionText: 'Kata seruan penerimaan yang diucapkan 3 kali untuk mengamini doa kebajikan "Semoga Demikianlah Yang Terjadi" adalah:',
      options: ['Sadhu... Sadhu... Sadhu...', 'Amin', 'Swaha', 'Tathastu'],
      correctOptionIndex: 0,
      explanation: 'Sadhu Sadhu Sadhu = Baik sekali / Semoga demikian.',
    ),
  ];
}
