import '../tes_seleksi_model.dart';

List<QuestionItem> getPerbankanKeuanganQuestions() {
  return const [
    QuestionItem(
      id: 'pbk_001',
      questionText: 'Rasio kecukupan modal minimun bank untuk menanggung risiko kerugian dinamakan CAR yaitu:',
      options: ['Capital Adequacy Ratio', 'Credit Assessment Rate', 'Capital Allocation Ratio', 'Cash Asset Ratio'],
      correctOptionIndex: 0,
      explanation: 'CAR mengukur ketahanan modal bank terhadap Aktiva Tertimbang Menurut Risiko (ATMR).',
    ),
    QuestionItem(
      id: 'pbk_002',
      questionText: 'Rasio yang membandingkan total kredit yang disalurkan bank terhadap total dana pihak ketiga (DPK) dinamakan:',
      options: ['LDR (Loan to Deposit Ratio)', 'NPL (Non-Performing Loan)', 'ROA (Return on Assets)', 'NIM (Net Interest Margin)'],
      correctOptionIndex: 0,
      explanation: 'LDR mengukur tingkat likuiditas perbankan dalam menyalurkan dana DPK menjadi kredit.',
    ),
    QuestionItem(
      id: 'pbk_003',
      questionText: 'Rasio kredit bermasalah atau menunggak pembayaran dibanding total kredit dinamakan:',
      options: ['NPL (Non-Performing Loan)', 'LDR', 'CAR', 'BOPO'],
      correctOptionIndex: 0,
      explanation: 'NPL mengindikasikan tingkat risiko kegagalan pengembalian pinjaman debitur.',
    ),
    QuestionItem(
      id: 'pbk_004',
      questionText: 'Batas toleransi maksimal rasio NPL netto perbankan yang ditetapkan Bank Indonesia / OJK adalah:',
      options: ['Maksimal 5%', 'Maksimal 10%', 'Maksimal 2%', 'Maksimal 15%'],
      correctOptionIndex: 0,
      explanation: 'Batas ambang NPL aman perbankan adalah di bawah 5%.',
    ),
    QuestionItem(
      id: 'pbk_005',
      questionText: 'Rasio efisiensi operasional bank yang membandingkan Beban Operasional terhadap Pendapatan Operasional dinamakan:',
      options: ['BOPO', 'NIM', 'ROE', 'CAR'],
      correctOptionIndex: 0,
      explanation: 'BOPO mengukur tingkat efisiensi manajemen operasional bank.',
    ),
    QuestionItem(
      id: 'pbk_006',
      questionText: 'Persentase selisih antara bunga kredit yang diterima bank dengan bunga simpanan yang dibayarkan ke nasabah dinamakan:',
      options: ['NIM (Net Interest Margin)', 'Spread Rate', 'Yield', 'Capital Gain'],
      correctOptionIndex: 0,
      explanation: 'NIM mencerminkan margin keuntungan bersih bank dari pendapatan bunga.',
    ),
    QuestionItem(
      id: 'pbk_007',
      questionText: 'Simpanan masyarakat di bank yang penarikannya dapat dilakukan setiap saat menggunakan cek atau bilyet giro dinamakan:',
      options: ['Giro (Demand Deposit)', 'Tabungan', 'Deposito Berjangka', 'Sertifikat Deposito'],
      correctOptionIndex: 0,
      explanation: 'Giro adalah simpanan transaksi likuid utama bagi badan usaha.',
    ),
    QuestionItem(
      id: 'pbk_008',
      questionText: 'Simpanan bank yang penarikannya hanya dapat dilakukan pada jangka waktu tertentu sesuai kesepakatan dinamakan:',
      options: ['Deposito Berjangka (Time Deposit)', 'Giro', 'Tabungan Harian', 'Reksa Dana'],
      correctOptionIndex: 0,
      explanation: 'Deposito memiliki jatuh tempo 1, 3, 6, atau 12 bulan dengan imbal bunga lebih tinggi.',
    ),
    QuestionItem(
      id: 'pbk_009',
      questionText: 'Surat berharga bukti kepemilikan modal atas suatu perusahaan perseroan terbatas dinamakan:',
      options: ['Saham (Stock / Equity)', 'Obligasi', 'Waran', 'Opsi'],
      correctOptionIndex: 0,
      explanation: 'Pemegang saham memiliki hak atas dividen dan suara dalam RUPS.',
    ),
    QuestionItem(
      id: 'pbk_010',
      questionText: 'Surat utang jangka menengah-panjang yang diterbitkan perusahaan atau negara untuk memperoleh pinjaman modal dinamakan:',
      options: ['Obligasi (Bond)', 'Saham', 'Reksa Dana', 'Right Issue'],
      correctOptionIndex: 0,
      explanation: 'Obligasi memberikan kupon imbal hasil berkala dan pengembalian pokok saat jatuh tempo.',
    ),
    QuestionItem(
      id: 'pbk_011',
      questionText: 'Pembayaran bagian keuntungan perusahaan yang dibagikan kepada para pemegang saham dinamakan:',
      options: ['Dividen', 'Capital Gain', 'Kupon', 'Royalti'],
      correctOptionIndex: 0,
      explanation: 'Dividen dibagikan berdasarkan keputusan Rapat Umum Pemegang Saham (RUPS).',
    ),
    QuestionItem(
      id: 'pbk_012',
      questionText: 'Keuntungan dari selisih harga jual saham yang lebih tinggi dibanding harga beli dinamakan:',
      options: ['Capital Gain', 'Capital Loss', 'Dividen', 'Yield'],
      correctOptionIndex: 0,
      explanation: 'Capital Gain diperoleh saat menjual aset di atas harga beli.',
    ),
    QuestionItem(
      id: 'pbk_013',
      questionText: 'Kerugian akibat harga jual aset saham lebih rendah daripada harga beli dinamakan:',
      options: ['Capital Loss', 'Capital Gain', 'Default', 'Haircut'],
      correctOptionIndex: 0,
      explanation: 'Capital Loss terjadi saat aset dilepas pada harga di bawah harga modal.',
    ),
    QuestionItem(
      id: 'pbk_014',
      questionText: 'Wadah yang menghimpun dana masyarakat untuk diinvestasikan ke dalam portofolio efek oleh Manajer Investasi dinamakan:',
      options: ['Reksa Dana (Mutual Fund)', 'Bank Kustodian', 'Pialang', 'Multifinance'],
      correctOptionIndex: 0,
      explanation: 'Reksa Dana dikelola oleh Manajer Investasi (MI) profesional.',
    ),
    QuestionItem(
      id: 'pbk_015',
      questionText: 'Lembaga keuangan perbankan yang bertugas menyimpan dan mengadministrasikan sertifikat efek Reksa Dana dinamakan:',
      options: ['Bank Kustodian', 'Wali Amanat', 'Underwriter', 'Bursa Efek'],
      correctOptionIndex: 0,
      explanation: 'Bank Kustodian mengamankan fisik kekayaan portofolio reksa dana.',
    ),
    QuestionItem(
      id: 'pbk_016',
      questionText: 'Indeks utama pergerakan harga seluruh saham yang tercatat di Bursa Efek Indonesia (BEI) dinamakan:',
      options: ['IHSG (Indeks Harga Saham Gabungan)', 'LQ45', 'IDX30', 'JII'],
      correctOptionIndex: 0,
      explanation: 'IHSG mengukur tren pergerakan pasar modal Indonesia.',
    ),
    QuestionItem(
      id: 'pbk_017',
      questionText: 'Indeks pasar di BEI yang mengukur kinerja 45 saham dengan likuiditas tinggi dan kapitalisasi besar dinamakan:',
      options: ['LQ45', 'IHSG', 'Kompas100', 'Jakarta Islamic Index'],
      correctOptionIndex: 0,
      explanation: 'LQ45 berisi 45 saham terlikuid terpilih.',
    ),
    QuestionItem(
      id: 'pbk_018',
      questionText: 'Pasar tempat saham perusahaan pertama kali dijual dan ditawarkan kepada publik (IPO) dinamakan:',
      options: ['Pasar Perdana (Primary Market)', 'Pasar Sekunder', 'Pasar Uang', 'Pasar Negosiasi'],
      correctOptionIndex: 0,
      explanation: 'Pasar Perdana adalah proses jual saham langsung dari penjamin emisi ke investor IPO.',
    ),
    QuestionItem(
      id: 'pbk_019',
      questionText: 'Pasar tempat transaksi jual-beli saham antar sesama investor setelah masa IPO selesai dinamakan:',
      options: ['Pasar Sekunder (Secondary Market)', 'Pasar Perdana', 'Pasar Tunai', 'Pasar Kas'],
      correctOptionIndex: 0,
      explanation: 'Pasar Sekunder berlangsung di bursa efek harian.',
    ),
    QuestionItem(
      id: 'pbk_020',
      questionText: 'Singkatan IPO dalam proses penawaran umum saham perdana adalah:',
      options: ['Initial Public Offering', 'Internal Product Option', 'International Portfolio Obligation', 'Integrated Public Operation'],
      correctOptionIndex: 0,
      explanation: 'IPO menandai go-public perusahan di bursa.',
    ),
    QuestionItem(
      id: 'pbk_021',
      questionText: 'Perusahaan yang bertugas menjamin penjualan saham perusahaan yang go-public dinamakan:',
      options: ['Penjamin Emisi Efek (Underwriter)', 'Manajer Investasi', 'Broker', 'Dealer'],
      correctOptionIndex: 0,
      explanation: 'Underwriter menjamin kelancaran emisi saham IPO.',
    ),
    QuestionItem(
      id: 'pbk_022',
      questionText: 'Penetapan harga obligasi yang dijual di atas nilai nominalnya (Par Value) dinamakan obligasi dijual secara:',
      options: ['Premium (At Premium)', 'Discount', 'Par', 'Yield'],
      correctOptionIndex: 0,
      explanation: 'Premium terjadi saat harga jual obligasi > nilai nominal.',
    ),
    QuestionItem(
      id: 'pbk_023',
      questionText: 'Penetapan harga obligasi di bawah nilai nominalnya dinamakan obligasi dijual secara:',
      options: ['Discount (At Discount)', 'Premium', 'Par', 'At Cost'],
      correctOptionIndex: 0,
      explanation: 'Discount terjadi saat harga obligasi < nilai nominal.',
    ),
    QuestionItem(
      id: 'pbk_024',
      questionText: 'Tingkat pengembalian hasil tahunan obligasi yang dihitung sampai jatuh tempo dinamakan:',
      options: ['YTM (Yield to Maturity)', 'Current Yield', 'Coupon Rate', 'Discount Rate'],
      correctOptionIndex: 0,
      explanation: 'YTM mencerminkan total return obligasi jika dipegang hingga jatuh tempo.',
    ),
    QuestionItem(
      id: 'pbk_025',
      questionText: 'Obligasi yang diterbitkan oleh Pemerintah Republik Indonesia untuk investor ritel individu dinamakan:',
      options: ['ORI (Obligasi Negara Ritel)', 'Sukuk Ritel', 'SBN', 'Corporate Bond'],
      correctOptionIndex: 0,
      explanation: 'ORI adalah instrumen Surat Berharga Negara ritel.',
    ),
    QuestionItem(
      id: 'pbk_026',
      questionText: 'Obligasi berbasis prinsip syariah yang menerbitkan sertifikat kepemilikan aset dinamakan:',
      options: ['Sukuk', 'Obligasi Konvensional', 'Commercial Paper', 'Promissory Note'],
      correctOptionIndex: 0,
      explanation: 'Sukuk mengandalkan aset underlying berprinsip syariah.',
    ),
    QuestionItem(
      id: 'pbk_027',
      questionText: 'Penilaian kelayakan anggaran investasi modal perusahaan berbasis nilai sekarang bersih (Present Value) dinamakan:',
      options: ['NPV (Net Present Value)', 'IRR', 'Payback Period', 'ARR'],
      correctOptionIndex: 0,
      explanation: 'NPV = Total PV Arus Kas Masuk - Investasi Awal.',
    ),
    QuestionItem(
      id: 'pbk_028',
      questionText: 'Kriteria keputusan investasi: proyek dianggap layak dan menguntungkan apabila nilai NPV adalah:',
      options: ['NPV > 0 (Positif)', 'NPV = 0', 'NPV < 0', 'NPV Negatif'],
      correctOptionIndex: 0,
      explanation: 'NPV positif menunjukkan proyek menghasilkan nilai tambah di atas diskonto.',
    ),
    QuestionItem(
      id: 'pbk_029',
      questionText: 'Tingkat suku bunga diskonto yang membuat nilai NPV tepat sama dengan nol dinamakan:',
      options: ['IRR (Internal Rate of Return)', 'WACC', 'Cost of Debt', 'Discount Rate'],
      correctOptionIndex: 0,
      explanation: 'IRR menggambarkan tingkat hasil pengembalian internal proyek.',
    ),
    QuestionItem(
      id: 'pbk_030',
      questionText: 'Metode capital budgeting yang mengukur jangka waktu mengembalikan seluruh modal awal investasi dinamakan:',
      options: ['Payback Period', 'NPV', 'IRR', 'Profitability Index'],
      correctOptionIndex: 0,
      explanation: 'Payback Period menghitung jumlah tahun hingga pengembalian modal.',
    ),
    QuestionItem(
      id: 'pbk_031',
      questionText: 'Biaya rata-rata tertimbang dari seluruh sumber modal perusahaan (utang dan ekuitas) dinamakan:',
      options: ['WACC (Weighted Average Cost of Capital)', 'CAPM', 'Beta', 'Cost of Equity'],
      correctOptionIndex: 0,
      explanation: 'WACC adalah patokan minimum return yang harus dihasilkan investasi perusahaan.',
    ),
    QuestionItem(
      id: 'pbk_032',
      questionText: 'Model penetapan harga aset modal untuk menghitung return ekspektasi ekuitas berbasis risiko sistematis dinamakan:',
      options: ['CAPM (Capital Asset Pricing Model)', 'Black-Scholes', 'APT', 'WACC'],
      correctOptionIndex: 0,
      explanation: 'CAPM formula: E(Ri) = Rf + Beta * (Rm - Rf).',
    ),
    QuestionItem(
      id: 'pbk_033',
      questionText: 'Koefisien "Beta" dalam model CAPM mengukur tingkat:',
      options: ['Risiko Sistematis (Risiko Pasar / Market Risk)', 'Risiko Unspesifik', 'Tingkat Inflasi', 'Risiko Kredit'],
      correctOptionIndex: 0,
      explanation: 'Beta > 1 menandakan saham lebih sensitif dan volatil dibanding pasar.',
    ),
    QuestionItem(
      id: 'pbk_034',
      questionText: 'Risiko spesifik perusahaan yang dapat dihilangkan melalui diversifikasi portofolio dinamakan:',
      options: ['Risiko Unsystematic (Unsystematic Risk)', 'Risiko Systematic', 'Risiko Pasar', 'Risiko Suku Bunga'],
      correctOptionIndex: 0,
      explanation: 'Diversifikasi menyebarkan risiko spesifik saham individual.',
    ),
    QuestionItem(
      id: 'pbk_035',
      questionText: 'Prinsip manajemen portofolio investasi "Don\'t put all your eggs in one basket" merupakan prinsip:',
      options: ['Diversifikasi (Diversification)', 'Leverage', 'Hedging', 'Arbitrase'],
      correctOptionIndex: 0,
      explanation: 'Diversifikasi meminimalkan dampak kegagalan satu aset.',
    ),
    QuestionItem(
      id: 'pbk_036',
      questionText: 'Tindakan lindung nilai untuk mengeliminasi risiko kerugian akibat fluktuasi harga valas atau komoditas dinamakan:',
      options: ['Hedging', 'Speculation', 'Arbitrage', 'Short Selling'],
      correctOptionIndex: 0,
      explanation: 'Hedging memanfaatkan instrumen derivatif menutupi posisi risiko.',
    ),
    QuestionItem(
      id: 'pbk_037',
      questionText: 'Praktik memanfaatkan selisih harga instrumen yang sama di dua pasar berbeda demi keuntungan tanpa risiko dinamakan:',
      options: ['Arbitrase (Arbitrage)', 'Short Selling', 'Hedging', 'Leverage'],
      correctOptionIndex: 0,
      explanation: 'Arbitrase mengeksploitasi inefisiensi penetapan harga pasar.',
    ),
    QuestionItem(
      id: 'pbk_038',
      questionText: 'Strategi perdagangan dengan meminjam saham untuk dijual sekarang dan membelinya kembali saat harga turun dinamakan:',
      options: ['Short Selling', 'Margin Trading', 'Option Pricing', 'Buy and Hold'],
      correctOptionIndex: 0,
      explanation: 'Short Selling meraup untung dari penurunan harga saham.',
    ),
    QuestionItem(
      id: 'pbk_039',
      questionText: 'Penggunaan dana pinjaman (utang) untuk mendongkrak kapasitas nilai investasi dan return ekuitas dinamakan:',
      options: ['Financial Leverage', 'Operating Leverage', 'Margin Call', 'Capitalizing'],
      correctOptionIndex: 0,
      explanation: 'Financial Leverage memperbesar keuntungan tetapi juga memperbesar potensi risiko.',
    ),
    QuestionItem(
      id: 'pbk_040',
      questionText: 'Lembaga independen yang mengawasi seluruh aktivitas jasa keuangan di Indonesia (Perbankan, Pasar Modal, IKNB) adalah:',
      options: ['OJK (Otoritas Jasa Keuangan)', 'Bank Indonesia', 'LPS', 'Kementerian Keuangan'],
      correctOptionIndex: 0,
      explanation: 'OJK bertugas mengatur dan mengawasi sektor jasa keuangan terpadu.',
    ),
    QuestionItem(
      id: 'pbk_041',
      questionText: 'Lembaga independen yang menjamin simpanan nasabah di perbankan Indonesia dinamakan:',
      options: ['LPS (Lembaga Penjamin Simpanan)', 'OJK', 'Bank Indonesia', 'Bappebti'],
      correctOptionIndex: 0,
      explanation: 'LPS menjamin saldo simpanan nasabah bank hingga limit Rp 2 Miliar per nasabah per bank.',
    ),
    QuestionItem(
      id: 'pbk_042',
      questionText: 'Batas maksimum saldo simpanan nasabah yang dijamin oleh LPS per nasabah pada satu bank adalah:',
      options: ['Rp 2 Miliar', 'Rp 1 Miliar', 'Rp 5 Miliar', 'Rp 500 Juta'],
      correctOptionIndex: 0,
      explanation: 'LPS menjamin simpanan layak bayar hingga Rp 2 miliar.',
    ),
    QuestionItem(
      id: 'pbk_043',
      questionText: 'Tiga syarat kelayakan simpanan nasabah yang dijamin LPS (Syarat 3C) adalah:',
      options: ['Tercatat di pembukuan, Tingkat bunga tidak melebihi bunga penjaminan, Tidak melakukan tindakan merugikan bank', 'Transfer, Tunai, Giro', 'CAR, NPL, LDR', 'Cek, Bilyet, Kartu'],
      correctOptionIndex: 0,
      explanation: 'Simpanan harus memenuhi 3 kriteria kelayakan klaim LPS.',
    ),
    QuestionItem(
      id: 'pbk_044',
      questionText: 'Sistem pembayaran antarbank real-time bruto untuk transaksi bernilai besar (di atas Rp 100 Juta) di Indonesia dinamakan:',
      options: ['BI-RTGS (Real Time Gross Settlement)', 'BI-FAST', 'SKNBI', 'Clearing'],
      correctOptionIndex: 0,
      explanation: 'BI-RTGS memproses transaksi dana jumlah besar seketika.',
    ),
    QuestionItem(
      id: 'pbk_045',
      questionText: 'Infrastruktur sistem pembayaran ritel nasional yang beroperasi 24/7 secara real-time murah dari Bank Indonesia dinamakan:',
      options: ['BI-FAST', 'BI-RTGS', 'Kliring', 'SWIFT'],
      correctOptionIndex: 0,
      explanation: 'BI-FAST memfasilitasi transfer dana ritel 24/7.',
    ),
    QuestionItem(
      id: 'pbk_046',
      questionText: 'Standar nasional kode QR pembayaran digital di Indonesia yang diresmikan Bank Indonesia dinamakan:',
      options: ['QRIS (Quick Response Code Indonesian Standard)', 'GPN', 'EDC', 'NFC'],
      correctOptionIndex: 0,
      explanation: 'QRIS menyatukan seluruh kanal pembayaran scan QR.',
    ),
    QuestionItem(
      id: 'pbk_047',
      questionText: 'Jaringan komunikasi keuangan global aman antarbank internasional di seluruh dunia dinamakan:',
      options: ['SWIFT', 'FedWire', 'CHIPS', 'SEPA'],
      correctOptionIndex: 0,
      explanation: 'SWIFT menghubungkan ribuan lembaga keuangan antarnegara.',
    ),
    QuestionItem(
      id: 'pbk_048',
      questionText: 'Lembaga penyedia layanan informasi rekam jejak riwayat kredit calon debitur (Credit Score) di Indonesia adalah:',
      options: ['SLIK (Sistem Layanan Informasi Keuangan - OJK)', 'BI Checking', 'LPS', 'Kustodian'],
      correctOptionIndex: 0,
      explanation: 'SLIK OJK menggantikan fungsi BI Checking untuk memeriksa skor riwayat kredit.',
    ),
    QuestionItem(
      id: 'pbk_049',
      questionText: 'Analisis prinsip 5C dalam menilai permohonan kredit calon debitur adalah:',
      options: ['Character, Capacity, Capital, Collateral, Condition', 'Cash, Credit, Cost, Currency, Check', 'Company, Customer, Cost, CAR, CPC', 'Charge, Change, Control, Clearance, Claim'],
      correctOptionIndex: 0,
      explanation: 'Prinsip 5C adalah standar evaluasi pemberian pinjaman kredit perbankan.',
    ),
    QuestionItem(
      id: 'pbk_050',
      questionText: 'Faktor "Collateral" dalam analisis kredit 5C mengacu pada:',
      options: ['Aset Jaminan / Agunan', 'Karakter Kejujuran', 'Kemampuan Membayar', 'Kondisi Ekonomi'],
      correctOptionIndex: 0,
      explanation: 'Collateral adalah aset jaminan penjamin pinjaman.',
    ),
    QuestionItem(
      id: 'pbk_051',
      questionText: 'Akad pembiayaan syariah berbasis prinsip bagi hasil keuntungan dan kerugian antara pemilik modal dan pengelola dinamakan:',
      options: ['Mudharabah', 'Musyarakah', 'Murabahah', 'Ijarah'],
      correctOptionIndex: 0,
      explanation: 'Mudharabah adalah pembiayaan bagi hasil antara Shahibul Maal dan Mudharib.',
    ),
    QuestionItem(
      id: 'pbk_052',
      questionText: 'Akad pembiayaan kemitraan di mana kedua belah pihak sama-sama menyertakan modal dan berbagi untung-rugi dinamakan:',
      options: ['Musyarakah', 'Mudharabah', 'Murabahah', 'Wadiah'],
      correctOptionIndex: 0,
      explanation: 'Musyarakah adalah akad syirkah penyertaan modal bersama.',
    ),
    QuestionItem(
      id: 'pbk_053',
      questionText: 'Akad jual-beli syariah di mana bank membeli barang lalu menjualnya ke nasabah dengan tambahan margin keuntungan yang disepakati dinamakan:',
      options: ['Murabahah', 'Salam', 'Istisna', 'Ijarah'],
      correctOptionIndex: 0,
      explanation: 'Murabahah adalah akad jual-beli dengan transparansi margin harga.',
    ),
    QuestionItem(
      id: 'pbk_054',
      questionText: 'Akad sewa-menyewa manfaat atas barang atau jasa dalam perbankan syariah dinamakan:',
      options: ['Ijarah', 'Wakalah', 'Kafalah', 'Rahn'],
      correctOptionIndex: 0,
      explanation: 'Ijarah adalah pemindahan hak guna manfaat barang sewa.',
    ),
    QuestionItem(
      id: 'pbk_055',
      questionText: 'Akad penitipan dana atau barang di mana penerima titipan boleh memanfaatkan dana tersebut dinamakan:',
      options: ['Wadiah Yad Dhamanah', 'Wadiah Yad Amanah', 'Wakalah', 'Qardh'],
      correctOptionIndex: 0,
      explanation: 'Wadiah Yad Dhamanah mengizinkan penggunaan dana simpanan dengan jaminan keutuhan.',
    ),
    QuestionItem(
      id: 'pbk_056',
      questionText: 'Akad pinjaman kebajikan tanpa imbalan bunga tambahan (nasabah hanya mengembalikan pokok) dinamakan:',
      options: ['Qardh / Qardhul Hasan', 'Rahn', 'Wakalah', 'Hawalah'],
      correctOptionIndex: 0,
      explanation: 'Qardhul Hasan adalah pinjaman sosial tanpa bunga.',
    ),
    QuestionItem(
      id: 'pbk_057',
      questionText: 'Akad gadaian barang berharga sebagai jaminan atas pinjaman dalam ekonomi syariah dinamakan:',
      options: ['Rahn', 'Kafalah', 'Hawalah', 'Wakalah'],
      correctOptionIndex: 0,
      explanation: 'Rahn adalah akad penyerahan agunan jaminan gadai.',
    ),
    QuestionItem(
      id: 'pbk_058',
      questionText: 'Dewan independen yang bertugas mengawasi pemenuhan kesesuaian prinsip syariah pada lembaga keuangan dinamakan:',
      options: ['DPS (Dewan Pengawas Syariah)', 'DSN-MUI', 'OJK Syariah', 'Komite Tabung'],
      correctOptionIndex: 0,
      explanation: 'DPS ditempatkan di tiap lembaga keuangan syariah.',
    ),
    QuestionItem(
      id: 'pbk_059',
      questionText: 'Lembaga MUI yang menerbitkan fatwa-fatwa hukum ekonomi dan keuangan syariah di Indonesia adalah:',
      options: ['DSN-MUI (Dewan Syariah Nasional)', 'DPS', 'BAZNAS', 'LPPOM'],
      correctOptionIndex: 0,
      explanation: 'DSN-MUI merumuskan fatwa produk keuangan syariah.',
    ),
    QuestionItem(
      id: 'pbk_060',
      questionText: 'Nilai waktu dari uang (Time Value of Money) menegaskan bahwa:',
      options: ['Uang Rp 1 Juta hari ini lebih bernilai dibanding Rp 1 Juta di masa depan', 'Nilai uang selalu tetap', 'Uang di masa depan selalu lebih tinggi', 'Bunga menurunkan nilai aset'],
      correctOptionIndex: 0,
      explanation: 'Prinsip TVM: Nilai uang saat ini lebih tinggi karena potensi kapasitas earning power.',
    ),
    QuestionItem(
      id: 'pbk_061',
      questionText: 'Proses menggandakan penerimaan bunga beruntun di mana bunga menghasilkan bunga kembali dinamakan:',
      options: ['Compound Interest (Bunga Berbunga)', 'Simple Interest', 'Anuitas', 'Amortisasi'],
      correctOptionIndex: 0,
      explanation: 'Compound Interest mempercepat pertumbuhan eksponensial nilai investasi.',
    ),
    QuestionItem(
      id: 'pbk_062',
      questionText: 'Rangkaian pembayaran atau penerimaan kas dalam jumlah tetap secara berkala selama jangka waktu tertentu dinamakan:',
      options: ['Anuitas (Annuity)', 'Amortisasi', 'Perpetuitas', 'Sinking Fund'],
      correctOptionIndex: 0,
      explanation: 'Anuitas adalah skema cicilan pembayaran berkala konstan.',
    ),
    QuestionItem(
      id: 'pbk_063',
      questionText: 'Anuitas yang pembayaran kasnya berlangsung terus menerus tanpa batas waktu akhir dinamakan:',
      options: ['Perpetuitas (Perpetuity)', 'Anuitas Dewasa', 'Amortisasi', 'Sinking Fund'],
      correctOptionIndex: 0,
      explanation: 'Perpetuitas PV = Cashflow / Suku Bunga.',
    ),
    QuestionItem(
      id: 'pbk_064',
      questionText: 'Jadwal pelunasan cicilan utang bertahap yang merincikan pembayaran porsi pokok dan porsi bunga dinamakan:',
      options: ['Tabel Amortisasi Kredit', 'Tabel Depresiasi', 'Laporan Laba Rugi', 'Cashflow Statement'],
      correctOptionIndex: 0,
      explanation: 'Tabel Amortisasi memperlihatkan skema penurunan saldo pokok pinjaman.',
    ),
    QuestionItem(
      id: 'pbk_065',
      questionText: 'Lembaga pembiayaan non-bank yang memberikan pinjaman dana tunai jaminan BPKB kendaraan atau sertifikat dinamakan:',
      options: ['Multifinance / Perusahaan Pembiayaan', 'Venture Capital', 'Fintech P2P', 'Bank Kustodian'],
      correctOptionIndex: 0,
      explanation: 'Multifinance memfasilitasi pembiayaan konsumen dan sewa guna usaha.',
    ),
    QuestionItem(
      id: 'pbk_066',
      questionText: 'Perusahaan permodalan yang memberikan investasi dana risiko tinggi ke perusahaan rintisan (Startup) dinamakan:',
      options: ['Venture Capital (Modal Ventura)', 'Private Equity', 'Angel Investor', 'Hedge Fund'],
      correctOptionIndex: 0,
      explanation: 'Venture Capital menyuntikkan modal ekuitas pada startup berprospek tinggi.',
    ),
    QuestionItem(
      id: 'pbk_067',
      questionText: 'Individual kaya raya yang memberikan suntikan dana awal (Seed Funding) ke startup baru dinamakan:',
      options: ['Angel Investor', 'Venture Capitalist', 'Underwriter', 'Broker'],
      correctOptionIndex: 0,
      explanation: 'Angel Investor mendanai startup pada tahap awal ide.',
    ),
    QuestionItem(
      id: 'pbk_068',
      questionText: 'Platform teknologi finansial yang mempertemukan pemberi pinjaman dengan peminjam secara daring dinamakan:',
      options: ['Fintech P2P Lending (Peer-to-Peer)', 'Crowdfunding', 'E-Wallet', 'Payment Gateway'],
      correctOptionIndex: 0,
      explanation: 'P2P Lending menghubungkan kreditur dan debitur via aplikasi online.',
    ),
    QuestionItem(
      id: 'pbk_069',
      questionText: 'Platform penggalangan dana secara gotong royong dari publik untuk proyek kreatif atau sosial dinamakan:',
      options: ['Crowdfunding', 'P2P Lending', 'Microfinance', 'Insurtech'],
      correctOptionIndex: 0,
      explanation: 'Crowdfunding mengumpulkan dana skala kecil dari masyarakat luas.',
    ),
    QuestionItem(
      id: 'pbk_070',
      questionText: 'Layanan penghubung otorisasi transaksi pembayaran online antara merchant e-commerce dengan sistem perbankan dinamakan:',
      options: ['Payment Gateway', 'E-Money', 'Switching', 'Core Banking'],
      correctOptionIndex: 0,
      explanation: 'Payment Gateway memproses jalur validasi pembayaran online aman.',
    ),
    QuestionItem(
      id: 'pbk_071',
      questionText: 'Sistem komputasi inti perbankan yang mengelola seluruh pencatatan transaksi nasabah secara terpusat dinamakan:',
      options: ['Core Banking System (CBS)', 'Payment Gateway', 'Switching', 'Database SQL'],
      correctOptionIndex: 0,
      explanation: 'Core Banking System adalah jantung pemrosesan perbankan.',
    ),
    QuestionItem(
      id: 'pbk_072',
      questionText: 'Penjualan aset saham piutang berjangka perusahaan kepada lembaga anjak piutang dinamakan transaksi:',
      options: ['Factoring (Anjak Piutang)', 'Leasing', 'Forfaiting', 'Securitization'],
      correctOptionIndex: 0,
      explanation: 'Factoring menjual tagihan piutang untuk mempercepat cairnya kas.',
    ),
    QuestionItem(
      id: 'pbk_073',
      questionText: 'Sewa guna usaha aset modal barang (pabrik/mesin) di mana penyewa berhak membeli barang di akhir periode dinamakan:',
      options: ['Finance Lease (Capital Lease)', 'Operating Lease', 'Factoring', 'Pledge'],
      correctOptionIndex: 0,
      explanation: 'Finance Lease mengalihkan risiko kepemilikan aset ke lessee.',
    ),
    QuestionItem(
      id: 'pbk_074',
      questionText: 'Sewa guna usaha murni di mana aset kembali ke pemilik di akhir periode tanpa hak opsi beli dinamakan:',
      options: ['Operating Lease', 'Finance Lease', 'Sale and Leaseback', 'Direct Lease'],
      correctOptionIndex: 0,
      explanation: 'Operating Lease bersifat sewa murni jangka pendek.',
    ),
    QuestionItem(
      id: 'pbk_075',
      questionText: 'Metode analisis fundamental saham yang menilai harga wajar perusahaan berdasar proyeksi arus kas masa depan dinamakan:',
      options: ['DCF (Discounted Cash Flow)', 'PBV', 'PER', 'Technical Analysis'],
      correctOptionIndex: 0,
      explanation: 'DCF menghitung nilai intrinsik saham dari PV arus kas bebas masa depan.',
    ),
    QuestionItem(
      id: 'pbk_076',
      questionText: 'Rasio valuation yang membandingkan harga pasar saham per lembar terhadap laba bersih per lembar saham (EPS) dinamakan:',
      options: ['PER (Price to Earnings Ratio)', 'PBV', 'DER', 'ROE'],
      correctOptionIndex: 0,
      explanation: 'PER = Harga Saham / Earnings Per Share (EPS).',
    ),
    QuestionItem(
      id: 'pbk_077',
      questionText: 'Rasio valuation yang membandingkan harga pasar saham terhadap nilai buku ekuitas per lembar dinamakan:',
      options: ['PBV (Price to Book Value)', 'PER', 'EV/EBITDA', 'PEG'],
      correctOptionIndex: 0,
      explanation: 'PBV membandingkan penilaian pasar relatif harga modal ekuitas.',
    ),
    QuestionItem(
      id: 'pbk_078',
      questionText: 'Metrik keuangan laba sebelum dikurangi beban bunga, pajak, depresiasi, dan amortisasi dinamakan:',
      options: ['EBITDA', 'EBIT', 'EBT', 'Net Income'],
      correctOptionIndex: 0,
      explanation: 'EBITDA mengukur arus kas operasional kotor perusahaan.',
    ),
    QuestionItem(
      id: 'pbk_079',
      questionText: 'Laporan keuangan yang menyajikan posisi Aset, Kewajiban (Liabilitas), dan Ekuitas perusahaan pada tanggal tertentu dinamakan:',
      options: ['Neraca (Balance Sheet / Laporan Posisi Keuangan)', 'Laporan Laba Rugi', 'Laporan Arus Kas', 'Laporan Perubahan Modal'],
      correctOptionIndex: 0,
      explanation: 'Neraca menyajikan rumus aset = liabilitas + ekuitas.',
    ),
    QuestionItem(
      id: 'pbk_080',
      questionText: 'Rasio solvabilitas yang membandingkan total utang (liabilitas) terhadap total ekuitas modal pemilik dinamakan:',
      options: ['DER (Debt to Equity Ratio)', 'DAR', 'Current Ratio', 'Quick Ratio'],
      correctOptionIndex: 0,
      explanation: 'DER mengukur tingkat struktur beban utang perusahaan.',
    ),
    QuestionItem(
      id: 'pbk_081',
      questionText: 'Rasio likuiditas yang membandingkan total aktiva lancar dengan kewajiban jangka pendek dinamakan:',
      options: ['Current Ratio', 'Quick Ratio', 'Cash Ratio', 'Solvency Ratio'],
      correctOptionIndex: 0,
      explanation: 'Current Ratio mengukur kemampuan membayar kewajiban lancar.',
    ),
    QuestionItem(
      id: 'pbk_082',
      questionText: 'Rasio likuiditas ketat yang mengeluar persediaan (inventory) dari aktiva lancar dinamakan:',
      options: ['Quick Ratio (Acid-Test Ratio)', 'Current Ratio', 'Cash Ratio', 'Working Capital'],
      correctOptionIndex: 0,
      explanation: 'Quick Ratio = (Aktiva Lancar - Persediaan) / Utang Lancar.',
    ),
    QuestionItem(
      id: 'pbk_083',
      questionText: 'Rasio efisiensi profitabilitas yang mengukur persentase laba bersih yang dihasilkan dari total modal ekuitas dinamakan:',
      options: ['ROE (Return on Equity)', 'ROA', 'ROI', 'GPM'],
      correctOptionIndex: 0,
      explanation: 'ROE = (Laba Bersih / Total Ekuitas) x 100%.',
    ),
    QuestionItem(
      id: 'pbk_084',
      questionText: 'Rasio profitabilitas yang mengukur persentase laba bersih yang dihasilkan dari penggunaan total aset dinamakan:',
      options: ['ROA (Return on Assets)', 'ROE', 'NPM', 'OPA'],
      correctOptionIndex: 0,
      explanation: 'ROA = (Laba Bersih / Total Aset) x 100%.',
    ),
    QuestionItem(
      id: 'pbk_085',
      questionText: 'Rencana aksi penyelamatan bank yang mengalami kesulitan likuiditas atau krisis modal mendesak dinamakan:',
      options: ['Bail-in / Bail-out', 'Liquidation', 'Merger', 'Acquisition'],
      correctOptionIndex: 0,
      explanation: 'Bail-in/Bail-out merupakan resolusi penanganan krisis stabilitas sistem keuangan.',
    ),
    QuestionItem(
      id: 'pbk_086',
      questionText: 'Pasar pinjam-menerima dana antar bank jangka pendek (misal overnight) untuk memenuhi kecukupan likuiditas dinamakan:',
      options: ['PUAB (Pasar Uang Antar Bank / Interbank Money Market)', 'Pasar Modal', 'Pasar Valas', 'Bursa Komoditas'],
      correctOptionIndex: 0,
      explanation: 'PUAB memfasilitasi transaksi likuiditas antarbank harian.',
    ),
    QuestionItem(
      id: 'pbk_087',
      questionText: 'Suku bunga acuan pinjaman dana tanpa jaminan antarbank di pasar uang London dinamakan:',
      options: ['LIBOR (London Interbank Offered Rate)', 'EURIBOR', 'SOFR', 'JIBOR'],
      correctOptionIndex: 0,
      explanation: 'LIBOR dulu menjadi acuan penetapan suku bunga penetapan internasional.',
    ),
    QuestionItem(
      id: 'pbk_088',
      questionText: 'Suku bunga acuan transaksi pinjaman antarbank di pasar uang Jakarta dinamakan:',
      options: ['JIBOR / IndONIA', 'BI-Rate', 'LPS Rate', 'SOFR'],
      correctOptionIndex: 0,
      explanation: 'IndONIA dan JIBOR adalah acuan pasar uang rupiah.',
    ),
    QuestionItem(
      id: 'pbk_089',
      questionText: 'Kontrak kesepakatan membeli atau menjual valuta asing pada kurs yang telah ditentukan untuk penyerahan di masa depan dinamakan:',
      options: ['Forward Contract / Futures', 'Spot Contract', 'Swap', 'Option'],
      correctOptionIndex: 0,
      explanation: 'Kontrak Forward/Futures mematok harga transaksi valas di masa depan.',
    ),
    QuestionItem(
      id: 'pbk_090',
      questionText: 'Transaksi jual-beli mata uang asing dengan penyerahan dana seketika (maksimal 2 hari kerja) dinamakan:',
      options: ['Spot Transaction', 'Forward', 'Option', 'Swap'],
      correctOptionIndex: 0,
      explanation: 'Transaksi Spot diselesaikan seketika di pasar valas.',
    ),
    QuestionItem(
      id: 'pbk_091',
      questionText: 'Instrumen keuangan yang nilainya diturunkan dari harga aset induk (underlying asset) dinamakan:',
      options: ['Derivatif (Derivative)', 'Saham Biasa', 'Obligasi', 'Deposito'],
      correctOptionIndex: 0,
      explanation: 'Derivatif melingkupi opsi, futures, swap, dan forward.',
    ),
    QuestionItem(
      id: 'pbk_092',
      questionText: 'Hak (bukan kewajiban) untuk membeli suatu aset pada harga tertentu dalam jangka waktu tertentu dinamakan:',
      options: ['Call Option', 'Put Option', 'Futures', 'Warrant'],
      correctOptionIndex: 0,
      explanation: 'Call Option memberikan hak opsi beli aset.',
    ),
    QuestionItem(
      id: 'pbk_093',
      questionText: 'Hak (bukan kewajiban) untuk menjual suatu aset pada harga tertentu dalam jangka waktu tertentu dinamakan:',
      options: ['Put Option', 'Call Option', 'Forward', 'Swap'],
      correctOptionIndex: 0,
      explanation: 'Put Option memberikan hak opsi jual aset.',
    ),
    QuestionItem(
      id: 'pbk_094',
      questionText: 'Tindakan kejahatan keuangan menyamarkan sisa aset hasil tindak pidana agar seolah berasal dari kegiatan sah dinamakan:',
      options: ['Pencucian Uang (Money Laundering)', 'Insuder Trading', 'Fraud', 'Embezzlement'],
      correctOptionIndex: 0,
      explanation: 'Pencucian uang melibatkan tahap Placement, Layering, dan Integration.',
    ),
    QuestionItem(
      id: 'pbk_095',
      questionText: 'Lembaga intelijen keuangan Indonesia yang menganalisis dan mencegah transaksi keuangan mencurigakan adalah:',
      options: ['PPATK (Pusat Pelaporan dan Analisis Transaksi Keuangan)', 'OJK', 'KPK', 'BPK'],
      correctOptionIndex: 0,
      explanation: 'PPATK menelusuri alur transaksi keuangan mencurigakan (TPPU).',
    ),
    QuestionItem(
      id: 'pbk_096',
      questionText: 'Praktik ilegal perdagangan saham memanfaatkan informasi internal rahasia perusahaan dinamakan:',
      options: ['Insider Trading', 'Market Manipulation', 'Wash Sale', 'Front Running'],
      correctOptionIndex: 0,
      explanation: 'Insider trading menyalahgunakan informasi non-publik demi keuntungan sepihak.',
    ),
    QuestionItem(
      id: 'pbk_097',
      questionText: 'Prinsip kehati-hatian perbankan mengenal identitas dan riwayat nasabah demi mencegah kejahatan dinamakan:',
      options: ['KYC (Know Your Customer)', 'CDD', 'EDD', 'AML'],
      correctOptionIndex: 0,
      explanation: 'Prinsip KYC memverifikasi dokumen identitas nasabah secara ketat.',
    ),
    QuestionItem(
      id: 'pbk_098',
      questionText: 'Tiga pilar kerangka pengawasan risiko perbankan standar internasional Basel Committee dinamakan:',
      options: ['Basel Accords (Basel I, II, III)', 'Camels Framework', 'COSO', 'SOX'],
      correctOptionIndex: 0,
      explanation: 'Basel III memperketat standar kecukupan modal dan risiko likuiditas perbankan global.',
    ),
    QuestionItem(
      id: 'pbk_099',
      questionText: 'Metode penilaian tingkat kesehatan bank konvensional yang terkenal dengan istilah CAMELS adalah singkatan dari:',
      options: ['Capital, Asset quality, Management, Earnings, Liquidity, Sensitivity to market risk', 'Cash, Asset, Margin, Equity, Liability, Stock', 'Credit, Audit, Money, Economy, Loan, Saving', 'CAR, Asset, Mind, Engagement, Legal, Strategy'],
      correctOptionIndex: 0,
      explanation: 'CAMELS menilai 6 dimensi tingkat kesehatan kinerja bank.',
    ),
    QuestionItem(
      id: 'pbk_100',
      questionText: 'Mata uang digital yang diterbitkan resmi dan dijamin penuh oleh bank sentral dinamakan:',
      options: ['CBDC (Central Bank Digital Currency / Rupiah Digital)', 'Cryptocurrency', 'Stablecoin', 'Token AI'],
      correctOptionIndex: 0,
      explanation: 'CBDC adalah bentuk digital sah dari mata uang kedaulatan negara (seperti Rupiah Digital).',
    ),
  ];
}
