import '../tes_seleksi_model.dart';

List<QuestionItem> getPemasaranDigitalQuestions() {
  return const [
    QuestionItem(
      id: 'pmd_001',
      questionText: 'Singkatan SEO dalam pemasaran digital mengacu pada istilah:',
      options: ['Search Engine Optimization', 'Social Media Engine Operation', 'System Execution Optimization', 'Site Engagement Orientation'],
      correctOptionIndex: 0,
      explanation: 'SEO adalah praktik mengoptimalkan peringkat organik situs di mesin pencari.',
    ),
    QuestionItem(
      id: 'pmd_002',
      questionText: 'Manakah yang merupakan strategi pencarian berbayar di mesin pencari (Paid Search)?',
      options: ['SEM (Search Engine Marketing)', 'SEO On-Page', 'Organic Search', 'Backlink Outreach'],
      correctOptionIndex: 0,
      explanation: 'SEM memanfaatkan iklan berbayar (seperti Google Ads) di halaman pencarian.',
    ),
    QuestionItem(
      id: 'pmd_003',
      questionText: 'Metrik digital yang mengukur persentase orang yang mengklik iklan dari total tayangan iklan adalah:',
      options: ['CTR (Click-Through Rate)', 'CPC (Cost Per Click)', 'CPM (Cost Per Mille)', 'CPA (Cost Per Acquisition)'],
      correctOptionIndex: 0,
      explanation: 'CTR = (Jumlah Klik / Jumlah Impresi) x 100%.',
    ),
    QuestionItem(
      id: 'pmd_004',
      questionText: 'Metrik biaya di mana pengiklan hanya membayar setiap kali iklan diklik pengguna dinamakan:',
      options: ['CPC (Cost Per Click)', 'CPM', 'CPA', 'CPL'],
      correctOptionIndex: 0,
      explanation: 'CPC membebankan biaya per klik pengunjung.',
    ),
    QuestionItem(
      id: 'pmd_005',
      questionText: 'Metrik biaya per seribu kali tayangan iklan dinamakan:',
      options: ['CPM (Cost Per Mille / Thousand Impressions)', 'CPC', 'CPA', 'CPV'],
      correctOptionIndex: 0,
      explanation: 'CPM dihitung per 1.000 tayangan impresi iklan.',
    ),
    QuestionItem(
      id: 'pmd_006',
      questionText: 'Hasil pengembalian finansial langsung atas biaya iklan yang dikeluarkan dinamakan:',
      options: ['ROAS (Return on Ad Spend)', 'ROI', 'CTR', 'CLV'],
      correctOptionIndex: 0,
      explanation: 'ROAS = Pendapatan dari Iklan / Biaya Iklan.',
    ),
    QuestionItem(
      id: 'pmd_007',
      questionText: 'Strategi menampilkan iklan kembali kepada pengguna yang pernah mengunjungi situs sebelumnya dinamakan:',
      options: ['Retargeting / Remarketing', 'Cold Targeting', 'Broad Targeting', 'Lookalike Targeting'],
      correctOptionIndex: 0,
      explanation: 'Retargeting menargetkan kembali mantan pengunjung website.',
    ),
    QuestionItem(
      id: 'pmd_008',
      questionText: 'Halaman khusus tempat mendaratnya pengunjung setelah mengklik iklan dinamakan:',
      options: ['Landing Page', 'Home Page', 'Contact Page', 'Blog Post'],
      correctOptionIndex: 0,
      explanation: 'Landing Page dirancang khusus untuk memicu aksi konversi.',
    ),
    QuestionItem(
      id: 'pmd_009',
      questionText: 'Tindakan mengarahkan pengunjung website menjadi pembeli atau pendaftar dinamakan:',
      options: ['Konversi (Conversion)', 'Impresi', 'Bounce', 'Reach'],
      correctOptionIndex: 0,
      explanation: 'Konversi adalah tercapainya aksi target bisnis.',
    ),
    QuestionItem(
      id: 'pmd_010',
      questionText: 'Pengujian membandingkan dua versi halaman (Versi A dan Versi B) untuk mengukur tingkat konversi terbaik dinamakan:',
      options: ['A/B Testing (Split Testing)', 'Beta Testing', 'Usability Test', 'SEO Audit'],
      correctOptionIndex: 0,
      explanation: 'A/B Testing menguji kinerja dua varian tampilan.',
    ),
    QuestionItem(
      id: 'pmd_011',
      questionText: 'Tag HTML yang menjadi judul utama halaman yang muncul pada hasil pencarian Google adalah:',
      options: ['Title Tag (<title>)', 'Meta Description', 'Header Tag (<h1>)', 'Alt Text'],
      correctOptionIndex: 0,
      explanation: 'Title Tag adalah elemen judul SEO terpenting pada halaman.',
    ),
    QuestionItem(
      id: 'pmd_012',
      questionText: 'Teks ringkasan singkat di bawah judul halaman pada SERP Google dinamakan:',
      options: ['Meta Description', 'Title Tag', 'Slug', 'Canonical Tag'],
      correctOptionIndex: 0,
      explanation: 'Meta description merangkum isi halaman di Snippet SERP.',
    ),
    QuestionItem(
      id: 'pmd_013',
      questionText: 'Deskripsi teks pada gambar yang membantu mesin pencari memahami isi gambar dinamakan:',
      options: ['Alt Text (Alternative Text)', 'Caption', 'Image Title', 'Anchor Text'],
      correctOptionIndex: 0,
      explanation: 'Alt Text mengindeks gambar di Google Images.',
    ),
    QuestionItem(
      id: 'pmd_014',
      questionText: 'Teks berikatan hyperlink yang dapat diklik untuk menuju ke halaman lain dinamakan:',
      options: ['Anchor Text', 'Alt Text', 'URL Slug', 'Backlink'],
      correctOptionIndex: 0,
      explanation: 'Anchor text adalah kata bertautan link.',
    ),
    QuestionItem(
      id: 'pmd_015',
      questionText: 'Tautan dari situs web luar yang mengarah ke situs web kita dinamakan:',
      options: ['Backlink (Inbound Link)', 'Outbound Link', 'Internal Link', 'Broken Link'],
      correctOptionIndex: 0,
      explanation: 'Backlink berkualitas meningkatkan otoritas domain (DA).',
    ),
    QuestionItem(
      id: 'pmd_016',
      questionText: 'Praktik SEO yang memanipulasi mesin pencari dengan cara melanggar pedoman resmi dinamakan:',
      options: ['Black Hat SEO', 'White Hat SEO', 'Gray Hat SEO', 'Technical SEO'],
      correctOptionIndex: 0,
      explanation: 'Black Hat SEO menggunakan trik manipulatif rawan penalti.',
    ),
    QuestionItem(
      id: 'pmd_017',
      questionText: 'Praktik SEO etis yang mematuhi sepenuhnya pedoman panduan mesin pencari dinamakan:',
      options: ['White Hat SEO', 'Black Hat SEO', 'Dark Pattern', 'Spamming'],
      correctOptionIndex: 0,
      explanation: 'White Hat SEO membangun reputasi situs secara organik beretika.',
    ),
    QuestionItem(
      id: 'pmd_018',
      questionText: 'Praktik menyembunyikan kata kunci berisi teks tersembunyi berlebihan dinamakan:',
      options: ['Keyword Stuffing', 'Keyword Research', 'Clustering', 'Mapping'],
      correctOptionIndex: 0,
      explanation: 'Keyword stuffing menumpuk kata kunci tak wajar.',
    ),
    QuestionItem(
      id: 'pmd_019',
      questionText: 'Model saluran corong pemasaran digital (Funnel) terdiri dari tahapan populer:',
      options: ['TOFU (Top of Funnel), MOFU (Middle), BOFU (Bottom of Funnel)', 'AIDA', 'B2B & B2C', 'SEO & SEM'],
      correctOptionIndex: 0,
      explanation: 'Funnel: TOFU (Awareness), MOFU (Consideration), BOFU (Conversion).',
    ),
    QuestionItem(
      id: 'pmd_020',
      questionText: 'Tahap TOFU (Top of Funnel) berfokus untuk membangun:',
      options: ['Awareness / Kesadaran Merek', 'Penjualan Langsung', 'Retensi Pelanggan', 'Loyalitas'],
      correctOptionIndex: 0,
      explanation: 'TOFU menarik audiens luas yang belum kenal produk.',
    ),
    QuestionItem(
      id: 'pmd_021',
      questionText: 'Tahap BOFU (Bottom of Funnel) berfokus untuk mendorong:',
      options: ['Keputusan Pembelian (Closing Sales)', 'Edukasi Produk', 'Pengenalan Merek', 'Pengumpulan Follower'],
      correctOptionIndex: 0,
      explanation: 'BOFU mengonversi calon prospek menjadi pembeli riil.',
    ),
    QuestionItem(
      id: 'pmd_022',
      questionText: 'Strategi pemasaran berbasis pembuatan konten konten artikel, video, atau infografis berkualitas dinamakan:',
      options: ['Content Marketing', 'Direct Sales', 'Cold Calling', 'Spam Marketing'],
      correctOptionIndex: 0,
      explanation: 'Content Marketing memikat audiens lewat konten bernilai.',
    ),
    QuestionItem(
      id: 'pmd_023',
      questionText: 'Metrik yang mengukur tingkat interaksi (like, comment, share) audiens terhadap konten media sosial dinamakan:',
      options: ['Engagement Rate', 'Reach', 'Impressions', 'Follower Growth'],
      correctOptionIndex: 0,
      explanation: 'Engagement Rate mengukur keaktifan interaksi audiens.',
    ),
    QuestionItem(
      id: 'pmd_024',
      questionText: 'Jumlah total akun unik yang melihat konten media sosial dinamakan:',
      options: ['Reach (Jangkauan)', 'Impressions', 'Engagement', 'Clicks'],
      correctOptionIndex: 0,
      explanation: 'Reach menghitung jumlah akun unik yang terpapar konten.',
    ),
    QuestionItem(
      id: 'pmd_025',
      questionText: 'Jumlah berapa kali konten ditampilkan di layar layar pengguna (bisa berulang) dinamakan:',
      options: ['Impressions (Impresi)', 'Reach', 'Engagement', 'Frequency'],
      correctOptionIndex: 0,
      explanation: 'Impressions menghitung total penayangan konten.',
    ),
    QuestionItem(
      id: 'pmd_026',
      questionText: 'Pemasaran berbayar dengan memanfaatkan pembuat konten populer untuk mempromosikan produk dinamakan:',
      options: ['Influencer Marketing / Key Opinion Leader (KOL)', 'Affiliate Marketing', 'Email Marketing', 'Native Ads'],
      correctOptionIndex: 0,
      explanation: 'Influencer/KOL memiliki basis pengikut berpengaruh.',
    ),
    QuestionItem(
      id: 'pmd_027',
      questionText: 'Model kemitraan di mana pemasar mendapat komisi komisi dari setiap penjualan hasil tautan referensi dinamakan:',
      options: ['Affiliate Marketing', 'Influencer Marketing', 'Display Ads', 'Sponsored Post'],
      correctOptionIndex: 0,
      explanation: 'Affiliate Marketing memberikan komisi berbasis kode referral/link.',
    ),
    QuestionItem(
      id: 'pmd_028',
      questionText: 'Pengiriman pesan email terotomatisasi berdasarkan tindakan pengguna di website dinamakan:',
      options: ['Email Automation / Drip Campaign', 'Email Blast', 'Spam Mail', 'Cold Mail'],
      correctOptionIndex: 0,
      explanation: 'Email Automation mengirim pesan terjadwal otomatis.',
    ),
    QuestionItem(
      id: 'pmd_029',
      questionText: 'Metrik email marketing yang mengukur persentase penerima yang membuka email dinamakan:',
      options: ['Open Rate', 'Click Rate', 'Unsubscribe Rate', 'Bounce Rate'],
      correctOptionIndex: 0,
      explanation: 'Open Rate = (Jumlah Email Dibuka / Email Terkirim) x 100%.',
    ),
    QuestionItem(
      id: 'pmd_030',
      questionText: 'Persentase email yang gagal terkirim ke kotak masuk penerima dinamakan:',
      options: ['Email Bounce Rate', 'Open Rate', 'Click Rate', 'Spam Rate'],
      correctOptionIndex: 0,
      explanation: 'Email Bounce terjadi akibat alamat email salah (Hard Bounce) atau server penuh (Soft Bounce).',
    ),
    QuestionItem(
      id: 'pmd_031',
      questionText: 'Iklan digital yang menyatu secara alami dengan gaya dan format konten media penerbit dinamakan:',
      options: ['Native Advertising', 'Pop-up Ads', 'Banner Ads', 'Interstitials'],
      correctOptionIndex: 0,
      explanation: 'Native Ads tampil alami seperti artikel/posting organik.',
    ),
    QuestionItem(
      id: 'pmd_032',
      questionText: 'Format iklan spanduk bergambar/grafis yang dipasang pada situs web penerbit dinamakan:',
      options: ['Display Ads / Banner Ads', 'Text Ads', 'Search Ads', 'Native Ads'],
      correctOptionIndex: 0,
      explanation: 'Display Ads memanfaatkan spanduk gambar/video visual.',
    ),
    QuestionItem(
      id: 'pmd_033',
      questionText: 'Iklan layar penuh yang muncul di antara peralihan halaman atau aplikasi dinamakan:',
      options: ['Interstitial Ads', 'Banner Ads', 'Native Ads', 'In-feed Ads'],
      correctOptionIndex: 0,
      explanation: 'Interstitial Ads menutup seluruh layar saat jeda navigasi.',
    ),
    QuestionItem(
      id: 'pmd_034',
      questionText: 'Kode pelacak kecil (skrip JavaScript) yang ditanam di situs web untuk merekam aktivitas pengunjung demi optimasi iklan dinamakan:',
      options: ['Tracking Pixel (misal Meta Pixel / Google Tag)', 'Cookie', 'Bot', 'Webmaster Tool'],
      correctOptionIndex: 0,
      explanation: 'Tracking Pixel mengirim data peristiwa (event) ke platform iklan.',
    ),
    QuestionItem(
      id: 'pmd_035',
      questionText: 'File data kecil yang disimpan browser di perangkat pengguna untuk mengingat sesi login dan preferensi dinamakan:',
      options: ['Cookie', 'Cache', 'Pixel', 'Session ID'],
      correctOptionIndex: 0,
      explanation: 'Cookie menyimpan data rekam jejak penjelajahan situs.',
    ),
    QuestionItem(
      id: 'pmd_036',
      questionText: 'Audiens baru yang dibuat sistem iklan berdasar kemiripan karakteristik dengan pelanggan eksis dinamakan:',
      options: ['Lookalike Audience', 'Custom Audience', 'Retargeted Audience', 'Broad Audience'],
      correctOptionIndex: 0,
      explanation: 'Lookalike Audience memperluas jangkauan iklan ke target yang mirip pembeli riil.',
    ),
    QuestionItem(
      id: 'pmd_037',
      questionText: 'Target audiens yang dibuat berbasis daftar nomor HP atau email pelanggan yang diunggah dinamakan:',
      options: ['Custom Audience', 'Lookalike Audience', 'Saved Audience', 'Interest Audience'],
      correctOptionIndex: 0,
      explanation: 'Custom Audience memanfaatkan data pelanggan internal perusahaan.',
    ),
    QuestionItem(
      id: 'pmd_038',
      questionText: 'Singkatan CTA dalam pembuatan landing page dan iklan pemasaran berarti:',
      options: ['Call To Action', 'Click To Ad', 'Customer Targeted Action', 'Cost To Acquire'],
      correctOptionIndex: 0,
      explanation: 'CTA adalah tombol/ajakan aksi (seperti "Beli Sekarang" atau "Daftar").',
    ),
    QuestionItem(
      id: 'pmd_039',
      questionText: 'Singkatan CRO dalam optimasi situs web pemasaran mengacu pada:',
      options: ['Conversion Rate Optimization', 'Customer Retention Operation', 'Click Rate Optimization', 'Content Reach Organisation'],
      correctOptionIndex: 0,
      explanation: 'CRO berfokus meningkatkan persentase pengunjung yang berkonversi.',
    ),
    QuestionItem(
      id: 'pmd_040',
      questionText: 'Metode riset menemukan kata kunci pencarian yang relevan beserta volume pencariannya dinamakan:',
      options: ['Keyword Research', 'SEO Audit', 'Content Mapping', 'Competitor Analysis'],
      correctOptionIndex: 0,
      explanation: 'Keyword Research menganalisis kata pencarian potensial pengguna.',
    ),
    QuestionItem(
      id: 'pmd_041',
      questionText: 'Kata kunci pencarian spesifik yang terdiri dari 3 kata atau lebih dengan tingkat persaingan rendah dinamakan:',
      options: ['Long-Tail Keyword', 'Short-Tail Keyword', 'Head Keyword', 'Seed Keyword'],
      correctOptionIndex: 0,
      explanation: 'Long-Tail Keyword memiliki niat beli (intent) tinggi dan persaingan rendah.',
    ),
    QuestionItem(
      id: 'pmd_042',
      questionText: 'Niat atau tujuan di balik pencarian kata kunci oleh pengguna internet dinamakan:',
      options: ['Search Intent (Niat Pencarian)', 'Search Volume', 'Keyword Difficulty', 'CPC'],
      correctOptionIndex: 0,
      explanation: 'Search Intent memilah pencarian Informasional, Navigasional, atau Transaksional.',
    ),
    QuestionItem(
      id: 'pmd_043',
      questionText: 'Perangkat lunak analisis lalu lintas web gratis populer buatan Google adalah:',
      options: ['Google Analytics (GA4)', 'Google Search Console', 'Google Trends', 'Google Ads'],
      correctOptionIndex: 0,
      explanation: 'Google Analytics merekam laporan aktivitas pengunjung situs.',
    ),
    QuestionItem(
      id: 'pmd_044',
      questionText: 'Layanan gratis Google untuk memantau status indeksasi dan kesehatan teknis SEO web adalah:',
      options: ['Google Search Console (GSC)', 'Google Analytics', 'Google Tag Manager', 'Google My Business'],
      correctOptionIndex: 0,
      explanation: 'GSC memantau kinerj organic search dan error indeksasi web.',
    ),
    QuestionItem(
      id: 'pmd_045',
      questionText: 'Profil bisnis gratis di Google yang menampilkan peta lokasi dan ulasan toko dinamakan:',
      options: ['Google Business Profile (GBP)', 'Google Ads', 'Google Merchant', 'Google Site'],
      correctOptionIndex: 0,
      explanation: 'GBP penting untuk optimasi SEO Lokal (Local SEO).',
    ),
    QuestionItem(
      id: 'pmd_046',
      questionText: 'Optimasi kehadiran bisnis di mesin pencari untuk pencarian wilayah geografis sekitar dinamakan:',
      options: ['Local SEO', 'Global SEO', 'Technical SEO', 'Voice SEO'],
      correctOptionIndex: 0,
      explanation: 'Local SEO menargetkan konsumen di sekitar wilayah toko fisik.',
    ),
    QuestionItem(
      id: 'pmd_047',
      questionText: 'Rangkaian pemantauan reputasi dan perbincangan merek di media sosial dinamakan:',
      options: ['Social Listening', 'Social Selling', 'Social Bookmarking', 'Social Advertising'],
      correctOptionIndex: 0,
      explanation: 'Social Listening melacak sebutan merek (brand mentions) di internet.',
    ),
    QuestionItem(
      id: 'pmd_048',
      questionText: 'Proses membangun hubungan penjualan langsung dengan prospek melalui platform media sosial dinamakan:',
      options: ['Social Selling', 'Social Listening', 'Cold Outreach', 'Telemarketing'],
      correctOptionIndex: 0,
      explanation: 'Social Selling menggunakan jejaring sosial (seperti LinkedIn) untuk prospeksi bisnis.',
    ),
    QuestionItem(
      id: 'pmd_049',
      questionText: 'Sistem komputasi otomatis yang membalas pesan obrolan pelanggan secara otomatis dinamakan:',
      options: ['Chatbot (AI Customer Service)', 'Auto-responder', 'Live Chat', 'Voice Bot'],
      correctOptionIndex: 0,
      explanation: 'Chatbot merespon pertanyaan umum pelanggan 24/7.',
    ),
    QuestionItem(
      id: 'pmd_050',
      questionText: 'Halaman hasil pencarian mesin pencari Google dikenal dengan singkatan:',
      options: ['SERP (Search Engine Results Page)', 'SEO', 'SEM', 'URL'],
      correctOptionIndex: 0,
      explanation: 'SERP menampilkan halaman daftar hasil pencarian.',
    ),
    QuestionItem(
      id: 'pmd_051',
      questionText: 'Program bot mesin pencari yang bertugas menjelajahi halaman web baru dinamakan:',
      options: ['Crawler / Spider (misal Googlebot)', 'Indexer', 'Scraper', 'Algorithm'],
      correctOptionIndex: 0,
      explanation: 'Crawler merayapi struktur tautan web di internet.',
    ),
    QuestionItem(
      id: 'pmd_052',
      questionText: 'Proses menyimpan dan mengorganisasi konten web ke dalam database mesin pencari dinamakan:',
      options: ['Indeksasi (Indexing)', 'Crawling', 'Ranking', 'Rendering'],
      correctOptionIndex: 0,
      explanation: 'Halaman yang lolos indeksasi baru bisa muncul di SERP.',
    ),
    QuestionItem(
      id: 'pmd_053',
      questionText: 'File teks sederhana di server yang memberi instruksi kepada bot crawler halaman mana yang boleh dirayapi dinamakan:',
      options: ['robots.txt', 'sitemap.xml', '.htaccess', 'index.html'],
      correctOptionIndex: 0,
      explanation: 'robots.txt mengontrol akses perayapan mesin pencari.',
    ),
    QuestionItem(
      id: 'pmd_054',
      questionText: 'File XML yang berisi daftar peta seluruh halaman web untuk mempermudah indeksasi dinamakan:',
      options: ['sitemap.xml', 'robots.txt', 'schema.org', 'rss.xml'],
      correctOptionIndex: 0,
      explanation: 'Sitemap XML memandu crawler menemukan seluruh URL situs.',
    ),
    QuestionItem(
      id: 'pmd_055',
      questionText: 'Elemen tag penanda untuk memberitahu Google URL versi asli dari halaman ganda (duplicate content) dinamakan:',
      options: ['Canonical Tag (rel="canonical")', 'Alternate Tag', 'Noindex Tag', 'Nofollow Tag'],
      correctOptionIndex: 0,
      explanation: 'Canonical tag mencegah masalah kontens ganda.',
    ),
    QuestionItem(
      id: 'pmd_056',
      questionText: 'Atribut tautan yang memberi tahu mesin pencari untuk tidak meneruskan nilai otoritas (link juice) dinamakan:',
      options: ['rel="nofollow"', 'rel="dofollow"', 'rel="sponsored"', 'rel="ugc"'],
      correctOptionIndex: 0,
      explanation: 'Nofollow mencegah transfer reputasi SEO ke URL tujuan.',
    ),
    QuestionItem(
      id: 'pmd_057',
      questionText: 'Matrik indikator kecepatan dan pengalaman pengguna situs web dari Google dinamakan:',
      options: ['Core Web Vitals (LCP, FID/INP, CLS)', 'PageSpeed Score', 'Lighthouse', 'Bounce Rate'],
      correctOptionIndex: 0,
      explanation: 'Core Web Vitals mengukur kinerja perambanan nyata pengguna.',
    ),
    QuestionItem(
      id: 'pmd_058',
      questionText: 'Kunci metrik Core Web Vitals yang mengukur kinerja kecepatan muat konten utama terbesar dinamakan:',
      options: ['LCP (Largest Contentful Paint)', 'FID', 'CLS', 'TTFB'],
      correctOptionIndex: 0,
      explanation: 'LCP mengukur waktu muat elemen visual terbesar.',
    ),
    QuestionItem(
      id: 'pmd_059',
      questionText: 'Metrik Core Web Vitals yang mengukur stabilitas visual pergeseran elemen tata letak saat dimuat dinamakan:',
      options: ['CLS (Cumulative Layout Shift)', 'LCP', 'INP', 'FCP'],
      correctOptionIndex: 0,
      explanation: 'CLS mengukur pergeseran tatanan tata letak tak terduga.',
    ),
    QuestionItem(
      id: 'pmd_060',
      questionText: 'Pemasaran beriklan dengan format pesan singkat di aplikasi pesan (seperti WhatsApp Business) dinamakan:',
      options: ['Conversational Marketing / Chat Marketing', 'Telemarketing', 'SMS Blast', 'Broadcast Mail'],
      correctOptionIndex: 0,
      explanation: 'Conversational Marketing mengandalkan percakapan akrab via chat.',
    ),
    QuestionItem(
      id: 'pmd_061',
      questionText: 'Saluran pemasaran melalui siaran audio episodic yang dapat diunduh/didengar secara streaming dinamakan:',
      options: ['Podcast Marketing', 'Video Marketing', 'Webinar', 'Broadcast Radio'],
      correctOptionIndex: 0,
      explanation: 'Podcast menyajikan konten audio edukasi/hiburan berlanjut.',
    ),
    QuestionItem(
      id: 'pmd_062',
      questionText: 'Video pendek vertikal berdurasi 15-60 detik yang populer di TikTok, Instagram Reels, dan YouTube Shorts dinamakan:',
      options: ['Short-Form Video Content', 'Long-Form Video', 'Vlog', 'Webinar'],
      correctOptionIndex: 0,
      explanation: 'Short-form video sangat efektif menarik jangkauan jangkauan viral.',
    ),
    QuestionItem(
      id: 'pmd_063',
      questionText: 'Penyelenggaraan seminar atau presentasi edukasi interaktif secara daring dinamakan:',
      options: ['Webinar (Web Seminar)', 'Webcast', 'Live Stream', 'Online Class'],
      correctOptionIndex: 0,
      explanation: 'Webinar mengumpulkan prospek prospek B2B bernilai tinggi.',
    ),
    QuestionItem(
      id: 'pmd_064',
      questionText: 'Konten berupa rekomendasi foto atau ulasan nyata yang dibuat oleh konsumen pengguna produk dinamakan:',
      options: ['UGC (User-Generated Content)', 'PGC (Professional Content)', 'Sponsored Post', 'Ad Creative'],
      correctOptionIndex: 0,
      explanation: 'UGC memiliki tingkat kepercayaan (trust) sangat tinggi dibanding iklan pabrikan.',
    ),
    QuestionItem(
      id: 'pmd_065',
      questionText: 'Proses pengelompokan audiens pelanggan berbasis demografi, geografi, dan perilaku minat digital dinamakan:',
      options: ['Audience Segmentation', 'Retargeting', 'Broad Targeting', 'Lookalike'],
      correctOptionIndex: 0,
      explanation: 'Segmentasi mempartisi calon konsumen agar iklan tepat sasaran.',
    ),
    QuestionItem(
      id: 'pmd_066',
      questionText: 'Format iklan komersial berbentuk tayangan video sebelum, di tengah, atau sesudah video YouTube utama dinamakan:',
      options: ['In-Stream Ads', 'Out-Stream Ads', 'Bumper Ads', 'Display Ads'],
      correctOptionIndex: 0,
      explanation: 'In-stream ads tayang di dalam pemutar video utama.',
    ),
    QuestionItem(
      id: 'pmd_067',
      questionText: 'Iklan video singkat berdurasi 6 detik yang tidak dapat dilewati (non-skippable) di YouTube dinamakan:',
      options: ['Bumper Ads', 'In-Stream Ads', 'Overlay Ads', 'Discovery Ads'],
      correctOptionIndex: 0,
      explanation: 'Bumper Ads berdurasi 6 detik tanpa tombol skip.',
    ),
    QuestionItem(
      id: 'pmd_068',
      questionText: 'Skor reputasi atau kualitas iklan Google Ads (skala 1-10) yang mempengaruhi biaya CPC dinamakan:',
      options: ['Quality Score', 'Ad Rank', 'Relevance Score', 'Optimization Score'],
      correctOptionIndex: 0,
      explanation: 'Quality Score tinggi menekan biaya CPC dan meningkatkan Ad Rank.',
    ),
    QuestionItem(
      id: 'pmd_069',
      questionText: 'Perhitungan lelang iklan Google Ads yang menentukan posisi penayangan iklan dinamakan:',
      options: ['Ad Rank (Max Bid x Quality Score)', 'Quality Score', 'Cost Per Click', 'Impression Share'],
      correctOptionIndex: 0,
      explanation: 'Ad Rank menentukan peringkat urutan tayang posisi iklan di SERP.',
    ),
    QuestionItem(
      id: 'pmd_070',
      questionText: 'Istilah "Omnichannel Marketing" mengacu pada strategi pemasaran yang:',
      options: ['Mengintegrasikan seluruh saluran pemasaran online dan offline secara mulus', 'Hanya fokus di media sosial', 'Hanya jualan di website', 'Menggunakan iklan TV saja'],
      correctOptionIndex: 0,
      explanation: 'Omnichannel menyelaraskan pengalaman konsumen lintas kanal digital dan toko fisik.',
    ),
    QuestionItem(
      id: 'pmd_071',
      questionText: 'Pemasaran berorientasi bisnis ke bisnis lainnya dinamakan pemasaran:',
      options: ['B2B (Business-to-Business)', 'B2C (Business-to-Consumer)', 'C2C', 'D2C'],
      correctOptionIndex: 0,
      explanation: 'B2B menjual produk/jasa ke organisasi perusahaan lain.',
    ),
    QuestionItem(
      id: 'pmd_072',
      questionText: 'Pemasaran produk langsung dari produsen ke konsumen akhir dinamakan pemasaran:',
      options: ['B2C / D2C (Direct-to-Consumer)', 'B2B', 'B2G', 'C2B'],
      correctOptionIndex: 0,
      explanation: 'D2C memotong rantai perantara distributor.',
    ),
    QuestionItem(
      id: 'pmd_073',
      questionText: 'Model bisnis platform di mana antar individu pengguna saling bertransaksi produk dinamakan:',
      options: ['C2C (Consumer-to-Consumer)', 'B2C', 'B2B', 'G2C'],
      correctOptionIndex: 0,
      explanation: 'C2C memfasilitasi jual-beli antar individu (seperti eBay atau marketplace bekas).',
    ),
    QuestionItem(
      id: 'pmd_074',
      questionText: 'Istilah "Growth Hacking" dalam pemasaran digital mengacu pada strategi:',
      options: ['Pemasaran eksperimental cepat berbiaya hemat untuk pertumbuhan kilat', 'Meretas akun media sosial pesaing', 'Membeli follower', 'Iklan Baliho'],
      correctOptionIndex: 0,
      explanation: 'Growth Hacking mengandalkan pengujian kreatif data-driven demi skala cepat.',
    ),
    QuestionItem(
      id: 'pmd_075',
      questionText: 'Indikator retensi yang mengukur persentase pengguna yang kembali memakai aplikasi dinamakan:',
      options: ['Retention Rate', 'Churn Rate', 'Bounce Rate', 'Exit Rate'],
      correctOptionIndex: 0,
      explanation: 'Retention Rate mengukur tingkat kesetiaan pemakaian berulang.',
    ),
    QuestionItem(
      id: 'pmd_076',
      questionText: 'Penataan tautan navigasi breadcrumb pada situs web berfungsi untuk:',
      options: ['Memudahkan pengguna dan mesin pencari memahami hirarki posisi halaman', 'Menampilkan iklan', 'Meningkatkan kecepatan server', 'Menghapus cookie'],
      correctOptionIndex: 0,
      explanation: 'Breadcrumb menunjukkan jalur hirarki navigasi (Home > Kategori > Produk).',
    ),
    QuestionItem(
      id: 'pmd_077',
      questionText: 'Strategi penulisan naskah iklan persuasif yang mendorong pembaca melakukan pembeliaan dinamakan:',
      options: ['Copywriting', 'Content Writing', 'Technical Writing', 'Journalism'],
      correctOptionIndex: 0,
      explanation: 'Copywriting berfokus pada persuasi ajakan tindakan pembeli.',
    ),
    QuestionItem(
      id: 'pmd_078',
      questionText: 'Penulisan artikel edukatif panjang berstruktur SEO untuk blog dinamakan:',
      options: ['Content Writing', 'Copywriting', 'Ghostwriting', 'Microcopy'],
      correctOptionIndex: 0,
      explanation: 'Content writing berfokus pada penyampaian edukasi dan informasi bernilai.',
    ),
    QuestionItem(
      id: 'pmd_079',
      questionText: 'Formulasi kerangka copywriting terkenal AIDA adalah singkatan dari:',
      options: ['Attention, Interest, Desire, Action', 'Awareness, Intent, Data, Ads', 'Action, Interest, Direct, Attraction', 'App, Image, Design, Art'],
      correctOptionIndex: 0,
      explanation: 'AIDA: Attention (Perhatian) -> Interest (Minat) -> Desire (Keinginan) -> Action (Tindakan).',
    ),
    QuestionItem(
      id: 'pmd_080',
      questionText: 'Formulasi copywriting PAS yang berfokus pada masalah konsumen adalah singkatan dari:',
      options: ['Problem, Agitate, Solution', 'Product, Action, Sales', 'Pain, Attention, Satisfaction', 'Plan, Ask, Solve'],
      correctOptionIndex: 0,
      explanation: 'PAS: Problem (Masalah) -> Agitate (Mempertajam Dampak) -> Solution (Solusi).',
    ),
    QuestionItem(
      id: 'pmd_081',
      questionText: 'Teknologi pemasaran digital yang memprediksi tren perilaku audiens menggunakan kecerdasan buatan dinamakan:',
      options: ['AI Marketing (Predictive AI)', 'Automation', 'Big Data', 'Cloud Computing'],
      correctOptionIndex: 0,
      explanation: 'AI Marketing memanfaatkan machine learning mempersonalisasi pesan target.',
    ),
    QuestionItem(
      id: 'pmd_082',
      questionText: 'Penggunaan perangkat lunak untuk mengotomatiskan alur kerja kampanye pemasaran dinamakan:',
      options: ['Marketing Automation', 'CRM', 'ERP', 'CMS'],
      correctOptionIndex: 0,
      explanation: 'Marketing Automation mengotomatiskan pengiriman email, sosial posting, dan scoring prospek.',
    ),
    QuestionItem(
      id: 'pmd_083',
      questionText: 'Metode penilaian prospek calon pelanggan berdasar tingkat kesiapan membeli dinamakan:',
      options: ['Lead Scoring', 'Lead Generation', 'Lead Nurturing', 'Lead Magnet'],
      correctOptionIndex: 0,
      explanation: 'Lead scoring memberi nilai pada prospek (Hot/Warm/Cold Lead).',
    ),
    QuestionItem(
      id: 'pmd_084',
      questionText: 'Penawaran hadiah gratis (seperti E-book atau Voucher) untuk mendapatkan kontak email calon pembeli dinamakan:',
      options: ['Lead Magnet', 'Freebie', 'Opt-in', 'Gimmick'],
      correctOptionIndex: 0,
      explanation: 'Lead Magnet menukarkan sumber daya gratis dengan alamat email prospek.',
    ),
    QuestionItem(
      id: 'pmd_085',
      questionText: 'Proses membina hubungan berkesinambungan dengan prospek melalui pesan edukatif dinamakan:',
      options: ['Lead Nurturing', 'Lead Generation', 'Lead Scoring', 'Direct Sales'],
      correctOptionIndex: 0,
      explanation: 'Lead Nurturing membimbing prospek melewati funnel hingga siap membeli.',
    ),
    QuestionItem(
      id: 'pmd_086',
      questionText: 'Sistem manajemen konten web yang memudahkan pembuatan situs tanpa koding (seperti WordPress) dinamakan:',
      options: ['CMS (Content Management System)', 'LMS', 'CRM', 'Framework'],
      correctOptionIndex: 0,
      explanation: 'CMS mengelola pembuatan dan publikasi konten web.',
    ),
    QuestionItem(
      id: 'pmd_087',
      questionText: 'Tingkat persentase penyelesaian menonton video dari awal hingga akhir dinamakan:',
      options: ['Completion Rate / Watch Time', 'Retention Rate', 'Drop-off Rate', 'View Rate'],
      correctOptionIndex: 0,
      explanation: 'Completion Rate mengukur seberapa menarik video ditonton penuh.',
    ),
    QuestionItem(
      id: 'pmd_088',
      questionText: 'Metrik durasi kumulatif waktu yang dihabiskan penonton menyaksikan video Anda di YouTube dinamakan:',
      options: ['Watch Time (Waktu Tonton)', 'Views', 'Impresi', 'CTR'],
      correctOptionIndex: 0,
      explanation: 'Watch Time adalah faktor bobot algoritma rekomendasi YouTube terpenting.',
    ),
    QuestionItem(
      id: 'pmd_089',
      questionText: 'Gambar sampul pratinjau menarik yang mewakili isi video YouTube dinamakan:',
      options: ['Thumbnail', 'Banner', 'Poster', 'Cover'],
      correctOptionIndex: 0,
      explanation: 'Thumbnail menarik meningkatkan nilai CTR video.',
    ),
    QuestionItem(
      id: 'pmd_090',
      questionText: 'Metode pembelian iklan digital secara otomatis melalui algoritma lelang real-time dinamakan:',
      options: ['Programmatic Advertising', 'Direct Media Buying', 'Manual Bidding', 'Affiliate'],
      correctOptionIndex: 0,
      explanation: 'Programmatic Advertising mengotomatiskan lelang ruang iklan (RTB).',
    ),
    QuestionItem(
      id: 'pmd_091',
      questionText: 'Platform tempat pengiklan membeli inventaris ruang iklan digital secara terotomatisasi dinamakan:',
      options: ['DSP (Demand-Side Platform)', 'SSP', 'Ad Exchange', 'DMP'],
      correctOptionIndex: 0,
      explanation: 'DSP digunakan pengiklan untuk mengelola pembelian iklan programmatic.',
    ),
    QuestionItem(
      id: 'pmd_092',
      questionText: 'Platform penerbit web (publisher) untuk menjual ruang iklan kosongnya secara otomatis dinamakan:',
      options: ['SSP (Supply-Side Platform)', 'DSP', 'Ad Server', 'CDP'],
      correctOptionIndex: 0,
      explanation: 'SSP memfasilitasi penerbit menjual inventaris iklan secara optimal.',
    ),
    QuestionItem(
      id: 'pmd_093',
      questionText: 'Fenomena psikologis di mana konsumen merasa takut ketinggalan tren hangat di internet dinamakan:',
      options: ['FOMO (Fear of Missing Out)', 'Social Proof', 'Urgency', 'Scarcity'],
      correctOptionIndex: 0,
      explanation: 'FOMO dimanfaatkan dalam penawaran terbatas untuk memicu aksi beli cepat.',
    ),
    QuestionItem(
      id: 'pmd_094',
      questionText: 'Penggunaan testimonial, jumlah pembeli, dan ulasan bintang untuk membuktikan kredibilitas dinamakan:',
      options: ['Social Proof (Bukti Sosial)', 'Authority', 'Scarcity', 'Reciprocity'],
      correctOptionIndex: 0,
      explanation: 'Social Proof membangun kepercayaan calon pembeli baru.',
    ),
    QuestionItem(
      id: 'pmd_095',
      questionText: 'Taktik penawaran stok terbatas atau batas waktu hitung mundur dinamakan strategi:',
      options: ['Scarcity & Urgency', 'FOMO', 'Social Proof', 'Anchoring'],
      correctOptionIndex: 0,
      explanation: 'Kelangkaan (Scarcity) dan Urgensi mendorong keputusan transaksi segera.',
    ),
    QuestionItem(
      id: 'pmd_096',
      questionText: 'Nilai proyeksi estimasi pendapatan bersih dari seorang pelanggan sepanjang hubungannya dengan produk dinamakan:',
      options: ['LTV / CLV (Customer Lifetime Value)', 'CAC', 'ARPU', 'MRR'],
      correctOptionIndex: 0,
      explanation: 'CLV menghitung nilai ekonomis total satu pelanggan.',
    ),
    QuestionItem(
      id: 'pmd_097',
      questionText: 'Rasio rasio ideal antara nilai Customer Lifetime Value (LTV) dibanding Customer Acquisition Cost (CAC) adalah:',
      options: ['3 : 1 atau lebih besar', '1 : 1', '1 : 3', '0.5 : 1'],
      correctOptionIndex: 0,
      explanation: 'Skala bisnis sehat mensyaratkan LTV minimal 3x lipat nilai CAC.',
    ),
    QuestionItem(
      id: 'pmd_098',
      questionText: 'Metrik pendapatan berulang bulanan pada bisnis berlangganan (SaaS) dinamakan:',
      options: ['MRR (Monthly Recurring Revenue)', 'ARR', 'GMV', 'ARPU'],
      correctOptionIndex: 0,
      explanation: 'MRR mengukur pendapatan berlangganan yang dapat diprediksi tiap bulan.',
    ),
    QuestionItem(
      id: 'pmd_099',
      questionText: 'Total nilai transaksi kotor seluruh barang yang diperjualbelikan di platform e-commerce dinamakan:',
      options: ['GMV (Gross Merchandise Value)', 'NMV', 'Revenue', 'NPS'],
      correctOptionIndex: 0,
      explanation: 'GMV mengukur total nilai perputaran transaksi kotor di marketplace.',
    ),
    QuestionItem(
      id: 'pmd_100',
      questionText: 'Praktek merancang antarmuka jebakan yang memperdaya pengguna membuat keputusan tidak disengaja dinamakan:',
      options: ['Dark Pattern', 'Bad UX', 'Clickbait', 'Phishing'],
      correctOptionIndex: 0,
      explanation: 'Dark Pattern adalah trik desain manipulatif yang menjebak pengguna.',
    ),
  ];
}
