import '../tes_seleksi_model.dart';

List<QuestionItem> getManajemenQuestions() {
  return const [
    QuestionItem(
      id: 'mnj_001',
      questionText: 'Empat fungsi dasar manajemen menurut Henry Fayol (POAC) adalah:',
      options: ['Planning, Organizing, Actuating, Controlling', 'Planning, Operating, Accounting, Communicating', 'Produksi, Organisasi, Asosiasi, Kontrol', 'Positioning, Organizing, Advertising, Controlling'],
      correctOptionIndex: 0,
      explanation: 'POAC: Perencanaan (Planning), Pengorganisasian (Organizing), Pengarahan (Actuating), Pengawasan (Controlling).',
    ),
    QuestionItem(
      id: 'mnj_002',
      questionText: 'Analisis SWOT dalam perencanaan strategis perusahaan merupakan singkatan dari:',
      options: ['Strengths, Weaknesses, Opportunities, Threats', 'Strategy, Work, Operation, Target', 'Sales, Warehousing, Organization, Trade', 'System, Workforce, Output, Technology'],
      correctOptionIndex: 0,
      explanation: 'SWOT mengidentifikasi Kekuatan (Strengths), Kelemahan (Weaknesses), Peluang (Opportunities), dan Ancaman (Threats).',
    ),
    QuestionItem(
      id: 'mnj_003',
      questionText: 'Dalam analisis SWOT, faktor internal perusahaan yang dapat dikendalikan langsung adalah:',
      options: ['Strengths dan Weaknesses', 'Opportunities dan Threats', 'Strengths dan Opportunities', 'Weaknesses dan Threats'],
      correctOptionIndex: 0,
      explanation: 'Kekuatan dan Kelemahan bersifat internal perusahaan.',
    ),
    QuestionItem(
      id: 'mnj_004',
      questionText: 'Strategi pemasarana 4P konvensional mencakup:',
      options: ['Product, Price, Place, Promotion', 'People, Process, Profit, Product', 'Plan, Positioning, Public, Price', 'Product, Packaging, Promotion, Payment'],
      correctOptionIndex: 0,
      explanation: 'Bauran pemasaran 4P: Produk (Product), Harga (Price), Tempat (Place), Promosi (Promotion).',
    ),
    QuestionItem(
      id: 'mnj_005',
      questionText: 'Strategi pemasaran 7P untuk industri jasa menambahkan 3 elemen dari 4P yaitu:',
      options: ['People, Process, Physical Evidence', 'Profit, Plan, Position', 'Packaging, Public, Public Relation', 'Performance, Platform, Payment'],
      correctOptionIndex: 0,
      explanation: 'Bauran jasa (7P): 4P + Orang (People), Proses (Process), Bukti Fisik (Physical Evidence).',
    ),
    QuestionItem(
      id: 'mnj_006',
      questionText: 'Tahapan STP dalam manajemen pemasaran secara berurutan adalah:',
      options: ['Segmenting, Targeting, Positioning', 'Selling, Testing, Promoting', 'Searching, Tracking, Placement', 'Sorting, Timing, Packaging'],
      correctOptionIndex: 0,
      explanation: 'STP: Segmentasi Pasar -> Penentuan Target -> Posisi Pasar (Positioning).',
    ),
    QuestionItem(
      id: 'mnj_007',
      questionText: 'Titik impas di mana total pendapatan sama dengan total biaya (tidak rugi dan tidak untung) dinamakan:',
      options: ['Break-Even Point (BEP)', 'Payback Period', 'Return on Investment', 'Net Profit Margin'],
      correctOptionIndex: 0,
      explanation: 'BEP adalah titik impas saat Pendapatan = Total Biaya.',
    ),
    QuestionItem(
      id: 'mnj_008',
      questionText: 'Biaya yang jumlahnya tetap sama tidak terpengaruh oleh volume produksi dinamakan:',
      options: ['Biaya Tetap (Fixed Cost)', 'Biaya Variabel', 'Biaya Marjinal', 'Biaya Semivariabel'],
      correctOptionIndex: 0,
      explanation: 'Fixed Cost (seperti sewa gedung) nilainya konstan.',
    ),
    QuestionItem(
      id: 'mnj_009',
      questionText: 'Biaya yang jumlahnya berubah-ubah secara proporsional sesuai dengan volume produksi dinamakan:',
      options: ['Biaya Variabel (Variable Cost)', 'Biaya Tetap', 'Biaya Overhead', 'Biaya Tertanam'],
      correctOptionIndex: 0,
      explanation: 'Variable Cost (seperti bahan baku) naik turun seiring output produksi.',
    ),
    QuestionItem(
      id: 'mnj_010',
      questionText: 'Struktur organisasi di mana wewenang mengalir langsung secara vertikal dari atasan ke bawahan dinamakan struktur:',
      options: ['Lini / Garis', 'Matriks', 'Fungsional', 'Proyek'],
      correctOptionIndex: 0,
      explanation: 'Struktur lini memiliki rantai komando lurus vertikal.',
    ),
    QuestionItem(
      id: 'mnj_011',
      questionText: 'Struktur organisasi yang mengombinasikan manajer fungsional dan manajer proyek dinamakan struktur:',
      options: ['Matriks', 'Lini', 'Divisional', 'Hirarkis'],
      correctOptionIndex: 0,
      explanation: 'Struktur matriks menempatkan karyawan di bawah pelaporan ganda (fungsional & proyek).',
    ),
    QuestionItem(
      id: 'mnj_012',
      questionText: 'Gaya kepemimpinan yang memberi kebebasan penuh kepada bawahan untuk mengambil keputusan dinamakan gaya:',
      options: ['Laissez-Faire', 'Otokratis', 'Demokratis', 'Transaksional'],
      correctOptionIndex: 0,
      explanation: 'Laissez-Faire memberi otonomi penuh (delegatif) pada tim.',
    ),
    QuestionItem(
      id: 'mnj_013',
      questionText: 'Gaya kepemimpinan pemusatan kekuasaan mutlak pada satu pemimpin tanpa melibatkan bawahan dinamakan gaya:',
      options: ['Otokratis (Autocratic)', 'Demokratis', 'Transformasional', 'Laissez-Faire'],
      correctOptionIndex: 0,
      explanation: 'Otokratis memegang kendali pengambilan keputusan terpusat tunggal.',
    ),
    QuestionItem(
      id: 'mnj_014',
      questionText: 'Gaya kepemimpinan yang menginspirasi dan memotivasi anggota untuk berinovasi mengubah masa depan dinamakan gaya:',
      options: ['Transformasional', 'Transaksional', 'Otokratis', 'Birokratis'],
      correctOptionIndex: 0,
      explanation: 'Pemimpin transformasional menginspirasi visi perubahan besar.',
    ),
    QuestionItem(
      id: 'mnj_015',
      questionText: 'Gaya kepemimpinan yang mengandalkan sistem imbalan (reward) dan hukuman (punishment) dinamakan gaya:',
      options: ['Transaksional', 'Transformasional', 'Servant Leadership', 'Karismatik'],
      correctOptionIndex: 0,
      explanation: 'Kepemimpinan transaksional berbasis transaksi tugas dan imbalan/hukuman.',
    ),
    QuestionItem(
      id: 'mnj_016',
      questionText: 'Teori Hierarki Kebutuhan Manusia dikembangkan oleh psikolog manajemen terkenal bernama:',
      options: ['Abraham Maslow', 'Frederick Herzberg', 'Douglas McGregor', 'Elton Mayo'],
      correctOptionIndex: 0,
      explanation: 'Abraham Maslow mencetuskan hierarki 5 tingkat kebutuhan manusia.',
    ),
    QuestionItem(
      id: 'mnj_017',
      questionText: 'Tingkatan kebutuhan paling puncak pada Piramida Maslow adalah kebutuhan:',
      options: ['Aktualisasi Diri (Self-Actualization)', 'Fisiologis', 'Rasa Aman', 'Penghargaan (Esteem)'],
      correctOptionIndex: 0,
      explanation: 'Aktualisasi diri berada di puncak piramida kebutuhan Maslow.',
    ),
    QuestionItem(
      id: 'mnj_018',
      questionText: 'Teori X dan Teori Y mengenai perilaku kerja karyawan dirumuskan oleh:',
      options: ['Douglas McGregor', 'Maslow', 'Herzberg', 'Taylor'],
      correctOptionIndex: 0,
      explanation: 'McGregor menggolongkan persepsi pekerja malas (Teori X) dan mandiri (Teori Y).',
    ),
    QuestionItem(
      id: 'mnj_019',
      questionText: 'Bapak Manajemen Ilmiah (Scientific Management) yang memelopori studi waktu dan gerak adalah:',
      options: ['Frederick Winslow Taylor', 'Henry Fayol', 'Max Weber', 'Peter Drucker'],
      correctOptionIndex: 0,
      explanation: 'F.W. Taylor adalah Bapak Manajemen Ilmiah.',
    ),
    QuestionItem(
      id: 'mnj_020',
      questionText: 'Bapak Manajemen Modern yang memperkenalkan konsep MBO (Management by Objectives) adalah:',
      options: ['Peter F. Drucker', 'Henry Fayol', 'Philip Kotler', 'Michael Porter'],
      correctOptionIndex: 0,
      explanation: 'Peter Drucker adalah Bapak Manajemen Modern perancang MBO.',
    ),
    QuestionItem(
      id: 'mnj_021',
      questionText: 'Strategi 5 Kekuatan Bersaing (Porter\'s Five Forces) dirumuskan oleh ahli strategi:',
      options: ['Michael Porter', 'Philip Kotler', 'Peter Drucker', 'Igor Ansoff'],
      correctOptionIndex: 0,
      explanation: 'Michael Porter merumuskan model analisis industri Five Forces.',
    ),
    QuestionItem(
      id: 'mnj_022',
      questionText: 'Manakah yang BUKAN merupakan elemen dari Porter\'s Five Forces?',
      options: ['Ancaman Produk Substitusi', 'Daya Tawar Pembeli', 'Daya Tawar Pemasok', 'Tingkat Inflasi Negara'],
      correctOptionIndex: 3,
      explanation: 'Inflasi adalah faktor makro ekonomi, bukan komponen Five Forces.',
    ),
    QuestionItem(
      id: 'mnj_023',
      questionText: 'Strategi generik Porter yang berfokus menjadi produsen berbiaya paling rendah di industri dinamakan:',
      options: ['Keunggulan Biaya (Cost Leadership)', 'Diferensiasi', 'Fokus', 'Inovasi'],
      correctOptionIndex: 0,
      explanation: 'Cost Leadership berfokus pada efisiensi biaya terendah.',
    ),
    QuestionItem(
      id: 'mnj_024',
      questionText: 'Strategi generik Porter yang menawarkan produk unik dan bernilai tambah tinggi dibanding pesaing dinamakan:',
      options: ['Diferensiasi (Differentiation)', 'Cost Leadership', 'Fokus Biaya', 'Diversifikasi'],
      correctOptionIndex: 0,
      explanation: 'Diferensiasi menciptakan keunikan fitur/kualitas produk.',
    ),
    QuestionItem(
      id: 'mnj_025',
      questionText: 'Matriks BCG (Boston Consulting Group) mengelompokkan unit bisnis berdasarkan pasar ke dalam 4 kuadran yaitu:',
      options: ['Star, Cash Cow, Question Mark, Dog', 'High, Medium, Low, Zero', 'Leader, Challenger, Follower, Nicher', 'Strength, Weakness, Opportunity, Threat'],
      correctOptionIndex: 0,
      explanation: 'Kuadran BCG: Bintang (Star), Sapi Perah (Cash Cow), Tanda Tanya (Question Mark), Anjing (Dog).',
    ),
    QuestionItem(
      id: 'mnj_026',
      questionText: 'Dalam Matriks BCG, unit bisnis dengan pangsa pasar tinggi di industri yang pertumbuhannya lambat dinamakan:',
      options: ['Cash Cow (Sapi Perah)', 'Star', 'Question Mark', 'Dog'],
      correctOptionIndex: 0,
      explanation: 'Cash Cow menghasilkan arus kas limpas stabil.',
    ),
    QuestionItem(
      id: 'mnj_027',
      questionText: 'Manajemen persediaan barang yang tiba tepat saat dibutuhkan produksi tanpa penumpukan gudang dinamakan:',
      options: ['Just-In-Time (JIT)', 'Economic Order Quantity (EOQ)', 'Kanban', 'Safety Stock'],
      correctOptionIndex: 0,
      explanation: 'JIT meminimalkan biaya penyimpanan gudang hingga mendekati nol.',
    ),
    QuestionItem(
      id: 'mnj_028',
      questionText: 'Metode perhitungan jumlah pemesanan bahan baku paling ekonomis untuk meminimalkan total biaya simpan dan pesan dinamakan:',
      options: ['EOQ (Economic Order Quantity)', 'JIT', 'ABC Analysis', 'Reorder Point'],
      correctOptionIndex: 0,
      explanation: 'EOQ menghitung kuantitas pesanan optimal.',
    ),
    QuestionItem(
      id: 'mnj_029',
      questionText: 'Batas tingkat persediaan barang minimum yang memicu pesanan ulang bahan baku dinamakan:',
      options: ['Reorder Point (ROP)', 'Safety Stock', 'Buffer Stock', 'Maximum Inventory'],
      correctOptionIndex: 0,
      explanation: 'ROP = (Laju Penggunaan x Lead Time) + Safety Stock.',
    ),
    QuestionItem(
      id: 'mnj_030',
      questionText: 'Filosofi manajemen kualitas Jepang yang menekankan perbaikan berkesinambungan secara terus-menerus dinamakan:',
      options: ['Kaizen', 'Kanban', 'Poka-Yoke', 'Seiri'],
      correctOptionIndex: 0,
      explanation: 'Kaizen berarti perbaikan berkesinambungan bertahap.',
    ),
    QuestionItem(
      id: 'mnj_031',
      questionText: 'Metode manajemen mutu 5S dari Jepang mencakup:',
      options: ['Seiri, Seiton, Seiso, Seiketsu, Shitsuke', 'Siri, Sato, Sama, Sugi, Soto', 'Sort, Set, Shine, Standard, Sustain', 'Jawaban A dan C Benar'],
      correctOptionIndex: 3,
      explanation: '5S (Ringkas, Rapi, Resik, Rawat, Rajin / Sort, Set, Shine, Standardize, Sustain).',
    ),
    QuestionItem(
      id: 'mnj_032',
      questionText: 'Metode kendali mutu Six Sigma menargetkan tingkat cacat produk maksimum sebesar:',
      options: ['3.4 Cacat per Sejuta Kesempatan (DPMO)', '1 Cacat per Seratus', '5% Cacat', '0 Cacat'],
      correctOptionIndex: 0,
      explanation: 'Six Sigma mencapai akurasi 99.99966% (3.4 DPMO).',
    ),
    QuestionItem(
      id: 'mnj_033',
      questionText: 'Tahapan metodologi Six Sigma DMAIC adalah singkatan dari:',
      options: ['Define, Measure, Analyze, Improve, Control', 'Design, Manufacture, Assemble, Inspect, Check', 'Data, Model, Algorithm, Implementation, Code', 'Direct, Manage, Act, Integrate, Comply'],
      correctOptionIndex: 0,
      explanation: 'DMAIC: Define -> Measure -> Analyze -> Improve -> Control.',
    ),
    QuestionItem(
      id: 'mnj_034',
      questionText: 'Rantai pasok (Supply Chain Management) mencakup aliran terintegrasi dari:',
      options: ['Pemasok Bahan Baku -> Pabrik -> Distributor -> Pengecer -> Konsumen Akhir', 'Konsumen -> Pabrik', 'Sales -> Marketing', 'Toko -> Kasir'],
      correctOptionIndex: 0,
      explanation: 'SCM mengelola alur produk dari supplier hingga end-user.',
    ),
    QuestionItem(
      id: 'mnj_035',
      questionText: 'Fenomena pembesaran fluktuasi permintaan barang di sepanjang rantai pasok dari pengecer ke pabrik dinamakan:',
      options: ['Bullwhip Effect', 'Snowball Effect', 'Ripple Effect', 'Bottleneck'],
      correctOptionIndex: 0,
      explanation: 'Bullwhip Effect memicu distorsi ketidakpastian persediaan di tingkat manufaktur.',
    ),
    QuestionItem(
      id: 'mnj_036',
      questionText: 'Proses merekrut, menyeleksi, melatih, dan mengevaluasi kinerja karyawan dalam perusahaan dinamakan:',
      options: ['Manajemen Sumber Daya Manusia (MSDM)', 'Manajemen Operasional', 'Public Relations', 'General Affair'],
      correctOptionIndex: 0,
      explanation: 'MSDM mengelola aset modal manusia (human capital).',
    ),
    QuestionItem(
      id: 'mnj_037',
      questionText: 'Proses pengumpulan informasi detail mengenai tugas, tanggung jawab, dan kualifikasi suatu jabatan dinamakan:',
      options: ['Analisis Jabatan (Job Analysis)', 'Deskripsi Kerja', 'Spesifikasi Kerja', 'Evaluasi Kerja'],
      correctOptionIndex: 0,
      explanation: 'Job Analysis menghasilkan Uraian Jabatan (Job Description) dan Spesifikasi Jabatan (Job Specification).',
    ),
    QuestionItem(
      id: 'mnj_038',
      questionText: 'Dokumen yang menjelaskan tugas, wewenang, dan tanggung jawab posisi pekerjaan dinamakan:',
      options: ['Job Description (Deskripsi Pekerjaan)', 'Job Specification', 'Job Enrichement', 'Job Enlargement'],
      correctOptionIndex: 0,
      explanation: 'Job description memuat gambaran tugas jabatan.',
    ),
    QuestionItem(
      id: 'mnj_039',
      questionText: 'Dokumen yang memuat syarat kualifikasi minimal karyawan (seperti pendidikan dan pengalaman) dinamakan:',
      options: ['Job Specification (Spesifikasi Pekerjaan)', 'Job Description', 'Job Rotation', 'Job Evaluation'],
      correctOptionIndex: 0,
      explanation: 'Job specification memuat kualifikasi SDM yang dibutuhkan.',
    ),
    QuestionItem(
      id: 'mnj_040',
      questionText: 'Strategi memperluas cakupan tugas karyawan secara horisontal dinamakan:',
      options: ['Job Enlargement', 'Job Enrichment', 'Job Rotation', 'Job Sharing'],
      correctOptionIndex: 0,
      explanation: 'Job enlargement menambah variasi tugas selevel.',
    ),
    QuestionItem(
      id: 'mnj_041',
      questionText: 'Strategi memberi tanggung jawab dan wewenang lebih tinggi secara vertikal kepada karyawan dinamakan:',
      options: ['Job Enrichment', 'Job Enlargement', 'Job Rotation', 'Outsourcing'],
      correctOptionIndex: 0,
      explanation: 'Job enrichment memperdalam otonomi dan tantangan kerja.',
    ),
    QuestionItem(
      id: 'mnj_042',
      questionText: 'Praktik memindahkan karyawan dari satu departemen ke departemen lain secara berkala dinamakan:',
      options: ['Rotasi Kerja (Job Rotation)', 'Promosi', 'Mutasi', 'Demosi'],
      correctOptionIndex: 0,
      explanation: 'Job rotation menambah wawasan serbaguna karyawan.',
    ),
    QuestionItem(
      id: 'mnj_043',
      questionText: 'Pemindahan karyawan ke posisi jabatan yang lebih tinggi disertai kenaikan gaji dan tanggung jawab dinamakan:',
      options: ['Promosi', 'Rotasi', 'Demosi', 'Transfer'],
      correctOptionIndex: 0,
      explanation: 'Promosi mengangkat jenjang karir karyawan.',
    ),
    QuestionItem(
      id: 'mnj_044',
      questionText: 'Pemindahan karyawan ke posisi posisi jabatan yang lebih rendah dinamakan:',
      options: ['Demosi', 'Promosi', 'Mutasi', 'Layoff'],
      correctOptionIndex: 0,
      explanation: 'Demosi menurunkan tingkat jabatan.',
    ),
    QuestionItem(
      id: 'mnj_045',
      questionText: 'Praktik menyerahkan sebagian pekerjaan operasional perusahaan ke pihak ketiga di luar perusahaan dinamakan:',
      options: ['Outsourcing (Alih Daya)', 'Insourcing', 'Offshoring', 'Joint Venture'],
      correctOptionIndex: 0,
      explanation: 'Outsourcing mengalihkan tugas non-inti ke vendor penyedia jasa.',
    ),
    QuestionItem(
      id: 'mnj_046',
      questionText: 'Tingkat pengunduran diri karyawan yang keluar dari perusahaan dalam periode tertentu dinamakan:',
      options: ['Turnover Rate', 'Retention Rate', 'Absenteisme', 'Burnout Rate'],
      correctOptionIndex: 0,
      explanation: 'Turnover rate mengukur persentase pergantian keluar-masuk karyawan.',
    ),
    QuestionItem(
      id: 'mnj_047',
      questionText: 'Kondisi kelelahan fisik dan emosional kronis akibat stres pekerjaan berkepanjangan dinamakan:',
      options: ['Burnout', 'Boredom', 'Workaholism', 'Turnover'],
      correctOptionIndex: 0,
      explanation: 'Burnout merusak produktivitas dan kesejahteraan mental pekerja.',
    ),
    QuestionItem(
      id: 'mnj_048',
      questionText: 'Upaya perusahaan membentuk reputasi sebagai tempat kerja yang menarik bagi calon talenta dinamakan:',
      options: ['Employer Branding', 'Corporate Branding', 'Public Relations', 'Recruitment Ads'],
      correctOptionIndex: 0,
      explanation: 'Employer branding memikat pencari kerja berbakat.',
    ),
    QuestionItem(
      id: 'mnj_049',
      questionText: 'Pemberian kompensasi imbalan finansial tambahan berdasarkan pencapaian target kinerja dinamakan:',
      options: ['Bonus / Insentif Kinerja', 'Gaji Pokok', 'Tunjangan Tetap', 'Pesangon'],
      correctOptionIndex: 0,
      explanation: 'Insentif mendorong motivasi prestasi karyawan.',
    ),
    QuestionItem(
      id: 'mnj_050',
      questionText: 'Hak kepemilikan saham perusahaan yang diberikan kepada karyawan sebagai kompensasi dinamakan:',
      options: ['ESOP (Employee Stock Option Plan)', 'Dividen', 'Capital Gain', 'Bonus Retensi'],
      correctOptionIndex: 0,
      explanation: 'ESOP memberikan opsi saham bagi karyawan.',
    ),
    QuestionItem(
      id: 'mnj_051',
      questionText: 'Tanggung jawab sosial perusahaan terhadap lingkungan dan masyarakat sekitar dinamakan:',
      options: ['CSR (Corporate Social Responsibility)', 'ESG', 'GGC', 'ISO 9001'],
      correctOptionIndex: 0,
      explanation: 'CSR adalah komitmen etis kepedulian sosial perusahaan.',
    ),
    QuestionItem(
      id: 'mnj_052',
      questionText: 'Prinsip tata kelola perusahaan yang baik dikenal dengan istilah GCG, singkatan dari:',
      options: ['Good Corporate Governance', 'Global Company Growth', 'General Corporate Group', 'Good Commercial Goods'],
      correctOptionIndex: 0,
      explanation: 'GCG mencakup Transparansi, Akuntabilitas, Responsibilitas, Independensi, dan Keadilan (TARIF).',
    ),
    QuestionItem(
      id: 'mnj_053',
      questionText: 'Lima prinsip utama GCG (TARIF) mencakup:',
      options: ['Transparency, Accountability, Responsibility, Independency, Fairness', 'Time, Action, Risk, Investment, Finance', 'Trust, Attitude, Respect, Innovation, Focus', 'Trade, Asset, Return, Income, Fund'],
      correctOptionIndex: 0,
      explanation: 'TARIF: Transparansi, Akuntabilitas, Responsibilitas, Independensi, Keadilan.',
    ),
    QuestionItem(
      id: 'mnj_054',
      questionText: 'Strategi ekspansi perusahaan dengan memasuki lini bisnis baru yang berbeda dari bisnis inti dinamakan:',
      options: ['Diversifikasi', 'Diferensiasi', 'Penetrasi Pasar', 'Pengembangan Produk'],
      correctOptionIndex: 0,
      explanation: 'Diversifikasi menyebarkan risiko usaha ke berbagai industri.',
    ),
    QuestionItem(
      id: 'mnj_055',
      questionText: 'Penggabungan dua atau lebih perusahaan menjadi satu entitas baru dinamakan:',
      options: ['Merger', 'Akuisisi', 'Konsolidasi', 'Joint Venture'],
      correctOptionIndex: 0,
      explanation: 'Merger menyatukan perusahaan seimbang menjadi satu entitas baru.',
    ),
    QuestionItem(
      id: 'mnj_056',
      questionText: 'Pengambilalihan kepemilikan saham pengendali suatu perusahaan oleh perusahaan lain dinamakan:',
      options: ['Akuisisi (Acquisition)', 'Merger', 'Franchise', 'Spin-off'],
      correctOptionIndex: 0,
      explanation: 'Akuisisi membeli saham mayoritas perusahaan target.',
    ),
    QuestionItem(
      id: 'mnj_057',
      questionText: 'Kerja sama usaha dua perusahaan independen membentuk entitas bisnis baru bersama dinamakan:',
      options: ['Joint Venture', 'Franchise', 'Lisensi', 'Kartel'],
      correctOptionIndex: 0,
      explanation: 'Joint Venture mendirikan perusahaan konsorsium bersama.',
    ),
    QuestionItem(
      id: 'mnj_058',
      questionText: 'Model bisnis kemitraan dengan memberi hak izin penggunaan merek dan sistem operasional dinamakan:',
      options: ['Waralaba (Franchise)', 'Lisensi', 'Outsourcing', 'Agency'],
      correctOptionIndex: 0,
      explanation: 'Franchisor menjual lisensi merek dan sistem ke Franchisee.',
    ),
    QuestionItem(
      id: 'mnj_059',
      questionText: 'Metode penilaian portofolio produk berdasarkan tingkat pertumbuhan pasar dan pangsa pasar dinamakan Matriks:',
      options: ['BCG Matrix', 'Ansoff Matrix', 'GE McKinsey Matrix', 'TOWS Matrix'],
      correctOptionIndex: 0,
      explanation: 'Matriks BCG mengevaluasi portofolio bisnis.',
    ),
    QuestionItem(
      id: 'mnj_060',
      questionText: 'Matriks Strategi Pertumbuhan Produk-Pasar (Penetrasi Pasar, Pengembangan Produk, Pengembangan Pasar, Diversifikasi) dirumuskan oleh:',
      options: ['Igor Ansoff (Ansoff Matrix)', 'Michael Porter', 'Philip Kotler', 'Boston Group'],
      correctOptionIndex: 0,
      explanation: 'Ansoff Matrix memetakan strategi pertumbuhan pasar-produk.',
    ),
    QuestionItem(
      id: 'mnj_061',
      questionText: 'Strategi Ansoff menjual produk yang sudah ada ke pasar baru yang belum terambah dinamakan:',
      options: ['Pengembangan Pasar (Market Development)', 'Penetrasi Pasar', 'Pengembangan Produk', 'Diversifikasi'],
      correctOptionIndex: 0,
      explanation: 'Market development membawa produk eksis ke wilayah geografis baru.',
    ),
    QuestionItem(
      id: 'mnj_062',
      questionText: 'Strategi Ansoff meluncurkan produk baru untuk pelanggan di pasar yang sudah ada dinamakan:',
      options: ['Pengembangan Produk (Product Development)', 'Penetrasi Pasar', 'Pengembangan Pasar', 'Diversifikasi'],
      correctOptionIndex: 0,
      explanation: 'Product development membuat varian produk baru bagi pelanggan eksis.',
    ),
    QuestionItem(
      id: 'mnj_063',
      questionText: 'Penyebab terjadinya hambatan kemacetan alur produksi dinamakan:',
      options: ['Bottleneck (Leher Botol)', 'Lead Time', 'Cycle Time', 'Idle Time'],
      correctOptionIndex: 0,
      explanation: 'Bottleneck membatasi kapasitas maksimum seluruh sistem produksi.',
    ),
    QuestionItem(
      id: 'mnj_064',
      questionText: 'Total waktu yang dibutuhkan sejak pemesanan pelanggan diterima hingga barang diserahkan dinamakan:',
      options: ['Lead Time', 'Cycle Time', 'Takt Time', 'Setup Time'],
      correctOptionIndex: 0,
      explanation: 'Lead Time mencakup seluruh durasi pemrosesan dan pengiriman.',
    ),
    QuestionItem(
      id: 'mnj_065',
      questionText: 'Waktu rata-rata yang dibutuhkan untuk menyelesaikan satu unit produk pada stasiun kerja dinamakan:',
      options: ['Cycle Time', 'Lead Time', 'Down Time', 'Wait Time'],
      correctOptionIndex: 0,
      explanation: 'Cycle time mengukur durasi pemrosesan per unit.',
    ),
    QuestionItem(
      id: 'mnj_066',
      questionText: 'Kecepatan produksi yang dibutuhkan untuk memenuhi tingkat permintaan pelanggan dinamakan:',
      options: ['Takt Time', 'Cycle Time', 'Lead Time', 'Run Time'],
      correctOptionIndex: 0,
      explanation: 'Takt Time = Jam Kerja Efektif / Jumlah Permintaan Pelanggan.',
    ),
    QuestionItem(
      id: 'mnj_067',
      questionText: 'Waktu henti operasional mesin akibat kerusakan atau pemeliharaan dinamakan:',
      options: ['Downtime', 'Uptime', 'Idle Time', 'Setup Time'],
      correctOptionIndex: 0,
      explanation: 'Downtime menghentikan kontinuitas produksi pabrik.',
    ),
    QuestionItem(
      id: 'mnj_068',
      questionText: 'Pemeliharaan terencana yang dilakukan secara berkala untuk mencegah kerusakan mesin dinamakan:',
      options: ['Preventive Maintenance', 'Breakdown Maintenance', 'Predictive Maintenance', 'Corrective Maintenance'],
      correctOptionIndex: 0,
      explanation: 'Preventive Maintenance mencegah timbulnya downtime mendadak.',
    ),
    QuestionItem(
      id: 'mnj_069',
      questionText: 'Pemeliharaan yang dilakukan setelah mesin mengalami kerusakan fisik dinamakan:',
      options: ['Corrective / Breakdown Maintenance', 'Preventive Maintenance', 'Predictive Maintenance', 'Total Productive Maintenance'],
      correctOptionIndex: 0,
      explanation: 'Corrective maintenance memperbaiki mesin pasca gangguan.',
    ),
    QuestionItem(
      id: 'mnj_070',
      questionText: 'Pendekatan pemeliharaan mesin terpadu yang melibatkan seluruh operator kerja pabrik dinamakan TPM, yaitu:',
      options: ['Total Productive Maintenance', 'Total Process Management', 'Total Quality Control', 'Total Performance Matrix'],
      correctOptionIndex: 0,
      explanation: 'TPM memaksimalkan efektivitas peralatan kerja pabrik.',
    ),
    QuestionItem(
      id: 'mnj_071',
      questionText: 'Matriks evaluasi kualitatif SWOT yang menghasilkan 4 sel kombinasi strategi SO, WO, ST, WT dinamakan:',
      options: ['Matriks TOWS / SWOT', 'Matriks Ansoff', 'Matriks BCG', 'Matriks Grand Strategy'],
      correctOptionIndex: 0,
      explanation: 'Matriks TOWS mencocokkan faktor internal dan eksternal.',
    ),
    QuestionItem(
      id: 'mnj_072',
      questionText: 'Kombinasi strategi TOWS yang memanfaatkan kekuatan internal untuk menangkap peluang eksternal adalah:',
      options: ['Strategi SO (Strengths - Opportunities)', 'Strategi WO', 'Strategi ST', 'Strategi WT'],
      correctOptionIndex: 0,
      explanation: 'Strategi SO adalah strategi agresif memanfaatkan keunggulan.',
    ),
    QuestionItem(
      id: 'mnj_073',
      questionText: 'Strategi TOWS yang meminimalkan kelemahan internal untuk menghindari ancaman eksternal dinamakan:',
      options: ['Strategi WT (Weaknesses - Threats)', 'Strategi SO', 'Strategi WO', 'Strategi ST'],
      correctOptionIndex: 0,
      explanation: 'Strategi WT adalah posisi bertahan (defensif).',
    ),
    QuestionItem(
      id: 'mnj_074',
      questionText: 'Peta rantai nilai internal perusahaan yang membagi aktivitas menjadi aktivitas utama dan pendukung dikembangkan oleh:',
      options: ['Michael Porter (Value Chain Analysis)', 'Peter Drucker', 'Philip Kotler', 'Henry Mintzberg'],
      correctOptionIndex: 0,
      explanation: 'Porter\'s Value Chain memetakan alur penciptaan nilai tambah.',
    ),
    QuestionItem(
      id: 'mnj_075',
      questionText: 'Manakah yang termasuk Aktivitas Utama (Primary Activities) dalam Porter\'s Value Chain?',
      options: ['Inbound Logistics, Operations, Outbound Logistics, Marketing & Sales, Service', 'Infrastruktur Perusahaan', 'Manajemen SDM', 'Pengembangan Teknologi'],
      correctOptionIndex: 0,
      explanation: '5 Aktivitas utama Value Chain Porter secara langsung menciptakan produk/jasa.',
    ),
    QuestionItem(
      id: 'mnj_076',
      questionText: 'Gaya kepemimpinan berbasis pelayanan yang mengutamakan kebutuhan dan pertumbuhan anggota tim dinamakan:',
      options: ['Servant Leadership', 'Autocratic Leadership', 'Bureaucratic Leadership', 'Transactional Leadership'],
      correctOptionIndex: 0,
      explanation: 'Servant Leadership memposisikan pemimpin sebagai pelayan anggota.',
    ),
    QuestionItem(
      id: 'mnj_077',
      questionText: 'Teori kepemimpinan situasi yang menyatakan gaya kepemimpinan harus disesuaikan dengan tingkat kesiapan/kematangan bawahan dirumuskan oleh:',
      options: ['Hersey dan Blanchard (Situational Leadership)', 'Fiedler', 'Blake dan Mouton', 'Kotter'],
      correctOptionIndex: 0,
      explanation: 'Hersey-Blanchard membagi 4 gaya: Telling, Selling, Participating, Delegating.',
    ),
    QuestionItem(
      id: 'mnj_078',
      questionText: 'Metode penganggaran di mana setiap alokasi biaya harus dijustifikasi dari nol setiap awal periode dinamakan:',
      options: ['Zero-Based Budgeting (ZBB)', 'Incremental Budgeting', 'Flexible Budgeting', 'Activity-Based Budgeting'],
      correctOptionIndex: 0,
      explanation: 'ZBB mengharuskan penyusunan anggaran dari Rp 0 tanpa mengacu periode lalu.',
    ),
    QuestionItem(
      id: 'mnj_079',
      questionText: 'Proses membandingkan performa bisnis dan proses internal perusahaan dengan standar terbaik industri (Best Practice) dinamakan:',
      options: ['Benchmarking', 'Balanced Scorecard', 'Auditing', 'Re-engineering'],
      correctOptionIndex: 0,
      explanation: 'Benchmarking mengacu pada pencapaian standar industri terbaik.',
    ),
    QuestionItem(
      id: 'mnj_080',
      questionText: 'Sistem manajemen strategis Balanced Scorecard (BSC) menilai kinerja perusahaan dari 4 perspektif yaitu:',
      options: ['Keuangan, Pelanggan, Proses Bisnis Internal, Pembelajaran & Pertumbuhan', 'Penjualan, Biaya, Untung, Rugi', 'Visi, Misi, Aksi, Hasil', 'SDM, Mesin, Metode, Material'],
      correctOptionIndex: 0,
      explanation: 'Kaplan & Norton merumuskan 4 perspektif BSC.',
    ),
    QuestionItem(
      id: 'mnj_081',
      questionText: 'Perancangan ulang proses bisnis secara radikal untuk mencapai lompatan kinerja dramatis dinamakan:',
      options: ['Business Process Reengineering (BPR)', 'Kaizen', 'TQM', 'Six Sigma'],
      correctOptionIndex: 0,
      explanation: 'BPR meredesain total alur kerja bisnis secara fundamental.',
    ),
    QuestionItem(
      id: 'mnj_082',
      questionText: 'Manajemen Kualitas Total yang melibatkan seluruh elemen organisasi untuk menjaga kepuasan pelanggan dikenal dengan istilah:',
      options: ['TQM (Total Quality Management)', 'TQM', 'ISO 9001', 'Six Sigma'],
      correctOptionIndex: 0,
      explanation: 'TQM memfokuskan peningkatan mutu menyeluruh di setiap departemen.',
    ),
    QuestionItem(
      id: 'mnj_083',
      questionText: 'Sertifikasi sistem manajemen mutu internasional yang diterbitkan oleh ISO adalah:',
      options: ['ISO 9001', 'ISO 14001', 'ISO 45001', 'ISO 27001'],
      correctOptionIndex: 0,
      explanation: 'ISO 9001 adalah standar internasional Quality Management System.',
    ),
    QuestionItem(
      id: 'mnj_084',
      questionText: 'Sertifikasi internasional untuk Sistem Manajemen Lingkungan pabrik/perusahaan adalah:',
      options: ['ISO 14001', 'ISO 9001', 'ISO 22000', 'ISO 50001'],
      correctOptionIndex: 0,
      explanation: 'ISO 14001 mengatur standar pengolahan lingkungan hidup.',
    ),
    QuestionItem(
      id: 'mnj_085',
      questionText: 'Sertifikasi internasional untuk Sistem Manajemen Keselamatan dan Kesehatan Kerja (K3) adalah:',
      options: ['ISO 45001', 'ISO 9001', 'ISO 14001', 'ISO 26000'],
      correctOptionIndex: 0,
      explanation: 'ISO 45001 acuan K3 tempat kerja.',
    ),
    QuestionItem(
      id: 'mnj_086',
      questionText: 'Tingkat pergantian manajer puncak yang diangkat dari luar perusahaan versus promosi internal dinamakan strategi:',
      options: ['Suksesi Kepemimpinan (Succession Planning)', 'Talent Management', 'Headhunting', 'Executive Search'],
      correctOptionIndex: 0,
      explanation: 'Perencanaan suksesi merancang calon pengganti posisi pimpinan kunci.',
    ),
    QuestionItem(
      id: 'mnj_087',
      questionText: 'Agensi perekrutan khusus yang bertugas berburu eksekutif tingkat atas untuk perusahaan dinamakan:',
      options: ['Headhunter / Executive Search', 'Outsourcing Agency', 'Job Portal', 'Outplacement'],
      correctOptionIndex: 0,
      explanation: 'Headhunter mencari kandidat eksekutif manajerial spesifik.',
    ),
    QuestionItem(
      id: 'mnj_088',
      questionText: 'Metode penilaian kinerja karyawan yang melibatkan umpan balik dari atasan, rekan kerja, bawahan, dan diri sendiri dinamakan:',
      options: ['Penilaian 360 Derajat (360-Degree Feedback)', 'Management by Objectives', 'Graphic Rating Scale', 'Critical Incident'],
      correctOptionIndex: 0,
      explanation: 'Umpan balik 360 derajat mengumpulkan perspektif komprehensif sekeliling karyawan.',
    ),
    QuestionItem(
      id: 'mnj_089',
      questionText: 'Survei tingkat keterikatan dan komitmen emosional karyawan terhadap organisasi dinamakan:',
      options: ['Employee Engagement Survey', 'Job Satisfaction Index', 'Exit Interview', 'Turnover Audit'],
      correctOptionIndex: 0,
      explanation: 'Employee engagement mengukur dedikasi dan keterikatan emosi pekerja.',
    ),
    QuestionItem(
      id: 'mnj_090',
      questionText: 'Wawancara yang dilakukan terhadap karyawan yang memutuskan berhenti bekerja dinamakan:',
      options: ['Exit Interview', 'Behavioral Interview', 'Stress Interview', 'Screening Interview'],
      correctOptionIndex: 0,
      explanation: 'Exit interview menggali alasan pengunduran diri untuk perbaikan internal.',
    ),
    QuestionItem(
      id: 'mnj_091',
      questionText: 'Bentuk pemasaran dari mulut ke mulut di era digital dinamakan:',
      options: ['Word of Mouth (WOM) / Viral Marketing', 'Direct Mail', 'Telemarketing', 'BTL Marketing'],
      correctOptionIndex: 0,
      explanation: 'WOM & Viral Marketing memanfaatkan rekomendasi ulasan antar konsumen.',
    ),
    QuestionItem(
      id: 'mnj_092',
      questionText: 'Pemasaran berfokus menarik calon pelanggan secara sukarela melalui konten bernilai dinamakan:',
      options: ['Inbound Marketing', 'Outbound Marketing', 'Push Marketing', 'Cold Calling'],
      correctOptionIndex: 0,
      explanation: 'Inbound Marketing memikat konsumen lewat konten edukatif bermanfaat.',
    ),
    QuestionItem(
      id: 'mnj_093',
      questionText: 'Metode pemasaran tradisional dengan gencar mendorong iklan langsung ke audiens dinamakan:',
      options: ['Outbound Marketing / Push Marketing', 'Inbound Marketing', 'Content Marketing', 'SEO'],
      correctOptionIndex: 0,
      explanation: 'Outbound/Push marketing mempromosikan produk secara agresif langsung ke publik.',
    ),
    QuestionItem(
      id: 'mnj_094',
      questionText: 'Model perilaku konsumen AIDDA merupakan singkatan dari:',
      options: ['Attention, Interest, Desire, Decision, Action', 'Awareness, Information, Data, Digital, Access', 'Attraction, Intent, Demand, Deal, Approval', 'Action, Interest, Direct, Duty, Account'],
      correctOptionIndex: 0,
      explanation: 'AIDDA: Perhatian -> Minat -> Hasrat -> Keputusan -> Tindakan Beli.',
    ),
    QuestionItem(
      id: 'mnj_095',
      questionText: 'Perasaan ragu atau penyesalan pembeli pasca melakukan transaksi pembelian barang mahal dinamakan:',
      options: ['Disonansi Kognitif (Cognitive Dissonance / Buyer\'s Remorse)', 'Impulse Buying', 'Customer Delight', 'Brand Loyalty'],
      correctOptionIndex: 0,
      explanation: 'Disonansi kognitif adalah rasa ketidaknyamanan psikologis pasca pemesanan.',
    ),
    QuestionItem(
      id: 'mnj_096',
      questionText: 'Pembelian barang secara mendadak tanpa perencanaan terlebih dahulu dinamakan:',
      options: ['Impulse Buying', 'Planned Buying', 'Compulsive Buying', 'Bargain Hunting'],
      correctOptionIndex: 0,
      explanation: 'Impulse buying dipicu emosi sesaat di tempat penjualan.',
    ),
    QuestionItem(
      id: 'mnj_097',
      questionText: 'Loyalitas pelanggan di mana konsumen secara konsisten menolak membeli produk merek lain dinamakan:',
      options: ['Ekuitas Merek (Brand Equity / Brand Insistence)', 'Brand Awareness', 'Brand Recall', 'Brand Recognition'],
      correctOptionIndex: 0,
      explanation: 'Brand Insistence menunjukkan ekuitas loyalitas merek tertinggi.',
    ),
    QuestionItem(
      id: 'mnj_098',
      questionText: 'Kemampuan konsumen mengingat atau mengenali suatu merek saat kategori produk disebutkan dinamakan:',
      options: ['Brand Awareness (Kesadaran Merek)', 'Brand Image', 'Brand Loyalty', 'Brand Identity'],
      correctOptionIndex: 0,
      explanation: 'Brand awareness mengukur tingkat daya ingat publik pada merek.',
    ),
    QuestionItem(
      id: 'mnj_099',
      questionText: 'Merek pertama yang muncul di pikiran konsumen saat mengingat suatu kategori produk dinamakan:',
      options: ['Top of Mind (TOM)', 'Brand Recall', 'Brand Recognition', 'Unaided Recall'],
      correctOptionIndex: 0,
      explanation: 'Top of Mind adalah puncak tertinggi kesadaran merek.',
    ),
    QuestionItem(
      id: 'mnj_100',
      questionText: 'Perluasan penggunaan nama merek yang sudah sukses ke produk kategori baru dinamakan:',
      options: ['Brand Extension (Perluasan Merek)', 'Co-Branding', 'Line Extension', 'Multi-Branding'],
      correctOptionIndex: 0,
      explanation: 'Brand extension memanfaatkan reputasi merek lama untuk produk di kategori baru.',
    ),
  ];
}
