import '../tes_seleksi_model.dart';

List<QuestionItem> getEkonomiPembangunanQuestions() {
  return const [
    QuestionItem(
      id: 'ekp_001',
      questionText: 'Total nilai pasar barang dan jasa akhir yang dihasilkan oleh faktor produksi di dalam suatu wilayah negara selama satu tahun dinamakan:',
      options: ['Produk Domestik Bruto (PDB / GDP)', 'Produk Nasional Bruto (PNB / GNP)', 'Pendapatan Nasional Bersih (NNI)', 'Pendapatan Per Kapita'],
      correctOptionIndex: 0,
      explanation: 'PDB mengukur nilai total output barang/jasa di dalam batas wilayah domestik suatu negara.',
    ),
    QuestionItem(
      id: 'ekp_002',
      questionText: 'Perbedaan utama antara Produk Domestik Bruto (PDB) dan Produk Nasional Bruto (PNB) terletak pada faktor:',
      options: ['Pendapatan Netto Luar Negeri atas Faktor Produksi', 'Tingkat Inflasi', 'Pajak Tidak Langsung', 'Penyusutan Modal'],
      correctOptionIndex: 0,
      explanation: 'PNB = PDB + Pendapatan Netto Faktor Luar Negeri.',
    ),
    QuestionItem(
      id: 'ekp_003',
      questionText: 'Perhitungan PDB yang memperhitung faktor pengaruh perubahan tingkat inflasi harga dinamakan:',
      options: ['PDB Riil (Real GDP)', 'PDB Nominal', 'PDB Per Kapita', 'PDB Potensial'],
      correctOptionIndex: 0,
      explanation: 'PDB Riil menggunakan harga konstan tahun dasar untuk mengeliminasi dampak inflasi.',
    ),
    QuestionItem(
      id: 'ekp_004',
      questionText: 'Indikator rata-rata pendapatan penduduk suatu negara yang dihitung dari PDB dibagi jumlah penduduk dinamakan:',
      options: ['Pendapatan Per Kapita', 'Pendapatan Disposabel', 'Rasio Gini', 'Indeks Pembangunan Manusia'],
      correctOptionIndex: 0,
      explanation: 'Pendapatan Per Kapita = Total PDB / Total Jumlah Penduduk.',
    ),
    QuestionItem(
      id: 'ekp_005',
      questionText: 'Kenaikan harga barang dan jasa secara umum dan terus menerus dalam periode tertentu dinamakan:',
      options: ['Inflasi', 'Deflasi', 'Stagflasi', 'Devaluasi'],
      correctOptionIndex: 0,
      explanation: 'Inflasi menurunkan daya beli nilai mata uang.',
    ),
    QuestionItem(
      id: 'ekp_006',
      questionText: 'Fenomena penurunan harga barang dan jasa secara umum dinamakan:',
      options: ['Deflasi', 'Inflasi', 'Hiperinflasi', 'Depresiasi'],
      correctOptionIndex: 0,
      explanation: 'Deflasi adalah laju inflasi negatif.',
    ),
    QuestionItem(
      id: 'ekp_007',
      questionText: 'Kondisi ekonomi buruk yang ditandai pertumbuhan ekonomi stagnan disertai tingkat inflasi dan pengangguran tinggi dinamakan:',
      options: ['Stagflasi', 'Resesi', 'Depresi Ekonomi', 'Hiperinflasi'],
      correctOptionIndex: 0,
      explanation: 'Stagflasi merupakan kombinasi dari Stagnasi ekonomi dan Inflasi tinggi.',
    ),
    QuestionItem(
      id: 'ekp_008',
      questionText: 'Laju kenaikan harga ekstrem yang tidak terkendali (bisa melampaui >100% per tahun) dinamakan:',
      options: ['Hiperinflasi', 'Galloping Inflation', 'Creeping Inflation', 'Demand-Pull'],
      correctOptionIndex: 0,
      explanation: 'Hiperinflasi menghancurkan sistem nilai mata uang negara.',
    ),
    QuestionItem(
      id: 'ekp_009',
      questionText: 'Inflasi yang disebabkan oleh lonjakan permintaan masyarakat melebihi kapasitas penawaran barang dinamakan:',
      options: ['Demand-Pull Inflation', 'Cost-Push Inflation', 'Imported Inflation', 'Structural Inflation'],
      correctOptionIndex: 0,
      explanation: 'Demand-Pull Inflation dipicu oleh dorongan kenaikan agregat permintaan.',
    ),
    QuestionItem(
      id: 'ekp_010',
      questionText: 'Inflasi yang dipicu oleh kenaikan biaya produksi (seperti kenaikan BBM atau bahan baku) dinamakan:',
      options: ['Cost-Push Inflation', 'Demand-Pull Inflation', 'Creeping Inflation', 'Hyperinflation'],
      correctOptionIndex: 0,
      explanation: 'Cost-Push Inflation terjadi akibat terdorongnya biaya produksi masukan.',
    ),
    QuestionItem(
      id: 'ekp_011',
      questionText: 'Kebijakan pemerintah mengatur penerimaan pajak dan pengeluaran belanja negara (APBN) dinamakan kebijakan:',
      options: ['Kebijakan Fiskal', 'Kebijakan Moneter', 'Kebijakan Perdagangan', 'Kebijakan Riil'],
      correctOptionIndex: 0,
      explanation: 'Kebijakan fiskal dikelola Kementerian Keuangan lewat instrumen APBN.',
    ),
    QuestionItem(
      id: 'ekp_012',
      questionText: 'Kebijakan bank sentral mengatur jumlah uang beredar dan suku bunga acuan dinamakan kebijakan:',
      options: ['Kebijakan Moneter', 'Kebijakan Fiskal', 'Kebijakan Impor', 'Kebijakan Tarif'],
      correctOptionIndex: 0,
      explanation: 'Kebijakan moneter dikelola Bank Sentral (Bank Indonesia) untuk stabilitas nilai rupiah.',
    ),
    QuestionItem(
      id: 'ekp_013',
      questionText: 'Kebijakan moneter ketat untuk menekan laju inflasi dengan menaikkan suku bunga dinamakan kebijakan:',
      options: ['Tight Money Policy (Kebijakan Uang Ketat / Kontraktif)', 'Easy Money Policy', 'Ekspansif', 'Dumping'],
      correctOptionIndex: 0,
      explanation: 'Kebijakan moneter kontraktif menyerap kelebihan jumlah uang beredar.',
    ),
    QuestionItem(
      id: 'ekp_014',
      questionText: 'Kebijakan moneter ekspansif untuk mendorong pertumbuhan ekonomi saat resesi dengan menurunkan suku bunga dinamakan:',
      options: ['Easy Money Policy (Kebijakan Uang Longgar)', 'Tight Money Policy', 'Austerity', 'Devaluasi'],
      correctOptionIndex: 0,
      explanation: 'Easy Money Policy merangsang penyaluran kredit dan investasi.',
    ),
    QuestionItem(
      id: 'ekp_015',
      questionText: 'Persentase simpanan wajib perbankan yang harus ditahan di Bank Sentral dinamakan:',
      options: ['Giro Wajib Minimal (GWM / Reserve Requirement)', 'Suku Bunga BI-Rate', 'Discount Rate', 'Open Market Operation'],
      correctOptionIndex: 0,
      explanation: 'GWM adalah rasio cadangan wajib perbankan di Bank Indonesia.',
    ),
    QuestionItem(
      id: 'ekp_016',
      questionText: 'Tindakan bank sentral membeli atau menjual surat berharga pemerintah di pasar uang dinamakan:',
      options: ['Operasi Pasar Terbuka (Open Market Operation)', 'Fasilitas Diskonto', 'Moral Suasion', 'GWM'],
      correctOptionIndex: 0,
      explanation: 'Operasi Pasar Terbuka (OPT) mengatur likuiditas lewat jual-beli Sertifikat Bank Indonesia (SBI).',
    ),
    QuestionItem(
      id: 'ekp_017',
      questionText: 'Tindakan pemerintah secara resmi menurunkan nilai mata uang sendiri terhadap mata uang asing dinamakan:',
      options: ['Devaluasi', 'Revaluasi', 'Depresiasi', 'Apresiasi'],
      correctOptionIndex: 0,
      explanation: 'Devaluasi adalah kebijakan resmi pemerintah menurunkan kurs mata uang.',
    ),
    QuestionItem(
      id: 'ekp_018',
      questionText: 'Penurunan nilai mata uang akibat mekanisme pasar bebas (permintaan dan penawaran valas) dinamakan:',
      options: ['Depresiasi', 'Devaluasi', 'Apresiasi', 'Inflasi'],
      correctOptionIndex: 0,
      explanation: 'Depresiasi terjadi secara alami di sistem kurs mengambang (floating rate).',
    ),
    QuestionItem(
      id: 'ekp_019',
      questionText: 'Peningkatan nilai mata uang domestik terhadap mata uang asing dalam sistem kurs mengambang dinamakan:',
      options: ['Apresiasi', 'Depresiasi', 'Revaluasi', 'Devaluasi'],
      correctOptionIndex: 0,
      explanation: 'Apresiasi menguatkan nilai tukar valuta domestik.',
    ),
    QuestionItem(
      id: 'ekp_020',
      questionText: 'Ukuran derajat ketimpangan distribusi pendapatan masyarakat di suatu negara menggunakan koefisien skala 0-1 dinamakan:',
      options: ['Rasio Gini (Gini Coefficient)', 'Kurva Lorenz', 'Indeks Palma', 'Garis Kemiskinan'],
      correctOptionIndex: 0,
      explanation: 'Rasio Gini = 0 (Pemerataan sempurna) dan Rasio Gini = 1 (Ketimpangan sempurna).',
    ),
    QuestionItem(
      id: 'ekp_021',
      questionText: 'Kurva geografis yang menggambarkan hubungan kumulatif persentase penduduk dengan persentase pendapatan dinamakan:',
      options: ['Kurva Lorenz', 'Kurva Phillips', 'Kurva Laffer', 'Kurva Kuznets'],
      correctOptionIndex: 0,
      explanation: 'Semakin melengkung jauh Kurva Lorenz dari garis diagonal, semakin tinggi ketimpangan.',
    ),
    QuestionItem(
      id: 'ekp_022',
      questionText: 'Hipotesis yang menyatakan bahwa pada tahap awal pertumbuhan ekonomi ketimpangan akan naik, namun kemudian akan menurun membentuk kurva U-terbalik dirumuskan oleh:',
      options: ['Simon Kuznets (Kurva Kuznets)', 'Arthur Lewis', 'Rostow', 'Harrod-Domar'],
      correctOptionIndex: 0,
      explanation: 'Kurva Kuznets menggambarkan hubungan U-terbalik antara PDB per kapita dan ketimpangan.',
    ),
    QuestionItem(
      id: 'ekp_023',
      questionText: 'Kurva yang memodelkan hubungan Trade-off jangka pendek antara tingkat Inflasi dan tingkat Pengangguran dinamakan:',
      options: ['Kurva Phillips', 'Kurva Lorenz', 'Kurva Laffer', 'Kurva IS-LM'],
      correctOptionIndex: 0,
      explanation: 'Kurva Phillips menunjukkan hubungan berlawanan antara inflasi dan pengangguran.',
    ),
    QuestionItem(
      id: 'ekp_024',
      questionText: 'Kurva yang menggambarkan hubungan antara tarif pajak dengan total penerimaan pajak pemerintah dinamakan:',
      options: ['Kurva Laffer', 'Kurva Phillips', 'Kurva Lorenz', 'Kurva Engel'],
      correctOptionIndex: 0,
      explanation: 'Kurva Laffer menunjukkan tarif pajak terlalu tinggi justru menurunkan penerimaan pajak.',
    ),
    QuestionItem(
      id: 'ekp_025',
      questionText: 'Indeks komposit UNDP untuk mengukur kualitas pembangunan manusia berbasis 3 dimensi utama (Kesehatan, Pendidikan, Standar Hidup Layak) dinamakan:',
      options: ['Indeks Pembangunan Manusia (IPM / HDI)', 'Indeks Kebahagiaan', 'PDB Per Kapita', 'Rasio Gini'],
      correctOptionIndex: 0,
      explanation: 'IPM (Human Development Index) menilai Umur Panjang/Kesehatan, Pengetahuan, dan GNI per kapita.',
    ),
    QuestionItem(
      id: 'ekp_026',
      questionText: 'Tiga dimensi utama penyusun Indeks Pembangunan Manusia (IPM / HDI) adalah:',
      options: ['Umur Harapan Hidup, Harapan Lama Sekolah & Rata-rata Lama Sekolah, Standar Hidup Layak (GNI per Kapita)', 'PDB, Pajak, Inflasi', 'Pendapatan, Ekspor, Impor', 'Kesehatan, Jalan Raya, Listrik'],
      correctOptionIndex: 0,
      explanation: 'IPM mengukur indikator kesehatan, pendidikan, dan pengeluaran per kapita disesuaikan.',
    ),
    QuestionItem(
      id: 'ekp_027',
      questionText: 'Batas kecukupan pengeluaran minimum kebutuhan dasar makanan dan non-makanan seseorang dinamakan:',
      options: ['Garis Kemiskinan (Poverty Line)', 'BMR', 'Upah Minimum', 'Batas Subsisten'],
      correctOptionIndex: 0,
      explanation: 'Penduduk dengan pengeluaran di bawah Garis Kemiskinan dikategorikan sebagai penduduk miskin.',
    ),
    QuestionItem(
      id: 'ekp_028',
      questionText: 'Kondisi kemiskinan di mana seseorang tidak mampu memenuhi kebutuhan dasar paling minimum untuk bertahan hidup dinamakan kemiskinan:',
      options: ['Absolut', 'Relatif', 'Struktural', 'Kultural'],
      correctOptionIndex: 0,
      explanation: 'Kemiskinan Absolut dihitung dari ketidakmampuan memenuhi Garis Kemiskinan dasar.',
    ),
    QuestionItem(
      id: 'ekp_029',
      questionText: 'Kondisi kemiskinan akibat tatanan sistem dan kebijakan pembangunan yang tidak adil dinamakan kemiskinan:',
      options: ['Struktural', 'Absolut', 'Kultural', 'Koorporat'],
      correctOptionIndex: 0,
      explanation: 'Kemiskinan Struktural terbelenggu akibat keterbatasan akses sistemik.',
    ),
    QuestionItem(
      id: 'ekp_030',
      questionText: 'Kemiskinan akibat sikap dan budaya hidup pasrah, malas, atau enggan berusaha dinamakan kemiskinan:',
      options: ['Kultural', 'Struktural', 'Absolut', 'Musiman'],
      correctOptionIndex: 0,
      explanation: 'Kemiskinan Kultural berasal dari faktor nilai dan kebiasaan subkultur.',
    ),
    QuestionItem(
      id: 'ekp_031',
      questionText: 'Teori Tahapan Pertumbuhan Ekonomi Rostow membagi pembangunan negara ke dalam:',
      options: ['5 Tahapan (Masyarakat Tradisional s/d Konsumsi Massa Tinggi)', '3 Tahapan', '7 Tahapan', '4 Tahapan'],
      correctOptionIndex: 0,
      explanation: 'WW Rostow: Tradisional -> Prasyarat Lepas Landas -> Lepas Landas (Take-off) -> Kematangan -> Konsumsi Tinggi.',
    ),
    QuestionItem(
      id: 'ekp_032',
      questionText: 'Tahap kritis ketiga dalam Teori Rostow di mana investasi meningkat pesat memicu dorongan pertumbuhan mandiri dinamakan tahap:',
      options: ['Lepas Landas (Take-off)', 'Prasyarat Lepas Landas', 'Masyarakat Tradisional', 'Konsumsi Tinggi'],
      correctOptionIndex: 0,
      explanation: 'Tahap Take-off (Lepas Landas) ditandai modernisasi dan kenaikan rasio investasi.',
    ),
    QuestionItem(
      id: 'ekp_033',
      questionText: 'Teori Pertumbuhan Ekonomi Harrod-Domar menekankan pentingnya pembentukan faktor:',
      options: ['Tabungan dan Investasi (Modal / Capital)', 'Jumlah Penduduk', 'Kemajuan Teknologi', 'Sumber Daya Alam'],
      correctOptionIndex: 0,
      explanation: 'Harrod-Domar menyatakan pertumbuhan ekonomi berbanding lurus dengan rasio tabungan/investasi.',
    ),
    QuestionItem(
      id: 'ekp_034',
      questionText: 'Teori Pertumbuhan Ekonomi Neoklasik Solow-Swan menambahkan variabel penting pendorong jangka panjang yaitu:',
      options: ['Kemajuan Teknologi (Kemajuan Teknis / Residual Solow)', 'Jumlah Uang', 'Pajak', 'Perdagangan'],
      correctOptionIndex: 0,
      explanation: 'Solow-Swan membuktikan teknologi adalah motor utama pertumbuhan jangka panjang.',
    ),
    QuestionItem(
      id: 'ekp_035',
      questionText: 'Teori Pertumbuhan Endogen (Endogenous Growth Theory) yang dikembangkan Paul Romer menekankan peran:',
      options: ['Modal Manusia (Human Capital), R&D, dan Pengetahuan', 'Sumber Daya Alam', 'Pemberian Hibah', 'Pinjaman Luar Negeri'],
      correctOptionIndex: 0,
      explanation: 'Teori Endogen menganggap investasi pengetahuan, inovasi, dan SDM sebagai penggerak intern ekonomi.',
    ),
    QuestionItem(
      id: 'ekp_036',
      questionText: 'Model Dualisme Ekonomi Lewis membagi perekonomian negara berkembang menjadi 2 sektor yaitu:',
      options: ['Sektor Tradisional (Pertanian Subsisten) dan Sektor Modern (Industri)', 'Sektor Kota dan Desa', 'Sektor Publik dan Swasta', 'Sektor Jasa dan Manufaktur'],
      correctOptionIndex: 0,
      explanation: 'Model W. Arthur Lewis memodelkan migrasi tenaga kerja dari sektor pertanian subsisten ke industri modern.',
    ),
    QuestionItem(
      id: 'ekp_037',
      questionText: 'Fenomena limpahan tenaga kerja di sektor pertanian tradisional yang memiliki produk marjinal (MPL) mendekati nol dinamakan:',
      options: ['Pengangguran Terselubung (Disguised Unemployment)', 'Pengangguran Terbuka', 'Pengangguran Friksional', 'Pengangguran Struktural'],
      correctOptionIndex: 0,
      explanation: 'Disguised Unemployment terjadi bila penambahan pekerja tidak lagi menambah hasil produk.',
    ),
    QuestionItem(
      id: 'ekp_038',
      questionText: 'Pengangguran yang terjadi akibat tenggat waktu jeda saat seseorang berpindah mencari pekerjaan baru dinamakan:',
      options: ['Pengangguran Friksional', 'Pengangguran Struktural', 'Pengangguran Siklis', 'Pengangguran Musiman'],
      correctOptionIndex: 0,
      explanation: 'Pengangguran Friksional bersifat sementara saat pencarian kerja.',
    ),
    QuestionItem(
      id: 'ekp_039',
      questionText: 'Pengangguran yang disebabkan oleh ketidakcocokan antara keterampilan pencari kerja dengan syarat jabatan baru dinamakan:',
      options: ['Pengangguran Struktural', 'Pengangguran Friksional', 'Pengangguran Siklis', 'Pengangguran Teknologi'],
      correctOptionIndex: 0,
      explanation: 'Pengangguran Struktural dipicu pergeseran struktur ekonomi/teknologi.',
    ),
    QuestionItem(
      id: 'ekp_040',
      questionText: 'Pengangguran akibat krisis resesi gelombang penurunan siklus bisnis (downturn) dinamakan:',
      options: ['Pengangguran Siklis (Cyclical Unemployment)', 'Pengangguran Friksional', 'Pengangguran Volunter', 'Pengangguran Pokok'],
      correctOptionIndex: 0,
      explanation: 'Pengangguran Siklis naik saat kemerosotan resesi ekonomi.',
    ),
    QuestionItem(
      id: 'ekp_041',
      questionText: 'Penduduk usia kerja (15 tahun ke atas) yang bekerja atau sedang aktif mencari pekerjaan dinamakan:',
      options: ['Angkatan Kerja (Labor Force)', 'Tenaga Kerja', 'Bukan Angkatan Kerja', 'Usia Produktif'],
      correctOptionIndex: 0,
      explanation: 'Angkatan Kerja = Jumlah Pekerja Aktif + Penganggur Terbuka.',
    ),
    QuestionItem(
      id: 'ekp_042',
      questionText: 'Persentase jumlah angkatan kerja terhadap total penduduk usia kerja dinamakan:',
      options: ['TPA (Tingkat Partisipasi Angkatan Kerja / LFPR)', 'Tingkat Pengangguran', 'Rasio Pekerja', 'Indeks Tenaga Kerja'],
      correctOptionIndex: 0,
      explanation: 'TPAK mengukur porsi usia kerja yang aktif secara ekonomi.',
    ),
    QuestionItem(
      id: 'ekp_043',
      questionText: 'Catatan rinci transaksi sistematis ekonomi antar penduduk suatu negara dengan negara lain dinamakan:',
      options: ['Neraca Pembayaran (Balance of Payments / BOP)', 'Neraca Perdagangan', 'APBN', 'Laporan Valas'],
      correctOptionIndex: 0,
      explanation: 'BOP merekam seluruh transaksi ekspor-impor, jasa, dan aliran modal antarnegara.',
    ),
    QuestionItem(
      id: 'ekp_044',
      questionText: 'Komponen Neraca Pembayaran yang mencatat ekspor-impor barang, jasa, dan pendapatan dinamakan:',
      options: ['Transaksi Berjalan (Current Account)', 'Transaksi Modal', 'Transaksi Finansial', 'Cadangan Devisa'],
      correctOptionIndex: 0,
      explanation: 'Current Account mencatat transaksi riil barang dan jasa.',
    ),
    QuestionItem(
      id: 'ekp_045',
      questionText: 'Selisih antara nilai ekspor barang dengan nilai impor barang suatu negara dinamakan:',
      options: ['Neraca Perdagangan (Balance of Trade)', 'Neraca Berjalan', 'Capital Account', 'Devaluasi Netto'],
      correctOptionIndex: 0,
      explanation: 'Neraca Perdagangan = Nilai Ekspor Barang - Nilai Impor Barang.',
    ),
    QuestionItem(
      id: 'ekp_046',
      questionText: 'Kondisi neraca perdagangan di mana nilai ekspor barang melampaui nilai impor barang dinamakan:',
      options: ['Surplus Perdagangan', 'Defisit Perdagangan', 'Seimbang', 'Krisis'],
      correctOptionIndex: 0,
      explanation: 'Surplus terjadi jika Ekspor > Impor.',
    ),
    QuestionItem(
      id: 'ekp_047',
      questionText: 'Kondisi neraca perdagangan di mana nilai impor barang lebih besar daripada nilai ekspor barang dinamakan:',
      options: ['Defisit Perdagangan', 'Surplus Perdagangan', 'Ekuitas Negatif', 'Stagflasi'],
      correctOptionIndex: 0,
      explanation: 'Defisit perdagangan terjadi saat Impor > Ekspor.',
    ),
    QuestionItem(
      id: 'tk_048_ekp',
      questionText: 'Kebijakan perdagangan internasional yang mengenakan pajak atas barang impor dinamakan:',
      options: ['Tarif / Bea Masuk', 'Kuota Impor', 'Subsidi Ekspor', 'Embargo'],
      correctOptionIndex: 0,
      explanation: 'Tarif impor meningkatkan harga barang impor melindungi industri domestik.',
    ),
    QuestionItem(
      id: 'ekp_049',
      questionText: 'Kebijakan pembatasan fisik jumlah maksimum unit barang tertentu yang boleh diimpor dinamakan:',
      options: ['Kuota Impor', 'Tarif', 'Dumping', 'Larangan Ekspor'],
      correctOptionIndex: 0,
      explanation: 'Kuota membatasi kuantitas volume barang impor.',
    ),
    QuestionItem(
      id: 'ekp_050',
      questionText: 'Praktik diskriminasi harga dengan menjual barang di pasar luar negeri lebih murah dibanding di dalam negeri dinamakan:',
      options: ['Dumping', 'Subsidi', 'Proteksionisme', 'Free Trade'],
      correctOptionIndex: 0,
      explanation: 'Dumping bertujuan merebut pangsa pasar luar negeri.',
    ),
    QuestionItem(
      id: 'ekp_051',
      questionText: 'Organisasi perdagangan dunia yang mengatur aturan main perdagangan internasional antarnegara adalah:',
      options: ['WTO (World Trade Organization)', 'IMF', 'World Bank', 'OECD'],
      correctOptionIndex: 0,
      explanation: 'WTO memfasilitasi perundingan dan resolusi sengketa perdagangan global.',
    ),
    QuestionItem(
      id: 'ekp_052',
      questionText: 'Lembaga keuangan internasional penstabil sistem moneter global dan pemberi bantuan likuiditas krisis adalah:',
      options: ['IMF (International Monetary Fund)', 'Bank Dunia (World Bank)', 'ADB', 'IDB'],
      correctOptionIndex: 0,
      explanation: 'IMF membantu pemulihan neraca pembayaran dan stabilitas kurs mata uang.',
    ),
    QuestionItem(
      id: 'ekp_053',
      questionText: 'Lembaga keuangan internasional yang memberikan pinjaman jangka panjang untuk proyek pembangunan dinamakan:',
      options: ['Bank Dunia (World Bank / IBRD)', 'IMF', 'WTO', 'Bank for International Settlements'],
      correctOptionIndex: 0,
      explanation: 'World Bank mendanai proyek infrastruktur dan pengentasan kemiskinan.',
    ),
    QuestionItem(
      id: 'ekp_054',
      questionText: 'Teori Keunggulan Mutlak (Absolute Advantage) dalam perdagangan internasional dirumuskan oleh bapak ekonomi:',
      options: ['Adam Smith', 'David Ricardo', 'John Maynard Keynes', 'Heckscher-Ohlin'],
      correctOptionIndex: 0,
      explanation: 'Adam Smith menyatakan negara harus berspesialisasi pada produk bertotal biaya paling efisien.',
    ),
    QuestionItem(
      id: 'ekp_055',
      questionText: 'Teori Keunggulan Komparatif (Comparative Advantage) yang berbasis biaya peluang (Opportunity Cost) dirumuskan oleh:',
      options: ['David Ricardo', 'Adam Smith', 'Paul Samuelson', 'Alfred Marshall'],
      correctOptionIndex: 0,
      explanation: 'David Ricardo membuktikan perdagangan tetap menguntungkan berdasar keunggulan biaya relatif terendah.',
    ),
    QuestionItem(
      id: 'ekp_056',
      questionText: 'Teori Perdagangan Heckscher-Ohlin (H-O) menyatakan negara akan mengekspor barang yang menggunakan faktor produksi:',
      options: ['Melimpah (Abundant Factor) di dalam negeri', 'Langka', 'Mahal', 'Impor'],
      correctOptionIndex: 0,
      explanation: 'Teori H-O berbasis kelimpahan relatif modal (capital) atau tenaga kerja (labor).',
    ),
    QuestionItem(
      id: 'ekp_057',
      questionText: 'Temuan empiris Wassily Leontief bahwa Amerika Serikat justru mengekspor barang padat karya dinamakan:',
      options: ['Paradoks Leontief (Leontief Paradox)', 'Krisis Gibson', 'Efek Rybczynski', 'Paradoks Thrift'],
      correctOptionIndex: 0,
      explanation: 'Paradoks Leontief menyanggah prediksi teori Heckscher-Ohlin pada ekspor AS.',
    ),
    QuestionItem(
      id: 'ekp_058',
      questionText: 'Fenomena di mana negara kaya sumber daya alam justru mengalami pertumbuhan ekonomi lebih lambat dinamakan:',
      options: ['Kutukan Sumber Daya Alam (Resource Curse / Dutch Disease)', 'Middle Income Trap', 'Poverty Trap', 'Capital Flight'],
      correctOptionIndex: 0,
      explanation: 'Resource Curse / Penyakit Belanda memicu ketergantungan komoditas mentah dan pengabaian manufaktur.',
    ),
    QuestionItem(
      id: 'ekp_059',
      questionText: 'Kondisi negara berkembang yang terjebak pada tingkat pendapatan menengah dan gagal menjadi negara maju dinamakan:',
      options: ['Middle-Income Trap', 'Poverty Trap', 'Stagflasi', 'Depresi'],
      correctOptionIndex: 0,
      explanation: 'Middle-Income Trap terjadi bila daya saing upah murah hilang sebelum inovasi teknologi terbangun.',
    ),
    QuestionItem(
      id: 'ekp_060',
      questionText: 'Lingkaran setan kemiskinan (Vicious Circle of Poverty) menurut Ragnar Nurkse dipicu oleh:',
      options: ['Pendapatan Rendah -> Tabungan Rendah -> Investasi Rendah -> Produktivitas Rendah', 'Pajak Tinggi', 'Perang', 'Bencana'],
      correctOptionIndex: 0,
      explanation: 'Siklus Nurkse menjelaskan kemiskinan yang mengabadikan dirinya sendiri.',
    ),
    QuestionItem(
      id: 'ekp_061',
      questionText: 'Konsep dorongan investasi besar-besaran secara serentak di berbagai sektor industri dinamakan Teori:',
      options: ['Big Push (Dorongan Big Push - Rosenstein-Rodan)', 'Unbalanced Growth', 'Take-off', 'Trickle Down'],
      correctOptionIndex: 0,
      explanation: 'Teori Big Push menekankan perlunya investasi modal raksasa minimum.',
    ),
    QuestionItem(
      id: 'ekp_062',
      questionText: 'Teori Pertumbuhan Tak Seimbang (Unbalanced Growth) yang mengutamakan sektor unggulan (leading sector) dirumuskan oleh:',
      options: ['Albert O. Hirschman', 'Rosenstein-Rodan', 'Nurkse', 'Myrdal'],
      correctOptionIndex: 0,
      explanation: 'Hirschman mengusulkan fokus pada sektor bermultiplier kaitan ke depan dan ke belakang (linkages).',
    ),
    QuestionItem(
      id: 'ekp_063',
      questionText: 'Efek penetesan hasil pertumbuhan ekonomi dari golongan kaya ke masyarakat miskin dinamakan:',
      options: ['Trickle-Down Effect', 'Spread Effect', 'Backwash Effect', 'Multiplier Effect'],
      correctOptionIndex: 0,
      explanation: 'Trickle-down effect mengasumsikan hasil pertumbuhan atas akan menetes ke bawah.',
    ),
    QuestionItem(
      id: 'ekp_064',
      questionText: 'Dampak penarikan sumber daya dari daerah terbelakang ke daerah pusat pertumbuhan dinamakan Gunnar Myrdal sebagai:',
      options: ['Backwash Effect', 'Spread Effect', 'Demonstration Effect', 'Multiplier Effect'],
      correctOptionIndex: 0,
      explanation: 'Backwash effect merugikan daerah pinggiran karena modal dan modal manusia tersedot ke kota.',
    ),
    QuestionItem(
      id: 'ekp_065',
      questionText: 'Dampak positif penyebaran pembangunan dan teknologi dari pusat ke daerah sekitarnya dinamakan:',
      options: ['Spread Effect', 'Backwash Effect', 'Demonstration Effect', 'Ripple Effect'],
      correctOptionIndex: 0,
      explanation: 'Spread Effect meneteskan kemajuan teknologi dan pasar ke kawasan pinggiran.',
    ),
    QuestionItem(
      id: 'ekp_066',
      questionText: 'Strategi pembangunan ekonomi yang memfokuskan penggantian produk barang impor dengan produksi buatan dalam negeri dinamakan:',
      options: ['Substitusi Impor (Import Substitution Industrialization)', 'Promosi Ekspor', 'Liberalisasi', 'Privatisasi'],
      correctOptionIndex: 0,
      explanation: 'Substitusi Impor memproteksi industri manufaktur dalam negeri.',
    ),
    QuestionItem(
      id: 'ekp_067',
      questionText: 'Strategi pembangunan berorientasi ke luar (outward-looking) dengan mendorong industri berdaya saing ekspor dinamakan:',
      options: ['Promosi Ekspor (Export Promotion)', 'Substitusi Impor', 'Proteksionisme', 'Isolasionisme'],
      correctOptionIndex: 0,
      explanation: 'Promosi Ekspor memacu pertumbuhan industri berbasis pasar global (seperti Macan Asia).',
    ),
    QuestionItem(
      id: 'ekp_068',
      questionText: 'Anggaran Pendapatan dan Belanja Negara (APBN) di Indonesia disahkan bersama oleh Pemerintah dan:',
      options: ['DPR (Dewan Perwakilan Rakyat)', 'DPD', 'MA', 'BPK'],
      correctOptionIndex: 0,
      explanation: 'APBN dirancang Pemerintah dan disetujui undang-undangnya oleh DPR.',
    ),
    QuestionItem(
      id: 'ekp_069',
      questionText: 'Kondisi APBN di mana pengeluaran belanja pemerintah melebihi pendapatan negara dinamakan APBN:',
      options: ['Defisit', 'Surplus', 'Berimbang', 'Stagnan'],
      correctOptionIndex: 0,
      explanation: 'Defisit APBN umumnya ditutup lewat penerbitan Surat Berharga Negara (SBN) atau utang.',
    ),
    QuestionItem(
      id: 'ekp_070',
      questionText: 'Batas maksimum defisit APBN Indonesia terhadap PDB yang diatur dalam Undang-Undang Keuangan Negara adalah:',
      options: ['Maksimal 3% dari PDB', 'Maksimal 5%', 'Maksimal 10%', 'Bebas'],
      correctOptionIndex: 0,
      explanation: 'UU No. 17/2003 membatasi defisit APBN maksimal 3% dari PDB.',
    ),
    QuestionItem(
      id: 'ekp_071',
      questionText: 'Batas maksimum rasio total utang pemerintah terhadap PDB menurut undang-undang Indonesia adalah:',
      options: ['Maksimal 60% dari PDB', 'Maksimal 30%', 'Maksimal 80%', 'Maksimal 100%'],
      correctOptionIndex: 0,
      explanation: 'Rasio utang pemerintah dibatasi maksimal 60% dari PDB.',
    ),
    QuestionItem(
      id: 'ekp_072',
      questionText: 'Pengeluaran wajib APBN yang dikirim ke pemerintah daerah untuk mendanai desentralisasi dinamakan:',
      options: ['TKDD (Transfer ke Daerah dan Dana Desa)', 'Belanja Pegawai', 'Belanja Modal', 'Subsidi'],
      correctOptionIndex: 0,
      explanation: 'TKDD mencakup DAU, DAK, DBH, dan Dana Desa.',
    ),
    QuestionItem(
      id: 'ekp_073',
      questionText: 'Dana APBN yang dialokasikan ke daerah dengan tujuan pemerataan kemampuan keuangan antar daerah dinamakan:',
      options: ['DAU (Dana Alokasi Umum)', 'DAK (Dana Alokasi Khusus)', 'DBH (Dana Bagi Hasil)', 'Dana Otonomi Khusus'],
      correctOptionIndex: 0,
      explanation: 'DAU bersifat unallocated grant untuk pemerataan keuangan daerah.',
    ),
    QuestionItem(
      id: 'ekp_074',
      questionText: 'Dana APBN yang dialokasikan ke daerah tertentu untuk membantu mendanai kegiatan khusus fisik daerah dinamakan:',
      options: ['DAK (Dana Alokasi Khusus)', 'DAU', 'DBH', 'Dana Insentif Daerah'],
      correctOptionIndex: 0,
      explanation: 'DAK bersifat earmarked grant mendanai kebutuhan khusus (seperti sekolah/jalan daerah).',
    ),
    QuestionItem(
      id: 'ekp_075',
      questionText: 'Angka perbandingan antara jumlah penduduk usia non-produktif (0-14 th & 65+ th) terhadap penduduk produktif (15-64 th) dinamakan:',
      options: ['Rasio Ketergantungan (Dependency Ratio)', 'Rasio Beban', 'Angka Kelahiran', 'Indeks Angkatan Kerja'],
      correctOptionIndex: 0,
      explanation: 'Dependency Ratio mengukur beban tanggungan penduduk produktif.',
    ),
    QuestionItem(
      id: 'ekp_076',
      questionText: 'Kondisi demografi di mana jumlah penduduk usia produktif melimpah melebihi 68% dari total penduduk dinamakan:',
      options: ['Bonus Demografi', 'Ledakan Penduduk', 'Aging Population', 'Depopulasi'],
      correctOptionIndex: 0,
      explanation: 'Bonus Demografi memberikan jendela peluang emas pertumbuhan ekonomi.',
    ),
    QuestionItem(
      id: 'ekp_077',
      questionText: 'Teori Kependudukan Malthus menyatakan bahwa pertumbuhan penduduk mengikuti deret ukur (geometris), sedangkan produksi pangan mengikuti:',
      options: ['Deret Hitung (Aritmatika)', 'Deret Ukur', 'Eksponensial', 'Tetap'],
      correctOptionIndex: 0,
      explanation: 'Thomas Malthus mengkhawatirkan laju pangan (1,2,3,4) ketinggalan dari laju penduduk (1,2,4,8).',
    ),
    QuestionItem(
      id: 'ekp_078',
      questionText: 'Model Transisi Demografi memodelkan perubahan angka kelahiran dan kematian melewati:',
      options: ['4 Tahapan Transisi (Pre-industrial s/d Post-industrial)', '2 Tahapan', '6 Tahapan', '1 Tahap'],
      correctOptionIndex: 0,
      explanation: 'Transisi demografi memodelkan penurunan angka kematian yang disusul penurunan angka kelahiran.',
    ),
    QuestionItem(
      id: 'ekp_079',
      questionText: 'Perbedaan nilai ekspor dan impor jasa serta transfer obligasi pendapatan dinamakan:',
      options: ['Neraca Jasa & Pendapatan Primary', 'Neraca Barang', 'Current Account', 'BOP'],
      correctOptionIndex: 0,
      explanation: 'Neraca Jasa mencatat transaksi jasa perhubungan, pariwisata, dan asuransi.',
    ),
    QuestionItem(
      id: 'ekp_080',
      questionText: 'Investasi asing langsung berupa pendirian pabrik atau cabang usaha di dalam negeri dinamakan:',
      options: ['FDI (Foreign Direct Investment / PMA)', 'FPI (Foreign Portfolio Investment)', 'Hot Money', 'Utang Luar Negeri'],
      correctOptionIndex: 0,
      explanation: 'FDI (PMA) membawa aset fisik modal jangka panjang dan transfer teknologi.',
    ),
    QuestionItem(
      id: 'ekp_081',
      questionText: 'Investasi asing pada instrumen surat berharga (saham/obligasi) yang mudah ditarik kembali sewaktu-waktu dinamakan:',
      options: ['FPI / Hot Money (Portofolio Asing)', 'FDI', 'PMA', 'Investasi Riil'],
      correctOptionIndex: 0,
      explanation: 'Hot Money bersifat volatil dan rawan keluar mendadak (capital flight).',
    ),
    QuestionItem(
      id: 'ekp_082',
      questionText: 'Fenomena pelarian modal besar-besaran dari dalam negeri ke luar negeri akibat krisis politik/ekonomi dinamakan:',
      options: ['Capital Flight (Pelarian Modal)', 'FDI', 'Braindrain', 'Devaluasi'],
      correctOptionIndex: 0,
      explanation: 'Capital flight menguras cadangan devisa dan menekan rupiah.',
    ),
    QuestionItem(
      id: 'ekp_083',
      questionText: 'Fenomena migrasi tenaga ahli terdidik berpendidikan tinggi dari negara berkembang ke negara maju dinamakan:',
      options: ['Brain Drain', 'Brain Gain', 'Urbanisasi', 'Remitansi'],
      correctOptionIndex: 0,
      explanation: 'Brain Drain mengurangi ketersediaan modal manusia berkualitas di negara asal.',
    ),
    QuestionItem(
      id: 'ekp_084',
      questionText: 'Transfer uang tunai yang dikirimkan oleh pekerja migran di luar negeri ke keluarga di negara asal dinamakan:',
      options: ['Remitansi (Remittance)', 'FDI', 'Grant', 'Devisa Umur'],
      correctOptionIndex: 0,
      explanation: 'Remitansi TKI menjadi salah satu penyumbang devisa terbesar bagi negara.',
    ),
    QuestionItem(
      id: 'ekp_085',
      questionText: 'Perpindahan penduduk dari kawasan pedesaan menuju kawasan perkotaan dinamakan:',
      options: ['Urbanisasi', 'Transmigrasi', 'Imigrasi', 'Ruralisasi'],
      correctOptionIndex: 0,
      explanation: 'Urbanisasi didorong faktor penarik kota dan faktor pendorong desa.',
    ),
    QuestionItem(
      id: 'ekp_086',
      questionText: 'Program pemindahan penduduk dari daerah padat Jawa ke pulau lain yang kurang padat dinamakan:',
      options: ['Transmigrasi', 'Urbanisasi', 'Emigrasi', 'Agropolitan'],
      correctOptionIndex: 0,
      explanation: 'Transmigrasi pemerataan persebaran penduduk dan pengembangan lahan luar Jawa.',
    ),
    QuestionItem(
      id: 'ekp_087',
      questionText: 'Konsep pengembangan kawasan perdesaan berbasis potensi ekonomi pertanian modern dinamakan:',
      options: ['Agropolitan', 'Megapolitan', 'Kawasan Industri', 'Smart City'],
      correctOptionIndex: 0,
      explanation: 'Agropolitan membangun kota pertanian mandiri di pedesaan.',
    ),
    QuestionItem(
      id: 'ekp_088',
      questionText: 'Nilai tukar mata uang yang disesuaikan dengan daya beli barang relatif antar negara dinamakan PPP yaitu:',
      options: ['Purchasing Power Parity (Keseimbangan Kemampuan Berbelanja)', 'Public Private Partnership', 'Payback Period', 'Point-to-Point'],
      correctOptionIndex: 0,
      explanation: 'PPP mengukur perbandingan daya beli mata uang pada paket barang standar (seperti Big Mac Index).',
    ),
    QuestionItem(
      id: 'ekp_089',
      questionText: 'Indeks populer tidak resmi media Economist yang mengukur PPP berbasis harga hamburger McDonald dinamakan:',
      options: ['Big Mac Index', 'CPI', 'HDI', 'Gini Index'],
      correctOptionIndex: 0,
      explanation: 'Big Mac Index membandingkan harga burger Big Mac di seluruh dunia.',
    ),
    QuestionItem(
      id: 'ekp_090',
      questionText: 'Sektor ekonomi informal pada negara berkembang ditandai dengan ciri-ciri:',
      options: ['Tidak terdaftar resmi, tanpa pajak, dan skala usaha kecil/mandiri', 'Berbadan hukum PT', 'Bursa Efek', 'Pabrik besar'],
      correctOptionIndex: 0,
      explanation: 'Sektor informal (pedagang kaki lima/buruh harian) menyerap mayoritas tenaga kerja negara berkembang.',
    ),
    QuestionItem(
      id: 'ekp_091',
      questionText: 'Model keseimbangan umum pasar barang (IS) dan pasar uang (LM) dirumuskan oleh:',
      options: ['Hicks dan Hansen (Model IS-LM)', 'Keynes', 'Friedman', 'Mundell-Fleming'],
      correctOptionIndex: 0,
      explanation: 'IS-LM menghubungkan suku bunga dan pendapatan nasional.',
    ),
    QuestionItem(
      id: 'ekp_092',
      questionText: 'Kurva IS menggambarkan keseimbangan pada:',
      options: ['Pasar Barang dan Jasa (Investment = Saving)', 'Pasar Uang', 'Pasar Tenaga Kerja', 'Pasar Valas'],
      correctOptionIndex: 0,
      explanation: 'Kurva IS memodelkan kombinasi suku bunga dan Y di pasar barang.',
    ),
    QuestionItem(
      id: 'ekp_093',
      questionText: 'Kurva LM menggambarkan keseimbangan pada:',
      options: ['Pasar Uang (Liquidity Preference = Money Supply)', 'Pasar Barang', 'Pasar Saham', 'Pasar Modal'],
      correctOptionIndex: 0,
      explanation: 'Kurva LM memodelkan permintaan dan penawaran uang.',
    ),
    QuestionItem(
      id: 'ekp_094',
      questionText: 'Perluasan model IS-LM untuk perekonomian terbuka dengan perdagangan luar negeri dinamakan Model:',
      options: ['Mundell-Fleming Model', 'Solow Model', 'Keynesian Cross', 'Harrod-Domar'],
      correctOptionIndex: 0,
      explanation: 'Model Mundell-Fleming menganalisis dampak fiskal/moneter pada iklim kurs tetap dan mengambang.',
    ),
    QuestionItem(
      id: 'ekp_095',
      questionText: 'Fenomena penurunan investasi swasta akibat kenaikan pengeluaran pemerintah dan suku bunga dinamakan:',
      options: ['Crowding-Out Effect', 'Multiplier Effect', 'Trickle-Down', 'Demonstration Effect'],
      correctOptionIndex: 0,
      explanation: 'Crowding-Out terjadi saat pinjaman pemerintah menaikkan suku bunga dan mendesak sektor swasta.',
    ),
    QuestionItem(
      id: 'ekp_096',
      questionText: 'Angka kelipatan perubahan pendapatan nasional akibat perubahan awal belanja pengeluaran dinamakan:',
      options: ['Angka Pengganda (Multiplier Effect / k)', 'Rasio Kapital', 'Velocity of Money', 'Kofisien Gini'],
      correctOptionIndex: 0,
      explanation: 'Multiplier effect k = 1 / (1 - MPC).',
    ),
    QuestionItem(
      id: 'ekp_097',
      questionText: 'Kecenderungan marginal masyarakat untuk mengonsumsi tambahan pendapatan dinamakan:',
      options: ['MPC (Marginal Propensity to Consume)', 'MPS', 'APC', 'APS'],
      correctOptionIndex: 0,
      explanation: 'MPC = Delta Konsumsi / Delta Pendapatan.',
    ),
    QuestionItem(
      id: 'ekp_098',
      questionText: 'Kecenderungan marginal masyarakat untuk menabung dari tambahan pendapatan dinamakan:',
      options: ['MPS (Marginal Propensity to Save)', 'MPC', 'APS', 'BMR'],
      correctOptionIndex: 0,
      explanation: 'MPC + MPS = 1.',
    ),
    QuestionItem(
      id: 'ekp_099',
      questionText: 'Target Tujuan Pembangunan Berkelanjutan PBB yang terdiri dari 17 sasaran global dinamakan:',
      options: ['SDGs (Sustainable Development Goals)', 'MDGs', 'G20 Agenda', 'Paris Agreement'],
      correctOptionIndex: 0,
      explanation: 'SDGs menargetkan 17 tujuan global hingga tahun 2030.',
    ),
    QuestionItem(
      id: 'ekp_100',
      questionText: 'Bappenas merupakan singkatan dari badan perencanaan pembangunan Indonesia yaitu:',
      options: ['Badan Perencanaan Pembangunan Nasional', 'Badan Pengawas Pembangunan Nasional', 'Bank Perancangan Ekonomi Nasional', 'Biro Perencanaan Nasional'],
      correctOptionIndex: 0,
      explanation: 'Bappenas menyusun Rencana Pembangunan Jangka Panjang/Menengah Nasional (RPJPN/RPJMN).',
    ),
  ];
}
