// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/beri_hadiah/beri_hadiah_dialog_npc.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class BeriHadiahDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat diberi hadiah umum (pakaian, buku, gadget, dsb) berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Waaah! ( * $npcName memeluk pakaian/hadiah spesial barunya dengan gembira * ) 🎁👶',
        'Bababa! ( * $npcName mencerabut pita bungkus hadiah dan tertawa melihatnya * )',
        'Gigaaa! ( * $npcName mencium bungkus hadiah manis dari $parentName * )',
        'Ooooh! ( * $npcName menatap selimut/topi baru yang hangat dengan mata berbinar * )',
        'Hehehe! ( * $npcName memakai topi/sepatu barunya dan tertawa bangga * )',
        'Nyaaa! ( * $npcName meraba kelembutan kain hadiah pemberian $parentName * )',
        'Abuuu... ( * $npcName mengoceh riang sambil memperlihatkan hadiahnya ke sekitar * )',
        'Mammm! ( * $npcName mendusel di atas kotak hadiah empuk * )',
        'Dayaya! ( * $npcName menepuk-nepuk bungkus kertas hadiah yang berbunyi kriuk * )',
        'Tetete! ( * $npcName menggoyangkan bungkusan hadiah dengan kepalan tangan kecil * )',
        'Kicukicu! ( * $npcName memberikan senyuman bayi paling hangat untuk $parentName * )',
        'Ehhhe! ( * $npcName memakai sepatu bayi barunya dan belajar melangkah * )',
        'Agiii! ( * $npcName menyodorkan bungkusan hadiah ke muka $parentName sambil tersenyum * )',
        'Owooo! ( * $npcName merangkak mengelilingi kotak hadiah barunya * )',
        'Bubu! ( * $npcName menaruh hadiah barunya di dekat bantal tidurnya * )',
        'Lalala! ( * $npcName bergoyang gembira merayakan hadiah indah ini * )',
        'Hummm! ( * $npcName memegang erat hadiah pemberian $parentName * )',
        'Cicu! ( * $npcName mencium pipi $parentName dengan sangat manis * )',
        'Nyaa-ha! ( * $npcName melempar pita warna-warni ke udara sambil tertawa * )',
        'Paapapa! ( * $npcName memeluk $parentName erat-erat dengan rasa gembira * )',
        'Glooogloo! ( * $npcName meremas kertas kado warna-warni * )',
        'Oowgh! ( * $npcName tertidur pulas dalam balutan baju hadiah baru * )',
        'Yaaaya! ( * $npcName tersenyum lebar menampilkan wajah paling imut * )',
        'Wiii! ( * $npcName menunjukkan hadiah barunya ke cermin * )',
        'Tatatata! ( * $npcName menggenggam hadiah barunya sampai tertidur * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Horeeee! Hadiah istimewa! Makasih banyak ya $parentName! Aku suka banget! 🎁✨',
        'Wah! Ini baju/sepatu/perlengkapan lucu yang aku pengen banget! $parentName hebat!',
        'Yeay! Boleh langsung aku pakai/buka sekarang hadiahnya $parentName? Makasih ya!',
        'Makasih $parentName! Warnanya bagus dan pas banget di badanku!',
        'Uwah! $parentName emang orang tua paling perhatian dan penyayang di dunia!',
        'Asyik! Makasih $parentName! Nanti aku pamerin hadiah ini ke sepupu & teman!',
        'Makasih $parentName! Aku bakal rawat hadiah ini baik-baik dan jaga tidak kotor!',
        'Hore! Bungkus kadonya cantik banget! Makasih $parentName tercinta!',
        'Waaah! Berasa seperti hari ulang tahunku setiap dapat hadiah dari $parentName!',
        'Makasih $parentName! Ini jadi barang paling berharga di kamarku!',
        'Yeaaay! $parentName baik deh, kasih hadiah sebagus ini tanpa alasan!',
        'Makasih banyak $parentName! Sini aku peluk kenceng-kenceng sebagai rasa terima kasih!',
        'Asyik! Aku mau pakai baju/sepatu baru ini buat jalan-jalan besok! Makasih $parentName!',
        'Makasih $parentName! Kebahagiaanku hari ini beneran meluap-luap!',
        'Uwah, makasih $parentName! Aku janji bakal terus jadi anak yang soleh/solehah!',
        'Yippie! Terima kasih hadiah indahnya $parentName! Muaaah!',
        'Makasih $parentName! Aku sangat bersyukur punya orang tua seistimewa ini!',
        'Hore! Hadiah ini bener-bener surprise paling manis minggu ini!',
        'Waaah! Harum barang baru! Kualitasnya bagus banget $parentName!',
        'Makasih $parentName! Semoga $parentName selalu sehat dan banyak rezeki!',
        'Yeay! $parentName selalu ngerti barang yang paling aku butuhin!',
        'Makasih banyak $parentName! Ayo kita simpan baik-baik di lemari!',
        'Uwah, makasih $parentName sayang! I love you so much!',
        'Makasih $parentName! Hari ini aku jadi anak paling bahagia!',
        'Hore, makasih $parentName! Senyuman $parentName hadiah paling indah sebenarnya!',
      ];
    } else if (childAge <= 11) {
      return [
        'Wah! Makasih banyak ya $parentName! Hadiah buku/pakaian/peralatan ini bermanfaat banget! 🎁📚✨',
        'Terima kasih $parentName! Aku udah lama banget butuh barang ini buat sekolah/hobi!',
        'Asyik! Makasih $parentName! Kado dari orang tua memang selalu yang paling spesial.',
        'Alhamdulillah, terima kasih banyak $parentName! Ini kejutan manis yang luar biasa!',
        'Waaah! Desain dan ukurannya pas banget! Terima kasih banyak $parentName!',
        'Makasih $parentName! Aku bakal rawat barang ini sebaik-baiknya di kamar.',
        'Terima kasih $parentName! Hadiah ini bikin semangat belajarku makin membara.',
        'Hore! Terima kasih $parentName! Aku makin kagum sama perhatian $parentName.',
        'Wah, makasih ya $parentName! Barang ini bakal bantu banget buat aktivitas sehari-hari.',
        'Terima kasih $parentName! Hadiah spesial ini bikin hariku di sekolah jadi lebih percaya diri.',
        'Makasih banyak $parentName! Sayang $parentName banget!',
        'Asyik! Terima kasih $parentName! Penampilan/perlengkapanku jadi makin keren.',
        'Terima kasih $parentName! Nanti aku tunjukkan cara pakainya ke $parentName ya.',
        'Makasih $parentName! Perhatian tulus dari $parentName tiada bandingannya.',
        'Wah, senangnya! Terima kasih $parentName sudah selalu mengerti kebutuhanku.',
        'Terima kasih $parentName! Aku janji akan memanfaatkannya untuk hal-hal positif.',
        'Alhamdulillah, makasih $parentName! Senyum bahagia ini khusus buat $parentName.',
        'Terima kasih banyak $parentName! Semoga rezeki $parentName selalu melimpah.',
        'Makasih $parentName! Barang hadiah ini akan saya jaga sampai kapanpun.',
        'Wah makasih $parentName! Ini jadi hadiah kejutan terbaik tahun ini!',
        'Terima kasih $parentName! Semoga kebahagiaan selalu mengiringi keluarga kita.',
        'Asyik! Makasih $parentName! Aku merasa sangat dihargai dan disayangi.',
        'Terima kasih banyak $parentName! Senang banget punya orang tua sebaik $parentName.',
        'Makasih $parentName! Kasih sayang orang tua adalah karunia terindah dalam hidupku!',
        'Terima kasih $parentName! Aku simpan dengan rapi!',
      ];
    } else {
      return [
        'Wah, terima kasih banyak ya $parentName! Hadiah spesial ini sangat berguna & berkesan bagi saya. 🎁💳✨',
        'Alhamdulillah, terima kasih $parentName. Di usia dewasa saya ini, perhatian $parentName tetap terasa amat hangat.',
        'Terima kasih $parentName! Barang/hadiah ini benar-benar mendukung pekerjaan/studi/hobi saya.',
        'Wah, terima kasih banyak $parentName! Kejutan manis ini sungguh menyentuh hati saya.',
        'Terima kasih $parentName atas hadiah istimewa ini. Saya sangat menghargai pemberian orang tua.',
        'Makasih ya $parentName! $parentName selalu tahu persis apa yang sedang saya butuhkan saat ini.',
        'Terima kasih banyak $parentName! Ini akan menjadi salah satu barang paling berharga milik saya.',
        'Alhamdulillah, terima kasih $parentName! Kebahagiaan mendapat perhatian dari orang tua tak terulang.',
        'Terima kasih $parentName. Saya janji akan merawat dan memanfaatkan hadiah ini secara maksimal.',
        'Wah, terima kasih $parentName! Ini benar-benar hadiah yang sangat berkelas dan bermanfaat.',
        'Terima kasih banyak $parentName. Kasih sayang dan doa $parentName adalah hadiah terbesar sesungguhnya.',
        'Makasih ya $parentName! Nanti kita gunakan/nikmati barang ini bersama-sama ya!',
        'Terima kasih $parentName! Pemberian ini akan selalu mengingatkan saya pada pengorbanan orang tua.',
        'Alhamdulillah, makasih $parentName! Rasa syukur saya tak terhingga dilahirkan dalam keluarga ini.',
        'Terima kasih banyak $parentName! Semoga Allah/Tuhan membalas kebaikan $parentName berlipat ganda.',
        'Wah, terima kasih $parentName! Ini menambah motivasi dan rasa percaya diri saya.',
        'Terima kasih $parentName atas kehangatan ini. Saya bangga bisa membahagiakan $parentName.',
        'Makasih $parentName! Barang ini akan selalu saya jaga dengan penuh rasa hormat.',
        'Terima kasih banyak $parentName. Setiap pemberian $parentName mengandung doa tulus.',
        'Alhamdulillah, makasih $parentName! Saya sangat menyukai bentuk dan kualitas hadiah ini.',
        'Terima kasih $parentName! Semoga kesehatan dan umur panjang selalu menyertai $parentName.',
        'Wah, makasih banyak $parentName! Ini menjadi momen kebersamaan yang sangat indah.',
        'Terima kasih $parentName! Momen pemberian hadiah ini akan selalu saya kenang.',
        'Makasih ya $parentName... Kasih sayang orang tua memang tiada tandingannya.',
        'Terima kasih $parentName! I love you so much $parentName!',
      ];
    }
  }
}
