import '../tes_seleksi_model.dart';

List<QuestionItem> getAdministrasiPublikQuestions() {
  return const [
    QuestionItem(
      id: 'adp_001',
      questionText: 'Bapak Administrasi Publik Modern yang menulis esai bersejarah "The Study of Administration" (1887) adalah:',
      options: ['Woodrow Wilson', 'Max Weber', 'Frederick Taylor', 'Dwight Waldo'],
      correctOptionIndex: 0,
      explanation: 'Woodrow Wilson merintis pemisahan dikotomi politik dan administrasi publik.',
    ),
    QuestionItem(
      id: 'adp_002',
      questionText: 'Dikotomi Politik-Administrasi yang digagas Woodrow Wilson menegaskan bahwa:',
      options: ['Politik menetapkan kebijakan, sedangkan Administrasi melaksanakannya secara teknis netral', 'Politik dan Administrasi adalah hal yang sama', 'Administrasi menentukan hukum', 'Politik berada di bawah birokrasi'],
      correctOptionIndex: 0,
      explanation: 'Dikotomi Wilson membedakan ranah perumusan kebijakan politik dan eksekusi administrasi.',
    ),
    QuestionItem(
      id: 'adp_003',
      questionText: 'Bapak Sosiologi yang merumuskan konsep Tipe Ideal Birokrasi Rasional-Legal adalah:',
      options: ['Max Weber', 'Emile Durkheim', 'Karl Marx', 'Auguste Comte'],
      correctOptionIndex: 0,
      explanation: 'Max Weber merumuskan ciri-ciri birokrasi rasional-legal ideal.',
    ),
    QuestionItem(
      id: 'adp_004',
      questionText: 'Ciri utama birokrasi rasional-legal Weberian mencakup:',
      options: ['Hirarki jabatan formal, aturan tertulis, pembagian kerja, dan impersonalitas', 'Loyalitas pribadi, nepotisme, nepotisme, fleksibilitas', 'Kepemimpinan kharismatik', 'Sistem patron-klien'],
      correctOptionIndex: 0,
      explanation: 'Birokrasi Weberian beroperasi atas prinsip impersonalitas, aturan tertulis, dan meritokrasi.',
    ),
    QuestionItem(
      id: 'adp_005',
      questionText: 'Sistem pengangkatan pegawai negeri berdasarkan kualifikasi, prestasi, dan kompetensi dinamakan:',
      options: ['Merit System (Sistem Merit)', 'Spoils System', 'Patronage System', 'Nepotisme'],
      correctOptionIndex: 0,
      explanation: 'Merit System menjamin rekrutmen objektif tanpa diskriminasi politik.',
    ),
    QuestionItem(
      id: 'adp_006',
      questionText: 'Sistem pengangkatan jabatan publik berdasarkan pembalasan jasa politik partisan dinamakan:',
      options: ['Spoils System', 'Merit System', 'Career System', 'Civil Service'],
      correctOptionIndex: 0,
      explanation: 'Spoils System membagikan jabatan birokrasi kepada pendukung politik pemenang.',
    ),
    QuestionItem(
      id: 'adp_007',
      questionText: 'Akronim fungsi manajemen POSDCORB yang dikemukakan oleh Luther Gulick dan Lyndall Urwick singkatan dari:',
      options: ['Planning, Organizing, Staffing, Directing, Co-ordinating, Reporting, Budgeting', 'Policy, Operations, Service, Development, Control, Organization, Resources, Balance', 'Public, Open, System, Data, Control, Option, Risk, Business', 'Project, Output, Strategy, Delivery, Communication, Result, Budget'],
      correctOptionIndex: 0,
      explanation: 'POSDCORB adalah kerangka kerja manajemen klasik Gulick & Urwick.',
    ),
    QuestionItem(
      id: 'adp_008',
      questionText: 'Paradigma baru manajemen publik yang mengadopsi efisiensi teknis sektor swasta ke birokrasi pemerintahan dinamakan:',
      options: ['NPM (New Public Management)', 'NPS (New Public Service)', 'OPA (Old Public Administration)', 'Good Governance'],
      correctOptionIndex: 0,
      explanation: 'NPM (Hood / Osborne & Gaebler) mengenalkan prinsip "Reinventing Government" berbasis kinerja pasar.',
    ),
    QuestionItem(
      id: 'adp_009',
      questionText: 'Buku karya David Osborne dan Ted Gaebler yang memicu gelombang gerakan New Public Management berjudul:',
      options: ['Reinventing Government', 'The Study of Administration', 'Serving Not Steering', 'Public Governance'],
      correctOptionIndex: 0,
      explanation: 'Reinventing Government mengusulkan pemerintah "Steering, not Rowing".',
    ),
    QuestionItem(
      id: 'adp_010',
      questionText: 'Prinsip NPM "Steering, Rather Than Rowing" berarti peran pemerintah seharusnya:',
      options: ['Mengarahkan kebijakan dan regulasi, bukan menyelenggarakan seluruh operasional secara langsung', 'Mengayuh seluruh sektor', 'Menutup sektor swasta', 'Menyerahkan negara ke LSM'],
      correctOptionIndex: 0,
      explanation: 'Pemerintah bertindak sebagai pengarah (Steering) bukannya pengayuh operasional (Rowing).',
    ),
    QuestionItem(
      id: 'adp_011',
      questionText: 'Paradigma Administrasi Publik yang mengkritik NPM dan mengedepankan prinsip "Serving, Not Steering" dikembangkan oleh Denhardt & Denhardt dinamakan:',
      options: ['NPS (New Public Service)', 'NPM', 'OPA', 'Digital Governance'],
      correctOptionIndex: 0,
      explanation: 'NPS (Janet & Robert Denhardt) menegaskan birokrat bertugas melayani warga negara (Citizens), bukan sekadar pelanggan (Customers).',
    ),
    QuestionItem(
      id: 'adp_012',
      questionText: 'Fokus utama New Public Service (NPS) adalah menempatkan masyarakat sebagai:',
      options: ['Warga Negara (Citizens) yang memiliki hak demokratis', 'Pelanggan (Customers)', 'Klien pasif', 'Pembeli produk'],
      correctOptionIndex: 0,
      explanation: 'NPS mengutamakan martabat dan hak partisipasi kewarganegaraan.',
    ),
    QuestionItem(
      id: 'adp_013',
      questionText: 'Tiga pilar utama dalam konsep Tata Kelola Pemerintahan yang Baik (Good Governance) adalah kolaborasi antara:',
      options: ['Pemerintah (State), Sektor Swasta (Market), dan Masyarakat Sipil (Civil Society)', 'Presiden, DPR, MA', 'Polisi, Tentara, Jaksa', 'Pusat, Provinsi, Daerah'],
      correctOptionIndex: 0,
      explanation: 'Good Governance menuntut kepemerintahan kolaboratif State, Market, & Civil Society.',
    ),
    QuestionItem(
      id: 'adp_014',
      questionText: 'Prinsip keterbukaan akses informasi publik kepada masyarakat dalam Good Governance dinamakan:',
      options: ['Transparansi', 'Akuntabilitas', 'Responsivitas', 'Efisiensi'],
      correctOptionIndex: 0,
      explanation: 'Transparansi menjamin ketersediaan informasi publik yang jujur dan mudah diakses.',
    ),
    QuestionItem(
      id: 'adp_015',
      questionText: 'Kewajiban penyelenggara negara untuk mempertanggungjawabkan setiap kebijakan kepada publik dinamakan:',
      options: ['Akuntabilitas', 'Transparansi', 'Persuasi', 'Diskresi'],
      correctOptionIndex: 0,
      explanation: 'Akuntabilitas mengukur pertanggungjawaban hukum dan moral atas anggaran/kebijakan.',
    ),
    QuestionItem(
      id: 'adp_016',
      questionText: 'Ketanggapan pejabat publik dalam merespons aspirasi dan kebutuhan masyarakat dinamakan:',
      options: ['Responsivitas', 'Akuntabilitas', 'Efektivitas', 'Inovasi'],
      correctOptionIndex: 0,
      explanation: 'Responsivitas mengukur kecepatan dan ketepatan melayani kebutuhan publik.',
    ),
    QuestionItem(
      id: 'adp_017',
      questionText: 'Kebebasan mengambil keputusan atau tindakan oleh pejabat publik berdasarkan penilaian pribadi di luar aturan baku dinamakan:',
      options: ['Diskresi (Discretion)', 'Maladministrasi', 'Abuse of Power', 'Akuntabilitas'],
      correctOptionIndex: 0,
      explanation: 'Diskresi diperlukan untuk mengatasi situasi darurat yang belum diatur UU (UU No. 30/2014).',
    ),
    QuestionItem(
      id: 'adp_018',
      questionText: 'Syarat penggunaan diskresi pejabat publik menurut UU Administrasi Pemerintahan adalah:',
      options: ['Sesuai tujuan wewenang, tidak melanggar AAUPB, dan didasari alasan objektif', 'Bebas tanpa batas', 'Hanya untuk menghemat uang', 'Atas persetujuan DPR'],
      correctOptionIndex: 0,
      explanation: 'Diskresi dibatasi oleh asas-asas umum pemerintahan yang baik (AAUPB).',
    ),
    QuestionItem(
      id: 'adp_019',
      questionText: 'Singkatan AAUPB dalam Hukum Administrasi dan Publik Indonesia adalah:',
      options: ['Asas-Asas Umum Pemerintahan yang Baik', 'Aturan Administrasi Umum Pelayanan Publik', 'Alokasi Anggaran Usaha Publik Bersama', 'Asosiasi Advokasi Penyelenggara Birokrasi'],
      correctOptionIndex: 0,
      explanation: 'AAUPB memuat 8 prinsip etik etika birokrasi pemerintahan.',
    ),
    QuestionItem(
      id: 'adp_020',
      questionText: 'Tahapan siklus kebijakan publik (Public Policy Cycle) secara berurutan adalah:',
      options: ['Penyusunan Agenda, Formulasi, Adopsi/Legitimasi, Implementasi, dan Evaluasi', 'Implementasi, Formulasi, Evaluasi, Rencana', 'Formulasi, Rencana, Eksekusi, Pembatalan', 'Uji Coba, Eksekusi, Revisi, Hukum'],
      correctOptionIndex: 0,
      explanation: 'Siklus Kebijakan: Agenda Setting -> Formulasi -> Legitimasi -> Implementasi -> Evaluasi.',
    ),
    QuestionItem(
      id: 'adp_021',
      questionText: 'Tahap memasukkan masalah publik ke dalam daftar prioritas pembuat kebijakan dinamakan:',
      options: ['Penyusunan Agenda (Agenda Setting)', 'Formulasi Kebijakan', 'Legitimasi Kebijakan', 'Implementasi Kebijakan'],
      correctOptionIndex: 0,
      explanation: 'Agenda Setting menyeleksi isu mana yang layak ditangani negara.',
    ),
    QuestionItem(
      id: 'adp_022',
      questionText: 'Tahap perumusan dan penyusunan alternatif pemecahan masalah publik dinamakan:',
      options: ['Formulasi Kebijakan (Policy Formulation)', 'Penyusunan Agenda', 'Evaluasi Kebijakan', 'Legitimasi Kebijakan'],
      correctOptionIndex: 0,
      explanation: 'Formulasi menyusun rancangan pasal draft opsi kebijakan.',
    ),
    QuestionItem(
      id: 'adp_023',
      questionText: 'Tahap pengesahan hukum opsi kebijakan menjadi peraturan resmi negara dinamakan:',
      options: ['Legitimasi / Adopsi Kebijakan', 'Formulasi', 'Implementasi', 'Evaluasi'],
      correctOptionIndex: 0,
      explanation: 'Legitimasi memberi kekuatan hukum mengikat (seperti pengesahan UU oleh DPR).',
    ),
    QuestionItem(
      id: 'adp_024',
      questionText: 'Tahap pelaksanaan rancangan kebijakan di lapangan oleh lembaga eksekutif/birokrasi dinamakan:',
      options: ['Implementasi Kebijakan (Policy Implementation)', 'Formulasi', 'Evaluasi', 'Audit'],
      correctOptionIndex: 0,
      explanation: 'Implementasi meluncurkan program aksi kebijakan di lapangan.',
    ),
    QuestionItem(
      id: 'adp_025',
      questionText: 'Tahap penilaian pencapaian dampak dan efektivitas hasil pelaksanaan kebijakan dinamakan:',
      options: ['Evaluasi Kebijakan (Policy Evaluation)', 'Implementasi', 'Formulasi', 'Monitoring'],
      correctOptionIndex: 0,
      explanation: 'Evaluasi menilai apakah tujuan awal kebijakan tercapai.',
    ),
    QuestionItem(
      id: 'adp_026',
      questionText: 'Model pengambilan keputusan Incremental (Incremental Model) yang mengemukakan kebijakan baru hanya merupakan variasi kecil dari kebijakan lama dirumuskan oleh:',
      options: ['Charles Lindblom', 'Herbert Simon', 'Yehezkel Dror', 'Graham Allison'],
      correctOptionIndex: 0,
      explanation: 'Charles Lindblom merumuskan "The Science of Muddling Through" (Pengambilan keputusan inkremental).',
    ),
    QuestionItem(
      id: 'adp_027',
      questionText: 'Model Rasional Komprehensif (Rational-Comprehensive Model) menuntut pembuat kebijakan untuk:',
      options: ['Menganalisis seluruh alternatif dan konsekuensi secara rasional sempurna', 'Hanya meniru yang lama', 'Mengikuti intuisi', 'Mengambil keputusan acak'],
      correctOptionIndex: 0,
      explanation: 'Model Rasional Komprehensif mengasumsikan informasi sempurna.',
    ),
    QuestionItem(
      id: 'adp_028',
      questionText: 'Konsep "Bounded Rationality" (Rasionalitas Terbatas) dalam pengambilan keputusan dikemukakan oleh penerima Nobel:',
      options: ['Herbert A. Simon', 'Charles Lindblom', 'David Easton', 'Thomas Dye'],
      correctOptionIndex: 0,
      explanation: 'Herbert Simon membuktikan rasionalitas manusia terbatas oleh kapasitas otak dan waktu (Satisficing).',
    ),
    QuestionItem(
      id: 'adp_029',
      questionText: 'Keputusan memilih alternatif yang cukup memuaskan (Satisficing) ketimbang opsi optimal sempurna dirumuskan oleh:',
      options: ['Herbert A. Simon', 'Lindblom', 'Easton', 'Dror'],
      correctOptionIndex: 0,
      explanation: 'Satisficing = Satisfy + Suffice (Cukup memuaskan dalam keterbatasan).',
    ),
    QuestionItem(
      id: 'adp_030',
      questionText: 'Model Tong Sampah (Garbage Can Model) dalam pengambilan keputusan organisasi dikembangkan oleh:',
      options: ['Cohen, March, dan Olsen', 'Allison', 'Simon', 'Easton'],
      correctOptionIndex: 0,
      explanation: 'Garbage Can Model memodelkan keputusan acak dalam anarki organisasi.',
    ),
    QuestionItem(
      id: 'adp_031',
      questionText: 'Model Sistem Politik David Easton membagi alur kebijakan menjadi tiga bagian yaitu:',
      options: ['Input (Tuntutan & Dukungan), Process (Black Box), dan Output (Kebijakan)', 'Legislatif, Eksekutif, Yudikatif', 'Pusat, Provinsi, Kota', 'Perencanaan, Pelaksanaan, Evaluasi'],
      correctOptionIndex: 0,
      explanation: 'Model Sistem Easton: Input -> Sistem Politik -> Output -> Feedback.',
    ),
    QuestionItem(
      id: 'adp_032',
      questionText: 'Pendekatan analisis kebijakan publik Top-Down dalam implementasi kebijakan berfokus pada:',
      options: ['Kepatuhan agen pelaksana terhadap petunjuk juknis pembuat kebijakan di tingkat pusat', 'Aspirasi masyarakat bawah', 'Diskresi lapangan', 'Inovasi lokal'],
      correctOptionIndex: 0,
      explanation: 'Top-Down (Sabatier & Mazmanian) menekankan kontrol hierarki pusat.',
    ),
    QuestionItem(
      id: 'adp_033',
      questionText: 'Pendekatan Bottom-Up dalam implementasi kebijakan mengutamakan peran:',
      options: ['Birokrat tingkat bawah / lapangan (Street-Level Bureaucrats)', 'Menteri pusat', 'Presiden', 'DPR'],
      correctOptionIndex: 0,
      explanation: 'Bottom-Up (Elmore / Hjern) berfokus pada dinamika lapangan.',
    ),
    QuestionItem(
      id: 'adp_034',
      questionText: 'Istilah "Street-Level Bureaucrats" (Birokrat Tingkat Lapangan) seperti guru, polisi, dan perawat dikemukakan oleh:',
      options: ['Michael Lipsky', 'Dwight Waldo', 'Robert Merton', 'Fred Riggs'],
      correctOptionIndex: 0,
      explanation: 'Michael Lipsky mengemukakan birokrat lapangan membentuk realitas kebijakan nyata.',
    ),
    QuestionItem(
      id: 'adp_035',
      questionText: 'Model implementasi kebijakan Edward III membagi 4 variabel penentu keberhasilan yaitu:',
      options: ['Komunikasi, Sumber Daya, Disposisi/Sikap, dan Struktur Birokrasi', 'Politik, Uang, Senjata, Media', 'Hukum, Pajak, Izin, Wilayah', 'Perencanaan, Audit, Pengawasan, Evaluasi'],
      correctOptionIndex: 0,
      explanation: 'George C. Edward III merumuskan 4 faktor kunci implementasi.',
    ),
    QuestionItem(
      id: 'adp_036',
      questionText: 'Model implementasi Van Meter dan Van Horn menekankan pentingnya keterkaitan antara:',
      options: ['Ukuran & Tujuan Kebijakan, Sumber Daya, Hubungan Antarorganisasi, Karakteristik Agen, Lingkungan, dan Disposisi', 'Presiden dan DPR', 'Swasta dan LSM', 'Pusat dan Daerah'],
      correctOptionIndex: 0,
      explanation: 'Van Meter & Van Horn merumuskan kerangka variabel implementasi kebijakan.',
    ),
    QuestionItem(
      id: 'adp_037',
      questionText: 'Undang-Undang Republik Indonesia yang mengatur tentang Pelayanan Publik adalah UU Nomor:',
      options: ['UU No. 25 Tahun 2009', 'UU No. 32 Tahun 2004', 'UU No. 23 Tahun 2014', 'UU No. 5 Tahun 2014'],
      correctOptionIndex: 0,
      explanation: 'UU No. 25 Tahun 2009 adalah pilar standar pelayanan publik Indonesia.',
    ),
    QuestionItem(
      id: 'adp_038',
      questionText: 'Standar Pelayanan Publik wajib memuat dokumen kesanggupan penyelenggara yang dinamakan:',
      options: ['Maklumat Pelayanan', 'SOP', 'Sertifikasi ISO', 'Visi Misi'],
      correctOptionIndex: 0,
      explanation: 'Maklumat Pelayanan dipublikasikan sebagai janji kepastian standar layanan.',
    ),
    QuestionItem(
      id: 'adp_039',
      questionText: 'Survei pengukuran tingkat kepuasan masyarakat terhadap kualitas pelayanan publik dinamakan:',
      options: ['SKM (Survei Kepuasan Masyarakat)', 'IPM', 'IKU', 'RB Index'],
      correctOptionIndex: 0,
      explanation: 'SKM diukur berkala untuk mengevaluasi kualitas mutu layanan unit instansi.',
    ),
    QuestionItem(
      id: 'adp_040',
      questionText: 'Undang-Undang Aparatur Sipil Negara (ASN) yang mengatur status PNS dan PPPK disahkan pada UU Nomor:',
      options: ['UU No. 5 Tahun 2014 (jo UU No. 20 Tahun 2023)', 'UU No. 43 Tahun 1999', 'UU No. 8 Tahun 1974', 'UU No. 25 Tahun 2009'],
      correctOptionIndex: 0,
      explanation: 'UU ASN membagi pegawai ASN menjadi PNS dan PPPK.',
    ),
    QuestionItem(
      id: 'adp_041',
      questionText: 'Pegawai ASN yang diangkat dengan perjanjian kerja jangka waktu tertentu dinamakan:',
      options: ['PPPK (Pegawai Pemerintah dengan Perjanjian Kerja)', 'PNS', 'Honorer', 'Tenaga Alih Daya'],
      correctOptionIndex: 0,
      explanation: 'PPPK memiliki hak jabatan profesi ASN berbasis kontrak kinerja.',
    ),
    QuestionItem(
      id: 'adp_042',
      questionText: 'Nilai-Nilai Dasar (Core Values) ASN BerAKHLAK yang diluncurkan Presiden Jokowi merupakan akronim dari:',
      options: ['Berorientasi Pelayanan, Akuntabel, Kompeten, Harmonis, Loyal, Adaptif, Kolaboratif', 'Bersih, Amanah, Kerja, Hemat, Loyal, Aktif, Komitmen', 'Birokrasi, Akses, Kualitas, Hak, Landasan, Akurat, Kinerja', 'Berani, Adil, Komunikatif, Hasil, Luhur, Anggun, Konsisten'],
      correctOptionIndex: 0,
      explanation: 'BerAKHLAK adalah Core Values standar perilaku ASN Indonesia.',
    ),
    QuestionItem(
      id: 'adp_043',
      questionText: 'Badan Pemerintah yang bertugas mengelola manajemen kepegawaian ASN nasional adalah:',
      options: ['BKN (Badan Kepegawaian Negara)', 'LAN', 'KASN', 'KemenPAN-RB'],
      correctOptionIndex: 0,
      explanation: 'BKN mengelola tata usaha kepegawaian dan database ASN.',
    ),
    QuestionItem(
      id: 'adp_044',
      questionText: 'Kementerian yang membidangi perumusan kebijakan reformasi birokrasi dan pendayagunaan aparatur negara adalah:',
      options: ['KemenPAN-RB', 'Kementerian Dalam Negeri', 'Kementerian Sekretariat Negara', 'Bappenas'],
      correctOptionIndex: 0,
      explanation: 'KemenPAN-RB merumuskan kebijakan efisiensi dan reformasi birokrasi nasional.',
    ),
    QuestionItem(
      id: 'adp_045',
      questionText: 'Lembaga Pemerintah Nonkementerian yang bertugas menyelenggarakan kajian dan pendidikan pelatihan kepemimpinan ASN adalah:',
      options: ['LAN (Lembaga Administrasi Negara)', 'BKN', 'ANRI', 'ANRI'],
      correctOptionIndex: 0,
      explanation: 'LAN menyelenggarakan DIKLAT pimpinan dan inovasi administrasi negara.',
    ),
    QuestionItem(
      id: 'adp_046',
      questionText: 'Lembaga yang bertugas menyimpan dan mengelola kearsipan dokumen sejarah negara di Indonesia adalah:',
      options: ['ANRI (Arsip Nasional Republik Indonesia)', 'Perpusnas', 'LAN', 'BKN'],
      correctOptionIndex: 0,
      explanation: 'ANRI menjaga keutuhan memori kearsipan dokumentasi negara.',
    ),
    QuestionItem(
      id: 'adp_047',
      questionText: 'Undang-Undang yang mengatur tentang Pemerintahan Daerah saat ini diatur dalam UU Nomor:',
      options: ['UU No. 23 Tahun 2014', 'UU No. 32 Tahun 2004', 'UU No. 22 Tahun 1999', 'UU No. 5 Tahun 1974'],
      correctOptionIndex: 0,
      explanation: 'UU No. 23 Tahun 2014 mengatur pembagian urusan pemerintah pusat dan daerah.',
    ),
    QuestionItem(
      id: 'adp_048',
      questionText: 'Penyerahan wewenang pemerintahan oleh Pemerintah Pusat kepada daerah otonom untuk mengatur urusan rumah tangganya dinamakan:',
      options: ['Desentralisasi', 'Dekonsentrasi', 'Tugas Pembantuan', 'Sentralisasi'],
      correctOptionIndex: 0,
      explanation: 'Desentralisasi melahirkan otonomi daerah penuh.',
    ),
    QuestionItem(
      id: 'adp_049',
      questionText: 'Pelimpahan wewenang pemerintahan dari Pemerintah Pusat kepada Gubernur selaku wakil pemerintah di daerah dinamakan:',
      options: ['Dekonsentrasi', 'Desentralisasi', 'Tugas Pembantuan', 'Otonomi Khusus'],
      correctOptionIndex: 0,
      explanation: 'Dekonsentrasi pelimpahan wewenang kepada instansi vertikal/Gubernur.',
    ),
    QuestionItem(
      id: 'adp_050',
      questionText: 'Penugasan dari Pemerintah Pusat kepada Daerah dan/atau Desa untuk melaksanakan tugas tertentu dinamakan:',
      options: ['Tugas Pembantuan (Medebewind)', 'Dekonsentrasi', 'Desentralisasi', 'Otonomi'],
      correctOptionIndex: 0,
      explanation: 'Tugas Pembantuan disertai pembiayaan dari pengutus.',
    ),
    QuestionItem(
      id: 'adp_051',
      questionText: 'Enam Urusan Pemerintahan Absolut yang sepenuhnya menjadi wewenang Pemerintah Pusat (tidak didesentralisasikan) adalah:',
      options: ['Politik Luar Negeri, Pertahanan, Keamanan, Yustisi, Moneter/Fiskal Nasional, dan Agama', 'Pendidikan, Kesehatan, Jalan, Pasar, Pertanian, Tambang', 'Pajak, Parawisata, Hutan, Laut, Perhubungan, Kerja', 'Seni, Olahraga, Budaya, Satpol, Kebersihan, Taman'],
      correctOptionIndex: 0,
      explanation: '6 urusan absolut tidak boleh diserahkan ke daerah otonom.',
    ),
    QuestionItem(
      id: 'adp_052',
      questionText: 'Dokumen Perencanaan Pembangunan Daerah jangka menengah periode 5 tahunan dinamakan:',
      options: ['RPJMD (Rencana Pembangunan Jangka Menengah Daerah)', 'RPJPD', 'RKPD', 'Renstra'],
      correctOptionIndex: 0,
      explanation: 'RPJMD menyelaraskan visi-misi kepala daerah terpilih selama 5 tahun.',
    ),
    QuestionItem(
      id: 'adp_053',
      questionText: 'Dokumen perencanaan tahunan daerah yang menjadi acuan penyusunan APBD dinamakan:',
      options: ['RKPD (Rencana Kerja Pemerintah Daerah)', 'RPJMD', 'Renja', 'KUA-PPAS'],
      correctOptionIndex: 0,
      explanation: 'RKPD adalah dokumen perencanaan tahunan pemerintah daerah.',
    ),
    QuestionItem(
      id: 'adp_054',
      questionText: 'Forum musyawarah tahunan pemangku kepentingan untuk menyepakati rencana pembangunan daerah dinamakan:',
      options: ['Musrenbang (Musyawarah Perencanaan Pembangunan)', 'KUA-PPAS', 'Rakerda', 'Paripurna'],
      correctOptionIndex: 0,
      explanation: 'Musrenbang menghimpun aspirasi dari tingkat desa hingga provinsi.',
    ),
    QuestionItem(
      id: 'adp_055',
      questionText: 'Undang-Undang yang mengatur tentang Desa di Indonesia adalah UU Nomor:',
      options: ['UU No. 6 Tahun 2014', 'UU No. 23 Tahun 2014', 'UU No. 32 Tahun 2004', 'UU No. 25 Tahun 2009'],
      correctOptionIndex: 0,
      explanation: 'UU Desa No. 6/2014 memberikan otonomi dan Dana Desa langsung.',
    ),
    QuestionItem(
      id: 'adp_056',
      questionText: 'Lembaga di desa yang menjalankan fungsi legislasi dan pengawasan pemerintahan desa dinamakan:',
      options: ['BPD (Badan Permusyawaratan Desa)', 'LPMD', 'Karang Taruna', 'PKK'],
      correctOptionIndex: 0,
      explanation: 'BPD adalah perwakilan masyarakat desa penyusun Peraturan Desa.',
    ),
    QuestionItem(
      id: 'adp_057',
      questionText: 'Alokasi anggaran APBN yang dikucurkan langsung ke rekening desa dinamakan:',
      options: ['Dana Desa', 'ADD (Alokasi Dana Desa)', 'Bantuan Keuangan', 'BHPR'],
      correctOptionIndex: 0,
      explanation: 'Dana Desa bersumber langsung dari APBN pusat.',
    ),
    QuestionItem(
      id: 'adp_058',
      questionText: 'Dana transfer bagian dari Kabupaten/Kota kepada desa yang bersumber dari DAU dan DBH dinamakan:',
      options: ['ADD (Alokasi Dana Desa)', 'Dana Desa', 'Dana Hibah', 'BUMDes'],
      correctOptionIndex: 0,
      explanation: 'ADD bersumber dari APBD Kabupaten minimal 10%.',
    ),
    QuestionItem(
      id: 'adp_059',
      questionText: 'Penerapan Teknologi Informasi dan Komunikasi (TIK) dalam penyelenggaraan pemerintah dinamakan:',
      options: ['E-Government / SPBE (Sistem Pemerintahan Berbasis Elektronik)', 'Digital Smart', 'Cyber Gov', 'E-Procurement'],
      correctOptionIndex: 0,
      explanation: 'SPBE (E-Gov) efisiensi transparansi layanan berbasis teknologi.',
    ),
    QuestionItem(
      id: 'adp_060',
      questionText: 'Sistem pengadaan barang dan jasa pemerintah secara elektronik dinamakan:',
      options: ['E-Procurement (LPSE / Catalog)', 'E-Budgeting', 'E-Kinerja', 'E-Audit'],
      correctOptionIndex: 0,
      explanation: 'LPSE E-Procurement menekan korupsi transparansi lelang proyek negara.',
    ),
    QuestionItem(
      id: 'adp_061',
      questionText: 'Metode penganggaran yang mengaitkan setiap alokasi dana dengan target kinerja yang terukur dinamakan:',
      options: ['Performance-Based Budgeting (Penganggaran Berbasis Kinerja)', 'Traditional Budgeting', 'Zero-Based Budgeting', 'Line-Item Budgeting'],
      correctOptionIndex: 0,
      explanation: 'Penganggaran Berbasis Kinerja berfokus pada output dan outcome terukur.',
    ),
    QuestionItem(
      id: 'adp_062',
      questionText: 'Metode penganggaran di mana setiap alokasi dana disusun dari nol kembali tanpa mengacu anggaran lalu dinamakan:',
      options: ['Zero-Based Budgeting (ZBB)', 'Incremental Budgeting', 'Line-Item', 'PPBS'],
      correctOptionIndex: 0,
      explanation: 'ZBB mengharuskan justifikasi ulang seluruh pos dari nol.',
    ),
    QuestionItem(
      id: 'adp_063',
      questionText: 'Metode penganggaran tradisional berdasar penambahan persentase tertentu dari anggaran tahun sebelumnya dinamakan:',
      options: ['Incremental Budgeting', 'Zero-Based Budgeting', 'Performance Budgeting', 'Output Budgeting'],
      correctOptionIndex: 0,
      explanation: 'Incremental budgeting menambahkan kenaikan persentase historis.',
    ),
    QuestionItem(
      id: 'adp_064',
      questionText: 'Indikator Kinerja Utama instansi pemerintah dalam sistem akuntabilitas dikenal dengan singkatan:',
      options: ['IKU (Indikator Kinerja Utama / KPI)', 'AKIP', 'LAKIP', 'SAKIP'],
      correctOptionIndex: 0,
      explanation: 'IKU adalah ukuran keberhasilan prioritas instansi.',
    ),
    QuestionItem(
      id: 'adp_065',
      questionText: 'Sistem Akuntabilitas Kinerja Instansi Pemerintah di Indonesia dikenal dengan singkatan:',
      options: ['SAKIP', 'LAKIP', 'IKU', 'RB'],
      correctOptionIndex: 0,
      explanation: 'SAKIP mengintegrasikan perencanaan, penganggaran, dan pelaporan kinerja.',
    ),
    QuestionItem(
      id: 'adp_066',
      questionText: 'Laporan tahunan pertanggungjawaban kinerja instansi pemerintah yang disampaikan ke KemenPAN-RB dinamakan:',
      options: ['LAKIP / LKjIP', 'LPPD', 'LKPJ', 'LPJ'],
      correctOptionIndex: 0,
      explanation: 'LKjIP berisi laporan akuntabilitas kinerja instansi.',
    ),
    QuestionItem(
      id: 'adp_067',
      questionText: 'Laporan Penyelenggaraan Pemerintahan Daerah yang disampaikan Kepala Daerah kepada Pemerintah Pusat dinamakan:',
      options: ['LPPD', 'LKPJ', 'RLPPD', 'LAKIP'],
      correctOptionIndex: 0,
      explanation: 'LPPD disampaikan Gubernur/Bupati ke Kemendagri.',
    ),
    QuestionItem(
      id: 'adp_068',
      questionText: 'Laporan Keterangan Pertanggungjawaban kepala daerah yang disampaikan kepada DPRD dinamakan:',
      options: ['LKPJ', 'LPPD', 'LKjIP', 'SAKIP'],
      correctOptionIndex: 0,
      explanation: 'LKPJ dilaporkan kepala daerah di sidang paripurna DPRD.',
    ),
    QuestionItem(
      id: 'adp_069',
      questionText: 'Predikat opini pemeriksaan keuangan tertinggi dari Badan Pemeriksa Keuangan (BPK) atas laporan keuangan instansi adalah:',
      options: ['WTP (Wajar Tanpa Pengecualian)', 'WDP (Wajar Dengan Pengecualian)', 'TW (Tidak Wajar)', 'TMP (Disclaimer)'],
      correctOptionIndex: 0,
      explanation: 'WTP adalah predikat audit keuangan terbaik BPK.',
    ),
    QuestionItem(
      id: 'adp_070',
      questionText: 'Opini BPK di mana auditor menolak memberikan pendapat karena pembukuan tidak lengkap dinamakan:',
      options: ['Disclaimer / TMP (Tidak Menyatakan Pendapat)', 'WTP', 'WDP', 'TW'],
      correctOptionIndex: 0,
      explanation: 'Disclaimer (TMP) terjadi jika auditor tidak bisa memperoleh bukti memadai.',
    ),
    QuestionItem(
      id: 'adp_071',
      questionText: 'Lembaga pengawas internal pemerintah di lingkungan kementerian/lembaga/daerah dikenal sebagai APIP yaitu:',
      options: ['Aparat Pengawasan Intern Pemerintah (Inspektorat / BPKP)', 'BPK', 'KPK', 'BKN'],
      correctOptionIndex: 0,
      explanation: 'APIP bertindak sebagai auditor internal pemerintah.',
    ),
    QuestionItem(
      id: 'adp_072',
      questionText: 'Badan Pengawasan Keuangan dan Pembangunan di bawah Presiden dinamakan:',
      options: ['BPKP', 'BPK', 'Inspektorat Jenderal', 'Bappenas'],
      correctOptionIndex: 0,
      explanation: 'BPKP membimbing pengawasan akuntabilitas keuangan negara.',
    ),
    QuestionItem(
      id: 'adp_073',
      questionText: 'Badan independen pemeriksaan keuangan negara yang diatur UUD 1945 adalah:',
      options: ['BPK (Badan Pemeriksa Keuangan)', 'BPKP', 'Kemenkeu', 'OJK'],
      correctOptionIndex: 0,
      explanation: 'BPK melakukan pemeriksaan eksternal atas pengelolaan uang negara.',
    ),
    QuestionItem(
      id: 'adp_074',
      questionText: 'Zona Integritas menuju Wilayah Bebas dari Korupsi di lingkungan birokrasi dikenal dengan singkatan:',
      options: ['WBK / WBBM', 'WTP', 'ISO', 'SAKIP'],
      correctOptionIndex: 0,
      explanation: 'Predikat WBK (Wilayah Bebas Korupsi) & WBBM (Wilayah Birokrasi Bersih Melayani).',
    ),
    QuestionItem(
      id: 'adp_075',
      questionText: 'Gagasan reformasi birokrasi komprehensif 8 area perubahan untuk meningkatkan efisiensi pemerintahan dinamakan:',
      options: ['Reformasi Birokrasi (RB)', 'Deregulasi', 'Debirokrasi', 'Restrukturisasi'],
      correctOptionIndex: 0,
      explanation: 'Grand Design Reformasi Birokrasi menargetkan birokrasi berkelas dunia.',
    ),
    QuestionItem(
      id: 'adp_076',
      questionText: 'Pemberian kompensasi tunjangan berbasis kelas jabatan dan capaian kinerja pegawai ASN dinamakan:',
      options: ['Tukin (Tunjangan Kinerja)', 'Gaji Pokok', 'Honorarium', 'Bonus'],
      correctOptionIndex: 0,
      explanation: 'Tunjangan Kinerja diberikan berdasar evaluasi kinerja dan reformasi birokrasi.',
    ),
    QuestionItem(
      id: 'adp_077',
      questionText: 'Metode analisis pembobotan nilai jabatan untuk menentukan kelas jabatan PNS dinamakan:',
      options: ['Evaluasi Jabatan (Job Evaluation)', 'Job Description', 'Analisis Beban Kerja', 'Anjab'],
      correctOptionIndex: 0,
      explanation: 'Evaluasi Jabatan menetapkan grade nilai kelas jabatan.',
    ),
    QuestionItem(
      id: 'adp_078',
      questionText: 'Perhitungan kebutuhan jumlah pegawai ideal berbasis volume beban kerja instansi dinamakan:',
      options: ['ABK (Analisis Beban Kerja)', 'Anjab', 'Peta Jabatan', 'Formasi'],
      correctOptionIndex: 0,
      explanation: 'ABK menghitung rasio jam kerja dan beban tugas.',
    ),
    QuestionItem(
      id: 'adp_079',
      questionText: 'Penyusunan uraian tugas, fungsi, dan kualifikasi persyaratan suatu jabatan dinamakan:',
      options: ['Anjab (Analisis Jabatan)', 'ABK', 'Evaluasi Jabatan', 'SOP'],
      correctOptionIndex: 0,
      explanation: 'Anjab menghasilkan uraian jabatan dan syarat jabatan.',
    ),
    QuestionItem(
      id: 'adp_080',
      questionText: 'Dokumen standar prosedur operasional langkah kerja birokrasi dikenal dengan istilah:',
      options: ['SOP (Standard Operating Procedure)', 'Juknis', 'Juklak', 'SK'],
      correctOptionIndex: 0,
      explanation: 'SOP menjamin kepastian tahapan dan standar kualitas kerja.',
    ),
    QuestionItem(
      id: 'adp_081',
      questionText: 'Penyederhanaan tingkatan struktural birokrasi mengalihkan ke jabatan fungsional dinamakan:',
      options: ['Delayering / Penyederhanaan Birokrasi', 'Sentralisasi', 'Downsizing', 'Outsourcing'],
      correctOptionIndex: 0,
      explanation: 'Delayering memangkas eselonisasi (Eselon III & IV) beralih ke fungsional.',
    ),
    QuestionItem(
      id: 'adp_082',
      questionText: 'Kelompok Jabatan ASN yang menunjukkan keahlian dan keterampilan spesifik independen dinamakan:',
      options: ['Jabatan Fungsional (JF)', 'Jabatan Pimpinan Tinggi', 'Jabatan Administrator', 'Jabatan Pelaksana'],
      correctOptionIndex: 0,
      explanation: 'Jabatan Fungsional berbasis angka kredit kepakaran.',
    ),
    QuestionItem(
      id: 'adp_083',
      questionText: 'Jabatan struktural tertinggi di lingkungan instansi pemerintah (Eselon I & II) dinamakan:',
      options: ['JPT (Jabatan Pimpinan Tinggi)', 'JA', 'JF', 'JFP'],
      correctOptionIndex: 0,
      explanation: 'JPT (Utama, Madya, Pratama) diisi melalui seleksi terbuka terikat merit system.',
    ),
    QuestionItem(
      id: 'adp_084',
      questionText: 'Proses seleksi terbuka calon pejabat pimpinan tinggi birokrasi (JPT) dikenal dengan istilah:',
      options: ['Open Bidding (Lelang Jabatan)', 'Spoils System', 'Mutasi Direct', 'Promosi Otomatis'],
      correctOptionIndex: 0,
      explanation: 'Open Bidding mengundang kandidat berkompetensi secara transparan.',
    ),
    QuestionItem(
      id: 'adp_085',
      questionText: 'Birokrasi yang mengalami pembengkakan struktur departemen tanpa peningkatan fungsi dinamakan:',
      options: ['Parkinson\'s Law (Hukum Parkinson)', 'Peter Principle', 'Weberian', 'NPM'],
      correctOptionIndex: 0,
      explanation: 'Hukum Parkinson: "Work expands so as to fill the time available for its completion".',
    ),
    QuestionItem(
      id: 'adp_086',
      questionText: 'Prinsip yang mengemukakan setiap pegawai cenderung dipromosikan hingga mencapai tingkat ketidakmampuannya dinamakan:',
      options: ['Peter Principle (Prinsip Peter)', 'Parkinson\'s Law', 'Murphy\'s Law', 'Pareto Principle'],
      correctOptionIndex: 0,
      explanation: 'Peter Principle: "In a hierarchy every employee tends to rise to his level of incompetence".',
    ),
    QuestionItem(
      id: 'adp_087',
      questionText: 'Model Ekologi Administrasi Publik yang membandingkan sistem birokrasi negara berkembang (Prismatic Society) dirumuskan oleh:',
      options: ['Fred W. Riggs', 'Ferrel Heady', 'Dwight Waldo', 'William Siffin'],
      correctOptionIndex: 0,
      explanation: 'Fred Riggs merumuskan Model Masyarakat Prisma (Prismatic Society) dengan ciri Formalisme & Hetrogenitas.',
    ),
    QuestionItem(
      id: 'adp_088',
      questionText: 'Kondisi di mana aturan undang-undang ditetapkan secara formal namun tidak dilaksanakan dalam praktik nyata menurut Riggs dinamakan:',
      options: ['Formalisme (Formalism)', 'Overlap', 'Nepotisme', 'Birokratisme'],
      correctOptionIndex: 0,
      explanation: 'Formalisme adalah jurang perbedaan antara hukum tertulis dan praktik nyata.',
    ),
    QuestionItem(
      id: 'adp_089',
      questionText: 'Teori Barang Publik (Public Goods) membedakan barang publik murni dari dua sifat utama yaitu:',
      options: ['Non-Rivalry (Tidak Saling Menyaingi) dan Non-Excludable (Tidak Bisa Dikecualikan)', 'Murah dan Gratis', 'Dibuat Pemerintah dan Dijual Swasta', 'Lokal dan Nasional'],
      correctOptionIndex: 0,
      explanation: 'Public Goods (seperti lampu jalan) bersifat Non-Rival & Non-Excludable.',
    ),
    QuestionItem(
      id: 'adp_090',
      questionText: 'Fenomena di mana seseorang menikmati manfaat barang publik tanpa ikut membayar biaya penyediaannya dinamakan:',
      options: ['Free-Rider Problem (Masalah Penumpang Gratis)', 'Moral Hazard', 'Adverse Selection', 'Public Waste'],
      correctOptionIndex: 0,
      explanation: 'Free-Rider terjadi pada barang publik akibat sifat Non-Excludable.',
    ),
    QuestionItem(
      id: 'adp_091',
      questionText: 'Kegagalan pasar (Market Failure) yang memicu dibutuhkannya intervensi regulasi pemerintah disebabkan oleh:',
      options: ['Eksternalitas, Monopoli Alami, Barang Publik, dan Asimetri Informasi', 'Pajak Tinggi', 'Inflasi', 'Bencana'],
      correctOptionIndex: 0,
      explanation: 'Kegagalan pasar melegitimasi intervensi peran kebijakan publik.',
    ),
    QuestionItem(
      id: 'adp_092',
      questionText: 'Dampak sampingan aktivitas ekonomi yang merugikan atau menguntungkan pihak ketiga tanpa kompensasi pasar dinamakan:',
      options: ['Eksternalitas (Externality)', 'Monopoli', 'Defisit', 'Subsidi'],
      correctOptionIndex: 0,
      explanation: 'Eksternalitas (seperti polusi pabrik) membutuhkan pajak/regulasi insentif pemerintah.',
    ),
    QuestionItem(
      id: 'adp_093',
      questionText: 'Bentuk kerja sama penyediaan infrastruktur publik antara pemerintah dan korporasi swasta dinamakan:',
      options: ['KPBU (Kerja Sama Pemerintah dan Badan Usaha / PPP)', 'BUMN', 'Privatisasi Murni', 'Swakelola'],
      correctOptionIndex: 0,
      explanation: 'KPBU (Public-Private Partnership) membagi risiko dan pendanaan infrastruktur.',
    ),
    QuestionItem(
      id: 'adp_094',
      questionText: 'Pengalihan kepemilikan BUMN atau aset negara ke tangan sektor swasta dinamakan:',
      options: ['Privatisasi', 'Nationalisasi', 'Holdinisasi', 'Restrukturisasi'],
      correctOptionIndex: 0,
      explanation: 'Privatisasi melepas saham instansi publik ke pasar modal swasta.',
    ),
    QuestionItem(
      id: 'adp_095',
      questionText: 'Pengambilalihan perusahaan swasta atau asing menjadi aset milik pemerintah dinamakan:',
      options: ['Nasionalisasi', 'Privatisasi', 'Merger', 'Spinoff'],
      correctOptionIndex: 0,
      explanation: 'Nasionalisasi mengalihkan kepemilikan swasta ke tangan negara.',
    ),
    QuestionItem(
      id: 'adp_096',
      questionText: 'Instansi pemerintah yang dibentuk untuk memberikan pelayanan barang/jasa kepada masyarakat dengan fleksibilitas pengelolaan keuangan dinamakan:',
      options: ['BLU (Badan Layanan Umum / BLUD)', 'BUMN', 'BUMD', 'Perum'],
      correctOptionIndex: 0,
      explanation: 'BLU (seperti RSUD dan PTN-BH) mengelola penerimaan non-pajak secara langsung.',
    ),
    QuestionItem(
      id: 'adp_097',
      questionText: 'Gagasan Maladministrasi dalam pelayanan publik mencakup perbuatan:',
      options: ['Penundaan berlarut, penyalahgunaan wewenang, penyimpangan prosedur, pemerasan, dan ketidakpatuhan', 'Gaji kecil', 'Cuti pegawai', 'Pindah kantor'],
      correctOptionIndex: 0,
      explanation: 'Maladministrasi mengacu pada perilaku buruk birokrasi yang merugikan publik.',
    ),
    QuestionItem(
      id: 'adp_098',
      questionText: 'Sistem pengaduan pelayanan publik nasional terpadu berbasis online di Indonesia dinamakan:',
      options: ['SP4N-LAPOR!', 'LPSN', 'Siber Pungli', 'SIPP'],
      correctOptionIndex: 0,
      explanation: 'SP4N-LAPOR! mengintegrasikan pengaduan warga ke seluruh instansi pemerintah.',
    ),
    QuestionItem(
      id: 'adp_099',
      questionText: 'Gagasan "Digital Governance" (E-Governance) bertujuan menciptakan birokrasi yang:',
      options: ['Lincah (Agile), transparan, efisien, dan berbasis data real-time', 'Kaku', 'Tertutup', 'Lambat'],
      correctOptionIndex: 0,
      explanation: 'Digital Governance mengtransformasikan layanan publik berbasis ekosistem siber.',
    ),
    QuestionItem(
      id: 'adp_100',
      questionText: 'Visi Reformasi Birokrasi Indonesia 2045 adalah mewujudkan pemerintahan:',
      options: ['World Class Bureaucracy (Birokrasi Berkelas Dunia)', 'Birokrasi Tradisional', 'Birokrasi Sentralistik', 'Birokrasi Partai'],
      correctOptionIndex: 0,
      explanation: 'World Class Bureaucracy menjadi puncak pencapaian tata kelola aparatur Indonesia 2045.',
    ),
  ];
}
