import '../tes_seleksi_model.dart';

List<QuestionItem> getKriminologiQuestions() {
  return const [
    QuestionItem(
      id: 'krim_001',
      questionText: 'Pakar yang pertama kali memperkenalkan istilah "Kriminologi" pada tahun 1879 adalah antropolog Prancis bernama:',
      options: ['Paul Topinard', 'Raffaele Garofalo', 'Cesare Lombroso', 'Enrico Ferri'],
      correctOptionIndex: 0,
      explanation: 'Paul Topinard pertama kali menyebut istilah Kriminologi pada tahun 1879.',
    ),
    QuestionItem(
      id: 'krim_002',
      questionText: 'Bapak Kriminologi Modern yang mengusung Mazhab Positivis Kriminologi adalah:',
      options: ['Cesare Lombroso', 'Cesare Beccaria', 'Jeremy Bentham', 'Edwin Sutherland'],
      correctOptionIndex: 0,
      explanation: 'Cesare Lombroso menulis "L\'Uomo Delinquente" (1876) merintis antropologi kriminal Positivis.',
    ),
    QuestionItem(
      id: 'krim_003',
      questionText: 'Teori Lombroso tentang penjahat yang terlahir (Born Criminal) ditandai dengan ciri fisik kemunduran evolusi dinamakan:',
      options: ['Atavisme (Atavism)', 'Anomie', 'Stigma', 'Somatotype'],
      correctOptionIndex: 0,
      explanation: 'Atavisme mengasumsikan penjahat memiliki stigmata fisik kehewanan primitif.',
    ),
    QuestionItem(
      id: 'krim_004',
      questionText: 'Bapak Mazhab Kriminologi Klasik yang menulis buku terkenal "On Crimes and Punishments" (1764) adalah:',
      options: ['Cesare Beccaria', 'Cesare Lombroso', 'Jeremy Bentham', 'Emile Durkheim'],
      correctOptionIndex: 0,
      explanation: 'Cesare Beccaria mengusung Mazhab Klasik berbasis kehendak bebas (free will) dan rasionalitas.',
    ),
    QuestionItem(
      id: 'krim_005',
      questionText: 'Prinsip Mazhab Klasik Kriminologi mengasumsikan bahwa manusia melakukan kejahatan atas dasar kalkulasi:',
      options: ['Kalkulasi Utilitarian (Hedonistic Calculus / Penimbangan Kesenangan vs Penderitaan)', 'Kesurupan', 'Fisik Genetik', 'Kemiskinan'],
      correctOptionIndex: 0,
      explanation: 'Jeremy Bentham & Beccaria memodelkan kalkulasi rasional keuntungan vs hukuman.',
    ),
    QuestionItem(
      id: 'krim_006',
      questionText: 'Tiga syarat efektivitas hukuman menurut Beccaria agar mampu mencegah kejahatan adalah:',
      options: ['Kepastian (Certainty), Kecepatan (Celerity), dan Keparahan yang proporsional (Severity)', 'Penyiksaan, Kebencian, Kejam', 'Penjara Seumur Hidup, Hukuman Mati, Denda', 'Pengasingan, Pekerjaan Paksa, Cambuk'],
      correctOptionIndex: 0,
      explanation: 'Beccaria menekankan kepastian (Certainty) lebih efektif daripada keparahan siksaan.',
    ),
    QuestionItem(
      id: 'krim_007',
      questionText: 'Teori Asosiasi Diferensial (Differential Association Theory) yang menyatakan kejahatan dipelajari melalui interaksi komunikasi dikemukakan oleh:',
      options: ['Edwin H. Sutherland', 'Robert K. Merton', 'Travis Hirschi', 'Howard Becker'],
      correctOptionIndex: 0,
      explanation: 'Sutherland menegaskan kejahatan adalah perilaku yang dipelajari (learned behavior) dalam kelompok intim.',
    ),
    QuestionItem(
      id: 'krim_008',
      questionText: 'Sutherland juga mempopulerkan istilah kejahatan kerah putih yang dilakukan pejabat atau pengusaha dinamakan:',
      options: ['White-Collar Crime', 'Blue-Collar Crime', 'Corporate Crime', 'Cyber Crime'],
      correctOptionIndex: 0,
      explanation: 'Sutherland merintis konsep White-Collar Crime (kejahatan orang terpandang berstatus sosial tinggi).',
    ),
    QuestionItem(
      id: 'krim_009',
      questionText: 'Kejahatan konvensional jalanan seperti pencurian, perampokan, dan penganiayaan dinamakan:',
      options: ['Blue-Collar Crime (Street Crime)', 'White-Collar Crime', 'Organized Crime', 'State Crime'],
      correctOptionIndex: 0,
      explanation: 'Blue-Collar Crime terjadi pada kejahatan fisik jalanan rakyat awam.',
    ),
    QuestionItem(
      id: 'krim_010',
      questionText: 'Teori Anomie karya Emile Durkheim mengartikan "Anomie" sebagai kondisi:',
      options: ['Normlessness (Ketiadaan atau kekacauan norma sosial)', 'Kemiskinan ekstrem', 'Sakit jiwa', 'Pemberontakan'],
      correctOptionIndex: 0,
      explanation: 'Anomie adalah hancurnya aturan atau pedoman norma masyarakat.',
    ),
    QuestionItem(
      id: 'krim_011',
      questionText: 'Teori Ketegangan (Strain Theory) yang mengadaptasi konsep Anomie menjadi ketimpangan antara tujuan budaya dan sarana resmi dikembangkan oleh:',
      options: ['Robert K. Merton', 'Emile Durkheim', 'Robert Agnew', 'Albert Cohen'],
      correctOptionIndex: 0,
      explanation: 'Merton menjelaskan Strain terjadi saat sarana resmi (means) tidak memadai mencapai tujuan (goals).',
    ),
    QuestionItem(
      id: 'krim_012',
      questionText: 'Lima bentuk adaptasi individu terhadap Strain menurut Merton yang menghasilkan kejahatan utamanya adalah:',
      options: ['Inovasi (Innovation)', 'Konformitas', 'Ritualisme', 'Retreatisme'],
      correctOptionIndex: 0,
      explanation: 'Inovasi menerima tujuan budaya tetapi menggunakan sarana ilegal/kejahatan.',
    ),
    QuestionItem(
      id: 'krim_013',
      questionText: 'Bentuk adaptasi Merton di mana individu menolak tujuan budaya dan sarana resmi lalu menarik diri (seperti pecandu narkoba berat) dinamakan:',
      options: ['Retreatisme (Retreatism)', 'Rebellion', 'Ritualisme', 'Inovasi'],
      correctOptionIndex: 0,
      explanation: 'Retreatisme menarik diri dari tujuan dan aturan masyarakat.',
    ),
    QuestionItem(
      id: 'krim_014',
      questionText: 'Bentuk adaptasi Merton di mana individu menolak tujuan dan sarana lama lalu memperjuangkan tatanan baru (revolusioner) dinamakan:',
      options: ['Pemberontakan (Rebellion)', 'Inovasi', 'Retreatisme', 'Ritualisme'],
      correctOptionIndex: 0,
      explanation: 'Rebellion mencoba mengganti norma lama dengan tatanan baru.',
    ),
    QuestionItem(
      id: 'krim_015',
      questionText: 'Teori Kontrol Sosial (Social Bond Theory) yang menyatakan seseorang tidak berbuat jahat karena memiliki ikatan sosial dipelopori oleh:',
      options: ['Travis Hirschi', 'Walter Reckless', 'Albert Bandura', 'Edwin Lemert'],
      correctOptionIndex: 0,
      explanation: 'Hirschi (1969) merumuskan 4 elemen ikatan sosial (Attachment, Commitment, Involvement, Belief).',
    ),
    QuestionItem(
      id: 'krim_016',
      questionText: 'Empat elemen ikatan sosial (Social Bonds) Hirschi yang mencegah kejahatan adalah:',
      options: ['Attachment, Commitment, Involvement, dan Belief', 'Id, Ego, Superego, Libido', 'Police, Court, Prison, Law', 'Family, School, Peer, Religion'],
      correctOptionIndex: 0,
      explanation: 'Ikatan Attachment, Komitmen, Keterlibatan, dan Kepercayaan menahan dorongan kejahatan.',
    ),
    QuestionItem(
      id: 'krim_017',
      questionText: 'Teori Labelling (Labeling Theory) yang menyatakan bahwa penyimpangan timbul akibat pemberian cap/label oleh masyarakat dipelopori oleh:',
      options: ['Howard S. Becker dan Edwin Lemert', 'Sutherland', 'Lombroso', 'Merton'],
      correctOptionIndex: 0,
      explanation: 'Howard Becker ("Outsiders") menegaskan "Deviance is not a quality of the act, but a consequence of the application of rules".',
    ),
    QuestionItem(
      id: 'krim_018',
      questionText: 'Edwin Lemert membedakan penyimpangan primer dan penyimpangan sekunder. Penyimpangan sekunder terjadi ketika:',
      options: ['Pelaku menerima cap/label penjahat dan mengadopsi gaya hidup penyimpangan sebagai bagian identitasnya', 'Penyimpangan pertama kali', 'Penyimpangan tak disengaja', 'Penyimpangan skala kecil'],
      correctOptionIndex: 0,
      explanation: 'Penyimpangan Sekunder adalah respon atas pemberian stigmata label masyarakat.',
    ),
    QuestionItem(
      id: 'krim_019',
      questionText: 'Teori Aktivitas Rutin (Routine Activity Theory) dikembangkan oleh Cohen dan Felson menyatakan kejahatan terjadi jika ada 3 elemen yaitu:',
      options: ['Motivated Offender (Pelaku Bermotif), Suitable Target (Target Sesuai), dan Absence of Capable Guardian (Ketiadaan Pengawas)', 'Uang, Senjata, Gelap', 'Niat, Rencana, Kesempatan', 'Pelaku, Korban, Polisi'],
      correctOptionIndex: 0,
      explanation: 'Cohen & Felson (1979) merumuskan segitiga kejahatan Aktivitas Rutin.',
    ),
    QuestionItem(
      id: 'krim_020',
      questionText: 'Teori Jendela Pecah (Broken Windows Theory) yang mengemukakan bahwa tanda-tanda kerusakan lingkungan kecil mengundang kejahatan lebih besar dikembangkan oleh:',
      options: ['James Q. Wilson dan George L. Kelling', 'Cohen dan Felson', 'Zimbardo', 'Shaw dan McKay'],
      correctOptionIndex: 0,
      explanation: 'Broken Windows Theory mengaitkan pembiaran kejahatan kecil dengan eskalasi kriminalitas.',
    ),
    QuestionItem(
      id: 'krim_021',
      questionText: 'Studi Teori Ekologi Manusia (Mazhab Chicago / Chicago School) yang memodelkan zona konsentris kriminalitas perkotaan dipelopori oleh:',
      options: ['Clifford Shaw dan Henry McKay', 'Sutherland', 'Becker', 'Lombroso'],
      correctOptionIndex: 0,
      explanation: 'Shaw & McKay merumuskan Teori Disorganisasi Sosial pada zona transisi kota Chicago.',
    ),
    QuestionItem(
      id: 'krim_022',
      questionText: 'Kondisi lingkungan perkotaan yang mengalami penurunan institusi keluarga dan komunitas sehingga gagal mengontrol kejahatan dinamakan:',
      options: ['Disorganisasi Sosial (Social Disorganization)', 'Anomie', 'Subkultur', 'Urbanisasi'],
      correctOptionIndex: 0,
      explanation: 'Social Disorganization terjadi di lingkungan kumuh berkepadatan tinggi.',
    ),
    QuestionItem(
      id: 'krim_023',
      questionText: 'Teori Subkultur Delinkuen yang mengemukakan geng remaja membentuk nilai pembalikan norma kelas menengah dikemukakan oleh:',
      options: ['Albert K. Cohen', 'Cloward dan Ohlin', 'Miller', 'Sykes dan Matza'],
      correctOptionIndex: 0,
      explanation: 'Albert Cohen merumuskan frustrasi status (status frustration) memicu subkultur geng remaja.',
    ),
    QuestionItem(
      id: 'krim_024',
      questionText: 'Teknik Netralisasi (Techniques of Neutralization) di mana pelaku rasional membenarkan kejahatannya dikemukakan oleh:',
      options: ['Gresham Sykes dan David Matza', 'Cohen dan Ohlin', 'Hirschi', 'Sutherland'],
      correctOptionIndex: 0,
      explanation: 'Sykes & Matza membagi 5 teknik netralisasi moral (Denial of Responsibility, Denial of Injury, dsb).',
    ),
    QuestionItem(
      id: 'krim_025',
      questionText: 'Salah satu teknik netralisasi Sykes & Matza di mana pelaku mengklaim "tidak ada korban yang dirugikan secara nyata" dinamakan:',
      options: ['Denial of Injury (Penolakan Kerugian)', 'Denial of Responsibility', 'Denial of Victim', 'Condemnation of Condemners'],
      correctOptionIndex: 0,
      explanation: 'Denial of Injury menganggap tindakannya sekadar kenakalan tanpa bahaya.',
    ),
    QuestionItem(
      id: 'krim_026',
      questionText: 'Teknik netralisasi di mana pelaku mengalihkan kesalahan dengan menyerang balik moralitas polisi atau hukum dinamakan:',
      options: ['Condemnation of the Condemners', 'Appeal to Higher Loyalties', 'Denial of Victim', 'Denial of Responsibility'],
      correctOptionIndex: 0,
      explanation: 'Condemnation of Condemners mengkritik penegak hukum yang dianggap korup.',
    ),
    QuestionItem(
      id: 'krim_027',
      questionText: 'Teknik netralisasi di mana pelaku berdalih kejahatan dilakukan demi kesetiaan geng atau kelompok intim dinamakan:',
      options: ['Appeal to Higher Loyalties (Pengabdian pada Kesetiaan Lebih Tinggi)', 'Denial of Victim', 'Denial of Injury', 'Denial of Responsibility'],
      correctOptionIndex: 0,
      explanation: 'Appeal to Higher Loyalties membenarkan pidana demi melindungi kawan.',
    ),
    QuestionItem(
      id: 'krim_028',
      questionText: 'Teori Kriminologi Kritis / Marxis memandang hukum pidana sebagai instrumen yang digunakan oleh:',
      options: ['Kelas penguasa pemilik modal (Borjuis) untuk mengontrol dan menindas kelas pekerja (Proletar)', 'Seluruh rakyat', 'Tuhan', 'Hakim independen'],
      correctOptionIndex: 0,
      explanation: 'Kriminologi Kritis (Willem Bonger / Ian Taylor) menganalisis kejahatan sebagai produk kapitalisme.',
    ),
    QuestionItem(
      id: 'krim_029',
      questionText: 'Studi kriminologi yang khusus memfokuskan penderitaan, peran, dan hak-hak korban kejahatan dinamakan:',
      options: ['Viktimologi (Victimology)', 'Penologi', 'Kriminalistik', 'Sosiologi Hukum'],
      correctOptionIndex: 0,
      explanation: 'Viktimologi dipelopori Benjamin Mendelsohn & Hans von Hentig.',
    ),
    QuestionItem(
      id: 'krim_030',
      questionText: 'Tindakan atau kecenderungan korban yang secara tidak disengaja memicu timbulnya kejahatan dinamakan:',
      options: ['Victim Precipitation (Presipitasi Korban)', 'Victim Blaming', 'Victimization', 'Repeat Victimization'],
      correctOptionIndex: 0,
      explanation: 'Victim Precipitation menguji peranan/perilaku awal korban yang mengundang kejahatan.',
    ),
    QuestionItem(
      id: 'krim_031',
      questionText: 'Sikap menyalahkan korban atas kejahatan yang dialaminya dinamakan:',
      options: ['Victim Blaming', 'Victim Precipitation', 'Secondary Victimization', 'Restorative'],
      correctOptionIndex: 0,
      explanation: 'Victim Blaming adalah bias memperlakukan korban seolah penyebab tindak pidana.',
    ),
    QuestionItem(
      id: 'krim_032',
      questionText: 'Trauma atau perlakuan buruk tambahan yang dialami korban saat menjalani proses peradilan pidana dinamakan:',
      options: ['Viktimisasi Sekunder (Secondary Victimization)', 'Viktimisasi Primer', 'Reviktimisasi', 'Disonansi'],
      correctOptionIndex: 0,
      explanation: 'Viktimisasi Sekunder terjadi akibat dampak sistem peradilan yang tidak sensitif korban.',
    ),
    QuestionItem(
      id: 'krim_033',
      questionText: 'Studi kriminologi yang mempelajari tentang sejarah, fungsi, dan efektivitas hukuman pidana serta pemasyarakatan dinamakan:',
      options: ['Penologi (Penology)', 'Viktimologi', 'Kriminalistik', 'Psikologi Kriminal'],
      correctOptionIndex: 0,
      explanation: 'Penologi menguji sistem pemindanaan dan lembaga pemasyarakatan.',
    ),
    QuestionItem(
      id: 'krim_034',
      questionText: 'Tujuan pemidanaan untuk mencegah masyarakat umum melakukan kejahatan dinamakan efek:',
      options: ['General Deterrence (Penangkalan Umum)', 'Specific Deterrence', 'Rehabilitasi', 'Retribusi'],
      correctOptionIndex: 0,
      explanation: 'General Deterrence menakut-nakuti publik agar tidak meniru kejahatan.',
    ),
    QuestionItem(
      id: 'krim_035',
      questionText: 'Tujuan pemidanaan untuk mencegah terpidana individual mengulangi kejahatan kembali dinamakan efek:',
      options: ['Specific / Individual Deterrence (Penangkalan Khusus)', 'General Deterrence', 'Incapacitation', 'Restitusi'],
      correctOptionIndex: 0,
      explanation: 'Specific Deterrence menindak pelanggar spesifik agar jera.',
    ),
    QuestionItem(
      id: 'krim_036',
      questionText: 'Tujuan pemidanaan dengan mengisolasi pelaku fisik dari masyarakat (misal penjara) agar tidak bisa berbuat jahat dinamakan:',
      options: ['Incapasitasi (Incapacitation / Pengasingan)', 'Rehabilitasi', 'Retribusi', 'Restitusi'],
      correctOptionIndex: 0,
      explanation: 'Incapacitation mencabut fisik kapasitas bergerak pelaku di tengah publik.',
    ),
    QuestionItem(
      id: 'krim_037',
      questionText: 'Tujuan pemidanaan yang berfokus memperbaiki moral dan kepribadian terpidana dinamakan:',
      options: ['Rehabilitasi (Rehabilitation)', 'Retribusi', 'Pembalasan', 'Incapasitasi'],
      correctOptionIndex: 0,
      explanation: 'Rehabilitasi membina terpidana agar siap kembali reintegrasi sosial.',
    ),
    QuestionItem(
      id: 'krim_038',
      questionText: 'Tujuan hukuman berbasis filosofi pembalasan setimpal ("Mata diganti mata") dinamakan keadilan:',
      options: ['Retributif (Retributive Justice)', 'Restoratif', 'Distributif', 'Rehabilitatif'],
      correctOptionIndex: 0,
      explanation: 'Keadilan Retributif mengutamakan pembalasan hukuman setimpal.',
    ),
    QuestionItem(
      id: 'krim_039',
      questionText: 'Kecenderungan mantan narapidana untuk mengulangi tindak kejahatan kembali setelah bebas dinamakan:',
      options: ['Residivisme (Recidivism)', 'Relaps', 'Rehabilitasi', 'Reintegrasi'],
      correctOptionIndex: 0,
      explanation: 'Residivisme mengukur tingkat kegagalan pembinaan pemasyarakatan.',
    ),
    QuestionItem(
      id: 'krim_040',
      questionText: 'Mantan terpidana yang berulang kali keluar-masuk penjara karena kejahatan dinamakan:',
      options: ['Residivis', 'Begal', 'Korban', 'Parolee'],
      correctOptionIndex: 0,
      explanation: 'Residivis adalah penjahat kambuhan.',
    ),
    QuestionItem(
      id: 'krim_041',
      questionText: 'Surat permohonan bebas bersyarat di bawah pengawasan petugas pembimbing kemasyarakatan dikenal sebagai sistem:',
      options: ['Parol (Parole)', 'Probasi (Probation)', 'Remisi', 'Asimilasi'],
      correctOptionIndex: 0,
      explanation: 'Parole adalah pembebasan bersyarat narasumber sebelum masa kurungan selesai.',
    ),
    QuestionItem(
      id: 'krim_042',
      questionText: 'Sanksi pidana pengawasan di luar penjara tanpa menjalani penahanan fisik dinamakan sistem:',
      options: ['Probasi (Probation / Hukuman Percobaan)', 'Parole', 'Incapasitasi', 'Isolasi'],
      correctOptionIndex: 0,
      explanation: 'Probation mengganti hukuman penjara dengan pengawasan hukum masyarakat.',
    ),
    QuestionItem(
      id: 'krim_043',
      questionText: 'Kejahatan terorganisasi yang beroperasi lintas batas wilayah negara (seperti perdagangan manusia/narkoba) dinamakan:',
      options: ['TOC (Transnational Organized Crime)', 'Street Crime', 'Cyber Crime', 'White-Collar Crime'],
      correctOptionIndex: 0,
      explanation: 'TOC melingkupi sindikat mafia internasional.',
    ),
    QuestionItem(
      id: 'krim_044',
      questionText: 'Tindak pidana perdagangan dan penyelundupan orang secara paksa dinamakan:',
      options: ['Human Trafficking (Tindak Pidana Perdagangan Orang / TPPO)', 'People Smuggling', 'Slavery', 'Kidnapping'],
      correctOptionIndex: 0,
      explanation: 'TPPO melibatkan eksploitasi, ancaman, dan perbudakan manusia.',
    ),
    QuestionItem(
      id: 'krim_045',
      questionText: 'Penyelundupan migran ilegal melintasi batas negara tanpa paksaan/eksploitasi dinamakan:',
      options: ['People Smuggling (Penyelundupan Manusia)', 'Human Trafficking', 'Kidnapping', 'Abduction'],
      correctOptionIndex: 0,
      explanation: 'People Smuggling dilakukan atas persetujuan migran sukarela melintasi batas secara ilegal.',
    ),
    QuestionItem(
      id: 'krim_046',
      questionText: 'Kejahatan penyusupan dan perusakan sistem jaringan komputer menggunakan malware/ransomware dinamakan:',
      options: ['Cybercrime (Kejahatan Siber)', 'Street Crime', 'White-Collar Crime', 'Property Crime'],
      correctOptionIndex: 0,
      explanation: 'Cybercrime mengeksploitasi celah teknologi komputer.',
    ),
    QuestionItem(
      id: 'krim_047',
      questionText: 'Metode penipuan siber mencuri identitas akun dengan menyamar sebagai lembaga resmi dinamakan:',
      options: ['Phishing', 'Spoofing', 'Skimming', 'Ransomware'],
      correctOptionIndex: 0,
      explanation: 'Phishing memancing korban menyerahkan kata sandi/kredensial.',
    ),
    QuestionItem(
      id: 'krim_048',
      questionText: 'Kejahatan pencurian data kartu ATM/Kredit menggunakan alat pemindai ilegal di mesin pembaca dinamakan:',
      options: ['Skimming', 'Phishing', 'Carding', 'Hacking'],
      correctOptionIndex: 0,
      explanation: 'Skimming menyalin pita magnetik kartu perbankan.',
    ),
    QuestionItem(
      id: 'krim_049',
      questionText: 'Perangkat lunak jahat yang mengunci/mengenkripsi data korban lalu meminta uang tebusan dinamakan:',
      options: ['Ransomware', 'Spyware', 'Adware', 'Trojan'],
      correctOptionIndex: 0,
      explanation: 'Ransomware menyandera file data komputer demi uang tebusan.',
    ),
    QuestionItem(
      id: 'krim_050',
      questionText: 'Jumlah kejahatan nyata yang tidak dilaporkan atau tidak terdaftar dalam statistik resmi polisi dinamakan:',
      options: ['Dark Figure of Crime (Kejahatan Tersembunyi)', 'Index Crime', 'Crime Rate', 'Clearance Rate'],
      correctOptionIndex: 0,
      explanation: 'Dark Figure of Crime adalah fenomena gunung es kejahatan yang tak terdata statistik.',
    ),
    QuestionItem(
      id: 'krim_051',
      questionText: 'Survei nasional yang menanyakan langsung kepada sampel warga apakah pernah menjadi korban kejahatan dinamakan:',
      options: ['NCVS (National Crime Victimization Survey)', 'UCR', 'Police Report', 'Census'],
      correctOptionIndex: 0,
      explanation: 'Survei Viktimisasi mengukur Dark Figure of Crime yang tidak dilaporkan ke polisi.',
    ),
    QuestionItem(
      id: 'krim_052',
      questionText: 'Laporan statistik tahunan kejahatan resmi buatan kepolisian (seperti UCR FBI) dinamakan:',
      options: ['Uniform Crime Reports (UCR)', 'NCVS', 'Self-Report Survey', 'Victim Survey'],
      correctOptionIndex: 0,
      explanation: 'UCR mencatat statistik resmi aduan kejahatan kepolisian.',
    ),
    QuestionItem(
      id: 'krim_053',
      questionText: 'Metode riset di mana responden (terutama remaja) diminta mengaku secara jujur tindak pelanggaran yang pernah dilakukan dinamakan:',
      options: ['Self-Report Survey (Survei Pengakuan Diri)', 'Victim Survey', 'UCR', 'Case Study'],
      correctOptionIndex: 0,
      explanation: 'Self-Report Survey mengungkap kenakalan remaja yang tersembunyi.',
    ),
    QuestionItem(
      id: 'krim_054',
      questionText: 'Angka statistik jumlah peristiwa kejahatan per 100.000 penduduk dalam kurun waktu tertentu dinamakan:',
      options: ['Crime Rate (Angka Kejahatan)', 'Crime Clock', 'Clearance Rate', 'Crime Severity Index'],
      correctOptionIndex: 0,
      explanation: 'Crime Rate = (Jumlah Kejahatan / Total Penduduk) x 100.000.',
    ),
    QuestionItem(
      id: 'krim_055',
      questionText: 'Persentase jumlah perkara kejahatan yang berhasil diselesaikan polisi hingga tuntas dinamakan:',
      options: ['Clearance Rate (Tingkat Penyelesaian Perkara)', 'Crime Rate', 'Crime Risk', 'Dark Figure'],
      correctOptionIndex: 0,
      explanation: 'Clearance Rate mengukur efektivitas kepolisian menyelesaikan kasus.',
    ),
    QuestionItem(
      id: 'krim_056',
      questionText: 'Representasi visual interval selisih waktu terjadinya satu tindak kejahatan dinamakan:',
      options: ['Crime Clock (Jam Kejahatan)', 'Crime Rate', 'Crime Index', 'Crime Map'],
      correctOptionIndex: 0,
      explanation: 'Crime Clock mengukur misal: "Satu pencurian terjadi setiap 5 menit".',
    ),
    QuestionItem(
      id: 'krim_057',
      questionText: 'Metode pemetaan berbasis GIS untuk mengidentifikasi titik-titik rawan konsentrasi lokasi kejahatan dinamakan:',
      options: ['Hot Spot Mapping (Pemetaan Titik Rawan Kejahatan)', 'Profiling', 'DNA Fingerprinting', 'Autopsi'],
      correctOptionIndex: 0,
      explanation: 'Hot Spot Mapping memetakan titik wilayah dengan rasio kejahatan tinggi.',
    ),
    QuestionItem(
      id: 'krim_058',
      questionText: 'Model pencegahan kejahatan dengan merancang tata ruang fisik lingkungan yang aman (CPTED) dirumuskan oleh:',
      options: ['C. Ray Jeffery dan Oscar Newman', 'Lombroso', 'Becker', 'Sutherland'],
      correctOptionIndex: 0,
      explanation: 'CPTED (Crime Prevention Through Environmental Design) memanfaatkan arsitektur lingkungan mencegah pidana.',
    ),
    QuestionItem(
      id: 'krim_059',
      questionText: 'Konsep "Defensible Space" dalam CPTED dikemukakan oleh arsitek:',
      options: ['Oscar Newman', 'Ray Jeffery', 'Jane Jacobs', 'Robert Moses'],
      correctOptionIndex: 0,
      explanation: 'Oscar Newman menekankan pengawasan alami (natural surveillance) kawasan perumahan.',
    ),
    QuestionItem(
      id: 'krim_060',
      questionText: 'Strategi pencegahan kejahatan situasional (Situational Crime Prevention) berfokus untuk:',
      options: ['Meningkatkan risiko dan kesulitan perbuatan jahat serta mengurangi imbalan kejahatan', 'Memenjarakan semua orang', 'Menghapus kemiskinan', 'Memberi konseling'],
      correctOptionIndex: 0,
      explanation: 'Ronald V. Clarke merumuskan Situational Crime Prevention (pemasangan CCTV, kunci ganda).',
    ),
    QuestionItem(
      id: 'krim_061',
      questionText: 'Praktik pencegahan kejahatan situasional dengan memperkuat hambatan fisik tempat target (seperti tralis pagar) dinamakan:',
      options: ['Target Hardening', 'Access Control', 'Surveillance', 'Deflect Offenders'],
      correctOptionIndex: 0,
      explanation: 'Target Hardening menyulitkan akses fisik ke target kejahatan.',
    ),
    QuestionItem(
      id: 'krim_062',
      questionText: 'Metode analisis kepolisian untuk merekonstruksi profil psikologis dan perilaku pelaku kejahatan berseri dinamakan:',
      options: ['Offender Profiling (Profiling Kriminal)', 'Autopsi', 'Ballistik', 'Grafologi'],
      correctOptionIndex: 0,
      explanation: 'Offender Profiling menganalisis modus operandi dan perilaku psikologis pelaku.',
    ),
    QuestionItem(
      id: 'krim_063',
      questionText: 'Pola perilaku atau cara khas yang dilakukan pelaku saat mengeksekusi tindak pidana dikenal dengan istilah:',
      options: ['Modus Operandi (MO)', 'Signature', 'Stigmata', 'Locus Delicti'],
      correctOptionIndex: 0,
      explanation: 'Modus Operandi adalah metode praktis eksekusi kejahatan.',
    ),
    QuestionItem(
      id: 'krim_064',
      questionText: 'Tindakan tambahan emosional khas pelaku di luar kebutuhan eksekusi pidana (seperti pola ukiran) dinamakan:',
      options: ['Signature (Ciri Khas Perilaku)', 'Modus Operandi', 'Motive', 'Stigma'],
      correctOptionIndex: 0,
      explanation: 'Signature memenuhi kebutuhan psikologis batin pelaku kejahatan berseri.',
    ),
    QuestionItem(
      id: 'krim_065',
      questionText: 'Pembunuhan yang melibatkan pembunuhan 3 orang atau lebih dalam kurun waktu terpisah dengan masa jeda (cooling-off period) dinamakan:',
      options: ['Serial Killer (Pembunuh Berseri)', 'Mass Murderer', 'Spree Killer', 'Genosida'],
      correctOptionIndex: 0,
      explanation: 'Serial Killer dipisahkan oleh rentang waktu jeda emosional (cooling-off period).',
    ),
    QuestionItem(
      id: 'krim_066',
      questionText: 'Pembunuhan banyak orang sekaligus di satu lokasi dalam satu peristiwa tunggal dinamakan:',
      options: ['Mass Murder (Pembunuhan Massal)', 'Serial Killer', 'Spree Killer', 'Assassination'],
      correctOptionIndex: 0,
      explanation: 'Mass Murder terjadi seketika di satu tempat (seperti penembakan massal).',
    ),
    QuestionItem(
      id: 'krim_067',
      questionText: 'Pembunuhan beberapa orang di lokasi berbeda dalam waktu singkat beruntun tanpa jeda dinamakan:',
      options: ['Spree Killer', 'Serial Killer', 'Mass Murder', 'Manslaughter'],
      correctOptionIndex: 0,
      explanation: 'Spree Killer bertindak dalam amukan pembunuhan beruntun kilat.',
    ),
    QuestionItem(
      id: 'krim_068',
      questionText: 'Disiplin ilmu sains ilmiah yang menerapkan metode sains untuk menganalisis bukti fisik kejahatan di laboratorium dinamakan:',
      options: ['Kriminalistik / Ilmu Forensik', 'Kriminologi', 'Penologi', 'Viktimologi'],
      correctOptionIndex: 0,
      explanation: 'Kriminalistik menerapkan ilmu sains (kimia, biologi, fisika) untuk pembuktian pidana.',
    ),
    QuestionItem(
      id: 'krim_069',
      questionText: 'Pemeriksaan medis ilmiah terhadap jenazah korban untuk menentukan sebab kematian dinamakan:',
      options: ['Autopsi (Bedah Mayat / Visum et Repertum)', 'Biopsi', 'Radiologi', 'Toksikologi'],
      correctOptionIndex: 0,
      explanation: 'Autopsi forensik menentukan waktu, mekanisme, dan penyebab pasti kematian.',
    ),
    QuestionItem(
      id: 'krim_070',
      questionText: 'Laporan medis resmi yang dibuat dokter forensik atas permintaan penyidik polisi untuk pembuktian pidana dinamakan:',
      options: ['Visum et Repertum (VeR)', 'BAP', 'BAP Saksi', 'Surat Kematian'],
      correctOptionIndex: 0,
      explanation: 'Visum et Repertum merupakan alat bukti surat sah di persidangan.',
    ),
    QuestionItem(
      id: 'krim_071',
      questionText: 'Cabang ilmu forensik yang khusus menganalisis racun dan zat kimia berbahaya dalam tubuh korban dinamakan:',
      options: ['Toksikologi Forensik', 'Balistik Forensik', 'Daktiloskopi', 'Odontologi'],
      correctOptionIndex: 0,
      explanation: 'Toksikologi mengidentifikasi kadar obat, alkohol, atau racun.',
    ),
    QuestionItem(
      id: 'krim_072',
      questionText: 'Cabang ilmu forensik yang menganalisis sidik jari manusia untuk identifikasi pelaku dinamakan:',
      options: ['Daktiloskopi (Dactyloscopy)', 'Odontologi', 'Antropologi', 'Grafologi'],
      correctOptionIndex: 0,
      explanation: 'Daktiloskopi mengidentifikasi alur unik garis pola sidik jari.',
    ),
    QuestionItem(
      id: 'krim_073',
      questionText: 'Cabang ilmu forensik yang memanfaatkan identifikasi struktur gigi korban dinamakan:',
      options: ['Odontologi Forensik', 'Daktiloskopi', 'Entomologi', 'Osteologi'],
      correctOptionIndex: 0,
      explanation: 'Odontologi mengidentifikasi korban bencana dari rekam medis gigi.',
    ),
    QuestionItem(
      id: 'krim_074',
      questionText: 'Cabang ilmu forensik yang mengamati tahap perkembangan serangga di mayat untuk menentukan perkiraan waktu kematian dinamakan:',
      options: ['Entomologi Forensik', 'Toksikologi', 'Botani', 'Palinologi'],
      correctOptionIndex: 0,
      explanation: 'Entomologi Forensik memanfaatkan larva serangga menentukan Post-Mortem Interval (PMI).',
    ),
    QuestionItem(
      id: 'krim_075',
      questionText: 'Cabang forensik yang menganalisis alur perkenaan peluru dan karakter senjata api dinamakan:',
      options: ['Balistik Forensik', 'Daktiloskopi', 'Toksikologi', 'Kinesiologi'],
      correctOptionIndex: 0,
      explanation: 'Balistik Forensik memeriksa alur goresan peluru dan proyektil.',
    ),
    QuestionItem(
      id: 'krim_076',
      questionText: 'Prinsip utama ilmu forensik "Every contact leaves a trace" (Setiap kontak meninggalkan jejak) dirumuskan oleh:',
      options: ['Edmond Locard (Locard\'s Exchange Principle)', 'Hans Gross', 'Alphonse Bertillon', 'Francis Galton'],
      correctOptionIndex: 0,
      explanation: 'Locard\'s Exchange Principle mendasari pencarian bukti mikro sampel fisik di TKP.',
    ),
    QuestionItem(
      id: 'krim_077',
      questionText: 'Pencatatan dan pengamanan rantai penguasaan bukti fisik dari TKP hingga persidangan dinamakan:',
      options: ['Chain of Custody (Rantai Penguasaan Alat Bukti)', 'Evidence Log', 'TKP Management', 'BAP'],
      correctOptionIndex: 0,
      explanation: 'Chain of Custody mencegah kontaminasi atau pemalsuan bukti di pengadilan.',
    ),
    QuestionItem(
      id: 'krim_078',
      questionText: 'Lokasi tempat terjadinya suatu tindak pidana kejahatan dilakukan dinamakan:',
      options: ['TKP (Tempat Kejadian Perkara / Crime Scene)', 'Locus Delicti', 'Police Line', 'Stasiun'],
      correctOptionIndex: 0,
      explanation: 'TKP menyimpan bukti fisik utama pembuktian perkara.',
    ),
    QuestionItem(
      id: 'krim_079',
      questionText: 'Proses mengamankan lokasi TKP menggunakan pita garis polisi dinamakan pembatasan:',
      options: ['Status Quo TKP (Police Line)', 'BAP', 'Autopsi', 'Rekonstruksi'],
      correctOptionIndex: 0,
      explanation: 'Police Line menjaga Status Quo TKP agar tidak terkontaminasi.',
    ),
    QuestionItem(
      id: 'krim_080',
      questionText: 'Peragaan kembali adegan peristiwa kejahatan oleh penyidik dan tersangka dinamakan:',
      options: ['Rekonstruksi', 'Autopsi', 'Olah TKP', 'Konfrontasi'],
      correctOptionIndex: 0,
      explanation: 'Rekonstruksi memperjelas persesuaian keterangan saksi dan BAP.',
    ),
    QuestionItem(
      id: 'krim_081',
      questionText: 'Pendekatan kepolisian yang berfokus membangun kemitraan erat dengan warga untuk mencegah kejahatan lokal dinamakan:',
      options: ['Community Policing (Polmas / Perpolisian Masyarakat)', 'Problem-Oriented Policing', 'Predictive Policing', 'Zero Tolerance'],
      correctOptionIndex: 0,
      explanation: 'Community Policing mengedepankan kemitraan preventif dengan masyarakat.',
    ),
    QuestionItem(
      id: 'krim_082',
      questionText: 'Strategi penegakan hukum ketat yang menindak tegas setiap pelanggaran hukum sekecil apapun dinamakan:',
      options: ['Zero Tolerance Policing', 'Community Policing', 'Soft Policing', 'Restorative'],
      correctOptionIndex: 0,
      explanation: 'Zero Tolerance menindak tegas seluruh pelanggaran tanpa ampun.',
    ),
    QuestionItem(
      id: 'krim_083',
      questionText: 'Kejahatan rasial yang didasari rasa benci atau prasangka terhadap ras, agama, atau orientasi korban dinamakan:',
      options: ['Hate Crime (Kejahatan Kebencian)', 'Street Crime', 'Passion Crime', 'Thug Crime'],
      correctOptionIndex: 0,
      explanation: 'Hate Crime menargetkan korban akibat prasangka diskriminasi identitas.',
    ),
    QuestionItem(
      id: 'krim_084',
      questionText: 'Kejahatan spontan yang dipicu oleh emosi kecemburuan atau amarah sesaat yang meluap dinamakan:',
      options: ['Crime of Passion', 'Premeditated Crime', 'State Crime', 'Corporate Crime'],
      correctOptionIndex: 0,
      explanation: 'Crime of Passion dilakukan tanpa perencanaan matang akibat ledakan emosi.',
    ),
    QuestionItem(
      id: 'krim_085',
      questionText: 'Kejahatan yang dilakukan oleh korporasi bisnis untuk meraup keuntungan perusahaan (seperti penipuan sistemik atau pembakaran hutan) dinamakan:',
      options: ['Corporate Crime (Kejahatan Korporasi)', 'White-Collar Crime', 'Occupational Crime', 'Organized Crime'],
      correctOptionIndex: 0,
      explanation: 'Corporate Crime menguntungkan entitas korporasi bisnis.',
    ),
    QuestionItem(
      id: 'krim_086',
      questionText: 'Kejahatan individu yang dilakukan oleh karyawan dengan memanfaatkan posisinya di tempat kerja dinamakan:',
      options: ['Occupational Crime (Kejahatan Jabatan)', 'Corporate Crime', 'Street Crime', 'Vandalism'],
      correctOptionIndex: 0,
      explanation: 'Occupational Crime dilakukan karyawan untuk keuntungan pribadi (seperti penggelapan kasir).',
    ),
    QuestionItem(
      id: 'krim_087',
      questionText: 'Kejahatan pelanggaran hukum berat yang dilakukan oleh aparatur negara atau pemerintah dinamakan:',
      options: ['State Crime (Kejahatan Negara)', 'Corporate Crime', 'Political Crime', 'War Crime'],
      correctOptionIndex: 0,
      explanation: 'State Crime mencakup penyiksaan, korupsi sistemik negara, dan pembantaian politik.',
    ),
    QuestionItem(
      id: 'krim_088',
      questionText: 'Istilah "Green Criminology" (Kriminologi Hijau) memfokuskan studi pada:',
      options: ['Kejahatan dan perusakan terhadap lingkungan hidup, alam, dan satwa liar', 'Kejahatan uang hijau', 'Taman kota', 'Pertanian'],
      correctOptionIndex: 0,
      explanation: 'Green Criminology menguji deforestasi, pencemaran limbah, dan perburuan liar.',
    ),
    QuestionItem(
      id: 'krim_089',
      questionText: 'Konsep penyingkiran tindak perbuatan tertentu dari ranah hukum pidana dinamakan:',
      options: ['Dekriminalisasi (Decriminalization)', 'Kriminalisasi', 'Depenalisasi', 'Legalitas'],
      correctOptionIndex: 0,
      explanation: 'Dekriminalisasi merubah perbuatan pidana menjadi bukan pidana (seperti pengguna narkoba menjadi pasien rehab).',
    ),
    QuestionItem(
      id: 'krim_090',
      questionText: 'Proses menetapkan suatu perbuatan baru yang semula bukan pidana menjadi tindak pidana dinamakan:',
      options: ['Kriminalisasi (Criminalization)', 'Dekriminalisasi', 'Depenalisasi', 'Penal'],
      correctOptionIndex: 0,
      explanation: 'Kriminalisasi menerbitkan aturan pidana baru.',
    ),
    QuestionItem(
      id: 'krim_091',
      questionText: 'Pengalihan penyelesaian perkara anak dari proses peradilan pidana ke luar jalur peradilan formal dinamakan:',
      options: ['Diversi (Diversion)', 'Restorasi', 'Probasi', 'Asimilasi'],
      correctOptionIndex: 0,
      explanation: 'Diversi diwajibkan dalam Sistem Peradilan Pidana Anak (SPPA) untuk melindungi anak dari trauma penjara.',
    ),
    QuestionItem(
      id: 'krim_092',
      questionText: 'Undang-Undang Sistem Peradilan Pidana Anak di Indonesia diatur dalam UU Nomor:',
      options: ['UU No. 11 Tahun 2012', 'UU No. 23 Tahun 2002', 'UU No. 35 Tahun 2014', 'UU No. 3 Tahun 1997'],
      correctOptionIndex: 0,
      explanation: 'UU No. 11/2012 tentang SPPA mengedepankan pendekatan Restorative Justice dan Diversi anak.',
    ),
    QuestionItem(
      id: 'krim_093',
      questionText: 'Anak yang berhadapan dengan hukum (ABH) menurut UU SPPA adalah anak yang berusia:',
      options: ['Telah mencapai 12 tahun tetapi belum berusia 18 tahun', 'Di bawah 10 tahun', '15-21 tahun', 'Bebas'],
      correctOptionIndex: 0,
      explanation: 'Batas usia pertanggungjawaban pidana anak adalah 12 hingga 18 tahun.',
    ),
    QuestionItem(
      id: 'krim_094',
      questionText: 'Lembaga khusus penempatan sementara bagi anak tersangka pidana selama proses peradilan dinamakan:',
      options: ['LPAS (Lembaga Penempatan Anak Sementara)', 'LPKA', 'LPSK', 'LBH'],
      correctOptionIndex: 0,
      explanation: 'LPAS menampung anak selama penahanan persidangan.',
    ),
    QuestionItem(
      id: 'krim_095',
      questionText: 'Lembaga Pemasyarakatan Khusus Anak untuk tempat pembinaan terpidana anak dinamakan:',
      options: ['LPKA (Lembaga Pemasyarakatan Khusus Anak)', 'LPAS', 'Rutan', 'LPS'],
      correctOptionIndex: 0,
      explanation: 'LPKA menggantikan istilah Penjara Anak dengan prinsip pendidikan.',
    ),
    QuestionItem(
      id: 'krim_096',
      questionText: 'Petugas fungsional yang membuat Laporan Penelitian Kemasyarakatan (Litmas) untuk perkara anak adalah:',
      options: ['Pembimbing Kemasyarakatan (PK Bapas)', 'Penyidik Polisi', 'Jaksa Anak', 'Hakim'],
      correctOptionIndex: 0,
      explanation: 'PK Bapas menyusun Litmas rekomendasi diversi/vonis anak.',
    ),
    QuestionItem(
      id: 'krim_097',
      questionText: 'Prinsip utama penanganan kasus kenakalan anak adalah mengutamakan kepentingan terbaik bagi anak dinamakan:',
      options: ['Best Interests of the Child', 'Deterrence', 'Retribution', 'Strict Liability'],
      correctOptionIndex: 0,
      explanation: 'Prinsip Internasional Konvensi Hak Anak mengutamakan kepentingan terbaik anak.',
    ),
    QuestionItem(
      id: 'krim_098',
      questionText: 'Kepanikan moral publik yang dibesar-besarkan media atas kelompok sosial tertentu dinamakan:',
      options: ['Moral Panic (Kepanikan Moral)', 'Social Fear', 'Public Rage', 'Mass Hysteria'],
      correctOptionIndex: 0,
      explanation: 'Stanley Cohen ("Folk Devils and Moral Panics") merumuskan fenomena Kepanikan Moral.',
    ),
    QuestionItem(
      id: 'krim_099',
      questionText: 'Kelompok sosial yang dijadikan kambing hitam dan sasaran kepanikan moral publik dinamakan Stanley Cohen sebagai:',
      options: ['Folk Devils', 'Outsiders', 'Scapegoat', 'Rebels'],
      correctOptionIndex: 0,
      explanation: 'Folk Devils adalah stereotip musuh moral masyarakat.',
    ),
    QuestionItem(
      id: 'krim_100',
      questionText: 'Sistem Peradilan Pidana (Criminal Justice System) terdiri dari empat komponen utama yaitu:',
      options: ['Kepolisian, Kejaksaan, Pengadilan, dan Lembaga Pemasyarakatan', 'Polisi, Tentara, Satpol PP, DPR', 'KPK, BPK, MA, MK', 'Pengacara, Saksi, Korban, Hakim'],
      correctOptionIndex: 0,
      explanation: 'Komponen CJS terpadu: Police, Prosecution, Courts, & Corrections.',
    ),
  ];
}
