import '../tes_seleksi_model.dart';

List<QuestionItem> getManajemenPerhotelanQuestions() {
  return const [
    QuestionItem(
      id: 'htl_001',
      questionText: 'Departemen garda depan hotel yang bertanggung jawab atas registrasi tamu, pemesanan kamar, dan layanan informasi adalah:',
      options: ['Front Office (FO)', 'Housekeeping', 'Food & Beverage', 'Engineering'],
      correctOptionIndex: 0,
      explanation: 'Front Office adalah pintu utama pendaftaran, check-in/out, dan pusat komunikasi tamu hotel.',
    ),
    QuestionItem(
      id: 'htl_002',
      questionText: 'Departemen hotel yang bertanggung jawab atas kebersihan, kerapihan, dan estetika kamar menginap serta area publik adalah:',
      options: ['Housekeeping', 'Front Office', 'Accounting', 'Security'],
      correctOptionIndex: 0,
      explanation: 'Housekeeping merawat kebersihan kamar (guest room) dan fasilitas umum hotel.',
    ),
    QuestionItem(
      id: 'htl_003',
      questionText: 'Departemen hotel yang memproduksi dan menyajikan makanan serta minuman bagi tamu dinamakan:',
      options: ['Food & Beverage (F&B) Department', 'Front Office', 'Sales & Marketing', 'Human Resources'],
      correctOptionIndex: 0,
      explanation: 'F&B Department mengelola restoran, dapur, banquet, dan pemesanan makanan kamar.',
    ),
    QuestionItem(
      id: 'htl_004',
      questionText: 'Petugas Front Office yang bertugas mengangkut barang bawaan tamu dari area kedatangan menuju kamar dinamakan:',
      options: ['Bellboy / Porter', 'Concierge', 'Receptionist', 'Doorman'],
      correctOptionIndex: 0,
      explanation: 'Bellboy/Porter mengurus penanganan barang bawaan (luggage) tamu.',
    ),
    QuestionItem(
      id: 'htl_005',
      questionText: 'Petugas garda depan khusus yang membantu tamu dalam layanan pemesanan tiket, paket tur, restoran, dan bantuan kustom dinamakan:',
      options: ['Concierge', 'Bellboy', 'Cashier', 'Night Auditor'],
      correctOptionIndex: 0,
      explanation: 'Concierge menangani permintaan informasi khusus dan reservasi luar bagi tamu.',
    ),
    QuestionItem(
      id: 'htl_006',
      questionText: 'Formulir pendaftaran yang wajib diisi dan ditandatangani tamu saat proses registrasi check-in dinamakan:',
      options: ['Registration Card (Reg Card)', 'Guest Folio', 'Voucher', 'Receipt'],
      correctOptionIndex: 0,
      explanation: 'Registration Card memuat data identitas dan konfirmasi syarat menginap tamu.',
    ),
    QuestionItem(
      id: 'htl_007',
      questionText: 'Harga sewa resmi kamar hotel per malam sebelum dikenakan diskon atau harga promosi dinamakan:',
      options: ['Rack Rate', 'Corporate Rate', 'Group Rate', 'Nett Rate'],
      correctOptionIndex: 0,
      explanation: 'Rack Rate adalah tarif publik standar tertinggi yang ditetapkan hotel.',
    ),
    QuestionItem(
      id: 'htl_008',
      questionText: 'Lembar rekapan transaksi yang memuat seluruh rincian tagihan sewa kamar dan pengeluaran tamu selama menginap dinamakan:',
      options: ['Guest Folio', 'Registration Card', 'Receipt', 'Purchase Order'],
      correctOptionIndex: 0,
      explanation: 'Guest Folio memantau saldo akumulasi transaksi pembayaran tamu.',
    ),
    QuestionItem(
      id: 'htl_009',
      questionText: 'Teknik penjualan Front Office dengan menawarkan kategori kamar yang lebih tinggi atau fasilitas ekstra berbayar dinamakan:',
      options: ['Upselling', 'Cross-selling', 'Discounting', 'Overbooking'],
      correctOptionIndex: 0,
      explanation: 'Upselling bertujuan meningkatkan rata-rata tarif kamar dengan menawarkan tipe kamar lebih mewah.',
    ),
    QuestionItem(
      id: 'htl_010',
      questionText: 'Status kamar hotel yang menandakan bahwa kamar sedang terisi oleh tamu yang menginap dinamakan:',
      options: ['Occupied (OCC)', 'Vacant Clean', 'Vacant Dirty', 'Out of Order'],
      correctOptionIndex: 0,
      explanation: 'Occupied berarti kamar sedang dihuni tamu secara sah.',
    ),
    QuestionItem(
      id: 'htl_011',
      questionText: 'Status kamar hotel yang kosong dan sudah dibersihkan serta siap disewakan kepada tamu baru dinamakan:',
      options: ['Vacant Clean (VC / VR)', 'Vacant Dirty', 'Occupied Dirty', 'Due Out'],
      correctOptionIndex: 0,
      explanation: 'Vacant Clean (atau Vacant Ready) menandakan kamar bersih siap dijual.',
    ),
    QuestionItem(
      id: 'htl_012',
      questionText: 'Status kamar hotel yang kosong namun dalam keadaan kotor setelah ditinggal tamu check-out dinamakan:',
      options: ['Vacant Dirty (VD)', 'Vacant Clean', 'Occupied', 'Out of Service'],
      correctOptionIndex: 0,
      explanation: 'Vacant Dirty memerlukan pembersihan oleh room attendant sebelum dijual kembali.',
    ),
    QuestionItem(
      id: 'htl_013',
      questionText: 'Status kamar hotel yang sedang rusak atau menjalani perbaikan sehingga tidak dapat disewakan dinamakan:',
      options: ['Out of Order (OOO)', 'Vacant Dirty', 'Occupied', 'Sleepout'],
      correctOptionIndex: 0,
      explanation: 'Out of Order menandakan kamar tidak tersedia karena kerusakan teknis.',
    ),
    QuestionItem(
      id: 'htl_014',
      questionText: 'Layanan penataan tempat tidur dan perapihan kamar hotel pada sore/malam hari menjelang waktu tidur tamu dinamakan:',
      options: ['Turndown Service', 'Make-up Room', 'Express Cleaning', 'Check-out Service'],
      correctOptionIndex: 0,
      explanation: 'Turndown Service menyiapkan kenyamanan tempat tidur di sore/malam hari.',
    ),
    QuestionItem(
      id: 'htl_015',
      questionText: 'Staf Housekeeping yang bertugas langsung merapikan dan membersihkan kamar tamu setiap harinya dinamakan:',
      options: ['Room Attendant / Housekeeper', 'Valet Girl', 'Butler', 'Steward'],
      correctOptionIndex: 0,
      explanation: 'Room Attendant bertanggung jawab atas kebersihan fisik kamar tamu.',
    ),
    QuestionItem(
      id: 'htl_016',
      questionText: 'Perlengkapan mandi dan kenyamanan pribadi gratis yang disediakan hotel di kamar mandi dinamakan:',
      options: ['Guest Amenities', 'Linen Supply', 'Stationery Kit', 'Mini Bar'],
      correctOptionIndex: 0,
      explanation: 'Amenities mencakup sabun, sikat gigi, sikat rambut, dan sampo gratis.',
    ),
    QuestionItem(
      id: 'htl_017',
      questionText: 'Kunci khusus yang dapat membuka seluruh pintu kamar di area blok hotel yang dipegang eksekutif Housekeeping dinamakan:',
      options: ['Master Key', 'Guest Key', 'Emergency Key', 'Passkey'],
      correctOptionIndex: 0,
      explanation: 'Master Key dapat mengakses seluruh pintu kamar kunci elektronik hotel.',
    ),
    QuestionItem(
      id: 'htl_018',
      questionText: 'Seksi di Housekeeping yang mengelola penyimpanan barang-barang tamu yang tertinggal di area hotel dinamakan:',
      options: ['Lost and Found', 'Linen Room', 'Uniform Room', 'Store Room'],
      correctOptionIndex: 0,
      explanation: 'Lost and Found mendata dan mengamankan barang tertinggal untuk dikembalikan.',
    ),
    QuestionItem(
      id: 'htl_019',
      questionText: 'Layanan pencucian, penyetrikaan, dan pembersihan kering pakaian milik tamu yang dikelola hotel dinamakan:',
      options: ['Laundry & Dry Cleaning', 'Housekeeping Service', 'Valet Parking', 'Concierge Service'],
      correctOptionIndex: 0,
      explanation: 'Laundry mengurus pencucian pakaian tamu dan linen milik hotel.',
    ),
    QuestionItem(
      id: 'htl_020',
      questionText: 'Gaya pelayanan makanan restoran di mana makanan diatur langsung di piring di dapur (plated service) sebelum disajikan dinamakan:',
      options: ['American Service', 'Russian Service', 'French Service', 'English Service'],
      correctOptionIndex: 0,
      explanation: 'American Service adalah pelayanan praktis cepat di mana hidangan sudah ditata di piring dapur.',
    ),
    QuestionItem(
      id: 'htl_021',
      questionText: 'Gaya pelayanan makanan mewah di mana pramusaji memindahkan makanan dari piring perak ke piring tamu di meja dinamakan:',
      options: ['Russian Service', 'American Service', 'Buffet Service', 'Cafeteria Service'],
      correctOptionIndex: 0,
      explanation: 'Russian Service menggunakan platter perak yang disajikan dari sisi kiri tamu.',
    ),
    QuestionItem(
      id: 'htl_022',
      questionText: 'Sistem pelayanan di mana makanan ditata di meja panjang dan tamu mengambil makanan sendiri secara bebas dinamakan:',
      options: ['Buffet Service (Prasmanan)', 'A la carte Service', 'Room Service', 'Family Service'],
      correctOptionIndex: 0,
      explanation: 'Buffet Service membebaskan tamu memilih hidangan dari konter prasmanan.',
    ),
    QuestionItem(
      id: 'htl_023',
      questionText: 'Layanan pemesanan dan pengantaran makanan/minuman dari restoran ke dalam kamar tempat menginap tamu dinamakan:',
      options: ['Room Service (In-Room Dining)', 'Take Away', 'Catering', 'Banquet Service'],
      correctOptionIndex: 0,
      explanation: 'Room Service menyajikan makanan langsung di kamar privat tamu.',
    ),
    QuestionItem(
      id: 'htl_024',
      questionText: 'Petugas pria yang bertugas melayani pemesanan makanan dan minuman di restoran hotel dinamakan:',
      options: ['Waiter', 'Waitress', 'Bartender', 'Sommelier'],
      correctOptionIndex: 0,
      explanation: 'Waiter adalah pramusaji pria di restoran/F&B Outlet.',
    ),
    QuestionItem(
      id: 'htl_025',
      questionText: 'Petugas wanita yang bertugas menyajikan makanan dan minuman di restoran hotel dinamakan:',
      options: ['Waitress', 'Waiter', 'Hostess', 'Cashier'],
      correctOptionIndex: 0,
      explanation: 'Waitress adalah pramusaji wanita di restoran.',
    ),
    QuestionItem(
      id: 'htl_026',
      questionText: 'Manajer puncak tertinggi di dapur hotel yang bertanggung jawab atas kreasi menu dan standar masakan dinamakan:',
      options: ['Executive Chef', 'Sous Chef', 'Chef de Partie', 'Commis'],
      correctOptionIndex: 0,
      explanation: 'Executive Chef memimpin keseluruhan operasional dapur hotel.',
    ),
    QuestionItem(
      id: 'htl_027',
      questionText: 'Asisten kepala dapur yang langsung bertindak menggantikan Executive Chef jika berhalangan dinamakan:',
      options: ['Sous Chef', 'Chef de Partie', 'Pastry Chef', 'Pastry Man'],
      correctOptionIndex: 0,
      explanation: 'Sous Chef adalah orang kedua di komando hirarki dapur hotel.',
    ),
    QuestionItem(
      id: 'htl_028',
      questionText: 'Chef yang memimpin seksi atau stasiun masak khusus di dapur (seperti seksi saus atau memanggang) dinamakan:',
      options: ['Chef de Partie (CDP)', 'Executive Chef', 'Commis I', 'Apprentice'],
      correctOptionIndex: 0,
      explanation: 'Chef de Partie mengawasi stasiun dapur tertentu (station chef).',
    ),
    QuestionItem(
      id: 'fsh_029',
      questionText: 'Seksi dapur hotel yang khusus mengolah dan memproduksi roti, kue, dan hidangan penutup (dessert) dinamakan:',
      options: ['Pastry & Bakery', 'Garde Manger', 'Butcher', 'Saucer'],
      correctOptionIndex: 0,
      explanation: 'Pastry & Bakery memproduksi roti, pastry, cake, dan dessert.',
    ),
    QuestionItem(
      id: 'htl_030',
      questionText: 'Tahap persiapan awal di dapur (memotong, menimbang, dan meracik bahan) sebelum proses memasak dimulai dinamakan:',
      options: ['Mise en Place', 'Plating', 'Garnishing', 'Cooking Process'],
      correctOptionIndex: 0,
      explanation: 'Mise en Place (Prancis: menempatkan pada tempatnya) adalah tahap persiapan bahan sebelum memasak.',
    ),
    QuestionItem(
      id: 'htl_031',
      questionText: 'Sistem jaminan keamanan pangan internasional untuk mengidentifikasi dan mengendalikan bahaya cemaran makanan dinamakan:',
      options: ['HACCP', 'ISO 9001', 'SOP', 'GMP'],
      correctOptionIndex: 0,
      explanation: 'HACCP (Hazard Analysis Critical Control Point) mengawasi bahaya kontaminasi makanan.',
    ),
    QuestionItem(
      id: 'htl_032',
      questionText: 'Zona suhu berbahaya antara 5°C hingga 60°C di mana mikroorganisme bakteri makanan berkembang biak sangat cepat dinamakan:',
      options: ['Temperature Danger Zone', 'Freezing Zone', 'Boiling Zone', 'Safety Zone'],
      correctOptionIndex: 0,
      explanation: 'Suhu 5°C - 60°C adalah zona bahaya pembiakan cepat bakteri makanan.',
    ),
    QuestionItem(
      id: 'htl_033',
      questionText: 'Perpindahan kuman/bakteri berbahaya dari bahan makanan mentah ke makanan matang yang siap dikonsumsi dinamakan:',
      options: ['Cross-Contamination (Contaminasi Silang)', 'Fermentasi', 'Pasteurisasi', 'Oksidasi'],
      correctOptionIndex: 0,
      explanation: 'Cross-Contamination terjadi saat alat mentah dipakai untuk makanan matang tanpa dicuci.',
    ),
    QuestionItem(
      id: 'htl_034',
      questionText: 'Sistem komputerisasi kasir terintegrasi untuk mencatat pesanan transaksi F&B dan penagihan ke sistem hotel dinamakan:',
      options: ['POS (Point of Sale System)', 'PMS', 'GDS', 'CRS'],
      correctOptionIndex: 0,
      explanation: 'POS System mencatat penjualan F&B yang terhubung ke tagihan kamar tamu.',
    ),
    QuestionItem(
      id: 'htl_035',
      questionText: 'Rasio persentase jumlah kamar yang berhasil disewakan dibanding total kamar siap jual di hotel dinamakan:',
      options: ['Occupancy Rate (Tingkat Hunian)', 'RevPAR', 'ADR', 'Yield Rate'],
      correctOptionIndex: 0,
      explanation: 'Occupancy Rate mengukur sejauh mana tingkat keterisian kamar hotel.',
    ),
    QuestionItem(
      id: 'htl_036',
      questionText: 'Rata-rata pendapatan bersih sewa kamar yang diperoleh dari setiap kamar terisi dinamakan:',
      options: ['ADR (Average Daily Rate)', 'RevPAR', 'Occupancy Rate', 'Rack Rate'],
      correctOptionIndex: 0,
      explanation: 'ADR dihitung dengan membagi total pendapatan kamar dengan jumlah kamar yang terjual.',
    ),
    QuestionItem(
      id: 'htl_037',
      questionText: 'Metrik keuangan utama hotel yang menghitung rata-rata pendapatan sewa kamar dibagi seluruh total kamar yang tersedia dinamakan:',
      options: ['RevPAR (Revenue Per Available Room)', 'ADR', 'GOP', 'EBITDA'],
      correctOptionIndex: 0,
      explanation: 'RevPAR mengukur performa pendapatan total persediaan kamar hotel.',
    ),
    QuestionItem(
      id: 'htl_038',
      questionText: 'Strategi harga kamar yang berubah-ubah secara dinamis menyesuaikan tingkat fluktuasi permintaan pasar dinamakan:',
      options: ['Yield Management / Revenue Management', 'Flat Rate Strategy', 'Cost-Plus Pricing', 'Fixed Pricing'],
      correctOptionIndex: 0,
      explanation: 'Yield Management memaksimalkan pendapatan dengan mengubah tarif sesuai tren permintaan.',
    ),
    QuestionItem(
      id: 'htl_039',
      questionText: 'Pemesanan kamar hotel yang dilakukan melalui platform situs/aplikasi perantara perjalanan online dinamakan pemesanan via:',
      options: ['OTA (Online Travel Agent)', 'Direct Booking', 'Travel Agent Offline', 'Walk-in'],
      correctOptionIndex: 0,
      explanation: 'OTA (seperti Agoda, Traveloka, Booking.com) adalah agen perjalanan digital.',
    ),
    QuestionItem(
      id: 'htl_040',
      questionText: 'Jenis pemesanan kamar hotel yang telah dijamin dengan pembayaran deposit sehingga kamar tetap ditahan hingga check-in dinamakan:',
      options: ['Guaranteed Reservation', 'Non-guaranteed Reservation', 'Waiting List', 'Tentative Booking'],
      correctOptionIndex: 0,
      explanation: 'Guaranteed Reservation menjamin ketersediaan kamar karena telah dibayar deposit.',
    ),
    QuestionItem(
      id: 'htl_041',
      questionText: 'Kondisi di mana tamu yang telah melakukan pemesanan kamar ternyata tidak datang menginap tanpa adanya konfirmasi pembatalan dinamakan:',
      options: ['No-Show', 'Cancellation', 'Skipper', 'Walk-in'],
      correctOptionIndex: 0,
      explanation: 'No-Show terjadi saat pemesan tidak hadir tanpa kabar pembatalan.',
    ),
    QuestionItem(
      id: 'htl_042',
      questionText: 'Kebijakan hotel menjual jumlah kamar melampaui fisik kapasitas kamar yang ada guna mengantisipasi pembatalan dinamakan:',
      options: ['Overbooking', 'Underbooking', 'Upgrading', 'Skipping'],
      correctOptionIndex: 0,
      explanation: 'Overbooking adalah strategi memperhitungkan persentase pembatalan/no-show.',
    ),
    QuestionItem(
      id: 'htl_043',
      questionText: 'Tindakan memindahkan tamu ke hotel sekelas lain akibat kamar di hotel mengalami kondisi overbooking dinamakan:',
      options: ['Walking Guest / Walked Guest', 'Upgrading', 'Skipping', 'Relocation Service'],
      correctOptionIndex: 0,
      explanation: 'Walking Guest memindahkan tamu dengan kompensasi dan pengantaran ke hotel sekelas.',
    ),
    QuestionItem(
      id: 'htl_044',
      questionText: 'Tamu yang menginap melebihi batas waktu resmi check-out tanpa persetujuan pihak hotel dinamakan:',
      options: ['Overstay / Late Check-Out', 'Early Check-in', 'No-Show', 'Skipper'],
      correctOptionIndex: 0,
      explanation: 'Overstay terjadi saat tamu terlambat mengosongkan kamar melewati batas waktu.',
    ),
    QuestionItem(
      id: 'htl_045',
      questionText: 'Tamu nakal yang kabur dari hotel tanpa melunasi seluruh tagihan biaya sewa dinamakan:',
      options: ['Skipper', 'No-show', 'Walking Guest', 'Sleeper'],
      correctOptionIndex: 0,
      explanation: 'Skipper adalah sebutan bagi tamu yang kabur meninggalkan hotel tanpa membayar.',
    ),
    QuestionItem(
      id: 'htl_046',
      questionText: 'Tamu yang datang langsung ke meja resepsionis untuk sewa kamar tanpa reservasi terlebih dahulu dinamakan:',
      options: ['Walk-In Guest', 'VIP Guest', 'Corporate Guest', 'Regular Guest'],
      correctOptionIndex: 0,
      explanation: 'Walk-in guest memesan kamar secara spontan di tempat.',
    ),
    QuestionItem(
      id: 'htl_047',
      questionText: 'Sektor industri pariwisata yang menangani konvensi, pameran, dan rapat acara bisnis dikenal dengan akronim:',
      options: ['MICE (Meeting, Incentive, Convention, Exhibition)', 'UNESCO', 'UNWTO', 'PHRI'],
      correctOptionIndex: 0,
      explanation: 'MICE mengelola rapat perusahaan, perjalanan insentif, konferensi, dan pameran.',
    ),
    QuestionItem(
      id: 'htl_048',
      questionText: 'Dokumen kerja lembar instruksi resmi yang memuat seluruh rincian teknis acara pertemuan/banquet di hotel dinamakan:',
      options: ['BEO (Banquet Event Order)', 'Guest Folio', 'Invoice', 'Purchase Order'],
      correctOptionIndex: 0,
      explanation: 'BEO memuat detail ruang, susunan kursi, menu F&B, dan peralatan audiovisual acara.',
    ),
    QuestionItem(
      id: 'htl_049',
      questionText: 'Manajer eksekutif tertinggi yang memimpin dan bertanggung jawab penuh atas seluruh manajemen hotel dinamakan:',
      options: ['General Manager (GM)', 'Resident Manager', 'Duty Manager', 'Operational Manager'],
      correctOptionIndex: 0,
      explanation: 'General Manager memegang puncak pucuk kepemimpinan operasional hotel.',
    ),
    QuestionItem(
      id: 'htl_050',
      questionText: 'Hotel yang dimiliki dan dikelola secara mandiri oleh pemiliknya tanpa terikat grup rantai jaringan internasional dinamakan:',
      options: ['Independent Hotel', 'Chain Hotel', 'Franchise Hotel', 'Affiliate Hotel'],
      correctOptionIndex: 0,
      explanation: 'Independent Hotel beroperasi sendiri secara mandiri.',
    ),
    QuestionItem(
      id: 'htl_051',
      questionText: 'Hotel yang beroperasi di bawah bendera merek manajemen rantai internasional (seperti Marriott atau Accor) dinamakan:',
      options: ['Chain Hotel', 'Independent Hotel', 'Boutique Hotel', 'B&B Hotel'],
      correctOptionIndex: 0,
      explanation: 'Chain Hotel terhubung dalam jaringan merek dan standar internasional.',
    ),
    QuestionItem(
      id: 'htl_052',
      questionText: 'Pedoman tertulis standar pelaksanaan kerja operasional yang wajib dipatuhi staf hotel dinamakan:',
      options: ['SOP (Standard Operating Procedure)', 'BEO', 'Job Description', 'Work Instruction'],
      correctOptionIndex: 0,
      explanation: 'SOP menjaga konsistensi kualitas layanan hotel.',
    ),
    QuestionItem(
      id: 'htl_053',
      questionText: 'Brankas besi penyimpanan barang-barang berharga yang disediakan di dalam kamar menginap tamu dinamakan:',
      options: ['In-Room Safe Deposit Box', 'Master Box', 'Locker', 'Luggage Box'],
      correctOptionIndex: 0,
      explanation: 'Safe Deposit Box mengamankan paspor, uang, dan barang berharga milik tamu.',
    ),
    QuestionItem(
      id: 'htl_054',
      questionText: 'Kartu kunci elektronik berteknologi chip/sensor yang digunakan untuk membuka pintu kamar hotel dinamakan:',
      options: ['Keycard / RFID Key', 'Barcode Card', 'Magnetic Ticket', 'Smart Card'],
      correctOptionIndex: 0,
      explanation: 'Keycard memprogram akses pintu kamar sesuai masa menginap tamu.',
    ),
    QuestionItem(
      id: 'htl_055',
      questionText: 'Departemen hotel yang bertanggung jawab atas perawatan mesin, listrik, AC, pendingin, dan fisik fasilitas bangunan dinamakan:',
      options: ['Engineering Department', 'Housekeeping', 'Security', 'Front Office'],
      correctOptionIndex: 0,
      explanation: 'Engineering memelihara kelancaran sarana teknis dan utilitas hotel.',
    ),
    QuestionItem(
      id: 'htl_056',
      questionText: 'Departemen yang bertugas mengawasi ketertiban, keamanan fisik, dan keselamatan seluruh penghuni hotel selama 24 jam dinamakan:',
      options: ['Security Department', 'Human Resources', 'Front Office', 'Concierge'],
      correctOptionIndex: 0,
      explanation: 'Security menjamin keamanan fisik tamu, staf, dan properti hotel.',
    ),
    QuestionItem(
      id: 'htl_057',
      questionText: 'Perangkat pemadam kebakaran otomatis yang terpasang di langit-langit kamar dan koridor hotel dinamakan:',
      options: ['Sprinkler System & Fire Alarm', 'Hydrant', 'Extinguisher', 'Fire Hose'],
      correctOptionIndex: 0,
      explanation: 'Sprinkler otomatis menyemprotkan air jika mendeteksi suhu panas indikasi kebakaran.',
    ),
    QuestionItem(
      id: 'htl_058',
      questionText: 'Layanan penjemputan dan pengantaran tamu antara hotel dan bandara dinamakan:',
      options: ['Airport Shuttle / Transfer Service', 'Valet Parking', 'Car Rental', 'Taxi Service'],
      correctOptionIndex: 0,
      explanation: 'Airport Shuttle mengantar-jemput tamu dari/ke bandara.',
    ),
    QuestionItem(
      id: 'htl_059',
      questionText: 'Paket sewa kamar hotel yang sudah mencakup harga kamar dan sarapan pagi dinamakan:',
      options: ['Continental Plan (CP) / Bed and Breakfast', 'European Plan (EP)', 'American Plan (AP)', 'Full Board'],
      correctOptionIndex: 0,
      explanation: 'Bed and Breakfast (atau Continental Plan) menyatu dengan sarapan pagi.',
    ),
    QuestionItem(
      id: 'htl_060',
      questionText: 'Paket harga sewa kamar yang hanya mencakup sewa kamar saja tanpa termasuk makan sama sekali dinamakan:',
      options: ['European Plan (EP)', 'American Plan (AP)', 'Full Board', 'Half Board'],
      correctOptionIndex: 0,
      explanation: 'European Plan (EP) murni hanya biaya kamar tanpa sarapan.',
    ),
    QuestionItem(
      id: 'htl_061',
      questionText: 'Paket penginapan hotel yang mencakup sewa kamar, makan pagi, makan siang, dan makan malam secara lengkap dinamakan:',
      options: ['Full Board / Full American Plan', 'Half Board', 'Continental Plan', 'Bermuda Plan'],
      correctOptionIndex: 0,
      explanation: 'Full Board mencakup 3 kali makan lengkap.',
    ),
    QuestionItem(
      id: 'htl_062',
      questionText: 'Menu sarapan pagi sederhana gaya Eropa yang terdiri dari roti, mentega, selai, dan teh/kopi dinamakan:',
      options: ['Continental Breakfast', 'American Breakfast', 'Indonesian Breakfast', 'English Breakfast'],
      correctOptionIndex: 0,
      explanation: 'Continental Breakfast menyajikan variasi roti dan minuman hangat.',
    ),
    QuestionItem(
      id: 'htl_063',
      questionText: 'Menu sarapan pagi lengkap gaya Amerika yang mencakup hidangan telur, sosis, bacon, roti bakar, dan jus buah dinamakan:',
      options: ['American Breakfast', 'Continental Breakfast', 'Oriental Breakfast', 'Asian Breakfast'],
      correctOptionIndex: 0,
      explanation: 'American Breakfast menyajikan hidangan sarapan hangat tinggi protein.',
    ),
    QuestionItem(
      id: 'htl_064',
      questionText: 'Tipe kamar hotel yang dilengkapi dengan satu tempat tidur berukuran sangat besar (super king size) dinamakan:',
      options: ['King Room', 'Twin Room', 'Single Room', 'Triple Room'],
      correctOptionIndex: 0,
      explanation: 'King Room menyediakan 1 tempat tidur king size.',
    ),
    QuestionItem(
      id: 'htl_065',
      questionText: 'Tipe kamar hotel yang dilengkapi dengan dua tempat tidur terpisah berukuran sedang dinamakan:',
      options: ['Twin Room', 'Double Room', 'Single Room', 'King Room'],
      correctOptionIndex: 0,
      explanation: 'Twin Room menyediakan dua tempat tidur terpisah (single/twin bed).',
    ),
    QuestionItem(
      id: 'htl_066',
      questionText: 'Tipe kamar hotel mewah yang dilengkapi dengan ruang tamu terpisah dari ruang kamar tidur dinamakan:',
      options: ['Suite Room', 'Standard Room', 'Superior Room', 'Deluxe Room'],
      correctOptionIndex: 0,
      explanation: 'Suite Room memisahkan area ruang tamu (living room) dengan kamar tidur.',
    ),
    QuestionItem(
      id: 'htl_067',
      questionText: 'Tipe kamar terluas dan paling mewah yang umumnya terletak di lantai puncak hotel dinamakan:',
      options: ['Presidential Suite', 'Junior Suite', 'Executive Room', 'Penthouse'],
      correctOptionIndex: 0,
      explanation: 'Presidential Suite merupakan kelas kamar paling puncak dan mewah.',
    ),
    QuestionItem(
      id: 'htl_068',
      questionText: 'Dua kamar hotel yang letaknya bersebelahan dan dihubungkan oleh pintu akses dalam kamar dinamakan:',
      options: ['Connecting Room', 'Adjoining Room', 'Adjacent Room', 'Duplex Room'],
      correctOptionIndex: 0,
      explanation: 'Connecting Room memiliki pintu penghubung internal antar-kamar.',
    ),
    QuestionItem(
      id: 'htl_069',
      questionText: 'Dua kamar hotel yang letaknya berdampingan namun tidak memiliki pintu penghubung dalam dinamakan:',
      options: ['Adjoining Room', 'Connecting Room', 'Suite Room', 'Studio Room'],
      correctOptionIndex: 0,
      explanation: 'Adjoining Room letaknya bersebelahan tanpa pintu sambung internal.',
    ),
    QuestionItem(
      id: 'htl_070',
      questionText: 'Seksi di F&B Service yang bertugas mengantarkan makanan pesanan dari dapur menuju meja restoran atau kamar dinamakan:',
      options: ['Food Runner', 'Busboy', 'Hostess', 'Captain'],
      correctOptionIndex: 0,
      explanation: 'Food Runner mengantar piring masakan siap saji ke area pelayanan.',
    ),
    QuestionItem(
      id: 'htl_071',
      questionText: 'Struktur hirarki manajerial tim dapur hotel yang dipelopori oleh Auguste Escoffier dinamakan:',
      options: ['Brigade de Cuisine', 'Kitchen Army', 'Chef Corps', 'Culinary Staff'],
      correctOptionIndex: 0,
      explanation: 'Brigade de Cuisine membagi tugas staf dapur secara terstruktur dan efisien.',
    ),
    QuestionItem(
      id: 'htl_072',
      questionText: 'Kategori hotel berdasarkan lokasi yang terletak di pusat perkotaan dan menyasar tamu pebisnis dinamakan:',
      options: ['City Hotel / Business Hotel', 'Resort Hotel', 'Motel', 'Boatel'],
      correctOptionIndex: 0,
      explanation: 'City Hotel berlokasi di pusat kota untuk perjalanan bisnis.',
    ),
    QuestionItem(
      id: 'htl_073',
      questionText: 'Kategori hotel yang berlokasi di daerah tujuan wisata (seperti pantai/gunung) untuk kebutuhan liburan dinamakan:',
      options: ['Resort Hotel', 'City Hotel', 'Transit Hotel', 'Commercial Hotel'],
      correctOptionIndex: 0,
      explanation: 'Resort Hotel memprioritaskan fasilitas rekreasi dan pemandangan alam.',
    ),
    QuestionItem(
      id: 'htl_074',
      questionText: 'Penginapan ekonomis berbasis tempat tidur (bunk bed) yang populer di kalangan wisatawan mandiri/backpacker dinamakan:',
      options: ['Hostel', 'Resort', 'Boutique Hotel', 'Villa'],
      correctOptionIndex: 0,
      explanation: 'Hostel menyediakan kamar asrama ekonomis berpemberdayaan fasilitas bersama.',
    ),
    QuestionItem(
      id: 'htl_075',
      questionText: 'Hotel transit yang berlokasi sangat dekat dengan kawasan bandara udara dinamakan:',
      options: ['Airport Hotel', 'Harbor Hotel', 'Motel', 'Casino Hotel'],
      correctOptionIndex: 0,
      explanation: 'Airport Hotel memfasilitasi tamu transit penerbangan.',
    ),
    QuestionItem(
      id: 'htl_076',
      questionText: 'Proses penutupan dan audit keuangan transaksi harian Front Office pada malam hari dinamakan:',
      options: ['Night Audit', 'Day End Closing', 'Balance Sheet', 'Check-out Audit'],
      correctOptionIndex: 0,
      explanation: 'Night Audit memeriksa kebenaran seluruh posting tagihan harian hotel.',
    ),
    QuestionItem(
      id: 'htl_077',
      questionText: 'Petugas Front Office yang merekap data tagihan kamar dan menutup pembukuan harian transaksi hotel di malam hari dinamakan:',
      options: ['Night Auditor', 'General Cashier', 'Income Auditor', 'Account Payable'],
      correctOptionIndex: 0,
      explanation: 'Night Auditor mengaudit transaksi keuangan hotel pada shift malam.',
    ),
    QuestionItem(
      id: 'htl_078',
      questionText: 'Waktu batas resmi berlakunya registrasi kamar menginap bagi tamu hotel (standar internasional pukul 14.00) dinamakan:',
      options: ['Check-In Time', 'Check-Out Time', 'Registration Time', 'Arrival Time'],
      correctOptionIndex: 0,
      explanation: 'Check-In Time adalah batas awal masuk penyerahan kunci kamar.',
    ),
    QuestionItem(
      id: 'htl_079',
      questionText: 'Waktu batas resmi tamu harus mengosongkan kamar dan menyelesaikan pembayaran (standar pukul 12.00) dinamakan:',
      options: ['Check-Out Time', 'Check-In Time', 'Departure Time', 'Closing Time'],
      correctOptionIndex: 0,
      explanation: 'Check-Out Time adalah batas penyerahan kembali kamar di siang hari.',
    ),
    QuestionItem(
      id: 'htl_080',
      questionText: 'Formulir umpan balik yang diisi tamu untuk menyampaikan kritik, saran, atau tingkat kepuasan pelayanan hotel dinamakan:',
      options: ['Guest Comment Card', 'Registration Card', 'Reservation Form', 'Voucher'],
      correctOptionIndex: 0,
      explanation: 'Guest Comment Card mengukur kepuasan dan evaluasi kualitas layanan.',
    ),
    QuestionItem(
      id: 'htl_081',
      questionText: 'Penanganan keluhan atau komplain tamu secara profesional untuk memulihkan kepuasan tamu dinamakan:',
      options: ['Guest Complaint Handling / Service Recovery', 'Upselling', 'Service Charge', 'Auditing'],
      correctOptionIndex: 0,
      explanation: 'Service Recovery memulihkan kembali kepercayaan dan kenyamanan tamu yang kecewa.',
    ),
    QuestionItem(
      id: 'htl_082',
      questionText: 'Program apresiasi keanggotaan bagi tamu langganan setia hotel untuk mendapatkan poin dan keuntungan diskon dinamakan:',
      options: ['Loyalty Program / Membership', 'Corporate Discount', 'Voucher Code', 'Agent Rate'],
      correctOptionIndex: 0,
      explanation: 'Loyalty Program merawat retensi kunjungan berulang tamu setia.',
    ),
    QuestionItem(
      id: 'htl_083',
      questionText: 'Layanan gratis dari hotel (seperti kue selamat datang atau buah) sebagai bentuk penghormatan tamu dinamakan:',
      options: ['Complimentary (Comp)', 'Extra Charge', 'Service Charge', 'Tax Service'],
      correctOptionIndex: 0,
      explanation: 'Complimentary disajikan tanpa mengenakan biaya kepada tamu (free of charge).',
    ),
    QuestionItem(
      id: 'htl_084',
      questionText: 'Proses mencatat dan mengonfirmasi pesanan makanan dan minuman dari tamu di meja restoran dinamakan:',
      options: ['Taking Order', 'Greeting', 'Clearing', 'Billing'],
      correctOptionIndex: 0,
      explanation: 'Taking Order adalah tahap pencatatan pesanan menu oleh pramusaji.',
    ),
    QuestionItem(
      id: 'htl_085',
      questionText: 'Daftar pilihan makanan dan minuman lengkap dengan harga yang disajikan kepada tamu restoran dinamakan:',
      options: ['Menu List', 'Wine List', 'Recipe Book', 'Inventory List'],
      correctOptionIndex: 0,
      explanation: 'Menu list memuat sajian makanan dan minuman yang ditawarkan.',
    ),
    QuestionItem(
      id: 'htl_086',
      questionText: 'Kartu menu di mana setiap porsi hidangan makanan memiliki harga terpisah sendiri dinamakan menu:',
      options: ['A la Carte', 'Table d\'Hôte', 'Buffet Menu', 'Set Menu'],
      correctOptionIndex: 0,
      explanation: 'A la Carte memungkinkan tamu memilih makanan dan membayar per porsi secara terpisah.',
    ),
    QuestionItem(
      id: 'htl_087',
      questionText: 'Paket menu makanan lengkap berurutan dari hidangan pembuka hingga penutup yang dijual dengan satu harga pasti dinamakan:',
      options: ['Table d\'Hôte / Set Menu', 'A la Carte', 'Buffet', 'Brunch'],
      correctOptionIndex: 0,
      explanation: 'Table d\'Hôte menyajikan paket set menu lengkap bernilai harga tunggal.',
    ),
    QuestionItem(
      id: 'htl_088',
      questionText: 'Hidangan pembuka kecil yang disajikan paling awal untuk membangkitkan selera makan dinamakan:',
      options: ['Appetizer', 'Main Course', 'Dessert', 'Soup'],
      correctOptionIndex: 0,
      explanation: 'Appetizer disajikan pertama untuk menggugah selera sebelum makanan utama.',
    ),
    QuestionItem(
      id: 'htl_089',
      questionText: 'Hidangan utama yang paling mengenyangkan dan menjadi inti porsi santap malam dinamakan:',
      options: ['Main Course', 'Appetizer', 'Dessert', 'Entrée'],
      correctOptionIndex: 0,
      explanation: 'Main Course adalah santapan pokok utama.',
    ),
    QuestionItem(
      id: 'htl_090',
      questionText: 'Hidangan penutup berupa es krim, kue manis, atau buah segar yang disajikan di akhir santap malam dinamakan:',
      options: ['Dessert', 'Appetizer', 'Main Course', 'Beverage'],
      correctOptionIndex: 0,
      explanation: 'Dessert menutup perjamuan dengan rasa manis atau menyegarkan.',
    ),
    QuestionItem(
      id: 'htl_091',
      questionText: 'Minuman hasil fermentasi sari buah anggur asli dinamakan:',
      options: ['Wine', 'Beer', 'Spirit', 'Liqueur'],
      correctOptionIndex: 0,
      explanation: 'Wine difermentasi dari sari buah anggur.',
    ),
    QuestionItem(
      id: 'htl_092',
      questionText: 'Pramusaji ahli minuman anggur (wine) di restoran mewah yang bertugas memberikan saran paduan wine dinamakan:',
      options: ['Sommelier', 'Barista', 'Bartender', 'Steward'],
      correctOptionIndex: 0,
      explanation: 'Sommelier adalah pakar pemandu rekomendasi dan penyajian wine.',
    ),
    QuestionItem(
      id: 'htl_093',
      questionText: 'Petugas peracik minuman alkohol dan non-alkohol di counter bar hotel dinamakan:',
      options: ['Bartender', 'Barista', 'Sommelier', 'Barboy'],
      correctOptionIndex: 0,
      explanation: 'Bartender meracik koktail dan mocktail di bar.',
    ),
    QuestionItem(
      id: 'htl_094',
      questionText: 'Minuman campuran segar non-alkohol dari kombinasi jus buah, sirup, dan soda dinamakan:',
      options: ['Mocktail', 'Cocktail', 'Smoothie', 'Infused Water'],
      correctOptionIndex: 0,
      explanation: 'Mocktail tidak mengandung alkohol sama sekali (zero-proof cocktail).',
    ),
    QuestionItem(
      id: 'htl_095',
      questionText: 'Minuman campuran yang mengandung bahan spirit minuman beralkohol dinamakan:',
      options: ['Cocktail', 'Mocktail', 'Soft Drink', 'Cordal'],
      correctOptionIndex: 0,
      explanation: 'Cocktail memadukan spirit beralkohol dengan bahan perasa lain.',
    ),
    QuestionItem(
      id: 'htl_096',
      questionText: 'Seksi di bagian dapur F&B yang bertanggung jawab melakukan pencucian dan perawatan piring makan serta alat dapur dinamakan:',
      options: ['Stewarding', 'Housekeeping', 'Garde Manger', 'Pantry'],
      correctOptionIndex: 0,
      explanation: 'Stewarding mengurus kebersihan saniter peralatan masak dan piring.',
    ),
    QuestionItem(
      id: 'htl_097',
      questionText: 'Petugas dapur yang bertugas mencuci piring, menjaga kebersihan peralatan, dan sanitasi area dapur dinamakan:',
      options: ['Steward', 'Dishwasher Attendant', 'Commis', 'Runner'],
      correctOptionIndex: 0,
      explanation: 'Steward memastikan seluruh peralatan dapur higienis dan bersih.',
    ),
    QuestionItem(
      id: 'htl_098',
      questionText: 'Pemeriksaan penghitungan jumlah fisik stok barang dan persediaan bahan makanan di gudang hotel dinamakan:',
      options: ['Stock Take / Inventory Stock', 'Receiving', 'Purchasing', 'Auditing'],
      correctOptionIndex: 0,
      explanation: 'Stock Take menghitung sisa fisik persediaan bahan baku gudang.',
    ),
    QuestionItem(
      id: 'htl_099',
      questionText: 'Persentase rasio perbandingan total biaya modal bahan baku makanan terhadap total nilai pendapatan penjualan F&B dinamakan:',
      options: ['Food Cost Percentage', 'Labor Cost', 'Profit Margin', 'Service Charge'],
      correctOptionIndex: 0,
      explanation: 'Food Cost Percentage mengukur efisiensi biaya pemakaian bahan makanan (idealnya 28-35%).',
    ),
    QuestionItem(
      id: 'htl_100',
      questionText: 'Disiplin ilmu manajemen industri jasa ramah tamah yang mengelola operasional akomodasi, restoran, dan pelayanan tamu dinamakan:',
      options: ['Manajemen Perhotelan (Hospitality Management)', 'Manajemen Keuangan', 'Teknologi Pangan', 'Pemasaran Digital'],
      correctOptionIndex: 0,
      explanation: 'Manajemen Perhotelan mempelajari tata kelola akomodasi bisnis hospitality, F&B, dan kepuasan tamu.',
    ),
  ];
}
