import '../tes_seleksi_model.dart';

List<QuestionItem> getArsitekturQuestions() {
  return const [
    QuestionItem(
      id: 'ars_001',
      questionText: 'Tiga prinsip dasar arsitektur menurut Vitruvius (Trilogi Vitruvius) adalah:',
      options: ['Firmitas (Kekuatan), Utilitas (Kegunaan), dan Venustas (Keindahan)', 'Bentuk, Warna, dan Fungsi', 'Struktur, Material, dan Anggaran', 'Skala, Proporsi, dan Ruang'],
      correctOptionIndex: 0,
      explanation: 'Vitruvius merumuskan Firmitas, Utilitas, dan Venustas sebagai trinitas arsitektur.',
    ),
    QuestionItem(
      id: 'ars_002',
      questionText: 'Prinsip desain "Form Follows Function" (Bentuk Mengikuti Fungsi) dikemukakan oleh arsitek modern terkenal:',
      options: ['Louis Sullivan', 'Le Corbusier', 'Frank Lloyd Wright', 'Mies van der Rohe'],
      correctOptionIndex: 0,
      explanation: 'Louis Sullivan mencetuskan slogan "form follows function".',
    ),
    QuestionItem(
      id: 'ars_003',
      questionText: 'Slogan arsitektur minimalis "Less is More" dikemukakan oleh tokoh arsitek:',
      options: ['Ludwig Mies van der Rohe', 'Le Corbusier', 'Zaha Hadid', 'Renzo Piano'],
      correctOptionIndex: 0,
      explanation: 'Mies van der Rohe mengagungkan kesederhanaan minimalis "Less is More".',
    ),
    QuestionItem(
      id: 'ars_004',
      questionText: 'Prinsip arsitektur organik yang menyatu harmoni dengan alam sekitar dirintis oleh arsitek:',
      options: ['Frank Lloyd Wright', 'Walter Gropius', 'Oscar Niemeyer', 'Norman Foster'],
      correctOptionIndex: 0,
      explanation: 'Frank Lloyd Wright merancang karya ikonik Fallingwater berkonsep arsitektur organik.',
    ),
    QuestionItem(
      id: 'ars_005',
      questionText: 'Ungkapan "A House is a Machine for Living in" (Rumah adalah mesin untuk ditinggali) dikemukakan oleh:',
      options: ['Le Corbusier', 'Louis Sullivan', 'Alvar Aalto', 'Kenzo Tange'],
      correctOptionIndex: 0,
      explanation: 'Le Corbusier menganggap rumah sebagai mesin fungsional efisien.',
    ),
    QuestionItem(
      id: 'ars_006',
      questionText: 'Gaya arsitektur Eropa abad tengah yang ditandai dengan jajaran kubah runcing (pointed arch) dan kaca patri (stained glass) dinamakan:',
      options: ['Arsitektur Gotik (Gothic)', 'Arsitektur Romanesque', 'Arsitektur Barok', 'Arsitektur Renaisans'],
      correctOptionIndex: 0,
      explanation: 'Arsitektur Gotik dicirikan oleh kubah lancip, flying buttress, dan stained glass.',
    ),
    QuestionItem(
      id: 'ars_007',
      questionText: 'Gaya arsitektur Klasik Yunani mengenal tiga jenis kolom utama (Orders) yaitu:',
      options: ['Doric, Ionic, dan Corinthian', 'Tuscan, Composite, dan Roman', 'Gothic, Baroque, dan Rococo', 'Modern, Minimalis, dan Tropis'],
      correctOptionIndex: 0,
      explanation: 'Tiga kolom klasik Yunani: Doric (kokoh polos), Ionic (gulungan vosa), Corinthian (daun akantus).',
    ),
    QuestionItem(
      id: 'ars_008',
      questionText: 'Kolom klasik Yunani yang ditandai dengan ornamen kepala kolom berbentuk gulungan skrol (volute) dinamakan:',
      options: ['Ionic', 'Doric', 'Corinthian', 'Tuscan'],
      correctOptionIndex: 0,
      explanation: 'Kolom Ionic memiliki kapitel berciri khas gulungan skrol volute.',
    ),
    QuestionItem(
      id: 'ars_009',
      questionText: 'Kolom klasik Yunani dengan ornamentasi daun-daunan akantus yang paling rumit indah dinamakan:',
      options: ['Corinthian', 'Doric', 'Ionic', 'Composite'],
      correctOptionIndex: 0,
      explanation: 'Corinthian merupakan kolom paling dekoratif dengan ukiran daun akantus.',
    ),
    QuestionItem(
      id: 'ars_010',
      questionText: 'Gerakan seni dan desain Bauhaus yang sangat mempengaruhi perkembangan arsitektur modern didirikan di negara:',
      options: ['Jerman', 'Prancis', 'Inggris', 'Amerika Serikat'],
      correctOptionIndex: 0,
      explanation: 'Sekolah Bauhaus didirikan oleh Walter Gropius di Weimar, Jerman (1919).',
    ),
    QuestionItem(
      id: 'ars_011',
      questionText: 'Bentuk proporsi estetika matematika rasio emas yang bernilai ~1.618 dinamakan:',
      options: ['Golden Ratio (Rasio Emas / Phi)', 'Modulor', 'Deret Fibonacci', 'Skala Humanis'],
      correctOptionIndex: 0,
      explanation: 'Golden Ratio (1 : 1.618) dipakai sejak zaman Yunani kuno untuk estetika harmonis.',
    ),
    QuestionItem(
      id: 'ars_012',
      questionText: 'Sistem proporsi pengukuran tubuh manusia yang diciptakan Le Corbusier dinamakan:',
      options: ['Le Modulor', 'Ergonomi', 'Antropometri', 'Vitruvian Man'],
      correctOptionIndex: 0,
      explanation: 'Le Modulor mengombinasikan skala manusia dengan Rasio Emas.',
    ),
    QuestionItem(
      id: 'ars_013',
      questionText: 'Ilmu yang mengukur dimensi ukuran tubuh manusia untuk perancangan furnitur dan ruang dinamakan:',
      options: ['Antropometri', 'Ergonomi', 'Ekologi', 'Proksemik'],
      correctOptionIndex: 0,
      explanation: 'Antropometri mengukur dimensi fisik tubuh manusia.',
    ),
    QuestionItem(
      id: 'ars_014',
      questionText: 'Ilmu yang mempelajari interaksi kenyamanan dan keselamatan fisik manusia terhadap produk/ruang kerja dinamakan:',
      options: ['Ergonomi', 'Antropometri', 'Proksemik', 'Estetika'],
      correctOptionIndex: 0,
      explanation: 'Ergonomi memastikan rancangan aman dan nyaman dipakai fisik manusia.',
    ),
    QuestionItem(
      id: 'ars_015',
      questionText: 'Studi tentang penggunaan jarak ruang antar pribadi manusia dalam interaksi sosial dikemukakan oleh Edward T. Hall dinamakan:',
      options: ['Proksemik (Proxemics)', 'Ergonomi', 'Feng Shui', 'Spatiality'],
      correctOptionIndex: 0,
      explanation: 'Proksemik membagi zona jarak (Intimate, Personal, Social, Public).',
    ),
    QuestionItem(
      id: 'ars_016',
      questionText: 'Teknik proyeksi menggambar bangunan dari sudut pandang miring 3D dinamakan gambar:',
      options: ['Aksonometri / Isometri', 'Perspektif', 'Tampak', 'Potongan'],
      correctOptionIndex: 0,
      explanation: 'Isometri/Aksonometri menampilkan objek 3D tanpa titik hilang.',
    ),
    QuestionItem(
      id: 'ars_017',
      questionText: 'Gambar proyeksi tegak dari atas yang memperlihatkan denah ruangan dan dinding dinamakan gambar:',
      options: ['Denah (Floor Plan)', 'Tampak', 'Potongan', 'Site Plan'],
      correctOptionIndex: 0,
      explanation: 'Denah adalah potongan horisontal setinggi ~1 meter dari permukaan lantai.',
    ),
    QuestionItem(
      id: 'ars_018',
      questionText: 'Gambar proyeksi ortogonal dari samping/depan yang memperlihatkan wujud luar fasad bangunan dinamakan:',
      options: ['Tampak (Elevation)', 'Denah', 'Potongan', 'Detail'],
      correctOptionIndex: 0,
      explanation: 'Tampak menunjukkan ekspresi fasad eksterior bangunan.',
    ),
    QuestionItem(
      id: 'ars_019',
      questionText: 'Gambar proyeksi irisan vertikal bangunan yang memperlihatkan bagian dalam dan struktur dinamakan:',
      options: ['Potongan (Section)', 'Denah', 'Tampak', 'Isometric'],
      correctOptionIndex: 0,
      explanation: 'Potongan (Section) memperlihatkan irisan vertikal pondasi hingga atap.',
    ),
    QuestionItem(
      id: 'ars_020',
      questionText: 'Gambar yang memperlihatkan tata letak bangunan di atas tapak lahan beserta jalan sekitarnya dinamakan:',
      options: ['Site Plan', 'Denah', 'Master Plan', 'Block Plan'],
      correctOptionIndex: 0,
      explanation: 'Site plan menunjukkan hubungan posisi bangunan terhadap batas tapak.',
    ),
    QuestionItem(
      id: 'ars_021',
      questionText: 'Gambar proyeksi 3D yang meniru cara pandang mata manusia dengan menggunakan titik hilang (vanishing point) dinamakan:',
      options: ['Gambar Perspektif', 'Isometri', 'Orktogonal', 'Aksonometri'],
      correctOptionIndex: 0,
      explanation: 'Perspektif (1, 2, atau 3 titik hilang) menciptakan ilusi kedalaman mata manusia.',
    ),
    QuestionItem(
      id: 'ars_022',
      questionText: 'Pendekatan perancangan arsitektur tropis yang memanfaatkan potensi iklim setempat secara alami tanpa listrik dinamakan:',
      options: ['Desain Pasif Tropis (Passive Tropical Design)', 'Desain Aktif', 'HVAC System', 'Smart Home'],
      correctOptionIndex: 0,
      explanation: 'Desain pasif mengandalkan pencahayaan alami, pengudaraan silang, dan overstek shading.',
    ),
    QuestionItem(
      id: 'ars_023',
      questionText: 'Metode pengudaraan alami di dalam gedung dengan memanfaatkan perbedaan tekanan angin dari dua sisi berhadapan dinamakan:',
      options: ['Ventilasi Silang (Cross Ventilation)', 'Stack Effect', 'Exhaust System', 'AC Split'],
      correctOptionIndex: 0,
      explanation: 'Ventilasi silang mengalirkan angin mengalir lewat inlet dan outlet berseberangan.',
    ),
    QuestionItem(
      id: 'ars_024',
      questionText: 'Fenomena aliran udara naik ke atas gedung akibat perbedaan massa jenis udara panas yang membubung ke atas dinamakan:',
      options: ['Efek Cerobong (Stack Effect / Thermal Buoyancy)', 'Cross Ventilation', 'Bernoulli Effect', 'Wind Shadow'],
      correctOptionIndex: 0,
      explanation: 'Stack effect menarik udara dingin dari bawah saat udara panas naik keluar rongga atas.',
    ),
    QuestionItem(
      id: 'ars_025',
      questionText: 'Kanopi atau elemen teritisan atap yang menjorok keluar untuk melindungi jendela dari terik matahari dan hujan dinamakan:',
      options: ['Overstek (Eaves / Shading Device)', 'Lisplang', 'Talang', 'Tritisan'],
      correctOptionIndex: 0,
      explanation: 'Overstek lebar khas bangunan tropis menahan tampias hujan dan radiasi panas.',
    ),
    QuestionItem(
      id: 'ars_026',
      questionText: 'Elemen kisi-kisi atau sirip peneduh fasad luar bangunan untuk memblokir sinar matahari langsung dinamakan:',
      options: ['Sun Shading / Sun Louver (Bole-soleil)', 'Secondary Skin', 'Rooster', 'Curtain Wall'],
      correctOptionIndex: 0,
      explanation: 'Bris-soleil / Sun shading menepis panas tanpa mengorbankan masuknya cahaya terang.',
    ),
    QuestionItem(
      id: 'ars_027',
      questionText: 'Lapisan fasad ganda luar bangunan yang berfungsi sebagai pelindung radiasi dan estetika dinamakan:',
      options: ['Secondary Skin (Kulit Kedua Fasad)', 'Curtain Wall', 'Cladding', 'Wall Paper'],
      correctOptionIndex: 0,
      explanation: 'Secondary skin memberikan barier termal dan ekspresi dinamis fasad.',
    ),
    QuestionItem(
      id: 'ars_028',
      questionText: 'Bata berongga berukir yang digunakan sebagai saluran ventilasi angin dan estetika dinding dinamakan:',
      options: ['Roster (Ventilation Block)', 'Bata Ringan (Hebel)', 'Roster Jalusi', 'Bata Merah'],
      correctOptionIndex: 0,
      explanation: 'Roster / Rostér memfasilitasi aliran sirkulasi udara dan celah cahaya artistik.',
    ),
    QuestionItem(
      id: 'ars_029',
      questionText: 'Dinding kaca non-struktural yang menutup fasad luar gedung pencakar langit dinamakan:',
      options: ['Curtain Wall (Dinding Tirai Kaca)', 'Partition Wall', 'Shear Wall', 'Bearing Wall'],
      correctOptionIndex: 0,
      explanation: 'Curtain wall hanya memikul berat sendirinya dan meneruskan beban angin ke struktur gedung.',
    ),
    QuestionItem(
      id: 'ars_030',
      questionText: 'Dinding beton bertulang kaku yang dirancang khusus untuk menahan gaya geser gempa bumi pada gedung tinggi dinamakan:',
      options: ['Dinding Geser (Shear Wall)', 'Dinding Dinding Tirai', 'Dinding Partisi', 'Dinding Batako'],
      correctOptionIndex: 0,
      explanation: 'Shear wall memberikan kekakuan lateral menahan gaya gempa dan angin.',
    ),
    QuestionItem(
      id: 'ars_031',
      questionText: 'Inti struktur gedung tinggi yang menampung sarana lift, tangga darurat, dan instalasi mekanikal dinamakan:',
      options: ['Core (Inti Bangunan)', 'Shaft', 'Podium', 'Basement'],
      correctOptionIndex: 0,
      explanation: 'Core gedung umumnya dari beton tebal yang juga bertindak sebagai kekuatan lateral utama.',
    ),
    QuestionItem(
      id: 'ars_032',
      questionText: 'Rongga vertikal menerus pada gedung tinggi untuk jalur pipa air, kabel, dan saluran udara dinamakan:',
      options: ['Shaft Utility', 'Void', 'Atrium', 'Balok'],
      correctOptionIndex: 0,
      explanation: 'Shaft utilitas mengarahkan instalasi vertikal gedung.',
    ),
    QuestionItem(
      id: 'ars_033',
      questionText: 'Rongga terbuka besar bertingkat di bagian dalam gedung yang membumbung tinggi dinamakan:',
      options: ['Atrium', 'Courtyard', 'Balkon', 'Mezzanine'],
      correctOptionIndex: 0,
      explanation: 'Atrium memberi impresi megah dan memasukkan pencahayaan alami ke bagian dalam gedung.',
    ),
    QuestionItem(
      id: 'ars_034',
      questionText: 'Taman atau ruang terbuka yang dikelilingi oleh massa bangunan dinamakan:',
      options: ['Courtyard (Plaza Dalam / Innercourt)', 'Patio', 'Terrace', 'Balkon'],
      correctOptionIndex: 0,
      explanation: 'Courtyard menciptakan oase ruang hijau privat di tengah denah bangunan.',
    ),
    QuestionItem(
      id: 'ars_035',
      questionText: 'Lantai tambahan setengah tingkat di antara dua lantai utama dinamakan lantai:',
      options: ['Mezzanine', 'Basement', 'Attic', 'Penthouse'],
      correctOptionIndex: 0,
      explanation: 'Mezzanine adalah balkon lantai perantara yang tidak memakan penuh seluas ruangan.',
    ),
    QuestionItem(
      id: 'ars_036',
      questionText: 'Ruang bawah tanah gedung yang digunakan untuk parkir dan fasilitas mesin utilitas dinamakan:',
      options: ['Basement', 'Sub-Structure', 'Attic', 'Ground Level'],
      correctOptionIndex: 0,
      explanation: 'Basement terletak di bawah permukaan tanah.',
    ),
    QuestionItem(
      id: 'ars_037',
      questionText: 'Ruang tempat tinggal di bawah atap miring dinamakan:',
      options: ['Attic (Loteng)', 'Mezzanine', 'Penthouse', 'Balkon'],
      correctOptionIndex: 0,
      explanation: 'Attic memanfaatkan ruang kosong di bawah rangka atap.',
    ),
    QuestionItem(
      id: 'ars_038',
      questionText: 'Unit hunian mewah eksklusif yang terletak di lantai paling atas gedung apartemen tinggi dinamakan:',
      options: ['Penthouse', 'Duplex', 'Studio', 'Loft'],
      correctOptionIndex: 0,
      explanation: 'Penthouse merupakan hunian teratas dengan pemandangan dan fasilitas mewah.',
    ),
    QuestionItem(
      id: 'ars_039',
      questionText: 'Konstruksi atap miring 4 sisi yang terdiri dari 2 sisi segitiga dan 2 sisi trapesium dinamakan atap:',
      options: ['Perisai (Hip Roof)', 'Pelana (Gable Roof)', 'Datar (Flat Roof)', 'Mansard'],
      correctOptionIndex: 0,
      explanation: 'Atap perisai (limasan) mengalirkan air hujan ke 4 penjuru.',
    ),
    QuestionItem(
      id: 'ars_040',
      questionText: 'Konstruksi atap miring sederhana 2 sisi yang membentuk bidang segitiga di ujungnya dinamakan atap:',
      options: ['Pelana (Gable Roof)', 'Perisai', 'Miring (Shed Roof)', 'Kubah'],
      correctOptionIndex: 0,
      explanation: 'Atap pelana memiliki dua bidang miring yang bertemu pada bubungan.',
    ),
    QuestionItem(
      id: 'ars_041',
      questionText: 'Garis puncak pertemuan tertinggi dua bidang miring atap dinamakan:',
      options: ['Bubungan (Ridge / Nok)', 'Nok', 'Gording', 'Kuda-kuda'],
      correctOptionIndex: 0,
      explanation: 'Bubungan (nok) menutup puncak pertemuan bidang atap.',
    ),
    QuestionItem(
      id: 'ars_042',
      questionText: 'Batang kayu/baja melintang yang menumpu kasau/reng tempat genteng bersandar dinamakan:',
      options: ['Gording (Purlin)', 'Kuda-kuda', 'Usuk', 'Lisplang'],
      correctOptionIndex: 0,
      explanation: 'Gording bertumpu di atas kuda-kuda memikul usuk dan genteng.',
    ),
    QuestionItem(
      id: 'ars_043',
      questionText: 'Rangka pemikul utama beban atap bertipe rangka batang segitiga dinamakan:',
      options: ['Kuda-Kuda Atap (Truss)', 'Gording', 'Usuk', 'Reng'],
      correctOptionIndex: 0,
      explanation: 'Kuda-kuda mentransfer beban atap ke kolom bangunan.',
    ),
    QuestionItem(
      id: 'ars_044',
      questionText: 'Konsep desain bangunan ramah lingkungan yang hemat energi dan bersertifikasi hijau dinamakan:',
      options: ['Green Building (Bangunan Hijau)', 'Smart Building', 'Sustainable Design', 'Semua Benar'],
      correctOptionIndex: 3,
      explanation: 'Green building / sustainable design berfokus pada efisiensi energi, air, dan material.',
    ),
    QuestionItem(
      id: 'ars_045',
      questionText: 'Lembaga sertifikasi resmi bangunan hijau di Indonesia dinamakan:',
      options: ['GBCI (Green Building Council Indonesia / Sertifikasi Greenship)', 'LEED', 'EDGE', 'BREEAM'],
      correctOptionIndex: 0,
      explanation: 'GBCI menerbitkan sertifikasi GREENSHIP di Indonesia.',
    ),
    QuestionItem(
      id: 'ars_046',
      questionText: 'Standar sertifikasi bangunan hijau internasional yang paling terkenal asal Amerika Serikat adalah:',
      options: ['LEED (Leadership in Energy and Environmental Design)', 'GREENSHIP', 'BREEAM', 'CASBEE'],
      correctOptionIndex: 0,
      explanation: 'LEED adalah standar acuan sertifikasi hijau global dari USGBC.',
    ),
    QuestionItem(
      id: 'ars_047',
      questionText: 'Taman tanaman hijau yang ditanam di atas permukaan atap datar gedung dinamakan:',
      options: ['Green Roof (Atap Hijau)', 'Vertical Garden', 'Roof Garden', 'Parklet'],
      correctOptionIndex: 0,
      explanation: 'Green roof meredam panas termal insulasi dan mengurangi limpasan air hujan.',
    ),
    QuestionItem(
      id: 'ars_048',
      questionText: 'Taman tanaman yang ditanam secara vertikal pada dinding luar/dalam bangunan dinamakan:',
      options: ['Vertical Garden (Living Wall)', 'Green Roof', 'Terrarium', 'Bio-wall'],
      correctOptionIndex: 0,
      explanation: 'Vertical garden (living wall) menghijaukan fasad terbatas lahan.',
    ),
    QuestionItem(
      id: 'ars_049',
      questionText: 'Satuan ukuran pencahayaan dalam sistem internasional (SI) yang mengukur tingkat iluminasi permukaan adalah:',
      options: ['Lux (lx)', 'Lumen (lm)', 'Candela (cd)', 'Watt'],
      correctOptionIndex: 0,
      explanation: 'Lux mengukur fluks cahaya per meter persegi (1 Lux = 1 Lumen/m²).',
    ),
    QuestionItem(
      id: 'ars_050',
      questionText: 'Satuan ukuran total fluks pancaran cahaya yang dikeluarkan oleh sumber lampu dinamakan:',
      options: ['Lumen (lm)', 'Lux', 'Candela', 'Kelvin'],
      correctOptionIndex: 0,
      explanation: 'Lumen mengukur total output cahaya sumber lampu.',
    ),
    QuestionItem(
      id: 'ars_051',
      questionText: 'Tingkat iluminasi standar pencahayaan minimum yang direkomendasikan untuk ruangan kantor kerja adalah sekitar:',
      options: ['300 Lux', '50 Lux', '1000 Lux', '5000 Lux'],
      correctOptionIndex: 0,
      explanation: 'Standard SNI pencahayaan ruang kerja kantor adalah 300 Lux.',
    ),
    QuestionItem(
      id: 'ars_052',
      questionText: 'Suhu warna cahaya lampu (Correlated Color Temperature) yang memancarkan warna hangat kekuningan hangat berada pada skala:',
      options: ['2700K - 3000K (Warm White)', '4000K (Cool White)', '6500K (Daylight)', '10000K'],
      correctOptionIndex: 0,
      explanation: '2700K-3000K memberikan pencahayaan Warm White santai rileks.',
    ),
    QuestionItem(
      id: 'ars_053',
      questionText: 'Suhu warna cahaya lampu kebiruan benderang seperti sinar matahari siang dinamakan:',
      options: ['Daylight (6500K)', 'Warm White (3000K)', 'Cool White (4000K)', 'Amber'],
      correctOptionIndex: 0,
      explanation: '6500K menghasilkan nuansa putih benderang Daylight.',
    ),
    QuestionItem(
      id: 'ars_054',
      questionText: 'Waktu yang dibutuhkan bunyi untuk meluruh berkurang 60 desibel pasca sumber suara berhenti dinamakan:',
      options: ['Waktu Dengung (Reverberation Time / RT60)', 'Eko (Gema)', 'Noise Reduction', 'Atenuasi'],
      correctOptionIndex: 0,
      explanation: 'RT60 adalah indikator utama kualitas akustik ruangan (auditorium/bioskop).',
    ),
    QuestionItem(
      id: 'ars_055',
      questionText: 'Material berpori lembut yang dipasang pada dinding ruangan berfungsi sebagai:',
      options: ['Penyerap Suara (Sound Absorber)', 'Pemantul Suara (Reflector)', 'Penyebar (Diffuser)', 'Isolator'],
      correctOptionIndex: 0,
      explanation: 'Material berpori (busa akustik/rockwool) menyerap gelombang suara menekan gema.',
    ),
    QuestionItem(
      id: 'ars_056',
      questionText: 'Elemen cembung atau berdinding keras tak teratur yang menyebarkan pantulan suara secara merata dinamakan:',
      options: ['Diffuser Akustik', 'Absorber', 'Reflector', 'Baffle'],
      correctOptionIndex: 0,
      explanation: 'Diffuser memecah pantulan suara agar tidak menimbulkan gema terkonsentrasi.',
    ),
    QuestionItem(
      id: 'ars_057',
      questionText: 'Rumus penghitungan luas lahan total maksimum dasar bangunan yang boleh dibangun di atas tanah dinamakan:',
      options: ['KDB (Koefisien Dasar Bangunan)', 'KLB', 'KDH', 'GSB'],
      correctOptionIndex: 0,
      explanation: 'KDB (% x Luas Lahan) menentukan batas lantai dasar proyek.',
    ),
    QuestionItem(
      id: 'ars_058',
      questionText: 'Angka faktor kelipatan total luas seluruh lantai bangunan (termasuk tingkat atas) dinamakan:',
      options: ['KLB (Koefisien Lantai Bangunan)', 'KDB', 'KDH', 'GSB'],
      correctOptionIndex: 0,
      explanation: 'KLB menentukan kapasitas maksimum total batas luas lantai bertingkat.',
    ),
    QuestionItem(
      id: 'ars_059',
      questionText: 'Persentase minimum area terbuka hijau di atas tapak lahan yang tidak boleh tertutup bangunan dinamakan:',
      options: ['KDH (Koefisien Daerah Hijau)', 'KDB', 'KLB', 'GSB'],
      correctOptionIndex: 0,
      explanation: 'KDH menjamin daerah peresapan air hujan dan vegetasi.',
    ),
    QuestionItem(
      id: 'ars_060',
      questionText: 'Gaya arsitektur lokal tradisional Indonesia yang beradaptasi secara selaras dengan iklim dinamakan arsitektur:',
      options: ['Nusantara / Vernakular Indonesia', 'Indische Empire', 'Kolonial', 'Art Deco'],
      correctOptionIndex: 0,
      explanation: 'Arsitektur Nusantara (seperti rumah panggung dan atap limasan tinggi) merespon iklim tropis kelembaban tinggi.',
    ),
    QuestionItem(
      id: 'ars_061',
      questionText: 'Rumah adat tradisional Jawa yang memiliki atap berbentuk tajug empat sisi simetris dinamakan rumah:',
      options: ['Joglo', 'Limasan', 'Kampung', 'Panggang Pe'],
      correctOptionIndex: 0,
      explanation: 'Rumah Joglo dengan struktur soko guru merupakan rumah tradisional khas Jawa.',
    ),
    QuestionItem(
      id: 'ars_062',
      questionText: 'Empat tiang kolom kayu utama penyangga puncak atap rumah Joglo dinamakan:',
      options: ['Soko Guru', 'Blandar', 'Tumpang Sari', 'Umpak'],
      correctOptionIndex: 0,
      explanation: 'Soko Guru adalah 4 tiang penyangga utama tumpang sari rumah Joglo.',
    ),
    QuestionItem(
      id: 'ars_063',
      questionText: 'Susunan balok kayu tumpang bertingkat di puncak soko guru Joglo dinamakan:',
      options: ['Tumpang Sari', 'Blandar', 'Kaki Soko', 'Penter'],
      correctOptionIndex: 0,
      explanation: 'Tumpang sari adalah susunan balok ukir bertingkat menopang puncak atap.',
    ),
    QuestionItem(
      id: 'ars_064',
      questionText: 'Rumah adat khas Minangkabau dengan bentuk atap melengkung runcing seperti tanduk kerbau dinamakan:',
      options: ['Rumah Gadang (Atap Gonjong)', 'Rumah Tongkonan', 'Rumah Honai', 'Rumah Lamin'],
      correctOptionIndex: 0,
      explanation: 'Rumah Gadang berciri atap Gonjong melengkung seperti tanduk.',
    ),
    QuestionItem(
      id: 'ars_065',
      questionText: 'Rumah adat tradisional suku Toraja di Sulawesi Selatan dengan atap melengkung menyerupai perahu dinamakan:',
      options: ['Rumah Tongkonan', 'Rumah Gadang', 'Rumah Boyang', 'Rumah Souraja'],
      correctOptionIndex: 0,
      explanation: 'Tongkonan memiliki struktur atap perahu melengkung bermotif ukiran khas Toraja.',
    ),
    QuestionItem(
      id: 'ars_066',
      questionText: 'Rumah adat bundar berpuncak jerami tanpa jendela khas suku Dani di Papua dinamakan:',
      options: ['Rumah Honai', 'Rumah Kariwari', 'Rumah Walewangko', 'Rumah Sasak'],
      correctOptionIndex: 0,
      explanation: 'Rumah Honai berbentuk bundar tertutup menahan dingin pegunungan Papua.',
    ),
    QuestionItem(
      id: 'ars_067',
      questionText: 'Gaya arsitektur perpaduan Eropa dan budaya lokal di Indonesia pada abad 19-20 dinamakan arsitektur:',
      options: ['Indische Empire Style / Kolonial Tropis', 'Art Deco', 'Modernis', 'Post-Modern'],
      correctOptionIndex: 0,
      explanation: 'Indische Empire memadukan gaya neoklasik Eropa dengan ventilasi dan teras luas tropis.',
    ),
    QuestionItem(
      id: 'ars_068',
      questionText: 'Gaya arsitektur awal abad ke-20 yang dicirikan dengan geometri melengkung dinamis (seperti Gedung Sate Bandung) dinamakan:',
      options: ['Art Deco', 'Art Nouveau', 'Brutalisme', 'Deconstructivism'],
      correctOptionIndex: 0,
      explanation: 'Art Deco populer di Bandung (Kota Art Deco) dengan bentuk geometris dan garis dekoratif.',
    ),
    QuestionItem(
      id: 'ars_069',
      questionText: 'Gaya arsitektur modern tahun 1950-1970an yang mengekspos permukaan beton mentah telanjang (un-finished concrete) dinamakan:',
      options: ['Brutalisme (Brutalist Architecture)', 'High-Tech', 'Deconstructivism', 'International Style'],
      correctOptionIndex: 0,
      explanation: 'Brutalisme (berasal dari beton ekspos béton brut) menampilkan struktur massa kaku telanjang.',
    ),
    QuestionItem(
      id: 'ars_070',
      questionText: 'Gaya arsitektur yang mendobrak struktur geometris konvensional dengan bentuk patahan distorsi (seperti karya Zaha Hadid) dinamakan:',
      options: ['Dekonstruktivisme (Deconstructivism)', 'Post-Modernism', 'Minimalisme', 'Pop Art'],
      correctOptionIndex: 0,
      explanation: 'Dekonstruktivisme memecah bentuk linier menjadi bentuk fluida dan lengkung non-Euclidean.',
    ),
    QuestionItem(
      id: 'ars_071',
      questionText: 'Arsitek wanita legendaris penerima Pritzker Prize pertama yang terkenal dengan karya fluida futuristik adalah:',
      options: ['Zaha Hadid', 'Kazuyo Sejima', 'Maya Lin', 'Eileen Gray'],
      correctOptionIndex: 0,
      explanation: 'Zaha Hadid julukan "Queen of the Curve" pemenang Pritzker Architecture Prize 2004.',
    ),
    QuestionItem(
      id: 'ars_072',
      questionText: 'Penghargaan tertinggi dunia di bidang arsitektur yang sering disebut setara Nobel Arsitektur dinamakan:',
      options: ['Pritzker Architecture Prize', 'Aga Khan Award', 'AIA Gold Medal', 'RIBA Stirling Prize'],
      correctOptionIndex: 0,
      explanation: 'Pritzker Prize adalah mahkota penghargaan arsitektur tertinggi global.',
    ),
    QuestionItem(
      id: 'ars_073',
      questionText: 'Penghargaan arsitektur internasional khusus untuk karya luar biasa di dunia Islam dinamakan:',
      options: ['Aga Khan Award for Architecture (AKAA)', 'Pritzker Prize', 'Mies van der Rohe Award', 'Praemium Imperiale'],
      correctOptionIndex: 0,
      explanation: 'Aga Khan Award mengapresiasi desain yang merespon komunitas Muslim dan lingkungan.',
    ),
    QuestionItem(
      id: 'ars_074',
      questionText: 'Arsitek Indonesia pemenang Aga Khan Award yang merancang Masjid Raya Sumatera Barat adalah:',
      options: ['Rizal Muslimin / Urbane', 'Y.B. Mangunwijaya', 'Ridwan Kamil', 'Andra Matin'],
      correctOptionIndex: 0,
      explanation: 'Masjid Raya Sumbar dengan bentukan atap gonjong khas dirancang oleh Rizal Muslimin.',
    ),
    QuestionItem(
      id: 'ars_075',
      questionText: 'Arsitek dan tokoh kemanusiaan Indonesia perancang Pemukiman Kali Code Yogyakarta pemenang Aga Khan Award 1992 adalah:',
      options: ['Y.B. Mangunwijaya (Romo Mangun)', 'Friedrich Silaban', 'Han Awal', 'Soejoedi Wirjoatmodjo'],
      correctOptionIndex: 0,
      explanation: 'Romo Mangun merancang penataan humanis Kali Code Yogyakarta.',
    ),
    QuestionItem(
      id: 'ars_076',
      questionText: 'Arsitek Indonesia perancang Masjid Istiqlal Jakarta adalah:',
      options: ['Friedrich Silaban', 'Soejoedi', 'Achmad Noe\'man', 'Soekarno'],
      correctOptionIndex: 0,
      explanation: 'Friedrich Silaban memenangkan sayembara desain Masjid Istiqlal Jakarta.',
    ),
    QuestionItem(
      id: 'ars_077',
      questionText: 'Arsitek perancang Gedung DPR/MPR RI di Senayan Jakarta adalah:',
      options: ['Soejoedi Wirjoatmodjo', 'Friedrich Silaban', 'Han Awal', 'VR van Romondt'],
      correctOptionIndex: 0,
      explanation: 'Soejoedi merancang gedung CONEFO yang kini menjadi Gedung DPR/MPR.',
    ),
    QuestionItem(
      id: 'ars_078',
      questionText: 'Arsitek asal Denmark perancang Sydney Opera House yang ikonik adalah:',
      options: ['Jørn Utzon', 'Eero Saarinen', 'Alvar Aalto', 'Arne Jacobsen'],
      correctOptionIndex: 0,
      explanation: 'Jørn Utzon merancang cangkang kerang Sydney Opera House.',
    ),
    QuestionItem(
      id: 'ars_079',
      questionText: 'Arsitek perancang Museum Louvre Pyramid di Paris asal Amerika-Tiongkok adalah:',
      options: ['I. M. Pei (Ieoh Ming Pei)', 'Kenzo Tange', 'Tadao Ando', 'Shigeru Ban'],
      correctOptionIndex: 0,
      explanation: 'I. M. Pei merancang piramida kaca Louvre yang kontroversial namun ikonik.',
    ),
    QuestionItem(
      id: 'ars_080',
      questionText: 'Arsitek Jepang penerima Pritzker Prize yang terkenal dengan pengolahan beton ekspos dan permainan cahaya alami adalah:',
      options: ['Tadao Ando', 'Kengo Kuma', 'Toyo Ito', 'Arata Isozaki'],
      correctOptionIndex: 0,
      explanation: 'Tadao Ando terkenal dengan karya Church of the Light berarsitektur beton presisi.',
    ),
    QuestionItem(
      id: 'ars_081',
      questionText: 'Gedung tertinggi di dunia saat ini (Burj Khalifa di Dubai, 828 meter) dirancang oleh arsitek:',
      options: ['Adrian Smith (SOM)', 'Norman Foster', 'Santiago Calatrava', 'César Pelli'],
      correctOptionIndex: 0,
      explanation: 'Adrian Smith merancang Burj Khalifa saat di Skidmore, Owings & Merrill (SOM).',
    ),
    QuestionItem(
      id: 'ars_082',
      questionText: 'Menara kembar Petronas Towers di Kuala Lumpur dirancang oleh arsitek:',
      options: ['César Pelli', 'Rem Koolhaas', 'Frank Gehry', 'Renzo Piano'],
      correctOptionIndex: 0,
      explanation: 'César Pelli merancang Petronas Twin Towers bernuansa geometris Islam.',
    ),
    QuestionItem(
      id: 'ars_083',
      questionText: 'Museum Guggenheim Bilbao yang berfasad lekukan logam titanium ikonik dirancang oleh:',
      options: ['Frank Gehry', 'Daniel Libeskind', 'Peter Eisenman', 'Bernard Tschumi'],
      correctOptionIndex: 0,
      explanation: 'Frank Gehry merancang Guggenheim Bilbao bergaya Dekonstruktivisme ekspresif.',
    ),
    QuestionItem(
      id: 'ars_084',
      questionText: 'Konsep penataan landscape taman yang memanfaatkan vegetasi tanaman lokal dinamakan lanskap:',
      options: ['Xeriscaping (Lanskap Hemat Air)', 'Hardscaping', 'Softscaping', 'Streetscaping'],
      correctOptionIndex: 0,
      explanation: 'Xeriscaping merancang taman hemat air menggunakan vegetasi resisten kekeringan.',
    ),
    QuestionItem(
      id: 'ars_085',
      questionText: 'Elemen tak hidup dalam desain lanskap (seperti jalan setapak, bangku, dinding perkerasan) dinamakan:',
      options: ['Hardscape', 'Softscape', 'Waterscape', 'Greenery'],
      correctOptionIndex: 0,
      explanation: 'Hardscape mencakup elemen perkerasan non-tanaman.',
    ),
    QuestionItem(
      id: 'ars_086',
      questionText: 'Elemen tanaman hidup dalam desain lanskap (seperti pohon, semak, rumput, bunga) dinamakan:',
      options: ['Softscape', 'Hardscape', 'Streetscape', 'Paving'],
      correctOptionIndex: 0,
      explanation: 'Softscape mencakup seluruh unsur vegetasi hidup.',
    ),
    QuestionItem(
      id: 'ars_087',
      questionText: 'Ilmu perencanaan ruang kawasan perkotaan yang mengatur zonasi dan transportasi kota dinamakan:',
      options: ['Perencanaan Wilayah dan Kota (PWK / Urban Planning)', 'Arsitektur Interior', 'Manajemen Konstruksi', 'Geodesi'],
      correctOptionIndex: 0,
      explanation: 'Urban Planning mengatur tata guna lahan dan perkembangan infrastruktur kota.',
    ),
    QuestionItem(
      id: 'ars_088',
      questionText: 'Peraturan pemerintah yang membagi kawasan kota menjadi zona perumahan, komersial, dan industri dinamakan:',
      options: ['Zonasi Tata Ruang (RTRW / RDTR)', 'KDB', 'KLB', 'Master Plan'],
      correctOptionIndex: 0,
      explanation: 'Zonasi RDTR menetapkan fungsi penggunaan lahan tiap blok kota.',
    ),
    QuestionItem(
      id: 'ars_089',
      questionText: 'Pencahayaan alami dari langit melalui atap kaca transparan dinamakan:',
      options: ['Skylight', 'Clerestory Window', 'Sun Tunnel', 'Light Well'],
      correctOptionIndex: 0,
      explanation: 'Skylight memasukkan sinar matahari dari atap ke interior.',
    ),
    QuestionItem(
      id: 'ars_090',
      questionText: 'Deretan jendela tinggi tepat di bawah garis atap/plafon untuk memasukkan cahaya alami dinamakan:',
      options: ['Jendela Clerestory (Clerestory Window)', 'Skylight', 'Jendela Bay', 'Juliette Balcony'],
      correctOptionIndex: 0,
      explanation: 'Clerestory memasukkan pencahayaan alami tanpa mengorbankan privasi dinding.',
    ),
    QuestionItem(
      id: 'ars_091',
      questionText: 'Jendela melengkung menonjol keluar dari bidang dinding luar rumah dinamakan:',
      options: ['Bay Window', 'Dormer Window', 'Casement Window', 'Sash Window'],
      correctOptionIndex: 0,
      explanation: 'Bay window memproyeksikan ceruk duduk jendela keluar dinding.',
    ),
    QuestionItem(
      id: 'ars_092',
      questionText: 'Jendela vertikal yang menonjol keluar dari bidang miring atap rumah dinamakan:',
      options: ['Dormer Window (Jendela Loteng)', 'Bay Window', 'Skylight', 'Transom'],
      correctOptionIndex: 0,
      explanation: 'Dormer memberi tambahan ruang kepala dan ventilasi cahaya pada loteng.',
    ),
    QuestionItem(
      id: 'ars_093',
      questionText: 'Elemen ventilasi berengsel di atas kusen pintu utama dinamakan:',
      options: ['Transom (Bovenlicht)', 'Architrave', 'Threshold', 'Sill'],
      correctOptionIndex: 0,
      explanation: 'Transom / Bovenlicht memasukkan pencahayaan dan sirkulasi di atas pintu.',
    ),
    QuestionItem(
      id: 'ars_094',
      questionText: 'Batu kunci berbentuk baji di puncak lengkungan busur batu (arch) yang mengunci struktur dinamakan:',
      options: ['Keystone (Batu Kunci)', 'Voussoir', 'Abutment', 'Impost'],
      correctOptionIndex: 0,
      explanation: 'Keystone adalah elemen mahkota puncak pengunci busur lengkung batu.',
    ),
    QuestionItem(
      id: 'ars_095',
      questionText: 'Pengujian fisik maket miniatur skala bangunan dinamakan:',
      options: ['Maket / Model Arsitektur', 'Render 3D', 'Prototype', 'Sketch'],
      correctOptionIndex: 0,
      explanation: 'Maket memberi pengalaman spasial nyata bentuk 3D fisik.',
    ),
    QuestionItem(
      id: 'ars_096',
      questionText: 'Format file CAD standar pertukaran gambar 2D/3D antar perangkat lunak arsitektur dinamakan:',
      options: ['DWG / DXF', 'PDF', 'PSD', 'OBJ'],
      correctOptionIndex: 0,
      explanation: 'DWG dan DXF adalah format standar industri CAD.',
    ),
    QuestionItem(
      id: 'ars_097',
      questionText: 'Teknologi visualisasi arsitektur yang memungkinkan klien menjelajahi bangunan secara virtual 360 derajat mengandalkan kacamata khusus dinamakan:',
      options: ['VR (Virtual Reality)', 'AR (Augmented Reality)', 'BIM 4D', 'Photogrammetry'],
      correctOptionIndex: 0,
      explanation: 'VR menyajikan simulasi ruang arsitektur immersif.',
    ),
    QuestionItem(
      id: 'ars_098',
      questionText: 'Asosiasi ikatan profesi arsitek resmi di Indonesia dinamakan:',
      options: ['IAI (Ikatan Arsitek Indonesia)', 'IAII', 'HDII', 'IALI'],
      correctOptionIndex: 0,
      explanation: 'IAI adalah organisasi profesi resmi arsitek di Indonesia.',
    ),
    QuestionItem(
      id: 'ars_099',
      questionText: 'Lisensi sertifikat kompetensi resmi yang wajib dimiliki arsitek untuk menandatangani gambar IMB/PBG dinamakan:',
      options: ['STRA (Surat Tanda Registrasi Arsitek)', 'SKA', 'IPTB', 'KTP'],
      correctOptionIndex: 0,
      explanation: 'STRA diterbitkan oleh Dewan Arsitek Indonesia (DAI) sesuai UU Arsitek.',
    ),
    QuestionItem(
      id: 'ars_100',
      questionText: 'Dokumen Izin Mendirikan Bangunan yang kini digantikan dalam regulasi undang-undang Indonesia dinamakan:',
      options: ['PBG (Persetujuan Bangunan Gedung)', 'IMB', 'SLF', 'AMDAL'],
      correctOptionIndex: 0,
      explanation: 'PBG menggantikan IMB sebagai izin resmi teknis konstruksi bangunan gedung.',
    ),
  ];
}
