import '../tes_seleksi_model.dart';

List<QuestionItem> getSistemInformasiQuestions() {
  return const [
    QuestionItem(
      id: 'si_001',
      questionText: 'Komponen utama Sistem Informasi yang menghubungkan manusia, data, dan proses dinamakan:',
      options: ['Teknologi Informasi & Komunikasi', 'Hardware, Software, Data, Prosedur, Manusia', 'Server & Client', 'Database Management System'],
      correctOptionIndex: 1,
      explanation: 'Sistem informasi mencakup komponen teknis dan manusia/prosedur.',
    ),
    QuestionItem(
      id: 'si_002',
      questionText: 'Diagram yang digunakan untuk menggambarkan aliran data dalam suatu sistem informasi adalah:',
      options: ['Use Case Diagram', 'Data Flow Diagram (DFD)', 'Class Diagram', 'ERD'],
      correctOptionIndex: 1,
      explanation: 'DFD menggambarkan aliran data dalam sistem.',
    ),
    QuestionItem(
      id: 'si_003',
      questionText: 'Pemodelan relasi antar entitas beserta atributnya dalam perancangan basis data dinamakan:',
      options: ['Sequence Diagram', 'Entity Relationship Diagram (ERD)', 'Activity Diagram', 'Flowchart'],
      correctOptionIndex: 1,
      explanation: 'ERD memetakan entitas dan relasi basis data.',
    ),
    QuestionItem(
      id: 'si_004',
      questionText: 'Sistem yang mengintegrasikan seluruh proses bisnis inti perusahaan seperti keuangan, SDM, dan logistik adalah:',
      options: ['Customer Relationship Management (CRM)', 'Enterprise Resource Planning (ERP)', 'Supply Chain Management (SCM)', 'Decision Support System (DSS)'],
      correctOptionIndex: 1,
      explanation: 'ERP mengintegrasikan seluruh departemen perusahaan.',
    ),
    QuestionItem(
      id: 'si_005',
      questionText: 'Manakah metodologi pengembangan perangkat lunak yang berfokus pada iterasi cepat dan fleksibilitas?',
      options: ['Waterfall', 'Agile / Scrum', 'V-Model', 'Linear Sequential'],
      correctOptionIndex: 1,
      explanation: 'Agile menekankan iterasi cepat dan respon perubahan.',
    ),
    QuestionItem(
      id: 'si_006',
      questionText: 'Proses mengubah data mentah menjadi informasi yang berguna untuk pengambilan keputusan bisnis disebut:',
      options: ['Data Mining & Business Intelligence', 'Data Backup', 'Data Entry', 'Data Compression'],
      correctOptionIndex: 0,
      explanation: 'Business Intelligence & Data Mining mengolah data jadi wawasan.',
    ),
    QuestionItem(
      id: 'si_007',
      questionText: 'Tingkatan pengguna yang bertugas menjembatani antara kebutuhan bisnis pengguna dengan tim pengembang IT adalah:',
      options: ['System Analyst / Business Analyst', 'Database Administrator', 'Network Engineer', 'Quality Assurance'],
      correctOptionIndex: 0,
      explanation: 'Business Analyst menjembatani kebutuhan bisnis dan solusi IT.',
    ),
    QuestionItem(
      id: 'si_008',
      questionText: 'Istilah "Cloud Computing" mengacu pada pemrosesan dan penyimpanan data melalui:',
      options: ['Harddisk Lokal', 'Jaringan Internet / Server Terdistribusi', 'Flashdisk', 'Kabel LAN tanpa jaringan luar'],
      correctOptionIndex: 1,
      explanation: 'Cloud computing beroperasi di server terdistribusi internet.',
    ),
    QuestionItem(
      id: 'si_009',
      questionText: 'Metrik evaluasi dalam pengujian UI/UX yang mengukur kemudahan pengguna saat memakai aplikasi disebut:',
      options: ['Scalability', 'Usability', 'Maintainability', 'Portability'],
      correctOptionIndex: 1,
      explanation: 'Usability mengukur tingkat kemudahan penggunaan.',
    ),
    QuestionItem(
      id: 'si_010',
      questionText: 'Ancaman keamanan siber yang mengelabui pengguna agar memberikan informasi sensitif melalui email palsu disebut:',
      options: ['DDoS Attack', 'Phishing', 'Ransomware', 'SQL Injection'],
      correctOptionIndex: 1,
      explanation: 'Phishing mengelabui korban untuk mencuri kredensial.',
    ),
    QuestionItem(
      id: 'si_011',
      questionText: 'Sistem yang khusus dirancang untuk mengelola hubungan dan interaksi perusahaan dengan pelanggan dinamakan:',
      options: ['ERP', 'CRM (Customer Relationship Management)', 'SCM', 'KMS'],
      correctOptionIndex: 1,
      explanation: 'CRM mengelola data dan interaksi pelanggan.',
    ),
    QuestionItem(
      id: 'si_012',
      questionText: 'Manakah diagram UML yang menggambarkan interaksi antara aktor eksternal dan sistem?',
      options: ['Use Case Diagram', 'Class Diagram', 'Component Diagram', 'Deployment Diagram'],
      correctOptionIndex: 0,
      explanation: 'Use Case Diagram memodelkan fungsi sistem dari sudut pandang aktor.',
    ),
    QuestionItem(
      id: 'si_013',
      questionText: 'Sistem informasi yang membantu eksekutif puncak mengambil keputusan strategis jangka panjang dinamakan:',
      options: ['Transaction Processing System (TPS)', 'Executive Information System (EIS)', 'Management Information System (MIS)', 'Office Automation System (OAS)'],
      correctOptionIndex: 1,
      explanation: 'EIS menyediakan rangkuman data eksekutif.',
    ),
    QuestionItem(
      id: 'si_014',
      questionText: 'Sistem yang mencatat transaksi harian operasional bisnis seperti kasir toko dinamakan:',
      options: ['TPS (Transaction Processing System)', 'DSS', 'ERP', 'BI'],
      correctOptionIndex: 0,
      explanation: 'TPS memproses transaksi rutin organisasi.',
    ),
    QuestionItem(
      id: 'si_015',
      questionText: 'Kerangka kerja tata kelola teknologi informasi (IT Governance) yang sangat populer di industri adalah:',
      options: ['COBIT', 'TOGAF', 'ITIL', 'PMBOK'],
      correctOptionIndex: 0,
      explanation: 'COBIT adalah standar internasional untuk tata kelola TI.',
    ),
    QuestionItem(
      id: 'si_016',
      questionText: 'Gudang data terpusat yang mengumpulkan data historis dari berbagai sumber operasional dinamakan:',
      options: ['Data Mart', 'Data Warehouse', 'Data Lake', 'Database Relasional'],
      correctOptionIndex: 1,
      explanation: 'Data Warehouse menyimpan data historis lintas departemen.',
    ),
    QuestionItem(
      id: 'si_017',
      questionText: 'Penyimpanan data mentah berukuran sangat besar dalam format aslinya tanpa skema terstruktur dinamakan:',
      options: ['Data Lake', 'Data Warehouse', 'Data Mart', 'OLAP'],
      correctOptionIndex: 0,
      explanation: 'Data Lake menampung data mentah terstruktur & tak terstruktur.',
    ),
    QuestionItem(
      id: 'si_018',
      questionText: 'Analisis pemrosesan analitis secara real-time pada data warehouse dinamakan:',
      options: ['OLTP', 'OLAP (Online Analytical Processing)', 'ETL', 'DBMS'],
      correctOptionIndex: 1,
      explanation: 'OLAP mengeksekusi query analisis kompleks pada data multidimensi.',
    ),
    QuestionItem(
      id: 'si_019',
      questionText: 'Proses mengekstrak, mentransformasi, dan memuat data dari database operasional ke data warehouse dinamakan:',
      options: ['ETL (Extract, Transform, Load)', 'API', 'SQL', 'CRUD'],
      correctOptionIndex: 0,
      explanation: 'ETL adalah rantai pemrosesan data warehouse.',
    ),
    QuestionItem(
      id: 'si_020',
      questionText: 'Pernyataan kelayakan bisnis dan finansial sebelum proyek SI dimulai dinamakan:',
      options: ['Feasibility Study (Studi Kelayakan)', 'System Specification', 'Sprint Planning', 'UAT'],
      correctOptionIndex: 0,
      explanation: 'Studi kelayakan menilai kelayakan operasional, teknis, dan finansial.',
    ),
    QuestionItem(
      id: 'si_021',
      questionText: 'Metrik yang mengukur persentase pengguna yang meninggalkan situs setelah melihat satu halaman saja disebut:',
      options: ['Conversion Rate', 'Bounce Rate', 'Click-Through Rate (CTR)', 'Retention Rate'],
      correctOptionIndex: 1,
      explanation: 'Bounce rate mengukur rasio kunjungan 1 halaman.',
    ),
    QuestionItem(
      id: 'si_022',
      questionText: 'Metrik pemasaran digital yang mengukur rasio jumlah klik terhadap total tayangan iklan adalah:',
      options: ['CTR (Click-Through Rate)', 'CPC', 'CPM', 'ROAS'],
      correctOptionIndex: 0,
      explanation: 'CTR = (Total Klik / Total Impresi) x 100%.',
    ),
    QuestionItem(
      id: 'si_023',
      questionText: 'Fase akhir dalam pengembangan perangkat lunak di mana pengguna akhir menguji fungsionalitas aplikasi dinamakan:',
      options: ['Alpha Testing', 'User Acceptance Testing (UAT)', 'Unit Testing', 'Stress Testing'],
      correctOptionIndex: 1,
      explanation: 'UAT memastikan sistem sesuai harapan bisnis penggunanya.',
    ),
    QuestionItem(
      id: 'si_024',
      questionText: 'Manakah yang BUKAN merupakan 5 V dalam istilah Big Data?',
      options: ['Volume', 'Velocity', 'Variety', 'Vulnerability'],
      correctOptionIndex: 3,
      explanation: '5 V Big Data: Volume, Velocity, Variety, Veracity, Value.',
    ),
    QuestionItem(
      id: 'si_025',
      questionText: 'Prinsip desain antarmuka pengguna yang memastikan elemen mudah dijangkau dan dipahami dinamakan:',
      options: ['UI/UX Design', 'Backend Architecture', 'DevOps', 'Data Mining'],
      correctOptionIndex: 0,
      explanation: 'UI/UX berfokus pada estetika dan pengalaman pengguna.',
    ),
    QuestionItem(
      id: 'si_026',
      questionText: 'Model bisnis di mana aplikasi disediakan sebagai layanan berbasis awan berbiaya langganan dinamakan:',
      options: ['SaaS (Software as a Service)', 'PaaS', 'IaaS', 'On-Premise'],
      correctOptionIndex: 0,
      explanation: 'SaaS menyediakan aplikasi siap pakai lewat cloud.',
    ),
    QuestionItem(
      id: 'si_027',
      questionText: 'Layanan cloud yang menyediakan lingkungan pengembangan seperti server dan runtime bahasa dinamakan:',
      options: ['IaaS', 'PaaS (Platform as a Service)', 'SaaS', 'FaaS'],
      correctOptionIndex: 1,
      explanation: 'PaaS menyediakan platform siap pakai untuk deploy aplikasi.',
    ),
    QuestionItem(
      id: 'si_028',
      questionText: 'Layanan cloud yang menyewakan infrastruktur dasar seperti mesin virtual dan ruang penyimpanan dinamakan:',
      options: ['IaaS (Infrastructure as a Service)', 'PaaS', 'SaaS', 'BaaS'],
      correctOptionIndex: 0,
      explanation: 'IaaS menyewakan VM, storage, dan network dasar.',
    ),
    QuestionItem(
      id: 'si_029',
      questionText: 'Rencana pemulihan operasional IT setelah terjadi bencana alam atau kegagalan sistem dinamakan:',
      options: ['Disaster Recovery Plan (DRP)', 'Business Model Canvas', 'SLA', 'KPI'],
      correctOptionIndex: 0,
      explanation: 'DRP memuat prosedur penanganan bencana sistem IT.',
    ),
    QuestionItem(
      id: 'si_030',
      questionText: 'Perjanjian tingkat layanan antara penyedia jasa IT dengan klien mengenai standar performa dinamakan:',
      options: ['SLA (Service Level Agreement)', 'KPI', 'MOU', 'NDA'],
      correctOptionIndex: 0,
      explanation: 'SLA menjamin uptime dan standar respon layanan.',
    ),
    QuestionItem(
      id: 'si_031',
      questionText: 'Indikator kinerja utama yang digunakan untuk mengukur keberhasilan pencapaian target dinamakan:',
      options: ['KPI (Key Performance Indicator)', 'ROI', 'SWOT', 'OKRs'],
      correctOptionIndex: 0,
      explanation: 'KPI mengukur efektivitas pencapaian target bisnis.',
    ),
    QuestionItem(
      id: 'si_032',
      questionText: 'Kerangka kerja manajerial berbentuk kanvas 9 kotak untuk merancang model bisnis startup dinamakan:',
      options: ['Business Model Canvas (BMC)', 'Swot Analysis', 'Value Chain Analysis', 'Scrum Framework'],
      correctOptionIndex: 0,
      explanation: 'BMC merangkum 9 elemen bisnis kunci.',
    ),
    QuestionItem(
      id: 'si_033',
      questionText: 'Manakah elemen BMC yang menggambarkan bagaimana produk memberikan solusi bernilai bagi pelanggan?',
      options: ['Value Proposition', 'Customer Segments', 'Revenue Streams', 'Key Resources'],
      correctOptionIndex: 0,
      explanation: 'Value Proposition menjelaskan keunggulan dan solusi produk.',
    ),
    QuestionItem(
      id: 'si_034',
      questionText: 'Dalam metodologi Scrum, pertemuan harian berdurasi 15 menit untuk membahas kemajuan tim dinamakan:',
      options: ['Daily Standup / Daily Scrum', 'Sprint Review', 'Sprint Retrospective', 'Backlog Refinement'],
      correctOptionIndex: 0,
      explanation: 'Daily Standup mengecek kemajuan harian tim.',
    ),
    QuestionItem(
      id: 'si_035',
      questionText: 'Daftar prioritas seluruh fitur dan kebutuhan produk yang akan dikembangkan dalam Scrum dinamakan:',
      options: ['Product Backlog', 'Sprint Backlog', 'Roadmap', 'User Story'],
      correctOptionIndex: 0,
      explanation: 'Product backlog menampung daftar prioritas fitur.',
    ),
    QuestionItem(
      id: 'si_036',
      questionText: 'Periode waktu iteratif pendek (biasanya 2-4 minggu) dalam Scrum untuk menyelesaikan sejumlah tugas dinamakan:',
      options: ['Sprint', 'Milestone', 'Phase', 'Release'],
      correctOptionIndex: 0,
      explanation: 'Sprint adalah siklus pengerjaan fitur dalam Scrum.',
    ),
    QuestionItem(
      id: 'si_037',
      questionText: 'Peran dalam tim Scrum yang bertugas memfasilitasi proses dan membuang hambatan kerja tim dinamakan:',
      options: ['Scrum Master', 'Product Owner', 'Project Manager', 'Lead Developer'],
      correctOptionIndex: 0,
      explanation: 'Scrum Master menjaga kelancaran alur Scrum.',
    ),
    QuestionItem(
      id: 'si_038',
      questionText: 'Peran dalam tim Scrum yang mewakili suara bisnis dan bertanggung jawab memprioritaskan Product Backlog adalah:',
      options: ['Product Owner', 'Scrum Master', 'Business Analyst', 'System Architect'],
      correctOptionIndex: 0,
      explanation: 'Product Owner mengelola Product Backlog dan nilai bisnis.',
    ),
    QuestionItem(
      id: 'si_039',
      questionText: 'Diagram yang menggambarkan alur urutan pertukaran pesan antar objek secara kronologis dinamakan:',
      options: ['Sequence Diagram', 'Activity Diagram', 'State Diagram', 'Class Diagram'],
      correctOptionIndex: 0,
      explanation: 'Sequence Diagram menampilkan urutan pesan antar objek seiring waktu.',
    ),
    QuestionItem(
      id: 'si_040',
      questionText: 'Diagram UML yang menggambarkan alur kerja (workflow) atau aktivitas sistem langkah demi langkah dinamakan:',
      options: ['Activity Diagram', 'Sequence Diagram', 'Use Case Diagram', 'Object Diagram'],
      correctOptionIndex: 0,
      explanation: 'Activity diagram memodelkan alur proses bisnis/sistem.',
    ),
    QuestionItem(
      id: 'si_041',
      questionText: 'Konsep dalam basis data yang memastikan hubungan antar tabel tetap konsisten dinamakan:',
      options: ['Integritas Referensial (Referential Integrity)', 'Normalisasi', 'Denormalisasi', 'Indeksasi'],
      correctOptionIndex: 0,
      explanation: 'Integritas referensial menjaga validitas relasi Foreign Key.',
    ),
    QuestionItem(
      id: 'si_042',
      questionText: 'Proses sengaja menggabungkan tabel untuk meningkatkan performa pembacaan query pada data warehouse dinamakan:',
      options: ['Denormalisasi', 'Normalisasi', 'Partisi', 'Replikasi'],
      correctOptionIndex: 0,
      explanation: 'Denormalisasi mengurangi join tabel demi kecepatan query analytical.',
    ),
    QuestionItem(
      id: 'si_043',
      questionText: 'Skema data warehouse yang terdiri dari satu tabel fakta (Fact Table) di pusat dikelilingi tabel dimensi dinamakan:',
      options: ['Star Schema', 'Snowflake Schema', 'Galaxy Schema', 'Relational Schema'],
      correctOptionIndex: 0,
      explanation: 'Star schema berpusat pada tabel fakta tunggal.',
    ),
    QuestionItem(
      id: 'si_044',
      questionText: 'Variasi Star Schema di mana tabel dimensi dinormalisasi lebih lanjut dinamakan:',
      options: ['Snowflake Schema', 'Star Schema', 'Fact Constellation', 'Flat Schema'],
      correctOptionIndex: 0,
      explanation: 'Snowflake schema memecah tabel dimensi secara ter-normalisasi.',
    ),
    QuestionItem(
      id: 'si_045',
      questionText: 'Tabel pusat dalam Data Warehouse yang berisi kuantitas nilai terukur (seperti total penjualan) dinamakan:',
      options: ['Fact Table', 'Dimension Table', 'Lookup Table', 'Summary Table'],
      correctOptionIndex: 0,
      explanation: 'Fact table berisi data kuantitatif dan kunci dimensi.',
    ),
    QuestionItem(
      id: 'si_046',
      questionText: 'Sistem basis data yang memproses transaksi bisnis harian seperti transaksi kartu kredit dinamakan:',
      options: ['OLTP (Online Transaction Processing)', 'OLAP', 'Data Mart', 'ETL'],
      correctOptionIndex: 0,
      explanation: 'OLTP menangani transaksi cepat volume tinggi.',
    ),
    QuestionItem(
      id: 'si_047',
      questionText: 'Singkatan dari operasi dasar manajemen data CRUD adalah:',
      options: ['Create, Read, Update, Delete', 'Copy, Run, Use, Destroy', 'Compile, Restore, Upload, Download', 'Connect, Receive, Use, Disconnect'],
      correctOptionIndex: 0,
      explanation: 'CRUD: Create, Read, Update, Delete.',
    ),
    QuestionItem(
      id: 'si_048',
      questionText: 'Perangkat lunak middleware yang menghubungkan sistem aplikasi berbeda melalui API dinamakan:',
      options: ['Enterprise Service Bus (ESB)', 'Web Server', 'Database Engine', 'Operating System'],
      correctOptionIndex: 0,
      explanation: 'ESB memfasilitasi komunikasi antar aplikasi enterprise.',
    ),
    QuestionItem(
      id: 'si_049',
      questionText: 'Manakah dari berikut ini yang BUKAN merupakan teknik pengumpulan kebutuhan (Requirements Elicitation)?',
      options: ['Wawancara', 'Kuesioner', 'Observasi', 'Code Compiling'],
      correctOptionIndex: 3,
      explanation: 'Code compiling adalah proses teknis bukan elicitation.',
    ),
    QuestionItem(
      id: 'si_050',
      questionText: 'Kebutuhan sistem yang mendefinisikan perilaku spesifik dan fungsi yang harus dilakukan aplikasi dinamakan:',
      options: ['Functional Requirements', 'Non-Functional Requirements', 'Business Constraints', 'Technical Specifications'],
      correctOptionIndex: 0,
      explanation: 'Functional requirement menjelaskan fitur dan aksi sistem.',
    ),
    QuestionItem(
      id: 'si_051',
      questionText: 'Kebutuhan sistem yang mendefinisikan kualitas seperti keamanan, performa, dan ketersediaan dinamakan:',
      options: ['Non-Functional Requirements', 'Functional Requirements', 'User Stories', 'Use Cases'],
      correctOptionIndex: 0,
      explanation: 'Non-functional requirement mengukur performa dan kualitas.',
    ),
    QuestionItem(
      id: 'si_052',
      questionText: 'Dokumen formal yang memuat seluruh spesifikasi kebutuhan sistem secara detail dinamakan:',
      options: ['SRS (Software Requirements Specification)', 'SLA', 'MOU', 'BOM'],
      correctOptionIndex: 0,
      explanation: 'SRS memuat dokumen lengkap persyaratan perangkat lunak.',
    ),
    QuestionItem(
      id: 'si_053',
      questionText: 'Proses pengujian perangkat lunak di mana dua versi aplikasi (A dan B) dibandingkan kinerjanya pada pengguna dinamakan:',
      options: ['A/B Testing', 'Unit Testing', 'Penetration Testing', 'Integration Testing'],
      correctOptionIndex: 0,
      explanation: 'A/B Testing membandingkan konversi 2 varian antarmuka.',
    ),
    QuestionItem(
      id: 'si_054',
      questionText: 'Sketsa kasar beresolusi rendah yang menggambarkan tata letak awal antarmuka aplikasi dinamakan:',
      options: ['Wireframe', 'Mockup', 'Prototype High-Fidelity', 'Final Design'],
      correctOptionIndex: 0,
      explanation: 'Wireframe adalah sketsa struktur awal visual.',
    ),
    QuestionItem(
      id: 'si_055',
      questionText: 'Desain visual beresolusi tinggi yang sudah menyertakan warna, tipografi, dan gaya grafis akhir dinamakan:',
      options: ['Mockup', 'Wireframe', 'Flowchart', 'Sketch'],
      correctOptionIndex: 0,
      explanation: 'Mockup adalah visualisasi statis beresolusi tinggi.',
    ),
    QuestionItem(
      id: 'si_056',
      questionText: 'Model antarmuka interaktif yang dapat diklik pengguna untuk mensimulasikan alur aplikasi dinamakan:',
      options: ['Prototype', 'Wireframe', 'SRS', 'ERD'],
      correctOptionIndex: 0,
      explanation: 'Prototype memberikan simulasi interaksi nyata.',
    ),
    QuestionItem(
      id: 'si_057',
      questionText: 'Prinsip desain visual yang mengatur hierarki ukuran teks dari judul hingga isi dinamakan:',
      options: ['Visual Hierarchy', 'Color Theory', 'Grid System', 'Typography Scale'],
      correctOptionIndex: 0,
      explanation: 'Visual hierarchy mengarahkan fokus mata pengguna.',
    ),
    QuestionItem(
      id: 'si_058',
      questionText: 'Metode riset UX di mana pengguna diminta menyelesaikan tugas sambil menyuarakan pikirannya dinamakan:',
      options: ['Think-Aloud Protocol', 'Card Sorting', 'Heuristic Evaluation', 'A/B Testing'],
      correctOptionIndex: 0,
      explanation: 'Think-Aloud merekam pemikiran pengguna secara langsung.',
    ),
    QuestionItem(
      id: 'si_059',
      questionText: 'Metode evaluasi UX oleh ahli berdasarkan 10 prinsip umum usabilitas dinamakan:',
      options: ['Heuristic Evaluation', 'Usability Testing', 'Focus Group Discussion', 'Survey'],
      correctOptionIndex: 0,
      explanation: 'Heuristic evaluation menggunakan pedoman usabilitas seperti Nielsen.',
    ),
    QuestionItem(
      id: 'si_060',
      questionText: 'Perwakilan karakter fiktif yang dibuat untuk menggambarkan profil pengguna target aplikasi dinamakan:',
      options: ['User Persona', 'Stakeholder', 'Actor', 'End User'],
      correctOptionIndex: 0,
      explanation: 'User Persona memodelkan profil target pengguna.',
    ),
    QuestionItem(
      id: 'si_061',
      questionText: 'Peta yang menggambarkan alur perjalanan pengguna saat berinteraksi dengan sistem dinamakan:',
      options: ['Customer Journey Map', 'Flowchart', 'Mind Map', 'Site Map'],
      correctOptionIndex: 0,
      explanation: 'Customer Journey Map menggambarkan tahapan pengalaman pengguna.',
    ),
    QuestionItem(
      id: 'si_062',
      questionText: 'Skema visual yang menunjukkan susunan hierarki struktur halaman situs web dinamakan:',
      options: ['Sitemap', 'Wireframe', 'ERD', 'UML'],
      correctOptionIndex: 0,
      explanation: 'Sitemap memetakan struktur navigasi halaman.',
    ),
    QuestionItem(
      id: 'si_063',
      questionText: 'Metode pengorganisasian menu informasi dengan meminta pengguna mengelompokkan kartu topik dinamakan:',
      options: ['Card Sorting', 'Tree Testing', 'A/B Testing', 'Affinity Diagram'],
      correctOptionIndex: 0,
      explanation: 'Card sorting membantu merancang arsitektur informasi.',
    ),
    QuestionItem(
      id: 'si_064',
      questionText: 'Ukuran rasio dari pengunjung yang melakukan aksi yang diinginkan (seperti membeli barang) dinamakan:',
      options: ['Conversion Rate', 'Bounce Rate', 'Click Rate', 'Churn Rate'],
      correctOptionIndex: 0,
      explanation: 'Conversion Rate mengukur tingkat keberhasilan transaksi sasaran.',
    ),
    QuestionItem(
      id: 'si_065',
      questionText: 'Persentase pelanggan yang berhenti berlangganan atau menggunakan layanan dalam periode tertentu dinamakan:',
      options: ['Churn Rate', 'Retention Rate', 'Bounce Rate', 'Exit Rate'],
      correctOptionIndex: 0,
      explanation: 'Churn rate mengukur tingkat kehilangan pelanggan.',
    ),
    QuestionItem(
      id: 'si_066',
      questionText: 'Estimasi total keuntungan yang dihasilkan oleh satu pelanggan sepanjang hubungannya dengan bisnis dinamakan:',
      options: ['Customer Lifetime Value (CLV)', 'Customer Acquisition Cost (CAC)', 'ROI', 'NPS'],
      correctOptionIndex: 0,
      explanation: 'CLV menghitung nilai proyeksi proyeksi finansial pelanggan.',
    ),
    QuestionItem(
      id: 'si_067',
      questionText: 'Total biaya yang dikeluarkan perusahaan untuk mendapatkan satu pelanggan baru dinamakan:',
      options: ['Customer Acquisition Cost (CAC)', 'CLV', 'OPEX', 'CAPEX'],
      correctOptionIndex: 0,
      explanation: 'CAC menghitung biaya akumulasi akuisisi pelanggan.',
    ),
    QuestionItem(
      id: 'si_068',
      questionText: 'Survei kepuasan pelanggan yang mengukur sejauh mana pengguna merekomendasikan produk dinamakan:',
      options: ['Net Promoter Score (NPS)', 'CSAT', 'CES', 'KPI'],
      correctOptionIndex: 0,
      explanation: 'NPS mengukur loyalitas pelanggan dari skala 0-10.',
    ),
    QuestionItem(
      id: 'si_069',
      questionText: 'Pengeluaran modal untuk investasi aset jangka panjang seperti pembelian server dinamakan:',
      options: ['CAPEX (Capital Expenditure)', 'OPEX', 'COGS', 'EBITDA'],
      correctOptionIndex: 0,
      explanation: 'CAPEX adalah pengeluaran modal aset tetap.',
    ),
    QuestionItem(
      id: 'si_070',
      questionText: 'Biaya operasional sehari-hari yang dikeluarkan untuk menjalankan sistem dinamakan:',
      options: ['OPEX (Operational Expenditure)', 'CAPEX', 'ROI', 'NPV'],
      correctOptionIndex: 0,
      explanation: 'OPEX adalah biaya rutin operasional harian.',
    ),
    QuestionItem(
      id: 'si_071',
      questionText: 'Teknik analitik data yang memprediksi tren masa depan berdasarkan pola data historis dinamakan:',
      options: ['Predictive Analytics', 'Descriptive Analytics', 'Prescriptive Analytics', 'Diagnostic Analytics'],
      correctOptionIndex: 0,
      explanation: 'Predictive Analytics meramalkan tren masa depan.',
    ),
    QuestionItem(
      id: 'si_072',
      questionText: 'Teknik analitik data yang memberikan rekomendasi tindakan optimal yang harus diambil dinamakan:',
      options: ['Prescriptive Analytics', 'Predictive Analytics', 'Descriptive Analytics', 'Diagnostic Analytics'],
      correctOptionIndex: 0,
      explanation: 'Prescriptive Analytics memberi arahan tindakan solusi terbaik.',
    ),
    QuestionItem(
      id: 'si_073',
      questionText: 'Teknik analitik data yang menjelaskan apa yang terjadi di masa lalu melalui laporan dan grafik dinamakan:',
      options: ['Descriptive Analytics', 'Predictive Analytics', 'Prescriptive Analytics', 'Real-Time Analytics'],
      correctOptionIndex: 0,
      explanation: 'Descriptive Analytics merangkum performa historis.',
    ),
    QuestionItem(
      id: 'si_074',
      questionText: 'Teknik analitik data yang menyelidiki alasan mengapa suatu peristiwa atau anomali terjadi dinamakan:',
      options: ['Diagnostic Analytics', 'Descriptive Analytics', 'Predictive Analytics', 'Prescriptive Analytics'],
      correctOptionIndex: 0,
      explanation: 'Diagnostic Analytics mencari sebab timbulnya masalah.',
    ),
    QuestionItem(
      id: 'si_075',
      questionText: 'Praktek mengoptimalkan struktur dan konten situs web agar muncul di halaman utama mesin pencari dinamakan:',
      options: ['SEO (Search Engine Optimization)', 'SEM', 'Social Media Ads', 'Email Marketing'],
      correctOptionIndex: 0,
      explanation: 'SEO meningkatkan peringkat pencarian organik.',
    ),
    QuestionItem(
      id: 'si_076',
      questionText: 'Bentuk pemasaran internet yang melibatkan promosi situs melalui iklan berbayar di mesin pencari dinamakan:',
      options: ['SEM (Search Engine Marketing)', 'SEO', 'Content Marketing', 'Affiliate Marketing'],
      correctOptionIndex: 0,
      explanation: 'SEM memanfaatkan iklan berbayar seperti Google Ads.',
    ),
    QuestionItem(
      id: 'si_077',
      questionText: 'Model komputasi di mana sumber daya IT disesuaikan secara otomatis naik/turun sesuai beban dinamakan:',
      options: ['Auto-Scaling', 'Load Balancing', 'Redundancy', 'High Availability'],
      correctOptionIndex: 0,
      explanation: 'Auto-scaling menambah/mengurangi instansi server secara dinamis.',
    ),
    QuestionItem(
      id: 'si_078',
      questionText: 'Teknik membagi beban lalu lintas jaringan ke beberapa server backend dinamakan:',
      options: ['Load Balancing', 'Auto-Scaling', 'DNS Routing', 'Port Forwarding'],
      correctOptionIndex: 0,
      explanation: 'Load balancer membagi trafik agar server tidak over kapasitas.',
    ),
    QuestionItem(
      id: 'si_079',
      questionText: 'Ketersediaan sistem tinggi yang dirancang tanpa titik kegagalan tunggal (Single Point of Failure) dinamakan:',
      options: ['High Availability (HA)', 'Fault Tolerance', 'Disaster Recovery', 'Backup'],
      correctOptionIndex: 0,
      explanation: 'HA menjamin persentase uptime tinggi (seperti 99.99%).',
    ),
    QuestionItem(
      id: 'si_080',
      questionText: 'Tingkat pengembalian investasi yang dihitung dari persentase keuntungan terhadap biaya modal dinamakan:',
      options: ['ROI (Return on Investment)', 'ROE', 'ROA', 'NPV'],
      correctOptionIndex: 0,
      explanation: 'ROI mengukur efisiensi pengembalian investasi finansial.',
    ),
    QuestionItem(
      id: 'si_081',
      questionText: 'Metode penilaian investasi yang menghitung selisih nilai arus kas masuk bersih dengan modal awal saat ini dinamakan:',
      options: ['NPV (Net Present Value)', 'IRR', 'Payback Period', 'BEP'],
      correctOptionIndex: 0,
      explanation: 'NPV menghitung arus kas dengan mempertimbangkan nilai waktu uang.',
    ),
    QuestionItem(
      id: 'si_082',
      questionText: 'Waktu yang dibutuhkan oleh suatu proyek untuk mengembalikan total biaya investasi awal dinamakan:',
      options: ['Payback Period', 'ROI', 'NPV', 'IRR'],
      correctOptionIndex: 0,
      explanation: 'Payback period menghitung lama waktu pemulihan modal.',
    ),
    QuestionItem(
      id: 'si_083',
      questionText: 'Undang-undang yang mengatur transaksi elektronik dan informasi digital di Indonesia adalah:',
      options: ['UU ITE', 'UU KIP', 'UU Ketenagakerjaan', 'UU Hak Cipta'],
      correctOptionIndex: 0,
      explanation: 'UU ITE mengatur Informasi dan Transaksi Elektronik.',
    ),
    QuestionItem(
      id: 'si_084',
      questionText: 'Regulasi perlindungan data pribadi konsumen yang berlaku di Uni Eropa dan menjadi acuan global dinamakan:',
      options: ['GDPR (General Data Protection Regulation)', 'HIPAA', 'PCI-DSS', 'ISO 27001'],
      correctOptionIndex: 0,
      explanation: 'GDPR menetapkan kerangka privasi data ketat.',
    ),
    QuestionItem(
      id: 'si_085',
      questionText: 'Standar keamanan internasional untuk sistem manajemen keamanan informasi dinamakan:',
      options: ['ISO 27001', 'ISO 9001', 'ISO 14001', 'ISO 20000'],
      correctOptionIndex: 0,
      explanation: 'ISO/IEC 27001 mengatur standar ISMS (Information Security Management System).',
    ),
    QuestionItem(
      id: 'si_086',
      questionText: 'Prinsip keamanan informasi CIA Triad mencakup:',
      options: ['Confidentiality, Integrity, Availability', 'Control, Inspection, Audit', 'Cyber, Internet, Authentication', 'Cryptographic, Identity, Access'],
      correctOptionIndex: 0,
      explanation: 'CIA Triad: Kerahasiaan, Keutuhan, dan Ketersediaan Data.',
    ),
    QuestionItem(
      id: 'si_087',
      questionText: 'Mekanisme verifikasi identitas pengguna menggunakan dua faktor (seperti kata sandi dan kode OTP) dinamakan:',
      options: ['Two-Factor Authentication (2FA)', 'SSO', 'Biometric', 'Tokenization'],
      correctOptionIndex: 0,
      explanation: '2FA menambahkan lapisan keamanan verifikasi ganda.',
    ),
    QuestionItem(
      id: 'si_088',
      questionText: 'Fasilitas masuk sekali (Single Sign-On) memungkinkan pengguna:',
      options: ['Masuk ke banyak aplikasi menggunakan satu set kredensial tunggal', 'Mengubah kata sandi secara otomatis', 'Mengunci akun dari serangan', 'Menghapus histori log'],
      correctOptionIndex: 0,
      explanation: 'SSO memberi akses ke multiple sistem dengan 1 kali login.',
    ),
    QuestionItem(
      id: 'si_089',
      questionText: 'Metode pengorganisasian data dalam tabel relasional tanpa adanya pengulangan kolom yang sama dinamakan:',
      options: ['First Normal Form (1NF)', '2NF', '3NF', 'BCNF'],
      correctOptionIndex: 0,
      explanation: '1NF menghilangkan atribut bernilai banyak (atomic value).',
    ),
    QuestionItem(
      id: 'si_090',
      questionText: 'Aturan 2NF terpenuhi apabila tabel sudah 1NF dan seluruh atribut non-kunci bergantung penuh pada:',
      options: ['Primary Key', 'Foreign Key', 'Candidate Key', 'Super Key'],
      correctOptionIndex: 0,
      explanation: '2NF menghilangkan ketergantungan parsial dari Primary Key.',
    ),
    QuestionItem(
      id: 'si_091',
      questionText: 'Aturan 3NF terpenuhi apabila tabel sudah 2NF dan tidak memiliki ketergantungan:',
      options: ['Transitif (Transitive Dependency)', 'Parsial', 'Fungsional', 'Multivalue'],
      correctOptionIndex: 0,
      explanation: '3NF menghilangkan ketergantungan transitif antar atribut non-kunci.',
    ),
    QuestionItem(
      id: 'si_092',
      questionText: 'Manakah bentuk diagram UML yang menggambarkan hubungan statis antar kelas dan objek dalam sistem?',
      options: ['Class Diagram', 'Object Diagram', 'Component Diagram', 'Package Diagram'],
      correctOptionIndex: 0,
      explanation: 'Class Diagram memodelkan struktur statis kelas dan relasinya.',
    ),
    QuestionItem(
      id: 'si_093',
      questionText: 'Simbol panah dengan ujung segitiga kosong pada Class Diagram menandakan hubungan:',
      options: ['Generalisasi / Pewarisan (Inheritance)', 'Asosiasi', 'Komposisi', 'Agregasi'],
      correctOptionIndex: 0,
      explanation: 'Panah segitiga kosong menunjukkan pewarisan (Generalization).',
    ),
    QuestionItem(
      id: 'si_094',
      questionText: 'Hubungan kepemilikan kuat pada Class Diagram di mana jika induk dihapus maka anak ikut terhapus dinamakan:',
      options: ['Komposisi (Composition)', 'Agregasi', 'Asosiasi', 'Dependensi'],
      correctOptionIndex: 0,
      explanation: 'Komposisi mengindikasikan hubungan bagian-keseluruhan yang ketat.',
    ),
    QuestionItem(
      id: 'si_095',
      questionText: 'Hubungan kepemilikan lemah pada Class Diagram di mana anak tetap hidup meski induk dihapus dinamakan:',
      options: ['Agregasi (Aggregation)', 'Komposisi', 'Generalisasi', 'Realisasi'],
      correctOptionIndex: 0,
      explanation: 'Agregasi adalah hubungan part-of yang lebih longgar.',
    ),
    QuestionItem(
      id: 'si_096',
      questionText: 'Pendekatan pengembangan sistem di mana prototipe cepat dibuat dan direvisi berulang kali dinamakan:',
      options: ['RAD (Rapid Application Development)', 'Waterfall', 'V-Model', 'Spiral'],
      correctOptionIndex: 0,
      explanation: 'RAD menekankan pembuatan prototipe cepat berbasis umpan balik.',
    ),
    QuestionItem(
      id: 'si_097',
      questionText: 'Model pengembangan sistem berbasis manajemen risiko berulang dinamakan:',
      options: ['Spiral Model', 'Waterfall', 'RAD', 'Agile'],
      correctOptionIndex: 0,
      explanation: 'Spiral model menggabungkan aspek iteratif dengan analisis risiko.',
    ),
    QuestionItem(
      id: 'si_098',
      questionText: 'Pendekatan integrasi berkelanjutan dan pengiriman otomatis dalam pengembangan IT dinamakan:',
      options: ['CI/CD (Continuous Integration / Continuous Deployment)', 'DevOps', 'Agile', 'Scrum'],
      correctOptionIndex: 0,
      explanation: 'CI/CD mengotomatiskan pengujian dan pendeplotan kode.',
    ),
    QuestionItem(
      id: 'si_099',
      questionText: 'Budaya kerja yang menyatukan tim pengembang (Dev) dan tim operasional IT (Ops) dinamakan:',
      options: ['DevOps', 'Agile', 'ITIL', 'Scrum'],
      correctOptionIndex: 0,
      explanation: 'DevOps menyatukan alur kerja pengembangan dan operasional.',
    ),
    QuestionItem(
      id: 'si_100',
      questionText: 'Model konseptual yang menggambarkan seluruh siklus hidup pengembangan sistem dari awal hingga pensiun dinamakan:',
      options: ['SDLC (System Development Life Cycle)', 'PLC', 'ALM', 'ITIL'],
      correctOptionIndex: 0,
      explanation: 'SDLC mencakup fase perencanaan, analisis, desain, implementasi, hingga pemeliharaan.',
    ),
  ];
}
