import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraJepangQuestions() {
  return const [
    QuestionItem(
      id: 'sas_jep_001',
      questionText: 'Sastra Jepang (#1): Karya prosa klasik Jepang tertua yang masih ada hingga kini adalah:',
      options: ['Kojiki (Catatan Hal-Hal Kuno)', 'Nihon Shoki (Sejarah Jepang)', 'Fudoki (Catatan Wilayah)', 'Manyoshu (Kumpulan Daun)'],
      correctOptionIndex: 0,
      explanation: 'Kojiki diselesaikan pada tahun 712 M, merupakan catatan mitologi dan sejarah tertua Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_002',
      questionText: 'Sastra Jepang (#2): Kumpulan puisi tertua di Jepang, berisi sekitar 4.500 puisi dalam berbagai bentuk, dinamakan:',
      options: ['Kokinshu', 'Manyoshu', 'Shinkokinshu', 'Hyakunin Isshu'],
      correctOptionIndex: 1,
      explanation: 'Manyoshu (Manyoshu) disusun pada abad ke-8, berisi puisi rakyat hingga istana.',
    ),
    QuestionItem(
      id: 'sas_jep_003',
      questionText: 'Sastra Jepang (#3): Penulis Genji Monogatari (Kisah Genji), novel psikologis pertama di dunia, adalah:',
      options: ['Murasaki Shikibu', 'Sei Shonagon', 'Ono no Komachi', 'Izumi Shikibu'],
      correctOptionIndex: 0,
      explanation: 'Murasaki Shikibu, seorang bangsawan istana Heian, menulis Genji sekitar tahun 1008 M.',
    ),
    QuestionItem(
      id: 'sas_jep_004',
      questionText: 'Sastra Jepang (#4): Tokoh utama dalam Genji Monogatari adalah:',
      options: ['Hikaru Genji', 'Yugiri', 'Kaoru', 'Nioi'],
      correctOptionIndex: 0,
      explanation: 'Hikaru Genji adalah putra kekaisaran yang menjadi pusat kisah cinta dan intrik istana.',
    ),
    QuestionItem(
      id: 'sas_jep_005',
      questionText: 'Sastra Jepang (#5): Buku catatan harian dan esai yang ditulis oleh Sei Shonagon pada era Heian berjudul:',
      options: ['Makura no Soshi (Buku Bantal)', 'Tsurezuregusa', 'Hojoki', 'Kagero Nikki'],
      correctOptionIndex: 0,
      explanation: 'Makura no Soshi adalah kumpulan esai, daftar, dan anekdot yang sangat berpengaruh dalam sastra Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_006',
      questionText: 'Sastra Jepang (#6): Karya klasik Jepang berupa kumpulan kisah perang klan Taira dan Minamoto pada abad ke-12 adalah:',
      options: ['Heike Monogatari (Kisah Heike)', 'Taiheiki', 'Soga Monogatari', 'Gikeiki'],
      correctOptionIndex: 0,
      explanation: 'Heike Monogatari mengisahkan kejatuhan klan Taira dan lahirnya pemerintahan samurai Kamakura.',
    ),
    QuestionItem(
      id: 'sas_jep_007',
      questionText: 'Sastra Jepang (#7): Puisi pendek Jepang yang terdiri dari 5-7-5-7-7 suku kata (31 mora) disebut:',
      options: ['Tanka', 'Haiku', 'Renga', 'Senryu'],
      correctOptionIndex: 0,
      explanation: 'Tanka adalah bentuk puisi tradisional dengan 31 mora, sering digunakan dalam Manyoshu dan Kokinshu.',
    ),
    QuestionItem(
      id: 'sas_jep_008',
      questionText: 'Sastra Jepang (#8): Bentuk puisi Jepang berpola 5-7-5 suku kata yang menyertakan kata musim (kigo) adalah:',
      options: ['Haiku', 'Tanka', 'Renga', 'Choka'],
      correctOptionIndex: 0,
      explanation: 'Haiku berkembang dari renga, dipopulerkan oleh Matsuo Basho pada abad ke-17.',
    ),
    QuestionItem(
      id: 'sas_jep_009',
      questionText: 'Sastra Jepang (#9): Tokoh haiku terbesar Jepang yang menulis puisi Furu ike ya (Kolam Tua) adalah:',
      options: ['Matsuo Basho', 'Yosa Buson', 'Kobayashi Issa', 'Masaoka Shiki'],
      correctOptionIndex: 0,
      explanation: 'Basho (1644-1694) adalah maestro haiku; puisinya tentang katak melompat ke kolam tua sangat ikonik.',
    ),
    QuestionItem(
      id: 'sas_jep_010',
      questionText: 'Sastra Jepang (#10): Penyair haiku yang terkenal dengan gaya sederhana dan penuh kasih pada makhluk kecil adalah:',
      options: ['Kobayashi Issa', 'Matsuo Basho', 'Yosa Buson', 'Taneda Santoka'],
      correctOptionIndex: 0,
      explanation: 'Issa (1763-1828) dikenal dengan haiku yang menggambarkan kehidupan sehari-hari dari sudut pandang rendah hati.',
    ),
    QuestionItem(
      id: 'sas_jep_011',
      questionText: 'Sastra Jepang (#11): Sastrawan Jepang modern pengarang novel Kokoro dan Botchan adalah:',
      options: ['Natsume Soseki', 'Mori Ogai', 'Ryunosuke Akutagawa', 'Yukio Mishima'],
      correctOptionIndex: 0,
      explanation: 'Soseki (1867-1916) adalah perintis novel psikologis modern di Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_012',
      questionText: 'Sastra Jepang (#12): Novel Kokoro karya Natsume Soseki mengisahkan hubungan antara:',
      options: ['Seorang mahasiswa dan seorang guru (Sensei)', 'Dua samurai dalam perang saudara', 'Seorang geisha dan pedagang', 'Pasangan suami-istri era Meiji'],
      correctOptionIndex: 0,
      explanation: 'Kokoro (1914) mengupas tema kesepian, persahabatan, dan pengkhianatan melalui narasi Sensei dan muridnya.',
    ),
    QuestionItem(
      id: 'sas_jep_013',
      questionText: 'Sastra Jepang (#13): Cerita pendek Rashomon dan Yabu no Naka karya sastrawan Jepang terkenal adalah karya:',
      options: ['Ryunosuke Akutagawa', 'Natsume Soseki', 'Osamu Dazai', 'Yasunari Kawabata'],
      correctOptionIndex: 0,
      explanation: 'Akutagawa (1892-1927) adalah maestro cerpen; Rashomon dan Yabu no Naka menginspirasi film Rashomon.',
    ),
    QuestionItem(
      id: 'sas_jep_014',
      questionText: 'Sastra Jepang (#14): Novel Sasaneyuki (The Makioka Sisters) karya Junichiro Tanizaki menggambarkan:',
      options: ['Kehidupan empat saudari di Osaka menjelang Perang Dunia II', 'Persaingan dua klan di Kyoto', 'Petualangan seorang ninja', 'Kisah cinta era Edo'],
      correctOptionIndex: 0,
      explanation: 'Tanizaki menulis Sasaneyuki (1943-1948) sebagai potret keluarga Jepang tradisional yang mulai pudar.',
    ),
    QuestionItem(
      id: 'sas_jep_015',
      questionText: 'Sastra Jepang (#15): Novel Yukiguni (Snow Country) karya Yasunari Kawabata berlatar di:',
      options: ['Pegunungan bersalju di Niigata', 'Pulau Okinawa', 'Kota Hiroshima', 'Hutan bambu Kyoto'],
      correctOptionIndex: 0,
      explanation: 'Yukiguni (Snow Country) (1935-1937) adalah kisah cinta antara geisha dan pebisnis di kawasan salju Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_016',
      questionText: 'Sastra Jepang (#16): Sastrawan Jepang peraih Hadiah Nobel Sastra pada tahun 1968 adalah:',
      options: ['Yasunari Kawabata', 'Yukio Mishima', 'Kenzaburo Oe', 'Haruki Murakami'],
      correctOptionIndex: 0,
      explanation: 'Kawabata menerima Nobel Sastra pada 1968 atas kepekaan estetikanya dalam prosa.',
    ),
    QuestionItem(
      id: 'sas_jep_017',
      questionText: 'Sastra Jepang (#17): Novel Ningen Shikkaku (No Longer Human) yang mengisahkan alienasi tokoh Yozo adalah karya:',
      options: ['Osamu Dazai', 'Ango Sakaguchi', 'Yukio Mishima', 'Kobo Abe'],
      correctOptionIndex: 0,
      explanation: 'Dazai (1909-1948) menulis Ningen Shikkaku, sebuah karya semi-autobiografi tentang perasaan alienasi.',
    ),
    QuestionItem(
      id: 'sas_jep_018',
      questionText: 'Sastra Jepang (#18): Novel Kamen no Kokuhaku (Confessions of a Mask) karya Yukio Mishima mengupas tema:',
      options: ['Identitas seksual dan krisis eksistensial', 'Perang samurai abad ke-17', 'Revolusi industri Jepang', 'Budaya pop Jepang'],
      correctOptionIndex: 0,
      explanation: 'Mishima (1925-1970) menulis novel tersebut pada 1949, mengungkapkan perjuangan batin tokoh utamanya.',
    ),
    QuestionItem(
      id: 'sas_jep_019',
      questionText: 'Sastra Jepang (#19): Sastrawan Jepang pengarang novel Suna no Onna (The Woman in the Dunes) adalah:',
      options: ['Kobo Abe', 'Yukio Mishima', 'Kenzaburo Oe', 'Shusaku Endo'],
      correctOptionIndex: 0,
      explanation: 'Abe (1924-1993) adalah eksponen sastra absurd; Suna no Onna (1962) diadaptasi menjadi film terkenal.',
    ),
    QuestionItem(
      id: 'sas_jep_020',
      questionText: 'Sastra Jepang (#20): Novel Chinmoku (Silence) karya Shusaku Endo mengisahkan:',
      options: ['Penganiayaan umat Kristen di Jepang abad ke-17', 'Kehidupan Buddha Zen', 'Perang Pasifik', 'Budaya geisha di Kyoto'],
      correctOptionIndex: 0,
      explanation: 'Endo (1923-1996) mengeksplorasi iman dan penderitaan dalam konteks sejarah kristenisasi Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_021',
      questionText: 'Sastra Jepang (#21): Penulis Norwegian Wood dan Kafka on the Shore yang sangat populer di dunia adalah:',
      options: ['Haruki Murakami', 'Banana Yoshimoto', 'Hiromi Kawakami', 'Mieko Kawakami'],
      correctOptionIndex: 0,
      explanation: 'Murakami (lahir 1949) adalah novelis kontemporer yang karyanya diterjemahkan ke puluhan bahasa.',
    ),
    QuestionItem(
      id: 'sas_jep_022',
      questionText: 'Sastra Jepang (#22): Novel Kitchen karya Banana Yoshimoto mengangkat tema:',
      options: ['Duka, keluarga, dan dapur sebagai ruang intim', 'Petualangan waktu di Tokyo', 'Kisah cinta koki dan pelanggan', 'Budaya kuliner Jepang'],
      correctOptionIndex: 0,
      explanation: 'Kitchen (1988) adalah novel pendek yang menyentuh kehilangan dan pembaharuan hubungan keluarga.',
    ),
    QuestionItem(
      id: 'sas_jep_023',
      questionText: 'Sastra Jepang (#23): Aksara Jepang yang berasal dari karakter Cina untuk kata benda dan akar kata kerja adalah:',
      options: ['Kanji', 'Hiragana', 'Katakana', 'Romaji'],
      correctOptionIndex: 0,
      explanation: 'Kanji adalah logogram yang diimpor dari Cina dan merupakan bagian inti sistem tulisan Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_024',
      questionText: 'Sastra Jepang (#24): Sistem penulisan Jepang yang digunakan untuk kata serapan asing dan onomatope adalah:',
      options: ['Katakana', 'Hiragana', 'Kanji', 'Furigana'],
      correctOptionIndex: 0,
      explanation: 'Katakana sering dipakai untuk menulis kata serapan seperti kompyuta (komputer).',
    ),
    QuestionItem(
      id: 'sas_jep_025',
      questionText: 'Sastra Jepang (#25): Hiragana terutama digunakan untuk:',
      options: ['Menulis partikel gramatikal dan okurigana', 'Menulis nama orang asing', 'Menulis istilah sains', 'Menulis teks arsitektur'],
      correctOptionIndex: 0,
      explanation: 'Hiragana berfungsi untuk menunjukkan fungsi gramatikal dan melengkapi bacaan kanji.',
    ),
    QuestionItem(
      id: 'sas_jep_026',
      questionText: 'Sastra Jepang (#26): Tingkat bahasa hormat dalam bahasa Jepang yang digunakan kepada orang berstatus lebih tinggi disebut:',
      options: ['Keigo', 'Sonkeigo', 'Kenjougo', 'Teineigo'],
      correctOptionIndex: 0,
      explanation: 'Keigo adalah sistem kesopanan yang meliputi Sonkeigo, Kenjougo, dan Teineigo.',
    ),
    QuestionItem(
      id: 'sas_jep_027',
      questionText: 'Sastra Jepang (#27): Bentuk bahasa Jepang untuk merendahkan diri sendiri demi menghormati lawan bicara dinamakan:',
      options: ['Kenjougo', 'Sonkeigo', 'Teineigo', 'Kudaketa'],
      correctOptionIndex: 0,
      explanation: 'Kenjougo adalah ungkapan merendah seperti mousu (mengatakan) dan itadaku (menerima).',
    ),
    QuestionItem(
      id: 'sas_jep_028',
      questionText: 'Sastra Jepang (#28): Contoh Sonkeigo yang benar untuk kata kerja iku (pergi) adalah:',
      options: ['Irassharu', 'Mairu', 'Ikimasu', 'Oide ni naru'],
      correctOptionIndex: 0,
      explanation: 'Irassharu adalah bentuk hormat dari pergi/datang/berada.',
    ),
    QuestionItem(
      id: 'sas_jep_029',
      questionText: 'Sastra Jepang (#29): Bentuk sopan standar desu/masu termasuk dalam kategori:',
      options: ['Teineigo', 'Sonkeigo', 'Kenjougo', 'Keigo'],
      correctOptionIndex: 0,
      explanation: 'Teineigo adalah bahasa sopan yang umum digunakan dalam percakapan sehari-hari.',
    ),
    QuestionItem(
      id: 'sas_jep_030',
      questionText: 'Sastra Jepang (#30): Kata sakura (bunga sakura) dalam puisi klasik sering digunakan sebagai:',
      options: ['Kigo (kata musim semi)', 'Emosi cinta', 'Simbol kematian', 'Nama tempat'],
      correctOptionIndex: 0,
      explanation: 'Sakura adalah kigo yang melambangkan musim semi dan ketidakkekalan dalam haiku.',
    ),
    QuestionItem(
      id: 'sas_jep_031',
      questionText: 'Sastra Jepang (#31): Pengarang Tsurezuregusa (Coretan Waktu Senggang) tentang kehidupan dan estetika adalah:',
      options: ['Yoshida Kenko', 'Kamo no Chomei', 'Matsuo Basho', 'Saigyo'],
      correctOptionIndex: 0,
      explanation: 'Kenko (1283-1350) menulis Tsurezuregusa yang penuh dengan makna Zen.',
    ),
    QuestionItem(
      id: 'sas_jep_032',
      questionText: 'Sastra Jepang (#32): Hojoki (Catatan dari Gubuk) karya Kamo no Chomei mengisahkan:',
      options: ['Kehidupan pertapa setelah mengalami bencana alam dan kesusahan', 'Perjalanan ke kuil', 'Kehidupan di istana', 'Perang Taira dan Minamoto'],
      correctOptionIndex: 0,
      explanation: 'Chomei (1155-1216) menulis tentang kesederhanaan dan kefanaan dunia.',
    ),
    QuestionItem(
      id: 'sas_jep_033',
      questionText: 'Sastra Jepang (#33): Drama tradisional Jepang dari abad ke-14 yang menggabungkan tari, musik, dan topeng disebut:',
      options: ['Noh', 'Kabuki', 'Bunraku', 'Kyogen'],
      correctOptionIndex: 0,
      explanation: 'Noh dikembangkan oleh Zeami Motokiyo dan sering menampilkan cerita mitologis.',
    ),
    QuestionItem(
      id: 'sas_jep_034',
      questionText: 'Sastra Jepang (#34): Teater tradisional Jepang yang penuh warna dengan aktor laki-laki memainkan semua peran adalah:',
      options: ['Kabuki', 'Noh', 'Bunraku', 'Rakugo'],
      correctOptionIndex: 0,
      explanation: 'Kabuki dimulai pada awal abad ke-17 dan terkenal dengan kostum mewah.',
    ),
    QuestionItem(
      id: 'sas_jep_035',
      questionText: 'Sastra Jepang (#35): Teater boneka tradisional Jepang yang dimainkan dengan tiga dalang disebut:',
      options: ['Bunraku', 'Ningyo joruri', 'Kamishibai', 'Karakuri'],
      correctOptionIndex: 0,
      explanation: 'Bunraku adalah seni boneka tradisional Jepang yang dipentaskan bersama narasi joruri.',
    ),
    QuestionItem(
      id: 'sas_jep_036',
      questionText: 'Sastra Jepang (#36): Upacara minum teh Jepang (chanoyu) sangat erat kaitannya dengan nilai estetika:',
      options: ['Wabi-sabi (keindahan dalam ketidaksempurnaan)', 'Mono no aware', 'Iki', 'Yugen'],
      correctOptionIndex: 0,
      explanation: 'Wabi-sabi menekankan kesederhanaan dan ketidaksempurnaan sebagai keindahan sejati.',
    ),
    QuestionItem(
      id: 'sas_jep_037',
      questionText: 'Sastra Jepang (#37): Konsep estetika Jepang tentang keindahan melankolis kesadaran akan kefanaan dinamakan:',
      options: ['Mono no aware', 'Wabi-sabi', 'Yugen', 'Aware'],
      correctOptionIndex: 0,
      explanation: 'Mono no aware adalah pengertian kesedihan dan keelokan dalam hal-hal yang fana.',
    ),
    QuestionItem(
      id: 'sas_jep_038',
      questionText: 'Sastra Jepang (#38): Novel Genji Monogatari dianggap sebagai novel pertama di dunia karena:',
      options: ['Berisi 54 bab dan diakui sebagai fiksi panjang pertama', 'Ditulis dengan aksara Cina', 'Pertama dipublikasikan cetak', 'Menggunakan alur sorot balik'],
      correctOptionIndex: 0,
      explanation: 'Genji Monogatari terdiri dari 54 bab dan dianggap novel psikologis pertama di dunia.',
    ),
    QuestionItem(
      id: 'sas_jep_039',
      questionText: 'Sastra Jepang (#39): Sastra Jepang pada zaman Meiji (1868-1912) mendapat pengaruh kuat dari:',
      options: ['Sastra Barat (realisme dan romantisme)', 'Sastra Cina klasik', 'Sastra India kuno', 'Sastra Persia'],
      correctOptionIndex: 0,
      explanation: 'Restorasi Meiji membuka Jepang terhadap pengaruh sastra Eropa.',
    ),
    QuestionItem(
      id: 'sas_jep_040',
      questionText: 'Sastra Jepang (#40): Gerakan sastra Shishosetsu (I-novel) adalah aliran yang:',
      options: ['Menonjolkan pengalaman pribadi penulis sebagai bahan cerita', 'Mengutamakan fantasi mitologi', 'Berciri politik radikal', 'Menggunakan surealisme'],
      correctOptionIndex: 0,
      explanation: 'Shishosetsu populer pada awal abad ke-20 di mana narator menceritakan pengalaman pribadi.',
    ),
    QuestionItem(
      id: 'sas_jep_041',
      questionText: 'Sastra Jepang (#41): Tokoh haiku yang menulis puisi katak melompat ke kolam tua adalah:',
      options: ['Matsuo Basho', 'Yosa Buson', 'Kobayashi Issa', 'Masaoka Shiki'],
      correctOptionIndex: 0,
      explanation: 'Matsuo Basho menciptakan haiku Furu ike ya kawazu tobikomu mizu no oto.',
    ),
    QuestionItem(
      id: 'sas_jep_042',
      questionText: 'Sastra Jepang (#42): Penyair besar Jepang modern pengarang puisi Ame ni mo makezu (Tak Kalah Hujan) adalah:',
      options: ['Kenji Miyazawa', 'Sakutaro Hagiwara', 'Takuboku Ishikawa', 'Akiko Yosano'],
      correctOptionIndex: 0,
      explanation: 'Miyazawa (1896-1933) menulis puisi terkenal Ame ni mo makezu.',
    ),
    QuestionItem(
      id: 'sas_jep_043',
      questionText: 'Sastra Jepang (#43): Kumpulan tanka Midaregami (Rambut Kusut) karya Akiko Yosano terkenal karena:',
      options: ['Ekspresi cinta dan sensualitas yang berani', 'Puisi perang yang patriotik', 'Puisi tentang alam', 'Kritik agama Buddha'],
      correctOptionIndex: 0,
      explanation: 'Yosano (1878-1942) menerbitkan Midaregami pada 1901 dengan gaya sensual dan bebas.',
    ),
    QuestionItem(
      id: 'sas_jep_044',
      questionText: 'Sastra Jepang (#44): Sastra Jepang periode Showa (1926-1989) ditandai oleh:',
      options: ['Beragam aliran realisme hingga eksistensialisme pascaperang', 'Hanya dominasi haiku', 'Penolakan pengaruh asing', 'Kebangkitan sastra lisan'],
      correctOptionIndex: 0,
      explanation: 'Zaman Showa menghasilkan karya besar yang merespons perubahan sosial dan perang.',
    ),
    QuestionItem(
      id: 'sas_jep_045',
      questionText: 'Sastra Jepang (#45): Penulis Kinkakuji (The Temple of the Golden Pavilion) adalah:',
      options: ['Yukio Mishima', 'Yasunari Kawabata', 'Kenzaburo Oe', 'Osamu Dazai'],
      correctOptionIndex: 0,
      explanation: 'Mishima (1956) mengangkat peristiwa nyata pembakaran Kinkakuji oleh biksu.',
    ),
    QuestionItem(
      id: 'sas_jep_046',
      questionText: 'Sastra Jepang (#46): Novel The Silent Cry karya Kenzaburo Oe membahas:',
      options: ['Pemberontakan petani dan krisis identitas di pedesaan', 'Perang Korea', 'Bom atom Hiroshima', 'Kehidupan mahasiswa di Tokyo'],
      correctOptionIndex: 0,
      explanation: 'Oe (Nobel 1994) menulis tentang krisis identitas dan sejarah kekerasan pedesaan.',
    ),
    QuestionItem(
      id: 'sas_jep_047',
      questionText: 'Sastra Jepang (#47): Karya A Personal Matter karya Kenzaburo Oe didasarkan pada:',
      options: ['Pengalaman pribadi penulis dengan anaknya yang lahir cacat', 'Kegagalan cinta di universitas', 'Perjalanan ke Afrika', 'Masa kecil di Manchuria'],
      correctOptionIndex: 0,
      explanation: 'Oe menulis novel ini pada 1964 menggambarkan pergulatan batin seorang ayah.',
    ),
    QuestionItem(
      id: 'sas_jep_048',
      questionText: 'Sastra Jepang (#48): Cerita rakyat Jepang Momotaro mengisahkan:',
      options: ['Anak laki-laki dari buah persik yang mengalahkan iblis Onigashima', 'Putri yang berubah jadi angsa', 'Kelinci di bulan', 'Perang monyet dan kepiting'],
      correctOptionIndex: 0,
      explanation: 'Momotaro adalah pahlawan rakyat yang melawan iblis bersama sahabat hewan.',
    ),
    QuestionItem(
      id: 'sas_jep_049',
      questionText: 'Sastra Jepang (#49): Cerita Tsuru no Ongaeshi (Balas Budi Bangau) mengisahkan:',
      options: ['Bangau yang berubah menjadi wanita untuk membalas kebaikan manusia', 'Bangau yang mencuri makanan', 'Perjalanan bangau ke istana', 'Bangau yang jadi dewa'],
      correctOptionIndex: 0,
      explanation: 'Kisah ini termasuk dalam dongeng Jepang tentang balas budi hewan.',
    ),
    QuestionItem(
      id: 'sas_jep_050',
      questionText: 'Sastra Jepang (#50): Kamus dan tata bahasa Jepang modern dipengaruhi oleh:',
      options: ['Standarisasi era Meiji dan reformasi pasca-Perang Dunia II', 'Aturan Dinasti Tang', 'Sistem Hangul Korea', 'Abjad Romawi murni'],
      correctOptionIndex: 0,
      explanation: 'Pemerintah Meiji dan reformasi 1945 menyederhanakan ejaan dan aksara Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_051',
      questionText: 'Sastra Jepang (#51): Konsep ki dalam budaya dan sastra Jepang merujuk pada:',
      options: ['Semangat, suasana hati, atau energi', 'Pohon', 'Hari', 'Bulan'],
      correctOptionIndex: 0,
      explanation: 'Ki adalah konsep penting menggambarkan perasaan atau atmosfer.',
    ),
    QuestionItem(
      id: 'sas_jep_052',
      questionText: 'Sastra Jepang (#52): Ungkapan Sakura ga chiru secara harfiah berarti:',
      options: ['Bunga sakura berjatuhan', 'Bunga sakura bermekaran', 'Bunga sakura layu', 'Bunga sakura harum'],
      correctOptionIndex: 0,
      explanation: 'Chiru berarti gugur/berjatuhan, menggambarkan keindahan fana sakura.',
    ),
    QuestionItem(
      id: 'sas_jep_053',
      questionText: 'Sastra Jepang (#53): Tetralogi Hojo no Umi (The Sea of Fertility) karya Yukio Mishima mengangkat tema:',
      options: ['Reinkarnasi dan krisis spiritual Jepang modern', 'Perjuangan kelas di Tokyo', 'Kehidupan nelayan Okinawa', 'Konflik Buddha dan Shinto'],
      correctOptionIndex: 0,
      explanation: 'Tetralogi ini (1965-1970) adalah mahakarya Mishima tentang reinkarnasi.',
    ),
    QuestionItem(
      id: 'sas_jep_054',
      questionText: 'Sastra Jepang (#54): Penulis Shiosai (The Sound of Waves) adalah:',
      options: ['Yukio Mishima', 'Yasunari Kawabata', 'Junichiro Tanizaki', 'Shusaku Endo'],
      correctOptionIndex: 0,
      explanation: 'Mishima menulis Shiosai (1954) yang menceritakan kisah cinta di pulau nelayan.',
    ),
    QuestionItem(
      id: 'sas_jep_055',
      questionText: 'Sastra Jepang (#55): Budaya membaca puisi berantai secara kelompok dinamakan:',
      options: ['Renga', 'Haikai', 'Senryu', 'Tanka'],
      correctOptionIndex: 0,
      explanation: 'Renga adalah puisi berantai yang dibuat oleh beberapa penyair.',
    ),
    QuestionItem(
      id: 'sas_jep_056',
      questionText: 'Sastra Jepang (#56): Penyair haikai Yosa Buson juga dikenal sebagai pelukis bergaya:',
      options: ['Bunjinga (lukisan literati)', 'Ukiyo-e', 'Sumi-e', 'Yamato-e'],
      correctOptionIndex: 0,
      explanation: 'Buson (1716-1784) adalah seniman bunjinga yang menggabungkan puisi dan lukisan.',
    ),
    QuestionItem(
      id: 'sas_jep_057',
      questionText: 'Sastra Jepang (#57): Kumpulan cerita hantu Kwaidan yang dikumpulkan Lafcadio Hearn berasal dari:',
      options: ['Cerita rakyat dan legenda Jepang', 'Novel horor Cina', 'Mitos Korea', 'Tradisi Buddha India'],
      correctOptionIndex: 0,
      explanation: 'Lafcadio Hearn (1850-1904) mengumpulkan cerita legenda horor Jepang.',
    ),
    QuestionItem(
      id: 'sas_jep_058',
      questionText: 'Sastra Jepang (#58): Genre catatan harian pribadi dalam sastra klasik Heian dinamakan:',
      options: ['Nikki (diari)', 'Monogatari', 'Zuihitsu', 'Shosetsu'],
      correctOptionIndex: 0,
      explanation: 'Nikki bungaku seperti Kagero Nikki adalah diari pribadi penulis Heian.',
    ),
    QuestionItem(
      id: 'sas_jep_059',
      questionText: 'Sastra Jepang (#59): Penulis novel-I (watakushi shosetsu) terkenal pengarang Shayo adalah:',
      options: ['Osamu Dazai', 'Yukio Mishima', 'Kenzaburo Oe', 'Haruki Murakami'],
      correctOptionIndex: 0,
      explanation: 'Dazai banyak menulis dalam bentuk watakushi shosetsu.',
    ),
    QuestionItem(
      id: 'sas_jep_060',
      questionText: 'Sastra Jepang (#60): Teks sastra kuno Manyoshu ditulis dalam aksara:',
      options: ['Man\'yogana (kanji digunakan untuk fonetik)', 'Hiragana murni', 'Katakana murni', 'Aksara Cina klasik'],
      correctOptionIndex: 0,
      explanation: 'Man\'yogana adalah sistem awal penggunaan kanji sebagai fonetik.',
    ),
    QuestionItem(
      id: 'sas_jep_061',
      questionText: 'Sastra Jepang (#61): Estetika yugen (keanggunan tersembunyi) sangat menonjol dalam seni:',
      options: ['Drama Noh pada zaman Muromachi', 'Haiku modern', 'Kabuki Edo', 'Manga modern'],
      correctOptionIndex: 0,
      explanation: 'Zeami merumuskan konsep yugen dalam seni pertunjukan drama Noh.',
    ),
    QuestionItem(
      id: 'sas_jep_062',
      questionText: 'Sastra Jepang (#62): Latar belakang cerita Rashomon karya Akutagawa berada pada era:',
      options: ['Zaman Heian akhir yang melanda bencana dan kelaparan', 'Zaman Edo yang makmur', 'Perang Dunia II', 'Era Tokyo modern'],
      correctOptionIndex: 0,
      explanation: 'Rashomon berlatar zaman Heian akhir yang penuh kemiskinan dan kekacauan.',
    ),
    QuestionItem(
      id: 'sas_jep_063',
      questionText: 'Sastra Jepang (#63): Novel Botchan karya Natsume Soseki menceritakan tentang:',
      options: ['Seorang guru muda yang berhadapan dengan birokrasi sekolah', 'Perjalanan samurai', 'Petani pedesaan', 'Geisha di Gion'],
      correctOptionIndex: 0,
      explanation: 'Botchan (1906) adalah novel satir Soseki tentang dunia pendidikan.',
    ),
    QuestionItem(
      id: 'sas_jep_064',
      questionText: 'Sastra Jepang (#64): Novel Maihime (The Dancing Girl) karya Mori Ogai terinspirasi oleh:',
      options: ['Pengalaman penulis belajar di Jerman', 'Kisah penari istana', 'Legenda Geisha', 'Perang Rusia-Jepang'],
      correctOptionIndex: 0,
      explanation: 'Mori Ogai (1890) menulis Maihime berdasarkan kisahnya di Berlin.',
    ),
    QuestionItem(
      id: 'sas_jep_065',
      questionText: 'Sastra Jepang (#65): Tema utama sastra Jepang pascaperang (setelah 1945) adalah:',
      options: ['Kekalahan, penderitaan, dan rekonstruksi identitas', 'Kebangkitan militerisme', 'Pemujaan kaisar', 'Penolakan demokrasi'],
      correctOptionIndex: 0,
      explanation: 'Sastrawan pascaperang mengungkap trauma kekalahan dan krisis sosial.',
    ),
    QuestionItem(
      id: 'sas_jep_066',
      questionText: 'Sastra Jepang (#66): Cita-cita utama dalam puisi Ame ni mo makezu karya Kenji Miyazawa adalah:',
      options: ['Menjadi pribadi yang kuat, rendah hati, dan berguna bagi sesama', 'Mencari kekayaan', 'Menjadi samurai', 'Menaklukkan dunia'],
      correctOptionIndex: 0,
      explanation: 'Puisi ini melambangkan cita-cita pelayanan altruistik kepada sesama.',
    ),
    QuestionItem(
      id: 'sas_jep_067',
      questionText: 'Sastra Jepang (#67): Teater komedi tradisional yang dipentaskan di sela-sela Noh disebut:',
      options: ['Kyogen', 'Rakugo', 'Manzai', 'Kodan'],
      correctOptionIndex: 0,
      explanation: 'Kyogen adalah seni komedi lisan yang diselingkan pada pementasan drama Noh.',
    ),
    QuestionItem(
      id: 'sas_jep_068',
      questionText: 'Sastra Jepang (#68): Seni pertunjukan Bunraku disebut ningyo joruri karena menggabungkan:',
      options: ['Boneka kayu dan narasi nyanyian joruri', 'Aktor manusia bertopeng', 'Tarian ritual Shinto', 'Musik gamelan'],
      correctOptionIndex: 0,
      explanation: 'Bunraku menggabungkan boneka kayu (ningyo) dan narasi joruri dengan shamisen.',
    ),
    QuestionItem(
      id: 'sas_jep_069',
      questionText: 'Sastra Jepang (#69): Peran utama kata kigo dalam puisi haiku adalah:',
      options: ['Menunjukkan penanda musim dan nuansa alam', 'Menentukan rima akhiran', 'Menandai nama penyair', 'Sebagai judul puisi'],
      correctOptionIndex: 0,
      explanation: 'Kigo adalah kata penanda musim wajib dalam haiku tradisional.',
    ),
    QuestionItem(
      id: 'sas_jep_070',
      questionText: 'Sastra Jepang (#70): Novel Sorekara (And Then) karya Natsume Soseki bercerita tentang:',
      options: ['Intelektual muda yang terjebak cinta segitiga dan pencarian makna hidup', 'Petualangan samurai', 'Perjuangan petani', 'Geisha di Kyoto'],
      correctOptionIndex: 0,
      explanation: 'Sorekara (1909) mengulas konflik batin individu di tengah perubahan era Meiji.',
    ),
    QuestionItem(
      id: 'sas_jep_071',
      questionText: 'Sastra Jepang (#71): Mazhab Romantisisme Jepang pada tahun 1930-an sering dikaitkan dengan:',
      options: ['Sentimen keindahan estetika tradisional dan nasionalisme', 'Pengaruh gerakan komunis', 'Modernisme surealis', 'Puisi feminisme'],
      correctOptionIndex: 0,
      explanation: 'Romantisisme Jepang merespons modernitas dengan membangkitkan keindahan masa lalu.',
    ),
    QuestionItem(
      id: 'sas_jep_072',
      questionText: 'Sastra Jepang (#72): Novel Senbazuru (A Thousand Cranes) karya Kawabata menggunakan latar:',
      options: ['Tradisi upacara minum teh dan estetika Jepang', 'Bunga sakura dan perang', 'Gunung Fuji dan laut', 'Pedang samurai'],
      correctOptionIndex: 0,
      explanation: 'Senbazuru menggunakan dunia upacara minum teh sebagai latar kecantikan dan tragedi.',
    ),
    QuestionItem(
      id: 'sas_jep_073',
      questionText: 'Sastra Jepang (#73): Kata kimochi dalam ekspresi sastra Jepang merujuk pada:',
      options: ['Perasaan, emosi, atau suasana hati', 'Makanan', 'Pakaian', 'Musim'],
      correctOptionIndex: 0,
      explanation: 'Kimochi bermakna perasaan atau emosi batiniah karakter.',
    ),
    QuestionItem(
      id: 'sas_jep_074',
      questionText: 'Sastra Jepang (#74): Prefiks honorifik o- atau go- dalam kebahasaan Jepang berfungsi untuk:',
      options: ['Menambah kehalusan dan penghormatan pada kata', 'Menunjukkan ukuran besar', 'Menandai benda mati', 'Menunjukkan bentuk lampau'],
      correctOptionIndex: 0,
      explanation: 'Prefiks o- dan go- dipakai untuk menghaluskan dan menghormati kata.',
    ),
    QuestionItem(
      id: 'sas_jep_075',
      questionText: 'Sastra Jepang (#75): Dalam tata bahasa Jepang, partikel ga bertindak sebagai:',
      options: ['Penanda subjek kalimat atau penekanan fokus', 'Penanda objek langsung', 'Penanda kepemilikan', 'Penanda waktu'],
      correctOptionIndex: 0,
      explanation: 'Partikel ga menandai subjek atau penekanan informasi baru.',
    ),
    QuestionItem(
      id: 'sas_jep_076',
      questionText: 'Sastra Jepang (#76): Potret keluarga borjuis di Osaka yang mulai runtuh diceritakan Tanizaki dalam novel:',
      options: ['Sasaneyuki (The Makioka Sisters)', 'In Praise of Shadows', 'Naomi', 'The Key'],
      correctOptionIndex: 0,
      explanation: 'Sasaneyuki menggambarkan perubahan sosial keluarga bangsawan borjuis Osaka.',
    ),
    QuestionItem(
      id: 'sas_jep_077',
      questionText: 'Sastra Jepang (#77): Kanshi (puisi beraksara Cina) dalam sejarah sastra Jepang ditulis oleh:',
      options: ['Bangsawan dan Cendekiawan istana', 'Petani pedesaan', 'Samurai kelas bawah', 'Pedagang pasar'],
      correctOptionIndex: 0,
      explanation: 'Kanshi menjadi simbol penguasaan literatur tinggi bagi kaum elit akademis.',
    ),
    QuestionItem(
      id: 'sas_jep_078',
      questionText: 'Sastra Jepang (#78): Antologi puisi resmi kekaisaran pertama yang disusun tahun 905 M adalah:',
      options: ['Kokin Wakashu (Kokinshu)', 'Manyoshu', 'Shinkokinshu', 'Hyakunin Isshu'],
      correctOptionIndex: 0,
      explanation: 'Kokinshu disusun atas perintah kaisar untuk membakukan Puisi Waka.',
    ),
    QuestionItem(
      id: 'sas_jep_079',
      questionText: 'Sastra Jepang (#79): Penyebaran awal kisah epik Heike Monogatari dilantunkan oleh:',
      options: ['Biwa Hoshi (Biksu tuna netra pemetik Biwa)', 'Prajurit perang', 'Kaisar Heian', 'Penyair Haiku'],
      correctOptionIndex: 0,
      explanation: 'Biwa Hoshi menyebarkan epik perang Heike Monogatari secara lisan.',
    ),
    QuestionItem(
      id: 'sas_jep_080',
      questionText: 'Sastra Jepang (#80): Ungkapan kesopanan sumimasen dalam konteks percakapan Jepang berarti:',
      options: ['Maaf, permisi, atau terima kasih', 'Selamat pagi', 'Selamat tinggal', 'Saya setuju'],
      correctOptionIndex: 0,
      explanation: 'Sumimasen adalah kata ungkapan fleksibel untuk maaf, terima kasih, atau permisi.',
    ),
    QuestionItem(
      id: 'sas_jep_081',
      questionText: 'Sastra Jepang (#81): Cerita anak-anak klasik Gon-gitsune (Gon si Rubah Kecil) ditulis oleh:',
      options: ['Nankichi Niimi', 'Kenji Miyazawa', 'Ryunosuke Akutagawa', 'Matsuo Basho'],
      correctOptionIndex: 0,
      explanation: 'Niimi (1913-1943) menulis kisah rubah kecil Gon yang mengharukan.',
    ),
    QuestionItem(
      id: 'sas_jep_082',
      questionText: 'Sastra Jepang (#82): Kata monogatari dalam istilah sastra Jepang berarti:',
      options: ['Kisah, cerita, atau narasi prosa', 'Puisi pendek', 'Nyanyian ritual', 'Drama komedi'],
      correctOptionIndex: 0,
      explanation: 'Monogatari adalah istilah umum karya naratif fiksi atau sejarah.',
    ),
    QuestionItem(
      id: 'sas_jep_083',
      questionText: 'Sastra Jepang (#83): Fenomena penarikan diri individu dari masyarakat modern Jepang disebut:',
      options: ['Hikikomori', 'Otaku', 'Karoshi', 'Freeter'],
      correctOptionIndex: 0,
      explanation: 'Hikikomori sering diangkat dalam karya novel dan drama sosial Jepang kontemporer.',
    ),
    QuestionItem(
      id: 'sas_jep_084',
      questionText: 'Sastra Jepang (#84): Novel Nemureru Bijo (The House of the Sleeping Beauties) karya Kawabata mengulas tema:',
      options: ['Seksualitas, penuaan, dan kecantikan fana', 'Petualangan masa remaja', 'Kisah perang', 'Bencana alam'],
      correctOptionIndex: 0,
      explanation: 'Nemureru Bijo (1961) mengeksplorasi penuaan dan kerinduan estetika.',
    ),
    QuestionItem(
      id: 'sas_jep_085',
      questionText: 'Sastra Jepang (#85): Puisi Furu ike ya karya Basho menggunakan katak (kawazu) sebagai penanda kigo musim:',
      options: ['Musim semi', 'Musim panas', 'Musim gugur', 'Musim dingin'],
      correctOptionIndex: 0,
      explanation: 'Katak melompat (kawazu) dalam Haiku Basho adalah kigo musim semi.',
    ),
    QuestionItem(
      id: 'sas_jep_086',
      questionText: 'Sastra Jepang (#86): Novel Kazo no hoki karya Ryu Murakami menggambarkan:',
      options: ['Realisme keras dan kehidupan pemuda perkotaan Jepang modern', 'Kisah klasik Heian', 'Puisi Haiku', 'Seni teater Noh'],
      correctOptionIndex: 0,
      explanation: 'Ryu Murakami mengeksplorasi sisi gelap dan pemberontakan pemuda modern.',
    ),
    QuestionItem(
      id: 'sas_jep_087',
      questionText: 'Sastra Jepang (#87): Jenis puisi Senryu berbeda dari Haiku karena:',
      options: ['Lebih berfokus pada satir emosi manusia tanpa wajib kigo', 'Memiliki 31 suku kata', 'Ditulis dalam bahasa Cina', 'Hanya dinyanyikan'],
      correctOptionIndex: 0,
      explanation: 'Senryu berpola 5-7-5 namun menyoroti sindiran sosial tanpa keharusan kigo.',
    ),
    QuestionItem(
      id: 'sas_jep_088',
      questionText: 'Sastra Jepang (#88): Perbedaan utama Nihon Shoki dibanding Kojiki adalah:',
      options: ['Nihon Shoki ditulis dalam bahasa Cina klasik yang lebih faktual-kronologis', 'Nihon Shoki berbentuk puisi', 'Nihon Shoki ditulis hiragana', 'Nihon Shoki karya sastrawan Barat'],
      correctOptionIndex: 0,
      explanation: 'Nihon Shoki (720 M) disusun resmi dalam aksara Cina kronologis.',
    ),
    QuestionItem(
      id: 'sas_jep_089',
      questionText: 'Sastra Jepang (#89): Catatan perjalanan puitis Oku no Hosomichi diciptakan oleh penyair:',
      options: ['Matsuo Basho', 'Yosa Buson', 'Kobayashi Issa', 'Saigyo'],
      correctOptionIndex: 0,
      explanation: 'Oku no Hosomichi adalah mahakarya catatan perjalanan puitis Basho.',
    ),
    QuestionItem(
      id: 'sas_jep_090',
      questionText: 'Sastra Jepang (#90): Krisis identitas dekade 1990-an (Lost Decade) banyak direfleksikan dalam karya:',
      options: ['Haruki Murakami dan pengarang kontemporer', 'Penyair Haiku Edo', 'Pemain Kabuki', 'Penyair Waka Heian'],
      correctOptionIndex: 0,
      explanation: 'Murakami dan fiksi kontemporer merespons alienasi era modern pasca-bubble economy.',
    ),
    QuestionItem(
      id: 'sas_jep_091',
      questionText: 'Sastra Jepang (#91): Fungsi penggunaan keigo dalam dialog karya fiksi Jepang adalah untuk:',
      options: ['Menggambarkan relasi hierarki status sosial tokoh', 'Sekadar aksesoris gaya', 'Menunjukkan bahasa asing', 'Tanda kata serapan'],
      correctOptionIndex: 0,
      explanation: 'Keigo mencerminkan jarak sosial dan status kedudukan para karakter.',
    ),
    QuestionItem(
      id: 'sas_jep_092',
      questionText: 'Sastra Jepang (#92): Tema ketabahan dalam kesedihan tercermin dalam lirik lagu puitis Ue o muite arukou karya:',
      options: ['Rokusuke Ei', 'Matsuo Basho', 'Akiko Yosano', 'Kenji Miyazawa'],
      correctOptionIndex: 0,
      explanation: 'Ue o muite arukou (Sukiyaki) memiliki lirik puitis melankolis yang optimis.',
    ),
    QuestionItem(
      id: 'sas_jep_093',
      questionText: 'Sastra Jepang (#93): Kumpulan cerpen The Elephant Vanishes karya Haruki Murakami mengusung gaya:',
      options: ['Realisme magis dan absurditas kehidupan perkotaan', 'Sejarah perang abad 19', 'Dongeng rakyat', 'Puisi tanka'],
      correctOptionIndex: 0,
      explanation: 'Murakami memadukan fenomena aneh dengan kehidupan sehari-hari.',
    ),
    QuestionItem(
      id: 'sas_jep_094',
      questionText: 'Sastra Jepang (#94): Sastrawan wanita pengarang novel Onnazaka (The Waiting Years) adalah:',
      options: ['Fumiko Enchi', 'Sawako Ariyoshi', 'Banana Yoshimoto', 'Akiko Yosano'],
      correctOptionIndex: 0,
      explanation: 'Enchi (1905-1986) mengkritik patriarki melalui Onnazaka.',
    ),
    QuestionItem(
      id: 'sas_jep_095',
      questionText: 'Sastra Jepang (#95): Novel Hana (The Doctor\'s Wife) karya Sawako Ariyoshi menyoroti:',
      options: ['Peran dan pengorbanan wanita dalam sejarah kedokteran Jepang', 'Kisah cinta romantis', 'Perang di lapangan', 'Legenda obat Tiongkok'],
      correctOptionIndex: 0,
      explanation: 'Ariyoshi menceritakan pengorbanan wanita pendukung ilmu medis.',
    ),
    QuestionItem(
      id: 'sas_jep_096',
      questionText: 'Sastra Jepang (#96): Penyair Sadako Kurihara terkenal dengan karya puisi bertema:',
      options: ['Perjuangan perdamaian dan kritik bom atom Hiroshima', 'Puisi cinta istana', 'Keindahan Gunung Fuji', 'Catatan kuliner'],
      correctOptionIndex: 0,
      explanation: 'Sadako Kurihara menulis puisi kesaksian penyintas bom atom Hiroshima.',
    ),
    QuestionItem(
      id: 'sas_jep_097',
      questionText: 'Sastra Jepang (#97): Karya sastra yang ditulis para biksu Buddha pertapa menekankan konsep:',
      options: ['Wabi-sabi dan ketidakkekalan duniawi (Mujou)', 'Kemewahan istana', 'Perang antar klan', 'Kekayaan materi'],
      correctOptionIndex: 0,
      explanation: 'Karya pertapa seperti Hojoki mengajarkan ketidakkekalan (Mujou).',
    ),
    QuestionItem(
      id: 'sas_jep_098',
      questionText: 'Sastra Jepang (#98): Kritik Natsume Soseki terhadap modernisasi era Meiji berfokus pada:',
      options: ['Keterasingan individu dan benturan kebudayaan', 'Kemajuan ekonomi', 'Kejayaan militer', 'Pertanian tradisional'],
      correctOptionIndex: 0,
      explanation: 'Soseki mengkritik alienasi batin akibat kesebatan modernisasi Barat.',
    ),
    QuestionItem(
      id: 'sas_jep_099',
      questionText: 'Sastra Jepang (#99): Karakteristik estetika minimalis sastra Jepang dipengaruhi oleh:',
      options: ['Filsafat Zen Buddha dan kesadaran alam', 'Revolusi Industri', 'Filsafat Yunani', 'Mitologi Nordik'],
      correctOptionIndex: 0,
      explanation: 'Filsafat Zen membentuk estetika kesederhanaan dan kepenuhan makna.',
    ),
    QuestionItem(
      id: 'sas_jep_100',
      questionText: 'Sastra Jepang (#100): Tujuan utama mempelajari Sastra Jepang dalam jenjang pendidikan tinggi adalah:',
      options: ['Memahami kekayaan budaya, estetika, sejarah, dan nilai kebahasaan Jepang', 'Sekadar membaca kanji', 'Mengafal judul novel', 'Menonton animasi'],
      correctOptionIndex: 0,
      explanation: 'Studi Sastra Jepang membekali pemahaman mendalam atas kebudayaan dan kebahasaan Jepang.',
    ),
  ];
}

