import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraInggrisQuestions() {
  return const [
    QuestionItem(
      id: 'sas_ing_001',
      questionText: 'Sastra Inggris (#1): Pola ritme puisi tradisional Inggris 5 suku kata lemah dan kuat dinamakan:',
      options: ['Iambic Pentameter', 'Trochaic Tetrameter', 'Anapestic Trimeter', 'Dactylic Hexameter'],
      correctOptionIndex: 0,
      explanation: 'Iambic pentameter adalah struktur ritme khas soneta Shakespeare.',
    ),
    QuestionItem(
      id: 'sas_ing_002',
      questionText: 'Sastra Inggris (#2): Pengarang karya drama tragedi Hamlet, Macbeth, dan Othello adalah:',
      options: ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Geoffrey Chaucer'],
      correctOptionIndex: 0,
      explanation: 'William Shakespeare adalah pujangga besar sastra Inggris klasik.',
    ),
    QuestionItem(
      id: 'sas_ing_003',
      questionText: 'Sastra Inggris (#3): Karya sastra The Canterbury Tales yang ditulis dalam bahasa Middle English diciptakan oleh:',
      options: ['Geoffrey Chaucer', 'John Milton', 'William Blake', 'Christopher Marlowe'],
      correctOptionIndex: 0,
      explanation: 'Geoffrey Chaucer dikenal sebagai Bapak Sastra Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_004',
      questionText: 'Sastra Inggris (#4): Pemberian sifat-sifat manusia kepada benda mati atau benda abstrak dalam majas dinamakan:',
      options: ['Personification', 'Metaphor', 'Simile', 'Hyperbole'],
      correctOptionIndex: 0,
      explanation: 'Personification (personifikasi) memberikan karakteristik manusia pada objek non-manusia.',
    ),
    QuestionItem(
      id: 'sas_ing_005',
      questionText: 'Sastra Inggris (#5): Novel Victorian Pride and Prejudice yang menyoroti isu kelas sosial ditulis oleh:',
      options: ['Jane Austen', 'Emily Brontë', 'Charlotte Brontë', 'Virginia Woolf'],
      correctOptionIndex: 0,
      explanation: 'Jane Austen menulis Pride and Prejudice pada era romantisme/realisme Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_006',
      questionText: 'Sastra Inggris (#6): Puisi epik monumental Paradise Lost yang mengisahkan kejatuhan manusia ciptaan:',
      options: ['John Milton', 'Lord Byron', 'Percy Bysshe Shelley', 'John Keats'],
      correctOptionIndex: 0,
      explanation: 'John Milton menulis Paradise Lost dalam bentuk blank verse.',
    ),
    QuestionItem(
      id: 'sas_ing_007',
      questionText: 'Sastra Inggris (#7): Aliran sastra pertengahan abad ke-20 yang menekankan krisis eksistensial dinamakan:',
      options: ['Modernism & Absurdism', 'Romanticism', 'Neoclassicism', 'Realism'],
      correctOptionIndex: 0,
      explanation: 'Modernisme dan Absurdisme mengkaji aliensi manusia pasca Perang Dunia.',
    ),
    QuestionItem(
      id: 'sas_ing_008',
      questionText: 'Sastra Inggris (#8): Struktur analisis kalimat tata bahasa Inggris mengenai susunan frasa (NP + VP) dipelajari dalam:',
      options: ['Syntax & Tree Diagrams', 'Phonology', 'Semantics', 'Pragmatics'],
      correctOptionIndex: 0,
      explanation: 'Sintaksis mempelajari tata urutan dan hubungan klausa/kata dalam kalimat.',
    ),
    QuestionItem(
      id: 'sas_ing_009',
      questionText: 'Sastra Inggris (#9): Novel gothic berciri misteri dan kejahatan Wuthering Heights ditulis oleh:',
      options: ['Emily Brontë', 'Mary Shelley', 'Virginia Woolf', 'George Eliot'],
      correctOptionIndex: 0,
      explanation: 'Emily Brontë menciptakan karya novel klasik Wuthering Heights.',
    ),
    QuestionItem(
      id: 'sas_ing_010',
      questionText: 'Sastra Inggris (#10): Cabang linguistik yang mempelajari sistem bunyi dan fonem suatu bahasa dinamakan:',
      options: ['Phonology', 'Morphology', 'Sociolinguistics', 'Stylistics'],
      correctOptionIndex: 0,
      explanation: 'Fonologi menganalisis pola bunyi dan kontras makna fonem.',
    ),
    QuestionItem(
      id: 'sas_ing_011',
      questionText: 'Sastra Inggris (#11): Drama tragis Romeo and Juliet karya William Shakespeare berlatar di kota:',
      options: ['Verona', 'Venice', 'London', 'Florence'],
      correctOptionIndex: 0,
      explanation: 'Kisah cinta tragis Romeo dan Juliet berlatar di kota Verona, Italia.',
    ),
    QuestionItem(
      id: 'sas_ing_012',
      questionText: 'Sastra Inggris (#12): Novel Great Expectations yang mengisahkan pertumbuhan pemuda Pip ditulis oleh:',
      options: ['Charles Dickens', 'Thomas Hardy', 'William Makepeace Thackeray', 'George Eliot'],
      correctOptionIndex: 0,
      explanation: 'Charles Dickens menulis novel klasiknya Great Expectations.',
    ),
    QuestionItem(
      id: 'sas_ing_013',
      questionText: 'Sastra Inggris (#13): Penyair era Romantisme Inggris yang menulis Ode to a Nightingale adalah:',
      options: ['John Keats', 'William Wordsworth', 'Samuel Taylor Coleridge', 'Lord Byron'],
      correctOptionIndex: 0,
      explanation: 'John Keats adalah tokoh penting era Romantisme Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_014',
      questionText: 'Sastra Inggris (#14): Puisi The Rime of the Ancient Mariner karya Samuel Taylor Coleridge mengisahkan:',
      options: ['Petualangan pelaut dan albatros', 'Perang Trojan', 'Kisah cinta raja', 'Legenda Arthur'],
      correctOptionIndex: 0,
      explanation: 'Coleridge menulis tentang kutukan pelaut tua yang membunuh burung albatros.',
    ),
    QuestionItem(
      id: 'sas_ing_015',
      questionText: 'Sastra Inggris (#15): Novel dystopian 1984 karya George Orwell mengkritik sistem pemerintahan:',
      options: ['Totalitarianisme', 'Demokrasi liberal', 'Monarki konstitusional', 'Feodalisme'],
      correctOptionIndex: 0,
      explanation: 'George Orwell menggambarkan bahaya pengawasan totalitarian dalam 1984.',
    ),
    QuestionItem(
      id: 'sas_ing_016',
      questionText: 'Sastra Inggris (#16): Novel Animal Farm karya George Orwell merupakan bentuk satire allegoris terhadap:',
      options: ['Revolusi Rusia dan Stalinisme', 'Perang Dunia I', 'Revolusi Perancis', 'Perang Saudara Amerika'],
      correctOptionIndex: 0,
      explanation: 'Animal Farm mengibaratkan para pemimpin revolusi sebagai hewan ternak.',
    ),
    QuestionItem(
      id: 'sas_ing_017',
      questionText: 'Sastra Inggris (#17): Penulis Amerika pengarang novel The Great Gatsby (1925) adalah:',
      options: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'William Faulkner', 'John Steinbeck'],
      correctOptionIndex: 0,
      explanation: 'F. Scott Fitzgerald menggambarkan Roaring Twenties dalam The Great Gatsby.',
    ),
    QuestionItem(
      id: 'sas_ing_018',
      questionText: 'Sastra Jepang/Amerika/Inggris: Novel The Old Man and the Sea yang meraih Nobel Sastra karya:',
      options: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'Mark Twain', 'Herman Melville'],
      correctOptionIndex: 0,
      explanation: 'Ernest Hemingway menulis kisah perjuangan nelayan tua Santiago.',
    ),
    QuestionItem(
      id: 'sas_ing_019',
      questionText: 'Sastra Inggris (#19): Novel Moby-Dick yang mengisahkan perburuan paus putih ditulis oleh:',
      options: ['Herman Melville', 'Nathaniel Hawthorne', 'Edgar Allan Poe', 'Walt Whitman'],
      correctOptionIndex: 0,
      explanation: 'Herman Melville menciptakan kapten Ahab dan paus putih Moby Dick.',
    ),
    QuestionItem(
      id: 'sas_ing_020',
      questionText: 'Sastra Inggris (#20): Penyair Amerika pengarang kumpulan puisi Leaves of Grass adalah:',
      options: ['Walt Whitman', 'Emily Dickinson', 'Robert Frost', 'T.S. Eliot'],
      correctOptionIndex: 0,
      explanation: 'Walt Whitman adalah pelopor puisi free verse Amerika.',
    ),
    QuestionItem(
      id: 'sas_ing_021',
      questionText: 'Sastra Inggris (#21): Puisi modernis monumental The Waste Land (1922) ditulis oleh:',
      options: ['T.S. Eliot', 'Ezra Pound', 'W.B. Yeats', 'W.H. Auden'],
      correctOptionIndex: 0,
      explanation: 'T.S. Eliot merefleksikan keputusasaan pasca Perang Dunia I.',
    ),
    QuestionItem(
      id: 'sas_ing_022',
      questionText: 'Sastra Inggris (#22): Penulis novel stream-of-consciousness Mrs. Dalloway dan To the Lighthouse adalah:',
      options: ['Virginia Woolf', 'James Joyce', 'D.H. Lawrence', 'E.M. Forster'],
      correctOptionIndex: 0,
      explanation: 'Virginia Woolf memelopori aliran kesadaran dalam sastra modernis.',
    ),
    QuestionItem(
      id: 'sas_ing_023',
      questionText: 'Sastra Inggris (#23): Novel Irlandia monumental Ulysses yang berlatar satu hari di Dublin ditulis oleh:',
      options: ['James Joyce', 'Oscar Wilde', 'Samuel Beckett', 'George Bernard Shaw'],
      correctOptionIndex: 0,
      explanation: 'James Joyce merenovasi narasi modern melalui novel Ulysses.',
    ),
    QuestionItem(
      id: 'sas_ing_024',
      questionText: 'Sastra Inggris (#24): Lakon drama absurd Waiting for Godot karya Samuel Beckett berfokus pada tokoh:',
      options: ['Vladimir dan Estragon', 'Hamlet dan Horatio', 'Romeo dan Mercutio', 'Othello dan Iago'],
      correctOptionIndex: 0,
      explanation: 'Beckett menggambarkan dua tokoh yang menunggu sosok Godot yang tak pernah datang.',
    ),
    QuestionItem(
      id: 'sas_ing_025',
      questionText: 'Sastra Inggris (#25): Pengarang drama komedi sindiran The Importance of Being Earnest adalah:',
      options: ['Oscar Wilde', 'George Bernard Shaw', 'Christopher Marlowe', 'Ben Jonson'],
      correctOptionIndex: 0,
      explanation: 'Oscar Wilde menyindir gaya hidup aristokrasi Victorian.',
    ),
    QuestionItem(
      id: 'sas_ing_026',
      questionText: 'Sastra Inggris (#26): Novel Frankenstein (1818) yang merupakan pelopor fiksi sains-gothic ditulis oleh:',
      options: ['Mary Shelley', 'Bram Stoker', 'Edgar Allan Poe', 'Robert Louis Stevenson'],
      correctOptionIndex: 0,
      explanation: 'Mary Shelley menciptakan monster Frankenstein.',
    ),
    QuestionItem(
      id: 'sas_ing_027',
      questionText: 'Sastra Inggris (#27): Novel vampir klasik Dracula (1897) ditulis oleh:',
      options: ['Bram Stoker', 'Mary Shelley', 'H.G. Wells', 'Arthur Conan Doyle'],
      correctOptionIndex: 0,
      explanation: 'Bram Stoker memopulerkan mitos Dracula.',
    ),
    QuestionItem(
      id: 'sas_ing_028',
      questionText: 'Sastra Inggris (#28): Tokoh detektif terkenal Sherlock Holmes diciptakan oleh:',
      options: ['Arthur Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe', 'Wilkie Collins'],
      correctOptionIndex: 0,
      explanation: 'Arthur Conan Doyle menulis serial petualangan Sherlock Holmes.',
    ),
    QuestionItem(
      id: 'sas_ing_029',
      questionText: 'Sastra Inggris (#29): Ratu fiksi kriminal pembuat karakter Hercule Poirot dan Miss Marple adalah:',
      options: ['Agatha Christie', 'Dorothy L. Sayers', 'P.D. James', 'Ruth Rendell'],
      correctOptionIndex: 0,
      explanation: 'Agatha Christie adalah penulis fiksi detektif paling laris.',
    ),
    QuestionItem(
      id: 'sas_ing_030',
      questionText: 'Sastra Inggris (#30): Cabang linguistik yang mempelajari arti kata dan kalimat dinamakan:',
      options: ['Semantics', 'Pragmatics', 'Syntax', 'Phonetics'],
      correctOptionIndex: 0,
      explanation: 'Semantik mengkaji makna harfiah kata dan ekspresi bahasa.',
    ),
    QuestionItem(
      id: 'sas_ing_031',
      questionText: 'Sastra Inggris (#31): Cabang linguistik yang mengkaji makna dalam konteks penggunaan tutur dinamakan:',
      options: ['Pragmatics', 'Semantics', 'Morphology', 'Phonology'],
      correctOptionIndex: 0,
      explanation: 'Pragmatik mempelajari maksud penutur sesuai situasi tuturnya.',
    ),
    QuestionItem(
      id: 'sas_ing_032',
      questionText: 'Sastra Inggris (#32): Unit terkecil pembentuk kata yang memiliki makna tata bahasa disebut:',
      options: ['Morpheme', 'Phoneme', 'Syllable', 'Grapheme'],
      correctOptionIndex: 0,
      explanation: 'Morfem adalah unit gramatikal terkecil (misal: un-, -ed).',
    ),
    QuestionItem(
      id: 'sas_ing_033',
      questionText: 'Sastra Inggris (#33): Unit bunyi terkecil dalam bahasa yang membedakan arti kata dinamakan:',
      options: ['Phoneme', 'Morpheme', 'Allophone', 'Diphthong'],
      correctOptionIndex: 0,
      explanation: 'Fonem membedakan makna antar dua kata (contoh: /p/ dan /b/).',
    ),
    QuestionItem(
      id: 'sas_ing_034',
      questionText: 'Sastra Inggris (#34): Perubahan bentuk kata kerja sesuai waktu kejadian (Tense) dipelajari dalam:',
      options: ['Morphology & Grammar', 'Phonetics', 'Stylistics', 'Sociolinguistics'],
      correctOptionIndex: 0,
      explanation: 'Morfologi infleksi mengatur konjugasi tenses pada kata kerja.',
    ),
    QuestionItem(
      id: 'sas_ing_035',
      questionText: 'Sastra Inggris (#35): Majas penegasan yang berlebih-lebihan dinamakan:',
      options: ['Hyperbole', 'Understatement', 'Irony', 'Paradox'],
      correctOptionIndex: 0,
      explanation: 'Hyperbole menggunakan pembalikan atau penggelembung kenyataan.',
    ),
    QuestionItem(
      id: 'sas_ing_036',
      questionText: 'Sastra Inggris (#36): Majas perbandingan langsung tanpa kata pembanding (like/as) dinamakan:',
      options: ['Metaphor', 'Simile', 'Metonymy', 'Synecdoche'],
      correctOptionIndex: 0,
      explanation: 'Metaphor menyamakan dua hal secara langsung.',
    ),
    QuestionItem(
      id: 'sas_ing_037',
      questionText: 'Sastra Inggris (#37): Perbandingan yang menggunakan kata pembanding seperti like atau as dinamakan:',
      options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'],
      correctOptionIndex: 0,
      explanation: 'Simile membandingkan eksplisit dengan kata pembanding.',
    ),
    QuestionItem(
      id: 'sas_ing_038',
      questionText: 'Sastra Inggris (#38): Pengulangan bunyi konsonan awal pada kata-kata yang berurutan dinamakan:',
      options: ['Alliteration', 'Assonance', 'Consonance', 'Onomatopoeia'],
      correctOptionIndex: 0,
      explanation: 'Alliteration memperindah irama puisi melalui pengulangan konsonan awal.',
    ),
    QuestionItem(
      id: 'sas_ing_039',
      questionText: 'Sastra Inggris (#39): Pengulangan bunyi vokal di dalam baris puisi dinamakan:',
      options: ['Assonance', 'Alliteration', 'Rhyme', 'Meter'],
      correctOptionIndex: 0,
      explanation: 'Assonance adalah pengulangan vokal serupa pada kata berdekatan.',
    ),
    QuestionItem(
      id: 'sas_ing_040',
      questionText: 'Sastra Inggris (#40): Kata yang tiruan bunyi dari objek atau aksinya (contoh: buzz, hiss) dinamakan:',
      options: ['Onomatopoeia', 'Oxymoron', 'Paradox', 'Pun'],
      correctOptionIndex: 0,
      explanation: 'Onomatopoeia adalah pembentukan kata berdasarkan tiruan bunyi.',
    ),
    QuestionItem(
      id: 'sas_ing_041',
      questionText: 'Sastra Inggris (#41): Novel Lord of the Flies karya William Golding mengisahkan tentang:',
      options: ['Anak-anak sekolah yang terdampar di pulau terpencil dan naluri kekerasan', 'Perang luar angkasa', 'Kisah cinta remaja', 'Sejarah Kerajaan Inggris'],
      correctOptionIndex: 0,
      explanation: 'Golding menggambarkan kerapuhan peradaban dan potensi kejahatan manusia.',
    ),
    QuestionItem(
      id: 'sas_ing_042',
      questionText: 'Sastra Inggris (#42): Penulis trilogi epik The Lord of the Rings adalah:',
      options: ['J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'George R.R. Martin'],
      correctOptionIndex: 0,
      explanation: 'J.R.R. Tolkien memelopori genre high fantasy modern.',
    ),
    QuestionItem(
      id: 'sas_ing_043',
      questionText: 'Sastra Inggris (#43): Penulis serial fantasi The Chronicles of Narnia adalah:',
      options: ['C.S. Lewis', 'J.R.R. Tolkien', 'Philip Pullman', 'Roald Dahl'],
      correctOptionIndex: 0,
      explanation: 'C.S. Lewis menciptakan dunia Narnia yang alegoris.',
    ),
    QuestionItem(
      id: 'sas_ing_044',
      questionText: 'Sastra Inggris (#44): Novel klasik Jane Eyre yang ditulis dengan nama samaran Currer Bell adalah karya:',
      options: ['Charlotte Brontë', 'Emily Brontë', 'Anne Brontë', 'Jane Austen'],
      correctOptionIndex: 0,
      explanation: 'Charlotte Brontë menulis novel realistik-gothic Jane Eyre.',
    ),
    QuestionItem(
      id: 'sas_ing_045',
      questionText: 'Sastra Inggris (#45): Penulis Amerika pengarang The Grapes of Wrath dan Of Mice and Men adalah:',
      options: ['John Steinbeck', 'William Faulkner', 'Ernest Hemingway', 'Mark Twain'],
      correctOptionIndex: 0,
      explanation: 'Steinbeck mencatat penderitaan era Depresi Besar di Amerika.',
    ),
    QuestionItem(
      id: 'sas_ing_046',
      questionText: 'Sastra Inggris (#46): Petualangan Huckleberry Finn dan Tom Sawyer ditulis oleh sastrawan Amerika:',
      options: ['Mark Twain', 'Herman Melville', 'Jack London', 'O. Henry'],
      correctOptionIndex: 0,
      explanation: 'Mark Twain (Samuel Clemens) adalah legenda sastra humoris Amerika.',
    ),
    QuestionItem(
      id: 'sas_ing_047',
      questionText: 'Sastra Inggris (#47): Penulis The Scarlet Letter yang mengkritik puritanisme New England adalah:',
      options: ['Nathaniel Hawthorne', 'Edgar Allan Poe', 'Washington Irving', 'Herman Melville'],
      correctOptionIndex: 0,
      explanation: 'Hawthorne mengkaji dosa, kecemburuan, dan moralitas puritan.',
    ),
    QuestionItem(
      id: 'sas_ing_048',
      questionText: 'Sastra Inggris (#48): Master cerita pendek misteri gothic The Raven dan The Tell-Tale Heart adalah:',
      options: ['Edgar Allan Poe', 'Bram Stoker', 'H.P. Lovecraft', 'Ambrose Bierce'],
      correctOptionIndex: 0,
      explanation: 'Poe adalah pelopor fiksi detektif dan misteri horor.',
    ),
    QuestionItem(
      id: 'sas_ing_049',
      questionText: 'Sastra Inggris (#49): Penyair wanita Amerika yang hidup menyendiri dan menulis ribuan puisi pendek unik adalah:',
      options: ['Emily Dickinson', 'Sylvia Plath', 'Maya Angelou', 'Elizabeth Bishop'],
      correctOptionIndex: 0,
      explanation: 'Emily Dickinson terkenal dengan puisinya yang inovatif.',
    ),
    QuestionItem(
      id: 'sas_ing_050',
      questionText: 'Sastra Inggris (#50): Drama A Streetcar Named Desire dan Death of a Salesman tergolong dalam karya:',
      options: ['Drama Realisme Amerika Abad ke-20', 'Drama Restorasi', 'Drama Elizabethan', 'Drama Absurd'],
      correctOptionIndex: 0,
      explanation: 'Tennessee Williams dan Arthur Miller memelopori realisme drama Amerika.',
    ),
    QuestionItem(
      id: 'sas_ing_051',
      questionText: 'Sastra Inggris (#51): Penulis drama Death of a Salesman yang mengkritik Mimpi Amerika (American Dream) adalah:',
      options: ['Arthur Miller', 'Tennessee Williams', 'Eugene O\'Neill', 'Edward Albee'],
      correctOptionIndex: 0,
      explanation: 'Arthur Miller menulis tragedi rakyat biasa Willy Loman.',
    ),
    QuestionItem(
      id: 'sas_ing_052',
      questionText: 'Sastra Inggris (#52): Penulis To Kill a Mockingbird yang menyoroti rasisme di Alabama Amerika adalah:',
      options: ['Harper Lee', 'Toni Morrison', 'Alice Walker', 'Maya Angelou'],
      correctOptionIndex: 0,
      explanation: 'Harper Lee memenangkan Pulitzer atas karya To Kill a Mockingbird.',
    ),
    QuestionItem(
      id: 'sas_ing_053',
      questionText: 'Sastra Inggris (#53): Novel Beloved karya penulis wanita Afrika-Amerika penerima Nobel Sastra diciptakan oleh:',
      options: ['Toni Morrison', 'Alice Walker', 'Zora Neale Hurston', 'Maya Angelou'],
      correctOptionIndex: 0,
      explanation: 'Toni Morrison mengangkat luka perbudakan dalam Beloved.',
    ),
    QuestionItem(
      id: 'sas_ing_054',
      questionText: 'Sastra Inggris (#54): Lakon drama Beowulf diciptakan dalam periode bahasa Inggris:',
      options: ['Old English (Anglo-Saxon)', 'Middle English', 'Early Modern English', 'Modern English'],
      correctOptionIndex: 0,
      explanation: 'Beowulf adalah epik tertua dalam Old English abad ke-8 sampai 11.',
    ),
    QuestionItem(
      id: 'sas_ing_055',
      questionText: 'Sastra Inggris (#55): Raja Kerajaan Wessex yang menyponsori penerjemahan teks latin ke Old English adalah:',
      options: ['King Alfred the Great', 'King Arthur', 'King Henry VIII', 'King Richard I'],
      correctOptionIndex: 0,
      explanation: 'Alfred the Great memelopori literasi bahasa Old English.',
    ),
    QuestionItem(
      id: 'sas_ing_056',
      questionText: 'Sastra Inggris (#56): Gerakan Renaissance Inggris mencapai puncak kejayaan sastra pada masa pemerintahan kaisar/ratu:',
      options: ['Queen Elizabeth I', 'Queen Victoria', 'Queen Anne', 'Queen Mary I'],
      correctOptionIndex: 0,
      explanation: 'Era Elizabethan memicu ledakan seni teater Shakespeare dan Marlowe.',
    ),
    QuestionItem(
      id: 'sas_ing_057',
      questionText: 'Sastra Inggris (#57): Penulis drama Doctor Faustus yang sezaman dengan Shakespeare adalah:',
      options: ['Christopher Marlowe', 'Ben Jonson', 'John Webster', 'Thomas Kyd'],
      correctOptionIndex: 0,
      explanation: 'Christopher Marlowe memelopori penggunaan blank verse.',
    ),
    QuestionItem(
      id: 'sas_ing_058',
      questionText: 'Sastra Inggris (#58): Bentuk bait puisi 14 baris ber-pola rima tertentu dinamakan:',
      options: ['Sonnet', 'Ode', 'Ballad', 'Elegy'],
      correctOptionIndex: 0,
      explanation: 'Soneta terdiri dari 14 baris (pola Shakespearean atau Petrarchan).',
    ),
    QuestionItem(
      id: 'sas_ing_059',
      questionText: 'Sastra Inggris (#59): Puisi lirik duka cita untuk mengenang kematian seseorang dinamakan:',
      options: ['Elegy', 'Ode', 'Epic', 'Lyric'],
      correctOptionIndex: 0,
      explanation: 'Elegy adalah puisi ratapan duka atas kematian.',
    ),
    QuestionItem(
      id: 'sas_ing_060',
      questionText: 'Sastra Inggris (#60): Puisi lirik pujian agung kepada objek atau peristiwa tertentu dinamakan:',
      options: ['Ode', 'Elegy', 'Satire', 'Sonnet'],
      correctOptionIndex: 0,
      explanation: 'Ode ditulis sebagai bentuk penghormatan tinggi.',
    ),
    QuestionItem(
      id: 'sas_ing_061',
      questionText: 'Sastra Inggris (#61): Pergeseran bunyi vokal besar-besaran pada abad 15 dalam bahasa Inggris dikenal sebagai:',
      options: ['Great Vowel Shift', 'Grimm\'s Law', 'Norman Conquest', 'Anglo-Saxon Shift'],
      correctOptionIndex: 0,
      explanation: 'Great Vowel Shift mengubah pengucapan vokal panjang dalam bahasa Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_062',
      questionText: 'Sastra Inggris (#62): Penaklukan Norman atas Inggris tahun 1066 memasukkan ribuan kata resapan dari bahasa:',
      options: ['Prancis (Norman French)', 'Jerman', 'Spanyol', 'Italia'],
      correctOptionIndex: 0,
      explanation: 'Peristiwa Norman Conquest mengubah Old English menjadi Middle English.',
    ),
    QuestionItem(
      id: 'sas_ing_063',
      questionText: 'Sastra Inggris (#63): Kamus bahasa Inggris pertama yang paling komprehensif diterbitkan tahun 1755 oleh:',
      options: ['Samuel Johnson', 'Noah Webster', 'James Murray', 'William Caxton'],
      correctOptionIndex: 0,
      explanation: 'Dr. Samuel Johnson menyusun A Dictionary of the English Language.',
    ),
    QuestionItem(
      id: 'sas_ing_064',
      questionText: 'Sastra Inggris (#64): Tokoh yang memperkenalkan mesin cetak pertama di Inggris tahun 1476 adalah:',
      options: ['William Caxton', 'Johannes Gutenberg', 'William Tyndale', 'John Wycliffe'],
      correctOptionIndex: 0,
      explanation: 'William Caxton mencetak buku-buku berbahasa Inggris pertama.',
    ),
    QuestionItem(
      id: 'sas_ing_065',
      questionText: 'Sastra Inggris (#65): Aliran analisis sastra yang berfokus pada struktur teks tanpa latar biografis penulis adalah:',
      options: ['New Criticism & Formalism', 'Psychoanalytic Criticism', 'Marxist Criticism', 'Post-colonialism'],
      correctOptionIndex: 0,
      explanation: 'New Criticism memprioritaskan close reading terhadap teks itu sendiri.',
    ),
    QuestionItem(
      id: 'sas_ing_066',
      questionText: 'Sastra Inggris (#66): Teori sastra yang mengkaji pengaruh ketidaksetaraan gender dan patriarki dinamakan:',
      options: ['Feminist Literary Criticism', 'Structuralism', 'Deconstruction', 'Ecocriticism'],
      correctOptionIndex: 0,
      explanation: 'Kritik feminis menganalisis representasi gender dalam sastra.',
    ),
    QuestionItem(
      id: 'sas_ing_067',
      questionText: 'Sastra Inggris (#67): Teori sastra yang mengkaji dampak jajahan imperialisme Barat dinamakan:',
      options: ['Post-colonial Criticism', 'New Historicism', 'Reader-Response', 'Formalism'],
      correctOptionIndex: 0,
      explanation: 'Kritik poskolonial mengkaji wacana kekuasaan dan identitas bangsa terjajah.',
    ),
    QuestionItem(
      id: 'sas_ing_068',
      questionText: 'Sastra Inggris (#68): Novel Thing Fall Apart yang merespons kolonialisme di Nigeria karya penulis Afrika:',
      options: ['Chinua Achebe', 'Wole Soyinka', 'Ngugi wa Thiong\'o', 'Ben Okri'],
      correctOptionIndex: 0,
      explanation: 'Chinua Achebe adalah bapak novelis Afrika modern berbahasa Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_069',
      questionText: 'Sastra Inggris (#69): Istilah variasi bahasa yang digunakan kelompok sosial tertentu dinamakan:',
      options: ['Sociolect', 'Dialect', 'Idiolect', 'Jargon'],
      correctOptionIndex: 0,
      explanation: 'Sosiolek adalah ragam bahasa khas kelas atau kelompok sosial.',
    ),
    QuestionItem(
      id: 'sas_ing_070',
      questionText: 'Sastra Inggris (#70): Variasi bahasa yang khas dan unik milik individu seorang penutur dinamakan:',
      options: ['Idiolect', 'Dialect', 'Sociolect', 'Accent'],
      correctOptionIndex: 0,
      explanation: 'Idiolek adalah gaya bahasa individual masing-masing penutur.',
    ),
    QuestionItem(
      id: 'sas_ing_071',
      questionText: 'Sastra Inggris (#71): Novel satire Gulliver\'s Travels (1726) yang mengecam sifat buruk manusia karya:',
      options: ['Jonathan Swift', 'Daniel Defoe', 'Alexander Pope', 'Henry Fielding'],
      correctOptionIndex: 0,
      explanation: 'Jonathan Swift adalah master satire prosa Inggris abad ke-18.',
    ),
    QuestionItem(
      id: 'sas_ing_072',
      questionText: 'Sastra Inggris (#72): Novel Robinson Crusoe yang memelopori genre fiksi petualangan pulau terpencil karya:',
      options: ['Daniel Defoe', 'Jonathan Swift', 'Robert Louis Stevenson', 'Jules Verne'],
      correctOptionIndex: 0,
      explanation: 'Daniel Defoe menulis novel klasik Robinson Crusoe (1719).',
    ),
    QuestionItem(
      id: 'sas_ing_073',
      questionText: 'Sastra Inggris (#73): Novel Treasure Island (1883) bercerita tentang bajak laut diciptakan oleh:',
      options: ['Robert Louis Stevenson', 'Daniel Defoe', 'H. Rider Haggard', 'Rudyard Kipling'],
      correctOptionIndex: 0,
      explanation: 'Robert Louis Stevenson melahirkan karakter Long John Silver.',
    ),
    QuestionItem(
      id: 'sas_ing_074',
      questionText: 'Sastra Inggris (#74): Penulis kumpulan cerita anak The Jungle Book adalah pujangga:',
      options: ['Rudyard Kipling', 'Roald Dahl', 'J.M. Barrie', 'Lewis Carroll'],
      correctOptionIndex: 0,
      explanation: 'Rudyard Kipling menulis The Jungle Book dan meraih Nobel Sastra.',
    ),
    QuestionItem(
      id: 'sas_ing_075',
      questionText: 'Sastra Inggris (#75): Novel petualangan absurd Alice\'s Adventures in Wonderland karya:',
      options: ['Lewis Carroll', 'Roald Dahl', 'C.S. Lewis', 'J.M. Barrie'],
      correctOptionIndex: 0,
      explanation: 'Lewis Carroll (Charles Dodgson) menulis Alice in Wonderland.',
    ),
    QuestionItem(
      id: 'sas_ing_076',
      questionText: 'Sastra Inggris (#76): Pencipta dongeng Peter Pan, anak laki-laki yang tak pernah tua di Neverland:',
      options: ['J.M. Barrie', 'Lewis Carroll', 'Roald Dahl', 'A.A. Milne'],
      correctOptionIndex: 0,
      explanation: 'J.M. Barrie mempopulerkan kisah Peter Pan dan Wendy.',
    ),
    QuestionItem(
      id: 'sas_ing_077',
      questionText: 'Sastra Inggris (#77): Pencipta karakter beruang anak-anak Winnie-the-Pooh adalah:',
      options: ['A.A. Milne', 'Beatrix Potter', 'Roald Dahl', 'Michael Bond'],
      correctOptionIndex: 0,
      explanation: 'A.A. Milne menulis dongeng Winnie-the-Pooh.',
    ),
    QuestionItem(
      id: 'sas_ing_078',
      questionText: 'Sastra Inggris (#78): Pengarang novel humor populer Charlie and the Chocolate Factory dan Matilda:',
      options: ['Roald Dahl', 'Enid Blyton', 'David Walliams', 'J.K. Rowling'],
      correctOptionIndex: 0,
      explanation: 'Roald Dahl adalah pengarang fiksi anak legendaris asal Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_079',
      questionText: 'Sastra Inggris (#79): Novel fantasi sihir paling fenomenal Harry Potter diciptakan oleh:',
      options: ['J.K. Rowling', 'J.R.R. Tolkien', 'Philip Pullman', 'Suzanne Collins'],
      correctOptionIndex: 0,
      explanation: 'J.K. Rowling menciptakan serial dunia sihir Hogwarts.',
    ),
    QuestionItem(
      id: 'sas_ing_080',
      questionText: 'Sastra Inggris (#80): Novel dystopian Farenheit 451 tentang pembakaran buku oleh pemerintah ditulis oleh:',
      options: ['Ray Bradbury', 'Aldous Huxley', 'Philip K. Dick', 'Arthur C. Clarke'],
      correctOptionIndex: 0,
      explanation: 'Ray Bradbury memperingatkan ancaman sensor sastra.',
    ),
    QuestionItem(
      id: 'sas_ing_081',
      questionText: 'Sastra Inggris (#81): Novel Brave New World yang menggambarkan rekayasa genetika masyarakat ditulis oleh:',
      options: ['Aldous Huxley', 'George Orwell', 'H.G. Wells', 'H.G. Ballard'],
      correctOptionIndex: 0,
      explanation: 'Aldous Huxley menulis novel futuristik distopia Brave New World.',
    ),
    QuestionItem(
      id: 'sas_ing_082',
      questionText: 'Sastra Inggris (#82): Penulis fiksi sains The Time Machine dan The War of the Worlds adalah:',
      options: ['H.G. Wells', 'Jules Verne', 'Isaac Asimov', 'Arthur C. Clarke'],
      correctOptionIndex: 0,
      explanation: 'H.G. Wells adalah bapak fiksi sains klasik Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_083',
      questionText: 'Sastra Inggris (#83): Hukum Fonetik pergeseran bunyi konsonan bahasa Proto-Indo-Eropa ke Jermanik dipelajari dalam:',
      options: ['Grimm\'s Law', 'Verner\'s Law', 'Great Vowel Shift', 'Morphophonemics'],
      correctOptionIndex: 0,
      explanation: 'Hukum Grimm menjelaskan evolusi konsonan bahasa Jermanik dan Inggris.',
    ),
    QuestionItem(
      id: 'sas_ing_084',
      questionText: 'Sastra Inggris (#84): Penggunaan dua kata berlawanan secara bersamaan (misal: deafening silence) dinamakan:',
      options: ['Oxymoron', 'Paradox', 'Irony', 'Antithesis'],
      correctOptionIndex: 0,
      explanation: 'Oxymoron mengabungkan dua kata berkontradiksi langsung.',
    ),
    QuestionItem(
      id: 'sas_ing_085',
      questionText: 'Sastra Inggris (#85): Pernyataan kontradiktif yang menyimpan kebenaran terselubung dinamakan:',
      options: ['Paradox', 'Oxymoron', 'Ambiguity', 'Pun'],
      correctOptionIndex: 0,
      explanation: 'Paradoks adalah konsep ide berkontradiksi namun mengandung kebenaran.',
    ),
    QuestionItem(
      id: 'sas_ing_086',
      questionText: 'Sastra Inggris (#86): Permainan kata berdasarkan kemiripan bunyi atau kembar makna dinamakan:',
      options: ['Pun', 'Irony', 'Sarcasm', 'Satire'],
      correctOptionIndex: 0,
      explanation: 'Pun adalah permainan kata untuk efek humor atau kecerdasan stilistika.',
    ),
    QuestionItem(
      id: 'sas_ing_087',
      questionText: 'Sastra Inggris (#87): Penggunaan bahasa sindiran halus yang bermakna sebaliknya dari ucapan dinamakan:',
      options: ['Irony', 'Hyperbole', 'Litotes', 'Sarcasm'],
      correctOptionIndex: 0,
      explanation: 'Ironi mengekspresikan makna yang bertolak belakang dengan ucapan harfiah.',
    ),
    QuestionItem(
      id: 'sas_ing_088',
      questionText: 'Sastra Inggris (#88): Majas penegasan dengan cara menyangkal kebalikan kalimatnya (misal: not bad) dinamakan:',
      options: ['Litotes', 'Hyperbole', 'Irony', 'Euphemism'],
      correctOptionIndex: 0,
      explanation: 'Litotes menekankan ungkapan positif lewat bentuk negatif ganda.',
    ),
    QuestionItem(
      id: 'sas_ing_089',
      questionText: 'Sastra Inggris (#89): Penggunaan ungkapan lebih halus untuk menggantikan kata kasar atau kurang menyenangkan dinamakan:',
      options: ['Euphemism', 'Dysphemism', 'Metaphor', 'Understatement'],
      correctOptionIndex: 0,
      explanation: 'Euphemism menghaluskan kata agar tidak menyinggung.',
    ),
    QuestionItem(
      id: 'sas_ing_090',
      questionText: 'Sastra Inggris (#90): Teoretikus strukturalisme fonologi dan tata bahasa transformasional-generatif adalah:',
      options: ['Noam Chomsky', 'Ferdinand de Saussure', 'Roman Jakobson', 'Leonard Bloomfield'],
      correctOptionIndex: 0,
      explanation: 'Noam Chomsky memelopori teori Generative Grammar.',
    ),
    QuestionItem(
      id: 'sas_ing_091',
      questionText: 'Sastra Inggris (#91): Konsep kemampuan kebahasaan abstrak dalam otak menurut Chomsky dinamakan:',
      options: ['Linguistic Competence', 'Linguistic Performance', 'Langue', 'Parole'],
      correctOptionIndex: 0,
      explanation: 'Competence adalah pengetahuan tata bahasa bawaan penutur.',
    ),
    QuestionItem(
      id: 'sas_ing_092',
      questionText: 'Sastra Inggris (#92): Penggunaan aktual bahasa dalam komunikasi sehari-hari menurut Chomsky dinamakan:',
      options: ['Linguistic Performance', 'Linguistic Competence', 'Langue', 'Syntax'],
      correctOptionIndex: 0,
      explanation: 'Performance adalah wujud aktual penerapan bahasa.',
    ),
    QuestionItem(
      id: 'sas_ing_093',
      questionText: 'Sastra Inggris (#93): Hipotesis Sapir-Whorf mengkaji hubungan erat antara bahasa dan:',
      options: ['Pola pikir dan persepsi budaya penutur', 'Struktur otak mekanis', 'Genetika rasial', 'Iklim geografis'],
      correctOptionIndex: 0,
      explanation: 'Sapir-Whorf Hypothesis menyatakan struktur bahasa mempengaruhi cara pandang budaya.',
    ),
    QuestionItem(
      id: 'sas_ing_094',
      questionText: 'Sastra Inggris (#94): Dialek bahasa Inggris standar yang digunakan dalam penyiaran resmi BBC dinamakan:',
      options: ['Received Pronunciation (RP)', 'Cockney', 'GenAm (General American)', 'Scouse'],
      correctOptionIndex: 0,
      explanation: 'RP adalah standar pengucapan prestise bahasa Inggris Britania.',
    ),
    QuestionItem(
      id: 'sas_ing_095',
      questionText: 'Sastra Inggris (#95): Dialek khas masyarakat kelas pekerja London yang terkenal dengan rhyming slang dinamakan:',
      options: ['Cockney', 'Geordie', 'Brummie', 'Scottish English'],
      correctOptionIndex: 0,
      explanation: 'Cockney adalah dialek tradisional kawasan timur kota London.',
    ),
    QuestionItem(
      id: 'sas_ing_096',
      questionText: 'Sastra Inggris (#96): Penggunaan bahasa Inggris sebagai lingua franca di berbagai penjuru dunia dipelajari dalam:',
      options: ['World Englishes & Global English', 'Dialectology', 'Historical Linguistics', 'Etymology'],
      correctOptionIndex: 0,
      explanation: 'World Englishes mengkaji variasi bahasa Inggris internasional.',
    ),
    QuestionItem(
      id: 'sas_ing_097',
      questionText: 'Sastra Inggris (#97): Asal-usul serta perkembangan sejarah makna kata dipelajari dalam cabang:',
      options: ['Etymology', 'Morphology', 'Phonology', 'Syntax'],
      correctOptionIndex: 0,
      explanation: 'Etimologi menyelidiki asal kata dan sejarah evolusi maknanya.',
    ),
    QuestionItem(
      id: 'sas_ing_098',
      questionText: 'Sastra Inggris (#98): Kajian linguistik yang memadukan ilmu bahasa dengan psikologi proses mental dinamakan:',
      options: ['Psycholinguistics', 'Sociolinguistics', 'Neurolinguistics', 'Stylistics'],
      correctOptionIndex: 0,
      explanation: 'Psikolinguistik mengkaji pemrosesan dan pemerolehan bahasa di otak.',
    ),
    QuestionItem(
      id: 'sas_ing_099',
      questionText: 'Sastra Inggris (#99): Kajian gaya bahasa dan penggunaan majas dalam analisis teks sastra dinamakan:',
      options: ['Stylistics', 'Discourse Analysis', 'Semiotics', 'Philology'],
      correctOptionIndex: 0,
      explanation: 'Stilistika menganalisis aspek stilistika gaya penulisan sastra.',
    ),
    QuestionItem(
      id: 'sas_ing_100',
      questionText: 'Sastra Inggris (#100): Tujuan utama mempelajari Sastra dan Linguistik Inggris adalah:',
      options: ['Menguasai kemampuan analisis kritis teks, literatur dunia, dan komunikasi internasional', 'Sekadar menghafal tata bahasa', 'Menulis cerita pendek tanpa aturan', 'Menjadi penerjemah tanpa teori'],
      correctOptionIndex: 0,
      explanation: 'Studi Sastra Inggris membekali kompetensi analisis literatur, kritis budaya, dan kebahasaan global.',
    ),
  ];
}
