import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraPrancisQuestions() {
  return const [
    QuestionItem(
      id: 'sas_pra_001',
      questionText: 'Epos pahlawan abad pertengahan tertua dalam bahasa Prancis Kuno (Chanson de Geste) sekitar abad ke-11 berjudul:',
      options: ['La Chanson de Roland', 'Le Roman de la Rose', 'Tristan et Iseut', 'L\'Song de Geste'],
      correctOptionIndex: 0,
      explanation: 'La Chanson de Roland menceritakan keberanian Roland dalam pertempuran Roncesvalles di bawah Charlemagne.',
    ),
    QuestionItem(
      id: 'sas_pra_002',
      questionText: 'Penulis komedi terbesar Prancis abad ke-17 yang mengarang drama "Le Misanthrope", "Tartuffe", dan "L\'Avare" adalah:',
      options: ['Molière (Jean-Baptiste Poquelin)', 'Jean Racine', 'Pierre Corneille', 'Jean de La Fontaine'],
      correctOptionIndex: 0,
      explanation: 'Molière adalah maestro komedi satire sosial pada era Raja Louis XIV.',
    ),
    QuestionItem(
      id: 'sas_pra_003',
      questionText: 'Tokoh Tartuffe dalam drama komedi Molière "Tartuffe" menggambarkan sosok:',
      options: ['Orang munafik yang berpura-pura sangat alim dan suci', 'Seorang kikir yang menyembunyikan uangnya', 'Seorang bangsawan pemarah', 'Seorang dokter palsu'],
      correctOptionIndex: 0,
      explanation: 'Tartuffe menjadi sinonim bahasa Prancis untuk kemunafikan agama dan moral.',
    ),
    QuestionItem(
      id: 'sas_pra_004',
      questionText: 'Dramawan tragedi Klasik Prancis abad ke-17 yang menulis "Phèdre" dan "Andromaque" adalah:',
      options: ['Jean Racine', 'Pierre Corneille', 'Molière', 'Voltaire'],
      correctOptionIndex: 0,
      explanation: 'Jean Racine adalah tokoh puncak tragedi klasik Prancis bersajak alexandrin.',
    ),
    QuestionItem(
      id: 'sas_pra_005',
      questionText: 'Dramawan tragedi yang mengarang "Le Cid" (1637) dan memicu perdebatan estetika (La Querelle du Cid) adalah:',
      options: ['Pierre Corneille', 'Jean Racine', 'Molière', 'Boileau'],
      correctOptionIndex: 0,
      explanation: 'Corneille menciptakan tragedi dilema kehormatan versus cinta dalam "Le Cid".',
    ),
    QuestionItem(
      id: 'sas_pra_006',
      questionText: 'Pengarang kumpulan fabel hewan bermoral tinggi "Fables" (1668) seperti "Le Corbeau et le Renard" adalah:',
      options: ['Jean de La Fontaine', 'Charles Perrault', 'François Rabelais', 'Michel de Montaigne'],
      correctOptionIndex: 0,
      explanation: 'Jean de La Fontaine mengarang fabel klasik yang mengajarkan kearifan hidup.',
    ),
    QuestionItem(
      id: 'sas_pra_007',
      questionText: 'Pengumpul dongeng klasik Prancis seperti "Cendrillon" (Cinderella), "Le Petit Chaperon Rouge" (Si Kerudung Merah), dan "La Belle au bois dormant" adalah:',
      options: ['Charles Perrault', 'Jean de La Fontaine', 'Mme d\'Aulnoy', 'Brothers Grimm'],
      correctOptionIndex: 0,
      explanation: 'Charles Perrault menerbitkan "Histoires ou contes du temps passé" pada tahun 1697.',
    ),
    QuestionItem(
      id: 'sas_pra_008',
      questionText: 'Filsuf Humanis abad ke-16 yang menciptakan genre tulisan esai "Les Essais" (1580) adalah:',
      options: ['Michel de Montaigne', 'François Rabelais', 'Desiderius Erasmus', 'René Descartes'],
      correctOptionIndex: 0,
      explanation: 'Montaigne memelopori bentuk esai introspektif modern dengan semboyan "Que sais-je?" (Apa yang kuketahui?).',
    ),
    QuestionItem(
      id: 'sas_pra_009',
      questionText: 'Penulis Humanisme Renaissance yang mengarang kisah satir raksasa "Gargantua et Pantagruel" adalah:',
      options: ['François Rabelais', 'Michel de Montaigne', 'Pierre de Ronsard', 'Joachim du Bellay'],
      correctOptionIndex: 0,
      explanation: 'François Rabelais terkenal akan humor karnavalesk dan perayaan kebebasan berpikir.',
    ),
    QuestionItem(
      id: 'sas_pra_010',
      questionText: 'Filsuf Pencerahan (Siècle des Lumières) yang mengarang tale filosofis satire "Candide, ou l\'Optimisme" (1759) adalah:',
      options: ['Voltaire (François-Marie Arouet)', 'Jean-Jacques Rousseau', 'Denis Diderot', 'Montesquieu'],
      correctOptionIndex: 0,
      explanation: 'Voltaire mengejek filosofi optimisme Leibnizian melalui petualangan tragikomis Candide.',
    ),
    QuestionItem(
      id: 'sas_pra_011',
      questionText: 'Prinsip penutup Candide yang terkenal "Il faut cultiver notre jardin" mengajarkan:',
      options: ['Manusia harus bekerja nyata dan fokus mengolah kebun kehidupan sendiri daripada berteori konyol', 'Manusia harus menjadi petani', 'Dunia ini adalah yang terbaik dari semua kemungkinan dunia', 'Tuhan tidak peduli'],
      correctOptionIndex: 0,
      explanation: '"Cultiver notre jardin" adalah seruan Voltaire untuk tindakan pragmatis yang bermanfaat.',
    ),
    QuestionItem(
      id: 'sas_pra_012',
      questionText: 'Filsuf Abad Pencerahan yang mengarang "Du contrat social" (Kontrak Sosial) dan "Émile, ou De l\'éducation" adalah:',
      options: ['Jean-Jacques Rousseau', 'Voltaire', 'Denis Diderot', 'Montesquieu'],
      correctOptionIndex: 0,
      explanation: 'Rousseau merumuskan teori kedaulatan rakyat dan kehendak umum (volonté générale).',
    ),
    QuestionItem(
      id: 'sas_pra_013',
      questionText: 'Filsuf utama penggagas proyek pengumpulan ilmu pengetahuan monumental "L\'Encyclopédie" (1751-1772) adalah:',
      options: ['Denis Diderot dan Jean le Rond d\'Alembert', 'Voltaire dan Rousseau', 'Descartes dan Pascal', 'Montesquieu dan Condorcet'],
      correctOptionIndex: 0,
      explanation: 'Diderot dan d\'Alembert memimpin penyusunan Encyclopédie sebagai senjata intelektual Pencerahan.',
    ),
    QuestionItem(
      id: 'sas_pra_014',
      questionText: 'Pengarang naskah politik Pencerahan "De l\'esprit des lois" (Semangat Hukum) yang merumuskan Trias Politika adalah:',
      options: ['Montesquieu (Charles-Louis de Secondat)', 'Voltaire', 'Rousseau', 'Condorcet'],
      correctOptionIndex: 0,
      explanation: 'Montesquieu merumuskan pemisahan kekuasaan eksekutif, legislatif, dan yudikatif.',
    ),
    QuestionItem(
      id: 'sas_pra_015',
      questionText: 'Pengarang dan pemuncak aliran Romantisisme Prancis yang mengarang novel "Les Misérables" dan "Notre-Dame de Paris" adalah:',
      options: ['Victor Hugo', 'Alexandre Dumas', 'Honoré de Balzac', 'Stendhal'],
      correctOptionIndex: 0,
      explanation: 'Victor Hugo (1802–1885) adalah raksasa sastra Romantisisme Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_016',
      questionText: 'Tokoh utama narapidana dalam novel "Les Misérables" karya Victor Hugo yang dikejar oleh inspektur Javert bernama:',
      options: ['Jean Valjean', 'Marius Pontmercy', 'Quasimodo', 'Edmond Dantès'],
      correctOptionIndex: 0,
      explanation: 'Jean Valjean dipenjara 19 tahun karena mencuri sepotong roti lalu bertobat menjadi dermawan.',
    ),
    QuestionItem(
      id: 'sas_pra_017',
      questionText: 'Pengarang novel sejarah populer "Le Comte de Monte-Cristo" dan "Les Trois Mousquetaires" (Tiga Musketeer) adalah:',
      options: ['Alexandre Dumas (père)', 'Victor Hugo', 'Gustave Flaubert', 'Émile Zola'],
      correctOptionIndex: 0,
      explanation: 'Alexandre Dumas adalah maestro novel petualangan epik Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_018',
      questionText: 'Novel "Le Rouge et le Noir" (Merah dan Hitam, 1830) yang mengisahkan ambisi sosial Julien Sorel ditulis oleh:',
      options: ['Stendhal (Henri Beyle)', 'Honoré de Balzac', 'Gustave Flaubert', 'Guy de Maupassant'],
      correctOptionIndex: 0,
      explanation: 'Stendhal melukiskan ambisi pemuda di tengah restorasi monarki Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_019',
      questionText: 'Seri novel monumental "La Comédie humaine" (Komedi Manusia) yang terdiri dari sekitar 90 novel realistis diciptakan oleh:',
      options: ['Honoré de Balzac', 'Gustave Flaubert', 'Émile Zola', 'Guy de Maupassant'],
      correctOptionIndex: 0,
      explanation: 'Balzac memotret seluruh lapisan masyarakat Prancis abad ke-19 melalui La Comédie humaine.',
    ),
    QuestionItem(
      id: 'sas_pra_020',
      questionText: 'Novel mahakarya realisme "Madame Bovary" (1857) yang menceritakan ketidakpuasan romantis Emma Bovary ditulis oleh:',
      options: ['Gustave Flaubert', 'Honoré de Balzac', 'Stendhal', 'Émile Zola'],
      correctOptionIndex: 0,
      explanation: 'Gustave Flaubert dijuluki bapak realisme modern lewat teknik pencarian "le mot juste".',
    ),
    QuestionItem(
      id: 'sas_pra_021',
      questionText: 'Puncak aliran Naturalisme Prancis yang mengarang seri novel 20 jilid "Les Rougon-Macquart" (termasuk "Germinal" dan "L\'Assommoir") adalah:',
      options: ['Émile Zola', 'Gustave Flaubert', 'Guy de Maupassant', 'Alphonse Daudet'],
      correctOptionIndex: 0,
      explanation: 'Émile Zola mengaplikasikan metode eksperimen ilmiah determinisme pada karya fiksi sastra.',
    ),
    QuestionItem(
      id: 'sas_pra_022',
      questionText: 'Surat terbuka Émile Zola yang terkenal pada tahun 1898 untuk membela Kapten Alfred Dreyfus berjudul:',
      options: ['J\'accuse...! (Saya Menuduh...!)', 'L\'Aurore', 'Germinal', 'La Bête humaine'],
      correctOptionIndex: 0,
      explanation: 'Surat "J\'accuse...!" diterbitkan di koran L\'Aurore memprotes konspirasi rasialis militer terhadap Dreyfus.',
    ),
    QuestionItem(
      id: 'sas_pra_023',
      questionText: 'Maestro cerita pendek Realisme Prancis yang mengarang "Boule de Suif" dan "La Parure" (Kalung Mutiara) adalah:',
      options: ['Guy de Maupassant', 'Émile Zola', 'Alphonse Daudet', 'Prosper Mérimée'],
      correctOptionIndex: 0,
      explanation: 'Guy de Maupassant mengarang ratusan cerpen dengan akhir plot twist yang mengejutkan.',
    ),
    QuestionItem(
      id: 'sas_pra_024',
      questionText: 'Penyair aliran Simbolisme yang mengarang kumpulan puisi kontroversial "Les Fleurs du mal" (Bunga-bunga Kejahatan, 1857) adalah:',
      options: ['Charles Baudelaire', 'Arthur Rimbaud', 'Paul Verlaine', 'Stéphane Mallarmé'],
      correctOptionIndex: 0,
      explanation: 'Charles Baudelaire memelopori estetika modernisme dan simbolisme dalam Les Fleurs du mal.',
    ),
    QuestionItem(
      id: 'sas_pra_025',
      questionText: 'Penyair jenius ajaib Prancis yang berhenti menulis puisi di usia 20 tahun dan mengarang "Le Bateau ivre" dan "Une saison en enfer" adalah:',
      options: ['Arthur Rimbaud', 'Paul Verlaine', 'Stéphane Mallarmé', 'Lautréamont'],
      correctOptionIndex: 0,
      explanation: 'Arthur Rimbaud (1854–1891) merevolusi puisi dengan pencarian "dérèglement de tous les sens".',
    ),
    QuestionItem(
      id: 'sas_pra_026',
      questionText: 'Penyair Simbolisme yang dekat dengan Rimbaud dan mengarang "Poèmes saturniens" dan "Romances sans paroles" adalah:',
      options: ['Paul Verlaine', 'Charles Baudelaire', 'Stéphane Mallarmé', 'Paul Valéry'],
      correctOptionIndex: 0,
      explanation: 'Paul Verlaine mengusung prinsip "De la musique avant toute chose" dalam puisi.',
    ),
    QuestionItem(
      id: 'sas_pra_027',
      questionText: 'Penyair Simbolisme hermetis yang menulis puisi eksperimental "Un coup de dés jamais n\'abolira le hasard" adalah:',
      options: ['Stéphane Mallarmé', 'Paul Valéry', 'Arthur Rimbaud', 'Guillaume Apollinaire'],
      correctOptionIndex: 0,
      explanation: 'Stéphane Mallarmé memelopori penggunaan tata letak visual tipografi dalam puisi modern.',
    ),
    QuestionItem(
      id: 'sas_pra_028',
      questionText: 'Sastrawan modern yang mengarang novel 7 jilid monumental "À la recherche du temps perdu" (Mencari Waktu yang Hilang) adalah:',
      options: ['Marcel Proust', 'André Gide', 'Louis-Ferdinand Céline', 'Colette'],
      correctOptionIndex: 0,
      explanation: 'Marcel Proust mengeksplorasi ingatan tak sengaja (involuntary memory) seperti pada episode kue Madeleines.',
    ),
    QuestionItem(
      id: 'sas_pra_029',
      questionText: 'Pengarang dan filsuf Eksistensialisme penerima Nobel Sastra 1957 yang mengarang "L\'Étranger" (Orang Asing) dan "Le Mythe de Sisyphe" adalah:',
      options: ['Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir', 'Gabriel Marcel'],
      correctOptionIndex: 0,
      explanation: 'Albert Camus mengusung filsafat Absurdisme dan perlawanan dalam karya-karyanya.',
    ),
    QuestionItem(
      id: 'sas_pra_030',
      questionText: 'Tokoh Meursault dalam novel "L\'Étranger" karya Camus menunjukkan sikap:',
      options: ['Ketidakpedulian yang absurd terhadap konvensi emosi masyarakat', 'Kecintaan mendalam pada tanah air', 'Ketaatan agama', 'Ambisi menjadi penguasa'],
      correctOptionIndex: 0,
      explanation: 'Meursault dihukum mati bukan hanya karena membunuh Arab, tetapi karena tidak menangis saat ibunya meninggal.',
    ),
    QuestionItem(
      id: 'sas_pra_031',
      questionText: 'Filsuf Eksistensialis utama yang mengarang "L\'Être et le Néant", drama "Huis Clos", dan MENOLAK Hadiah Nobel Sastra 1964 adalah:',
      options: ['Jean-Paul Sartre', 'Albert Camus', 'Maurice Merleau-Ponty', 'Jacques Derrida'],
      correctOptionIndex: 0,
      explanation: 'Jean-Paul Sartre menolak Nobel 1964 karena tidak mau terikat oleh institusi borjuis.',
    ),
    QuestionItem(
      id: 'sas_pra_032',
      questionText: 'Kutipan terkenal dari drama Sartre "Huis Clos" (No Exit) adalah:',
      options: ['"L\'enfer, c\'est les Autres" (Neraka adalah orang lain)', 'L\'existence précède l\'essence', 'Je pense, donc je suis', 'Vouloir, c\'est pouvoir'],
      correctOptionIndex: 0,
      explanation: '"L\'enfer, c\'est les Autres" merujuk pada tatapan dan penilaian orang lain yang mengurung kebebasan kita.',
    ),
    QuestionItem(
      id: 'sas_pra_033',
      questionText: 'Filsuf feminis modern yang mengarang naskah ikonis "Le Deuxième Sexe" (Jenis Kelamin Kedua, 1949) adalah:',
      options: ['Simone de Beauvoir', 'Marguerite Duras', 'Colette', 'Luce Irigaray'],
      correctOptionIndex: 0,
      explanation: 'Simone de Beauvoir terkenal dengan pernyataan: "On ne naît pas femme: on le devient" (Orang tidak dilahirkan sebagai wanita, melainkan menjadi wanita).',
    ),
    QuestionItem(
      id: 'sas_pra_034',
      questionText: 'Pengarang wanita pengarang novel autobiografis "L\'Amant" (The Lover, 1984) penerima Prix Goncourt adalah:',
      options: ['Marguerite Duras', 'Nathalie Sarraute', 'Marguerite Yourcenar', 'Françoise Sagan'],
      correctOptionIndex: 0,
      explanation: 'Marguerite Duras mengisahkan masa mudanya di Indochina Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_035',
      questionText: 'Wanita pertama yang terpilih menjadi anggota Académie Française pada tahun 1980 dan mengarang "Mémoires d\'Hadrien" adalah:',
      options: ['Marguerite Yourcenar', 'Simone de Beauvoir', 'Colette', 'George Sand'],
      correctOptionIndex: 0,
      explanation: 'Marguerite Yourcenar memecahkan tradisi 300 tahun keanggotaan pria di Académie Française.',
    ),
    QuestionItem(
      id: 'sas_pra_036',
      questionText: 'Pengarang dongeng filosofis abad ke-20 paling dicintai di dunia "Le Petit Prince" (Pangeran Kecil, 1943) adalah:',
      options: ['Antoine de Saint-Exupéry', 'Romain Gary', 'Jean Giono', 'Marcel Pagnol'],
      correctOptionIndex: 0,
      explanation: 'Saint-Exupéry adalah penerbang dan pengarang cerita alegoris Pangeran Kecil dari Asteroid B-612.',
    ),
    QuestionItem(
      id: 'sas_pra_037',
      questionText: 'Pesan rahasia rubah kepada Pangeran Kecil yang sangat terkenal adalah:',
      options: ['"On ne voit bien qu\'avec le cœur. L\'essentiel est invisible pour les yeux."', '"L\'amour est aveugle."', '"La vie est belle."', '"Vouloir c\'est pouvoir."'],
      correctOptionIndex: 0,
      explanation: '"Hanya dengan hatilah seseorang dapat melihat dengan benar; apa yang terpenting tidak terlihat oleh mata."',
    ),
    QuestionItem(
      id: 'sas_pra_038',
      questionText: 'Aturan tata bahasa Prancis untuk modus "Subjonctif" digunakan untuk mengekspresikan:',
      options: ['Keraguan, keinginan, emosi, ketidakpastian, atau keharusan subyektif', 'Kenyataan objektif pasti', 'Fakta sejarah masa lalu', 'Perintah langsung'],
      correctOptionIndex: 0,
      explanation: 'Subjonctif digunakan setelah ekspresi subyektif seperti "il faut que...", "je veux que...", "bien que...".',
    ),
    QuestionItem(
      id: 'sas_pra_039',
      questionText: 'Bentuk konjugasi Subjonctif Présent kata kerja "être" untuk subjek "que je" adalah:',
      options: ['sois', 'sois', 'soit', 'soyez'],
      correctOptionIndex: 0,
      explanation: 'Subjonctif dari être: que je sois, que tu sois, qu\'il soit, que nous soyons, que vous soyez, qu\'ils soient.',
    ),
    QuestionItem(
      id: 'sas_pra_040',
      questionText: 'Bentuk konjugasi Subjonctif Présent kata kerja "avoir" untuk subjek "que nous" adalah:',
      options: ['ayons', 'avons', 'ayez', 'aient'],
      correctOptionIndex: 0,
      explanation: 'Subjonctif dari avoir: que j\'aie, que tu aies, qu\'il ait, que nous ayons, que vous ayez, qu\'ils aient.',
    ),
    QuestionItem(
      id: 'sas_pra_041',
      questionText: 'Waktu lampau "Imparfait" dalam tata bahasa Prancis digunakan untuk:',
      options: ['Mendeskripsikan latar belakang, kebiasaan berulang masa lalu, atau keadaan yang berlangsung tanpa batas waktu jelas', 'Aksi tunggal yang selesai seketika', 'Masa depan dekat', 'Pengandaian mutlak'],
      correctOptionIndex: 0,
      explanation: 'Imparfait berfungsi sebagai deskripsi/kebiasaan masa lalu (contoh: Quand j\'étais jeune, je jouais au football).',
    ),
    QuestionItem(
      id: 'sas_pra_042',
      questionText: 'Waktu lampau "Passé Composé" digunakan untuk:',
      options: ['Aksi spesifik yang selesai pada waktu tertentu di masa lalu', 'Kebiasaan lama', 'Deskripsi cuaca masa lalu', 'Pengandaian syarat'],
      correctOptionIndex: 0,
      explanation: 'Passé composé menyatakan kejadian tunggal yang komplet di masa lalu.',
    ),
    QuestionItem(
      id: 'sas_pra_043',
      questionText: 'Kapan Participe Passé yang diikuti kata kerja bantu "avoir" HARUS bersesuaian (accord) dalam jenis dan jumlah?',
      options: ['Jika Objek Langsung (Complément d\'Objet Direct / COD) mendahului kata kerja', 'Selalu bersesuaian dengan subjek', 'Tidak pernah bersesuaian', 'Jika subjeknya wanita'],
      correctOptionIndex: 0,
      explanation: 'Aturan emas: Participe passé dengan avoir melakukan accord dengan COD HANYA JIKA COD tersebut terletak SEBELUM kata kerja (misal: Les fleurs que j\'ai achetées).',
    ),
    QuestionItem(
      id: 'sas_pra_044',
      questionText: 'Daftar kata kerja intrasitif gerak/keadaan (DR & MRS VANDERTRAMPP) serta kata kerja refleksif menggunakan kata kerja bantu apa pada bentuk Passé Composé?',
      options: ['être', 'avoir', 'faire', 'aller'],
      correctOptionIndex: 0,
      explanation: 'Kata kerja seperti venir, aller, mourir, naître, tomber menggunakan auxiliary "être" dan selalu accord dengan subjek.',
    ),
    QuestionItem(
      id: 'sas_pra_045',
      questionText: 'Kata ganti objek langsung (COD / Pronoms Compléments d\'Objet Direct) orang ketiga tunggal adalah:',
      options: ['le / la / l\'', 'lui', 'y', 'en'],
      correctOptionIndex: 0,
      explanation: 'COD menggantikan benda/orang langsung tanpa preposisi (Je le vois).',
    ),
    QuestionItem(
      id: 'sas_pra_046',
      questionText: 'Kata ganti objek tidak langsung (COI / Pronoms Compléments d\'Objet Indirect) orang ketiga tunggal (à + personne) adalah:',
      options: ['lui', 'le', 'y', 'en'],
      correctOptionIndex: 0,
      explanation: 'COI (lui) menggantikan "à + orang" tunggal (Je lui parle = Je parle à Paul).',
    ),
    QuestionItem(
      id: 'sas_pra_047',
      questionText: 'Kata ganti adverbial "Y" menggantikan tempat atau frasa yang diawali preposisi:',
      options: ['à / dans / en / sur (menunjukkan tempat/tujuan)', 'de', 'par', 'avec'],
      correctOptionIndex: 0,
      explanation: 'Pronom "Y" menggantikan lokasi (J\'y vais = Je vais à Paris).',
    ),
    QuestionItem(
      id: 'sas_pra_048',
      questionText: 'Kata ganti adverbial "EN" menggantikan jumlah, partitif, atau frasa yang diawali preposisi:',
      options: ['de / du / de la / des', 'à', 'dans', 'pour'],
      correctOptionIndex: 0,
      explanation: 'Pronom "EN" menggantikan kuantitas atau de + noun (J\'en veux = Je veux du pain).',
    ),
    QuestionItem(
      id: 'sas_pra_049',
      questionText: 'Fenomena pelafalan fonetik bahasa Prancis di mana konsonan akhir yang biasanya bisu dilafalkan karena diikuti kata diawali vokal (contoh: les_amis [lesami]) dinamakan:',
      options: ['La Liaison (Pengikatan)', 'L\'Élision (Pelesapan)', 'L\'Enchaînement', 'La Nasalisation'],
      correctOptionIndex: 0,
      explanation: 'Liaison menghubungkan konsonan akhir bisu dengan vokal kata berikutnya.',
    ),
    QuestionItem(
      id: 'sas_pra_050',
      questionText: 'Pelesapan vokal akhir (seperti e pada le/la/de) digantikan tanda apostrof di depan kata berawal vokal (contoh: l\'eau, j\'aime) dinamakan:',
      options: ['L\'Élision', 'La Liaison', 'L\'Assimilation', 'L\'Aspiration'],
      correctOptionIndex: 0,
      explanation: 'Élision menghilangkan vokal e/a sebelum vokal atau h muet.',
    ),
    QuestionItem(
      id: 'sas_pra_051',
      questionText: 'Huruf "H" dalam bahasa Prancis terbagi dua yaitu "H muet" dan "H aspiré". Perlakuan terhadap "H aspiré" adalah:',
      options: ['TIDAK boleh dilakukan liaison maupun élision (contoh: le héros, les héros)', 'Boleh dilakukan liaison', 'Dilafalkan seperti h bahasa Inggris', 'Selalu dianggap vokal'],
      correctOptionIndex: 0,
      explanation: 'H aspiré mencegah pengikatan liaison dan elisi (le héros, BUKAN l\'héros).',
    ),
    QuestionItem(
      id: 'sas_pra_052',
      questionText: 'Metrum puisi klasik Prancis tradisional yang terdiri dari 12 suku kata (syllabes) per baris dinamakan:',
      options: ['L\'Alexandrin', 'Le Décasyllabe', 'L\'Octosyllabe', 'Le Vers libre'],
      correctOptionIndex: 0,
      explanation: 'Alexandrin adalah standar puisi berterima 12 suku kata karya Corneille, Racine, dan Hugo.',
    ),
    QuestionItem(
      id: 'sas_pra_053',
      questionText: 'Pemotongan ritme di tengah baris Alexandrin (setelah suku kata ke-6) dinamakan:',
      options: ['La Césure (Kaesura)', 'L\'Enjambement', 'Le Strophe', 'L\'Hemistiche'],
      correctOptionIndex: 0,
      explanation: 'Césure membagi Alexandrin menjadi dua bagian (hémistiches) masing-masing 6 suku kata.',
    ),
    QuestionItem(
      id: 'sas_pra_054',
      questionText: 'Teknik puisi di mana makna klausa melimpah melewati akhir baris puisi ke baris berikutnya dinamakan:',
      options: ['L\'Enjambement', 'La Césure', 'L\'Allitération', 'La Rime croisée'],
      correctOptionIndex: 0,
      explanation: 'Enjambement menyambung kalimat tanpa jeda di akhir baris.',
    ),
    QuestionItem(
      id: 'sas_pra_055',
      questionText: 'Skema rima puisi berturut-turut (Rimes suivies / plate) berpolakan:',
      options: ['AABB', 'ABAB', 'ABBA', 'ABCB'],
      correctOptionIndex: 0,
      explanation: 'Rimes suivies: AABB. Rimes croisées: ABAB. Rimes embrassées: ABBA.',
    ),
    QuestionItem(
      id: 'sas_pra_056',
      questionText: 'Skema rima puisi silang (Rimes croisées) berpolakan:',
      options: ['ABAB', 'AABB', 'ABBA', 'AAAA'],
      correctOptionIndex: 0,
      explanation: 'Rimes croisées melingkupi skema ABAB.',
    ),
    QuestionItem(
      id: 'sas_pra_057',
      questionText: 'Skema rima puisi peluk (Rimes embrassées) berpolakan:',
      options: ['ABBA', 'AABB', 'ABAB', 'ABCD'],
      correctOptionIndex: 0,
      explanation: 'Rimes embrassées memeluk rima tengah: ABBA.',
    ),
    QuestionItem(
      id: 'sas_pra_058',
      questionText: 'Lembaga kebahasaan tertinggi pengawal kemurnian dan standar Bahasa Prancis yang didirikan Cardinal Richelieu pada tahun 1635 adalah:',
      options: ['L\'Académie française', 'La Sorbonne', 'Le Collège de France', 'L\'Institut de France'],
      correctOptionIndex: 0,
      explanation: 'Académie française beranggotakan 40 pengawal bahasa berjuluk "Les Immortels".',
    ),
    QuestionItem(
      id: 'sas_pra_059',
      questionText: 'Kamus bahasa Prancis definitif paling terkenal yang diterbitkan oleh Pierre Larousse pada abad ke-19 adalah:',
      options: ['Le Petit Larousse / Grand Dictionnaire universel', 'Le Robert', 'Dictionnaire de l\'Académie', 'Littré'],
      correctOptionIndex: 0,
      explanation: 'Éditions Larousse adalah penerbit kamus dan ensiklopedia terbesar di Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_060',
      questionText: 'Penghargaan sastra paling bergengsi di Prancis yang dianugerahkan setiap bulan November sejak 1903 adalah:',
      options: ['Le Prix Goncourt', 'Le Prix Renaudot', 'Le Prix Femina', 'Le Prix Interallié'],
      correctOptionIndex: 0,
      explanation: 'Prix Goncourt memberikan kehormatan tertinggi bagi prosa novel Prancis terbaik tiap tahunnya.',
    ),
    QuestionItem(
      id: 'sas_pra_061',
      questionText: 'Gerakan teater abad ke-20 yang memopulerkan absurditas kehidupan (Teater Absurd) dengan dramawan Samuel Beckett ("En attendant Godot") dan Eugène Ionesco ("La Cantatrice chauve") dinamakan:',
      options: ['Le Théâtre de l\'Absurde', 'Le Théâtre Classique', 'Le Nouveau Roman', 'Le Surréalisme'],
      correctOptionIndex: 0,
      explanation: 'Teater Absurd menolak logika drama tradisional untuk merepresentasikan absurditas eksistensi.',
    ),
    QuestionItem(
      id: 'sas_pra_062',
      questionText: 'Dalam drama Samuel Beckett "En attendant Godot" (Menunggu Godot), tokoh Vladimir dan Estragon:',
      options: ['Menunggu sosok Godot yang tidak pernah datang di pinggir jalan dekat pohon', 'Melakukan perjalanan ke luar negeri', 'Bertengkar memperebutkan harta', 'Menghadapi pengadilan'],
      correctOptionIndex: 0,
      explanation: 'Menunggu Godot adalah alegori penantian absurd manusia tanpa kepastian.',
    ),
    QuestionItem(
      id: 'sas_pra_063',
      questionText: 'Drama Eugène Ionesco tentang warga kota yang satu per satu berubah menjadi badak sebagai alegori totalitarianisme berjudul:',
      options: ['Rhinocéros (1959)', 'La Cantatrice chauve', 'La Leçon', 'Les Chaises'],
      correctOptionIndex: 0,
      explanation: 'Rhinocéros mengkritik konformisme masal terhadap ideologi fasisme/totaliter.',
    ),
    QuestionItem(
      id: 'sas_pra_064',
      questionText: 'Gerakan eksperimental novel Prancis 1950-an (Nouveau Roman) yang menolak karakter dan plot tradisional dipelopori oleh:',
      options: ['Alain Robbe-Grillet, Nathalie Sarraute, dan Michel Butor', 'Sartre dan Camus', 'Hugo dan Balzac', 'Duras dan Sagan'],
      correctOptionIndex: 0,
      explanation: 'Nouveau Roman berfokus pada deskripsi objektif persepsi fisik.',
    ),
    QuestionItem(
      id: 'sas_pra_065',
      questionText: 'Gerakan seni dan sastra Surealisme (Le Surréalisme) yang meluncurkan "Manifeste du surréalisme" pada tahun 1924 dipimpin oleh:',
      options: ['André Breton', 'Paul Éluard', 'Louis Aragon', 'Tristan Tzara'],
      correctOptionIndex: 0,
      explanation: 'André Breton mendefinisikan Surealisme sebagai otomatisme psikis murni tanpa kendali akal.',
    ),
    QuestionItem(
      id: 'sas_pra_066',
      questionText: 'Gerakan anti-seni radikal pendahulu Surealisme yang lahir di Zurich pada Perang Dunia I dinamakan:',
      options: ['Le Dadaïsme (Dada)', 'Le Cubisme', 'Le Futurisme', 'Le Symbolisme'],
      correctOptionIndex: 0,
      explanation: 'Dada dipelopori Tristan Tzara menolak estetika perang borjuis.',
    ),
    QuestionItem(
      id: 'sas_pra_067',
      questionText: 'Penyair Dadais dan Surealis yang menulis puisi cinta "La terre est bleue comme une orange" adalah:',
      options: ['Paul Éluard', 'André Breton', 'Louis Aragon', 'Robert Desnos'],
      correctOptionIndex: 0,
      explanation: 'Paul Éluard mengarang puisi metafora surealisme terkenal ini.',
    ),
    QuestionItem(
      id: 'sas_pra_068',
      questionText: 'Pengarang dan pilot tempur yang mengarang "Vol de nuit" (Penerbangan Malam) dan "Terre des hommes" adalah:',
      options: ['Antoine de Saint-Exupéry', 'André Malraux', 'Louis-Ferdinand Céline', 'Romain Gary'],
      correctOptionIndex: 0,
      explanation: 'Saint-Exupéry mendokumentasikan heroism profesi penerbang pos udara awal.',
    ),
    QuestionItem(
      id: 'sas_pra_069',
      questionText: 'Novelis dan Menteri Kebudayaan Prancis yang mengarang novel Revolusi Tiongkok "La Condition humaine" (1933) adalah:',
      options: ['André Malraux', 'Antoine de Saint-Exupéry', 'Jean Giraudoux', 'François Mauriac'],
      correctOptionIndex: 0,
      explanation: 'André Malraux memenangkan Prix Goncourt atas "La Condition humaine".',
    ),
    QuestionItem(
      id: 'sas_pra_070',
      questionText: 'Novel polemik kontroversial gaya bahasa lisan "Voyage au bout de la nuit" (1932) ditulis oleh:',
      options: ['Louis-Ferdinand Céline', 'Marcel Proust', 'André Gide', 'Georges Bernanos'],
      correctOptionIndex: 0,
      explanation: 'Céline merevolusi prosa Prancis dengan ritme argot (slang) lisan.',
    ),
    QuestionItem(
      id: 'sas_pra_071',
      questionText: 'Novelis penerima Nobel Sastra 1947 pengarang "Les Faux-Monnayeurs" (The Counterfeiters) dan "L\'Immoraliste" adalah:',
      options: ['André Gide', 'François Mauriac', 'Roger Martin du Gard', 'Paul Claudel'],
      correctOptionIndex: 0,
      explanation: 'André Gide mengeksplorasi kebebasan individu dan konflik kejujuran moral.',
    ),
    QuestionItem(
      id: 'sas_pra_072',
      questionText: 'Pengarang Katolik penerima Nobel Sastra 1952 yang mengarang novel "Thérèse Desqueyroux" dan "Le Nœud de serpents" adalah:',
      options: ['François Mauriac', 'Georges Bernanos', 'Paul Claudel', 'Julien Green'],
      correctOptionIndex: 0,
      explanation: 'François Mauriac membedah dosa dan penebusan dalam keluarga borjuis Bordeaux.',
    ),
    QuestionItem(
      id: 'sas_pra_073',
      questionText: 'Satu-satunya pengarang yang memenangkan Prix Goncourt DUA KALI (dengan menggunakan nama pena Émile Ajar untuk yang kedua) adalah:',
      options: ['Romain Gary (Romain Kacew)', 'Boris Vian', 'Raymond Queneau', 'Henri Troyat'],
      correctOptionIndex: 0,
      explanation: 'Romain Gary memenangkan Prix Goncourt 1956 (Les Racines du ciel) dan 1975 (La Vie devant soi sebagai Émile Ajar).',
    ),
    QuestionItem(
      id: 'sas_pra_074',
      questionText: 'Kelompok penulis dan matematikawan eksperimental Prancis (OU.LI.PO.) yang menciptakan karya berbatasan aturan ketat dipelopori oleh:',
      options: ['Raymond Queneau dan François Le Lionnais', 'Breton dan Tzara', 'Sartre dan Camus', 'Robbe-Grillet dan Sarraute'],
      correctOptionIndex: 0,
      explanation: 'Oulipo (Ouvroir de littérature potentielle) menciptakan eksperimen sastra unik.',
    ),
    QuestionItem(
      id: 'sas_pra_075',
      questionText: 'Anggota Oulipo Georges Perec mengarang novel "La Disparition" (1969) dengan keunikan lipogram ekstrem yaitu:',
      options: ['Seluruh novel ditulis TANPA menggunakan huruf vokal "E" sama sekali', 'Ditulis tanpa tanda baca', 'Hanya menggunakan kata 3 huruf', 'Ditulis dari kanan ke kiri'],
      correctOptionIndex: 0,
      explanation: 'Perec berhasil menulis novel 300 halaman tanpa huruf E (vokal paling umum bahasa Prancis).',
    ),
    QuestionItem(
      id: 'sas_pra_076',
      questionText: 'Tiga jenis ragam register bahasa Prancis terbagi menjadi:',
      options: ['Formel (Soutenu), Courant (Standar), dan Familier / Argot (Informal/Gaul)', 'Parisian, Provençal, Breton', 'Kuno, Abad Pertengahan, Modern', 'Tulisan, Lisan, Isyarat'],
      correctOptionIndex: 0,
      explanation: 'Register menentukan variasi pilihan kata sesuai konteks sosial.',
    ),
    QuestionItem(
      id: 'sas_pra_077',
      questionText: 'Bahasa gaul balikan suku kata Prancis (Syllable Reversal Slang) seperti "verlan" (dari l\'envers) mengubah kata "femme" menjadi:',
      options: ['meuf', 'keuf', 'reubeu', 'zef'],
      correctOptionIndex: 0,
      explanation: 'Verlan membalik suku kata: femme -> meuf, arabe -> reubeu, flic -> keuf.',
    ),
    QuestionItem(
      id: 'sas_pra_078',
      questionText: 'Verlan untuk kata "café" adalah:',
      options: ['féca', 'céfa', 'kef', 'feca'],
      correctOptionIndex: 0,
      explanation: 'café [ka-fe] dibalik menjadi féca [fe-ka].',
    ),
    QuestionItem(
      id: 'sas_pra_079',
      questionText: 'Ragam bahasa daerah tradisional Selatan Prancis yang terpisah dari Bahasa Prancis Utara (Langue d\'oïl) dinamakan:',
      options: ['La Langue d\'oc (Occitan)', 'Le Breton', 'Le Basco', 'Le Corse'],
      correctOptionIndex: 0,
      explanation: 'Sejarah bahasa Prancis terbagi dua: Langue d\'oïl (Utara) dan Langue d\'oc (Selatan).',
    ),
    QuestionItem(
      id: 'sas_pra_080',
      questionText: 'Perintah raja François I pada tahun 1539 (Ordonnance de Villers-Cotterêts) menetapkan bahwa:',
      options: ['Bahasa Prancis menggantikan Bahasa Latin sebagai bahasa resmi hukum dan administrasi kerajaan', 'Bahasa Latin wajib digunakan', 'Buku-buku harus dibakar', 'Pendidikan gratis dibuat'],
      correctOptionIndex: 0,
      explanation: 'Ordonnance de Villers-Cotterêts mengukuhkan bahasa Prancis sebagai bahasa negara resmi.',
    ),
    QuestionItem(
      id: 'sas_pra_081',
      questionText: 'Di antara kata benda Prancis berikut, manakah yang berjenis kelamin FEMININ (la / une)?',
      options: ['la maison (rumah)', 'le livre (buku)', 'le soleil (matahari)', 'le problème (masalah)'],
      correctOptionIndex: 0,
      explanation: 'maison adalah kata benda feminin (la maison).',
    ),
    QuestionItem(
      id: 'sas_pra_082',
      questionText: 'Di antara kata benda yang berakhiran -tion (seperti la nation, la situation), mayoritas besar bergender:',
      options: ['Féminin', 'Masculin', 'Neutre', 'Pluriel'],
      correctOptionIndex: 0,
      explanation: 'Hampir 99% kata benda berakhiran -tion bergender feminin.',
    ),
    QuestionItem(
      id: 'sas_pra_083',
      questionText: 'Kata benda serapan berakhiran -isme (seperti le romantisme, le réalisme) bergender:',
      options: ['Masculin', 'Féminin', 'Neutre', 'Pluriel'],
      correctOptionIndex: 0,
      explanation: 'Akhiran -isme selalu bergender maskulin.',
    ),
    QuestionItem(
      id: 'sas_pra_084',
      questionText: 'Kalimat pengandaian tipe 3 (Syarat tidak mungkin di masa lalu) menggunakan pola:',
      options: ['Si + Plus-que-parfait ---> Conditionnel Passé', 'Si + Présent ---> Futur Simple', 'Si + Imparfait ---> Conditionnel Présent', 'Si + Passé composé ---> Présent'],
      correctOptionIndex: 0,
      explanation: 'Pola Syarat Lampau: Si + Plus-que-parfait, Conditionnel passé (Si j\'avais su, je serais venu).',
    ),
    QuestionItem(
      id: 'sas_pra_085',
      questionText: 'Kalimat pengandaian tipe 2 (Pengandaian hipotetis masa kini) menggunakan pola:',
      options: ['Si + Imparfait ---> Conditionnel Présent', 'Si + Présent ---> Futur Simple', 'Si + Plus-que-parfait ---> Conditionnel Passé', 'Si + Subjonctif ---> Futur'],
      correctOptionIndex: 0,
      explanation: 'Pola Hipotetis: Si + Imparfait, Conditionnel présent (Si j\'avais l\'argent, j\'achèterais une voiture).',
    ),
    QuestionItem(
      id: 'sas_pra_086',
      questionText: 'Bentuk Conditionnel Présent dibentuk dari:',
      options: ['Radikal Futur Simple + Akhiran Imparfait (-ais, -ais, -ait, -ions, -iez, -aient)', 'Radikal Présent + Akhiran -er', 'Participe passé + avoir', 'Subjonctif + de'],
      correctOptionIndex: 0,
      explanation: 'Conditionnel présent memadukan radikal Futur dengan desinences Imparfait.',
    ),
    QuestionItem(
      id: 'sas_pra_087',
      questionText: 'Bentuk Passé Simple kata kerja kelompok 1 (-er seperti parler) untuk subjek "il" adalah:',
      options: ['parla', 'parlait', 'parlaient', 'parla-t-il'],
      correctOptionIndex: 0,
      explanation: 'Passé simple mengakhiri verba -er dengan -a (il parla, elle chanta) dalam sastra tulis.',
    ),
    QuestionItem(
      id: 'sas_pra_088',
      questionText: 'Waktu sastra "Passé Simple" digunakan khusus dalam:',
      options: ['Penulisan sastra formal / sejarah naratif (bukan percakapan lisan)', 'Percakapan sehari-hari', 'Pesan teks SMS', 'Iklan televisi'],
      correctOptionIndex: 0,
      explanation: 'Passé simple adalah tenses sastra murni tulisan (temps littéraire).',
    ),
    QuestionItem(
      id: 'sas_pra_089',
      questionText: 'Keluarga pengarang fiksi ilmiah klasik yang mengarang "Vingt Mille Lieues sous les mers" (20.000 Liga di Bawah Laut) dan "Le Tour du monde en quatre-vingts jours" adalah:',
      options: ['Jules Verne', 'H.G. Wells', 'Alexandre Dumas', 'René Barjavel'],
      correctOptionIndex: 0,
      explanation: 'Jules Verne adalah bapak visioner fiksi ilmiah petualangan Prancis.',
    ),
    QuestionItem(
      id: 'sas_pra_090',
      questionText: 'Kapten kapal selam Nautilus dalam novel Jules Verne "Vingt Mille Lieues sous les mers" bernama:',
      options: ['Capitaine Nemo', 'Capitaine Ahab', 'Capitaine Grant', 'Phileas Fogg'],
      correctOptionIndex: 0,
      explanation: 'Capitaine Nemo memimpin kapal selam canggih Nautilus.',
    ),
    QuestionItem(
      id: 'sas_pra_091',
      questionText: 'Pengarang novel fantasi distopia "La Nuit des temps" (1968) dan "Ravage" adalah:',
      options: ['René Barjavel', 'Jules Verne', 'Pierre Boulle', 'Bernard Werber'],
      correctOptionIndex: 0,
      explanation: 'René Barjavel memelopori fiksi ilmiah modern Prancis dan Paradox Kakek (Grandfather Paradox).',
    ),
    QuestionItem(
      id: 'sas_pra_092',
      questionText: 'Penulis novel "La Planète des singes" (Planet of the Apes, 1963) dan "Le Pont de la rivière Kwaï" adalah:',
      options: ['Pierre Boulle', 'René Barjavel', 'Vercors', 'J.H. Rosny aîné'],
      correctOptionIndex: 0,
      explanation: 'Pierre Boulle mengarang novel fiksi ilmiah ikonik Planet para Kera.',
    ),
    QuestionItem(
      id: 'sas_pra_093',
      questionText: 'Penulis novel trilogi populer tentang semut "Les Fourmis" (1991) adalah:',
      options: ['Bernard Werber', 'Pierre Boulle', 'Amélie Nothomb', 'Marc Levy'],
      correctOptionIndex: 0,
      explanation: 'Bernard Werber menggabungkan sains entomologi dan fiksi filsafat.',
    ),
    QuestionItem(
      id: 'sas_pra_094',
      questionText: 'Penulis Belgia kontemporer berbahasa Prancis yang mengarang novel autobiografis "Stupeur et Tremblements" (1999) adalah:',
      options: ['Amélie Nothomb', 'Georges Simenon', 'Suzanne Lilar', 'Lise Thiry'],
      correctOptionIndex: 0,
      explanation: 'Amélie Nothomb mengisahkan pengalamannya bekerja di perusahaan Jepang.',
    ),
    QuestionItem(
      id: 'sas_pra_095',
      questionText: 'Penulis novel detektif pencipta karakter Commissaire Maigret adalah maestro asal Belgia:',
      options: ['Georges Simenon', 'Agatha Christie', 'Maurice Leblanc', 'Gaston Leroux'],
      correctOptionIndex: 0,
      explanation: 'Georges Simenon mengarang puluhan novel investigasi Detektif Maigret.',
    ),
    QuestionItem(
      id: 'sas_pra_096',
      questionText: 'Pengarang kisah pencuri pria terhormat "Arsène Lupin, gentleman-cambrioleur" adalah:',
      options: ['Maurice Leblanc', 'Gaston Leroux', 'Émile Gaboriau', 'Eugène Sue'],
      correctOptionIndex: 0,
      explanation: 'Maurice Leblanc menciptakan karakter Arsène Lupin pada tahun 1905.',
    ),
    QuestionItem(
      id: 'sas_pra_097',
      questionText: 'Pengarang novel misteri gothic "Le Fantôme de l\'Opéra" (The Phantom of the Opera, 1910) adalah:',
      options: ['Gaston Leroux', 'Maurice Leblanc', 'Theophile Gautier', 'Prosper Mérimée'],
      correctOptionIndex: 0,
      explanation: 'Gaston Leroux mengarang kisah Erik sang hantu di Opéra Garnier Paris.',
    ),
    QuestionItem(
      id: 'sas_pra_098',
      questionText: 'Novelis kontemporer penerima Nobel Sastra 2008 yang mengarang novel "Désert" dan "Le Procès-verbal" adalah:',
      options: ['J.M.G. Le Clézio', 'Patrick Modiano', 'Annie Ernaux', 'Jean-Marie Gustave'],
      correctOptionIndex: 0,
      explanation: 'J.M.G. Le Clézio dianugerahi Nobel atas keindahan eksplorasi budaya luar peradaban barat.',
    ),
    QuestionItem(
      id: 'sas_pra_099',
      questionText: 'Novelis penerima Nobel Sastra 2014 yang berfokus pada ingatan kolektif pendudukan Jerman di Paris dalam "Rue des Boutiques Sombres" adalah:',
      options: ['Patrick Modiano', 'J.M.G. Le Clézio', 'Annie Ernaux', 'Michel Houellebecq'],
      correctOptionIndex: 0,
      explanation: 'Patrick Modiano memenangkan Nobel 2014 atas seni ingatan evocatifnya.',
    ),
    QuestionItem(
      id: 'sas_pra_100',
      questionText: 'Penulis wanita penerima Nobel Sastra 2022 yang memelopori memoir sosiologis-autobiografis "Les Années" (The Years) adalah:',
      options: ['Annie Ernaux', 'Patrick Modiano', 'Marguerite Duras', 'Nathalie Sarraute'],
      correctOptionIndex: 0,
      explanation: 'Annie Ernaux dianugerahi Nobel Sastra 2022 atas keberanian analisis ingatan kolektif dan pribadi.',
    ),
  ];
}
