import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraArabQuestions() {
  return const [
    QuestionItem(
      id: 'sas_arab_001',
      questionText: 'Ilmu dalam tata bahasa Arab yang mempelajari tentang perubahan harakat akhir kata (I\'rab) dinamakan ilmu:',
      options: ['Nahwu', 'Sharaf', 'Balaghah', 'Arudh'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Nahwu mempelajari kaidah akhir kata dan struktur kalimat Arab.',
    ),
    QuestionItem(
      id: 'sas_arab_002',
      questionText: 'Ilmu yang mempelajari tentang bentuk asal-usul kata dan perubahan pola kata (Wazan/Tasrif) dinamakan ilmu:',
      options: ['Sharaf (Morfologi Arab)', 'Nahwu', 'Badi\'', 'Bayan'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Sharaf mempelajari pembentukan dan perubahan wazan kata.',
    ),
    QuestionItem(
      id: 'sas_arab_003',
      questionText: 'Ilmu yang mempelajari keindahan sastra, gaya bahasa, dan kiasan retorika Arab dinamakan ilmu:',
      options: ['Balaghah', 'Nahwu', 'Tajwid', 'Khat'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Balaghah adalah sastra retorika Arab (Bayan, Ma\'ani, Badi\').',
    ),
    QuestionItem(
      id: 'sas_arab_004',
      questionText: 'Tiga jenis pembagian kata (Kelimah) dalam Bahasa Arab terdiri dari Isim, Fi\'il, dan:',
      options: ['Harf', 'Fi\'il Amar', 'Mubtada', 'Khabar'],
      correctOptionIndex: 0,
      explanation: 'Kata dalam bahasa Arab dibagi 3: Isim (kata benda/sifat), Fi\'il (kata kerja), Harf (kata hubung).',
    ),
    QuestionItem(
      id: 'sas_arab_005',
      questionText: 'Kata yang menunjukkan arti benda, nama, sifat, atau tempat tanpa terikat oleh waktu dinamakan:',
      options: ['Isim', 'Fi\'il', 'Harf', 'Zaraf'],
      correctOptionIndex: 0,
      explanation: 'Isim adalah noun (kata benda/sifat/nama).',
    ),
    QuestionItem(
      id: 'sas_arab_006',
      questionText: 'Kata yang menunjukkan suatu perbuatan yang terikat dengan dimensi waktu (lampau, sekarang, mendatang) dinamakan:',
      options: ['Fi\'il', 'Isim', 'Harf', 'Sifat'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il adalah verb (kata kerja).',
    ),
    QuestionItem(
      id: 'sas_arab_007',
      questionText: 'Fi\'il yang menunjukkan pekerjaan yang telah lampau/selesai dilakukan dinamakan Fi\'il:',
      options: ['Mazi (Past Tense)', 'Mudhari\'', 'Amar', 'Nahi'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Mazi menunjukkan masa lalu.',
    ),
    QuestionItem(
      id: 'sas_arab_008',
      questionText: 'Fi\'il yang menunjukkan pekerjaan yang sedang dilakukan atau akan dilakukan dinamakan Fi\'il:',
      options: ['Mudhari\' (Present/Future)', 'Mazi', 'Amar', 'Majhul'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Mudhari\' menunjukkan masa sekarang/depan.',
    ),
    QuestionItem(
      id: 'sas_arab_009',
      questionText: 'Fi\'il yang menunjukkan perintah perbuatan dinamakan Fi\'il:',
      options: ['Amar (Imperatif)', 'Nahi', 'Mazi', 'Mudhari\''],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Amar adalah kalimat perintah.',
    ),
    QuestionItem(
      id: 'sas_arab_010',
      questionText: 'Tanda I\'rab Marfu\' dasar (utama) pada Isim Mufrad adalah harakat:',
      options: ['Dammah (ُ)', 'Fathah', 'Kasrah', 'Sukun'],
      correctOptionIndex: 0,
      explanation: 'Dammah adalah tanda utama I\'rab Raf\'.',
    ),
    QuestionItem(
      id: 'sas_arab_011',
      questionText: 'Tanda I\'rab Mansub dasar (utama) pada Isim Mufrad adalah harakat:',
      options: ['Fathah (َ)', 'Dammah', 'Kasrah', 'Sukun'],
      correctOptionIndex: 0,
      explanation: 'Fathah adalah tanda utama I\'rab Nasab.',
    ),
    QuestionItem(
      id: 'sas_arab_012',
      questionText: 'Tanda I\'rab Majrur dasar (utama) pada Isim Mufrad adalah harakat:',
      options: ['Kasrah (ِ)', 'Dammah', 'Fathah', 'Tanwin'],
      correctOptionIndex: 0,
      explanation: 'Kasrah adalah tanda utama I\'rab Jar.',
    ),
    QuestionItem(
      id: 'sas_arab_013',
      questionText: 'Tanda I\'rab Majzum dasar (utama) pada Fi\'il Mudhari\' sahih akhir adalah:',
      options: ['Sukun (ْ)', 'Kasrah', 'Fathah', 'Dammah'],
      correctOptionIndex: 0,
      explanation: 'Sukun adalah tanda utama I\'rab Jazm.',
    ),
    QuestionItem(
      id: 'sas_arab_014',
      questionText: 'Jumlah (kalimat) dalam Bahasa Arab yang diawali dengan Isim dinamakan Jumlah:',
      options: ['Ismiyyah', 'Fi\'liyyah', 'Zarfiyyah', 'Syibh-ul Jumlah'],
      correctOptionIndex: 0,
      explanation: 'Jumlah Ismiyyah diawali Isim dan terdiri dari Mubtada dan Khabar.',
    ),
    QuestionItem(
      id: 'sas_arab_015',
      questionText: 'Jumlah (kalimat) dalam Bahasa Arab yang diawali dengan Fi\'il dinamakan Jumlah:',
      options: ['Fi\'liyyah', 'Ismiyyah', 'Na\'tiyyah', 'Idhafiyyah'],
      correctOptionIndex: 0,
      explanation: 'Jumlah Fi\'liyyah diawali Fi\'il dan terdiri dari Fi\'il, Fa\'il (dan Ma\'ful).',
    ),
    QuestionItem(
      id: 'sas_arab_016',
      questionText: 'Subjek pelaku dalam Jumlah Fi\'liyyah yang I\'rab-nya selalu Marfu\' dinamakan:',
      options: ['Fa\'il', 'Ma\'ful bih', 'Mubtada', 'Na\'at'],
      correctOptionIndex: 0,
      explanation: 'Fa\'il adalah pelaku tindakan (subjek).',
    ),
    QuestionItem(
      id: 'sas_arab_017',
      questionText: 'Objek yang dikenai perbuatan dalam Jumlah Fi\'liyyah yang I\'rab-nya Mansub dinamakan:',
      options: ['Ma\'ful bih', 'Fa\'il', 'Khabar', 'Hal'],
      correctOptionIndex: 0,
      explanation: 'Ma\'ful bih adalah objek penderita.',
    ),
    QuestionItem(
      id: 'sas_arab_018',
      questionText: 'Isim diterangkan yang berada di awal Jumlah Ismiyyah dinamakan:',
      options: ['Mubtada', 'Khabar', 'Badal', 'Na\'at'],
      correctOptionIndex: 0,
      explanation: 'Mubtada adalah subjek pemula kalimat nomial.',
    ),
    QuestionItem(
      id: 'sas_arab_019',
      questionText: 'Bagian penyempurna makna Mubtada dalam Jumlah Ismiyyah dinamakan:',
      options: ['Khabar', 'Mubtada', 'Sifat', 'Mudhaf'],
      correctOptionIndex: 0,
      explanation: 'Khabar menerangkan keadaan Mubtada.',
    ),
    QuestionItem(
      id: 'sas_arab_020',
      questionText: 'Isim yang menunjukkan jumlah tunggal (satu) dinamakan Isim:',
      options: ['Mufrad', 'Musanna', 'Jamak', 'Ma\'rifah'],
      correctOptionIndex: 0,
      explanation: 'Isim Mufrad menunjukkan benda satu.',
    ),
    QuestionItem(
      id: 'sas_arab_021',
      questionText: 'Isim yang menunjukkan jumlah dua (ganda) dengan tambahan alif-nun (ان) atau ya-nun (ين) dinamakan Isim:',
      options: ['Musanna (Tasnawiyyah)', 'Mufrad', 'Jamak Takseer', 'Jamak Muzakkar'],
      correctOptionIndex: 0,
      explanation: 'Isim Musanna menunjukkan dua benda.',
    ),
    QuestionItem(
      id: 'sas_arab_022',
      questionText: 'Isim yang menunjukkan jumlah tiga atau lebih dinamakan Isim:',
      options: ['Jamak', 'Musanna', 'Mufrad', 'Nakirah'],
      correctOptionIndex: 0,
      explanation: 'Jamak bermakna jamak (banyak/lebih dari dua).',
    ),
    QuestionItem(
      id: 'sas_arab_023',
      questionText: 'Jamak yang beraturan untuk laki-laki dengan tambahan wau-nun (ون) atau ya-nun (ين) dinamakan:',
      options: ['Jamak Muzakkar Salim', 'Jamak Muannas Salim', 'Jamak Taksir', 'Isim Munsarif'],
      correctOptionIndex: 0,
      explanation: 'Jamak Muzakkar Salim bentuk jamak teratur laki-laki.',
    ),
    QuestionItem(
      id: 'sas_arab_024',
      questionText: 'Jamak yang beraturan untuk perempuan dengan tambahan alif-ta (ات) dinamakan:',
      options: ['Jamak Muannas Salim', 'Jamak Muzakkar Salim', 'Jamak Taksir', 'Isim Jamak'],
      correctOptionIndex: 0,
      explanation: 'Jamak Muannas Salim bentuk jamak teratur perempuan.',
    ),
    QuestionItem(
      id: 'sas_arab_025',
      questionText: 'Jamak yang tidak beraturan dan mengalami perubahan susunan pola kata dasarnya dinamakan:',
      options: ['Jamak Taksir', 'Jamak Salim', 'Musanna', 'Isim Asmaul Khamsah'],
      correctOptionIndex: 0,
      explanation: 'Jamak Taksir memecah susunan bentuk tunggal (misal: Kitabun -> Kutubun).',
    ),
    QuestionItem(
      id: 'sas_arab_026',
      questionText: 'Kumpulan puisi-puisi terbaik zaman Jahiliyah yang ditulis dengan tinta emas dan digantung di Ka\'bah dinamakan:',
      options: ['Al-Mu\'allaqat', 'Al-Hamasah', 'Diwan Abu Nawas', 'Al-Alfiyyah'],
      correctOptionIndex: 0,
      explanation: 'Al-Mu\'allaqat adalah 7-10 mahakarya syair Arab Jahiliyah.',
    ),
    QuestionItem(
      id: 'sas_arab_027',
      questionText: 'Penyair klasik Arab terkemuka zaman Jahiliyah pengarang Mu\'allaqat tentang ratapan reruntuhan dinamakan:',
      options: ['Imru\'ul Qays', 'Al-Mutanabbi', 'Abu Nawas', 'Ahmad Syawqi'],
      correctOptionIndex: 0,
      explanation: 'Imru\'ul Qays dijuluki sebagai Raja Penyair Jahiliyah.',
    ),
    QuestionItem(
      id: 'sas_arab_028',
      questionText: 'Penyair legendaris zaman Abbasiyah yang terkenal dengan puisi humor, kiasan, dan kecerdasannya adalah:',
      options: ['Abu Nawas (Abu Ali al-Hasan)', 'Al-Mutanabbi', 'Al-Ma\'arri', 'Imru\'ul Qays'],
      correctOptionIndex: 0,
      explanation: 'Abu Nawas adalah pujangga terbesar Istana Harun al-Rasyid.',
    ),
    QuestionItem(
      id: 'sas_arab_029',
      questionText: 'Penyair terbesar Arab era Abbasiyah yang sangat terkenal dengan keagungan syair pujian dan hikmahnya adalah:',
      options: ['Al-Mutanabbi', 'Abu Nuwas', 'Nizar Qabbani', 'Mahmud Darwish'],
      correctOptionIndex: 0,
      explanation: 'Al-Mutanabbi dianggap pujangga puncak sastra Arab klasik.',
    ),
    QuestionItem(
      id: 'sas_arab_030',
      questionText: 'Penyair modern Mesir yang mendapat julukan "Amir syu\'ara" (Pangeran Para Penyair) adalah:',
      options: ['Ahmad Syawqi', 'Kahlil Gibran', 'Nizar Qabbani', 'Taha Husayn'],
      correctOptionIndex: 0,
      explanation: 'Ahmad Syawqi dianugerahi gelar Amir syu\'ara.',
    ),
    QuestionItem(
      id: 'sas_arab_031',
      questionText: 'Sastrawan dan filsuf Lebanon pembuat mahakarya "The Prophet" (Al-Nabi) yang memadukan sastra Arab-Barat adalah:',
      options: ['Kahlil Gibran', 'Mikhail Naimy', 'Mahmud Darwish', 'Adonis'],
      correctOptionIndex: 0,
      explanation: 'Kahlil Gibran pujangga романtis dunia asal Lebanon.',
    ),
    QuestionItem(
      id: 'sas_arab_032',
      questionText: 'Sastrawan buta legendaris Mesir pelopor novelis modern pengarang autobiografi "Al-Ayyam" adalah:',
      options: ['Taha Husayn', 'Naguib Mahfouz', 'Tawfiq al-Hakim', 'Al-Manfaluti'],
      correctOptionIndex: 0,
      explanation: 'Dr. Taha Husayn adalah Bapak Sastra Arab Modern.',
    ),
    QuestionItem(
      id: 'sas_arab_033',
      questionText: 'Sastrawan Arab pertama (asal Mesir) yang meraih Hadiah Nobel Sastra pada tahun 1988 adalah:',
      options: ['Naguib Mahfouz (Najib Mahfuz)', 'Taha Husayn', 'Kahlil Gibran', 'Ghassan Kanafani'],
      correctOptionIndex: 0,
      explanation: 'Naguib Mahfouz memenangkan Nobel Sastra lewat novel Trilogi Kairo.',
    ),
    QuestionItem(
      id: 'sas_arab_034',
      questionText: 'Penyair perjuangan nasional Palestina yang sangat terkenal dengan syair-syair perlawanan dan tanah air adalah:',
      options: ['Mahmud Darwish', 'Nizar Qabbani', 'Fadwa Tuqan', 'Adonis'],
      correctOptionIndex: 0,
      explanation: 'Mahmud Darwish adalah Suara Penyair Palestina.',
    ),
    QuestionItem(
      id: 'sas_arab_035',
      questionText: 'Ilmu dalam Balaghah yang mempelajari tentang perumpamaan (Tasybih), Majas, dan Kinayah dinamakan ilmu:',
      options: ['Bayan', 'Ma\'ani', 'Badi\'', 'Arudh'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Bayan membahas daya kiasan dan pembandingan makna.',
    ),
    QuestionItem(
      id: 'sas_arab_036',
      questionText: 'Penyerupaan suatu hal dengan hal lain menggunakan kata pembanding (Kaf/Ka-anna) dinamakan:',
      options: ['Tasybih', 'Majas Mursal', 'Isti\'arah', 'Kinayah'],
      correctOptionIndex: 0,
      explanation: 'Tasybih adalah similes / perumpamaan langsung.',
    ),
    QuestionItem(
      id: 'sas_arab_037',
      questionText: 'Penggunaan kata yang bukan pada makna aslinya karena ada hubungan kiasan (metafora) dinamakan:',
      options: ['Isti\'arah', 'Tasybih', 'Kinayah', 'Jinas'],
      correctOptionIndex: 0,
      explanation: 'Isti\'arah adalah metafora murni dalam retorika Arab.',
    ),
    QuestionItem(
      id: 'sas_arab_038',
      questionText: 'Ilmu dalam Balaghah yang mempelajari keindahan keharmonisan lafaz (seperti Sajak, Jinas) dan makna dinamakan ilmu:',
      options: ['Badi\'', 'Bayan', 'Ma\'ani', 'Nahwu'],
      correctOptionIndex: 0,
      explanation: 'Ilmu Badi\' berfokus pada keindahan ornamen kata.',
    ),
    QuestionItem(
      id: 'sas_arab_039',
      questionText: 'Persamaan bunyi sajak akhir pada dua kalimat atau lebih dalam prosa Arab dinamakan:',
      options: ['Saja\' (سَجَعٌ)', 'Jinas', 'Tabaq', 'Tawriyah'],
      correctOptionIndex: 0,
      explanation: 'Saja\' adalah rima sajak pada ujung wacana prosa.',
    ),
    QuestionItem(
      id: 'sas_arab_040',
      questionText: 'Penggunaan dua kata yang bentuk ejaannya hampir sama namun artinya berbeda dinamakan:',
      options: ['Jinas (جِنَاسٌ)', 'Saja\'', 'Tibaq', 'Muqabalah'],
      correctOptionIndex: 0,
      explanation: 'Jinas adalah pun/homonim dalam retorika Badi\'.',
    ),
    QuestionItem(
      id: 'sas_arab_041',
      questionText: 'Pengumpulan dua kata berlawanan arti (antonim) dalam satu kalimat dinamakan:',
      options: ['Tibaq (طِبَاقٌ)', 'Muqabalah', 'Jinas', 'Saja\''],
      correctOptionIndex: 0,
      explanation: 'Tibaq adalah penyebutan lawan kata (misal: siang dan malam).',
    ),
    QuestionItem(
      id: 'sas_arab_042',
      questionText: 'Ilmu yang mempelajari pola ritme dan metrum (Bahr) dalam bait-bait puisi Arab dinamakan ilmu:',
      options: ['\'Arudh & Qawafi', 'Balaghah', 'Sharaf', 'Khat'],
      correctOptionIndex: 0,
      explanation: 'Ilmu \'Arudh dirumuskan oleh Al-Khalil bin Ahmad al-Farahidi.',
    ),
    QuestionItem(
      id: 'sas_arab_043',
      questionText: 'Pencetus dan penemu kaidah Ilmu \'Arudh (metrum puisi) dan kamus Arab pertama (Kitab al-\'Ain) adalah:',
      options: ['Al-Khalil bin Ahmad al-Farahidi', 'Sibawayh', 'Abu al-Aswad al-Du\'ali', 'Ibn Jinni'],
      correctOptionIndex: 0,
      explanation: 'Al-Khalil adalah peletak dasar ilmu metrum \'Arudh.',
    ),
    QuestionItem(
      id: 'sas_arab_044',
      questionText: 'Tokoh tata bahasa Arab terbesar penulis kitab tata bahasa monumental "Al-Kitab" adalah:',
      options: ['Sibawayh', 'Al-Khalil', 'Ibn Malik', 'Al-Zamakhsyari'],
      correctOptionIndex: 0,
      explanation: 'Sibawayh dijuluki Imam Nahwu pencipta Al-Kitab.',
    ),
    QuestionItem(
      id: 'sas_arab_045',
      questionText: 'Kitab matan ilmu Nahwu berwujud 1000 bait puisi karangan Ibnu Malik yang sangat populer di pesantren dinamakan:',
      options: ['Alfiyyah Ibni Malik', 'Matan Jurumiyyah', 'Imriti', 'Mutammimah'],
      correctOptionIndex: 0,
      explanation: 'Alfiyyah Ibni Malik memuat 1000 bait kaidah Nahwu-Sharaf.',
    ),
    QuestionItem(
      id: 'sas_arab_046',
      questionText: 'Kitab dasar ringkas ilmu Nahwu karangan Syekh ash-Shanhaji yang menjadi rujukan awal dinamakan:',
      options: ['Matan Al-Ajurrumiyyah', 'Alfiyyah', 'Kafiyah', 'Shaban'],
      correctOptionIndex: 0,
      explanation: 'Al-Ajurrumiyyah ringkasan kaidah I\'rab populer.',
    ),
    QuestionItem(
      id: 'sas_arab_047',
      questionText: 'Dongeng klasik 1001 Malam yang memuat kisah Sinbad dan Aladdin dalam prosa Arab dinamakan:',
      options: ['Alf Lailah wa Lailah (أَلْفُ لَيْلَةٍ وَلَيْلَةٌ)', 'Kalilah wa Dimnah', 'Maqamat al-Hariri', 'Hayy ibn Yaqzan'],
      correctOptionIndex: 0,
      explanation: 'Alf Lailah wa Lailah karya sastra narasi dunia.',
    ),
    QuestionItem(
      id: 'sas_arab_048',
      questionText: 'Kumpulan fabel fiksi berkarakter binatang penerjemahan karya Ibn al-Muqaffa\' dinamakan:',
      options: ['Kalilah wa Dimnah', 'Alf Lailah', 'Maqamat', 'Risalat al-Ghufran'],
      correctOptionIndex: 0,
      explanation: 'Kalilah wa Dimnah fabel hikmah politik alegoris.',
    ),
    QuestionItem(
      id: 'sas_arab_049',
      questionText: 'Genre sastra prosa klasik Arab berhias sajak indah yang berisi kisah anekdot pengembaraan dinamakan:',
      options: ['Maqamat (مَقَامَات)', 'Qasidah', 'Ghazal', 'Risaalah'],
      correctOptionIndex: 0,
      explanation: 'Maqamat karya Al-Hamadhani & Al-Hariri berciri sajak prosais.',
    ),
    QuestionItem(
      id: 'sas_arab_050',
      questionText: 'Kumpulan puisi cinta dan kerinduan romantisme dalam tradisi puisi Arab klasik dinamakan tema:',
      options: ['Ghazal (غَزَلٌ)', 'Fakhr', 'Hija\'', 'Risa\''],
      correctOptionIndex: 0,
      explanation: 'Ghazal adalah genre puisi percintaan.',
    ),
    QuestionItem(
      id: 'sas_arab_051',
      questionText: 'Bait puisi Arab yang berisi kebanggaan atas suku, keberanian, atau diri sendiri dinamakan tema:',
      options: ['Fakhr (فَخْرٌ)', 'Hija\'', 'Madih', 'Zuhd'],
      correctOptionIndex: 0,
      explanation: 'Fakhr adalah puisi kebanggaan/kebangkitan kehormatan.',
    ),
    QuestionItem(
      id: 'sas_arab_052',
      questionText: 'Bait puisi Arab yang berisi celaan atau sindiran tajam kepada musuh dinamakan tema:',
      options: ['Hija\' (هَجَاءٌ)', 'Madih', 'Ghazal', 'Risa\''],
      correctOptionIndex: 0,
      explanation: 'Hija\' adalah puisi sindiran/satir.',
    ),
    QuestionItem(
      id: 'sas_arab_053',
      questionText: 'Bait puisi Arab yang berisi pujian dan penghormatan kepada penguasa atau pahlawan dinamakan tema:',
      options: ['Madih (مَدِيْحٌ)', 'Hija\'', 'Risa\'', 'Zuhd'],
      correctOptionIndex: 0,
      explanation: 'Madih adalah puisi panegirik (pujian).',
    ),
    QuestionItem(
      id: 'sas_arab_054',
      questionText: 'Bait puisi Arab yang berisi ratapan duka atas kematian seseorang dinamakan tema:',
      options: ['Risa\' (رِثَاءٌ)', 'Ghazal', 'Fakhr', 'Khamriyyat'],
      correctOptionIndex: 0,
      explanation: 'Risa\' adalah puisi elegi ratapan duka cita.',
    ),
    QuestionItem(
      id: 'sas_arab_055',
      questionText: 'Bait puisi yang berisi ajakan kesederhanaan, perenungan spiritual, dan meninggalkan keduniawian dinamakan tema:',
      options: ['Zuhdiyyat (Zuhd)', 'Ghazal', 'Hija\'', 'Fakhr'],
      correctOptionIndex: 0,
      explanation: 'Zuhdiyyat berfokus pada ketakwaan dan spiritualitas.',
    ),
    QuestionItem(
      id: 'sas_arab_056',
      questionText: 'Seni kaligrafi tulisan Arab yang tegak lurus, tebal, dan kaku yang merupakan gaya tertua adalah Khat:',
      options: ['Kufi', 'Naskhi', 'Thuluth', 'Riq\'ah'],
      correctOptionIndex: 0,
      explanation: 'Khat Kufi gaya kaligrafi tertua bersegi.',
    ),
    QuestionItem(
      id: 'sas_arab_057',
      questionText: 'Gaya kaligrafi Arab yang paling umum digunakan untuk mencetak buku, mushaf Al-Qur\'an, dan media cetak adalah Khat:',
      options: ['Naskhi', 'Kufi', 'Diwani', 'Farisi'],
      correctOptionIndex: 0,
      explanation: 'Khat Naskhi paling mudah dibaca dan standar cetak.',
    ),
    QuestionItem(
      id: 'sas_arab_058',
      questionText: 'Gaya kaligrafi Arab dengan lukisan indah melengkung megah yang biasa digunakan untuk dekorasi dinding masjid adalah Khat:',
      options: ['Thuluth (Sulus)', 'Riq\'ah', 'Naskhi', 'Kufi'],
      correctOptionIndex: 0,
      explanation: 'Khat Thuluth memiliki nilai keindahan ornamen tinggi.',
    ),
    QuestionItem(
      id: 'sas_arab_059',
      questionText: 'Gaya tulisan kaligrafi Arab tangan cepat yang ringkas dan praktis untuk catatan harian adalah Khat:',
      options: ['Riq\'ah', 'Thuluth', 'Diwani', 'Kufi'],
      correctOptionIndex: 0,
      explanation: 'Khat Riq\'ah paling praktis untuk tulisan tangan harian.',
    ),
    QuestionItem(
      id: 'sas_arab_060',
      questionText: 'Karya sastra filosofis alegoris karya Ibn Tufail tentang anak yang tumbuh di pulau terpencil mencari Tuhan dinamakan:',
      options: ['Hayy ibn Yaqzan', 'Risalat al-Ghufran', 'Al-Muqaddimah', 'Tahafut al-Falasifah'],
      correctOptionIndex: 0,
      explanation: 'Hayy ibn Yaqzan novel filosofis pencarian kebenaran rasional.',
    ),
    QuestionItem(
      id: 'sas_arab_061',
      questionText: 'Mahakarya Ibnu Khaldun yang menjadi peletak dasar sosiologi dan filsafat sejarah dunia adalah Kitab:',
      options: ['Al-Muqaddimah', 'Al-I\'tibār', 'Tahafut', 'Al-Kamil'],
      correctOptionIndex: 0,
      explanation: 'Muqaddimah Ibnu Khaldun karya sosiologi sejarah abad ke-14.',
    ),
    QuestionItem(
      id: 'sas_arab_062',
      questionText: 'Mahakarya Abu al-\'Ala al-Ma\'arri tentang perjalanan imajinasi ke alam akhirat yang menginspirasi Divine Comedy Dante dinamakan:',
      options: ['Risalat al-Ghufran (Risalah Pengampunan)', 'Hayy ibn Yaqzan', 'Maqamat', 'Al-Luzumiyyat'],
      correctOptionIndex: 0,
      explanation: 'Risalat al-Ghufran mahakarya imajinasi eskatologi.',
    ),
    QuestionItem(
      id: 'sas_arab_063',
      questionText: 'Isim yang tidak boleh menerima harakat Tanwin dan Kasrah (kecuali saat kemasukan Alif-Lam/Idhafah) dinamakan:',
      options: ['Isim Ghairu Munsarif', 'Isim Mankus', 'Isim Maqsur', 'Isim Mabni'],
      correctOptionIndex: 0,
      explanation: 'Ghairu Munsarif tidak bertanwin dan majrur dengan fathah.',
    ),
    QuestionItem(
      id: 'sas_arab_064',
      questionText: 'Isim yang diakhiri dengan Alif Lazimah (seperti Al-Fata, Al-\'Asa) dinamakan Isim:',
      options: ['Maqsur', 'Mankus', 'Mamudud', 'Sahih'],
      correctOptionIndex: 0,
      explanation: 'Isim Maqsur diakhiri Alif lazimah (harakat I\'rab-nya takdiri/tersembunyi).',
    ),
    QuestionItem(
      id: 'sas_arab_065',
      questionText: 'Isim yang diakhiri dengan Ya Lazimah berharakat kasrah sebelumnya (seperti Al-Qadi) dinamakan Isim:',
      options: ['Mankus', 'Maqsur', 'Mamudud', 'Musanna'],
      correctOptionIndex: 0,
      explanation: 'Isim Mankus diakhiri Ya lazimah (seperti Al-Qadi).',
    ),
    QuestionItem(
      id: 'sas_arab_066',
      questionText: 'Isim yang diakhiri dengan Alif Mamdudah diikuti Hamzah (seperti Sahra\', Hamra\') dinamakan Isim:',
      options: ['Mamdud', 'Maqsur', 'Mankus', 'Nakirah'],
      correctOptionIndex: 0,
      explanation: 'Isim Mamdud diakhiri Alif-Hamzah (اء).',
    ),
    QuestionItem(
      id: 'sas_arab_067',
      questionText: 'Kata-kata yang bentuk harakat akhirnya tetap dan tidak pernah berubah (seperti kata ganti Ana, Anta) dinamakan:',
      options: ['Mabni', 'Mu\'rab', 'Munsarif', 'Marfu\''],
      correctOptionIndex: 0,
      explanation: 'Kata Mabni harakat akhirnya konstan tidak terpengaruh amil.',
    ),
    QuestionItem(
      id: 'sas_arab_068',
      questionText: 'Kata-kata yang harakat akhirnya dapat berubah sesuai dengan kedudukannya dalam kalimat dinamakan:',
      options: ['Mu\'rab', 'Mabni', 'Majhul', 'Lazim'],
      correctOptionIndex: 0,
      explanation: 'Kata Mu\'rab berubah harakat sesuai I\'rab.',
    ),
    QuestionItem(
      id: 'sas_arab_069',
      questionText: 'Fi\'il yang tidak membutuhkan Ma\'ful bih (objek) dalam kalimat dinamakan Fi\'il:',
      options: ['Lazim (Intransitif)', 'Muta\'addi', 'Majhul', 'Naqis'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Lazim tidak memerlukan objek.',
    ),
    QuestionItem(
      id: 'sas_arab_070',
      questionText: 'Fi\'il yang membutuhkan kehadiran Ma\'ful bih (objek) dinamakan Fi\'il:',
      options: ['Muta\'addi (Transitif)', 'Lazim', 'Jamid', 'Tamm'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Muta\'addi memerlukan satu atau lebih objek.',
    ),
    QuestionItem(
      id: 'sas_arab_071',
      questionText: 'Fi\'il pasif yang subjek pelakunya disembunyikan dinamakan Fi\'il:',
      options: ['Majhul', 'Ma\'lum', 'Muta\'addi', 'Naqis'],
      correctOptionIndex: 0,
      explanation: 'Fi\'il Majhul kata kerja pasif (seperti Kutiba = ditulis).',
    ),
    QuestionItem(
      id: 'sas_arab_072',
      questionText: 'Subjek pengganti Fa\'il pada Fi\'il Majhul yang I\'rab-nya Marfu\' dinamakan:',
      options: ['Na\'ibul Fa\'il', 'Ma\'ful bih', 'Khabar', 'Hal'],
      correctOptionIndex: 0,
      explanation: 'Na\'ibul Fa\'il menggantikan Fa\'il pada kalimat pasif.',
    ),
    QuestionItem(
      id: 'sas_arab_073',
      questionText: 'Penggabungan dua Isim yang berfungsi menunjukkan kepemilikan (seperti Kitab-u Al-Ustadzi) dinamakan struktur:',
      options: ['Idhafah (Mudhaf & Mudhaf Ilaih)', 'Na\'at Man\'ut', 'Tawkid', 'Ataf'],
      correctOptionIndex: 0,
      explanation: 'Idhafah menggabungkan Mudhaf dan Mudhaf Ilaih (selalu Majrur).',
    ),
    QuestionItem(
      id: 'sas_arab_074',
      questionText: 'Hubungan kata sifat dan kata yang disifati yang harus selaras dalam gender, jumlah, dan I\'rab dinamakan:',
      options: ['Na\'at dan Man\'ut (Sifat-Mausuf)', 'Idhafah', 'Mubtada Khabar', 'Badal'],
      correctOptionIndex: 0,
      explanation: 'Na\'at mematuhi Man\'ut dalam 4 hal.',
    ),
    QuestionItem(
      id: 'sas_arab_075',
      questionText: 'Huruf penghubung (Harf \'Athaf) yang menyatakan urutan langsung tanpa jeda (seperti Fa / فـ) bermakna:',
      options: ['Maka / Lalu seketika', 'Kemudian (dengan jeda)', 'Atau', 'Tetapi'],
      correctOptionIndex: 0,
      explanation: 'Fa\' menunjukkan urutan langsung (Taqib).',
    ),
    QuestionItem(
      id: 'sas_arab_076',
      questionText: 'Huruf \'Athaf "Summa" (ثُمَّ) menyatakan urutan dengan:',
      options: ['Jeda waktu (Tarakhi)', 'Seketika', 'Pilihan', 'Sanggahan'],
      correctOptionIndex: 0,
      explanation: 'Summa bermakna kemudian setelah jeda waktu.',
    ),
    QuestionItem(
      id: 'sas_arab_077',
      questionText: 'Isim penderita keadaan (menerangkan kondisi Fa\'il/Ma\'ful saat kejadian) yang ber-I\'rab Mansub dinamakan:',
      options: ['Hal (حَالٌ)', 'Tamyiz', 'Muf\'ul Mutlaq', 'Zaraf'],
      correctOptionIndex: 0,
      explanation: 'Hal menjelaskan kondisi saat perbuatan berlangsung (misal: berjalan sambil tersenyum).',
    ),
    QuestionItem(
      id: 'sas_arab_078',
      questionText: 'Isim Mansub yang berfungsi menghilangkan samar-samar pada timbangan, ukuran, atau bilangan dinamakan:',
      options: ['Tamyiz (تَمْيِيْزٌ)', 'Hal', 'Mustasna', 'Badal'],
      correctOptionIndex: 0,
      explanation: 'Tamyiz memperjelas kadar atau kuantitas samar.',
    ),
    QuestionItem(
      id: 'sas_arab_079',
      questionText: 'Isim yang dikecualikan dari hukum kalimat sebelumnya menggunakan kata "Illa" (إِلَّا) dinamakan:',
      options: ['Mustasna (مُسْتَثْنَى)', 'Mustasna Minhu', 'Tamyiz', 'Munada'],
      correctOptionIndex: 0,
      explanation: 'Mustasna adalah kata pengecualian setelah Illa.',
    ),
    QuestionItem(
      id: 'sas_arab_080',
      questionText: 'Isim yang dipanggil menggunakan huruf panggilan "Ya" (يَا) dinamakan:',
      options: ['Munada (مُنَادَى)', 'Nida\'', 'Badal', 'Tawkid'],
      correctOptionIndex: 0,
      explanation: 'Munada adalah kata yang dipanggil.',
    ),
    QuestionItem(
      id: 'sas_arab_081',
      questionText: 'Gerakan pembaharuan sastra Arab modern di Mahjar (Amerika) yang dipelopori Gibran Kahlil Gibran dinamakan:',
      options: ['Al-Rabitah al-Qalamiyyah', 'Al-Diwan', 'Apollo', 'Al-Mahjar'],
      correctOptionIndex: 0,
      explanation: 'Al-Rabitah al-Qalamiyyah asosiasi penulis imigran Arab di New York.',
    ),
    QuestionItem(
      id: 'sas_arab_082',
      questionText: 'Genre drama panggung Arab modern pertama yang dirintis oleh Tawfiq al-Hakim dikategorikan sebagai:',
      options: ['Masrahiyyah (Seni Drama)', 'Rewayah', 'Qissah Qasirah', 'Qasidah'],
      correctOptionIndex: 0,
      explanation: 'Masrahiyyah adalah teater/drama panggung Arab.',
    ),
    QuestionItem(
      id: 'sas_arab_083',
      questionText: 'Karya fiksi novel panjang dalam peristilahan sastra Arab modern dinamakan:',
      options: ['Riwayah (رِوَايَةٌ)', 'Qissah Qasirah', 'Uqdliyah', 'Maqalah'],
      correctOptionIndex: 0,
      explanation: 'Riwayah berarti novel.',
    ),
    QuestionItem(
      id: 'sas_arab_084',
      questionText: 'Karya fiksi cerita pendek (cerpen) dalam istilah sastra Arab dinamakan:',
      options: ['Qissah Qasirah (قِصَّةٌ قَصِيْرَةٌ)', 'Riwayah', 'Masrahiyyah', 'Ughniyah'],
      correctOptionIndex: 0,
      explanation: 'Qissah Qasirah berarti cerita pendek.',
    ),
    QuestionItem(
      id: 'sas_arab_085',
      questionText: 'Puisi bebas Arab modern yang tidak terikat ketat metrum \'Arudh klasik dinamakan:',
      options: ['Al-Syi\'r al-Hurr (Puisi Bebas)', 'Al-Qasidah', 'Al-Muwasysyah', 'Al-Rajaz'],
      correctOptionIndex: 0,
      explanation: 'Al-Syi\'r al-Hurr melepaskan diri dariikatan bahr tradisional.',
    ),
    QuestionItem(
      id: 'sas_arab_086',
      questionText: 'Bentuk puisi klasik Andalusia (Spanyol Islam) yang kaya irama lagu dinamakan:',
      options: ['Al-Muwasysyah (المُوَشَّحَات)', 'Al-Qasidah', 'Al-Syi\'r al-Hurr', 'Al-Zajal'],
      correctOptionIndex: 0,
      explanation: 'Muwasysyah genre puisi strophic khas Andalusia.',
    ),
    QuestionItem(
      id: 'sas_arab_087',
      questionText: 'Wazan dasar standar dalam ilmu Sharaf yang digunakan sebagai pembanding perubahan kata adalah:',
      options: ['Fa-\'A-La (فَعَلَ)', 'Fa-\'I-La', 'A-Fa-\'A-La', 'Is-Taf-\'A-La'],
      correctOptionIndex: 0,
      explanation: 'Fa-\'a-la (ف-ع-ل) adalah timbangan standar (Mizan Sarfi).',
    ),
    QuestionItem(
      id: 'sas_arab_088',
      questionText: 'Bentuk kata benda pelaku (subjek perbuatan) dari wazan Fa-\'a-la adalah:',
      options: ['Fa-\'il (فَاعِلٌ)', 'Maf-\'ul', 'Fi-\'l', 'Maf-\'al'],
      correctOptionIndex: 0,
      explanation: 'Fa-\'il adalah Isim Fa\'il (pelaku).',
    ),
    QuestionItem(
      id: 'sas_arab_089',
      questionText: 'Bentuk kata benda penderita (objek perbuatan) dari wazan Fa-\'a-la adalah:',
      options: ['Maf-\'ul (مَفْعُوْلٌ)', 'Fa-\'il', 'Muf-\'il', 'Taf-\'il'],
      correctOptionIndex: 0,
      explanation: 'Maf-\'ul adalah Isim Maf\'ul (objek penderita).',
    ),
    QuestionItem(
      id: 'sas_arab_090',
      questionText: 'Bentuk kata benda keterangan tempat/waktu dari wazan Fa-\'a-la adalah:',
      options: ['Maf-\'al / Maf-\'il (مَفْعَلٌ)', 'Fa-\'il', 'Muf-\'ala', 'Taf-\'il'],
      correctOptionIndex: 0,
      explanation: 'Maf-\'al/Maf-\'il adalah Isim Zaraf (tempat/waktu).',
    ),
    QuestionItem(
      id: 'sas_arab_091',
      questionText: 'Bentuk kata benda instrumen alat dari wazan Fa-\'a-la adalah:',
      options: ['Mif-\'al / Mif-\'alah (مِفْعَالٌ)', 'Maf-\'ul', 'Fa-\'il', 'Fu-\'al'],
      correctOptionIndex: 0,
      explanation: 'Mif-\'al adalah Isim Alat (instrumen kerja).',
    ),
    QuestionItem(
      id: 'sas_arab_092',
      questionText: 'Isim abstrak hasil penyulingan makna kata kerja tanpa terikat waktu dinamakan:',
      options: ['Masdar (مَصْدَرٌ)', 'Isim Fa\'il', 'Isim Zaraf', 'Fi\'il'],
      correctOptionIndex: 0,
      explanation: 'Masdar adalah gerund/verbal noun.',
    ),
    QuestionItem(
      id: 'sas_arab_093',
      questionText: 'Huruf-huruf tambahan (Zawaid) pada Fi\'il Mazid terhimpun dalam rumus ringkas:',
      options: ['Sa-altumuunihaa (سَأَلْتُمُونِيهَا)', 'Fathun Dammun', 'Abjad Hawwaz', 'Kaf Ha Ya \'Ain Sad'],
      correctOptionIndex: 0,
      explanation: 'Sa-altumuunihaa menghimpun 10 huruf ziadah tambahan.',
    ),
    QuestionItem(
      id: 'sas_arab_094',
      questionText: 'Seni retorika khutbah dan pidato sastra Arab yang terkenal sejak zaman pra-Islam dinamakan:',
      options: ['Khithabah (خِطَابَةٌ)', 'Kitabah', 'Qira\'ah', 'Riwayah'],
      correctOptionIndex: 0,
      explanation: 'Khithabah seni oratorium pidato Arab.',
    ),
    QuestionItem(
      id: 'sas_arab_095',
      questionText: 'Tradisi pengkajian perbandingan sastra Arab dengan sastra-sastra dunia dinamakan:',
      options: ['Al-Adab al-Muqaran (Sastra Bandingan)', 'Al-Adab al-Arabi', 'Al-Naqd al-Adabi', 'Al-Tarjamah'],
      correctOptionIndex: 0,
      explanation: 'Al-Adab al-Muqaran adalah studi sastra komparatif.',
    ),
    QuestionItem(
      id: 'sas_arab_096',
      questionText: 'Kritik sastra Arab untuk menilai mutu keindahan karya puisi dan prosa dinamakan:',
      options: ['Al-Naqd al-Adabi (Kritik Sastra)', 'Balaghah', 'Arudh', 'Tarikh al-Adab'],
      correctOptionIndex: 0,
      explanation: 'Al-Naqd al-Adabi studi evaluasi estetika sastra.',
    ),
    QuestionItem(
      id: 'sas_arab_097',
      questionText: 'Perkembangan periodisasi sejarah sastra Arab dibagi menjadi periode Jahiliyah, Islami, Umayyah, Abbasiyah, Turki Utsmani, dan:',
      options: ['Hadis / Mu\'asir (Modern & Kontemporer)', 'Puritan', 'Skolastik', 'Prakarsa'],
      correctOptionIndex: 0,
      explanation: 'Periode Al-Adab al-Mu\'asir mencakup sastra Arab modern abad 19-sekarang.',
    ),
    QuestionItem(
      id: 'sas_arab_098',
      questionText: 'Antologi teks bacaan sastra klasik dan ensiklopedia budaya karya Al-Jahiz yang sangat terkenal adalah:',
      options: ['Kitab al-Bukhala\' & Al-Hawayan', 'Al-Muqaddimah', 'Al-Aghani', 'Kalilah wa Dimnah'],
      correctOptionIndex: 0,
      explanation: 'Al-Jahiz pengarang Kitab al-Bukhala\' (Buku Orang-Orang Kikir).',
    ),
    QuestionItem(
      id: 'sas_arab_099',
      questionText: 'Ensiklopedia raksasa tentang nyanyian, biograf penyair, dan musik Arab klasik karya Abu al-Faraj al-Isfahani adalah Kitab:',
      options: ['Al-Aghani (كِتَابُ الأَغَانِي)', 'Al-Muqaddimah', 'Diwan', 'Hamasah'],
      correctOptionIndex: 0,
      explanation: 'Kitab al-Aghani ensiklopedia 24 jilid lagu dan puisi klasik.',
    ),
    QuestionItem(
      id: 'sas_arab_100',
      questionText: 'Tujuan utama mempelajari Sastra dan Bahasa Arab pada jenjang perguruan tinggi adalah untuk:',
      options: ['Menguasai struktur kebahasaan, apresiasi teks sastra klasik/modern, dan kajian kebudayaan Arab secara mendalam', 'Menghafal kosakata saja', 'Menjadi penerjemah tanpa analisis', 'Menghafal bait puisi saja'],
      correctOptionIndex: 0,
      explanation: 'Studi Sastra Arab mencakup kemahiran linguistik, analisis estetika teks, dan pemahaman kebudayaan komprehensif.',
    ),
  ];
}
