// lib/game/widgets/aktivitas_menu/pilih_aktivitas/pendidikan_karir/kerja_logic/database_nama_pekerjaan.dart
import 'package:flutter/material.dart';

class JobDatabase {
  static final List<Map<String, dynamic>> availableJobs = [
    // ---- DASAR & ENTRY-LEVEL ----
    {
      'title': 'Kasir',
      'salary': 400,
      'minIntel': 10,
      'category': 'Dasar',
      'desc': 'Melayani transaksi pembayaran',
      'icon': Icons.point_of_sale,
      'color': Colors.blueGrey,
    },
    {
      'title': 'Supir Ojek Online',
      'salary': 400,
      'minIntel': 10,
      'category': 'Dasar',
      'desc': 'Mengantarkan penumpang dengan kendaraan',
      'icon': Icons.motorcycle,
      'color': Colors.green,
    },
    {
      'title': 'Karyawan Toko',
      'salary': 500,
      'minIntel': 20,
      'category': 'Dasar',
      'desc': 'Melayani pelanggan dan mengelola toko',
      'icon': Icons.store,
      'color': Colors.blue,
    },
    {
      'title': 'Buruh Pabrik',
      'salary': 600,
      'minIntel': 15,
      'category': 'Dasar',
      'desc': 'Bekerja di lini produksi pabrik',
      'icon': Icons.precision_manufacturing,
      'color': Colors.orange,
    },
    {
      'title': 'Cleaning Service',
      'salary': 350,
      'minIntel': 10,
      'category': 'Dasar',
      'desc': 'Membersihkan dan merawat gedung',
      'icon': Icons.cleaning_services,
      'color': Colors.grey,
    },
    {
      'title': 'Satpam',
      'salary': 400,
      'minIntel': 15,
      'category': 'Dasar',
      'desc': 'Menjaga keamanan dan ketertiban',
      'icon': Icons.security,
      'color': Colors.indigo,
    },
    {
      'title': 'Kurir',
      'salary': 450,
      'minIntel': 15,
      'category': 'Dasar',
      'desc': 'Mengantar paket dan barang',
      'icon': Icons.local_shipping,
      'color': Colors.amber,
    },

    // ---- TERAMPIL (TANPA GELAR) ----
    {
      'title': 'Montir',
      'salary': 800,
      'minIntel': 30,
      'category': 'Terampil',
      'desc': 'Memperbaiki kendaraan dan mesin',
      'icon': Icons.build,
      'color': Colors.brown,
    },
    {
      'title': 'Tukang Listrik',
      'salary': 900,
      'minIntel': 35,
      'category': 'Terampil',
      'desc': 'Memasang dan memperbaiki instalasi listrik',
      'icon': Icons.electrical_services,
      'color': Colors.orange,
    },
    {
      'title': 'Tukang Kayu',
      'salary': 850,
      'minIntel': 30,
      'category': 'Terampil',
      'desc': 'Membuat dan memperbaiki furnitur kayu',
      'icon': Icons.handyman,
      'color': Colors.brown,
    },
    {
      'title': 'Tukang Las',
      'salary': 900,
      'minIntel': 30,
      'category': 'Terampil',
      'desc': 'Mengelas logam dan struktur besi',
      'icon': Icons.fire_extinguisher,
      'color': Colors.grey,
    },
    {
      'title': 'Nelayan',
      'salary': 700,
      'minIntel': 20,
      'category': 'Terampil',
      'desc': 'Menangkap ikan di laut dan sungai',
      'icon': Icons.directions_boat,
      'color': Colors.blue,
    },
    {
      'title': 'Petani',
      'salary': 600,
      'minIntel': 20,
      'category': 'Terampil',
      'desc': 'Mengelola lahan pertanian dan ternak',
      'icon': Icons.agriculture,
      'color': Colors.green,
    },
    {
      'title': 'Koki',
      'salary': 800,
      'minIntel': 30,
      'category': 'Terampil',
      'desc': 'Memasak dan menyiapkan makanan',
      'icon': Icons.restaurant,
      'color': Colors.red,
    },
    {
      'title': 'Pelayan Restoran',
      'salary': 500,
      'minIntel': 20,
      'category': 'Terampil',
      'desc': 'Melayani pelanggan di restoran',
      'icon': Icons.restaurant_menu,
      'color': Colors.pink,
    },

    // ---- KREATIF & ESPORTS ----
    {
      'title': 'Brand Ambassador Esport',
      'salary': 2500,
      'minIntel': 40,
      'category': 'Kreatif',
      'desc': 'Menjadi ikon promosi dan perwakilan tim E-Sport ternama',
      'icon': Icons.sports_esports,
      'color': Colors.blueAccent,
    },
    {
      'title': 'Pro Player Esport',
      'salary': 3000,
      'minIntel': 30,
      'category': 'Kreatif',
      'desc': 'Bermain game kompetitif secara profesional di tim E-Sport ternama',
      'icon': Icons.gamepad,
      'color': Colors.deepOrangeAccent,
    },
    {
      'title': 'Talent Esports',
      'salary': 2000,
      'minIntel': 30,
      'category': 'Kreatif',
      'desc': 'Menjadi talent pengisi konten dan wajah publik dari tim E-Sport',
      'icon': Icons.star_border,
      'color': Colors.amberAccent,
    },

    // ---- LAYANAN & SOSIAL ----
    {
      'title': 'Driver Pribadi',
      'salary': 700,
      'minIntel': 25,
      'category': 'Layanan',
      'desc': 'Mengantar majikan ke berbagai tempat',
      'icon': Icons.car_rental,
      'color': Colors.teal,
    },
    {
      'title': 'Asisten Rumah Tangga',
      'salary': 500,
      'minIntel': 15,
      'category': 'Layanan',
      'desc': 'Membantu pekerjaan rumah tangga',
      'icon': Icons.home,
      'color': Colors.green,
    },
    {
      'title': 'Baby Sitter',
      'salary': 450,
      'minIntel': 20,
      'category': 'Layanan',
      'desc': 'Merawat dan mengawasi anak-anak',
      'icon': Icons.child_care,
      'color': Colors.pink,
    },
    {
      'title': 'Pengasuh Lansia',
      'salary': 500,
      'minIntel': 20,
      'category': 'Layanan',
      'desc': 'Merawat dan mendampingi lansia',
      'icon': Icons.elderly,
      'color': Colors.grey,
    },

    // ---- PROFESIONAL (BUTUH GELAR) ----
    // STEM & TEKNIK
    {
      'title': 'Junior Software Engineer',
      'salary': 3500,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Mengembangkan aplikasi dan sistem',
      'icon': Icons.computer,
      'color': Colors.indigo,
    },
    {
      'title': 'Data Analyst',
      'salary': 3000,
      'minIntel': 65,
      'category': 'Profesional',
      'desc': 'Menganalisis data untuk keputusan bisnis',
      'icon': Icons.analytics,
      'color': Colors.blue,
    },
    {
      'title': 'Network Engineer',
      'salary': 3200,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Mengelola infrastruktur jaringan',
      'icon': Icons.wifi,
      'color': Colors.cyan,
    },
    {
      'title': 'Civil Engineer',
      'salary': 3000,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Merancang dan mengawasi proyek konstruksi',
      'icon': Icons.architecture,
      'color': Colors.brown,
    },
    {
      'title': 'Mechanical Engineer',
      'salary': 3200,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Merancang sistem mekanik dan mesin',
      'icon': Icons.settings,
      'color': Colors.grey,
    },
    {
      'title': 'Electrical Engineer',
      'salary': 3300,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Merancang sistem kelistrikan dan elektronik',
      'icon': Icons.flash_on,
      'color': Colors.orange,
    },
    {
      'title': 'Chemical Engineer',
      'salary': 3500,
      'minIntel': 65,
      'category': 'Profesional',
      'desc': 'Mengembangkan proses produksi kimia',
      'icon': Icons.science,
      'color': Colors.deepOrange,
    },
    {
      'title': 'Architect',
      'salary': 3800,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Merancang bangunan dan struktur',
      'icon': Icons.home_work,
      'color': Colors.amber,
    },

    // KESEHATAN
    {
      'title': 'Dokter Umum',
      'salary': 5000,
      'minIntel': 80,
      'category': 'Profesional',
      'desc': 'Mendiagnosis dan mengobati pasien',
      'icon': Icons.medical_services,
      'color': Colors.red,
    },
    {
      'title': 'Dokter Spesialis',
      'salary': 8000,
      'minIntel': 85,
      'category': 'Profesional',
      'desc': 'Spesialisasi di bidang tertentu (bedah, anak, dll)',
      'icon': Icons.local_hospital,
      'color': Colors.red.shade900,
    },
    {
      'title': 'Dokter Gigi',
      'salary': 4500,
      'minIntel': 75,
      'category': 'Profesional',
      'desc': 'Merawat kesehatan gigi dan mulut',
      'icon': Icons.medical_information,
      'color': Colors.teal,
    },
    {
      'title': 'Apoteker',
      'salary': 3500,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Menyediakan dan mengelola obat-obatan',
      'icon': Icons.medication,
      'color': Colors.purple,
    },
    {
      'title': 'Perawat',
      'salary': 2800,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Memberikan perawatan medis langsung',
      'icon': Icons.health_and_safety,
      'color': Colors.blue,
    },
    {
      'title': 'Ahli Gizi',
      'salary': 2500,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Memberikan konsultasi gizi dan diet',
      'icon': Icons.restaurant,
      'color': Colors.green,
    },

    // BISNIS & EKONOMI
    {
      'title': 'Manajer Keuangan',
      'salary': 4000,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Mengelola keuangan and investasi perusahaan',
      'icon': Icons.attach_money,
      'color': Colors.green,
    },
    {
      'title': 'Akuntan',
      'salary': 3200,
      'minIntel': 65,
      'category': 'Profesional',
      'desc': 'Mengelola laporan keuangan dan pajak',
      'icon': Icons.calculate,
      'color': Colors.blue,
    },
    {
      'title': 'Analis Ekonomi',
      'salary': 3500,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Menganalisis tren ekonomi dan pasar',
      'icon': Icons.timeline,
      'color': Colors.cyan,
    },
    {
      'title': 'Bankir',
      'salary': 3800,
      'minIntel': 65,
      'category': 'Profesional',
      'desc': 'Mengelola dana dan memberikan pinjaman',
      'icon': Icons.account_balance,
      'color': Colors.indigo,
    },
    {
      'title': 'Marketing Specialist',
      'salary': 3000,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Merancang strategi pemasaran produk',
      'icon': Icons.trending_up,
      'color': Colors.purple,
    },

    // HUKUM & SOSIAL
    {
      'title': 'Pengacara',
      'salary': 5000,
      'minIntel': 75,
      'category': 'Profesional',
      'desc': 'Memberikan bantuan hukum dan pembelaan',
      'icon': Icons.gavel,
      'color': Colors.deepPurple,
    },
    {
      'title': 'Jaksa',
      'salary': 4500,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Menuntut perkara pidana di pengadilan',
      'icon': Icons.account_balance,
      'color': Colors.blueGrey,
    },
    {
      'title': 'Diplomat',
      'salary': 4000,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Mewakili negara dalam hubungan internasional',
      'icon': Icons.public,
      'color': Colors.blue,
    },
    {
      'title': 'Jurnalis',
      'salary': 2500,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Mengumpulkan dan menyajikan berita',
      'icon': Icons.newspaper,
      'color': Colors.grey,
    },
    {
      'title': 'Psikolog',
      'salary': 3500,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Memberikan konseling dan terapi psikologis',
      'icon': Icons.psychology,
      'color': Colors.pink,
    },
    {
      'title': 'Pegawai Negeri Sipil (PNS)',
      'salary': 1500,
      'minIntel': 50,
      'category': 'Profesional',
      'desc': 'Bekerja di instansi pemerintah',
      'icon': Icons.account_balance,
      'color': Colors.teal,
    },

    // PENDIDIKAN & BAHASA
    {
      'title': 'Guru SD',
      'salary': 1200,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Mengajar siswa kelas 1-6 SD',
      'icon': Icons.school,
      'color': Colors.purple,
    },
    {
      'title': 'Guru SMP',
      'salary': 1400,
      'minIntel': 65,
      'category': 'Profesional',
      'desc': 'Mengajar siswa kelas 7-9 SMP',
      'icon': Icons.school,
      'color': Colors.deepPurple,
    },
    {
      'title': 'Guru SMA',
      'salary': 1800,
      'minIntel': 70,
      'category': 'Profesional',
      'desc': 'Mengajar siswa kelas 10-12 SMA',
      'icon': Icons.school,
      'color': Colors.indigo,
    },
    {
      'title': 'Dosen',
      'salary': 3000,
      'minIntel': 75,
      'category': 'Profesional',
      'desc': 'Mengajar dan meneliti di perguruan tinggi',
      'icon': Icons.menu_book,
      'color': Colors.blue,
    },
    // KREATIF & SENI
    {
      'title': 'Sutradara Film',
      'salary': 4000,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Mengarahkan produksi film dan televisi',
      'icon': Icons.movie,
      'color': Colors.red,
    },
    {
      'title': 'Produser Musik',
      'salary': 3500,
      'minIntel': 55,
      'category': 'Profesional',
      'desc': 'Memproduksi dan mengelola rekaman musik',
      'icon': Icons.music_video,
      'color': Colors.orange,
    },

    // PERTANIAN & LAINNYA
    {
      'title': 'Agronom',
      'salary': 2800,
      'minIntel': 55,
      'category': 'Profesional',
      'desc': 'Mengelola produksi tanaman dan pertanian',
      'icon': Icons.agriculture,
      'color': Colors.green,
    },
    {
      'title': 'Manajer Hotel',
      'salary': 3000,
      'minIntel': 60,
      'category': 'Profesional',
      'desc': 'Mengelola operasional hotel dan akomodasi',
      'icon': Icons.hotel,
      'color': Colors.teal,
    },

    // PRESTISE TINGGI
    {
      'title': 'CEO Startup',
      'salary': 10000,
      'minIntel': 80,
      'category': 'Prestise',
      'desc': 'Memimpin perusahaan rintisan',
      'icon': Icons.rocket,
      'color': Colors.amber,
    },
    {
      'title': 'Pilot',
      'salary': 6000,
      'minIntel': 70,
      'category': 'Prestise',
      'desc': 'Mengemudikan pesawat terbang',
      'icon': Icons.flight,
      'color': Colors.blue,
    },
    {
      'title': 'Arsitek Senior',
      'salary': 6000,
      'minIntel': 75,
      'category': 'Prestise',
      'desc': 'Merancang bangunan bertingkat tinggi',
      'icon': Icons.architecture,
      'color': Colors.brown,
    },
    {
      'title': 'Pengacara Senior',
      'salary': 8000,
      'minIntel': 80,
      'category': 'Prestise',
      'desc': 'Menangani kasus-kasus besar',
      'icon': Icons.gavel,
      'color': Colors.deepPurple,
    },
    {
      'title': 'Konsultan Manajemen',
      'salary': 7000,
      'minIntel': 75,
      'category': 'Prestise',
      'desc': 'Memberikan saran strategis untuk perusahaan',
      'icon': Icons.business_center,
      'color': Colors.indigo,
    },
  ];
}
