import '../tes_seleksi_model.dart';

List<QuestionItem> getTeknikKimiaQuestions() {
  return const [
    QuestionItem(
      id: 'tk_001',
      questionText: 'Hukum Kekekalan Massa yang menjadi dasar penyusunan Neraca Massa menyatakan bahwa:',
      options: ['Massa Masuk - Massa Keluar = Akumulasi Massa', 'Massa Masuk selalu lebih besar', 'Massa dapat diciptakan dari energi', 'Massa berbanding lurus dengan suhu'],
      correctOptionIndex: 0,
      explanation: 'Persamaan umum Neraca Massa: Masuk - Keluar + Generasi - Konsumsi = Akumulasi.',
    ),
    QuestionItem(
      id: 'tk_002',
      questionText: 'Dalam sistem steady-state (keadaan tunak) tanpa reaksi kimia, persamaan neraca massa adalah:',
      options: ['Massa Masuk = Massa Keluar', 'Massa Masuk > Massa Keluar', 'Akumulasi = 1', 'Massa Masuk = 0'],
      correctOptionIndex: 0,
      explanation: 'Pada kondisi steady-state, nilai akumulasi sama dengan nol (Masuk = Keluar).',
    ),
    QuestionItem(
      id: 'tk_003',
      questionText: 'Operasi pemisahan campuran dua atau lebih cairan berdasarkan perbedaan titik didihnya dinamakan:',
      options: ['Distilasi', 'Absorpsi', 'Ekstraksi', 'Kristalisasi'],
      correctOptionIndex: 0,
      explanation: 'Distilasi memisahkan komponen cairan berdasarkan perbedaan volatilitas/titik didih.',
    ),
    QuestionItem(
      id: 'tk_004',
      questionText: 'Operasi pemisahan zat terlarut dari campuran gas dengan melarutkannya ke dalam cairan pelarut dinamakan:',
      options: ['Absorpsi', 'Stripping', 'Adsorpsi', 'Desorpsi'],
      correctOptionIndex: 0,
      explanation: 'Absorpsi mengontakkan fas gas dengan cair pelarut (absorbent).',
    ),
    QuestionItem(
      id: 'tk_005',
      questionText: 'Operasi pelepasan gas terlarut dari fase cair menggunakan gas pendorong dinamakan:',
      options: ['Stripping (Desorpsi)', 'Absorpsi', 'Ekstraksi', 'Leaching'],
      correctOptionIndex: 0,
      explanation: 'Stripping adalah kebalikan dari proses absorpsi.',
    ),
    QuestionItem(
      id: 'tk_006',
      questionText: 'Operasi pemisahan komponen dari campuran cair menggunakan pelarut cair lain dinamakan:',
      options: ['Ekstraksi Cair-Cair', 'Leaching', 'Distilasi', 'Filtrasi'],
      correctOptionIndex: 0,
      explanation: 'Ekstraksi cair-cair memisahkan solute berdasar perbedaan kelarutan dalam dua solven.',
    ),
    QuestionItem(
      id: 'tk_007',
      questionText: 'Operasi ekstraksi zat terlarut dari bahan padatan menggunakan pelarut cair dinamakan:',
      options: ['Leaching (Ekstraksi Padat-Cair)', 'Absorpsi', 'Adsorpsi', 'Sublimasi'],
      correctOptionIndex: 0,
      explanation: 'Leaching mengekstrak komponen dari matriks padat (seperti kopi/minyak sawit).',
    ),
    QuestionItem(
      id: 'tk_008',
      questionText: 'Operasi penyerapan molekul zat (solute) pada permukaan zat padat berpori dinamakan:',
      options: ['Adsorpsi', 'Absorpsi', 'Kristalisasi', 'Evaporasi'],
      correctOptionIndex: 0,
      explanation: 'Adsorpsi mengikat molekul pada permukaan fasa padat (adsorbent).',
    ),
    QuestionItem(
      id: 'tk_009',
      questionText: 'Bahan padat berpori tinggi yang populer digunakan sebagai adsorbent pemurni cair/gas adalah:',
      options: ['Karbon Aktif / Zeolit', 'Pasir Kuarsa', 'Semen', 'Kapur'],
      correctOptionIndex: 0,
      explanation: 'Karbon aktif dan zeolit memiliki luas permukaan spesifik raksasa untuk adsorpsi.',
    ),
    QuestionItem(
      id: 'tk_010',
      questionText: 'Operasi pembentukan partikel padat murni dari larutan lewat jenuh dinamakan:',
      options: ['Kristalisasi', 'Evaporasi', 'Pengeringan', 'Sedimentasi'],
      correctOptionIndex: 0,
      explanation: 'Kristalisasi mengendapkan kristal padat murni dari larutan terlewat-jenuh.',
    ),
    QuestionItem(
      id: 'tk_011',
      questionText: 'Operasi pelepasan sebagian pelarut cair dari larutan encer dengan cara mendidihkannya dinamakan:',
      options: ['Evaporasi (Penguapan)', 'Pengeringan (Drying)', 'Distilasi', 'Filtrasi'],
      correctOptionIndex: 0,
      explanation: 'Evaporasi memekatkan larutan cair dengan menguapkan pelarutnya.',
    ),
    QuestionItem(
      id: 'tk_012',
      questionText: 'Operasi penghilangan kelembaban cairan dari padatan berpori menggunakan udara panas dinamakan:',
      options: ['Pengeringan (Drying)', 'Evaporasi', 'Kristalisasi', 'Leaching'],
      correctOptionIndex: 0,
      explanation: 'Drying membuang kandungan air padatan hingga kadar air seimbang.',
    ),
    QuestionItem(
      id: 'tk_013',
      questionText: 'Reaktor kimia kontinyu ideal dengan pengadukan sempurna di mana komposisi di dalam reaktor sama dengan aliran keluar dinamakan:',
      options: ['CSTR (Continuous Stirred-Tank Reactor)', 'PFR (Plug Flow Reactor)', 'Batch Reactor', 'Fluidized Bed'],
      correctOptionIndex: 0,
      explanation: 'CSTR diasumsikan teraduk sempurna (perfectly mixed) pada kondisi steady-state.',
    ),
    QuestionItem(
      id: 'tk_014',
      questionText: 'Reaktor kimia berupa pipa tanpa pengadukan di mana komposisi berubah sepanjang aksial pipa dinamakan:',
      options: ['PFR (Plug Flow Reactor)', 'CSTR', 'Batch Reactor', 'Autoklaf'],
      correctOptionIndex: 0,
      explanation: 'PFR diasumsikan mengalir seperti sumbat tanpa pencampuran aksial.',
    ),
    QuestionItem(
      id: 'tk_015',
      questionText: 'Reaktor tertutup skala laboratorium tanpa aliran masuk dan keluar selama reaksi berlangsung dinamakan:',
      options: ['Reaktor Batch', 'CSTR', 'PFR', 'Packed Bed'],
      correctOptionIndex: 0,
      explanation: 'Reaktor batch memproses bahan sekaligus dalam satu siklus waktu t.',
    ),
    QuestionItem(
      id: 'tk_016',
      questionText: 'Reaktor kimia berisikan tumpukan butiran katalis padat yang dialiri reaktan dinamakan:',
      options: ['Packed Bed Reactor (PBR)', 'Fluidized Bed Reactor', 'CSTR', 'Slurry Reactor'],
      correctOptionIndex: 0,
      explanation: 'PBR memuat katalis padat stasioner di dalam kolom pipa.',
    ),
    QuestionItem(
      id: 'tk_017',
      questionText: 'Reaktor di mana padatan katalis tersuspensi melayang akibat dorongan laju gas/cair ke atas dinamakan:',
      options: ['Fluidized Bed Reactor', 'Packed Bed Reactor', 'Batch', 'CSTR'],
      correctOptionIndex: 0,
      explanation: 'Fluidized bed memicu suspensi padatan bertindak seperti fluida.',
    ),
    QuestionItem(
      id: 'tk_018',
      questionText: 'Zat yang menambahkan laju reaksi kimia tanpa ikut terkonsumsi dalam reaksi akhir dinamakan:',
      options: ['Katalisator (Katalis)', 'Reaktan', 'Inhibitor', 'Solven'],
      correctOptionIndex: 0,
      explanation: 'Katalis menurunkan energi aktivasi reaksi.',
    ),
    QuestionItem(
      id: 'tk_019',
      questionText: 'Zat yang memperlambat atau menghentikan laju reaksi kimia dinamakan:',
      options: ['Inhibitor', 'Katalis', 'Promotor', 'Substrat'],
      correctOptionIndex: 0,
      explanation: 'Inhibitor menaikkan hambatan energi atau meracuni katalis.',
    ),
    QuestionItem(
      id: 'tk_020',
      questionText: 'Energi minimum yang harus dilampaui molekul agar reaksi kimia dapat terjadi dinamakan:',
      options: ['Energi Aktivasi (Ea)', 'Energi Bebas Gibbs', 'Entalpi Reaksi', 'Entropi'],
      correctOptionIndex: 0,
      explanation: 'Katalis bekerja menyediakan jalur reaksi alternatif dengan Ea lebih rendah.',
    ),
    QuestionItem(
      id: 'tk_021',
      questionText: 'Persamaan Arrhenius menyatakan hubungan antara konstanta laju reaksi (k) dengan suhu (T) yaitu:',
      options: ['k = A x exp(-Ea / (R T))', 'k = A x T', 'k = Ea / (R T)', 'k = R T / A'],
      correctOptionIndex: 0,
      explanation: 'Persamaan Arrhenius memodelkan ketergantungan eksponensial laju reaksi pada suhu.',
    ),
    QuestionItem(
      id: 'tk_022',
      questionText: 'Reaksi kimia yang menyerap kalor dari lingkungan (Delta H > 0) dinamakan reaksi:',
      options: ['Endoterm', 'Eksoterm', 'Isoterm', 'Adiakbatik'],
      correctOptionIndex: 0,
      explanation: 'Reaksi endoterm membutuhkan masukan energi kalor dari luar.',
    ),
    QuestionItem(
      id: 'tk_023',
      questionText: 'Reaksi kimia yang melepas kalor ke lingkungan (Delta H < 0) dinamakan reaksi:',
      options: ['Eksoterm', 'Endoterm', 'Isobarik', 'Isochorik'],
      correctOptionIndex: 0,
      explanation: 'Reaksi eksoterm memancarkan kalor pembakaran.',
    ),
    QuestionItem(
      id: 'tk_024',
      questionText: 'Metode grafis populer untuk menentukan jumlah piringan (plate) teoritis kolom distilasi dinamakan:',
      options: ['Metode McCabe-Thiele', 'Metode Ponchon-Savarit', 'Metode Shortcut Gilliland', 'Metode Underwood'],
      correctOptionIndex: 0,
      explanation: 'Metode McCabe-Thiele memplot garis operasi dan garis kesetimbangan uap-cair.',
    ),
    QuestionItem(
      id: 'tk_025',
      questionText: 'Rasio antara aliran cairan yang dikembalikan ke kolom distilasi dengan aliran produk atas dinamakan:',
      options: ['Rasio Refluks (Reflux Ratio / R)', 'Rasio Boildown', 'Rasio Stripping', 'Rasio Distilat'],
      correctOptionIndex: 0,
      explanation: 'Reflux ratio R = L / D memicu pemurnian fraksinasi.',
    ),
    QuestionItem(
      id: 'tk_026',
      questionText: 'Campuran cairan yang mendidih pada suhu konstan dengan komposisi uap sama dengan komposisi cairannya sehingga tidak dapat dipisahkan dengan distilasi biasa dinamakan:',
      options: ['Campuran Azeotrop', 'Campuran Ideal', 'Campuran Eutektik', 'Larutan Jenuh'],
      correctOptionIndex: 0,
      explanation: 'Azeotrop (seperti Etanol 95.6% dan Air) membutuhkan distilasi ekstraktif/azeotropik.',
    ),
    QuestionItem(
      id: 'tk_027',
      questionText: 'Hukum Raoult untuk larutan ideal menyatakan bahwa tekanan parsial komponen i di fasa uap (Pi) sama dengan:',
      options: ['Tekanan Uap Murni (Pi*) x Fraksi Mol Cairan (xi)', 'Tekanan Total x Fraksi Mol Uap', 'Tekanan / Fraksi', 'Suhu x Volume'],
      correctOptionIndex: 0,
      explanation: 'Hukum Raoult: Pi = xi x Pi*.',
    ),
    QuestionItem(
      id: 'tk_028',
      questionText: 'Hukum Henry menyatakan bahwa kelarutan gas dalam cairan sebanding dengan:',
      options: ['Tekanan Parsial Gas di atas Cairan', 'Suhu Cairan', 'Volume Cairan', 'Massa Molar'],
      correctOptionIndex: 0,
      explanation: 'Hukum Henry: C = H x Pgas.',
    ),
    QuestionItem(
      id: 'tk_029',
      questionText: 'Hukum Fick Pertama memodelkan laju perpindahan massa secara:',
      options: ['Difusi (J = -D (dC/dx))', 'Konveksi', 'Adsorpsi', 'Distilasi'],
      correctOptionIndex: 0,
      explanation: 'Hukum Fick I menyatakan fluks difusi sebanding dengan gradien konsentrasi.',
    ),
    QuestionItem(
      id: 'tk_030',
      questionText: 'Koefisien difusi molekuler (Diffusivity / DAB) memiliki satuan standar:',
      options: ['m² per detik', 'm per detik', 'kg per detik', 'Mol per m³'],
      correctOptionIndex: 0,
      explanation: 'Diffusivity m²/s mengukur laju difusi zat.',
    ),
    QuestionItem(
      id: 'tk_031',
      questionText: 'Angka tak berdimensi yang membandingkan ketebalan lapisan batas momentum dengan lapisan batas massa dinamakan:',
      options: ['Bilangan Schmidt (Sc = nu / D)', 'Bilangan Sherwood', 'Bilangan Prandtl', 'Bilangan Lewis'],
      correctOptionIndex: 0,
      explanation: 'Bilangan Schmidt membandingkan viskositas kinematis terhadap difusivitas massa.',
    ),
    QuestionItem(
      id: 'tk_032',
      questionText: 'Angka tak berdimensi yang menjadi analogi Bilangan Nusselt pada transfer massa dinamakan:',
      options: ['Bilangan Sherwood (Sh)', 'Bilangan Schmidt', 'Bilangan Peclet', 'Bilangan Stanton'],
      correctOptionIndex: 0,
      explanation: 'Bilangan Sherwood (Sh) mengukur transfer massa konvektif.',
    ),
    QuestionItem(
      id: 'tk_033',
      questionText: 'Analogi transfer momentum, panas, dan massa yang terkenal dinamakan Analogi:',
      options: ['Analogi Chilton-Colburn / Reynolds', 'Analogi Taylor', 'Analogi Prandtl', 'Analogi Fick'],
      correctOptionIndex: 0,
      explanation: 'Analogi Chilton-Colburn menyambungkan j-factor massa, panas, dan gesekan fluida.',
    ),
    QuestionItem(
      id: 'tk_034',
      questionText: 'Gas ideal memenuhi persamaan keadaan (Equation of State):',
      options: ['P V = n R T', 'P V = R T^2', 'P / V = n R T', 'P T = n R V'],
      correctOptionIndex: 0,
      explanation: 'Persamaan gas ideal PV = nRT.',
    ),
    QuestionItem(
      id: 'tk_035',
      questionText: 'Persamaan keadaan nyata (Real Gas) yang memperhitungkan volume molekul (b) dan gaya tarik antarmolekul (a) dinamakan:',
      options: ['Persamaan Van der Waals', 'Persamaan Redlich-Kwong', 'Persamaan Peng-Robinson', 'Semua Benar'],
      correctOptionIndex: 3,
      explanation: 'Van der Waals, Redlich-Kwong, dan Peng-Robinson memodelkan penyimpangan gas nyata.',
    ),
    QuestionItem(
      id: 'tk_036',
      questionText: 'Kondisi suhu dan tekanan tertentu di mana fasa cair dan fasa uap tidak dapat dibedakan lagi dinamakan:',
      options: ['Titik Kritis (Critical Point)', 'Titik Tripel', 'Titik Didih', 'Titik Embun'],
      correctOptionIndex: 0,
      explanation: 'Di atas titik kritis, zat bertindak sebagai Fluida Superkritis.',
    ),
    QuestionItem(
      id: 'tk_037',
      questionText: 'Titik di mana ketiga fasa (padat, cair, dan gas) berada dalam kesetimbangan bersama dinamakan:',
      options: ['Titik Tripel (Triple Point)', 'Titik Kritis', 'Titik Beku', 'Titik Nyala'],
      correctOptionIndex: 0,
      explanation: 'Pada titik tripel, padat, cair, dan uap hadir berdampingan stabil.',
    ),
    QuestionItem(
      id: 'tk_038',
      questionText: 'Energi bebas Gibbs (G) didefinisikan sebagai fungsi entalpi (H), suhu (T), dan entropi (S) melalui rumus:',
      options: ['G = H - T S', 'G = H + T S', 'G = U + P V', 'G = T S - H'],
      correctOptionIndex: 0,
      explanation: 'Persamaan energi bebas Gibbs: G = H - TS.',
    ),
    QuestionItem(
      id: 'tk_039',
      questionText: 'Kriteria ketersediaan reaksi berlanjut secara spontan pada suhu dan tekanan konstan adalah:',
      options: ['Delta G < 0 (Negatif)', 'Delta G > 0', 'Delta G = 0', 'Delta H = 0'],
      correctOptionIndex: 0,
      explanation: 'Reaksi eksergonik spontan ditandai perubahan energi bebas Gibbs negatif.',
    ),
    QuestionItem(
      id: 'tk_040',
      questionText: 'Persamaan Clausius-Clapeyron memodelkan hubungan antara:',
      options: ['Tekanan Uap Jenuh dan Suhu', 'Volume dan Massa Jenis', 'Entalpi dan Entropi', 'Kapasitas Panas'],
      correctOptionIndex: 0,
      explanation: 'Clausius-Clapeyron memodelkan kurva perubahan tekanan uap terhadap suhu transisi fasa.',
    ),
    QuestionItem(
      id: 'tk_041',
      questionText: 'Suatu proses termodinamika yang berlangsung pada suhu konstan dinamakan proses:',
      options: ['Isotermal', 'Isobarik', 'Isokhorik', 'Adiabatis'],
      correctOptionIndex: 0,
      explanation: 'Isotermal beroperasi pada temperatur tetap (Delta T = 0).',
    ),
    QuestionItem(
      id: 'tk_042',
      questionText: 'Suatu proses termodinamika yang berlangsung pada tekanan konstan dinamakan proses:',
      options: ['Isobarik', 'Isotermal', 'Isokhorik', 'Politropik'],
      correctOptionIndex: 0,
      explanation: 'Isobarik berlangsung pada tekanan sistem tetap.',
    ),
    QuestionItem(
      id: 'tk_043',
      questionText: 'Suatu proses termodinamika yang berlangsung tanpa adanya pertukaran kalor dengan lingkungan (Q = 0) dinamakan:',
      options: ['Adiabatis', 'Isotermal', 'Isobarik', 'Isokhorik'],
      correctOptionIndex: 0,
      explanation: 'Adiabatis terisolasi sempurna tanpa transfer kalor.',
    ),
    QuestionItem(
      id: 'tk_044',
      questionText: 'Diagram yang menampilkan kurva kesetimbangan air-udara (kelembaban, suhu bola kering, suhu bola basah) dinamakan:',
      options: ['Diagram Psikrometri (Psychrometric Chart)', 'Diagram Mollier', 'Diagram T-s', 'Diagram P-h'],
      correctOptionIndex: 0,
      explanation: 'Diagram psikrometri digunakan untuk desain sistem pengeringan dan pengondisian udara (HVAC).',
    ),
    QuestionItem(
      id: 'tk_045',
      questionText: 'Suhu udara murni yang diukur oleh termometer standar tanpa kelembaban dinamakan suhu:',
      options: ['Bola Kering (Dry-Bulb Temperature)', 'Bola Basah', 'Titik Embun', 'Suhu Saturation'],
      correctOptionIndex: 0,
      explanation: 'Dry-bulb temperature adalah suhu lingkungan riil.',
    ),
    QuestionItem(
      id: 'tk_046',
      questionText: 'Suhu saat udara jenuh dengan uap air sehingga embun mulai berkondensasi dinamakan suhu:',
      options: ['Titik Embun (Dew Point Temperature)', 'Bola Kering', 'Bola Basah', 'Titik Didih'],
      correctOptionIndex: 0,
      explanation: 'Dew point adalah suhu saat RH mencapai 100% dan kondensasi terjadi.',
    ),
    QuestionItem(
      id: 'tk_047',
      questionText: 'Peralatan pabrik kimia yang berfungsi mendinginkan air pendingin bekas dengan kontak udara ambient dinamakan:',
      options: ['Menara Pendingin (Cooling Tower)', 'Kondensor', 'Evaporator', 'Chiller'],
      correctOptionIndex: 0,
      explanation: 'Cooling tower mendinginkan air sirkulasi lewat penguapan konvektif udara.',
    ),
    QuestionItem(
      id: 'tk_048',
      questionText: 'Peralatan pemisah fase padat dari cairan menggunakan media filter berpori dinamakan:',
      options: ['Filtrasi (Filter Press / Vacuum Filter)', 'Sedimentasi', 'Sentrifugasi', 'Flotasi'],
      correctOptionIndex: 0,
      explanation: 'Filtrasi menahan partikel padat pada kain/medium filter.',
    ),
    QuestionItem(
      id: 'tk_049',
      questionText: 'Operasi pemisahan padatan tersuspensi berdasarkan pengendapan akibat gaya gravitasi dinamakan:',
      options: ['Sedimentasi (Clarifier / Thickener)', 'Filtrasi', 'Flotasi', 'Sentrifugasi'],
      correctOptionIndex: 0,
      explanation: 'Sedimentasi mengendapkan lumpur padat di dasar tangki clarifier.',
    ),
    QuestionItem(
      id: 'tk_050',
      questionText: 'Operasi pemisahan fasa berdasarkan percepatan gaya sentrifugal tinggi dinamakan:',
      options: ['Sentrifugasi (Centrifuge)', 'Sedimentasi', 'Cyclone', 'Filtrasi'],
      correctOptionIndex: 0,
      explanation: 'Centrifuge memisahkan suspensi padat-cair atau cair-cair berputar kecepatan tinggi.',
    ),
    QuestionItem(
      id: 'tk_051',
      questionText: 'Peralatan pemisah debu padat dari aliran gas menggunakan aliran pusaran siklon dinamakan:',
      options: ['Siklon (Cyclone Separator)', 'Baghouse Filter', 'Scrubber', 'Electrostatic Precipitator'],
      correctOptionIndex: 0,
      explanation: 'Cyclone memanfaatkan gaya sentrifugal memisahkan partikel debu dari gas.',
    ),
    QuestionItem(
      id: 'tk_052',
      questionText: 'Alat penangkap debu industri memanfaatkan medan listrik tegangan tinggi untuk menarik partikel debu dinamakan:',
      options: ['ESP (Electrostatic Precipitator)', 'Cyclone', 'Venturi Scrubber', 'Filter Bag'],
      correctOptionIndex: 0,
      explanation: 'ESP memberi muatan ion pada debu lalu mengendapkannya di pelat pengumpul.',
    ),
    QuestionItem(
      id: 'tk_053',
      questionText: 'Peralatan pembersih gas buang industri menggunakan semprotan cairan penyerap dinamakan:',
      options: ['Scrubber (Wet Scrubber)', 'Cyclone', 'Filter Press', 'Adsorber'],
      correctOptionIndex: 0,
      explanation: 'Wet scrubber menyemprotkan air/cairan kimia menyerap polutan gas beracun (seperti SOx/NOx).',
    ),
    QuestionItem(
      id: 'tk_054',
      questionText: 'Zat asam sulfat (H2SO4) diproduksi secara masif di industri kimia melalui proses terkenal dinamakan:',
      options: ['Proses Kontak (Contact Process)', 'Proses Haber-Bosch', 'Proses Ostwald', 'Proses Solvay'],
      correctOptionIndex: 0,
      explanation: 'Proses Kontak mengoksidasi SO2 menjadi SO3 menggunakan katalis V2O5.',
    ),
    QuestionItem(
      id: 'tk_055',
      questionText: 'Sintesis gas Amonia (NH3) dari gas Nitrogen dan Hidrogen di industri mengandalkan proses:',
      options: ['Proses Haber-Bosch', 'Proses Kontak', 'Proses Solvay', 'Proses Fischer-Tropsch'],
      correctOptionIndex: 0,
      explanation: 'Proses Haber-Bosch mengombinasikan N2 dan H2 pada tekanan tinggi dengan katalis berbasis besi.',
    ),
    QuestionItem(
      id: 'tk_056',
      questionText: 'Proses industri pembentukan Asam Nitrat (HNO3) dari oksidasi amonia dinamakan:',
      options: ['Proses Ostwald', 'Proses Haber', 'Proses Kontak', 'Proses Chlor-Alkali'],
      correctOptionIndex: 0,
      explanation: 'Proses Ostwald mengoksidasi amonia menggunakan katalis Platinum-Rhodium.',
    ),
    QuestionItem(
      id: 'tk_057',
      questionText: 'Industri pengolahan minyak bumi memisahkan minyak mentah menjadi fraksi-fraksinya menggunakan:',
      options: ['Distilasi Bertingkat (Fractional Distillation)', 'Ekstraksi', 'Absorpsi', 'Kristalisasi'],
      correctOptionIndex: 0,
      explanation: 'Distilasi fraksinasi memisahkan minyak bumi berdasar rentang titik didih (LPG, Bensin, Kerosin, Solar).',
    ),
    QuestionItem(
      id: 'tk_058',
      questionText: 'Proses pemecahan hidrokarbon rantai panjang menjadi molekul hidrokarbon pendek berharga tinggi dinamakan:',
      options: ['Cracking (Fluid Catalytic Cracking / FCC)', 'Reforming', 'Blending', 'Polymerization'],
      correctOptionIndex: 0,
      explanation: 'Cracking memutus rantai berat residu minyak menjadi fraksi bensin.',
    ),
    QuestionItem(
      id: 'tk_059',
      questionText: 'Proses pengubahan struktur hidrokarbon rantai lurus menjadi hidrokarbon bercabang bertoktan tinggi dinamakan:',
      options: ['Reforming (Catalytic Reforming)', 'Cracking', 'Alkilasi', 'Coking'],
      correctOptionIndex: 0,
      explanation: 'Reforming meningkatkan nilai Angka Oktan bensin.',
    ),
    QuestionItem(
      id: 'tk_060',
      questionText: 'Angka yang menunjukkan kualitas ketahanan bensin terhadap ketukan (knocking) dalam mesin dinamakan:',
      options: ['Angka Oktan (Octane Number)', 'Angka Setan (Cetane Number)', 'Nilai Kalor', 'Titik Nyala'],
      correctOptionIndex: 0,
      explanation: 'Angka Oktan (seperti RON 92, 95) mengukur ketahanan bahan bakar bensin dari ketukan.',
    ),
    QuestionItem(
      id: 'tk_061',
      questionText: 'Angka yang menunjukkan kualitas kemampuan menyala bahan bakar solar/diesel dinamakan:',
      options: ['Angka Setan (Cetane Number)', 'Angka Oktan', 'Titik Tuang', 'Viskositas Kinematis'],
      correctOptionIndex: 0,
      explanation: 'Angka Setan (Cetane Number) mengukur kemudahan penyalaan bahan bakar diesel.',
    ),
    QuestionItem(
      id: 'tk_062',
      questionText: 'Polimerisasi gabungan monomer-monomer sejenis tanpa pelepasan molekul sampingan dinamakan polimerisasi:',
      options: ['Adisi', 'Kondensasi', 'Kopolimer', 'Radikal'],
      correctOptionIndex: 0,
      explanation: 'Polimerisasi adisi membuka ikatan rangkap monomer (seperti Polietilena).',
    ),
    QuestionItem(
      id: 'tk_063',
      questionText: 'Polimerisasi yang menghasilkan molekul sampingan kecil (seperti air H2O atau HCl) dinamakan polimerisasi:',
      options: ['Kondensasi', 'Adisi', 'Anionik', 'Ziegler-Natta'],
      correctOptionIndex: 0,
      explanation: 'Polimerisasi kondensasi membebaskan byproduct air (seperti pembentukan Nylon/PET).',
    ),
    QuestionItem(
      id: 'tk_064',
      questionText: 'Plastik yang dapat dilunakkan kembali dengan pemanasan berulang kali dinamakan plastik:',
      options: ['Termoplastik (Thermoplastic)', 'Termoset (Thermosetting)', 'Elastomer', 'Resin Sintetis'],
      correctOptionIndex: 0,
      explanation: 'Termoplastik (seperti PE, PP, PVC) dapat didaur ulang dipanaskan leleh kembali.',
    ),
    QuestionItem(
      id: 'tk_065',
      questionText: 'Plastik yang mengalami perubahan kimia permanen saat dicetak sehingga tidak dapat dilelehkan kembali dinamakan:',
      options: ['Termoset (Thermoset)', 'Termoplastik', 'Karet Alam', 'Polimer Adisi'],
      correctOptionIndex: 0,
      explanation: 'Termoset (seperti Bakelit, Epoksi) membentuk ikatan silang kaku yang akan hangus jika dipanaskan ulang.',
    ),
    QuestionItem(
      id: 'tk_066',
      questionText: 'Proses vulkanisasi karet alam mengandalkan penambahan unsur pembuat ikatan silang berupa:',
      options: ['Belerang / Sulfur (S)', 'Karbon Black', 'Silika', 'Kalsium'],
      correctOptionIndex: 0,
      explanation: 'Vulkanisasi belerang membentuk jembatan sulfur meningkatkan kekuatan dan elastisitas karet.',
    ),
    QuestionItem(
      id: 'tk_067',
      questionText: 'Gas buang cerobong pabrik yang menjadi pemicu utama hujan asam adalah:',
      options: ['Sulfur Oksida (SOx) dan Nitrogen Oksida (NOx)', 'Karbon Monoksida (CO)', 'Metana (CH4)', 'CFC'],
      correctOptionIndex: 0,
      explanation: 'SO2 dan NO2 bereaksi dengan uap air di atmosfer membentuk H2SO4 dan HNO3 penyebab hujan asam.',
    ),
    QuestionItem(
      id: 'tk_068',
      questionText: 'Indikator pengujian limbah cair yang mengukur jumlah oksigen terlarut yang dibutuhkan mikroba untuk menguraikan bahan organik dinamakan:',
      options: ['BOD (Biological Oxygen Demand)', 'COD (Chemical Oxygen Demand)', 'TSS', 'TDS'],
      correctOptionIndex: 0,
      explanation: 'BOD mengukur konsumsi oksigen biologis oleh bakteri pencerna limbah.',
    ),
    QuestionItem(
      id: 'tk_069',
      questionText: 'Indikator limbah cair yang mengukur total oksigen yang dibutuhkan untuk mengoksidasi bahan organik secara kimiawi dinamakan:',
      options: ['COD (Chemical Oxygen Demand)', 'BOD', 'DO', 'pH'],
      correctOptionIndex: 0,
      explanation: 'COD mengukur pengoksidasi kimiawi kuat (K2Cr2O7) dan nilainya selalu lebih tinggi dari BOD.',
    ),
    QuestionItem(
      id: 'tk_070',
      questionText: 'Perbandingan nilai BOD/COD limbah cair yang > 0.5 mengindikasikan bahwa limbah tersebut bersifat:',
      options: ['Mudah Dibiodeflokulasi / Biodegradable', 'Non-biodegradable', 'Beracun', 'Anorganik Murni'],
      correctOptionIndex: 0,
      explanation: 'Rasio BOD/COD tinggi berarti limbah cocok diolah dengan pemrosesan biologi.',
    ),
    QuestionItem(
      id: 'tk_071',
      questionText: 'Proses pengolahan air minum berbasis membran полупроницаемый (semipermeabel) tekanan tinggi dinamakan:',
      options: ['Reverse Osmosis (RO)', 'Ultrafiltrasi', 'Elektrodialisis', 'Mikrofiltrasi'],
      correctOptionIndex: 0,
      explanation: 'RO memaksa air murni menembus membran menahan garam terlarut (desalinasi).',
    ),
    QuestionItem(
      id: 'tk_072',
      questionText: 'Proses penambahan koagulan (seperti Tawas / Al2(SO4)3) untuk menggumpalkan koloid limbah dinamakan:',
      options: ['Koagulasi dan Flokulasi', 'Sedimentasi', 'Aerasi', 'Klorinasi'],
      correctOptionIndex: 0,
      explanation: 'Koagulan menetralkan muatan koloid, dan flokulasi menggumpalkannya menjadi flok besar.',
    ),
    QuestionItem(
      id: 'tk_073',
      questionText: 'Suatu analisis keselamatan kerja pabrik kimia berbasis identifikasi bahaya dan operabilitas dinamakan:',
      options: ['HAZOP (Hazard and Operability Study)', 'FMEA', 'FTA', 'JSA'],
      correctOptionIndex: 0,
      explanation: 'HAZOP menggunakan kata panduan (guide words) mengidentifikasi penyimpangan sistem pabrik.',
    ),
    QuestionItem(
      id: 'tk_074',
      questionText: 'Kata panduan (Guide Words) dalam studi HAZOP mencakup kata-kata:',
      options: ['NO / MORE / LESS / AS WELL AS / REVERSE', 'HIGH / LOW', 'FAST / SLOW', 'SAFE / DANGER'],
      correctOptionIndex: 0,
      explanation: 'HAZOP menggunakan parameter No, More, Less, Part Of, Reverse, dsb.',
    ),
    QuestionItem(
      id: 'tk_075',
      questionText: 'Alat ukur debit aliran fluida berdasar perbedaan tekanan melalui penyempitan venturi dinamakan:',
      options: ['Venturimeter / Orificemeter', 'Rotameter', 'Pitot Tube', 'Anemometer'],
      correctOptionIndex: 0,
      explanation: 'Venturi dan Orifice meter mengukur debit dari beda tekanan (Delta P).',
    ),
    QuestionItem(
      id: 'tk_076',
      questionText: 'Alat ukur debit fluida transparan berposisi vertikal dengan pelampung (float) dinamakan:',
      options: ['Rotameter (Variable Area Flowmeter)', 'Venturimeter', 'Turbine Meter', 'Clipper'],
      correctOptionIndex: 0,
      explanation: 'Rotameter mengukur debit berdasarkan posisi ketinggian pelampung terangkat.',
    ),
    QuestionItem(
      id: 'tk_077',
      questionText: 'Pipa kecil pengukur kecepatan lokal fluida berbasis tekanan statis dan stagnasi dinamakan:',
      options: ['Tabung Pitot (Pitot Tube)', 'Venturimeter', 'Manometer U', 'Orifice'],
      correctOptionIndex: 0,
      explanation: 'Pitot tube mengukur kecepatan lokal v = sqrt(2 g Delta h).',
    ),
    QuestionItem(
      id: 'tk_078',
      questionText: 'Konsep integrasi panas antar aliran panas dan dingin untuk menghemat energi pabrik dinamakan:',
      options: ['Pinch Technology (Teknologi Pinch)', 'Heat Exchanger Network', 'Exergy Analysis', 'Audit Energi'],
      correctOptionIndex: 0,
      explanation: 'Teknologi Pinch menentukan temperatur batas terdekat recovery energi terintegrasi.',
    ),
    QuestionItem(
      id: 'tk_079',
      questionText: 'Pengukuran ketersediaan energi kerja maksimum dari suatu sistem dinamakan:',
      options: ['Eksergi (Exergy)', 'Entalpi', 'Entropi', 'Energi Dalam'],
      correctOptionIndex: 0,
      explanation: 'Eksergi mengukur porsi energi berguna yang dapat dikonversi menjadi kerja.',
    ),
    QuestionItem(
      id: 'tk_080',
      questionText: 'Suatu rasio tanpa dimensi yang menunjukkan kebasahan udara terhadap kapasitas air jenuh dinamakan:',
      options: ['Kelembaban Relatif (RH / Relative Humidity)', 'Kelembaban Spesifik', 'Beban Kelembaban', 'Entalpi Udara'],
      correctOptionIndex: 0,
      explanation: 'RH = (Tekanan parsial uap air / Tekanan uap jenuh) x 100%.',
    ),
    QuestionItem(
      id: 'tk_081',
      questionText: 'Metode pengolahan minyak kelapa sawit mentah (CPO) memisahkan asam lemak bebas menggunakan distilasi dinamakan:',
      options: ['Refining & Deodorization', 'Degumming', 'Fractionation', 'Bleaching'],
      correctOptionIndex: 0,
      explanation: 'Refining menghilangkan asam lemak bebas, warna, dan bau tak sedap CPO.',
    ),
    QuestionItem(
      id: 'tk_082',
      questionText: 'Proses penghilangan getah fosfolipid dari CPO menggunakan asam fosfat dinamakan:',
      options: ['Degumming', 'Bleaching', 'Deodorization', 'Winterization'],
      correctOptionIndex: 0,
      explanation: 'Degumming mengendapkan senyawa fosfatida (gum).',
    ),
    QuestionItem(
      id: 'tk_083',
      questionText: 'Proses pemucatan warna gelap CPO mengandalkan adsorpsi menggunakan tanah pemucat dinamakan:',
      options: ['Bleaching (Bleaching Earth)', 'Degumming', 'Fractionation', 'Hydrogenation'],
      correctOptionIndex: 0,
      explanation: 'Bleaching earth menyerap pigmen karotenoid dan klorofil minyak.',
    ),
    QuestionItem(
      id: 'tk_084',
      questionText: 'Proses pembuatan sabun dari reaksi saponifikasi minyak/lemak dengan basa kuat (NaOH/KOH) menghasilkan sabun dan:',
      options: ['Gliserol (Gliserin)', 'Asam Karboksilat', 'Ester', 'Alkohol Murni'],
      correctOptionIndex: 0,
      explanation: 'Trigliserida + 3 NaOH -> 3 Garam Sabun + Gliserol.',
    ),
    QuestionItem(
      id: 'tk_085',
      questionText: 'Proses transesterifikasi trigliserida minyak nabati dengan metanol menghasilkan bahan bakar terbarukan dinamakan:',
      options: ['Biodiesel (FAME / Fatty Acid Methyl Ester)', 'Bioetanol', 'Biogas', 'Bioavtur'],
      correctOptionIndex: 0,
      explanation: 'Transesterifikasi mengubah minyak nabati menjadi metil ester (biodiesel) dan gliserol.',
    ),
    QuestionItem(
      id: 'tk_086',
      questionText: 'Proses fermentasi karbohidrat gula menggunakan khamir yeast menghasilkan bahan bakar cair berupa:',
      options: ['Bioetanol', 'Biodiesel', 'Biogas', 'Biolubricant'],
      correctOptionIndex: 0,
      explanation: 'Bioetanol diperoleh dari fermentasi gula/pati oleh Saccharomyces cerevisiae.',
    ),
    QuestionItem(
      id: 'tk_087',
      questionText: 'Gas terbarukan hasil pencernaan anaerobik sampah organik yang didominasi gas Metana (CH4) dinamakan:',
      options: ['Biogas', 'Syngas', 'LPG', 'LNG'],
      correctOptionIndex: 0,
      explanation: 'Biogas mengandung 50-70% CH4 dan CO2 dari dekoposisi anaerob.',
    ),
    QuestionItem(
      id: 'tk_088',
      questionText: 'Gas sintetis (Syngas) hasil gasifikasi batubara atau biomassa terdiri dari campuran utama gas:',
      options: ['Karbon Monoksida (CO) dan Hidrogen (H2)', 'Metana dan Oksigen', 'CO2 dan Nitrogen', 'Amonia dan Uap Air'],
      correctOptionIndex: 0,
      explanation: 'Syngas (CO + H2) adalah bahan baku sintesis kimia.',
    ),
    QuestionItem(
      id: 'tk_089',
      questionText: 'Proses konversi Syngas (CO + H2) menjadi bahan bakar sintetis cair mengandalkan proses:',
      options: ['Proses Fischer-Tropsch (FT)', 'Proses Haber', 'Proses Bergius', 'Proses Kroll'],
      correctOptionIndex: 0,
      explanation: 'Sintesis Fischer-Tropsch mengonversi CO dan H2 menjadi hidrokarbon rantai panjang.',
    ),
    QuestionItem(
      id: 'tk_090',
      questionText: 'Material padat berpori orde nanometer yang dimanfaatkan sebagai katalis perengkahan dan penukar ion dinamakan:',
      options: ['Zeolit', 'Silika Gel', 'Alumina', 'Titania'],
      correctOptionIndex: 0,
      explanation: 'Zeolit memiliki struktur aluminosilikat berpori seragam.',
    ),
    QuestionItem(
      id: 'tk_091',
      questionText: 'Polimer termoplas terpopuler berbahan dasar monomer Etilena yang dipakai pada kantong plastik dinamakan:',
      options: ['Polietilena (PE)', 'Polipropilena (PP)', 'Polistirena (PS)', 'PVC'],
      correctOptionIndex: 0,
      explanation: 'Polietilena (HDPE/LDPE) disintesis dari monomer etilena CH2=CH2.',
    ),
    QuestionItem(
      id: 'tk_092',
      questionText: 'Polimer plastik yang mengandung unsur Klorin dan populer digunakan untuk pipa saluran air dinamakan:',
      options: ['PVC (Polyvinyl Chloride)', 'PET', 'Teflon', 'Nylon'],
      correctOptionIndex: 0,
      explanation: 'PVC disintesis dari vinil klorida.',
    ),
    QuestionItem(
      id: 'tk_093',
      questionText: 'Polimer anti-lengket tahan panas berbahan dasar Politetrafluoroetilena dinamakan merek dagang:',
      options: ['Teflon (PTFE)', 'Kevlar', 'Bakelit', 'Akrilik'],
      correctOptionIndex: 0,
      explanation: 'PTFE (Teflon) memiliki koefisien gesek amat rendah dan tahan kimia.',
    ),
    QuestionItem(
      id: 'tk_094',
      questionText: 'Bahan polimer sintetik sangat kuat anti-peluru berbahan aramid dinamakan:',
      options: ['Kevlar', 'Nylon 66', 'Dacron', 'Spandex'],
      correctOptionIndex: 0,
      explanation: 'Kevlar adalah poliamida aromatik berkecepatan tarik tinggi.',
    ),
    QuestionItem(
      id: 'tk_095',
      questionText: 'Bahan semen portland dibuat dengan membakar campuran utama batu kapur (CaCO3) dan tanah liat di dalam:',
      options: ['Tanur Putar (Rotary Kiln)', 'Autoklaf', 'Boiler', 'Reaktor CSTR'],
      correctOptionIndex: 0,
      explanation: 'Rotary kiln membakar bahan baku semen pada suhu 1450°C menghasilkan klinker.',
    ),
    QuestionItem(
      id: 'tk_096',
      questionText: 'Komponen klinker semen yang berfungsi mengatur waktu pengikatan (setting time) adalah penambahan:',
      options: ['Gipsum (Kalsium Sulfat / CaSO4.2H2O)', 'Pasir Silika', 'Biji Besi', 'Kapur Tohor'],
      correctOptionIndex: 0,
      explanation: 'Gipsum ditambahkan saat penggilingan klinker agar semen tidak kilat mengeras (flash set).',
    ),
    QuestionItem(
      id: 'tk_097',
      questionText: 'Pupuk kimia anorganik sumber hara Nitrogen murni bertkadar N ~46% adalah:',
      options: ['Urea (CO(NH2)2)', 'ZA (Zwapelzure Ammoniak)', 'TSP', 'KCL'],
      correctOptionIndex: 0,
      explanation: 'Urea mengandung kadar nitrogen tertinggi 46%.',
    ),
    QuestionItem(
      id: 'tk_098',
      questionText: 'Pupuk ZA merupakan sumber hara hara Nitrogen dan:',
      options: ['Belerang / Sulfur (S)', 'Fosfor (P)', 'Kalium (K)', 'Kalsium (Ca)'],
      correctOptionIndex: 0,
      explanation: 'ZA (Ammonium Sulfat) mengandung N 21% dan S 24%.',
    ),
    QuestionItem(
      id: 'tk_099',
      questionText: 'Perangkat penampungu uap air bertekanan tinggi hasil pembakaran di industri dinamakan:',
      options: ['Boiler (Ketel Uap)', 'Turbin', 'Kondensor', 'Evaporator'],
      correctOptionIndex: 0,
      explanation: 'Boiler memanaskan air murni menjadi uap bertekanan (steam).',
    ),
    QuestionItem(
      id: 'tk_100',
      questionText: 'Uap air superpanas tanpa titik-titik air bebas yang dipakai memutar turbin dinamakan:',
      options: ['Superheated Steam (Uap Lewat Panas)', 'Saturated Steam', 'Wet Steam', 'Condensate'],
      correctOptionIndex: 0,
      explanation: 'Superheated steam bersuhu tinggi mencegah kondensasi erosi pada sudu turbin.',
    ),
  ];
}
