import '../tes_seleksi_model.dart';

List<QuestionItem> getTeknikInformatikaQuestions() {
  return const [
    QuestionItem(
      id: 'ti_001',
      questionText: 'Kompleksitas waktu terbaik untuk algoritma Pencarian Biner (Binary Search) adalah:',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'],
      correctOptionIndex: 0,
      explanation: 'Pencarian biner menemukan elemen di tengah pada langkah pertama O(1).',
    ),
    QuestionItem(
      id: 'ti_002',
      questionText: 'Struktur data mana yang menerapkan prinsip LIFO (Last In First Out)?',
      options: ['Queue', 'Stack', 'Array', 'Linked List'],
      correctOptionIndex: 1,
      explanation: 'Stack menggunakan konsep LIFO.',
    ),
    QuestionItem(
      id: 'ti_003',
      questionText: 'Apa kepanjangan dari SQL dalam manajemen basis data?',
      options: ['Structured Query Language', 'Simple Query Logic', 'System Quality Language', 'Sequential Query List'],
      correctOptionIndex: 0,
      explanation: 'SQL singkatan dari Structured Query Language.',
    ),
    QuestionItem(
      id: 'ti_004',
      questionText: 'Manakah protokol jaringan yang berjalan di port default 443?',
      options: ['HTTP', 'HTTPS', 'FTP', 'SSH'],
      correctOptionIndex: 1,
      explanation: 'HTTPS menggunakan port 443.',
    ),
    QuestionItem(
      id: 'ti_005',
      questionText: 'Konsep OOP di mana kelas turunan mewarisi sifat dari kelas induk disebut:',
      options: ['Encapsulation', 'Inheritance', 'Polymorphism', 'Abstraction'],
      correctOptionIndex: 1,
      explanation: 'Inheritance adalah pewarisan sifat.',
    ),
    QuestionItem(
      id: 'ti_006',
      questionText: 'Fungsi utama dari CPU (Central Processing Unit) adalah:',
      options: ['Menyimpan data jangka panjang', 'Mengolah instruksi dan eksekusi program', 'Menampilkan grafik di layar', 'Menyuplai daya ke motherboard'],
      correctOptionIndex: 1,
      explanation: 'CPU bertugas memproses instruksi aritmatika dan logika.',
    ),
    QuestionItem(
      id: 'ti_007',
      questionText: 'Format sistem bilangan berbasis 16 disebut bilangan:',
      options: ['Biner', 'Oktal', 'Desimal', 'Heksadesimal'],
      correctOptionIndex: 3,
      explanation: 'Basis 16 adalah heksadesimal.',
    ),
    QuestionItem(
      id: 'ti_008',
      questionText: 'Algoritma sorting yang membagi himpunan data menjadi 2 bagian secara rekursif adalah:',
      options: ['Bubble Sort', 'Selection Sort', 'Merge Sort', 'Insertion Sort'],
      correctOptionIndex: 2,
      explanation: 'Merge sort mengadopsi pendekatan Divide and Conquer.',
    ),
    QuestionItem(
      id: 'ti_009',
      questionText: 'Istilah "Deadlock" dalam Sistem Operasi mengacu pada:',
      options: ['Kondisi memori penuh', 'Kondisi 2 atau lebih proses saling menunggu sumber daya secara permanen', 'Proses booting yang gagal', 'Serangan malware dari jaringan'],
      correctOptionIndex: 1,
      explanation: 'Deadlock terjadi saat proses terjebak saling menunggu.',
    ),
    QuestionItem(
      id: 'ti_010',
      questionText: 'Manakah yang BUKAN merupakan tipe data primitif dalam Java?',
      options: ['int', 'boolean', 'char', 'String'],
      correctOptionIndex: 3,
      explanation: 'String di Java adalah objek/referensi.',
    ),
    QuestionItem(
      id: 'ti_011',
      questionText: 'Port default untuk protokol SSH adalah:',
      options: ['21', '22', '80', '8080'],
      correctOptionIndex: 1,
      explanation: 'Port default SSH adalah 22.',
    ),
    QuestionItem(
      id: 'ti_012',
      questionText: 'Struktur data pohon di mana setiap node memiliki maksimal dua anak dinamakan:',
      options: ['B-Tree', 'Binary Tree', 'AVL Tree', 'Red-Black Tree'],
      correctOptionIndex: 1,
      explanation: 'Binary tree memiliki maksimal 2 anak per node.',
    ),
    QuestionItem(
      id: 'ti_013',
      questionText: 'Di bawah ini yang BUKAN merupakan basis data relasional (RDBMS) adalah:',
      options: ['PostgreSQL', 'MySQL', 'MongoDB', 'Oracle DB'],
      correctOptionIndex: 2,
      explanation: 'MongoDB adalah basis data NoSQL.',
    ),
    QuestionItem(
      id: 'ti_014',
      questionText: 'Distribusi sistem operasi yang menggunakan Kernel Linux adalah:',
      options: ['Windows 11', 'Ubuntu', 'macOS', 'iOS'],
      correctOptionIndex: 1,
      explanation: 'Ubuntu berbasis Kernel Linux.',
    ),
    QuestionItem(
      id: 'ti_015',
      questionText: 'Prinsip SOLID dalam pemrograman berorientasi objek, huruf S mewakili:',
      options: ['Single Responsibility Principle', 'System Integration', 'Software Security', 'Sequential Execution'],
      correctOptionIndex: 0,
      explanation: 'S singkatan dari Single Responsibility Principle.',
    ),
    QuestionItem(
      id: 'ti_016',
      questionText: 'Notasi matematika untuk menghitung batas atas kompleksitas algoritma adalah:',
      options: ['Big O Notation', 'Big Omega Notation', 'Big Theta Notation', 'Little o Notation'],
      correctOptionIndex: 0,
      explanation: 'Big O mengukur batas atas terburuk.',
    ),
    QuestionItem(
      id: 'ti_017',
      questionText: 'Protokol yang menerjemahkan nama domain menjadi IP Address adalah:',
      options: ['DHCP', 'DNS', 'ARP', 'NAT'],
      correctOptionIndex: 1,
      explanation: 'DNS (Domain Name System).',
    ),
    QuestionItem(
      id: 'ti_018',
      questionText: 'Version Control System (VCS) berbasis terdistribusi yang sangat populer adalah:',
      options: ['Docker', 'Git', 'Kubernetes', 'Jenkins'],
      correctOptionIndex: 1,
      explanation: 'Git adalah DVCS terpopuler.',
    ),
    QuestionItem(
      id: 'ti_019',
      questionText: 'Perintah SQL untuk memasukkan baris data baru ke tabel adalah:',
      options: ['ADD', 'UPDATE', 'INSERT INTO', 'CREATE'],
      correctOptionIndex: 2,
      explanation: 'INSERT INTO menambahkan baris baru.',
    ),
    QuestionItem(
      id: 'ti_020',
      questionText: 'Bahasa pemrograman yang dieksekusi secara native oleh peramban web (browser) adalah:',
      options: ['Python', 'Java', 'JavaScript', 'C++'],
      correctOptionIndex: 2,
      explanation: 'JavaScript dieksekusi oleh web browser.',
    ),
    QuestionItem(
      id: 'ti_021',
      questionText: 'Manakah arsitektur jaringan yang menempatkan perangkat sebagai penyedia layanan dan penerima layanan?',
      options: ['Peer to Peer', 'Client-Server', 'Mesh', 'Ring'],
      correctOptionIndex: 1,
      explanation: 'Arsitektur Client-Server.',
    ),
    QuestionItem(
      id: 'ti_022',
      questionText: 'Nilai desimal 10 jika diubah ke dalam bentuk biner adalah:',
      options: ['1001', '1010', '1100', '1110'],
      correctOptionIndex: 1,
      explanation: '1010 dalam biner sama dengan 10 desimal.',
    ),
    QuestionItem(
      id: 'ti_023',
      questionText: 'Operator logika XOR akan menghasilkan nilai 1 (TRUE) jika:',
      options: ['Kedua input bernilai 1', 'Kedua input bernilai 0', 'Kedua input memiliki nilai berbeda', 'Kedua input memiliki nilai sama'],
      correctOptionIndex: 2,
      explanation: 'XOR bernilai true jika kedua input berlawanan.',
    ),
    QuestionItem(
      id: 'ti_024',
      questionText: 'Istilah "Refactoring" dalam pemrograman mengacu pada:',
      options: ['Menambahkan fitur baru ke aplikasi', 'Mengubah struktur internal kode tanpa mengubah perilaku eksternalnya', 'Menghapus basis data lama', 'Mengunggah aplikasi ke server'],
      correctOptionIndex: 1,
      explanation: 'Refactoring meningkatkan kualitas struktur kode tanpa mengubah fungsionalitas.',
    ),
    QuestionItem(
      id: 'ti_025',
      questionText: 'Framework pemetaan objek ke basis data relasional di dunia Java dinamakan:',
      options: ['Hibernate / JPA', 'ReactJS', 'Laravel', 'Django'],
      correctOptionIndex: 0,
      explanation: 'Hibernate/JPA adalah ORM Java.',
    ),
    QuestionItem(
      id: 'ti_026',
      questionText: 'Komponen dalam arsitektur komputer yang menyimpan data instruksi sementara dengan kecepatan sangat tinggi adalah:',
      options: ['Harddisk', 'RAM', 'Cache Memory', 'Flashdisk'],
      correctOptionIndex: 2,
      explanation: 'Cache memory sangat cepat dan menempel dekat CPU.',
    ),
    QuestionItem(
      id: 'ti_027',
      questionText: 'Kondisi "Buffer Overflow" terjadi saat:',
      options: ['Program menulis data melebihi kapasitas memori yang dialokasikan', 'Koneksi internet terputus', 'Baterai perangkat habis', 'File gagal diunduh'],
      correctOptionIndex: 0,
      explanation: 'Buffer overflow menimpa alokasi memori bersebelahan.',
    ),
    QuestionItem(
      id: 'ti_028',
      questionText: 'Manakah dari berikut ini yang BUKAN merupakan metode HTTP?',
      options: ['GET', 'POST', 'PUSH', 'DELETE'],
      correctOptionIndex: 2,
      explanation: 'HTTP menggunakan PUT/PATCH/POST/DELETE, PUSH bukan metode request standar.',
    ),
    QuestionItem(
      id: 'ti_029',
      questionText: 'Proses mengubah plain text menjadi cipertext yang tak terbaca tanpa kunci dinamakan:',
      options: ['Dekripsi', 'Enkripsi', 'Hashing', 'Kompresi'],
      correctOptionIndex: 1,
      explanation: 'Enkripsi menyandikan pesan.',
    ),
    QuestionItem(
      id: 'ti_030',
      questionText: 'Fungsi Hash satu arah yang populer dan menghasilkan nilai output 256-bit adalah:',
      options: ['MD5', 'SHA-256', 'RSA', 'AES'],
      correctOptionIndex: 1,
      explanation: 'SHA-256 adalah algoritma cryptographic hash 256 bit.',
    ),
    QuestionItem(
      id: 'ti_031',
      questionText: 'Metode pengujian perangkat lunak tanpa melihat struktur kode internalnya dinamakan:',
      options: ['White Box Testing', 'Black Box Testing', 'Gray Box Testing', 'Unit Testing'],
      correctOptionIndex: 1,
      explanation: 'Black Box Testing fokus pada masukan dan keluaran fungsi.',
    ),
    QuestionItem(
      id: 'ti_032',
      questionText: 'Format pertukaran data berbasis teks yang ringan dan mudah dibaca manusia serta mesin adalah:',
      options: ['XML', 'JSON', 'CSV', 'YAML'],
      correctOptionIndex: 1,
      explanation: 'JSON (JavaScript Object Notation).',
    ),
    QuestionItem(
      id: 'ti_033',
      questionText: 'Di bawah ini yang termasuk ke dalam kompiler bahasa C++ adalah:',
      options: ['GCC / G++', 'JVM', 'CPython', 'Node.js'],
      correctOptionIndex: 0,
      explanation: 'GCC (GNU Compiler Collection) dikembangkan untuk C/C++.',
    ),
    QuestionItem(
      id: 'ti_034',
      questionText: 'Metodologi pengembangan sistem perangkat lunak berbentuk alur sekuensial linear dinamakan:',
      options: ['Waterfall Model', 'Agile Model', 'Scrum', 'Extreme Programming'],
      correctOptionIndex: 0,
      explanation: 'Waterfall adalah model sekuensial linear bertahap.',
    ),
    QuestionItem(
      id: 'ti_035',
      questionText: 'Istilah "Virtual Memory" pada sistem operasi mengacu pada:',
      options: ['RAM fisik tambahan', 'Penggunaan sebagian ruang penyimpanan sekunder (disk) sebagai ekstensi RAM', 'Kartu memori eksternal', 'Penyimpanan cloud'],
      correctOptionIndex: 1,
      explanation: 'Virtual memory memanfaatkan ruang disk saat RAM penuh.',
    ),
    QuestionItem(
      id: 'ti_036',
      questionText: 'Arsitektur mikroservis (Microservices) membagi aplikasi menjadi:',
      options: ['Satu blok kode raksasa yang tak terpisahkan', 'Layanan-layanan kecil independen yang saling berkomunikasi via API', 'File HTML dan CSS tunggal', 'Satu tabel basis data monolithic'],
      correctOptionIndex: 1,
      explanation: 'Microservices memecah aplikasi jadi modul independen.',
    ),
    QuestionItem(
      id: 'ti_037',
      questionText: 'Manakah protokol yang bertugas menetapkan alamat IP secara otomatis kepada perangkat dalam jaringan?',
      options: ['DNS', 'DHCP', 'FTP', 'SMTP'],
      correctOptionIndex: 1,
      explanation: 'DHCP (Dynamic Host Configuration Protocol).',
    ),
    QuestionItem(
      id: 'ti_038',
      questionText: 'Protokol standar untuk pengiriman surat elektronik (email) di internet adalah:',
      options: ['HTTP', 'SMTP', 'SNMP', 'POP3'],
      correctOptionIndex: 1,
      explanation: 'SMTP (Simple Mail Transfer Protocol) bertugas mengemas & mengirim email.',
    ),
    QuestionItem(
      id: 'ti_039',
      questionText: 'Metode pengurutan "Quick Sort" memilih satu elemen acak sebagai acuan yang disebut:',
      options: ['Index', 'Pivot', 'Root', 'Leaf'],
      correctOptionIndex: 1,
      explanation: 'Quick sort menggunakan elemen pivot.',
    ),
    QuestionItem(
      id: 'ti_040',
      questionText: 'Model OSI Layer terdiri dari berapa lapisan?',
      options: ['4 Lapisan', '5 Lapisan', '7 Lapisan', '9 Lapisan'],
      correctOptionIndex: 2,
      explanation: 'Model OSI memiliki 7 lapisan (Physical hingga Application).',
    ),
    QuestionItem(
      id: 'ti_041',
      questionText: 'Perangkat keras jaringan yang bekerja pada Layer 2 (Data Link) dan mengirim frame data berdasarkan MAC Address dinamakan:',
      options: ['Hub', 'Switch', 'Router', 'Repeater'],
      correctOptionIndex: 1,
      explanation: 'Switch Layer 2 memforward data berdasarkan MAC Address.',
    ),
    QuestionItem(
      id: 'ti_042',
      questionText: 'Perangkat keras jaringan yang bekerja pada Layer 3 (Network) untuk menghubungkan 2 jaringan berbeda dinamakan:',
      options: ['Switch', 'Hub', 'Router', 'Modem'],
      correctOptionIndex: 2,
      explanation: 'Router meneruskan paket antar subnet/jaringan berbasis IP.',
    ),
    QuestionItem(
      id: 'ti_043',
      questionText: 'Manakah algoritma enkripsi simetris modern dengan blok data 128-bit yang dipakai standar global?',
      options: ['AES (Advanced Encryption Standard)', 'RSA', 'Diffie-Hellman', 'ECC'],
      correctOptionIndex: 0,
      explanation: 'AES adalah standar enkripsi simetris.',
    ),
    QuestionItem(
      id: 'ti_044',
      questionText: 'Enkripsi asimetris menggunakan sepasang kunci yaitu:',
      options: ['Kunci Utama & Kunci Cadangan', 'Kunci Publik & Kunci Privat', 'Kunci Lokal & Kunci Server', 'Kunci Master & Kunci Sesi'],
      correctOptionIndex: 1,
      explanation: 'Enkripsi asimetris menggunakan Public Key & Private Key.',
    ),
    QuestionItem(
      id: 'ti_045',
      questionText: 'Teknik dalam SQL di mana penyerang menyisipkan perintah SQL ilegal melalui form masukan aplikasi dinamakan:',
      options: ['Cross-Site Scripting (XSS)', 'SQL Injection (SQLi)', 'CSRF', 'Man in the Middle (MitM)'],
      correctOptionIndex: 1,
      explanation: 'SQL Injection menyisipkan sintaks SQL via input.',
    ),
    QuestionItem(
      id: 'ti_046',
      questionText: 'Kerentanan web di mana penyerang menyuntikkan skrip malicious JavaScript ke halaman web yang dilihat pengguna lain adalah:',
      options: ['SQL Injection', 'Cross-Site Scripting (XSS)', 'Buffer Overflow', 'DoS Attack'],
      correctOptionIndex: 1,
      explanation: 'XSS menyuntikkan skrip JS di browser korban.',
    ),
    QuestionItem(
      id: 'ti_047',
      questionText: 'Dalam basis data, sifat ACID yang menjamin bahwa seluruh transaksi berhasil penuh atau batal sama sekali dinamakan:',
      options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
      correctOptionIndex: 0,
      explanation: 'Atomicity menggaransi transaksi All-or-Nothing.',
    ),
    QuestionItem(
      id: 'ti_048',
      questionText: 'Proses normalisasi basis data hingga bentuk 3NF bertujuan untuk meminimalkan:',
      options: ['Jumlah tabel', 'Redundansi data dan anomali', 'Kecepatan query', 'Ukuran indeks'],
      correctOptionIndex: 1,
      explanation: 'Normalisasi menghilangkan redundansi dan anomali data.',
    ),
    QuestionItem(
      id: 'ti_049',
      questionText: 'Atribut dalam tabel basis data relasional yang merujuk pada Primary Key dari tabel lain dinamakan:',
      options: ['Candidate Key', 'Super Key', 'Foreign Key', 'Alternate Key'],
      correctOptionIndex: 2,
      explanation: 'Foreign Key mengaitkan relasi ke Primary Key tabel lain.',
    ),
    QuestionItem(
      id: 'ti_050',
      questionText: 'Manakah tipe indeks basis data yang menyusun ulang urutan fisik data aktual pada disk?',
      options: ['Non-Clustered Index', 'Clustered Index', 'Secondary Index', 'Hash Index'],
      correctOptionIndex: 1,
      explanation: 'Clustered index menentukan urutan penyimpanan fisik data pada tabel.',
    ),
    QuestionItem(
      id: 'ti_051',
      questionText: 'Perintah SQL DDL untuk menghapus seluruh isi tabel secara cepat tanpa mencatat log per baris adalah:',
      options: ['DELETE FROM', 'TRUNCATE TABLE', 'DROP TABLE', 'REMOVE TABLE'],
      correctOptionIndex: 1,
      explanation: 'TRUNCATE TABLE mengosongkan tabel dengan cepat.',
    ),
    QuestionItem(
      id: 'ti_052',
      questionText: 'Perintah SQL DDL untuk menghapus struktur tabel beserta isinya secara permanen adalah:',
      options: ['TRUNCATE TABLE', 'DELETE TABLE', 'DROP TABLE', 'ALTER TABLE'],
      correctOptionIndex: 2,
      explanation: 'DROP TABLE menghapus skema dan data tabel.',
    ),
    QuestionItem(
      id: 'ti_053',
      questionText: 'Arsitektur kontainerisasi yang memungkinkan pengemasan aplikasi beserta dependensinya adalah:',
      options: ['VirtualBox', 'Docker', 'VMware', 'KVM'],
      correctOptionIndex: 1,
      explanation: 'Docker adalah platform kontainerisasi populer.',
    ),
    QuestionItem(
      id: 'ti_054',
      questionText: 'Platform orchestrator otomatis untuk pengelolaan kontainer skala besar adalah:',
      options: ['Kubernetes (K8s)', 'Nginx', 'Apache', 'RabbitMQ'],
      correctOptionIndex: 0,
      explanation: 'Kubernetes mengatur kluster kontainer.',
    ),
    QuestionItem(
      id: 'ti_055',
      questionText: 'Pola desain software (Design Pattern) yang memastikan hanya ada SATU instansi dari sebuah kelas dinamakan:',
      options: ['Factory Pattern', 'Singleton Pattern', 'Observer Pattern', 'Adapter Pattern'],
      correctOptionIndex: 1,
      explanation: 'Singleton menjamin hanya ada 1 instance objek.',
    ),
    QuestionItem(
      id: 'ti_056',
      questionText: 'Pola desain yang memberikan mekanisme langganan (subscription) saat terjadi perubahan status objek dinamakan:',
      options: ['Observer Pattern', 'Singleton Pattern', 'Decorator Pattern', 'Strategy Pattern'],
      correctOptionIndex: 0,
      explanation: 'Observer pattern memberitahu dependent object saat ada perubahan.',
    ),
    QuestionItem(
      id: 'ti_057',
      questionText: 'Konsep dalam pemrograman fungsional di mana fungsi dapat menerima fungsi lain sebagai argumen dinamakan:',
      options: ['Higher-Order Function', 'Pure Function', 'Lambda Expression', 'Recursive Function'],
      correctOptionIndex: 0,
      explanation: 'Higher-order function mengambil/mengembalikan fungsi lain.',
    ),
    QuestionItem(
      id: 'ti_058',
      questionText: 'Teknik eksekusi program di mana tugas dapat berjalan di latar belakang tanpa menghentikan thread utama dinamakan:',
      options: ['Synchronous', 'Asynchronous', 'Blocking', 'Sequential'],
      correctOptionIndex: 1,
      explanation: 'Asynchronous memproses non-blocking di latar belakang.',
    ),
    QuestionItem(
      id: 'ti_059',
      questionText: 'Kondisi "Race Condition" pada pemrograman multi-threading terjadi saat:',
      options: ['Thread berjalan terlalu cepat', 'Dua atau lebih thread mengakses sumber daya bersama secara bersamaan tanpa sinkronisasi', 'Program kekurangan memori', 'Prosesor mengalami overheat'],
      correctOptionIndex: 1,
      explanation: 'Race condition dipicu akses bersama tanpa kendali sinkronisasi.',
    ),
    QuestionItem(
      id: 'ti_060',
      questionText: 'Mekanisme sinkronisasi thread untuk mengunci akses ke bagian kode kritis dinamakan:',
      options: ['Semaphore / Mutex', 'Garbage Collector', 'Deadlock', 'Buffer'],
      correctOptionIndex: 0,
      explanation: 'Mutex/Semaphore memberikan mutual exclusion penguncian.',
    ),
    QuestionItem(
      id: 'ti_061',
      questionText: 'Di bawah ini yang BUKAN merupakan bagian dari memori proses (Process Memory Layout) adalah:',
      options: ['Stack', 'Heap', 'Text / Code Segment', 'Network Segment'],
      correctOptionIndex: 3,
      explanation: 'Layout memori terdiri dari Text, Data, BSS, Heap, dan Stack.',
    ),
    QuestionItem(
      id: 'ti_062',
      questionText: 'Alokasi memori dinamis di bahasa C/C++ dialokasikan pada area:',
      options: ['Stack', 'Heap', 'Register', 'ROM'],
      correctOptionIndex: 1,
      explanation: 'Memori dinamis (malloc/new) bertempat di Heap.',
    ),
    QuestionItem(
      id: 'ti_063',
      questionText: 'Variabel lokal dan alamat kembalian panggilan fungsi disimpan di area memori:',
      options: ['Heap', 'Stack', 'BSS Segment', 'Harddisk'],
      correctOptionIndex: 1,
      explanation: 'Stack menyimpan bingkai fungsi (call frame) dan lokal variabel.',
    ),
    QuestionItem(
      id: 'ti_064',
      questionText: 'Proses otomatis membebaskan memori yang tidak lagi dirujuk oleh objek aktif di Java/Dart dinamakan:',
      options: ['Defragmentation', 'Garbage Collection', 'Memory Paging', 'Swapping'],
      correctOptionIndex: 1,
      explanation: 'Garbage collection mereklamasi memori yang tak terpakai.',
    ),
    QuestionItem(
      id: 'ti_065',
      questionText: 'Teknik "Paging" dalam manajemen memori sistem operasi berfungsi untuk:',
      options: ['Membagi memori menjadi blok-blok berukuran tetap (Page)', 'Membuat salinan cadangan file', 'Mempercepat pengiriman jaringan', 'Mengamankan kata sandi'],
      correctOptionIndex: 0,
      explanation: 'Paging membagi memori fisik/fisik virtual ke bentuk Page/Frame.',
    ),
    QuestionItem(
      id: 'ti_066',
      questionText: 'Algoritma penjadwalan CPU di mana setiap proses diberi jatah waktu eksekusi (Time Quantum) secara bergantian dinamakan:',
      options: ['First-Come First-Served (FCFS)', 'Round Robin (RR)', 'Shortest Job First (SJF)', 'Priority Scheduling'],
      correctOptionIndex: 1,
      explanation: 'Round Robin membagi jatah waktu eksekusi secara bergiliran.',
    ),
    QuestionItem(
      id: 'ti_067',
      questionText: 'Manakah algoritma penjadwalan disk yang bergerak menyapu satu arah lalu berbalik arah seperti lift?',
      options: ['FCFS', 'SCAN / Elevator Algorithm', 'SSTF', 'C-LOOK'],
      correctOptionIndex: 1,
      explanation: 'SCAN disebut juga algoritma elevator.',
    ),
    QuestionItem(
      id: 'ti_068',
      questionText: 'Subnet mask prefix /24 dalam IPv4 memiliki bentuk oktet desimal:',
      options: ['255.255.0.0', '255.255.255.0', '255.255.255.128', '255.0.0.0'],
      correctOptionIndex: 1,
      explanation: '/24 bernilai 255.255.255.0 (24 bit 1).',
    ),
    QuestionItem(
      id: 'ti_069',
      questionText: 'Berapa jumlah host maksimum yang dapat dipakai dalam subnet IPv4 /24?',
      options: ['254 Host', '256 Host', '512 Host', '128 Host'],
      correctOptionIndex: 0,
      explanation: '256 total minus Network ID & Broadcast ID = 254 Host.',
    ),
    QuestionItem(
      id: 'ti_070',
      questionText: 'Ukuran alamat IPv6 adalah:',
      options: ['32 bit', '64 bit', '128 bit', '256 bit'],
      correctOptionIndex: 2,
      explanation: 'IPv6 berukuran 128 bit.',
    ),
    QuestionItem(
      id: 'ti_071',
      questionText: 'Di bawah ini yang BUKAN merupakan jenis serangan Denial of Service (DoS/DDoS) adalah:',
      options: ['SYN Flood', 'UDP Flood', 'HTTP Flood', 'SQL Injection'],
      correctOptionIndex: 3,
      explanation: 'SQL Injection adalah serangan kelemahan logika query, bukan pemboman trafik.',
    ),
    QuestionItem(
      id: 'ti_072',
      questionText: 'Serangan keamanan di mana peretas menyadap komunikasi antara dua pihak tanpa diketahui dinamakan:',
      options: ['Man-in-the-Middle (MitM)', 'Phishing', 'Brute Force', 'Zero-Day Exploit'],
      correctOptionIndex: 0,
      explanation: 'MitM menyadap/memanipulasi jalur komunikasi dua pihak.',
    ),
    QuestionItem(
      id: 'ti_073',
      questionText: 'Metode peretasan kata sandi dengan menguji seluruh kombinasi karakter secara sistematis dinamakan:',
      options: ['Dictionary Attack', 'Brute Force Attack', 'Social Engineering', 'Rainbow Table Attack'],
      correctOptionIndex: 1,
      explanation: 'Brute force mencobakan semua kombinasi karakter hingga cocok.',
    ),
    QuestionItem(
      id: 'ti_074',
      questionText: 'Teknik manipulasi psikologis untuk membujuk orang agar memberikan informasi rahasia dinamakan:',
      options: ['Social Engineering', 'Phishing', 'Ransomware', 'Trojan Horse'],
      correctOptionIndex: 0,
      explanation: 'Social engineering memanfaatkan kelemahan psikologis manusia.',
    ),
    QuestionItem(
      id: 'ti_075',
      questionText: 'Malware yang mengunci/mengekskripsi data korban dan meminta tebusan dinamakan:',
      options: ['Spyware', 'Ransomware', 'Adware', 'Rootkit'],
      correctOptionIndex: 1,
      explanation: 'Ransomware menyandera file dan meminta tebusan.',
    ),
    QuestionItem(
      id: 'ti_076',
      questionText: 'Dalam graf, pencarian lintasan terpendek dari satu titik sumber ke seluruh titik lain pada bobot positif menggunakan algoritma:',
      options: ['Dijkstra Algorithm', 'Kruskal Algorithm', 'Prim Algorithm', 'Bellman-Ford Algorithm'],
      correctOptionIndex: 0,
      explanation: 'Algoritma Dijkstra menemukan lintasan terpendek berbobot positif.',
    ),
    QuestionItem(
      id: 'ti_077',
      questionText: 'Algoritma untuk mencari Minimum Spanning Tree (MST) dalam graf berbobot adalah:',
      options: ['Kruskal & Prim', 'Dijkstra & A*', 'BFS & DFS', 'Floyd-Warshall'],
      correctOptionIndex: 0,
      explanation: 'Kruskal dan Prim mencari Minimum Spanning Tree.',
    ),
    QuestionItem(
      id: 'ti_078',
      questionText: 'Pencarian mendalam dalam graf yang menggunakan struktur data Stack/Rekursi dinamakan:',
      options: ['Breadth-First Search (BFS)', 'Depth-First Search (DFS)', 'Binary Search', 'Linear Search'],
      correctOptionIndex: 1,
      explanation: 'DFS menelusuri secara mendalam memakai Stack.',
    ),
    QuestionItem(
      id: 'ti_079',
      questionText: 'Pencarian melebar dalam graf yang menggunakan struktur data Queue dinamakan:',
      options: ['Depth-First Search (DFS)', 'Breadth-First Search (BFS)', 'Best-First Search', 'A* Search'],
      correctOptionIndex: 1,
      explanation: 'BFS menelusuri secara mendatar per level memakai Queue.',
    ),
    QuestionItem(
      id: 'ti_080',
      questionText: 'Struktur data khusus berupa Pohon Biner yang memenuhi sifat "Nilai induk selalu lebih besar dari anaknya" dinamakan:',
      options: ['Max Heap', 'Min Heap', 'AVL Tree', 'B-Tree'],
      correctOptionIndex: 0,
      explanation: 'Max Heap memiliki nilai parent >= children.',
    ),
    QuestionItem(
      id: 'ti_081',
      questionText: 'Teknik pemrograman Dynamic Programming memecahkan masalah dengan menyimpan hasil sub-masalah yang pernah dihitung yang disebut:',
      options: ['Memoization / Tabulation', 'Recursion', 'Backtracking', 'Divide and Conquer'],
      correctOptionIndex: 0,
      explanation: 'Memoization/Tabulation menyimpan solusi sub-masalah agar tidak dihitung ulang.',
    ),
    QuestionItem(
      id: 'ti_082',
      questionText: 'Di bawah ini yang BUKAN merupakan contoh algoritma pembawa konsep "Greedy" adalah:',
      options: ['Algoritma Fractional Knapsack', 'Algoritma Huffman Coding', 'Algoritma Dijkstra', 'Algoritma 0/1 Knapsack (DP)'],
      correctOptionIndex: 3,
      explanation: '0/1 Knapsack diselesaikan dengan Dynamic Programming, bukan Greedy.',
    ),
    QuestionItem(
      id: 'ti_083',
      questionText: 'Dalam jaringan komputer, fungsi utama dari protokol ARP (Address Resolution Protocol) adalah:',
      options: ['Menerjemahkan IP Address menjadi MAC Address', 'Menerjemahkan Domain menjadi IP Address', 'Membagi beban server', 'Mengecek integritas paket'],
      correctOptionIndex: 0,
      explanation: 'ARP memetakan IP address ke physical/MAC address.',
    ),
    QuestionItem(
      id: 'ti_084',
      questionText: 'Protokol Transport Layer yang bersifat Connection-Oriented dan menjamin pengiriman paket secara urut adalah:',
      options: ['UDP (User Datagram Protocol)', 'TCP (Transmission Control Protocol)', 'IP (Internet Protocol)', 'ICMP'],
      correctOptionIndex: 1,
      explanation: 'TCP menjamin kelengkapan dan urutan paket.',
    ),
    QuestionItem(
      id: 'ti_085',
      questionText: 'Protokol Transport Layer yang bersifat Connectionless dan cepat tanpa handshake dinamakan:',
      options: ['TCP', 'UDP', 'FTP', 'HTTP'],
      correctOptionIndex: 1,
      explanation: 'UDP adalah connectionless protocol tanpa jaminan pengiriman.',
    ),
    QuestionItem(
      id: 'ti_086',
      questionText: 'Perintah ping pada terminal sistem operasi menggunakan protokol jaringan:',
      options: ['IGMP', 'ICMP (Internet Control Message Protocol)', 'ARP', 'SNMP'],
      correctOptionIndex: 1,
      explanation: 'Ping memanfaatkan ICMP Echo Request & Reply.',
    ),
    QuestionItem(
      id: 'ti_087',
      questionText: 'Dalam arsitektur web RESTful API, status kode HTTP 200 OK berarti:',
      options: ['Permintaan Berhasil', 'Resource Baru Berhasil Dibuat', 'Klien Tidak Terotorisasi', 'Halaman Tidak Ditemukan'],
      correctOptionIndex: 0,
      explanation: 'HTTP 200 OK menandakan sukses.',
    ),
    QuestionItem(
      id: 'ti_088',
      questionText: 'Status kode HTTP 404 Not Found berarti:',
      options: ['Kesalahan Server Internal', 'Permintaan Tidak Sah', 'Sumber Daya / Halaman Tidak Ditemukan', 'Akses Ditolak'],
      correctOptionIndex: 2,
      explanation: 'HTTP 404 menandakan endpoint/file tak ditemukan.',
    ),
    QuestionItem(
      id: 'ti_089',
      questionText: 'Status kode HTTP 500 Internal Server Error mengindikasikan:',
      options: ['Kesalahan pada sisi server saat memproses permintaan', 'Koneksi terputus', 'Password salah', 'Server dialihkan'],
      correctOptionIndex: 0,
      explanation: '500 mengindikasikan crash/error pada backend server.',
    ),
    QuestionItem(
      id: 'ti_090',
      questionText: 'Istilah "CDN (Content Delivery Network)" berfungsi untuk:',
      options: ['Menyimpan cache konten statis di berbagai lokasi server geografis terdekat pengguna', 'Mengenkripsi basis data', 'Membuat skema database', 'Menghapus virus'],
      correctOptionIndex: 0,
      explanation: 'CDN mendekatkan konten ke lokasi geografis pengguna.',
    ),
    QuestionItem(
      id: 'ti_091',
      questionText: 'Teknik pengujian kode di mana developer menulis tes otomatis sebelum menulis kode implementasi dinamakan:',
      options: ['Test-Driven Development (TDD)', 'Behavior-Driven Development (BDD)', 'Integration Testing', 'Regression Testing'],
      correctOptionIndex: 0,
      explanation: 'TDD menekankan penulisan test diawal.',
    ),
    QuestionItem(
      id: 'ti_092',
      questionText: 'Pengujian otomatis untuk memastikan perubahan kode baru tidak merusak fungsi yang sudah ada dinamakan:',
      options: ['Regression Testing', 'Unit Testing', 'Acceptance Testing', 'Smoke Testing'],
      correctOptionIndex: 0,
      explanation: 'Regression testing menjamin fungsionalitas lama tidak rusak.',
    ),
    QuestionItem(
      id: 'ti_093',
      questionText: 'Teknologi Machine Learning di mana model dilatih menggunakan data yang memiliki label target dinamakan:',
      options: ['Supervised Learning', 'Unsupervised Learning', 'Reinforcement Learning', 'Semi-Unsupervised'],
      correctOptionIndex: 0,
      explanation: 'Supervised learning menggunakan dataset berlabel.',
    ),
    QuestionItem(
      id: 'ti_094',
      questionText: 'Teknik Machine Learning seperti Clustering K-Means yang mengelompokkan data tanpa label dinamakan:',
      options: ['Supervised Learning', 'Unsupervised Learning', 'Reinforcement Learning', 'Deep Learning'],
      correctOptionIndex: 1,
      explanation: 'Unsupervised learning mengolah data tanpa petunjuk label.',
    ),
    QuestionItem(
      id: 'ti_095',
      questionText: 'Arsitektur Jaringan Saraf Tiruan (Artificial Neural Network) yang sangat efektif memproses citra/gambar adalah:',
      options: ['Convolutional Neural Network (CNN)', 'Recurrent Neural Network (RNN)', 'Long Short-Term Memory (LSTM)', 'Multilayer Perceptron'],
      correctOptionIndex: 0,
      explanation: 'CNN dirancang unggul mengolah data spasial gambar.',
    ),
    QuestionItem(
      id: 'ti_096',
      questionText: 'Arsitektur Deep Learning seperti Transformer / GPT sangat dominan digunakan dalam pemrosesan:',
      options: ['Natural Language Processing (NLP)', 'Audio Signal Filtering', 'Hardware Compiling', 'Network Routing'],
      correctOptionIndex: 0,
      explanation: 'Transformer mendominasi bidang pemrosesan bahasa alami (NLP).',
    ),
    QuestionItem(
      id: 'ti_097',
      questionText: 'Konsep dalam pemrograman Berorientasi Objek untuk menyembunyikan detail detail internal dan hanya menampilkan interface luar dinamakan:',
      options: ['Encapsulation / Abstraction', 'Polymorphism', 'Inheritance', 'Overriding'],
      correctOptionIndex: 0,
      explanation: 'Encapsulation menyembunyikan detail implementasi internal.',
    ),
    QuestionItem(
      id: 'ti_098',
      questionText: 'Kemampuan sebuah objek untuk memiliki banyak bentuk method dengan nama yang sama tetapi perilaku berbeda dinamakan:',
      options: ['Polymorphism', 'Encapsulation', 'Inheritance', 'Instantiation'],
      correctOptionIndex: 0,
      explanation: 'Polymorphism berarti banyak bentuk.',
    ),
    QuestionItem(
      id: 'ti_099',
      questionText: 'Dalam bahasa SQL, klausa yang digunakan untuk menyaring hasil pengelompokan (GROUP BY) dinamakan:',
      options: ['WHERE', 'HAVING', 'ORDER BY', 'FILTER'],
      correctOptionIndex: 1,
      explanation: 'HAVING memfilter agregat hasil pengelompokan GROUP BY.',
    ),
    QuestionItem(
      id: 'ti_100',
      questionText: 'Struktur data non-linear yang terdiri dari kumpulan Simpul (Node) dan Sisi (Edge) dinamakan:',
      options: ['Graph', 'Array', 'Stack', 'Queue'],
      correctOptionIndex: 0,
      explanation: 'Graph terdiri dari himpunan Vertex/Node dan Edge.',
    ),
  ];
}
