import '../tes_seleksi_model.dart';

List<QuestionItem> getTeknikMesinQuestions() {
  return const [
    QuestionItem(
      id: 'tm_001',
      questionText: 'Hukum Pertama Termodinamika merupakan bentuk pernyataan dari Hukum:',
      options: ['Kekekalan Energi', 'Kekekalan Massa', 'Kekekalan Momentum', 'Entropi Maksimum'],
      correctOptionIndex: 0,
      explanation: 'Hukum I Termodinamika menyatakan energi tidak dapat diciptakan atau dimusnahkan (Q - W = Delta U).',
    ),
    QuestionItem(
      id: 'tm_002',
      questionText: 'Hukum Kedua Termodinamika memperkenalkan konsep besaran fisika:',
      options: ['Entropi (S)', 'Entalpi (H)', 'Suhu (T)', 'Kerja (W)'],
      correctOptionIndex: 0,
      explanation: 'Hukum II Termodinamika menyatakan entropi total alam semesta selalu meningkat.',
    ),
    QuestionItem(
      id: 'tm_003',
      questionText: 'Siklus termodinamika teoritis paling ideal dengan efisiensi maksimum dinamakan:',
      options: ['Siklus Carnot', 'Siklus Rankine', 'Siklus Otto', 'Siklus Diesel'],
      correctOptionIndex: 0,
      explanation: 'Siklus Carnot memberikan batas efisiensi termal maksimum.',
    ),
    QuestionItem(
      id: 'tm_004',
      questionText: 'Siklus termodinamika yang menjadi acuan standar untuk mesin bensin (Spark-Ignition) adalah:',
      options: ['Siklus Otto', 'Siklus Diesel', 'Siklus Brayton', 'Siklus Stirling'],
      correctOptionIndex: 0,
      explanation: 'Mesin bensin bekerja berdasarkan idealisasi Siklus Otto (pembakaran volume konstan).',
    ),
    QuestionItem(
      id: 'tm_005',
      questionText: 'Siklus termodinamika acuan dasar untuk mesin Diesel (Compression-Ignition) adalah:',
      options: ['Siklus Diesel', 'Siklus Otto', 'Siklus Rankine', 'Siklus Ericsson'],
      correctOptionIndex: 0,
      explanation: 'Siklus Diesel memodelkan pembakaran pada tekanan konstan.',
    ),
    QuestionItem(
      id: 'tm_006',
      questionText: 'Siklus termodinamika standar untuk pembangkit listrik tenaga uap (PLTU) adalah:',
      options: ['Siklus Rankine', 'Siklus Brayton', 'Siklus Otto', 'Siklus Carnot'],
      correctOptionIndex: 0,
      explanation: 'PLTU beroperasi menggunakan Siklus Rankine air-uap.',
    ),
    QuestionItem(
      id: 'tm_007',
      questionText: 'Siklus termodinamika acuan untuk mesin turbin gas dan mesin jet pesawat adalah:',
      options: ['Siklus Brayton / Joule', 'Siklus Rankine', 'Siklus Diesel', 'Siklus Stirling'],
      correctOptionIndex: 0,
      explanation: 'Turbin gas beroperasi sesuai Siklus Brayton.',
    ),
    QuestionItem(
      id: 'tm_008',
      questionText: 'Mekanisme perpindahan panas melalui kontak fisik molekul benda padat tanpa perpindahan zat dinamakan:',
      options: ['Konduksi', 'Konveksi', 'Radiasi', 'Evaporasi'],
      correctOptionIndex: 0,
      explanation: 'Konduksi merambat lewat getaran atom benda padat.',
    ),
    QuestionItem(
      id: 'tm_009',
      questionText: 'Perpindahan panas yang disertai perpindahan molekul fluida (cair/gas) dinamakan:',
      options: ['Konveksi', 'Konduksi', 'Radiasi', 'Sublimasi'],
      correctOptionIndex: 0,
      explanation: 'Konveksi membawa energi kalor bersama aliran pergerakan fluida.',
    ),
    QuestionItem(
      id: 'tm_010',
      questionText: 'Perpindahan panas dalam bentuk gelombang elektromagnetik tanpa memerlukan media perantara dinamakan:',
      options: ['Radiasi', 'Konduksi', 'Konveksi', 'Kondensasi'],
      correctOptionIndex: 0,
      explanation: 'Radiasi (seperti panas matahari) merambat di ruang hampa.',
    ),
    QuestionItem(
      id: 'tm_011',
      questionText: 'Hukum Fourier mengukur laju perpindahan panas secara:',
      options: ['Konduksi', 'Konveksi', 'Radiasi', 'Radiasi Benda Hitam'],
      correctOptionIndex: 0,
      explanation: 'Hukum Fourier: q = -k A (dT/dx) untuk konduksi.',
    ),
    QuestionItem(
      id: 'tm_012',
      questionText: 'Hukum Pendinginan Newton (Newton\'s Law of Cooling) mengukur laju perpindahan panas secara:',
      options: ['Konveksi (q = h A (Ts - Tinf))', 'Konduksi', 'Radiasi', 'Evaporasi'],
      correctOptionIndex: 0,
      explanation: 'Laju konveksi sebanding dengan koefisien konveksi (h) dan beda suhu.',
    ),
    QuestionItem(
      id: 'tm_013',
      questionText: 'Fluida ideal dalam mekanika fluida diasumsikan bersifat:',
      options: ['Inkompresibel (Massa jenis konstan) dan Tanpa Viskositas (Inviscid)', 'Kompresibel', 'Sangat Kental', 'Turbulen'],
      correctOptionIndex: 0,
      explanation: 'Fluida ideal tidak memiliki gesekan viskositas dan volume konstan.',
    ),
    QuestionItem(
      id: 'tm_014',
      questionText: 'Persamaan Bernoulli untuk aliran fluida inkompresibel menyatakan kekekalan:',
      options: ['Energi Total per Satuan Volume (Tekanan + Kinetik + Potensial = Konstan)', 'Massa', 'Momentum', 'Suhu'],
      correctOptionIndex: 0,
      explanation: 'Persamaan Bernoulli menjumlahkan tekanan p + 0.5 rho v^2 + rho g z = konstan.',
    ),
    QuestionItem(
      id: 'tm_015',
      questionText: 'Angka tak berdimensi yang membedakan antara aliran laminer dan aliran turbulen dinamakan:',
      options: ['Bilangan Reynolds (Re)', 'Bilangan Nusselt', 'Bilangan Prandtl', 'Bilangan Mach'],
      correctOptionIndex: 0,
      explanation: 'Bilangan Reynolds (Re = rho v D / mu) menentukan rezim aliran fluida.',
    ),
    QuestionItem(
      id: 'tm_016',
      questionText: 'Batas nilai Bilangan Reynolds (Re) untuk aliran laminer di dalam pipa adalah:',
      options: ['Re < 2300', 'Re > 4000', 'Re = 10000', 'Re > 100000'],
      correctOptionIndex: 0,
      explanation: 'Aliran pipa tenang laminer jika Re < 2300.',
    ),
    QuestionItem(
      id: 'tm_017',
      questionText: 'Aliran fluida dengan garis alir acak berputar cepat dinamakan aliran:',
      options: ['Turbulen (Re > 4000)', 'Laminer', 'Transisi', 'Stasioner'],
      correctOptionIndex: 0,
      explanation: 'Aliran turbulen ditandai fluktuasi acak dan Re > 4000.',
    ),
    QuestionItem(
      id: 'tm_018',
      questionText: 'Perangkat penukar panas (Heat Exchanger) tipe selongsong dan tabung dinamakan:',
      options: ['Shell and Tube Heat Exchanger', 'Plate Heat Exchanger', 'Double Pipe', 'Radiator'],
      correctOptionIndex: 0,
      explanation: 'Shell and tube HE paling umum dipakai di industri pabrik.',
    ),
    QuestionItem(
      id: 'tm_019',
      questionText: 'Mesin fluida yang menambah energi cairan untuk menaikkan tekanan atau mengalirkannya dinamakan:',
      options: ['Pompa', 'Kompresor', 'Turbin', 'Blower'],
      correctOptionIndex: 0,
      explanation: 'Pompa khusus memindahkan cairan (fluida inkompresibel).',
    ),
    QuestionItem(
      id: 'tm_020',
      questionText: 'Mesin fluida yang menaikkan tekanan fluida gas atau udara dinamakan:',
      options: ['Kompresor', 'Pompa Sentrifugal', 'Turbin Air', 'Kipas'],
      correctOptionIndex: 0,
      explanation: 'Kompresor memampatkan gas (fluida kompresibel).',
    ),
    QuestionItem(
      id: 'tm_021',
      questionText: 'Fenomena pembentukan dan pecahnya gelembung uap air di dalam pompa akibat tekanan lokal turun di bawah tekanan uap jenuh dinamakan:',
      options: ['Kavitasi (Cavitation)', 'Surging', 'Water Hammer', 'Stalling'],
      correctOptionIndex: 0,
      explanation: 'Kavitasi merusak sudu-sudu impeller pompa akibat erosi implosi gelembung uap.',
    ),
    QuestionItem(
      id: 'tm_022',
      questionText: 'Lonjakan tekanan kejutan mekanis pada pipa akibat penutupan katup secara mendadak dinamakan:',
      options: ['Water Hammer (Pukulan Air)', 'Kavitasi', 'Choking', 'Venturi Effect'],
      correctOptionIndex: 0,
      explanation: 'Water hammer menimbulkan suara pukulan keras dan merusak pipa.',
    ),
    QuestionItem(
      id: 'tm_023',
      questionText: 'Turbin air tipe impuls yang cocok untuk kepala air (head) tinggi dan debit rendah adalah:',
      options: ['Turbin Pelton', 'Turbin Francis', 'Turbin Kaplan', 'Turbin Crossflow'],
      correctOptionIndex: 0,
      explanation: 'Turbin Pelton diputar oleh semprotan jet air nozzle tekanan tinggi.',
    ),
    QuestionItem(
      id: 'tm_024',
      questionText: 'Turbin air tipe reaksi yang cocok untuk head sedang hingga tinggi adalah:',
      options: ['Turbin Francis', 'Turbin Pelton', 'Turbin Turgo', 'Turbin Banki'],
      correctOptionIndex: 0,
      explanation: 'Turbin Francis adalah turbin reaksi paling banyak dipakai di dunia.',
    ),
    QuestionItem(
      id: 'tm_025',
      questionText: 'Turbin air tipe baling-baling (propeller) yang cocok untuk head rendah dan debit air sangat besar adalah:',
      options: ['Turbin Kaplan', 'Turbin Pelton', 'Turbin Francis', 'Turbin Turgo'],
      correctOptionIndex: 0,
      explanation: 'Turbin Kaplan memiliki sudu runner yang dapat diatur kemiringannya.',
    ),
    QuestionItem(
      id: 'tm_026',
      questionText: 'Diagram fasa besi-karbon (Fe-Fe3C) menunjukkan batas kandungan karbon maksimum pada baja sebesar:',
      options: ['2.14% Karbon', '6.67% Karbon', '0.08% Karbon', '4.3% Karbon'],
      correctOptionIndex: 0,
      explanation: 'Baja didefinisikan memiliki paduan karbon < 2.14% (di atasnya tergolong Besi Tuang/Cast Iron).',
    ),
    QuestionItem(
      id: 'tm_027',
      questionText: 'Kandungan karbon pada Besi Tuang (Cast Iron) berada pada rentang:',
      options: ['2.14% hingga 6.67%', '0.02% hingga 2.14%', '< 0.008%', '> 10%'],
      correctOptionIndex: 0,
      explanation: 'Besi tuang memiliki kadar karbon 2.14% s/d 6.67%.',
    ),
    QuestionItem(
      id: 'tm_028',
      questionText: 'Struktur mikro baja keras berstruktur jarum yang diperoleh dari pendinginan cepat (quenching) dinamakan:',
      options: ['Martensit', 'Austenit', 'Ferit', 'Perlit'],
      correctOptionIndex: 0,
      explanation: 'Quenching cepat mengubah austensit menjadi martensit keras tetapi getas.',
    ),
    QuestionItem(
      id: 'tm_029',
      questionText: 'Proses perlakuan panas (Heat Treatment) memanaskan kembali baja martensit keras untuk meningkatkan keuletan dinamakan:',
      options: ['Tempering', 'Annealing', 'Normalizing', 'Hardening'],
      correctOptionIndex: 0,
      explanation: 'Tempering mengurangi kegetasan martensit.',
    ),
    QuestionItem(
      id: 'tm_030',
      questionText: 'Proses perlakuan panas pendinginan lambat di dalam dapur furnace untuk melunakkan logam dinamakan:',
      options: ['Annealing', 'Quenching', 'Normalizing', 'Carburizing'],
      correctOptionIndex: 0,
      explanation: 'Annealing melunakkan logam dan menghilangkan tegangan dalam.',
    ),
    QuestionItem(
      id: 'tm_031',
      questionText: 'Pengujian mekanik untuk mengukur keuletan dan batas luluh (yield strength) material dinamakan:',
      options: ['Uji Tarik (Tensile Test)', 'Uji Impak', 'Uji Keras', 'Uji Creep'],
      correctOptionIndex: 0,
      explanation: 'Uji tarik menghasilkan kurva tegangan-regangan (Stress-Strain Curve).',
    ),
    QuestionItem(
      id: 'tm_032',
      questionText: 'Hukum Hooke menyatakan bahwa dalam batas elastisitas, tegangan (sigma) sebanding dengan regangan (epsilon) dikali:',
      options: ['Modulus Elastisitas / Modulus Young (E)', 'Modulus Geser (G)', 'Nisbah Poisson (v)', 'Batas Luluh'],
      correctOptionIndex: 0,
      explanation: 'Hukum Hooke: sigma = E x epsilon.',
    ),
    QuestionItem(
      id: 'tm_033',
      questionText: 'Pengujian impak untuk mengukur ketangguhan (toughness) energi patah material menggunakan metode:',
      options: ['Charpy & Izod', 'Rockwell', 'Brinell', 'Vickers'],
      correctOptionIndex: 0,
      explanation: 'Charpy dan Izod mengayunkan beban pendulum memukul spesimen bertakik.',
    ),
    QuestionItem(
      id: 'tm_034',
      questionText: 'Pengujian kekerasan logam menggunakan bola baja keras sebagai penekan dinamakan pengujian:',
      options: ['Brinell', 'Rockwell', 'Vickers', 'Knoop'],
      correctOptionIndex: 0,
      explanation: 'Uji Brinell menekan indenter bola baja ke permukaan logam.',
    ),
    QuestionItem(
      id: 'tm_035',
      questionText: 'Pengujian kekerasan logam menggunakan piramida intan bersudut 136 derajat dinamakan:',
      options: ['Vickers', 'Brinell', 'Rockwell C', 'Shore'],
      correctOptionIndex: 0,
      explanation: 'Uji Vickers mengandalkan penekan piramida intan.',
    ),
    QuestionItem(
      id: 'tm_036',
      questionText: 'Fenomena kegagalan mekanis patahnya komponen akibat beban berulang/siklik di bawah batas luluh dinamakan:',
      options: ['Kelelahan Logam (Fatigue)', 'Merambat (Creep)', 'Buckling', 'Yielding'],
      correctOptionIndex: 0,
      explanation: 'Fatigue memicu retak mikro yang menjalar akibat fluktuasi beban berulang.',
    ),
    QuestionItem(
      id: 'tm_037',
      questionText: 'Deformasi plastis lambat permanen pada komponen yang mengalami beban konstan dan suhu tinggi dinamakan:',
      options: ['Creep (Merambat)', 'Fatigue', 'Wear', 'Corrosion'],
      correctOptionIndex: 0,
      explanation: 'Creep terjadi pada komponen suhu tinggi seperti sudu turbin gas.',
    ),
    QuestionItem(
      id: 'tm_038',
      questionText: 'Elemen mesin yang digunakan untuk mentransmisikan daya putar antar poros dengan rasio kecepatan konstan adalah:',
      options: ['Roda Gigi (Gear)', 'Sabuk (Belt)', 'Rantai (Chain)', 'Kopling'],
      correctOptionIndex: 0,
      explanation: 'Roda gigi memberikan transmisi daya tanpa slip.',
    ),
    QuestionItem(
      id: 'tm_039',
      questionText: 'Jenis roda gigi lurus dengan gigi paralel terhadap sumbu poros dinamakan:',
      options: ['Spur Gear', 'Helical Gear', 'Bevel Gear', 'Worm Gear'],
      correctOptionIndex: 0,
      explanation: 'Spur gear adalah bentuk roda gigi paling sederhana.',
    ),
    QuestionItem(
      id: 'tm_040',
      questionText: 'Jenis roda gigi berbentuk miring membentuk sudut heliks dinamakan:',
      options: ['Helical Gear', 'Spur Gear', 'Bevel Gear', 'Rack and Pinion'],
      correctOptionIndex: 0,
      explanation: 'Helical gear beroperasi lebih halus dan tenang dibanding spur gear.',
    ),
    QuestionItem(
      id: 'tm_041',
      questionText: 'Jenis roda gigi yang digunakan untuk mentransmisikan daya antar dua poros yang bersilangan tegak lurus dinamakan:',
      options: ['Bevel Gear (Roda Gigi Payung)', 'Spur Gear', 'Helical Gear', 'Planetary Gear'],
      correctOptionIndex: 0,
      explanation: 'Bevel gear menghubungkan poros bersilang (seperti gardan mobil).',
    ),
    QuestionItem(
      id: 'tm_042',
      questionText: 'Pasangan roda gigi cacing (Worm & Worm Gear) memiliki keunggulan berupa:',
      options: ['Rasio Pengurangan Kecepatan Sangat Tinggi dan Self-Locking', 'Kecepatan sangat tinggi', 'Efisiensi 100%', 'Bisa berputar balik'],
      correctOptionIndex: 0,
      explanation: 'Worm gear menghasilkan reduksi gigi besar dalam satu pasang.',
    ),
    QuestionItem(
      id: 'tm_043',
      questionText: 'Pasangan roda gigi yang mengonversi gerak putar menjadi gerak lurus translasi dinamakan:',
      options: ['Rack and Pinion', 'Bevel Gear', 'Worm Gear', 'Epicyclic Gear'],
      correctOptionIndex: 0,
      explanation: 'Rack and pinion mengubah putaran pinion menjadi rekstraksi lurus rack (seperti kemudi mobil).',
    ),
    QuestionItem(
      id: 'tm_044',
      questionText: 'Elemen mesin yang berfungsi menumpu dan menahan poros agar dapat berputar tanpa gesekan berlebih dinamakan:',
      options: ['Bantalan (Bearing)', 'Pasak (Key)', 'Kopling (Coupling)', 'Poros (Shaft)'],
      correctOptionIndex: 0,
      explanation: 'Bearing mengurangi gesekan rotasi poros.',
    ),
    QuestionItem(
      id: 'tm_045',
      questionText: 'Bantalan luncur yang memanfaatkan lapisan tipis pelumas cair dinamakan:',
      options: ['Journal Bearing / Sliding Contact Bearing', 'Ball Bearing', 'Roller Bearing', 'Needle Bearing'],
      correctOptionIndex: 0,
      explanation: 'Journal bearing menumpu beban radial pada lapisan pelumas cair.',
    ),
    QuestionItem(
      id: 'tm_046',
      questionText: 'Bantalan gelinding yang mengandalkan elemen bola-bola baja dinamakan:',
      options: ['Ball Bearing (Bantalan Bola)', 'Roller Bearing', 'Tapered Bearing', 'Journal Bearing'],
      correctOptionIndex: 0,
      explanation: 'Ball bearing mengandalkan kontak titik elemen bola.',
    ),
    QuestionItem(
      id: 'tm_047',
      questionText: 'Elemen pengikat silinder berulir luar yang dipasangkan dengan mur (nut) dinamakan:',
      options: ['Baut (Bolt)', 'Sekrup (Screw)', 'Pasak (Key)', 'Paku Keling (Rivet)'],
      correctOptionIndex: 0,
      explanation: 'Baut memegang komponen menggunakan pasangan mur.',
    ),
    QuestionItem(
      id: 'tm_048',
      questionText: 'Elemen pengunci kecil yang dipasang di antara poros dan hub roda gigi untuk mencegah slip diputar dinamakan:',
      options: ['Pasak (Key / Spline)', 'Pasak Pasak', 'Ring Spring', 'Snap Ring'],
      correctOptionIndex: 0,
      explanation: 'Pasak (key) mentransmisikan torsi antara poros dan benda putar.',
    ),
    QuestionItem(
      id: 'tm_049',
      questionText: 'Perangkat pengikat permanen yang dipasang dengan menimpa ujung pasak secara dingin/panas dinamakan:',
      options: ['Paku Keling (Rivet)', 'Baut', 'Pasak', 'Las'],
      correctOptionIndex: 0,
      explanation: 'Rivet menyambungkan lembaran konstruksi secara permanen (seperti pada pesawat/kapal).',
    ),
    QuestionItem(
      id: 'tm_050',
      questionText: 'Elemen pemutus dan penyambung daya putar dari mesin ke transmisi kendaraan dinamakan:',
      options: ['Kopling Gesek (Clutch)', 'Brake', 'Flywheel', 'Differential'],
      correctOptionIndex: 0,
      explanation: 'Clutch memutus dan menghubungkan momen putar dari mesin ke transmisi.',
    ),
    QuestionItem(
      id: 'tm_051',
      questionText: 'Roda gila (Flywheel) pada mesin pembakaran dalam berfungsi untuk:',
      options: ['Menyimpan energi kinetik dan meratakan fluktuasi putaran poros engkol', 'Menaikkan daya', 'Memompa oli', 'Mendinginkan mesin'],
      correctOptionIndex: 0,
      explanation: 'Flywheel meredam fluktuasi siklus pembakaran.',
    ),
    QuestionItem(
      id: 'tm_052',
      questionText: 'Proses pemotongan logam menggunakan pahat potong tunggal berputar pada mesin bubut dinamakan:',
      options: ['Pembubutan (Turning)', 'Fraiss (Milling)', 'Sekrap (Shaping)', 'Gurdur (Drilling)'],
      correctOptionIndex: 0,
      explanation: 'Turning membubut benda kerja yang berputar di chuck.',
    ),
    QuestionItem(
      id: 'tm_053',
      questionText: 'Proses pemotongan logam menggunakan pisau potong jamur berputar (Milling Cutter) dinamakan:',
      options: ['Frais (Milling)', 'Bubut (Turning)', 'Gerinda (Grinding)', 'Broaching'],
      correctOptionIndex: 0,
      explanation: 'Milling memotong permukaan datar atau alur benda kerja.',
    ),
    QuestionItem(
      id: 'tm_054',
      questionText: 'Proses pembuatan lubang silinder menggunakan mata bor berputar dinamakan:',
      options: ['Garis / Bor (Drilling)', 'Boring', 'Reaming', 'Tapping'],
      correctOptionIndex: 0,
      explanation: 'Drilling membuat lubang awal pada material.',
    ),
    QuestionItem(
      id: 'tm_055',
      questionText: 'Proses melebarkan dan menghaluskan ukuran lubang presisi dinamakan:',
      options: ['Boring & Reaming', 'Drilling', 'Tapping', 'Punching'],
      correctOptionIndex: 0,
      explanation: 'Reaming menghaluskan lubang bekas bor ke toleransi ketat.',
    ),
    QuestionItem(
      id: 'tm_056',
      questionText: 'Proses pembuatan ulir dalam pada lubang menggunakan perkakas ulir dinamakan:',
      options: ['Tapping (Tap)', 'Threading (Sneai)', 'Boring', 'Frais'],
      correctOptionIndex: 0,
      explanation: 'Tap membuat ulir dalam, sedangkan Snei (Die) membuat ulir luar.',
    ),
    QuestionItem(
      id: 'tm_057',
      questionText: 'Proses pengikisan presisi permukaan benda keras menggunakan batu gerinda berputar dinamakan:',
      options: ['Penggerindaan (Grinding)', 'Lapping', 'Honing', 'Polishing'],
      correctOptionIndex: 0,
      explanation: 'Grinding penyelesaian akhir kekasaran permukaan halus.',
    ),
    QuestionItem(
      id: 'tm_058',
      questionText: 'Proses manufaktur mencairkan logam dan menuangkannya ke dalam rongga cetakan dinamakan:',
      options: ['Pengecoran Logam (Casting)', 'Penempaan (Forging)', 'Ekstrusi', 'Pengerolan'],
      correctOptionIndex: 0,
      explanation: 'Casting menuangkan cairan logam ke cetakan pasir/logam.',
    ),
    QuestionItem(
      id: 'tm_059',
      questionText: 'Proses pembentukan logam padat menggunakan gaya tekan impak martil penempaan dinamakan:',
      options: ['Penempaan (Forging)', 'Pengecoran', 'Penarikan (Drawing)', 'Pengerolan'],
      correctOptionIndex: 0,
      explanation: 'Forging menghasilkan sifat mekanik rapat dan kuat pada komponen (seperti poros engkol).',
    ),
    QuestionItem(
      id: 'tm_060',
      questionText: 'Proses menekan balok logam panas melewati lubang cetakan die berbentuk profil dinamakan:',
      options: ['Ekstrusi (Extrusion)', 'Pengerolan (Rolling)', 'Deep Drawing', 'Stamping'],
      correctOptionIndex: 0,
      explanation: 'Ekstrusi menghasilkan profil batang memanjang (seperti profil aluminium).',
    ),
    QuestionItem(
      id: 'tm_061',
      questionText: 'Proses mengurangi ketebalan lembaran logam dengan melewatkannya di antara dua rol berputar dinamakan:',
      options: ['Pengerolan (Rolling)', 'Penempaan', 'Ekstrusi', 'Bending'],
      correctOptionIndex: 0,
      explanation: 'Rolling menghasilkan pelat dan lembaran seng/baja.',
    ),
    QuestionItem(
      id: 'tm_062',
      questionText: 'Metode pengelasan busur listrik menggunakan elektroda terbungkus flux dinamakan:',
      options: ['SMAW (Shielded Metal Arc Welding / Las Listrik)', 'GMAW', 'GTAW', 'SAW'],
      correctOptionIndex: 0,
      explanation: 'SMAW (Las stik) menggunakan elektroda terbungkus paling populer.',
    ),
    QuestionItem(
      id: 'tm_063',
      questionText: 'Metode pengelasan busur gas pelindung yang mengandalkan elektroda Tungsten tak terumpan dinamakan:',
      options: ['GTAW / TIG (Tungsten Inert Gas)', 'GMAW / MIG', 'SMAW', 'FCAW'],
      correctOptionIndex: 0,
      explanation: 'TIG (GTAW) mengandalkan elektroda tungsten menghasilkan sambungan halus higienis.',
    ),
    QuestionItem(
      id: 'tm_064',
      questionText: 'Metode pengelasan gas pelindung dengan pengumpanan kawat rol kontinu dinamakan:',
      options: ['GMAW / MIG-MAG (Metal Inert Gas)', 'GTAW', 'SMAW', 'Las Karbit'],
      correctOptionIndex: 0,
      explanation: 'MIG/MAG mengarahkan kawat elektroda kontinu dan gas argon/CO2.',
    ),
    QuestionItem(
      id: 'tm_065',
      questionText: 'Pengelasan menggunakan campuran gas Oksigen dan Asetilen dinamakan:',
      options: ['OAW (Oxy-Acetylene Welding / Las Karbit)', 'SMAW', 'GTAW', 'Plasma Arc'],
      correctOptionIndex: 0,
      explanation: 'OAW memanfaatkan nyala api pembakaran gas O2 dan Asetilen.',
    ),
    QuestionItem(
      id: 'tm_066',
      questionText: 'Mesin perkakas otomatis yang dikendalikan oleh instruksi kode numerik komputer dinamakan:',
      options: ['Mesin CNC (Computer Numerical Control)', 'Mesin Manual', 'PLC', 'Robot Artikulasi'],
      correctOptionIndex: 0,
      explanation: 'CNC meng-otomatiskan gerakan pahat presisi tinggi via G-Code.',
    ),
    QuestionItem(
      id: 'tm_067',
      questionText: 'Kode instruksi standar internasional untuk perintah gerakan pemotongan mesin CNC dinamakan:',
      options: ['G-Code dan M-Code', 'Python', 'Assembly', 'HTML'],
      correctOptionIndex: 0,
      explanation: 'G-Code mengontrol gerakan geometris, M-Code mengontrol fungsi mesin (spindle/coolant).',
    ),
    QuestionItem(
      id: 'tm_068',
      questionText: 'Gerakan getaran mekanis pada sistem yang terus berosilasi tanpa adanya gaya luar pengganggu dinamakan:',
      options: ['Getaran Bebas (Free Vibration)', 'Getaran Paksa', 'Getaran Deredam', 'Resonansi'],
      correctOptionIndex: 0,
      explanation: 'Getaran bebas terjadi saat sistem diberi simpangan awal lalu dilepas.',
    ),
    QuestionItem(
      id: 'tm_069',
      questionText: 'Frekuensi alami osilasi sistem mekanis tanpa adanya peredam dinamakan:',
      options: ['Frekuensi Pribadi (Natural Frequency / fn)', 'Frekuensi Paksa', 'Frekuensi Resonansi', 'Frekuensi Redaman'],
      correctOptionIndex: 0,
      explanation: 'Frekuensi alami fn = sqrt(k / m) / (2 pi).',
    ),
    QuestionItem(
      id: 'tm_070',
      questionText: 'Fenomena lonjakan amplitudo getaran ekstrem saat frekuensi gaya luar sama dengan frekuensi alami sistem dinamakan:',
      options: ['Resonansi', 'Flutter', 'Damping', 'Attenuation'],
      correctOptionIndex: 0,
      explanation: 'Resonansi memicu getaran amplitudo raksasa yang dapat merusak struktur.',
    ),
    QuestionItem(
      id: 'tm_071',
      questionText: 'Perangkat mekanis yang dirancang khusus untuk menyerap energi getaran dinamakan:',
      options: ['Peredam (Damper / Shock Absorber)', 'Pegas (Spring)', 'Massa', 'Bantalan'],
      correctOptionIndex: 0,
      explanation: 'Damper membuang energi getaran dalam bentuk kalor (viskos).',
    ),
    QuestionItem(
      id: 'tm_072',
      questionText: 'Rasio redaman (Damping Ratio / zeta) pada sistem beredam kritis bernilai:',
      options: ['zeta = 1', 'zeta < 1', 'zeta > 1', 'zeta = 0'],
      correctOptionIndex: 0,
      explanation: 'Critical damping terjadi saat zeta = 1 (kembali ke posisi diam tanpa osilasi).',
    ),
    QuestionItem(
      id: 'tm_073',
      questionText: 'Kondisi sistem getaran yang paling sering berosilasi sebelum diam (Underdamped) terjadi bila:',
      options: ['zeta < 1', 'zeta = 1', 'zeta > 1', 'zeta = 0'],
      correctOptionIndex: 0,
      explanation: 'Underdamped (zeta < 1) menghasilkan osilasi berulang yang meluruh.',
    ),
    QuestionItem(
      id: 'tm_074',
      questionText: 'Mekanisme transmisi daya fleksibel menggunakan puli dan pita sabuk dinamakan:',
      options: ['Transmisi Sabuk (Belt Drive)', 'Rantai', 'Roda Gigi', 'Pasak'],
      correctOptionIndex: 0,
      explanation: 'Belt drive menghubungkan dua puli jarak jauh.',
    ),
    QuestionItem(
      id: 'tm_075',
      questionText: 'Jenis sabuk berpenampang trapesium yang populer dipakai pada mesin otomotif dinamakan:',
      options: ['V-Belt (Sabuk V)', 'Flat Belt', 'Timing Belt', 'Round Belt'],
      correctOptionIndex: 0,
      explanation: 'V-Belt memberikan gaya jepit gesekan tinggi pada alur puli V.',
    ),
    QuestionItem(
      id: 'tm_076',
      questionText: 'Sabuk bergigi yang menjamin transmisi posisi sinkron tanpa slip dinamakan:',
      options: ['Timing Belt', 'V-Belt', 'Flat Belt', 'Ribbed Belt'],
      correctOptionIndex: 0,
      explanation: 'Timing belt menyinkronkan poros engkol dan poros nok (camshaft).',
    ),
    QuestionItem(
      id: 'tm_077',
      questionText: 'Transmisi daya fleksibel tanpa slip jarak menengah menggunakan sproket dinamakan:',
      options: ['Transmisi Rantai (Chain Drive)', 'Belt Drive', 'Gear Train', 'Kopling'],
      correctOptionIndex: 0,
      explanation: 'Chain drive mengikat dua sproket bergigi (seperti pada sepeda motor).',
    ),
    QuestionItem(
      id: 'tm_078',
      questionText: 'Tekanan fluida hidrolik dikirimkan merata ke segala arah sesuai dengan prinsip:',
      options: ['Hukum Pascal', 'Hukum Archimedes', 'Hukum Torricelli', 'Hukum Boyles'],
      correctOptionIndex: 0,
      explanation: 'Hukum Pascal menyatakan tekanan fluida dalam ruang tertutup diteruskan sama rata.',
    ),
    QuestionItem(
      id: 'tm_079',
      questionText: 'Sistem transmisi daya mengandalkan tekanan minyak pelumas cair dinamakan sistem:',
      options: ['Hidrolik', 'Pneumatik', 'Mekanis', 'Elektrik'],
      correctOptionIndex: 0,
      explanation: 'Sistem hidrolik mentransmisikan daya besar lewat oli bertekanan tinggi.',
    ),
    QuestionItem(
      id: 'tm_080',
      questionText: 'Sistem daya dan kontrol yang mengandalkan media udara bertekanan dinamakan sistem:',
      options: ['Pneumatik', 'Hidrolik', 'Termal', 'Elektrokimia'],
      correctOptionIndex: 0,
      explanation: 'Pneumatik menggunakan udara terkompresi.',
    ),
    QuestionItem(
      id: 'tm_081',
      questionText: 'Silinder penggerak pneumatik yang bergerak maju dan mundur menggunakan udara bertekanan dinamakan:',
      options: ['Double-Acting Cylinder (Silinder Kerja Ganda)', 'Single-Acting Cylinder', 'Rotary Actuator', 'Solenoid'],
      correctOptionIndex: 0,
      explanation: 'Double-acting cylinder membutuhkan masukan udara di kedua port untuk gerakan bolak-balik.',
    ),
    QuestionItem(
      id: 'tm_082',
      questionText: 'Katup kontrol arah (Directional Control Valve) yang mengendalikan aliran aliran fluida pneumatik dinamakan katup:',
      options: ['DCV (Directional Control Valve)', 'Flow Control', 'Pressure Relief', 'Check Valve'],
      correctOptionIndex: 0,
      explanation: 'DCV mengatur arah aliran fluida kerja aktuator.',
    ),
    QuestionItem(
      id: 'tm_083',
      questionText: 'Katup pengaman yang membuka otomatis membuang kelebihan tekanan cair/gas dinamakan:',
      options: ['Pressure Relief Valve (PRV)', 'Check Valve', 'Throttle Valve', 'Needle Valve'],
      correctOptionIndex: 0,
      explanation: 'PRV melindungi bejana tekan dari bahaya ledakan overpressure.',
    ),
    QuestionItem(
      id: 'tm_084',
      questionText: 'Katup satu arah yang membolehkan aliran fluida mengalir ke satu arah dan mencegah aliran balik dinamakan:',
      options: ['Check Valve (Katup Satu Aarah)', 'Gate Valve', 'Globe Valve', 'Ball Valve'],
      correctOptionIndex: 0,
      explanation: 'Check valve mencegah backflow aliran fluida.',
    ),
    QuestionItem(
      id: 'tm_085',
      questionText: 'Ilmu yang mempelajari gesekan (friction), pelumasan (lubrication), dan keausan (wear) kontak permukaan dinamakan:',
      options: ['Tribologi', 'Reologi', 'Metrologi', 'Kinematika'],
      correctOptionIndex: 0,
      explanation: 'Tribologi membahas fenomena gesekan dan keausan interaksi permukaan.',
    ),
    QuestionItem(
      id: 'tm_086',
      questionText: 'Jenis keausan akibat gesekan pengikisan partikel keras di antara dua permukaan dinamakan keausan:',
      options: ['Abrasif (Abrasive Wear)', 'Adhesif', 'Erosi', 'Kavitasi'],
      correctOptionIndex: 0,
      explanation: 'Keausan abrasif mengikis permukaan logam.',
    ),
    QuestionItem(
      id: 'tm_087',
      questionText: 'Pelumas gemuk kental yang dipakai pada bantalan beban berat kecepatan rendah dinamakan:',
      options: ['Grease (Gemuk Pelumas)', 'Oli Mineral', 'Oli Sintetis', 'Parafin'],
      correctOptionIndex: 0,
      explanation: 'Grease adalah campuran oli dan pengental (soap thickener).',
    ),
    QuestionItem(
      id: 'tm_088',
      questionText: 'Ukuran kekentalan atau ketahanan alir suatu cairan pelumas dinamakan:',
      options: ['Viskositas', 'Massa Jenis', 'Tegangan Permukaan', 'Kapilaritas'],
      correctOptionIndex: 0,
      explanation: 'Viskositas mengukur tingkat kekentalan fluida pelumas.',
    ),
    QuestionItem(
      id: 'tm_089',
      questionText: 'Indeks standar internasional untuk mengukur kelas kekentalan oli mesin dinamakan:',
      options: ['SAE (Society of Automotive Engineers)', 'API', 'ISO VG', 'NLGI'],
      correctOptionIndex: 0,
      explanation: 'SAE (seperti SAE 10W-40) mengklasifikasikan viskositas oli mesin.',
    ),
    QuestionItem(
      id: 'tm_090',
      questionText: 'Mesin pembakaran dalam (Internal Combustion Engine) 4-Langkah menyelesaikan 1 siklus kerja dalam:',
      options: ['4 Langkah Torak / 2 Putaran Poros Engkol (720 derajat)', '2 Langkah / 1 Putaran', '4 Putaran Poros', '1 Langkah'],
      correctOptionIndex: 0,
      explanation: 'Mesin 4-Tak membutuhkan 4 gerakan piston dan 2 putaran kruk as (720°).',
    ),
    QuestionItem(
      id: 'tm_091',
      questionText: 'Empat langkah urutan kerja mesin 4-Tak secara berurutan adalah:',
      options: ['Hisap, Kompresi, Usaha (Pembakaran), Buang', 'Kompresi, Hisap, Buang, Usaha', 'Hisap, Buang, Kompresi, Usaha', 'Usaha, Buang, Hisap, Kompresi'],
      correctOptionIndex: 0,
      explanation: 'Siklus 4-Tak: Intake -> Compression -> Power -> Exhaust.',
    ),
    QuestionItem(
      id: 'tm_092',
      questionText: 'Mesin pembakaran dalam 2-Langkah menyelesaikan 1 siklus kerja dalam:',
      options: ['2 Langkah Torak / 1 Putaran Poros Engkol (360 derajat)', '4 Langkah / 2 Putaran', '1 Langkah', '3 Putaran'],
      correctOptionIndex: 0,
      explanation: 'Mesin 2-Tak menyelesaikan siklus dalam 1 putaran engkol penuh (360°).',
    ),
    QuestionItem(
      id: 'tm_093',
      questionText: 'Komponen mesin yang menyalakan percikan bunga api listrik pada mesin bensin dinamakan:',
      options: ['Busi (Spark Plug)', 'Injektor', 'Nok (Camshaft)', 'Karburator'],
      correctOptionIndex: 0,
      explanation: 'Busi memercikkan bunga api membakar campuran udara-bensin.',
    ),
    QuestionItem(
      id: 'tm_094',
      questionText: 'Mesin Diesel tidak menggunakan busi penyearah api karena pembakaran terjadi akibat:',
      options: ['Self-Ignition (Suhu & Tekanan Kompresi Tinggi)', 'Bahan Bakar Khusus', 'Koil', 'Magneto'],
      correctOptionIndex: 0,
      explanation: 'Solar menyala sendiri akibat panas tinggi kompresi udara (rasio kompresi 16-22:1).',
    ),
    QuestionItem(
      id: 'tm_095',
      questionText: 'Perangkat pengisi udara tekan yang diputar oleh gas buang mesin dinamakan:',
      options: ['Turbocharger', 'Supercharger', 'Intercooler', 'Blow-off Valve'],
      correctOptionIndex: 0,
      explanation: 'Turbocharger memanfaatkan energi kinetik gas buang memutar turbin pemampat udara.',
    ),
    QuestionItem(
      id: 'tm_096',
      questionText: 'Perangkat pemampat udara tekan masukan yang diputar langsung oleh sabuk poros engkol dinamakan:',
      options: ['Supercharger', 'Turbocharger', 'Radiator', 'EGR'],
      correctOptionIndex: 0,
      explanation: 'Supercharger diputar secara mekanis oleh puli kruk as.',
    ),
    QuestionItem(
      id: 'tm_097',
      questionText: 'Penukar panas yang mendinginkan udara terkompresi dari turbocharger sebelum masuk silinder dinamakan:',
      options: ['Intercooler', 'Radiator', 'Kondensor', 'Evaporator'],
      correctOptionIndex: 0,
      explanation: 'Intercooler mendinginkan udara masukan agar kerapatan molekul O2 meningkat.',
    ),
    QuestionItem(
      id: 'tm_098',
      questionText: 'Sistem pengondisian udara (AC) mendinginkan ruangan mengandalkan siklus kompresi uap dengan zat pendingin:',
      options: ['Refrigeran (Freon / R134a / R32)', 'Air', 'Oli', 'Amonia padat'],
      correctOptionIndex: 0,
      explanation: 'Siklus refrigerasi kompresi uap mengandalkan fluida kerja refrigeran.',
    ),
    QuestionItem(
      id: 'tm_099',
      questionText: 'Komponen sistem AC yang menyerap panas dari ruangan dan menguapkan refrigeran dinamakan:',
      options: ['Evaporator', 'Kondensor', 'Kompresor', 'Katup Ekspansi'],
      correctOptionIndex: 0,
      explanation: 'Evaporator mendinginkan udara ruangan via penguapan refrigeran.',
    ),
    QuestionItem(
      id: 'tm_100',
      questionText: 'Komponen sistem AC yang melepas panas refrigeran ke udara luar dan mengembunkannya menjadi cair dinamakan:',
      options: ['Kondensor', 'Evaporator', 'Katup Ekspansi', 'Filter Drier'],
      correctOptionIndex: 0,
      explanation: 'Kondensor membuang kalor refrigeran bertekanan tinggi ke lingkungan luar.',
    ),
  ];
}
