import '../tes_seleksi_model.dart';

List<QuestionItem> getKedokteranQuestions() {
  return const [
    QuestionItem(
      id: 'med_001',
      questionText: 'Katup jantung yang memisahkan atrium kiri dan ventrikel kiri dinamakan:',
      options: ['Katup Trikuspid', 'Katup Bikuspid / Mitral', 'Katup Aorta', 'Katup Pulmonal'],
      correctOptionIndex: 1,
      explanation: 'Katup Bikuspid (Mitral) memisahkan atrium kiri dan ventrikel kiri.',
    ),
    QuestionItem(
      id: 'med_002',
      questionText: 'Bagian otak yang berfungsi sebagai pusat keseimbangan dan koordinasi motorik halus adalah:',
      options: ['Cerebrum', 'Cerebellum', 'Thalamus', 'Medulla Oblongata'],
      correctOptionIndex: 1,
      explanation: 'Cerebellum (otak kecil) mengontrol koordinasi keseimbangan.',
    ),
    QuestionItem(
      id: 'med_003',
      questionText: 'Hormon yang dihasilkan oleh sel beta pankreas untuk menurunkan kadar gula darah adalah:',
      options: ['Glukagon', 'Insulin', 'Adrenalin', 'Kortisol'],
      correctOptionIndex: 1,
      explanation: 'Sel beta pankreas mengsekresi hormon insulin.',
    ),
    QuestionItem(
      id: 'med_004',
      questionText: 'Unit fungsional terkecil ginjal yang bertugas menyaring darah adalah:',
      options: ['Nefron', 'Neuron', 'Alveolus', 'Vili'],
      correctOptionIndex: 0,
      explanation: 'Nefron adalah unit penyaring utama ginjal.',
    ),
    QuestionItem(
      id: 'med_005',
      questionText: 'Tulang terpanjang dan terkuat pada tubuh manusia adalah:',
      options: ['Tibia', 'Fibula', 'Femur', 'Humerus'],
      correctOptionIndex: 2,
      explanation: 'Femur (tulang paha) adalah tulang terbesar dan terkuat.',
    ),
    QuestionItem(
      id: 'med_006',
      questionText: 'Pertukaran gas oksigen dan karbon dioksida di paru-paru terjadi pada struktur:',
      options: ['Bronkus', 'Bronkiolus', 'Alveolus', 'Trakea'],
      correctOptionIndex: 2,
      explanation: 'Alveolus adalah kantung udara tempat pertukaran gas.',
    ),
    QuestionItem(
      id: 'med_007',
      questionText: 'Pembuluh darah yang membawa darah kaya oksigen dari paru-paru menuju atrium kiri jantung adalah:',
      options: ['Vena Pulmonalis', 'Arteri Pulmonalis', 'Vena Cava Superior', 'Aorta'],
      correctOptionIndex: 0,
      explanation: 'Vena pulmonalis membawa darah teroksigenasi dari paru ke jantung.',
    ),
    QuestionItem(
      id: 'med_008',
      questionText: 'Penyakit genetik akibat terganggunya proses pembekuan darah dinamakan:',
      options: ['Anemia', 'Leukemia', 'Hemofilia', 'Thalassemia'],
      correctOptionIndex: 2,
      explanation: 'Hemofilia adalah gangguan pembekuan darah bawaan.',
    ),
    QuestionItem(
      id: 'med_009',
      questionText: 'Pusat pengatur suhu tubuh (termoregulasi) berada di bagian otak:',
      options: ['Hipotalamus', 'Hipokampus', 'Amigdala', 'Korpus Kalosum'],
      correctOptionIndex: 0,
      explanation: 'Hipotalamus berfungsi mengatur suhu tubuh dan homeostasis.',
    ),
    QuestionItem(
      id: 'med_010',
      questionText: 'Sel darah yang tidak memiliki inti sel (nukleus) pada kondisi matang adalah:',
      options: ['Eritrosit', 'Leukosit', 'Limfosit', 'Monosit'],
      correctOptionIndex: 0,
      explanation: 'Eritrosit (sel darah merah) mamalia matang tidak berinti.',
    ),
    QuestionItem(
      id: 'med_011',
      questionText: 'Tekanan darah sistolik mengukur tekanan saat:',
      options: ['Jantung beristirahat', 'Ventrikel jantung berkontraksi', 'Atrium jantung mengembang', 'Katup mitral terbuka'],
      correctOptionIndex: 1,
      explanation: 'Sistolik adalah tekanan saat ventrikel berkontraksi memompa darah.',
    ),
    QuestionItem(
      id: 'med_012',
      questionText: 'Vitamin yang larut dalam lemak (fat-soluble) adalah:',
      options: ['Vitamin B & C', 'Vitamin A, D, E, K', 'Vitamin C & D', 'Vitamin B kompleks'],
      correctOptionIndex: 1,
      explanation: 'Vitamin A, D, E, K larut dalam lemak.',
    ),
    QuestionItem(
      id: 'med_013',
      questionText: 'Kelenjar endokrin terbesar di leher yang menghasilkan hormon pengatur metabolisme tubuh adalah:',
      options: ['Kelenjar Tiroid', 'Kelenjar Adrenal', 'Kelenjar Pituitari', 'Kelenjar Timus'],
      correctOptionIndex: 0,
      explanation: 'Kelenjar tiroid menghasilkan tiroksin untuk metabolisme.',
    ),
    QuestionItem(
      id: 'med_014',
      questionText: 'Kondisi penurunan sel darah merah atau hemoglobin di bawah batas normal disebut:',
      options: ['Hipertensi', 'Anemia', 'Polisitemia', 'Leukopenia'],
      correctOptionIndex: 1,
      explanation: 'Anemia adalah kekurangan Hb/eritrosit.',
    ),
    QuestionItem(
      id: 'med_015',
      questionText: 'Penutup kartilago yang mencegah makanan masuk ke saluran pernapasan saat menelan dinamakan:',
      options: ['Epiglotis', 'Laring', 'Faring', 'Pita Suara'],
      correctOptionIndex: 0,
      explanation: 'Epiglotis menutup laring saat menelan.',
    ),
    QuestionItem(
      id: 'med_016',
      questionText: 'Saraf kranial ke-X (Ke-10) yang menginervasi organ dada dan perut dinamakan saraf:',
      options: ['Nervus Vagus', 'Nervus Optikus', 'Nervus Olfaktorius', 'Nervus Trigeminus'],
      correctOptionIndex: 0,
      explanation: 'Nervus Vagus (CN X) mengontrol organ viseral.',
    ),
    QuestionItem(
      id: 'med_017',
      questionText: 'Enzim pencernaan dalam lambung yang memecah protein menjadi pepton adalah:',
      options: ['Amilase', 'Pepsin', 'Tripsin', 'Lipase'],
      correctOptionIndex: 1,
      explanation: 'Pepsin bekerja di lambung asam memecah protein.',
    ),
    QuestionItem(
      id: 'med_018',
      questionText: 'Organ tubuh yang menyimpan empedu hasil produksi hati dinamakan:',
      options: ['Pankreas', 'Kandung Empedu (Vesica Fellea)', 'Duodenum', 'Limpa'],
      correctOptionIndex: 1,
      explanation: 'Kandung empedu menyimpan cairan empedu dari hati.',
    ),
    QuestionItem(
      id: 'med_019',
      questionText: 'Infeksi bakteri Mycobacterium tuberculosis paling sering menyerang organ:',
      options: ['Ginjal', 'Hati', 'Paru-paru', 'Jantung'],
      correctOptionIndex: 2,
      explanation: 'TB paling umum menginfeksi paru-paru.',
    ),
    QuestionItem(
      id: 'med_020',
      questionText: 'Antibodi primer yang ditemukan dalam ASI (kolostrum) dan sekret mukosa adalah:',
      options: ['IgG', 'IgA', 'IgM', 'IgE'],
      correctOptionIndex: 1,
      explanation: 'IgA dominan pada cairan sekresi dan ASI.',
    ),
    QuestionItem(
      id: 'med_021',
      questionText: 'Penyebab utama penyakit malaria adalah parasit mikroba jenis:',
      options: ['Plasmodium', 'Salmonella', 'Entamoeba', 'Ascaris'],
      correctOptionIndex: 0,
      explanation: 'Malaria disebabkan parasit protozoa Plasmodium.',
    ),
    QuestionItem(
      id: 'med_022',
      questionText: 'Vektor penular demam berdarah dengue (DBD) pada manusia adalah nyamuk:',
      options: ['Anopheles', 'Aedes aegypti', 'Culex', 'Mansonia'],
      correctOptionIndex: 1,
      explanation: 'Aedes aegypti membawa virus Dengue.',
    ),
    QuestionItem(
      id: 'med_023',
      questionText: 'Refleks patela (lutut) diuji untuk mengevaluasi integritas segmen saraf tulang belakang:',
      options: ['Servikal', 'Torakal', 'Lumbal (L2-L4)', 'Sakral'],
      correctOptionIndex: 2,
      explanation: 'Refleks patela menguji segmen lumbal L2-L4.',
    ),
    QuestionItem(
      id: 'med_024',
      questionText: 'Gas yang terikat sangat kuat pada hemoglobin dibanding oksigen sehingga memicu keracunan asap adalah:',
      options: ['Karbon Monoksida (CO)', 'Karbon Dioksida (CO2)', 'Nitrogen (N2)', 'Metana (CH4)'],
      correctOptionIndex: 0,
      explanation: 'CO memiliki afinitas terikat Hb jauh lebih tinggi dari O2.',
    ),
    QuestionItem(
      id: 'med_025',
      questionText: 'Ruang jantung yang memiliki dinding otot paling tebal untuk memompa darah ke seluruh tubuh adalah:',
      options: ['Atrium Kanan', 'Atrium Kiri', 'Ventrikel Kanan', 'Ventrikel Kiri'],
      correctOptionIndex: 3,
      explanation: 'Ventrikel kiri menebal karena memompa darah sistemik seluruh tubuh.',
    ),
    QuestionItem(
      id: 'med_026',
      questionText: 'Organ imunologi yang berfungsi menghancurkan eritrosit tua dan menyimpan cadangan darah adalah:',
      options: ['Limpa (Spleen)', 'Hati', 'Timus', 'Kelenjar Getah Bening'],
      correctOptionIndex: 0,
      explanation: 'Limpa menyaring eritrosit tua.',
    ),
    QuestionItem(
      id: 'med_027',
      questionText: 'Hormon pemicu kontraksi rahim saat persalinan dan stimulasi produksi ASI dinamakan:',
      options: ['Progesteron', 'Oksitosin', 'Estrogen', 'Prolaktin'],
      correctOptionIndex: 1,
      explanation: 'Oksitosin menstimulasi kontraksi uterus dan milk ejection.',
    ),
    QuestionItem(
      id: 'med_028',
      questionText: 'Bagian retina mata yang kaya akan sel kerucut (cone cell) untuk penglihatan tajam dan warna dinamakan:',
      options: ['Fovea Centralis / Macula', 'Bintik Buta', 'Kornea', 'Lensa'],
      correctOptionIndex: 0,
      explanation: 'Fovea centralis adalah pusat resolusi dan warna mata.',
    ),
    QuestionItem(
      id: 'med_029',
      questionText: 'Kekurangan vitamin C kronis dapat mengakibatkan penyakit yang ditandai gusi berdarah yaitu:',
      options: ['Rakitis', 'Skorbut (Scurvy)', 'Beri-beri', 'Pellagra'],
      correctOptionIndex: 1,
      explanation: 'Skorbut terjadi akibat defisiensi vitamin C.',
    ),
    QuestionItem(
      id: 'med_030',
      questionText: 'Kekurangan vitamin D pada anak-anak dapat menyebabkan kelainan tulang berkembang yaitu:',
      options: ['Osteoporosis', 'Rakitis', 'Skoliosis', 'Osteoartritis'],
      correctOptionIndex: 1,
      explanation: 'Rakitis melunakkan tulang anak akibat kurang vit D/kalsium.',
    ),
    QuestionItem(
      id: 'med_031',
      questionText: 'Peradangan pada lapisan usus buntu dinamakan:',
      options: ['Gastritis', 'Apendisitis', 'Hepatitis', 'Kolesistitis'],
      correctOptionIndex: 1,
      explanation: 'Apendisitis adalah inflamasi appendix.',
    ),
    QuestionItem(
      id: 'med_032',
      questionText: 'Alat medis yang digunakan untuk mendengarkan suara internal tubuh seperti detak jantung adalah:',
      options: ['Tensimeter', 'Stetoskop', 'Termometer', 'Otoskop'],
      correctOptionIndex: 1,
      explanation: 'Stetoskop auskultasi suara organ dalam.',
    ),
    QuestionItem(
      id: 'med_033',
      questionText: 'Pemeriksaan rekam aktivitas listrik jantung dinamakan:',
      options: ['Electroencephalogram (EEG)', 'Electrocardiogram (ECG/EKG)', 'Electromyogram (EMG)', 'USG'],
      correctOptionIndex: 1,
      explanation: 'EKG mencatat gelombang kelistrikan jantung.',
    ),
    QuestionItem(
      id: 'med_034',
      questionText: 'Sel imun leukosit yang memproduksi antibodi spesifik adalah:',
      options: ['Limfosit B', 'Limfosit T', 'Neutrofil', 'Eosinofil'],
      correctOptionIndex: 0,
      explanation: 'Sel B terdeferensiasi jadi sel plasma penghasil antibodi.',
    ),
    QuestionItem(
      id: 'med_035',
      questionText: 'Persendian yang memungkinkan pergerakan ke segala arah dinamakan sendi:',
      options: ['Sendi Engsel', 'Sendi Peluru (Ball and Socket)', 'Sendi Putar', 'Sendi Geser'],
      correctOptionIndex: 1,
      explanation: 'Sendi peluru (misal bahu & paha) membolehkan rotasi multidirectional.',
    ),
    QuestionItem(
      id: 'med_036',
      questionText: 'Bagian darah transparan kekuningan tanpa sel darah yang mengandung faktor pembekuan dinamakan:',
      options: ['Serum', 'Plasma Darah', 'Trombosit', 'Hemolimfa'],
      correctOptionIndex: 1,
      explanation: 'Plasma mengandung fibrinogen & clotting factor.',
    ),
    QuestionItem(
      id: 'med_037',
      questionText: 'Penyebab hipertensi primer paling sering bersifat:',
      options: ['Idiopatik / Multifaktorial', 'Gagal Ginjal', 'Tumor Adrenal', 'Obat-obatan'],
      correctOptionIndex: 0,
      explanation: 'Hipertensi esensial/primer tidak memiliki penyebab tunggal spesifik (idiopatik).',
    ),
    QuestionItem(
      id: 'med_038',
      questionText: 'Kondisi penumpukan plak kolesterol pada dinding arteri dinamakan:',
      options: ['Aterosklerosis', 'Arteritis', 'Aneurisma', 'Varises'],
      correctOptionIndex: 0,
      explanation: 'Aterosklerosis menyempitkan lumen pembuluh darah.',
    ),
    QuestionItem(
      id: 'med_039',
      questionText: 'Cairan tubuh yang melumasi persendian dinamakan:',
      options: ['Cairan Serebrospinal', 'Cairan Sinovial', 'Cairan Pleura', 'Limfa'],
      correctOptionIndex: 1,
      explanation: 'Cairan sinovial berada di rongga sendi.',
    ),
    QuestionItem(
      id: 'med_040',
      questionText: 'Bagian saraf mata yang menghantarkan impuls penglihatan ke otak dinamakan:',
      options: ['Nervus Optikus (CN II)', 'Nervus Oculomotorius', 'Nervus Trochlearis', 'Nervus Abducens'],
      correctOptionIndex: 0,
      explanation: 'Nervus Optikus membawa sinyal visual dari retina ke korteks visual.',
    ),
    QuestionItem(
      id: 'med_041',
      questionText: 'Tipe pembelahan sel yang menghasilkan sel anakan haploid (n) untuk sel gamet adalah:',
      options: ['Mitosis', 'Meiosis', 'Amitosis', 'Binary Fission'],
      correctOptionIndex: 1,
      explanation: 'Meiosis mereduksi kromosom sel gamet.',
    ),
    QuestionItem(
      id: 'med_042',
      questionText: 'Bagian telinga luar yang menangkap gelombang suara dinamakan:',
      options: ['Kanal Auditori', 'Pinna / Daun Telinga', 'Membran Timpani', 'Koklea'],
      correctOptionIndex: 1,
      explanation: 'Daun telinga memfokuskan gelombang akustik.',
    ),
    QuestionItem(
      id: 'med_043',
      questionText: 'Organ pendengaran bagian dalam berbentuk rumah siput dinamakan:',
      options: ['Koklea', 'Vestibulum', 'Kanal Semisirkularis', 'Martil'],
      correctOptionIndex: 0,
      explanation: 'Koklea mengubah getaran mekanik jadi sinyal saraf pendengaran.',
    ),
    QuestionItem(
      id: 'med_044',
      questionText: 'Hormon yang memicu pelepasan sel telur (ovulasi) pada wanita adalah:',
      options: ['FSH', 'LH (Luteinizing Hormone)', 'Estrogen', 'Progesteron'],
      correctOptionIndex: 1,
      explanation: 'LH surge merangsang terjadinya ovulasi.',
    ),
    QuestionItem(
      id: 'med_045',
      questionText: 'Kondisi penyumbatan mendadak arteri pulmonalis oleh pembekuan darah dinamakan:',
      options: ['Emboli Paru', 'Infark Miokard', 'Stroke Iskemik', 'Pneumotoraks'],
      correctOptionIndex: 0,
      explanation: 'Emboli paru terjadi akibat trombus menyumbat arteri pulmonalis.',
    ),
    QuestionItem(
      id: 'med_046',
      questionText: 'Jumlah pasang rusuk melayang (floating ribs) pada manusia adalah:',
      options: ['7 Pasang', '3 Pasang', '2 Pasang', '1 Pasang'],
      correctOptionIndex: 2,
      explanation: 'Manusia memiliki 2 pasang rusuk melayang (iga ke-11 & 12).',
    ),
    QuestionItem(
      id: 'med_047',
      questionText: 'Otot yang bekerja secara tak sadar (involunter) dan terdapat pada dinding organ dalam adalah:',
      options: ['Otot Lurik', 'Otot Polos', 'Otot Rangka', 'Otot Tendon'],
      correctOptionIndex: 1,
      explanation: 'Otot polos bergerak involunter pada viseral.',
    ),
    QuestionItem(
      id: 'med_048',
      questionText: 'Hormon pertumbuhan (Growth Hormone) disekresi oleh kelenjar:',
      options: ['Pituitari Anterior', 'Kelenjar Tiroid', 'Pankreas', 'Kelenjar Adrenal'],
      correctOptionIndex: 0,
      explanation: 'Hipofisis/Pituitari anterior memproduksi GH.',
    ),
    QuestionItem(
      id: 'med_049',
      questionText: 'Zat pembawa pesan kimiawi antar neuron pada celah sinaps dinamakan:',
      options: ['Hormon', 'Neurotransmiter', 'Enzim', 'Antibodi'],
      correctOptionIndex: 1,
      explanation: 'Neurotransmiter mendistribusikan sinyal antar sel saraf.',
    ),
    QuestionItem(
      id: 'med_050',
      questionText: 'Neurotransmiter utama yang terlibat dalam motivasi, reward, dan gerakan adalah:',
      options: ['Dopamin', 'Asetilkolin', 'GABA', 'Serotonin'],
      correctOptionIndex: 0,
      explanation: 'Dopamin mengontrol sistem reward dan fungsi motorik.',
    ),
    QuestionItem(
      id: 'med_051',
      questionText: 'Bagian lambung yang berbatasan langsung dengan esofagus dinamakan:',
      options: ['Kardia', 'Fundus', 'Korpus', 'Pilorus'],
      correctOptionIndex: 0,
      explanation: 'Kardia adalah pintu masuk lambung dari esophagus.',
    ),
    QuestionItem(
      id: 'med_052',
      questionText: 'Penyakit kerusakan sel hati akibat konsumsi alkohol kronis atau infeksi hepatitis dinamakan:',
      options: ['Sirosis Hati', 'Kolesistitis', 'Pankreatitis', 'Gastritis'],
      correctOptionIndex: 0,
      explanation: 'Sirosis adalah pembentukan jaringan parut fibrotik pada hati.',
    ),
    QuestionItem(
      id: 'med_053',
      questionText: 'Tes diagnostik penapisan kanker serviks menggunakan apus sel serviks dinamakan:',
      options: ['Pap Smear', 'Biopsi', 'Mammografi', 'Endoskopi'],
      correctOptionIndex: 0,
      explanation: 'Pap smear menyaring sel serviks abnormal.',
    ),
    QuestionItem(
      id: 'med_054',
      questionText: 'Pemeriksaan pemindaian payudara dengan sinar-X untuk deteksi dini kanker dinamakan:',
      options: ['Mammografi', 'USG Abdomen', 'CT Scan', 'MRI'],
      correctOptionIndex: 0,
      explanation: 'Mammografi memindai jaringan payudara.',
    ),
    QuestionItem(
      id: 'med_055',
      questionText: 'Imunitas yang diperoleh janin dari ibunya melalui plasenta dinamakan imunitas:',
      options: ['Pasif Alami', 'Aktif Alami', 'Pasif Buatan', 'Aktif Buatan'],
      correctOptionIndex: 0,
      explanation: 'Transfer IgG lewat plasenta adalah kekebalan pasif alami.',
    ),
    QuestionItem(
      id: 'med_056',
      questionText: 'Vaksinasi atau imunisasi memberikan kekebalan imun tipe:',
      options: ['Aktif Buatan', 'Pasif Buatan', 'Aktif Alami', 'Pasif Alami'],
      correctOptionIndex: 0,
      explanation: 'Vaksin merangsang pembentukan memori imun secara aktif buatan.',
    ),
    QuestionItem(
      id: 'med_057',
      questionText: 'Metode pertolongan pertama penanganan henti jantung dinamakan:',
      options: ['RJP / CPR', 'Heimlich Maneuver', 'Tourniquet', 'GCS'],
      correctOptionIndex: 0,
      explanation: 'CPR (Resusitasi Jantung Paru) menjaga sirkulasi saat henti jantung.',
    ),
    QuestionItem(
      id: 'med_058',
      questionText: 'Tindakan membebaskan sumbatan jalan napas akibat tersedak dilakukan dengan teknik:',
      options: ['Heimlich Maneuver', 'RJP', 'Defibrilasi', 'Trakeostomi'],
      correctOptionIndex: 0,
      explanation: 'Heimlich maneuver menekan diafragma mengeluarkan sumbatan.',
    ),
    QuestionItem(
      id: 'med_059',
      questionText: 'Alat medis kejutan listrik untuk mengembalikan irama jantung fibrilasi dinamakan:',
      options: ['Defibrilator / AED', 'Pacemaker', 'Ventilator', 'EKG'],
      correctOptionIndex: 0,
      explanation: 'Defibrilator memberikan de-polarisasi serentak kelistrikan jantung.',
    ),
    QuestionItem(
      id: 'med_060',
      questionText: 'Kondisi penurunan tekanan darah mendadak yang mengancam nyawa dinamakan:',
      options: ['Syok', 'Stupor', 'Syncope', 'Koma'],
      correctOptionIndex: 0,
      explanation: 'Syok ditandai kegagalan perfusi jaringan tubuh.',
    ),
    QuestionItem(
      id: 'med_061',
      questionText: 'Penyebab syok anafilaktik paling umum adalah:',
      options: ['Reaksi Alergi Berat', 'Pendarahan Hebat', 'Infeksi Bakteri', 'Gagal Jantung'],
      correctOptionIndex: 0,
      explanation: 'Syok anafilaktik dipicu hipersensitivitas alergi berat.',
    ),
    QuestionItem(
      id: 'med_062',
      questionText: 'Derajat luka bakar yang mengenai seluruh lapisan epidermis dan dermis dengan kerusakan saraf dinamakan:',
      options: ['Luka Bakar Derajat III', 'Luka Bakar Derajat I', 'Luka Bakar Derajat II', 'Luka Bakar Superficial'],
      correctOptionIndex: 0,
      explanation: 'Derajat III merusak full-thickness jaringan kulit hingga saraf.',
    ),
    QuestionItem(
      id: 'med_063',
      questionText: 'Tulang penyusun tengkorak kepala bagian belakang dinamakan tulang:',
      options: ['Oksipital', 'Frontal', 'Parietal', 'Temporal'],
      correctOptionIndex: 0,
      explanation: 'Os Occipitale terletak di posterior tengkorak.',
    ),
    QuestionItem(
      id: 'med_064',
      questionText: 'Pemberian nutrisi langsung melalui pembuluh darah vena tanpa melalui usus dinamakan nutrisi:',
      options: ['Parenteral', 'Enteral', 'Oral', 'Subkutan'],
      correctOptionIndex: 0,
      explanation: 'Nutrisi parenteral langsung dimasukkan ke sirkulasi vena.',
    ),
    QuestionItem(
      id: 'med_065',
      questionText: 'Cairan serebrospinal (CSF) diproduksi di dalam otak oleh struktur:',
      options: ['Pleksus Koroideus', 'Meninges', 'Araknoid', 'Subaraknoid'],
      correctOptionIndex: 0,
      explanation: 'Pleksus koroideus memproduksi CSF di ventrikel otak.',
    ),
    QuestionItem(
      id: 'med_066',
      questionText: 'Lapisan terluar pelindung otak dan medulla spinalis adalah:',
      options: ['Dura Mater', 'Pia Mater', 'Araknoid Mater', 'Epidural'],
      correctOptionIndex: 0,
      explanation: 'Dura mater adalah meninges terluar yang tebal.',
    ),
    QuestionItem(
      id: 'med_067',
      questionText: 'Teknik pemeriksaan radiologi yang memanfaatkan medan magnet kuat tanpa radiasi Sinar-X dinamakan:',
      options: ['Magnetic Resonance Imaging (MRI)', 'CT Scan', 'Rontgen', 'Fluoroskopi'],
      correctOptionIndex: 0,
      explanation: 'MRI memancarkan gelombang radio dan magnetik.',
    ),
    QuestionItem(
      id: 'med_068',
      questionText: 'Skala klinis yang digunakan untuk mengukur tingkat kesadaran pasien dinamakan:',
      options: ['Glasgow Coma Scale (GCS)', 'APGAR Score', 'BMI Index', 'Visual Analog Scale'],
      correctOptionIndex: 0,
      explanation: 'GCS mengukur respon mata, verbal, dan motorik.',
    ),
    QuestionItem(
      id: 'med_069',
      questionText: 'Skala evaluasi kondisi kesehatan bayi yang baru lahir 1 menit pertama adalah:',
      options: ['APGAR Score', 'GCS', 'Bratton Score', 'TNM System'],
      correctOptionIndex: 0,
      explanation: 'APGAR menilai warna kulit, denyut, refleks, tonus, napas bayi.',
    ),
    QuestionItem(
      id: 'med_070',
      questionText: 'Organ manusia yang mampu melakukan regenerasi jaringan alami paling pesat adalah:',
      options: ['Hati (Hepar)', 'Jantung', 'Otak', 'Ginjal'],
      correctOptionIndex: 0,
      explanation: 'Hati memiliki daya kompensasi regenerasi jaringan tinggi.',
    ),
    QuestionItem(
      id: 'med_071',
      questionText: 'Bakteri berbentuk batang atau silinder dinamakan kelompok:',
      options: ['Basil', 'Kokus', 'Spirillum', 'Vibrio'],
      correctOptionIndex: 0,
      explanation: 'Bacillus berbentuk batang.',
    ),
    QuestionItem(
      id: 'med_072',
      questionText: 'Bakteri Gram-Positif ditandai dengan warna pewarnaan Gram berwarna:',
      options: ['Ungu / Biru', 'Merah / Merah Muda', 'Kuning', 'Hijau'],
      correctOptionIndex: 0,
      explanation: 'Gram-positif mengikat kristal violet jadi berwarna ungu.',
    ),
    QuestionItem(
      id: 'med_073',
      questionText: 'Zat warna pencuci/pembanding utama pada pewarnaan Gram adalah:',
      options: ['Kristal Violet & Safranin', 'Metilen Biru', 'Eosin', 'Iodium'],
      correctOptionIndex: 0,
      explanation: 'Gram menggunakan Kristal Violet dan pembawa Safranin.',
    ),
    QuestionItem(
      id: 'med_074',
      questionText: 'Kondisi infeksi sistemik meluas di dalam sirkulasi darah dinamakan:',
      options: ['Sepsis', 'Bakteremia', 'Toksemia', 'Iskemia'],
      correctOptionIndex: 0,
      explanation: 'Sepsis adalah respon inflamasi sistemik terhadap infeksi.',
    ),
    QuestionItem(
      id: 'med_075',
      questionText: 'Obat pemicu pelebaran pembuluh darah bronchi pada penderita asma dinamakan:',
      options: ['Bronkodilator (misal Salbutamol)', 'Antihistamin', 'Kortikosteroid', 'Analgesik'],
      correctOptionIndex: 0,
      explanation: 'Bronkodilator merelaksasi otot polos saluran napas.',
    ),
    QuestionItem(
      id: 'med_076',
      questionText: 'Penyebab utama penyakit maag kronis atau ulkus peptikum yang diinduksi bakteri adalah:',
      options: ['Helicobacter pylori', 'Escherichia coli', 'Staphylococcus aureus', 'Salmonella typhi'],
      correctOptionIndex: 0,
      explanation: 'H. pylori merusak mukosa pelindung lambung.',
    ),
    QuestionItem(
      id: 'med_077',
      questionText: 'Kelumpuhan salah satu sisi tubuh akibat stroke dinamakan:',
      options: ['Hemiplegia', 'Paraplegia', 'Tetraplegia', 'Monoplegia'],
      correctOptionIndex: 0,
      explanation: 'Hemiplegia melumpuhkan separuh tubuh lateral.',
    ),
    QuestionItem(
      id: 'med_078',
      questionText: 'Bagian ginjal tempat terjadinya pengumpulan urin sebelum dialirkan ke ureter dinamakan:',
      options: ['Pelvis Renalis', 'Korteks', 'Medula', 'Glomerulus'],
      correctOptionIndex: 0,
      explanation: 'Pelvis renalis mengumpulkan urin akhir dari kaliks ginjal.',
    ),
    QuestionItem(
      id: 'med_079',
      questionText: 'Hormon pemicu pembentukan sel darah merah di sumsum tulang yang diproduksi ginjal adalah:',
      options: ['Eritropoietin (EPO)', 'Renin', 'Angiotensin', 'Aldosteron'],
      correctOptionIndex: 0,
      explanation: 'EPO merangsang eritropoiesis di sumsum tulang.',
    ),
    QuestionItem(
      id: 'med_080',
      questionText: 'Gula darah jenis utama yang digunakan sel sebagai sumber energi ATP adalah:',
      options: ['Glukosa', 'Fruktosa', 'Galaktosa', 'Maltosa'],
      correctOptionIndex: 0,
      explanation: 'Glukosa adalah substrate metabolik sel utama.',
    ),
    QuestionItem(
      id: 'med_081',
      questionText: 'Gangguan penglihatan di mana mata kesulitan melihat benda jarak jauh dinamakan:',
      options: ['Miopi (Rabun Jauh)', 'Hipermetropi', 'Presbiopi', 'Astigmatisme'],
      correctOptionIndex: 0,
      explanation: 'Miopi dibantu dengan lensa cekung (negatif).',
    ),
    QuestionItem(
      id: 'med_082',
      questionText: 'Lensa mata yang memburam keruh akibat penuaan dinamakan penyakit:',
      options: ['Katarak', 'Glaukoma', 'Trakoma', 'Pterigium'],
      correctOptionIndex: 0,
      explanation: 'Katarak ditandai kekeruhan pada lensa kristalina.',
    ),
    QuestionItem(
      id: 'med_083',
      questionText: 'Peningkatan tekanan intraokular mata yang dapat merusak saraf optik dinamakan:',
      options: ['Glaukoma', 'Katarak', 'Retinopati', 'Uveitis'],
      correctOptionIndex: 0,
      explanation: 'Glaukoma dipicu tingginya tekanan cairan bola mata.',
    ),
    QuestionItem(
      id: 'med_084',
      questionText: 'Struktur berbentuk pita jaringan ikat yang menghubungkan tulang dengan tulang dinamakan:',
      options: ['Ligamen', 'Tendon', 'Kartilago', 'Fascia'],
      correctOptionIndex: 0,
      explanation: 'Ligamen menyambungkan tulang ke tulang pada sendi.',
    ),
    QuestionItem(
      id: 'med_085',
      questionText: 'Struktur pita jaringan ikat yang menghubungkan otot ke tulang dinamakan:',
      options: ['Tendon', 'Ligamen', 'Kartilago', 'Bursa'],
      correctOptionIndex: 0,
      explanation: 'Tendon menyambung otot ke tulang.',
    ),
    QuestionItem(
      id: 'med_086',
      questionText: 'Penyebab tersering timbulnya penyakit rabies pada manusia adalah gigitan hewan terinfeksi virus:',
      options: ['Lyssavirus', 'Rhabdovirus / Lyssavirus', 'Retrovirus', 'Arbovirus'],
      correctOptionIndex: 1,
      explanation: 'Lyssavirus (keluarga Rhabdoviridae) menyebabkan rabies.',
    ),
    QuestionItem(
      id: 'med_087',
      questionText: 'Teknik pembedahan melahirkan bayi dengan insisi dinding perut dan rahim dinamakan:',
      options: ['Seksio Sesarea (C-Section)', 'Episiotomi', 'Kuretase', 'Laparoskopi'],
      correctOptionIndex: 0,
      explanation: 'Seksio Sesarea melahirkan janin via pembedahan abdomen.',
    ),
    QuestionItem(
      id: 'med_088',
      questionText: 'Kekurangan hormon tiroid sejak lahir yang memicu gangguan fisik dan mental dinamakan:',
      options: ['Kretinisme', 'Gigantisme', 'Akromegali', 'Cushing Syndrome'],
      correctOptionIndex: 0,
      explanation: 'Kretinisme terjadi akibat hipotiroidisme kongenital.',
    ),
    QuestionItem(
      id: 'med_089',
      questionText: 'Pertumbuhan berlebih pada tulang wajah dan ekstremitas dewasa akibat kelebihan GH dinamakan:',
      options: ['Akromegali', 'Gigantisme', 'Kretinisme', 'Dwarfisme'],
      correctOptionIndex: 0,
      explanation: 'Akromegali terjadi jika kelebihan GH muncul pasca penutupan lempeng epifisis.',
    ),
    QuestionItem(
      id: 'med_090',
      questionText: 'Pengujian reaksi refleks pupil terhadap cahaya terang mengevaluasi saraf kranial:',
      options: ['Nervus Optikus (II) & Oculomotorius (III)', 'Nervus Olfaktorius (I)', 'Nervus Vagus (X)', 'Nervus Trigeminus (V)'],
      correctOptionIndex: 0,
      explanation: 'Sensori dibawa CN II dan konstriksi pupil dieksekusi CN III.',
    ),
    QuestionItem(
      id: 'med_091',
      questionText: 'Zat pewarna alami darah hemoglobin mengikat atom logam:',
      options: ['Besi (Fe)', 'Tembaga (Cu)', 'Seng (Zn)', 'Magnesium (Mg)'],
      correctOptionIndex: 0,
      explanation: 'Gugus Heme mengandung atom besi Fe2+.',
    ),
    QuestionItem(
      id: 'med_092',
      questionText: 'Penyakit autoimun yang merusak lapisan mielin pelindung sel saraf otak dan medulla dinamakan:',
      options: ['Multiple Sclerosis', 'Myasthenia Gravis', 'Lupus (SLE)', 'Rheumatoid Arthritis'],
      correctOptionIndex: 0,
      explanation: 'Multiple sclerosis menyerang selubung mielin SSO.',
    ),
    QuestionItem(
      id: 'med_093',
      questionText: 'Penyakit gangguan neuromuskular autoimun yang menyebabkan kelemahan otot lurik dinamakan:',
      options: ['Myasthenia Gravis', 'Parkinson', 'ALS', 'Alzheimer'],
      correctOptionIndex: 0,
      explanation: 'Myasthenia Gravis merusak reseptor asetilkolin di junction neuromuscular.',
    ),
    QuestionItem(
      id: 'med_094',
      questionText: 'Penyakit degeneratif otak yang ditandai hilangnya neuron dopaminergik di substantia nigra dinamakan:',
      options: ['Parkinson', 'Alzheimer', 'Huntington', 'Stroke'],
      correctOptionIndex: 0,
      explanation: 'Parkinson ditandai tremor dan hilangnya neurotransmiter dopamin.',
    ),
    QuestionItem(
      id: 'med_095',
      questionText: 'Penyakit pikun degeneratif tersering yang ditandai plak amyloid di otak dinamakan:',
      options: ['Alzheimer', 'Parkinson', 'Epilepsi', 'Ensefalitis'],
      correctOptionIndex: 0,
      explanation: 'Alzheimer merusak memori dan kognitif akibat akumulasi amyloid-beta.',
    ),
    QuestionItem(
      id: 'med_096',
      questionText: 'Serangan kejang berulang akibat aktivitas listrik abnormal pada otak dinamakan:',
      options: ['Epilepsi', 'Syncope', 'Meningitis', 'Vertigo'],
      correctOptionIndex: 0,
      explanation: 'Epilepsi ditandai cetusan impuls listrik abnormal berulang.',
    ),
    QuestionItem(
      id: 'med_097',
      questionText: 'Infeksi pada selaput pembungkus otak dan sumsum tulang belakang dinamakan:',
      options: ['Meningitis', 'Ensefalitis', 'Neuritis', 'Myelitis'],
      correctOptionIndex: 0,
      explanation: 'Meningitis adalah inflamasi pada meninges.',
    ),
    QuestionItem(
      id: 'med_098',
      questionText: 'Kondisi penumpukan cairan serebrospinal abnormal di ventrikel otak dinamakan:',
      options: ['Hidrosefalus', 'Microcephalus', 'Anencephaly', 'Edema Otak'],
      correctOptionIndex: 0,
      explanation: 'Hidrosefalus memperbesar ukuran ventrikel dan kepala.',
    ),
    QuestionItem(
      id: 'med_099',
      questionText: 'Tindakan cuci darah buatan luar tubuh untuk pengganti ginjal rusaks dinamakan:',
      options: ['Hemodialisis', 'Peritoneal Dialisis', 'Transplantasi', 'Kateterisasi'],
      correctOptionIndex: 0,
      explanation: 'Hemodialisis menyaring produk sisa metabolisme via mesin dialiser.',
    ),
    QuestionItem(
      id: 'med_100',
      questionText: 'Ketiadaan produksi hormon insulin akibat autoimun pembunuh sel beta dinamakan diabetes tipe:',
      options: ['Diabetes Melitus Tipe 1', 'Diabetes Melitus Tipe 2', 'Diabetes Gestasional', 'Diabetes Insipidus'],
      correctOptionIndex: 0,
      explanation: 'DM Tipe 1 merupakan kerusakan sel beta pankreas yang bergantung insulin.',
    ),
  ];
}
