// lib/game/widgets/assets_menu/aset_premium/garasi_mobil/database_mobil.dart

final List<Map<String, dynamic>> mobilTersediaList = [
  // =============================================
  // TIER 1 - KOTA & BEBEK (0.8M - 1.8M)
  // =============================================
  {
    'id': '1',
    'nama': 'Suzuki Carry',
    'merek': 'Suzuki',
    'tahun': 2022,
    'harga': 1000000, // 1 Juta
    'tipe': 'Pickup',
    'kondisi': 'Bekas',
    'hp': 60,
    'topSpeed': 120,
  },
  {
    'id': '2',
    'nama': 'Daihatsu Ayla',
    'merek': 'Daihatsu',
    'tahun': 2023,
    'harga': 1200000,
    'tipe': 'City Car',
    'kondisi': 'Baru',
    'hp': 70,
    'topSpeed': 140,
  },
  {
    'id': '3',
    'nama': 'Toyota Agya',
    'merek': 'Toyota',
    'tahun': 2023,
    'harga': 1300000,
    'tipe': 'City Car',
    'kondisi': 'Baru',
    'hp': 72,
    'topSpeed': 145,
  },
  {
    'id': '4',
    'nama': 'Honda Brio',
    'merek': 'Honda',
    'tahun': 2023,
    'harga': 1500000,
    'tipe': 'City Car',
    'kondisi': 'Baru',
    'hp': 90,
    'topSpeed': 155,
  },
  {
    'id': '5',
    'nama': 'Daihatsu Sigra',
    'merek': 'Daihatsu',
    'tahun': 2022,
    'harga': 1600000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 75,
    'topSpeed': 135,
  },
  {
    'id': '6',
    'nama': 'Toyota Calya',
    'merek': 'Toyota',
    'tahun': 2022,
    'harga': 1800000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 78,
    'topSpeed': 138,
  },

  // =============================================
  // TIER 2 - MPV KELUARGA (2.0M - 3.5M)
  // =============================================
  {
    'id': '7',
    'nama': 'Daihatsu Xenia',
    'merek': 'Daihatsu',
    'tahun': 2023,
    'harga': 2200000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 88,
    'topSpeed': 150,
  },
  {
    'id': '8',
    'nama': 'Suzuki Ertiga',
    'merek': 'Suzuki',
    'tahun': 2023,
    'harga': 2500000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 95,
    'topSpeed': 160,
  },
  {
    'id': '9',
    'nama': 'Honda Mobilio',
    'merek': 'Honda',
    'tahun': 2021,
    'harga': 3000000,
    'tipe': 'MPV',
    'kondisi': 'Bekas',
    'hp': 120,
    'topSpeed': 170,
  },
  {
    'id': '10',
    'nama': 'Mitsubishi Xpander',
    'merek': 'Mitsubishi',
    'tahun': 2023,
    'harga': 3500000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 105,
    'topSpeed': 165,
  },

  // =============================================
  // TIER 3 - SEDAN & SUV ENTRY (4.0M - 6.0M)
  // =============================================
  {
    'id': '11',
    'nama': 'Toyota Vios',
    'merek': 'Toyota',
    'tahun': 2023,
    'harga': 4200000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 110,
    'topSpeed': 185,
  },
  {
    'id': '12',
    'nama': 'Toyota Avanza',
    'merek': 'Toyota',
    'tahun': 2022,
    'harga': 4500000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 120,
    'topSpeed': 180,
  },
  {
    'id': '13',
    'nama': 'Honda City',
    'merek': 'Honda',
    'tahun': 2023,
    'harga': 4500000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 120,
    'topSpeed': 190,
  },
  {
    'id': '14',
    'nama': 'Toyota Rush',
    'merek': 'Toyota',
    'tahun': 2022,
    'harga': 5000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 100,
    'topSpeed': 160,
  },
  {
    'id': '15',
    'nama': 'Honda BR-V',
    'merek': 'Honda',
    'tahun': 2022,
    'harga': 5500000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 140,
    'topSpeed': 185,
  },
  {
    'id': '16',
    'nama': 'Toyota Innova Zenix',
    'merek': 'Toyota',
    'tahun': 2023,
    'harga': 6000000,
    'tipe': 'MPV',
    'kondisi': 'Baru',
    'hp': 170,
    'topSpeed': 190,
  },

  // =============================================
  // TIER 4 - SUV PREMIUM (7.0M - 9.5M)
  // =============================================
  {
    'id': '17',
    'nama': 'Mitsubishi Pajero Sport',
    'merek': 'Mitsubishi',
    'tahun': 2023,
    'harga': 7000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 180,
    'topSpeed': 195,
  },
  {
    'id': '18',
    'nama': 'Nissan X-Trail',
    'merek': 'Nissan',
    'tahun': 2022,
    'harga': 7500000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 160,
    'topSpeed': 190,
  },
  {
    'id': '19',
    'nama': 'Honda CR-V',
    'merek': 'Honda',
    'tahun': 2023,
    'harga': 8000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 190,
    'topSpeed': 210,
  },
  {
    'id': '20',
    'nama': 'Mitsubishi Pajero',
    'merek': 'Mitsubishi',
    'tahun': 2021,
    'harga': 8000000,
    'tipe': 'SUV',
    'kondisi': 'Bekas',
    'hp': 160,
    'topSpeed': 180,
  },
  {
    'id': '21',
    'nama': 'Mazda CX-5',
    'merek': 'Mazda',
    'tahun': 2023,
    'harga': 8200000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 190,
    'topSpeed': 215,
  },
  {
    'id': '22',
    'nama': 'Subaru Forester',
    'merek': 'Subaru',
    'tahun': 2022,
    'harga': 8800000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 180,
    'topSpeed': 205,
  },
  {
    'id': '23',
    'nama': 'Toyota Camry',
    'merek': 'Toyota',
    'tahun': 2023,
    'harga': 9500000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 210,
    'topSpeed': 230,
  },
  {
    'id': '24',
    'nama': 'Toyota Fortuner',
    'merek': 'Toyota',
    'tahun': 2022,
    'harga': 9500000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 200,
    'topSpeed': 190,
  },

  // =============================================
  // TIER 5 - PREMIUM SEDAN & SUV LARGE (10M - 12.5M)
  // =============================================
  {
    'id': '25',
    'nama': 'Honda Accord',
    'merek': 'Honda',
    'tahun': 2023,
    'harga': 10000000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 250,
    'topSpeed': 240,
  },
  {
    'id': '26',
    'nama': 'Ford Everest',
    'merek': 'Ford',
    'tahun': 2022,
    'harga': 11000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 200,
    'topSpeed': 195,
  },
  {
    'id': '27',
    'nama': 'BMW 3 Series',
    'merek': 'BMW',
    'tahun': 2023,
    'harga': 11500000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 280,
    'topSpeed': 260,
  },
  {
    'id': '28',
    'nama': 'Audi A4',
    'merek': 'Audi',
    'tahun': 2023,
    'harga': 12000000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 270,
    'topSpeed': 255,
  },
  {
    'id': '29',
    'nama': 'Ford Mustang',
    'merek': 'Ford',
    'tahun': 2022,
    'harga': 12000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 400,
    'topSpeed': 280,
  },
  {
    'id': '30',
    'nama': 'Jeep Wrangler',
    'merek': 'Jeep',
    'tahun': 2022,
    'harga': 12500000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 280,
    'topSpeed': 180,
  },

  // =============================================
  // TIER 6 - SPORT & LUXURY ENTRY (13M - 15M)
  // =============================================
  {
    'id': '31',
    'nama': 'Chevrolet Camaro',
    'merek': 'Chevrolet',
    'tahun': 2022,
    'harga': 13000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 450,
    'topSpeed': 290,
  },
  {
    'id': '32',
    'nama': 'Mercedes C-Class',
    'merek': 'Mercedes',
    'tahun': 2023,
    'harga': 13500000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 300,
    'topSpeed': 270,
  },
  {
    'id': '33',
    'nama': 'Dodge Challenger',
    'merek': 'Dodge',
    'tahun': 2022,
    'harga': 14000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 480,
    'topSpeed': 295,
  },
  {
    'id': '34',
    'nama': 'BMW M4',
    'merek': 'BMW',
    'tahun': 2023,
    'harga': 14500000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 350,
    'topSpeed': 290,
  },
  {
    'id': '35',
    'nama': 'Toyota Land Cruiser',
    'merek': 'Toyota',
    'tahun': 2023,
    'harga': 15000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 350,
    'topSpeed': 210,
  },

  // =============================================
  // TIER 7 - SUPER SPORT & PREMIUM SUV (17M - 22M)
  // =============================================
  {
    'id': '36',
    'nama': 'Porsche Cayenne',
    'merek': 'Porsche',
    'tahun': 2023,
    'harga': 17000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 340,
    'topSpeed': 260,
  },
  {
    'id': '37',
    'nama': 'Porsche 911',
    'merek': 'Porsche',
    'tahun': 2023,
    'harga': 18000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 380,
    'topSpeed': 300,
  },
  {
    'id': '38',
    'nama': 'Jaguar F-Type',
    'merek': 'Jaguar',
    'tahun': 2022,
    'harga': 19000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 450,
    'topSpeed': 310,
  },
  {
    'id': '39',
    'nama': 'Mercedes AMG GT',
    'merek': 'Mercedes',
    'tahun': 2023,
    'harga': 20000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 450,
    'topSpeed': 310,
  },
  {
    'id': '40',
    'nama': 'Maserati Ghibli',
    'merek': 'Maserati',
    'tahun': 2023,
    'harga': 21000000,
    'tipe': 'Sedan',
    'kondisi': 'Baru',
    'hp': 430,
    'topSpeed': 320,
  },
  {
    'id': '41',
    'nama': 'Audi R8',
    'merek': 'Audi',
    'tahun': 2023,
    'harga': 22000000,
    'tipe': 'Sport',
    'kondisi': 'Baru',
    'hp': 520,
    'topSpeed': 330,
  },

  // =============================================
  // TIER 8 - HYPERCAR & LUXURY (24M - 28M)
  // =============================================
  {
    'id': '42',
    'nama': 'Lamborghini Urus',
    'merek': 'Lamborghini',
    'tahun': 2023,
    'harga': 24000000,
    'tipe': 'SUV',
    'kondisi': 'Baru',
    'hp': 650,
    'topSpeed': 305,
  },
  {
    'id': '43',
    'nama': 'Ferrari F8',
    'merek': 'Ferrari',
    'tahun': 2022,
    'harga': 25000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 700,
    'topSpeed': 340,
  },
  {
    'id': '44',
    'nama': 'McLaren 720S',
    'merek': 'McLaren',
    'tahun': 2022,
    'harga': 26000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 710,
    'topSpeed': 345,
  },
  {
    'id': '45',
    'nama': 'Bentley Continental GT',
    'merek': 'Bentley',
    'tahun': 2023,
    'harga': 28000000,
    'tipe': 'Luxury',
    'kondisi': 'Baru',
    'hp': 550,
    'topSpeed': 320,
  },
  {
    'id': '46',
    'nama': 'Lamborghini Aventador',
    'merek': 'Lamborghini',
    'tahun': 2022,
    'harga': 28000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 750,
    'topSpeed': 350,
  },

  // =============================================
  // TIER 9 - LEGEND & ULTIMATE EXCLUSIVE (32M - 42M)
  // =============================================
  {
    'id': '47',
    'nama': 'Rolls-Royce Ghost',
    'merek': 'Rolls-Royce',
    'tahun': 2023,
    'harga': 32000000,
    'tipe': 'Luxury',
    'kondisi': 'Baru',
    'hp': 570,
    'topSpeed': 310,
  },
  {
    'id': '48',
    'nama': 'Pagani Huayra',
    'merek': 'Pagani',
    'tahun': 2021,
    'harga': 35000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 830,
    'topSpeed': 370,
  },
  {
    'id': '49',
    'nama': 'Koenigsegg Jesko',
    'merek': 'Koenigsegg',
    'tahun': 2022,
    'harga': 38000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 1600,
    'topSpeed': 480,
  },
  {
    'id': '50',
    'nama': 'Bugatti Chiron',
    'merek': 'Bugatti',
    'tahun': 2023,
    'harga': 42000000,
    'tipe': 'Hypercar',
    'kondisi': 'Baru',
    'hp': 1500,
    'topSpeed': 420,
  },
];
