import '../tes_seleksi_model.dart';

List<QuestionItem> getAgroteknologiQuestions() {
  return const [
    QuestionItem(
      id: 'agr_001',
      questionText: 'Tiga unsur hara makro utama yang paling dibutuhkan tanaman dalam jumlah besar adalah:',
      options: ['Nitrogen (N), Fosfor (P), dan Kalium (K)', 'Besi (Fe), Seng (Zn), dan Tembaga (Cu)', 'Kalsium (Ca), Magnesium (Mg), dan Belerang (S)', 'Boron (B), Mangan (Mn), dan Molibdenum (Mo)'],
      correctOptionIndex: 0,
      explanation: 'Nitrogen, Fosfor, dan Kalium (NPK) adalah tiga hara makro primer bagi pertumbuhan tanaman.',
    ),
    QuestionItem(
      id: 'agr_002',
      questionText: 'Gejala menguningnya daun tanaman akibat kekurangan unsur klorofil atau hara nitrogen dinamakan:',
      options: ['Klorosis', 'Nekrosis', 'Etiolasi', 'Gutasi'],
      correctOptionIndex: 0,
      explanation: 'Klorosis adalah kondisi hilangnya klorofil sehingga daun berwarna kuning pucat.',
    ),
    QuestionItem(
      id: 'agr_003',
      questionText: 'Kematian jaringan tanaman yang ditandai dengan bercak cokelat atau hitam kering pada daun dinamakan:',
      options: ['Nekrosis', 'Klorosis', 'Etiolasi', 'Turgor'],
      correctOptionIndex: 0,
      explanation: 'Nekrosis adalah kerusakan mati jaringan sel tanaman.',
    ),
    QuestionItem(
      id: 'agr_004',
      questionText: 'Pertumbuhan tanaman yang sangat cepat namun lemah dan pucat akibat kekurangan cahaya matahari dinamakan:',
      options: ['Etiolasi', 'Klorosis', 'Dormansi', 'Vernalisasi'],
      correctOptionIndex: 0,
      explanation: 'Etiolasi terjadi ketika tanaman tumbuh memanjang abnormal memburu cahaya.',
    ),
    QuestionItem(
      id: 'agr_005',
      questionText: 'Proses penguapan air dari jaringan tubuh tanaman melalui stomata ke udara dinamakan:',
      options: ['Transpirasi', 'Evaporasi', 'Gutasi', 'Imbibisi'],
      correctOptionIndex: 0,
      explanation: 'Transpirasi adalah pelepasan uap air melalui pori-pori stomata daun.',
    ),
    QuestionItem(
      id: 'agr_006',
      questionText: 'Keluarnya tetesan air dari ujung daun pada malam/pagi hari akibat tekanan akar yang tinggi dinamakan:',
      options: ['Gutasi', 'Transpirasi', 'Osmosis', 'Difusi'],
      correctOptionIndex: 0,
      explanation: 'Gutasi adalah pelepasan cairan air melalui struktur hidatoda di tepi daun.',
    ),
    QuestionItem(
      id: 'agr_007',
      questionText: 'Hormon tumbuhan yang memicu pemanjangan sel, dominansi apikal, dan pembentukan akar adalah:',
      options: ['Auksin', 'Sitokinin', 'Giberelin', 'Asam Absisat'],
      correctOptionIndex: 0,
      explanation: 'Auksin berperan penting dalam dominansi apikal dan pemanjangan sel batang/akar.',
    ),
    QuestionItem(
      id: 'agr_008',
      questionText: 'Hormon tumbuhan yang merangsang pembelahan sel (sitokinesis) dan menunda penuaan daun adalah:',
      options: ['Sitokinin', 'Auksin', 'Etilen', 'Asam Absisat'],
      correctOptionIndex: 0,
      explanation: 'Sitokinin memicu pembelahan sel serta pembentukan tunas samping.',
    ),
    QuestionItem(
      id: 'agr_009',
      questionText: 'Hormon tumbuhan yang berfungsi merangsang perkecambahan benih dan pemanjangan buku batang adalah:',
      options: ['Giberelin', 'Sitokinin', 'Etilen', 'Traulin'],
      correctOptionIndex: 0,
      explanation: 'Giberelin mematahkan dormansi benih dan memicu pertumbuhan memanjang.',
    ),
    QuestionItem(
      id: 'agr_010',
      questionText: 'Hormon tumbuhan berbentuk gas yang berfungsi mempercepat proses pematangan buah adalah:',
      options: ['Etilen', 'Auksin', 'Giberelin', 'Kalin'],
      correctOptionIndex: 0,
      explanation: 'Etilen memicu pemasakan buah dan pengguguran daun (absisi).',
    ),
    QuestionItem(
      id: 'agr_011',
      questionText: 'Hormon tumbuhan yang merespons kondisi stres air dengan menutup stomata daun adalah:',
      options: ['Asam Absisat (ABA)', 'Auksin', 'Sitokinin', 'Giberelin'],
      correctOptionIndex: 0,
      explanation: 'Asam Absisat memicu penutupan stomata saat tanaman mengalami kekeringan.',
    ),
    QuestionItem(
      id: 'agr_012',
      questionText: 'Metode budidaya tanaman tanpa menggunakan tanah melainkan memanfaatkan media larutan nutrisi air dinamakan:',
      options: ['Hidroponik', 'Aeroponik', 'Aquaponik', 'Marikultur'],
      correctOptionIndex: 0,
      explanation: 'Hidroponik menanam tanaman menggunakan media air bernutrisi.',
    ),
    QuestionItem(
      id: 'agr_013',
      questionText: 'Metode budidaya hidroponik di mana akar tanaman digantung di udara dan disemprot kabut nutrisi dinamakan:',
      options: ['Aeroponik', 'Aquaponik', 'Drip Irrigation', 'Deep Water Culture'],
      correctOptionIndex: 0,
      explanation: 'Aeroponik menyemprotkan kabut nutrisi secara berkala ke akar yang menggantung.',
    ),
    QuestionItem(
      id: 'agr_014',
      questionText: 'Sistem integrasi pertanian yang memadukan budidaya ikan dengan budidaya tanaman hidroponik dinamakan:',
      options: ['Aquaponik', 'Aeroponik', 'Permakultur', 'Agroforestri'],
      correctOptionIndex: 0,
      explanation: 'Aquaponik memanfaatkan kotoran ikan sebagai nutrisi organik tanaman.',
    ),
    QuestionItem(
      id: 'agr_015',
      questionText: 'Teknik perbanyakan tanaman secara vegetatif aseptik di dalam tabung reaksi menggunakan media steril dinamakan:',
      options: ['Kultur Jaringan (Tissue Culture)', 'Okulasi', 'Cangkok', 'Stek'],
      correctOptionIndex: 0,
      explanation: 'Kultur jaringan menumbuhkan eksplan sel tanaman pada media buatan yang steril.',
    ),
    QuestionItem(
      id: 'agr_016',
      questionText: 'Potongan kecil jaringan tanaman (seperti daun atau tunas) yang digunakan dalam kultur jaringan dinamakan:',
      options: ['Eksplan', 'Kalus', 'Planlet', 'Zigot'],
      correctOptionIndex: 0,
      explanation: 'Eksplan adalah bagian jaringan tanaman awal yang diisolasi untuk kultur jaringan.',
    ),
    QuestionItem(
      id: 'agr_017',
      questionText: 'Masa istirahat benih di mana benang perkecambahan tidak aktif walaupun kondisi lingkungan mendukung dinamakan:',
      options: ['Dormansi', 'Vernalisasi', 'Imbibisi', 'Gerimis'],
      correctOptionIndex: 0,
      explanation: 'Dormansi benih adalah masa istirahat fisiologis sebelum berkecambah.',
    ),
    QuestionItem(
      id: 'agr_018',
      questionText: 'Proses penyerapan air oleh benih yang mengawali proses perkecambahan dinamakan:',
      options: ['Imbibisi', 'Osmosis', 'Transpirasi', 'Gutasi'],
      correctOptionIndex: 0,
      explanation: 'Imbibisi adalah tahap masuknya air meresap ke dalam kulit benih.',
    ),
    QuestionItem(
      id: 'agr_019',
      questionText: 'Tingkat keasaman tanah yang ideal bagi sebagian besar tanaman pertanian berkisar antara pH:',
      options: ['6,0 hingga 7,0', '3,0 hingga 4,5', '8,5 hingga 10,0', '1,0 hingga 2,0'],
      correctOptionIndex: 0,
      explanation: 'pH tanah netral hingga agak asam (6,0 - 7,0) menyediakan ketersediaan hara paling optimal.',
    ),
    QuestionItem(
      id: 'agr_020',
      questionText: 'Bahan pembenah tanah alami berupa kapur pertanian yang digunakan untuk menaikkan pH tanah masam adalah:',
      options: ['Dolomit / Kapur Pertanian', 'Belerang', 'Urea', 'Za'],
      correctOptionIndex: 0,
      explanation: 'Dolomit (CaMg(CO3)2) efektif menetralkan keasaman tanah masam.',
    ),
    QuestionItem(
      id: 'agr_021',
      questionText: 'Kapasitas tanah untuk menjerap dan mempertukarkan kation hara positif (seperti Ca2+, Mg2+, K+) dinamakan:',
      options: ['KTK (Kapasitas Tukar Kation)', 'Porositas', 'Permeabilitas', 'Bulk Density'],
      correctOptionIndex: 0,
      explanation: 'KTK mencerminkan tingkat kesuburan dan kemampuan tanah memegang hara.',
    ),
    QuestionItem(
      id: 'agr_022',
      questionText: 'Lapisan bahan organik tanah yang telah mengalami pelapukan lanjut dan berwarna gelap dinamakan:',
      options: ['Humus', 'Solum', 'Regolit', 'Parent material'],
      correctOptionIndex: 0,
      explanation: 'Humus meningkatkan retensi air dan memperbaiki struktur kesuburan tanah.',
    ),
    QuestionItem(
      id: 'agr_023',
      questionText: 'Tiga komponen utama pembentuk tekstur tanah adalah perbandingan fraksi:',
      options: ['Pasir, Debu, dan Liat', 'Batu, Pasir, dan Kerikil', 'Humus, Air, dan Udara', 'Tanah, Serabut, dan Gambut'],
      correctOptionIndex: 0,
      explanation: 'Tekstur tanah ditentukan oleh proporsi partikel pasir (sand), debu (silt), dan liat (clay).',
    ),
    QuestionItem(
      id: 'agr_024',
      questionText: 'Strategi pengelolaan hama dengan memadukan berbagai metode ramah lingkungan dinamakan:',
      options: ['PHT (Pengendalian Hama Terpadu)', 'Pestisida Kimia Masif', 'Eradikasi Total', 'Monokultur'],
      correctOptionIndex: 0,
      explanation: 'PHT mengutamakan keseimbangan ekosistem dan penggunaan musuh alami hama.',
    ),
    QuestionItem(
      id: 'agr_025',
      questionText: 'Pemanfaatan hewan predator atau parasitoid untuk menekan populasi hama tanaman dinamakan pengendalian secara:',
      options: ['Biologis / Hayati', 'Kimiawi', 'Mekanis', 'Kultur Teknis'],
      correctOptionIndex: 0,
      explanation: 'Pengendalian hayati memanfaatkan agens hayati musuh alami hama.',
    ),
    QuestionItem(
      id: 'agr_026',
      questionText: 'Jamur antagonis yang sering dimanfaatkan sebagai agen hayati untuk mengendalikan penyakit jamur akar tanaman adalah:',
      options: ['Trichoderma sp.', 'Rhizopus sp.', 'Saccharomyces sp.', 'Aspergillus sp.'],
      correctOptionIndex: 0,
      explanation: 'Trichoderma dikenal sebagai jamur menguntungkan penekan penyakit tular tanah.',
    ),
    QuestionItem(
      id: 'agr_027',
      questionText: 'Bakteri tanah yang mampu bersimbiosis dengan akar tanaman legum/kacang-kacangan untuk mengikat nitrogen bebas adalah:',
      options: ['Rhizobium sp.', 'Nitrosomonas sp.', 'Escherichia coli', 'Bacillus thuringiensis'],
      correctOptionIndex: 0,
      explanation: 'Rhizobium mengikat N2 dari udara di dalam bintil akar leguminosa.',
    ),
    QuestionItem(
      id: 'agr_028',
      questionText: 'Cendawan mikoriza yang bersimbiosis dengan akar tanaman untuk memperluas area penyerapan hara fosfor dinamakan:',
      options: ['Mikoriza (MVA)', 'Fusarium', 'Phytophthora', 'Pythium'],
      correctOptionIndex: 0,
      explanation: 'Mikoriza meningkatkan kapasitas akar menyerap air dan hara Fosfor (P).',
    ),
    QuestionItem(
      id: 'agr_029',
      questionText: 'Pola penanaman bergiliran beberapa jenis tanaman berbeda pada lahan yang sama secara bergantian dinamakan:',
      options: ['Rotasi Tanaman', 'Monokultur', 'Tumpangsari', 'Reboisasi'],
      correctOptionIndex: 0,
      explanation: 'Rotasi tanaman memutus siklus hama penyakit dan menjaga kesuburan tanah.',
    ),
    QuestionItem(
      id: 'agr_030',
      questionText: 'Sistem penanaman lebih dari satu jenis tanaman sekaligus dalam satu bidang lahan secara bersamaan dinamakan:',
      options: ['Tumpangsari (Intercropping)', 'Monokultur', 'Bera', 'Dry farming'],
      correctOptionIndex: 0,
      explanation: 'Tumpangsari memanfaatkan efisiensi lahan dan ruang secara optimal.',
    ),
    QuestionItem(
      id: 'agr_031',
      questionText: 'Pola penanaman satu jenis tanaman saja secara terus-menerus pada suatu luas lahan dinamakan:',
      options: ['Monokultur', 'Polikultur', 'Agroforestri', 'Permakultur'],
      correctOptionIndex: 0,
      explanation: 'Monokultur berisiko memicu ledakan hama karena hilangnya keanekaragaman hayati.',
    ),
    QuestionItem(
      id: 'agr_032',
      questionText: 'Sistem irigasi modern yang mengalirkan air dan nutrisi langsung ke perakaran tanaman dalam bentuk tetesan hemat air adalah:',
      options: ['Irigasi Tetes (Drip Irrigation)', 'Irigasi Genangan', 'Irigasi Sprinkler', 'Irigasi Sub-Permukaan'],
      correctOptionIndex: 0,
      explanation: 'Irigasi tetes menghemat penggunaan air dengan efisiensi penyerapan sangat tinggi.',
    ),
    QuestionItem(
      id: 'agr_033',
      questionText: 'Pencegahan erosi tanah pada lahan miring dengan membuat berundak-undak bertingkat dinamakan:',
      options: ['Terasering', 'Mulsa', 'Drainase', 'Pengolahan Tanah Maksimum'],
      correctOptionIndex: 0,
      explanation: 'Terasering menahan aliran permukaan dan pencegahan erosi tanah di lereng.',
    ),
    QuestionItem(
      id: 'agr_034',
      questionText: 'Penutupan permukaan tanah di sekitar tanaman menggunakan jerami atau plastik untuk menekan gulma dinamakan:',
      options: ['Mulsa (Mulching)', 'Penyulaman', 'Penyiangan', 'Pembumbunan'],
      correctOptionIndex: 0,
      explanation: 'Mulsa menjaga kelembapan tanah, suhu media, dan menekan pertumbuhan gulma.',
    ),
    QuestionItem(
      id: 'agr_035',
      questionText: 'Kegiatan mengganti tanaman yang mati atau tumbuh abnormal dengan bibit baru pada awal penanaman dinamakan:',
      options: ['Penyulaman', 'Penyiangan', 'Pruning', 'Pengajiran'],
      correctOptionIndex: 0,
      explanation: 'Penyulaman dilakukan agar populasi tanaman di lahan tetap sesuai target.',
    ),
    QuestionItem(
      id: 'agr_036',
      questionText: 'Kegiatan membuang gulma atau tumbuhan pengganggu di sekitar tanaman budidaya dinamakan:',
      options: ['Penyiangan', 'Penyulaman', 'Pemangkasan', 'Harvesting'],
      correctOptionIndex: 0,
      explanation: 'Penyiangan mengurangi kompetisi perebutan hara dan cahaya dari gulma.',
    ),
    QuestionItem(
      id: 'agr_037',
      questionText: 'Kegiatan memotong bagian cabang atau daun tanaman yang tidak produktif atau terserang penyakit dinamakan:',
      options: ['Pemangkasan (Pruning)', 'Pembumbunan', 'Penyulaman', 'Okulasi'],
      correctOptionIndex: 0,
      explanation: 'Pruning merangsang pertumbuhan tunas produktif dan sirkulasi udara.',
    ),
    QuestionItem(
      id: 'agr_038',
      questionText: 'Penggabungan mata tunas dari satu tanaman ke batang bawah tanaman lain yang sejenis dinamakan:',
      options: ['Okulasi (Budding)', 'Cangkok', 'Stek', 'Sambung pucuk'],
      correctOptionIndex: 0,
      explanation: 'Okulasi memadukan keunggulan batang bawah yang kuat dengan varietas unggul mata tunas.',
    ),
    QuestionItem(
      id: 'agr_039',
      questionText: 'Pupuk kimia sintetis yang berfungsi sebagai sumber hara Nitrogen utama bagi tanaman adalah:',
      options: ['Urea', 'SP-36', 'KCl', 'Dolomit'],
      correctOptionIndex: 0,
      explanation: 'Urea (CO(NH2)2) mengandung kadar Nitrogen tinggi sekitar 46%.',
    ),
    QuestionItem(
      id: 'agr_040',
      questionText: 'Pupuk anorganik yang diproduksi khusus untuk menyediakan hara Fosfor (P) bagi pertumbuhan akar adalah:',
      options: ['SP-36 / TSP', 'Urea', 'KCl', 'ZA'],
      correctOptionIndex: 0,
      explanation: 'SP-36 merangsang pertumbuhan akar dan pembungaan.',
    ),
    QuestionItem(
      id: 'agr_041',
      questionText: 'Pupuk anorganik sumber hara Kalium (K) yang berperan meningkatkan ketahanan tanaman dan kualitas buah adalah:',
      options: ['KCl (Kalium Klorida)', 'Urea', 'ZA', 'Ampos'],
      correctOptionIndex: 0,
      explanation: 'KCl memperkuat pembentukan buah dan daya tahan dari penyakit.',
    ),
    QuestionItem(
      id: 'agr_042',
      questionText: 'Pupuk organik yang berasal dari hasil penguraian sisa kotoran hewan ternak dinamakan:',
      options: ['Pupuk Kandang', 'Pupuk Hijau', 'Kompos', 'Kasgot'],
      correctOptionIndex: 0,
      explanation: 'Pupuk kandang memanfaatkan limbah feses/urine ternak yang telah difermentasi.',
    ),
    QuestionItem(
      id: 'agr_043',
      questionText: 'Pupuk organik hasil pelapukan sisa dedaunan dan sampah organik dengan bantuan mikroba dekomposer dinamakan:',
      options: ['Kompos', 'Urea', 'N PK', 'Fosfat alam'],
      correctOptionIndex: 0,
      explanation: 'Kompos adalah pupuk organik hasil dekomposisi bahan biologis.',
    ),
    QuestionItem(
      id: 'agr_044',
      questionText: 'Pupuk organik hayati hasil olahan kotoran yang diurai oleh larva lalat Black Soldier Fly (BSF) dinamakan:',
      options: ['Kasgot (Bekas Maggot)', 'Pupuk Guano', 'Biochar', 'Humus'],
      correctOptionIndex: 0,
      explanation: 'Kasgot merupakan pupuk organik nutrisi tinggi dari residu pencernaan maggot BSF.',
    ),
    QuestionItem(
      id: 'agr_045',
      questionText: 'Pupuk organik yang memanfaatkan kotoran burung laut atau kelelawar yang kaya fosfat dinamakan:',
      options: ['Guano', 'Kasgot', 'Kompos', 'Kapur'],
      correctOptionIndex: 0,
      explanation: 'Guano terakumulasi dari kotoran kelelawar/burung laut yang kaya unsur P dan N.',
    ),
    QuestionItem(
      id: 'agr_046',
      questionText: 'Proses pengubahan gas Nitrogen bebas di udara (N2) menjadi amonia atau nitrat yang dapat diserap tanaman dinamakan:',
      options: ['Fiksasi Nitrogen', 'Denitrifikasi', 'Amonifikasi', 'Nitrifikasi'],
      correctOptionIndex: 0,
      explanation: 'Fiksasi Nitrogen mengubah N2 udara menjadi bentuk hara terlarut.',
    ),
    QuestionItem(
      id: 'agr_047',
      questionText: 'Proses biologis pengubahan amonia menjadi nitrit dan kemudian menjadi nitrat oleh bakteri tanah dinamakan:',
      options: ['Nitrifikasi', 'Fiksasi', 'Denitrifikasi', 'Asimilasi'],
      correctOptionIndex: 0,
      explanation: 'Nitrifikasi diubah oleh bakteri Nitrosomonas dan Nitrobacter.',
    ),
    QuestionItem(
      id: 'agr_048',
      questionText: 'Organel sel tumbuhan yang berfungsi sebagai tempat berlangsungnya proses fotosintesis adalah:',
      options: ['Kloroplas', 'Mitokondria', 'Vakuola', 'Ribosom'],
      correctOptionIndex: 0,
      explanation: 'Kloroplas mengandung pigmen klorofil pembawa rekasi fotosintesis.',
    ),
    QuestionItem(
      id: 'agr_049',
      questionText: 'Reaksi gelap fotosintesis (Siklus Calvin) berlangsung di dalam bagian kloroplas yang dinamakan:',
      options: ['Stroma', 'Tilakoid', 'Grana', 'Membran luar'],
      correctOptionIndex: 0,
      explanation: 'Siklus Calvin berlangsung pada cairan stroma kloroplas.',
    ),
    QuestionItem(
      id: 'agr_050',
      questionText: 'Reaksi terang fotosintesis terjadi di dalam struktur kloroplas yang dinamakan:',
      options: ['Membran Tilakoid / Grana', 'Stroma', 'Vakuola', 'Nukleus'],
      correctOptionIndex: 0,
      explanation: 'Reaksi terang penangkapan cahaya matahari terjadi di tilakoid/grana.',
    ),
    QuestionItem(
      id: 'agr_051',
      questionText: 'Penyebab utama penyakit busuk daun late blight pada tanaman kentang dan tomat adalah organisme:',
      options: ['Phytophthora infestans (Oomycota)', 'Fusarium oxysporum', 'Xanthomonas campestris', 'Mosaic Virus'],
      correctOptionIndex: 0,
      explanation: 'Phytophthora infestans adalah patogen penyebab busuk daun late blight.',
    ),
    QuestionItem(
      id: 'agr_052',
      questionText: 'Penyebab penyakit layu bakteri pada tanaman terung-terungan (Solanaceae) adalah bakteri:',
      options: ['Ralstonia solanacearum', 'Bacillus subtilis', 'Rhizobium leguminosarum', 'Agrobacterium tumefaciens'],
      correctOptionIndex: 0,
      explanation: 'Ralstonia solanacearum memicu penyakit layu pembuluh vaskular.',
    ),
    QuestionItem(
      id: 'agr_053',
      questionText: 'Serangga hama penghisap cairan daun yang sering menjadi vektor pembawa virus kuning pada cabai adalah:',
      options: ['Kutu Daun (Kutu Kebul / Bemisia tabaci)', 'Ulat Grayak', 'Walang Sangit', 'Penggerek Batang'],
      correctOptionIndex: 0,
      explanation: 'Kutu kebul (Bemisia tabaci) memindahkan Begomovirus penyebab penyakit kuning cabai.',
    ),
    QuestionItem(
      id: 'agr_054',
      questionText: 'Hama utama tanaman padi yang merusak bulir padi muda pada fase pengisian cairan bulir dinamakan:',
      options: ['Walang Sangit (Leptocorisa oratorius)', 'Wereng Cokelat', 'Tikus Sawah', 'Ganjur'],
      correctOptionIndex: 0,
      explanation: 'Walang sangit menghisap cairan bulir padi yang sedang matang susu.',
    ),
    QuestionItem(
      id: 'agr_055',
      questionText: 'Hama serangga padi yang sangat berbahaya karena dapat menyebabkan gejala kerdil hampa dan sudu dinamakan:',
      options: ['Wereng Batang Cokelat (Nilaparvata lugens)', 'Ulat Tanah', 'Keong Mas', 'Orong-orong'],
      correctOptionIndex: 0,
      explanation: 'Wereng cokelat merupakan hama destruktif perusak pertanaman padi.',
    ),
    QuestionItem(
      id: 'agr_056',
      questionText: 'Pestisida pertanian yang khusus digunakan untuk mengendalikan serangan gulma atau tumbuhan pengganggu dinamakan:',
      options: ['Herbisida', 'Insektisida', 'Fungisida', 'Nematisida'],
      correctOptionIndex: 0,
      explanation: 'Herbisida membasmi gulma dan tumbuhan pengganggu.',
    ),
    QuestionItem(
      id: 'agr_057',
      questionText: 'Pestisida pertanian yang khusus digunakan untuk membasmi penyakit yang disebabkan oleh cendawan/jamur dinamakan:',
      options: ['Fungisida', 'Herbisida', 'Insektisida', 'Bakterisida'],
      correctOptionIndex: 0,
      explanation: 'Fungisida menekan penyakit jamur tanaman.',
    ),
    QuestionItem(
      id: 'agr_058',
      questionText: 'Pestisida ramah lingkungan yang dibuat dari racun alami ekstrak tumbuh-tumbuhan (seperti mimba/gadung) dinamakan:',
      options: ['Pestisida Nabati / Biopestisida', 'Pestisida Sistemik anorganik', 'Pestisida Kontak sintetis', 'Fungisida kimia'],
      correctOptionIndex: 0,
      explanation: 'Pestisida nabati mengekstrak senyawa sekunder tanaman alami penolak hama.',
    ),
    QuestionItem(
      id: 'agr_059',
      questionText: 'Konsep pertanian presisi (Precision Agriculture) memanfaatkan teknologi modern berupa:',
      options: ['Sensor tanah, GPS, dan Drone pemantau', 'Cangkul dan bajak tradisional', 'Pestisida berlebih tanpa takaran', 'Pembakaran lahan serentak'],
      correctOptionIndex: 0,
      explanation: 'Precision Farming mengoptimalkan efisiensi input berbasis data sensor dan pemetaan digital.',
    ),
    QuestionItem(
      id: 'agr_060',
      questionText: 'Teknologi pemuliaan tanaman dengan menyisipkan gen asing dari spesies lain dinamakan tanaman:',
      options: ['Transgenik / PRG (Produk Rekayasa Genetika)', 'Hibrida', 'Mutan', 'Lokal'],
      correctOptionIndex: 0,
      explanation: 'Tanaman transgenik disisipi rekombinan DNA spesifik unggul.',
    ),
    QuestionItem(
      id: 'agr_061',
      questionText: 'Variasi tanaman keturunan pertama (F1) dari persilangan dua tetua galur murni yang berbeda dinamakan varietas:',
      options: ['Hibrida (F1 Hybrid)', 'Galur Murni', 'Komposit', 'Polikross'],
      correctOptionIndex: 0,
      explanation: 'Varietas Hibrida menampakkan keunggulan vigor heterosis keturunan F1.',
    ),
    QuestionItem(
      id: 'agr_062',
      questionText: 'Fenomena peningkatan ketahanan dan pertumbuhan F1 hibrida yang melebihi rata-rata kedua tetuanya dinamakan:',
      options: ['Heterosis / Vigor Hibrida', 'Homozygositas', 'Inbreeding depression', 'Epistasis'],
      correctOptionIndex: 0,
      explanation: 'Heterosis adalah peningkatan performa hibrida F1 dibanding tetuanya.',
    ),
    QuestionItem(
      id: 'agr_063',
      questionText: 'Jaringan pembawa air dan hara mineral dari akar menuju ke daun pada tanaman vaskular dinamakan:',
      options: ['Xilem', 'Floem', 'Kambium', 'Kortex'],
      correctOptionIndex: 0,
      explanation: 'Xilem mengangkut air dan unsur hara terlarut dari tanah ke daun.',
    ),
    QuestionItem(
      id: 'agr_064',
      questionText: 'Jaringan pembawa hasil fotosintesis dari daun ke seluruh bagian organ tanaman dinamakan:',
      options: ['Floem', 'Xilem', 'Epidermis', 'Parenkim'],
      correctOptionIndex: 0,
      explanation: 'Floem mengedarkan glukosa asimilat hasil fotosintesis.',
    ),
    QuestionItem(
      id: 'agr_065',
      questionText: 'Lapisan sel aktif membelah yang menyebabkan pertumbuhan membesar sekunder pada batang dikotil dinamakan:',
      options: ['Kambium', 'Xilem', 'Floem', 'Korteks'],
      correctOptionIndex: 0,
      explanation: 'Kambium membelah membentuk xilem sekunder ke dalam dan floem ke luar.',
    ),
    QuestionItem(
      id: 'agr_066',
      questionText: 'Tipe perkecambahan benih di mana kotiledon (daun lembaga) terangkat keluar di atas permukaan tanah dinamakan:',
      options: ['Epigeal', 'Hipogeal', 'Vivipari', 'Dorman'],
      correctOptionIndex: 0,
      explanation: 'Perkecambahan Epigeal memperlihatkan hipokotil memanjang mengangkat kotiledon.',
    ),
    QuestionItem(
      id: 'agr_067',
      questionText: 'Tipe perkecambahan benih di mana kotiledon tetap tertinggal di dalam tanah (seperti pada jagung) dinamakan:',
      options: ['Hipogeal', 'Epigeal', 'Apomiksis', 'Partenokarpi'],
      correctOptionIndex: 0,
      explanation: 'Perkecambahan Hipogeal memanjangkan epikotil dan meninggalkan kotiledon di tanah.',
    ),
    QuestionItem(
      id: 'agr_068',
      questionText: 'Pembentukan buah tanpa melalui proses pembuahan/penyerbukan sehingga menghasilkan buah tanpa biji dinamakan:',
      options: ['Partenokarpi', 'Apomiksis', 'Poliembrioni', 'Vernalisasi'],
      correctOptionIndex: 0,
      explanation: 'Partenokarpi menghasilkan buah tanpa biji (misal pisang atau semangka tanpa biji).',
    ),
    QuestionItem(
      id: 'agr_069',
      questionText: 'Proses stimulasi pembungaan tanaman akibat pemaparan suhu dingin periode tertentu dinamakan:',
      options: ['Vernalisasi', 'Fotoperiodisme', 'Termoperiodisme', 'Stratifikasi'],
      correctOptionIndex: 0,
      explanation: 'Vernalisasi adalah induksi pembungaan dengan paparan suhu dingin.',
    ),
    QuestionItem(
      id: 'agr_070',
      questionText: 'Respons pertumbuhan tanaman terhadap panjang pendeknya pencahayaan sinar matahari harian dinamakan:',
      options: ['Fotoperiodisme', 'Fototropisme', 'Vernalisasi', 'Tigmotropisme'],
      correctOptionIndex: 0,
      explanation: 'Fotoperiodisme memicu pembungaan berdasarkan durasi gelap-terang harian (Short-day / Long-day plants).',
    ),
    QuestionItem(
      id: 'agr_071',
      questionText: 'Gerak pertumbuhan bagian tanaman menuju atau menjauhi arah datangnya sinar cahaya matahari dinamakan:',
      options: ['Fototropisme', 'Geotropisme', 'Hidrotropisme', 'Nasti'],
      correctOptionIndex: 0,
      explanation: 'Fototropisme membelokkan pertumbuhan tunas menuju arah cahaya matahari.',
    ),
    QuestionItem(
      id: 'agr_072',
      questionText: 'Gerak pertumbuhan akar tanaman menembus tanah menuju ke pusat gravitasi bumi dinamakan:',
      options: ['Geotropisme / Gravitropisme Positif', 'Fototropisme', 'Tigmotropisme', 'Nasti'],
      correctOptionIndex: 0,
      explanation: 'Geotropisme positif mengarahkan akar tumbuh searah gravitasi.',
    ),
    QuestionItem(
      id: 'agr_073',
      questionText: 'Penanganan pascapanen buah dan sayur untuk menurunkan suhu lapangan secara cepat setelah dipanen dinamakan:',
      options: ['Pre-cooling', 'Curing', 'Waxing', 'Degreening'],
      correctOptionIndex: 0,
      explanation: 'Pre-cooling mendinginkan komoditas panen cepat untuk memperlambat laju respirasi.',
    ),
    QuestionItem(
      id: 'agr_074',
      questionText: 'Proses pelapisan lilin tipis aman makan pada permukaan buah untuk mengurangi laju transpirasi pascapanen dinamakan:',
      options: ['Waxing', 'Sorting', 'Grading', 'Blanching'],
      correctOptionIndex: 0,
      explanation: 'Waxing melapisi kulit buah agar mengilap dan menahan penguapan.',
    ),
    QuestionItem(
      id: 'agr_075',
      questionText: 'Metode pengeringan hasil pertanian di mana komoditas diletakkan di dalam ruang tertutup bertekanan dan suhu dingin ekstrem dinamakan:',
      options: ['Freeze Drying (Pengeringan Beku)', 'Sun Drying', 'Oven Drying', 'Solar Dryer'],
      correctOptionIndex: 0,
      explanation: 'Freeze Drying menjaga kandungan nutrisi dan rasa komoditas tanpa merusak struktur.',
    ),
    QuestionItem(
      id: 'agr_076',
      questionText: 'Kandungan kadar air maksimum biji-bijian (seperti gabah atau jagung) yang aman untuk disimpan lama tanpa jamur adalah sekitar:',
      options: ['12% hingga 14%', '20% hingga 25%', '5% hingga 8%', '30% hingga 35%'],
      correctOptionIndex: 0,
      explanation: 'Kadar air aman penyimpanan benih/gabah berkisar 12-14% untuk mencegah pertumbuhan jamur.',
    ),
    QuestionItem(
      id: 'agr_077',
      questionText: 'Gas yang dikeluarkan oleh buah klimakterik selama proses pematangan pascapanen adalah:',
      options: ['Etilen (C2H4)', 'Karbon Dioksida', 'Oksigen', 'Nitrogen'],
      correctOptionIndex: 0,
      explanation: 'Buah klimakterik memproduksi etilen tinggi saat fase puncak pematangan.',
    ),
    QuestionItem(
      id: 'agr_078',
      questionText: 'Contoh buah klimakterik yang mengalami peningkatan laju respirasi dramatis saat pematangan adalah:',
      options: ['Pisang, Mangga, dan Alpukat', 'Jeruk, Semangka, dan Anggur', 'Stroberi, Nanas, dan Timun', 'Cabai, Melon, dan Jeruk Nipis'],
      correctOptionIndex: 0,
      explanation: 'Pisang, mangga, dan alpukat dapat diperam matang setelah dipetik.',
    ),
    QuestionItem(
      id: 'agr_079',
      questionText: 'Contoh buah non-klimakterik yang tidak mengalami peningkatan respirasi dan tidak dapat diperam setelah dipetik adalah:',
      options: ['Jeruk, Anggur, dan Semangka', 'Pisang, Pepaya, dan Mangga', 'Tomat, Alpukat, dan Sawo', 'Durian, Nangka, dan Apel'],
      correctOptionIndex: 0,
      explanation: 'Buah non-klimakterik (seperti jeruk dan anggur) harus dipetik saat sudah matang pohon.',
    ),
    QuestionItem(
      id: 'agr_080',
      questionText: 'Penyebab kerusakan fisik benih akibat paparan suhu dingin penyimpanan yang tidak sesuai dinamakan:',
      options: ['Chilling Injury', 'Heat Stress', 'Sunburn', 'Drowning'],
      correctOptionIndex: 0,
      explanation: 'Chilling injury terjadi pada komoditas tropis saat disimpan pada suhu rendah tanpa pembekuan.',
    ),
    QuestionItem(
      id: 'agr_081',
      questionText: 'Sistem pertanian terpadu yang memadukan komoditas kehutanan (pohon kayu) dengan tanaman pertanian dinamakan:',
      options: ['Agroforestri', 'Permakultur', 'Silvopastura', 'Agrowisata'],
      correctOptionIndex: 0,
      explanation: 'Agroforestri memadukan pohon pepohonan hutan dengan tanaman pangan.',
    ),
    QuestionItem(
      id: 'agr_082',
      questionText: 'Integrasi antara tanaman kehutanan/pertanian dengan pemeliharaan hewan ternak dinamakan:',
      options: ['Silvopastura', 'Agrosilvopastura', 'Aquakultur', 'Agroforestri'],
      correctOptionIndex: 0,
      explanation: 'Silvopastura menggabungkan pepohonan kayu dengan rumput pakan ternak.',
    ),
    QuestionItem(
      id: 'agr_083',
      questionText: 'Bentuk lahan gambut yang kaya bahan organik tapi memiliki tingkat keasaman sangat tinggi dan miskin hara hara dinamakan:',
      options: ['Lahan Gambut / Sub-optimal', 'Lahan Aluvial', 'Lahan Latosol', 'Lahan Volkanik'],
      correctOptionIndex: 0,
      explanation: 'Lahan gambut membutuhkan pengelolaan tata air khusus dan penambahan pembenah tanah.',
    ),
    QuestionItem(
      id: 'agr_084',
      questionText: 'Tanah marginal masam yang mendominasi wilayah tropis basah dengan kandungan aluminium (Al) tinggi adalah:',
      options: ['Ultisol (Podsolik Merah Kuning)', 'Andosol', 'Mollisol', 'Vertisol'],
      correctOptionIndex: 0,
      explanation: 'Ultisol merupakan jenis tanah masam yang melapuk lanjut dengan keracunan Aluminium.',
    ),
    QuestionItem(
      id: 'agr_085',
      questionText: 'Tanah subur bertekstur gembur yang terbentuk dari material abu dan lapakan gunung berapi dinamakan:',
      options: ['Andosol', 'Histosol', 'Grumosol', 'Spodosol'],
      correctOptionIndex: 0,
      explanation: 'Andosol merupakan tanah volkanik dengan kandungan bahan organik dan kesuburan tinggi.',
    ),
    QuestionItem(
      id: 'agr_086',
      questionText: 'Tanah liat lempung lempung berat yang mudah mengembang saat basah dan meretak pecah saat kering dinamakan:',
      options: ['Vertisol (Grumosol)', 'Inceptisol', 'Oxisol', 'Entisol'],
      correctOptionIndex: 0,
      explanation: 'Vertisol tinggi kandungan lempung smektit yang mengembang-kerut ekstrem.',
    ),
    QuestionItem(
      id: 'agr_087',
      questionText: 'Proses penggaraman atau penumpukan garam terlarut berlebih pada tanah akibat irigasi buruk dinamakan:',
      options: ['Salinisasi', 'Alkalisasi', 'Erosi', 'Sedimentasi'],
      correctOptionIndex: 0,
      explanation: 'Salinisasi merusak daya serap akar akibat tingginya tekanan osmotik garam.',
    ),
    QuestionItem(
      id: 'agr_088',
      questionText: 'Organel sel tempat berabrakasi respirasi seluler penghasil energi ATP bagi sel tanaman adalah:',
      options: ['Mitokondria', 'Kloroplas', 'Lisosom', 'Golgi'],
      correctOptionIndex: 0,
      explanation: 'Mitokondria mengoksidasi glukosa menjadi energi ATP bagi metabolisme.',
    ),
    QuestionItem(
      id: 'agr_089',
      questionText: 'Alat ukur yang digunakan untuk mengetahui tingkat kemanisan (kadar gula terlarut °Brix) pada buah adalah:',
      options: ['Refraktometer', 'PH meter', 'Konduktivites meter (EC meter)', 'Anemometer'],
      correctOptionIndex: 0,
      explanation: 'Refraktometer mengukur indeks bias cairan untuk menentukan tingkat derajat Brix (gula).',
    ),
    QuestionItem(
      id: 'agr_090',
      questionText: 'Alat ukur yang digunakan untuk mengetahui kepekatan konsentrasi nutrisi larutan hidroponik dinamakan:',
      options: ['EC Meter (Electrical Conductivity Meter)', 'Lux Meter', 'Soil Tester', 'Hygrometer'],
      correctOptionIndex: 0,
      explanation: 'EC Meter mengukur daya hantar listrik larutan nutrisi hidroponik (mS/cm).',
    ),
    QuestionItem(
      id: 'agr_091',
      questionText: 'Bioteknologi tanah berupa arang hayati pembakar lambat tanpa oksigen (pirolisis) untuk pembenah media tanah dinamakan:',
      options: ['Biochar', 'Biopori', 'Biogas', 'Biodiesel'],
      correctOptionIndex: 0,
      explanation: 'Biochar adalah arang hayati terikat karboksil tinggi untuk perbaikan tanah.',
    ),
    QuestionItem(
      id: 'agr_092',
      questionText: 'Lubang resapan buatan vertikal di dalam tanah untuk menampung air hujan dan pembuatan kompos dinamakan:',
      options: ['Lubang Biopori', 'Sumur Resapan', 'Drainase Lahan', 'Parit Kontur'],
      correctOptionIndex: 0,
      explanation: 'Biopori mengoptimalkan resapan air tanah dan aktivitas organisme tanah.',
    ),
    QuestionItem(
      id: 'agr_093',
      questionText: 'Penyakit tanaman padi akibat virus yang ditularkan oleh wereng hijau dan membuat tanaman kerdil dinamakan:',
      options: ['Penyakit Tungro', 'Penyakit Blas', 'Hwarang', 'Kresek'],
      correctOptionIndex: 0,
      explanation: 'Tungro adalah penyakit virus kerdil padi vektor wereng hijau (Nephotettix virescens).',
    ),
    QuestionItem(
      id: 'agr_094',
      questionText: 'Penyakit patah leher dan bercak belah ketupat pada daun padi yang disebabkan cendawan Pyricularia oryzae dinamakan:',
      options: ['Penyakit Blas (Blast)', 'Tungro', 'Layu Baku', 'Bercak Cokelat'],
      correctOptionIndex: 0,
      explanation: 'Blas (Pyricularia oryzae) merusak daun dan leher malai padi.',
    ),
    QuestionItem(
      id: 'agr_095',
      questionText: 'Gulma air invasif yang berkembang cepat menutup permukaan danau/waduk serta mempercepat pendangkalan adalah:',
      options: ['Eceng Gondok (Eichhornia crassipes)', 'Rumput Teki', 'Alang-alang', 'Babadotan'],
      correctOptionIndex: 0,
      explanation: 'Eceng gondok adalah gulma perairan invasif berdaya reproduksi tinggi.',
    ),
    QuestionItem(
      id: 'agr_096',
      questionText: 'Gulma darat menjengkelkan berimpang umbi dalam tanah yang sangat tahan herbisida kontak adalah:',
      options: ['Rumput Teki (Cyperus rotundus)', 'Bayam Duri', 'Krokot', 'Alang-alang'],
      correctOptionIndex: 0,
      explanation: 'Rumput teki memiliki umbi dorman di dalam tanah yang sulit dibasmi.',
    ),
    QuestionItem(
      id: 'agr_097',
      questionText: 'Pengolahan tanah minimum tanpa merusak struktur asli tanah untuk mencegah erosi dinamakan:',
      options: ['Minimum Tillage / No-Tillage (Tanpa Olah Tanah)', 'Maximum Tillage', 'Ploughing', 'Subsoiling'],
      correctOptionIndex: 0,
      explanation: 'No-Tillage menanam langsung tanpa mengganggu lapisan tanah bawah.',
    ),
    QuestionItem(
      id: 'agr_098',
      questionText: 'Biji komoditas pertanian yang dikembangkan khusus sebagai bahan tanam bersertifikat dinamakan:',
      options: ['Benih', 'Bibit', 'Hasil Panen', 'Gabah'],
      correctOptionIndex: 0,
      explanation: 'Benih adalah biji struktural untuk bahan tanam reproduksi vegetatif/generatif.',
    ),
    QuestionItem(
      id: 'agr_099',
      questionText: 'Tanaman muda hasil perkecambahan benih yang siap ditanam di lapangan dinamakan:',
      options: ['Bibit', 'Benih', 'Eksplan', 'Kalus'],
      correctOptionIndex: 0,
      explanation: 'Bibit adalah calon tanaman muda yang telah tumbuh akar dan daun awal.',
    ),
    QuestionItem(
      id: 'agr_100',
      questionText: 'Cabang ilmu pengetahuan dan teknologi yang menerapkan prinsip sains biologi dalam budidaya tanaman dan pengelolaan lahan dinamakan:',
      options: ['Agroteknologi', 'Agribisnis', 'Teknologi Pangan', 'Teknik Pertanian'],
      correctOptionIndex: 0,
      explanation: 'Agroteknologi memadukan agronomi, pemuliaan, proteksi, dan ilmu tanah modern.',
    ),
  ];
}
