// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/ajak_bermain_ke_taman/ajak_bermain_ke_taman_dialog_npc.dart
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class AjakBermainKeTamanDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat diajak bermain ke taman berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Waaah! ( * $npcName menunjuk-nunjuk rumput hijau dan pepohonan di taman sambil tersenyum lebar * ) 🌳👶',
        'Bababa! ( * $npcName mencerabut bunga rumput kecil lalu menunjukkannya kepada $parentName * )',
        'Gigaaa! ( * $npcName merangkak riang di atas rumput empuk taman kota * )',
        'Ooooh! ( * $npcName menatap burung kupu-kupu yang terbang di sekitar taman dengan mata berbinar * )',
        'Hehehe! ( * $npcName tertawa gembira saat didorong di ayunan anak bayi oleh $parentName * )',
        'Nyaaa! ( * $npcName meraba tekstur dedaunan gugur di tanah taman * )',
        'Abuuu... ( * $npcName meluncur pelan di perosotan mini sambil dipegangi erat oleh $parentName * )',
        'Mammm! ( * $npcName mencoba memegang bunga warna-warni di tepi jalan taman * )',
        'Dayaya! ( * $npcName mendengarkan suara gemericik air mancur taman dengan takjub * )',
        'Tetete! ( * $npcName menepuk-nepuk angin segar taman sambil diikat di stroller * )',
        'Kicukicu! ( * $npcName mengarahkan tangan kecilnya ke burung merpati yang terbang * )',
        'Ehhhe! ( * $npcName tertawa ngakak saat $parentName mengajaknya main sembunyi-sembunyi di balik pohon * )',
        'Agiii! ( * $npcName memegang kencang tangan $parentName saat belajar berjalan di rumput * )',
        'Owooo! ( * $npcName melihat anak-anak lain berlarian dan ikut mengoceh riang * )',
        'Bubu! ( * $npcName menguap nyaman karena hembusan angin segar taman * )',
        'Lalala! ( * $npcName menari-nari kecil saat mendengar musik taman kota * )',
        'Hummm! ( * $npcName menyandarkan badannya ke dada $parentName sambil menikmati pemandangan * )',
        'Cicu! ( * $npcName menyodorkan daun bersih yang dipetiknya ke arah $parentName * )',
        'Nyaa-ha! ( * $npcName mengejar balon sabun yang melayang di udara taman * )',
        'Paapapa! ( * $npcName menepuk-nepuk bahu $parentName saat digendong mengelilingi taman * )',
        'Glooogloo! ( * $npcName bermain pasir halus di area bermain anak * )',
        'Oowgh! ( * $npcName tertidur nyenyak di stroller setelah capek main di taman * )',
        'Yaaaya! ( * $npcName tersenyum ceria menikmati matahari pagi di taman * )',
        'Wiii! ( * $npcName digendong tinggi-tinggi oleh $parentName seolah terbang di udara taman * )',
        'Tatatata! ( * $npcName memeluk leher $parentName erat-erat dengan gembira * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Horeeee! Ke taman! Aku mau main ayunan sama perosotan kenceng-kenceng $parentName! 🛝🌳✨',
        'Yeay! $parentName ayo balapan lari di rumput taman! Siapa yang menang dapat es krim!',
        'Makasih $parentName udah ajak aku ke taman! Lihat ada kupu-kupu warna-warni!',
        'Wah, banyak mainan seru di taman! Ayo $parentName dorong ayunanku tinggi-tinggi!',
        'Asyik! Aku mau main pasir taman sama bikin istana megah bareng $parentName!',
        'Makasih $parentName! Udara di taman seger banget ya, aku senang banget!',
        'Hore! Aku mau sapa teman-teman baru di taman dulu ya $parentName!',
        'Waaah, perosotannya tinggi banget! Tapi aku berani kalau ada $parentName yang jaga!',
        'Makasih $parentName! Nanti kita makan bekal camilan di bangku taman ya!',
        'Yeaaay! $parentName emang paling jago bikin hari libur aku jadi seru!',
        'Makasih banyak $parentName! Aku mau mengejar gelembung sabun di dekat air mancur!',
        'Asyik! Ayo kita jalan-jalan di jalan setapak taman sambil pegangan tangan!',
        'Makasih $parentName! Lihat, aku bisa main jungkat-jungkit sama anak lain!',
        'Uwah, ada kolam ikan di taman! Ayo kita beri makan ikan-ikannya $parentName!',
        'Yippie! Main di taman sama $parentName selalu jadi momen favoritku!',
        'Makasih $parentName! Sini aku petik bunga liar yang cantik ini buat $parentName!',
        'Hore! Aku mau naik jembatan kayu kecil di taman itu $parentName!',
        'Waaah! Angin tamannya bikin ketawa terus deh! Makasih ya $parentName!',
        'Makasih $parentName! Nanti sebelum pulang kita foto-foto bareng di bawah pohon ya!',
        'Yeay! Taman ini bagus banget! Nanti esok hari ajak aku ke sini lagi ya $parentName!',
        'Makasih banyak $parentName! Pelukan hangat di taman rasanya double hangatnya!',
        'Uwah, aku capek berlarian tapi rasanya seneng banget! Makasih $parentName!',
        'Makasih $parentName! Aku janji nggak bakal lari jauh-jauh dari pengawasan $parentName!',
        'Hore, makasih $parentName! Hari main ke taman ini super duper menyenangkan!',
      ];
    } else if (childAge <= 11) {
      return [
        'Wah! Makasih banyak ya $parentName udah ajak aku jalan-jalan dan olahraga di taman! 🏃‍♂️🌳✨',
        'Terima kasih $parentName! Bermain di taman bener-bener refreshing banget habis seminggu sekolah.',
        'Asyik! Terima kasih $parentName! Nanti kita bisa main sepeda atau lempar tangkap bola di rumput!',
        'Alhamdulillah, terima kasih banyak $parentName! Piknik sederhana di taman ini rasanya mewah sekali.',
        'Waaah! Udara segar taman kota beneran bikin pikiran jadi tenang dan sehat! Terima kasih $parentName!',
        'Makasih $parentName! Aku senang banget bisa piknik dan makan bekal bersama $parentName di sini.',
        'Terima kasih $parentName! Bermain bersama $parentName di alam terbuka gini seru banget.',
        'Hore! Terima kasih $parentName! Aku bisa latihan sepatu roda / main layangan di taman ini!',
        'Wah, makasih ya $parentName! Taman ini fasilitasnya lengkap dan tempatnya asri banget.',
        'Terima kasih $parentName! Momen jalan santai sore di taman bareng $parentName beneran berharga.',
        'Makasih banyak $parentName! Sayang $parentName banget!',
        'Asyik! Terima kasih $parentName! Foto-foto kebersamaan kita di taman hasilnya bagus banget.',
        'Terima kasih $parentName! Nanti kita duduk-duduk di rumput sambil bincang-bincang santai ya.',
        'Makasih $parentName! Rasanya semua jenuh dan lelah belajar langsung sirna di taman ini.',
        'Wah, senangnya! Terima kasih $parentName sudah selalu meluangkan waktu berharga buat aku.',
        'Terima kasih $parentName! Taman ini jadi lokasi favorit kita berdua mulai sekarang.',
        'Alhamdulillah, makasih $parentName! Melihat pemandangan hijau bikin mata jadi segar kembali.',
        'Terima kasih banyak $parentName! Nanti kalau ada waktu luang ajak aku ke sini lagi ya!',
        'Makasih $parentName! Aku bahagia banget bisa menikmati sore yang indah ini bersama orang tua terbaik.',
        'Wah makasih $parentName! Ayo kita kelilingi taman ini sampai ujung sana!',
        'Terima kasih $parentName! Semoga kebersamaan dan kesehatan selalu menyertai keluarga kita.',
        'Asyik! Makasih $parentName! Aku bisa menyapa tetangga dan teman-teman yang juga di taman.',
        'Terima kasih banyak $parentName! Senang banget punya orang tua yang penuh perhatian.',
        'Makasih $parentName! Senyum bahagia orang tua di bawah rindangnya pohon taman bikin hatiku adem!',
        'Terima kasih $parentName! Ayo kita nikmati es krim taman sebelum pulang!',
      ];
    } else {
      return [
        'Wah, terima kasih banyak ya $parentName! Jalan-jalan dan santai di taman ini beneran merilekskan jiwa. 🍃🌳✨',
        'Alhamdulillah, terima kasih $parentName. Di tengah rutinitas yang padat, piknik di taman ini jadi oasis tersendiri.',
        'Terima kasih $parentName! Menikmati hembusan angin dan pemandangan hijau bersama $parentName rasanya sangat menenangkan.',
        'Wah, terima kasih banyak $parentName! Momen kumpul dan ngobrol santai di taman ini sungguh berharga.',
        'Terima kasih $parentName atas inisiatif diajak ke taman. Ini cara terbaik untuk recharge energi positif.',
        'Makasih ya $parentName! $parentName selalu tahu cara bikin momen sederhana jadi terasa hangat dan bermakna.',
        'Terima kasih banyak $parentName! Tempatnya sangat asri dan pas banget buat jogging atau jalan sehat bersama.',
        'Alhamdulillah, terima kasih $parentName! Kebahagiaan menikmati alam terbuka bersama orang tua tak ada tandingannya.',
        'Terima kasih $parentName. Saya sangat menikmati percakapan mendalam kita selama mengelilingi taman ini.',
        'Wah, terima kasih $parentName! Ini benar-benar healing yang menyenangkan tanpa perlu jauh-jauh keluar kota.',
        'Terima kasih banyak $parentName. Kehangatan ikatan keluarga kita makin terasa erat di tempat selaras ini.',
        'Makasih ya $parentName! Foto-foto kebersamaan kita di taman ini bakal saya simpan baik-baik sebagai kenangan indah.',
        'Terima kasih $parentName! Berjalan di bawah rindangnya pepohonan mengingatkan saya pada masa kecil dulu.',
        'Alhamdulillah, makasih $parentName! Rasa syukur saya tak terhingga punya orang tua sehangat ini.',
        'Terima kasih banyak $parentName! Semoga kesehatan dan kedamaian selalu menyertai $parentName.',
        'Wah, terima kasih $parentName! Saya jadi bisa menghirup udara segar dan melepas beban pikiran pekerjaan/studi.',
        'Terima kasih $parentName atas waktu dan kebersamaan ini. Saya bangga menjadi anak $parentName.',
        'Makasih $parentName! Piknik dan menikmati bekal di taman ini sungguh nikmat dan mengesankan.',
        'Terima kasih banyak $parentName. Setiap detik yang dihabiskan bersama $parentName adalah anugerah indah.',
        'Alhamdulillah, makasih $parentName! Suasana taman yang tenang membuat komunikasi kita makin lancar.',
        'Terima kasih $parentName! Semoga Allah/Tuhan selalu melimpahkan kebahagiaan untuk keluarga kita.',
        'Wah, makasih banyak $parentName! Ini menambah energi positif untuk menghadapi tantangan hari esok.',
        'Terima kasih $parentName! Momen jalan sore di taman ini akan menjadi salah satu kenangan manis favorit saya.',
        'Makasih ya $parentName... Kasih sayang dan perhatian orang tua memang tiada tandingannya.',
        'Terima kasih $parentName! I love you so much $parentName!',
      ];
    }
  }
}
