import '../tes_seleksi_model.dart';

List<QuestionItem> getAkuntansiQuestions() {
  return const [
    QuestionItem(
      id: 'akt_001',
      questionText: 'Persamaan Dasar Akuntansi yang selalu seimbang dinyatakan dengan rumus:',
      options: ['Aset = Liabilitas + Ekuitas', 'Aset = Liabilitas - Ekuitas', 'Ekuitas = Aset + Liabilitas', 'Liabilitas = Aset + Ekuitas'],
      correctOptionIndex: 0,
      explanation: 'Persamaan dasar akuntansi: Aset (Harta) = Liabilitas (Utang) + Ekuitas (Modal).',
    ),
    QuestionItem(
      id: 'akt_002',
      questionText: 'Prinsip pencatatan berpasangan (Double-Entry System) menyatakan bahwa setiap transaksi akan mempengaruhi minimal:',
      options: ['Dua Akun (Debit dan Kredit dalam nilai seimbang)', 'Satu Akun saja', 'Tiga Akun sekaligus', 'Hanya akun Kas'],
      correctOptionIndex: 0,
      explanation: 'Double-entry mensyaratkan keseimbangan total Debit dan Kredit.',
    ),
    QuestionItem(
      id: 'akt_003',
      questionText: 'Sisi sebelah KIRI dalam buku besar akuntansi dinamakan sisi:',
      options: ['Debit', 'Kredit', 'Saldo', 'Neraca'],
      correctOptionIndex: 0,
      explanation: 'Posisi sebelah kiri adalah Debit, sedangkan posisi kanan adalah Kredit.',
    ),
    QuestionItem(
      id: 'akt_004',
      questionText: 'Saldo normal untuk kelompok akun Aset dan Beban terletak pada sisi:',
      options: ['Debit', 'Kredit', 'Nol', 'Dua-duanya'],
      correctOptionIndex: 0,
      explanation: 'Aset dan Beban bertambah di sisi Debit dan berkurang di Kredit.',
    ),
    QuestionItem(
      id: 'akt_005',
      questionText: 'Saldo normal untuk kelompok akun Liabilitas, Ekuitas, dan Pendapatan terletak pada sisi:',
      options: ['Kredit', 'Debit', 'Campuran', 'Penyesuaian'],
      correctOptionIndex: 0,
      explanation: 'Liabilitas, Ekuitas, dan Pendapatan bertambah di sisi Kredit.',
    ),
    QuestionItem(
      id: 'akt_006',
      questionText: 'Pencatatan transaksi penerimaan kas dari pelunasan piutang usaha akan dicatat pada jurnal:',
      options: ['Kas di Debit dan Piutang Usaha di Kredit', 'Piutang Usaha di Debit dan Kas di Kredit', 'Kas di Debit dan Pendapatan di Kredit', 'Utang di Debit dan Kas di Kredit'],
      correctOptionIndex: 0,
      explanation: 'Penerimaan piutang menambah Kas (Debit) dan mengurangi Piutang Usaha (Kredit).',
    ),
    QuestionItem(
      id: 'akt_007',
      questionText: 'Laporan keuangan yang menyajikan pendapatan dan beban perusahaan selama satu periode tertentu dinamakan:',
      options: ['Laporan Laba Rugi (Income Statement)', 'Neraca (Balance Sheet)', 'Laporan Arus Kas', 'Laporan Perubahan Ekuitas'],
      correctOptionIndex: 0,
      explanation: 'Laporan Laba Rugi mengukur kinerja keuangan bersih (Pendapatan - Beban).',
    ),
    QuestionItem(
      id: 'akt_008',
      questionText: 'Laporan keuangan yang menggambarkan posisi Aset, Liabilitas, dan Ekuitas pada tanggal tertentu dinamakan:',
      options: ['Neraca (Balance Sheet / Laporan Posisi Keuangan)', 'Laporan Laba Rugi', 'Laporan Arus Kas', 'Catatan atas Laporan Keuangan'],
      correctOptionIndex: 0,
      explanation: 'Neraca menyajikan posisi saldo aset, utang, dan modal pada satu titik waktu.',
    ),
    QuestionItem(
      id: 'akt_009',
      questionText: 'Laporan arus kas membagi aliran kas masuk dan keluar ke dalam 3 aktivitas yaitu:',
      options: ['Operasi, Investasi, dan Pendanaan (Financing)', 'Penjualan, Pembelian, dan Gaji', 'Debit, Kredit, dan Saldo', 'Lancar, Tetap, dan Kontinjensi'],
      correctOptionIndex: 0,
      explanation: 'Laporan Arus Kas memilah aliran kas Operasi, Investasi, dan Pendanaan.',
    ),
    QuestionItem(
      id: 'akt_010',
      questionText: 'Pencatatan pendapatan saat hak timbul dan beban saat terjadi tanpa menunggu kas diterima/dibayar dinamakan basis:',
      options: ['Accrual Basis (Basis Akrual)', 'Cash Basis (Basis Kas)', 'Modified Basis', 'Tax Basis'],
      correctOptionIndex: 0,
      explanation: 'Basis akrual mengakui pendapatan dan beban saat transaksi terjadi.',
    ),
    QuestionItem(
      id: 'akt_011',
      questionText: 'Pencatatan transaksi yang hanya dilakukan saat arus kas riil diterima atau dikeluarkan dinamakan basis:',
      options: ['Cash Basis (Basis Kas)', 'Accrual Basis', 'Fair Value Basis', 'Historical Cost'],
      correctOptionIndex: 0,
      explanation: 'Basis kas mencatat pendapatan saat kas masuk dan beban saat kas keluar.',
    ),
    QuestionItem(
      id: 'akt_012',
      questionText: 'Jurnal yang dibuat pada akhir periode untuk menyesuaikan saldo akun agar mencerminkan kondisi sebenarnya dinamakan:',
      options: ['Jurnal Penyesuaian (Adjusting Journal Entry)', 'Jurnal Penutup', 'Jurnal Pembalik', 'Jurnal Umum'],
      correctOptionIndex: 0,
      explanation: 'Jurnal penyesuaian mengalokasikan pendapatan/beban terhimpun.',
    ),
    QuestionItem(
      id: 'akt_013',
      questionText: 'Jurnal yang dibuat pada akhir periode untuk mengosongkan saldo akun-akun nominal (sementara) dinamakan:',
      options: ['Jurnal Penutup (Closing Entry)', 'Jurnal Penyesuaian', 'Jurnal Pembalik', 'Jurnal Khusus'],
      correctOptionIndex: 0,
      explanation: 'Jurnal penutup mengaitkan akun nominal Pendapatan, Beban, dan Prive ke Laba Ditahan.',
    ),
    QuestionItem(
      id: 'akt_014',
      questionText: 'Akun-akun yang saldo akhirnya ditutup menjadi nol pada akhir periode akuntansi dinamakan akun:',
      options: ['Nominal / Sementara (Pendapatan & Beban)', 'Riil / Permanen (Aset, Utang, Modal)', 'Kontra', 'Persediaan'],
      correctOptionIndex: 0,
      explanation: 'Akun nominal (Laba rugi) ditutup per akhir periode.',
    ),
    QuestionItem(
      id: 'akt_015',
      questionText: 'Akun-akun yang saldonya berlanjut dibawa ke periode berikutnya dinamakan akun:',
      options: ['Riil / Permanen (Aset, Liabilitas, Ekuitas)', 'Nominal', 'Sementara', 'Penyesuaian'],
      correctOptionIndex: 0,
      explanation: 'Akun riil tercantum di Neraca dan tidak ditutup.',
    ),
    QuestionItem(
      id: 'akt_016',
      questionText: 'Metode penilaian persediaan yang mengasumsikan barang yang pertama masuk adalah barang yang pertama keluar dinamakan:',
      options: ['FIFO (First-In, First-Out)', 'LIFO (Last-In, First-Out)', 'Rata-Rata Tertimbang (Weighted Average)', 'Identifikasi Khusus'],
      correctOptionIndex: 0,
      explanation: 'FIFO menjual barang stok terlama terlebih dahulu.',
    ),
    QuestionItem(
      id: 'akt_017',
      questionText: 'Metode penilaian persediaan barang di mana biaya rata-rata per unit dihitung setiap ada pembelian barang baru dinamakan:',
      options: ['Rata-Rata Bergerak / Tertimbang (Average Method)', 'FIFO', 'LIFO', 'Standard Cost'],
      correctOptionIndex: 0,
      explanation: 'Metode Rata-Rata membagi total biaya persediaan dengan jumlah unit tersedia.',
    ),
    QuestionItem(
      id: 'akt_018',
      questionText: 'Alokasi sistematis jumlah terdepresiasi dari aset tetap selama masa manfaatnya dinamakan:',
      options: ['Penyusutan / Depresiasi', 'Amortisasi', 'Deplesi', 'Impairment'],
      correctOptionIndex: 0,
      explanation: 'Depresiasi mengalokasikan harga perolehan aset tetap berwujud.',
    ),
    QuestionItem(
      id: 'akt_019',
      questionText: 'Alokasi sistematis pembebanan harga perolehan Aset Takberwujud (seperti Hak Paten atau Hak Cipta) dinamakan:',
      options: ['Amortisasi', 'Depresiasi', 'Deplesi', 'Revaluasi'],
      correctOptionIndex: 0,
      explanation: 'Amortisasi adalah penyusutan aset takberwujud.',
    ),
    QuestionItem(
      id: 'akt_020',
      questionText: 'Alokasi pembebanan berkurangnya nilai sumber daya alam (seperti tambang minyak atau kayu hutan) dinamakan:',
      options: ['Deplesi', 'Depresiasi', 'Amortisasi', 'Akresi'],
      correctOptionIndex: 0,
      explanation: 'Deplesi mengukur penyusutan nilai ekonomis hasil alam.',
    ),
    QuestionItem(
      id: 'akt_021',
      questionText: 'Metode depresiasi yang menghasilkan beban penyusutan bernilai sama konstan setiap tahunnya dinamakan:',
      options: ['Metode Garis Lurus (Straight-Line Method)', 'Metode Saldo Menurun Berganda', 'Metode Jumlah Angka Tahun', 'Metode Satuan Hasil'],
      correctOptionIndex: 0,
      explanation: 'Garis Lurus: (Harga Perolehan - Nilai Residu) / Masa Manfaat.',
    ),
    QuestionItem(
      id: 'akt_022',
      questionText: 'Metode depresiasi dipercepat yang membebankan depresiasi lebih besar pada tahun-tahun awal dinamakan:',
      options: ['Metode Saldo Menurun (Declining Balance Method)', 'Metode Garis Lurus', 'Metode Unit Produksi', 'Metode Jam Kerja'],
      correctOptionIndex: 0,
      explanation: 'Saldo Menurun membebankan depresiasi tinggi di awal masa manfaat.',
    ),
    QuestionItem(
      id: 'akt_023',
      questionText: 'Aset yang diperkirakan dapat dicairkan menjadi kas atau dikonsumsi dalam waktu kurang dari 1 tahun dinamakan:',
      options: ['Aset Lancar (Current Assets)', 'Aset Tetap', 'Aset Takberwujud', 'Aset Lain-lain'],
      correctOptionIndex: 0,
      explanation: 'Aset lancar mencakup Kas, Piutang, Persediaan, dan Beban Dibayar Dimuka.',
    ),
    QuestionItem(
      id: 'akt_024',
      questionText: 'Manakah di bawah ini yang BUKAN merupakan komponen Aset Lancar?',
      options: ['Gedung dan Mesin Pabrik', 'Kas dan Setara Kas', 'Piutang Usaha', 'Persediaan Barang Dagang'],
      correctOptionIndex: 0,
      explanation: 'Gedung dan Mesin tergolong Aset Tetap (Non-Lancar).',
    ),
    QuestionItem(
      id: 'akt_025',
      questionText: 'Kewajiban utang perusahaan yang harus dilunasi dalam jangka waktu kurang dari 1 tahun dinamakan:',
      options: ['Liabilitas Jangka Pendek (Current Liabilities)', 'Liabilitas Jangka Panjang', 'Ekuitas', 'Obligasi'],
      correctOptionIndex: 0,
      explanation: 'Utang jangka pendek harus dilunasi dalam siklus operasi normal (<1 tahun).',
    ),
    QuestionItem(
      id: 'akt_026',
      questionText: 'Surat utang jangka panjang yang diterbitkan perusahaan untuk memperoleh pinjaman modal dinamakan:',
      options: ['Obligasi (Bonds Payable)', 'Saham Biasa', 'Wesel Bayar Jangka Pendek', 'Kredit Usaha'],
      correctOptionIndex: 0,
      explanation: 'Obligasi adalah instrumen utang jangka panjang berjangka waktu tertentu.',
    ),
    QuestionItem(
      id: 'akt_027',
      questionText: 'Nilai nominal tercantum pada lembar obligasi yang harus dibayar saat jatuh tempo dinamakan:',
      options: ['Nilai Pari / Nilai Nominal (Face Value)', 'Nilai Pasar', 'Harga Kurs', 'Diskon'],
      correctOptionIndex: 0,
      explanation: 'Nilai Pari (Par Value) adalah jumlah pokok obligasi.',
    ),
    QuestionItem(
      id: 'akt_028',
      questionText: 'Kondisi di mana obligasi dijual di atas nilai nominalnya dinamakan dijual secara:',
      options: ['Premium (Agio Obligasi)', 'Diskon (Disagio Obligasi)', 'At Par', 'Rugi'],
      correctOptionIndex: 0,
      explanation: 'Premium terjadi bila harga jual > nilai nominal (karena suku bunga pasar < suku bunga kupon).',
    ),
    QuestionItem(
      id: 'akt_029',
      questionText: 'Kondisi di mana obligasi dijual di bawah nilai nominalnya dinamakan dijual secara:',
      options: ['Diskon (Disagio Obligasi)', 'Premium', 'At Par', 'Gain'],
      correctOptionIndex: 0,
      explanation: 'Diskon terjadi saat harga jual < nilai nominal obligasi.',
    ),
    QuestionItem(
      id: 'akt_030',
      questionText: 'Pengambilan uang tunai atau aset perusahaan oleh pemilik untuk kepentingan pribadi dinamakan:',
      options: ['Prive (Drawings)', 'Dividen', 'Beban Gaji', 'Investasi'],
      correctOptionIndex: 0,
      explanation: 'Prive mengurangi saldo ekuitas pemilik pada perusahaan perorangan.',
    ),
    QuestionItem(
      id: 'akt_031',
      questionText: 'Pembagian laba bersih perusahaan berbentuk perseroan (PT) kepada para pemegang saham dinamakan:',
      options: ['Dividen', 'Prive', 'Capital Gain', 'Royalti'],
      correctOptionIndex: 0,
      explanation: 'Dividen disetujui RUPS untuk dibagikan ke pemegang saham.',
    ),
    QuestionItem(
      id: 'akt_032',
      questionText: 'Akumulasi laba bersih perusahaan yang tidak dibagikan sebagai dividen tetapi ditahan untuk investasi ulang dinamakan:',
      options: ['Laba Ditahan (Retained Earnings)', 'Modal Disetor', 'Agio Saham', 'Cadangan Umum'],
      correctOptionIndex: 0,
      explanation: 'Retained Earnings menampung akumulasi laba bersih yang ditahan.',
    ),
    QuestionItem(
      id: 'akt_033',
      questionText: 'Saham milik sendiri yang dibeli kembali oleh perusahaan dari pasar modal dinamakan:',
      options: ['Saham Tresuri (Treasury Stock)', 'Saham Preferen', 'Saham Biasa', 'Saham Bonus'],
      correctOptionIndex: 0,
      explanation: 'Treasury Stock mengurangi total ekuitas pemegang saham.',
    ),
    QuestionItem(
      id: 'akt_034',
      questionText: 'Saham yang memiliki hak istimewa menerima dividen terlebih dahulu dibanding saham biasa dinamakan:',
      options: ['Saham Preferen (Preferred Stock)', 'Saham Biasa', 'Saham Tresuri', 'Saham Pendiri'],
      correctOptionIndex: 0,
      explanation: 'Saham preferen diprioritaskan dalam pembagian dividen dan likuidasi.',
    ),
    QuestionItem(
      id: 'akt_035',
      questionText: 'Rumus untuk menghitung Harga Pokok Penjualan (HPP) perusahaan dagang adalah:',
      options: ['Persediaan Awal + Pembelian Bersih - Persediaan Akhir', 'Penjualan - Laba Bersih', 'Pembelian + Persediaan Akhir', 'Persediaan Awal + Penjualan'],
      correctOptionIndex: 0,
      explanation: 'HPP = Persediaan Awal + Pembelian Bersih - Persediaan Akhir.',
    ),
    QuestionItem(
      id: 'akt_036',
      questionText: 'Selisih antara Penjualan Bersih dengan Harga Pokok Penjualan (HPP) dinamakan:',
      options: ['Laba Kotor (Gross Profit)', 'Laba Bersih', 'Laba Operasional', 'EBIT'],
      correctOptionIndex: 0,
      explanation: 'Laba Kotor = Penjualan - HPP.',
    ),
    QuestionItem(
      id: 'akt_037',
      questionText: 'Laba yang diperoleh setelah Laba Kotor dikurangi Beban-Beban Operasional dinamakan:',
      options: ['Laba Operasional (Operating Profit / EBIT)', 'Laba Kotor', 'Laba Bersih', 'EBT'],
      correctOptionIndex: 0,
      explanation: 'Laba Operasional = Laba Kotor - Beban Usaha/Operasional.',
    ),
    QuestionItem(
      id: 'akt_038',
      questionText: 'Hasil akhir Laba Operasional dikurangi beban bunga dan pajak dinamakan:',
      options: ['Laba Bersih (Net Income)', 'Laba Kotor', 'EBITDA', 'Laba Ditahan'],
      correctOptionIndex: 0,
      explanation: 'Laba Bersih (Net Profit) adalah hasil akhir kinerja bottom line.',
    ),
    QuestionItem(
      id: 'akt_039',
      questionText: 'Tiga komponen utama Biaya Produksi perusahaan manufaktur adalah:',
      options: ['Biaya Bahan Baku Langsung, Biaya Tenaga Kerja Langsung, dan Biaya Overhead Pabrik (BOP)', 'Biaya Gaji, Biaya Sewa, Biaya Iklan', 'Biaya Tetap, Biaya Variabel, Biaya Semivariabel', 'Bahan Baku, Penjualan, Administrasi'],
      correctOptionIndex: 0,
      explanation: 'Biaya Manufaktur = Raw Material + Direct Labor + Factory Overhead (BOP).',
    ),
    QuestionItem(
      id: 'akt_040',
      questionText: 'Penggabungan Biaya Bahan Baku Langsung dan Biaya Tenaga Kerja Langsung dinamakan:',
      options: ['Biaya Utama (Prime Cost)', 'Biaya Konversi', 'Biaya Overhead', 'Biaya Periode'],
      correctOptionIndex: 0,
      explanation: 'Prime Cost = Bahan Baku Langsung + Tenaga Kerja Langsung.',
    ),
    QuestionItem(
      id: 'akt_041',
      questionText: 'Penggabungan Biaya Tenaga Kerja Langsung dan Biaya Overhead Pabrik dinamakan:',
      options: ['Biaya Konversi (Conversion Cost)', 'Biaya Utama', 'Biaya Produk', 'Biaya Standar'],
      correctOptionIndex: 0,
      explanation: 'Conversion Cost menguba bahan mentah menjadi barang jadi.',
    ),
    QuestionItem(
      id: 'akt_042',
      questionText: 'Metode kalkulasi harga pokok produk di mana seluruh biaya produksi (tetap dan variabel) dimasukkan dinamakan:',
      options: ['Full Costing (Absorption Costing)', 'Variable Costing', 'Activity-Based Costing', 'Direct Costing'],
      correctOptionIndex: 0,
      explanation: 'Full Costing membebankan seluruh BOP tetap dan variabel ke HPP.',
    ),
    QuestionItem(
      id: 'akt_043',
      questionText: 'Metode kalkulasi harga pokok yang HANYA membebankan biaya produksi variabel ke dalam HPP dinamakan:',
      options: ['Variable Costing (Direct Costing)', 'Full Costing', 'Marginal Costing', 'Target Costing'],
      correctOptionIndex: 0,
      explanation: 'Variable Costing memperlakukan BOP tetap sebagai biaya periode (period cost).',
    ),
    QuestionItem(
      id: 'akt_044',
      questionText: 'Sistem akuntansi biaya yang mengalokasikan biaya overhead berdasarkan aktivitas pencetus biaya (cost driver) dinamakan:',
      options: ['ABC System (Activity-Based Costing)', 'Job Order Costing', 'Process Costing', 'Standard Costing'],
      correctOptionIndex: 0,
      explanation: 'ABC menelusuri overhead ke pemicu biaya aktivitas secara akurat.',
    ),
    QuestionItem(
      id: 'akt_045',
      questionText: 'Sistem pengumpulan biaya produksi yang digunakan perusahaan dengan produk pesanan unik spesifik dinamakan:',
      options: ['Job Order Costing (Harga Pokok Pesanan)', 'Process Costing', 'ABC Costing', 'Batch Costing'],
      correctOptionIndex: 0,
      explanation: 'Job Order Costing menghitung biaya per pesanan unik (seperti percetakan/konstruksi).',
    ),
    QuestionItem(
      id: 'akt_046',
      questionText: 'Sistem pengumpulan biaya produksi masal yang kontinyu homogen (seperti pabrik semen) dinamakan:',
      options: ['Process Costing (Harga Pokok Proses)', 'Job Order Costing', 'Target Costing', 'Life Cycle Costing'],
      correctOptionIndex: 0,
      explanation: 'Process Costing menghitung biaya rata-rata per satuan unit homogen masal.',
    ),
    QuestionItem(
      id: 'akt_047',
      questionText: 'Pemeriksaan independen atas Laporan Keuangan oleh Akuntan Publik dinamakan proses:',
      options: ['Auditing (Pemeriksaan Akuntansi)', 'Bookkeeping', 'Financial Planning', 'Tax Planning'],
      correctOptionIndex: 0,
      explanation: 'Auditing memberikan keyakinan memadai atas keandalan laporan keuangan.',
    ),
    QuestionItem(
      id: 'akt_048',
      questionText: 'Opini auditor terbaik yang menyatakan laporan keuangan disajikan secara wajar dalam semua hal yang material adalah:',
      options: ['Opini Wajar Tanpa Pengecualian (Unqualified Opinion)', 'Opini Wajar dengan Pengecualian (Qualified)', 'Opini Tidak Wajar (Adverse)', 'Tidak Memberikan Pendapat (Disclaimer)'],
      correctOptionIndex: 0,
      explanation: 'Unqualified Opinion (WTP) adalah Opini Bersih tertinggi audit.',
    ),
    QuestionItem(
      id: 'akt_049',
      questionText: 'Opini auditor saat terdapat pembatasan lingkup audit atau ketidaksesuaian material namun tidak meluas dinamakan:',
      options: ['Opini Wajar Dengan Pengecualian (Qualified Opinion)', 'Unqualified', 'Adverse', 'Disclaimer'],
      correctOptionIndex: 0,
      explanation: 'Qualified Opinion menyatakan wajar kecuali untuk pos tertentu.',
    ),
    QuestionItem(
      id: 'akt_050',
      questionText: 'Opini auditor saat laporan keuangan terbukti salah saji material dan sangat meluas (menyesatkan) dinamakan:',
      options: ['Opini Tidak Wajar (Adverse Opinion)', 'Qualified Opinion', 'Disclaimer', 'Unqualified'],
      correctOptionIndex: 0,
      explanation: 'Adverse Opinion menerangkan bahwa laporan keuangan tidak disajikan secara wajar.',
    ),
    QuestionItem(
      id: 'akt_051',
      questionText: 'Kondisi auditor tidak dapat mengumpulkan bukti audit yang cukup akibat pembatasan ekstrim dinamakan opini:',
      options: ['Tidak Memberikan Pendapat (Disclaimer of Opinion)', 'Adverse', 'Qualified', 'Unqualified'],
      correctOptionIndex: 0,
      explanation: 'Disclaimer menerbitkan pernyataan menolak memberikan opini audit.',
    ),
    QuestionItem(
      id: 'akt_052',
      questionText: 'Standar Akuntansi Keuangan yang berlaku di Indonesia diterbitkan oleh pembentuk standar yaitu:',
      options: ['DSAK IAI (Dewan Standar Akuntansi Keuangan)', 'OJK', 'BPK', 'Kemenkeu'],
      correctOptionIndex: 0,
      explanation: 'DSAK-IAI menerbitkan SAK di Indonesia.',
    ),
    QuestionItem(
      id: 'akt_053',
      questionText: 'Standar Akuntansi Keuangan global yang menjadi konvergensi acuan SAK Indonesia adalah:',
      options: ['IFRS (International Financial Reporting Standards)', 'US GAAP', 'UK GAAP', 'IASB'],
      correctOptionIndex: 0,
      explanation: 'SAK Indonesia mengadopsi IFRS.',
    ),
    QuestionItem(
      id: 'akt_054',
      questionText: 'Rasio likuiditas yang mengukur kemampuan perusahaan melunasi utang jangka pendek dengan aset lancar dinamakan:',
      options: ['Rasio Lancar (Current Ratio)', 'Quick Ratio', 'Cash Ratio', 'Solvabilitas'],
      correctOptionIndex: 0,
      explanation: 'Current Ratio = Aset Lancar / Liabilitas Jangka Pendek.',
    ),
    QuestionItem(
      id: 'akt_055',
      questionText: 'Rasio likuiditas ketat yang mengukur kemampuan pelunasan utang lancar tanpa mengandalkan persediaan dinamakan:',
      options: ['Rasio Cepat (Quick Ratio / Acid-Test Ratio)', 'Current Ratio', 'Cash Ratio', 'Working Capital'],
      correctOptionIndex: 0,
      explanation: 'Quick Ratio = (Aset Lancar - Persediaan) / Liabilitas Jangka Pendek.',
    ),
    QuestionItem(
      id: 'akt_056',
      questionText: 'Rasio solvabilitas yang mengukur persentase total aset yang didanai oleh utang dinamakan:',
      options: ['Debt to Asset Ratio (DAR)', 'Debt to Equity Ratio (DER)', 'TIE', 'ROA'],
      correctOptionIndex: 0,
      explanation: 'DAR = Total Utang / Total Aset.',
    ),
    QuestionItem(
      id: 'akt_057',
      questionText: 'Rasio solvabilitas yang membandingkan total utang dengan total modal ekuitas pemilik dinamakan:',
      options: ['Debt to Equity Ratio (DER)', 'DAR', 'Current Ratio', 'ROE'],
      correctOptionIndex: 0,
      explanation: 'DER = Total Utang / Total Ekuitas.',
    ),
    QuestionItem(
      id: 'akt_058',
      questionText: 'Rasio profitabilitas yang mengukur tingkat pengembalian laba bersih atas total aset perusahaan dinamakan:',
      options: ['ROA (Return on Assets)', 'ROE', 'ROI', 'ROS'],
      correctOptionIndex: 0,
      explanation: 'ROA = Laba Bersih / Total Aset.',
    ),
    QuestionItem(
      id: 'akt_059',
      questionText: 'Rasio profitabilitas yang mengukur hasil pengembalian laba bersih atas modal saham pemilik dinamakan:',
      options: ['ROE (Return on Equity)', 'ROA', 'ROIC', 'EPS'],
      correctOptionIndex: 0,
      explanation: 'ROE = Laba Bersih / Total Ekuitas.',
    ),
    QuestionItem(
      id: 'akt_060',
      questionText: 'Rasio yang membagi laba bersih dengan jumlah lembar saham biasa yang beredar dinamakan:',
      options: ['Laba Per Lembar Saham (EPS / Earnings Per Share)', 'PER', 'PBV', 'Dividend Yield'],
      correctOptionIndex: 0,
      explanation: 'EPS = (Laba Bersih - Dividen Preferen) / Jumlah Saham Beredar.',
    ),
    QuestionItem(
      id: 'akt_061',
      questionText: 'Metode penyusunan Laporan Arus Kas yang menyesuaikan Laba Bersih dengan transaksi non-kas dinamakan metode:',
      options: ['Metode Tidak Langsung (Indirect Method)', 'Metode Langsung (Direct Method)', 'Metode Eliminasi', 'Metode Ekuitas'],
      correctOptionIndex: 0,
      explanation: 'Metode Tidak Langsung merekonsiliasi Laba Bersih ke Arus Kas Operasi.',
    ),
    QuestionItem(
      id: 'akt_062',
      questionText: 'Metode arus kas yang melaporkan secara detail penerimaan kas bruto dari pelanggan dan pembayaran kas ke pemasok dinamakan:',
      options: ['Metode Langsung (Direct Method)', 'Metode Tidak Langsung', 'Metode Akrual', 'Metode Kas'],
      correctOptionIndex: 0,
      explanation: 'Metode Langsung mencatat kelompok penerimaan dan pengeluaran kas operasi riil.',
    ),
    QuestionItem(
      id: 'akt_063',
      questionText: 'Bukti transaksi pencatatan pembelian barang dagang secara kredit adalah:',
      options: ['Faktur (Invoice)', 'Kuitansi', 'Nota Kontan', 'Cek'],
      correctOptionIndex: 0,
      explanation: 'Faktur adalah bukti penjualan/pembelian barang secara kredit.',
    ),
    QuestionItem(
      id: 'akt_064',
      questionText: 'Bukti pembayaran tunai sejumlah uang yang ditandatangani oleh penerima uang dinamakan:',
      options: ['Kuitansi', 'Faktur', 'Nota Debet', 'Cek'],
      correctOptionIndex: 0,
      explanation: 'Kuitansi adalah bukti penerimaan/pembayaran uang tunai.',
    ),
    QuestionItem(
      id: 'akt_065',
      questionText: 'Surat perintah nasabah kepada bank untuk mencairkan uang tunai kepada pemegang surat dinamakan:',
      options: ['Cek (Cheque)', 'Bilyet Giro', 'Nota Kredit', 'Draft'],
      correctOptionIndex: 0,
      explanation: 'Cek adalah surat perintah pembayaran kas dari bank.',
    ),
    QuestionItem(
      id: 'akt_066',
      questionText: 'Surat perintah pemindahbukuan dana dari rekening nasabah ke rekening penerima dinamakan:',
      options: ['Bilyet Giro', 'Cek', 'Kuitansi', 'Voucher'],
      correctOptionIndex: 0,
      explanation: 'Bilyet Giro memindahbukan dana non-tunai antar rekening.',
    ),
    QuestionItem(
      id: 'akt_067',
      questionText: 'Kondisi di mana saldo kas menurut catatan perusahaan berbeda dengan saldo catatan rekening koran bank membutuhkan penyesuaian:',
      options: ['Rekonsiliasi Bank (Bank Reconciliation)', 'Jurnal Penutup', 'Audit Kepatuhan', 'Penyusunan Neraca'],
      correctOptionIndex: 0,
      explanation: 'Rekonsiliasi Bank menyelaraskan perbedaan saldo kas perusahaan dan saldo bank.',
    ),
    QuestionItem(
      id: 'akt_068',
      questionText: 'Setoran kas perusahaan ke bank yang belum dicatat oleh bank pada tanggal rekening koran dinamakan:',
      options: ['Setoran Dalam Perjalanan (Deposit in Transit)', 'Cek Beredar', 'Biaya Admin Bank', 'Cek Kosong'],
      correctOptionIndex: 0,
      explanation: 'Deposit in Transit menambah saldo kas laporan bank.',
    ),
    QuestionItem(
      id: 'akt_069',
      questionText: 'Cek yang telah diterbitkan perusahaan tetapi belum dicairkan oleh penerima ke bank dinamakan:',
      options: ['Cek Beredar (Outstanding Check)', 'Deposit in Transit', 'NSF Check', 'Void Check'],
      correctOptionIndex: 0,
      explanation: 'Outstanding check mengurangi saldo laporan bank.',
    ),
    QuestionItem(
      id: 'akt_070',
      questionText: 'Cek yang ditolak bank karena dana rekening penarik tidak mencukupi dinamakan:',
      options: ['Cek Kosong (NSF Check / Not Sufficient Funds)', 'Outstanding Check', 'Cancel Check', 'Certified Check'],
      correctOptionIndex: 0,
      explanation: 'NSF Check adalah cek kosong yang mengurangi kas perusahaan.',
    ),
    QuestionItem(
      id: 'akt_071',
      questionText: 'Dana kas kecil yang dikelola untuk pembayaran pengeluaran rutin bernilai relatif kecil dinamakan:',
      options: ['Kas Kecil (Petty Cash)', 'Kas Bank', 'Giro', 'Deposito'],
      correctOptionIndex: 0,
      explanation: 'Petty cash membiayai pengeluaran operasional minor.',
    ),
    QuestionItem(
      id: 'akt_072',
      questionText: 'Sistem pengisian kas kecil di mana saldo dana selalu diisi kembali sebesar pengeluaran yang terjadi dinamakan sistem:',
      options: ['Imprest (Imprest Fund System / Impres)', 'Fluctuating System (Sistem Fluktuasi)', 'Variable', 'Fixed'],
      correctOptionIndex: 0,
      explanation: 'Imprest fund system mengisi kembali dana kas kecil sebesar pengeluaran yang dilaporkan.',
    ),
    QuestionItem(
      id: 'akt_073',
      questionText: 'Sistem pengelolaan kas kecil di mana jumlah saldo kas kecil berubah-ubah fluktuatif setiap pengisian dinamakan sistem:',
      options: ['Fluctuating Fund System (Sistem Fluktuasi)', 'Imprest System', 'Accrual System', 'Periodic System'],
      correctOptionIndex: 0,
      explanation: 'Sistem fluktuasi mencatat jurnal kas kecil pada tiap kali transaksi.',
    ),
    QuestionItem(
      id: 'akt_074',
      questionText: 'Pajak Pertambahan Nilai (PPN) yang dipungut saat perusahaan menjual barang dagang dinamakan PPN:',
      options: ['PPN Keluaran (Output VAT)', 'PPN Masukan', 'PPh 21', 'PPh 23'],
      correctOptionIndex: 0,
      explanation: 'PPN Keluaran adalah utang pajak atas transaksi penjualan.',
    ),
    QuestionItem(
      id: 'akt_075',
      questionText: 'Pajak Pertambahan Nilai (PPN) yang dibayar perusahaan saat membeli barang dari pemasok dinamakan PPN:',
      options: ['PPN Masukan (Input VAT)', 'PPN Keluaran', 'PPh 25', 'PPh Final'],
      correctOptionIndex: 0,
      explanation: 'PPN Masukan dapat dikreditkan mengurangi PPN Keluaran.',
    ),
    QuestionItem(
      id: 'akt_076',
      questionText: 'Pajak Penghasilan pasal 21 (PPh 21) di Indonesia merupakan pemotongan pajak atas:',
      options: ['Penghasilan Gaji, Upah, dan Honorarium Perorangan', 'Impor Barang', 'Sewa Tanah & Bangunan', 'Dividen Badan'],
      correctOptionIndex: 0,
      explanation: 'PPh 21 memotong pajak penghasilan pekerjaan karyawan.',
    ),
    QuestionItem(
      id: 'akt_077',
      questionText: 'Perbedaan akuntansi antara Penghasilan Kena Pajak (Fiskal) dan Laba Akuntansi (Komersial) yang bersifat sementara dinamakan:',
      options: ['Beda Waktu (Temporary Difference)', 'Beda Tetap', 'Beda Permanen', 'Tax Evasion'],
      correctOptionIndex: 0,
      explanation: 'Beda Waktu menimbulkan timbulnya Aset/Liabilitas Pajak Tangguhan (Deferred Tax).',
    ),
    QuestionItem(
      id: 'akt_078',
      questionText: 'Perbedaan antara akuntansi fiskal dan komersial yang tidak akan terpulihkan di masa depan (seperti sumbangan) dinamakan:',
      options: ['Beda Tetap / Permanen (Permanent Difference)', 'Beda Waktu', 'Deferred Tax', 'Tax Credit'],
      correctOptionIndex: 0,
      explanation: 'Beda Permanen tidak diakui dalam pajak tangguhan.',
    ),
    QuestionItem(
      id: 'akt_079',
      questionText: 'Penyusunan laporan keuangan gabungan antara Perusahaan Induk (Parent) dan Perusahaan Anak (Subsidiary) dinamakan:',
      options: ['Laporan Keuangan Konsolidasi (Consolidated Financial Statements)', 'Laporan Segmen', 'Laporan Berkelanjutan', 'Laporan Gabungan'],
      correctOptionIndex: 0,
      explanation: 'Laporan Konsolidasi menyajikan induk dan anak sebagai entitas tunggal.',
    ),
    QuestionItem(
      id: 'akt_080',
      questionText: 'Proses eliminasi transaksi antar perusahaan dalam entitas grup pada konsolidasi dinamakan eliminasi:',
      options: ['Intercompany Transactions (Transaksi Antar Perusahaan)', 'Dividen Internal', 'Ekuitas Anak', 'Semua Benar'],
      correctOptionIndex: 3,
      explanation: 'Eliminasi mengapus saldo timbal balik antar anggota grup.',
    ),
    QuestionItem(
      id: 'akt_081',
      questionText: 'Selisih lebih antara harga akuisisi perusahaan dengan nilai wajar aset bersih yang diidentifikasi dinamakan:',
      options: ['Goodwill', 'Diskon Akuisisi', 'Agio Saham', 'Hak Minoritas'],
      correctOptionIndex: 0,
      explanation: 'Goodwill adalah aset takberwujud hasil pembayaran lebih saat akuisisi.',
    ),
    QuestionItem(
      id: 'akt_082',
      questionText: 'Bagian ekuitas anak perusahaan yang tidak dimiliki oleh perusahaan induk dinamakan:',
      options: ['Kepentingan Non-Pengendali (Non-Controlling Interest / Hak Minoritas)', 'Parent Equity', 'Goodwill', 'Retained Earnings'],
      correctOptionIndex: 0,
      explanation: 'NCI (Hak Minoritas) merepresentasikan saham pihak luar di perusahaan anak.',
    ),
    QuestionItem(
      id: 'akt_083',
      questionText: 'Metode akuntansi untuk investasi saham 20% - 50% di mana investor memiliki pengaruh signifikan dinamakan:',
      options: ['Metode Ekuitas (Equity Method)', 'Metode Biaya (Cost Method)', 'Metode Nilai Wajar', 'Metode Konsolidasi'],
      correctOptionIndex: 0,
      explanation: 'Metode Ekuitas menyesuaikan nilai investasi sesuai bagian laba/rugi perusahaan asosiasi.',
    ),
    QuestionItem(
      id: 'akt_084',
      questionText: 'Metode akuntansi investasi saham di bawah 20% tanpa pengaruh signifikan di mana dividen diakui sebagai pendapatan dinamakan:',
      options: ['Metode Biaya / Nilai Wajar (Cost / Fair Value Method)', 'Metode Ekuitas', 'Metode Konsolidasi', 'Metode Pooling'],
      correctOptionIndex: 0,
      explanation: 'Metode Biaya mencatat investasi sebesar harga perolehan.',
    ),
    QuestionItem(
      id: 'akt_085',
      questionText: 'Instrumen keuangan turunan yang nilainya diturunkan dari variabel komoditas, suku bunga, atau mata uang dinamakan:',
      options: ['Derivatif (Derivatives)', 'Obligasi', 'Saham', 'Reksa Dana'],
      correctOptionIndex: 0,
      explanation: 'Derivatif (seperti Option, Future, Swap) dipakai untuk lindung nilai (hedging).',
    ),
    QuestionItem(
      id: 'akt_086',
      questionText: 'Strategi lindung nilai transaksi keuangan untuk mengurangi risiko kerugian perubahan harga/kurs dinamakan:',
      options: ['Hedging (Lindung Nilai)', 'Spekulasi', 'Arbitrase', 'Leverage'],
      correctOptionIndex: 0,
      explanation: 'Hedging membatasi risiko kerugian fluktuasi finansial.',
    ),
    QuestionItem(
      id: 'akt_087',
      questionText: 'Sistem akuntansi yang menyajikan informasi keuangan berbasis prinsip-prinsip syariat Islam dinamakan:',
      options: ['Akuntansi Syariah', 'Akuntansi Sektor Publik', 'Akuntansi Keperilakuan', 'Akuntansi Forensik'],
      correctOptionIndex: 0,
      explanation: 'Akuntansi Syariah mengacu pada standar PSAK Syariah (KDPPLKS).',
    ),
    QuestionItem(
      id: 'akt_088',
      questionText: 'Akuntansi yang berfokus pada pengumpulan bukti keuangan untuk pembuktian tindak pidana kecurangan (fraud) di pengadilan dinamakan:',
      options: ['Akuntansi Forensik', 'Audit Manajemen', 'Akuntansi Pajak', 'Akuntansi Keuangan'],
      correctOptionIndex: 0,
      explanation: 'Akuntan Forensik menyelidiki dugaan kecurangan finansial dan korupsi.',
    ),
    QuestionItem(
      id: 'akt_089',
      questionText: 'Segitiga kecurangan (Fraud Triangle) menurut Donald Cressey terdiri dari 3 elemen yaitu:',
      options: ['Tekanan (Pressure), Kesempatan (Opportunity), dan Rasionalisasi', 'Niat, Rencana, Eksekusi', 'Uang, Kekuasaan, Peluang', 'Kriminal, Motif, Bukti'],
      correctOptionIndex: 0,
      explanation: 'Fraud Triangle: Pressure, Opportunity, dan Rationalization.',
    ),
    QuestionItem(
      id: 'akt_090',
      questionText: 'Sistem Akuntansi yang digunakan pada lembaga pemerintahan non-nirlaba dinamakan:',
      options: ['Akuntansi Sektor Publik / Pemerintahan', 'Akuntansi Komersial', 'Akuntansi Manajemen', 'Akuntansi Biaya'],
      correctOptionIndex: 0,
      explanation: 'Akuntansi Sektor Publik mengacu pada Standar Akuntansi Pemerintahan (SAP).',
    ),
    QuestionItem(
      id: 'akt_091',
      questionText: 'Perusahaan yang bisnis utamanya membeli barang dari pemasok dan menjualnya kembali tanpa mengubah bentuk barang dinamakan:',
      options: ['Perusahaan Dagang', 'Perusahaan Jasa', 'Perusahaan Manufaktur', 'Perusahaan Ekstraktif'],
      correctOptionIndex: 0,
      explanation: 'Perusahaan Dagang memperjualbelikan barang fisik tanpa pengolahan.',
    ),
    QuestionItem(
      id: 'akt_092',
      questionText: 'Perusahaan yang menjual produk tidak berwujud fisik seperti layanan kesehatan atau perbankan dinamakan:',
      options: ['Perusahaan Jasa', 'Perusahaan Dagang', 'Perusahaan Manufaktur', 'Pabrik'],
      correctOptionIndex: 0,
      explanation: 'Perusahaan Jasa tidak memiliki persediaan barang dagang.',
    ),
    QuestionItem(
      id: 'akt_093',
      questionText: 'Perusahaan yang mengolah bahan mentah menjadi barang jadi melalui proses produksi dinamakan:',
      options: ['Perusahaan Manufaktur', 'Perusahaan Dagang', 'Perusahaan Jasa', 'Retailer'],
      correctOptionIndex: 0,
      explanation: 'Perusahaan Manufaktur memproses bahan baku menjadi produk jadi.',
    ),
    QuestionItem(
      id: 'akt_094',
      questionText: 'Syarat penyerahan barang di mana hak milik dan risiko barang beralih ke pembeli sejak barang keluar dari gudang penjual dinamakan:',
      options: ['FOB Shipping Point', 'FOB Destination', 'CIF', 'CFR'],
      correctOptionIndex: 0,
      explanation: 'FOB Shipping Point: Beban angkut dibayar pembeli sejak pengiriman.',
    ),
    QuestionItem(
      id: 'akt_095',
      questionText: 'Syarat penyerahan barang di mana hak milik dan beban angkut ditanggung penjual hingga barang tiba di gudang pembeli dinamakan:',
      options: ['FOB Destination', 'FOB Shipping Point', 'EXW', 'DDP'],
      correctOptionIndex: 0,
      explanation: 'FOB Destination: Beban angkut ditanggung penjual sampai tujuan.',
    ),
    QuestionItem(
      id: 'akt_096',
      questionText: 'Syarat pembayaran 2/10, n/30 berarti pembeli mendapat potongan harga 2% jika melunasi dalam waktu:',
      options: ['10 Hari (Jatuh tempo 30 hari)', '2 Hari', '30 Hari', '20 Hari'],
      correctOptionIndex: 0,
      explanation: '2/10, n/30: Potongan 2% jika lunas <=10 hari, batas pembayaran 30 hari.',
    ),
    QuestionItem(
      id: 'akt_097',
      questionText: 'Pengurangan harga yang diberikan penjual karena barang yang dikirim rusak atau tidak sesuai pesanan dinamakan:',
      options: ['Retur dan Potongan Penjualan (Sales Returns & Allowances)', 'Diskon Kuantitas', 'Kas Diskon', 'Rabat'],
      correctOptionIndex: 0,
      explanation: 'Retur Penjualan mencatat pengembalian/pengurangan harga atas barang rusak.',
    ),
    QuestionItem(
      id: 'akt_098',
      questionText: 'Pencatatan persediaan barang dagang di mana fisik persediaan dihitung secara berkala pada akhir periode dinamakan sistem:',
      options: ['Sistem Periodik / Fisik (Periodic Inventory System)', 'Sistem Perpetual', 'Sistem FIFO', 'Sistem Kontinyu'],
      correctOptionIndex: 0,
      explanation: 'Sistem Periodik mengharuskan stock opname akhir periode untuk menentukan HPP.',
    ),
    QuestionItem(
      id: 'akt_099',
      questionText: 'Pencatatan persediaan di mana setiap mutasi keluar-masuk barang selalu dicatat secara real-time dinamakan sistem:',
      options: ['Sistem Perpetual (Perpetual Inventory System)', 'Sistem Periodik', 'Sistem Fisik', 'Sistem LIFO'],
      correctOptionIndex: 0,
      explanation: 'Sistem Perpetual memperbarui saldo persediaan dan HPP setiap kali transaksi.',
    ),
    QuestionItem(
      id: 'akt_100',
      questionText: 'Pemeriksaan fisik langsung menghitung jumlah stok barang di gudang pada akhir periode dinamakan:',
      options: ['Stock Opname (Physical Inventory Count)', 'Audit Kas', 'Vouching', 'Scanning'],
      correctOptionIndex: 0,
      explanation: 'Stock opname menyelaraskan stok fisik nyata dengan catatan pembukuan.',
    ),
  ];
}
