import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaPrancisQuestions() {
  return const [
    QuestionItem(
      id: 'bah_pra_001',
      questionText: 'Kata sapaan Bahasa Prancis yang berarti "Halo / Selamat Siang" adalah:',
      options: ['Bonjour', 'Bonsoir', 'Bonne nuit', 'Salut'],
      correctOptionIndex: 0,
      explanation: 'Bonjour adalah salam resmi selamat siang/pagi.',
    ),
    QuestionItem(
      id: 'bah_pra_002',
      questionText: 'Kata sapaan Bahasa Prancis yang berarti "Selamat Malam" saat bertemu adalah:',
      options: ['Bonsoir', 'Bonjour', 'Bonne nuit', 'Au revoir'],
      correctOptionIndex: 0,
      explanation: 'Bonsoir adalah salam malam hari saat bertemu.',
    ),
    QuestionItem(
      id: 'bah_pra_003',
      questionText: 'Ungkapan ucapan "Selamat Malam / Selamat Tidur" sebelum beristirahat adalah:',
      options: ['Bonne nuit', 'Bonsoir', 'Bonjour', 'Salut'],
      correctOptionIndex: 0,
      explanation: 'Bonne nuit diucapkan sebelum tidur.',
    ),
    QuestionItem(
      id: 'bah_pra_004',
      questionText: 'Kata sapaan informal / santai "Hai / Dah" antarteman adalah:',
      options: ['Salut', 'Bonjour', 'Au revoir', 'Pardon'],
      correctOptionIndex: 0,
      explanation: 'Salut adalah sapaan santai kasual.',
    ),
    QuestionItem(
      id: 'bah_pra_005',
      questionText: 'Ungkapan perpisahan formal Bahasa Prancis "Sampai Jumpa Lagi" adalah:',
      options: ['Au revoir', 'Salut', 'A bientôt', 'Adieu'],
      correctOptionIndex: 0,
      explanation: 'Au revoir adalah ucapan perpisahan formal.',
    ),
    QuestionItem(
      id: 'bah_pra_006',
      questionText: 'Ungkapan perpisahan "Sampai Jumpa Segera" adalah:',
      options: ['À bientôt', 'Au revoir', 'À demain', 'À tout à l\'heure'],
      correctOptionIndex: 0,
      explanation: 'À bientôt berarti sampai jumpa segera.',
    ),
    QuestionItem(
      id: 'bah_pra_007',
      questionText: 'Ungkapan perpisahan "Sampai Jumpa Besok" adalah:',
      options: ['À demain', 'À bientôt', 'Au revoir', 'Bonne journée'],
      correctOptionIndex: 0,
      explanation: 'À demain berarti sampai jumpa besok.',
    ),
    QuestionItem(
      id: 'bah_pra_008',
      questionText: 'Ungkapan ucapan "Terima Kasih" dalam Bahasa Prancis adalah:',
      options: ['Merci', 'De rien', 'S\'il vous plaît', 'Pardon'],
      correctOptionIndex: 0,
      explanation: 'Merci berarti terima kasih.',
    ),
    QuestionItem(
      id: 'bah_pra_009',
      questionText: 'Ungkapan ucapan "Terima Kasih Banyak" adalah:',
      options: ['Merci beaucoup', 'Merci bien', 'De rien', 'Je vous en prie'],
      correctOptionIndex: 0,
      explanation: 'Merci beaucoup berarti terima kasih banyak.',
    ),
    QuestionItem(
      id: 'bah_pra_110',
      questionText: 'Jawaban santai untuk ucapan terima kasih ("Sama-sama / Kembalian") adalah:',
      options: ['De rien', 'Merci', 'Pardon', 'D\'accord'],
      correctOptionIndex: 0,
      explanation: 'De rien bermakna sama-sama santai.',
    ),
    QuestionItem(
      id: 'bah_pra_011',
      questionText: 'Jawaban formal untuk ucapan terima kasih ("Dengan senang hati") adalah:',
      options: ['Je vous en prie', 'De rien', 'Merci', 'Pas de quoi'],
      correctOptionIndex: 0,
      explanation: 'Je vous en prie adalah ucapan balasan formal.',
    ),
    QuestionItem(
      id: 'bah_pra_012',
      questionText: 'Ungkapan "Permisi / Tolong" secara formal adalah:',
      options: ['S\'il vous plaît', 'S\'il te plaît', 'Pardon', 'Excusez-moi'],
      correctOptionIndex: 0,
      explanation: 'S\'il vous plaît diucapkan saat meminta tolong secara formal.',
    ),
    QuestionItem(
      id: 'bah_pra_013',
      questionText: 'Ungkapan "Maaf" untuk meminta maaf secara sopan adalah:',
      options: ['Pardon / Excusez-moi', 'Merci', 'Bonjour', 'D\'accord'],
      correctOptionIndex: 0,
      explanation: 'Pardon / Excusez-moi untuk permohonan maaf.',
    ),
    QuestionItem(
      id: 'bah_pra_014',
      questionText: 'Kata ganti orang pertama tunggal "Saya" adalah:',
      options: ['Je (J\')', 'Tu', 'Il', 'Elle'],
      correctOptionIndex: 0,
      explanation: 'Je berarti Saya (menjadi J\' bila bertemu vokal).',
    ),
    QuestionItem(
      id: 'bah_pra_015',
      questionText: 'Kata ganti orang kedua informal "Kamu" adalah:',
      options: ['Tu', 'Vous', 'Je', 'Nous'],
      correctOptionIndex: 0,
      explanation: 'Tu digunakan untuk teman/orang terdekat.',
    ),
    QuestionItem(
      id: 'bah_pra_016',
      questionText: 'Kata ganti orang kedua formal "Anda / Jamak Kalian" adalah:',
      options: ['Vous', 'Tu', 'Nous', 'Ils'],
      correctOptionIndex: 0,
      explanation: 'Vous adalah kata ganti formal / kalian jamak.',
    ),
    QuestionItem(
      id: 'bah_pra_017',
      questionText: 'Kata ganti orang ketiga tunggal maskulin "Dia (Laki-laki)" adalah:',
      options: ['Il', 'Elle', 'On', 'Ils'],
      correctOptionIndex: 0,
      explanation: 'Il berarti Dia (laki-laki).',
    ),
    QuestionItem(
      id: 'bah_pra_018',
      questionText: 'Kata ganti orang ketiga tunggal feminin "Dia (Perempuan)" adalah:',
      options: ['Elle', 'Il', 'On', 'Elles'],
      correctOptionIndex: 0,
      explanation: 'Elle berarti Dia (perempuan).',
    ),
    QuestionItem(
      id: 'bah_pra_019',
      questionText: 'Kata ganti orang pertama jamak "Kami / Kita" adalah:',
      options: ['Nous', 'Vous', 'Ils', 'Elles'],
      correctOptionIndex: 0,
      explanation: 'Nous bermakna Kami/Kita.',
    ),
    QuestionItem(
      id: 'bah_pra_020',
      questionText: 'Kata ganti orang ketiga jamak "Mereka (Maskulin/Campuran)" adalah:',
      options: ['Ils', 'Elles', 'Nous', 'Vous'],
      correctOptionIndex: 0,
      explanation: 'Ils berarti Mereka (laki-laki/campuran).',
    ),
    QuestionItem(
      id: 'bah_pra_021',
      questionText: 'Artikel definit (kata sandang pasti) untuk kata benda maskulin tunggal adalah:',
      options: ['le (l\')', 'la', 'les', 'un'],
      correctOptionIndex: 0,
      explanation: 'le adalah artikel definit maskulin (misal: le livre).',
    ),
    QuestionItem(
      id: 'bah_pra_022',
      questionText: 'Artikel definit untuk kata benda feminin tunggal adalah:',
      options: ['la (l\')', 'le', 'les', 'une'],
      correctOptionIndex: 0,
      explanation: 'la adalah artikel definit feminin (misal: la maison).',
    ),
    QuestionItem(
      id: 'bah_pra_023',
      questionText: 'Artikel definit untuk semua kata benda jamak (Pluriel) adalah:',
      options: ['les', 'le', 'la', 'des'],
      correctOptionIndex: 0,
      explanation: 'les adalah artikel definit jamak.',
    ),
    QuestionItem(
      id: 'bah_pra_024',
      questionText: 'Artikel indefinit (kata sandang tak pasti) maskulin tunggal adalah:',
      options: ['un', 'une', 'des', 'du'],
      correctOptionIndex: 0,
      explanation: 'un bermakna seorang/sebuah maskulin (misal: un garçon).',
    ),
    QuestionItem(
      id: 'bah_pra_025',
      questionText: 'Artikel indefinit feminin tunggal adalah:',
      options: ['une', 'un', 'des', 'de la'],
      correctOptionIndex: 0,
      explanation: 'une bermakna seorang/sebuah feminin (misal: une fille).',
    ),
    QuestionItem(
      id: 'bah_pra_026',
      questionText: 'Konjugasi kata kerja bantu "être" (to be) untuk subjek "Je" adalah:',
      options: ['suis (Je suis)', 'es', 'est', 'sommes'],
      correctOptionIndex: 0,
      explanation: 'Je suis (Saya adalah).',
    ),
    QuestionItem(
      id: 'bah_pra_027',
      questionText: 'Konjugasi kata kerja "être" untuk subjek "Tu" adalah:',
      options: ['es (Tu es)', 'suis', 'est', 'êtes'],
      correctOptionIndex: 0,
      explanation: 'Tu es (Kamu adalah).',
    ),
    QuestionItem(
      id: 'bah_pra_028',
      questionText: 'Konjugasi kata kerja "être" untuk subjek "Il / Elle" adalah:',
      options: ['est (Il est)', 'suis', 'es', 'sont'],
      correctOptionIndex: 0,
      explanation: 'Il/Elle est (Dia adalah).',
    ),
    QuestionItem(
      id: 'bah_pra_029',
      questionText: 'Konjugasi kata kerja bantu kepemilikan "avoir" (to have) untuk subjek "J\'" adalah:',
      options: ['ai (J\'ai)', 'as', 'a', 'avons'],
      correctOptionIndex: 0,
      explanation: 'J\'ai (Saya punya).',
    ),
    QuestionItem(
      id: 'bah_pra_030',
      questionText: 'Konjugasi kata kerja "avoir" untuk subjek "Tu" adalah:',
      options: ['as (Tu as)', 'ai', 'a', 'avez'],
      correctOptionIndex: 0,
      explanation: 'Tu as (Kamu punya).',
    ),
    QuestionItem(
      id: 'bah_pra_031',
      questionText: 'Angka 1 (Satu) dalam Bahasa Prancis disebut:',
      options: ['un / une', 'deux', 'trois', 'quatre'],
      correctOptionIndex: 0,
      explanation: 'un/une berarti 1.',
    ),
    QuestionItem(
      id: 'bah_pra_032',
      questionText: 'Angka 2 (Dua) dalam Bahasa Prancis disebut:',
      options: ['deux', 'un', 'trois', 'cinq'],
      correctOptionIndex: 0,
      explanation: 'deux berarti 2.',
    ),
    QuestionItem(
      id: 'bah_pra_033',
      questionText: 'Angka 3 (Tiga) dalam Bahasa Prancis disebut:',
      options: ['trois', 'quatre', 'cinq', 'six'],
      correctOptionIndex: 0,
      explanation: 'trois berarti 3.',
    ),
    QuestionItem(
      id: 'bah_pra_034',
      questionText: 'Angka 4 (Empat) dalam Bahasa Prancis disebut:',
      options: ['quatre', 'trois', 'cinq', 'sept'],
      correctOptionIndex: 0,
      explanation: 'quatre berarti 4.',
    ),
    QuestionItem(
      id: 'bah_pra_035',
      questionText: 'Angka 5 (Lima) dalam Bahasa Prancis disebut:',
      options: ['cinq', 'six', 'sept', 'huit'],
      correctOptionIndex: 0,
      explanation: 'cinq berarti 5.',
    ),
    QuestionItem(
      id: 'bah_pra_036',
      questionText: 'Angka 10 (Sepuluh) dalam Bahasa Prancis disebut:',
      options: ['dix', 'neuf', 'huit', 'onze'],
      correctOptionIndex: 0,
      explanation: 'dix berarti 10.',
    ),
    QuestionItem(
      id: 'bah_pra_037',
      questionText: 'Angka 20 (Dua Puluh) dalam Bahasa Prancis disebut:',
      options: ['vingt', 'trente', 'quarante', 'dix'],
      correctOptionIndex: 0,
      explanation: 'vingt berarti 20.',
    ),
    QuestionItem(
      id: 'bah_pra_038',
      questionText: 'Angka 70 dalam sistem hitungan Bahasa Prancis dinamakan:',
      options: ['soixante-dix (60+10)', 'septante', 'soixante-doute', 'sept-dix'],
      correctOptionIndex: 0,
      explanation: '70 dalam Bahasa Prancis standar dihitung 60 + 10 (soixante-dix).',
    ),
    QuestionItem(
      id: 'bah_pra_039',
      questionText: 'Angka 80 dalam sistem hitungan Bahasa Prancis dinamakan:',
      options: ['quatre-vingts (4x20)', 'huitante', 'octante', 'quatre-dix'],
      correctOptionIndex: 0,
      explanation: '80 dihitung 4 x 20 (quatre-vingts).',
    ),
    QuestionItem(
      id: 'bah_pra_040',
      questionText: 'Angka 90 dalam sistem hitungan Bahasa Prancis dinamakan:',
      options: ['quatre-vingt-dix (4x20+10)', 'nonante', 'neuf-dix', 'quatre-dix-dix'],
      correctOptionIndex: 0,
      explanation: '90 dihitung 4 x 20 + 10 (quatre-vingt-dix).',
    ),
    QuestionItem(
      id: 'bah_pra_041',
      questionText: 'Mata uang resmi yang digunakan di Prancis dan Uni Eropa adalah:',
      options: ['Euro (€)', 'Franc', 'Livre', 'Dollar'],
      correctOptionIndex: 0,
      explanation: 'Euro adalah mata uang resmi Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_042',
      questionText: 'Ujian kemampuan standar resmi Bahasa Prancis internasional untuk penutur asing dinamakan:',
      options: ['DELF / DALF', 'TOEFL', 'JLPT', 'HSK'],
      correctOptionIndex: 0,
      explanation: 'DELF (Diplôme d\'Études en Langue Française) / DALF.',
    ),
    QuestionItem(
      id: 'bah_pra_043',
      questionText: 'Kalimat negatif sederhana dalam Bahasa Prancis mengapit kata kerja dengan pasangan kata:',
      options: ['ne ... pas', 'ne ... plus', 'ne ... jamais', 'ne ... rien'],
      correctOptionIndex: 0,
      explanation: 'ne + Verb + pas membentuk kalimat negatif standar.',
    ),
    QuestionItem(
      id: 'bah_pra_044',
      questionText: 'Bentuk waktu lampau selesai (Present Perfect / Past) yang paling umum dalam bahasa lisan adalah:',
      options: ['Passé composé', 'Imparfait', 'Plus-que-parfait', 'Futur simple'],
      correctOptionIndex: 0,
      explanation: 'Passé composé menyatakan kejadian lampau selesai.',
    ),
    QuestionItem(
      id: 'bah_pra_045',
      questionText: 'Bentuk waktu lampau yang digunakan untuk menggambarkan latar belakang, kebiasaan, atau kondisi lamanya kejadian adalah:',
      options: ['Imparfait', 'Passé composé', 'Passé simple', 'Futur proche'],
      correctOptionIndex: 0,
      explanation: 'Imparfait menggambarkan latar kebiasaan masa lalu.',
    ),
    QuestionItem(
      id: 'bah_pra_046',
      questionText: 'Bentuk waktu mendatang dekat yang menggunakan "aller + Infinitif" dinamakan:',
      options: ['Futur proche', 'Futur simple', 'Présent', 'Passé récent'],
      correctOptionIndex: 0,
      explanation: 'Futur proche (akan segera terjadi) menggunakan aller + Infinitive.',
    ),
    QuestionItem(
      id: 'bah_pra_047',
      questionText: 'Kata tanya "Qui?" bermakna:',
      options: ['Siapa?', 'Apa?', 'Kapan?', 'Di mana?'],
      correctOptionIndex: 0,
      explanation: 'Qui menanyakan orang (siapa).',
    ),
    QuestionItem(
      id: 'bah_pra_048',
      questionText: 'Kata tanya "Que?" / "Qu\'est-ce que?" bermakna:',
      options: ['Apa?', 'Siapa?', 'Mengapa?', 'Bagaimana?'],
      correctOptionIndex: 0,
      explanation: 'Que / Qu\'est-ce que menanyakan benda/aksi (apa).',
    ),
    QuestionItem(
      id: 'bah_pra_049',
      questionText: 'Kata tanya "Où?" bermakna:',
      options: ['Di mana? / Ke mana?', 'Kapan?', 'Bagaimana?', 'Berapa?'],
      correctOptionIndex: 0,
      explanation: 'Où menanyakan tempat.',
    ),
    QuestionItem(
      id: 'bah_pra_050',
      questionText: 'Kata tanya "Quand?" bermakna:',
      options: ['Kapan? (Waktu)', 'Mengapa?', 'Siapa?', 'Bagaimana?'],
      correctOptionIndex: 0,
      explanation: 'Quand menanyakan waktu.',
    ),
    QuestionItem(
      id: 'bah_pra_051',
      questionText: 'Kata tanya "Pourquoi?" bermakna:',
      options: ['Mengapa? / Kenapa?', 'Kapan?', 'Bagaimana?', 'Di mana?'],
      correctOptionIndex: 0,
      explanation: 'Pourquoi menanyakan alasan.',
    ),
    QuestionItem(
      id: 'bah_pra_052',
      questionText: 'Kata tanya "Comment?" bermakna:',
      options: ['Bagaimana?', 'Mengapa?', 'Apa?', 'Siapa?'],
      correctOptionIndex: 0,
      explanation: 'Comment menanyakan cara/keadaan.',
    ),
    QuestionItem(
      id: 'bah_pra_053',
      questionText: 'Arti kosakata "l\'école" adalah:',
      options: ['Sekolah', 'Rumah', 'Toko', 'Gereja'],
      correctOptionIndex: 0,
      explanation: 'l\'école berarti sekolah.',
    ),
    QuestionItem(
      id: 'bah_pra_054',
      questionText: 'Arti kosakata "la maison" adalah:',
      options: ['Rumah', 'Sekolah', 'Kamar', 'Restoran'],
      correctOptionIndex: 0,
      explanation: 'la maison berarti rumah.',
    ),
    QuestionItem(
      id: 'bah_pra_055',
      questionText: 'Arti kosakata "la gare" adalah:',
      options: ['Stasiun Kereta Api', 'Bandara', 'Pelabuhan', 'Pasar'],
      correctOptionIndex: 0,
      explanation: 'la gare berarti stasiun kereta.',
    ),
    QuestionItem(
      id: 'bah_pra_056',
      questionText: 'Arti kosakata "l\'aéroport" adalah:',
      options: ['Bandara Udara', 'Stasiun', 'Terminal', 'Dermaga'],
      correctOptionIndex: 0,
      explanation: 'l\'aéroport berarti bandara.',
    ),
    QuestionItem(
      id: 'bah_pra_057',
      questionText: 'Arti kosakata "le livre" adalah:',
      options: ['Buku', 'Pena', 'Kertas', 'Meja'],
      correctOptionIndex: 0,
      explanation: 'le livre berarti buku.',
    ),
    QuestionItem(
      id: 'bah_pra_058',
      questionText: 'Arti kosakata "le stylo" adalah:',
      options: ['Pulpen / Pena', 'Pensil', 'Buku', 'Penghapus'],
      correctOptionIndex: 0,
      explanation: 'le stylo berarti pulpen.',
    ),
    QuestionItem(
      id: 'bah_pra_059',
      questionText: 'Arti kosakata "la voiture" adalah:',
      options: ['Mobil', 'Sepeda', 'Bus', 'Kereta'],
      correctOptionIndex: 0,
      explanation: 'la voiture berarti mobil.',
    ),
    QuestionItem(
      id: 'bah_pra_060',
      questionText: 'Arti kosakata "le vélo" adalah:',
      options: ['Sepeda', 'Motor', 'Mobil', 'Kereta'],
      correctOptionIndex: 0,
      explanation: 'le vélo berarti sepeda.',
    ),
    QuestionItem(
      id: 'bah_pra_061',
      questionText: 'Arti kosakata "l\'eau" adalah:',
      options: ['Air', 'Susu', 'Anggur', 'Kopi'],
      correctOptionIndex: 0,
      explanation: 'l\'eau berarti air.',
    ),
    QuestionItem(
      id: 'bah_pra_062',
      questionText: 'Arti kosakata "le pain" adalah:',
      options: ['Roti', 'Nasi', 'Daging', 'Keju'],
      correctOptionIndex: 0,
      explanation: 'le pain berarti roti (makanan pokok Prancis).',
    ),
    QuestionItem(
      id: 'bah_pra_063',
      questionText: 'Arti kosakata "le fromage" adalah:',
      options: ['Keju', 'Mentega', 'Roti', 'Susu'],
      correctOptionIndex: 0,
      explanation: 'le fromage berarti keju.',
    ),
    QuestionItem(
      id: 'bah_pra_064',
      questionText: 'Arti kosakata "le vin" adalah:',
      options: ['Minuman Anggur (Wine)', 'Air', 'Teh', 'Kopi'],
      correctOptionIndex: 0,
      explanation: 'le vin adalah anggur minuman khas Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_065',
      questionText: 'Hari Senin dalam Bahasa Prancis disebut:',
      options: ['lundi', 'mardi', 'mercredi', 'jeudi'],
      correctOptionIndex: 0,
      explanation: 'lundi adalah hari Senin.',
    ),
    QuestionItem(
      id: 'bah_pra_066',
      questionText: 'Hari Selasa dalam Bahasa Prancis disebut:',
      options: ['mardi', 'lundi', 'mercredi', 'vendredi'],
      correctOptionIndex: 0,
      explanation: 'mardi adalah hari Selasa.',
    ),
    QuestionItem(
      id: 'bah_pra_067',
      questionText: 'Hari Rabu dalam Bahasa Prancis disebut:',
      options: ['mercredi', 'mardi', 'jeudi', 'samedi'],
      correctOptionIndex: 0,
      explanation: 'mercredi adalah hari Rabu.',
    ),
    QuestionItem(
      id: 'bah_pra_068',
      questionText: 'Hari Kamis dalam Bahasa Prancis disebut:',
      options: ['jeudi', 'mercredi', 'vendredi', 'dimanche'],
      correctOptionIndex: 0,
      explanation: 'jeudi adalah hari Kamis.',
    ),
    QuestionItem(
      id: 'bah_pra_069',
      questionText: 'Hari Jumat dalam Bahasa Prancis disebut:',
      options: ['vendredi', 'jeudi', 'samedi', 'lundi'],
      correctOptionIndex: 0,
      explanation: 'vendredi adalah hari Jumat.',
    ),
    QuestionItem(
      id: 'bah_pra_070',
      questionText: 'Hari Sabtu dalam Bahasa Prancis disebut:',
      options: ['samedi', 'vendredi', 'dimanche', 'mardi'],
      correctOptionIndex: 0,
      explanation: 'samedi adalah hari Sabtu.',
    ),
    QuestionItem(
      id: 'bah_pra_071',
      questionText: 'Hari Minggu dalam Bahasa Prancis disebut:',
      options: ['dimanche', 'samedi', 'lundi', 'jeudi'],
      correctOptionIndex: 0,
      explanation: 'dimanche adalah hari Minggu.',
    ),
    QuestionItem(
      id: 'bah_pra_072',
      questionText: 'Musim Semi di Prancis dinamakan:',
      options: ['le printemps', 'l\'été', 'l\'automne', 'l\'hiver'],
      correctOptionIndex: 0,
      explanation: 'le printemps adalah musim semi.',
    ),
    QuestionItem(
      id: 'bah_pra_073',
      questionText: 'Musim Panas di Prancis dinamakan:',
      options: ['l\'été', 'le printemps', 'l\'automne', 'l\'hiver'],
      correctOptionIndex: 0,
      explanation: 'l\'été adalah musim panas.',
    ),
    QuestionItem(
      id: 'bah_pra_074',
      questionText: 'Musim Gugur di Prancis dinamakan:',
      options: ['l\'automne', 'l\'été', 'l\'hiver', 'le printemps'],
      correctOptionIndex: 0,
      explanation: 'l\'automne adalah musim gugur.',
    ),
    QuestionItem(
      id: 'bah_pra_075',
      questionText: 'Musim Dingin di Prancis dinamakan:',
      options: ['l\'hiver', 'l\'automne', 'le printemps', 'l\'été'],
      correctOptionIndex: 0,
      explanation: 'l\'hiver adalah musim dingin salju.',
    ),
    QuestionItem(
      id: 'bah_pra_076',
      questionText: 'Ibu kota sekaligus kota terbesar di Prancis yang terkenal dengan Menara Eiffel adalah:',
      options: ['Paris', 'Lyon', 'Marseille', 'Nice'],
      correctOptionIndex: 0,
      explanation: 'Paris adalah ibu kota Republik Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_077',
      questionText: 'Menara besi paling ikonik di kota Paris buatan Gustave Eiffel dinamakan:',
      options: ['La Tour Eiffel (Menara Eiffel)', 'Le Louvre', 'Arc de Triomphe', 'Notre-Dame'],
      correctOptionIndex: 0,
      explanation: 'La Tour Eiffel ikon utama kota Paris.',
    ),
    QuestionItem(
      id: 'bah_pra_078',
      questionText: 'Museum seni terbesar di dunia di Paris tempat lukisan Mona Lisa dipamerkan adalah Museum:',
      options: ['Le Louvre', 'Musée d\'Orsay', 'Centre Pompidou', 'Rodin'],
      correctOptionIndex: 0,
      explanation: 'Musée du Louvre adalah museum seni terluas dunia.',
    ),
    QuestionItem(
      id: 'bah_pra_079',
      questionText: 'Monumen kejayaan perang di Paris yang dibangun atas perintah Napoleon Bonaparte adalah:',
      options: ['Arc de Triomphe', 'La Tour Eiffel', 'Panthéon', 'Sacré-Cœur'],
      correctOptionIndex: 0,
      explanation: 'Arc de Triomphe monumen kemenangan di Place Charles de Gaulle.',
    ),
    QuestionItem(
      id: 'bah_pra_080',
      questionText: 'Katedral bertema Gotik terkenal di Paris yang menginspirasi kisah Hunchback of Notre-Dame adalah:',
      options: ['Cathédrale Notre-Dame de Paris', 'Sacré-Cœur', 'Sainte-Chapelle', 'Saint-Denis'],
      correctOptionIndex: 0,
      explanation: 'Notre-Dame de Paris karya mahakarya Gotik.',
    ),
    QuestionItem(
      id: 'bah_pra_081',
      questionText: 'Hari Nasional Prancis (Bastille Day) diperingati setiap tanggal:',
      options: ['14 Juli (14 Juillet)', '1 Mei', '11 November', '8 Mei'],
      correctOptionIndex: 0,
      explanation: '14 Juli memperingati penyerbuan benteng Bastille 1789.',
    ),
    QuestionItem(
      id: 'bah_pra_082',
      questionText: 'Semboyan kebangsaan Republik Prancis "Liberté, Égalité, Fraternité" bermakna:',
      options: ['Kebebasan, Kesetaraan, Persaudaraan', 'Keadilan, Keamanan, Kemakmuran', 'Persatuan, Kehormatan, Kemenangan', 'Perdamaian, Kebenaran, Kebebasan'],
      correctOptionIndex: 0,
      explanation: 'Liberté, Égalité, Fraternité adalah moto resmi Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_083',
      questionText: 'Lagu kebangsaan resmi Republik Prancis diciptakan oleh Rouget de Lisle dinamakan:',
      options: ['La Marseillaise', 'L\'Hymne à l\'amour', 'Chanson de Roland', 'Sous le ciel de Paris'],
      correctOptionIndex: 0,
      explanation: 'La Marseillaise lagu kebangsaan Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_084',
      questionText: 'Roti tradisional khas Prancis berbentuk panjang renyah dinamakan:',
      options: ['Baguette', 'Croissant', 'Brioche', 'Eclair'],
      correctOptionIndex: 0,
      explanation: 'Baguette adalah roti panjang khas Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_085',
      questionText: 'Kue kering berlapis mentega berbentuk bulan sabit khas Prancis dinamakan:',
      options: ['Croissant', 'Baguette', 'Macaron', 'Soufflé'],
      correctOptionIndex: 0,
      explanation: 'Croissant roti berlapis berbentuk bulan sabit.',
    ),
    QuestionItem(
      id: 'bah_pra_086',
      questionText: 'Kue busa berwarna-warni terbuat dari tepung almond dan isian krim khas Prancis dinamakan:',
      options: ['Macaron', 'Croissant', 'Crêpe', 'Madeleine'],
      correctOptionIndex: 0,
      explanation: 'Macaron adalah kue bulat manis berwarna-warni.',
    ),
    QuestionItem(
      id: 'bah_pra_087',
      questionText: 'Kue dadar tipis khas Prancis yang bisa disajikan manis atau asin dinamakan:',
      options: ['Crêpe', 'Waffle', 'Pancake', 'Tarte'],
      correctOptionIndex: 0,
      explanation: 'Crêpe adalah kue dadar tipis khas Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_088',
      questionText: 'Organisasi internasional persatuan negara-negara pengguna Bahasa Prancis di dunia dinamakan:',
      options: ['La Francophonie (OIF)', 'Commonwealth', 'Uni Eropa', 'NATO'],
      correctOptionIndex: 0,
      explanation: 'La Francophonie (Organisation internationale de la Francophonie).',
    ),
    QuestionItem(
      id: 'bah_pra_089',
      questionText: 'Simbol tokoh wanita nasional allegoris Republik Prancis dinamakan:',
      options: ['Marianne', 'Joan of Arc', 'Marie Antoinette', 'Coco'],
      correctOptionIndex: 0,
      explanation: 'Marianne adalah personifikasi Republik Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_090',
      questionText: 'Pahlawan wanita suci Prancis abad ke-15 yang memimpin perang melawan Inggris adalah:',
      options: ['Jeanne d\'Arc (Joan of Arc)', 'Marie Curie', 'Coco Chanel', 'Edith Piaf'],
      correctOptionIndex: 0,
      explanation: 'Jeanne d\'Arc pahlawan wanita nasional Prancis.',
    ),
    QuestionItem(
      id: 'bah_pra_091',
      questionText: 'Ilmuwan wanita Prancis kelahiran Polandia peraih dua Hadiah Nobel penemu Radium adalah:',
      options: ['Marie Curie', 'Jeanne d\'Arc', 'Simone de Beauvoir', 'George Sand'],
      correctOptionIndex: 0,
      explanation: 'Marie Curie peraih Nobel Fisika dan Kimia.',
    ),
    QuestionItem(
      id: 'bah_pra_092',
      questionText: 'Perancang busana Prancis terkemuka pendiri rumah mode Chanel pelopor "Little Black Dress" adalah:',
      options: ['Coco Chanel (Gabrielle Chanel)', 'Christian Dior', 'Yves Saint Laurent', 'Hubert de Givenchy'],
      correctOptionIndex: 0,
      explanation: 'Coco Chanel tokoh revolusi busana wanita abad 20.',
    ),
    QuestionItem(
      id: 'bah_pra_093',
      questionText: 'Penyanyi legendaris Prancis pengarang lagu "La Vie en rose" dan "Non, je ne regrette rien" adalah:',
      options: ['Édith Piaf', 'Mireille Mathieu', 'France Gall', 'Vanessa Paradis'],
      correctOptionIndex: 0,
      explanation: 'Édith Piaf penyair dan vokalis chanson Prancis terbesar.',
    ),
    QuestionItem(
      id: 'bah_pra_094',
      questionText: 'Festival Film Internasional paling bergengsi di dunia yang diadakan di kota pesisir selatan Prancis dinamakan Festival Film:',
      options: ['Cannes (Festival de Cannes)', 'Venice', 'Berlin', 'Oscar'],
      correctOptionIndex: 0,
      explanation: 'Festival de Cannes memberi penghargaan Palme d\'Or.',
    ),
    QuestionItem(
      id: 'bah_pra_095',
      questionText: 'Hadiah penghargaan tertinggi pada Festival Film Cannes dinamakan:',
      options: ['Palme d\'Or (Palma Emas)', 'Golden Bear', 'Golden Lion', 'Oscar'],
      correctOptionIndex: 0,
      explanation: 'Palme d\'Or adalah trofi tertinggi Cannes.',
    ),
    QuestionItem(
      id: 'bah_pra_096',
      questionText: 'Tanda baca accent yang melengkung ke kanan atas huruf (seperti é) dinamakan:',
      options: ['Accent aigu', 'Accent grave', 'Accent circonflexe', 'Cédille'],
      correctOptionIndex: 0,
      explanation: 'Accent aigu (é) mengubah bunyi e menjadi pendek tegas.',
    ),
    QuestionItem(
      id: 'bah_pra_097',
      questionText: 'Tanda baca accent miring ke kiri atas vokal (seperti è, à, ù) dinamakan:',
      options: ['Accent grave', 'Accent aigu', 'Accent circonflexe', 'Tréma'],
      correctOptionIndex: 0,
      explanation: 'Accent grave (è, à, ù) menandai bunyi e terbuka/perbedaan kata.',
    ),
    QuestionItem(
      id: 'bah_pra_098',
      questionText: 'Tanda baca berbentuk topi di atas vokal (seperti ê, î, ô) dinamakan:',
      options: ['Accent circonflexe', 'Accent aigu', 'Accent grave', 'Cédille'],
      correctOptionIndex: 0,
      explanation: 'Accent circonflexe (̂) menandakan penghilangan huruf s historis.',
    ),
    QuestionItem(
      id: 'bah_pra_099',
      questionText: 'Tanda kail di bawah huruf c (ç) yang mengubah bunyinya menjadi "s" dinamakan:',
      options: ['Cédille (Ç)', 'Tréma', 'Accent aigu', 'Apostrophe'],
      correctOptionIndex: 0,
      explanation: 'Cédille (ç) mengubah huruf c keras menjadi lembut s.',
    ),
    QuestionItem(
      id: 'bah_pra_100',
      questionText: 'Tujuan utama mempelajari Bahasa Prancis pada jenjang pendidikan tinggi adalah untuk:',
      options: ['Menguasai komunikasi lisan/tulis, tata bahasa DELF, kebudayaan Francophonie, dan teknik penerjemahan internasional', 'Sekadar jalan-jalan ke Paris', 'Menghafal kosakata saja', 'Membaca tanpa aturan grammar'],
      correctOptionIndex: 0,
      explanation: 'Studi Bahasa Prancis membekali kompetensi komunikasi bisnis internasional, diplomatik, dan pemahaman kebudayaan global.',
    ),
  ];
}
