import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaJepangQuestions() {
  return const [
    QuestionItem(
      id: 'bah_jep_001',
      questionText: 'Huruf fonetis dasar Bahasa Jepang yang digunakan untuk menuliskan kata-kata asli Jepang dinamakan:',
      options: ['Hiragana (ひらがな)', 'Katakana', 'Kanji', 'Romaji'],
      correctOptionIndex: 0,
      explanation: 'Hiragana digunakan untuk kosa kata asli Jepang dan tata bahasa.',
    ),
    QuestionItem(
      id: 'bah_jep_002',
      questionText: 'Huruf fonetis yang digunakan khusus untuk menuliskan kata-kata serapan dari bahasa asing di Jepang dinamakan:',
      options: ['Katakana (カタカナ)', 'Hiragana', 'Kanji', 'Furigana'],
      correctOptionIndex: 0,
      explanation: 'Katakana digunakan untuk kata serapan asing (gairaigo).',
    ),
    QuestionItem(
      id: 'bah_jep_003',
      questionText: 'Huruf karakter lambang makna yang diserap dari Cina ke Jepang dinamakan:',
      options: ['Kanji (漢字)', 'Hiragana', 'Katakana', 'Romaji'],
      correctOptionIndex: 0,
      explanation: 'Kanji adalah karakter ideogram serapan dari Cina.',
    ),
    QuestionItem(
      id: 'bah_jep_004',
      questionText: 'Cara membaca karakter Kanji secara pengucapan asli Jepang dinamakan:',
      options: ['Kun\'yomi (訓読み)', 'On\'yomi', 'Romaji', 'Okurigana'],
      correctOptionIndex: 0,
      explanation: 'Kun\'yomi adalah bacaan cara Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_005',
      questionText: 'Cara membaca karakter Kanji secara pelafalan serapan bunyi Cina dinamakan:',
      options: ['On\'yomi (音読み)', 'Kun\'yomi', 'Okurigana', 'Furigana'],
      correctOptionIndex: 0,
      explanation: 'On\'yomi adalah bacaan cara Cina.',
    ),
    QuestionItem(
      id: 'bah_jep_006',
      questionText: 'Huruf hiragana kecil yang ditulis di atas/samping kanji untuk memandu cara baca dinamakan:',
      options: ['Furigana (ルビ)', 'Okurigana', 'Katakana', 'Dakuten'],
      correctOptionIndex: 0,
      explanation: 'Furigana adalah penunjuk fonetik di atas kanji.',
    ),
    QuestionItem(
      id: 'bah_jep_007',
      questionText: 'Partikel penanda subjek utama kalimat (Topik pembicaraan) adalah:',
      options: ['Wa (は)', 'Ga (が)', 'Wo (を)', 'Ni (に)'],
      correctOptionIndex: 0,
      explanation: 'Partikel Wa (ditulis は) menandai topik utama kalimat.',
    ),
    QuestionItem(
      id: 'bah_jep_008',
      questionText: 'Partikel penanda objek penderita langsung dari kata kerja transitif adalah:',
      options: ['Wo / O (を)', 'Wa', 'Ga', 'De'],
      correctOptionIndex: 0,
      explanation: 'Partikel Wo (ditulis を) menandai objek penderita.',
    ),
    QuestionItem(
      id: 'bah_jep_009',
      questionText: 'Partikel penanda tempat terjadinya suatu aktivitas perbuatan adalah:',
      options: ['De (で)', 'Ni', 'E', 'Kara'],
      correctOptionIndex: 0,
      explanation: 'Partikel De menunjukkan lokasi tempat berlangsungnya aksi.',
    ),
    QuestionItem(
      id: 'bah_jep_010',
      questionText: 'Partikel penanda tujuan arah pergerakan (ke / menuju) adalah:',
      options: ['E (へ) / Ni (に)', 'De', 'Wo', 'Wa'],
      correctOptionIndex: 0,
      explanation: 'Partikel E (ditulis へ) atau Ni penanda arah pergerakan.',
    ),
    QuestionItem(
      id: 'bah_jep_011',
      questionText: 'Ungkapan salam Bahasa Jepang yang berarti "Selamat Pagi" secara sopan adalah:',
      options: ['Ohayou gozaimasu (おはようございます)', 'Konnichiwa', 'Konbanwa', 'Oyasuminasai'],
      correctOptionIndex: 0,
      explanation: 'Ohayou gozaimasu berarti selamat pagi.',
    ),
    QuestionItem(
      id: 'bah_jep_012',
      questionText: 'Ungkapan salam Bahasa Jepang yang berarti "Selamat Siang / Halo" adalah:',
      options: ['Konnichiwa (こんにちは)', 'Konbanwa', 'Ohayou', 'Arigatou'],
      correctOptionIndex: 0,
      explanation: 'Konnichiwa adalah salam selamat siang.',
    ),
    QuestionItem(
      id: 'bah_jep_013',
      questionText: 'Ungkapan salam Bahasa Jepang yang berarti "Selamat Malam" saat bertemu adalah:',
      options: ['Konbanwa (こんばんは)', 'Konnichiwa', 'Oyasuminasai', 'Sayounara'],
      correctOptionIndex: 0,
      explanation: 'Konbanwa adalah salam selamat malam saat bertemu.',
    ),
    QuestionItem(
      id: 'bah_jep_014',
      questionText: 'Ungkapan salam selamat tidur sebelum beristirahat di malam hari adalah:',
      options: ['Oyasuminasai (おやすみなさい)', 'Konbanwa', 'Sayounara', 'Itadakimasu'],
      correctOptionIndex: 0,
      explanation: 'Oyasuminasai diucapkan sebelum tidur.',
    ),
    QuestionItem(
      id: 'bah_jep_015',
      questionText: 'Ungkapan yang diucapkan saat hendak makan (bermakna ucapan terima kasih atas makanan) adalah:',
      options: ['Itadakimasu (いただきます)', 'Gochisousama ashita', 'Sumimasen', 'Gomen nasai'],
      correctOptionIndex: 0,
      explanation: 'Itadakimasu diucapkan sebelum menyantap makanan.',
    ),
    QuestionItem(
      id: 'bah_jep_016',
      questionText: 'Ungkapan yang diucapkan setelah selesai makan adalah:',
      options: ['Gochisousama deshita (ごちそうさまでした)', 'Itadakimasu', 'Sumimasen', 'Otsukaresama'],
      correctOptionIndex: 0,
      explanation: 'Gochisousama deshita diucapkan setelah selesai makan.',
    ),
    QuestionItem(
      id: 'bah_jep_017',
      questionText: 'Ungkapan maaf atau untuk meminta perhatian seseorang secara sopan (Permisi/Maaf) adalah:',
      options: ['Sumimasen (すみません)', 'Arigatou', 'Douzo', 'Hai'],
      correctOptionIndex: 0,
      explanation: 'Sumimasen berarti permisi atau maaf.',
    ),
    QuestionItem(
      id: 'bah_jep_018',
      questionText: 'Ungkapan terima kasih sopan dalam Bahasa Jepang adalah:',
      options: ['Arigatou gozaimasu (ありがとうございます)', 'Doumo', 'Douitasashimashite', 'Sumimasen'],
      correctOptionIndex: 0,
      explanation: 'Arigatou gozaimasu ungkapan terima kasih formal.',
    ),
    QuestionItem(
      id: 'bah_jep_019',
      questionText: 'Jawaban sopan untuk ucapan terima kasih ("Sama-sama") adalah:',
      options: ['Douitasashimashite (どういたしまして)', 'Kochira koso', 'Hai douzo', 'Ii desu'],
      correctOptionIndex: 0,
      explanation: 'Douitasashimashite berarti sama-sama/kembali.',
    ),
    QuestionItem(
      id: 'bah_jep_020',
      questionText: 'Kata ganti orang pertama tunggal "Saya" ragam sopan standar adalah:',
      options: ['Watashi (私)', 'Boku', 'Ore', 'Anata'],
      correctOptionIndex: 0,
      explanation: 'Watashi adalah kata ganti saya yang sopan netral.',
    ),
    QuestionItem(
      id: 'bah_jep_021',
      questionText: 'Kata ganti orang pertama "Saya" yang umum digunakan laki-laki dalam situasi kasual adalah:',
      options: ['Boku (僕) / Ore (俺)', 'Watashi', 'Watakushi', 'Anata'],
      correctOptionIndex: 0,
      explanation: 'Boku/Ore digunakan pria dalam pergaulan santai.',
    ),
    QuestionItem(
      id: 'bah_jep_022',
      questionText: 'Kata ganti orang kedua "Anda / Kamu" adalah:',
      options: ['Anata (あなた)', 'Kimi', 'Omae', 'Watashi'],
      correctOptionIndex: 0,
      explanation: 'Anata berarti Anda/Kamu.',
    ),
    QuestionItem(
      id: 'bah_jep_023',
      questionText: 'Sebutan hormat yang ditambahkan di belakang nama orang lain (misal: Tanaka-san) adalah:',
      options: ['-san (さん)', '-sama', '-chan', '-kun'],
      correctOptionIndex: 0,
      explanation: '-san adalah akhiran kehormatan netral.',
    ),
    QuestionItem(
      id: 'bah_jep_024',
      questionText: 'Sebutan hormat tingkat tinggi yang ditambahkan di belakang nama pelanggan atau tamu adalah:',
      options: ['-sama (様)', '-san', '-dono', '-chan'],
      correctOptionIndex: 0,
      explanation: '-sama (様) digunakan untuk menghormati pelanggan (Okyaku-sama).',
    ),
    QuestionItem(
      id: 'bah_jep_025',
      questionText: 'Sebutan panggilan akrab yang biasa ditambahkan di belakang nama anak-anak atau wanita muda adalah:',
      options: ['-chan (ちゃん)', '-kun', '-san', '-sama'],
      correctOptionIndex: 0,
      explanation: '-chan panggilan sayang untuk anak/teman akrab.',
    ),
    QuestionItem(
      id: 'bah_jep_026',
      questionText: 'Angka 1 (Satu) dalam Bahasa Jepang disebut:',
      options: ['Ichi (一)', 'Ni', 'San', 'Yon'],
      correctOptionIndex: 0,
      explanation: 'Ichi berarti 1.',
    ),
    QuestionItem(
      id: 'bah_jep_027',
      questionText: 'Angka 2 (Dua) dalam Bahasa Jepang disebut:',
      options: ['Ni (二)', 'Ichi', 'San', 'Shi'],
      correctOptionIndex: 0,
      explanation: 'Ni berarti 2.',
    ),
    QuestionItem(
      id: 'bah_jep_028',
      questionText: 'Angka 3 (Tiga) dalam Bahasa Jepang disebut:',
      options: ['San (三)', 'Yon', 'Go', 'Roku'],
      correctOptionIndex: 0,
      explanation: 'San berarti 3.',
    ),
    QuestionItem(
      id: 'bah_jep_029',
      questionText: 'Angka 4 (Empat) dalam Bahasa Jepang dapat diucapkan sebagai:',
      options: ['Yon / Shi (四)', 'Go', 'Roku', 'Nana'],
      correctOptionIndex: 0,
      explanation: 'Angka 4 dibaca Yon atau Shi.',
    ),
    QuestionItem(
      id: 'bah_jep_030',
      questionText: 'Angka 10 (Sepuluh) dalam Bahasa Jepang disebut:',
      options: ['Juu (十)', 'Kyuu', 'Hachi', 'Nana'],
      correctOptionIndex: 0,
      explanation: 'Juu berarti 10.',
    ),
    QuestionItem(
      id: 'bah_jep_031',
      questionText: 'Angka 100 (Seratus) dalam Bahasa Jepang disebut:',
      options: ['Hyaku (百)', 'Sen', 'Man', 'Juu'],
      correctOptionIndex: 0,
      explanation: 'Hyaku berarti 100.',
    ),
    QuestionItem(
      id: 'bah_jep_032',
      questionText: 'Angka 1.000 (Seribu) dalam Bahasa Jepang disebut:',
      options: ['Sen (千)', 'Hyaku', 'Man', 'Oku'],
      correctOptionIndex: 0,
      explanation: 'Sen berarti 1.000.',
    ),
    QuestionItem(
      id: 'bah_jep_033',
      questionText: 'Angka 10.000 (Sepuluh Ribu) sebagai unit hitung dasar uang Jepang disebut:',
      options: ['Man (万)', 'Sen', 'Hyaku', 'Oku'],
      correctOptionIndex: 0,
      explanation: 'Man (万) bernilai 10.000 (Ichiman = 10.000 yen).',
    ),
    QuestionItem(
      id: 'bah_jep_034',
      questionText: 'Mata uang resmi negara Jepang dinamakan:',
      options: ['Yen (円)', 'Yuan', 'Won', 'Dollar'],
      correctOptionIndex: 0,
      explanation: 'Yen (En / 円) mata uang Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_035',
      questionText: 'Bentuk kata kerja sopan posisi waktu sekarang positif ditandai akhiran:',
      options: ['-masu (〜ます)', '-masen', '-mashita', '-masen deshita'],
      correctOptionIndex: 0,
      explanation: '-masu menandai bentuk positif sopan (Present/Future).',
    ),
    QuestionItem(
      id: 'bah_jep_036',
      questionText: 'Bentuk kata kerja sopan negatif posisi waktu sekarang ditandai akhiran:',
      options: ['-masen (〜ません)', '-masu', '-mashita', '-desu'],
      correctOptionIndex: 0,
      explanation: '-masen menandai bentuk negatif sopan.',
    ),
    QuestionItem(
      id: 'bah_jep_037',
      questionText: 'Bentuk kata kerja sopan positif posisi waktu lampau ditandai akhiran:',
      options: ['-mashita (〜ました)', '-masen deshita', '-masu', '-nai'],
      correctOptionIndex: 0,
      explanation: '-mashita menandai bentuk positif masa lalu (Past).',
    ),
    QuestionItem(
      id: 'bah_jep_038',
      questionText: 'Bentuk kata kerja sopan negatif posisi waktu lampau ditandai akhiran:',
      options: ['-masen deshita (〜ませんでした)', '-mashita', '-masu', '-nai'],
      correctOptionIndex: 0,
      explanation: '-masen deshita bentuk past negative sopan.',
    ),
    QuestionItem(
      id: 'bah_jep_039',
      questionText: 'Bentuk kata kerja sambung (Bentuk-Te / Te-kei) digunakan untuk:',
      options: ['Menghubungkan urutan perbuatan, memohon (Te kudasai), atau sedang berlangsung (Te iru)', 'Menutup kalimat', 'Menyatakan perintah kasar', 'Masa lalu negatif'],
      correctOptionIndex: 0,
      explanation: 'Bentuk Te-kei sangat multifungsi dalam tata bahasa Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_040',
      questionText: 'Pola kalimat "V-te kudasai" (〜てください) bermakna:',
      options: ['Tolong lakukan (Permohonan halus)', 'Jangan lakukan', 'Boleh melakukan', 'Tidak boleh melakukan'],
      correctOptionIndex: 0,
      explanation: 'Te kudasai meminta tolong secara sopan.',
    ),
    QuestionItem(
      id: 'bah_jep_041',
      questionText: 'Pola kalimat "V-te mo ii desu" (〜てもいいです) bermakna:',
      options: ['Boleh melakukan (Izin)', 'Dilarang melakukan', 'Harus melakukan', 'Tidak perlu melakukan'],
      correctOptionIndex: 0,
      explanation: 'Te mo ii desu memberikan izin perbuatan.',
    ),
    QuestionItem(
      id: 'bah_jep_042',
      questionText: 'Pola kalimat "V-te wa ikemasen" (〜てはいけません) bermakna:',
      options: ['Dilarang / Tidak boleh melakukan', 'Boleh melakukan', 'Silakan melakukan', 'Harus melakukan'],
      correctOptionIndex: 0,
      explanation: 'Te wa ikemasen menyatakan larangan keras.',
    ),
    QuestionItem(
      id: 'bah_jep_043',
      questionText: 'Pola kalimat "V-nai de kudasai" (〜ないでください) bermakna:',
      options: ['Tolong jangan lakukan', 'Silakan lakukan', 'Harus lakukan', 'Sudah dilakukan'],
      correctOptionIndex: 0,
      explanation: 'Nai de kudasai permohonan agar tidak melakukan sesuatu.',
    ),
    QuestionItem(
      id: 'bah_jep_044',
      questionText: 'Pola kalimat "V-nakereba narimasen" (〜なければなりません) bermakna:',
      options: ['Harus / Wajib dilakukan', 'Boleh tidak dilakukan', 'Dilarang lakukan', 'Mungkin dilakukan'],
      correctOptionIndex: 0,
      explanation: 'Nakereba narimasen menyatakan keharusan/kewajiban.',
    ),
    QuestionItem(
      id: 'bah_jep_045',
      questionText: 'Kata sifat dalam Bahasa Jepang dibagi menjadi dua kelompok yaitu Kata Sifat-I (I-keiyoushi) dan:',
      options: ['Kata Sifat-Na (Na-keiyoushi)', 'Kata Sifat-No', 'Kata Sifat-Ga', 'Kata Sifat-Da'],
      correctOptionIndex: 0,
      explanation: 'Adjektiva Jepang terbagi I-keiyoushi dan Na-keiyoushi.',
    ),
    QuestionItem(
      id: 'bah_jep_046',
      questionText: 'Bentuk negatif dari Kata Sifat-I "Oishii" (Enak) adalah:',
      options: ['Oishiku nai (おいしくない)', 'Oishii ja nai', 'Oishii deshita', 'Oishiku arimasen'],
      correctOptionIndex: 0,
      explanation: 'Kata sifat-I diubah negatif dengan mengganti ~i menjadi ~kunai.',
    ),
    QuestionItem(
      id: 'bah_jep_047',
      questionText: 'Bentuk negatif dari Kata Sifat-Na "Shizuka" (Tenang) adalah:',
      options: ['Shizuka ja nai / Shizuka dewamurimasen', 'Shizukaku nai', 'Shizukatai', 'Shizukana nai'],
      correctOptionIndex: 0,
      explanation: 'Kata sifat-Na diubah negatif dengan menambahkan ja nai / dewa arimasen.',
    ),
    QuestionItem(
      id: 'bah_jep_048',
      questionText: 'Bahasa halus hormat yang digunakan untuk meninggikan derajat lawan bicara/atasan dinamakan Bahasa:',
      options: ['Sonkeigo (尊敬語)', 'Kenjougo', 'Teineigo', 'Kantamushi'],
      correctOptionIndex: 0,
      explanation: 'Sonkeigo adalah bahasa hormat mengagungkan atasan.',
    ),
    QuestionItem(
      id: 'bah_jep_049',
      questionText: 'Bahasa halus merendahkan diri sendiri di hadapan atasan/pelanggan dinamakan Bahasa:',
      options: ['Kenjougo (謙譲語)', 'Sonkeigo', 'Teineigo', 'Tameguchi'],
      correctOptionIndex: 0,
      explanation: 'Kenjougo adalah bahasa merendahkan diri.',
    ),
    QuestionItem(
      id: 'bah_jep_050',
      questionText: 'Bahasa sopan standar menggunakan desu/masu dinamakan Bahasa:',
      options: ['Teineigo (丁寧語)', 'Sonkeigo', 'Kenjougo', 'Kansai-ben'],
      correctOptionIndex: 0,
      explanation: 'Teineigo adalah ragam sopan umum formal.',
    ),
    QuestionItem(
      id: 'bah_jep_051',
      questionText: 'Ujian kemampuan standar resmi Bahasa Jepang internasional untuk penutur asing dinamakan:',
      options: ['JLPT (Japanese Language Proficiency Test / Noryokushiken)', 'TOEIC', 'HSK', 'TOPIK'],
      correctOptionIndex: 0,
      explanation: 'JLPT / Nihongo Noryokushiken (N5 hingga N1).',
    ),
    QuestionItem(
      id: 'bah_jep_052',
      questionText: 'Tingkat kemahiran tertinggi pada ujian JLPT adalah tingkat:',
      options: ['N1', 'N5', 'N3', 'Level 100'],
      correctOptionIndex: 0,
      explanation: 'JLPT N1 adalah tingkat kemahiran tertinggi.',
    ),
    QuestionItem(
      id: 'bah_jep_053',
      questionText: 'Tingkat kemahiran kelulusan dasar pemula pada ujian JLPT adalah tingkat:',
      options: ['N5', 'N1', 'N3', 'Basic 1'],
      correctOptionIndex: 0,
      explanation: 'JLPT N5 adalah tingkat dasar pemula.',
    ),
    QuestionItem(
      id: 'bah_jep_054',
      questionText: 'Arti kosakata "Gakkou" (学校) adalah:',
      options: ['Sekolah', 'Rumah', 'Stasiun', 'Toko'],
      correctOptionIndex: 0,
      explanation: 'Gakkou berarti sekolah.',
    ),
    QuestionItem(
      id: 'bah_jep_055',
      questionText: 'Arti kosakata "Eki" (駅) adalah:',
      options: ['Stasiun Kereta', 'Bandara', 'Halte', 'Pelabuhan'],
      correctOptionIndex: 0,
      explanation: 'Eki berarti stasiun.',
    ),
    QuestionItem(
      id: 'bah_jep_056',
      questionText: 'Arti kosakata "Uchi" / "Ie" (家) adalah:',
      options: ['Rumah / Tempat Tinggal', 'Kantin', 'Kamar', 'Taman'],
      correctOptionIndex: 0,
      explanation: 'Uchi/Ie berarti rumah.',
    ),
    QuestionItem(
      id: 'bah_jep_057',
      questionText: 'Arti kosakata "Hon" (本) adalah:',
      options: ['Buku', 'Pena', 'Kertas', 'Pensil'],
      correctOptionIndex: 0,
      explanation: 'Hon berarti buku.',
    ),
    QuestionItem(
      id: 'bah_jep_058',
      questionText: 'Arti kosakata "Kuruma" (車) adalah:',
      options: ['Mobil', 'Sepeda Motor', 'Kereta', 'Pesawat'],
      correctOptionIndex: 0,
      explanation: 'Kuruma berarti mobil/kendaraan.',
    ),
    QuestionItem(
      id: 'bah_jep_059',
      questionText: 'Arti kosakata "Densha" (電車) adalah:',
      options: ['Kereta Listrik', 'Mobil', 'Bus', 'Sepeda'],
      correctOptionIndex: 0,
      explanation: 'Densha berarti kereta api listrik.',
    ),
    QuestionItem(
      id: 'bah_jep_060',
      questionText: 'Arti kosakata "飛行機" (Hikouki) adalah:',
      options: ['Pesawat Terbang', 'Kapal Laut', 'Taksi', 'Helikopter'],
      correctOptionIndex: 0,
      explanation: 'Hikouki berarti pesawat terbang.',
    ),
    QuestionItem(
      id: 'bah_jep_061',
      questionText: 'Arti kosakata "Mizu" (水) adalah:',
      options: ['Air Minum / Air Dingin', 'Teh', 'Kopi', 'Susu'],
      correctOptionIndex: 0,
      explanation: 'Mizu berarti air minum.',
    ),
    QuestionItem(
      id: 'bah_jep_062',
      questionText: 'Teh hijau hangat khas Jepang dinamakan:',
      options: ['Ocha (お茶)', 'Koucha', 'Sake', 'Kohii'],
      correctOptionIndex: 0,
      explanation: 'Ocha adalah teh hijau khas Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_063',
      questionText: 'Arti kosakata "Tabemono" (食べ物) adalah:',
      options: ['Makanan', 'Minuman', 'Pakaian', 'Buah'],
      correctOptionIndex: 0,
      explanation: 'Tabemono bermakna makanan.',
    ),
    QuestionItem(
      id: 'bah_jep_064',
      questionText: 'Arti kosakata "Nomimono" (飲み物) adalah:',
      options: ['Minuman', 'Makanan', 'Obat', 'Masakan'],
      correctOptionIndex: 0,
      explanation: 'Nomimono bermakna minuman.',
    ),
    QuestionItem(
      id: 'bah_jep_065',
      questionText: 'Hari Minggu dalam Bahasa Jepang disebut:',
      options: ['Nichiyoubi (日曜日)', 'Getsuyoubi', 'Kayoubi', 'Suiyoubi'],
      correctOptionIndex: 0,
      explanation: 'Nichiyoubi adalah hari Minggu (Hari Matahari).',
    ),
    QuestionItem(
      id: 'bah_jep_066',
      questionText: 'Hari Senin dalam Bahasa Jepang disebut:',
      options: ['Getsuyoubi (月曜日)', 'Nichiyoubi', 'Mokuyoubi', 'Kinyoubi'],
      correctOptionIndex: 0,
      explanation: 'Getsuyoubi adalah hari Senin (Hari Bulan).',
    ),
    QuestionItem(
      id: 'bah_jep_067',
      questionText: 'Hari Selasa dalam Bahasa Jepang disebut:',
      options: ['Kayoubi (火曜日)', 'Getsuyoubi', 'Suiyoubi', 'Doyoubi'],
      correctOptionIndex: 0,
      explanation: 'Kayoubi adalah hari Selasa (Hari Api).',
    ),
    QuestionItem(
      id: 'bah_jep_068',
      questionText: 'Hari Rabu dalam Bahasa Jepang disebut:',
      options: ['Suiyoubi (水曜日)', 'Kayoubi', 'Mokuyoubi', 'Nichiyoubi'],
      correctOptionIndex: 0,
      explanation: 'Suiyoubi adalah hari Rabu (Hari Air).',
    ),
    QuestionItem(
      id: 'bah_jep_069',
      questionText: 'Hari Kamis dalam Bahasa Jepang disebut:',
      options: ['Mokuyoubi (木曜日)', 'Suiyoubi', 'Kinyoubi', 'Doyoubi'],
      correctOptionIndex: 0,
      explanation: 'Mokuyoubi adalah hari Kamis (Hari Kayu/Pohon).',
    ),
    QuestionItem(
      id: 'bah_jep_070',
      questionText: 'Hari Jumat dalam Bahasa Jepang disebut:',
      options: ['Kinyoubi (金曜日)', 'Mokuyoubi', 'Doyoubi', 'Getsuyoubi'],
      correctOptionIndex: 0,
      explanation: 'Kinyoubi adalah hari Jumat (Hari Logam/Emas).',
    ),
    QuestionItem(
      id: 'bah_jep_071',
      questionText: 'Hari Sabtu dalam Bahasa Jepang disebut:',
      options: ['Doyoubi (土曜日)', 'Kinyoubi', 'Nichiyoubi', 'Kayoubi'],
      correctOptionIndex: 0,
      explanation: 'Doyoubi adalah hari Sabtu (Hari Tanah).',
    ),
    QuestionItem(
      id: 'bah_jep_072',
      questionText: 'Musim Semi di Jepang dinamakan:',
      options: ['Haru (春)', 'Natsu', 'Aki', 'Fuyu'],
      correctOptionIndex: 0,
      explanation: 'Haru adalah musim semi (mekarnya bunga sakura).',
    ),
    QuestionItem(
      id: 'bah_jep_073',
      questionText: 'Musim Panas di Jepang dinamakan:',
      options: ['Natsu (夏)', 'Haru', 'Aki', 'Fuyu'],
      correctOptionIndex: 0,
      explanation: 'Natsu adalah musim panas.',
    ),
    QuestionItem(
      id: 'bah_jep_074',
      questionText: 'Musim Gugur di Jepang dinamakan:',
      options: ['Aki (秋)', 'Natsu', 'Fuyu', 'Haru'],
      correctOptionIndex: 0,
      explanation: 'Aki adalah musim gugur (daun momiji memerah).',
    ),
    QuestionItem(
      id: 'bah_jep_075',
      questionText: 'Musim Dingin / Salju di Jepang dinamakan:',
      options: ['Fuyu (冬)', 'Aki', 'Natsu', 'Haru'],
      correctOptionIndex: 0,
      explanation: 'Fuyu adalah musim dingin.',
    ),
    QuestionItem(
      id: 'bah_jep_076',
      questionText: 'Tradisi piknik menikmati keindahan mekarnya bunga sakura di musim semi disebut:',
      options: ['Hanami (花見)', 'Tsukimi', 'Momijigari', 'Matsuri'],
      correctOptionIndex: 0,
      explanation: 'Hanami adalah tradisi menonton mekarnya sakura.',
    ),
    QuestionItem(
      id: 'bah_jep_077',
      questionText: 'Tradisi piknik menikmati daun gugur memerah di musim gugur disebut:',
      options: ['Momijigari (紅葉狩り)', 'Hanami', 'Tanabata', 'Hatsumode'],
      correctOptionIndex: 0,
      explanation: 'Momijigari menikmati indahnya daun gugur momiji.',
    ),
    QuestionItem(
      id: 'bah_jep_078',
      questionText: 'Pakaian tradisional khas Jepang yang dipakai pada festival musim panas atau acara resmi adalah:',
      options: ['Kimono / Yukata', 'Hanbok', 'Cheongsam', 'Saree'],
      correctOptionIndex: 0,
      explanation: 'Kimono dan Yukata adalah busana tradisional Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_079',
      questionText: 'Sabuk kain lebar pelengkap ikatan pakaian Kimono/Yukata dinamakan:',
      options: ['Obi (帯)', 'Geta', 'Tabi', 'Haori'],
      correctOptionIndex: 0,
      explanation: 'Obi adalah sabuk pengikat Kimono.',
    ),
    QuestionItem(
      id: 'bah_jep_080',
      questionText: 'Sandal kayu tradisional khas Jepang dinamakan:',
      options: ['Geta (下駄)', 'Zouri', 'Tabi', 'Uwabaki'],
      correctOptionIndex: 0,
      explanation: 'Geta adalah sandal kayu bertapak tradisional.',
    ),
    QuestionItem(
      id: 'bah_jep_081',
      questionText: 'Seni merangkai bunga tradisional khas Jepang dinamakan:',
      options: ['Ikebana (生け花)', 'Origami', 'Bonsai', 'Chado'],
      correctOptionIndex: 0,
      explanation: 'Ikebana adalah seni merangkai bunga estetis.',
    ),
    QuestionItem(
      id: 'bah_jep_082',
      questionText: 'Upacara minum teh tradisional Jepang yang sarat nilai filosofis dinamakan:',
      options: ['Chado / Sado (茶道)', 'Ikebana', 'Shodo', 'Kabuki'],
      correctOptionIndex: 0,
      explanation: 'Chado adalah seni upacara minum teh tradisional.',
    ),
    QuestionItem(
      id: 'bah_jep_083',
      questionText: 'Seni kaligrafi kuas tinta khas Jepang dinamakan:',
      options: ['Shodo (書道)', 'Ikebana', 'Kendo', 'Judo'],
      correctOptionIndex: 0,
      explanation: 'Shodo adalah seni menulis indah dengan kuas tinta.',
    ),
    QuestionItem(
      id: 'bah_jep_084',
      questionText: 'Kartu ucapan selamat Tahun Baru di Jepang yang dikirimkan lewat pos dinamakan:',
      options: ['Nengajou (年賀状)', 'Koushin', 'Etegami', 'Kitte'],
      correctOptionIndex: 0,
      explanation: 'Nengajou adalah kartu pos khusus ucapan Tahun Baru.',
    ),
    QuestionItem(
      id: 'bah_jep_085',
      questionText: 'Tradisi ziarah pertama kali ke kuil di awal tahun baru dinamakan:',
      options: ['Hatsumode (初詣)', 'Hanami', 'Omikuji', 'Ema'],
      correctOptionIndex: 0,
      explanation: 'Hatsumode adalah kunjungan kuil pertama tahun baru.',
    ),
    QuestionItem(
      id: 'bah_jep_086',
      questionText: 'Papan kayu kecil di kuil Jepang tempat menuliskan doa dan harapan dinamakan:',
      options: ['Ema (絵馬)', 'Omikuji', 'Omamori', 'Torii'],
      correctOptionIndex: 0,
      explanation: 'Ema adalah papan kayu permohonan di kuil.',
    ),
    QuestionItem(
      id: 'bah_jep_087',
      questionText: 'Kertas ramalan keberuntungan yang ditarik di kuil Jepang dinamakan:',
      options: ['Omikuji (おみくじ)', 'Omamori', 'Ema', 'Mikoshi'],
      correctOptionIndex: 0,
      explanation: 'Omikuji adalah gulungan kertas ramalan kuil.',
    ),
    QuestionItem(
      id: 'bah_jep_088',
      questionText: 'Jimat pelindung keberuntungan dari kuil Jepang dinamakan:',
      options: ['Omamori (お守り)', 'Omikuji', 'Ema', 'Sensu'],
      correctOptionIndex: 0,
      explanation: 'Omamori adalah kantong jimat keberuntungan.',
    ),
    QuestionItem(
      id: 'bah_jep_089',
      questionText: 'Gapura gerbang merah khas kuil Shinto Jepang dinamakan:',
      options: ['Torii (鳥居)', 'Pagoda', 'Shomen', 'Fusuma'],
      correctOptionIndex: 0,
      explanation: 'Torii adalah gerbang pembatas kuil Shinto.',
    ),
    QuestionItem(
      id: 'bah_jep_090',
      questionText: 'Gaya komunikasi tidak langsung orang Jepang yang mengutamakan keharmonisan dinamakan:',
      options: ['Aimai (曖昧) / Wa', 'Honne', 'Tatemae', 'Gaijin'],
      correctOptionIndex: 0,
      explanation: 'Aimai adalah komunikasi samar/halus menjaga keharmonisan (Wa).',
    ),
    QuestionItem(
      id: 'bah_jep_091',
      questionText: 'Konsep perbedaan antara perasaan sejatinya di batin (Honne) dan sikap luar yang ditampilkan di publik (Tatemae) dinamakan:',
      options: ['Honne (本音) dan Tatemae (建前)', 'Senpai dan Kouhai', 'Uchi dan Soto', 'Giri dan Ninjo'],
      correctOptionIndex: 0,
      explanation: 'Honne (perasaan asli) vs Tatemae (sikap sosial publik).',
    ),
    QuestionItem(
      id: 'bah_jep_092',
      questionText: 'Konsep hubungan kelompok dalam (Uchi) dan kelompok luar (Soto) berpengaruh pada:',
      options: ['Penggunaan tingkatan ragam bahasa sopan dan honorifik kebahasaan', 'Cara makan', 'Pakaian', 'Jadwal kerja'],
      correctOptionIndex: 0,
      explanation: 'Uchi-Soto menentukan pemilihan bahasa sopan/keigo.',
    ),
    QuestionItem(
      id: 'bah_jep_093',
      questionText: 'Hubungan hirarki senior (Senpai) dan junior (Kouhai) sangat kental pada budaya:',
      options: ['Persekolahan dan Dunia Kerja Jepang', 'Perdagangan bebas', 'Pariwisata murni', 'Perjalanan luar negeri'],
      correctOptionIndex: 0,
      explanation: 'Senpai-Kouhai mendasari hubungan senioritas Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_094',
      questionText: 'Ungkapan salam yang diucapkan saat meninggalkan rumah/kantor untuk pergi ("Saya pergi dulu") adalah:',
      options: ['Ittekimasu (いってきます)', 'Itterasshai', 'Tadaima', 'Okaeri'],
      correctOptionIndex: 0,
      explanation: 'Ittekimasu diucapkan orang yang hendak berangkat.',
    ),
    QuestionItem(
      id: 'bah_jep_095',
      questionText: 'Jawaban bagi orang yang pergi ("Selamat jalan / Hati-hati") adalah:',
      options: ['Itterasshai (いってらっしゃい)', 'Ittekimasu', 'Tadaima', 'Okaeri'],
      correctOptionIndex: 0,
      explanation: 'Itterasshai diucapkan melepas orang pergi.',
    ),
    QuestionItem(
      id: 'bah_jep_096',
      questionText: 'Ungkapan yang diucapkan saat tiba kembali di rumah ("Saya pulang") adalah:',
      options: ['Tadaima (ただいま)', 'Okaeri', 'Ittekimasu', 'Irasshaimase'],
      correctOptionIndex: 0,
      explanation: 'Tadaima diucapkan saat baru sampai rumah.',
    ),
    QuestionItem(
      id: 'bah_jep_097',
      questionText: 'Jawaban menyambut orang yang baru pulang ke rumah ("Selamat datang kembali") adalah:',
      options: ['Okaerinasai (おかえりなさい)', 'Tadaima', 'Irasshaimase', 'Otsukaresama'],
      correctOptionIndex: 0,
      explanation: 'Okaerinasai diucapkan menyambut anggota keluarga pulang.',
    ),
    QuestionItem(
      id: 'bah_jep_098',
      questionText: 'Ungkapan ucapan kerja keras atas selesainya suatu pekerjaan ("Terima kasih atas kerja kerasnya") adalah:',
      options: ['Otsukaresama deshita (お疲れ様でした)', 'Gochisousama', 'Sumimasen', 'Shitsurei shimasu'],
      correctOptionIndex: 0,
      explanation: 'Otsukaresama deshita ucapan apresiasi rekan kerja.',
    ),
    QuestionItem(
      id: 'bah_jep_099',
      questionText: 'Kereta cepat super futuristik ikonik milik Jepang dinamakan:',
      options: ['Shinkansen (新幹線)', 'Kintetsu', 'Yamanote', 'Bullet Sub'],
      correctOptionIndex: 0,
      explanation: 'Shinkansen adalah kereta api super cepat Jepang.',
    ),
    QuestionItem(
      id: 'bah_jep_100',
      questionText: 'Tujuan utama mempelajari Bahasa Jepang pada jenjang pendidikan tinggi adalah untuk:',
      options: ['Menguasai komunikasi lisan/tulisan, tata bahasa standar JLPT, kebudayaan bisnis Jepang, dan teknik penerjemahan', 'Menghafal anime saja', 'Membaca komik tanpa teori', 'Sekadar liburan ke Jepang'],
      correctOptionIndex: 0,
      explanation: 'Studi Bahasa Jepang membentuk kompetensi linguistik, kebudayaan, dan komunikasi profesional global.',
    ),
  ];
}
