import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaKoreaQuestions() {
  return const [
    QuestionItem(
      id: 'bah_kor_001',
      questionText: 'Sistem alfabet tulisan resmi Bahasa Korea yang diciptakan oleh Raja Sejong Yang Agung pada tahun 1443 dinamakan:',
      options: ['Hangeul (한글)', 'Hanja', 'Kanji', 'Hiragana'],
      correctOptionIndex: 0,
      explanation: 'Hangeul adalah abjad Korea yang diciptakan Raja Sejong.',
    ),
    QuestionItem(
      id: 'bah_kor_002',
      questionText: 'Naskah pengumuman penciptaan abjad Hangeul oleh Raja Sejong yang diakui UNESCO sebagai warisan dunia dinamakan:',
      options: ['Hunminjeongeum (훈민정음)', 'Samguk Yusa', 'Joseon Wangjo Sillok', 'Goryeosa'],
      correctOptionIndex: 0,
      explanation: 'Hunminjeongeum bermakna "Bunyi yang tepat untuk diajarkan kepada rakyat".',
    ),
    QuestionItem(
      id: 'bah_kor_003',
      questionText: 'Karakter aksara Cina yang digunakan dalam sejarah bahasa dan istilah resmi Korea dinamakan:',
      options: ['Hanja (한자)', 'Hangeul', 'Kana', 'Pinyin'],
      correctOptionIndex: 0,
      explanation: 'Hanja adalah istilah untuk karakter Cina di Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_004',
      questionText: 'Jumlah huruf vokal dasar (단모음) dalam abjad Hangeul Korea adalah:',
      options: ['10 Vokal Utama (ㅏ, ㅑ, ㅓ, ㅕ, ㅗ, ㅛ, ㅜ, ㅠ, ㅡ, ㅣ)', '5', '14', '21'],
      correctOptionIndex: 0,
      explanation: 'Hangeul memiliki 10 vokal dasar utama.',
    ),
    QuestionItem(
      id: 'bah_kor_005',
      questionText: 'Jumlah konsonan dasar (자음) dalam abjad Hangeul Korea adalah:',
      options: ['14 Konsonan Dasar (ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅅ, ㅇ, ㅈ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ)', '10', '5', '19'],
      correctOptionIndex: 0,
      explanation: 'Hangeul memiliki 14 konsonan dasar.',
    ),
    QuestionItem(
      id: 'bah_kor_006',
      questionText: 'Konsonan matian yang terletak di bagian bawah suku kata Hangeul dinamakan:',
      options: ['Batchim (받침)', 'Joun', 'Choseong', 'Jungseong'],
      correctOptionIndex: 0,
      explanation: 'Batchim adalah konsonan akhir (bawah) dalam blok suku kata.',
    ),
    QuestionItem(
      id: 'bah_kor_007',
      questionText: 'Kata sapaan Bahasa Korea yang paling umum dan sopan untuk "Halo / Selamat Pagi/Siang/Malam" adalah:',
      options: ['Annyeonghaseyo (안녕하세요)', 'Annyeong', 'Annyeonghigaseyo', 'Gamsahamnida'],
      correctOptionIndex: 0,
      explanation: 'Annyeonghaseyo adalah salam sopan standar.',
    ),
    QuestionItem(
      id: 'bah_kor_008',
      questionText: 'Kata sapaan informal "Halo / Dah" yang hanya digunakan kepada teman akrab atau orang lebih muda adalah:',
      options: ['Annyeong (안녕)', 'Annyeonghaseyo', 'Annyeonghasimnika', 'Yeoboseyo'],
      correctOptionIndex: 0,
      explanation: 'Annyeong adalah sapaan santai (banmal).',
    ),
    QuestionItem(
      id: 'bah_kor_009',
      questionText: 'Salam perpisahan yang diucapkan kepada orang yang AKAN PERGI ("Selamat jalan") adalah:',
      options: ['Annyeonghi gaseyo (안녕히 가세요)', 'Annyeonghi gyeseyo', 'Annyeong', 'Eoso oseyo'],
      correctOptionIndex: 0,
      explanation: 'Annyeonghi gaseyo diucapkan melepas orang yang berjalan pergi (gaseyo = pergilah).',
    ),
    QuestionItem(
      id: 'bah_kor_010',
      questionText: 'Salam perpisahan yang diucapkan oleh orang yang pergi kepada orang yang TINGGAL ("Selamat tinggal") adalah:',
      options: ['Annyeonghi gyeseyo (안녕히 계세요)', 'Annyeonghi gaseyo', 'Jal jineyo', 'Tto manayo'],
      correctOptionIndex: 0,
      explanation: 'Annyeonghi gyeseyo diucapkan kepada orang yang menetap/tinggal (gyeseyo = tinggallah).',
    ),
    QuestionItem(
      id: 'bah_kor_011',
      questionText: 'Ungkapan terima kasih paling resmi dan formal dalam Bahasa Korea adalah:',
      options: ['Gamsahamnida (감사합니다)', 'Gomawoyo', 'Gomawo', 'Cheonmaneyo'],
      correctOptionIndex: 0,
      explanation: 'Gamsahamnida adalah ungkapan terima kasih formal.',
    ),
    QuestionItem(
      id: 'bah_kor_012',
      questionText: 'Ungkapan terima kasih santai antarteman sebaya adalah:',
      options: ['Gomawo (고마워)', 'Gamsahamnida', 'Sumida', 'Mianhae'],
      correctOptionIndex: 0,
      explanation: 'Gomawo adalah terima kasih santai (banmal).',
    ),
    QuestionItem(
      id: 'bah_kor_013',
      questionText: 'Jawaban sopan untuk ucapan terima kasih ("Sama-sama / Tidak apa-apa") adalah:',
      options: ['Cheonmaneyo (천만에요) / Anieyo (아니에요)', 'Gamsahamnida', 'Ne', 'Yeoboseyo'],
      correctOptionIndex: 0,
      explanation: 'Cheonmaneyo / Anieyo bermakna sama-sama.',
    ),
    QuestionItem(
      id: 'bah_kor_014',
      questionText: 'Ungkapan minta maaf secara sopan dan formal adalah:',
      options: [' 죄송합니다 (Joesonghamnida) / 미안합니다 (Mianhamnida)', 'Mianhae', 'Gwaenchanayo', 'Annyeong'],
      correctOptionIndex: 0,
      explanation: 'Joesonghamnida / Mianhamnida adalah permohonan maaf formal.',
    ),
    QuestionItem(
      id: 'bah_kor_015',
      questionText: 'Ungkapan menenangkan atau menjawab maaf ("Tidak apa-apa / Garis besar oke") adalah:',
      options: ['Gwaenchanayo (괜찮아요)', 'Joesongto', 'Anieyo', 'Mian'],
      correctOptionIndex: 0,
      explanation: 'Gwaenchanayo bermakna tidak apa-apa.',
    ),
    QuestionItem(
      id: 'bah_kor_016',
      questionText: 'Ungkapan menjawab telepon dalam Bahasa Korea ("Halo?") adalah:',
      options: ['Yeoboseyo (여보세요)', 'Annyeong', 'Eoso oseyo', 'Yeboseo'],
      correctOptionIndex: 0,
      explanation: 'Yeoboseyo diucapkan saat mengangkat telepon.',
    ),
    QuestionItem(
      id: 'bah_kor_017',
      questionText: 'Ungkapan ucapan "Selamat Makan" sebelum menyantap hidangan adalah:',
      options: ['Jal meokgesseumnida (잘 먹겠습니다)', 'Jal meogossemnida', 'Masisseoyo', 'B 배부폐yo'],
      correctOptionIndex: 0,
      explanation: 'Jal meokgesseumnida diucapkan sebelum makan.',
    ),
    QuestionItem(
      id: 'bah_kor_018',
      questionText: 'Ungkapan ucapan terima kasih setelah selesai makan adalah:',
      options: ['Jal meogossemnida (잘 먹었습니다)', 'Jal meokgesseumnida', 'Masissumnida', 'Geonbae'],
      correctOptionIndex: 0,
      explanation: 'Jal meogossemnida diucapkan setelah selesai makan.',
    ),
    QuestionItem(
      id: 'bah_kor_019',
      questionText: 'Kata "Ya" ragam formal dalam Bahasa Korea adalah:',
      options: ['Ne (네) / Ye (예)', 'Anio', 'Eung', 'Aniya'],
      correctOptionIndex: 0,
      explanation: 'Ne / Ye bermakna Ya.',
    ),
    QuestionItem(
      id: 'bah_kor_020',
      questionText: 'Kata "Tidak / Bukan" ragam sopan adalah:',
      options: ['Anio (아니오) / Anieyo (아니에요)', 'Ne', 'Ye', 'Eung'],
      correctOptionIndex: 0,
      explanation: 'Anio / Anieyo bermakna Tidak / Bukan.',
    ),
    QuestionItem(
      id: 'bah_kor_021',
      questionText: 'Partikel penanda subjek topik utama (Topic marker) adalah:',
      options: ['-eun / -neun (은/는)', '-i / -ga', '-eul / -leul', '-eseo'],
      correctOptionIndex: 0,
      explanation: '-eun (setelah konsonan) / -neun (setelah vokal) penanda topik.',
    ),
    QuestionItem(
      id: 'bah_kor_022',
      questionText: 'Partikel penanda subjek gramatikal (Subject marker) adalah:',
      options: ['-i / -ga (이/가)', '-eun / -neun', '-eul / -leul', '-e'],
      correctOptionIndex: 0,
      explanation: '-i (setelah konsonan) / -ga (setelah vokal) penanda subjek.',
    ),
    QuestionItem(
      id: 'bah_kor_023',
      questionText: 'Partikel penanda objek penderita langsung (Object marker) adalah:',
      options: ['-eul / -leul (을/를)', '-i / -ga', '-eun / -neun', '-ro'],
      correctOptionIndex: 0,
      explanation: '-eul (setelah konsonan) / -leul (setelah vokal) penanda objek.',
    ),
    QuestionItem(
      id: 'bah_kor_024',
      questionText: 'Partikel penanda tempat keberadaan atau waktu (di/pada/ke) adalah:',
      options: ['-e (에)', '-eseo', '-hanteo', '-buteo'],
      correctOptionIndex: 0,
      explanation: '-e menandai posisi diam, waktu, atau arah tujuan.',
    ),
    QuestionItem(
      id: 'bah_kor_025',
      questionText: 'Partikel penanda tempat berlangsungnya suatu aktivitas perbuatan adalah:',
      options: ['-eseo (에서)', '-e', '-kkaji', '-do'],
      correctOptionIndex: 0,
      explanation: '-eseo menandai lokasi terjadinya aksi aktif.',
    ),
    QuestionItem(
      id: 'bah_kor_026',
      questionText: 'Pola tata bahasa formal sopan paling tinggi akhiran kalimat berita adalah:',
      options: ['-mnida / -seumnida (입니다 / 습니다)', '-ayo / -eoyo', '-ya', '-seon'],
      correctOptionIndex: 0,
      explanation: '-mnida/-seumnida adalah akhiran formal tertinggi (seupnida style).',
    ),
    QuestionItem(
      id: 'bah_kor_027',
      questionText: 'Pola tata bahasa sopan umum informal sehari-hari akhiran kalimat adalah:',
      options: ['-ayo / -eoyo (아/어요)', '-seumnida', '-da', '-ra'],
      correctOptionIndex: 0,
      explanation: '-ayo/-eoyo adalah ragam sopan kasual (haeyo-che).',
    ),
    QuestionItem(
      id: 'bah_kor_028',
      questionText: 'Ragam bahasa tidak sopan / santai sesama teman akrab atau orang lebih muda dinamakan:',
      options: ['Banmal (반말)', 'Jondietmal', 'Honorifik', 'Saenghwal'],
      correctOptionIndex: 0,
      explanation: 'Banmal adalah ragam bahasa santai tanpa akhiran honorifik.',
    ),
    QuestionItem(
      id: 'bah_kor_029',
      questionText: 'Ragam bahasa halus dan sangat menghormati lawan bicara yang lebih tua/tinggi dinamakan:',
      options: ['Jondietmal (존댓말)', 'Banmal', 'Satoori', 'Guk-eo'],
      correctOptionIndex: 0,
      explanation: 'Jondietmal adalah ragam bahasa sopan menghormati.',
    ),
    QuestionItem(
      id: 'bah_kor_030',
      questionText: 'Sebutan panggilan dari perempuan kepada kakak laki-laki kandung/akrab adalah:',
      options: ['Oppa (오빠)', 'Hyung', 'Noona', 'Unnie'],
      correctOptionIndex: 0,
      explanation: 'Oppa dipanggil oleh perempuan kepada kakak laki-laki.',
    ),
    QuestionItem(
      id: 'bah_kor_031',
      questionText: 'Sebutan panggilan dari laki-laki kepada kakak laki-laki kandung/akrab adalah:',
      options: ['Hyung (형)', 'Oppa', 'Noona', 'Sunbae'],
      correctOptionIndex: 0,
      explanation: 'Hyung dipanggil oleh laki-laki kepada kakak laki-laki.',
    ),
    QuestionItem(
      id: 'bah_kor_032',
      questionText: 'Sebutan panggilan dari laki-laki kepada kakak perempuan adalah:',
      options: ['Noona (누나)', 'Unnie', 'Oppa', 'Emma'],
      correctOptionIndex: 0,
      explanation: 'Noona dipanggil oleh laki-laki kepada kakak perempuan.',
    ),
    QuestionItem(
      id: 'bah_kor_033',
      questionText: 'Sebutan panggilan dari perempuan kepada kakak perempuan adalah:',
      options: ['Unnie (언니)', 'Noona', 'Hyung', 'Ahjumma'],
      correctOptionIndex: 0,
      explanation: 'Unnie dipanggil oleh perempuan kepada kakak perempuan.',
    ),
    QuestionItem(
      id: 'bah_kor_034',
      questionText: 'Sebutan panggilan untuk senior di kampus atau tempat kerja adalah:',
      options: ['Sunbae / Sunbaenim (선배님)', 'Hoobae', 'Sonsaengnim', 'Ajusshi'],
      correctOptionIndex: 0,
      explanation: 'Sunbae(nim) adalah panggilan untuk senior.',
    ),
    QuestionItem(
      id: 'bah_kor_035',
      questionText: 'Sebutan panggilan untuk junior di sekolah atau tempat kerja adalah:',
      options: ['Hoobae (후배)', 'Sunbae', 'Dongsaeng', 'Chingu'],
      correctOptionIndex: 0,
      explanation: 'Hoobae adalah panggilan untuk junior.',
    ),
    QuestionItem(
      id: 'bah_kor_036',
      questionText: 'Angka Asli Korea (Sino-Korea vs Native) 1 (Satu) Native Korea disebut:',
      options: ['Hana (하나)', 'Dul', 'Set', 'Net'],
      correctOptionIndex: 0,
      explanation: 'Hana adalah 1 angka Asli Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_037',
      questionText: 'Angka Asli Korea 2 (Dua) Native Korea disebut:',
      options: ['Dul (둘)', 'Hana', 'Set', 'Net'],
      correctOptionIndex: 0,
      explanation: 'Dul adalah 2 angka Asli Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_038',
      questionText: 'Angka Asli Korea 3 (Tiga) Native Korea disebut:',
      options: ['Set (셋)', 'Net', 'Daseot', 'Yeoseot'],
      correctOptionIndex: 0,
      explanation: 'Set adalah 3 angka Asli Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_039',
      questionText: 'Angka Sino-Korea (serapan Cina) 1, 2, 3 berurutan disebut:',
      options: ['Il, I, Sam (일, 이, 삼)', 'Hana, Dul, Set', 'Guk, Min, Su', 'Man, Won, Cheon'],
      correctOptionIndex: 0,
      explanation: 'Sino-Korea: Il (1), I (2), Sam (3).',
    ),
    QuestionItem(
      id: 'bah_kor_040',
      questionText: 'Mata uang resmi negara Korea Selatan dinamakan:',
      options: ['Won (원)', 'Yen', 'Yuan', 'Ringgit'],
      correctOptionIndex: 0,
      explanation: 'Won (₩) adalah mata uang Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_041',
      questionText: 'Ujian kemampuan standar resmi Bahasa Korea untuk penutur asing dinamakan:',
      options: ['TOPIK (Test of Proficiency in Korean / 한국어능력시험)', 'JLPT', 'HSK', 'TOEFL'],
      correctOptionIndex: 0,
      explanation: 'TOPIK adalah tes resmi sertifikasi bahasa Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_042',
      questionText: 'Tingkat kemahiran tertinggi pada ujian TOPIK II adalah Level:',
      options: ['Level 6', 'Level 1', 'Level 10', 'Level A'],
      correctOptionIndex: 0,
      explanation: 'TOPIK II Level 6 adalah tingkat tertinggi kemahiran.',
    ),
    QuestionItem(
      id: 'bah_kor_043',
      questionText: 'Arti kosakata "Hakgyo" (학교) adalah:',
      options: ['Sekolah', 'Rumah', 'Rumah Sakit', 'Toko'],
      correctOptionIndex: 0,
      explanation: 'Hakgyo berarti sekolah.',
    ),
    QuestionItem(
      id: 'bah_kor_044',
      questionText: 'Arti kosakata "Jip" (집) adalah:',
      options: ['Rumah', 'Sekolah', 'Kantor', 'Pasar'],
      correctOptionIndex: 0,
      explanation: 'Jip berarti rumah.',
    ),
    QuestionItem(
      id: 'bah_kor_045',
      questionText: 'Arti kosakata "Hwesa" (회사) adalah:',
      options: ['Perusahaan / Perusahaan Kantor', 'Sekolah', 'Pabrik', 'Bank'],
      correctOptionIndex: 0,
      explanation: 'Hwesa berarti perusahaan/kantor.',
    ),
    QuestionItem(
      id: 'bah_kor_046',
      questionText: 'Arti kosakata "Byeongwon" (병원) adalah:',
      options: ['Rumah Sakit', 'Apotek', 'Bandara', 'Stasiun'],
      correctOptionIndex: 0,
      explanation: 'Byeongwon berarti rumah sakit.',
    ),
    QuestionItem(
      id: 'bah_kor_047',
      questionText: 'Arti kosakata "Eunhaeng" (은행) adalah:',
      options: ['Bank', 'Pasar', 'Toko', 'Taman'],
      correctOptionIndex: 0,
      explanation: 'Eunhaeng berarti bank.',
    ),
    QuestionItem(
      id: 'bah_kor_048',
      questionText: 'Arti kosakata "Sijang" (시장) adalah:',
      options: ['Pasar', 'Mall', 'Restoran', 'Bioskop'],
      correctOptionIndex: 0,
      explanation: 'Sijang berarti pasar.',
    ),
    QuestionItem(
      id: 'bah_kor_049',
      questionText: 'Arti kosakata "Sikdang" (식당) adalah:',
      options: ['Restoran / Rumah Makan', 'Dapur', 'Kantin', 'Kamar'],
      correctOptionIndex: 0,
      explanation: 'Sikdang berarti rumah makan/restoran.',
    ),
    QuestionItem(
      id: 'bah_kor_050',
      questionText: 'Arti kosakata "Gonghang" (공항) adalah:',
      options: ['Bandara Udara', 'Stasiun', 'Pelabuhan', 'Terminal'],
      correctOptionIndex: 0,
      explanation: 'Gonghang berarti bandara udara.',
    ),
    QuestionItem(
      id: 'bah_kor_051',
      questionText: 'Arti kosakata "Subway / Jihacheol" (지하철) adalah:',
      options: ['Kereta Bawah Tanah (Subway)', 'Bus', 'Taksi', 'Sepeda'],
      correctOptionIndex: 0,
      explanation: 'Jihacheol adalah kereta bawah tanah.',
    ),
    QuestionItem(
      id: 'bah_kor_052',
      questionText: 'Arti kosakata "Bus" (버스) adalah:',
      options: ['Bus', 'Mobil', 'Kereta', 'Motor'],
      correctOptionIndex: 0,
      explanation: 'Beoseu berarti bus.',
    ),
    QuestionItem(
      id: 'bah_kor_053',
      questionText: 'Arti kosakata "Taeksi" (택시) adalah:',
      options: ['Taksi', 'Bus', 'Mobil', 'Sepeda'],
      correctOptionIndex: 0,
      explanation: 'Taeksi berarti taksi.',
    ),
    QuestionItem(
      id: 'bah_kor_054',
      questionText: 'Arti kosakata "Chaek" (책) adalah:',
      options: ['Buku', 'Pena', 'Kertas', 'Meja'],
      correctOptionIndex: 0,
      explanation: 'Chaek berarti buku.',
    ),
    QuestionItem(
      id: 'bah_kor_055',
      questionText: 'Arti kosakata "Pen" (펜) / "Yeonpil" adalah:',
      options: ['Pena / Pensil', 'Buku', 'Penghapus', 'Tas'],
      correctOptionIndex: 0,
      explanation: 'Pen (pena) dan Yeonpil (pensil).',
    ),
    QuestionItem(
      id: 'bah_kor_056',
      questionText: 'Arti kosakata "Mul" (물) adalah:',
      options: ['Air', 'Susu', 'Teh', 'Kopi'],
      correctOptionIndex: 0,
      explanation: 'Mul berarti air.',
    ),
    QuestionItem(
      id: 'bah_kor_057',
      questionText: 'Arti kosakata "Bap" (밥) adalah:',
      options: ['Nasi / Makanan Utama', 'Roti', 'Daging', 'Mie'],
      correctOptionIndex: 0,
      explanation: 'Bap berarti nasi atau hidangan makanan.',
    ),
    QuestionItem(
      id: 'bah_kor_058',
      questionText: 'Makanan tradisional fermentasi sawi pedas khas Korea dinamakan:',
      options: ['Kimchi (김치)', 'Tteokbokki', 'Bibimbap', 'Bulgogi'],
      correctOptionIndex: 0,
      explanation: 'Kimchi makanan tradisional khas fermentasi Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_059',
      questionText: 'Makanan populer Korea berupa nasi campur sayur dan daging dengan saus gochujang adalah:',
      options: ['Bibimbap (비빔밥)', 'Kimbap', 'Kimchi', 'Japchae'],
      correctOptionIndex: 0,
      explanation: 'Bibimbap bermakna nasi campur.',
    ),
    QuestionItem(
      id: 'bah_kor_060',
      questionText: 'Makanan jajanan pasar Korea berupa kue beras pedas manis dinamakan:',
      options: ['Tteokbokki (떡볶이)', 'Kimbap', 'Odeng', 'Sundae'],
      correctOptionIndex: 0,
      explanation: 'Tteokbokki kue beras berbumbu pedas.',
    ),
    QuestionItem(
      id: 'bah_kor_061',
      questionText: 'Makanan gulungan nasi rumput laut berbumbu khas Korea dinamakan:',
      options: ['Kimbap (김밥)', 'Bibimbap', 'Sushi', 'Samgyeopsal'],
      correctOptionIndex: 0,
      explanation: 'Kimbap adalah gulungan nasi gimbap rumput laut.',
    ),
    QuestionItem(
      id: 'bah_kor_062',
      questionText: 'Hari Senin dalam Bahasa Korea disebut:',
      options: ['Wol-yo-il (월요일)', 'Hwa-yo-il', 'Su-yo-il', 'Mok-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Wol-yo-il adalah hari Senin (Hari Bulan).',
    ),
    QuestionItem(
      id: 'bah_kor_063',
      questionText: 'Hari Selasa dalam Bahasa Korea disebut:',
      options: ['Hwa-yo-il (화요일)', 'Wol-yo-il', 'Su-yo-il', 'Geum-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Hwa-yo-il adalah hari Selasa (Hari Api).',
    ),
    QuestionItem(
      id: 'bah_kor_064',
      questionText: 'Hari Rabu dalam Bahasa Korea disebut:',
      options: ['Su-yo-il (수요일)', 'Hwa-yo-il', 'Mok-yo-il', 'To-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Su-yo-il adalah hari Rabu (Hari Air).',
    ),
    QuestionItem(
      id: 'bah_kor_065',
      questionText: 'Hari Kamis dalam Bahasa Korea disebut:',
      options: ['Mok-yo-il (목요일)', 'Su-yo-il', 'Geum-yo-il', 'Il-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Mok-yo-il adalah hari Kamis (Hari Pohon/Kayu).',
    ),
    QuestionItem(
      id: 'bah_kor_066',
      questionText: 'Hari Jumat dalam Bahasa Korea disebut:',
      options: ['Geum-yo-il (금요일)', 'Mok-yo-il', 'To-yo-il', 'Wol-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Geum-yo-il adalah hari Jumat (Hari Emas/Logam).',
    ),
    QuestionItem(
      id: 'bah_kor_067',
      questionText: 'Hari Sabtu dalam Bahasa Korea disebut:',
      options: ['To-yo-il (토요일)', 'Geum-yo-il', 'Il-yo-il', 'Hwa-yo-il'],
      correctOptionIndex: 0,
      explanation: 'To-yo-il adalah hari Sabtu (Hari Tanah).',
    ),
    QuestionItem(
      id: 'bah_kor_068',
      questionText: 'Hari Minggu dalam Bahasa Korea disebut:',
      options: ['Il-yo-il (일요일)', 'To-yo-il', 'Wol-yo-il', 'Su-yo-il'],
      correctOptionIndex: 0,
      explanation: 'Il-yo-il adalah hari Minggu (Hari Matahari).',
    ),
    QuestionItem(
      id: 'bah_kor_069',
      questionText: 'Musim Semi di Korea dinamakan:',
      options: ['Bom (봄)', 'Yeoreum', 'Gaeul', 'Gyeoul'],
      correctOptionIndex: 0,
      explanation: 'Bom adalah musim semi.',
    ),
    QuestionItem(
      id: 'bah_kor_070',
      questionText: 'Musim Panas di Korea dinamakan:',
      options: ['Yeoreum (여름)', 'Bom', 'Gaeul', 'Gyeoul'],
      correctOptionIndex: 0,
      explanation: 'Yeoreum adalah musim panas.',
    ),
    QuestionItem(
      id: 'bah_kor_071',
      questionText: 'Musim Gugur di Korea dinamakan:',
      options: ['Gaeul (가을)', 'Yeoreum', 'Gyeoul', 'Bom'],
      correctOptionIndex: 0,
      explanation: 'Gaeul adalah musim gugur.',
    ),
    QuestionItem(
      id: 'bah_kor_072',
      questionText: 'Musim Dingin di Korea dinamakan:',
      options: ['Gyeoul (겨울)', 'Gaeul', 'Bom', 'Yeoreum'],
      correctOptionIndex: 0,
      explanation: 'Gyeoul adalah musim dingin salju.',
    ),
    QuestionItem(
      id: 'bah_kor_073',
      questionText: 'Pakaian tradisional khas Korea yang anggun dinamakan:',
      options: ['Hanbok (한복)', 'Kimono', 'Cheongsam', 'Ao Dai'],
      correctOptionIndex: 0,
      explanation: 'Hanbok adalah pakaian tradisional Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_074',
      questionText: 'Hari Raya Panen Tradisional Korea yang dirayakan pada bulan 8 penanggalan lunar dinamakan:',
      options: ['Chuseok (추석)', 'Seollal', 'Dano', 'Pepero Day'],
      correctOptionIndex: 0,
      explanation: 'Chuseok adalah hari festival ucapan syukur panen.',
    ),
    QuestionItem(
      id: 'bah_kor_075',
      questionText: 'Hari Raya Tahun Baru Imlek/Lunar Korea dinamakan:',
      options: ['Seollal (설날)', 'Chuseok', 'Hansik', 'Sambok'],
      correctOptionIndex: 0,
      explanation: 'Seollal adalah Perayaan Tahun Baru Lunar Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_076',
      questionText: 'Sup kue beras tradisional yang wajib disantap saat Seollal dinamakan:',
      options: ['Tteokguk (떡국)', 'Samgyetang', 'Sundubu', 'Miyeokguk'],
      correctOptionIndex: 0,
      explanation: 'Tteokguk dimakan saat Seollal tanda bertambah umur.',
    ),
    QuestionItem(
      id: 'bah_kor_077',
      questionText: 'Sup rumput laut yang biasa dimakan saat ulang tahun di Korea dinamakan:',
      options: ['Miyeokguk (미역국)', 'Tteokguk', 'Doenjang jjigae', 'Kimchi jjigae'],
      correctOptionIndex: 0,
      explanation: 'Miyeokguk adalah sup rumput laut tradisi ulang tahun.',
    ),
    QuestionItem(
      id: 'bah_kor_078',
      questionText: 'Gelombang popularitas budaya Korea (K-Pop, K-Drama, K-Beauty) di seluruh dunia dinamakan:',
      options: ['Hallyu (한류) / Korean Wave', 'Chaebol', 'Mukbang', 'Noraebang'],
      correctOptionIndex: 0,
      explanation: 'Hallyu adalah fenomena Korean Wave global.',
    ),
    QuestionItem(
      id: 'bah_kor_079',
      questionText: 'Karakteristik tempat hiburan menyanyi karoke kamar di Korea dinamakan:',
      options: ['Noraebang (노래방)', 'PC Bang', 'Jjimjilbang', 'Pojangmacha'],
      correctOptionIndex: 0,
      explanation: 'Noraebang adalah tempat bernyanyi karaoke.',
    ),
    QuestionItem(
      id: 'bah_kor_080',
      questionText: 'Tempat pemandian umum sauna tradisional Korea 24 jam dinamakan:',
      options: ['Jjimjilbang (찜질방)', 'Noraebang', 'PC Bang', 'Hanok'],
      correctOptionIndex: 0,
      explanation: 'Jjimjilbang adalah kompleks sauna spa tradisional.',
    ),
    QuestionItem(
      id: 'bah_kor_081',
      questionText: 'Warung tenda pinggir jalan tempat menjual makanan dan minuman Korea dinamakan:',
      options: ['Pojangmacha (포장마차)', 'Sikdang', 'Kape', 'Mart'],
      correctOptionIndex: 0,
      explanation: 'Pojangmacha adalah warung tenda jajanan malam.',
    ),
    QuestionItem(
      id: 'bah_kor_082',
      questionText: 'Fenomena siaran live makan dalam jumlah besar di media sosial dinamakan:',
      options: ['Mukbang (먹방)', 'Cookbang', 'Vlog', 'Hallyu'],
      correctOptionIndex: 0,
      explanation: 'Mukbang (Eating Show) adalah tren penyiaran makan.',
    ),
    QuestionItem(
      id: 'bah_kor_083',
      questionText: 'Rumah tradisional kayu berdinding tanah dan ber-atap genteng khas Korea dinamakan:',
      options: ['Hanok (한옥)', 'Hanbok', 'Ondol', 'Maru'],
      correctOptionIndex: 0,
      explanation: 'Hanok adalah arsitektur rumah tradisional Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_084',
      questionText: 'Sistem pemanas lantai tradisional bawah tanah pada rumah Korea dinamakan:',
      options: ['Ondol (온돌)', 'Hanok', 'Kotatsu', 'Heater'],
      correctOptionIndex: 0,
      explanation: 'Ondol menghangatkan lantai rumah saat musim dingin.',
    ),
    QuestionItem(
      id: 'bah_kor_085',
      questionText: 'Ibu kota negara Korea Selatan adalah:',
      options: ['Seoul (서울)', 'Busan', 'Incheon', 'Jeju'],
      correctOptionIndex: 0,
      explanation: 'Seoul adalah ibu kota Republik Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_086',
      questionText: 'Kota pelabuhan terbesar di selatan Korea Selatan adalah:',
      options: ['Busan (부산)', 'Seoul', 'Daegu', 'Gwangju'],
      correctOptionIndex: 0,
      explanation: 'Busan adalah kota terbesar kedua dan pelabuhan utama.',
    ),
    QuestionItem(
      id: 'bah_kor_087',
      questionText: 'Pulau wisata paling terkenal di selatan Korea Selatan yang memiliki Gunung Hallasan dinamakan:',
      options: ['Jeju-do (제주도)', 'Nami-seom', 'Dokdo', 'Gangwon-do'],
      correctOptionIndex: 0,
      explanation: 'Pulau Jeju adalah destinasi wisata alam utama Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_088',
      questionText: 'Istilah Konglish (Korean-English) "Fighting!" yang diucapkan untuk memberi semangat adalah:',
      options: ['Haiting! / Paiting! (화이팅 / 파이팅)', 'Daebak', 'Heol', 'Aigoo'],
      correctOptionIndex: 0,
      explanation: 'Paiting! diucapkan untuk menyemangati seseorang.',
    ),
    QuestionItem(
      id: 'bah_kor_089',
      questionText: 'Ungkapan slang rasa kagum seruan "Luar biasa / Hebat!" adalah:',
      options: ['Daebak! (대박)', 'Jjang', 'Heol', 'Kkaebsong'],
      correctOptionIndex: 0,
      explanation: 'Daebak diucapkan saat kagum akan sesuatu yang hebat.',
    ),
    QuestionItem(
      id: 'bah_kor_090',
      questionText: 'Ungkapan seruan kaget atau mengeluh ("Aduh! / Ya ampun!") adalah:',
      options: ['Aigoo! (아이구)', 'Daebak', 'Omo', 'Jinzza'],
      correctOptionIndex: 0,
      explanation: 'Aigoo diucapkan saat kaget, lelah, atau kecewa.',
    ),
    QuestionItem(
      id: 'bah_kor_091',
      questionText: 'Ungkapan seruan terkejut wanita ("Ya ampun!") adalah:',
      options: ['Omo! (어머)', 'Aigoo', 'Heol', 'Daebak'],
      correctOptionIndex: 0,
      explanation: 'Omo diucapkan wanita saat terkejut.',
    ),
    QuestionItem(
      id: 'bah_kor_092',
      questionText: 'Ungkapan penegasan bertanya "Benarkah? / Sungguh?" adalah:',
      options: ['Jinjja? (진짜) / Jeongmal? (정말)', 'Geurae', 'Aniya', 'Majayo'],
      correctOptionIndex: 0,
      explanation: 'Jinjja? / Jeongmal? menanyakan kebenaran secara sungguh-sungguh.',
    ),
    QuestionItem(
      id: 'bah_kor_093',
      questionText: 'Kata penegasan setuju ("Benar / Betul sekali") adalah:',
      options: ['Majayo (맞아요)', 'Anieyo', 'Geuraeyo', 'Shiroyo'],
      correctOptionIndex: 0,
      explanation: 'Majayo bermakna betul/benar.',
    ),
    QuestionItem(
      id: 'bah_kor_094',
      questionText: 'Ungkapan penolakan sopan "Saya tidak suka / Tidak mau" adalah:',
      options: ['Sireoyo (싫어요)', 'Joahyo', 'Gwaenchanayo', 'Andwayo'],
      correctOptionIndex: 0,
      explanation: 'Sireoyo menyatakan tidak suka/mau.',
    ),
    QuestionItem(
      id: 'bah_kor_095',
      questionText: 'Ungkapan persetujuan "Saya suka" adalah:',
      options: ['Joahyo (좋아요)', 'Sireoyo', 'Nappeoyo', 'Yeppoyo'],
      correctOptionIndex: 0,
      explanation: 'Joahyo menyetujui atau menyukai sesuatu.',
    ),
    QuestionItem(
      id: 'bah_kor_096',
      questionText: 'Ungkapan ucapan "Selamat Ulang Tahun" sopan dalam Bahasa Korea adalah:',
      options: ['Saeng-il chuk-ha-haemnida (생일 축하합니다)', 'Saeng-il chuk-ha-hae', 'Chuk-ha-haeyo', 'Suhang-saeng'],
      correctOptionIndex: 0,
      explanation: 'Saeng-il chuk-ha-haemnida ucapan selamat ulang tahun sopan.',
    ),
    QuestionItem(
      id: 'bah_kor_097',
      questionText: 'Konglomerat bisnis grup keluarga raksasa di Korea Selatan (seperti Samsung, Hyundai) dinamakan:',
      options: ['Chaebol (재벌)', 'Hallyu', 'Kibo', 'Zaibatsu'],
      correctOptionIndex: 0,
      explanation: 'Chaebol adalah istilahkonglomerasi bisnis keluarga Korea.',
    ),
    QuestionItem(
      id: 'bah_kor_098',
      questionText: 'Wajib militer bagi warga pria Korea Selatan yang memenuhi syarat umur dinamakan:',
      options: ['Gun-dae / Byeong-yeok (군대 / 병역)', 'Hallyu', 'K-Defense', 'Chuseok'],
      correctOptionIndex: 0,
      explanation: 'Pria Korea Selatan mengemban kewajiban dinas militer.',
    ),
    QuestionItem(
      id: 'bah_kor_099',
      questionText: 'Dialek daerah Bahasa Korea di luar ibu kota Seoul dinamakan:',
      options: ['Satoori (사투리)', 'Pyo-jun-eo', 'Banmal', 'Hanja'],
      correctOptionIndex: 0,
      explanation: 'Satoori adalah istilah untuk dialek daerah (seperti Dialek Busan, Gyeongsang).',
    ),
    QuestionItem(
      id: 'bah_kor_100',
      questionText: 'Tujuan utama mempelajari Bahasa Korea pada jenjang pendidikan tinggi adalah untuk:',
      options: ['Menguasai struktur Hangeul, tata bahasa TOPIK, komunikasi bisnis, penerjemahan, dan studi kebudayaan Korea', 'Sekadar menonton K-Drama', 'Menghafal lirik K-Pop tanpa teori', 'Sekadar liburan ke Seoul'],
      correctOptionIndex: 0,
      explanation: 'Studi Bahasa Korea membentuk kemahiran linguistik akademis, kompetensi profesional TOPIK, dan analisis kebudayaan global.',
    ),
  ];
}
