import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaMandarinQuestions() {
  return const [
    QuestionItem(
      id: 'bah_man_001',
      questionText: 'Sistem alih aksara fonetik ejaan abjad Latin resmi untuk melafalkan Bahasa Mandarin dinamakan:',
      options: ['Pinyin (拼音)', 'Bopomofo', 'Kanji', 'Hanja'],
      correctOptionIndex: 0,
      explanation: 'Hanyu Pinyin adalah ejaan fonetik Latin Bahasa Mandarin.',
    ),
    QuestionItem(
      id: 'bah_man_002',
      questionText: 'Berapakah jumlah nada utama (Tone) dalam Bahasa Mandarin standar (Putonghua)?',
      options: ['4 Nada Utama + 1 Nada Netral', '3 Nada', '6 Nada', '8 Nada'],
      correctOptionIndex: 0,
      explanation: 'Mandarin memiliki 4 nada kontur utama ditambah nada netral.',
    ),
    QuestionItem(
      id: 'bah_man_003',
      questionText: 'Nada Pertama (Shengdiao 第一声) pada Pinyin ditandai dengan nada garis lurus datar ber-karakteristik:',
      options: ['Nada Tinggi Datar ( High Flat )', 'Nada Naik', 'Nada Turun Naik', 'Nada Turun Hentak'],
      correctOptionIndex: 0,
      explanation: 'Nada 1 bernada tinggi dan datar (misal: mā 媽).',
    ),
    QuestionItem(
      id: 'bah_man_004',
      questionText: 'Nada Kedua (第二声) pada Pinyin ber-karakteristik:',
      options: ['Nada Naik ( Rising Tone )', 'Nada Datar', 'Nada Turun', 'Nada Netral'],
      correctOptionIndex: 0,
      explanation: 'Nada 2 bernada naik seperti kalimat bertanya (misal: má 麻).',
    ),
    QuestionItem(
      id: 'bah_man_005',
      questionText: 'Nada Ketiga (第三声) pada Pinyin ber-karakteristik:',
      options: ['Nada Turun lalu Naik ( Dipping Tone )', 'Nada Datar', 'Nada Hentak', 'Nada Tinggi'],
      correctOptionIndex: 0,
      explanation: 'Nada 3 meluncur turun lalu melengkung naik (misal: mǎ 馬).',
    ),
    QuestionItem(
      id: 'bah_man_006',
      questionText: 'Nada Keempat (第四声) pada Pinyin ber-karakteristik:',
      options: ['Nada Turun Hentak ( Falling Tone )', 'Nada Datar', 'Nada Naik', 'Nada Ringan'],
      correctOptionIndex: 0,
      explanation: 'Nada 4 turun tajam dan dihentak (misal: mà 罵).',
    ),
    QuestionItem(
      id: 'bah_man_007',
      questionText: 'Aksara karakter tulisan Bahasa Mandarin yang telah disederhanakan jumlah goresannya dinamakan:',
      options: ['Hanzi Sederhana (Simplified / 简体字)', 'Hanzi Tradisional', 'Kanji', 'Bopomofo'],
      correctOptionIndex: 0,
      explanation: 'Simplified Hanzi digunakan di Tiongkok Daratan dan Singapura.',
    ),
    QuestionItem(
      id: 'bah_man_008',
      questionText: 'Aksara karakter Mandarin tradisional dengan goresan asli klasik yang masih digunakan di Taiwan dan Hong Kong dinamakan:',
      options: ['Hanzi Tradisional (Traditional / 繁体字)', 'Hanzi Sederhana', 'Pinyin', 'Katayana'],
      correctOptionIndex: 0,
      explanation: 'Traditional Hanzi dipertahankan di Taiwan dan Hong Kong.',
    ),
    QuestionItem(
      id: 'bah_man_009',
      questionText: 'Kata sapaan Bahasa Mandarin yang paling dasar dan umum untuk "Halo / Apa Kabar" adalah:',
      options: ['Ni Hao (你好)', 'Zaijian', 'Xiexie', 'Bu keqi'],
      correctOptionIndex: 0,
      explanation: 'Ni Hao adalah sapaan umum Halo.',
    ),
    QuestionItem(
      id: 'bah_man_010',
      questionText: 'Kata sapaan Bahasa Mandarin ragam sangat sopan untuk "Anda" (kepada orang tua/atasan) adalah:',
      options: ['Nin (您)', 'Ni', 'Ta', 'Women'],
      correctOptionIndex: 0,
      explanation: 'Nin (您) adalah ragam sangat hormat untuk Anda.',
    ),
    QuestionItem(
      id: 'bah_man_011',
      questionText: 'Kata sapaan jamak untuk "Halo Semuanya" adalah:',
      options: ['Dajia hao (大家好)', 'Ni hao', 'Zaoshang hao', 'Wanshang hao'],
      correctOptionIndex: 0,
      explanation: 'Dajia hao bermakna Halo semuanya.',
    ),
    QuestionItem(
      id: 'bah_man_012',
      questionText: 'Kata sapaan "Selamat Pagi" dalam Bahasa Mandarin adalah:',
      options: ['Zaoshang hao (早上好) / Zao (早)', 'Wanshang hao', 'Xiawu hao', 'Zaijian'],
      correctOptionIndex: 0,
      explanation: 'Zaoshang hao berarti selamat pagi.',
    ),
    QuestionItem(
      id: 'bah_man_013',
      questionText: 'Kata sapaan "Selamat Siang / Sore" adalah:',
      options: ['Xiawu hao (下午好)', 'Zaoshang hao', 'Wanshang hao', 'Wan an'],
      correctOptionIndex: 0,
      explanation: 'Xiawu hao berarti selamat siang/sore.',
    ),
    QuestionItem(
      id: 'bah_man_014',
      questionText: 'Kata sapaan "Selamat Malam" saat bertemu adalah:',
      options: ['Wanshang hao (晚上好)', 'Wan an', 'Zaoshang hao', 'Ni hao'],
      correctOptionIndex: 0,
      explanation: 'Wanshang hao berarti selamat malam saat bertemu.',
    ),
    QuestionItem(
      id: 'bah_man_015',
      questionText: 'Ungkapan "Selamat Malam / Selamat Tidur" sebelum beristirahat adalah:',
      options: ['Wan an (晚安)', 'Wanshang hao', 'Zaijian', 'Mingtion jian'],
      correctOptionIndex: 0,
      explanation: 'Wan an diucapkan sebelum tidur.',
    ),
    QuestionItem(
      id: 'bah_man_016',
      questionText: 'Ungkapan perpisahan "Sampai Jumpa Lagi" adalah:',
      options: ['Zaijian (再见)', 'Xiexie', 'Duibuqi', 'Mingtian jian'],
      correctOptionIndex: 0,
      explanation: 'Zaijian bermakna sampai jumpa lagi.',
    ),
    QuestionItem(
      id: 'bah_man_017',
      questionText: 'Ungkapan "Sampai Jumpa Besok" adalah:',
      options: ['Mingtian jian (明天见)', 'Zaijian', 'Hou tian jian', 'Zao an'],
      correctOptionIndex: 0,
      explanation: 'Mingtian jian bermakna sampai jumpa besok.',
    ),
    QuestionItem(
      id: 'bah_man_018',
      questionText: 'Ungkapan ucapan "Terima Kasih" adalah:',
      options: ['Xiexie (谢谢)', 'Bu keqi', 'Duibuqi', 'Mei guanxi'],
      correctOptionIndex: 0,
      explanation: 'Xiexie adalah ucapan terima kasih.',
    ),
    QuestionItem(
      id: 'bah_man_019',
      questionText: 'Jawaban sopan untuk ucapan terima kasih ("Sama-sama / Jangan sungkan") adalah:',
      options: ['Bu keqi (不客气) / Bu yong xie (不用谢)', 'Xiexie', 'Duibuqi', 'Hen hao'],
      correctOptionIndex: 0,
      explanation: 'Bu keqi bermakna sama-sama / tidak usah sungkan.',
    ),
    QuestionItem(
      id: 'bah_man_020',
      questionText: 'Ungkapan meminta maaf secara sopan ("Maaf") adalah:',
      options: ['Duibuqi (对不起) / Baoqian (抱歉)', 'Mei guanxi', 'Bu keqi', 'Xiexie'],
      correctOptionIndex: 0,
      explanation: 'Duibuqi / Baoqian adalah ungkapan maaf.',
    ),
    QuestionItem(
      id: 'bah_man_021',
      questionText: 'Jawaban untuk ucapan maaf ("Tidak apa-apa / Tidak masalah") adalah:',
      options: ['Mei guanxi (没关系)', 'Duibuqi', 'Bu keqi', 'Hen hao'],
      correctOptionIndex: 0,
      explanation: 'Mei guanxi bermakna tidak apa-apa.',
    ),
    QuestionItem(
      id: 'bah_man_022',
      questionText: 'Kata ganti orang pertama tunggal "Saya" adalah:',
      options: ['Wo (我)', 'Ni', 'Ta', 'Women'],
      correctOptionIndex: 0,
      explanation: 'Wo bermakna Saya.',
    ),
    QuestionItem(
      id: 'bah_man_023',
      questionText: 'Kata ganti orang kedua tunggal "Kamu" adalah:',
      options: ['Ni (你)', 'Wo', 'Ta', 'Nimen'],
      correctOptionIndex: 0,
      explanation: 'Ni bermakna Kamu.',
    ),
    QuestionItem(
      id: 'bah_man_024',
      questionText: 'Kata ganti orang ketiga tunggal "Dia (Laki-laki / Perempuan / Benda)" dilafalkan:',
      options: ['Ta (他 / 她 / 它)', 'Wo', 'Ni', 'Tamen'],
      correctOptionIndex: 0,
      explanation: 'Ta dilafalkan sama untuk dia pria (他), wanita (她), dan benda (它).',
    ),
    QuestionItem(
      id: 'bah_man_025',
      questionText: 'Pembentuk kata ganti jamak (Kami / Kalian / Mereka) menggunakan akhiran akhiran:',
      options: ['-men (们) (Women, Nimen, Tamen)', '-de', '-le', '-guo'],
      correctOptionIndex: 0,
      explanation: '-men membentuk kata ganti jamak.',
    ),
    QuestionItem(
      id: 'bah_man_026',
      questionText: 'Partikel penanda kepemilikan (Possessive particle) "Punya / Yang" adalah:',
      options: ['De (的)', 'Le', 'Guo', 'Ma'],
      correctOptionIndex: 0,
      explanation: 'De (的) menunjukkan kepemilikan (misal: Wo de shu = Buku saya).',
    ),
    QuestionItem(
      id: 'bah_man_027',
      questionText: 'Partikel tanya di akhir kalimat untuk pertanyaan Ya/Tidak (Apakah) adalah:',
      options: ['Ma (吗)', 'Ne', 'Ba', 'Le'],
      correctOptionIndex: 0,
      explanation: 'Ma (吗) di akhir kalimat membentuk pertanyaan.',
    ),
    QuestionItem(
      id: 'bah_man_028',
      questionText: 'Partikel saran / konfirmasi di akhir kalimat ("...kan? / ...ya?") adalah:',
      options: ['Ba (吧)', 'Ma', 'Ne', 'De'],
      correctOptionIndex: 0,
      explanation: 'Ba (吧) menyatakan ajakan atau konfirmasi halus.',
    ),
    QuestionItem(
      id: 'bah_man_029',
      questionText: 'Partikel penanda perubahan kondisi atau perbuatan selesai adalah:',
      options: ['Le (了)', 'Guo', 'Zhe', 'De'],
      correctOptionIndex: 0,
      explanation: 'Le (了) menandai perubahan keadaan atau tindakan selesai.',
    ),
    QuestionItem(
      id: 'bah_man_030',
      questionText: 'Partikel penanda pengalaman masa lalu ("Pernah") adalah:',
      options: ['Guo (过)', 'Le', 'Zhe', 'Zai'],
      correctOptionIndex: 0,
      explanation: 'Guo (过) menyatakan pengalaman pernah melakukan sesuatu.',
    ),
    QuestionItem(
      id: 'bah_man_031',
      questionText: 'Angka 1 (Satu) dalam Bahasa Mandarin disebut:',
      options: ['Yi (一)', 'Er', 'San', 'Si'],
      correctOptionIndex: 0,
      explanation: 'Yi berarti 1.',
    ),
    QuestionItem(
      id: 'bah_man_032',
      questionText: 'Angka 2 (Dua) untuk berhitung urutan disebut Er (二), sedangkan untuk jumlah benda (Dua buah) menggunakan:',
      options: ['Liang (两)', 'Er', 'San', 'Shuang'],
      correctOptionIndex: 0,
      explanation: 'Liang (两) digunakan saat menghitung kuantitas dua benda.',
    ),
    QuestionItem(
      id: 'bah_man_033',
      questionText: 'Angka 3 (Tiga) dalam Bahasa Mandarin disebut:',
      options: ['San (三)', 'Si', 'Wu', 'Liu'],
      correctOptionIndex: 0,
      explanation: 'San berarti 3.',
    ),
    QuestionItem(
      id: 'bah_man_034',
      questionText: 'Angka 4 (Empat) dalam Bahasa Mandarin disebut:',
      options: ['Si (四)', 'Wu', 'Qi', 'Ba'],
      correctOptionIndex: 0,
      explanation: 'Si berarti 4.',
    ),
    QuestionItem(
      id: 'bah_man_035',
      questionText: 'Angka 5 (Lima) dalam Bahasa Mandarin disebut:',
      options: ['Wu (五)', 'Si', 'Liu', 'Jiu'],
      correctOptionIndex: 0,
      explanation: 'Wu berarti 5.',
    ),
    QuestionItem(
      id: 'bah_man_036',
      questionText: 'Angka 10 (Sepuluh) dalam Bahasa Mandarin disebut:',
      options: ['Shi (十)', 'Bai', 'Qian', 'Wan'],
      correctOptionIndex: 0,
      explanation: 'Shi berarti 10.',
    ),
    QuestionItem(
      id: 'bah_man_037',
      questionText: 'Angka 100 (Seratus) dalam Bahasa Mandarin disebut:',
      options: ['Bai (百)', 'Qian', 'Wan', 'Shi'],
      correctOptionIndex: 0,
      explanation: 'Bai (百) berarti 100.',
    ),
    QuestionItem(
      id: 'bah_man_038',
      questionText: 'Angka 1.000 (Seribu) dalam Bahasa Mandarin disebut:',
      options: ['Qian (千)', 'Bai', 'Wan', 'Yi'],
      correctOptionIndex: 0,
      explanation: 'Qian (千) berarti 1.000.',
    ),
    QuestionItem(
      id: 'bah_man_039',
      questionText: 'Angka 10.000 (Sepuluh Ribu) sebagai unit hitung dasar dalam Mandarin disebut:',
      options: ['Wan (万)', 'Qian', 'Bai', 'Yi'],
      correctOptionIndex: 0,
      explanation: 'Wan (万) bernilai 10.000.',
    ),
    QuestionItem(
      id: 'bah_man_040',
      questionText: 'Mata uang resmi Republik Rakyat Tiongkok dinamakan Renminbi (RMB) dengan satuan unit:',
      options: ['Yuan (元 / 块)', 'Yen', 'Won', 'Dolar'],
      correctOptionIndex: 0,
      explanation: 'Yuan (Kuai) adalah satuan mata uang Tiongkok.',
    ),
    QuestionItem(
      id: 'bah_man_041',
      questionText: 'Ujian kemampuan standar resmi Bahasa Mandarin internasional untuk penutur asing dinamakan:',
      options: ['HSK (Hanyu Shuiping Kaoshi / 汉语水平考试)', 'JLPT', 'TOPIK', 'DELF'],
      correctOptionIndex: 0,
      explanation: 'HSK adalah tes standar internasional Bahasa Mandarin (Level 1-6).',
    ),
    QuestionItem(
      id: 'bah_man_042',
      questionText: 'Kata penggolong (Classifier / Liangci) paling umum dan netral untuk benda/orang adalah:',
      options: ['Ge (个)', 'Ben', 'Zhi', 'Zhang'],
      correctOptionIndex: 0,
      explanation: 'Ge (个) kata penggolong universal paling umum.',
    ),
    QuestionItem(
      id: 'bah_man_043',
      questionText: 'Kata penggolong khusus untuk jilid buku (misal: Yi ben shu) adalah:',
      options: ['Ben (本)', 'Ge', 'Zhang', 'Zhi'],
      correctOptionIndex: 0,
      explanation: 'Ben (本) penggolong buku.',
    ),
    QuestionItem(
      id: 'bah_man_044',
      questionText: 'Kata penggolong khusus untuk benda berpermukaan datar (seperti kertas, foto, meja) adalah:',
      options: ['Zhang (张)', 'Ben', 'Ge', 'Tiao'],
      correctOptionIndex: 0,
      explanation: 'Zhang (张) penggolong lembar/bidang datar.',
    ),
    QuestionItem(
      id: 'bah_man_045',
      questionText: 'Kata penggolong khusus untuk benda panjang meliuk (seperti jalan, sungai, ikan, celana) adalah:',
      options: ['Tiao (条)', 'Zhang', 'Zhi', 'Jian'],
      correctOptionIndex: 0,
      explanation: 'Tiao (条) penggolong objek panjang fleksibel.',
    ),
    QuestionItem(
      id: 'bah_man_046',
      questionText: 'Kata penggolong khusus untuk pakaian baju/pakaian atas (seperti Yi jian yifu) adalah:',
      options: ['Jian (件)', 'Tiao', 'Ge', 'Shuang'],
      correctOptionIndex: 0,
      explanation: 'Jian (件) penggolong pakaian atas.',
    ),
    QuestionItem(
      id: 'bah_man_047',
      questionText: 'Kata penggolong khusus untuk sepasang benda (seperti sepatu, sumpit) adalah:',
      options: ['Shuang (双)', 'Zhi', 'Ge', 'Tiao'],
      correctOptionIndex: 0,
      explanation: 'Shuang (双) penggolong sepasang.',
    ),
    QuestionItem(
      id: 'bah_man_048',
      questionText: 'Pola struktur tata bahasa penekanan penanganan objek menggunakan kata "Ba" (把) berstruktur:',
      options: ['Subjek + Ba + Objek + Kata Kerja + Pelengkap', 'Subjek + Objek + Ba + Kata Kerja', 'Ba + Subjek + Objek', 'Kata Kerja + Ba + Subjek'],
      correctOptionIndex: 0,
      explanation: 'Struktur Ba-zi-ju mendahulukan objek sebelum kata kerja.',
    ),
    QuestionItem(
      id: 'bah_man_049',
      questionText: 'Pola struktur tata bahasa kalimat pasif menggunakan kata "Bei" (被) berstruktur:',
      options: ['Objek (Penderita) + Bei + Pelaku + Kata Kerja', 'Pelaku + Bei + Objek', 'Bei + Subjek + Kata kerja', 'Kata kerja + Bei + Objek'],
      correctOptionIndex: 0,
      explanation: 'Struktur Bei-zi-ju membentuk kalimat pasif.',
    ),
    QuestionItem(
      id: 'bah_man_050',
      questionText: 'Kata kerja modal "Hui" (会) bermakna:',
      options: ['Bisa / Mampu (hasil pembelajaran/keterampilan)', 'Boleh', 'Harus', 'Ingin'],
      correctOptionIndex: 0,
      explanation: 'Hui menyatakan kemampuan yang diperoleh dari belajar.',
    ),
    QuestionItem(
      id: 'bah_man_051',
      questionText: 'Kata kerja modal "Neng" (能) bermakna:',
      options: ['Bisa / Mampu (kondisi fisik/kesempatan)', 'Harus', 'Boleh', 'Ingin'],
      correctOptionIndex: 0,
      explanation: 'Neng menyatakan kemampuan fisik atau kesanggupan situasi.',
    ),
    QuestionItem(
      id: 'bah_man_052',
      questionText: 'Kata kerja modal "Keyi" (可以) bermakna:',
      options: ['Boleh / Diizinkan (Permission)', 'Harus', 'Bisa murni', 'Mau'],
      correctOptionIndex: 0,
      explanation: 'Keyi menyatakan izin/kebolehserhaan.',
    ),
    QuestionItem(
      id: 'bah_man_053',
      questionText: 'Kata kerja modal "Yao" (要) bermakna:',
      options: ['Mau / Ingin / Harus', 'Boleh', 'Bisa', 'Tidak mau'],
      correctOptionIndex: 0,
      explanation: 'Yao menyatakan keinginan kuat atau keharusan.',
    ),
    QuestionItem(
      id: 'bah_man_054',
      questionText: 'Arti kosakata "Xuexiao" (学校) adalah:',
      options: ['Sekolah', 'Rumah', 'Toko', 'Pabrik'],
      correctOptionIndex: 0,
      explanation: 'Xuexiao berarti sekolah.',
    ),
    QuestionItem(
      id: 'bah_man_055',
      questionText: 'Arti kosakata "Jia" (家) adalah:',
      options: ['Rumah / Keluarga', 'Sekolah', 'Kantor', 'Taman'],
      correctOptionIndex: 0,
      explanation: 'Jia berarti rumah atau keluarga.',
    ),
    QuestionItem(
      id: 'bah_man_056',
      questionText: 'Arti kosakata "Yiyuan" (医院) adalah:',
      options: ['Rumah Sakit', 'Apotek', 'Stasiun', 'Bank'],
      correctOptionIndex: 0,
      explanation: 'Yiyuan berarti rumah sakit.',
    ),
    QuestionItem(
      id: 'bah_man_057',
      questionText: 'Arti kosakata "Yinhang" (银行) adalah:',
      options: ['Bank', 'Pasar', 'Bandara', 'Hotel'],
      correctOptionIndex: 0,
      explanation: 'Yinhang berarti bank.',
    ),
    QuestionItem(
      id: 'bah_man_058',
      questionText: 'Arti kosakata "Shadian" (商店) / "Chaoshi" (超市) adalah:',
      options: ['Toko / Supermarket', 'Restoran', 'Sekolah', 'Bioskop'],
      correctOptionIndex: 0,
      explanation: 'Shangdian (toko) / Chaoshi (supermarket).',
    ),
    QuestionItem(
      id: 'bah_man_059',
      questionText: 'Arti kosakata "Fanguan" (饭馆) / "Canguan" (餐馆) adalah:',
      options: ['Restoran / Rumah Makan', 'Dapur', 'Hotel', 'Pasar'],
      correctOptionIndex: 0,
      explanation: 'Fanguan / Canguan berarti rumah makan/restoran.',
    ),
    QuestionItem(
      id: 'bah_man_060',
      questionText: 'Arti kosakata "Huochezhan" (火车站) adalah:',
      options: ['Stasiun Kereta Api', 'Bandara', 'Pelabuhan', 'Terminal'],
      correctOptionIndex: 0,
      explanation: 'Huochezhan berarti stasiun kereta api.',
    ),
    QuestionItem(
      id: 'bah_man_061',
      questionText: 'Arti kosakata "Feijichang" (飞机场) adalah:',
      options: ['Bandara Udara', 'Stasiun', 'Pelabuhan', 'Terminal'],
      correctOptionIndex: 0,
      explanation: 'Feijichang berarti bandara.',
    ),
    QuestionItem(
      id: 'bah_man_062',
      questionText: 'Arti kosakata "Shu" (书) adalah:',
      options: ['Buku', 'Pena', 'Kertas', 'Meja'],
      correctOptionIndex: 0,
      explanation: 'Shu berarti buku.',
    ),
    QuestionItem(
      id: 'bah_man_063',
      questionText: 'Arti kosakata "Bi" (笔) adalah:',
      options: ['Pena / Alat Tulis', 'Buku', 'Penghapus', 'Tas'],
      correctOptionIndex: 0,
      explanation: 'Bi berarti pena/alat tulis.',
    ),
    QuestionItem(
      id: 'bah_man_064',
      questionText: 'Arti kosakata "Shui" (水) adalah:',
      options: ['Air', 'Teh', 'Kopi', 'Susu'],
      correctOptionIndex: 0,
      explanation: 'Shui berarti air.',
    ),
    QuestionItem(
      id: 'bah_man_065',
      questionText: 'Arti kosakata "Cha" (茶) adalah:',
      options: ['Teh', 'Kopi', 'Air', 'Jus'],
      correctOptionIndex: 0,
      explanation: 'Cha berarti teh.',
    ),
    QuestionItem(
      id: 'bah_man_066',
      questionText: 'Arti kosakata "Mi fan" (米饭) adalah:',
      options: ['Nasi Putih', 'Roti', 'Mie', 'Daging'],
      correctOptionIndex: 0,
      explanation: 'Mi fan berarti nasi putih.',
    ),
    QuestionItem(
      id: 'bah_man_067',
      questionText: 'Arti kosakata "Miantiao" (面条) adalah:',
      options: ['Mie', 'Nasi', 'Roti', 'Sup'],
      correctOptionIndex: 0,
      explanation: 'Miantiao berarti mie.',
    ),
    QuestionItem(
      id: 'bah_man_068',
      questionText: 'Hari Senin dalam Bahasa Mandarin disebut:',
      options: ['Xingqi yi (星期一) / Zhou yi', 'Xingqi er', 'Xingqi san', 'Xingqi si'],
      correctOptionIndex: 0,
      explanation: 'Xingqi yi adalah hari Senin (Minggu-1).',
    ),
    QuestionItem(
      id: 'bah_man_069',
      questionText: 'Hari Selasa dalam Bahasa Mandarin disebut:',
      options: ['Xingqi er (星期二)', 'Xingqi yi', 'Xingqi san', 'Xingqi wu'],
      correctOptionIndex: 0,
      explanation: 'Xingqi er adalah hari Selasa (Minggu-2).',
    ),
    QuestionItem(
      id: 'bah_man_070',
      questionText: 'Hari Rabu dalam Bahasa Mandarin disebut:',
      options: ['Xingqi san (星期三)', 'Xingqi er', 'Xingqi si', 'Xingqi liu'],
      correctOptionIndex: 0,
      explanation: 'Xingqi san adalah hari Rabu (Minggu-3).',
    ),
    QuestionItem(
      id: 'bah_man_071',
      questionText: 'Hari Kamis dalam Bahasa Mandarin disebut:',
      options: ['Xingqi si (星期四)', 'Xingqi san', 'Xingqi wu', 'Xingqi tian'],
      correctOptionIndex: 0,
      explanation: 'Xingqi si adalah hari Kamis (Minggu-4).',
    ),
    QuestionItem(
      id: 'bah_man_072',
      questionText: 'Hari Jumat dalam Bahasa Mandarin disebut:',
      options: ['Xingqi wu (星期五)', 'Xingqi si', 'Xingqi liu', 'Xingqi er'],
      correctOptionIndex: 0,
      explanation: 'Xingqi wu adalah hari Jumat (Minggu-5).',
    ),
    QuestionItem(
      id: 'bah_man_073',
      questionText: 'Hari Sabtu dalam Bahasa Mandarin disebut:',
      options: ['Xingqi liu (星期六)', 'Xingqi wu', 'Xingqi tian', 'Xingqi yi'],
      correctOptionIndex: 0,
      explanation: 'Xingqi liu adalah hari Sabtu (Minggu-6).',
    ),
    QuestionItem(
      id: 'bah_man_074',
      questionText: 'Hari Minggu dalam Bahasa Mandarin disebut:',
      options: ['Xingqi tian (星期天) / Xingqi ri (星期日)', 'Xingqi liu', 'Xingqi yi', 'Xingqi qi'],
      correctOptionIndex: 0,
      explanation: 'Xingqi tian / ri adalah hari Minggu (Hari Langit/Matahari).',
    ),
    QuestionItem(
      id: 'bah_man_075',
      questionText: 'Musim Semi dalam Bahasa Mandarin disebut:',
      options: ['Chuntian (春天)', 'Xiatian', 'Qiutian', 'Dongtian'],
      correctOptionIndex: 0,
      explanation: 'Chuntian adalah musim semi.',
    ),
    QuestionItem(
      id: 'bah_man_076',
      questionText: 'Musim Panas dalam Bahasa Mandarin disebut:',
      options: ['Xiatian (夏天)', 'Chuntian', 'Qiutian', 'Dongtian'],
      correctOptionIndex: 0,
      explanation: 'Xiatian adalah musim panas.',
    ),
    QuestionItem(
      id: 'bah_man_077',
      questionText: 'Musim Gugur dalam Bahasa Mandarin disebut:',
      options: ['Qiutian (秋天)', 'Xiatian', 'Dongtian', 'Chuntian'],
      correctOptionIndex: 0,
      explanation: 'Qiutian adalah musim gugur.',
    ),
    QuestionItem(
      id: 'bah_man_078',
      questionText: 'Musim Dingin dalam Bahasa Mandarin disebut:',
      options: ['Dongtian (冬天)', 'Qiutian', 'Chuntian', 'Xiatian'],
      correctOptionIndex: 0,
      explanation: 'Dongtian adalah musim dingin salju.',
    ),
    QuestionItem(
      id: 'bah_man_079',
      questionText: 'Perayaan Tahun Baru Imlek / Festival Musim Semi di Tiongkok dinamakan:',
      options: ['Chunjie (春节)', 'Zhongqiu jie', 'Duanwu jie', 'Qingming jie'],
      correctOptionIndex: 0,
      explanation: 'Chunjie (Imlek) perayaan terbesar masyarakat Tionghoa.',
    ),
    QuestionItem(
      id: 'bah_man_080',
      questionText: 'Festival Pertengahan Musim Gugur dengan tradisi menyantap Kue Bulan dinamakan:',
      options: ['Zhongqiu jie (中秋节)', 'Chunjie', 'Duanwu jie', 'Yuanxiao jie'],
      correctOptionIndex: 0,
      explanation: 'Zhongqiu jie adalah Mooncake Festival (Festival Kue Bulan).',
    ),
    QuestionItem(
      id: 'bah_man_081',
      questionText: 'Festival Peh Cun / Perahu Naga dengan tradisi makan Bacang dinamakan:',
      options: ['Duanwu jie (端午节)', 'Zhongqiu jie', 'Chunjie', 'Chongyang jie'],
      correctOptionIndex: 0,
      explanation: 'Duanwu jie adalah Dragon Boat Festival (makan zongzi/bacang).',
    ),
    QuestionItem(
      id: 'bah_man_082',
      questionText: 'Pakaian tradisional Tionghoa wanita berkerah berdiri dan berpotongan pas di tubuh dinamakan:',
      options: ['Cheongsam / Qipao (旗袍)', 'Hanfu', 'Changshan', 'Kimono'],
      correctOptionIndex: 0,
      explanation: 'Qipao / Cheongsam gaun tradisional khas Tionghoa.',
    ),
    QuestionItem(
      id: 'bah_man_083',
      questionText: 'Amplop merah berisi uang hadiah saat Imlek dinamakan:',
      options: ['Hongbao (红包)', 'Zongzi', 'Jiaozi', 'Tangyuan'],
      correctOptionIndex: 0,
      explanation: 'Hongbao (Angpao) adalah amplop merah hadiah Imlek.',
    ),
    QuestionItem(
      id: 'bah_man_084',
      questionText: 'Seni seni tradisional menggunting kertas menjadi corak hiasan jendela dinamakan:',
      options: ['Jianzhi (剪纸)', 'Shufa', 'Guohua', 'Jingju'],
      correctOptionIndex: 0,
      explanation: 'Jianzhi adalah seni potong kertas tradisional.',
    ),
    QuestionItem(
      id: 'bah_man_085',
      questionText: 'Seni lukis tradisional Tionghoa menggunakan kuas dan tinta bak dinamakan:',
      options: ['Guohua (国画)', 'Jianzhi', 'Shufa', 'Piyingxi'],
      correctOptionIndex: 0,
      explanation: 'Guohua adalah seni lukis nasional Tiongkok.',
    ),
    QuestionItem(
      id: 'bah_man_086',
      questionText: 'Seni kaligrafi indah Mandarin menggunakan kuas dan tinta bak dinamakan:',
      options: ['Shufa (书法)', 'Guohua', 'Jianzhi', 'Wushu'],
      correctOptionIndex: 0,
      explanation: 'Shufa adalah seni kaligrafi karakter Hanzi.',
    ),
    QuestionItem(
      id: 'bah_man_087',
      questionText: 'Seni pertunjukan Opera Peking tradisional khas Beijing dinamakan:',
      options: ['Jingju (京剧)', 'Kunqu', 'Yueju', 'Huangmeixi'],
      correctOptionIndex: 0,
      explanation: 'Jingju adalah Opera Peking.',
    ),
    QuestionItem(
      id: 'bah_man_088',
      questionText: 'Seni bela diri tradisional khas Tiongkok dinamakan:',
      options: ['Wushu (武术) / Gongfu (功夫)', 'Taekwondo', 'Karate', 'Judo'],
      correctOptionIndex: 0,
      explanation: 'Wushu / Kungfu seni bela diri Tiongkok.',
    ),
    QuestionItem(
      id: 'bah_man_089',
      questionText: 'Ibu kota negara Republik Rakyat Tiongkok adalah:',
      options: ['Beijing (北京)', 'Shanghai', 'Guangzhou', 'Shenzhen'],
      correctOptionIndex: 0,
      explanation: 'Beijing adalah ibu kota RRT.',
    ),
    QuestionItem(
      id: 'bah_man_090',
      questionText: 'Pusat kota metropolitan bisnis dan keuangan terbesar di Tiongkok adalah:',
      options: ['Shanghai (上海)', 'Beijing', 'Tianjin', 'Chongqing'],
      correctOptionIndex: 0,
      explanation: 'Shanghai adalah pusat keuangan global Tiongkok.',
    ),
    QuestionItem(
      id: 'bah_man_091',
      questionText: 'Bangunan benteng pertahanan kuno terpanjang di dunia yang melintasi bukit-bukit Tiongkok adalah:',
      options: ['Tembok Besar Tiongkok (Wanli Changcheng / 长城)', 'Kota Terlarang', 'Istana Musim Panas', 'Klenteng'],
      correctOptionIndex: 0,
      explanation: 'Wanli Changcheng adalah Great Wall of China.',
    ),
    QuestionItem(
      id: 'bah_man_092',
      questionText: 'Istana kerajaan kekaisaran Dinasti Ming dan Qing di Beijing yang kini jadi museum dinamakan:',
      options: ['Kota Terlarang (Gugong / 故宫)', 'Tiantan', 'Summer Palace', 'Terracotta'],
      correctOptionIndex: 0,
      explanation: 'Gugong (Forbidden City) kompleks istana kaisar.',
    ),
    QuestionItem(
      id: 'bah_man_093',
      questionText: 'Ungkapan ucapan "Selamat Ulang Tahun" dalam Bahasa Mandarin adalah:',
      options: ['Shengri kuaile! (生日快乐!)', 'Xinnian kuaile!', 'Gongxi facai!', 'Zhubu gaozheng!'],
      correctOptionIndex: 0,
      explanation: 'Shengri kuaile diucapkan saat ulang tahun.',
    ),
    QuestionItem(
      id: 'bah_man_094',
      questionText: 'Ungkapan ucapan "Selamat Tahun Baru" dalam Bahasa Mandarin adalah:',
      options: ['Xinnian kuaile! (新年快乐!)', 'Shengri kuaile!', 'Wan an!', 'Zaijian!'],
      correctOptionIndex: 0,
      explanation: 'Xinnian kuaile berarti Selamat Tahun Baru.',
    ),
    QuestionItem(
      id: 'bah_man_095',
      questionText: 'Ungkapan salam kemakmuran saat Imlek ("Selamat dan semoga tambah makmur sejahtera") adalah:',
      options: ['Gongxi facai! (恭喜发财!)', 'Xiexie', 'Bu keqi', 'Shen ti jian kang'],
      correctOptionIndex: 0,
      explanation: 'Gongxi facai harapan kemakmuran rezeki Imlek.',
    ),
    QuestionItem(
      id: 'bah_man_096',
      questionText: 'Ungkapan doa kesehatan ("Semoga sehat selalu") adalah:',
      options: ['Shenti jiankang (身体健康)', 'Wanshi ruyi', 'Shengri kuaile', 'Gongxi'],
      correctOptionIndex: 0,
      explanation: 'Shenti jiankang mendoakan badan sehat.',
    ),
    QuestionItem(
      id: 'bah_man_097',
      questionText: 'Ungkapan doa kelancaran ("Semoga segala hal berjalan sesuai keinginan") adalah:',
      options: ['Wanshi ruyi (万事如意)', 'Shenti jiankang', 'Xinnian kuaile', 'Zaijian'],
      correctOptionIndex: 0,
      explanation: 'Wanshi ruyi mendoakan segala urusan sukses lancar.',
    ),
    QuestionItem(
      id: 'bah_man_098',
      questionText: 'Minuman teh tradisional Tionghoa yang diyakini menyehatkan tubuh dinamakan:',
      options: ['Cha (茶)', 'Jiu', 'Kafei', 'Kezhi'],
      correctOptionIndex: 0,
      explanation: 'Cha (Teh) minuman kebudayaan Tiongkok.',
    ),
    QuestionItem(
      id: 'bah_man_099',
      questionText: 'Alat perhitung kuno tradisional Tionghoa berupa manik-manik kayu bingkai dinamakan:',
      options: ['Suanpan (算盘 / Sempoa)', 'Luopan', 'Zhong', 'Chou'],
      correctOptionIndex: 0,
      explanation: 'Suanpan adalah sempoa alat hitung tradisional.',
    ),
    QuestionItem(
      id: 'bah_man_100',
      questionText: 'Tujuan utama mempelajari Bahasa Mandarin pada jenjang perguruan tinggi adalah untuk:',
      options: ['Menguasai komunikasi lisan/tulis, ejaan HSK, kemahiran Hanzi, analisis kebudayaan, dan negosiasi bisnis internasional', 'Sekadar menonton drama', 'Menghafal lagu', 'Sekadar turis'],
      correctOptionIndex: 0,
      explanation: 'Studi Bahasa Mandarin membentuk kemahiran komunikasi bisnis global, penguasaan HSK, dan literasi kebudayaan Tiongkok.',
    ),
  ];
}
