import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaArabQuestions() {
  return const [
    QuestionItem(
      id: 'bah_arab_001',
      questionText: 'Kata sapaan Bahasa Arab yang digunakan untuk mengucapkan "Selamat Pagi" adalah:',
      options: ['Shabahul Khair (صباح الخير)', 'Masa-ul Khair', 'Ahlan wa Sahlan', 'Syukran'],
      correctOptionIndex: 0,
      explanation: 'Shabahul Khair adalah ungkapan selamat pagi dalam bahasa Arab.',
    ),
    QuestionItem(
      id: 'bah_arab_002',
      questionText: 'Jawaban yang tepat untuk sapaan "Shabahul Khair" adalah:',
      options: ['Shabahun Nur (صباح النور)', 'Masa-un Nur', 'Afwan', 'Ma\'as salamah'],
      correctOptionIndex: 0,
      explanation: 'Shabahun Nur (pagi yang cerah) adalah balasan ucapan selamat pagi.',
    ),
    QuestionItem(
      id: 'bah_arab_003',
      questionText: 'Kata ganti orang pertama tunggal "Saya" dalam Bahasa Arab dinamakan:',
      options: ['Ana (أَنَا)', 'Anta', 'Huwa', 'Hiya'],
      correctOptionIndex: 0,
      explanation: 'Ana berarti Saya.',
    ),
    QuestionItem(
      id: 'bah_arab_004',
      questionText: 'Kata ganti orang kedua tunggal laki-laki "Kamu (Laki-laki)" dalam Bahasa Arab dinamakan:',
      options: ['Anta (أَنْتَ)', 'Anti', 'Ana', 'Antum'],
      correctOptionIndex: 0,
      explanation: 'Anta berarti Kamu untuk laki-laki.',
    ),
    QuestionItem(
      id: 'bah_arab_005',
      questionText: 'Kata ganti orang kedua tunggal perempuan "Kamu (Perempuan)" dinamakan:',
      options: ['Anti (أَنْتِ)', 'Anta', 'Hiya', 'Antunna'],
      correctOptionIndex: 0,
      explanation: 'Anti berarti Kamu untuk perempuan.',
    ),
    QuestionItem(
      id: 'bah_arab_006',
      questionText: 'Kata ganti orang ketiga tunggal laki-laki "Dia (Laki-laki)" dinamakan:',
      options: ['Huwa (هُوَ)', 'Hiya', 'Anta', 'Hum'],
      correctOptionIndex: 0,
      explanation: 'Huwa berarti Dia (laki-laki).',
    ),
    QuestionItem(
      id: 'bah_arab_007',
      questionText: 'Kata ganti orang ketiga tunggal perempuan "Dia (Perempuan)" dinamakan:',
      options: ['Hiya (هِيَ)', 'Huwa', 'Anti', 'Hunna'],
      correctOptionIndex: 0,
      explanation: 'Hiya berarti Dia (perempuan).',
    ),
    QuestionItem(
      id: 'bah_arab_008',
      questionText: 'Kata tunjuk "Ini" untuk kata benda jenis laki-laki (muzakkar) adalah:',
      options: ['Haza (هَذَا)', 'Hazihi', 'Zalika', 'Tilka'],
      correctOptionIndex: 0,
      explanation: 'Haza adalah kata tunjuk dekat muzakkar.',
    ),
    QuestionItem(
      id: 'bah_arab_009',
      questionText: 'Kata tunjuk "Ini" untuk kata benda jenis perempuan (muannas) adalah:',
      options: ['Hazihi (هَذِهِ)', 'Haza', 'Tilka', 'Zalika'],
      correctOptionIndex: 0,
      explanation: 'Hazihi adalah kata tunjuk dekat muannas (biasanya diakhiri ta marbuthah).',
    ),
    QuestionItem(
      id: 'bah_arab_010',
      questionText: 'Kata tunjuk "Itu" untuk benda muzakkar jarak jauh adalah:',
      options: ['Zalika (ذَلِكَ)', 'Tilka', 'Haza', 'Hazihi'],
      correctOptionIndex: 0,
      explanation: 'Zalika adalah kata tunjuk jauh muzakkar.',
    ),
    QuestionItem(
      id: 'bah_arab_011',
      questionText: 'Kata tunjuk "Itu" untuk benda muannas jarak jauh adalah:',
      options: ['Tilka (تِلْكَ)', 'Zalika', 'Hazihi', 'Haza'],
      correctOptionIndex: 0,
      explanation: 'Tilka adalah kata tunjuk jauh muannas.',
    ),
    QuestionItem(
      id: 'bah_arab_012',
      questionText: 'Arti dari kosakata "Madrasah" (مَدْرَسَةٌ) adalah:',
      options: ['Sekolah', 'Rumah', 'Masjid', 'Pasar'],
      correctOptionIndex: 0,
      explanation: 'Madrasah berarti sekolah.',
    ),
    QuestionItem(
      id: 'bah_arab_013',
      questionText: 'Arti dari kosakata "Baitun" (بَيْتٌ) adalah:',
      options: ['Rumah', 'Sekolah', 'Toko', 'Kamar'],
      correctOptionIndex: 0,
      explanation: 'Baitun berarti rumah.',
    ),
    QuestionItem(
      id: 'bah_arab_014',
      questionText: 'Arti dari kosakata "Kitabun" (كِتَابٌ) adalah:',
      options: ['Buku', 'Pena', 'Meja', 'Penggaris'],
      correctOptionIndex: 0,
      explanation: 'Kitabun berarti buku.',
    ),
    QuestionItem(
      id: 'bah_arab_015',
      questionText: 'Arti dari kosakata "Qalamun" (قَلَمٌ) adalah:',
      options: ['Pena / Pulpen', 'Buku', 'Pensil', 'Kertas'],
      correctOptionIndex: 0,
      explanation: 'Qalamun berarti pena.',
    ),
    QuestionItem(
      id: 'bah_arab_016',
      questionText: 'Arti dari kosakata "Maktabun" (مَكْتَبٌ) adalah:',
      options: ['Meja Tulis / Kantor', 'Kursi', 'Papan Tulis', 'Lemari'],
      correctOptionIndex: 0,
      explanation: 'Maktabun berarti meja tulis atau kantor.',
    ),
    QuestionItem(
      id: 'bah_arab_017',
      questionText: 'Arti dari kosakata "Kursiyyun" (كُرْسِيٌّ) adalah:',
      options: ['Kursi', 'Meja', 'Pintu', 'Jendela'],
      correctOptionIndex: 0,
      explanation: 'Kursiyyun berarti kursi.',
    ),
    QuestionItem(
      id: 'bah_arab_018',
      questionText: 'Arti dari kosakata "Babun" (بَابٌ) adalah:',
      options: ['Pintu', 'Jendela', 'Dinding', 'Atap'],
      correctOptionIndex: 0,
      explanation: 'Babun berarti pintu.',
    ),
    QuestionItem(
      id: 'bah_arab_019',
      questionText: 'Arti dari kosakata "Naafizatun" (نَافِذَةٌ) adalah:',
      options: ['Jendela', 'Pintu', 'Kunci', 'Lantai'],
      correctOptionIndex: 0,
      explanation: 'Naafizatun berarti jendela.',
    ),
    QuestionItem(
      id: 'bah_arab_020',
      questionText: 'Angka 1 (Satu) dalam Bahasa Arab dinamakan:',
      options: ['Wahid (وَاحِدٌ)', 'Isnain', 'Salasah', 'Arba\'ah'],
      correctOptionIndex: 0,
      explanation: 'Wahid berarti satu.',
    ),
    QuestionItem(
      id: 'bah_arab_021',
      questionText: 'Angka 2 (Dua) dalam Bahasa Arab dinamakan:',
      options: ['Isnain (إِثْنَيْنِ)', 'Wahid', 'Salasah', 'Khamsah'],
      correctOptionIndex: 0,
      explanation: 'Isnain berarti dua.',
    ),
    QuestionItem(
      id: 'bah_arab_022',
      questionText: 'Angka 3 (Tiga) dalam Bahasa Arab dinamakan:',
      options: ['Salasah (ثَلَاثَةٌ)', 'Arba\'ah', 'Khamsah', 'Sittah'],
      correctOptionIndex: 0,
      explanation: 'Salasah berarti tiga.',
    ),
    QuestionItem(
      id: 'bah_arab_023',
      questionText: 'Angka 5 (Lima) dalam Bahasa Arab dinamakan:',
      options: ['Khamsah (خَمْسَةٌ)', 'Arba\'ah', 'Sittah', 'Sab\'ah'],
      correctOptionIndex: 0,
      explanation: 'Khamsah berarti lima.',
    ),
    QuestionItem(
      id: 'bah_arab_024',
      questionText: 'Angka 10 (Sepuluh) dalam Bahasa Arab dinamakan:',
      options: ['\'Asyarah (عَشَرَةٌ)', 'Tisa\'ah', 'Samaniyah', 'Sab\'ah'],
      correctOptionIndex: 0,
      explanation: '\'Asyarah berarti sepuluh.',
    ),
    QuestionItem(
      id: 'bah_arab_025',
      questionText: 'Ucapan terima kasih "Syukran" (شُكْرًا) dibalas dengan ucapan:',
      options: ['\'Afwan (عَفْوًا)', 'Ahlan', 'Na\'am', 'Laa'],
      correctOptionIndex: 0,
      explanation: '\'Afwan adalah balasan ucapan Syukran (sama-sama).',
    ),
    QuestionItem(
      id: 'bah_arab_026',
      questionText: 'Kata tanya "Siapa" dalam Bahasa Arab dinamakan:',
      options: ['Man (مَنْ)', 'Ma', 'Kaifa', 'Aina'],
      correctOptionIndex: 0,
      explanation: 'Man berarti siapa.',
    ),
    QuestionItem(
      id: 'bah_arab_027',
      questionText: 'Kata tanya "Apa" untuk menanyakan benda dinamakan:',
      options: ['Ma (مَا)', 'Man', 'Hal', 'Maza'],
      correctOptionIndex: 0,
      explanation: 'Ma/Maza berarti apa.',
    ),
    QuestionItem(
      id: 'bah_arab_028',
      questionText: 'Kata tanya "Di mana" untuk menanyakan tempat dinamakan:',
      options: ['Aina (أَيْنَ)', 'Kaifa', 'Mata', 'Kam'],
      correctOptionIndex: 0,
      explanation: 'Aina berarti di mana.',
    ),
    QuestionItem(
      id: 'bah_arab_029',
      questionText: 'Kata tanya "Bagaimana" untuk menanyakan kabar/kondisi dinamakan:',
      options: ['Kaifa (كَيْفَ)', 'Aina', 'Mata', 'Hal'],
      correctOptionIndex: 0,
      explanation: 'Kaifa berarti bagaimana (contoh: Kaifa haluk?).',
    ),
    QuestionItem(
      id: 'bah_arab_030',
      questionText: 'Kata tanya "Kapan" untuk menanyakan waktu dinamakan:',
      options: ['Mata (مَتَى)', 'Aina', 'Kam', 'Man'],
      correctOptionIndex: 0,
      explanation: 'Mata berarti kapan.',
    ),
    QuestionItem(
      id: 'bah_arab_031',
      questionText: 'Kata tanya "Berapa" untuk menanyakan jumlah dinamakan:',
      options: ['Kam (كَمْ)', 'Mata', 'Kaifa', 'Hal'],
      correctOptionIndex: 0,
      explanation: 'Kam berarti berapa.',
    ),
    QuestionItem(
      id: 'bah_arab_032',
      questionText: 'Kata tanya "Apakah" untuk konfirmasi jawaban Ya/Tidak dinamakan:',
      options: ['Hal (هَلْ)', 'Man', 'Ma', 'Aina'],
      correctOptionIndex: 0,
      explanation: 'Hal bermakna apakah (dijawab Na\'am atau Laa).',
    ),
    QuestionItem(
      id: 'bah_arab_033',
      questionText: 'Jawaban "Ya" dalam Bahasa Arab adalah:',
      options: ['Na\'am (نَعَمْ)', 'Laa', 'Bala', 'Kalla'],
      correctOptionIndex: 0,
      explanation: 'Na\'am berarti Ya.',
    ),
    QuestionItem(
      id: 'bah_arab_034',
      questionText: 'Jawaban "Tidak / Bukan" dalam Bahasa Arab adalah:',
      options: ['Laa (لَا)', 'Na\'am', 'Afwan', 'Syukran'],
      correctOptionIndex: 0,
      explanation: 'Laa berarti tidak.',
    ),
    QuestionItem(
      id: 'bah_arab_035',
      questionText: 'Kata kerja "Membaca" (Mazi/Past) untuk Huwa adalah:',
      options: ['Qara-a (قَرَأَ)', 'Kataba', 'Jalasa', 'Zahaba'],
      correctOptionIndex: 0,
      explanation: 'Qara-a berarti telah membaca.',
    ),
    QuestionItem(
      id: 'bah_arab_036',
      questionText: 'Kata kerja "Menulis" (Mazi/Past) untuk Huwa adalah:',
      options: ['Kataba (كَتَبَ)', 'Qara-a', 'Akala', 'Syariba'],
      correctOptionIndex: 0,
      explanation: 'Kataba berarti telah menulis.',
    ),
    QuestionItem(
      id: 'bah_arab_037',
      questionText: 'Kata kerja "Pergi" (Mazi/Past) untuk Huwa adalah:',
      options: ['Zahaba (ذَهَبَ)', 'Raja\'a', 'Dakhala', 'Kharaja'],
      correctOptionIndex: 0,
      explanation: 'Zahaba berarti telah pergi.',
    ),
    QuestionItem(
      id: 'bah_arab_038',
      questionText: 'Kata kerja "Pulang / Kembali" (Mazi) untuk Huwa adalah:',
      options: ['Raja\'a (رَجَعَ)', 'Zahaba', 'Nazafe', 'Fataha'],
      correctOptionIndex: 0,
      explanation: 'Raja\'a berarti telah kembali/pulang.',
    ),
    QuestionItem(
      id: 'bah_arab_039',
      questionText: 'Kata kerja "Makan" (Mazi) untuk Huwa adalah:',
      options: ['Akala (أَكَلَ)', 'Syariba', 'Nāma', 'Qāma'],
      correctOptionIndex: 0,
      explanation: 'Akala berarti telah makan.',
    ),
    QuestionItem(
      id: 'bah_arab_040',
      questionText: 'Kata kerja "Minum" (Mazi) untuk Huwa adalah:',
      options: ['Syariba (شَرِبَ)', 'Akala', 'Tabaḥa', 'Gasala'],
      correctOptionIndex: 0,
      explanation: 'Syariba berarti telah minum.',
    ),
    QuestionItem(
      id: 'bah_arab_041',
      questionText: 'Arti dari ungkapan "Masjidun" (مَسْجِدٌ) adalah:',
      options: ['Masjid / Tempat Sujud', 'Gereja', 'Pasar', 'Stasion'],
      correctOptionIndex: 0,
      explanation: 'Masjidun berarti tempat ibadah masjid.',
    ),
    QuestionItem(
      id: 'bah_arab_042',
      questionText: 'Arti dari ungkapan "Suuq" (سُوقٌ) adalah:',
      options: ['Pasar', 'Toko', 'Jalan', 'Taman'],
      correctOptionIndex: 0,
      explanation: 'Suuq berarti pasar tempat jual beli.',
    ),
    QuestionItem(
      id: 'bah_arab_043',
      questionText: 'Arti dari ungkapan "Syari\'" (شَارِعٌ) adalah:',
      options: ['Jalan Raya', 'Lorong', 'Jembatan', 'Lapangan'],
      correctOptionIndex: 0,
      explanation: 'Syari\' berarti jalan raya.',
    ),
    QuestionItem(
      id: 'bah_arab_044',
      questionText: 'Arti dari ungkapan "Mustasfa" (مُسْتَشْفَى) adalah:',
      options: ['Rumah Sakit', 'Apotek', 'Laboratorium', 'Klinik'],
      correctOptionIndex: 0,
      explanation: 'Mustasfa berarti rumah sakit.',
    ),
    QuestionItem(
      id: 'bah_arab_045',
      questionText: 'Arti dari ungkapan "Mat\'am" (مَطْعَمٌ) adalah:',
      options: ['Restoran / Rumah Makan', 'Dapur', 'Hotel', 'Kantin'],
      correctOptionIndex: 0,
      explanation: 'Mat\'am berarti restoran/rumah makan.',
    ),
    QuestionItem(
      id: 'bah_arab_046',
      questionText: 'Arti dari ungkapan "Matar" (مَطَارٌ) adalah:',
      options: ['Bandara / Bandara Udara', 'Stasiun', 'Pelabuhan', 'Terminal'],
      correctOptionIndex: 0,
      explanation: 'Matar berarti bandara.',
    ),
    QuestionItem(
      id: 'bah_arab_047',
      questionText: 'Arti dari ungkapan "Minaa\'" (مِينَاءٌ) adalah:',
      options: ['Pelabuhan Laut', 'Bandara', 'Rel', 'Dermaga'],
      correctOptionIndex: 0,
      explanation: 'Minaa\' berarti pelabuhan.',
    ),
    QuestionItem(
      id: 'bah_arab_048',
      questionText: 'Arti kata "Ustadz" (أُسْتَاذٌ) adalah:',
      options: ['Guru / Dosen Laki-laki', 'Siswa', 'Kepala Sekolah', 'Pegawai'],
      correctOptionIndex: 0,
      explanation: 'Ustadz berarti guru/pengajar laki-laki.',
    ),
    QuestionItem(
      id: 'bah_arab_049',
      questionText: 'Arti kata "Thalib" (طَالِبٌ) adalah:',
      options: ['Siswa / Mahasiswa Laki-laki', 'Guru', 'Dokter', 'Pedagang'],
      correctOptionIndex: 0,
      explanation: 'Thalib berarti penuntut ilmu/siswa.',
    ),
    QuestionItem(
      id: 'bah_arab_050',
      questionText: 'Arti kata "Thabib" (طَبِيبٌ) adalah:',
      options: ['Dokter Laki-laki', 'Perawat', 'Apoteker', 'Insinyur'],
      correctOptionIndex: 0,
      explanation: 'Thabib berarti dokter.',
    ),
    QuestionItem(
      id: 'bah_arab_051',
      questionText: 'Arti kata "Muhandis" (مُهَنْدِسٌ) adalah:',
      options: ['Insinyur / Arsitek', 'Polisi', 'Tentara', 'Pilot'],
      correctOptionIndex: 0,
      explanation: 'Muhandis berarti insinyur.',
    ),
    QuestionItem(
      id: 'bah_arab_052',
      questionText: 'Arti kata "Syurthiyyun" (شُرْطِيٌّ) adalah:',
      options: ['Polisi', 'Tentara', 'Hakim', 'Jaksa'],
      correctOptionIndex: 0,
      explanation: 'Syurthiyyun berarti polisi.',
    ),
    QuestionItem(
      id: 'bah_arab_053',
      questionText: 'Arti kata "Tajir" (تَاجِرٌ) adalah:',
      options: ['Pedagang / Pebisnis', 'Petani', 'Nelayan', 'Penjahit'],
      correctOptionIndex: 0,
      explanation: 'Tajir berarti pedagang.',
    ),
    QuestionItem(
      id: 'bah_arab_054',
      questionText: 'Arti kata "Fallah" (فَلَّاحٌ) adalah:',
      options: ['Petani', 'Nelayan', 'Peternak', 'Koki'],
      correctOptionIndex: 0,
      explanation: 'Fallah berarti petani.',
    ),
    QuestionItem(
      id: 'bah_arab_055',
      questionText: 'Arti kata "Sayyad" (صَيَّادٌ) adalah:',
      options: ['Nelayan / Pemburu', 'Petani', 'Sopir', 'Masinis'],
      correctOptionIndex: 0,
      explanation: 'Sayyad berarti nelayan/pemburu.',
    ),
    QuestionItem(
      id: 'bah_arab_056',
      questionText: 'Kata depan (Harf Jar) "Fi" (فِي) bermakna:',
      options: ['Di dalam / Pada', 'Ke', 'Dari', 'Di atas'],
      correctOptionIndex: 0,
      explanation: 'Fi berarti di dalam/pada.',
    ),
    QuestionItem(
      id: 'bah_arab_057',
      questionText: 'Kata depan (Harf Jar) "Ila" (إِلَى) bermakna:',
      options: ['Ke / Ke arah', 'Dari', 'Di bawah', 'Bersama'],
      correctOptionIndex: 0,
      explanation: 'Ila berarti ke.',
    ),
    QuestionItem(
      id: 'bah_arab_058',
      questionText: 'Kata depan (Harf Jar) "Min" (مِنْ) bermakna:',
      options: ['Dari', 'Ke', 'Di dalam', 'Untuk'],
      correctOptionIndex: 0,
      explanation: 'Min berarti dari.',
    ),
    QuestionItem(
      id: 'bah_arab_059',
      questionText: 'Kata depan (Harf Jar) "\'Ala" (عَلَى) bermakna:',
      options: ['Di atas (menempel)', 'Di bawah', 'Di samping', 'Di depan'],
      correctOptionIndex: 0,
      explanation: '\'Ala berarti di atas menempel.',
    ),
    QuestionItem(
      id: 'bah_arab_060',
      questionText: 'Kata keterangan tempat (Zaraf) "Amama" (أَمَامَ) bermakna:',
      options: ['Di depan', 'Di belakang', 'Di atas', 'Di bawah'],
      correctOptionIndex: 0,
      explanation: 'Amama berarti di depan.',
    ),
    QuestionItem(
      id: 'bah_arab_061',
      questionText: 'Kata keterangan tempat "Wara-a" (وَرَاءَ) / "Khalfa" bermakna:',
      options: ['Di belakang', 'Di depan', 'Di samping', 'Di antara'],
      correctOptionIndex: 0,
      explanation: 'Wara-a/Khalfa berarti di belakang.',
    ),
    QuestionItem(
      id: 'bah_arab_062',
      questionText: 'Kata keterangan tempat "Fauqa" (فَوْقَ) bermakna:',
      options: ['Di atas (melayang / tidak menempel)', 'Di bawah', 'Di samping', 'Di dalam'],
      correctOptionIndex: 0,
      explanation: 'Fauqa berarti di atas melayang.',
    ),
    QuestionItem(
      id: 'bah_arab_063',
      questionText: 'Kata keterangan tempat "Tahta" (تَحْتَ) bermakna:',
      options: ['Di bawah', 'Di atas', 'Di depan', 'Di samping'],
      correctOptionIndex: 0,
      explanation: 'Tahta berarti di bawah.',
    ),
    QuestionItem(
      id: 'bah_arab_064',
      questionText: 'Kata keterangan tempat "Janiba" (جَانِبَ) bermakna:',
      options: ['Di samping', 'Di depan', 'Di belakang', 'Di tengah'],
      correctOptionIndex: 0,
      explanation: 'Janiba berarti di samping.',
    ),
    QuestionItem(
      id: 'bah_arab_065',
      questionText: 'Arti kata "Abun" (أَبٌ) adalah:',
      options: ['Ayah', 'Ibu', 'Saudara', 'Kakek'],
      correctOptionIndex: 0,
      explanation: 'Abun berarti ayah.',
    ),
    QuestionItem(
      id: 'bah_arab_066',
      questionText: 'Arti kata "Ummun" (أُمٌّ) adalah:',
      options: ['Ibu', 'Ayah', 'Nenek', 'Bibi'],
      correctOptionIndex: 0,
      explanation: 'Ummun berarti ibu.',
    ),
    QuestionItem(
      id: 'bah_arab_067',
      questionText: 'Arti kata "Akhun" (أَخٌ) adalah:',
      options: ['Saudara Laki-laki', 'Saudari Perempuan', 'Paman', 'Bibi'],
      correctOptionIndex: 0,
      explanation: 'Akhun berarti saudara laki-laki.',
    ),
    QuestionItem(
      id: 'bah_arab_068',
      questionText: 'Arti kata "Ukhtun" (أُخْتٌ) adalah:',
      options: ['Saudari Perempuan', 'Saudara Laki-laki', 'Ibu', 'Nenek'],
      correctOptionIndex: 0,
      explanation: 'Ukhtun berarti saudari perempuan.',
    ),
    QuestionItem(
      id: 'bah_arab_069',
      questionText: 'Arti kata "Jaddun" (جَدٌّ) adalah:',
      options: ['Kakek', 'Nenek', 'Paman', 'Bapak'],
      correctOptionIndex: 0,
      explanation: 'Jaddun berarti kakek.',
    ),
    QuestionItem(
      id: 'bah_arab_070',
      questionText: 'Arti kata "Jaddatun" (جَدَّةٌ) adalah:',
      options: ['Nenek', 'Kakek', 'Ibu', 'Bibi'],
      correctOptionIndex: 0,
      explanation: 'Jaddatun berarti nenek.',
    ),
    QuestionItem(
      id: 'bah_arab_071',
      questionText: 'Arti kata "Ahad" (الأَحَد) dalam nama hari adalah hari:',
      options: ['Minggu / Ahad', 'Senin', 'Selasa', 'Rabu'],
      correctOptionIndex: 0,
      explanation: 'Al-Ahad berarti hari Minggu.',
    ),
    QuestionItem(
      id: 'bah_arab_072',
      questionText: 'Arti kata "Al-Isnain" (الإِثْنَيْن) adalah hari:',
      options: ['Senin', 'Selasa', 'Rabu', 'Kamis'],
      correctOptionIndex: 0,
      explanation: 'Al-Isnain berarti hari Senin.',
    ),
    QuestionItem(
      id: 'bah_arab_073',
      questionText: 'Arti kata "Al-Jumu\'ah" (الْجُمُعَة) adalah hari:',
      options: ['Jumat', 'Sabtu', 'Kamis', 'Rabu'],
      correctOptionIndex: 0,
      explanation: 'Al-Jumu\'ah berarti hari Jumat.',
    ),
    QuestionItem(
      id: 'bah_arab_074',
      questionText: 'Arti kata "As-Sabt" (السَّبْت) adalah hari:',
      options: ['Sabtu', 'Minggu', 'Jumat', 'Senin'],
      correctOptionIndex: 0,
      explanation: 'As-Sabt berarti hari Sabtu.',
    ),
    QuestionItem(
      id: 'bah_arab_075',
      questionText: 'Kata "Ahmar" (أَحْمَرُ) melambangkan warna:',
      options: ['Merah', 'Putih', 'Hitam', 'Hijau'],
      correctOptionIndex: 0,
      explanation: 'Ahmar berarti merah.',
    ),
    QuestionItem(
      id: 'bah_arab_076',
      questionText: 'Kata "Abyad" (أَبْيَضُ) melambangkan warna:',
      options: ['Putih', 'Hitam', 'Biru', 'Kuning'],
      correctOptionIndex: 0,
      explanation: 'Abyad berarti putih.',
    ),
    QuestionItem(
      id: 'bah_arab_077',
      questionText: 'Kata "Aswad" (أَسْوَدُ) melambangkan warna:',
      options: ['Hitam', 'Merah', 'Hijau', 'Cokelat'],
      correctOptionIndex: 0,
      explanation: 'Aswad berarti hitam.',
    ),
    QuestionItem(
      id: 'bah_arab_078',
      questionText: 'Kata "Akhdar" (أَخْضَرُ) melambangkan warna:',
      options: ['Hijau', 'Kuning', 'Biru', 'Merah'],
      correctOptionIndex: 0,
      explanation: 'Akhdar berarti hijau.',
    ),
    QuestionItem(
      id: 'bah_arab_079',
      questionText: 'Kata "Azraq" (أَزْرَقُ) melambangkan warna:',
      options: ['Biru', 'Kuning', 'Ungu', 'Abu-abu'],
      correctOptionIndex: 0,
      explanation: 'Azraq berarti biru.',
    ),
    QuestionItem(
      id: 'bah_arab_080',
      questionText: 'Kata "Asfar" (أَصْفَرُ) melambangkan warna:',
      options: ['Kuning', 'Merah', 'Oranye', 'Cokelat'],
      correctOptionIndex: 0,
      explanation: 'Asfar berarti kuning.',
    ),
    QuestionItem(
      id: 'bah_arab_081',
      questionText: 'Arti kata "Ra\'sun" (رَأْسٌ) pada anggota tubuh adalah:',
      options: ['Kepala', 'Mata', 'Telinga', 'Tangan'],
      correctOptionIndex: 0,
      explanation: 'Ra\'sun berarti kepala.',
    ),
    QuestionItem(
      id: 'bah_arab_082',
      questionText: 'Arti kata "\'Ainun" (عَيْنٌ) adalah:',
      options: ['Mata', 'Hidung', 'Mulut', 'Wajah'],
      correctOptionIndex: 0,
      explanation: '\'Ainun berarti mata.',
    ),
    QuestionItem(
      id: 'bah_arab_083',
      questionText: 'Arti kata "Anfun" (أَنْفٌ) adalah:',
      options: ['Hidung', 'Mata', 'Telinga', 'Dagu'],
      correctOptionIndex: 0,
      explanation: 'Anfun berarti hidung.',
    ),
    QuestionItem(
      id: 'bah_arab_084',
      questionText: 'Arti kata "Famun" (فَمٌ) adalah:',
      options: ['Mulut', 'Gigi', 'Lidah', 'Bibir'],
      correctOptionIndex: 0,
      explanation: 'Famun berarti mulut.',
    ),
    QuestionItem(
      id: 'bah_arab_085',
      questionText: 'Arti kata "Uzunun" (أُذُنٌ) adalah:',
      options: ['Telinga', 'Mata', 'Kepala', 'Rambut'],
      correctOptionIndex: 0,
      explanation: 'Uzunun berarti telinga.',
    ),
    QuestionItem(
      id: 'bah_arab_086',
      questionText: 'Arti kata "Yadun" (يَدٌ) adalah:',
      options: ['Tangan', 'Kaki', 'Jari', 'Lengan'],
      correctOptionIndex: 0,
      explanation: 'Yadun berarti tangan.',
    ),
    QuestionItem(
      id: 'bah_arab_087',
      questionText: 'Arti kata "Rijlun" (رِجْلٌ) adalah:',
      options: ['Kaki', 'Tangan', 'Lutut', 'Paha'],
      correctOptionIndex: 0,
      explanation: 'Rijlun berarti kaki.',
    ),
    QuestionItem(
      id: 'bah_arab_088',
      questionText: 'Arti ungkapan "Ma ismuka?" (مَا اسْمُكَ؟) adalah:',
      options: ['Siapa namamu?', 'Di mana rumahmu?', 'Berapa umuranmu?', 'Apa pekerjaanmu?'],
      correctOptionIndex: 0,
      explanation: 'Ma ismuka menanyakan nama.',
    ),
    QuestionItem(
      id: 'bah_arab_089',
      questionText: 'Arti ungkapan "Min aina anta?" (مِنْ أَيْنَ أَنْتَ؟) adalah:',
      options: ['Dari mana kamu berasal?', 'Ke mana kamu akan pergi?', 'Di mana kamu tinggal?', 'Siapa temanku?'],
      correctOptionIndex: 0,
      explanation: 'Min aina anta menanyakan asal tempat.',
    ),
    QuestionItem(
      id: 'bah_arab_090',
      questionText: 'Arti ungkapan perpisahan "Ma\'as Salamah" (مَعَ السَّلاَمَةِ) adalah:',
      options: ['Selamat tinggal / Semoga selamat', 'Selamat pagi', 'Selamat datang', 'Sampai besok'],
      correctOptionIndex: 0,
      explanation: 'Ma\'as Salamah adalah ungkapan perpisahan.',
    ),
    QuestionItem(
      id: 'bah_arab_091',
      questionText: 'Jawaban dari ungkapan "Ma\'as Salamah" adalah:',
      options: ['Fi Amanillah (فِي أَمَانِ اللهِ)', 'Syukran', 'Afwan', 'Ahlan bika'],
      correctOptionIndex: 0,
      explanation: 'Fi Amanillah (semoga dalam perlindungan Allah) balasan ma\'as salamah.',
    ),
    QuestionItem(
      id: 'bah_arab_092',
      questionText: 'Kata "Sayyaratun" (سَيَّارَةٌ) bermakna alat transportasi:',
      options: ['Mobil', 'Sepeda Motor', 'Sepeda', 'Bus'],
      correctOptionIndex: 0,
      explanation: 'Sayyaratun berarti mobil.',
    ),
    QuestionItem(
      id: 'bah_arab_093',
      questionText: 'Kata "Hafilatun" (حَافِلَةٌ) bermakna alat transportasi:',
      options: ['Bus', 'Kereta', 'Mobil', 'Taksi'],
      correctOptionIndex: 0,
      explanation: 'Hafilatun berarti bus.',
    ),
    QuestionItem(
      id: 'bah_arab_094',
      questionText: 'Kata "Qithar" (قِطَارٌ) bermakna alat transportasi:',
      options: ['Kereta Api', 'Pesawat', 'Kapal Laut', 'Truk'],
      correctOptionIndex: 0,
      explanation: 'Qithar berarti kereta api.',
    ),
    QuestionItem(
      id: 'bah_arab_095',
      questionText: 'Kata "Tha\'irah" (طَائِرَةٌ) bermakna alat transportasi:',
      options: ['Pesawat Terbang', 'Helikopter', 'Kapal', 'Sepeda'],
      correctOptionIndex: 0,
      explanation: 'Tha\'irah berarti pesawat terbang.',
    ),
    QuestionItem(
      id: 'bah_arab_096',
      questionText: 'Kata "Safinah" (سَفِينَةٌ) bermakna alat transportasi:',
      options: ['Kapal Laut', 'Perahu', 'Pesawat', 'Truk'],
      correctOptionIndex: 0,
      explanation: 'Safinah berarti kapal laut.',
    ),
    QuestionItem(
      id: 'bah_arab_097',
      questionText: 'Kata "Darrajatun" (دَرَّاجَةٌ) bermakna alat transportasi:',
      options: ['Sepeda', 'Motor', 'Mobil', 'Delman'],
      correctOptionIndex: 0,
      explanation: 'Darrajatun berarti sepeda.',
    ),
    QuestionItem(
      id: 'bah_arab_098',
      questionText: 'Istilah "Al-Lughah Al-\'Arabiyyah" (اللُّغَةُ العَرَبِيَّةُ) berarti:',
      options: ['Bahasa Arab', 'Bahasa Asing', 'Sastra Arab', 'Tata Bahasa'],
      correctOptionIndex: 0,
      explanation: 'Al-Lughah Al-\'Arabiyyah berarti Bahasa Arab.',
    ),
    QuestionItem(
      id: 'bah_arab_099',
      questionText: 'Organisasi internasional gabungan negara-negara berbahasa Arab dinamakan:',
      options: ['Liga Arab (Jamia\'at ad-Duwal al-\'Arabiyyah)', 'OIK', 'ASEAN', 'GCC'],
      correctOptionIndex: 0,
      explanation: 'Liga Arab adalah perserikatan negara-negara Arab.',
    ),
    QuestionItem(
      id: 'bah_arab_100',
      questionText: 'Hari Bahasa Arab Sedunia diperingati oleh UNESCO setiap tanggal:',
      options: ['18 Desember', '17 Agustus', '1 Mei', '24 Oktober'],
      correctOptionIndex: 0,
      explanation: '18 Desember ditetapkan UNESCO sebagai Hari Bahasa Arab Sedunia.',
    ),
  ];
}
