import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesBahasaInggrisQuestions() {
  return const [
    QuestionItem(
      id: 'bah_ing_001',
      questionText: 'What is the correct past tense form of the irregular verb "to fly"?',
      options: ['Flew', 'Flown', 'Flyed', 'Fling'],
      correctOptionIndex: 0,
      explanation: 'The simple past tense of fly is flew, while flown is the past participle.',
    ),
    QuestionItem(
      id: 'bah_ing_002',
      questionText: 'Choose the correct conditional sentence type 2: "If I _____ rich, I would travel the world."',
      options: ['were', 'was', 'am', 'had been'],
      correctOptionIndex: 0,
      explanation: 'In hypothetical type 2 conditionals, "were" is standard for all subjects.',
    ),
    QuestionItem(
      id: 'bah_ing_003',
      questionText: 'Identify the passive voice structure of: "The manager approved the report."',
      options: ['The report was approved by the manager.', 'The report is approved by manager.', 'The manager was approving report.', 'The report has approved.'],
      correctOptionIndex: 0,
      explanation: 'Simple past passive requires Object + was/were + past participle (V3).',
    ),
    QuestionItem(
      id: 'bah_ing_004',
      questionText: 'Which preposition correctly completes the sentence: "She has been working here _____ 2018."',
      options: ['since', 'for', 'during', 'from'],
      correctOptionIndex: 0,
      explanation: '"Since" indicates the starting point of a specific point in time.',
    ),
    QuestionItem(
      id: 'bah_ing_005',
      questionText: 'Which preposition is used for a duration of time: "We stayed in London _____ three weeks."',
      options: ['for', 'since', 'in', 'at'],
      correctOptionIndex: 0,
      explanation: '"For" specifies the duration of a period of time.',
    ),
    QuestionItem(
      id: 'bah_ing_006',
      questionText: 'What does the idiom "piece of cake" mean in conversation?',
      options: ['Something very easy to do', 'A slice of dessert', 'A difficult task', 'An expensive gift'],
      correctOptionIndex: 0,
      explanation: '"Piece of cake" is an idiom meaning effortless or very easy.',
    ),
    QuestionItem(
      id: 'bah_ing_007',
      questionText: 'What does the idiom "break a leg" mean when said to a performer?',
      options: ['Good luck!', 'Be careful', 'Stop acting', 'Fall down'],
      correctOptionIndex: 0,
      explanation: '"Break a leg" is a theatrical idiom used to wish good luck.',
    ),
    QuestionItem(
      id: 'bah_ing_008',
      questionText: 'Select the correct adjective order: "She bought a _____ bag."',
      options: ['beautiful small Italian leather', 'small beautiful Italian leather', 'Italian leather small beautiful', 'leather small Italian beautiful'],
      correctOptionIndex: 0,
      explanation: 'OSASCOMP order: Opinion (beautiful), Size (small), Origin (Italian), Material (leather).',
    ),
    QuestionItem(
      id: 'bah_ing_009',
      questionText: 'Which modal verb expresses strong necessity or legal obligation?',
      options: ['Must', 'Might', 'Could', 'Should'],
      correctOptionIndex: 0,
      explanation: '"Must" denotes mandatory obligation or necessity.',
    ),
    QuestionItem(
      id: 'bah_ing_010',
      questionText: 'Identify the word with the opposite meaning (antonym) to "Abundant":',
      options: ['Scarce', 'Plentiful', 'Ample', 'Copious'],
      correctOptionIndex: 0,
      explanation: '"Scarce" means in short supply, opposite of abundant.',
    ),
    QuestionItem(
      id: 'bah_ing_011',
      questionText: 'Identify the synonym for the word "Meticulous":',
      options: ['Careful and precise', 'Careless', 'Hasty', 'Sloppy'],
      correctOptionIndex: 0,
      explanation: '"Meticulous" means showing great attention to detail.',
    ),
    QuestionItem(
      id: 'bah_ing_012',
      questionText: 'Which sentence demonstrates correct subject-verb agreement?',
      options: ['Neither of the students is present.', 'Neither of the students are present.', 'Neither of students were present.', 'Neither student be here.'],
      correctOptionIndex: 0,
      explanation: '"Neither" as a pronoun takes a singular verb (is).',
    ),
    QuestionItem(
      id: 'bah_ing_013',
      questionText: 'What is the noun form of the verb "Analyze"?',
      options: ['Analysis', 'Analytic', 'Analyst', 'Analytically'],
      correctOptionIndex: 0,
      explanation: '"Analysis" is the noun form of the verb analyze.',
    ),
    QuestionItem(
      id: 'bah_ing_014',
      questionText: 'Choose the correct relative pronoun: "The scientist _____ discovered the vaccine won the award."',
      options: ['who', 'which', 'whom', 'whose'],
      correctOptionIndex: 0,
      explanation: '"Who" is used for persons as the subject of the clause.',
    ),
    QuestionItem(
      id: 'bah_ing_015',
      questionText: 'Choose the correct possessive relative pronoun: "The boy _____ bicycle was stolen cried."',
      options: ['whose', 'who', 'whom', 'which'],
      correctOptionIndex: 0,
      explanation: '"Whose" indicates possession.',
    ),
    QuestionItem(
      id: 'bah_ing_016',
      questionText: 'What does "Brevity" mean in formal writing?',
      options: ['Conciseness and exact use of words', 'Lengthiness', 'Complexity', 'Redundancy'],
      correctOptionIndex: 0,
      explanation: '"Brevity" refers to briefness and conciseness.',
    ),
    QuestionItem(
      id: 'bah_ing_017',
      questionText: 'Complete the sentence: "Hardly _____ entered the room when the lights went out."',
      options: ['had I', 'I had', 'did I', 'I did'],
      correctOptionIndex: 0,
      explanation: 'Inversion occurs after negative adverbials like "Hardly had + Subject + V3".',
    ),
    QuestionItem(
      id: 'bah_ing_018',
      questionText: 'Which phrase is appropriate for starting a formal business email?',
      options: ['Dear Mr. Smith,', 'Hey Smith!', 'Yo what\'s up,', 'Hiya Smith,'],
      correctOptionIndex: 0,
      explanation: '"Dear Mr. Smith," is the standard formal email greeting.',
    ),
    QuestionItem(
      id: 'bah_ing_019',
      questionText: 'What is the meaning of the phrasal verb "to call off"?',
      options: ['To cancel an event', 'To postpone', 'To phone someone', 'To shout loudly'],
      correctOptionIndex: 0,
      explanation: '"Call off" means to cancel.',
    ),
    QuestionItem(
      id: 'bah_ing_020',
      questionText: 'What is the meaning of the phrasal verb "to put off"?',
      options: ['To postpone / delay', 'To extinguish', 'To wear clothes', 'To turn off'],
      correctOptionIndex: 0,
      explanation: '"Put off" means to delay or postpone.',
    ),
    QuestionItem(
      id: 'bah_ing_021',
      questionText: 'Which word means "lasting for a very short time"?',
      options: ['Ephemeral', 'Eternal', 'Permanent', 'Perpetual'],
      correctOptionIndex: 0,
      explanation: '"Ephemeral" means short-lived or transitory.',
    ),
    QuestionItem(
      id: 'bah_ing_022',
      questionText: 'What is the term for a word that sounds the same as another word but has a different meaning?',
      options: ['Homophone', 'Homograph', 'Antonym', 'Synonym'],
      correctOptionIndex: 0,
      explanation: 'Homophones sound identical (e.g., hear/here).',
    ),
    QuestionItem(
      id: 'bah_ing_023',
      questionText: 'Which sentence contains a dangling modifier error?',
      options: ['Walking down the street, the tree fell on the car.', 'While I was walking, a tree fell.', 'The tree fell after I walked past.', 'I saw the tree fall.'],
      correctOptionIndex: 0,
      explanation: '"Walking down the street" incorrectly modifies "the tree".',
    ),
    QuestionItem(
      id: 'bah_ing_024',
      questionText: 'Identify the gerund in the sentence: "Swimming is my favorite summer sport."',
      options: ['Swimming', 'favorite', 'summer', 'sport'],
      correctOptionIndex: 0,
      explanation: '"Swimming" functions as a verbal noun (gerund).',
    ),
    QuestionItem(
      id: 'bah_ing_025',
      questionText: 'Which auxiliary verb completes the present perfect continuous: "They _____ been studying for hours."',
      options: ['have', 'has', 'are', 'were'],
      correctOptionIndex: 0,
      explanation: 'Plural subject "They" takes "have been V-ing".',
    ),
    QuestionItem(
      id: 'bah_ing_026',
      questionText: 'What is the correct reported speech for: He said, "I am hungry."',
      options: ['He said that he was hungry.', 'He said he is hungry.', 'He tells he was hungry.', 'He said that I am hungry.'],
      correctOptionIndex: 0,
      explanation: 'Present simple "am" shifts back to past simple "was" in reported speech.',
    ),
    QuestionItem(
      id: 'bah_ing_027',
      questionText: 'Which suffix converts the adjective "Happy" into a noun?',
      options: ['-ness (Happiness)', '-ment', '-ity', '-ful'],
      correctOptionIndex: 0,
      explanation: 'Adding -ness forms abstract nouns from adjectives (happiness).',
    ),
    QuestionItem(
      id: 'bah_ing_028',
      questionText: 'Which suffix converts the verb "Develop" into a noun?',
      options: ['-ment (Development)', '-ness', '-able', '-tion'],
      correctOptionIndex: 0,
      explanation: 'Adding -ment forms nouns from verbs (development).',
    ),
    QuestionItem(
      id: 'bah_ing_029',
      questionText: 'Choose the correct question tag: "She is a doctor, _____?"',
      options: ['isn\'t she?', 'is she?', 'doesn\'t she?', 'wasn\'t she?'],
      correctOptionIndex: 0,
      explanation: 'Positive sentence with "is" takes negative tag "isn\'t she?".',
    ),
    QuestionItem(
      id: 'bah_ing_030',
      questionText: 'Choose the correct question tag: "You don\'t smoke, _____?"',
      options: ['do you?', 'don\'t you?', 'are you?', 'did you?'],
      correctOptionIndex: 0,
      explanation: 'Negative sentence with "don\'t" takes positive tag "do you?".',
    ),
    QuestionItem(
      id: 'bah_ing_031',
      questionText: 'What is the plural form of the noun "Criterion"?',
      options: ['Criteria', 'Criterions', 'Criterias', 'Criterium'],
      correctOptionIndex: 0,
      explanation: '"Criteria" is the Greek-origin plural of criterion.',
    ),
    QuestionItem(
      id: 'bah_ing_032',
      questionText: 'What is the plural form of the noun "Phenomenon"?',
      options: ['Phenomena', 'Phenomenons', 'Phenomenas', 'Phenomeni'],
      correctOptionIndex: 0,
      explanation: '"Phenomena" is the plural of phenomenon.',
    ),
    QuestionItem(
      id: 'bah_ing_033',
      questionText: 'Which word means "fear of enclosed spaces"?',
      options: ['Claustrophobia', 'Acrophobia', 'Agoraphobia', 'Hydrophobia'],
      correctOptionIndex: 0,
      explanation: 'Claustrophobia is fear of confined/enclosed spaces.',
    ),
    QuestionItem(
      id: 'bah_ing_034',
      questionText: 'Which word means "fear of heights"?',
      options: ['Acrophobia', 'Claustrophobia', 'Agoraphobia', 'Xenophobia'],
      correctOptionIndex: 0,
      explanation: 'Acrophobia is fear of heights.',
    ),
    QuestionItem(
      id: 'bah_ing_035',
      questionText: 'Choose the sentence with correct punctuation:',
      options: ['I need to buy apples, oranges, and bananas.', 'I need to buy apples oranges, and bananas', 'I need, to buy apples, oranges', 'I need to buy: apples oranges'],
      correctOptionIndex: 0,
      explanation: 'The Oxford comma serial punctuation lists items clearly.',
    ),
    QuestionItem(
      id: 'bah_ing_036',
      questionText: 'What does the Latin abbreviation "e.g." stand for in English?',
      options: ['Exempli gratia (For example)', 'Id est (That is)', 'Et cetera (And so on)', 'Nota bene (Note well)'],
      correctOptionIndex: 0,
      explanation: '"e.g." stands for exempli gratia, meaning "for example".',
    ),
    QuestionItem(
      id: 'bah_ing_037',
      questionText: 'What does the Latin abbreviation "i.e." stand for in English?',
      options: ['Id est (That is / In other words)', 'Exempli gratia', 'Et cetera', 'Ibidem'],
      correctOptionIndex: 0,
      explanation: '"i.e." stands for id est, meaning "that is".',
    ),
    QuestionItem(
      id: 'bah_ing_038',
      questionText: 'Identify the superlative form of "Bad":',
      options: ['Worst', 'Worse', 'Badder', 'Baddest'],
      correctOptionIndex: 0,
      explanation: 'Bad - Worse - Worst.',
    ),
    QuestionItem(
      id: 'bah_ing_039',
      questionText: 'Identify the comparative form of "Good":',
      options: ['Better', 'Best', 'Gooder', 'Goodest'],
      correctOptionIndex: 0,
      explanation: 'Good - Better - Best.',
    ),
    QuestionItem(
      id: 'bah_ing_040',
      questionText: 'Complete the proverb: "Actions speak louder than _____."',
      options: ['words', 'thoughts', 'promises', 'speech'],
      correctOptionIndex: 0,
      explanation: '"Actions speak louder than words" means what you do matters more than what you say.',
    ),
    QuestionItem(
      id: 'bah_ing_041',
      questionText: 'Complete the proverb: "Every cloud has a silver _____."',
      options: ['lining', 'border', 'edge', 'color'],
      correctOptionIndex: 0,
      explanation: '"Every cloud has a silver lining" means every difficult situation has a hopeful aspect.',
    ),
    QuestionItem(
      id: 'bah_ing_042',
      questionText: 'What is the correct spelling of the word meaning a written agreement?',
      options: ['Contract', 'Contrakt', 'Contrac', 'Kantract'],
      correctOptionIndex: 0,
      explanation: 'Contract is spelled C-O-N-T-R-A-C-T.',
    ),
    QuestionItem(
      id: 'bah_ing_043',
      questionText: 'Which tense is used for an action completed before another past action?',
      options: ['Past Perfect', 'Past Continuous', 'Simple Past', 'Present Perfect'],
      correctOptionIndex: 0,
      explanation: 'Past Perfect (had + V3) describes an action prior to another past moment.',
    ),
    QuestionItem(
      id: 'bah_ing_044',
      questionText: 'Identify the conditional type 3: "If she _____ harder, she would have passed the exam."',
      options: ['had studied', 'studied', 'studies', 'has studied'],
      correctOptionIndex: 0,
      explanation: 'Type 3 conditional uses "had + V3" in the if-clause.',
    ),
    QuestionItem(
      id: 'bah_ing_045',
      questionText: 'What is the opposite of "Optimistic"?',
      options: ['Pessimistic', 'Realistic', 'Enthusiastic', 'Positive'],
      correctOptionIndex: 0,
      explanation: 'Pessimistic is the antonym of optimistic.',
    ),
    QuestionItem(
      id: 'bah_ing_046',
      questionText: 'What is the synonym of "Candid"?',
      options: ['Frank / Honest', 'Secretive', 'Deceitful', 'Shy'],
      correctOptionIndex: 0,
      explanation: '"Candid" means truthful and straightforward.',
    ),
    QuestionItem(
      id: 'bah_ing_047',
      questionText: 'Which part of speech modifies a verb, adjective, or another adverb?',
      options: ['Adverb', 'Adjective', 'Noun', 'Conjunction'],
      correctOptionIndex: 0,
      explanation: 'Adverbs modify verbs, adjectives, or other adverbs.',
    ),
    QuestionItem(
      id: 'bah_ing_048',
      questionText: 'Which part of speech modifies a noun or pronoun?',
      options: ['Adjective', 'Adverb', 'Verb', 'Preposition'],
      correctOptionIndex: 0,
      explanation: 'Adjectives describe or modify nouns/pronouns.',
    ),
    QuestionItem(
      id: 'bah_ing_049',
      questionText: 'Identify the type of clause: "the man [who lives next door] is a chef."',
      options: ['Relative / Adjective Clause', 'Noun Clause', 'Adverbial Clause', 'Prepositional Phrase'],
      correctOptionIndex: 0,
      explanation: 'It modifies the noun "man", so it is an adjective/relative clause.',
    ),
    QuestionItem(
      id: 'bah_ing_050',
      questionText: 'What does "Skimming" mean in reading comprehension?',
      options: ['Reading rapidly to get the main idea', 'Searching for a specific fact', 'Reading aloud', 'Memorizing text'],
      correctOptionIndex: 0,
      explanation: 'Skimming is quick reading to obtain the general gist.',
    ),
    QuestionItem(
      id: 'bah_ing_051',
      questionText: 'What does "Scanning" mean in reading comprehension?',
      options: ['Searching quickly for specific information or keywords', 'Reading for general gist', 'Summarizing text', 'Analyzing poetry'],
      correctOptionIndex: 0,
      explanation: 'Scanning is looking for specific data (dates, names).',
    ),
    QuestionItem(
      id: 'bah_ing_052',
      questionText: 'Which connector shows contrast: "_____ it was raining, we went for a walk."',
      options: ['Although', 'Because', 'Therefore', 'Furthermore'],
      correctOptionIndex: 0,
      explanation: '"Although" introduces a concessive/contrast clause.',
    ),
    QuestionItem(
      id: 'bah_ing_053',
      questionText: 'Which connector shows cause: "We stayed home _____ it was raining heavy."',
      options: ['because', 'despite', 'however', 'otherwise'],
      correctOptionIndex: 0,
      explanation: '"Because" states the reason/cause.',
    ),
    QuestionItem(
      id: 'bah_ing_054',
      questionText: 'What is the past participle of the verb "to write"?',
      options: ['Written', 'Wrote', 'Write', 'Writing'],
      correctOptionIndex: 0,
      explanation: 'Write - Wrote - Written.',
    ),
    QuestionItem(
      id: 'bah_ing_055',
      questionText: 'What is the past participle of the verb "to break"?',
      options: ['Broken', 'Broke', 'Break', 'Breaking'],
      correctOptionIndex: 0,
      explanation: 'Break - Broke - Broken.',
    ),
    QuestionItem(
      id: 'bah_ing_056',
      questionText: 'What is the past participle of the verb "to speak"?',
      options: ['Spoken', 'Spoke', 'Speak', 'Speaked'],
      correctOptionIndex: 0,
      explanation: 'Speak - Spoke - Spoken.',
    ),
    QuestionItem(
      id: 'bah_ing_057',
      questionText: 'Choose the correct form: "I look forward to _____ you soon."',
      options: ['seeing', 'see', 'saw', 'seen'],
      correctOptionIndex: 0,
      explanation: '"Look forward to" is followed by a gerund (V-ing).',
    ),
    QuestionItem(
      id: 'bah_ing_058',
      questionText: 'Choose the correct form: "She is used to _____ early in the morning."',
      options: ['waking up', 'wake up', 'woke up', 'waken'],
      correctOptionIndex: 0,
      explanation: '"Be used to" is followed by V-ing.',
    ),
    QuestionItem(
      id: 'bah_ing_059',
      questionText: 'What is the meaning of "Proactive"?',
      options: ['Taking action in advance rather than reacting', 'Lazy and slow', 'Reactive to events', 'Hesitant'],
      correctOptionIndex: 0,
      explanation: 'Proactive means taking initiative beforehand.',
    ),
    QuestionItem(
      id: 'bah_ing_060',
      questionText: 'Select the sentence with a subjunctive mood:',
      options: ['The doctor recommended that he rest.', 'He rests every day.', 'Is he resting now?', 'He rested yesterday.'],
      correctOptionIndex: 0,
      explanation: 'Subjunctive uses base verb "rest" after verbs of recommendation.',
    ),
    QuestionItem(
      id: 'bah_ing_061',
      questionText: 'Which acronym stands for Test of English as a Foreign Language?',
      options: ['TOEFL', 'IELTS', 'TOEIC', 'SAT'],
      correctOptionIndex: 0,
      explanation: 'TOEFL = Test of English as a Foreign Language.',
    ),
    QuestionItem(
      id: 'bah_ing_062',
      questionText: 'Which acronym stands for International English Language Testing System?',
      options: ['IELTS', 'TOEFL', 'GRE', 'GMAT'],
      correctOptionIndex: 0,
      explanation: 'IELTS = International English Language Testing System.',
    ),
    QuestionItem(
      id: 'bah_ing_063',
      questionText: 'What does "Bilingual" mean?',
      options: ['Able to speak two languages fluently', 'Able to speak three languages', 'Mute', 'Mono-tongue'],
      correctOptionIndex: 0,
      explanation: 'Bilingual refers to fluency in two languages.',
    ),
    QuestionItem(
      id: 'bah_ing_064',
      questionText: 'What does "Multilingual" mean?',
      options: ['Able to speak several/many languages', 'Speaking one language', 'Speaking no language', 'Deaf'],
      correctOptionIndex: 0,
      explanation: 'Multilingual refers to proficiency in multiple languages.',
    ),
    QuestionItem(
      id: 'bah_ing_065',
      questionText: 'Identify the correctly spelled word:',
      options: ['Accommodation', 'Acommodation', 'Accomodation', 'Acomodation'],
      correctOptionIndex: 0,
      explanation: 'Accommodation has double c and double m.',
    ),
    QuestionItem(
      id: 'bah_ing_066',
      questionText: 'Identify the correctly spelled word:',
      options: ['Embarrassment', 'Embarasment', 'Embarassment', 'Embarrasment'],
      correctOptionIndex: 0,
      explanation: 'Embarrassment has double r and double s.',
    ),
    QuestionItem(
      id: 'bah_ing_067',
      questionText: 'Identify the correctly spelled word:',
      options: ['Necessary', 'Neccessary', 'Necesary', 'Necessery'],
      correctOptionIndex: 0,
      explanation: 'Necessary has single c and double s.',
    ),
    QuestionItem(
      id: 'bah_ing_068',
      questionText: 'What is the opposite of "Mandatory"?',
      options: ['Optional', 'Compulsory', 'Obligatory', 'Required'],
      correctOptionIndex: 0,
      explanation: 'Optional is the antonym of mandatory.',
    ),
    QuestionItem(
      id: 'bah_ing_069',
      questionText: 'What is the synonym of "Compulsory"?',
      options: ['Mandatory', 'Optional', 'Voluntary', 'Free'],
      correctOptionIndex: 0,
      explanation: 'Compulsory means mandatory/required.',
    ),
    QuestionItem(
      id: 'bah_ing_070',
      questionText: 'Which punctuation mark is used to indicate possession or contraction?',
      options: ['Apostrophe (\')', 'Comma (,)', 'Hyphen (-)', 'Semicolon (;)'],
      correctOptionIndex: 0,
      explanation: 'Apostrophe shows possession (John\'s) or contraction (it\'s).',
    ),
    QuestionItem(
      id: 'bah_ing_071',
      questionText: 'Which punctuation mark joins two independent clauses without a conjunction?',
      options: ['Semicolon (;)', 'Colon (統)', 'Comma (,)', 'Dash (-)'],
      correctOptionIndex: 0,
      explanation: 'A semicolon links related independent clauses.',
    ),
    QuestionItem(
      id: 'bah_ing_072',
      questionText: 'What is the main purpose of an Introduction in academic writing?',
      options: ['To present thesis statement and background context', 'To list references', 'To present raw data tables', 'To conclude final thoughts'],
      correctOptionIndex: 0,
      explanation: 'Introduction sets context and states thesis.',
    ),
    QuestionItem(
      id: 'bah_ing_073',
      questionText: 'What is a "Thesis Statement"?',
      options: ['A sentence stating the main argument/purpose of an essay', 'A summary of bibliography', 'A random fact', 'A quote from an author'],
      correctOptionIndex: 0,
      explanation: 'Thesis statement declares the central claim of an essay.',
    ),
    QuestionItem(
      id: 'bah_ing_074',
      questionText: 'Choose the correct form: "By next month, I _____ here for five years."',
      options: ['will have worked', 'will work', 'am working', 'worked'],
      correctOptionIndex: 0,
      explanation: 'Future Perfect (will have + V3) indicates completion prior to a future point.',
    ),
    QuestionItem(
      id: 'bah_ing_075',
      questionText: 'Choose the correct form: "Listen! The baby _____ right now."',
      options: ['is crying', 'cries', 'cried', 'has cried'],
      correctOptionIndex: 0,
      explanation: 'Present Continuous (is V-ing) denotes an action occurring at the moment of speech.',
    ),
    QuestionItem(
      id: 'bah_ing_076',
      questionText: 'What is the term for words with identical spelling but different meanings/pronunciations?',
      options: ['Homograph', 'Homophone', 'Synonym', 'Antonym'],
      correctOptionIndex: 0,
      explanation: 'Homographs share the same spelling (e.g., lead/lead).',
    ),
    QuestionItem(
      id: 'bah_ing_077',
      questionText: 'What does "Flamboyant" mean?',
      options: ['Noticeably stylish, bright, and showy', 'Dull and quiet', 'Secretive', 'Modest'],
      correctOptionIndex: 0,
      explanation: 'Flamboyant means elaborate or colorful in style.',
    ),
    QuestionItem(
      id: 'bah_ing_078',
      questionText: 'What does "Pragmatic" mean?',
      options: ['Dealing with things sensibly and realistically', 'Theoretical only', 'Idealistic', 'Impractical'],
      correctOptionIndex: 0,
      explanation: 'Pragmatic means practical and realistic.',
    ),
    QuestionItem(
      id: 'bah_ing_079',
      questionText: 'What is an "Oxymoron" in figures of speech?',
      options: ['A figure of speech combining contradictory terms (e.g., deafening silence)', 'Exaggeration', 'Comparison using like', 'Imitation of sound'],
      correctOptionIndex: 0,
      explanation: 'Oxymoron pairs opposite terms together.',
    ),
    QuestionItem(
      id: 'bah_ing_080',
      questionText: 'What is "Onomatopoeia"?',
      options: ['A word that phonetically imitates the sound it describes (e.g., buzz, hiss)', 'Understatement', 'Metaphor', 'Personification'],
      correctOptionIndex: 0,
      explanation: 'Onomatopoeia mimics natural sounds.',
    ),
    QuestionItem(
      id: 'bah_ing_081',
      questionText: 'What is "Hyperbole"?',
      options: ['Exaggerated statements not meant literally (e.g., I told you a million times)', 'Understatement', 'Direct quote', 'Comparison'],
      correctOptionIndex: 0,
      explanation: 'Hyperbole is deliberate extreme exaggeration.',
    ),
    QuestionItem(
      id: 'bah_ing_082',
      questionText: 'What is "Personification"?',
      options: ['Giving human traits to non-human things (e.g., the wind whispered)', 'Comparing two things with as', 'Direct command', 'Rhyme scheme'],
      correctOptionIndex: 0,
      explanation: 'Personification attributes human characteristics to objects/nature.',
    ),
    QuestionItem(
      id: 'bah_ing_083',
      questionText: 'Which prefix means "before"?',
      options: ['Pre- (e.g., Pre-war)', 'Post-', 'Anti-', 'Sub-'],
      correctOptionIndex: 0,
      explanation: 'Pre- means before in time or rank.',
    ),
    QuestionItem(
      id: 'bah_ing_084',
      questionText: 'Which prefix means "after"?',
      options: ['Post- (e.g., Post-war)', 'Pre-', 'Pro-', 'Un-'],
      correctOptionIndex: 0,
      explanation: 'Post- means after.',
    ),
    QuestionItem(
      id: 'bah_ing_085',
      questionText: 'Which prefix means "against"?',
      options: ['Anti- (e.g., Antibiotic)', 'Pro-', 'Sub-', 'Inter-'],
      correctOptionIndex: 0,
      explanation: 'Anti- denotes opposition or against.',
    ),
    QuestionItem(
      id: 'bah_ing_086',
      questionText: 'Which prefix means "under" or "below"?',
      options: ['Sub- (e.g., Submarine)', 'Super-', 'Trans-', 'Over-'],
      correctOptionIndex: 0,
      explanation: 'Sub- means beneath or under.',
    ),
    QuestionItem(
      id: 'bah_ing_087',
      questionText: 'Which prefix means "across" or "beyond"?',
      options: ['Trans- (e.g., Transport)', 'Sub-', 'Re-', 'In-'],
      correctOptionIndex: 0,
      explanation: 'Trans- means across or extending beyond.',
    ),
    QuestionItem(
      id: 'bah_ing_088',
      questionText: 'What is the meaning of the idiom "bite the bullet"?',
      options: ['To face a difficult situation with courage', 'To eat fast', 'To get shot', 'To avoid responsibility'],
      correctOptionIndex: 0,
      explanation: '"Bite the bullet" means accepting a tough scenario bravely.',
    ),
    QuestionItem(
      id: 'bah_ing_089',
      questionText: 'What is the meaning of the idiom "burn the midnight oil"?',
      options: ['To work or study late into the night', 'To waste fuel', 'To start a fire', 'To sleep early'],
      correctOptionIndex: 0,
      explanation: '"Burn the midnight oil" means staying up late working.',
    ),
    QuestionItem(
      id: 'bah_ing_090',
      questionText: 'What is the meaning of "hit the nail on the head"?',
      options: ['To describe exactly right', 'To injure oneself', 'To build a house', 'To miss the point'],
      correctOptionIndex: 0,
      explanation: '"Hit the nail on the head" means doing or saying something precise and accurate.',
    ),
    QuestionItem(
      id: 'bah_ing_091',
      questionText: 'Choose the correct form: "Neither my brother nor my sisters _____ attending."',
      options: ['are', 'is', 'was', 'be'],
      correctOptionIndex: 0,
      explanation: 'With "neither...nor", verb agrees with the closer subject ("sisters" -> are).',
    ),
    QuestionItem(
      id: 'bah_ing_092',
      questionText: 'Choose the correct form: "Neither my sisters nor my brother _____ attending."',
      options: ['is', 'are', 'were', 'be'],
      correctOptionIndex: 0,
      explanation: 'Verb agrees with the closer subject ("brother" -> is).',
    ),
    QuestionItem(
      id: 'bah_ing_093',
      questionText: 'What is the comparative form of "Far" when referring to distance?',
      options: ['Farther', 'Further', 'Farest', 'Furthest'],
      correctOptionIndex: 0,
      explanation: 'Farther specifically refers to physical distance.',
    ),
    QuestionItem(
      id: 'bah_ing_094',
      questionText: 'What is the comparative form of "Far" when referring to additional depth/degree?',
      options: ['Further', 'Farther', 'Farest', 'Farthest'],
      correctOptionIndex: 0,
      explanation: 'Further refers to additional degree, time, or depth.',
    ),
    QuestionItem(
      id: 'bah_ing_095',
      questionText: 'Identify the correct passive sentence: "They will build a new school."',
      options: ['A new school will be built.', 'A new school will built.', 'A new school is built.', 'A new school was built.'],
      correctOptionIndex: 0,
      explanation: 'Future passive requires "will be + V3".',
    ),
    QuestionItem(
      id: 'bah_ing_096',
      questionText: 'What does the term "Cohesion" in writing refer to?',
      options: ['Grammatical and lexical links that connect sentences together', 'The price of a book', 'Spelling accuracy', 'Page margin alignment'],
      correctOptionIndex: 0,
      explanation: 'Cohesion refers to structural linguistic ties.',
    ),
    QuestionItem(
      id: 'bah_ing_097',
      questionText: 'What does "Coherence" in writing refer to?',
      options: ['The logical flow and clarity of ideas', 'Grammar rules only', 'Font size', 'Word count'],
      correctOptionIndex: 0,
      explanation: 'Coherence means logical structure and clarity of thought.',
    ),
    QuestionItem(
      id: 'bah_ing_098',
      questionText: 'Which word means "able to recover quickly from difficult conditions"?',
      options: ['Resilient', 'Fragile', 'Vulnerable', 'Brittle'],
      correctOptionIndex: 0,
      explanation: 'Resilient describes toughness and quick recovery.',
    ),
    QuestionItem(
      id: 'bah_ing_099',
      questionText: 'Which word means "a solution or remedy for all difficulties or diseases"?',
      options: ['Panacea', 'Placebo', 'Pathogen', 'Parasite'],
      correctOptionIndex: 0,
      explanation: 'Panacea is a cure-all solution.',
    ),
    QuestionItem(
      id: 'bah_ing_100',
      questionText: 'What is the primary goal of studying English Language & Applied Linguistics?',
      options: ['To master effective communication, translation, and linguistic structure analysis', 'To memorize dictionaries', 'To avoid learning grammar', 'To speak without accent'],
      correctOptionIndex: 0,
      explanation: 'Applied English linguistics develops comprehensive mastery of communication, grammar, and text analysis.',
    ),
  ];
}
