import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesLinguistikTerapanQuestions() {
  return const [
    QuestionItem(
      id: 'ling_ter_001',
      questionText: 'Cabang ilmu linguistik terapan yang mengkaji hubungan antara bahasa dan struktur sosial masyarakat dinamakan:',
      options: ['Sosiolinguistik', 'Psikolinguistik', 'Neurolinguistik', 'Pragmatik'],
      correctOptionIndex: 0,
      explanation: 'Sosiolinguistik mengkaji fungsi bahasa dalam interaksi masyarakat.',
    ),
    QuestionItem(
      id: 'ling_ter_002',
      questionText: 'Cabang ilmu linguistik terapan yang mengkaji proses pemerolehan dan pemrosesan bahasa dalam otak/pikiran manusia dinamakan:',
      options: ['Psikolinguistik', 'Sosiolinguistik', 'Etimologi', 'Leksikografi'],
      correctOptionIndex: 0,
      explanation: 'Psikolinguistik mempelajari aspek psikologis pemrosesan bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_003',
      questionText: 'Cabang ilmu linguistik yang mengkaji pemanfaatan konteks tuturan untuk memahami maksud pembicara dinamakan:',
      options: ['Pragmatik', 'Semantik', 'Sintaksis', 'Morfologi'],
      correctOptionIndex: 0,
      explanation: 'Pragmatik mengkaji arti tuturan berdasar situasi konteks.',
    ),
    QuestionItem(
      id: 'ling_ter_004',
      questionText: 'Proses mengalihkan pesan teks dari bahasa sumber (Source Language) ke bahasa sasaran (Target Language) dinamakan:',
      options: ['Penerjemahan (Translation)', 'Transkripsi', 'Transliterasi', 'Interferensi'],
      correctOptionIndex: 0,
      explanation: 'Translation mengalihkan pesan antarbahasa secara tertulis.',
    ),
    QuestionItem(
      id: 'ling_ter_005',
      questionText: 'Penerjemahan lisan seketika tanpa jeda saat penutur berbicara dinamakan:',
      options: ['Simultaneous Interpreting', 'Consecutive Interpreting', 'Sight Translation', 'Dubbing'],
      correctOptionIndex: 0,
      explanation: 'Simultaneous interpreting menerjemahkan lisan secara simultan/serentak.',
    ),
    QuestionItem(
      id: 'ling_ter_006',
      questionText: 'Penerjemahan lisan di mana penerjemah mencatat poin lalu menerjemahkan setelah penutur jeda berhenti berbicara dinamakan:',
      options: ['Consecutive Interpreting', 'Simultaneous Interpreting', 'Subtitling', 'Localization'],
      correctOptionIndex: 0,
      explanation: 'Consecutive interpreting menerjemahkan bertahap setelah penutur jeda.',
    ),
    QuestionItem(
      id: 'ling_ter_007',
      questionText: 'Proses penyesuaian produk perangkat lunak, game, atau situs web agar sesuai dengan norma budaya dan bahasa lokal dinamakan:',
      options: ['Lokalisasi (Localization / L10n)', 'Internasionalisasi', 'Transkripsi', 'Kritik Teks'],
      correctOptionIndex: 0,
      explanation: 'Lokalisasi menyelaraskan produk digital dengan budaya lokal.',
    ),
    QuestionItem(
      id: 'ling_ter_008',
      questionText: 'Teori penerjemahan Eugene Nida yang mengutamakan kesetaraan respon emosi/pemahaman pembaca sasaran dinamakan kesepadanan:',
      options: ['Dinamis (Dynamic Equivalence)', 'Formal (Formal Equivalence)', 'Harfiah', 'Morfologis'],
      correctOptionIndex: 0,
      explanation: 'Dynamic equivalence berfokus pada kewajaran respon pembaca target.',
    ),
    QuestionItem(
      id: 'ling_ter_009',
      questionText: 'Teori penerjemahan yang mengutamakan kesetiaan persis pada bentuk dan struktur kata bahasa sumber dinamakan kesepadanan:',
      options: ['Formal (Formal Equivalence)', 'Dinamis', 'Pragmatis', 'Bebas'],
      correctOptionIndex: 0,
      explanation: 'Formal equivalence mempertahankan struktur kata asal.',
    ),
    QuestionItem(
      id: 'ling_ter_010',
      questionText: 'Cabang linguistik terapan yang berfokus pada seni dan penyusunan kamus dinamakan:',
      options: ['Leksikografi', 'Leksikologi', 'Etimologi', 'Dialektologi'],
      correctOptionIndex: 0,
      explanation: 'Leksikografi adalah teknik dan teori pembuatan kamus.',
    ),
    QuestionItem(
      id: 'ling_ter_011',
      questionText: 'Studi sejarah dan asal-usul kata beserta perubahan bentuk dan maknanya dinamakan:',
      options: ['Etimologi', 'Leksikografi', 'Ortografi', 'Fonofonemi'],
      correctOptionIndex: 0,
      explanation: 'Etimologi meneliti riwayat asal-usul kata.',
    ),
    QuestionItem(
      id: 'ling_ter_012',
      questionText: 'Sistem ejaan standar penulisan suatu bahasa menggunakan huruf Latin/aksara resmi dinamakan:',
      options: ['Ortografi (Orthography)', 'Kaligrafi', 'Tipografi', 'Grafologi'],
      correctOptionIndex: 0,
      explanation: 'Ortografi adalah kaidah ejaan resmi tulisan.',
    ),
    QuestionItem(
      id: 'ling_ter_013',
      questionText: 'Cabang linguistik terapan yang memanfaatkan pemrosesan komputer untuk mengolah data bahasa alami (NLP) dinamakan:',
      options: ['Linguistik Komputasi (Computational Linguistics)', 'Sosiolinguistik', 'Neurolinguistik', 'Filologi'],
      correctOptionIndex: 0,
      explanation: 'Linguistik Komputasi menggunakan algoritma komputer untuk bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_014',
      questionText: 'Pengembangan teknologi kecerdasan buatan untuk mengerti dan memproses bahasa manusia dinamakan:',
      options: ['NLP (Natural Language Processing)', 'OCR', 'Machine Learning', 'Data Mining'],
      correctOptionIndex: 0,
      explanation: 'NLP adalah bidang pemrosesan bahasa alami AI.',
    ),
    QuestionItem(
      id: 'ling_ter_015',
      questionText: 'Himpunan besar data teks autentik berformat digital yang digunakan untuk analisis riset linguistik dinamakan:',
      options: ['Korpus Bahasa (Corpus)', 'Database', 'Glosarium', 'Arsip'],
      correctOptionIndex: 0,
      explanation: 'Korpus adalah bank data teks ilmiah riset kebahasaan.',
    ),
    QuestionItem(
      id: 'ling_ter_016',
      questionText: 'Teori tindak tutur (Speech Act Theory) yang dikembangkan J.L. Austin membagi tindak tutur menjadi Lokusi, Ilokusi, dan:',
      options: ['Perlokusi', 'Interlokus', 'Translokus', 'Konokusi'],
      correctOptionIndex: 0,
      explanation: '3 tindak tutur: Lokusi (ucapan), Ilokusi (maksud), Perlokusi (efek pendengar).',
    ),
    QuestionItem(
      id: 'ling_ter_017',
      questionText: 'Tindak tutur berupa makna atau maksud tersembunyi yang ingin dicapai penutur (seperti memerintah halus) dinamakan tindak:',
      options: ['Ilokusi', 'Lokusi', 'Perlokusi', 'Elokusi'],
      correctOptionIndex: 0,
      explanation: 'Ilokusi memuat niat/fungsi ujaran.',
    ),
    QuestionItem(
      id: 'ling_ter_018',
      questionText: 'Efek atau dampak yang timbul pada diri pendengar setelah mendengar ujaran dinamakan tindak:',
      options: ['Perlokusi', 'Ilokusi', 'Lokusi', 'Solikusi'],
      correctOptionIndex: 0,
      explanation: 'Perlokusi adalah dampak nyata pada tindakan pendengar.',
    ),
    QuestionItem(
      id: 'ling_ter_019',
      questionText: 'Prinsip Kerja Sama Grice (Gricean Maxims) dalam komunikasi pragmatik mencakup maksim Kuantitas, Kualitas, Relevansi, dan:',
      options: ['Cara (Maxim of Manner)', 'Kesopanan', 'Kesetaraan', 'Kecepatan'],
      correctOptionIndex: 0,
      explanation: '4 Maksim Grice: Quantity, Quality, Relation/Relevance, Manner.',
    ),
    QuestionItem(
      id: 'ling_ter_020',
      questionText: 'Pelanggaran maksim pragmatik yang disengaja untuk menyampaikan sindiran halus dinamakan:',
      options: ['Flouting the Maxim', 'Obeying the Maxim', 'Code Mixing', 'Diglossia'],
      correctOptionIndex: 0,
      explanation: 'Flouting maxim melahirkan implikatur percakapan.',
    ),
    QuestionItem(
      id: 'ling_ter_021',
      questionText: 'Maksud tersirat yang ingin disampaikan dalam percakapan tanpa diucapkan secara jujur langsung dinamakan:',
      options: ['Implikatur (Conversational Implicature)', 'Eksplikatur', 'Presuposisi', 'Deiksis'],
      correctOptionIndex: 0,
      explanation: 'Implikatur adalah arti tersirat percakapan.',
    ),
    QuestionItem(
      id: 'ling_ter_022',
      questionText: 'Asumsi awal atau praanggapan pembicara sebelum menyampaikan suatu tuturan dinamakan:',
      options: ['Presuposisi (Presupposition)', 'Implikatur', 'Deiksis', 'Anapora'],
      correctOptionIndex: 0,
      explanation: 'Presuposisi adalah praanggapan dasar sebelum bicara.',
    ),
    QuestionItem(
      id: 'ling_ter_023',
      questionText: 'Gejala kebahasaan di mana rujukan kata bergantung penuh pada konteks pembicara (seperti "ini", "itu", "sekarang", "saya") dinamakan:',
      options: ['Deiksis (Deixis)', 'Kata Ulang', 'Kata Majemuk', 'Afiksasi'],
      correctOptionIndex: 0,
      explanation: 'Deiksis memerlukan konteks waktu/tempat/orang untuk menentukan rujukan.',
    ),
    QuestionItem(
      id: 'ling_ter_024',
      questionText: 'Cabang ilmu linguistik terapan yang mengkaji bukti-bukti kebahasaan untuk kepentingan hukum di pengadilan dinamakan:',
      options: ['Linguistik Forensik (Forensic Linguistics)', 'Linguistik Komputasi', 'Sosiolinguistik', 'Filologi'],
      correctOptionIndex: 0,
      explanation: 'Linguistik Forensik menganalisis ancaman, pencemaran nama baik, dan bukti dokumen hukum.',
    ),
    QuestionItem(
      id: 'ling_ter_025',
      questionText: 'Pemerolehan bahasa pertama (B1) pada anak-anak secara alami di lingkungan keluarga dinamakan:',
      options: ['Pemerolehan Bahasa (Language Acquisition)', 'Pembelajaran Bahasa', 'Pengajaran Bahasa', 'Translasi'],
      correctOptionIndex: 0,
      explanation: 'Acquisition terjadi secara tidak sadar pada anak usia dini.',
    ),
    QuestionItem(
      id: 'ling_ter_026',
      questionText: 'Proses penguasaan bahasa kedua (B2) melalui pendidikan formal di kelas sekolah dinamakan:',
      options: ['Pembelajaran Bahasa (Language Learning)', 'Pemerolehan Bahasa', 'Akulturasi', 'Asimilasi'],
      correctOptionIndex: 0,
      explanation: 'Learning terjadi secara sadar lewat instruksi tata bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_027',
      questionText: 'Hipotesis Tata Bahasa Generatif Noam Chomsky yang menyatakan manusia lahir membawa perangkat pemerolehan bahasa bawaan dinamakan:',
      options: ['LAD (Language Acquisition Device)', 'Behaviorisme', 'Konstruktivisme', 'Kognitivisme'],
      correctOptionIndex: 0,
      explanation: 'LAD adalah kapasitas otak biologis bawaan menurut Chomsky.',
    ),
    QuestionItem(
      id: 'ling_ter_028',
      questionText: 'Teori pembelajaran bahasa yang menekankan pembentukan kebiasaan (Habit Formation) melalui stimulasi dan respon dinamakan:',
      options: ['Behaviorisme (Skinner)', 'Nativisme', 'Kognitivisme', 'Interaksionisme'],
      correctOptionIndex: 0,
      explanation: 'Behaviorisme Skinner mendasarkan belajar bahasa pada stimulus-respon-penguatan.',
    ),
    QuestionItem(
      id: 'ling_ter_029',
      questionText: 'Hipotesis Sapir-Whorf (Relativitas Bahasa) menyatakan bahwa:',
      options: ['Struktur bahasa yang digunakan seseorang mempengaruhi cara pandang dan jalan pikirannya tentang dunia', 'Semua bahasa di dunia persis sama', 'Bahasa tidak ada hubungannya dengan pikiran', 'Bahasa ditentukan oleh iklim'],
      correctOptionIndex: 0,
      explanation: 'Relativitas Bahasa menyatakan tata bahasa memandu persepsi realitas.',
    ),
    QuestionItem(
      id: 'ling_ter_030',
      questionText: 'Sistem bahasa perantara sementara yang dibangun oleh pembelajar bahasa asing di antara B1 dan B2 dinamakan:',
      options: ['Interlanguage (Bahasa Antara)', 'Pidgin', 'Kreol', 'Dialek'],
      correctOptionIndex: 0,
      explanation: 'Interlanguage adalah sistem bahasa transisi pelajar B2.',
    ),
    QuestionItem(
      id: 'ling_ter_031',
      questionText: 'Kondisi di mana perkembangan interlanguage pembelajar terhenti pada kesalahan tata bahasa tertentu dinamakan:',
      options: ['Fosilisasi (Fossilization)', 'Interferensi', 'Aphasia', 'Anomia'],
      correctOptionIndex: 0,
      explanation: 'Fosilisasi adalah penghentian permanen perbaikan tata bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_032',
      questionText: 'Gangguan berbahasa akibat kerusakan otak pada area wicara (Area Broca atau Wernicke) dinamakan:',
      options: ['Afasia (Aphasia)', 'Disleksia', 'Disgrafia', 'Stuttering'],
      correctOptionIndex: 0,
      explanation: 'Afasia adalah kehilangan kemampuan berbahasa akibat lesi otak.',
    ),
    QuestionItem(
      id: 'ling_ter_033',
      questionText: 'Afasia yang ditandai kesulitan memproduksi ucapan secara lancar padahal pemahaman baik dinamakan:',
      options: ['Afasia Broca (Motorik / Ekspresif)', 'Afasia Wernicke', 'Afasia Amnesik', 'Afasia Global'],
      correctOptionIndex: 0,
      explanation: 'Afasia Broca merusak kelancaran produksi ucapan.',
    ),
    QuestionItem(
      id: 'ling_ter_034',
      questionText: 'Afasia yang ditandai ucapan lancar tanpa arti dan kesulitan memahami pembicaraan orang dinamakan:',
      options: ['Afasia Wernicke (Sensorik / Reseptif)', 'Afasia Broca', 'Afasia Anomik', 'Afasia Konduksi'],
      correctOptionIndex: 0,
      explanation: 'Afasia Wernicke merusak pemahaman persepsi bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_035',
      questionText: 'Gangguan kesulitan membaca dan mengenali simbol huruf pada anak dinamakan:',
      options: ['Disleksia (Dyslexia)', 'Disgrafia', 'Diskalkulia', 'Apraksia'],
      correctOptionIndex: 0,
      explanation: 'Disleksia adalah kendala spesifik dalam membaca.',
    ),
    QuestionItem(
      id: 'ling_ter_036',
      questionText: 'Gangguan kesulitan menulis dan merangkai simbol tulisan pada anak dinamakan:',
      options: ['Disgrafia (Dysgraphia)', 'Disleksia', 'Dislalia', 'Autisme'],
      correctOptionIndex: 0,
      explanation: 'Disgrafia adalah kendala motorik dan konseptual menulis.',
    ),
    QuestionItem(
      id: 'ling_ter_037',
      questionText: 'Bahasa kontak darurat sederhana yang tumbuh dari dua kelompok berlainan bahasa untuk tujuan perdagangan dinamakan:',
      options: ['Pidgin', 'Kreol', 'Lingua Franca', 'Jargon'],
      correctOptionIndex: 0,
      explanation: 'Pidgin adalah bahasa kontak tanpa penutur asli.',
    ),
    QuestionItem(
      id: 'ling_ter_038',
      questionText: 'Bahasa pidgin yang telah berkembang stabil dan menjadi bahasa ibu (bahasa pertama) generasi penerusnya dinamakan:',
      options: ['Kreol (Creole)', 'Pidgin', 'Idiolek', 'Sosiolek'],
      correctOptionIndex: 0,
      explanation: 'Kreol adalah pidgin yang telah menjadi bahasa ibu.',
    ),
    QuestionItem(
      id: 'ling_ter_039',
      questionText: 'Bahasa umum yang disepakati sebagai bahasa perantara komunikasi antar suku/bangsa yang berbeda dinamakan:',
      options: ['Lingua Franca', 'Bahasa Resmi', 'Bahasa Ibu', 'Vernakular'],
      correctOptionIndex: 0,
      explanation: 'Lingua Franca adalah bahasa pergaulan pemersatu.',
    ),
    QuestionItem(
      id: 'ling_ter_040',
      questionText: 'Bahasa lokal/daerah yang digunakan sehari-hari oleh masyarakat setempat dinamakan bahasa:',
      options: ['Vernakular (Vernacular)', 'Baku', 'Internasional', 'Sintetis'],
      correctOptionIndex: 0,
      explanation: 'Vernakular adalah bahasa lokal ragam non-formal.',
    ),
    QuestionItem(
      id: 'ling_ter_041',
      questionText: 'Metode pengajaran bahasa asing yang menekankan pada penghafalan tata bahasa dan penerjemahan naskah dinamakan:',
      options: ['Grammar Translation Method (GTM)', 'Direct Method', 'Audio-Lingual Method', 'Communicative Approach'],
      correctOptionIndex: 0,
      explanation: 'GTM fokus pada kaidah tata bahasa dan terjemahan naskah.',
    ),
    QuestionItem(
      id: 'ling_ter_042',
      questionText: 'Metode pengajaran bahasa asing yang melarang penggunaan bahasa ibu di kelas dan mengutamakan percakapan langsung dinamakan:',
      options: ['Direct Method (Metode Langsung)', 'GTM', 'Silent Way', 'Suggestopedia'],
      correctOptionIndex: 0,
      explanation: 'Direct Method mewajibkan penggunaan bahasa target 100%.',
    ),
    QuestionItem(
      id: 'bah_ter_043',
      questionText: 'Metode pengajaran bahasa berbasis dril pengulangan pola kalimat secara intensif (berdasar Behaviorisme) dinamakan:',
      options: ['Audio-Lingual Method (ALM)', 'GTM', 'Task-Based Learning', 'Total Physical Response'],
      correctOptionIndex: 0,
      explanation: 'ALM mengutamakan dril pengulangan audio lisan.',
    ),
    QuestionItem(
      id: 'ling_ter_044',
      questionText: 'Pendekatan pengajaran bahasa modern yang mengutamakan keberhasilan komunikasi nyata di kelas dinamakan:',
      options: ['Communicative Language Teaching (CLT)', 'GTM', 'Grammar Method', 'Structural Approach'],
      correctOptionIndex: 0,
      explanation: 'CLT berfokus pada kompetensi komunikatif autentik.',
    ),
    QuestionItem(
      id: 'ling_ter_045',
      questionText: 'Metode pengajaran bahasa untuk anak-anak dengan mengoordinasikan perintah ucapan dan gerakan fisik tubuh dinamakan:',
      options: ['Total Physical Response (TPR)', 'CLT', 'ALM', 'Suggestopedia'],
      correctOptionIndex: 0,
      explanation: 'TPR (Asher) mengintegrasikan perintah bahasa dan gerak motorik.',
    ),
    QuestionItem(
      id: 'ling_ter_046',
      questionText: 'Analisis perbedaan dan persamaan antara dua sistem bahasa untuk memprediksi kesulitan pembelajar dinamakan:',
      options: ['Analisis Kontrastif (Contrastive Analysis)', 'Analisis Kesalahan', 'Analisis Wacana', 'Analisis Stilistika'],
      correctOptionIndex: 0,
      explanation: 'Analisis kontrastif mengomparasikan sistem B1 dan B2.',
    ),
    QuestionItem(
      id: 'ling_ter_047',
      questionText: 'Analisis terhadap kesalahan-kesalahan nyata yang dibuat oleh pembelajar bahasa asing dinamakan:',
      options: ['Analisis Kesalahan (Error Analysis)', 'Analisis Kontrastif', 'Analisis Wacana', 'Kritik Teks'],
      correctOptionIndex: 0,
      explanation: 'Error Analysis (Corder) mengkaji bentuk kesalahan pembelajar.',
    ),
    QuestionItem(
      id: 'ling_ter_048',
      questionText: 'Penyusunan kurikulum pengajaran bahasa berbasis analisis kebutuhan nyata peserta didik dinamakan:',
      options: ['Needs Analysis (Analisis Kebutuhan)', 'Syllabus Design', 'Testing', 'Scoring'],
      correctOptionIndex: 0,
      explanation: 'Needs analysis mendata tujuan spesifik pembelajar.',
    ),
    QuestionItem(
      id: 'ling_ter_049',
      questionText: 'Pengujian bahasa yang mengukur kemampuan umum tanpa terikat kurikulum tertentu (seperti TOEFL/IELTS) dinamakan tes:',
      options: ['Proficiency Test (Tes Kemahiran)', 'Achievement Test', 'Diagnostic Test', 'Placement Test'],
      correctOptionIndex: 0,
      explanation: 'Proficiency test mengukur kecakapan standar umum.',
    ),
    QuestionItem(
      id: 'ling_ter_050',
      questionText: 'Tes yang bertujuan menempatkan siswa pada tingkatan kelas belajar yang sesuai dengan kemampuannya dinamakan tes:',
      options: ['Placement Test (Tes Penempatan)', 'Diagnostic Test', 'Achievement Test', 'Aptitude Test'],
      correctOptionIndex: 0,
      explanation: 'Placement test menentukan level kelas pelajar.',
    ),
    QuestionItem(
      id: 'ling_ter_051',
      questionText: 'Tes yang mengukur pencapaian siswa terhadap materi yang telah diajarkan dalam satu semester dinamakan tes:',
      options: ['Achievement Test (Tes Hasil Belajar)', 'Proficiency Test', 'Aptitude Test', 'Prognostic Test'],
      correctOptionIndex: 0,
      explanation: 'Achievement test menguji materi kurikulum yang dipelajari.',
    ),
    QuestionItem(
      id: 'ling_ter_052',
      questionText: 'Tes yang bertujuan mendeteksi kelemahan spesifik siswa dalam penguasaan tata bahasa dinamakan tes:',
      options: ['Diagnostic Test (Tes Diagnostik)', 'Placement Test', 'Proficiency Test', 'Progress Test'],
      correctOptionIndex: 0,
      explanation: 'Diagnostic test menemukan area kesulitan belajar.',
    ),
    QuestionItem(
      id: 'ling_ter_053',
      questionText: 'Syarat alat tes yang mampu mengukur persis apa yang seharusnya diukur dinamakan prinsip:',
      options: ['Validitas (Validity)', 'Reliabilitas', 'Praktisitas', 'Autentisitas'],
      correctOptionIndex: 0,
      explanation: 'Validitas menjamin ketepatan ukur tes.',
    ),
    QuestionItem(
      id: 'ling_ter_054',
      questionText: 'Syarat alat tes yang menghasilkan skor konsisten jika diujikan berulang kali dinamakan prinsip:',
      options: ['Reliabilitas (Reliability)', 'Validitas', 'Subjektivitas', 'Efisiensi'],
      correctOptionIndex: 0,
      explanation: 'Reliabilitas mengukur keandalan dan konsistensi tes.',
    ),
    QuestionItem(
      id: 'ling_ter_055',
      questionText: 'Kajian stilistika (Stylistics) dalam linguistik terapan berfokus pada:',
      options: ['Analisis gaya bahasa dan pilihan kata dalam teks sastra / karya tulis', 'Pembuatan kamus', 'Pengobatan afasia', 'Suara fonem'],
      correctOptionIndex: 0,
      explanation: 'Stilistika menganalisis keindahan gaya bahasa tulisan.',
    ),
    QuestionItem(
      id: 'ling_ter_056',
      questionText: 'Studi tentang penggunaan bahasa dalam media cetak, televisi, dan media sosial dinamakan:',
      options: ['Linguistik Media (Media Linguistics)', 'Dialektologi', 'Etimologi', 'Kritik Teks'],
      correctOptionIndex: 0,
      explanation: 'Linguistik media mengkaji wacana pers dan internet.',
    ),
    QuestionItem(
      id: 'ling_ter_057',
      questionText: 'Penggunaan teks-teks dunia nyata (seperti koran, menu restoran) dalam pengajaran bahasa dinamakan materi:',
      options: ['Autentik (Authentic Materials)', 'Buatan', 'Teoretis', 'Simulasi'],
      correctOptionIndex: 0,
      explanation: 'Materi autentik berasal dari penggunaan nyata bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_058',
      questionText: 'Model penerjemahan menggunakan mesin perangkat lunak otomatis dinamakan:',
      options: ['Machine Translation (MT)', 'CAT Tool', 'Subtitling', 'Dubbing'],
      correctOptionIndex: 0,
      explanation: 'Machine Translation contohnya Google Translate atau DeepL.',
    ),
    QuestionItem(
      id: 'ling_ter_059',
      questionText: 'Perangkat lunak pembantu penerjemah manusia yang menyimpan memori terjemahan (Translation Memory) dinamakan:',
      options: ['CAT Tool (Computer-Assisted Translation)', 'NLP', 'OCR', 'Text Editor'],
      correctOptionIndex: 0,
      explanation: 'CAT Tools (seperti SDL Trados) membantu efisiensi penerjemah.',
    ),
    QuestionItem(
      id: 'ling_ter_060',
      questionText: 'Proses penerjemahan dialog film yang ditampilkan berupa teks di bagian bawah layar dinamakan:',
      options: ['Subtitling (Teks Terjemahan Film)', 'Dubbing', 'Voice Over', 'Audio Description'],
      correctOptionIndex: 0,
      explanation: 'Subtitling adalah alih bahasa teks layar film.',
    ),
    QuestionItem(
      id: 'ling_ter_061',
      questionText: 'Proses mengganti suara asli aktor dalam film dengan suara penerjemah bahasa sasaran dinamakan:',
      options: ['Dubbing (Sulit Suara)', 'Subtitling', 'Transcription', 'Captioning'],
      correctOptionIndex: 0,
      explanation: 'Dubbing adalah pengisian suara terjemahan.',
    ),
    QuestionItem(
      id: 'ling_ter_062',
      questionText: 'Pendekatan analisis wacana yang membongkar ketimpangan kekuasaan, ideologi, dan dominasi sosial dalam teks dinamakan:',
      options: ['Critical Discourse Analysis (CDA)', 'Analisis Sintaksis', 'Semiotika Murni', 'Fonologi'],
      correctOptionIndex: 0,
      explanation: 'CDA (Fairclough/van Dijk) membongkar relasi kuasa dan ideologi teks.',
    ),
    QuestionItem(
      id: 'ling_ter_063',
      questionText: 'Penggunaan bahasa oleh masyarakat tutur dalam ranah formal (seperti pendidikan, hukum, kedinasan) dinamakan ragam:',
      options: ['Baku / Standard Language', 'Dialek', 'Slang', 'Pidgin'],
      correctOptionIndex: 0,
      explanation: 'Bahasa standar digunakan di lembaga resmi.',
    ),
    QuestionItem(
      id: 'ling_ter_064',
      questionText: 'Kebijakan dan perencanaan tata bahasa yang dilakukan oleh pemerintah untuk pembinaan bahasa negara dinamakan:',
      options: ['Perencanaan Bahasa (Language Planning)', 'Akulturasi', 'Interferensi', 'Globalisasi'],
      correctOptionIndex: 0,
      explanation: 'Language planning mengarahkan pembentukan ejaan dan pembakuan.',
    ),
    QuestionItem(
      id: 'ling_ter_065',
      questionText: 'Upaya penyelamatan dan pencatatan dokumentasi terhadap bahasa-bahasa daerah terancam punah dinamakan:',
      options: ['Revitalisasi & Dokumentasi Bahasa', 'Kepunahan Bahasa', 'Pengembangan Dialek', 'Lokalisasi'],
      correctOptionIndex: 0,
      explanation: 'Revitalisasi bahasa mencegah kematian bahasa daerah (language death).',
    ),
    QuestionItem(
      id: 'ling_ter_066',
      questionText: 'Peristiwa hilangnya penutur asli suatu bahasa sehingga bahasa tersebut tidak lagi digunakan dinamakan:',
      options: ['Kematian Bahasa (Language Death)', 'Fosilisasi', 'Shift', 'Interferensi'],
      correctOptionIndex: 0,
      explanation: 'Language death terjadi saat penutur terakhir meninggal.',
    ),
    QuestionItem(
      id: 'ling_ter_067',
      questionText: 'Pergeseran pemakaian bahasa di mana suatu komunitas perlahan meninggalkan bahasa ibunya demi bahasa dominan dinamakan:',
      options: ['Pergeseran Bahasa (Language Shift)', 'Pemeliharaan Bahasa', 'Asimilasi', 'Bilingualisme'],
      correctOptionIndex: 0,
      explanation: 'Language shift adalah peralihan bertahap ke bahasa mayoritas.',
    ),
    QuestionItem(
      id: 'ling_ter_068',
      questionText: 'Upaya komunitas untuk terus bertahan menggunakan bahasa ibunya di tengah pengaruh bahasa mayoritas dinamakan:',
      options: ['Pemeliharaan Bahasa (Language Maintenance)', 'Language Shift', 'Language Death', 'Fosilisasi'],
      correctOptionIndex: 0,
      explanation: 'Language maintenance menjaga keberlanjutan bahasa ibu.',
    ),
    QuestionItem(
      id: 'ling_ter_069',
      questionText: 'Kemampuan seseorang untuk berkomunikasi secara setara dalam dua bahasa berbeda dinamakan:',
      options: ['Bilingualisme (Kwi-bahasawan)', 'Multilingualisme', 'Monolingualisme', 'Diglosia'],
      correctOptionIndex: 0,
      explanation: 'Bilingualisme adalah penguasaan dua bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_070',
      questionText: 'Kemampuan seseorang atau masyarakat untuk menguasai dan menggunakan banyak bahasa dinamakan:',
      options: ['Multilingualisme (Eka-bahasawan)', 'Bilingualisme', 'Diglosia', 'Monolingualisme'],
      correctOptionIndex: 0,
      explanation: 'Multilingualisme menguasai lebih dari dua bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_071',
      questionText: 'Kemampuan hanya menguasai satu bahasa saja dinamakan:',
      options: ['Monolingualisme (Eka-bahasawan)', 'Bilingualisme', 'Multilingualisme', 'Diglosia'],
      correctOptionIndex: 0,
      explanation: 'Monolingualisme menguasai tunggal 1 bahasa.',
    ),
    QuestionItem(
      id: 'ling_ter_072',
      questionText: 'Istilah sosiolinguistik untuk menyebut variasi bahasa berdasar tingkat status sosial/ekonomi penutur dinamakan:',
      options: ['Sosiolek', 'Idiolek', 'Dialek', 'Kronolek'],
      correctOptionIndex: 0,
      explanation: 'Sosiolek variasi bahasa berdasar kelas sosial.',
    ),
    QuestionItem(
      id: 'ling_ter_073',
      questionText: 'Variasi bahasa berdasar perbedaan kurun waktu zaman sejarah dinamakan:',
      options: ['Kronolek / Dialek Temporal', 'Sosiolek', 'Idiolek', 'Jargon'],
      correctOptionIndex: 0,
      explanation: 'Kronolek adalah variasi bahasa sesuai era masa.',
    ),
    QuestionItem(
      id: 'ling_ter_074',
      questionText: 'Ragam bahasa yang dianggap paling tinggi dan bergengsi dalam sosiolinguistik dinamakan:',
      options: ['Akrolek', 'Basilek', 'Sosiolek', 'Slang'],
      correctOptionIndex: 0,
      explanation: 'Akrolek adalah variasi bahasa sosial tertinggi.',
    ),
    QuestionItem(
      id: 'ling_ter_075',
      questionText: 'Ragam bahasa sosial yang dianggap paling rendah atau tidak formal dinamakan:',
      options: ['Basilek', 'Akrolek', 'Jargon', 'Argot'],
      correctOptionIndex: 0,
      explanation: 'Basilek adalah variasi bahasa rakyat awam/rendah.',
    ),
    QuestionItem(
      id: 'ling_ter_076',
      questionText: 'Kosakata rahasia yang digunakan oleh kelompok kejahatan atau pencuri agar tidak dimengerti orang luar dinamakan:',
      options: ['Argot / Cant', 'Jargon', 'Slang', 'Pidgin'],
      correctOptionIndex: 0,
      explanation: 'Argot adalah bahasa rahasia kelompok tertutup.',
    ),
    QuestionItem(
      id: 'ling_ter_077',
      questionText: 'Studi linguistik terapan yang mengkaji isyarat bahasa tubuh, mimik, dan gerak tangan saat berbicara dinamakan:',
      options: ['Kinesik (Kinesics)', 'Proksemik', 'Parabahasa', 'Haptik'],
      correctOptionIndex: 0,
      explanation: 'Kinesik mengkaji bahasa tubuh gestur lisan.',
    ),
    QuestionItem(
      id: 'ling_ter_078',
      questionText: 'Studi linguistik terapan yang mengkaji penggunaan jarak ruang antar individu dalam komunikasi dinamakan:',
      options: ['Proksemik (Proxemics)', 'Kinesik', 'Haptik', 'Kronemik'],
      correctOptionIndex: 0,
      explanation: 'Proksemik mengkaji zona jarak ruang personal.',
    ),
    QuestionItem(
      id: 'ling_ter_079',
      questionText: 'Studi linguistik terapan yang mengkaji makna sentuhan fisik dalam komunikasi dinamakan:',
      options: ['Haptik (Haptics)', 'Kinesik', 'Proksemik', 'Vokalik'],
      correctOptionIndex: 0,
      explanation: 'Haptik mengkaji komunikasi sentuhan.',
    ),
    QuestionItem(
      id: 'ling_ter_080',
      questionText: 'Unsur non-verbal lisan seperti intonasi, nada, volume, dan jeda ucapan dinamakan:',
      options: ['Parabahasa (Paralanguage / Vokalik)', 'Kinesik', 'Proksemik', 'Ortografi'],
      correctOptionIndex: 0,
      explanation: 'Paralanguage mencakup nada dan ekspresi vokal.',
    ),
    QuestionItem(
      id: 'ling_ter_081',
      questionText: 'Proses pengubahan ujaran lisan menjadi rekaman tulisan teks dinamakan:',
      options: ['Transkripsi (Transcription)', 'Transliterasi', 'Translasi', 'Transformasi'],
      correctOptionIndex: 0,
      explanation: 'Transkripsi mengubah suara lisan jadi tulisan fonetis/teks.',
    ),
    QuestionItem(
      id: 'ling_ter_082',
      questionText: 'Proses pengalihan aksara dari satu jenis huruf ke jenis huruf lain (misal Arab ke Latin) dinamakan:',
      options: ['Transliterasi (Transliteration)', 'Transkripsi', 'Translasi', 'Adaptasi'],
      correctOptionIndex: 0,
      explanation: 'Transliterasi mengalihkan sistem ejaan huruf/aksara.',
    ),
    QuestionItem(
      id: 'ling_ter_083',
      questionText: 'Perangkat analisis korpus yang menampilkan kata kunci di tengah beserta konteks kalimat kiri-kanannya dinamakan:',
      options: ['KWIC (Key Word in Context / Konkordansi)', 'N-gram', 'Lemmatization', 'POS Tagging'],
      correctOptionIndex: 0,
      explanation: 'KWIC menampilkan konkordansi kata dalam konteks.',
    ),
    QuestionItem(
      id: 'ling_ter_084',
      questionText: 'Proses penandaan kelas kata (noun, verb, adj) secara otomatis pada korpus teks oleh komputer dinamakan:',
      options: ['POS Tagging (Part-of-Speech Tagging)', 'Parsing', 'Lemmatization', 'Stemming'],
      correctOptionIndex: 0,
      explanation: 'POS Tagging melabeli kategori kata pada teks digital.',
    ),
    QuestionItem(
      id: 'ling_ter_085',
      questionText: 'Proses pengembalian bentuk kata ber-imbuhan menjadi kata dasar (lemma) dalam linguistik komputasi dinamakan:',
      options: ['Lematisasi (Lemmatization) / Stemming', 'POS Tagging', 'Parsing', 'Chunking'],
      correctOptionIndex: 0,
      explanation: 'Lemmatization menyederhanakan kata turunan ke bentuk dasar.',
    ),
    QuestionItem(
      id: 'ling_ter_086',
      questionText: 'Analisis struktur pohon sintaksis kalimat oleh program komputer dinamakan:',
      options: ['Parsing (Analisis Sintaksis Komputer)', 'Tagging', 'Scraping', 'Mining'],
      correctOptionIndex: 0,
      explanation: 'Parsing membedah struktur gramatikal kalimat otomatis.',
    ),
    QuestionItem(
      id: 'ling_ter_087',
      questionText: 'Penguasaan bahasa kedua di mana pembelajar memikirkan konsep dalam B1 dulu lalu diterjemahkan dinamakan bilingualisme:',
      options: ['Majemuk (Compound / Subordinate)', 'Koordinat', 'Seimbang', 'Simultan'],
      correctOptionIndex: 0,
      explanation: 'Subordinate bilingualism bergantung pada B1.',
    ),
    QuestionItem(
      id: 'ling_ter_088',
      questionText: 'Penguasaan dua bahasa sejak bayi secara bersamaan di lingkungan keluarga dinamakan pemerolehan bilingualisme:',
      options: ['Simultan (Simultaneous)', 'Sekuisial', 'Late', 'Terganggu'],
      correctOptionIndex: 0,
      explanation: 'Simultaneous bilingualism tumbuh sejak lahir.',
    ),
    QuestionItem(
      id: 'ling_ter_089',
      questionText: 'Pemerolehan bahasa kedua yang terjadi setelah bahasa pertama sudah matang dikuasai dinamakan bilingualisme:',
      options: ['Sekuisial (Sequential)', 'Simultan', 'Dini', 'Bawaan'],
      correctOptionIndex: 0,
      explanation: 'Sequential bilingualism menyusul setelah B1 dikuasai.',
    ),
    QuestionItem(
      id: 'ling_ter_090',
      questionText: 'Model pendidikan di mana mata pelajaran umum diajarkan menggunakan bahasa asing/kedua dinamakan pengajaran:',
      options: ['Imersi (Immersion / CLIL)', 'Submersi', 'GTM', 'Bilingual murni'],
      correctOptionIndex: 0,
      explanation: 'Immersion / CLIL merendam siswa dalam bahasa target untuk materi umum.',
    ),
    QuestionItem(
      id: 'ling_ter_091',
      questionText: 'Program pengajaran bahasa bagi imigran agar segera membaur dengan bahasa mayoritas dinamakan program:',
      options: ['Asimilasi / Asimilatif', 'Revitalisasi', 'Akulturasi', 'Pelestarian'],
      correctOptionIndex: 0,
      explanation: 'Program bahasa asimilatif mendorong penguasaan bahasa resmi dominan.',
    ),
    QuestionItem(
      id: 'ling_ter_092',
      questionText: 'Penelitian lapangan yang mengamati dan mencatat perilaku berbahasa masyarakat secara langsung dinamakan metode:',
      options: ['Etnografi Komunikasi (Ethnography of Communication)', 'Eksperimen Laboratorium', 'Kuesioner', 'Studi Pustaka'],
      correctOptionIndex: 0,
      explanation: 'Etnografi Komunikasi (Dell Hymes) meneliti peritiwa tutur di lapangan.',
    ),
    QuestionItem(
      id: 'ling_ter_093',
      questionText: 'Akronym SPEAKING yang dirumuskan Dell Hymes untuk menganalisis konteks tutur mencakup Setting, Participants, Ends, Act sequence, Key, Instrumentalities, Norms, dan:',
      options: ['Genre', 'Grammar', 'Group', 'Gloss'],
      correctOptionIndex: 0,
      explanation: 'Model SPEAKING Dell Hymes diakhiri G = Genre (ragam wacana).',
    ),
    QuestionItem(
      id: 'ling_ter_094',
      questionText: 'Studi yang mengkaji urutan giliran bicara (Turn-taking) dalam interaksi percakapan dinamakan:',
      options: ['Analisis Percakapan (Conversation Analysis)', 'Analisis Sintaksis', 'Semiotika', 'Pragmatik Murni'],
      correctOptionIndex: 0,
      explanation: 'Conversation Analysis meneliti norma alur giliran bicara.',
    ),
    QuestionItem(
      id: 'ling_ter_095',
      questionText: 'Tindakan menyela atau memotong pembicaraan orang lain dalam alur percakapan dinamakan:',
      options: ['Interupsi (Interruption)', 'Overlap', 'Pause', 'Repair'],
      correctOptionIndex: 0,
      explanation: 'Interupsi adalah penyelaan giliran bicara.',
    ),
    QuestionItem(
      id: 'ling_ter_096',
      questionText: 'Tindakan membetulkan kesalahan ucap diri sendiri atau orang lain dalam percakapan dinamakan:',
      options: ['Repair (Perbaikan Tuturan)', 'Interupsi', 'Overlap', 'Hesitation'],
      correctOptionIndex: 0,
      explanation: 'Repair mekanisme koreksi mandiri/orang lain dalam tutur.',
    ),
    QuestionItem(
      id: 'ling_ter_097',
      questionText: 'Jeda ragu-ragu saat berbicara yang diisi bunyi seperti "ehm", "aaa" dinamakan:',
      options: ['Filled Pause (Jeda Berisi)', 'Unfilled Pause', 'Interupsi', 'Lapsus'],
      correctOptionIndex: 0,
      explanation: 'Filled pause diisi fonem jeda peragu.',
    ),
    QuestionItem(
      id: 'ling_ter_098',
      questionText: 'Kesalahan selip lidah saat berbicara (seperti terbalik mengucapkan suku kata) dinamakan:',
      options: ['Slip of the Tongue (Lapsus Linguae)', 'Afasia', 'Disleksia', 'Fosilisasi'],
      correctOptionIndex: 0,
      explanation: 'Slip of the tongue adalah kekeliruan eksekusi ucapan sementara.',
    ),
    QuestionItem(
      id: 'ling_ter_099',
      questionText: 'Sifat sistem bahasa manusia yang mampu menghasilkan kalimat-kalimat baru tanpa batas dinamakan sifat:',
      options: ['Produktivitas / Kreativitas Bahasa', 'Arbitrer', 'Konvensional', 'Statis'],
      correctOptionIndex: 0,
      explanation: 'Produktivitas bahasa memungkinkan pembentukan tuturan tak terbatas.',
    ),
    QuestionItem(
      id: 'ling_ter_100',
      questionText: 'Tujuan utama mempelajari Linguistik Terapan (Applied Linguistics) adalah untuk:',
      options: ['Memecahkan masalah-masalah praktis dunia nyata yang berkaitan dengan bahasa (pendidikan, penerjemahan, teknologi, dan hukum)', 'Sekadar menghafal teori linguistik', 'Menghapus bahasa daerah', 'Menciptakan bahasa baru buatan'],
      correctOptionIndex: 0,
      explanation: 'Linguistik Terapan memanfaatkan ilmu bahasa untuk pemecahan masalah praktis dalam kehidupan nyata manusia.',
    ),
  ];
}
