import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPgsdMatematikaQuestions() {
  return const [
    QuestionItem(
      id: 'pgsd_mat_001',
      questionText: 'Media pembelajaran konkret yang paling tepat untuk mengenalkan konsep nilai tempat (satuan, puluhan, ratusan) di SD adalah:',
      options: ['Blok Dienes (Base Ten Blocks)', 'Kalkulator Digital', 'Jangka dan Penggaris', 'Papan Catur'],
      correctOptionIndex: 0,
      explanation: 'Blok Dienes secara visual memodelkan kubus satuan, batang puluhan, dan keping ratusan.',
    ),
    QuestionItem(
      id: 'pgsd_mat_002',
      questionText: 'Tahap perkembangan kognitif Piaget di mana anak usia SD (7-11 tahun) mulai dapat berpikir logis pada benda nyata dinamakan tahap:',
      options: ['Operasional Konkret', 'Sensorimotor', 'Pra-operasional', 'Operasional Formal'],
      correctOptionIndex: 0,
      explanation: 'Anak SD berada pada tahap operasional konkret.',
    ),
    QuestionItem(
      id: 'pgsd_mat_003',
      questionText: 'Hasil dari 45 + 38 adalah:',
      options: ['83', '81', '73', '85'],
      correctOptionIndex: 0,
      explanation: '45 + 38 = 83.',
    ),
    QuestionItem(
      id: 'pgsd_mat_004',
      questionText: 'Hasil dari 125 - 67 adalah:',
      options: ['58', '57', '68', '48'],
      correctOptionIndex: 0,
      explanation: '125 - 67 = 58.',
    ),
    QuestionItem(
      id: 'pgsd_mat_005',
      questionText: 'Hasil perkalian 14 x 15 adalah:',
      options: ['210', '190', '220', '200'],
      correctOptionIndex: 0,
      explanation: '14 x 15 = 210.',
    ),
    QuestionItem(
      id: 'pgsd_mat_006',
      questionText: 'Hasil pembagian 144 : 12 adalah:',
      options: ['12', '14', '11', '13'],
      correctOptionIndex: 0,
      explanation: '144 : 12 = 12.',
    ),
    QuestionItem(
      id: 'pgsd_mat_007',
      questionText: 'Manakah angka yang merupakan bilangan prima antara 10 dan 20?',
      options: ['11, 13, 17, 19', '11, 13, 15, 17', '12, 14, 16, 18', '11, 14, 17, 19'],
      correctOptionIndex: 0,
      explanation: 'Bilangan prima 10-20 adalah 11, 13, 17, dan 19.',
    ),
    QuestionItem(
      id: 'pgsd_mat_008',
      questionText: 'Faktor Persekutuan Terbesar (FPB) dari 24 dan 36 adalah:',
      options: ['12', '6', '18', '24'],
      correctOptionIndex: 0,
      explanation: 'Faktor 24: 1,2,3,4,6,8,12,24. Faktor 36: 1,2,3,4,6,9,12,18,36. FPB = 12.',
    ),
    QuestionItem(
      id: 'pgsd_mat_009',
      questionText: 'Kelipatan Persekutuan Terkecil (KPK) dari 6 dan 8 adalah:',
      options: ['24', '12', '48', '16'],
      correctOptionIndex: 0,
      explanation: 'Kelipatan 6: 6,12,18,24... Kelipatan 8: 8,16,24... KPK = 24.',
    ),
    QuestionItem(
      id: 'pgsd_mat_010',
      questionText: 'Bentuk pecahan paling sederhana dari 16/24 adalah:',
      options: ['2/3', '3/4', '4/6', '1/2'],
      correctOptionIndex: 0,
      explanation: '16/24 dibagi 8 (FPB) menjadi 2/3.',
    ),
    QuestionItem(
      id: 'pgsd_mat_011',
      questionText: 'Hasil dari 1/2 + 2/3 adalah:',
      options: ['7/6 atau 1 1/6', '3/5', '5/6', '2/6'],
      correctOptionIndex: 0,
      explanation: '3/6 + 4/6 = 7/6 = 1 1/6.',
    ),
    QuestionItem(
      id: 'pgsd_mat_012',
      questionText: 'Hasil dari 3/4 - 1/2 adalah:',
      options: ['1/4', '2/4', '1/2', '1/8'],
      correctOptionIndex: 0,
      explanation: '3/4 - 2/4 = 1/4.',
    ),
    QuestionItem(
      id: 'pgsd_mat_013',
      questionText: 'Hasil perkalian pecahan 2/5 x 3/4 adalah:',
      options: ['6/20 disederhanakan menjadi 3/10', '5/9', '8/15', '6/9'],
      correctOptionIndex: 0,
      explanation: '(2x3)/(5x4) = 6/20 = 3/10.',
    ),
    QuestionItem(
      id: 'pgsd_mat_014',
      questionText: 'Hasil pembagian pecahan 1/2 : 1/4 adalah:',
      options: ['2', '1/8', '4', '1/2'],
      correctOptionIndex: 0,
      explanation: '1/2 x 4/1 = 2.',
    ),
    QuestionItem(
      id: 'pgsd_mat_015',
      questionText: 'Bentuk desimal dari pecahan 3/5 adalah:',
      options: ['0,6', '0,35', '0,5', '0,75'],
      correctOptionIndex: 0,
      explanation: '3/5 = 6/10 = 0,6.',
    ),
    QuestionItem(
      id: 'pgsd_mat_016',
      questionText: 'Bentuk persen (%) dari 1/4 adalah:',
      options: ['25%', '50%', '20%', '75%'],
      correctOptionIndex: 0,
      explanation: '1/4 x 100% = 25%.',
    ),
    QuestionItem(
      id: 'pgsd_mat_017',
      questionText: 'Keliling persegi dengan panjang sisi 8 cm adalah:',
      options: ['32 cm', '64 cm', '16 cm', '24 cm'],
      correctOptionIndex: 0,
      explanation: 'Keliling = 4 x sisi = 4 x 8 = 32 cm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_018',
      questionText: 'Luas persegi dengan panjang sisi 9 cm adalah:',
      options: ['81 cm²', '36 cm²', '18 cm²', '72 cm²'],
      correctOptionIndex: 0,
      explanation: 'Luas = sisi x sisi = 9 x 9 = 81 cm².',
    ),
    QuestionItem(
      id: 'pgsd_mat_019',
      questionText: 'Keliling persegi panjang dengan panjang 10 cm dan lebar 6 cm adalah:',
      options: ['32 cm', '60 cm', '16 cm', '40 cm'],
      correctOptionIndex: 0,
      explanation: 'Keliling = 2 x (p + l) = 2 x (10 + 6) = 32 cm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_020',
      questionText: 'Luas persegi panjang dengan panjang 12 cm dan lebar 5 cm adalah:',
      options: ['60 cm²', '34 cm²', '17 cm²', '50 cm²'],
      correctOptionIndex: 0,
      explanation: 'Luas = p x l = 12 x 5 = 60 cm².',
    ),
    QuestionItem(
      id: 'pgsd_mat_021',
      questionText: 'Luas segitiga dengan alas 10 cm dan tinggi 8 cm adalah:',
      options: ['40 cm²', '80 cm²', '20 cm²', '50 cm²'],
      correctOptionIndex: 0,
      explanation: 'Luas = 1/2 x alas x tinggi = 1/2 x 10 x 8 = 40 cm².',
    ),
    QuestionItem(
      id: 'pgsd_mat_022',
      questionText: 'Keliling lingkaran dengan jari-jari (r) = 7 cm (π = 22/7) adalah:',
      options: ['44 cm', '154 cm', '22 cm', '88 cm'],
      correctOptionIndex: 0,
      explanation: 'Keliling = 2 x π x r = 2 x 22/7 x 7 = 44 cm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_023',
      questionText: 'Luas lingkaran dengan jari-jari (r) = 7 cm (π = 22/7) adalah:',
      options: ['154 cm²', '44 cm²', '308 cm²', '77 cm²'],
      correctOptionIndex: 0,
      explanation: 'Luas = π x r² = 22/7 x 7 x 7 = 154 cm².',
    ),
    QuestionItem(
      id: 'pgsd_mat_024',
      questionText: 'Volume kubus yang memiliki panjang rusuk 5 cm adalah:',
      options: ['125 cm³', '25 cm³', '150 cm³', '100 cm³'],
      correctOptionIndex: 0,
      explanation: 'Volume = s³ = 5 x 5 x 5 = 125 cm³.',
    ),
    QuestionItem(
      id: 'pgsd_mat_025',
      questionText: 'Luas permukaan kubus yang memiliki panjang rusuk 4 cm adalah:',
      options: ['96 cm²', '64 cm²', '16 cm²', '48 cm²'],
      correctOptionIndex: 0,
      explanation: 'Luas Permukaan = 6 x s² = 6 x 16 = 96 cm².',
    ),
    QuestionItem(
      id: 'pgsd_mat_026',
      questionText: 'Volume balok dengan panjang 8 cm, lebar 5 cm, dan tinggi 4 cm adalah:',
      options: ['160 cm³', '80 cm³', '150 cm³', '40 cm³'],
      correctOptionIndex: 0,
      explanation: 'Volume = p x l x t = 8 x 5 x 4 = 160 cm³.',
    ),
    QuestionItem(
      id: 'pgsd_mat_027',
      questionText: 'Bangun ruang yang memiliki 1 titik puncak, 1 alas lingkaran, dan 1 selimut melengkung adalah:',
      options: ['Kerucut', 'Tabung', 'Bola', 'Prisma'],
      correctOptionIndex: 0,
      explanation: 'Kerucut memiliki alas lingkaran dan titik puncak.',
    ),
    QuestionItem(
      id: 'pgsd_mat_028',
      questionText: 'Bangun ruang yang memiliki 2 alas berupa lingkaran sejajar dan 1 selimut melengkung adalah:',
      options: ['Tabung', 'Kerucut', 'Prisma Segitiga', 'Kubus'],
      correctOptionIndex: 0,
      explanation: 'Tabung (silinder) dibatasi oleh dua lingkaran sejajar dan selimut tabung.',
    ),
    QuestionItem(
      id: 'pgsd_mat_029',
      questionText: 'Berapakah jumlah sudut dalam sebuah segitiga pada bidang datar?',
      options: ['180°', '360°', '90°', '270°'],
      correctOptionIndex: 0,
      explanation: 'Jumlah ketiga sudut dalam segitiga selalu 180°.',
    ),
    QuestionItem(
      id: 'pgsd_mat_030',
      questionText: 'Sudut yang besarnya tepat 90° dinamakan sudut:',
      options: ['Siku-siku', 'Lancip', 'Tumpul', 'Lurus'],
      correctOptionIndex: 0,
      explanation: 'Sudut siku-siku memiliki besar tepat 90°.',
    ),
    QuestionItem(
      id: 'pgsd_mat_031',
      questionText: 'Sudut yang besarnya kurang dari 90° dinamakan sudut:',
      options: ['Lancip', 'Siku-siku', 'Tumpul', 'Refleks'],
      correctOptionIndex: 0,
      explanation: 'Sudut lancip besarnya antara 0° dan 90°.',
    ),
    QuestionItem(
      id: 'pgsd_mat_032',
      questionText: 'Sudut yang besarnya antara 90° dan 180° dinamakan sudut:',
      options: ['Tumpul', 'Lancip', 'Siku-siku', 'Lurus'],
      correctOptionIndex: 0,
      explanation: 'Sudut tumpul lebih besar dari 90° namun kurang dari 180°.',
    ),
    QuestionItem(
      id: 'pgsd_mat_033',
      questionText: 'Rata-rata hitung dari sekumpulan data dinamakan:',
      options: ['Mean', 'Median', 'Modus', 'Jangkauan'],
      correctOptionIndex: 0,
      explanation: 'Mean adalah jumlah seluruh data dibagi banyaknya data.',
    ),
    QuestionItem(
      id: 'pgsd_mat_034',
      questionText: 'Nilai tengah dari sekumpulan data yang telah diurutkan dinamakan:',
      options: ['Median', 'Mean', 'Modus', 'Kuartil'],
      correctOptionIndex: 0,
      explanation: 'Median adalah nilai yang membagi data terurut menjadi dua bagian sama.',
    ),
    QuestionItem(
      id: 'pgsd_mat_035',
      questionText: 'Nilai data yang paling sering muncul (frekuensi tertinggi) dinamakan:',
      options: ['Modus', 'Mean', 'Median', 'Simpangan'],
      correctOptionIndex: 0,
      explanation: 'Modus adalah nilai dengan jumlah kemunculan terbanyak.',
    ),
    QuestionItem(
      id: 'pgsd_mat_036',
      questionText: 'Mean dari data: 4, 6, 8, 10, 12 adalah:',
      options: ['8', '7', '9', '10'],
      correctOptionIndex: 0,
      explanation: '(4+6+8+10+12) / 5 = 40 / 5 = 8.',
    ),
    QuestionItem(
      id: 'pgsd_mat_037',
      questionText: 'Median dari data: 3, 5, 7, 9, 11 adalah:',
      options: ['7', '5', '9', '6'],
      correctOptionIndex: 0,
      explanation: 'Nilai tengah dari 5 data terurut adalah data ke-3, yaitu 7.',
    ),
    QuestionItem(
      id: 'pgsd_mat_038',
      questionText: 'Modus dari kumpulan nilai: 6, 7, 8, 7, 9, 7, 10 adalah:',
      options: ['7', '8', '6', '9'],
      correctOptionIndex: 0,
      explanation: 'Angka 7 muncul terbanyak (3 kali).',
    ),
    QuestionItem(
      id: 'pgsd_mat_039',
      questionText: 'Satuan standar panjang dalam sistem internasional (SI) adalah:',
      options: ['Meter (m)', 'Kilogram (kg)', 'Detik (s)', 'Liter (L)'],
      correctOptionIndex: 0,
      explanation: 'Meter adalah satuan standar SI untuk panjang.',
    ),
    QuestionItem(
      id: 'pgsd_mat_040',
      questionText: 'Konversi 2,5 kilometer (km) ke meter (m) adalah:',
      options: ['2.500 m', '250 m', '25.000 m', '25 m'],
      correctOptionIndex: 0,
      explanation: '1 km = 1.000 m, maka 2,5 x 1.000 = 2.500 m.',
    ),
    QuestionItem(
      id: 'pgsd_mat_041',
      questionText: 'Konversi 3500 gram (g) ke kilogram (kg) adalah:',
      options: ['3,5 kg', '35 kg', '0,35 kg', '350 kg'],
      correctOptionIndex: 0,
      explanation: '1 kg = 1.000 g, maka 3.500 / 1.000 = 3,5 kg.',
    ),
    QuestionItem(
      id: 'pgsd_mat_042',
      questionText: 'Konversi 2 jam ke menit adalah:',
      options: ['120 menit', '60 menit', '180 menit', '240 menit'],
      correctOptionIndex: 0,
      explanation: '1 jam = 60 menit, 2 x 60 = 120 menit.',
    ),
    QuestionItem(
      id: 'pgsd_mat_043',
      questionText: 'Sebuah mobil melaju dengan kecepatan 60 km/jam selama 2 jam. Jarak yang ditempuh mobil adalah:',
      options: ['120 km', '30 km', '180 km', '90 km'],
      correctOptionIndex: 0,
      explanation: 'Jarak = Kecepatan x Waktu = 60 x 2 = 120 km.',
    ),
    QuestionItem(
      id: 'pgsd_mat_044',
      questionText: 'Debit air adalah 10 liter/menit. Berapa liter air yang mengalir dalam waktu 5 menit?',
      options: ['50 liter', '2 liter', '15 liter', '500 liter'],
      correctOptionIndex: 0,
      explanation: 'Volume = Debit x Waktu = 10 x 5 = 50 liter.',
    ),
    QuestionItem(
      id: 'pgsd_mat_045',
      questionText: 'Pernyataan sifat komutatif pada penjumlahan adalah:',
      options: ['a + b = b + a', '(a + b) + c = a + (b + c)', 'a x (b + c) = a x b + a x c', 'a + 0 = a'],
      correctOptionIndex: 0,
      explanation: 'Sifat komutatif adalah sifat pertukaran (a + b = b + a).',
    ),
    QuestionItem(
      id: 'pgsd_mat_046',
      questionText: 'Pernyataan sifat asosiatif pada perkalian adalah:',
      options: ['(a x b) x c = a x (b x c)', 'a x b = b x a', 'a x (b + c) = a x b + a x c', 'a x 1 = a'],
      correctOptionIndex: 0,
      explanation: 'Sifat asosiatif adalah sifat pengelompokan.',
    ),
    QuestionItem(
      id: 'pgsd_mat_047',
      questionText: 'Pernyataan sifat distributif perkalian terhadap penjumlahan adalah:',
      options: ['a x (b + c) = (a x b) + (a x c)', 'a x b = b x a', '(a + b) + c = a + (b + c)', 'a + b = c'],
      correctOptionIndex: 0,
      explanation: 'Sifat distributif adalah sifat penyebaran.',
    ),
    QuestionItem(
      id: 'pgsd_mat_048',
      questionText: 'Elemen identitas pada operasi penjumlahan bilangan adalah:',
      options: ['0', '1', '-1', 'Tak terhingga'],
      correctOptionIndex: 0,
      explanation: 'Semua bilangan ditambah 0 menghasilkan bilangan itu sendiri.',
    ),
    QuestionItem(
      id: 'pgsd_mat_049',
      questionText: 'Elemen identitas pada operasi perkalian bilangan adalah:',
      options: ['1', '0', '-1', '10'],
      correctOptionIndex: 0,
      explanation: 'Semua bilangan dikali 1 menghasilkan bilangan itu sendiri.',
    ),
    QuestionItem(
      id: 'pgsd_mat_050',
      questionText: 'Hasil operasi bilangan bulat (-8) + 12 adalah:',
      options: ['4', '-4', '20', '-20'],
      correctOptionIndex: 0,
      explanation: '-8 + 12 = 4.',
    ),
    QuestionItem(
      id: 'pgsd_mat_051',
      questionText: 'Hasil operasi perkalian (-5) x (-6) adalah:',
      options: ['30', '-30', '11', '-11'],
      correctOptionIndex: 0,
      explanation: 'Perkalian dua bilangan negatif menghasilkan bilangan positif: (-5) x (-6) = 30.',
    ),
    QuestionItem(
      id: 'pgsd_mat_052',
      questionText: 'Hasil pembagian 36 : (-4) adalah:',
      options: ['-9', '9', '-8', '8'],
      correctOptionIndex: 0,
      explanation: 'Positif dibagi negatif menghasilkan negatif: 36 : (-4) = -9.',
    ),
    QuestionItem(
      id: 'pgsd_mat_053',
      questionText: 'Skala peta adalah 1 : 100.000. Jika jarak pada peta 4 cm, maka jarak sebenarnya adalah:',
      options: ['4 km', '40 km', '400 m', '40 km'],
      correctOptionIndex: 0,
      explanation: '4 cm x 100.000 = 400.000 cm = 4.000 m = 4 km.',
    ),
    QuestionItem(
      id: 'pgsd_mat_054',
      questionText: 'Jarak sebenarnya dua kota 15 km. Jika skala peta 1 : 300.000, berapa jarak kedua kota pada peta?',
      options: ['5 cm', '50 cm', '0,5 cm', '15 cm'],
      correctOptionIndex: 0,
      explanation: '15 km = 1.500.000 cm. Jarak peta = 1.500.000 / 300.000 = 5 cm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_055',
      questionText: 'Perbandingan uang Ani dan Budi adalah 2 : 3. Jika jumlah uang mereka Rp50.000, berapa uang Ani?',
      options: ['Rp20.000', 'Rp30.000', 'Rp10.000', 'Rp25.000'],
      correctOptionIndex: 0,
      explanation: 'Uang Ani = 2/(2+3) x 50.000 = 2/5 x 50.000 = Rp20.000.',
    ),
    QuestionItem(
      id: 'pgsd_mat_056',
      questionText: 'Pedagang membeli barang seharga Rp100.000 dan menjualnya Rp120.000. Persentase keuntungannya adalah:',
      options: ['20%', '15%', '25%', '10%'],
      correctOptionIndex: 0,
      explanation: 'Untung = Rp20.000. Persentase untung = (20.000/100.000) x 100% = 20%.',
    ),
    QuestionItem(
      id: 'pgsd_mat_057',
      questionText: 'Baju seharga Rp200.000 mendapat diskon 15%. Berapa harga yang harus dibayar?',
      options: ['Rp170.000', 'Rp180.000', 'Rp150.000', 'Rp30.000'],
      correctOptionIndex: 0,
      explanation: 'Diskon = 15% x 200.000 = 30.000. Harga bayar = 200.000 - 30.000 = Rp170.000.',
    ),
    QuestionItem(
      id: 'pgsd_mat_058',
      questionText: 'Hasil perpangkatan dari 12² adalah:',
      options: ['144', '24', '124', '169'],
      correctOptionIndex: 0,
      explanation: '12 x 12 = 144.',
    ),
    QuestionItem(
      id: 'pgsd_mat_059',
      questionText: 'Hasil akar kuadrat √225 adalah:',
      options: ['15', '25', '13', '35'],
      correctOptionIndex: 0,
      explanation: '15 x 15 = 225.',
    ),
    QuestionItem(
      id: 'pgsd_mat_060',
      questionText: 'Hasil pangkat tiga dari 4³ adalah:',
      options: ['64', '12', '16', '36'],
      correctOptionIndex: 0,
      explanation: '4 x 4 x 4 = 64.',
    ),
    QuestionItem(
      id: 'pgsd_mat_061',
      questionText: 'Hasil akar pangkat tiga ∛512 adalah:',
      options: ['8', '6', '7', '9'],
      correctOptionIndex: 0,
      explanation: '8 x 8 x 8 = 512.',
    ),
    QuestionItem(
      id: 'pgsd_mat_062',
      questionText: 'Sebuah bel A berbunyi tiap 4 menit dan bel B tiap 6 menit. Jika berbunyi bersama jam 08.00, kapan berbunyi bersama lagi?',
      options: ['08.12', '08.10', '08.24', '08.16'],
      correctOptionIndex: 0,
      explanation: 'KPK dari 4 dan 6 adalah 12 menit. Jam 08.00 + 12 menit = 08.12.',
    ),
    QuestionItem(
      id: 'pgsd_mat_063',
      questionText: 'Ibu memiliki 20 apel dan 30 jeruk. Buah akan dimasukkan ke kantong plastik sama banyak. Berapa kantong terbanyak yang dibutuhkan?',
      options: ['10 kantong', '5 kantong', '15 kantong', '20 kantong'],
      correctOptionIndex: 0,
      explanation: 'FPB dari 20 dan 30 adalah 10.',
    ),
    QuestionItem(
      id: 'pgsd_mat_064',
      questionText: 'Sifat bangun datar trapesium sama kaki yang benar adalah:',
      options: ['Memiliki sepasang sisi sejajar dan dua kaki sama panjang', 'Keempat sisinya sama panjang', 'Keempat sudutnya 90°', 'Tidak memiliki sumbu simetri'],
      correctOptionIndex: 0,
      explanation: 'Trapesium sama kaki mempunyai sepasang sisi sejajar dan dua sisi miring (kaki) yang sama panjang.',
    ),
    QuestionItem(
      id: 'pgsd_mat_065',
      questionText: 'Sifat bangun datar layang-layang yang benar adalah:',
      options: ['Memiliki dua pasang sisi sama panjang dan diagonal saling tegak lurus', 'Semua sudutnya sama besar', 'Keempat sisinya sama panjang', 'Memiliki 4 sumbu simetri'],
      correctOptionIndex: 0,
      explanation: 'Layang-layang memiliki dua pasang sisi berdekatan sama panjang dan diagonalnya berpotongan tegak lurus.',
    ),
    QuestionItem(
      id: 'pgsd_mat_066',
      questionText: 'Sifat jajaran genjang yang benar adalah:',
      options: ['Sisi-sisi yang berhadapan sama panjang dan sejajar', 'Semua sudut siku-siku', 'Memiliki 4 sumbu simetri lipat', 'Diagonalnya sama panjang'],
      correctOptionIndex: 0,
      explanation: 'Jajaran genjang memiliki dua pasang sisi sejajar dan sama panjang.',
    ),
    QuestionItem(
      id: 'pgsd_mat_067',
      questionText: 'Berapa banyak simetri lipat yang dimiliki oleh bangun persegi?',
      options: ['4', '2', '8', '1'],
      correctOptionIndex: 0,
      explanation: 'Persegi memiliki 4 sumbu simetri lipat.',
    ),
    QuestionItem(
      id: 'pgsd_mat_068',
      questionText: 'Berapa banyak simetri lipat yang dimiliki oleh segitiga sama sisi?',
      options: ['3', '1', '2', '0'],
      correctOptionIndex: 0,
      explanation: 'Segitiga sama sisi mempunyai 3 sumbu simetri lipat.',
    ),
    QuestionItem(
      id: 'pgsd_mat_069',
      questionText: 'Berapa banyak simetri lipat pada persegi panjang?',
      options: ['2', '4', '1', '0'],
      correctOptionIndex: 0,
      explanation: 'Persegi panjang memiliki 2 sumbu simetri lipat.',
    ),
    QuestionItem(
      id: 'pgsd_mat_070',
      questionText: 'Berapa jumlah titik sudut yang dimiliki oleh bangun ruang kubus?',
      options: ['8', '6', '12', '4'],
      correctOptionIndex: 0,
      explanation: 'Kubus memiliki 8 titik sudut, 6 sisi, dan 12 rusuk.',
    ),
    QuestionItem(
      id: 'pgsd_mat_071',
      questionText: 'Berapa jumlah rusuk yang dimiliki oleh limas segi empat?',
      options: ['8', '5', '6', '12'],
      correctOptionIndex: 0,
      explanation: 'Limas segi empat memiliki 4 rusuk alas + 4 rusuk tegak = 8 rusuk.',
    ),
    QuestionItem(
      id: 'pgsd_mat_072',
      questionText: 'Berapa jumlah sisi yang dimiliki oleh prisma segitiga?',
      options: ['5', '6', '9', '3'],
      correctOptionIndex: 0,
      explanation: 'Prisma segitiga memiliki 2 alas segitiga + 3 sisi tegak = 5 sisi.',
    ),
    QuestionItem(
      id: 'pgsd_mat_073',
      questionText: 'Dalam koordinat Kartesius (x, y), titik A(3, -4) berada pada kuadran:',
      options: ['Kuadran IV', 'Kuadran I', 'Kuadran II', 'Kuadran III'],
      correctOptionIndex: 0,
      explanation: 'X positif dan Y negatif terletak pada Kuadran IV.',
    ),
    QuestionItem(
      id: 'pgsd_mat_074',
      questionText: 'Sumbu horizontal pada sistem koordinat Kartesius dinamakan sumbu:',
      options: ['Absis (Sumbu X)', 'Ordinat (Sumbu Y)', 'Z', 'Diagonal'],
      correctOptionIndex: 0,
      explanation: 'Sumbu horizontal disebut absis (x).',
    ),
    QuestionItem(
      id: 'pgsd_mat_075',
      questionText: 'Sumbu vertikal pada sistem koordinat Kartesius dinamakan sumbu:',
      options: ['Ordinat (Sumbu Y)', 'Absis (Sumbu X)', 'Polar', 'Vektor'],
      correctOptionIndex: 0,
      explanation: 'Sumbu vertikal disebut ordinat (y).',
    ),
    QuestionItem(
      id: 'pgsd_mat_076',
      questionText: 'Diagram berbentuk lingkaran yang terbagi menjadi sektor-sektor persentase atau derajat dinamakan:',
      options: ['Diagram Lingkaran (Pie Chart)', 'Diagram Batang', 'Diagram Garis', 'Histogram'],
      correctOptionIndex: 0,
      explanation: 'Diagram lingkaran menyajikan data proporsional dalam sektor lingkaran.',
    ),
    QuestionItem(
      id: 'pgsd_mat_077',
      questionText: 'Diagram yang paling cocok untuk menampilkan perkembangan data berurutan waktu (perubahan kontinuitas) adalah:',
      options: ['Diagram Garis', 'Diagram Batang', 'Diagram Lingkaran', 'Diagram Pictogram'],
      correctOptionIndex: 0,
      explanation: 'Diagram garis efektif memperlihatkan tren waktu.',
    ),
    QuestionItem(
      id: 'pgsd_mat_078',
      questionText: 'Pernyataan teorema Pythagoras pada segitiga siku-siku dengan hipotenusa c dan sisi siku-siku a dan b adalah:',
      options: ['c² = a² + b²', 'a² = b² + c²', 'c = a + b', 'c² = a² - b²'],
      correctOptionIndex: 0,
      explanation: 'Kuadrat hipotenusa sama dengan jumlah kuadrat dua sisi siku-sikunya.',
    ),
    QuestionItem(
      id: 'pgsd_mat_079',
      questionText: 'Pada segitiga siku-siku jika alas a = 3 cm dan tinggi b = 4 cm, berapa panjang hipotenusa c?',
      options: ['5 cm', '7 cm', '6 cm', '8 cm'],
      correctOptionIndex: 0,
      explanation: 'c = √(3² + 4²) = √(9 + 16) = √25 = 5 cm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_080',
      questionText: 'Pencerminan (refleksi) suatu bangun datar terhadap garis cermin akan menghasilkan bayangan yang:',
      options: ['Sama bentuk dan ukurannya (kongruen) serta terbalik posisinya', 'Lebih besar', 'Berbeda bentuk', 'Lebih kecil'],
      correctOptionIndex: 0,
      explanation: 'Refleksi menghasilkan bayangan yang kongruen dengan posisi simetris terbalik.',
    ),
    QuestionItem(
      id: 'pgsd_mat_081',
      questionText: 'Pergeseran seluruh titik pada bangun datar sejauh dan arah tertentu dinamakan:',
      options: ['Translasi', 'Refleksi', 'Rotasi', 'Dilatasi'],
      correctOptionIndex: 0,
      explanation: 'Translasi adalah pergeseran posisi bangun datar.',
    ),
    QuestionItem(
      id: 'pgsd_mat_082',
      questionText: 'Perputaran bangun datar mengelilingi suatu titik pusat dinamakan:',
      options: ['Rotasi', 'Translasi', 'Dilatasi', 'Refleksi'],
      correctOptionIndex: 0,
      explanation: 'Rotasi adalah pemutaran posisi objek terhadap pusat sudut putar.',
    ),
    QuestionItem(
      id: 'pgsd_mat_083',
      questionText: 'Perbesaran atau pengecilan ukuran bangun datar tanpa mengubah bentuknya dinamakan:',
      options: ['Dilatasi', 'Translasi', 'Rotasi', 'Refleksi'],
      correctOptionIndex: 0,
      explanation: 'Dilatasi mengubah ukuran skala objek.',
    ),
    QuestionItem(
      id: 'pgsd_mat_084',
      questionText: 'Dua bangun datar dikatakan sebangun jika:',
      options: ['Sudut-sudut bersesuaian sama besar dan sisi bersesuaian sebanding', 'Luasnya pasti sama', 'Kelilingnya sama', 'Bentuknya berbeda'],
      correctOptionIndex: 0,
      explanation: 'Kesebangunan mensyaratkan perbandingan sisi proporsional dan sudut sama besar.',
    ),
    QuestionItem(
      id: 'pgsd_mat_085',
      questionText: 'Dua bangun datar dikatakan kongruen jika:',
      options: ['Bentuk dan ukurannya persis sama', 'Luasnya beda', 'Hanya sudutnya sama', 'Warnanya sama'],
      correctOptionIndex: 0,
      explanation: 'Kongruen berarti persis sama bentuk dan ukurannya.',
    ),
    QuestionItem(
      id: 'pgsd_mat_086',
      questionText: 'Hasil penjumlahan 2,4 + 1,75 adalah:',
      options: ['4,15', '3,15', '4,25', '3,95'],
      correctOptionIndex: 0,
      explanation: '2,40 + 1,75 = 4,15.',
    ),
    QuestionItem(
      id: 'pgsd_mat_087',
      questionText: 'Hasil pengurangan 5,2 - 2,84 adalah:',
      options: ['2,36', '2,46', '3,36', '2,26'],
      correctOptionIndex: 0,
      explanation: '5,20 - 2,84 = 2,36.',
    ),
    QuestionItem(
      id: 'pgsd_mat_088',
      questionText: 'Hasil perkalian 0,5 x 0,4 adalah:',
      options: ['0,2', '0,02', '2,0', '0,25'],
      correctOptionIndex: 0,
      explanation: '0,5 x 0,4 = 0,20 = 0,2.',
    ),
    QuestionItem(
      id: 'pgsd_mat_089',
      questionText: 'Hasil pembagian 4,8 : 0,6 adalah:',
      options: ['8', '0,8', '80', '6'],
      correctOptionIndex: 0,
      explanation: '48 / 6 = 8.',
    ),
    QuestionItem(
      id: 'pgsd_mat_090',
      questionText: 'Metode Realistic Mathematics Education (RME) yang dikembangkan di Belanda menekankan bahwa matematika adalah:',
      options: ['Aktivitas manusia yang berkaitan dengan kehidupan nyata', 'Hafalan rumus murni', 'Latihan soal abstrak tanpa alat bantu', 'Aturan kaku matematika formal'],
      correctOptionIndex: 0,
      explanation: 'RME mengaitkan matematika dengan realitas dunia siswa.',
    ),
    QuestionItem(
      id: 'pgsd_mat_091',
      questionText: 'Alat peraga dekak-dekak (Sempoa) sangat berguna di SD untuk menanamkan konsep:',
      options: ['Nilai tempat dan operasi hitung penjumlahan/pengurangan', 'Sudut lingkaran', 'Teorema Pythagoras', 'Peluang kejadian'],
      correctOptionIndex: 0,
      explanation: 'Sempoa membantu visualisasi manik-manik nilai tempat.',
    ),
    QuestionItem(
      id: 'pgsd_mat_092',
      questionText: 'Penggunaan media papan berpaku (Geoboard) di SD bertujuan untuk membantu siswa mempelajari:',
      options: ['Konsep keliling dan luas bangun datar', 'Operasi pembagian desimal', 'Statistika rata-rata', 'Persamaan kuadrat'],
      correctOptionIndex: 0,
      explanation: 'Geoboard melatih pembentukan bangun datar dan perhitungan unit satuan luas.',
    ),
    QuestionItem(
      id: 'pgsd_mat_093',
      questionText: 'Sebuah dadu bersisi 6 dilempar sekali. Peluang muncul angka genap (2, 4, 6) adalah:',
      options: ['1/2 (atau 3/6)', '1/6', '1/3', '2/3'],
      correctOptionIndex: 0,
      explanation: 'Ada 3 angka genap dari 6 kemungkinan = 3/6 = 1/2.',
    ),
    QuestionItem(
      id: 'pgsd_mat_094',
      questionText: 'Sebuah koin seimbang dilempar sekali. Peluang muncul angka adalah:',
      options: ['1/2', '1', '1/4', '0'],
      correctOptionIndex: 0,
      explanation: 'Peluang = 1 sisi angka / 2 total sisi = 1/2.',
    ),
    QuestionItem(
      id: 'pgsd_mat_095',
      questionText: 'Suatu bak berbentuk kubus terisi penuh air sebanyak 1.000 liter. Berapa panjang rusuk bak tersebut? (1 liter = 1 dm³)',
      options: ['10 dm (1 meter)', '100 dm', '1 dm', '5 dm'],
      correctOptionIndex: 0,
      explanation: '∛1000 dm³ = 10 dm.',
    ),
    QuestionItem(
      id: 'pgsd_mat_096',
      questionText: 'Umur Ayah 4 windu. Berapa tahun umur Ayah? (1 windu = 8 tahun)',
      options: ['32 tahun', '40 tahun', '24 tahun', '48 tahun'],
      correctOptionIndex: 0,
      explanation: '4 x 8 tahun = 32 tahun.',
    ),
    QuestionItem(
      id: 'pgsd_mat_097',
      questionText: 'Sebuah dekade sama dengan berapa tahun?',
      options: ['10 tahun', '100 tahun', '5 tahun', '8 tahun'],
      correctOptionIndex: 0,
      explanation: '1 dekade (dasawarsa) = 10 tahun.',
    ),
    QuestionItem(
      id: 'pgsd_mat_098',
      questionText: 'Satu abad sama dengan berapa tahun?',
      options: ['100 tahun', '10 tahun', '1000 tahun', '50 tahun'],
      correctOptionIndex: 0,
      explanation: '1 abad = 100 tahun.',
    ),
    QuestionItem(
      id: 'pgsd_mat_099',
      questionText: 'Pendekatan Bruner dalam pembelajaran matematika SD melalui 3 tahap berurutan yaitu:',
      options: ['Enaktif, Ikonik, dan Simbolik', 'Simbolik, Enaktif, Ikonik', 'Ikonik, Enaktif, Simbolik', 'Sensori, Operasional, Formal'],
      correctOptionIndex: 0,
      explanation: 'Bruner membagi belajar matematika: Enaktif (benda konkret), Ikonik (gambar), Simbolik (lambang).',
    ),
    QuestionItem(
      id: 'pgsd_mat_100',
      questionText: 'Tujuan utama pembelajaran Matematika di Sekolah Dasar adalah untuk mengembangkan:',
      options: ['Kemampuan berpikir logis, analitis, sistematis, kritis, dan kreatif serta bernalar', 'Kemampuan menghafal rumus cepat', 'Kemampuan berhitung cepat tanpa pemahaman', 'Keterampilan menggambar teknik'],
      correctOptionIndex: 0,
      explanation: 'Matematika SD membentuk fondasi penalaran logis dan pemecahan masalah kehidupan sehari-hari.',
    ),
  ];
}
