// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/puji_anak/puji_anak_dialog_npc.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class PujiAnakDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat dipuji orang tua berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Hehehe! ( * $npcName tersenyum lebar dengan mata berbinar-binar saat dipuji $parentName * ) 😊👶',
        'Bababa! ( * $npcName menepuk-nepuk tangannya sendiri gembira mendengar pujian * )',
        'Gigaaa! ( * $npcName merangkak mendekati $parentName lalu memeluk kakinya bangga * )',
        'Ooooh! ( * $npcName tertawa ngakak sambil mendusel di dada $parentName * )',
        'Nyaaa! ( * $npcName menunjukkan mainan/kemampuannya lagi dengan wajah berseri-seri * )',
        'Abuuu... ( * $npcName mengoceh riang seolah bilang "aku kan anak pinter!" * )',
        'Mammm! ( * $npcName tersenyum malu-malu lalu menutupi wajahnya dengan kedua tangan mungil * )',
        'Dayaya! ( * $npcName melompat-lompat kecil di pangkuan $parentName gembira * )',
        'Tetete! ( * $npcName menggeleng-gelengkan kepalanya gembira menikmati pujian hangat * )',
        'Kicukicu! ( * $npcName memberikan ciuman bayi manis di pipi $parentName * )',
        'Ehhhe! ( * $npcName mengacungkan jari jempol mungilnya dengan lucu * )',
        'Agiii! ( * $npcName tersenyum lebar menampilkan dua gigi bawah barunya * )',
        'Owooo! ( * $npcName mengibas-ngibaskan tangannya seolah ingin dipeluk lagi * )',
        'Bubu! ( * $npcName menyandarkan kepalanya dengan rasa aman dan percaya diri * )',
        'Lalala! ( * $npcName bernyanyi bayi riang merayakan pujian dari $parentName * )',
        'Hummm! ( * $npcName mengedipkan matanya yang bulat dengan tatapan penuh cinta * )',
        'Cicu! ( * $npcName menggenggam tangan $parentName erat-erat dengan bangga * )',
        'Nyaa-ha! ( * $npcName tertawa geli saat $parentName mengusap rambutnya yang lembut * )',
        'Paapapa! ( * $npcName menunjuk dirinya sendiri sambil tersenyum bangga * )',
        'Glooogloo! ( * $npcName berguling-guling ceria di atas karpet setelah dipuji * )',
        'Oowgh! ( * $npcName meletakkan tangannya di dada seolah merasa sangat bahagia * )',
        'Yaaaya! ( * $npcName memberikan senyuman terbaiknya khusus untuk $parentName * )',
        'Wiii! ( * $npcName mengayunkan kakinya gembira di atas sofa * )',
        'Tatatata! ( * $npcName memeluk bonekanya erat-erat sambil tersenyum manis * )',
        'Ceriaaa! ( * $npcName menguap gembira lalu tertidur nyenyak dengan senyuman * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Makasih banyak $parentName! Aku memang anak pintar kan? Hehehe! 🌟😊✨',
        'Yeay! Dipuji $parentName! Nanti aku bakal makin rajin dan nurut deh!',
        'Wah, makasih $parentName! Hatiku rasanya seneng banget dipuji kayak gini!',
        'Aku kan anak kesayangan $parentName, jadi aku harus selalu berbuat baik!',
        'Hehehe, makasih $parentName! Sini aku cium pipi $parentName sebagai gantinya!',
        'Makasih $parentName! Nanti aku tunjukkan kehebatan melukis/merapikan mainan lagi ya!',
        'Uwah! Dipuji $parentName bikin aku jadi pengen melompat tinggi-tinggi!',
        'Makasih $parentName! Aku janji bakal terus jadi anak yang membanggakan!',
        'Yeaaay! $parentName emang paling jago bikin aku merasa jadi pahlawan super!',
        'Makasih banyak $parentName! Kata guru di TK aku juga harus rajin dan baik!',
        'Asyik! Terima kasih $parentName! Aku sayanggg banget sama $parentName!',
        'Makasih $parentName! Senyuman $parentName waktu muji aku manis banget deh!',
        'Uwah, makasih $parentName! Nanti aku bantu $parentName bersihin rumah lagi ya!',
        'Makasih $parentName! Aku bakal simpan kata-kata pujian ini di dalam hatiku!',
        'Yippie! Dipuji sama orang tua paling hebat di dunia! Makasih ya $parentName!',
        'Makasih $parentName! Aku merasa jadi anak paling beruntung di dunia!',
        'Hore! Nanti aku cerita ke teman-teman kalau aku baru aja dipuji $parentName!',
        'Waaah! Makasih $parentName! Rasanya ada sejuta bintang terang di dadaku!',
        'Makasih $parentName! Aku mau terus belajar hal baru biar dipuji lagi!',
        'Yeay! $parentName bangga sama aku, aku juga bangga punya $parentName!',
        'Makasih banyak $parentName! Peluk erat buat $parentName yang penyayang!',
        'Uwah, aku sampai keluar air mata bahagia dikit! Makasih $parentName!',
        'Makasih $parentName! Aku janji nggak bakal bikin $parentName kecewa!',
        'Hore, makasih $parentName! Hari ini aku jadi tambah bersemangat!',
      ];
    } else if (childAge <= 11) {
      return [
        'Makasih banyak ya $parentName! Pujian ini bener-bener nambah rasa percaya diri aku! 🌟👍✨',
        'Terima kasih $parentName! Aku bakal terus berusaha memberikan yang terbaik di sekolah!',
        'Alhamdulillah, terima kasih $parentName. Mendengar $parentName bangga adalah kebahagiaan terbesarku.',
        'Asyik! Terima kasih $parentName! Usaha keras dan belajarku akhirnya membuahkan hasil indah.',
        'Waaah! Makasih $parentName! Pujian dari orang tua rasanya jauh lebih berharga dari nilai seratus.',
        'Makasih $parentName! Aku berjanji akan tetap rendah hati dan terus belajar giat.',
        'Terima kasih $parentName! Kata-kata penyemangat $parentName selalu jadi pendorong utama suksesku.',
        'Hore! Terima kasih $parentName! Aku makin yakin kalau aku mampu meraih impianku.',
        'Wah, makasih ya $parentName! Dukungan dan kebanggaan $parentName sangat berarti buat aku.',
        'Terima kasih $parentName! Aku bersyukur punya orang tua yang selalu mengapresiasi usahaku.',
        'Makasih banyak $parentName! Sayang $parentName banget!',
        'Asyik! Terima kasih $parentName! Senyuman bangga di wajah $parentName bikin lelahku hilang.',
        'Terima kasih $parentName! Aku bakal pertahankan prestasi dan kebaikan ini terus!',
        'Makasih $parentName! Pengakuan dari $parentName membuatku merasa sangat dihargai.',
        'Wah, senangnya! Terima kasih $parentName sudah selalu melihat sisi positif dari diriku.',
        'Terima kasih $parentName! Aku akan terus jadi anak yang mandiri dan berbakti.',
        'Alhamdulillah, makasih $parentName! Pujian ini bakal aku ingat sebagai pemicu semangat.',
        'Terima kasih banyak $parentName! Semoga aku selalu bisa mengukir senyuman di wajah $parentName.',
        'Makasih $parentName! Dukungan moral dari $parentName tidak ada tandingannya di dunia ini.',
        'Wah makasih $parentName! Aku siap menghadapi ujian/tantangan berikutnya dengan mantap!',
        'Terima kasih $parentName! Semoga kebahagiaan dan kebanggaan ini bertahan selamanya.',
        'Asyik! Makasih $parentName! Aku bakal tunjukkan perkembangan yang makin bagus lagi nanti.',
        'Terima kasih banyak $parentName! Senang banget punya orang tua se-bijaksana $parentName.',
        'Makasih $parentName! Senyuman bangga orang tua adalah hadiah paling berharga buat anak!',
        'Terima kasih $parentName! Aku siap jadi anak yang lebih berprestasi lagi!',
      ];
    } else {
      return [
        'Terima kasih banyak ya $parentName! Apresiasi dan pujian ini sangat berarti bagi perkembangan jiwa saya. 🌟👏✨',
        'Alhamdulillah, terima kasih $parentName. Pengakuan dari orang tua adalah validasi tertinggi yang selalu saya harapkan.',
        'Terima kasih $parentName! Pujian dan kepercayaan ini menjadi bahan bakar utama bagi saya untuk terus berkarya.',
        'Wah, terima kasih banyak $parentName! Mendengar $parentName bangga pada pencapaian saya membuat segalanya terasa berharga.',
        'Terima kasih $parentName atas kata-kata bijak dan pujian hangatnya. Saya akan terus berusaha menjadi pribadi yang berguna.',
        'Makasih ya $parentName! $parentName selalu menjadi sosok pendorong yang paling setia dalam hidup saya.',
        'Terima kasih banyak $parentName! Kebanggaan $parentName adalah kompas yang menuntun langkah saya.',
        'Alhamdulillah, terima kasih $parentName! Rasa percaya diri saya semakin mantap berkat apresiasi $parentName.',
        'Terima kasih $parentName. Saya sangat bersyukur dibesarkan oleh orang tua yang penuh kasih dan penghargaan.',
        'Wah, terima kasih $parentName! Ini memberikan ketenangan jiwa dan kekuatan ekstra menghadapi dunia luar.',
        'Terima kasih banyak $parentName. Kepercayaan yang $parentName berikan tidak akan pernah saya sia-siakan.',
        'Makasih ya $parentName! Semoga saya senantiasa mampu menjaga nama baik dan martabat keluarga kita.',
        'Terima kasih $parentName! Pujian tulus ini akan selalu saya simpan dalam sudut memori paling hangat.',
        'Alhamdulillah, makasih $parentName! Rasa bangga yang $parentName pancarkan adalah kebahagiaan hidup saya.',
        'Terima kasih banyak $parentName! Semoga Allah/Tuhan selalu memberikan kesehatan dan umur panjang untuk $parentName.',
        'Wah, terima kasih $parentName! Ini membuktikan bahwa setiap kerja keras dan dedikasi tidak pernah sia-sia.',
        'Terima kasih $parentName atas kehangatan ini. Saya bangga dan bersyukur dilahirkan sebagai anak $parentName.',
        'Makasih $parentName! Apresiasi orang tua adalah benteng pertahanan terbaik dalam menghadapi lika-liku hidup.',
        'Terima kasih banyak $parentName. Doa dan kebanggaan $parentName adalah jalan pembuka kemudahan saya.',
        'Alhamdulillah, makasih $parentName! Kata-kata pujian ini sungguh menyejukkan hati dan pikiran.',
        'Terima kasih $parentName! Semoga saya selalu bisa menjadi kebanggaan orang tua di mana pun berada.',
        'Wah, makasih banyak $parentName! Ini menambah semangat saya untuk mencapai standar pencapaian yang lebih tinggi.',
        'Terima kasih $parentName! Momen apresiasi ini sangat berkesan dan menguatkan ikatan batin kita.',
        'Makasih ya $parentName... Kasih sayang dan pujian tulus orang tua memang tiada tandingannya.',
        'Terima kasih $parentName! I love you so much $parentName!',
      ];
    }
  }
}
