// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/adult_action_dialogue/desahan_masturbate/desahan_masturbate_dialog_user.dart
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class DesahanMasturbateDialogUser {
  /// Mengembalikan list 100 variasi narasi & desahan User saat Masturbate bersama pasangan berdasarkan gender User
  static List<String> getUserDialogues({
    required String playerName,
    required String playerGender,
    required String partnerName,
  }) {
    final bool isPlayerFemale = playerGender.trim().toLowerCase() == 'perempuan';

    if (isPlayerFemale) {
      return [
        'Mmh... $partnerName... lihat cara aku memanjakan diriku sambil menatapmu... 💖🔥',
        'Hah... hah... jariku sendiri meremas lembut di sini...',
        'Ahhh! Tatapan matamu yang gairah bikin aku makin memacu jariku...',
        'Hah... lihat kan betapa basah dan hangatnya aku...',
        'Mmmhh... hah... elusan jemariku sendiri makin kencang...',
        'Ah... ahh... $partnerName... sentuh dirimu sendiri juga sambil lihat aku...',
        'Haaah... napasku tersengal-sengal cuma karena kamu meremas dadamu...',
        'Mhmmm... nikmatnya stimulasi mandiri ini sambil menatapmu...',
        'Ahhh! Gesekan jemariku di titik sensitifku bikin gila...',
        'Hah... hah... aku membayangkan kamu yang sedang melakukannya padaku...',
        'Mmmh... ah... suaraku makin parau mendesahkan namamu...',
        'Ahhh! Kehangatan dari jemariku sendiri meluap nikmat...',
        'Hah... hah... lihat cara aku memainkan bagian ini khusus buatmu...',
        'Mhmmm... bisikkan dorongan gairah padaku $partnerName... ahh...',
        'Ahhh! Gesekan ritmis ini bikin pinggulku bergoyang sendiri...',
        'Haaah... aku sudah tidak bisa menahannya lagi... ahhh...',
        'Mmmh... sentuhan jemariku makin cepat dan intens...',
        'Ahhh! Nikmat ini luar biasa memabukkan...',
        'Hah... hah... desahan manisku makin kencang saat matamu menatapku...',
        'Mhmmm... dekatkan wajahmu tapi biarkan jariku yang bekerja... ahhh...',
        'Ahhh! Puncak kenikmatan stimulasi ini... aku milikmu...',
        'Haaah... aku mempercepat gerakan jemariku sekarang... ahh!',
        'Mmmh... napas menderuku beradu dengan tatapan liarmu...',
        'Ahhh! $partnerName... kamu beneran bikin aku ketagihan momen ini...',
        'Hah... hah... ayo kita klimaks bersama lewat stimulasi ini... ahhh! 💕',
        'Mhmmm... rasanya makin sensitif dan panas...',
        'Ahhh! Gerakan jariku makin tak terkendali...',
        'Haaah... elus dadaku pelan sambil aku terus memacu... ahhh...',
        'Mmmh... ritme usapan jemariku pas banget...',
        'Ahhh! Aku sudah tidak sanggup menahannya lagi... sebentar lagi...',
        'Hah... hah... bimbing imajinasiku menuju puncak sensasi ini...',
        'Mhmmm... kita saling menatap sambil menikmati milik masing-masing...',
        'Ahhh! $partnerName... kamu nakal banget menatapku begitu...',
        'Haaah... aku mau jariku bergerak lebih cepat sayang... ahh!',
        'Mmmh... sentuhan mandiri ini terasa sangat intens...',
        'Ahhh! Ya Tuhan... sensasi ini sungguh gila...',
        'Hah... hah... lihat betapa cepatnya gerakan tanganku...',
        'Mhmmm... bisikan mesramu menambah gairah di dadaku...',
        'Ahhh! Jariku menyentuh bagian paling peka... di situ!',
        'Haaah... aku serasa melayang tinggi di awan...',
        'Mmmh... kecup bibirku di sela-sela pacuan jariku...',
        'Ahhh! $partnerName... cepat... aku sudah hampir sampai puncaknya...',
        'Hah... hah... kehangatan ini meluap dari dalam...',
        'Mhmmm... senyuman puasmu bikin aku makin bersemangat...',
        'Ahhh! Jangan palingkan pandanganmu dariku $partnerName...',
        'Haaah... suaraku sampai habis mendesah karena nikmatnya...',
        'Mmmh... tiap pacuan jariku memberi kenikmatan luar biasa...',
        'Ahhh! Kita makin terbakar gairah malam ini...',
        'Hah... hah... aku lemas dalam kejutan sensasi ini...',
        'Mhmmm... $partnerName... sensasi masturbasi bersama ini luar biasa! 🔥',
        'Ahhh... rasanya makin intens dan nikmat sekali...',
        'Haaah... tatapanmu begitu menghangatkan jiwaku...',
        'Mmmh... ubah posisi dudukku sedikit... ahhh pas banget!',
        'Ahhh! Suara gairah kita saling bersahutan indah...',
        'Hah... hah... tatap jariku saat memacu lebih cepat...',
        'Mhmmm... jemariku menari di area paling sensitif...',
        'Ahhh! Aku mau kita seperti ini lebih sering...',
        'Haaah... gesekan lembut ini bikin merinding bahagia...',
        'Mmmh... rasa hangat di dalam tubuhku meluap-luap...',
        'Ahhh! $partnerName... puncaknya makin dekat... ahh!',
        'Hah... hah... napasku makin memburu dan cepat...',
        'Mhmmm... usap kepalaku saat aku terus memacu sayang...',
        'Ahhh! Gerakan tanganku penuh gairah mendalam...',
        'Haaah... jangan biarkan matamu terpejam...',
        'Mmmh... kecupan manis di dahi lalu lanjut memacu... ahh...',
        'Ahhh! Sensasi ini bikin seluruh badanku bergetar...',
        'Hah... hah... ikuti irama desahanku sayang...',
        'Mhmmm... $partnerName... senyumanmu bikin aku makin liar...',
        'Ahhh! Ya di situ! Aku pacu jariku lebih kencang!',
        'Haaah... aku memeluk bantal sambil memacu sekarang!',
        'Mmmh... tubuhku berkeringat tapi terasa nikmat sekali...',
        'Ahhh! Kehangatan sensasi ini menembus jantungku...',
        'Hah... hah... bisikkan lagi kata godaan di telingaku...',
        'Mhmmm... ritme pelan ini juga sangat menggoda...',
        'Ahhh! Aku merasa sangat diinginkan olehmu...',
        'Haaah... ayo kita tembus batas nikmat ini!',
        'Mmmh... sentuh paha atasmu sambil aku memacu jariku...',
        'Ahhh! $partnerName... kamu beneran bikin aku mabuk gairah...',
        'Hah... hah... tarikan napas liarmu bikin aku makin kencang...',
        'Mhmmm... ganti jari sedikit... ahhh enak banget!',
        'Ahhh! Puncak sensasi mandiri ini tiada tandingannya...',
        'Hah... hah... tekan sebentar di titik itu... hangat sekali...',
        'Mmmh... getaran lembut ini bikin ketagihan...',
        'Ahhh! Aah... a-aku sudah tidak kuat lagi... klimaks datang!',
        'Hah... hah... tatap aku saat klimaks memuncak!',
        'Mhmmm... rasanya meledak nikmat di dalam...',
        'Ahhh! $partnerName... terima kasih atas kebersamaan panas ini...',
        'Haaah... napasku masih tersengal-sengal di dekatmu...',
        'Mmmh... tiduran bersamaku sambil menyeka keringat...',
        'Ahhh! Senyum puasmu hadiah terbaik malam ini...',
        'Hah... hah... kita beneran pasangan paling kompak...',
        'Mhmmm... biarkan tubuh kita tetap rileks hangat...',
        'Ahhh! Momen nakal bersama ini selalu menyenangkan...',
        'Haaah... kecup bibirku pelan untuk menutup kesempurnaan ini...',
        'Mmmh... elusan tanganmu di rambutku menenangkan...',
        'Ahhh! Aku sayang banget sama kamu $partnerName...',
        'Hah... hah... napas kita pelan-pelan kembali teratur...',
        'Mhmmm... momen mesra ini favoritku selamanya...',
        'Ahhh! Suasana kamar ini jadi begitu hangat dan nakal...',
        'Haaah... mari kita tidur nyenyak dalam kehangatan cinta ini! 💕',
      ];
    } else {
      return [
        'Uhh... $partnerName... lihat cara aku memperlakukannya khusus buatmu... 💖🔥',
        'Hah... hah... genggaman tanganku sendiri makin kencang di sini...',
        'Uhh! Tatapan mata liarmu bikin gairahku makin membakar...',
        'Haaah... lihat betapa tegang dan hangatnya aku sekarang...',
        'Mmh... hah... urutan jemariku di batangku makin cepat...',
        'Uhh... ahh... $partnerName... sentuh dirimu juga sambil tatap aku...',
        'Hah... hah... napasku berat saat melihat kamu memanjakan dirimu...',
        'Uhh... nikmatnya stimulasi ini sambil mendengarkan desahanmu...',
        'Haaah! Gesekan tanganku di bagian ujung bikin aku gila...',
        'Mmh... aku bayangkan bagaimana jika ini bibir hangatmu...',
        'Uhh... ah... suaraku makin berat mendesahkan namamu...',
        'Hah... hah... ketegangan di tanganku meluap nikmat...',
        'Uhh! Lihat ritme ganjarku yang makin bersemangat ini...',
        'Haaah... bisikkan kata godaan padaku $partnerName... uhh...',
        'Mmh... gesekan cepat ini bikin pinggulku terdorong...',
        'Uhh! Aku sudah hampir tidak bisa menahannya lagi...',
        'Hah... hah... gerakan tanganku makin cepat dan intens...',
        'Uhh! Nikmat ini luar biasa memabukkan...',
        'Haaah... desahan beratku makin kencang saat matamu menatapku...',
        'Mmh... dekatkan wajahmu tapi biarkan tanganku yang bekerja...',
        'Uhh! Puncak kenikmatan stimulasi ini... khusus buatmu...',
        'Hah... hah... aku pacu gerakan tanganku sekuatnya sekarang... uhh!',
        'Uhh... napas menderuku beradu dengan tatapan liarmu...',
        'Haaah! $partnerName... kamu beneran bikin gairahku memuncak...',
        'Mmh... ayo kita klimaks bersama lewat momen ini! 💕',
        'Uhh... rasanya makin sensitif dan panas...',
        'Hah... hah... gerakan tanganku makin tak terkendali...',
        'Uhh! Elus dadaku pelan sambil aku terus memacu... uhh...',
        'Haaah... ritme usapan tanganku pas banget...',
        'Mmh... aku sudah tidak sanggup menahannya lagi... sebentar lagi...',
        'Uhh! Bimbing imajinasiku menuju puncak sensasi ini...',
        'Hah... hah... kita saling menatap sambil menikmati milik masing-masing...',
        'Uhh! $partnerName... kamu nakal banget menatapku begitu...',
        'Haaah... aku mau tanganku bergerak lebih cepat sayang... uhh!',
        'Mmh... sentuhan mandiri ini terasa sangat intens...',
        'Uhh! Ya Tuhan... sensasi ini sungguh gila...',
        'Hah... hah... lihat betapa cepatnya pacuan tanganku...',
        'Uhh... bisikan mesramu menambah gairah di dadaku...',
        'Haaah! Tanganku menyentuh area paling peka... di situ!',
        'Mmh... aku serasa melayang tinggi di awan...',
        'Uhh! Kecup bibirku di sela-sela pacuan tanganku...',
        'Hah... hah... $partnerName... cepat... aku sudah mau ejakulasi...',
        'Uhh... kehangatan ini meluap dari dalam...',
        'Haaah... senyuman puasmu bikin aku makin bersemangat...',
        'Mmh... jangan palingkan pandanganmu dariku $partnerName...',
        'Uhh! Suaraku sampai serak mendesah karena nikmatnya...',
        'Hah... hah... tiap kocokan tanganku memberi kenikmatan luar biasa...',
        'Uhh! Kita makin terbakar gairah malam ini...',
        'Haaah... aku lemas dalam kejutan sensasi ini...',
        'Mmh... $partnerName... sensasi masturbasi bersama ini luar biasa! 🔥',
        'Uhh... rasanya makin intens dan nikmat sekali...',
        'Hah... hah... tatapanmu begitu menghangatkan jiwaku...',
        'Uhh... ubah posisi dudukku sedikit... ahhh pas banget!',
        'Haaah! Suara gairah kita saling bersahutan indah...',
        'Mmh... tatap tanganku saat memacu lebih cepat...',
        'Uhh! Tanganku menari di area paling sensitif...',
        'Hah... hah... aku mau kita seperti ini lebih sering...',
        'Uhh! Gesekan cepat ini bikin merinding bahagia...',
        'Haaah... rasa hangat di dalam tubuhku meluap-luap...',
        'Mmh... $partnerName... puncaknya makin dekat... uhh!',
        'Uhh! Napasku makin memburu dan cepat...',
        'Hah... hah... usap kepalaku saat aku terus memacu sayang...',
        'Uhh! Gerakan tanganku penuh gairah mendalam...',
        'Haaah... jangan biarkan matamu terpejam...',
        'Mmh... kecupan manis di dahi lalu lanjut memacu... uhh...',
        'Uhh! Sensasi ini bikin seluruh badanku bergetar...',
        'Hah... hah... ikuti irama desahanku sayang...',
        'Uhh... $partnerName... senyumanmu bikin aku makin liar...',
        'Haaah! Ya di situ! Aku pacu tanganku lebih kencang!',
        'Mmh... aku bersandar di bantal sambil memacu sekarang!',
        'Uhh! Tubuhku berkeringat tapi terasa nikmat sekali...',
        'Hah... hah... kehangatan sensasi ini menembus jantungku...',
        'Uhh... bisikkan lagi kata godaan di telingaku...',
        'Haaah... ritme pelan ini juga sangat menggoda...',
        'Mmh... aku merasa sangat diinginkan olehmu...',
        'Uhh! Ayo kita tembus batas nikmat ini!',
        'Hah... hah... sentuh dadamu sambil aku memacu tanganku...',
        'Uhh! $partnerName... kamu beneran bikin aku mabuk gairah...',
        'Haaah... tarikan napas liarmu bikin aku makin kencang...',
        'Mmh... ganti pegangan sedikit... uhh enak banget!',
        'Uhh! Puncak sensasi mandiri ini tiada tandingannya...',
        'Hah... hah... tekan sebentar di bagian bawah... hangat sekali...',
        'Uhh... getaran cepat ini bikin ketagihan...',
        'Haaah! Uhh... a-aku sudah tidak kuat lagi... klimaks/ejakulasi datang!',
        'Mmh... tatap aku saat ejakulasi memuncak!',
        'Uhh! Rasanya meledak nikmat di luar/dalam...',
        'Hah... hah... $partnerName... terima kasih atas kebersamaan panas ini...',
        'Uhh... napasku masih tersengal-sengal di dekatmu...',
        'Haaah... tiduran bersamaku sambil menyeka keringat...',
        'Mmh... senyum puasmu hadiah terbaik malam ini...',
        'Uhh! Kita beneran pasangan paling kompak...',
        'Hah... hah... biarkan tubuh kita tetap rileks hangat...',
        'Uhh! Momen nakal bersama ini selalu menyenangkan...',
        'Haaah... kecup bibirku pelan untuk menutup kesempurnaan ini...',
        'Mmh... elusan tanganmu di dada dan rambutku menenangkan...',
        'Uhh! Aku sayang banget sama kamu $partnerName...',
        'Hah... hah... napas kita perlahan teratur dan tenang...',
        'Mmh... momen mesra ini favoritku selamanya...',
        'Uhh! Suasana kamar ini jadi begitu hangat dan nakal...',
        'Haaah... mari kita tidur nyenyak dalam kehangatan cinta ini! 💕',
      ];
    }
  }
}
