// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/beri_uang_jajan/beri_uang_jajan_dialog_user.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class BeriUangJajanDialogUser {
  /// Mengembalikan list 100 variasi dialog User (Orang Tua) saat memberikan uang jajan
  static List<String> getUserDialogues({
    required String childName,
    required int childAge,
    required String parentName,
    required String amountFormatted,
  }) {
    if (childAge < 3) {
      return [
        'Ini nak, $parentName pegangkan uang jajan buat $childName ya, walau masih kecil hihi... 💵👶',
        'Nih buat tabungan bayi kesayangan $parentName! Uang kertasnya jangan digigit ya sayang!',
        'Sini anak mungil $childName, $parentName kasih uang jajan buat beli biskuit bayi!',
        'Pegang uang ini pelan-pelan ya sayang, ini uang jajan pertama dari $parentName!',
        'Nanti uang jajan ini $parentName masukkan ke celengan bayi $childName ya!',
        'Ulian lucu sekali menggenggam uang! Ini buat perlengkapan jajanmu ya nak.',
        'Ini uang jajan untuk anak manis $childName, nanti $parentName yang belikan mainannya.',
        'Sini sayang, $parentName simpan uang ini di dompet khusus anak bayi ya!',
        'Senyumanmu saat memegang lembaran uang ini sungguh menggemaskan buah hatiku!',
        'Ini rezeki jajan buat $childName hari ini dari $parentName!',
        'Jangan dimakan ya kertasnya nak, ini uang jajan buat beli makanan bayi lezat!',
        'Nih sayang, uang jajan simbolis biar kamu belajar rezeki sejak kecil!',
        'Anak bayi $parentName dapat uang jajan! Semoga kamu tumbuh jadi orang yang dermawan ya.',
        'Pegang baik-baik ya anak pintar, ini uang jajan dari hasil kerja keras $parentName.',
        'Setiap lembar uang ini mengandung kebaikan dan kasih sayang $parentName padamu.',
        'Aduh lucunya tangan kecilmu mencoba memegang lembaran uang jajan ini!',
        'Ini buat beli susu kotak dan biskuit favoritmu ya $childName sayang.',
        'Nanti uang jajan ini kita kumpulkan buat beli sepatu bayi baru ya nak!',
        'Teruslah tersenyum riang buah hatiku, $parentName akan selalu mencukupi kebutuhanmu.',
        'Ini uang jajan dari $parentName, simpan di celengan lucu kamu ya!',
        'Tangan mungilmu sangat menggemaskan saat menerima uang jajan ini.',
        'Semoga rezekimu melimpah sampai dewasa nanti ya nak, ini uang jajan awalmu.',
        'Nanti kalau udah besar baru boleh jajan sendiri ya, sekarang $parentName yang bantu.',
        'Kasih sayang dan uang jajan ini tulus dari hati $parentName untuk anak tercinta.',
        'Semoga uang jajan ini membawa kebahagiaan kecil untuk harimu yang lucu!',
      ];
    } else if (childAge <= 5) {
      return [
        'Nih anak pintar $childName! Uang jajan $amountFormatted dari $parentName buat jajan ya! 🍫🍦',
        'Ini uang jajan buat beli es krim dan permen kesukaanmu hari ini, $childName!',
        'Gunakan uang jajan ini baik-baik ya sayang! Beli makanan yang sehat dan bergizi.',
        'Nih $parentName kasih uang jajan, tapi ingat disisihkan sedikit buat masuk celengan ya!',
        'Anak rajin $childName berhak dapat uang jajan extra hari ini dari $parentName!',
        'Ini uang saku buat sekolah TK hari ini ya nak. Jangan nakal dan patuhi gurumu!',
        'Nih uang jajan buat $childName! Kalau ada kembaliannya, simpan di dompet kecilmu ya.',
        'Senang ya dapat uang jajan? $parentName juga senang bisa berbagi rezeki sama kamu.',
        'Beli jajan di tempat yang bersih ya sayang! Ini uang jajannya dari $parentName.',
        'Nih buat beli ciki favoritmu! Tapi jangan lupa makan nasi dulu ya nak!',
        'Ini uang jajan harian untuk anak tercantik/tertampan kesayangan $parentName!',
        'Tabung sebagian ya nak! Ini uang jajan dari $parentName untuk harimu yang ceria.',
        'Semoga uang jajan ini bisa bikin senyuman manis $childName makin lebar hari ini!',
        'Nih hadiah anak penurut! Uang jajan khusus dari $parentName!',
        'Gunakan buat jajan bersama teman-temanmu ya sayang, berbagi itu indah!',
        'Ini uang jajan untuk buah hati $parentName. Hati-hati jangan sampai hilang ya!',
        'Nih simpan baik-baik di kantong bajumu! Uang jajan dari orang tua tersayang.',
        'Belanja yang hemat ya anak pinter! Ini uang saku buat jajan harimu.',
        'Semoga kamu makin semangat belajar dan bermain dengan adanya uang jajan ini!',
        'Nih uang jajan dari $parentName! Minta tolong Ibu/Ayah kalau mau beli di toko ya.',
        'Ingat pesan $parentName, jangan jajan es sembarangan ya nak! Ini uangnya.',
        'Uang jajan ini bentuk kasih sayang dan apresiasi $parentName untuk anak baik.',
        'Hati-hati menyimpan uangnya ya $childName, jangan sampai terjatuh di jalan.',
        'Ayo bilang apa sama $parentName kalau diberi uang jajan? Hehehe ini uangnya!',
        'Semoga uang jajan ini menambah kebahagiaan harimu yang manis!',
      ];
    } else if (childAge <= 11) {
      return [
        'Ini uang jajan sekolah kamu hari ini $amountFormatted ya $childName. Jajan yang bijak! 💵🏫',
        'Nih $parentName berikan uang saku harian. Sebagian disisihkan untuk tabungan ya nak.',
        'Gunakan uang jajan ini untuk beli makanan sehat di kantin sekolah ya $childName.',
        'Ini uang jajan tambahan dari $parentName karena kamu sudah rajin belajar dan berprestasi!',
        'Simpan uang jajan ini dengan baik di dompet sekolahmu ya. Jangan sampai tercecer.',
        'Nih $amountFormatted buat jajan dan ongkos kecilmu hari ini, anak kesayangan $parentName.',
        'Selalu utamakan beli perlengkapan sekolah & makanan bergizi ya dengan uang jajan ini.',
        'Semoga uang saku ini cukup untuk memenuhi kebutuhan jajamu selama kegiatan sekolah.',
        'Ini rezeki dari hasil kerja keras $parentName, gunakan dengan penuh tanggung jawab ya.',
        'Nih uang jajan buat $childName! Belajarlah mengelola uang sejak dini ya anak hebat.',
        'Kamu sudah makin dewasa dan mandiri. Ini uang saku harianmu dari $parentName.',
        'Jika ada sisa dari uang jajan ini, jangan lupa dimasukkan ke dalam tabungan bank anakmu.',
        'Nih uang jajan buat sekolah hari ini! Semangat belajarnya ya anak kebanggaan $parentName!',
        'Gunakan uang ini untuk hal-hal yang bermanfaat ya $childName sayang.',
        'Ini bentuk perhatian dan kasih sayang $parentName agar kamu tenang selama di sekolah.',
        'Jangan lupa traktir temanmu sesekali kalau ada rezeki lebih ya nak! Ini uang jajannya.',
        'Simpan di tempat yang aman ya! $parentName selalu mendoakan keselamatan dan kelancaran belajarmu.',
        'Nih uang saku harian $amountFormatted. Kalau butuh tambahan untuk kegiatan ekskul, cerita ke $parentName ya.',
        'Jadilah anak yang hemat dan tidak boros ya sayang. Ini uang saku dari $parentName.',
        'Semoga dengan uang jajan ini kamu makin bersemangat menuntut ilmu di sekolah!',
        'Ini uang jajan dari $parentName. Selalu bersyukur atas setiap rezeki yang kita terima ya nak.',
        'Nih jatah uang jajanmu! Ingat untuk tidak jajan di tempat yang kurang bersih.',
        'Setiap lembar uang saku ini diserta doa tulus dari $parentName untuk kebaikanmu.',
        'Gunakan uang jajan ini sebaik mungkin ya $childName, $parentName sangat menyayangimu.',
        'Nih uang saku hari ini! Selamat belajar dan bermain bersama teman-teman sekolahmu!',
      ];
    } else {
      return [
        'Ini uang saku & operasional harianmu $amountFormatted ya $childName. Kelola dengan bijak! 💳✨',
        'Nih $parentName berikan uang saku. Semoga bisa membantu memenuhi kebutuhan harianmu.',
        'Gunakan uang ini untuk transportasi, keperluan belajar, atau kebutuhan penting lainnya ya.',
        'Ini tambahan rezeki dari $parentName untuk mendukung aktivitas & perjuangan masa depanmu.',
        'Di usiamu yang makin dewasa, $parentName percaya kamu bisa mengelola uang saku ini dengan cermat.',
        'Nih uang saku dari $parentName. Jangan ragu bilang jika ada kebutuhan mendadak yang diperlukan.',
        'Selalu sisihkan sebagian untuk tabungan dan dana darurat pribadi ya $childName.',
        'Semoga uang saku ini memberikan kelancaran dan ketenangan dalam menjalani aktivitasmu.',
        'Ini bentuk kasih sayang dan apresiasi $parentName atas kemandirian serta kedewasaanmu.',
        'Gunakan dengan rasa tanggung jawab ya nak. $parentName selalu mendukung langkah positifmu.',
        'Nih jatah uang saku periode ini dari $parentName. Semoga bermanfaat dan penuh berkah.',
        'Selalu ingat untuk bersikap hemat dan tidak terbawa gaya hidup konsumtif ya sayang.',
        'Uang saku ini adalah hasil jerih payah $parentName, semoga memberimu motivasi untuk sukses.',
        'Semoga dengan dukungan ini kamu makin fokus mengejar cita-cita dan impianmu.',
        'Nih simpan baik-baik di rekening atau dompetmu ya $childName. Sukses selalu buatmu!',
        'Kasih sayang dan uang saku dari $parentName selalu mengiringi langkah perjuanganmu.',
        'Gunakan untuk hal-hal yang produktif dan membawa kebaikan bagi dirimu dan sesama.',
        'Nih tambahan modal harianmu dari $parentName. Tetaplah menjadi pribadi yang rendah hati.',
        'Semoga kebaikan dan kemudahan selalu menyertai setiap rupiah yang kamu pergunakan.',
        'Jadilah sosok yang bijak dalam finansial. Ini uang saku dari $parentName untukmu.',
        'Nih buat pegangan kamu hari ini! Jangan lupa jaga kesehatan dan porsi makanmu ya.',
        'Terima kasih sudah menjadi anak yang berbakti dan membanggakan orang tua. Ini uang sakumu.',
        'Semoga rezeki ini membawa kedamaian dan kelancaran bagi seluruh urusanmu.',
        'Nih uang saku harian/mingguan dari $parentName! Doa $parentName selalu bersamamu.',
        'Manfaatkan sebaik-baiknya ya nak. $parentName sangat mencintai dan membanggakanmu!',
      ];
    }
  }
}
