// lib/game/widgets/aktivitas_menu/pilih_aktivitas/pendidikan_karir/career_logic/kerja_logic/special_carrier/atlit_profesional_job_logic/aktivitas_karir_atlet/sepakbola/action_menu/sosial_media_fans/press_conference_logic/press_conference_events.dart

import 'press_conference_models.dart';

class PressConferenceEvents {
  static List<PressEvent> getAllEvents() {
    return [
      // 1. Pra-Pertandingan (Pre-Match)
      PressEvent(
        id: 'pre_match_big_game',
        title: 'Konferensi Pers Pra-Pertandingan ⚽🔥',
        category: 'Pra-Pertandingan',
        question: 'Wartawan: "Pertandingan besar melawan rival utama tinggal menghitung hari. Bagaimana kesiapan tim dan apakah kalian yakin bisa menang?"',
        options: [
          PressOption(
            label: '🙏 Rendah Hati (Humble)',
            styleName: 'Rendah Hati',
            answerText: '"Lawan adalah tim yang sangat kuat. Kami menghormati mereka, namun kami bekerja keras di latihan untuk memberikan yang terbaik."',
            publicTrustDelta: 8,
            pressureDelta: -5,
            happinessDelta: 2,
            relationshipDelta: 5,
            mediaGrade: 'A',
            fanReaction: '💬 Fans memuji sikap dewasa dan profesionalisme kamu!',
            teamReaction: '💬 Pelatih dan rekan tim merasa tenang dengan jawabanmu.',
          ),
          PressOption(
            label: '🔥 Percaya Diri / Agresif (Aggressive)',
            styleName: 'Agresif',
            answerText: '"Kami di sini untuk menang! Lawan tidak ada apa-apanya jika kami bermain dengan kekuatan penuh."',
            publicTrustDelta: -4,
            pressureDelta: 10,
            happinessDelta: 5,
            relationshipDelta: -3,
            mediaGrade: 'B',
            fanReaction: '💬 Fans lawan murka di media sosial! Suportermu bersorak antusias!',
            teamReaction: '💬 Rekan tim merasa tertekan oleh ekspektasi tinggi yang kamu ciptakan.',
          ),
          PressOption(
            label: '🎭 Diplomatis / Netral (Diplomatic)',
            styleName: 'Diplomatis',
            answerText: '"Bola itu bundar. Hasilnya akan kita lihat di lapangan nanti."',
            publicTrustDelta: 3,
            pressureDelta: 0,
            happinessDelta: 0,
            relationshipDelta: 2,
            mediaGrade: 'B',
            fanReaction: '💬 Jawaban standar yang tidak memicu kontroversi.',
            teamReaction: '💬 Tim fokus pada persiapan pertandingan.',
          ),
          PressOption(
            label: '🤡 Humor / Lucu (Humorous)',
            styleName: 'Humor',
            answerText: '"Yang penting nanti malam tidur nyenyak dulu, sisanya serahkan pada rumput stadion!"',
            publicTrustDelta: 5,
            pressureDelta: -8,
            happinessDelta: 8,
            relationshipDelta: -2,
            mediaGrade: 'C',
            fanReaction: '💬 Unggahan klip videomu lucu dan viral di medsos!',
            teamReaction: '💬 Pelatih menggelengkan kepala melihat jawaban kurang seriusmu.',
          ),
        ],
      ),

      // 2. Pasca-Pertandingan (Post-Match Win)
      PressEvent(
        id: 'post_match_victory',
        title: 'Konferensi Pers Pasca-Kemenangan 🏆✨',
        category: 'Pasca-Pertandingan',
        question: 'Wartawan: "Selamat atas kemenangan luar biasa hari ini! Apa kunci sukses penampilan gemilangmu di lapangan?"',
        options: [
          PressOption(
            label: '🙏 Rendah Hati (Humble)',
            styleName: 'Rendah Hati',
            answerText: '"Kemenangan ini adalah buah kerja keras seluruh tim dan taktik hebat dari pelatih, bukan cuma saya."',
            publicTrustDelta: 10,
            pressureDelta: -6,
            happinessDelta: 4,
            relationshipDelta: 8,
            mediaGrade: 'A',
            fanReaction: '💬 Publik kagum pada kerendahan hatimu setelah tampil memukau!',
            teamReaction: '💬 Rekan satu tim semakin menyukaimu karena membagi kredit kemenangan.',
          ),
          PressOption(
            label: '🔥 Percaya Diri / Agresif (Aggressive)',
            styleName: 'Agresif',
            answerText: '"Saya sudah tahu bakal cetak gol dan menguasai laga sejak menit pertama."',
            publicTrustDelta: -5,
            pressureDelta: 8,
            happinessDelta: 6,
            relationshipDelta: -5,
            mediaGrade: 'C',
            fanReaction: '💬 Beberapa kritikus menyebutmu agak arogan.',
            teamReaction: '💬 Rekan tim merasa kamu terlalu menonjolkan diri sendiri.',
          ),
          PressOption(
            label: '🎭 Diplomatis / Netral (Diplomatic)',
            styleName: 'Diplomatis',
            answerText: '"Kami menjalankan instruksi taktik dengan disiplin dan hasil positif mengikuti."',
            publicTrustDelta: 4,
            pressureDelta: -2,
            happinessDelta: 2,
            relationshipDelta: 3,
            mediaGrade: 'B',
            fanReaction: '💬 Media menilai jawabanmu sangat profesional.',
            teamReaction: '💬 Suasana ruang ganti tetap terjaga kondusif.',
          ),
        ],
      ),

      // 3. Konferensi Transfer / Bursa Transfer
      PressEvent(
        id: 'transfer_rumors',
        title: 'Konferensi Pers Spekulasi Transfer 💼🔄',
        category: 'Transfer',
        question: 'Wartawan: "Beredar rumor beberapa klub raksasa tertarik merekrutmu. Apakah kamu berencana hengkang dari klub saat ini?"',
        options: [
          PressOption(
            label: '🙏 Rendah Hati (Humble)',
            styleName: 'Rendah Hati',
            answerText: '"Saya sangat bahagia di klub ini dan fokus memberikan yang terbaik selama masih terikat kontrak."',
            publicTrustDelta: 9,
            pressureDelta: -4,
            happinessDelta: 2,
            relationshipDelta: 7,
            mediaGrade: 'A',
            fanReaction: '💬 Suporter klub bersorak gembira atas loyalitasmu!',
            teamReaction: '💬 Manajemen klub merasa dihargai oleh konfirmasimu.',
          ),
          PressOption(
            label: '🔥 Percaya Diri / Agresif (Aggressive)',
            styleName: 'Agresif',
            answerText: '"Setiap pemain hebat selalu menginginkan panggung yang lebih besar dan tantangan baru."',
            publicTrustDelta: -8,
            pressureDelta: 12,
            happinessDelta: 3,
            relationshipDelta: -6,
            mediaGrade: 'B',
            fanReaction: '💬 Fans mengecam pernyataanmu di medsos sebagai sinyal hengkang!',
            teamReaction: '💬 Hubungan dengan pelatih sedikit merenggang.',
          ),
          PressOption(
            label: '🎭 Diplomatis / Netral (Diplomatic)',
            styleName: 'Diplomatis',
            answerText: '"Urusan masa depan dan kontrak ada di tangan agen serta manajemen klub."',
            publicTrustDelta: 2,
            pressureDelta: 2,
            happinessDelta: 0,
            relationshipDelta: 0,
            mediaGrade: 'B',
            fanReaction: '💬 Fans masih diliputi tanda tanya mengenai masa depanmu.',
            teamReaction: '💬 Manajemen bersiap mengantisipasi langkah agenmu.',
          ),
        ],
      ),

      // 4. Konferensi Krisis / Skandal
      PressEvent(
        id: 'crisis_scandal',
        title: 'Konferensi Pers Klarifikasi Isu 🎙️⚠️',
        category: 'Krisis / Skandal',
        question: 'Wartawan: "Beredar foto dirimu berpesta hingga larut malam sebelum laga penting. Bagaimana tanggapanmu?"',
        options: [
          PressOption(
            label: '🙏 Rendah Hati (Humble)',
            styleName: 'Rendah Hati',
            answerText: '"Saya meminta maaf yang sebesar-besarnya kepada klub, pelatih, dan fans atas kecerobohan saya."',
            publicTrustDelta: 6,
            pressureDelta: -5,
            happinessDelta: -3,
            relationshipDelta: 5,
            mediaGrade: 'A',
            fanReaction: '💬 Permintaan maaf yang tulus diapresiasi oleh sebagian besar publik.',
            teamReaction: '💬 Pelatih menghargai kejujuran dan sikap ksatria kamu.',
          ),
          PressOption(
            label: '🔥 Percaya Diri / Agresif (Aggressive)',
            styleName: 'Agresif',
            answerText: '"Kehidupan pribadi saya di luar lapangan bukan urusan media atau siapapun!"',
            publicTrustDelta: -12,
            pressureDelta: 15,
            happinessDelta: 2,
            relationshipDelta: -10,
            mediaGrade: 'D',
            fanReaction: '💬 Gelombang protes dan kritik pedas melanda akun sosial mediamu!',
            teamReaction: '💬 Pelatih memberi teguran keras di internal tim.',
          ),
          PressOption(
            label: '🎭 Diplomatis / Netral (Diplomatic)',
            styleName: 'Diplomatis',
            answerText: '"Foto tersebut diambil di waktu luang dan tidak mengganggu fokus profesional saya dalam bertanding."',
            publicTrustDelta: 1,
            pressureDelta: 4,
            happinessDelta: 0,
            relationshipDelta: -2,
            mediaGrade: 'C',
            fanReaction: '💬 Fans terbelah antara pro dan kontra.',
            teamReaction: '💬 Tim mengimbau agar tetap menjaga fokus pada laga mendatang.',
          ),
        ],
      ),
    ];
  }
}
