// lib/utils/country_helper.dart

class CountryHelper {
  static const Map<String, String> _countryIsoMap = {
    "afganistan": "AF",
    "afrika selatan": "ZA",
    "albania": "AL",
    "aljazair": "DZ",
    "amerika serikat": "US",
    "andorra": "AD",
    "angola": "AO",
    "antigua dan barbuda": "AG",
    "arab saudi": "SA",
    "argentina": "AR",
    "armenia": "AM",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahama": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belanda": "NL",
    "belarus": "BY",
    "belgia": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bermuda": "BM",
    "bhutan": "BT",
    "bolivia": "BO",
    "bosnia dan hercegovina": "BA",
    "botswana": "BW",
    "brazil": "BR",
    "brunei": "BN",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "ceko": "CZ",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "costa rica": "CR",
    "curacao": "CW",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominika": "DM",
    "ekuador": "EC",
    "el salvador": "SV",
    "eritrea": "ER",
    "estonia": "EE",
    "eswatini": "SZ",
    "ethiopia": "ET",
    "fiji": "FJ",
    "filipina": "PH",
    "finlandia": "FI",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "ghana": "GH",
    "gibraltar": "GI",
    "greenland": "GL",
    "grenada": "GD",
    "guam": "GU",
    "guatemala": "GT",
    "guiana prancis": "GF",
    "guinea": "GN",
    "guinea bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "honduras": "HN",
    "hong kong": "HK",
    "hungaria": "HU",
    "india": "IN",
    "indonesia": "ID",
    "inggris": "GB",
    "irak": "IQ",
    "iran": "IR",
    "irlandia": "IE",
    "islandia": "IS",
    "israel": "IL",
    "italia": "IT",
    "jamaika": "JM",
    "jepang": "JP",
    "jerman": "DE",
    "kamboja": "KH",
    "kamerun": "CM",
    "kanada": "CA",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kepulauan faroe": "FO",
    "kirgizstan": "KG",
    "kiribati": "KI",
    "kolombia": "CO",
    "komoro": "KM",
    "kongo": "CG",
    "korea selatan": "KR",
    "korea utara": "KP",
    "kosovo": "XK",
    "kroasia": "HR",
    "kuba": "CU",
    "kuwait": "KW",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luksemburg": "LU",
    "madagaskar": "MG",
    "makau": "MO",
    "makedonia utara": "MK",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "maroko": "MA",
    "marshall": "MH",
    "mauritania": "MR",
    "mauritius": "MU",
    "meksiko": "MX",
    "mesir": "EG",
    "mikronesia": "FM",
    "moldova": "MD",
    "monako": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "mozambik": "MZ",
    "myanmar": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "niger": "NE",
    "nigeria": "NG",
    "nikaragua": "NI",
    "norwegia": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "palestina": "PS",
    "panama": "PA",
    "pantai gading": "CI",
    "papua nugini": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "polandia": "PL",
    "portugal": "PT",
    "prancis": "FR",
    "puerto rico": "PR",
    "qatar": "QA",
    "republik afrika tengah": "CF",
    "republik demokratik kongo": "CD",
    "republik dominika": "DO",
    "republik rumania": "RO",
    "republik serbia": "RS",
    "republik sudan": "SD",
    "republik tanzania": "TZ",
    "republik timor leste": "TL",
    "republik uganda": "UG",
    "republik zambia": "ZM",
    "republik zimbabwe": "ZW",
    "rusia": "RU",
    "rwanda": "RW",
    "saint kitts dan nevis": "KN",
    "saint lucia": "LC",
    "saint vincent dan grenadine": "VC",
    "samoa": "WS",
    "samoa amerika": "AS",
    "san marino": "SM",
    "sao tome dan principe": "ST",
    "selandia baru": "NZ",
    "senegal": "SN",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapura": "SG",
    "siprus": "CY",
    "slovenia": "SI",
    "slowakia": "SK",
    "somalia": "SO",
    "spanyol": "ES",
    "sri lanka": "LK",
    "sudan selatan": "SS",
    "suriah": "SY",
    "suriname": "SR",
    "swedia": "SE",
    "swiss": "CH",
    "tahiti": "PF",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanjung verde": "CV",
    "thailand": "TH",
    "togo": "TG",
    "tonga": "TO",
    "trinidad dan tobago": "TT",
    "tunisia": "TN",
    "turki": "TR",
    "turkmenistan": "TM",
    "tuvalu": "TV",
    "ukraina": "UA",
    "uni emirat arab": "AE",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "vatikan": "VA",
    "venezuela": "VE",
    "vietnam": "VN",
    "yaman": "YE",
    "yordania": "JO",
    "yunani": "GR"
  };

  /// Mendapatkan kode ISO 2-huruf dari nama negara (misal "Filipina" -> "PH")
  static String getIsoCode(String? countryName) {
    if (countryName == null || countryName.trim().isEmpty) return '';
    String cleanName = countryName.trim().toLowerCase();
    
    // Jika formatnya "Kota, Negara", ambil nama negara setelah koma
    if (cleanName.contains(',')) {
      cleanName = cleanName.split(',').last.trim();
    }
    
    if (_countryIsoMap.containsKey(cleanName)) {
      return _countryIsoMap[cleanName]!;
    }
    
    // Pencarian substring jika tidak pas persis
    for (var entry in _countryIsoMap.entries) {
      if (cleanName.contains(entry.key) || entry.key.contains(cleanName)) {
        return entry.value;
      }
    }
    return '';
  }

  /// Mendapatkan emoji bendera negara berdasarkan nama negara (misal "Filipina" -> "🇵🇭")
  static String getFlagEmoji(String? countryName) {
    final String iso = getIsoCode(countryName);
    if (iso.length != 2) return '';
    int firstChar = iso.toUpperCase().codeUnitAt(0) - 0x41 + 0x1F1E6;
    int secondChar = iso.toUpperCase().codeUnitAt(1) - 0x41 + 0x1F1E6;
    return String.fromCharCode(firstChar) + String.fromCharCode(secondChar);
  }
}
