// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/ajak_diskusi/ajak_diskusi_dialog_user.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class AjakDiskusiDialogUser {
  /// Mengembalikan list 100 variasi dialog User (Orang Tua) saat mengajak anak berdiskusi
  static List<String> getUserDialogues({
    required String childName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Ayo anak mungil $childName, $parentName mau ngobrol dan mendengarkan celoteh manismu! 💬👶',
        'Sini sayang, mari kita bicara tentang hewan-hewan lucu dan warna-warni di buku cerita ini!',
        'Anak bayi kesayangan $parentName, yuk mengoceh bareng $parentName tentang harimu!',
        'Dengarkan suara $parentName ya sayang, $parentName ingin kamu belajar mengenal banyak kata baru!',
        'Ulian bahagianya menatap matamu saat $parentName mengajakkan obrolan hangat!',
        'Ini percakapan komunikasi awal kita ya nak, biar kamu tumbuh jadi anak yang komunikatif.',
        'Sini anak pinter $childName, tunjukkan pada $parentName mainan mana yang paling kamu sukai!',
        'Nih $parentName ajak berdiskusi lewat dongeng sebelum tidur yang penuh dengan pesan kebaikan.',
        'Mendengarkan ocehan manismu merespon kata-kata $parentName adalah hiburan paling menenangkan.',
        'Ini momen interaksi verbal pertama antara $parentName dan buah hati tercinta.',
        'Bicaralah sesukamu ya sayang, $parentName akan selalu menyimak setiap ocehan manismu.',
        'Nih $parentName tanyakan: mau minum susu hangat atau mau jalan-jalan sore di taman?',
        'Anak bayi $parentName diajak berdiskusi! Semoga tumbuh kembang bicaramu makin pesat ya nak.',
        'Pegang telunjuk $parentName ya saat kita saling mengobrol dan tersenyum bersama.',
        'Setiap kata yang $parentName ucapkan dirancang untuk menstimulasi pendengaran dan kecerdasanmu.',
        'Aduh lucunya ekspresi seriusmu seolah-olah mengerti seluruh perkataan $parentName!',
        'Ini buat melatih kepekaan emosional dan bahasa anak kesayangan $parentName.',
        'Nanti kita lanjut mengobrol lagi ya nak, $parentName senang sekali bicara bersamamu!',
        'Teruslah mengoceh riang buah hatiku, kebahagiaan komunikasi ini adalah anugerah indah.',
        'Ini momen obrolan penuh rasa cinta dari $parentName khusus untuk anak kesayangan.',
        'Tangan mungilmu yang menunjuk-nunjuk objek membuat percakapan kita makin seru!',
        'Semoga diskusi awal ini memberikan rasa percaya diri bagi kemampuan bicaramu di masa depan.',
        'Nanti kalau kamu sudah bisa bicara lancar, pasti obrolan kita bakal makin ramai ya nak!',
        'Kasih sayang dan komunikasi ini tulus dari hati $parentName untuk anak tercinta.',
        'Semoga interaksi manis ini membawa kehangatan dan keceriaan di rumah kita!',
      ];
    } else if (childAge <= 5) {
      return [
        'Ayo $childName, $parentName mau ajak kamu berdiskusi tentang cita-cita & aturan di rumah! 🗣️✨',
        'Mari kita duduk bersama sayang, menurut $childName apa yang membuat harimu bahagia hari ini?',
        'Sini nak, $parentName ingin dengar pendapatmu tentang kegiatan sekolah TK dan teman-teman barumu!',
        'Nih $parentName ajak kamu bermusyawarah: weekend nanti kita mau liburan ke mana?',
        'Anak rajin $childName, ayo kita sepakati bersama jadwal main HP dan jam merapikan mainan ya!',
        'Mari berdiskusi dengan santun sayang, $parentName selalu ingin mendengar apa yang kamu rasakan.',
        'Nih $parentName tanya pendapatmu: baju warna apa yang paling cocok kamu pakai esok hari?',
        'Senang ya kalau diajak ngobrol seperti anak gede? $parentName bangga dengan kecerdasan bicaramu.',
        'Sampaikan keinginanmu dengan jujur dan baik ya nak, $parentName akan selalu mendengarkan.',
        'Nih kita bahas tentang pentingnya berbagi mainan dan berkata jujur kepada sesama!',
        'Ini diskusi harian untuk anak tercantik/tertampan kesayangan $parentName!',
        'Berbicaralah dengan berani dan santun ya nak! Aspirasimu sangat berharga buat $parentName.',
        'Semoga diskusi ini membuatmu belajar memahami aturan dan melatih cara berpikirmu!',
        'Nih anak baik! $parentName ingin tahu apa impian terbesarmu kalau sudah besar nanti.',
        'Ceritakan pada $parentName jika ada hal yang membuatmu bingung atau takut di sekolah ya sayang.',
        'Ini ruang dialog yang aman dari $parentName untuk buah hati kesayangan. Mari kita bicara!',
        'Lihat betapa pentingnya saling mendengarkan dalam keluarga kita! $parentName sangat membanggakanmu.',
        'Berpendapatlah dengan bebas ya anak pinter! $parentName akan membimbingmu dengan kasih sayang.',
        'Semoga kamu tumbuh menjadi pribadi yang komunikatif, bijaksana, dan santun!',
        'Nih dengarkan nasihat dan pandangan $parentName, lalu beritahu $parentName bagaimana pendapatmu!',
        'Ingat pesan $parentName, setiap masalah bisa kita selesaikan baik-baik lewat bicara jujur.',
        'Diskusi ini bentuk kebanggaan dan kasih sayang tulus $parentName untuk anak penurut.',
        'Ayo kita buat kesepakatan bersama yang adil dan menyenangkan buat kita berdua ya $childName!',
        'Ayo tersenyum gembira! Obrolan berkualitas bersama orang tua adalah momen terbaik harimu!',
        'Semoga hasil diskusi kita hari ini membawa keceriaan dan kedisiplinan yang baik!',
      ];
    } else if (childAge <= 11) {
      return [
        'Ayo $childName, saatnya kita berdiskusi tentang target sekolah, hobi, & aturan di rumah! 🗣️📚✨',
        'Nih $parentName ingin mendengar pandanganmu mengenai manajemen waktu belajar dan bermainmu.',
        'Mari kita bicarakan bersama kendala apa yang sedang kamu hadapi di sekolah maupun lingkungan teman.',
        'Ini kesempatan bagimu untuk menyampaikan ide dan aspirasi mengenai kegiatan keluarga kita.',
        'Duduklah bersama $parentName, mari kita cari solusi terbaik untuk masalah yang sedang kamu pikirkan.',
        'Nih momen diskusi berkualitas buat anak kesayangan $parentName! Sampaikan pendapatmu secara terbuka.',
        'Selalu gunakan etika berdiskusi yang santun dan jujur saat menyampaikan pemikiranmu ya sayang.',
        'Semoga ruang dialog ini melatihmu menjadi sosok yang berpikir kritis, dewasa, dan solutif.',
        'Ini wujud keterbukaan $parentName agar kamu merasa dihargai sebagai anggota keluarga yang setara.',
        'Nih pembicaraan penting buat $childName! Belajarlah mengambil keputusan dengan penuh tanggung jawab.',
        'Kamu sudah makin berkembang dan berwawasan luas. $parentName sangat bangga diajak berdiskusi olehmu.',
        'Mari kita buat kesepakatan bersama mengenai kedisiplinan dan penggunaan teknologi di rumah.',
        'Nih ruang konsultasi dari $parentName! Jangan pernah ragu cerita jika ada hal yang mengganggu pikiranmu.',
        'Sampaikan argumenmu dengan tenang dan logis ya $childName sayang, $parentName menyimak sepenuhnya.',
        'Ini bentuk penghormatan dan rasa sayang $parentName atas kedewasaan yang mulai kamu tunjukkan.',
        'Jangan lupa bahwa setiap kesepakatan dalam diskusi ini harus kita jalankan bersama dengan konsisten ya!',
        'Simpan nasihat dan hasil diskusi ini di dalam hatimu ya! $parentName selalu mendoakan keberhasilanmu.',
        'Nih terbuka pintu diskusi sama $parentName. Kalau ada cita-cita atau hobi baru, mari kita bahas bersama!',
        'Jadilah anak yang bijak dan selalu siap mendengar sudut pandang orang lain ya sayang.',
        'Semoga dengan percakapan ini kamu makin percaya diri dan merasa didukung sepenuhnya oleh keluarga!',
        'Ini waktu khusus $parentName alokasikan untuk bertukar pikiran dan mempererat keakraban kita.',
        'Nih evaluasi dan diskusi bersama! Mari kita tingkatkan kebiasaan baik di dalam keluarga.',
        'Setiap masukan positif darimu sangat berharga bagi keharmonisan rumah tangga kita.',
        'Sampaikan pesan dan harapanmu pada $parentName ya $childName, $parentName sangat mencintaimu.',
        'Nih diskusi sukses! Selamat melangkah dengan rencana baru yang sudah kita sepakati bersama!',
      ];
    } else {
      return [
        'Ayo $childName, mari kita berdiskusi secara dewasa mengenai masa depan, karir, & kehidupan! 🗣️💡✨',
        'Nih $parentName ajak tukar pikiran tentang langkah-langkah strategis yang akan kamu tempuh.',
        'Sampaikan pandangan hidup dan aspirasimu secara jujur dan transparan pada $parentName ya $childName.',
        'Ini momen berharga bagi kita untuk saling memahami kebutuhan dan harapan satu sama lain.',
        'Di usiamu yang sudah dewasa ini, pandangan dan keputusanmu sangat $parentName hormati.',
        'Nih ruang konsultasi & pertukaran ide khusus dari $parentName. Mari kita cari solusi terbaik.',
        'Selalu kedepankan kebijaksanaan, fakta, dan etika saat berdiskusi tentang hal-hal besar ya $childName.',
        'Semoga diskusi mendalam ini memberimu keteguhan hati dan arah yang jelas dalam melangkah.',
        'Ini bentuk kemitraan emosional antara orang tua dan anak untuk saling menguatkan dalam hidup.',
        'Mari kita bahas mengenai pengelolaan finansial, prinsip moral, dan rencana jangka panjangmu.',
        'Nih waktu berkualitas bersama keluarga. Semoga komunikasi yang lancar ini membawa keberkahan.',
        'Selalu ingat bahwa pertimbangan dari orang tua berasal dari kasih sayang dan pengalaman hidup yang tulus.',
        'Kepercayaan dan kemandirianmu saat ini adalah buah dari ruang dialog sehat yang selalu kita jaga.',
        'Semoga dengan keterbukaan ini, tidak ada sekat atau kesalahpahaman yang mengganjal di antara kita.',
        'Nih simpan kesepakatan diskusi ini sebagai peta penuntun perjalanan kedewasaanmu ya $childName.',
        'Kasih sayang dan bimbingan $parentName selalu menyertai setiap keputusan baik yang kamu ambil.',
        'Gunakan kesempatan diskusi ini untuk memperluas cara pandang dan mematangkan mentalitasmu.',
        'Nih dialog hangat dari $parentName! Tetaplah menjadi pribadi yang rendah hati dan mau mendengar.',
        'Semoga kedamaian dan keharmonisan selalu menyertai keluarga kita melalui komunikasi yang sejuk.',
        'Jadilah sosok pemimpin yang bijak dan berwawasan luas. Ini ruang diskusi dari $parentName untukmu.',
        'Nih buat penyegaran pikiran dan pemantapan langkahmu! $parentName selalu bangga mendampingimu.',
        'Terima kasih telah bersikap terbuka dan mau berdiskusi secara jujur bersama $parentName.',
        'Semoga kebersamaan dalam berdiskusi ini menjadi kenangan manis yang terus mempererat batin kita.',
        'Nih restu dan masukan terbaik dari $parentName! Doa $parentName selalu menyertai perjuanganmu.',
        'Manfaatkan hasil diskusi ini sebaik-baiknya ya nak. $parentName sangat mencintai dan membanggakanmu!',
      ];
    }
  }
}
