// lib/game/widgets/hubungan_menu/action_menu/child_action_dialogue/ajak_diskusi/ajak_diskusi_dialog_npc.dart
import 'package:mylifesim/avatar/vn_character_view.dart';
import 'package:mylifesim/game/widgets/vn_dialogue/vn_dialogue_models.dart';

class AjakDiskusiDialogNpc {
  /// Mengembalikan list 100 variasi respon NPC saat diajak diskusi berdasarkan usia
  static List<String> getNPCDialogues({
    required String npcName,
    required int childAge,
    required String parentName,
  }) {
    if (childAge < 3) {
      return [
        'Ooooh? ( * $npcName mendengarkan obrolan $parentName sambil mengedipkan matanya dengan bingung * ) 💬👶',
        'Bababa! ( * $npcName mengoceh balik seolah-olah sedang ikut berdiskusi hangat * )',
        'Gigaaa! ( * $npcName menunjuk-nunjuk gambar di buku sambil mengeluarkan suara ceria * )',
        'Abuuu... ( * $npcName menatap bibir $parentName yang sedang berbicara dengan fokus * )',
        'Hehehe! ( * $npcName tertawa gembira saat $parentName mengajaknya mengobrol panjang lebar * )',
        'Nyaaa! ( * $npcName memegang pipi $parentName seolah mau merespon ucapan * )',
        'Mammm! ( * $npcName mengangguk-anggukkan kepalanya dengan imut * )',
        'Dayaya! ( * $npcName menepuk-nepuk tangannya seolah setuju dengan obrolan $parentName * )',
        'Tetete! ( * $npcName mengeluarkan suara celoteh bayi yang sangat menggemaskan * )',
        'Kicukicu! ( * $npcName memberikan senyuman manis di tengah percakapan * )',
        'Ehhhe! ( * $npcName menunjuk objek di ruangan yang sedang dibicarakan $parentName * )',
        'Agiii! ( * $npcName mengibar-ngibarkan tangannya gembira diajak bicara * )',
        'Owooo! ( * $npcName membelalakkan matanya kagum mendengarkan cerita $parentName * )',
        'Bubu! ( * $npcName mendusel nyaman sambil mendengarkan nada suara sejuk $parentName * )',
        'Lalala! ( * $npcName menirukan bunyi kata-kata sederhana yang diucapkan $parentName * )',
        'Hummm! ( * $npcName mengerutkan dahi kecilnya seolah berpikir keras * )',
        'Cicu! ( * $npcName menyodorkan mainan untuk diperhatikan oleh $parentName * )',
        'Nyaa-ha! ( * $npcName tertawa geli saat nada bicara $parentName melucu * )',
        'Paapapa! ( * $npcName memegang telunjuk $parentName sambil terus menyimak * )',
        'Glooogloo! ( * $npcName mengoyak-goyangkan kakinya gembira diajak komunikasi * )',
        'Oowgh! ( * $npcName menguap pelan tapi tetap mempertahankan tatapan matanya * )',
        'Yaaaya! ( * $npcName tersenyum bahagia diajak mengobrol seperti orang gede * )',
        'Wiii! ( * $npcName mengayunkan tangannya seolah ingin bertanya sesuatu * )',
        'Tatatata! ( * $npcName memeluk boneka sambil mendengarkan dongeng/cerita * )',
        'Ceriaaa! ( * $npcName mengoceh tanpa henti merespon arahan dari $parentName * )',
      ];
    } else if (childAge <= 5) {
      return [
        'Wah, diskusi! Menurut aku $parentName, warna langit itu biru karena ada awan putihnya! ☁️🗣️✨',
        'Aku setuju sama $parentName! Nanti di TK aku mau jadi anak yang paling rajin!',
        'Kenapa burung bisa terbang tapi aku nggak bisa $parentName? Ceritain dong!',
        'Aku mau cita-cita jadi dokter / polisi / astronot nanti kalau udah gede $parentName!',
        'Hehehe, pendapat aku sih es krim rasa cokelat lebih enak dari rasa vanilla $parentName!',
        'Kenapa kita harus makan sayur $parentName? Biar badan aku jadi kuat kaya pahlawan super ya?',
        'Aku senang banget diajak ngobrol serius sama $parentName! Berasa udah gede!',
        'Nanti kalau kita pergi liburan, aku mau pilih tempat yang ada tamannya ya $parentName!',
        'Kenapa matahari kalau malam hari hilang $parentName? Dia pergi bobo juga ya?',
        'Makasih $parentName udah mau dengerin cerita dan pendapat lucu aku!',
        'Aku janji bakal nurut sama nasihat dan hasil diskusi kita hari ini $parentName!',
        'Kalau menurut $parentName mainan aku harus dirapikan jam berapa? Aku mau ikut aturan!',
        'Uwah, penjelasan $parentName pinter banget! Aku jadi makin tahu banyak hal!',
        'Nanti malam kita lanjut diskusi tentang cerita hewan/dinosaurus lagi ya $parentName!',
        'Aku suka kalau $parentName nanya pendapat aku dulu sebelum beli barang!',
        'Asyik! Suara $parentName waktu ngobrol sejuk banget di telingaku.',
        'Kenapa orang dewasa harus kerja $parentName? Biar bisa beli susu sama mainan ya?',
        'Aku mau belajar menulis nama aku sendiri besok $parentName! Biar makin pinter!',
        'Makasih $parentName! Diskusi ini bikin aku makin sayang sama $parentName!',
        'Boleh nggak aku cerita tentang teman baruku di sekolah tadi $parentName?',
        'Yeay! $parentName mendengarkan aku dengan penuh perhatian! Makasih ya!',
        'Aku janji nggak bakal nakal lagi sesuai kesepakatan diskusi kita $parentName!',
        'Nanti kalau aku ada bingung, aku boleh nanya-nanya lagi kan $parentName?',
        'Hore! Obrolan sama $parentName selalu seru dan membahagiakan!',
      ];
    } else if (childAge <= 11) {
      return [
        'Menurut saya $parentName, soal masalah sekolah ini solusi terbaiknya adalah mengatur jadwal belajar lebih ketat. 🗣️📚✨',
        'Terima kasih $parentName sudah mengajak saya berdiskusi dan menghargai sudut pandang saya.',
        'Saya setuju dengan pandangan $parentName. Nasihat ini sangat masuk akal untuk kebaikan saya.',
        'Mengenai cita-cita dan hobi saya, saya ingin fokus memperdalam bakat di bidang ini $parentName.',
        'Terima kasih $parentName sudah terbuka mengajak pembicaraan tentang aturan dan kedisiplinan rumah.',
        'Saya paham kekhawatiran $parentName. Saya janji akan lebih bijak membagi waktu antara game dan belajar.',
        'Bagaimana kalau kita buat kesepakatan bersama mengenai jam penggunaan gadget $parentName?',
        'Diskusi ini bikin saya merasa dipahami dan dewasa. Terima kasih banyak ya $parentName.',
        'Mengenai rencana liburan/kegiatan sekolah, saya sangat mendukung ide dari $parentName.',
        'Saya ingin cerita sedikit tentang kendala yang saya hadapi di sekolah $parentName... Mohon sarannya.',
        'Terima kasih $parentName sudah menjadi pendengar yang baik dan pembimbing yang bijaksana.',
        'Saya akan menjalankan keputusan hasil diskusi kita hari ini dengan penuh rasa tanggung jawab.',
        'Senang sekali rasanya saat pendapat saya dipertimbangkan dalam keputusan keluarga kita.',
        'Terima kasih $parentName sudah mengajari saya cara berpikir kritis dan berkomunikasi dengan santun.',
        'Saya setuju $parentName, kejujuran dan kerja keras adalah prinsip utama yang harus saya pegang.',
        'Mengenai masalah teman di sekolah, saran dari $parentName sangat membantu saya mengambil sikap.',
        'Terima kasih $parentName! Obrolan berkualitas seperti ini bikin hubungan kita makin erat.',
        'Saya berjanji akan terus terbuka dan jujur menceritakan setiap perkembangan saya pada $parentName.',
        'Pendapat $parentName selalu menjadi sudut pandang terbaik yang saya jadikan teladan.',
        'Ayo kita jadwalkan diskusi keluarga seperti ini secara rutin ya $parentName!',
        'Terima kasih $parentName atas kepercayaan dan ruang diskusi yang sehat ini.',
        'Saya merasa sangat beruntung punya orang tua yang mau diajak tukar pikiran secara demokratis.',
        'Hasil diskusi ini memberikan kejelasan dan ketenangan pikiran buat saya.',
        'Terima kasih $parentName! Nasihat bijak $parentName akan selalu saya ingat.',
        'Saya siap melangkah sesuai dengan keputusan terbaik yang kita sepakati bersama!',
      ];
    } else {
      return [
        'Terima kasih banyak $parentName atas ajakan diskusinya. Sudut pandang & pengalaman $parentName sangat mencerahkan. 🗣️💡✨',
        'Mengenai arah karir dan rencana pendidikan masa depan saya, masukan dari $parentName sangat berharga.',
        'Saya sangat menghargai cara $parentName memperlakukan saya sebagai sosok yang dewasa dalam berdiskusi.',
        'Tukar pikiran seperti ini benar-benar membuka wawasan saya dalam menghadapi dinamika kehidupan.',
        'Terima kasih $parentName sudah bersedia mendengarkan aspirasi dan pandangan hidup saya secara terbuka.',
        'Mengenai masalah keuangan/manajemen waktu, saran dari $parentName akan langsung saya terapkan.',
        'Saya paham betul kekhawatiran dan harapan $parentName. Mari kita cari jalan tengah terbaik bersama.',
        'Komunikasi yang transparan seperti ini membuat ikatan batin keluarga kita semakin kokoh.',
        'Terima kasih $parentName atas bimbingan dan kepercayaannya. Saya akan menjaga amanah ini sebaik-baiknya.',
        'Mengenai prinsip moral dan etika hidup, nasihat $parentName adalah kompas penuntun utama saya.',
        'Saya bersyukur memiliki orang tua yang bisa diajak berdiskusi tentang hal-hal strategis dan mendalam.',
        'Hasil kesepakatan diskusi kita hari ini memberikan arah langkah yang sangat jelas bagi saya.',
        'Terima kasih $parentName telah memberikan ruang bagi saya untuk mengekspresikan pemikiran dan ide.',
        'Saya percaya dengan kolaborasi dan komunikasi yang baik, setiap masalah keluarga bisa kita selesaikan.',
        'Diskusi ini menegaskan kembali betapa pentingnya peran dan kebijaksanaan $parentName dalam hidup saya.',
        'Mengenai rencana jangka panjang saya, masukan $parentName memberikan rasa aman dan percaya diri.',
        'Terima kasih $parentName sudah selalu objektif dan bijaksana dalam menanggapi setiap argumen saya.',
        'Obrolan mendalam ini menjadi fondasi kuat bagi kedewasaan mental dan emosional saya.',
        'Saya berjanji akan melaksanakan komitmen dari hasil diskusi ini dengan penuh rasa tanggung jawab.',
        'Terima kasih $parentName! Ruang dialog yang hangat ini adalah karunia indah dalam keluarga kita.',
        'Sudut pandang $parentName selalu kaya akan kearifan hidup yang tak bisa saya dapatkan dari tempat lain.',
        'Saya siap melangkah dengan lebih mantap berkat restu dan hasil diskusi kita bersama.',
        'Terima kasih $parentName atas waktu dan perhatiannya yang begitu luar biasa.',
        'Kebijaksanaan $parentName adalah inspirasi terbesar saya untuk menjadi manusia yang bermanfaat.',
        'Terima kasih $parentName! I love you so much $parentName!',
      ];
    }
  }
}
