import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPgsdKarakterWargaNegaraQuestions() {
  return const [
    QuestionItem(
      id: 'pgsd_kwn_001',
      questionText: 'Manakah nilai dasar civic education yang paling mendasari penghargaan terhadap perbedaan latar belakang, pandangan, dan identitas orang lain?',
      options: ['Toleransi & Penghargaan atas Keberagaman', 'Kepatuhan Buta', 'Etnosentrisme', 'Individualisme Ekstrem'],
      correctOptionIndex: 0,
      explanation: 'Toleransi mendasari hidup berdampingan secara damai dalam masyarakat global yang majemuk.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_002',
      questionText: 'Pengembangan kesadaran warga negara dunia (Global Citizenship Education) bertujuan untuk:',
      options: ['Membentuk individu yang peduli isu-isu global seperti perdamaian, HAM, dan kelestarian lingkungan', 'Menghapus identitas kebangsaan lokal', 'Menguasai perdagangan internasional secara sepihak', 'Menyeragamkan bahasa dunia'],
      correctOptionIndex: 0,
      explanation: 'Global Citizenship membekali individu pemahaman tanggung jawab universal melintasi batas negara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_003',
      questionText: 'Sikap tanggung jawab sosial warga negara terhadap fasilitas publik dan lingkungan bersama tercermin dari tindakan:',
      options: ['Merawat, menjaga kebersihan, dan tidak merusak fasilitas umum', 'Memanfaatkannya hanya untuk kepentingan pribadi', 'Mengotori sarana umum jika tidak ada petugas', 'Menyerahkan perawatan sepenuhnya pada pemerintah'],
      correctOptionIndex: 0,
      explanation: 'Menjaga fasilitas publik adalah wujud civic responsibility paling mendasar.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_004',
      questionText: 'Prinsip persamaan di hadapan hukum (Equality before the law) menegaskan bahwa:',
      options: ['Setiap warga negara memiliki kedudukan, hak, dan kewajiban hukum yang sama tanpa diskriminasi', 'Orang kaya dibebaskan dari hukuman', 'Pejabat tidak bisa dituntut hukum', 'Hukum hanya berlaku untuk warga biasa'],
      correctOptionIndex: 0,
      explanation: 'Equality before the law menjamin keadilan bagi seluruh individu tanpa memandang status sosial.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_005',
      questionText: 'Prinsip dasar musyawarah untuk mencapai mufakat dalam pengambilan keputusan bersama mengutamakan:',
      options: ['Pencapaian kesepakatan bersama secara adil dan menghormati aspirasi semua pihak', 'Pemaksaan kehendak pihak mayoritas', 'Keputusan sepihak pimpinan rapat', 'Suara terbanyak tanpa mendengarkan pendapat lain'],
      correctOptionIndex: 0,
      explanation: 'Musyawarah mufakat mengedepankan komunikasi empati dan solusi berkeadilan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_006',
      questionText: 'Hak Asasi Manusia (HAM) bersifat universal, yang bermakna bahwa HAM:',
      options: ['Berlaku untuk semua manusia di dunia tanpa memandang suku, agama, ras, atau gender', 'Hanya berlaku di negara maju', 'Dapat dicabut sewaktu-waktu oleh penguasa', 'Hanya dimiliki oleh orang dewasa'],
      correctOptionIndex: 0,
      explanation: 'Karakteristik utama HAM adalah universalitasnya melekat sejak lahir pada tiap manusia.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_007',
      questionText: 'Kewajiban utama seorang murid di sekolah sebagai bentuk pelaksanaan karakter kewarganegaraan adalah:',
      options: ['Belajar bersungguh-sungguh, mematuhi tata tertib, dan menghormati warga sekolah', 'Datang terlambat tanpa alasan', 'Menuntut hak tanpa menjalankan tugas', 'Memilih-milih teman berdasarkan status sosial'],
      correctOptionIndex: 0,
      explanation: 'Keseimbangan antara melaksanakan kewajiban dan menerima hak adalah inti karakter kewarganegaraan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_008',
      questionText: 'Sikap cinta tanah air dan bangsa yang sehat (nasionalisme positif) ditunjukkan dengan:',
      options: ['Bangga pada budaya lokal serta berkontribusi positif bagi kemajuan masyarakat', 'Membenci bangsa dan kebudayaan asing', 'Merasa bangsa sendiri paling unggul di atas segala bangsa', 'Menutup diri dari pergaulan antarnegara'],
      correctOptionIndex: 0,
      explanation: 'Nasionalisme positif membangun negeri sendiri sambil tetap menghormati identitas bangsa lain.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_009',
      questionText: 'Perilaku gotong royong dan kerja sama dalam kehidupan sekolah memberikan manfaat berupa:',
      options: ['Mempererat tali persaudaraan dan mempermudah pencapaian tujuan bersama', 'Menimbulkan rasa persaingan yang tidak sehat', 'Memperlambat selesainya pekerjaan', 'Membuat siswa bergantung penuh pada orang lain'],
      correctOptionIndex: 0,
      explanation: 'Gotong royong membangun kohesi sosial dan karakter kolaboratif.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_010',
      questionText: 'Penerapan nilai integritas dan kejujuran pada siswa SD dalam konteks persekolahan tercermin dari:',
      options: ['Mengerjakan ujian secara mandiri tanpa mencontek', 'Mencontek jawaban teman agar nilai tinggi', 'Menyalahkan teman atas kesalahan sendiri', 'Mengubah angka nilai laporan belajar'],
      correctOptionIndex: 0,
      explanation: 'Kejujuran akademik adalah pondasi integritas moral karakter anak.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_011',
      questionText: 'Prinsip keadilan sosial bagi seluruh masyarakat berimplikasi pada pentingnya:',
      options: ['Pemerataan kesempatan belajar, perlindungan kelompok rentan, dan kepedulian sosial', 'Pemberian keistimewaan hanya pada yang mampu', 'Abaikan masyarakat miskin', 'Pusat pembangunan hanya di kota besar'],
      correctOptionIndex: 0,
      explanation: 'Keadilan sosial menjamin akses kesempatan adil bagi seluruh lapisan warga.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_012',
      questionText: 'Pentingnya pengenalan budaya anti-korupsi sejak dini di Sekolah Dasar difokuskan pada penanaman nilai:',
      options: ['Jujur, disiplin, tanggung jawab, dan sederhana', 'Mencari kekayaan dengan segala cara', 'Ketakutan pada hukuman polisi semata', 'Kepatuhan karena ancaman'],
      correctOptionIndex: 0,
      explanation: 'Nilai kejujuran dan kesederhanaan membentuk benteng moral anti-korupsi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_013',
      questionText: 'Bentuk partisipasi aktif warga sekolah dalam demokrasi tingkat dasar adalah:',
      options: ['Pemilihan ketua kelas dan pengurus OSIS secara jujur dan adil', 'Penunjukan langsung oleh wali kelas tanpa musyawarah', 'Pembatalan hasil pemilihan suara', 'Boikot kegiatan sekolah'],
      correctOptionIndex: 0,
      explanation: 'Pemilihan pengurus kelas mengajarkan praktik demokrasi partisipatif sejak dini.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_014',
      questionText: 'Pengenalan hak-hak anak sebagaimana tertuang dalam Konvensi Hak Anak PBB meliputi hak berikut, KECUALI:',
      options: ['Hak untuk dieksploitasi sebagai tenaga kerja di bawah umur', 'Hak atas kelangsungan hidup', 'Hak atas perlindungan dari kekerasan', 'Hak untuk tumbuh dan berkembang'],
      correctOptionIndex: 0,
      explanation: 'Anak dilindungi secara hukum dari eksploitasi kerja di bawah umur.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_015',
      questionText: 'Sikap empati dan kepedulian terhadap sesama warga dunia ketika terjadi bencana alam di suatu daerah diwujudkan melalui:',
      options: ['Penggalangan bantuan kemanusiaan dan doa solidaritas', 'Acuh tak acuh karena lokasi bencana jauh', 'Menyebarkan kabar bohong di media sosial', 'Menyalahkan korban bencana'],
      correctOptionIndex: 0,
      explanation: 'Solidaritas kemanusiaan melintasi batas geografis dan identitas.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_016',
      questionText: 'Pengenalan norma kesopanan dan kesusilaan kepada anak bertujuan agar mereka:',
      options: ['Mampu berperilaku santun, menghormati orang tua/guru, dan menjaga kerukunan', 'Menjadi penakut dan tidak berani mengutarakan pendapat', 'Selalu mengikuti keinginan teman balaya', 'Membedakan perlakuan berdasarkan kekayaan'],
      correctOptionIndex: 0,
      explanation: 'Norma kesopanan memandu perilaku pergaulan sosial yang beradab.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_017',
      questionText: 'Penanaman disiplin diri pada anak Sekolah Dasar paling efektif dilakukan melalui:',
      options: ['Keteladanan dari guru/orang tua serta pembiasaan rutin yang konsisten', 'Hukuman fisik yang berat', 'Ancaman verbal terus menerus', 'Pemberian hadiah uang setiap hari'],
      correctOptionIndex: 0,
      explanation: 'Keteladanan dan pembiasaan konsisten membangun disiplin internal anak.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_018',
      questionText: 'Pancasila sebagai dasar negara Indonesia mengandung 5 sila utama. Sila pertama "Ketuhanan Yang Maha Esa" menjamin:',
      options: ['Kemerdekaan tiap-tiap penduduk untuk memeluk agamanya dan beribadat menurut agamanya', 'Kewajiban memeluk satu agama resmi saja', 'Larangan beragama', 'Pemusnahan aliran kepercayaan'],
      correctOptionIndex: 0,
      explanation: 'Sila 1 menjamin kebebasan beragama dan kepercayaan bagi warga negara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_019',
      questionText: 'Sila kedua "Kemanusiaan yang Adil dan Beradab" mengajarkan bangsa Indonesia untuk:',
      options: ['Menjunjung tinggi nilai kemanusiaan, tenggang rasa, dan tidak membeda-bedakan manusia', 'Mengutamakan kepentingan kelompok sendiri', 'Melakukan penjajahan terhadap bangsa lain', 'Mengeksploitasi sumber daya tanpa etika'],
      correctOptionIndex: 0,
      explanation: 'Sila 2 menekankan perlakuan manusia secara bermartabat dan adil.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_020',
      questionText: 'Sila ketiga "Persatuan Indonesia" menempatkan keselamatan, persatuan, serta kesatuan bangsa di atas:',
      options: ['Kepentingan pribadi dan golongan', 'Kepentingan hukum', 'Kepentingan pendidikan', 'Kepentingan lingkungan'],
      correctOptionIndex: 0,
      explanation: 'Persatuan Indonesia mengutamakan integrasi nasional di atas keprihatinan egosentris.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_021',
      questionText: 'Sila keempat Pancasila dilambangkan dengan simbol:',
      options: ['Kepala Banteng', 'Bintang Gold', 'Rantai Emas', 'Padi dan Kapas'],
      correctOptionIndex: 0,
      explanation: 'Kepala Banteng melambangkan musyawarah dan berkumpulnya warga.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_022',
      questionText: 'Sila kelima Pancasila dilambangkan dengan simbol Padi dan Kapas yang bermakna keberadaan kemakmuran berupa:',
      options: ['Pangan dan Sandang bagi seluruh rakyat secara adil', 'Kekayaan emas', 'Keberhasilan industri', 'Kekuatan militer'],
      correctOptionIndex: 0,
      explanation: 'Padi (pangan) dan Kapas (sandang) adalah simbol kemakmuran dan pemenuhan kebutuhan pokok.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_023',
      questionText: 'Lambang negara Republik Indonesia adalah Burung Garuda Pancasila dengan jumlah bulu sayap sebanyak:',
      options: ['17 helai di masing-masing sayap', '8 helai', '45 helai', '19 helai'],
      correctOptionIndex: 0,
      explanation: '17 helai bulu sayap melambangkan tanggal 17 Proklamasi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_024',
      questionText: 'Jumlah bulu ekor pada Garuda Pancasila melambangkan bulan Proklamasi (Agustus) sebanyak:',
      options: ['8 helai', '17 helai', '45 helai', '12 helai'],
      correctOptionIndex: 0,
      explanation: '8 helai bulu ekor melambangkan bulan ke-8 (Agustus).',
    ),
    QuestionItem(
      id: 'pgsd_kwn_025',
      questionText: 'Jumlah bulu leher pada Garuda Pancasila melambangkan tahun Proklamasi sebanyak:',
      options: ['45 helai', '19 helai', '17 helai', '8 helai'],
      correctOptionIndex: 0,
      explanation: '45 helai bulu leher melambangkan tahun 1945.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_026',
      questionText: 'Konstitusi tertulis tertinggi negara Indonesia adalah:',
      options: ['UUD Negara Republik Indonesia Tahun 1945', 'Ketetapan MPR', 'Undang-Undang / Perppu', 'Peraturan Presiden'],
      correctOptionIndex: 0,
      explanation: 'UUD 1945 adalah hukum dasar tertulis tertinggi di Indonesia.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_027',
      questionText: 'Lembaga tinggi negara yang berwenang mengubah dan menetapkan UUD di Indonesia adalah:',
      options: ['Majelis Permusyawaratan Rakyat (MPR)', 'Dewan Perwakilan Rakyat (DPR)', 'Presiden', 'Mahkamah Agung (MA)'],
      correctOptionIndex: 0,
      explanation: 'Pasal 3 UUD 1945 menetapkan MPR berwenang mengubah dan menetapkan UUD.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_028',
      questionText: 'Lembaga legislatif di Indonesia yang berwenang membuat Undang-Undang bersama Presiden adalah:',
      options: ['Dewan Perwakilan Rakyat (DPR)', 'Mahkamah Konstitusi (MK)', 'Badan Pemeriksa Keuangan (BPK)', 'Dewan Pertimbangan Presiden'],
      correctOptionIndex: 0,
      explanation: 'DPR memegang kekuasaan membentuk Undang-Undang.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_029',
      questionText: 'Lembaga yudikatif yang berwenang menguji undang-undang terhadap UUD 1945 di Indonesia adalah:',
      options: ['Mahkamah Konstitusi (MK)', 'Mahkamah Agung (MA)', 'Komisi Yudisial (KY)', 'Kejaksaan Agung'],
      correctOptionIndex: 0,
      explanation: 'MK menguji UU terhadap konstitusi UUD 1945.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_030',
      questionText: 'Tujuan negara Indonesia sebagaimana tercantum dalam Pembukaan UUD 1945 Alinea Ke-4 KECUALI:',
      options: ['Menjajah bangsa-bangsa lain di dunia', 'Melindungi segenap bangsa Indonesia dan seluruh tumpah darah Indonesia', 'Memajukan kesejahteraan umum', 'Mencerdaskan kehidupan bangsa'],
      correctOptionIndex: 0,
      explanation: 'Penjajahan di atas dunia harus dihapuskan karena tidak sesuai kemanusiaan dan keadilan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_031',
      questionText: 'Bentuk negara Indonesia sesuai dengan Pasal 1 ayat (1) UUD 1945 adalah:',
      options: ['Negara Kesatuan yang berbentuk Republik', 'Negara Serikat / Federasi', 'Monarki Absolut', 'Kekaisaran'],
      correctOptionIndex: 0,
      explanation: 'Indonesia adalah Negara Kesatuan berbentuk Republik (NKRI).',
    ),
    QuestionItem(
      id: 'pgsd_kwn_032',
      questionText: 'Sistem pemerintahan di Indonesia di mana Presiden menjabat sebagai kepala negara sekaligus kepala pemerintahan adalah sistem:',
      options: ['Presidensial', 'Parlementer', 'Semiparlementer', 'Monarki Tradisional'],
      correctOptionIndex: 0,
      explanation: 'Indonesia menganut sistem pemerintahan presidensial.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_033',
      questionText: 'Prinsip kedaulatan di Indonesia sesuai UUD 1945 berada di tangan rakyat dan dilaksanakan menurut:',
      options: ['Undang-Undang Dasar', 'Keinginan partai politik terbesar', 'Keputusan menteri', 'Titah raja'],
      correctOptionIndex: 0,
      explanation: 'Kedaulatan berada di tangan rakyat dan dilaksanakan menurut UUD.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_034',
      questionText: 'Lagu kebangsaan Indonesia Raya diciptakan oleh komponis nasional:',
      options: ['Wage Rudolf Soepratman (W.R. Soepratman)', 'Ismail Marzuki', 'C. Simanjuntak', 'Kusbini'],
      correctOptionIndex: 0,
      explanation: 'W.R. Soepratman menciptakan lagu kebangsaan Indonesia Raya.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_035',
      questionText: 'Bahasa persatuan Indonesia sebagaimana ditegaskan dalam Sumpah Pemuda dan Pasal 36 UUD 1945 adalah:',
      options: ['Bahasa Indonesia', 'Bahasa Melayu', 'Bahasa Jawa', 'Bahasa Inggris'],
      correctOptionIndex: 0,
      explanation: 'Bahasa Indonesia adalah bahasa resmi negara dan bahasa persatuan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_036',
      questionText: 'Bendera negara Indonesia dinamakan Sang Merah Putih dengan makna simbolis warna merah berarti:',
      options: ['Keberanian', 'Kesucian', 'Kemakmuran', 'Kejujuran'],
      correctOptionIndex: 0,
      explanation: 'Warna merah melambangkan keberanian dan warna putih melambangkan kesucian.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_037',
      questionText: 'Penetapan wilayah Indonesia sebagai satu kesatuan wilayah darat, laut, dan udara secara utuh ditegaskan pertama kali melalui:',
      options: ['Deklarasi Djuanda 13 Desember 1957', 'Perjanjian Linggajati', 'KMB 1949', 'Renville'],
      correctOptionIndex: 0,
      explanation: 'Deklarasi Djuanda menyatakan laut antarpulau sebagai pemersatu wilayah NKRI.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_038',
      questionText: 'Batas laut teritorial Indonesia ditarik sejauh berapa mil laut dari garis pangkal pulau?',
      options: ['12 Mil Laut', '200 Mil Laut', '24 Mil Laut', '3 Mil Laut'],
      correctOptionIndex: 0,
      explanation: 'Laut teritorial berjarak 12 mil laut dari garis pangkal lurus.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_039',
      questionText: 'Zona Ekonomi Eksklusif (ZEE) memberikan hak berdaulat bagi Indonesia untuk mengelola sumber daya alam sejauh:',
      options: ['200 Mil Laut', '12 Mil Laut', '50 Mil Laut', '100 Mil Laut'],
      correctOptionIndex: 0,
      explanation: 'ZEE berjarak 200 mil laut dari garis pantai.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_040',
      questionText: 'Bentuk kepedulian terhadap lingkungan hidup sebagai wujud karakter kewarganegaraan dapat dilakukan dengan 3R, yaitu:',
      options: ['Reuse, Reduce, Recycle', 'Read, Write, Run', 'Remove, Refuse, Replace', 'Repair, React, Recover'],
      correctOptionIndex: 0,
      explanation: '3R (Reduce/Mengurangi, Reuse/Guna Ulang, Recycle/Daur Ulang) adalah prinsip kelestarian lingkungan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_041',
      questionText: 'Kewajiban membela negara bagi setiap warga negara di Indonesia diatur dalam UUD 1945 Pasal:',
      options: ['Pasal 27 ayat (3) dan Pasal 30 ayat (1)', 'Pasal 1 ayat (1)', 'Pasal 33 ayat (1)', 'Pasal 28A'],
      correctOptionIndex: 0,
      explanation: 'Bela negara merupakan hak sekaligus kewajiban konstitusional setiap warga negara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_042',
      questionText: 'Komponen utama dalam Sistem Pertahanan dan Keamanan Rakyat Semesta (Sishankamrata) Indonesia adalah:',
      options: ['TNI dan POLRI', 'Rakyat terlatih saja', 'Pasukan asing', 'Satpam sekolah'],
      correctOptionIndex: 0,
      explanation: 'TNI (pertahanan) dan POLRI (keamanan) merupakan komponen utama, sedangkan rakyat sebagai komponen pendukung/pendukung.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_043',
      questionText: 'Tugas utama Kepolisian Negara Republik Indonesia (POLRI) adalah:',
      options: ['Menjaga keamanan dan ketertiban masyarakat serta menegakkan hukum', 'Mempertahankan kedaulatan dari serangan militer negara asing', 'Membuat UU', 'Mengadili perkara korupsi'],
      correctOptionIndex: 0,
      explanation: 'POLRI mengemban fungsi keamanan internal dan pengayoman masyarakat.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_044',
      questionText: 'Tugas utama Tentara Nasional Indonesia (TNI) adalah:',
      options: ['Mempertahankan kedaulatan negara dan keutuhan wilayah NKRI dari ancaman militer', 'Menilang pelanggar lalu lintas', 'Mengurus pemilihan umum', 'Memungut pajak negara'],
      correctOptionIndex: 0,
      explanation: 'TNI menjaga benteng pertahanan kedaulatan negara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_045',
      questionText: 'Sikap toleransi antarumat beragama diwujudkan melalui perbuatan:',
      options: ['Menghormati tetangga yang sedang menjalankan ibadah keagamaannya', 'Melarang perayaan hari besar agama lain', 'Mengganggu ketenangan tempat ibadah orang lain', 'Memaksa orang lain berpindah agama'],
      correctOptionIndex: 0,
      explanation: 'Menghormati kebebasan ibadah agama lain menciptakan kerukunan nasional.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_046',
      questionText: 'Sikap inklusif dalam pergaulan sekolah dapat ditunjukkan dengan:',
      options: ['Menerima dan berteman dengan siapa saja tanpa membedakan kondisi fisik, suku, atau kemampuan', 'Membuat geng beranggota siswa kaya saja', 'Menjauhi teman yang berkebutuhan khusus', 'Mengejek dialek bahasa daerah teman'],
      correctOptionIndex: 0,
      explanation: 'Inklusivitas menghargai dan merangkul keunikan setiap anak.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_047',
      questionText: 'Bahaya dari penyebaran berita bohong (hoaks) dan ujaran kebencian di media sosial bagi persatuan bangsa adalah:',
      options: ['Memecah belah kerukunan dan memicu konflik sosial antarwarga', 'Mempercepat kemajuan teknologi', 'Menambah wawasan ilmiah', 'Meningkatkan rasa persaudaraan'],
      correctOptionIndex: 0,
      explanation: 'Hoaks dan hate speech merusak rasa saling percaya antar komponen bangsa.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_048',
      questionText: 'Literasi digital yang bijak bagi siswa sekolah mencakup kemampuan:',
      options: ['Saring sebelum saring (memverifikasi kebenaran informasi sebelum membagikan)', 'Membagikan semua berita tanpa dibaca', 'Menggunakan kata-kata kasar di media sosial', 'Peretasan akun orang lain'],
      correctOptionIndex: 0,
      explanation: 'Penyaringan informasi secara kritis mencegah penyebaran disinformasi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_049',
      questionText: 'Prinsip akuntabilitas dalam kepemimpinan sekolah berarti pimpinan/guru harus:',
      options: ['Dapat mempertanggungjawabkan setiap kebijakan dan penggunaan dana secara transparan', 'Menyembunyikan laporan keuangan', 'Mengambil keputusan sembunyi-sembunyi', 'Menolak dikritik oleh wali murid'],
      correctOptionIndex: 0,
      explanation: 'Akuntabilitas menjamin transparansi dan tanggung jawab kepemimpinan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_050',
      questionText: 'Tokoh pendidikan nasional Indonesia pendiri Taman Siswa yang menetapkan semboyan "Tut Wuri Handayani" adalah:',
      options: ['Ki Hajar Dewantara', 'Dr. Soetomo', 'R.A. Kartini', 'K.H. Ahmad Dahlan'],
      correctOptionIndex: 0,
      explanation: 'Ki Hajar Dewantara adalah Bapak Pendidikan Nasional Indonesia.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_051',
      questionText: 'Makna dari bagian semboyan pendidikan "Ing Ngarsa Sung Tuladha" adalah:',
      options: ['Di depan memberikan teladan / contoh yang baik', 'Di tengah memberi semangat', 'Di belakang memberi dorongan', 'Di atas memberi perintah'],
      correctOptionIndex: 0,
      explanation: 'Ing Ngarsa Sung Tuladha berarti pemimpin di depan harus menjadi teladan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_052',
      questionText: 'Makna dari bagian semboyan pendidikan "Ing Madya Mangun Karsa" adalah:',
      options: ['Di tengah-tengah membangun semangat dan prakarsa', 'Di depan memberi teladan', 'Di belakang memberi dorongan', 'Di luar memberi penilaian'],
      correctOptionIndex: 0,
      explanation: 'Ing Madya Mangun Karsa berarti berada di tengah memberi inspirasi dan kehendak.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_053',
      questionText: 'Makna dari semboyan "Tut Wuri Handayani" yang menjadi logo Kementerian Pendidikan adalah:',
      options: ['Dari belakang memberikan dorongan dan arahan', 'Dari depan memimpin', 'Dari samping mendampingi', 'Dari atas mengawasi'],
      correctOptionIndex: 0,
      explanation: 'Tut Wuri Handayani berarti pendidik dari belakang memberikan dorongan moral.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_054',
      questionText: 'Hari Pendidikan Nasional di Indonesia diperingati setiap tanggal 2 Mei yang merupakan hari kelahiran:',
      options: ['Ki Hajar Dewantara', 'R.A. Kartini', 'Soekarno', 'Moh. Yamin'],
      correctOptionIndex: 0,
      explanation: '2 Mei ditetapkan sebagai Hardiknas menghormati jasa Ki Hajar Dewantara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_055',
      questionText: 'Perjuangan R.A. Kartini dalam emansipasi wanita dituangkan dalam kumpulan surat-suratnya yang terkenal berjudul:',
      options: ['Habis Gelap Terbitlah Terang', 'Layar Terkembang', 'Habis Manis Sepah Dibuang', 'Bumi Manusia'],
      correctOptionIndex: 0,
      explanation: 'Door Duisternis tot Licht diterjemahkan sebagai Habis Gelap Terbitlah Terang.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_056',
      questionText: 'Hari Kartini diperingati setiap tanggal 21 April untuk mengenang perjuangan dalam hal:',
      options: ['Kesetaraan hak pendidikan dan emansipasi wanita', 'Perang kemerdekaan militer', 'Perdagangan kain batik', 'Politik luar negeri'],
      correctOptionIndex: 0,
      explanation: 'Kartini memperjuangkan hak pendidikan bagi perempuan Indonesia.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_057',
      questionText: 'Nilai Pancasila yang melarang perundungan (bullying) dan kekerasan fisik di sekolah tercermin terutama pada Sila ke:',
      options: ['Sila 2 (Kemanusiaan yang Adil dan Beradab)', 'Sila 1', 'Sila 3', 'Sila 5'],
      correctOptionIndex: 0,
      explanation: 'Sila ke-2 menjunjung martabat kemanusiaan dan menolak penindasan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_058',
      questionText: 'Upaya pencegahan perilaku bullying di sekolah dasar dapat dilakukan melalui:',
      options: ['Edukasi empati, budaya saling menghargai, dan sanksi edukatif yang tegas', 'Membiarkan siswa menyelesaikan sendiri secara fisik', 'Menyembunyikan kejadian dari orang tua', 'Mengelompokkan siswa berdasarkan ras'],
      correctOptionIndex: 0,
      explanation: 'Edukasi empati dan lingkungan aman mencegah perundungan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_059',
      questionText: 'Sikap disiplin lalu lintas sebagai cerminan kesadaran hukum warga negara diwujudkan dengan:',
      options: ['Memakai helm saat berkendara dan mematuhi rambu-rambu lalu lintas', 'Menerobos lampu merah saat sepi', 'Mengendarai motor di bawah umur tanpa SIM', 'Melawan arus lalu lintas'],
      correctOptionIndex: 0,
      explanation: 'Mematuhi tata tertib jalan raya menjaga keselamatan diri dan orang lain.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_060',
      questionText: 'Pembayaran pajak oleh warga negara secara tertib (seperti PBB, PPh) berfungsi untuk:',
      options: ['Pembangunan sarana umum, sekolah, jalan, dan fasilitas publik', 'Kekayaan pribadi pejabat', 'Dibagikan secara gratis kepada orang asing', 'Disimpan di bank luar negeri'],
      correctOptionIndex: 0,
      explanation: 'Pajak adalah modal utama pembiayaan pembangunan nasional.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_061',
      questionText: 'Asas pemilu di Indonesia yang disingkat LUBER JURDIL singkatan dari:',
      options: ['Langsung, Umum, Bebas, Rahasia, Jujur, dan Adil', 'Lancar, Unggul, Bersih, Rapi, Jujur, Adil', 'Lokal, Umum, Bebas, Resmi, Jelas, Dinamis', 'Luhur, Utuh, Baik, Ramah, Jujur, Damai'],
      correctOptionIndex: 0,
      explanation: 'LUBER JURDIL adalah asas penyelenggaraan Pemilihan Umum di Indonesia.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_062',
      questionText: 'Makna asas "Langsung" dalam Pemilu di Indonesia adalah:',
      options: ['Pemilih memberikan suaranya secara langsung tanpa diwakilkan oleh orang lain', 'Pemilihan dilakukan di tempat terbuka', 'Hasil pemilu langsung diumumkan hari itu juga', 'Pemilih mencoblos di kantor polisi'],
      correctOptionIndex: 0,
      explanation: 'Asas langsung mewajibkan pemilih menyalurkan suaranya tanpa perantara.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_063',
      questionText: 'Makna asas "Rahasia" dalam Pemilu adalah:',
      options: ['Pilihan pemilih dijamin tidak akan diketahui oleh pihak manapun', 'Jadwal pemilu disahasiakan', 'Nama calon anggota dewan dirahasiakan', 'Lokasi TPS dirahasiakan'],
      correctOptionIndex: 0,
      explanation: 'Asas rahasia melindungi kebebasan pemilih dari intimidasi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_064',
      questionText: 'Lembaga independen yang bertugas menyelenggarakan Pemilihan Umum di Indonesia adalah:',
      options: ['KPU (Komisi Pemilihan Umum)', 'Bawaslu', 'DKPP', 'Kementerian Dalam Negeri'],
      correctOptionIndex: 0,
      explanation: 'KPU bertindak sebagai penyelenggara teknis Pemilu.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_065',
      questionText: 'Lembaga yang bertugas mengawasi seluruh tahapan penyelenggaraan Pemilu di Indonesia adalah:',
      options: ['Bawaslu (Badan Pengawas Pemilu)', 'KPU', 'DPR', 'Polri'],
      correctOptionIndex: 0,
      explanation: 'Bawaslu mengawasi integritas dan potensi pelanggaran Pemilu.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_066',
      questionText: 'Bentuk partisipasi politik warga negara yang berusia 17 tahun ke atas saat Pemilu adalah:',
      options: ['Menggunakan hak pilihnya secara bijak dan bertanggung jawab', 'Golput (tidak memilih) karena acuh', 'Menerima uang suap politik (money politics)', 'Mengintimidasi pemilih lain'],
      correctOptionIndex: 0,
      explanation: 'Menggunakan hak pilih dengan kritis adalah kewajiban moral kewarganegaraan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_067',
      questionText: 'Bahaya praktik politik uang (money politics) dalam pemilu adalah:',
      options: ['Merusak kualitas demokrasi dan melahirkan pemimpin yang korup', 'Meningkatkan kemakmuran rakyat', 'Menjamin keadilan sosial', 'Membuat pemilu efisien'],
      correctOptionIndex: 0,
      explanation: 'Money politics merusak esensi kedaulatan rakyat dan etika demokrasi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_068',
      questionText: 'Otonomi daerah di Indonesia memberikan kewenangan kepada daerah untuk:',
      options: ['Mengatur dan mengurus sendiri urusan pemerintahan sesuai aspirasi masyarakat lokal', 'Membuat mata uang sendiri', 'Mendirikan angkatan perang sendiri', 'Membuat perjanjian diplomatik dengan luar negeri'],
      correctOptionIndex: 0,
      explanation: 'Otonomi daerah memberi kemandirian pengelolaan potensi daerah.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_069',
      questionText: 'Urusan pemerintahan yang tetap menjadi kewenangan absolut pemerintah pusat (tidak diotonomikan) KECUALI:',
      options: ['Pengelolaan kebersihan sampah pasar lokal', 'Politik Luar Negeri', 'Pertahanan dan Keamanan', 'Moneter dan Fiskal'],
      correctOptionIndex: 0,
      explanation: 'Kebersihan pasar lokal merupakan kewenangan pemerintah daerah.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_070',
      questionText: 'Kepala daerah yang memimpin penyelenggaraan pemerintahan di tingkat Kabupaten dinamakan:',
      options: ['Bupati', 'Walikota', 'Gubernur', 'Camat'],
      correctOptionIndex: 0,
      explanation: 'Kabupaten dipimpin oleh seorang Bupati.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_071',
      questionText: 'Kepala daerah yang memimpin wilayah Kota dinamakan:',
      options: ['Walikota', 'Bupati', 'Gubernur', 'Lurah'],
      correctOptionIndex: 0,
      explanation: 'Pemerintahan kota dipimpin oleh seorang Walikota.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_072',
      questionText: 'Kepala daerah yang memimpin wilayah Provinsi dinamakan:',
      options: ['Gubernur', 'Bupati', 'Walikota', 'Menteri'],
      correctOptionIndex: 0,
      explanation: 'Provinsi dipimpin oleh Gubernur sebagai wakil pemerintah pusat di daerah.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_073',
      questionText: 'Peraturan hukum yang dibuat oleh DPRD Provinsi bersama Gubernur dinamakan:',
      options: ['Peraturan Daerah (Perda) Provinsi', 'Peraturan Presiden', 'Peraturan Menteri', 'Undang-Undang'],
      correctOptionIndex: 0,
      explanation: 'Perda Provinsi dibentuk DPRD Provinsi bersama Gubernur.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_074',
      questionText: 'Prinsip tata kelola pemerintahan yang baik (Good Governance) meliputi aspek berikut KECUALI:',
      options: ['Nepotisme dan Kerahasiaan Informasi', 'Transparansi', 'Akuntabilitas', 'Partisipasi Masyarakat'],
      correctOptionIndex: 0,
      explanation: 'Nepotisme merusak good governance.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_075',
      questionText: 'Korupsi, Kolusi, dan Nepotisme (KKN) merupakan tindakan yang melanggar hukum dan moral karena:',
      options: ['Merugikan keuangan negara dan merenggut hak-hak rakyat adil', 'Meningkatkan kesejahteraan sosial', 'Mempercepat pelayanan umum', 'Menciptakan kepastian hukum'],
      correctOptionIndex: 0,
      explanation: 'KKN merusak keadilan sosial dan mencederai integritas bangsa.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_076',
      questionText: 'Lembaga independen pemberantas korupsi di Indonesia yang dibentuk berdasarkan UU No. 30 Tahun 2002 adalah:',
      options: ['KPK (Komisi Pemberantasan Korupsi)', 'Komnas HAM', 'KY', 'OMBUDSMAN'],
      correctOptionIndex: 0,
      explanation: 'KPK bertugas melakukan pencegahan dan penindakan tindak pidana korupsi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_077',
      questionText: 'Lembaga mandiri yang bertugas mengawasi penyelenggaraan pelayanan publik oleh instansi pemerintah adalah:',
      options: ['Ombudsman Republik Indonesia', 'KPK', 'Komnas HAM', 'LPSK'],
      correctOptionIndex: 0,
      explanation: 'Ombudsman mengawasi kualitas pelayanan publik dan maladministrasi.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_078',
      questionText: 'Lembaga nasional yang bertugas menguji dan melindungi pelaksanaan Hak Asasi Manusia di Indonesia adalah:',
      options: ['Komnas HAM', 'KPU', 'KPAI', 'BNPT'],
      correctOptionIndex: 0,
      explanation: 'Komnas HAM mengawasi pemenuhan perlindungan HAM.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_079',
      questionText: 'Lembaga nasional independen yang mengawasi pemenuhan hak dan perlindungan anak Indonesia adalah:',
      options: ['KPAI (Komisi Perlindungan Anak Indonesia)', 'Komnas Perempuan', 'KPK', 'BKKBN'],
      correctOptionIndex: 0,
      explanation: 'KPAI memantau pelaksanaan hak perlindungan anak.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_080',
      questionText: 'Sikap patuh pada peraturan sekolah yang berasal dari kesadaran diri sendiri dinamakan disiplin:',
      options: ['Disiplin Internal (Self-Discipline)', 'Disiplin Otoriter', 'Disiplin Semu', 'Disiplin Paksaan'],
      correctOptionIndex: 0,
      explanation: 'Disiplin internal lahir dari pemahaman nilai dan tanggung jawab.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_081',
      questionText: 'Pentingnya menjaga kerukunan hidup bertetangga dalam lingkungan masyarakat tercermin dari sikap:',
      options: ['Saling sapa, tolong menolong, dan tidak membuat kegaduhan', 'Menutup diri dan bersikap sombong', 'Menyebarkan gosip tetangga', 'Membuang sampah ke pekarangan rumah tetangga'],
      correctOptionIndex: 0,
      explanation: 'Tenggang rasa dan silaturahmi menciptakan keharmonisan lingkungan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_082',
      questionText: 'Konflik sosial di masyarakat yang dipicu oleh perbedaan SARA (Suku, Agama, Ras, dan Antargolongan) dapat dicegah dengan:',
      options: ['Mengedepankan dialog moderasi beragama dan moderasi berbudaya', 'Memperbesar perbedaan', 'Menggalang kekuatan massa suku', 'Melarang pergaulan antarsuku'],
      correctOptionIndex: 0,
      explanation: 'Dialog inkusif dan sikap moderat mencegah gesekan SARA.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_083',
      questionText: 'Moderasi beragama memiliki arti yaitu:',
      options: ['Cara pandang dan praktik beragama secara seimbang, tidak ekstrem kanan maupun ekstrem kiri', 'Mencampuradukkan ajaran agama', 'Meninggalkan ibadah agama', 'Memaksa orang memeluk agama kita'],
      correctOptionIndex: 0,
      explanation: 'Moderasi beragama menekankan komitmen kebangsaan, toleransi, dan anti-kekerasan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_084',
      questionText: 'Penanaman jiwa kewirausahaan (entrepreneurship) berbasis karakter di SD mengajarkan nilai:',
      options: ['Kreatif, inovatif, pantang menyerah, dan jujur', 'Kerja instan dan menghalalkan segala cara', 'Ketergantungan pada bantuan orang lain', 'Keserakahan menumpuk uang'],
      correctOptionIndex: 0,
      explanation: 'Kewirausahaan membentuk kemandirian, daya cipta, dan ketangguhan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_085',
      questionText: 'Prinsip kesetaraan gender dalam lingkungan pendidikan SD diwujudkan dengan:',
      options: ['Memberikan kesempatan belajar dan memimpin yang sama bagi siswa laki-laki dan perempuan', 'Hanya menunjuk siswa laki-laki sebagai ketua', 'Melarang siswa perempuan menyukai sains', 'Membedakan kurikulum pelajaran'],
      correctOptionIndex: 0,
      explanation: 'Kesetaraan gender memberikan hak dan ruang tumbuh setara bagi putra dan putri.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_086',
      questionText: 'Kesadaran membayar retribusi dan menjaga fasilitas umum tempat wisata menunjukkan karakter warga negara yang:',
      options: ['Taat hukum dan peduli lingkungan sosial', 'Sombong', 'Konsumtif', 'Pasif'],
      correctOptionIndex: 0,
      explanation: 'Ketaatan aturan publik mencerminkan civic virtue.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_087',
      questionText: 'Penetapan Hari Kemerdekaan Indonesia 17 Agustus sebagai hari libur nasional bertujuan untuk:',
      options: ['Mengenang jasa para pahlawan dan memperkuat jiwa nasionalisme bangsa', 'Menghabiskan waktu tidur', 'Mendorong rekreasi mewah', 'Mengurangi jam belajar sekolah'],
      correctOptionIndex: 0,
      explanation: 'Peringatan kemerdekaan memupuk nilai kebangsaan dan rasa syukur nasional.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_088',
      questionText: 'Upacara bendera setiap hari Senin di sekolah dasar diselenggarakan untuk melatih siswa dalam hal:',
      options: ['Kedisiplinan, kepemimpinan, dan penghormatan simbol negara', 'Menghafal gerakan baris-berbaris tanpa arti', 'Mengisi waktu kosong guru', 'Membuat siswa kelelahan'],
      correctOptionIndex: 0,
      explanation: 'Upacara bendera menanamkan rasa hormat pada sang merah putih dan sejarah perjuangan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_089',
      questionText: 'Pengenalan lagu-lagu wajib nasional kepada siswa SD berguna untuk:',
      options: ['Menanamkan semangat patriotisme dan cinta tanah air', 'Menghafal lirik lagu rumit', 'Menggantikan musik modern', 'Ujian vokal murni'],
      correctOptionIndex: 0,
      explanation: 'Lagu wajib nasional memuat pesan sejarah dan api perjuangan bangsa.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_090',
      questionText: 'Karakter "Sederhana" dalam tata kehidupan berbangsa dan bernegara menghindarkan seseorang dari sifat:',
      options: ['Pamer harta (hedonisme) dan konsumerisme berlebihan', 'Hemat', 'Cermat', 'Inovatif'],
      correctOptionIndex: 0,
      explanation: 'Gaya hidup sederhana membentengi diri dari kesenjangan sosial dan sifat konsumtif.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_091',
      questionText: 'Hak atas rasa aman dan bebas dari rasa takut merupakan hak konstitusional warga negara yang diatur dalam UUD 1945 Pasal:',
      options: ['Pasal 28G ayat (1)', 'Pasal 33 ayat (3)', 'Pasal 31 ayat (1)', 'Pasal 29 ayat (2)'],
      correctOptionIndex: 0,
      explanation: 'Pasal 28G menjamin hak perlindungan diri dan kebebasan dari rasa takut.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_092',
      questionText: 'Hak setiap warga negara untuk mendapatkan pendidikan yang layak diatur dalam UUD 1945 Pasal:',
      options: ['Pasal 31 ayat (1)', 'Pasal 27 ayat (2)', 'Pasal 34 ayat (1)', 'Pasal 36'],
      correctOptionIndex: 0,
      explanation: 'Pasal 31 ayat 1 menegaskan bahwa Setiap warga negara berhak mendapat pendidikan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_093',
      questionText: 'Pemerintah memprioritaskan anggaran pendidikan sekurang-kurangnya berapa persen dari APBN dan APBD?',
      options: ['20 Persen', '10 Persen', '5 Persen', '50 Persen'],
      correctOptionIndex: 0,
      explanation: 'UUD 1945 Pasal 31 ayat (4) mewajibkan anggaran pendidikan minimal 20%.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_094',
      questionText: 'Fakir miskin dan anak-anak yang terlantar dipelihara oleh negara tercantum dalam UUD 1945 Pasal:',
      options: ['Pasal 34 ayat (1)', 'Pasal 33 ayat (1)', 'Pasal 28A', 'Pasal 30 ayat (2)'],
      correctOptionIndex: 0,
      explanation: 'Pasal 34 menjamin perlindungan sosial negara terhadap fakir miskin dan anak terlantar.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_095',
      questionText: 'Bumi, air, dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk:',
      options: ['Sebesar-besar kemakmuran rakyat', 'Keuntungan pengusaha asing', 'Kekayaan para menteri', 'Kas investasi luar negeri'],
      correctOptionIndex: 0,
      explanation: 'Pasal 33 ayat 3 menegaskan pengelolaan SDA berorientasi pada kemakmuran rakyat.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_096',
      questionText: 'Tindakan menyebarkan informasi tanpa menyaring kebenarannya di grup pesan singkat melanggar etika:',
      options: ['Kewarganegaraan Digital (Digital Citizenship)', 'Tata Boga', 'Pendidikan Jasmani', 'Kesenian'],
      correctOptionIndex: 0,
      explanation: 'Kewarganegaraan digital menuntut etika dan tanggung jawab berinternet.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_097',
      questionText: 'Peran siswa sebagai agen perubahan (Agent of Change) di lingkungan sekolah dapat diwujudkan melalui:',
      options: ['Inisiatif menjaga kebersihan lingkungan dan menghentikan perundungan', 'Mengikuti aksi bolos bersama', 'Merusak fasilitas toilet sekolah', 'Membuat keributan saat jam pelajaran'],
      correctOptionIndex: 0,
      explanation: 'Agent of change membawa pengaruh positif dan teladan perbaikan.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_098',
      questionText: 'Kebebasan berpendapat di muka umum di Indonesia dijamin oleh undang-undang dengan syarat:',
      options: ['Dilakukan secara santun, damai, dan tidak melanggar hak orang lain', 'Boleh merusak sarana publik', 'Menggunakan tindak kekerasan', 'Menghina simbol agama'],
      correctOptionIndex: 0,
      explanation: 'Kebebasan berekspresi diiringi tanggung jawab menghormati ketertiban umum.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_099',
      questionText: 'Profil Pelajar Pancasila dalam kurikulum pendidikan Indonesia memiliki 6 dimensi utama KECUALI:',
      options: ['Individualisme dan Egosentrisme', 'Beriman, Bertakwa kepada Tuhan YME & Berakhlak Mulia', 'Berkebinekaan Global & Gotong Royong', 'Bernalar Kritis & Kreatif'],
      correctOptionIndex: 0,
      explanation: 'Profil Pelajar Pancasila membentuk pribadi holistik dan berkarakter luhur.',
    ),
    QuestionItem(
      id: 'pgsd_kwn_100',
      questionText: 'Tujuan akhir penanaman Karakter dan Pendidikan Kewarganegaraan di Sekolah Dasar adalah untuk melahirkan generasi yang:',
      options: ['Cerdas secara intelektual, matang secara emosional, berakhlak mulia, dan berkomitmen menjaga persatuan bangsa', 'Menjadi penghafal undang-undang tanpa tindakan', 'Pandai berdebat tanpa etika', 'Mencari keuntungan pribadi saja'],
      correctOptionIndex: 0,
      explanation: 'Pendidikan karakter membentuk warga negara cerdas dan berkeperibadian luhur (Smart and Good Citizen).',
    ),
  ];
}
