import '../../tes_seleksi_model.dart';

List<QuestionItem> getTesPgsdIpaQuestions() {
  return const [
    QuestionItem(
      id: 'pgsd_ipa_001',
      questionText: 'Proses pembuatan makanan pada tumbuhan hijau dengan bantuan cahaya matahari dinamakan:',
      options: ['Fotosintesis', 'Respirasi', 'Transpirasi', 'Gutasi'],
      correctOptionIndex: 0,
      explanation: 'Fotosintesis mengolah karbondioksida dan air menjadi glukosa dan oksigen dengan bantuan klorofil dan cahaya.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_002',
      questionText: 'Zat hijau daun yang berperan menyerap energi cahaya dalam proses fotosintesis adalah:',
      options: ['Klorofil', 'Karoten', 'Stomata', 'Xilem'],
      correctOptionIndex: 0,
      explanation: 'Klorofil adalah pigmen hijau penangkap energi matahari pada tumbuhan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_003',
      questionText: 'Gas yang diserap oleh tumbuhan untuk bahan utama fotosintesis adalah:',
      options: ['Karbondioksida (CO₂)', 'Oksigen (O₂)', 'Nitrogen (N₂)', 'Hidrogen (H₂)'],
      correctOptionIndex: 0,
      explanation: 'Karbondioksida diserap dari udara melalui stomata untuk fotosintesis.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_004',
      questionText: 'Gas yang dihasilkan oleh tumbuhan sebagai produk samping fotosintesis yang bermanfaat bagi pernapasan manusia adalah:',
      options: ['Oksigen (O₂)', 'Karbondioksida (CO₂)', 'Karbonmonoksida (CO)', 'Argon'],
      correctOptionIndex: 0,
      explanation: 'Fotosintesis menghasilkan oksigen yang dibutuhkan makhluk hidup.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_005',
      questionText: 'Jaringan pembuluh pada tumbuhan yang berfungsi mengangkut air dan mineral dari akar ke daun adalah:',
      options: ['Xilem', 'Floem', 'Kambium', 'Epidermis'],
      correctOptionIndex: 0,
      explanation: 'Xilem (pembuluh kayu) mengangkut air/mineral dari tanah ke daun.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_006',
      questionText: 'Jaringan pembuluh pada tumbuhan yang berfungsi mengedarkan hasil fotosintesis dari daun ke seluruh bagian tumbuhan adalah:',
      options: ['Floem', 'Xilem', 'Korteks', 'Parenkim'],
      correctOptionIndex: 0,
      explanation: 'Floem (pembuluh tapis) mendistribusikan zat makanan hasil fotosintesis.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_007',
      questionText: 'Mulut daun tempat terjadinya pertukaran gas O₂ dan CO₂ serta penguapan air pada tumbuhan dinamakan:',
      options: ['Stomata', 'Lentisel', 'Kloroplas', 'Trikoma'],
      correctOptionIndex: 0,
      explanation: 'Stomata berfungsi sebagai alat respirasi dan transpirasi daun.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_008',
      questionText: 'Metamorfosis sempurna pada serangga ditandai dengan tahapan perkembangan:',
      options: ['Telur - Larva - Pupa (Kepompong) - Imago (Dewasa)', 'Telur - Nimfa - Imago', 'Telur - Imago', 'Telur - Pupa - Imago'],
      correctOptionIndex: 0,
      explanation: 'Metamorfosis sempurna melalui 4 fase lengkap termasuk pupa (kepompong).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_009',
      questionText: 'Hewan berikut yang mengalami metamorfosis sempurna adalah:',
      options: ['Kupu-kupu dan Nyamuk', 'Belalang dan Kecoak', 'Jangkrik dan Capung', 'Kutu rambut dan Kutu buku'],
      correctOptionIndex: 0,
      explanation: 'Kupu-kupu dan nyamuk mengalami fase larva dan kepompong.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_010',
      questionText: 'Hewan berikut yang mengalami metamorfosis tidak sempurna adalah:',
      options: ['Belalang dan Kecoak', 'Kupu-kupu dan Lalat', 'Katak dan Nyamuk', 'Semut dan Lebah'],
      correctOptionIndex: 0,
      explanation: 'Belalang dan kecoak tidak mengalami fase pupa (hanya telur-nimfa-imago).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_011',
      questionText: 'Katak mengalami tahapan metamorfosis unik dengan fase berudu yang bernapas menggunakan:',
      options: ['Insang', 'Paru-paru', 'Kulit', 'Trakea'],
      correctOptionIndex: 0,
      explanation: 'Berudu (kecebong) bernapas di dalam air menggunakan insang.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_012',
      questionText: 'Katak dewasa bernapas mengandalkan kombinasi antara paru-paru dan:',
      options: ['Kulit lembab', 'Insang luar', 'Trakea', 'Stomata'],
      correctOptionIndex: 0,
      explanation: 'Katak dewasa menyerap oksigen melalui paru-paru dan permukaan kulit yang basah.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_013',
      questionText: 'Hubungan timbal balik antara dua makhluk hidup yang saling menguntungkan kedua belah pihak dinamakan:',
      options: ['Simbiosis Mutualisme', 'Simbiosis Komensalisme', 'Simbiosis Parasitisme', 'Predasi'],
      correctOptionIndex: 0,
      explanation: 'Mutualisme menguntungkan kedua organisme (contoh: lebah dan bunga).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_014',
      questionText: 'Hubungan antara bunga dan lebah penyerbuk merupakan contoh simbiosis:',
      options: ['Mutualisme', 'Komensalisme', 'Parasitisme', 'Amensalisme'],
      correctOptionIndex: 0,
      explanation: 'Lebah mendapat nektar dan bunga terbantu penyerbukannya.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_015',
      questionText: 'Hubungan di mana satu pihak diuntungkan dan pihak lain tidak diuntungkan maupun dirugikan dinamakan:',
      options: ['Simbiosis Komensalisme', 'Simbiosis Mutualisme', 'Simbiosis Parasitisme', 'Kompetisi'],
      correctOptionIndex: 0,
      explanation: 'Komensalisme menguntungkan satu pihak tanpa merugikan pihak lain (contoh: ikan remora dan hiu).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_016',
      questionText: 'Tanaman anggrek yang menempel pada pohon mangga merupakan contoh simbiosis:',
      options: ['Komensalisme', 'Parasitisme', 'Mutualisme', 'Predasi'],
      correctOptionIndex: 0,
      explanation: 'Anggrek mendapat tempat hidup tanpa mengambil makanan dari pohon mangga.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_017',
      questionText: 'Hubungan di mana satu pihak mendapat keuntungan sedangkan pihak lain dirugikan dinamakan:',
      options: ['Simbiosis Parasitisme', 'Simbiosis Komensalisme', 'Simbiosis Mutualisme', 'Netralisme'],
      correctOptionIndex: 0,
      explanation: 'Parasitisme merugikan inang (contoh: benalu pada pohon inang).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_018',
      questionText: 'Tanaman benalu yang tumbuh menyerap zat makanan dari pohon inang merupakan contoh simbiosis:',
      options: ['Parasitisme', 'Komensalisme', 'Mutualisme', 'Kanibalisme'],
      correctOptionIndex: 0,
      explanation: 'Benalu mengambil air dan nutrisi inang hingga mengganggu pertumbuhan inang.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_019',
      questionText: 'Organ pencernaan manusia tempat terjadinya penyerapan nutrisi makanan ke dalam darah adalah:',
      options: ['Usus Halus', 'Lambung', 'Usus Besar', 'Kerongkongan'],
      correctOptionIndex: 0,
      explanation: 'Vili usus halus menyerap sari-sari makanan ke pembuluh darah.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_020',
      questionText: 'Organ pencernaan tempat penyerapan air dan pembentukan feses dinamakan:',
      options: ['Usus Besar (Kolon)', 'Usus Halus', 'Lambung', 'Pankreas'],
      correctOptionIndex: 0,
      explanation: 'Usus besar menyerap kembali air dan membusukkan sisa makanan dengan bantuan E. coli.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_021',
      questionText: 'Enzim asam klorida (HCl) di dalam lambung berfungsi untuk:',
      options: ['Membunuh kuman penyakit dan mengaktifkan pepsinogen', 'Menggumpalkan susu', 'Mengubah amilum jadi glukosa', 'Emulsi lemak'],
      correctOptionIndex: 0,
      explanation: 'Asam lambung (HCl) menciptakan suasana asam membunuh bakteri.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_022',
      questionText: 'Enzim ptyalin (amilase) dalam ludah mulut berfungsi menguraikan zat:',
      options: ['Karbohidrat / Amilum menjadi glukosa/maltosa', 'Protein jadi asam amino', 'Lemak jadi asam lemak', 'Vitamin'],
      correctOptionIndex: 0,
      explanation: 'Ptyalin memecah karbohidrat kompleks di rongga mulut.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_023',
      questionText: 'Organ pernapasan manusia tempat terjadinya pertukaran gas O₂ dan CO₂ dinamakan:',
      options: ['Alveolus (di Paru-paru)', 'Bronkus', 'Trakea', 'Laring'],
      correctOptionIndex: 0,
      explanation: 'Alveolus adalah kantung udara tipis penukar gas pernapasan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_024',
      questionText: 'Sekat rongga dada yang berperan utama dalam pernapasan perut manusia dinamakan:',
      options: ['Diafragma', 'Pleura', 'Alveolus', 'Bronkiolus'],
      correctOptionIndex: 0,
      explanation: 'Diafragma berkontraksi merata saat inspirasi pernapasan perut.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_025',
      questionText: 'Pembuluh darah yang membawa darah kaya oksigen dari jantung ke seluruh tubuh dinamakan:',
      options: ['Pembuluh Nadi (Arteri)', 'Pembuluh Balik (Vena)', 'Kapiler', 'Limfa'],
      correctOptionIndex: 0,
      explanation: 'Arteri memompa darah beroksigen keluar dari jantung.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_026',
      questionText: 'Pembuluh darah yang membawa darah kotor kaya karbondioksida dari seluruh tubuh kembali ke jantung dinamakan:',
      options: ['Pembuluh Balik (Vena)', 'Pembuluh Nadi (Arteri)', 'Aorta', 'Arteriol'],
      correctOptionIndex: 0,
      explanation: 'Vena membawa darah kaya CO₂ kembali menuju jantung.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_027',
      questionText: 'Ruang jantung yang berfungsi memompa darah kaya oksigen ke seluruh tubuh dinamakan:',
      options: ['Bilik Kiri (Ventrikel Kiri)', 'Serambi Kiri', 'Bilik Kanan', 'Serambi Kanan'],
      correctOptionIndex: 0,
      explanation: 'Bilik kiri memiliki otot tebal untuk memompa darah sistemik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_028',
      questionText: 'Perubahan wujud benda dari padat menjadi gas tanpa melalui fase cair dinamakan:',
      options: ['Menyublim', 'Mengkristal', 'Menguap', 'Mencair'],
      correctOptionIndex: 0,
      explanation: 'Menyublim adalah perubahan langsung padat ke gas (contoh: kapur barus).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_029',
      questionText: 'Perubahan wujud benda dari gas menjadi padat dinamakan:',
      options: ['Mengkristal / Menghablur', 'Menyublim', 'Mengembun', 'Membeku'],
      correctOptionIndex: 0,
      explanation: 'Mengkristal adalah perubahan gas menjadi padat (contoh: salju).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_030',
      questionText: 'Perubahan wujud benda dari cair menjadi gas dinamakan:',
      options: ['Menguap', 'Mengembun', 'Mencair', 'Membeku'],
      correctOptionIndex: 0,
      explanation: 'Menguap adalah pelepasan molekul cair menjadi gas saat dipanaskan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_031',
      questionText: 'Perubahan wujud benda dari gas menjadi cair dinamakan:',
      options: ['Mengembun', 'Menguap', 'Mencair', 'Menyublim'],
      correctOptionIndex: 0,
      explanation: 'Mengembun terjadi saat uap air mendingin menjadi titik air.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_032',
      questionText: 'Perpindahan panas melalui zat perantara tanpa disertai perpindahan partikel zatnya (misal: sendok panas di teh panas) disebut:',
      options: ['Konduksi', 'Konveksi', 'Radiasi', 'Evaporasi'],
      correctOptionIndex: 0,
      explanation: 'Konduksi terjadi pada benda padat tanpa alir partikel.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_033',
      questionText: 'Perpindahan panas yang disertai perpindahan partikel zat perantaranya (misal: mendidihkan air) disebut:',
      options: ['Konveksi', 'Konduksi', 'Radiasi', 'Sublimasi'],
      correctOptionIndex: 0,
      explanation: 'Konveksi terjadi pada fluida (cair/gas) karena perbedaan massa jenis.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_034',
      questionText: 'Perpindahan panas tanpa memerlukan zat perantara (misal: sinar matahari sampai ke bumi) disebut:',
      options: ['Radiasi', 'Konduksi', 'Konveksi', 'Kondensasi'],
      correctOptionIndex: 0,
      explanation: 'Radiasi memancar melalui gelombang elektromagnetik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_035',
      questionText: 'Sifat cahaya yang menyebabkan terbentuknya bayangan dan memungkinkan terjadinya gerhana adalah:',
      options: ['Cahaya merambat lurus', 'Cahaya dapat dibiaskan', 'Cahaya mengalami difraksi', 'Cahaya dapat diuraikan'],
      correctOptionIndex: 0,
      explanation: 'Cahaya yang merambat lurus terhalang benda gelap membentuk bayang-bayang.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_036',
      questionText: 'Pensil yang dimasukkan ke dalam gelas berisi air tampak bengkok disebabkan sifat cahaya:',
      options: ['Dapat dibiaskan (Pembiasan / Refraksi)', 'Dapat dipantulkan', 'Merambat lurus', 'Menembus benda bening'],
      correctOptionIndex: 0,
      explanation: 'Pembiasan terjadi karena perubahan kecepatan cahaya saat melewati dua medium berbeda kerapatan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_037',
      questionText: 'Terbentuknya pelangi di langit setelah hujan merupakan contoh sifat cahaya:',
      options: ['Dapat diuraikan (Dispersi)', 'Dapat dipantulkan', 'Dapat diserap', 'Merambat lurus'],
      correctOptionIndex: 0,
      explanation: 'Pelangi terjadi akibat dispersi (penguraian) cahaya putih menjadi spektrum warna oleh titik air.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_038',
      questionText: 'Cermin yang permukaannya melengkung ke luar dan selalu menghasilkan bayangan maya, tegak, diperkecil adalah:',
      options: ['Cermin Cembung', 'Cermin Cekung', 'Cermin Datar', 'Lensa Cekung'],
      correctOptionIndex: 0,
      explanation: 'Cermin cembung (seperti kaca spion) memperluas jarak pandang dengan bayangan diperkecil.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_039',
      questionText: 'Alat optik yang digunakan pada kapal selam untuk mengamati keadaan di permukaan laut adalah:',
      options: ['Periskop', 'Mikroskop', 'Teleskop', 'Lup'],
      correctOptionIndex: 0,
      explanation: 'Periskop memanfaatkan cermin/prisma untuk memantulkan bayangan dari atas ke bawah.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_040',
      questionText: 'Energi yang dihasilkan oleh benda yang bergetar dinamakan:',
      options: ['Energi Bunyi', 'Energi Cahaya', 'Energi Kimia', 'Energi Potensial'],
      correctOptionIndex: 0,
      explanation: 'Getaran benda menghasilkan gelombang bunyi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_041',
      questionText: 'Bunyi tidak dapat merambat melalui media:',
      options: ['Ruang Hampa Udara (Vakum)', 'Benda Padat', 'Zat Cair', 'Udara / Gas'],
      correctOptionIndex: 0,
      explanation: 'Bunyi adalah gelombang mekanik yang memerlukan medium untuk merambat.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_042',
      questionText: 'Bunyi pantul yang terdengar beberapa saat setelah bunyi asli selesai diucapkan dinamakan:',
      options: ['Gema', 'Gaung / Kerdam', 'Resonansi', 'Eko'],
      correctOptionIndex: 0,
      explanation: 'Gema terjadi ketika dinding pantul jauh sehingga pantulan terdengar terpisah jelas.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_043',
      questionText: 'Bunyi pantul yang terdengar bersamaan atau hampir bersamaan dengan bunyi asli sehingga mengaburkan bunyi dinamakan:',
      options: ['Gaung / Kerdam', 'Gema', 'Ultrasonik', 'Audiosonik'],
      correctOptionIndex: 0,
      explanation: 'Gaung terjadi bila dinding pemantul dekat dari sumber bunyi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_044',
      questionText: 'Frekuensi bunyi yang dapat didengar oleh telinga manusia normal berada pada rentang:',
      options: ['20 Hz - 20.000 Hz (Audiosonik)', 'Kurang dari 20 Hz (Infrasonik)', 'Lebih dari 20.000 Hz (Ultrasonik)', 'Above 100.000 Hz'],
      correctOptionIndex: 0,
      explanation: 'Audiosonik adalah batas pendengaran telinga manusia.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_045',
      questionText: 'Hewan seperti kelelawar dan lumba-lumba memanfaatkan bunyi frekuensi tinggi untuk navigasi yang disebut:',
      options: ['Ekolokasi (Ultrasonik)', 'Infrasonik', 'Resonansi', 'Refraksi'],
      correctOptionIndex: 0,
      explanation: 'Ekolokasi memancarkan ultrasonik untuk mendeteksi rintangan dan mangsa.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_046',
      questionText: 'Kutub magnet yang senama (misal Utara dengan Utara) jika didekatkan akan:',
      options: ['Tolak-menolak', 'Tarik-menarik', 'Berdiam diri', 'Meleleh'],
      correctOptionIndex: 0,
      explanation: 'Kutub sejenis bertolak belakang (tolak-menolak).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_047',
      questionText: 'Kutub magnet yang tidak senama (Utara dengan Selatan) jika didekatkan akan:',
      options: ['Tarik-menarik', 'Tolak-menolak', 'Bergetar', 'Menghilang'],
      correctOptionIndex: 0,
      explanation: 'Kutub berlawanan arah tarik-menarik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_048',
      questionText: 'Pembuatan magnet buatan dengan cara mengalirkan arus listrik searah (DC) pada kumparan kawat disebut:',
      options: ['Elektromagnetik', 'Induksi', 'Gosokan', 'Kondensasi'],
      correctOptionIndex: 0,
      explanation: 'Elektromagnet menggunakan aliran listrik pada kumparan besi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_049',
      questionText: 'Rangkaian listrik yang alat-alat listriknya dipasang secara sejajar bercabang dinamakan:',
      options: ['Rangkaian Paralel', 'Rangkaian Seri', 'Rangkaian Campuran', 'Rangkaian Terbuka'],
      correctOptionIndex: 0,
      explanation: 'Rangkaian paralel bercabang sehingga jika satu lampu mati, lampu lain tetap menyala.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_050',
      questionText: 'Rangkaian listrik yang alat-alatnya disusun berurutan dalam satu jalur tanpa cabang dinamakan:',
      options: ['Rangkaian Seri', 'Rangkaian Paralel', 'Rangkaian Tertutup', 'Rangkaian Kompleks'],
      correctOptionIndex: 0,
      explanation: 'Rangkaian seri menyusun komponen berturut-turut dalam segaris.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_051',
      questionText: 'Benda yang dapat menghantarkan arus listrik atau panas dengan baik dinamakan:',
      options: ['Konduktor', 'Isolator', 'Semikonduktor', 'Radiator'],
      correctOptionIndex: 0,
      explanation: 'Konduktor (seperti tembaga, besi) mudah menghantarkan listrik/panas.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_052',
      questionText: 'Benda yang tidak dapat menghantarkan arus listrik atau panas dinamakan:',
      options: ['Isolator', 'Konduktor', 'Transistor', 'Kapasitor'],
      correctOptionIndex: 0,
      explanation: 'Isolator (seperti plastik, kayu, karet) menghambat aliran energi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_053',
      questionText: 'Satuan standar Internasional untuk mengukur Kuat Arus Listrik adalah:',
      options: ['Ampere (A)', 'Volt (V)', 'Watt (W)', 'Ohm (Ω)'],
      correctOptionIndex: 0,
      explanation: 'Ampere adalah satuan SI untuk arus listrik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_054',
      questionText: 'Satuan Internasional untuk mengukur Tegangan Listrik (Beda Potensial) adalah:',
      options: ['Volt (V)', 'Ampere (A)', 'Watt (W)', 'Joule (J)'],
      correctOptionIndex: 0,
      explanation: 'Volt mengukur beda potensial listrik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_055',
      questionText: 'Satuan Internasional untuk mengukur Daya Listrik adalah:',
      options: ['Watt (W)', 'Joule (J)', 'Volt (V)', 'Ampere (A)'],
      correctOptionIndex: 0,
      explanation: 'Watt mengukur laju penggunaan daya listrik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_056',
      questionText: 'Perubahan bentuk energi yang terjadi pada setrika listrik adalah:',
      options: ['Energi Listrik menjadi Energi Panas (Kalor)', 'Energi Listrik jadi Gerak', 'Energi Listrik jadi Kimia', 'Energi Listrik jadi Bunyi'],
      correctOptionIndex: 0,
      explanation: 'Elemen pemanas setrika mengubah daya listrik menjadi kalor.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_057',
      questionText: 'Perubahan bentuk energi pada kipas angin adalah:',
      options: ['Energi Listrik menjadi Energi Gerak (Kinetik)', 'Energi Listrik jadi Panas', 'Energi Kinetik jadi Listrik', 'Energi Kimia jadi Gerak'],
      correctOptionIndex: 0,
      explanation: 'Motor kipas angin mengubah energi listrik menjadi putaran baling-baling.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_058',
      questionText: 'Alat pemutar pada pembangkit listrik yang diubah oleh generator menjadi arus listrik dinamakan:',
      options: ['Turbin', 'Kondensor', 'Aki', 'Transformator'],
      correctOptionIndex: 0,
      explanation: 'Turbin diputar fluida (air/uap/angin) untuk menggerakkan rotor generator.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_059',
      questionText: 'Energi alternatif terbarukan yang memanfaatkan panas dari dalam bumi dinamakan:',
      options: ['Energi Geotermal (Panas Bumi)', 'Energi Biomassa', 'Energi Nuklir', 'Energi Biogas'],
      correctOptionIndex: 0,
      explanation: 'Geotermal memanfaatkan uap panas perut bumi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_060',
      questionText: 'Energi alternatif yang dihasilkan dari pembusukan kotoran ternak dinamakan:',
      options: ['Biogas', 'Biodiesel', 'Bioetanol', 'Solar'],
      correctOptionIndex: 0,
      explanation: 'Biogas (metana) dihasilkan dari fermentasi anaerob kotoran organik.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_061',
      questionText: 'Planet dalam tata surya yang paling dekat dengan matahari adalah:',
      options: ['Merkurius', 'Venus', 'Bumi', 'Mars'],
      correctOptionIndex: 0,
      explanation: 'Merkurius adalah planet urutan pertama terdekat dari Matahari.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_062',
      questionText: 'Planet terdekat kedua dari matahari yang sering disebut sebagai Bintang Fajar/Bintang Timur adalah:',
      options: ['Venus', 'Merkurius', 'Mars', 'Jupiter'],
      correctOptionIndex: 0,
      explanation: 'Venus memantulkan cahaya sangat terang sehingga terlihat di fajar/senja.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_063',
      questionText: 'Planet keempat dalam tata surya yang dijuluki Planet Merah adalah:',
      options: ['Mars', 'Venus', 'Jupiter', 'Saturnus'],
      correctOptionIndex: 0,
      explanation: 'Mars tampak kemerahan karena tingginya kandungan besi oksida di permukaannya.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_064',
      questionText: 'Planet terbesar dalam tata surya kita adalah:',
      options: ['Jupiter', 'Saturnus', 'Uranus', 'Neptunus'],
      correctOptionIndex: 0,
      explanation: 'Jupiter adalah raksasa gas terbesar di tata surya.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_065',
      questionText: 'Planet yang terkenal memiliki cincin paling indah dan jelas terbuat dari es dan debu adalah:',
      options: ['Saturnus', 'Jupiter', 'Uranus', 'Neptunus'],
      correctOptionIndex: 0,
      explanation: 'Saturnus dikelilingi cincin partikel es yang tebal.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_066',
      questionText: 'Gerakan bumi berputar pada porosnya sendiri dinamakan:',
      options: ['Rotasi Bumi', 'Revolusi Bumi', 'Presesi', 'Presisi'],
      correctOptionIndex: 0,
      explanation: 'Rotasi bumi memerlukan waktu 24 jam untuk 1 putaran poros.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_067',
      questionText: 'Akibat dari terjadinya rotasi bumi antara lain adalah:',
      options: ['Terjadinya pergantian siang dan malam serta perbedaan waktu', 'Pergantian musim', 'Gerhana bulan', 'Perubahan rasi bintang tahunan'],
      correctOptionIndex: 0,
      explanation: 'Rotasi bumi menyebabkan siang-malam dan perbedaan zona waktu.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_068',
      questionText: 'Gerakan bumi mengelilingi matahari pada orbitnya dinamakan:',
      options: ['Revolusi Bumi', 'Rotasi Bumi', 'Kala Rotasi', 'Evolusi'],
      correctOptionIndex: 0,
      explanation: 'Revolusi bumi memerlukan waktu 365,25 hari (1 tahun).',
    ),
    QuestionItem(
      id: 'pgsd_ipa_069',
      questionText: 'Akibat dari terjadinya revolusi bumi antara lain adalah:',
      options: ['Pergantian musim dan gerak semu tahunan matahari', 'Siang dan malam', 'Pembelokan arah angin pasat', 'Pasang surut air laut harian'],
      correctOptionIndex: 0,
      explanation: 'Revolusi bumi dan kemiringan sumbu bumi menyebabkan pergantian musim.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_070',
      questionText: 'Peristiwa tertutupnya matahari oleh bulan karena kedudukan Matahari - Bulan - Bumi berada dalam satu garis lurus dinamakan:',
      options: ['Gerhana Matahari', 'Gerhana Bulan', 'Pasang Purnama', 'Pasang Perbani'],
      correctOptionIndex: 0,
      explanation: 'Gerhana matahari terjadi saat Bulan berada di antara Matahari dan Bumi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_071',
      questionText: 'Peristiwa saat bayangan bumi menutupi bulan karena kedudukan Matahari - Bumi - Bulan berada pada garis lurus dinamakan:',
      options: ['Gerhana Bulan', 'Gerhana Matahari', 'Fase Bulan Baru', 'Solar Flare'],
      correctOptionIndex: 0,
      explanation: 'Gerhana bulan terjadi saat Bumi berada di antara Matahari dan Bulan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_072',
      questionText: 'Bagian bayangan inti yang paling gelap saat gerhana dinamakan:',
      options: ['Umbra', 'Penumbra', 'Antumbra', 'Corona'],
      correctOptionIndex: 0,
      explanation: 'Umbra adalah bayangan utama yang sangat gelap.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_073',
      questionText: 'Bagian bayangan samar/kabur di sekitar umbra saat gerhana dinamakan:',
      options: ['Penumbra', 'Umbra', 'Atmfer', 'Kromosfer'],
      correctOptionIndex: 0,
      explanation: 'Penumbra adalah daerah bayangan kabur transisi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_074',
      questionText: 'Gaya gravitasi bulan dan matahari merupakan penyebab utama terjadinya fenomena:',
      options: ['Pasang dan surut air laut', 'Angin darat dan angin laut', 'Gempa bumi tektonik', 'Tsunami'],
      correctOptionIndex: 0,
      explanation: 'Tarikan gravitasi bulan menarik massa air laut menyebabkan pasang surut.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_075',
      questionText: 'Lapisan udara yang menyelimuti bumi dinamakan:',
      options: ['Atmosfer', 'Hidrosfer', 'Litosfer', 'Biosfer'],
      correctOptionIndex: 0,
      explanation: 'Atmosfer adalah lapisan gas penutup bumi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_076',
      questionText: 'Lapisan atmosfer terendah tempat terjadinya cuaca, hujan, dan awan adalah:',
      options: ['Troposfer', 'Stratosfer', 'Mesosfer', 'Termosfer'],
      correctOptionIndex: 0,
      explanation: 'Troposfer (0-12 km) tempat dinamika cuaca terjadi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_077',
      questionText: 'Lapisan atmosfer yang mengandung lapisan ozon pelindung bumi dari sinar ultraviolet adalah:',
      options: ['Stratosfer', 'Troposfer', 'Mesosfer', 'Eksosfer'],
      correctOptionIndex: 0,
      explanation: 'Stratosfer memuat ozon (O₃) penyerap radiasi UV.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_078',
      questionText: 'Lapisan atmosfer yang berfungsi membakar meteor yang jatuh menuju bumi dinamakan:',
      options: ['Mesosfer', 'Troposfer', 'Stratosfer', 'Ionosfer'],
      correctOptionIndex: 0,
      explanation: 'Mesosfer menghancurkan benda langit karena gesekan atmosfer.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_079',
      questionText: 'Lapisan batuan kerak bumi tempat manusia tinggal dinamakan:',
      options: ['Litosfer', 'Hidrosfer', 'Biosfer', 'Barisfer'],
      correctOptionIndex: 0,
      explanation: 'Litosfer adalah lapisan padat kerak dan mantel atas bumi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_080',
      questionText: 'Siklus air (siklus hidrologi) diawali dengan proses penguapan air laut/sungai oleh matahari yang disebut:',
      options: ['Evaporasi', 'Kondensasi', 'Presipitasi', 'Infiltrasi'],
      correctOptionIndex: 0,
      explanation: 'Evaporasi adalah penguapan air cair menjadi uap gas.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_081',
      questionText: 'Proses perubahan uap air menjadi awan (titik-titik air) dalam siklus hidrologi dinamakan:',
      options: ['Kondensasi', 'Evaporasi', 'Presipitasi', 'Transpirasi'],
      correctOptionIndex: 0,
      explanation: 'Kondensasi memadatkan uap air menjadi awan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_082',
      questionText: 'Proses jatuhnya air dari awan ke permukaan bumi dalam bentuk hujan dinamakan:',
      options: ['Presipitasi', 'Evaporasi', 'Infiltrasi', 'Transpirasi'],
      correctOptionIndex: 0,
      explanation: 'Presipitasi adalah curah hujan/salju.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_083',
      questionText: 'Proses penyerapan air hujan ke dalam pori-pori tanah dinamakan:',
      options: ['Infiltrasi', 'Presipitasi', 'Evaporasi', 'Sublimasi'],
      correctOptionIndex: 0,
      explanation: 'Infiltrasi mengalirkan air permukaan masuk menjadi air tanah.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_084',
      questionText: 'Penguapan air yang berasal dari jaringan tubuh tumbuhan dinamakan:',
      options: ['Transpirasi', 'Evaporasi', 'Kondensasi', 'Respirasi'],
      correctOptionIndex: 0,
      explanation: 'Transpirasi adalah pelepasan uap air oleh stomata tumbuhan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_085',
      questionText: 'Jenis tanah yang subur berasal dari pelapukan abu vulkanik gunung berapi dinamakan:',
      options: ['Tanah Vulkanik (Andosol)', 'Tanah Humus', 'Tanah Gambut', 'Tanah Liat'],
      correctOptionIndex: 0,
      explanation: 'Tanah vulkanik kaya unsur hara dari letusan gunung api.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_086',
      questionText: 'Tanah yang terbentuk dari sisa-sisa tumbuhan yang membusuk di lapisan atas hutan dinamakan:',
      options: ['Tanah Humus', 'Tanah Pasir', 'Tanah Kapur', 'Tanah Aluvial'],
      correctOptionIndex: 0,
      explanation: 'Humus berwarna gelap dan sangat subur bagi tanaman.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_087',
      questionText: 'Jenis tanah hasil endapan lumpur sungai yang subur di daerah dataran rendah dinamakan:',
      options: ['Tanah Aluvial', 'Tanah Latosol', 'Tanah Podsolik', 'Tanah Gambut'],
      correctOptionIndex: 0,
      explanation: 'Tanah aluvial diendapkan oleh aliran sungai.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_088',
      questionText: 'Upaya pelestarian alam dengan menanam kembali pohon di hutan yang gundul dinamakan:',
      options: ['Reboisasi', 'Terasering', 'Rehabilitasi', 'Konservasi'],
      correctOptionIndex: 0,
      explanation: 'Reboisasi mengembalikan fungsi penyerapan air hutan.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_089',
      questionText: 'Metode bercocok tanam membuat sengkedan bertingkat di lereng gunung untuk mencegah erosi disebut:',
      options: ['Terasering', 'Reboisasi', 'Urban Farming', 'Hidroponik'],
      correctOptionIndex: 0,
      explanation: 'Terasering menahan aliran air tanah miring agar tanah tidak tergerus.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_090',
      questionText: 'Kawasan suaka alam yang melindungi hewan-hewan langka dari kepunahan dinamakan:',
      options: ['Suaka Margasatwa', 'Cagar Alam', 'Taman Nasional', 'Hutan Lindung'],
      correctOptionIndex: 0,
      explanation: 'Suaka margasatwa dikhususkan perlindungan faunanya.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_091',
      questionText: 'Kawasan yang melindungi keutuhan flora (tumbuhan), fauna, dan ekosistem unik di dalamnya dinamakan:',
      options: ['Cagar Alam', 'Suaka Margasatwa', 'Taman Ria', 'Kebun Raya'],
      correctOptionIndex: 0,
      explanation: 'Cagar alam melindungi keanekaragaman hayati secara menyeluruh.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_092',
      questionText: 'Hewan endemik khas Indonesia Komodo (Varanus komodoensis) hidup secara alami di provinsi:',
      options: ['Nusa Tenggara Timur (NTT)', 'Nusa Tenggara Barat (NTB)', 'Bali', 'Sulawesi Selatan'],
      correctOptionIndex: 0,
      explanation: 'Komodo hidup di Taman Nasional Komodo, NTT.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_093',
      questionText: 'Burung Cenderawasih merupakan fauna khas yang berasal dari wilayah Indonesia bagian:',
      options: ['Timur (Papua)', 'Barat (Sumatera)', 'Tengah (Sulawesi)', 'Jawa'],
      correctOptionIndex: 0,
      explanation: 'Cenderawasih adalah burung endemik tanah Papua.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_094',
      questionText: 'Adaptasi unta di padang pasir dengan memiliki punuk berfungsi untuk menyimpang cadangan:',
      options: ['Lemak', 'Air murni', 'Darah', 'Protein'],
      correctOptionIndex: 0,
      explanation: 'Punuk unta menyimpan cadangan lemak yang dioksidasi menjadi energi dan air.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_095',
      questionText: 'Kemampuan cicak memutuskan ekornya untuk mengelabuhi musuh dinamakan:',
      options: ['Autotomi', 'Mimikri', 'Ekolokasi', 'Kamuflase'],
      correctOptionIndex: 0,
      explanation: 'Autotomi adalah pelepasan anggota tubuh (ekor) saat terancam.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_096',
      questionText: 'Kemampuan bunglon mengubah warna kulitnya sesuai tempat lingkungan berada dinamakan:',
      options: ['Mimikri', 'Autotomi', 'Hibernasi', 'Estivasi'],
      correctOptionIndex: 0,
      explanation: 'Mimikri menguba ketersediaan warna pigmen kulit sesuai kondisi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_097',
      questionText: 'Tumbuhan kantong semar dan embun matahari beradaptasi menangkap serangga untuk memenuhi kebutuhan:',
      options: ['Nitrogen', 'Karbohidrat', 'Air', 'Oksigen'],
      correctOptionIndex: 0,
      explanation: 'Tumbuhan karnivora menyerap nitrogen dari tubuh serangga.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_098',
      questionText: 'Pohon jati menggugurkan daunnya pada musim kemarau bertujuan untuk:',
      options: ['Mengurangi penguapan air (transpirasi)', 'Mempercepat fotosintesis', 'Menarik serangga', 'Menyimpan oksigen'],
      correctOptionIndex: 0,
      explanation: 'Menggugurkan daun (merangas) menghemat cadangan air tanah saat kemarau.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_099',
      questionText: 'Alat peraga IPA berupa globe dan lampu senter di kelas SD paling tepat untuk memperagakan konsep:',
      options: ['Gerhana dan Terjadinya Siang-Malam', 'Siklus air', 'Magnetisasi', 'Pencernaan makanan'],
      correctOptionIndex: 0,
      explanation: 'Senter memodelkan sinar matahari dan globe memodelkan rotasi bumi.',
    ),
    QuestionItem(
      id: 'pgsd_ipa_100',
      questionText: 'Tujuan utama pembelajaran IPA di Sekolah Dasar melalui pendekatan Sains Teknologi Masyarakat (STM) adalah:',
      options: ['Mengembangkan keterampilan proses sains dan kepedulian lingkungan kehidupan nyata', 'Menghafal rumus fisika', 'Menjadi teknisi laboratorium', 'Menghafal istilah latin'],
      correctOptionIndex: 0,
      explanation: 'IPA SD membangun literasi sains dasar dan sikap ilmiah terhadap alam sekitar.',
    ),
  ];
}
