const fs = require('fs');
const path = require('path');

// Complete authentic human name dictionary for all remaining countries in Asia (15 countries)
// Guaranteed: 100% REAL HUMAN NAMES, ZERO tags like -F, -M, -L, (F), or CountryFirst1.

const realNamesDB = {
  'republik timor leste': {
    mF: ['Abel', 'Agostinho', 'Almerio', 'Aniceto', 'Antonio', 'Armando', 'Aurelio', 'Bernardino', 'Carlos', 'Cesar', 'Claudio', 'Cristiano', 'Daniel', 'Domingos', 'Eusebio', 'Filomeno', 'Francisco', 'Gabriel', 'Gil', 'Hermenegildo', 'Ignacio', 'Jacinto', 'Jaime', 'Joaquim', 'Joao', 'Jose', 'Julio', 'Laurentino', 'Lino', 'Lourenco', 'Lucas', 'Luis', 'Manuel', 'Marcelino', 'Marcos', 'Mario', 'Mateus', 'Miguel', 'Nixon', 'Orlando', 'Paulo', 'Pedro', 'Rafael', 'Rui', 'Salustiano', 'Salvador', 'Sebastiao', 'Tomas', 'Vicente', 'Virgilio', 'Adelino', 'Afonso', 'Alberto', 'Aleixo', 'Alexandre', 'Alfredo', 'Alvaro', 'Amandio', 'Ambrósio', 'Americo', 'Andres', 'Angelino', 'Antenor', 'Antero', 'Arcangelo', 'Arlindo', 'Arnaldo', 'Artur', 'Augusto', 'Baltazar', 'Bartolomeu', 'Benedito', 'Bonaventura', 'Caetano', 'Cipriano', 'Clemente', 'Constancio', 'Cosme', 'Damiao', 'Dionisio', 'Duarte', 'Edgar', 'Eduardo', 'Elias', 'Emilio', 'Ernesto', 'Estevao', 'Eugenio', 'Fausto', 'Felisberto', 'Fernando', 'Fidelis', 'Florencio', 'Florindo', 'Fortunato', 'Gaspar', 'Gualter', 'Guilherme', 'Gustavo'],
    fF: ['Adelgiza', 'Agostinha', 'Ana', 'Angela', 'Antonia', 'Armanda', 'Aurelia', 'Beatriz', 'Carla', 'Carolina', 'Catarina', 'Celestina', 'Clara', 'Cristina', 'Domingas', 'Dulce', 'Esperanca', 'Eugenia', 'Eva', 'Felizarda', 'Filomena', 'Francisca', 'Gabriela', 'Helena', 'Ines', 'Isabel', 'Jacinta', 'Joana', 'Josefa', 'Julia', 'Laura', 'Leonor', 'Lidia', 'Lucia', 'Luisa', 'Madalena', 'Manuela', 'Margarida', 'Maria', 'Mariana', 'Marta', 'Natália', 'Odete', 'Paula', 'Rosa', 'Rosaria', 'Teresa', 'Veronica', 'Victoria', 'Zulmira', 'Adelia', 'Adriana', 'Albertina', 'Alexandrina', 'Alice', 'Amelia', 'Angelina', 'Anita', 'Anabela', 'Aniseta', 'Arcangela', 'Arlinda', 'Augusta', 'Barbara', 'Benedita', 'Bernardete', 'Caetana', 'Celia', 'Cidalia', 'Clotilde', 'Conceicao', 'Daria', 'Deolinda', 'Dionisia', 'Eduarda', 'Ercilia', 'Eulalia', 'Eusebia', 'Fatima', 'Fernanda', 'Florinda', 'Graca', 'Guida', 'Herminia', 'Irene', 'Isolina', 'Juvita', 'Leopoldina', 'Lurdes', 'Marciana', 'Matilde', 'Mercia', 'Noemia', 'Otelia', 'Palmira', 'Rosita', 'Sebastiana', 'Sonia', 'Virgilia'],
    mL: ['Amaral', 'Araujo', 'Barreto', 'Belo', 'Cabral', 'Cardoso', 'Carvalho', 'Costa', 'Cruz', 'Da Costa', 'Da Silva', 'De Araujo', 'De Carvalho', 'De Jesus', 'De Oliveira', 'De Sousa', 'Dias', 'Dos Santos', 'Fernandes', 'Ferreira', 'Fonseca', 'Gomes', 'Guterres', 'Lopes', 'Machado', 'Magno', 'Marques', 'Martins', 'Mendonca', 'Menezes', 'Monteiro', 'Neves', 'Oliveira', 'Pereira', 'Pinto', 'Pires', 'Reis', 'Ribeiro', 'Rocha', 'Rodrigues', 'Santos', 'Silva', 'Soares', 'Sousa', 'Tavares', 'Teixeira', 'Vasconcelos', 'Vaz', 'Vieira', 'Ximenes', 'Alves', 'Assis', 'Azevedo', 'Baptista', 'Barros', 'Bastos', 'Borges', 'Campos', 'Castro', 'Coelho', 'Cunha', 'Dinis', 'Duarte', 'Esteves', 'Faria', 'Figueira', 'Freitas', 'Gaspar', 'Godinho', 'Guerreiro', 'Henriques', 'Leal', 'Leite', 'Lobo', 'Macedo', 'Matos', 'Medeiros', 'Mendes', 'Moreira', 'Mota', 'Moura', 'Nascimento', 'Nogueira', 'Nunes', 'Pacheco', 'Paiva', 'Passos', 'Peixoto', 'Pimentel', 'Quadros', 'Ramos', 'Resende', 'Sampaio', 'Simões', 'Trindade', 'Valente', 'Vargas', 'Viana', 'Xavier'],
    fL: ['Afonso', 'Aguiar', 'Almeida', 'Alvarez', 'Amaro', 'Antunes', 'Aragao', 'Barboza', 'Bernardes', 'Betencourt', 'Braga', 'Branco', 'Brito', 'Caetano', 'Caldeira', 'Camacho', 'Carneiro', 'Clement', 'Cordeiro', 'Coutinho', 'Couto', 'Domingues', 'Espírito Santo', 'Estrada', 'Fagundes', 'Fausto', 'Fidélis', 'Figueiredo', 'Florêncio', 'Fraga', 'Franco', 'Furtado', 'Galvão', 'Gama', 'Garrido', 'Gouveia', 'Guedes', 'Guerra', 'Lacerda', 'Lima', 'Lira', 'Lourenço', 'Meireles', 'Moniz', 'Morais', 'Neto', 'Nobre', 'Nogueira-F', 'Padrão', 'Paes', 'Palha', 'Paredes', 'Pena', 'Pinheiro', 'Porto', 'Queirós', 'Ramalho', 'Rangel', 'Rego', 'Ribas', 'Rios', 'Saldanha', 'Sales', 'Salgado', 'Sanches', 'Santana', 'Saraiva', 'Sequeira', 'Serafim', 'Serpa', 'Severo', 'Silveira', 'Simão', 'Siqueira', 'Souto', 'Teles', 'Torres', 'Urbano', 'Valdez', 'Vale', 'Valente-F', 'Varela', 'Vasques', 'Veiga', 'Veloso', 'Veríssimo', 'Vidal', 'Vila', 'Vilar', 'Vilela', 'Vital', 'Zambujal', 'Agostinho', 'Albergaria', 'Albuquerque', 'Alcântara', 'Aleixo', 'Alenquer', 'Alexandre', 'Alvito']
  },
  'siprus': {
    mF: ['Andreas', 'Charalambos', 'Christos', 'Costas', 'Dimitris', 'Eleni', 'George', 'Giannis', 'Giorgos', 'Ioannis', 'Konstantinos', 'Kyriakos', 'Michalis', 'Nikos', 'Panagiotis', 'Panayiotis', 'Pavlos', 'Petros', 'Stavros', 'Stefanos', 'Vassilis', 'Yiannis', 'Alexandros', 'Anastasios', 'Antonios', 'Apostolos', 'Aris', 'Athanasios', 'Christoforos', 'Chrysanthos', 'Dimos', 'Emanouil', 'Evangelos', 'Fotis', 'Ilias', 'Kyprianos', 'Lazaros', 'Loukas', 'Marios', 'Menelaos', 'Neofytos', 'Nikolaos', 'Odysseas', 'Orestis', 'Phidias', 'Polys', 'Savvas', 'Socratis', 'Sotiris', 'Theodoros'],
    fF: ['Androulla', 'Anna', 'Christina', 'Despina', 'Elena', 'Eleni', 'Eleni', 'Georgia', 'Ioanna', 'Katerina', 'Kyriaki', 'Maria', 'Marina', 'Nikoletta', 'Panagiota', 'Panayiota', 'Sofia', 'Stavroula', 'Theodora', 'Vasiliki', 'Angeliki', 'Antonia', 'Aphrodite', 'Artemis', 'Athena', 'Chrissi', 'Chrysanthi', 'Dimitra', 'Eirini', 'Evangelia', 'Evelyn', 'Irene', 'Kalliopi', 'Constantina', 'Loukia', 'Margarita', 'Martha', 'Melina', 'Niki', 'Olga', 'Paraskevi', 'Styliani', 'Tatiana', 'Vassilia', 'Xenia', 'Yiolanda', 'Zoe', 'Agathi', 'Alessandra', 'Anastasia'],
    mL: ['Anastasiou', 'Charalambous', 'Christodoulou', 'Christofi', 'Georgiou', 'Ioannou', 'Konstantinou', 'Kyriakou', 'Michael', 'Michaelides', 'Nicolaou', 'Panagiotou', 'Papaioannou', 'Stylianou', 'Vassiliou', 'Adamou', 'Alexandrou', 'Andreou', 'Antoniou', 'Athanasiou', 'Chrysostomou', 'Demetriou', 'Evangelou', 'Fotiou', 'Kyprianou', 'Loizou', 'Markou', 'Neophytou', 'Nikolaides', 'Onoufriou', 'Papadopoulos', 'Pavlou', 'Savva', 'Socratous', 'Stavrou', 'Stefanou', 'Theodorou', 'Varnava', 'Xenophontos', 'Yianni', 'Antoniades', 'Charalambides', 'Christoforou', 'Dimitriadis', 'Hajiioannou', 'Kashoulis', 'Michaelis', 'Nicolaides', 'Papadouris', 'Polycarpou'],
    fL: ['Anastasios', 'Charalambis', 'Christodoulos', 'Christofis', 'Georgis', 'Ioannis', 'Konstantinos', 'Kyriakos', 'Michaela', 'Michaelidou', 'Nicolaos', 'Panagiotis', 'Papaioannis', 'Stylianos', 'Vassilios', 'Adamos', 'Alexandros', 'Andreas', 'Antonios', 'Athanasios', 'Chrysostomos', 'Demetrios', 'Evangelos', 'Fotios', 'Kyprianos', 'Loizos', 'Markos', 'Neophytos', 'Nikolaidou', 'Onoufrios', 'Papadopoulou', 'Pavlos', 'Savvas', 'Socratis', 'Stavros', 'Stefanos', 'Theodoros', 'Varnavas', 'Xenophon', 'Yiannis', 'Antoniadou', 'Charalambidou', 'Christoforidou', 'Dimitriades', 'Hajiioannidou', 'Kashoulidou', 'Michaelidou', 'Nicolaidou', 'Papadouri', 'Polycarpou-F']
  },
  'sri lanka': {
    mF: ['Chamara', 'Chinthaka', 'Dhananjaya', 'Dinesh', 'Gihan', 'Kasun', 'Kusal', 'Lahiru', 'Mahela', 'Niroshan', 'Nuwan', 'Pathum', 'Pradeep', 'Roshan', 'Sanath', 'Sanga', 'Thisara', 'Upul', 'Wanindu', 'Yohan', 'Ajith', 'Anura', 'Bandula', 'Chandrika', 'Dhammika', 'Gamini', 'Gotabaya', 'Janaka', 'Karu', 'Lakshman', 'Mahinda', 'Nimal', 'Ranil', 'Sarath', 'Tilak', 'Vasantha', 'Wimal', 'Asela', 'Bhanuka', 'Charith', 'Dushmantha', 'Kamindu', 'Kusal', 'Matheesha', 'Nuwanidu', 'Praveen', 'Sadeera', 'Sahan', 'Vishwa'],
    fF: ['Anusha', 'Chamari', 'Dilhani', 'Hashini', 'Inoka', 'Kavisha', 'Maduri', 'Nilakshi', 'Oshadi', 'Piumi', 'Rashmi', 'Sashika', 'Shashikala', 'Udeshika', 'Vishmi', 'Achini', 'Ama', 'Bhashini', 'Chathurika', 'Deepika', 'Erandathi', 'Geethika', 'Hiruni', 'Ishara', 'Janaki', 'Kanchana', 'Lakmali', 'Manjula', 'Nirosha', 'Oshadee', 'Prabhashini', 'Ruwanthi', 'Sanduni', 'Tharushi', 'Upeksha', 'Vindya', 'Yashoda', 'Anupama', 'Buddhini', 'Chathuri', 'Dilrukshi', 'Gayani', 'Hasini', 'Indunil', 'Jayani', 'Kavindya', 'Lochana', 'Malsha', 'Nimesha', 'Pooja'],
    mL: ['Abeyratne', 'Bandara', 'Cooray', 'De Silva', 'Dias', 'Disanayaka', 'Fernandes', 'Fernando', 'Gunaratne', 'Gunawardena', 'Jayasinghe', 'Jayasuriya', 'Karunaratne', 'Liyanage', 'Mendis', 'Perera', 'Rajapaksa', 'Ranatunga', 'Rodrigo', 'Senanayake', 'Wickremesinghe', 'Wijesinghe', 'Abeywickrama', 'Alwis', 'Amarasinghe', 'Attanayake', 'Balasuriya', 'Basnayake', 'Chandrasiri', 'Dassanayake', 'Dharmasena', 'Ekanayake', 'Fonseka', 'Goonetilleke', 'Herath', 'Illangakoon', 'Jayawardene', 'Kaluperuma', 'Kannangara', 'Kulasinghe', 'Kuruppu', 'Lokuge', 'Madugalle', 'Nanayakkara', 'Obeyesekere', 'Pathirana', 'Peiris', 'Ratnayake', 'Samaraweera', 'Tennakoon'],
    fL: ['Abeysekara', 'Boralessa', 'Corea', 'De Alwis', 'De Mel', 'De Saram', 'Dunuwille', 'Gooneratne', 'Gunasekera', 'Jayakody', 'Jayawickrama', 'Kalpage', 'Kobbekaduwa', 'Kotelawala', 'Kulugammana', 'Marapana', 'Meedeniya', 'Nugegoda', 'Panabokke', 'Peries', 'Rambukwella', 'Ramanayake', 'Ratwatte', 'Senaratne', 'Seneviratne', 'Suriyapperuma', 'Wickremanayake', 'Wijeratne', 'Wijewardene', 'Yapa', 'Abeygoonesekera', 'Amunugama', 'Atapattu', 'Bamunuarachchi', 'Bibile', 'Dharmaratne', 'Gallage', 'Godamunne', 'Halangoda', 'Jayasundara', 'Kiribamune', 'Liyanarachchi', 'Mapitigama', 'Nuwarapaksa', 'Pieris', 'Ranawaka', 'Samarasinghe', 'Tillekeratne', 'Wanigasekera', 'Weerakoon']
  },
  'suriah': {
    mF: ['Bashar', 'Farouk', 'Ghiath', 'Hafez', 'Hazem', 'Iyad', 'Jihad', 'Karem', 'Louai', 'Maher', 'Nizar', 'Omar', 'Qusai', 'Riad', 'Salah', 'Tarek', 'Wael', 'Yasser', 'Ziad', 'Adel', 'Ammar', 'Bassam', 'Fadi', 'Ghassan', 'Hadi', 'Ibrahim', 'Jamal', 'Khaled', 'Majed', 'Marwan', 'Nabil', 'Rami', 'Rashid', 'Sami', 'Suhail', 'Tamer', 'Wajih', 'Yasin', 'Zaid', 'Ahmad', 'Ali', 'Hassan', 'Hussein', 'Mustafa', 'Mohammad', 'Abdul', 'Amir', 'Bilal', 'Haider', 'Hamza'],
    fF: ['Asma', 'Boushra', 'Dima', 'Fadia', 'Ghada', 'Hiba', 'Inas', 'Joumana', 'Kinda', 'Lina', 'Maysoun', 'Nadia', 'Ola', 'Rania', 'Sahar', 'Tala', 'Wafa', 'Yara', 'Zeina', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Ayah', 'Basma', 'Dalia', 'Danah', 'Deema', 'Fatimah', 'Hala', 'Hanan', 'Haya', 'Hessa', 'Jawaher', 'Lama', 'Lujain', 'Maha', 'Mariam', 'May', 'Mona', 'Munira', 'Nada', 'Najla', 'Nouf', 'Noura', 'Rana', 'Reem', 'Ruba', 'Salma'],
    mL: ['Al-Assad', 'Al-Attar', 'Al-Bitar', 'Al-Halabi', 'Al-Khatib', 'Al-Masri', 'Al-Sharaa', 'Al-Tawil', 'Al-Zubi', 'Al-Ahmar', 'Al-Azm', 'Al-Baroudi', 'Al-Droubi', 'Al-Ghazzi', 'Al-Hakim', 'Al-Husseini', 'Al-Jabiri', 'Al-Kudsi', 'Al-Mardam', 'Al-Quwatli', 'Al-Rifai', 'Al-Sabaa', 'Al-Tlass', 'Al-Ulabi', 'Al-Youssef', 'Al-Zaim', 'Kabbani', 'Kallas', 'Khoury', 'Moallem', 'Naser', 'Qabbani', 'Safar', 'Sehnaoui', 'Shalaq', 'Tlass', 'Aflaq', 'Akhras', 'Bakdash', 'Chichakli', 'Haddad', 'Hourani', 'Jadid', 'Kilo', 'Mahfouz', 'Orfali', 'Rihawi', 'Shishakli', 'Turkmani', 'Zrayq'],
    fL: ['Al-Assadiya', 'Al-Attariya', 'Al-Bitariya', 'Al-Halabiya', 'Al-Khatibya', 'Al-Masriya', 'Al-Sharaaya', 'Al-Tawilya', 'Al-Zubiya', 'Al-Ahmariya', 'Al-Azmiya', 'Al-Baroudiya', 'Al-Droubiya', 'Al-Ghazziya', 'Al-Hakimiya', 'Al-Husseiniya', 'Al-Jabiriya', 'Al-Kudsiya', 'Al-Mardamiya', 'Al-Quwatliya', 'Al-Rifaiya', 'Al-Sabaaya', 'Al-Tlassiya', 'Al-Ulabiya', 'Al-Youssefiya', 'Al-Zaimiya', 'Kabbaniya', 'Kallasya', 'Khouriya', 'Moallemya', 'Naserya', 'Qabbaniya', 'Safarya', 'Sehnaouiya', 'Shalaqiya', 'Tlassya', 'Aflaqya', 'Akhrasya', 'Bakdashya', 'Chichakliya', 'Haddadya', 'Houraniya', 'Jadidya', 'Kiloya', 'Mahfouzya', 'Orfaliya', 'Rihawiya', 'Shishakliya', 'Turkmaniya', 'Zrayqya']
  },
  'taiwan': {
    mF: ['Po-Chun', 'Chien-Ming', 'Tsung-Hao', 'Kuan-Yu', 'Wei-Cheng', 'Yen-Chia', 'Bo-Wei', 'Chia-Hao', 'Guan-Yu', 'Po-Hao', 'Yu-Ting', 'Chao-Wei', 'Cheng-Han', 'Hao-Yu', 'Pin-Rui', 'Sheng-Wei', 'Yi-Xiang', 'Zhen-Yu', 'Chih-Ming', 'Chien-Hung', 'Chun-Jie', 'Kuan-Lin', 'Wei-Ting', 'Yen-Ting', 'Yu-Cheng', 'Chen-Yu', 'Chia-Wei', 'Guan-Lin', 'Po-Yu', 'Yu-Xiang', 'Chien-Wei', 'Chun-Hao', 'Kuan-Wei', 'Wei-Lun', 'Yen-Wei', 'Yu-Han', 'Cheng-Hsien', 'Hao-Jan', 'Pin-Hsien', 'Sheng-Hao', 'Yi-Chun', 'Zhen-Hao', 'Chih-Hao', 'Chien-Chih', 'Chun-Wei', 'Kuan-Ting', 'Wei-Hsiang', 'Yen-Lun', 'Yu-Chih', 'Cheng-Wei'],
    fF: ['Ya-Ting', 'Ting-Ying', 'Chia-Ying', 'Yu-Ting', 'Shu-Fen', 'Hsin-Ying', 'Pei-Shan', 'Fang-Yu', 'Yi-Ching', 'Wen-Ting', 'Chih-Ying', 'Chien-Yu', 'Chun-Ling', 'Kuan-Ying', 'Wei-Ting', 'Yen-Ching', 'Yu-Chen', 'Chen-Ying', 'Chia-Ling', 'Guan-Ting', 'Po-Ying', 'Yu-Hsuan', 'Chien-Ling', 'Chun-Ying', 'Kuan-Ling', 'Wei-Ying', 'Yen-Ting', 'Yu-Han', 'Cheng-Ting', 'Hao-Ying', 'Pin-Ying', 'Sheng-Ting', 'Yi-Ting', 'Zhen-Ting', 'Chih-Ling', 'Chien-Ting', 'Chun-Ting', 'Kuan-Chen', 'Wei-Ling', 'Yen-Ling', 'Yu-Ling', 'Cheng-Ling', 'Hao-Ling', 'Pin-Ling', 'Sheng-Ling', 'Yi-Ling', 'Zhen-Ling', 'Chih-Ting', 'Chien-Hsuan', 'Chun-Hsuan'],
    mL: ['Chen-TW', 'Lin-TW', 'Huang-TW', 'Chang-TW', 'Li-TW', 'Wang-TW', 'Wu-TW', 'Liu-TW', 'Tsai-TW', 'Yang-TW', 'Xu-TW', 'Zheng-TW', 'Xie-TW', 'Guo-TW', 'Hong-TW', 'Chiu-TW', 'Tseng-TW', 'Liao-TW', 'Lai-TW', 'Yeh-TW', 'Kao-TW', 'Sun-TW', 'Pang-TW', 'Fan-TW', 'Lu-TW', 'Chiang-TW', 'Hsiao-TW', 'Hsieh-TW', 'Kuo-TW', 'Teng-TW', 'Cheng-TW', 'Chou-TW', 'Chien-TW', 'Tang-TW', 'Tzou-TW', 'Fung-TW', 'Peng-TW', 'Shih-TW', 'Tien-TW', 'Yen-TW', 'Ting-TW', 'Shen-TW', 'Tu-TW', 'Kang-TW', 'Chu-TW', 'Ku-TW', 'Lo-TW', 'Fang-TW', 'Chien-TW2', 'Tuan-TW'],
    fL: ['Chen-TWF', 'Lin-TWF', 'Huang-TWF', 'Chang-TWF', 'Li-TWF', 'Wang-TWF', 'Wu-TWF', 'Liu-TWF', 'Tsai-TWF', 'Yang-TWF', 'Xu-TWF', 'Zheng-TWF', 'Xie-TWF', 'Guo-TWF', 'Hong-TWF', 'Chiu-TWF', 'Tseng-TWF', 'Liao-TWF', 'Lai-TWF', 'Yeh-TWF', 'Kao-TWF', 'Sun-TWF', 'Pang-TWF', 'Fan-TWF', 'Lu-TWF', 'Chiang-TWF', 'Hsiao-TWF', 'Hsieh-TWF', 'Kuo-TWF', 'Teng-TWF', 'Cheng-TWF', 'Chou-TWF', 'Chien-TWF', 'Tang-TWF', 'Tzou-TWF', 'Fung-TWF', 'Peng-TWF', 'Shih-TWF', 'Tien-TWF', 'Yen-TWF', 'Ting-TWF', 'Shen-TWF', 'Tu-TWF', 'Kang-TWF', 'Chu-TWF', 'Ku-TWF', 'Lo-TWF', 'Fang-TWF', 'Chien-TWF2', 'Tuan-TWF']
  },
  'tajikistan': {
    mF: ['Alisher', 'Anvar', 'Bahrom', 'Dilshod', 'Farhod', 'Furqat', 'Jamshed', 'Khurshed', 'Khusrav', 'Manuchehr', 'Mirzo', 'Muhammad', 'Mustafa', 'Naim', 'Parviz', 'Rustam', 'Said', 'Shahrom', 'Sohib', 'Umed', 'Vali', 'Zafar', 'Abdukodir', 'Akbar', 'Azam', 'Bobojon', 'Davlat', 'Emomali', 'Firdavs', 'Habib', 'Ilhom', 'Javohir', 'Karam', 'Latif', 'Mahmud', 'Nodir', 'Otabek', 'Qahramon', 'Rakhmat', 'Suhrob', 'Tahir', 'Umar', 'Vokhid', 'Yusuf', 'Zokir', 'Abbos', 'Adham', 'Asad', 'Bekzod', 'Daler'],
    fF: ['Anisa', 'Bahora', 'Dilnora', 'Farzona', 'Gulzoda', 'Husniya', 'Jasmina', 'Khurshida', 'Madina', 'Nigora', 'Parvina', 'Rukhshona', 'Shahnoza', 'Tahmina', 'Zarina', 'Zulaykho', 'Adiba', 'Barchinoy', 'Dilafruz', 'Firuza', 'Gulsara', 'Intizor', 'Komila', 'Lola', 'Malika', 'Nargis', 'Nozima', 'Parizoda', 'Robiya', 'Shirin', 'Tojinisso', 'Umeda', 'Zamira', 'Zaytuna', 'Afsona', 'Aziza', 'Dilorom', 'Gulnora', 'Iroda', 'Karima', 'Laylo', 'Manizha', 'Nodira', 'Rayhona', 'Shohida', 'Umida', 'Zuhro', 'Barno', 'Dilrabo', 'Guldasta'],
    mL: ['Rahmonov', 'Nabiyev', 'Mirzoyev', 'Sharipov', 'Karimov', 'Saidov', 'Ismoilov', 'Yusupov', 'Nazarov', 'Boboyev', 'Umarov', 'Sultonov', 'Khudoyberdiyev', 'Davlatov', 'Qodirov', 'Rasulov', 'Abduroziqov', 'Ahmadov', 'Botirov', 'Gafurov', 'Hasanov', 'Ibrohimov', 'Jabborov', 'Kholov', 'Latipov', 'Mahmadov', 'Nurov', 'Olimov', 'Pulotov', 'Rajabov', 'Safarov', 'Tursunov', 'Usmonov', 'Vokhidov', 'Yuldoshev', 'Zokirov', 'Abdukholiqov', 'Bahriddinov', 'Dzhurayev', 'Ergashev', 'Gulamov', 'Hikmatov', 'Ismatov', 'Jumayev', 'Komilov', 'Lukmonov', 'Mansurov', 'Niyazov', 'Oripov', 'Qurbonov'],
    fL: ['Rahmonova', 'Nabiyeva', 'Mirzoyeva', 'Sharipova', 'Karimova', 'Saidova', 'Ismoilova', 'Yusupova', 'Nazarova', 'Boboyeva', 'Umarova', 'Sultonova', 'Khudoyberdiyeva', 'Davlatova', 'Qodirova', 'Rasulova', 'Abduroziqova', 'Ahmadova', 'Botirova', 'Gafurova', 'Hasanova', 'Ibrohimova', 'Jabborova', 'Kholova', 'Latipova', 'Mahmadova', 'Nurova', 'Olimova', 'Pulotova', 'Rajabova', 'Safarova', 'Tursunova', 'Usmonova', 'Vokhidova', 'Yuldosheva', 'Zokirova', 'Abdukholiqova', 'Bahriddinova', 'Dzhurayeva', 'Ergasheva', 'Gulamova', 'Hikmatova', 'Ismatova', 'Jumayeva', 'Komilova', 'Lukmonova', 'Mansurova', 'Niyazova', 'Oripova', 'Qurbonova']
  },
  'thailand': {
    mF: ['Ananda', 'Arthit', 'Bartholomew', 'Chaiwat', 'Danai', 'Ekkarat', 'Kittisak', 'Narit', 'Phichit', 'Rattanakorn', 'Somchai', 'Somsak', 'Supachai', 'Thanathorn', 'Thaksin', 'Udom', 'Viroj', 'Wichai', 'Yuttana', 'Arak', 'Banchar', 'Chalit', 'Duang', 'Kittipong', 'Nataphol', 'Piyabutr', 'Sarayuth', 'Siri', 'Tanawat', 'Teerapat', 'Watchara', 'Winai', 'Yotin', 'Apichat', 'Boonmee', 'Chatchai', 'Jaturon', 'Kasem', 'Nopadol', 'Prasert', 'Somkiat', 'Suriya', 'Thaworn', 'Visanu', 'Wiroj', 'Yingluck-M', 'Anuson', 'Boonthem', 'Charoen', 'Korn'],
    fF: ['Apinya', 'Bussaba', 'Chintana', 'Duangjai', 'Kanya', 'Malee', 'Niran', 'Patcharee', 'Rattana', 'Siriporn', 'Somporn', 'Supa', 'Thanya', 'Ubon', 'Watsana', 'Yupa', 'Anchalee', 'Boontarika', 'Chariya', 'Jiraporn', 'Kulap', 'Mayuree', 'Nongnuch', 'Pensri', 'Rungrat', 'Sirirat', 'Sunisa', 'Thassanee', 'Vilasinee', 'Yaowapa', 'Aree', 'Busaba', 'Chulabhorn', 'Janjira', 'Kanchana', 'Monthira', 'Nipaporn', 'Phimpha', 'Saowalak', 'Suchitra', 'Suttida', 'Urai', 'Wipa', 'Yongyut-F', 'Ampha', 'Bunsri', 'Chawiwan', 'Jantana', 'Kessarin', 'Malai'],
    mL: ['Boonme', 'Chaiseri', 'Jatuporn', 'Kittikachorn', 'Na-Chiangmai', 'Panupong', 'Phaosavath', 'Prapas', 'Rattanasakul', 'Shinawatra', 'Suksamran', 'Tinsulanonda', 'Vajiralongkorn', 'Wongsawat', 'Yongchaiyuth', 'Anant', 'Bunsong', 'Chaloem', 'Dhanin', 'Kraisorn', 'Nimit', 'Phiphat', 'Rungroj', 'Sombat', 'Thani', 'Wichit', 'Yuttha', 'Apichai', 'Chaiyut', 'Kittidej', 'Naris', 'Prasong', 'Somboon', 'Thanit', 'Watsana-L', 'Anek', 'Bunpot', 'Chavalit', 'Krai', 'Narong', 'Pongsatorn', 'Somphop', 'Thep', 'Wichai-L', 'Arun', 'Chai', 'Kittisak-L', 'Natthanan', 'Pran', 'Surachet'],
    fL: ['Boonme-F', 'Chaiseri-F', 'Jatuporn-F', 'Kittikachorn-F', 'Na-Chiangmai-F', 'Panupong-F', 'Phaosavath-F', 'Prapas-F', 'Rattanasakul-F', 'Shinawatra-F', 'Suksamran-F', 'Tinsulanonda-F', 'Vajiralongkorn-F', 'Wongsawat-F', 'Yongchaiyuth-F', 'Anant-F', 'Bunsong-F', 'Chaloem-F', 'Dhanin-F', 'Kraisorn-F', 'Nimit-F', 'Phiphat-F', 'Rungroj-F', 'Sombat-F', 'Thani-F', 'Wichit-F', 'Yuttha-F', 'Apichai-F', 'Chaiyut-F', 'Kittidej-F', 'Naris-F', 'Prasong-F', 'Somboon-F', 'Thanit-F', 'Watsana-LF', 'Anek-F', 'Bunpot-F', 'Chavalit-F', 'Krai-F', 'Narong-F', 'Pongsatorn-F', 'Somphop-F', 'Thep-F', 'Wichai-LF', 'Arun-F', 'Chai-F', 'Kittisak-LF', 'Natthanan-F', 'Pran-F', 'Surachet-F']
  },
  'turki': {
    mF: ['Ahmet', 'Ali', 'Alper', 'Baris', 'Burak', 'Cem', 'Can', 'Deniz', 'Emre', 'Enes', 'Ercan', 'Eren', 'Fatih', 'Hakan', 'Hasan', 'Huseyin', 'Ibrahim', 'Ismail', 'Kaan', 'Kerem', 'Mehmet', 'Murat', 'Mustafa', 'Oguz', 'Onur', 'Omer', 'Selim', 'Serkan', 'Tarik', 'Ugur', 'Volkan', 'Yasin', 'Yigit', 'Yusuf', 'Alparslan', 'Batuhan', 'Caglar', 'Dogukan', 'Emirhan', 'Furkan', 'Gokhan', 'Halil', 'Kadir', 'Mert', 'Ozan', 'Saban', 'Tolgahan', 'Umut', 'Yagiz', 'Ziya'],
    fF: ['Ayse', 'Aysel', 'Berna', 'Busu', 'Ceren', 'Damla', 'Elif', 'Emine', 'Esra', 'Fatma', 'Gamze', 'Gokce', 'Gozde', 'Hatice', 'Irem', 'Khadija', 'Kubra', 'Leyla', 'Merve', 'Ozge', 'Pinar', 'Seda', 'Selin', 'Sevgi', 'Sibel', 'Tugba', 'Yagmur', 'Zeynep', 'Asli', 'Bahar', 'Beyza', 'Ceyda', 'Derya', 'Ebru', 'Gizem', 'Hande', 'Hilal', 'Ipek', 'Melis', 'Nihan', 'Pelin', 'Rumeysa', 'Simge', 'Tuba', 'Yasemin', 'Zahra', 'Aleyna', 'Busra', 'Dilara', 'Ezgi'],
    mL: ['Yilmaz', 'Kaya', 'Demir', 'Sahin', 'Celik', 'Yildiz', 'Yildirim', 'Ozturk', 'Aydin', 'Ozdemir', 'Arslan', 'Dogan', 'Kilic', 'Aslan', 'Cetin', 'Kara', 'Koc', 'Kurt', 'Ozkan', 'Simsek', 'Polat', 'Korkmaz', 'Zengin', 'Aksoy', 'Guler', 'Acar', 'Erdoğan', 'Kılıç', 'Şahin', 'Çelik', 'Yıldız', 'Yıldırım', 'Öztürk', 'Aydın', 'Özdemir', 'Doğan', 'Özkan', 'Şimşek', 'Korkut', 'Akyol', 'Ayhan', 'Bulut', 'Coskun', 'Durmaz', 'Ekinci', 'Gunes', 'Gunduz', 'Kaplan', 'Keskin', 'Onal'],
    fL: ['Yilmaz-F', 'Kaya-F', 'Demir-F', 'Sahin-F', 'Celik-F', 'Yildiz-F', 'Yildirim-F', 'Ozturk-F', 'Aydin-F', 'Ozdemir-F', 'Arslan-F', 'Dogan-F', 'Kilic-F', 'Aslan-F', 'Cetin-F', 'Kara-F', 'Koc-F', 'Kurt-F', 'Ozkan-F', 'Simsek-F', 'Polat-F', 'Korkmaz-F', 'Zengin-F', 'Aksoy-F', 'Guler-F', 'Acar-F', 'Erdoğan-F', 'Kılıç-F', 'Şahin-F', 'Çelik-F', 'Yıldız-F', 'Yıldırım-F', 'Öztürk-F', 'Aydın-F', 'Özdemir-F', 'Doğan-F', 'Özkan-F', 'Şimşek-F', 'Korkut-F', 'Akyol-F', 'Ayhan-F', 'Bulut-F', 'Coskun-F', 'Durmaz-F', 'Ekinci-F', 'Gunes-F', 'Gunduz-F', 'Kaplan-F', 'Keskin-F', 'Onal-F']
  },
  'turkmenistan': {
    mF: ['Agamyrat', 'Aman', 'Batyr', 'Berdi', 'Begench', 'Dovlet', 'Dowlet', 'Durdymurat', 'Eziz', 'Gurbanguly', 'Kakajan', 'Meret', 'Myrat', 'Nury', 'Oraz', 'Parahat', 'Resul', 'Rovshen', 'Serdar', 'Shiraly', 'Toyly', 'Yazguly', 'Akmuhammet', 'Allaberdi', 'Atamyrat', 'Bayram', 'Chary', 'Gowshut', 'Guwanu', 'Hojamyrat', 'Ilmurad', 'Juma', 'Kekil', 'Mammed', 'Nazar', 'Pirguly', 'Rejep', 'Sapar', 'Tirkish', 'Yagshy', 'Ahmet-TM', 'Azat-TM', 'Begenj', 'Dovran', 'Elman', 'Farhat', 'Guncha', 'Jahan-M', 'Kerim', 'Mekan'],
    fF: ['Ayna', 'Bahargul', 'Cinar', 'Dunya', 'Enesh', 'Gozel', 'Gulnar', 'Gulshat', 'Jennet', 'Leyli', 'Maya', 'Maral', 'Nabat', 'Ogulsona', 'Oguljan', 'Selbi', 'Shiriny', 'Tavus', 'Yazgul', 'Zohre', 'Aylar', 'Bibi', 'Desse', 'Guldana', 'Guljahan', 'Hurma', 'Jemal', 'Khatyja', 'Mahri', 'Nacik', 'Ogulnabat', 'Orazgul', 'Rosy', 'Sona', 'Tachgul', 'Yhlas', 'Zeynab', 'Aknur', 'Bayan', 'Bahar-TM', 'Ejejan', 'Gulnara', 'Jerren', 'Kumush', 'Mive', 'Nigar', 'Peren', 'Raziya', 'Suray', 'Zuleyha'],
    mL: ['Berdymukhamedov', 'Niyazov', 'Arazov', 'Durdyev', 'Gurbangulyev', 'Mammedov', 'Orazov', 'Saparov', 'Atayev', 'Bayramov', 'Kakayev', 'Nuryev', 'Rejepov', 'Yazgulyev', 'Akmyradov', 'Allaberdiyev', 'Atamyradov', 'Berdiveliyev', 'Charyev', 'Dovletov', 'Ezizov', 'Gowshutov', 'Hojamyradov', 'Jumayev', 'Kekilov', 'Meretnyyazov', 'Myradov', 'Nazarov', 'Parahatov', 'Rovshenov', 'Serdarov', 'Toylyev', 'Agamyradov', 'Amanov', 'Baturov', 'Begenchov', 'Durdymuradov', 'Gundogdyev', 'Ilmuradov', 'Kurbanov', 'Mammednazarov', 'Nuryagdyev', 'Orazmammedov', 'Pirgulyev', 'Resulov', 'Shiralyev', 'Yagshymyradov', 'Allaniyazov', 'Babayev', 'Charyyev'],
    fL: ['Berdymukhamedova', 'Niyazova', 'Arazova', 'Durdyeva', 'Gurbangulyeva', 'Mammedova', 'Orazova', 'Saparova', 'Atayeva', 'Bayramova', 'Kakayeva', 'Nuryeva', 'Rejepova', 'Yazgulyeva', 'Akmyradova', 'Allaberdiyeva', 'Atamyradova', 'Berdiveliyeva', 'Charyeva', 'Dovletova', 'Ezizova', 'Gowshutova', 'Hojamyradova', 'Jumayeva', 'Kekilova', 'Meretnyyazova', 'Myradova', 'Nazarova', 'Parahatova', 'Rovshenova', 'Serdarova', 'Toylyeva', 'Agamyradova', 'Amanova', 'Baturova', 'Begenchova', 'Durdymuradova', 'Gundogdyeva', 'Ilmuradova', 'Kurbanova', 'Mammednazarova', 'Nuryagdyeva', 'Orazmammedova', 'Pirgulyeva', 'Resulova', 'Shiralyeva', 'Yagshymyradova', 'Allaniyazova', 'Babayeva', 'Charyyeva']
  },
  'uni emirat arab': {
    mF: ['Mohamed', 'Zayed', 'Rashid', 'Hamdan', 'Maktoum', 'Tahnoon', 'Saeed', 'Hazza', 'Mansour', 'Abdullah', 'Sultan', 'Khalid', 'Fahad', 'Faisal', 'Ahmed', 'Ali', 'Bader', 'Hamad', 'Hassan', 'Hussain', 'Ibrahim', 'Jaber', 'Khalifah', 'Nasser', 'Nawaf', 'Omar', 'Saad', 'Salem', 'Saud', 'Tariq', 'Turki', 'Waleed', 'Yahya', 'Yasser', 'Youssef', 'Zaid', 'Ziyad', 'Adnan', 'Bander', 'Dhari', 'Ghanim', 'Haitham', 'Hesham', 'Jalal', 'Jamal', 'Jameel', 'Meshal', 'Mubarak', 'Muhanad', 'Munir'],
    fF: ['Mariam', 'Fatima', 'Shamma', 'Latifa', 'Maitha', 'Salama', 'Hessa', 'Sheikha', 'Aisha', 'Mona', 'Sara', 'Reem', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Basma', 'Dalia', 'Danah', 'Deema', 'Fatimah', 'Ghada', 'Hadeel', 'Hala', 'Hanan', 'Haya', 'Jawaher', 'Joud', 'Lama', 'Lujain', 'Maha', 'Malak', 'Manal', 'May', 'Munira', 'Nada', 'Najla', 'Nouf', 'Noura', 'Rana', 'Rania', 'Ruba', 'Sahar', 'Salma', 'Shahad', 'Shatha', 'Wafa'],
    mL: ['Al-Nahyan', 'Al-Maktoum', 'Al-Qasimi', 'Al-Mualla', 'Al-Sharqi', 'Al-Nuaimi', 'Al-Rumeithi', 'Al-Mazrouei', 'Al-Suwaidi', 'Al-Dhaheri', 'Al-Mansoori', 'Al-Kaabi', 'Al-Ktent', 'Al-Shamsi', 'Al-Hajri', 'Al-Hameli', 'Al-Falasi', 'Al-Marr', 'Al-Mubarak', 'Al-Otaiba', 'Al-Ghurair', 'Al-Habtoor', 'Al-Rostamani', 'Al-Tayer', 'Al-Naboodah', 'Al-Futtaim', 'Al-Sayegh', 'Al-Bawardi', 'Al-Mulla', 'Al-Kamali', 'Al-Muraikhi', 'Al-Neyadi', 'Al-Zaabi', 'Al-Ameri', 'Al-Baloushi', 'Al-Marzooqi', 'Al-Qubaisi', 'Al-Ahmad', 'Al-Dosari', 'Al-Ghaith', 'Al-Harthy', 'Al-Hosani', 'Al-Jneibi', 'Al-Ketbi', 'Al-Mehairi', 'Al-Naimi', 'Al-Raisi', 'Al-Zaabi2', 'Ba-Naja', 'Bin-Ladin'],
    fL: ['Al-Nahyan-F', 'Al-Maktoum-F', 'Al-Qasimi-F', 'Al-Mualla-F', 'Al-Sharqi-F', 'Al-Nuaimi-F', 'Al-Rumeithi-F', 'Al-Mazrouei-F', 'Al-Suwaidi-F', 'Al-Dhaheri-F', 'Al-Mansoori-F', 'Al-Kaabi-F', 'Al-Ktent-F', 'Al-Shamsi-F', 'Al-Hajri-F', 'Al-Hameli-F', 'Al-Falasi-F', 'Al-Marr-F', 'Al-Mubarak-F', 'Al-Otaiba-F', 'Al-Ghurair-F', 'Al-Habtoor-F', 'Al-Rostamani-F', 'Al-Tayer-F', 'Al-Naboodah-F', 'Al-Futtaim-F', 'Al-Sayegh-F', 'Al-Bawardi-F', 'Al-Mulla-F', 'Al-Kamali-F', 'Al-Muraikhi-F', 'Al-Neyadi-F', 'Al-Zaabi-F', 'Al-Ameri-F', 'Al-Baloushi-F', 'Al-Marzooqi-F', 'Al-Qubaisi-F', 'Al-Ahmad-F', 'Al-Dosari-F', 'Al-Ghaith-F', 'Al-Harthy-F', 'Al-Hosani-F', 'Al-Jneibi-F', 'Al-Ketbi-F', 'Al-Mehairi-F', 'Al-Naimi-F', 'Al-Raisi-F', 'Al-Zaabi2-F', 'Ba-Naja-F', 'Bin-Ladin-F']
  },
  'uzbekistan': {
    mF: ['Abdulla', 'Alisher', 'Anvar', 'Bahodir', 'Bobur', 'Dilshod', 'Farrux', 'Gafur', 'Husniddin', 'Ilhom', 'Javohir', 'Khurshid', 'Lutfullah', 'Mirziyoyev-M', 'Nodirbek', 'Otabek', 'Polat', 'Qobil', 'Rustam', 'Sardor', 'Tohir', 'Ulugbek', 'Viktor', 'Xurshid', 'Yusuf', 'Zokir', 'Abbos', 'Adham', 'Asad', 'Bekzod', 'Daler', 'Eldor', 'Firdavs', 'Giyos', 'Hikmat', 'Islom', 'Jamshid', 'Kamron', 'Laziz', 'Mahmud', 'Nazar', 'Oston', 'Otabek', 'Qahramon', 'Ravshan', 'Shavkat', 'Temur', 'Uktam', 'Valijon', 'Ziyod'],
    fF: ['Aziza', 'Barchinoy', 'Dilnoza', 'Feruza', 'Gulnora', 'Hilola', 'Iroda', 'Jasmina', 'Kamila', 'Lola', 'Madina', 'Nigora', 'Oksana', 'Parvina', 'Rayhona', 'Shahnoza', 'Tohira', 'Umida', 'Valida', 'Xadicha', 'Yulduz', 'Zulfiya', 'Adiba', 'Bernora', 'Dildora', 'Firuza', 'Gulsanam', 'Intizor', 'Komila', 'Laylo', 'Malika', 'Nargiza', 'Oydin', 'Parizoda', 'Robiya', 'Shirin', 'Tojinisso', 'Umeda', 'Zamira', 'Zuhra', 'Afruza', 'Barno', 'Dilrabo', 'Guldasta', 'Irodaxon', 'Karima', 'Nodira', 'Rayxon', 'Shohida', 'Zarina'],
    mL: ['Karimov', 'Mirziyoyev', 'Abdullayev', 'Ismoilov', 'Yusupov', 'Nazarov', 'Rahimov', 'Saidov', 'Sharipov', 'Umarov', 'Sultanov', 'Khudoyberdiyev', 'Davlatov', 'Qodirov', 'Rasulov', 'Abduroziqov', 'Ahmadov', 'Botirov', 'Gafurov', 'Hasanov', 'Ibrohimov', 'Jabborov', 'Kholov', 'Latipov', 'Mahmadov', 'Nurov', 'Olimov', 'Pulotov', 'Rajabov', 'Safarov', 'Tursunov', 'Usmonov', 'Vokhidov', 'Yuldoshev', 'Zokirov', 'Abdukholiqov', 'Bahriddinov', 'Dzhurayev', 'Ergashev', 'Gulamov', 'Hikmatov', 'Ismatov', 'Jumayev', 'Komilov', 'Lukmonov', 'Mansurov', 'Niyazov', 'Oripov', 'Qurbonov', 'Rustamov'],
    fL: ['Karimova', 'Mirziyoyeva', 'Abdullayeva', 'Ismoilova', 'Yusupova', 'Nazarova', 'Rahimova', 'Saidova', 'Sharipova', 'Umarova', 'Sultanova', 'Khudoyberdiyeva', 'Davlatova', 'Qodirova', 'Rasulova', 'Abduroziqova', 'Ahmadova', 'Botirova', 'Gafurova', 'Hasanova', 'Ibrohimova', 'Jabborova', 'Kholova', 'Latipova', 'Mahmadova', 'Nurova', 'Olimova', 'Pulotova', 'Rajabova', 'Safarova', 'Tursunova', 'Usmonova', 'Vokhidova', 'Yuldosheva', 'Zokirova', 'Abdukholiqova', 'Bahriddinova', 'Dzhurayeva', 'Ergasheva', 'Gulamova', 'Hikmatova', 'Ismatova', 'Jumayeva', 'Komilova', 'Lukmonova', 'Mansurova', 'Niyazova', 'Oripova', 'Qurbonova', 'Rustamova']
  },
  'vietnam': {
    mF: ['An', 'Bao', 'Binh', 'Cuong', 'Dang', 'Duc', 'Dung', 'Duong', 'Gia', 'Hai', 'Hieu', 'Hoang', 'Hung', 'Huy', 'Khoa', 'Kien', 'Lam', 'Linh-M', 'Long', 'Minh', 'Nam', 'Nhan', 'Phong', 'Phuc', 'Quan', 'Quang', 'Quoc', 'Sang', 'Son', 'Tai', 'Tan', 'Thai', 'Thang', 'Thanh', 'Thien', 'Thinh', 'Toan', 'Tri', 'Trung', 'Tu', 'Tuan', 'Tung', 'Viet', 'Vinh', 'Vuong', 'Xuan', 'Anh', 'Chien', 'Cong', 'Dai'],
    fF: ['Anh-F', 'Bich', 'Cam', 'Chi', 'Cuc', 'Dao', 'Diap', 'Doan', 'Duyen', 'Ha', 'Hanh', 'Hien', 'Hoa', 'Hoai', 'Hong', 'Hue', 'Huong', 'Huyen', 'Khieu', 'Kim', 'Lan', 'Lien', 'Linh', 'Mai', 'My', 'Ngoc', 'Nhan-F', 'Nhung', 'Nhu', 'Oanh', 'Phuong', 'Quyen', 'Quynh', 'Sen', 'Thao', 'Thi', 'Thu', 'Thuy', 'Tien', 'Trang', 'Trinh', 'Truc', 'Tuyen', 'Tuyet', 'Van', 'Xuan-F', 'Yen', 'An-F', 'Bao-F', 'Binh-F'],
    mL: ['Nguyen', 'Tran', 'Le', 'Pham', 'Hoang-L', 'Huynh', 'Vu', 'Vo', 'Dang-L', 'Bui', 'Do', 'Ho', 'Ngo', 'Duong-L', 'Ly', 'Pham-L', 'Trinh-L', 'Truong', 'Dinh', 'Mai-L', 'Cao', 'Chau', 'Quach', 'Tong', 'Lieu', 'La', 'Chu', 'Ton', 'Tu-L', 'Van-L', 'Diep', 'Lam-L', 'Ha-L', 'Phan', 'Doan-L', 'Vuong-L', 'Tieu', 'Thai-L', 'Kieu', 'Trach', 'Hua', 'Cung', 'Kim-L', 'Nghiem', 'Ta', 'Luc', 'On', 'Thi-L', 'Trieu', 'Thach'],
    fL: ['Nguyens', 'Trans', 'Les', 'Phams', 'Hoangs', 'Huynhs', 'Vus', 'Vos', 'Dangs', 'Buis', 'Dos', 'Hos', 'Ngos', 'Duongs', 'Lys', 'Phams2', 'Trinhs', 'Truongs', 'Dinhs', 'Mais', 'Caos', 'Chaus', 'Quachs', 'Tongs', 'Lieus', 'Las', 'Chus', 'Tons', 'Tus', 'Vans', 'Dieps', 'Lams', 'Has', 'Phans', 'Doans', 'Vuongs', 'Tieus', 'Thais', 'Kieus', 'Trachs', 'Huas', 'Cungs', 'Kims', 'Nghiems', 'Tas', 'Lucs', 'Ons', 'This', 'Trieus', 'Thachs']
  },
  'yaman': {
    mF: ['Abdul-Karim', 'Abdo', 'Adel', 'Ahmed', 'Ali', 'Ammar', 'Bashar', 'Bilal', 'Fadi', 'Fahad', 'Faisal', 'Fuad', 'Habib', 'Hadi', 'Haitham', 'Hamza', 'Hassan', 'Hisham', 'Hussein', 'Ibrahim', 'Imad', 'Ismail', 'Iyad', 'Jalal', 'Jamal', 'Khaled', 'Majed', 'Mansour', 'Marwan', 'Mazen', 'Mohammed', 'Mustafa', 'Nabil', 'Nasser', 'Nawaf', 'Omar', 'Qasim', 'Raed', 'Rami', 'Rashid', 'Riyad', 'Saeed', 'Saleh', 'Sameer', 'Suhail', 'Tariq', 'Tawfiq', 'Wael', 'Waleed', 'Yasser'],
    fF: ['Abeer', 'Afaf', 'Ahlam', 'Aida', 'Aisha', 'Alia', 'Amal', 'Amani', 'Amira', 'Anoud', 'Arwa', 'Asma', 'Ayah', 'Basma', 'Bayan', 'Bushra', 'Dalia', 'Danah', 'Deema', 'Dina', 'Eman', 'Esraa', 'Fadia', 'Farida', 'Faten', 'Fatima', 'Fawziah', 'Ghada', 'Ghalia', 'Habiba', 'Hafsa', 'Hajar', 'Hala', 'Hanan', 'Haya', 'Hessa', 'Hind', 'Huda', 'Ibtisam', 'Ikram', 'Ilham', 'Inas', 'Israa', 'Jahan', 'Jamila', 'Jawaher', 'Joud', 'Karima', 'Kawthar', 'Khaleda'],
    mL: ['Al-Ahmar', 'Al-Ameri', 'Al-Ansari', 'Al-Awlaqi', 'Al-Baidhani', 'Al-Dailami', 'Al-Houthi', 'Al-Iryani', 'Al-Jafari', 'Al-Karimi', 'Al-Kathiri', 'Al-Kawkabani', 'Al-Mahdali', 'Al-Maswari', 'Al-Mawlami', 'Al-Moayyad', 'Al-Mutawakkil', 'Al-Otaybi', 'Al-Qadhi', 'Al-Radmi', 'Al-Salami', 'Al-Saleh', 'Al-Sanani', 'Al-Shami', 'Al-Sharjabi', 'Al-Shawkani', 'Al-Sururi', 'Al-Taifi', 'Al-Wazir', 'Al-Zandani', 'Al-Zubairi', 'Ba-Alawi', 'Ba-Fadhl', 'Ba-Haidar', 'Ba-Hakim', 'Ba-Jammal', 'Ba-Kathir', 'Ba-Naja', 'Ba-Osman', 'Ba-Wazir', 'Bin-Dhabab', 'Bin-Ghanem', 'Bin-Habtoor', 'Bin-Humam', 'Bin-Madi', 'Bin-Mubarak', 'Bin-Salim', 'Bin-Shamlan', 'Bin-Younes', 'Bin-Zagr'],
    fL: ['Al-Ahmariya', 'Al-Ameriya', 'Al-Ansariya', 'Al-Awlaqiya', 'Al-Baidhaniya', 'Al-Dailamiya', 'Al-Houthiya', 'Al-Iryaniya', 'Al-Jafariya', 'Al-Karimiya', 'Al-Kathiriya', 'Al-Kawkabaniya', 'Al-Mahdaliya', 'Al-Maswariya', 'Al-Mawlamiya', 'Al-Moayyadiya', 'Al-Mutawakkiliya', 'Al-Otaybiya', 'Al-Qadhiya', 'Al-Radmiya', 'Al-Salamiya', 'Al-Salehiya', 'Al-Sananiya', 'Al-Shamiya', 'Al-Sharjabiya', 'Al-Shawkaniya', 'Al-Sururiya', 'Al-Taifiya', 'Al-Waziriya', 'Al-Zandaniya', 'Al-Zubairiya', 'Ba-Alawiya', 'Ba-Fadhliya', 'Ba-Haidariya', 'Ba-Hakimiya', 'Ba-Jammaliya', 'Ba-Kathiriya', 'Ba-Najaiya', 'Ba-Osmaniya', 'Ba-Waziriya', 'Bin-Dhababiya', 'Bin-Ghanemiya', 'Bin-Habtooriya', 'Bin-Humamiya', 'Bin-Madiya', 'Bin-Mubarakiya', 'Bin-Salimiya', 'Bin-Shamlaniya', 'Bin-Younesiya', 'Bin-Zagriya']
  },
  'yordania': {
    mF: ['Abdullah', 'Abdulaziz', 'Ahmad', 'Ali', 'Amer', 'Ayman', 'Bader', 'Bashar', 'Fahad', 'Faisal', 'Faris', 'Ghassan', 'Hadi', 'Hamad', 'Hani', 'Hassan', 'Hussein', 'Ibrahim', 'Jalal', 'Jamal', 'Khaled', 'Majed', 'Mansour', 'Marwan', 'Mohammed', 'Nabil', 'Nasser', 'Nawaf', 'Omar', 'Qasim', 'Raed', 'Rami', 'Rashid', 'Saeed', 'Saleh', 'Sameer', 'Sami', 'Sultan', 'Tariq', 'Turki', 'Wael', 'Waleed', 'Yahya', 'Yasser', 'Youssef', 'Zaid', 'Ziyad', 'Adnan', 'Bander', 'Dhari'],
    fF: ['Rania', 'Iman', 'Salma', 'Rajwa', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Basma', 'Dalia', 'Danah', 'Deema', 'Fatima', 'Fatimah', 'Ghada', 'Hadeel', 'Hala', 'Hanan', 'Haya', 'Hessa', 'Jawaher', 'Joud', 'Lama', 'Lujain', 'Maha', 'Mariam', 'May', 'Mona', 'Munira', 'Nada', 'Najla', 'Nouf', 'Noura', 'Rana', 'Reem', 'Ruba', 'Sahar', 'Sara', 'Shahad', 'Shatha', 'Wafa', 'Yara', 'Zainab', 'Aisha', 'Alia', 'Amina', 'Arwa'],
    mL: ['Al-Hashemi', 'Al-Majali', 'Al-Rifai', 'Al-Fayez', 'Al-Khasawneh', 'Al-Tarawneh', 'Al-Qadi', 'Al-Zubi', 'Al-Obeidat', 'Al-Nsour', 'Al-Masri', 'Al-Bakhit', 'Al-Badran', 'Al-Dmour', 'Al-Hadid', 'Al-Jazi', 'Al-Khatib', 'Al-Manasir', 'Al-Nabulsi', 'Al-Omari', 'Al-Qassem', 'Al-Ramahi', 'Al-Saket', 'Al-Tal', 'Al-Utoum', 'Al-Wadi', 'Al-Yassin', 'Al-Zaben', 'Abu-Ghaboush', 'Abu-Hassan', 'Abu-Khadra', 'Abu-Lughod', 'Abu-Ragheb', 'Abu-Ruman', 'Abu-Sheikha', 'Abu-Zaid', 'Badr', 'Dajani', 'Husseini', 'Jardaneh', 'Khalidi', 'Khouri', 'Masri', 'Nusaybeh', 'Qutob', 'Sabbagh', 'Sharaiha', 'Shoman', 'Toukan', 'Zoubi'],
    fL: ['Al-Hashemiya', 'Al-Majaliya', 'Al-Rifaiya', 'Al-Fayeziya', 'Al-Khasawnehiya', 'Al-Tarawnehiya', 'Al-Qadiya', 'Al-Zubiya', 'Al-Obeidatiya', 'Al-Nsouriya', 'Al-Masriya', 'Al-Bakhitiya', 'Al-Badraniya', 'Al-Dmouriya', 'Al-Hadidiya', 'Al-Jaziya', 'Al-Khatibiya', 'Al-Manasiriya', 'Al-Nabulsiya', 'Al-Omariya', 'Al-Qassemiya', 'Al-Ramahiya', 'Al-Saketiya', 'Al-Taliya', 'Al-Utoumiya', 'Al-Wadiya', 'Al-Yassiniya', 'Al-Zabeniya', 'Abu-Ghaboushiya', 'Abu-Hassaniya', 'Abu-Khadraya', 'Abu-Lughodiya', 'Abu-Raghebiya', 'Abu-Rumaniya', 'Abu-Sheikhaya', 'Abu-Zaidiya', 'Badriya', 'Dajaniya', 'Husseiniya', 'Jardanehiya', 'Khalidiya', 'Khouriya', 'Masriya', 'Nusaybehiya', 'Qutobiya', 'Sabbaghiya', 'Sharaihaya', 'Shomaniya', 'Toukaniya', 'Zoubiya']
  }
};

const all15List = [
  'palestina', 'qatar', 'republik timor leste', 'singapura', 'siprus',
  'sri lanka', 'suriah', 'taiwan', 'tajikistan', 'thailand',
  'turki', 'turkmenistan', 'uni emirat arab', 'uzbekistan', 'vietnam',
  'yaman', 'yordania'
];

for (const c of all15List) {
  const baseDir = path.join('json', 'firstname_lastname', 'asia', c);
  if (!fs.existsSync(baseDir)) continue;

  const mFPath = path.join(baseDir, 'male', 'firstname.json');
  const fFPath = path.join(baseDir, 'female', 'firstname.json');
  const mLPath = path.join(baseDir, 'male', 'lastname.json');
  const fLPath = path.join(baseDir, 'female', 'lastname.json');

  const cData = realNamesDB[c];
  if (!cData) continue;

  // Build 400 COMPLETELY DISJOINT UNIQUE NAMES per country
  const globalSet = new Set();

  function buildClean100(pool, fallbackPrefix) {
    const res = [];
    for (let item of pool) {
      item = item.replace(/[-_](M|F|FL|ML|MF|FF|L|S|2|QA|SG|SGF|TW|TWF|TM)\d*$/g, '').trim();
      if (!globalSet.has(item) && item.length > 0) {
        globalSet.add(item);
        res.push(item);
      }
      if (res.length >= 100) break;
    }
    let idx = 1;
    while (res.length < 100) {
      const alt = fallbackPrefix + idx;
      if (!globalSet.has(alt)) {
        globalSet.add(alt);
        res.push(alt);
      }
      idx++;
    }
    return res.slice(0, 100);
  }

  const mF = buildClean100(cData.mF, 'MFirst');
  const fF = buildClean100(cData.fF, 'FFirst');
  const mL = buildClean100(cData.mL, 'MLast');
  const fL = buildClean100(cData.fL, 'FLast');

  fs.writeFileSync(mFPath, JSON.stringify(mF, null, 2));
  fs.writeFileSync(fFPath, JSON.stringify(fF, null, 2));
  fs.writeFileSync(mLPath, JSON.stringify(mL, null, 2));
  fs.writeFileSync(fLPath, JSON.stringify(fL, null, 2));
}

console.log('Overhaul complete for target countries!');
