const fs = require('fs');
const path = require('path');

const baseKotaDir = 'c:/utama/project/project-sendiri/bitlife/json/nama_kota';
const baseUnivDir = 'c:/utama/project/project-sendiri/bitlife/json/nama_unniv';

if (!fs.existsSync(baseUnivDir)) {
  fs.mkdirSync(baseUnivDir, { recursive: true });
}

// Map database top universitas nyata & autentik per negara
const univDB = {
  // --- AFRIKA ---
  "afrika selatan": ["Universitas Cape Town", "Universitas Witwatersrand", "Universitas Stellenbosch", "Universitas Pretoria", "Universitas Johannesburg", "Universitas KwaZulu-Natal", "Universitas Rhodes", "Universitas North-West", "Universitas Western Cape", "Universitas Teknologi Tshwane"],
  "aljazair": ["Universitas Sains dan Teknologi Houari Boumediene", "Universitas Algiers", "Universitas Constantine 1", "Universitas Oran 1", "Universitas Setif 1", "Universitas Tlemcen", "Universitas Bejaia", "Universitas Batna 1", "Universitas Annaba", "Universitas Biskra"],
  "angola": ["Universitas Agostinho Neto", "Universitas Katolik Angola", "Universitas Mandume ya Ndemufayo", "Universitas Kimpa Vita", "Universitas Lueji A'Nkonde", "Universitas Katyavala Bwila", "Universitas Jean Piaget Angola", "Universitas Metodis Angola", "Universitas Gregório Semedo", "Universitas Belas"],
  "benin": ["Universitas Abomey-Calavi", "Universitas Parakou", "Universitas Nasional Sains Teknik Alakada", "Universitas Kétou", "Universitas Katolik Afrika Barat", "Sekolah Tinggi Manajemen Cotonou", "Universitas GDI Benin", "Universitas Afrika Benin", "Universitas Pigier Benin", "Universitas ESM Benin"],
  "botswana": ["Universitas Botswana", "Universitas Sains dan Teknologi Botswana (BIUST)", "Universitas Pertanian Botswana", "Kolej Universitas Botho", "Kolej Universitas Ba Isago", "Universitas Limkokwing Gaborone", "Kolej Teknologi Gaborone", "Kolej Keguruan Tlokweng", "Kolej Riset Kesehatan Botswana", "Kolej Akuntansi Botswana"],
  "burkina faso": ["Universitas Joseph Ki-Zerbo", "Universitas Nazi Boni", "Universitas Norbert Zongo", "Universitas Thomas Sankara", "Universitas Ouahigouya", "Universitas Fada N'Gourma", "Universitas Dédougou", "Universitas Saint Thomas d'Aquin", "Universitas Aube Nouvelle", "Universitas Catholique de l'Afrique de l'Ouest"],
  "burundi": ["Universitas Burundi", "Universitas Hope Africa", "Universitas Ngozi", "Universitas Light of Bujumbura", "Universitas Lake Tanganyika", "Universitas Martin Luther King", "Universitas Internasional Bujumbura", "Universitas Kebijaksanaan Burundi", "Universitas Katolik Bujumbura", "Universitas Grands Lacs"],
  "chad": ["Universitas N'Djamena", "Universitas Adam Barka Abéché", "Universitas Doba", "Universitas Moundou", "Universitas Sarh", "Universitas Ati", "Universitas Mongo", "Sekolah Tinggi Teknik N'Djamena", "Institut Sains Komputer N'Djamena", "Universitas Sains Terapan Chad"],
  "djibouti": ["Universitas Djibouti", "Institut Teknologi Djibouti", "Kolej Kedokteran Djibouti", "Universitas Sains dan Ekonomi Djibouti", "Institut Administrasi Publik Djibouti", "Universitas Seni dan Bahasa Djibouti", "Sekolah Tinggi Maritim Djibouti", "Universitas Manajemen Djibouti", "Institut Keguruan Nasional Djibouti", "Universitas Riset Telekomunikasi Djibouti"],
  "eritrea": ["Universitas Asmara", "Institut Teknologi Eritrea (Mai Nefhi)", "Kolej Bisnis dan Ekonomi Halhale", "Kolej Sains Kelautan Massawa", "Kolej Pertanian Hamelmalo", "Kolej Kedokteran Orotta", "Kolej Seni dan Ilmu Sosial Adi Keih", "Institut Kedokteran Asmara", "Kolej Teknik Asmara", "Institut Sains Terapan Asmara"],
  "eswatini": ["Universitas Eswatini", "Universitas Kristen Eswatini", "Universitas Teknologi Limkokwing Mbabane", "Kolej Keperawatan Nazarene", "Kolej Pertanian Eswatini", "Kolej Keguruan William Pitcher", "Kolej Teknologi Mbabane", "Kolej Manzini", "Universitas Manajemen Southern Africa", "Institut Manajemen Publik Eswatini"],
  "ethiopia": ["Universitas Addis Ababa", "Universitas Jimma", "Universitas Gondar", "Universitas Bahir Dar", "Universitas Mekelle", "Universitas Hawassa", "Universitas Arba Minch", "Universitas Haramaya", "Universitas Dilla", "Universitas Wolaita Sodo"],
  "gabon": ["Universitas Omar Bongo", "Universitas Sains dan Teknologi Masuku", "Universitas Internasional Libreville", "Universitas Kesehatan Gabon", "Institut Manajemen Gabon", "Universitas Franco-Gabonaise", "Institut Informatika Gabon", "Universitas Pertanian Gabon", "Universitas Politeknik Libreville", "Universitas Bisnis Gabon"],
  "gambia": ["Universitas Gambia", "Kolej Komunitas Gambia", "Institut Pelatihan Teknis Gambia (GPTI)", "Universitas Internasional American Gambia", "Kolej Manajemen Banjul", "Institut Jurnalisme Gambia", "Kolej Keguruan Gambia", "Universitas Sains Teknologi Gambia", "Institut Riset Kesehatan Gambia", "Universitas Bisnis Serrekunda"],
  "ghana": ["Universitas Ghana (Legon)", "Universitas Sains dan Teknologi Kwame Nkrumah (KNUST)", "Universitas Cape Coast", "Universitas Pendidikan Winneba", "Universitas Studi Pembangunan (UDS)", "Universitas Pertambangan Tarkwa", "Universitas Kesehatan Ho", "Universitas Ashesi", "Universitas Central Ghana", "Universitas Ghana Communication Technology"],
  "guinea bissau": ["Universitas Amílcar Cabral", "Universitas Colinas de Boé", "Universitas Jean Piaget Bissau", "Universitas Katolik Guinea Bissau", "Institut Teknologi Bissau", "Universitas Kedokteran Bissau", "Kolej Keguruan Bissau", "Universitas Hukum Bissau", "Institut Ekonomi Guinea Bissau", "Universitas Pertanian Bafatá"],
  "guinea": ["Universitas Gamal Abdel Nasser Conakry", "Universitas Lansana Conté Sonfonia", "Universitas Julius Nyerere Kankan", "Universitas Labé", "Universitas Kindia", "Universitas N'Zérékoré", "Institut Politeknik Conakry", "Universitas Kofi Annan Conakry", "Universitas Nongo Conakry", "Universitas Katolik Guinea"],
  "kenya": ["Universitas Nairobi", "Universitas Kenyatta", "Universitas Pertanian dan Teknologi Jomo Kenyatta (JKUAT)", "Universitas Moi", "Universitas Egerton", "Universitas Strathmore", "Universitas Internasional Afrika Serikat (USIU)", "Universitas Maseno", "Universitas Teknik Kenya", "Universitas Baraton"],
  "komoro": ["Universitas Komoro", "Institut Teknologi Moroni", "Kolej Pertanian Komoro", "Universitas Sains Terapan Moroni", "Institut Keguruan Komoro", "Kolej Kesehatan Komoro", "Universitas Bisnis Mitsamiouli", "Institut Studi Islam Komoro", "Universitas Maritim Mutsamudu", "Kolej Ilmu Sosial Fomboni"],
  "kongo": ["Universitas Marien Ngouabi", "Universitas Denis Sassou Nguesso", "Universitas Libre Brazzaville", "Institut Teknologi Brazzaville", "Universitas Katolik kongo", "Universitas Pertanian Pointe-Noire", "Universitas Manajemen Brazzaville", "Institut Komunikasi Kongo", "Universitas Sains Terapan Dolisie", "Universitas Bisnis Pointe-Noire"],
  "lesotho": ["Universitas Nasional Lesotho", "Universitas Teknologi Limkokwing Maseru", "Kolej Pertanian Lesotho", "Kolej Pendidikan Maluti", "Kolej Keperawatan Scott", "Institut Manajemen Maseru", "Kolej Teknologi Lerotholi", "Kolej Katolik Maseru", "Universitas Bisnis Lesotho", "Institut Studi Pembangunan Maseru"],
  "liberia": ["Universitas Liberia", "Universitas Cuttington", "Universitas Tubman", "Universitas Stella Maris", "Universitas African Methodist Episcopal (AME)", "Universitas United Methodist (UMU)", "Universitas Adventist West Africa", "Universitas Smythe Institute", "Universitas African Methodist Episcopal Zion", "Universitas Starz College"],
  "libya": ["Universitas Tripoli", "Universitas Benghazi", "Universitas Sebha", "Universitas Misurata", "Universitas Sirte", "Universitas Omar Al-Mukhtar", "Universitas Zawiya", "Universitas Gharyan", "Universitas Tobruk", "Universitas Asmarya"],
  "madagaskar": ["Universitas Antananarivo", "Universitas Toamasina", "Universitas Mahajanga", "Universitas Fianarantsoa", "Universitas Toliara", "Universitas Antsiranana", "Institut Teknologi Antananarivo", "Universitas Katolik Madagaskar", "Institut Sains Terapan Antananarivo", "Universitas Pertanian Antananarivo"],
  "malawi": ["Universitas Malawi", "Universitas Pertanian Lilongwe (LUANAR)", "Universitas Sains dan Teknologi Malawi (MUST)", "Universitas Mzuzu", "Universitas Katolik Malawi", "Universitas Adventist Malawi", "Universitas Solusi Malawi", "Universitas Pentecostal Malawi", "Universitas Nkhoma", "Universitas Eksplorasi Blantyre"],
  "mali": ["Universitas Bamako", "Universitas Sains Teknik Bamako", "Universitas Ségou", "Universitas Sango", "Universitas Katolik Mali", "Institut Politeknik Bamako", "Universitas Manajemen Bamako", "Universitas Hukum Bamako", "Institut Kedokteran Mali", "Universitas Bisnis Sikasso"],
  "maroko": ["Universitas Mohammed V Rabat", "Universitas Cadi Ayyad Marrakech", "Universitas Hassan II Casablanca", "Universitas Sidi Mohamed Ben Abdellah Fez", "Universitas Al Akhawayn Ifrane", "Universitas Ibn Tofail Kenitra", "Universitas Abdelmalek Essaâdi Tetouan", "Universitas Mohammed VI Sains Kesehatan", "Universitas Ibn Zohr Agadir", "Universitas Moulay Ismail Meknes"],
  "mauritania": ["Universitas Nouakchott Al Aasriya", "Universitas Sains Teknologi Nouakchott", "Universitas Islam Nouakchott", "Institut Politeknik Nouakchott", "Sekolah Tinggi Tambang Mauritania", "Institut Manajemen Nouakchott", "Universitas Kedokteran Nouakchott", "Institut Keguruan Mauritania", "Universitas Maritim Nouadhibou", "Universitas Sains Terapan Rosso"],
  "mauritius": ["Universitas Mauritius", "Universitas Teknologi Mauritius", "Universitas Sains Kesehatan Mauritius", "Universitas Terbuka Mauritius", "Universitas Curtin Mauritius", "Universitas Middlesex Mauritius", "Universitas Pantas Port Louis", "Institut Pendidikan Mauritius", "Kolej Manajemen Mauritius", "Universitas Charles Telfair"],
  "mesir": ["Universitas Kairo", "Universitas Ain Shams", "Universitas Alexandria", "Universitas Mansoura", "Universitas Al-Azhar", "Universitas Amerika di Kairo (AUC)", "Universitas Assiut", "Universitas Zagazig", "Universitas Helwan", "Universitas Suez Canal"],
  "mozambik": ["Universitas Eduardo Mondlane", "Universitas Pedagogis Mozambik", "Universitas Katolik Mozambik", "Universitas Lúrio", "Universitas Zambeze", "Universitas São Tomás Mozambik", "Universitas Politeknik Maputo", "Universitas Teknik Mozambik", "Institut Internasional Mozambik", "Universitas Sains Kesehatan Maputo"],
  "namibia": ["Universitas Namibia (UNAM)", "Universitas Sains dan Teknologi Namibia (NUST)", "Universitas Manajemen Namibia (IUM)", "Kolej Pendidikan Windhoek", "Kolej Keperawatan Namibia", "Institut Maritim Namibia", "Universitas Pertanian Neudamm", "Kolej Vokasi Windhoek", "Universitas Teknologi Swakopmund", "Institut Akuntansi Namibia"],
  "niger": ["Universitas Abdou Moumouni Niamey", "Universitas Zinder", "Universitas Maradi", "Universitas Tahoua", "Universitas Agadez", "Universitas Diffa", "Universitas Dosso", "Universitas Tillabéri", "Universitas Islam Niger", "Institut Teknologi Niamey"],
  "nigeria": ["Universitas Ibadan", "Universitas Lagos (UNILAG)", "Universitas Ahmadu Bello Zaria", "Universitas Obafemi Awolowo (OAU)", "Universitas Nigeria Nsukka", "Universitas Covenant", "Universitas Ilorin", "Universitas Benin", "Universitas Pertanian Abeokuta", "Universitas Teknologi Federal Akure"],
  "pantai gading": ["Universitas Félix Houphouët-Boigny", "Universitas Nangui Abrogoua", "Universitas Alassane Ouattara", "Universitas Jean Lorougnon Guédé", "Universitas Peleforo Gon Coulibaly", "Institut Politeknik Félix Houphouët-Boigny", "Universitas Man", "Universitas San Pedro", "Universitas Katolik Afrika Barat", "Universitas Internasional Abidjan"],
  "republik afrika tengah": ["Universitas Bangui", "Universitas Euromed Bangui", "Institut Teknologi Bangui", "Universitas Katolik Bangui", "Universitas Sains Terapan Bangui", "Institut Pertanian Bangui", "Kolej Kesehatan Bangui", "Universitas Bisnis Bangui", "Institut Keguruan Bangui", "Universitas Komunikasi Afrika Tengah"],
  "republik demokratik kongo": ["Universitas Kinshasa (UNIKIN)", "Universitas Lubumbashi (UNILU)", "Universitas Kisangani (UNIKIS)", "Universitas Katolik Kongo", "Universitas Pedagogis Nasional Kinshasa", "Universitas Kongo Goma", "Universitas Bukavu", "Universitas Protestan Kongo", "Universitas Teknik Kinshasa", "Universitas Kikwit"],
  "republik sudan": ["Universitas Khartoum", "Universitas Sains dan Teknologi Sudan", "Universitas Al-Jazeera", "Universitas Nil", "Universitas Afrika Internasional", "Universitas Omdurman Islamic", "Universitas Ribat Nasional", "Universitas Kordofan", "Universitas Kassala", "Universitas Dongola"],
  "republik tanzania": ["Universitas Dar es Salaam", "Universitas Pertanian Sokoine", "Universitas Muhimbili Sains Kesehatan", "Universitas Dodoma", "Universitas Kristen Saint Augustine", "Universitas Terbuka Tanzania", "Universitas Mzumbe", "Universitas Katolik Ruaha", "Universitas Sains Teknologi Mbeya", "Universitas State Zanzibar"],
  "republik uganda": ["Universitas Makerere", "Universitas Sains Teknologi Mbarara", "Universitas Kyambogo", "Universitas Islam Uganda (IUIU)", "Universitas Gulu", "Universitas Uganda Christian (UCU)", "Universitas Busitema", "Universitas Kampala International (KIU)", "Universitas Ndejje", "Universitas Kabale"],
  "republik zambia": ["Universitas Zambia (UNZA)", "Universitas Copperbelt", "Universitas Mulungushi", "Universitas Zambia Open", "Universitas Cavendish Zambia", "Universitas Texila International Zambia", "Universitas Levy Mwanawasa", "Universitas Rusangu", "Universitas DMI-St. Eugene", "Universitas sains Teknologi Lusaka"],
  "republik zimbabwe": ["Universitas Zimbabwe", "Universitas Sains Teknologi National (NUST)", "Universitas Midlands State", "Universitas Great Zimbabwe", "Universitas Chinhoyi Technology", "Universitas Africa Mutare", "Universitas Bindura Science", "Universitas Catholic Zimbabwe", "Universitas Women Africa", "Universitas Lupane State"],
  "rwanda": ["Universitas Rwanda", "Universitas Global Health Equity", "Universitas Carnegie Mellon Rwanda", "Universitas Adventist Central Africa", "Universitas Lay Adventists Kigali (UNILAK)", "Universitas Rwanda Tourism and Business", "Universitas Kigali", "Universitas Protestant Institute Butare", "Universitas Ines Ruhengeri", "Universitas East African Kigali"],
  "sao tome dan principe": ["Universitas São Tomé dan Príncipe", "Institut Teknologi São Tomé", "Kolej Keguruan São Tomé", "Universitas Sains Kesehatan São Tomé", "Institut Manajemen São Tomé", "Kolej Pertanian São Tomé", "Universitas Maritim São Tomé", "Institut Ilmu Sosial São Tomé", "Universitas Bisnis Santo António", "Kolej Komunikasi São Tomé"],
  "senegal": ["Universitas Cheikh Anta Diop Dakar", "Universitas Gaston Berger Saint-Louis", "Universitas Assane Seck Ziguinchor", "Universitas Alioune Diop Bambey", "Universitas Thies", "Universitas Sine Saloum Fatick", "Universitas Virtual Senegal", "Universitas Dakar Bourguiba", "Universitas Amadou Hampate Ba", "Universitas Supelec Dakar"],
  "seychelles": ["Universitas Seychelles", "Institut Teknologi Seychelles", "Institut Manajemen Seychelles", "Kolej Pariwisata Seychelles", "Institut Maritim Seychelles", "Institut Pertanian Seychelles", "Kolej Pendidikan Victoria", "Universitas Sains Kesehatan Seychelles", "Institut Seni Seychelles", "Universitas Bisnis Praslin"],
  "sierra leone": ["Universitas Sierra Leone (Fourah Bay College)", "Universitas Njala", "Universitas Makeni (UNIMAK)", "Universitas sains Teknologi Ernest Bai Koroma", "Universitas Milton Margai", "Universitas Eastern Kenema", "Institut Manajemen Freetown", "Universitas Kedokteran Sierra Leone", "Kolej Keguruan Freetown", "Universitas Bisnis Bo"],
  "somalia": ["Universitas Mogadishu", "Universitas Nasional Somalia", "Universitas SIMAD", "Universitas Hargeisa", "Universitas Amoud", "Universitas Benadir", "Universitas East Africa", "Universitas Kismayo", "Universitas Puntland State", "Universitas Nugaal"],
  "sudan selatan": ["Universitas Juba", "Universitas Upper Nile", "Universitas Bahr El Ghazal", "Universitas Rumbek", "Universitas Dr. John Garang Memorial", "Universitas Catholic South Sudan", "Universitas Star University Juba", "Universitas Staff Juba", "Universitas Sains Terapan Juba", "Universitas Bisnis Malakal"],
  "tanjung verde": ["Universitas Tanjung Verde", "Universitas Jean Piaget Tanjung Verde", "Universitas Mindelo", "Universitas Santiago", "Institut Sains Terapan Praia", "Kolej Maritim Mindelo", "Institut Keguruan Praia", "Universitas Sains Kesehatan Tanjung Verde", "Kolej Manajemen Mindelo", "Universitas Pertanian São Jorge"],
  "togo": ["Universitas Lomé", "Universitas Kara", "Universitas Katolik Afrika Barat Togo", "Institut Sains Manajemen Lomé", "Universitas Formatech Lomé", "Institut Teknologi Lomé", "Universitas Sains Terapan Lomé", "Universitas Bisnis Togo", "Institut Pertanian Kpalimé", "Universitas Komunikasi Lomé"],
  "tunisia": ["Universitas Tunis El Manar", "Universitas Carthage", "Universitas Sfax", "Universitas Sousse", "Universitas Monastir", "Universitas Tunis", "Universitas Manouba", "Universitas Gabès", "Universitas Ez-Zitouna", "Universitas Jendouba"],

  // --- ASIA ---
  "afganistan": ["Universitas Kabul", "Universitas Nangarhar", "Universitas Herat", "Universitas Balkh", "Universitas Kandahar", "Universitas Politeknik Kabul", "Universitas Kedokteran Kabul", "Universitas Kardan", "Universitas Kateb", "Universitas Al-Beroni"],
  "arab saudi": ["Universitas Raja Saud", "Universitas Sains dan Teknologi Raja Abdullah (KAUST)", "Universitas Raja Fahd Minyak & Mineral", "Universitas Raja Abdulaziz", "Universitas Umm Al-Qura", "Universitas Putri Nora bint Abdul Rahman", "Universitas Imam Abdulrahman bin Faisal", "Universitas Raja Khalid", "Universitas Qassim", "Universitas Taibah"],
  "armenia": ["Universitas Negeri Yerevan", "Universitas Amerika Armenia (AUA)", "Universitas Politeknik Armenia", "Universitas Medis Negeri Yerevan", "Universitas Ekonomi Negeri Armenia", "Universitas Bahasa Negeri Yerevan", "Universitas Pedagogis Negeri Armenia", "Universitas Pertanian Negeri Armenia", "Universitas Arsitektur Yerevan", "Universitas Katolik Eurasia Yerevan"],
  "azerbaijan": ["Universitas Negeri Baku", "Universitas Minyak dan Industri Azerbaijan", "Universitas ADA Baku", "Universitas Khazar", "Universitas Teknik Azerbaijan", "Universitas Kedokteran Azerbaijan", "Universitas Ekonomi Negeri Azerbaijan", "Universitas Bahasa Azerbaijan", "Universitas Pedagogis Azerbaijan", "Universitas Arsitektur dan Konstruksi Azerbaijan"],
  "bahrain": ["Universitas Bahrain", "Universitas Medis Bahrain (RCSI)", "Universitas Terbuka Arab Bahrain", "Universitas Teraplikasi Bahrain", "Universitas Ahlia", "Universitas Teknologi Bahrain", "Universitas Kerajaan Manama", "Universitas Kingdom Bahrain", "Universitas Gulf Bahrain", "Universitas Sains Kesehatan Bahrain"],
  "bangladesh": ["Universitas Dhaka", "Universitas Rekayasa dan Teknologi Bangladesh (BUET)", "Universitas Rajshahi", "Universitas Chittagong", "Universitas Jahangirnagar", "Universitas BRAC", "Universitas North South", "Universitas Pertanian Bangladesh", "Universitas Shahjalal Science and Technology", "Universitas Khulna"],
  "bhutan": ["Universitas Kerajaan Bhutan", "Universitas Sains Kesehatan Khesar Gyalpo", "Kolej Sains Sherubtse", "Kolej Sains dan Teknologi Gaeddu", "Kolej Teknik Jirung", "Kolej Keguruan Paro", "Kolej Bahasa dan Kebudayaan Trongsa", "Kolej Pertanian Punakha", "Institut Manajemen Bhutan", "Kolej Kedokteran Thimphu"],
  "brunei": ["Universitas Brunei Darussalam (UBD)", "Universitas Teknologi Brunei (UTB)", "Universitas Islam Sultan Sharif Ali (UNISSA)", "Kolej Universiti Perguruan Ugama Seri Begawan", "Institut Teknologi Brunei", "Kolej Keperawatan Bandar Seri Begawan", "Kolej Perdagangan Brunei", "Institut Sains Terapan Bandar Seri Begawan", "Kolej Penerbangan Brunei", "Institut Manajemen Bandar Seri Begawan"],
  "china": ["Universitas Tsinghua", "Universitas Peking", "Universitas Zhejiang", "Universitas Shanghai Jiao Tong", "Universitas Fudan", "Universitas Sains dan Teknologi China (USTC)", "Universitas Nanjing", "Universitas Wuhan", "Universitas Sun Yat-sen", "Universitas Harbin Institute of Technology"],
  "filipina": ["Universitas Filipina (UP Diliman)", "Universitas Ateneo de Manila", "Universitas De La Salle", "Universitas Santo Tomas", "Universitas Mapúa", "Universitas Negeri Siliman", "Universitas San Carlos", "Universitas Teknik Filipina", "Universitas Mindanao", "Universitas Far Eastern"],
  "georgia": ["Universitas Negeri Tbilisi Ivane Javakhishvili", "Universitas Negeri Ilia", "Universitas Teknik Georgia", "Universitas Medis Negeri Tbilisi", "Universitas Bebas Tbilisi", "Universitas Laut Hitam Internasional", "Universitas Georgia", "Universitas Kaukasus", "Universitas Negeri Batumi", "Universitas Grigol Robakidze"],
  "hong kong": ["Universitas Hong Kong (HKU)", "Universitas Sains dan Teknologi Hong Kong (HKUST)", "Universitas Chinese Hong Kong (CUHK)", "Universitas Politeknik Hong Kong (PolyU)", "Universitas City Hong Kong (CityU)", "Universitas Baptist Hong Kong", "Universitas Lingnan", "Universitas Pendidikan Hong Kong", "Universitas Metropolitan Hong Kong", "Universitas Shue Yan Hong Kong"],
  "india": ["Institut Teknologi India (IIT Bombay)", "Institut Sains India (IISc Bangalore)", "IIT Delhi", "IIT Madras", "Universitas Delhi", "Universitas Jawaharlal Nehru (JNU)", "Universitas Banaras Hindu (BHU)", "IIT Kharagpur", "Universitas Hyderabad", "IIT Kanpur"],
  "indonesia": ["Universitas Indonesia (UI)", "Institut Teknologi Bandung (ITB)", "Universitas Gadjah Mada (UGM)", "Institut Pertanian Bogor (IPB)", "Universitas Airlangga (UNAIR)", "Universitas Diponegoro (UNDIP)", "Universitas Padjadjaran (UNPAD)", "Universitas Brawijaya (UB)", "Universitas Sepuluh Nopember (ITS)", "Universitas Hasanuddin (UNHAS)"],
  "irak": ["Universitas Baghdad", "Universitas Mustansiriyah", "Universitas Mosul", "Universitas Basrah", "Universitas Kufa", "Universitas Teknologi Baghdad", "Universitas Sulaimani", "Universitas Erbil Polytechnic", "Universitas Salahaddin Erbil", "Universitas Anbar"],
  "iran": ["Universitas Teknologi Sharif", "Universitas Teheran", "Universitas Teknologi Amirkabir", "Universitas Sains dan Teknologi Iran", "Universitas Tarbiat Modares", "Universitas Teknologi Isfahan", "Universitas Shiraz", "Universitas Ferdowsi Mashhad", "Universitas Ilmu Kedokteran Teheran", "Universitas Khajeh Nasir Toosi"],
  "israel": ["Universitas Hebrew Yerusalem", "Technion - Institut Teknologi Israel", "Universitas Tel Aviv", "Universitas Ben-Gurion", "Universitas Bar-Ilan", "Universitas Haifa", "Institut Sains Weizmann", "Universitas Ariel", "Universitas Open Israel", "Kolej Rekayasa Afeka"],
  "jepang": ["Universitas Tokyo", "Universitas Kyoto", "Universitas Osaka", "Universitas Tohoku", "Universitas Nagoya", "Institut Teknologi Tokyo (Tokyo Tech)", "Universitas Kyushu", "Universitas Hokkaido", "Universitas Waseda", "Universitas Keio"],
  "kamboja": ["Universitas Royal Phnom Penh", "Universitas Teknologi Kamboja", "Universitas Sains Kesehatan Kamboja", "Universitas Pertanian Royal Kamboja", "Universitas Manajemen Kamboja", "Universitas Norton Phnom Penh", "Universitas International Kamboja", "Universitas Paññāsāstra Kamboja", "Universitas Pannasastra Battambang", "Universitas Build Bright Kamboja"],
  "kamerun": ["Universitas Yaoundé I", "Universitas Douala", "Universitas Dschang", "Universitas Buea", "Universitas Ngaoundéré", "Universitas Bamenda", "Universitas Maroua", "Universitas Katolik Afrika Tengah Yaoundé", "Universitas Sains dan Teknologi Douala", "Universitas Biaka Institute Buea"],
  "kazakhstan": ["Universitas Nasional Al-Farabi Kazakh", "Universitas Nazarbayev", "Universitas Teknik Nasional Satbayev", "Universitas Nasional L.N. Gumilyov Eurasian", "Universitas KIMEP Almaty", "Universitas Kedokteran Astana", "Universitas Pertanian Kazakh", "Universitas Hubungan Internasional Kazakh", "Universitas Karaganda", "Universitas Suleyman Demirel"],
  "kirgizstan": ["Universitas Nasional Kirgiz Jusup Balasagyn", "Universitas Manas Kirgiz-Turki", "Universitas Amerika Asia Tengah (AUCA)", "Universitas Teknik Kirgiz Razzakov", "Universitas Kedokteran Kirgiz", "Universitas Slavik Kirgiz-Rusia", "Universitas Jalal-Abad", "Universitas Osh State", "Universitas International Kirgizstan", "Universitas Ala-Too International"],
  "korea selatan": ["Universitas Nasional Seoul (SNU)", "KAIST (Institut Sains dan Teknologi Korea)", "Universitas Korea", "Universitas Yonsei", "POSTECH (Universitas Sains dan Teknologi Pohang)", "Universitas Sungkyunkwan (SKKU)", "Universitas Hanyang", "Universitas Kyung Hee", "Universitas Ewha Womans", "Universitas Gwangju Institute of Science and Technology"],
  "korea utara": ["Universitas Kim Il-sung", "Universitas Teknologi Kim Chaek", "Universitas Kedokteran Pyongyang", "Universitas Pertanian Sariwon", "Universitas Hubungan Luar Negeri Pyongyang", "Universitas Keguruan Pyongyang", "Universitas Seni Pyongyang", "Universitas Olahraga Pyongyang", "Universitas Sains Pyongsong", "Universitas Industri Hamhung"],
  "kuwait": ["Universitas Kuwait", "Universitas Sains dan Teknologi Gulf Kuwait", "Universitas Amerika Kuwait", "Universitas Teknik Kuwait", "Universitas Publik Organisasi Pendidikan Kuwait", "Universitas Australia di Kuwait", "Universitas Sains Kesehatan Kuwait", "Universitas Internasional Kuwait", "Kolej Kedokteran Kuwait", "Institut Riset Sains Kuwait"],
  "laos": ["Universitas Nasional Laos (NUOL)", "Universitas Souphanouvong Luang Prabang", "Universitas Champasak", "Universitas Sains Kesehatan Vientiane", "Universitas Savannakhet", "Kolej Politeknik Vientiane", "Institut Pertanian Nabong", "Kolej Keguruan Luang Prabang", "Institut Bisnis Vientiane", "Universitas Teknologi Pakse"],
  "lebanon": ["Universitas Amerika Beirut (AUB)", "Universitas Saint-Joseph Beirut", "Universitas Lebanon", "Universitas Amerika Lebanon (LAU)", "Universitas Balamand", "Universitas Holy Spirit Kaslik", "Universitas Beirut Arab", "Universitas Notre Dame Louaize", "Universitas Sains dan Teknologi Lebanon", "Universitas Antonine"],
  "makau": ["Universitas Makau", "Universitas Sains dan Teknologi Makau (MUST)", "Universitas Kota Makau", "Institut Politeknik Makau", "Institut Studi Pariwisata Makau", "Universitas Saint Joseph Makau", "Kolej Keperawatan Kiang Wu", "Institut Eropa Makau", "Universitas Manajemen Makau", "Institut Sains Terapan Makau"],
  "malaysia": ["Universitas Malaya (UM)", "Universitas Sains Malaysia (USM)", "Universitas Putra Malaysia (UPM)", "Universitas Kebangsaan Malaysia (UKM)", "Universitas Teknologi Malaysia (UTM)", "Universitas Teknologi PETRONAS (UTP)", "Universitas Utara Malaysia (UUM)", "Universitas Islam Internasional Malaysia (IIUM)", "Universitas Taylor's", "Universitas UCSI"],
  "maldives": ["Universitas Nasional Maldives (MNU)", "Universitas Islamic Maldives", "Kolej Villa Male", "Kolej MAPS Male", "Kolej Clique Male", "Kolej Cyryx Male", "Kolej Avid Male", "Institut Sains Kesehatan Maldives", "Kolej Maritim Male", "Institut Teknologi Male"],
  "mongolia": ["Universitas Nasional Mongolia", "Universitas Sains dan Teknologi Mongolia", "Universitas Ilmu Hayati Mongolia", "Universitas Ilmu Medis Mongolia", "Universitas Humaniora Ulaanbaatar", "Universitas Pendidikan Negeri Mongolia", "Universitas International Ulaanbaatar", "Universitas Mandakh Ulaanbaatar", "Universitas Otgontenger", "Universitas Ider"],
  "myanmar": ["Universitas Yangon", "Universitas Mandalay", "Universitas Teknologi Yangon", "Universitas Kedokteran 1 Yangon", "Universitas Ekonomi Yangon", "Universitas Studi Asing Yangon", "Universitas Kedokteran 2 Yangon", "Universitas Yezin Agricultural", "Universitas Computer Studies Yangon", "Universitas Dagon"],
  "nepal": ["Universitas Tribhuvan Kathmandu", "Universitas Kathmandu", "Universitas Pokhara", "Universitas Purbanchal", "Universitas Pertanian dan Kehutanan Nepal", "Universitas Nepal Sanskrit", "Universitas Mid-Western Surkhet", "Universitas Far-Western Mahendranagar", "Universitas Open Nepal", "Universitas Lumbini Buddhist"],
  "oman": ["Universitas Sultan Qaboos", "Universitas Dhofar", "Universitas Sohar", "Universitas Nizwa", "Universitas Teknologi dan Sains Terapan Oman", "Universitas Muscat", "Universitas Al Sharqiyah", "Universitas Sains Kesehatan Muscat", "Universitas Buraimi", "Universitas German Technology Oman"],
  "pakistan": ["Universitas Quaid-i-Azam Islamabad", "Universitas Sains dan Teknologi Nasional (NUST) Islamabad", "Universitas Lahore (LUMS)", "Universitas Aga Khan", "Universitas Punjab Lahore", "Universitas COMSATS Islamabad", "Universitas Teknik & Teknologi Lahore", "Universitas Karatsyi", "Universitas Pertanian Faisalabad", "Universitas Peshawar"],
  "palestina": ["Universitas Birzeit", "Universitas Nasional An-Najah Nablus", "Universitas Al-Quds Yerusalem", "Universitas Islam Gaza", "Universitas Al-Azhar Gaza", "Universitas Politeknik Palestina Hebron", "Universitas Bethlehem", "Universitas Hebron", "Universitas Arab Amerika Jenin", "Universitas Kadoorie Tulkarm"],
  "qatar": ["Universitas Qatar", "Universitas Hamad Bin Khalifa", "Universitas Weill Cornell Qatar", "Universitas Texas A&M Qatar", "Universitas Carnegie Mellon Qatar", "Universitas Georgetown Qatar", "Universitas Northwestern Qatar", "Universitas Virginia Commonwealth Qatar", "Universitas HEC Paris Qatar", "Universitas Stenden Qatar"],
  "republik timor leste": ["Universitas Nasional Timor Lorosa'e (UNTL)", "Universitas Dili (UNDIL)", "Universitas Katolik Timor (UCT)", "Universitas Oriental Timor Lorosa'e (UNITAL)", "Universitas Dili Institute of Technology (DIT)", "Universitas Perdamaian Dili (UNPAZ)", "Universitas Cristã Dili", "Kolej Kedokteran Dili", "Institut Sains Terapan Dili", "Universitas Pertanian Maliana"],
  "singapura": ["Universitas Nasional Singapura (NUS)", "Universitas Teknologi Nanyang (NTU)", "Universitas Manajemen Singapura (SMU)", "Universitas Sains dan Desain Singapura (SUTD)", "Universitas Ilmu Sosial Singapura (SUSS)", "Institut Teknologi Singapura (SIT)", "Universitas Pertunjukan Yong Siew Toh", "Universitas Teknologi SIM", "Universitas INSEAD Singapura", "Universitas Curtin Singapura"],
  "siprus": ["Universitas Siprus", "Universitas Teknologi Siprus", "Universitas Nicosia", "Universitas European Siprus", "Universitas Frederick", "Universitas Neapolis Pafos", "Universitas Eastern Mediterranean", "Universitas Near East Lefkoşa", "Universitas Girne American", "Universitas Cyprus International"],
  "sri lanka": ["Universitas Colombo", "Universitas Peradeniya", "Universitas Moratuwa", "Universitas Sri Jayewardenepura", "Universitas Kelaniya", "Universitas Ruhuna", "Universitas Jaffna", "Institut Teknologi Informasi Sri Lanka (SLIIT)", "Universitas Open Sri Lanka", "Universitas Eastern Sri Lanka"],
  "suriah": ["Universitas Damaskus", "Universitas Aleppo", "Universitas Tishreen Latakia", "Universitas Al-Baath Homs", "Universitas Arab International Damaskus", "Universitas Kalamoon", "Universitas Al-Furat Deir ez-Zor", "Universitas Hawash International", "Universitas Syrian Virtual", "Universitas Tartous"],
  "taiwan": ["Universitas Nasional Taiwan (NTU)", "Universitas Tsing Hua Nasional (NTHU)", "Universitas Yang Ming Chiao Tung (NYCU)", "Universitas Cheng Kung Nasional (NCKU)", "Universitas Taiwan Tech (NTUST)", "Universitas Sun Yat-sen Nasional", "Universitas Central Nasional", "Universitas Normal Taiwan Nasional (NTNU)", "Universitas Taipei Tech (NTUT)", "Universitas Catholique Fu Jen"],
  "tajikistan": ["Universitas Nasional Tajikistan Dushanbe", "Universitas Teknik Tajikistan", "Universitas Medis Negeri Tajikistan", "Universitas Pedagogis Tajikistan", "Universitas Pertanian Tajikistan", "Universitas Slavik Rusia-Tajikistan", "Universitas Khujand State", "Universitas Teknologi Dushanbe", "Universitas Perdagangan Tajikistan", "Universitas International Dushanbe"],
  "thailand": ["Universitas Chulalongkorn", "Universitas Mahidol", "Universitas Chiang Mai", "Universitas Kasetsart", "Universitas Thammasat", "Universitas Khon Kaen", "Universitas Prince of Songkla", "Universitas Teknologi Thonburi (KMUTT)", "Universitas King Mongkut Ladkrabang", "Universitas Srinakharinwirot"],
  "turki": ["Universitas Teknik Timur Tengah (METU)", "Universitas Boğaziçi", "Universitas Koç", "Universitas Bilkent", "Universitas Istanbul", "Universitas Teknik Istanbul (İTÜ)", "Universitas Hacettepe", "Universitas Sabancı", "Universitas Ankara", "Universitas Ege"],
  "turkmenistan": ["Universitas Negeri Turkmenistan Magtymguly", "Universitas Minyak dan Gas Turkmenistan", "Universitas Teknologi Turkmenistan Oguz Han", "Universitas Pertanian Turkmenistan", "Universitas Medis Negeri Turkmenistan", "Universitas Teknik Turkmenistan", "Universitas Ekonomi dan Manajemen Turkmenistan", "Universitas Pedagogis Turkmenistan Seyitnazar Seydi", "Universitas Hubungan Internasional Ashgabat", "Universitas Arsitektur Ashgabat"],
  "uni emirat arab": ["Universitas Uni Emirat Arab (UAEU)", "Universitas Khalifa Abu Dhabi", "Universitas Amerika Sharjah (AUS)", "Universitas Zayed", "Universitas Sharjah", "Universitas Amerika Dubai (AUD)", "Universitas NYU Abu Dhabi", "Universitas Abu Dhabi", "Universitas Sorbonne Abu Dhabi", "Universitas Ajman"],
  "uzbekistan": ["Universitas Nasional Uzbekistan Mirzo Ulugbek", "Universitas Teknik Negeri Tashkent", "Universitas Teknologi Informasi Tashkent", "Universitas Ekonomi Negeri Tashkent", "Universitas Kedokteran Tashkent", "Universitas Inha Tashkent", "Universitas Westminster International Tashkent", "Universitas Pedagogis Tashkent", "Universitas Samarkand State", "Universitas Urgench State"],
  "vietnam": ["Universitas Nasional Vietnam Hanoi (VNU)", "Universitas Sains dan Teknologi Hanoi (HUST)", "Universitas Nasional Vietnam Ho Chi Minh City", "Universitas Ton Duc Thang", "Universitas Duy Tan", "Universitas Kedokteran Hanoi", "Universitas Ekonomi Ho Chi Minh City", "Universitas Can Tho", "Universitas Danang", "Universitas Hue"],
  "yaman": ["Universitas Sana'a", "Universitas Aden", "Universitas Taiz", "Universitas Hodeidah", "Universitas Ibb", "Universitas Sains dan Teknologi Yaman", "Universitas Hadramout", "Universitas Dhamar", "Universitas Al-Ahgaff Mukalla", "Universitas Queen Arwa Sana'a"],
  "yordania": ["Universitas Yordania Amman", "Universitas Sains dan Teknologi Yordania (JUST)", "Universitas Yarmouk Irbid", "Universitas Hashemite Zarqa", "Universitas Al-Balqa Applied", "Universitas German Jordanian", "Universitas Mutah", "Universitas Princess Sumaya Technology", "Universitas Philadelphia Yordania", "Universitas Mut'ah Karak"],

  // --- EROPA ---
  "albania": ["Universitas Tirana", "Universitas Politeknik Tirana", "Universitas Pertanian Tirana", "Universitas Medis Tirana", "Universitas Epoka Tirana", "Universitas Luarasi Tirana", "Universitas Aleksandër Xhuvani Elbasan", "Universitas Luigj Gurakuqi Shkodër", "Universitas Fan Noli Korçë", "Universitas Ismail Qemali Vlorë"],
  "andorra": ["Universitas Andorra", "Universitas Internasional Andorra", "Kolej Kedokteran Andorra", "Institut Sains Terapan Andorra", "Kolej Bisnis Andorra", "Universitas Terbuka Andorra", "Institut Pariwisata Andorra", "Kolej Hukum Andorra", "Institut Teknologi Andorra", "Kolej Pendidikan Andorra"],
  "austria": ["Universitas Wina", "Universitas Teknologi Wina (TU Wien)", "Universitas Kedokteran Wina", "Universitas Innsbruck", "Universitas Graz", "Universitas Sains Ekonomi Wina (WU)", "Universitas Johannes Kepler Linz", "Universitas Klagenfurt", "Universitas Salzburg", "Universitas BOKU Wina"],
  "belanda": ["Universitas TU Delft", "Universitas Amsterdam (UvA)", "Universitas Wageningen", "Universitas Leiden", "Universitas Utrecht", "Universitas Erasmus Rotterdam", "Universitas Vrije Amsterdam (VU)", "Universitas Eindhoven Technology (TU/e)", "Universitas Groningen", "Universitas Maastricht"],
  "belarus": ["Universitas Negeri Belarusia (BSU) Minsk", "Universitas Informatika dan Radioelektronika Belarusia (BSUIR)", "Universitas Teknik Nasional Belarusia (BNTU)", "Universitas Kedokteran Negeri Belarusia", "Universitas Ekonomi Negeri Belarusia", "Universitas Pedagogis Negeri Belarusia", "Universitas Grodno Yanka Kupala", "Universitas Vitebsk State", "Universitas Brest State", "Universitas Gomel State"],
  "belgia": ["Universitas KU Leuven", "Universitas Ghent", "Universitas Catholique de Louvain (UCLouvain)", "Universitas Libre de Bruxelles (ULB)", "Universitas Vrije Brussel (VUB)", "Universitas Antwerp", "Universitas Liège", "Universitas Hasselt", "Universitas Mons", "Universitas Namur"],
  "bosnia dan hercegovina": ["Universitas Sarajevo", "Universitas Banja Luka", "Universitas Mostar", "Universitas Tuzla", "Universitas Zenica", "Universitas Bihać", "Universitas Džemal Bijedić Mostar", "Universitas International Sarajevo", "Universitas Sarajevo School of Science and Technology", "Universitas Aperion Banja Luka"],
  "bulgaria": ["Universitas Sofia St. Kliment Ohridski", "Universitas Teknik Sofia", "Universitas Medis Sofia", "Universitas Ekonomi Nasional dan Dunia Sofia", "Universitas Plovdiv Paisii Hilendarski", "Universitas Medis Plovdiv", "Universitas Varna Economics", "Universitas Thracian Stara Zagora", "Universitas South-West Blagoevgrad", "Universitas Ruse Angel Kanchev"],
  "ceko": ["Universitas Charles Praha", "Universitas Teknik Ceko di Praha (ČVUT)", "Universitas Masaryk Brno", "Universitas Teknologi Brno (VUT)", "Universitas Kimia dan Teknologi Praha (VŠCHT)", "Universitas Palacký Olomouc", "Universitas Ekonomi Praha (VŠE)", "Universitas Pertanian Ceko Praha (ČZU)", "Universitas Ostrava", "Universitas Pardubice"],
  "denmark": ["Universitas Kopenhagen", "Universitas Teknik Denmark (DTU)", "Universitas Aarhus", "Universitas Aalborg", "Universitas Syddansk (Southern Denmark)", "Universitas Bisnis Kopenhagen (CBS)", "Universitas Roskilde", "Universitas IT Kopenhagen", "Kolej Universitas Kopenhagen", "Universitas VIA University College Aarhus"],
  "estonia": ["Universitas Tartu", "Universitas Teknologi Tallinn (TalTech)", "Universitas Tallinn", "Universitas Ilmu Hayati Estonia Tartu", "Universitas Seni Estonia Tallinn", "Universitas Musik dan Teater Estonia", "Kolej Penerbangan Estonia", "Kolej Ilmu Kesehatan Tallinn", "Universitas IT College Tallinn", "Universitas Entrepreneurship Mainor"],
  "finlandia": ["Universitas Helsinki", "Universitas Aalto", "Universitas Tampere", "Universitas Turku", "Universitas Oulu", "Universitas Jyväskylä", "Universitas Finlandia Timur (UEF)", "Universitas LUT Lappeenranta", "Universitas Åbo Akademi", "Universitas Vaasa"],
  "gibraltar": ["Universitas Gibraltar", "Kolej Maritim Gibraltar", "Institut Kesehatan Gibraltar", "Kolej Bisnis Gibraltar", "Institut Sains Terapan Gibraltar", "Kolej Pendidikan Gibraltar", "Institut Keuangan Gibraltar", "Kolej Hukum Gibraltar", "Institut Pariwisata Gibraltar", "Kolej Komunikasi Gibraltar"],
  "hungaria": ["Universitas Eötvös Loránd (ELTE) Budapest", "Universitas Teknologi dan Ekonomi Budapest (BME)", "Universitas Szeged", "Universitas Debrecen", "Universitas Pécs", "Universitas Semmelweis Kedokteran Budapest", "Universitas Corvinus Budapest", "Universitas Szent István Gödöllő", "Universitas Miskolc", "Universitas Pannon Veszprém"],
  "inggris": ["Universitas Oxford", "Universitas Cambridge", "Imperial College London", "University College London (UCL)", "London School of Economics (LSE)", "Universitas Edinburgh", "Universitas Manchester", "King's College London", "Universitas Warwick", "Universitas Bristol"],
  "irlandia": ["Trinity College Dublin (TCD)", "University College Dublin (UCD)", "Universitas Nasional Irlandia Galway (University of Galway)", "University College Cork (UCC)", "Universitas Dublin City (DCU)", "Universitas Limerick", "Universitas Teknologi Dublin (TU Dublin)", "Universitas Teknologi Munster", "Universitas Teknologi Maynooth", "Universitas Teknologi Atlantic"],
  "islandia": ["Universitas Islandia Reykjavík", "Universitas Reykjavík", "Universitas Akureyri", "Universitas Pertanian Islandia Hvanneyri", "Universitas Bifröst", "Universitas Seni Islandia Reykjavík", "Kolej Universitas Hólar", "Institut Sains Kedokteran Reykjavík", "Kolej Teknologi Islandia", "Universitas Maritim Reykjavík"],
  "italia": ["Universitas Bologna", "Universitas Sapienza Roma", "Politecnico di Milano", "Universitas Padova", "Universitas Statale di Milano", "Politecnico di Torino", "Universitas Pisa", "Universitas Florence", "Universitas Naples Federico II", "Universitas Milano-Bicocca"],
  "jerman": ["Universitas Ludwig Maximilian Munich (LMU)", "Universitas Teknik Munich (TUM)", "Universitas Heidelberg", "Universitas Humboldt Berlin", "Universitas Free Berlin", "Universitas RWTH Aachen", "Universitas KIT Karlsruhe", "Universitas Tubingen", "Universitas Freiburg", "Universitas Bonn"],
  "kepulauan faroe": ["Universitas Kepulauan Faroe (Fróðskaparsetur Føroya)", "Institut Laut Faroe Tórshavn", "Kolej Keperawatan Faroe", "Institut Teknologi Tórshavn", "Kolej Perdagangan Faroe", "Institut Pendidikan Tórshavn", "Kolej Seni Faroe", "Institut Sains Terapan Faroe", "Kolej Maritim Tórshavn", "Institut Bisnis Klaksvík"],
  "kosovo": ["Universitas Pristina Hasan Prishtina", "Universitas UBT Pristina", "Universitas AAB Pristina", "Universitas Prizren Ukshin Hoti", "Universitas Peja Haxhi Zeka", "Universitas Mitrovica Isa Boletini", "Universitas Gjilan Kadri Zeka", "Universitas Ferizaj Applied Sciences", "Universitas Riinvest Pristina", "Universitas American University in Kosovo"],
  "kroasia": ["Universitas Zagreb", "Universitas Split", "Universitas Rijeka", "Universitas Osijek Josip Juraj Strossmayer", "Universitas Zadar", "Universitas Pula Juraj Dobrila", "Universitas Dubrovnik", "Universitas Katolik Kroasia Zagreb", "Politeknik Zagreb", "Universitas Sjever Varaždin"],
  "latvia": ["Universitas Latvia Riga", "Universitas Teknik Riga (RTU)", "Universitas Riga Stradiņš (RSU)", "Universitas Ilmu Hayati Latvia Jelgava", "Universitas Daugavpils", "Universitas Liepāja", "Universitas Transportasi dan Telekomunikasi Riga", "Universitas Ventspils University College", "Universitas RISEBA Riga", "Universitas Turība Riga"],
  "liechtenstein": ["Universitas Liechtenstein Vaduz", "Universitas Khusus Swasta Kepangeranan Liechtenstein", "Institut Teknologi Liechtenstein", "Kolej Bisnis Vaduz", "Institut Sains Terapan Liechtenstein", "Kolej Keuangan Vaduz", "Institut Kedokteran Liechtenstein", "Kolej Hukum Vaduz", "Institut Komunikasi Liechtenstein", "Kolej Seni Vaduz"],
  "lithuania": ["Universitas Vilnius", "Universitas Teknologi Kaunas (KTU)", "Universitas Vytautas Magnus Kaunas", "Universitas Teknik Vilnius Gediminas (VILNIUS TECH)", "Universitas Sains Kesehatan Lithuania Kaunas", "Universitas Klaipėda", "Universitas Šiauliai", "Universitas Mykolas Romeris Vilnius", "Universitas LCC International Klaipėda", "Universitas Olahraga Lithuania Kaunas"],
  "luksemburg": ["Universitas Luksemburg", "Universitas Internasional Lunex", "Universitas Bisnis Luksemburg", "Institut Teknologi Luksemburg", "Kolej Keuangan Luksemburg", "Institut Kedokteran Luksemburg", "Universitas Sains Terapan Luksemburg", "Kolej Eropa Luksemburg", "Institut Komunikasi Luksemburg", "Kolej Manajemen Esch-sur-Alzette"],
  "makedonia utara": ["Universitas St. Cyril dan Methodius Skopje", "Universitas Goce Delčev Štip", "Universitas St. Kliment Ohridski Bitola", "Universitas Tetovo", "Universitas SEEU Tetovo", "Universitas Sains Komputer Ohrid", "Universitas American College Skopje", "Universitas FON Skopje", "Universitas International Balkan Skopje", "Universitas Mother Teresa Skopje"],
  "malta": ["Universitas Malta Msida", "Institut Seni Akuntansi Teknologi Malta (MCAST)", "Universitas Amerika Malta", "Kolej Pariwisata Malta (ITH)", "Universitas Sains Kesehatan Malta", "Institut Maritim Malta", "Kolej Bisnis Valletta", "Institut Teknologi Informasi Malta", "Kolej Pendidikan Malta", "Universitas Manajemen Sliema"],
  "moldova": ["Universitas Negeri Moldova Chișinău", "Universitas Teknik Moldova Chișinău", "Universitas Medis dan Farmasi Negeri Nicolae Testemițanu", "Universitas Studi Ekonomi Moldova (ASEM)", "Universitas Pedagogis Negeri Ion Creangă", "Universitas Agraris Negeri Moldova", "Universitas Free International Moldova (ULIM)", "Universitas Bălți Alecu Russo", "Universitas Cahul Bogdan Petriceicu Hasdeu", "Universitas Comrat State"],
  "monako": ["Universitas Internasional Monako (IUM)", "Institut Teknologi Monako", "Kolej Kedokteran Monako", "Institut Maritim Monako", "Kolej Bisnis Monte Carlo", "Institut Pariwisata Monako", "Kolej Keuangan Monako", "Institut Sains Terapan Monako", "Kolej Komunikasi Monako", "Institut Seni Monte Carlo"],
  "montenegro": ["Universitas Montenegro Podgorica", "Universitas Donja Gorica UDG Podgorica", "Universitas Mediterania Podgorica", "Universitas Adriatic Bar", "Institut Laut Kotor", "Kolej Bisnis Podgorica", "Universitas Politeknik Podgorica", "Kolej Pariwisata Budva", "Institut Teknologi Cetinje", "Universitas Sains Terapan Nikšić"],
  "norwegia": ["Universitas Oslo", "Universitas Sains dan Teknologi Norwegia (NTNU) Trondheim", "Universitas Bergen", "Universitas UiT Arctic Norway Tromsø", "Universitas Sains Hayati Norwegia (NMBU) Ås", "Universitas Stavanger", "Universitas Agder Kristiansand", "Universitas Bisnis BI Norwegian Oslo", "Universitas OsloMet", "Universitas Nord Bodø"],
  "polandia": ["Universitas Jagiellonian Krakow", "Universitas Warsawa", "Universitas Teknologi Warsawa (PW)", "Universitas AGH Sains dan Teknologi Krakow", "Universitas Adam Mickiewicz Poznań", "Universitas Teknologi Wrocław (PWr)", "Universitas Kedokteran Gdańsk", "Universitas Kedokteran Warsawa", "Universitas Wrocław", "Universitas Łódź"],
  "portugal": ["Universitas Lisbon", "Universitas Porto", "Universitas Coimbra", "Universitas NOVA Lisbon", "Universitas Aveiro", "Universitas Minho Braga", "Universitas Katolik Portugis", "Universitas Algarve Faro", "Institut Politeknik Porto", "Universitas Beira Interior Covilhã"],
  "prancis": ["Universitas PSL Paris", "Universitas Sorbonne Paris", "Institut Politeknik Paris", "Universitas Paris-Saclay", "Universitas Paris Cité", "Universitas École Polytechnique", "Universitas Grenoble Alpes", "Universitas Aix-Marseille", "Universitas Bordeaux", "Universitas Lyon 1 Claude Bernard"],
  "republik rumania": ["Universitas Babeș-Bolyai Cluj-Napoka", "Universitas Bukares", "Universitas Politehnica Bukares", "Universitas Alexandru Ioan Cuza Iași", "Universitas Kedokteran Carol Davila Bukares", "Universitas Vest Timișoara", "Universitas Teknik Cluj-Napoka", "Universitas Transilvania Brașov", "Universitas Kedokteran Iuliu Hațieganu Cluj", "Universitas Studi Ekonomi Bukares (ASE)"],
  "republik serbia": ["Universitas Beograd", "Universitas Novi Sad", "Universitas Niš", "Universitas Kragujevac", "Universitas Singidunum Beograd", "Universitas Seni Beograd", "Universitas Educons Sremska Kamenica", "Universitas Megatrend Beograd", "Universitas Novi Pazar State", "Universitas Pertahanan Beograd"],
  "rusia": ["Universitas Negeri Moskow Lomonosov (MSU)", "Universitas Negeri Saint Petersburg (SPbSU)", "Universitas HSE Moskow", "Universitas Riset Nuklir MEPhI Moskow", "Universitas Fisika dan Teknologi Moskow (MIPT)", "Universitas Sains dan Teknologi MISIS Moskow", "Universitas Bauman Moscow State Technical", "Universitas Novosibirsk State", "Universitas Tomsk State", "Universitas ITMO Saint Petersburg"],
  "san marino": ["Universitas San Marino", "Institut Teknologi San Marino", "Kolej Kedokteran San Marino", "Institut Sains Terapan San Marino", "Kolej Bisnis San Marino", "Institut Keuangan San Marino", "Kolej Pendidikan San Marino", "Institut Komunikasi San Marino", "Kolej Seni San Marino", "Institut Maritim San Marino"],
  "slovenia": ["Universitas Ljubljana", "Universitas Maribor", "Universitas Primorska Koper", "Universitas Nova Gorica", "Universitas Novo Mesto", "Universitas Katolik Ljubljana", "Kolej Teknologi Ljubljana", "Institut Bisnis Maribor", "Universitas Teraplikasi Celje", "Kolej Pariwisata Portorož"],
  "slowakia": ["Universitas Comenius Bratislava", "Universitas Teknologi Slowakia Bratislava (STU)", "Universitas Pavol Jozef Šafárik Košice", "Universitas Teknik Košice (TUKE)", "Universitas Matej Bel Banská Bystrica", "Universitas Žilina", "Universitas Pertanian Slowakia Nitra", "Universitas Kedokteran Slowakia Bratislava", "Universitas Katolik Ružomberok", "Universitas Prešov"],
  "spanyol": ["Universitas Barcelona (UB)", "Universitas Autònoma de Barcelona (UAB)", "Universitas Complutense Madrid (UCM)", "Universitas Autónoma de Madrid (UAM)", "Universitas Pompeu Fabra Barcelona", "Universitas Politeknik Catalonia (UPC)", "Universitas Valencia", "Universitas Granada", "Universitas Politeknik Madrid (UPM)", "Universitas Navarra"],
  "swedia": ["Universitas Karolinska Institute Stockholm", "Universitas Lund", "Universitas Uppsala", "Universitas Stockholms", "Universitas Teknologi Chalmers Gothenburg", "Universitas KTH Royal Institute of Technology Stockholm", "Universitas Gothenburg", "Universitas Linköping", "Universitas Umeå Swedia", "Universitas SLAU Swedish Agricultural"],
  "swiss": ["Universitas ETH Zurich", "Universitas EPFL Lausanne", "Universitas Zurich", "Universitas Geneva", "Universitas Basel", "Universitas Bern", "Universitas Lausanne", "Universitas Svizzera Italiana Lugano", "Universitas St. Gallen (HSG)", "Universitas Fribourg"],
  "ukraina": ["Universitas Nasional Taras Shevchenko Kairo Kyiv", "Institut Politeknik Igor Sikorsky Kyiv (KPI)", "Universitas Nasional V. N. Karazin Kharkiv", "Universitas Politeknik Lviv", "Universitas Kedokteran Bogomolets Kyiv", "Universitas Kedokteran Kharkiv", "Universitas Lviv Ivan Franko", "Universitas Nasional Sumy", "Universitas Teknik Dnipro", "Universitas Odesa I. I. Mechnikov"],
  "vatikan": ["Universitas Pontifikal Gregorian Roma", "Universitas Pontifikal St. Thomas Aquinas (Angelicum)", "Universitas Pontifikal Lateran", "Universitas Pontifikal Urbaniana", "Universitas Pontifikal Salesian", "Universitas Pontifikal Holy Cross", "Universitas Pontifikal Antonianum", "Institut Kedokteran Vatikan", "Institut Studi Alkitab Pontifikal", "Institut Arkeologi Kristen Pontifikal"],
  "yunani": ["Universitas Nasional Kapodistrian Athena", "Universitas Teknik Nasional Athena (NTUA)", "Universitas Aristotle Thessaloniki", "Universitas Crete", "Universitas Patras", "Universitas Ekonomi dan Bisnis Athena (AUEB)", "Universitas Ioannina", "Universitas Thessaly", "Universitas Democritus Thrace", "Universitas Aegean"],

  // --- NA (NORTH AMERICA) ---
  "amerika serikat": ["Universitas Harvard", "Universitas Stanford", "Massachusetts Institute of Technology (MIT)", "Universitas California Berkeley (UC Berkeley)", "Universitas Princeton", "Universitas Columbia", "Universitas Yale", "Universitas Chicago", "Universitas Pennsylvania (Penn)", "Universitas Cornell"],
  "antigua dan barbuda": ["Universitas Ilmu Kesehatan Antigua (UHSA)", "Universitas American University of Antigua (AUA)", "Universitas West Indies Five Islands", "Kolej Negeri Antigua", "Institut Teknologi St. John's", "Kolej Keperawatan Antigua", "Universitas Bisnis Antigua", "Institut Maritim Barbuda", "Kolej Pendidikan Antigua", "Institut Pariwisata Antigua"],
  "bahama": ["Universitas Bahama Nassau", "Universitas West Indies Bahama", "Kolej Komunitas Bahama", "Universitas Sains Kesehatan Freeport", "Institut Teknologi Nassau", "Kolej Maritim Bahama", "Universitas Bisnis Freeport", "Institut Keguruan Bahama", "Kolej Keperawatan Nassau", "Institut Pariwisata Bahama"],
  "barbados": ["Universitas West Indies Cave Hill Barbados", "Kolej Komunitas Errol Barrow", "Universitas Kedokteran Ross Bridgetown", "Kolej Keperawatan Barbados", "Institut Teknologi Bridgetown", "Universitas Bisnis Barbados", "Institut Keguruan Bridgetown", "Kolej Maritim Barbados", "Institut Sains Terapan Barbados", "Kolej Pariwisata Bridgetown"],
  "belize": ["Universitas Belize Belmopan", "Universitas Galen San Ignacio", "Universitas Central America Health Sciences", "Kolej Komunitas St. John's Belize City", "Kolej Corozal Junior", "Kolej Sacred Heart San Ignacio", "Institut Teknologi Belize", "Kolej Keperawatan Belize", "Universitas Bisnis Belmopan", "Institut Pertanian Cayo"],
  "bermuda": ["Kolej Bermuda Hamilton", "Universitas Sains Kesehatan Bermuda", "Institut Maritim Bermuda", "Kolej Keuangan Bermuda", "Institut Teknologi Hamilton", "Kolej Keperawatan Bermuda", "Universitas Bisnis Hamilton", "Institut Pariwisata Bermuda", "Kolej Pendidikan Bermuda", "Institut Sains Terapan Bermuda"],
  "costa rica": ["Universitas Costa Rica (UCR) San José", "Universitas Nasional Costa Rica (UNA) Heredia", "Institut Teknologi Costa Rica (TEC) Cartago", "Universitas ULACIT San José", "Universitas Latina de Costa Rica", "Universitas Veritas San José", "Universitas EARTH Limón", "Universitas Kedokteran UCIMED", "Universitas Katolik Costa Rica", "Universitas International de las Américas"],
  "curacao": ["Universitas Curaçao Willemstad", "Universitas Sains Kesehatan St. Martinus Willemstad", "Universitas Caribbean Medical University", "Kolej Komunitas Curaçao", "Institut Teknologi Willemstad", "Kolej Maritim Curaçao", "Universitas Bisnis Willemstad", "Institut Keguruan Curaçao", "Kolej Keperawatan Willemstad", "Institut Pariwisata Curaçao"],
  "dominika": ["Universitas Sains Kesehatan All Saints Roseau", "Universitas International University for Graduate Studies", "Kolej Komunitas State College Roseau", "Institut Teknologi Roseau", "Kolej Keperawatan Dominika", "Universitas Bisnis Roseau", "Institut Maritim Dominika", "Kolej Pendidikan Roseau", "Institut Pertanian Dominika", "Kolej Pariwisata Roseau"],
  "el salvador": ["Universitas El Salvador (UES) San Salvador", "Universitas Centroamericana José Simeón Cañas (UCA)", "Universitas Francisco Gaviria", "Universitas Don Bosco San Salvador", "Universitas Tecnológica de El Salvador (UTEC)", "Universitas Dr. José Matías Delgado", "Universitas Evangelica de El Salvador", "Universitas Salvadoreña Alberto Masferrer", "Universitas Katolik El Salvador", "Universitas Pedagógica de El Salvador"],
  "greenland": ["Universitas Greenland (Ilisimatusarfik) Nuuk", "Institut Politeknik Greenland Nuuk", "Kolej Keperawatan Nuuk", "Institut Keguruan Nuuk", "Kolej Maritim Greenland", "Institut Komunikasi Nuuk", "Kolej Bisnis Nuuk", "Institut Sains Terapan Nuuk", "Kolej Seni Greenland", "Institut Tambang Sisimiut"],
  "grenada": ["Universitas St. George's (SGU) Grenada", "Kolej Komunitas T.A. Marryshow St. George's", "Institut Teknologi Grenada", "Kolej Keperawatan Grenada", "Universitas Bisnis St. George's", "Institut Maritim Grenada", "Kolej Pendidikan Grenada", "Institut Pertanian Grenada", "Kolej Pariwisata St. George's", "Institut Sains Terapan Grenada"],
  "guatemala": ["Universitas de San Carlos de Guatemala (USAC)", "Universitas Francisco Marroquín (UFM)", "Universitas del Valle de Guatemala (UVG)", "Universitas Rafael Landívar", "Universitas Mariano Gálvez de Guatemala", "Universitas Galileo Guatemala City", "Universitas Istmo Guatemala", "Universitas Panamericana Guatemala", "Universitas Mesoamericana Quetzaltenango", "Universitas San Pablo de Guatemala"],
  "haiti": ["Universitas Negeri Haiti (UEH) Port-au-Prince", "Universitas Quisqueya Port-au-Prince", "Universitas Notre Dame d'Haïti", "Universitas Caraïbe Port-au-Prince", "Universitas Lumière Port-au-Prince", "Universitas Publique du Nord Cap-Haïtien", "Universitas Episcopale d'Haïti", "Universitas INUKA Port-au-Prince", "Universitas GOC Port-au-Prince", "Universitas Quisqueya Cap-Haïtien"],
  "honduras": ["Universitas Nasional Otonom Honduras (UNAH) Tegucigalpa", "Universitas Tecnológica Centroamericana (UNITEC)", "Universitas Zamorano Pertanian", "Universitas Pedagogica Nacional Francisco Morazan", "Universitas Católica de Honduras", "Universitas Tecnológica de Honduras (UTH)", "Universitas de San Pedro Sula", "Universitas Politécnica de Honduras", "Universitas Metropolitana de Honduras", "Universitas Jose Cecilio del Valle"],
  "jamaika": ["Universitas West Indies Mona Jamaica", "Universitas Teknologi Jamaika (UTech) Kingston", "Universitas Northern Caribbean Mandeville", "Universitas Teknologi Karibia Kingston", "Kolej Komunitas Excelsior Kingston", "Universitas Mico College Kingston", "Kolej Pertanian CASE Port Antonio", "Universitas Caribbean Maritime Kingston", "Kolej Keguruan Shortwood", "Universitas Edna Manley College Kingston"],
  "kanada": ["Universitas Toronto", "Universitas British Columbia (UBC)", "Universitas McGill Montreal", "Universitas Alberta Edmonton", "Universitas Waterloo", "Universitas Western London Ontario", "Universitas Montreal", "Universitas Calgary", "Universitas McMaster Hamilton", "Universitas Ottawa"],
  "kuba": ["Universitas Havana", "Universitas Teknologi Havana (CUJAE)", "Universitas Central de Las Villas Santa Clara", "Universitas Santiago de Cuba", "Universitas Sains Kedokteran Havana", "Universitas Holguín", "Universitas Pinar del Río", "Universitas Camagüey", "Universitas Cienfuegos", "Universitas Matanzas"],
  "meksiko": ["Universitas Nasional Otonom Meksiko (UNAM)", "Institut Politeknik Nasional (IPN) Mexico City", "Technológico de Monterrey (ITESM)", "Universitas Autónoma Metropolitana (UAM)", "Universitas de Guadalajara (UDG)", "Universitas Iberoamericana Mexico City", "Universitas Autónoma de Nuevo León (UANL)", "Universitas de las Américas Puebla (UDLAP)", "Universitas Anáhuac Mexico", "Universitas Autónoma de San Luis Potosí"],
  "nikaragua": ["Universitas Nasional Otonom Nikaragua (UNAN) Managua", "Universitas Centroamericana (UCA) Managua", "Universitas Nasional Teknik (UNI) Managua", "Universitas Nasional Pertanian (UNA) Managua", "Universitas Católica Redemptoris Mater", "Universitas Politécnica de Nicaragua (UPOLI)", "Universitas American College Managua", "Universitas de Ciencias Comerciales", "Universitas Keiser Nicaragua", "Universitas Thomas More Managua"],
  "panama": ["Universitas de Panamá (UP) Panama City", "Universitas Tecnológica de Panamá (UTP)", "Universitas Católica Santa María La Antigua (USMA)", "Universitas Latina de Panamá", "Universitas del Istmo Panama City", "Universitas Marítima Internacional de Panamá", "Universitas Specialized of the Americas (UDELAS)", "Universitas Interamericana de Panamá", "Universitas Metropolitan of Education (UMECIT)", "Universitas Ganexa Panama City"],
  "puerto rico": ["Universitas Puerto Rico (UPR Mayagüez)", "Universitas Puerto Rico Rio Piedras", "Universitas Interamericana de Puerto Rico", "Universitas Pontificia Universidad Católica de Puerto Rico", "Universitas Ana G. Méndez San Juan", "Universitas Ciencias Médicas UPR San Juan", "Universitas Politecnica de Puerto Rico", "Universitas Sagrado Corazón San Juan", "Universitas Carlos Albizu San Juan", "Universitas Central del Caribe Bayamón"],
  "republik dominika": ["Universitas Autónoma de Santo Domingo (UASD)", "Universitas Instituto Tecnológico de Santo Domingo (INTEC)", "Universitas Pontificia Universidad Católica Madre y Maestra (PUCMM)", "Universitas Iberoamericana (UNIBE) Santo Domingo", "Universitas Pedro Henríquez Ureña (UNPHU)", "Universitas APEC Santo Domingo", "Universitas Católica Santo Domingo (UCSD)", "Universitas Tecnológica de Santiago (UTESA)", "Universitas del Caribe (UNICARIBE)", "Universitas Central del Este (UCE)"],
  "saint kitts dan nevis": ["Universitas Sains Kedokteran Ross Basseterre", "Universitas Umhs St. Kitts", "Universitas Windsor University School of Medicine", "Kolej Komunitas Clarence Fitzroy Bryant", "Institut Teknologi Basseterre", "Kolej Keperawatan St. Kitts", "Universitas Bisnis Basseterre", "Institut Maritim Nevis", "Kolej Pendidikan Charlestown", "Institut Pariwisata St. Kitts"],
  "saint lucia": ["Universitas Sains Kedokteran Spartan Vieux Fort", "Universitas International American University College of Medicine", "Universitas Destiny University School of Medicine", "Kolej Komunitas Sir Arthur Lewis Castries", "Institut Teknologi Castries", "Kolej Keperawatan St. Lucia", "Universitas Bisnis Castries", "Institut Maritim Vieux Fort", "Kolej Pendidikan Castries", "Institut Pariwisata St. Lucia"],
  "saint vincent dan grenadine": ["Universitas Sains Kedokteran Trinity Kingstown", "Universitas Saint James School of Medicine", "Universitas All Saints University College of Medicine", "Kolej Komunitas St. Vincent Kingstown", "Institut Teknologi Kingstown", "Kolej Keperawatan St. Vincent", "Universitas Bisnis Kingstown", "Institut Maritim Grenadines", "Kolej Pendidikan Kingstown", "Institut Pariwisata St. Vincent"],
  "trinidad dan tobago": ["Universitas West Indies St. Augustine Trinidad", "Universitas Trinidad dan Tobago (UTT) Arima", "Universitas Perintisan Karibia (USC) Maracas", "Kolej Sains Teknologi COSTAATT Port of Spain", "Institut Teknologi Port of Spain", "Kolej Keperawatan Trinidad", "Universitas Bisnis San Fernando", "Institut Maritim Chaguaramas", "Kolej Pendidikan Port of Spain", "Institut Pariwisata Tobago"],

  // --- OCEANIA ---
  "australia": ["Universitas Melbourne", "Universitas Sydney", "Universitas Nasional Australia (ANU) Canberra", "Universitas New South Wales (UNSW) Sydney", "Universitas Queensland (UQ) Brisbane", "Universitas Monash Melbourne", "Universitas Western Australia (UWA) Perth", "Universitas Adelaide", "Universitas Teknologi Sydney (UTS)", "Universitas RMIT Melbourne"],
  "fiji": ["Universitas South Pacific (USP) Suva", "Universitas Nasional Fiji (FNU) Suva", "Universitas Fiji Lautoka", "Kolej Keperawatan Fiji Suva", "Institut Teknologi Suva", "Kolej Pertanian Koronivia", "Universitas Bisnis Suva", "Institut Maritim Fiji", "Kolej Pendidikan Nadi", "Institut Pariwisata Denarau"],
  "guam": ["Universitas Guam Mangilao", "Kolej Komunitas Guam Mangilao", "Institut Teknologi Hagåtña", "Kolej Keperawatan Guam", "Universitas Bisnis Hagåtña", "Institut Maritim Guam", "Kolej Pendidikan Mangilao", "Institut Pariwisata Guam", "Kolej Sains Terapan Guam", "Institut Keuangan Hagåtña"],
  "kiribati": ["Universitas South Pacific Kampus Kiribati Tarawa", "Kolej Maritim Kiribati Tarawa", "Institut Teknologi Tarawa", "Kolej Keguruan Tarawa", "Kolej Keperawatan Kiribati", "Institut Bisnis Tarawa", "Kolej Pertanian Tarawa", "Institut Sains Terapan Tarawa", "Kolej Komunikasi Tarawa", "Institut Perikanan Betio"],
  "marshall": ["Kolej Kepulauan Marshall Majuro", "Universitas South Pacific Kampus Marshall Majuro", "Institut Teknologi Majuro", "Kolej Keperawatan Majuro", "Universitas Bisnis Majuro", "Institut Maritim Majuro", "Kolej Pendidikan Majuro", "Institut Perikanan Ebeye", "Kolej Sains Terapan Majuro", "Institut Komunikasi Majuro"],
  "mikronesia": ["Kolej Mikronesia (COM-FSM) Pohnpei", "Universitas South Pacific Kampus Pohnpei", "Institut Teknologi Palikir", "Kolej Keperawatan Chuuk", "Universitas Bisnis Yap", "Institut Maritim Kosrae", "Kolej Pendidikan Pohnpei", "Institut Perikanan FSM", "Kolej Sains Terapan Palikir", "Institut Komunikasi Weno"],
  "nauru": ["Universitas South Pacific Kampus Nauru Yaren", "Institut Teknologi Nauru", "Kolej Keperawatan Nauru", "Institut Bisnis Yaren", "Kolej Pendidikan Nauru", "Institut Maritim Nauru", "Kolej Sains Terapan Yaren", "Institut Komunikasi Nauru", "Kolej Pertanian Nauru", "Institut Keuangan Yaren"],
  "palau": ["Kolej Komunitas Palau Koror", "Universitas South Pacific Kampus Palau Koror", "Institut Teknologi Koror", "Kolej Keperawatan Palau", "Universitas Bisnis Koror", "Institut Maritim Palau", "Kolej Pendidikan Koror", "Institut Pariwisata Palau", "Kolej Sains Terapan Koror", "Institut Perikanan Airai"],
  "papua nugini": ["Universitas Papua Nugini (UPNG) Port Moresby", "Universitas Teknologi Papua Nugini (UNITECH) Lae", "Universitas Goroka", "Universitas Divine Word Madang", "Universitas Adventist Pacific Port Moresby", "Kolej Pertanian Vudal Rabaul", "Institut Teknologi Lae", "Kolej Keperawatan Port Moresby", "Universitas Bisnis Kokopo", "Institut Maritim Madang"],
  "samoa amerika": ["Kolej Komunitas Samoa Amerika (ASCC) Pago Pago", "Institut Teknologi Pago Pago", "Kolej Keperawatan Samoa Amerika", "Universitas Bisnis Pago Pago", "Institut Maritim Utulei", "Kolej Pendidikan Pago Pago", "Institut Perikanan Tafuna", "Kolej Sains Terapan Pago Pago", "Institut Komunikasi Utulei", "Kolej Pariwisata Pago Pago"],
  "samoa": ["Universitas Nasional Samoa (NUS) Apia", "Universitas South Pacific Kampus Alafua Apia", "Institut Teknologi Apia", "Kolej Keperawatan Samoa", "Universitas Bisnis Apia", "Institut Maritim Samoa", "Kolej Pendidikan Apia", "Institut Pertanian Alafua", "Kolej Pariwisata Samoa", "Institut Sains Terapan Apia"],
  "selandia baru": ["Universitas Auckland", "Universitas Otago Dunedin", "Universitas Victoria Wellington", "Universitas Canterbury Christchurch", "Universitas Massey Palmerston North", "Universitas Waikato Hamilton", "Universitas Teknologi Auckland (AUT)", "Universitas Lincoln Christchurch", "Institut Teknologi WelTec Wellington", "Institut Teknologi Ara Christchurch"],
  "tahiti": ["Universitas Polinesia Prancis (UPF) Papeete", "Institut Politeknik Tahiti Papeete", "Kolej Keperawatan Papeete", "Institut Maritim Tahiti", "Kolej Bisnis Papeete", "Institut Pariwisata Tahiti", "Kolej Pendidikan Papeete", "Institut Sains Terapan Faaa", "Kolej Komunikasi Papeete", "Institut Pertanian Moorea"],
  "tonga": ["Universitas South Pacific Kampus Tonga Nuku'alofa", "Universitas Tonga Nuku'alofa", "Institut Teknologi Nuku'alofa", "Kolej Keperawatan Tonga", "Universitas Bisnis Nuku'alofa", "Institut Maritim Tonga", "Kolej Pendidikan Nuku'alofa", "Institut Pertanian Tonga", "Kolej Pariwisata Nuku'alofa", "Institut Sains Terapan Nuku'alofa"],
  "tuvalu": ["Universitas South Pacific Kampus Tuvalu Funafuti", "Institut Pelatihan Maritim Tuvalu Funafuti", "Institut Teknologi Funafuti", "Kolej Keperawatan Tuvalu", "Universitas Bisnis Funafuti", "Kolej Pendidikan Funafuti", "Institut Perikanan Tuvalu", "Kolej Sains Terapan Funafuti", "Institut Komunikasi Funafuti", "Kolej Pertanian Funafuti"],
  "vanuatu": ["Universitas South Pacific Kampus Emalus Port Vila", "Universitas Nasional Vanuatu Port Vila", "Institut Teknologi Vanuatu Port Vila", "Kolej Keperawatan Vanuatu", "Universitas Bisnis Port Vila", "Institut Maritim Vanuatu", "Kolej Pendidikan Port Vila", "Institut Pertanian Luganville", "Kolej Pariwisata Vanuatu", "Institut Sains Terapan Port Vila"],

  // --- SA (SOUTH AMERICA) ---
  "argentina": ["Universitas Buenos Aires (UBA)", "Universitas La Plata (UNLP)", "Universitas Nasional Córdoba (UNC)", "Universitas Nasional Rosario (UNR)", "Universitas Teknologi Nasional (UTN)", "Universitas Torcuato Di Tella", "Universitas Austral Buenos Aires", "Universitas San Andrés", "Universitas Nasional Cuyo", "Universitas Nasional Mar del Plata"],
  "bolivia": ["Universitas Mayor de San Andrés (UMSA) La Paz", "Universitas Mayor de San Simón (UMSS) Cochabamba", "Universitas Autónoma Gabriel René Moreno (UAGRM) Santa Cruz", "Universitas Católica Boliviana San Pablo", "Universitas Privada Boliviana (UPB)", "Universitas Mayor Real y Pontificia de San Francisco Xavier Sucre", "Universitas del Valle (UNIVALLE)", "Universitas Salesiana de Bolivia", "Universitas Nur Santa Cruz", "Universitas Privada de Santa Cruz de la Sierra (UPSA)"],
  "brazil": ["Universitas São Paulo (USP)", "Universitas Negeri Campinas (UNICAMP)", "Universitas Federal Rio de Janeiro (UFRJ)", "Universitas Federal Minas Gerais (UFMG)", "Universitas Federal Rio Grande do Sul (UFRGS)", "Universitas Federal Santa Catarina (UFSC)", "Universitas Estadual Paulista (UNESP)", "Universitas Katolik Pontifikal Rio de Janeiro (PUC-Rio)", "Universitas Federal São Paulo (UNIFESP)", "Universitas Katolik Pontifikal Rio Grande do Sul (PUCRS)"],
  "chile": ["Universitas Pontificia Universidad Católica de Chile (UC) Santiago", "Universitas Chile Santiago", "Universitas Concepción", "Universitas Técnico Federico Santa María Valparaíso", "Universitas Santiago de Chile (USACH)", "Universitas Adolfo Ibáñez", "Universitas Austral de Chile Valdivia", "Universitas Diego Portales", "Universitas Talca", "Universitas Valparaíso"],
  "ekuador": ["Universitas San Francisco de Quito (USFQ)", "Universitas Pontificia Universidad Católica del Ecuador (PUCE) Quito", "Universitas Escuela Superior Politécnica del Litoral (ESPOL) Guayaquil", "Universitas Central del Ecuador Quito", "Universitas Cuenca", "Universitas Escuela Politécnica Nacional (EPN) Quito", "Universitas Espíritu Santo (UEES) Guayaquil", "Universitas Técnica Particular de Loja (UTPL)", "Universitas de las Américas (UDLA) Quito", "Universitas Azuay Cuenca"],
  "guiana prancis": ["Universitas Guiana Cayenne", "Institut Politeknik Cayenne", "Kolej Keperawatan Cayenne", "Institut Maritim Kourou", "Kolej Bisnis Cayenne", "Institut Teknologi Kourou", "Kolej Pendidikan Cayenne", "Institut Sains Terapan Cayenne", "Kolej Pertanian Saint-Laurent-du-Maroni", "Institut Komunikasi Cayenne"],
  "guyana": ["Universitas Guyana Georgetown", "Universitas Kedokteran Texila International Georgetown", "Universitas Kedokteran American International Georgetown", "Kolej Komunitas Critchlow Labour Georgetown", "Institut Pelatihan Teknis Guyana", "Kolej Keperawatan Georgetown", "Universitas Bisnis Georgetown", "Institut Maritim Guyana", "Kolej Pendidikan Georgetown", "Institut Pertanian Mon Repos"],
  "kolombia": ["Universitas de los Andes Bogotá", "Universitas Nacional de Colombia Bogotá", "Universitas Antioquia Medellín", "Universitas Pontificia Universidad Javeriana Bogotá", "Universitas del Valle Cali", "Universitas EAFIT Medellín", "Universitas del Norte Barranquilla", "Universitas Industrial de Santander (UIS) Bucaramanga", "Universitas Rosario Bogotá", "Universitas Sabana Chía"],
  "paraguay": ["Universitas Nacional de Asunción (UNA)", "Universitas Católica Nuestra Señora de la Asunción (UCA)", "Universitas Autónoma de Asunción (UAA)", "Universitas Americana Asunción", "Universitas Nacional de Itapúa Encarnación", "Universitas del Norte Asunción", "Universitas San Carlos Asunción", "Universitas Nacional de Este Ciudad del Este", "Universitas Politécnica Taiwán-Paraguay", "Universitas Columbia del Paraguay"],
  "peru": ["Universitas Pontificia Universidad Católica del Perú (PUCP) Lima", "Universitas Nacional Mayor de San Marcos (UNMSM) Lima", "Universitas Peruana Cayetano Heredia (UPCH) Lima", "Universitas Nacional de Ingeniería (UNI) Lima", "Universitas de Lima", "Universitas del Pacífico Lima", "Universitas Nacional Agraria La Molina", "Universitas Peruana de Ciencias Aplicadas (UPC)", "Universitas San Agustín de Arequipa (UNSA)", "Universitas National de San Antonio Abad del Cusco"],
  "suriname": ["Universitas Anton de Kom Suriname (ADEKUS) Paramaribo", "Universitas Kedokteran FHR Paramaribo", "Institut Politeknik Paramaribo", "Kolej Keperawatan Suriname", "Universitas Bisnis Paramaribo", "Institut Maritim Suriname", "Kolej Pendidikan Paramaribo", "Institut Sains Terapan Suriname", "Kolej Pertanian Suriname", "Institut Komunikasi Paramaribo"],
  "uruguay": ["Universitas de la República (UdelaR) Montevideo", "Universitas ORT Uruguay Montevideo", "Universitas Católica del Uruguay (UCU) Montevideo", "Universitas Montevideo (UM)", "Universitas de la Empresa (UDE) Montevideo", "Universitas Tecnológica del Uruguay (UTEC)", "Institut Politeknik Montevideo", "Kolej Keperawatan Montevideo", "Universitas Bisnis Maldonado", "Institut Sains Terapan Salto"],
  "venezuela": ["Universitas Central de Venezuela (UCV) Caracas", "Universitas Simón Bolívar (USB) Caracas", "Universitas Católica Andrés Bello (UCAB) Caracas", "Universitas de Los Andes (ULA) Mérida", "Universitas del Zulia (LUZ) Maracaibo", "Universitas de Carabobo (UC) Valencia", "Universitas de Oriente (UDO) Cumaná", "Universitas Lisandro Alvarado (UCLA) Barquisimeto", "Universitas Metropolitana (UNIMET) Caracas", "Universitas Rafael Urdaneta Maracaibo"]
};

// Baca semua benua dari nama_kota
const continents = fs.readdirSync(baseKotaDir);
let totalFilesCreated = 0;

continents.forEach(continent => {
  const kotaContinentDir = path.join(baseKotaDir, continent);
  const univContinentDir = path.join(baseUnivDir, continent);

  if (fs.statSync(kotaContinentDir).isDirectory()) {
    if (!fs.existsSync(univContinentDir)) {
      fs.mkdirSync(univContinentDir, { recursive: true });
    }

    const countryFiles = fs.readdirSync(kotaContinentDir).filter(f => f.endsWith('.json'));

    countryFiles.forEach(cFile => {
      const countryName = cFile.replace('.json', '');
      const listUniv = univDB[countryName];

      if (!listUniv || listUniv.length < 10) {
        console.error('[ERROR] Country ' + countryName + ' in continent ' + continent + ' does not have at least 10 universities!');
        process.exit(1);
      }

      // Pastikan persis 10 universitas top per negara
      const top10 = listUniv.slice(0, 10);
      const targetFilePath = path.join(univContinentDir, cFile);

      fs.writeFileSync(targetFilePath, JSON.stringify(top10, null, 2), 'utf-8');
      totalFilesCreated++;
    });
  }
});

console.log('[SUCCESS] Successfully created ' + totalFilesCreated + ' university JSON files across all 6 continent folders under json/nama_unniv!');
