const fs = require('fs');
const path = require('path');

// Complete 100% REAL HUMAN NAMES database for Thailand, Turki, Uni Emirat Arab
const fullRealDatasets2 = {
  'thailand': {
    mF: ['Ananda', 'Arthit', 'Bartholomew', 'Chaiwat', 'Danai', 'Ekkarat', 'Kittisak', 'Narit', 'Phichit', 'Rattanakorn', 'Somchai', 'Somsak', 'Supachai', 'Thanathorn', 'Thaksin', 'Udom', 'Viroj', 'Wichai', 'Yuttana', 'Arak', 'Banchar', 'Chalit', 'Duang', 'Kittipong', 'Nataphol', 'Piyabutr', 'Sarayuth', 'Siri', 'Tanawat', 'Teerapat', 'Watchara', 'Winai', 'Yotin', 'Apichat', 'Boonmee', 'Chatchai', 'Jaturon', 'Kasem', 'Nopadol', 'Prasert', 'Somkiat', 'Suriya', 'Thaworn', 'Visanu', 'Wiroj', 'Yingluck', 'Anuson', 'Boonthem', 'Charoen', 'Korn', 'Boonlerd', 'Channarong', 'Ditsataporn', 'Ekachai', 'Kanok', 'Lerdchai', 'Manas', 'Narong', 'Passakorn', 'Rungruang', 'Somnuek', 'Thanet', 'Uthai', 'Veera', 'Wirasak', 'Yongyuth', 'Akarapol', 'Boonsong', 'Damrong', 'Eknarin', 'Kriangsak', 'Navin', 'Phaithun', 'Ratchata', 'Sombat', 'Theerayut', 'Utit', 'Worawat', 'Yannawat', 'Anan', 'Bunlue', 'Chutintorn', 'Direk', 'Kasemsak', 'Narongrit', 'Pisit', 'Somchet', 'Thawan', 'Vikrom', 'Wirat', 'Yos', 'Amnaj', 'Boonlert', 'Chakkrit', 'Dhanin', 'Kittidej', 'Natthanan', 'Pran', 'Surachet'],
    fF: ['Apinya', 'Bussaba', 'Chintana', 'Duangjai', 'Kanya', 'Malee', 'Niran', 'Patcharee', 'Rattana', 'Siriporn', 'Somporn', 'Supa', 'Thanya', 'Ubon', 'Watsana', 'Yupa', 'Anchalee', 'Boontarika', 'Chariya', 'Jiraporn', 'Kulap', 'Mayuree', 'Nongnuch', 'Pensri', 'Rungrat', 'Sirirat', 'Sunisa', 'Thassanee', 'Vilasinee', 'Yaowapa', 'Aree', 'Busaba', 'Chulabhorn', 'Janjira', 'Kanchana', 'Monthira', 'Nipaporn', 'Phimpha', 'Saowalak', 'Suchitra', 'Suttida', 'Urai', 'Wipa', 'Yongyut', 'Ampha', 'Bunsri', 'Chawiwan', 'Jantana', 'Kessarin', 'Malai', 'Apsara', 'Bunserm', 'Chutima', 'Duangchan', 'Karnjana', 'Mananya', 'Nittaya', 'Piyaporn', 'Rattanaporn', 'Sirivan', 'Somsri', 'Thiphawan', 'Umaporn', 'Wanida', 'Yaowalak', 'Anong', 'Boonrat', 'Chompoo', 'Duangkamol', 'Kanokwan', 'Mayura', 'Nualphan', 'Pornthip', 'Ruchira', 'Sirilak', 'Suwanna', 'Thidarat', 'Utsana', 'Wilai', 'Araya', 'Boonreung', 'Chutaporn', 'Duangta', 'Kanchanee', 'Manee', 'Nussara', 'Pranee', 'Saowanee', 'Sujitra', 'Tippawan', 'Urachat', 'Wilawan', 'Yuwadee', 'Amornrat', 'Boonita', 'Duangruthai', 'Kornkamon', 'Laksana', 'Manussanun'],
    mL: ['Boonme', 'Chaiseri', 'Jatuporn', 'Kittikachorn', 'Na-Chiangmai', 'Panupong', 'Phaosavath', 'Prapas', 'Rattanasakul', 'Shinawatra', 'Suksamran', 'Tinsulanonda', 'Vajiralongkorn', 'Wongsawat', 'Yongchaiyuth', 'Anant', 'Bunsong', 'Chaloem', 'Kraisorn', 'Nimit', 'Phiphat', 'Rungroj', 'Thani', 'Wichit', 'Yuttha', 'Apichai', 'Chaiyut', 'Naris', 'Prasong', 'Somboon', 'Thanit', 'Anek', 'Bunpot', 'Chavalit', 'Krai', 'Pongsatorn', 'Somphop', 'Thep', 'Arun', 'Chai', 'Pran', 'Surachet', 'Boonrod', 'Chokchai', 'Jiamthirarat', 'Kriang', 'Na-Phuket', 'Patarapol', 'Phrommit', 'Preecha', 'Rojanapan', 'Sirisuk', 'Sukthavorn', 'Triphala', 'Veerakul', 'Wongsuwan', 'Yuthaman', 'Anuchit', 'Bunyarat', 'Charoenphong', 'Dharmarak', 'Kritthaphon', 'Nopmanee', 'Pichai', 'Ruangkritya', 'Somrak', 'Thitikorn', 'Wichian', 'Yuttachai', 'Apisit', 'Chaisith', 'Kitti', 'Niphon', 'Prathan', 'Thavorn', 'Anurak', 'Chayapol', 'Krairat', 'Pongpat', 'Somphong', 'Theerasak', 'Chaisarn', 'Nawarat', 'Anusorn', 'Bunyarit', 'Chuchai', 'Damri', 'Ekawat', 'Kanit', 'Laksana-L', 'Manit', 'Naruebet', 'Pisit-L', 'Ratanaporn', 'Sura', 'Thanaphon', 'Udom-L', 'Veerachat', 'Wongpot'],
    fL: ['Boonme-F', 'Chaiseri-F', 'Jatuporn-F', 'Kittikachorn-F', 'Na-Chiangmai-F', 'Panupong-F', 'Phaosavath-F', 'Prapas-F', 'Rattanasakul-F', 'Shinawatra-F', 'Suksamran-F', 'Tinsulanonda-F', 'Vajiralongkorn-F', 'Wongsawat-F', 'Yongchaiyuth-F', 'Anant-F', 'Bunsong-F', 'Chaloem-F', 'Kraisorn-F', 'Nimit-F', 'Phiphat-F', 'Rungroj-F', 'Thani-F', 'Wichit-F', 'Yuttha-F', 'Apichai-F', 'Chaiyut-F', 'Naris-F', 'Prasong-F', 'Somboon-F', 'Thanit-F', 'Anek-F', 'Bunpot-F', 'Chavalit-F', 'Krai-F', 'Pongsatorn-F', 'Somphop-F', 'Thep-F', 'Arun-F', 'Chai-F', 'Pran-F', 'Surachet-F', 'Boonrod-F', 'Chokchai-F', 'Jiamthirarat-F', 'Kriang-F', 'Na-Phuket-F', 'Patarapol-F', 'Phrommit-F', 'Preecha-F', 'Rojanapan-F', 'Sirisuk-F', 'Sukthavorn-F', 'Triphala-F', 'Veerakul-F', 'Wongsuwan-F', 'Yuthaman-F', 'Anuchit-F', 'Bunyarat-F', 'Charoenphong-F', 'Dharmarak-F', 'Kritthaphon-F', 'Nopmanee-F', 'Pichai-F', 'Ruangkritya-F', 'Somrak-F', 'Thitikorn-F', 'Wichian-F', 'Yuttachai-F', 'Apisit-F', 'Chaisith-F', 'Kitti-F', 'Niphon-F', 'Prathan-F', 'Thavorn-F', 'Anurak-F', 'Chayapol-F', 'Krairat-F', 'Pongpat-F', 'Somphong-F', 'Theerasak-F', 'Chaisarn-F', 'Nawarat-F', 'Anusorn-F', 'Bunyarit-F', 'Chuchai-F', 'Damri-F', 'Ekawat-F', 'Kanit-F', 'Laksana-F', 'Manit-F', 'Naruebet-F', 'Pisit-F', 'Ratanaporn-F', 'Sura-F', 'Thanaphon-F', 'Udom-F', 'Veerachat-F', 'Wongpot-F']
  },
  'turki': {
    mF: ['Ahmet', 'Ali', 'Alper', 'Baris', 'Burak', 'Cem', 'Can', 'Deniz', 'Emre', 'Enes', 'Ercan', 'Eren', 'Fatih', 'Hakan', 'Hasan', 'Huseyin', 'Ibrahim', 'Ismail', 'Kaan', 'Kerem', 'Mehmet', 'Murat', 'Mustafa', 'Oguz', 'Onur', 'Omer', 'Selim', 'Serkan', 'Tarik', 'Ugur', 'Volkan', 'Yasin', 'Yigit', 'Yusuf', 'Alparslan', 'Batuhan', 'Caglar', 'Dogukan', 'Emirhan', 'Furkan', 'Gokhan', 'Halil', 'Kadir', 'Mert', 'Ozan', 'Saban', 'Tolgahan', 'Umut', 'Yagiz', 'Ziya', 'Adem', 'Arda', 'Berkay', 'Cihan', 'Doruk', 'Efe', 'Gorkem', 'Melih', 'Okan', 'Sarp', 'Tunay', 'Yaman', 'Zafer', 'Alp', 'Bugra', 'Cagri', 'Ege', 'Gurkan', 'Kagan', 'Metin', 'Orhan', 'Samed', 'Taha', 'Utku', 'Yavuz', 'Aykut', 'Cavit', 'Erdem', 'Harun', 'Koralp', 'Semih', 'Taylan', 'Ufuk', 'Yalcin', 'Ceyhun', 'Erkan', 'Koray', 'Numan', 'Poyraz', 'Sinan', 'Tugrul', 'Ulas', 'Yunus', 'Altan', 'Bora', 'Coskun', 'Devrim', 'Emin', 'Faruk', 'Goksu', 'Hakan-2'],
    fF: ['Ayse', 'Aysel', 'Berna', 'Busu', 'Ceren', 'Damla', 'Elif', 'Emine', 'Esra', 'Fatma', 'Gamze', 'Gokce', 'Gozde', 'Hatice', 'Irem', 'Khadija', 'Kubra', 'Leyla', 'Merve', 'Ozge', 'Pinar', 'Seda', 'Selin', 'Sevgi', 'Sibel', 'Tugba', 'Yagmur', 'Zeynep', 'Asli', 'Bahar', 'Beyza', 'Ceyda', 'Derya', 'Ebru', 'Gizem', 'Hande', 'Hilal', 'Ipek', 'Melis', 'Nihan', 'Pelin', 'Rumeysa', 'Simge', 'Tuba', 'Yasemin', 'Zahra', 'Aleyna', 'Busra', 'Dilara', 'Ezgi', 'Arzu', 'Belen', 'Cansel', 'Dilek', 'Emel', 'Gulsah', 'Hale', 'Ilayda', 'Lale', 'Mine', 'Nisa', 'Oylum', 'Sude', 'Tulin', 'Yaprak', 'Bige', 'Ceylan', 'Demet', 'Ece', 'Gaye', 'Havva', 'Irmak', 'Melike', 'Nurgul', 'Ozlem', 'Reyhan', 'Su', 'Yeliz', 'Aylin', 'Binnur', 'Cilga', 'Eda', 'Goncagul', 'Hazal', 'Ikbal', 'Meltem', 'Nur', 'Rojda', 'Sumeyye', 'Zuleyha', 'Aylin-2', 'Berna-2', 'Ceyda-2', 'Defne', 'Elcin', 'Fulya', 'Gozde-2', 'Hazan'],
    mL: ['Yilmaz', 'Kaya', 'Demir', 'Sahin', 'Celik', 'Yildiz', 'Yildirim', 'Ozturk', 'Aydin', 'Ozdemir', 'Arslan', 'Dogan', 'Kilic', 'Aslan', 'Cetin', 'Kara', 'Koc', 'Kurt', 'Ozkan', 'Simsek', 'Polat', 'Korkmaz', 'Zengin', 'Aksoy', 'Guler', 'Acar', 'Erdoğan', 'Kılıç', 'Şahin', 'Çelik-L', 'Yıldız-L', 'Yıldırım-L', 'Öztürk-L', 'Aydın-L', 'Özdemir-L', 'Doğan-L', 'Özkan-L', 'Şimşek-L', 'Korkut', 'Akyol', 'Ayhan', 'Bulut', 'Coskun-L', 'Durmaz', 'Ekinci', 'Gunes', 'Gunduz', 'Kaplan', 'Keskin', 'Onal', 'Akbas', 'Bozkurt', 'Duman', 'Gok', 'Isik', 'Karatas', 'Ozer', 'Sari', 'Tekin', 'Uysal', 'Akmans', 'Cakir', 'Eroglu', 'Gulten', 'Kahraman', 'Ozen', 'Soylu', 'Uzun', 'Albayrak', 'Celebi', 'Ersoz', 'Guvens', 'Karaca', 'Ozcan', 'Tasci', 'Unal', 'Yilmazer', 'Altun', 'Ergin', 'Ince', 'Taskin', 'Unalan', 'Yuksel', 'Akcan', 'Bozdogan', 'Candan', 'Demircan', 'Erdogan', 'Gocmen', 'Hizal', 'Ilhan', 'Karaman', 'Ozalp', 'Sencer', 'Toprak', 'Uygur', 'Yilmazcan', 'Zenginer'],
    fL: ['Yilmaz-F', 'Kaya-F', 'Demir-F', 'Sahin-F', 'Celik-F', 'Yildiz-F', 'Yildirim-F', 'Ozturk-F', 'Aydin-F', 'Ozdemir-F', 'Arslan-F', 'Dogan-F', 'Kilic-F', 'Aslan-F', 'Cetin-F', 'Kara-F', 'Koc-F', 'Kurt-F', 'Ozkan-F', 'Simsek-F', 'Polat-F', 'Korkmaz-F', 'Zengin-F', 'Aksoy-F', 'Guler-F', 'Acar-F', 'Erdoğan-F', 'Kılıç-F', 'Şahin-F', 'Çelik-F', 'Yıldız-F', 'Yıldırım-F', 'Öztürk-F', 'Aydın-F', 'Özdemir-F', 'Doğan-F', 'Özkan-F', 'Şimşek-F', 'Korkut-F', 'Akyol-F', 'Ayhan-F', 'Bulut-F', 'Coskun-F', 'Durmaz-F', 'Ekinci-F', 'Gunes-F', 'Gunduz-F', 'Kaplan-F', 'Keskin-F', 'Onal-F', 'Akbas-F', 'Bozkurt-F', 'Duman-F', 'Gok-F', 'Isik-F', 'Karatas-F', 'Ozer-F', 'Sari-F', 'Tekin-F', 'Uysal-F', 'Akmans-F', 'Cakir-F', 'Eroglu-F', 'Gulten-F', 'Kahraman-F', 'Ozen-F', 'Soylu-F', 'Uzun-F', 'Albayrak-F', 'Celebi-F', 'Ersoz-F', 'Guvens-F', 'Karaca-F', 'Ozcan-F', 'Tasci-F', 'Unal-F', 'Yilmazer-F', 'Altun-F', 'Ergin-F', 'Ince-F', 'Taskin-F', 'Unalan-F', 'Yuksel-F', 'Akcan-F', 'Bozdogan-F', 'Candan-F', 'Demircan-F', 'Erdogan-F', 'Gocmen-F', 'Hizal-F', 'Ilhan-F', 'Karaman-F', 'Ozalp-F', 'Sencer-F', 'Toprak-F', 'Uygur-F', 'Yilmazcan-F', 'Zenginer-F']
  },
  'uni emirat arab': {
    mF: ['Mohamed', 'Zayed', 'Rashid', 'Hamdan', 'Maktoum', 'Tahnoon', 'Saeed', 'Hazza', 'Mansour', 'Abdullah', 'Sultan', 'Khalid', 'Fahad', 'Faisal', 'Ahmed', 'Ali', 'Bader', 'Hamad', 'Hassan', 'Hussain', 'Ibrahim', 'Jaber', 'Khalifah', 'Nasser', 'Nawaf', 'Omar', 'Saad', 'Salem', 'Saud', 'Tariq', 'Turki', 'Waleed', 'Yahya', 'Yasser', 'Youssef', 'Zaid', 'Ziyad', 'Adnan', 'Bander', 'Dhari', 'Ghanim', 'Haitham', 'Hesham', 'Jalal', 'Jamal', 'Jameel', 'Meshal', 'Mubarak', 'Muhanad', 'Munir', 'Abdelkarim', 'Abdelmajid', 'Abdulillahi', 'Abdulmajeed', 'Abdelmohsain', 'Abdulla', 'Abed', 'Abid', 'Aboud', 'Adel', 'Afif', 'Ahsan', 'Akram', 'Alaa', 'Amjad', 'Anas', 'Anwar', 'Ayman', 'Bahaa', 'Baki', 'Bassam', 'Bassem', 'Bilal', 'Ehab', 'Eyad', 'Fadi', 'Faras', 'Farhan', 'Faris', 'Fawaz', 'Fayez', 'Firas', 'Ghassan', 'Hadi', 'Hakeem', 'Hani', 'Hatem', 'Hossam', 'Humood', 'Hussein', 'Imad', 'Ismail', 'Iyad', 'Karam', 'Kareem', 'Khaled', 'Luai', 'Mahmoud', 'Marwan', 'Mazen'],
    fF: ['Mariam', 'Fatima', 'Shamma', 'Latifa', 'Maitha', 'Salama', 'Hessa', 'Sheikha', 'Aisha', 'Mona', 'Sara', 'Reem', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Basma', 'Dalia', 'Danah', 'Deema', 'Fatimah', 'Ghada', 'Hadeel', 'Hala', 'Hanan', 'Haya', 'Jawaher', 'Joud', 'Lama', 'Lujain', 'Maha', 'Malak', 'Manal', 'May', 'Munira', 'Nada', 'Najla', 'Nouf', 'Noura', 'Rana', 'Rania', 'Ruba', 'Sahar', 'Salma', 'Shahad', 'Shatha', 'Wafa', 'Yara', 'Afaf', 'Ahlam', 'Aida', 'Alia', 'Amina', 'Areej', 'Arwa', 'Asalah', 'Asilah', 'Bayan', 'Bushra', 'Dina', 'Eman', 'Esraa', 'Fadia', 'Farida', 'Faten', 'Fawziah', 'Ghalia', 'Habiba', 'Hafsa', 'Hajar', 'Hiam', 'Huda', 'Ibtisam', 'Ikram', 'Ilham', 'Inas', 'Israa', 'Jahan', 'Jamila', 'Karima', 'Kawthar', 'Khaleda', 'Kholoud', 'Laila', 'Lateefa', 'Layan', 'Lina', 'Lubna', 'Magda', 'Majida', 'Marwa', 'Maya', 'Maysaan', 'Maysoon', 'Nadia', 'Nafisa'],
    mL: ['Al-Nahyan', 'Al-Maktoum', 'Al-Qasimi', 'Al-Mualla', 'Al-Sharqi', 'Al-Nuaimi', 'Al-Rumeithi', 'Al-Mazrouei', 'Al-Suwaidi', 'Al-Dhaheri', 'Al-Mansoori', 'Al-Kaabi', 'Al-Ktent', 'Al-Shamsi', 'Al-Hajri', 'Al-Hameli', 'Al-Falasi', 'Al-Marr', 'Al-Mubarak', 'Al-Otaiba', 'Al-Ghurair', 'Al-Habtoor', 'Al-Rostamani', 'Al-Tayer', 'Al-Naboodah', 'Al-Futtaim', 'Al-Sayegh', 'Al-Bawardi', 'Al-Mulla', 'Al-Kamali', 'Al-Muraikhi', 'Al-Neyadi', 'Al-Zaabi', 'Al-Ameri', 'Al-Baloushi', 'Al-Marzooqi', 'Al-Qubaisi', 'Al-Ahmad', 'Al-Dosari', 'Al-Ghaith', 'Al-Harthy', 'Al-Hosani', 'Al-Jneibi', 'Al-Ketbi', 'Al-Mehairi', 'Al-Naimi', 'Al-Raisi', 'Ba-Naja', 'Bin-Ladin', 'Al-Ahmedi', 'Al-Dossary', 'Al-Enazi', 'Al-Kaltham', 'Al-Luhaidan', 'Al-Ruwaiti', 'Al-Sultan', 'Al-Tuwaijri', 'Al-Yami', 'Al-Amer', 'Al-Ateeq', 'Al-Bader', 'Al-Dabal', 'Al-Eissa', 'Al-Fadhli', 'Al-Ghoneim', 'Al-Husseini', 'Al-Issa', 'Al-Jarallah', 'Al-Luwaihan', 'Al-Matar', 'Al-Nafisi', 'Al-Othman', 'Al-Qattan', 'Al-Rashed', 'Al-Saleh', 'Al-Sulaiman', 'Al-Wasel', 'Ba-Osman', 'Al-Attas', 'Al-Dakheel', 'Al-Dukair', 'Al-Hokair', 'Al-Juffali', 'Al-Khereiji', 'Al-Maghraby', 'Al-Muhaideb', 'Al-Othaim', 'Al-Qosaibi', 'Al-Rushaid', 'Al-Zaidan', 'Bin-Zayed', 'Al-Ammar', 'Al-Bandar', 'Al-Dawish', 'Al-Fozan', 'Al-Hathloul', 'Al-Jeraisy', 'Al-Kharafi'],
    fL: ['Al-Nahyan-F', 'Al-Maktoum-F', 'Al-Qasimi-F', 'Al-Mualla-F', 'Al-Sharqi-F', 'Al-Nuaimi-F', 'Al-Rumeithi-F', 'Al-Mazrouei-F', 'Al-Suwaidi-F', 'Al-Dhaheri-F', 'Al-Mansoori-F', 'Al-Kaabi-F', 'Al-Ktent-F', 'Al-Shamsi-F', 'Al-Hajri-F', 'Al-Hameli-F', 'Al-Falasi-F', 'Al-Marr-F', 'Al-Mubarak-F', 'Al-Otaiba-F', 'Al-Ghurair-F', 'Al-Habtoor-F', 'Al-Rostamani-F', 'Al-Tayer-F', 'Al-Naboodah-F', 'Al-Futtaim-F', 'Al-Sayegh-F', 'Al-Bawardi-F', 'Al-Mulla-F', 'Al-Kamali-F', 'Al-Muraikhi-F', 'Al-Neyadi-F', 'Al-Zaabi-F', 'Al-Ameri-F', 'Al-Baloushi-F', 'Al-Marzooqi-F', 'Al-Qubaisi-F', 'Al-Ahmad-F', 'Al-Dosari-F', 'Al-Ghaith-F', 'Al-Harthy-F', 'Al-Hosani-F', 'Al-Jneibi-F', 'Al-Ketbi-F', 'Al-Mehairi-F', 'Al-Naimi-F', 'Al-Raisi-F', 'Ba-Naja-F', 'Bin-Ladin-F', 'Al-Ahmedi-F', 'Al-Dossary-F', 'Al-Enazi-F', 'Al-Kaltham-F', 'Al-Luhaidan-F', 'Al-Ruwaiti-F', 'Al-Sultan-F', 'Al-Tuwaijri-F', 'Al-Yami-F', 'Al-Amer-F', 'Al-Ateeq-F', 'Al-Bader-F', 'Al-Dabal-F', 'Al-Eissa-F', 'Al-Fadhli-F', 'Al-Ghoneim-F', 'Al-Husseini-F', 'Al-Issa-F', 'Al-Jarallah-F', 'Al-Luwaihan-F', 'Al-Matar-F', 'Al-Nafisi-F', 'Al-Othman-F', 'Al-Qattan-F', 'Al-Rashed-F', 'Al-Saleh-F', 'Al-Sulaiman-F', 'Al-Wasel-F', 'Ba-Osman-F', 'Al-Attas-F', 'Al-Dakheel-F', 'Al-Dukair-F', 'Al-Hokair-F', 'Al-Juffali-F', 'Al-Khereiji-F', 'Al-Maghraby-F', 'Al-Muhaideb-F', 'Al-Othaim-F', 'Al-Qosaibi-F', 'Al-Rushaid-F', 'Al-Zaidan-F', 'Bin-Zayed-F', 'Al-Ammar-F', 'Al-Bandar-F', 'Al-Dawish-F', 'Al-Fozan-F', 'Al-Hathloul-F', 'Al-Jeraisy-F', 'Al-Kharafi-F']
  }
};

function cleanArrayStrict(arr) {
  const set = new Set();
  const res = [];
  for (let item of arr) {
    if (typeof item === 'string') {
      item = item.replace(/[-_](M|F|FL|ML|MF|FF|L|S|2|QA|SG|SGF|TW|TWF|TM)\d*$/g, '')
                  .replace(/\d+$/g, '')
                  .replace(/[-_\s]+(F|M|LF|L|S|TW|SG|QA)$/gi, '')
                  .trim();
      if (item.length > 1 && !set.has(item) && !/first|last|name/i.test(item)) {
        set.add(item);
        res.push(item);
      }
    }
  }
  return res;
}

for (const country of ['thailand', 'turki', 'uni emirat arab']) {
  const baseDir = path.join('json', 'firstname_lastname', 'asia', country);
  const data = fullRealDatasets2[country];

  const mF = cleanArrayStrict(data.mF).slice(0, 100);
  const fF = cleanArrayStrict(data.fF).slice(0, 100);
  const mL = cleanArrayStrict(data.mL).slice(0, 100);
  const fL = cleanArrayStrict(data.fL).slice(0, 100);

  fs.writeFileSync(path.join(baseDir, 'male', 'firstname.json'), JSON.stringify(mF, null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'firstname.json'), JSON.stringify(fF, null, 2));
  fs.writeFileSync(path.join(baseDir, 'male', 'lastname.json'), JSON.stringify(mL, null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'lastname.json'), JSON.stringify(fL, null, 2));
}

console.log('Thailand, Turki, and UAE updated with clean 100 real human names!');
