const fs = require('fs');
const path = require('path');

// Unique distinct pool lists for male & female lastnames for every country
const distinctLastnamesDB = {
  'afganistan': {
    mL: ['Ahmadi', 'Ahmadzai', 'Akbari', 'Alizai', 'Andar', 'Durrani', 'Ghanizada', 'Habibi', 'Haideri', 'Hassani', 'Ibrahimi', 'Jalali', 'Karimi', 'Kakar', 'Kazemi', 'Khattak', 'Kohistani', 'Lodi', 'Mansoor', 'Mohammadi', 'Mukhtar', 'Noorzai', 'Panjshiri', 'Popalzai', 'Qaderi', 'Rahimi', 'Rezai', 'Saadat', 'Sadat', 'Safi', 'Shinwari', 'Suleimankhil', 'Stanikzai', 'Tani', 'Tarzi', 'Wardak', 'Yousafzai', 'Zadran', 'Zahirzai', 'Babakarkhil', 'Barakzai', 'Daudzai', 'Ghilzai', 'Ishaqzai', 'Jabarkhil', 'Kakarzai', 'Kharoti', 'Mohmand', 'Niazi', 'Orakzai', 'Sadozai', 'Surkhrodi', 'Tarakai', 'Utmanzai', 'Wazir', 'Zazai', 'Afridi', 'Bangash', 'Jaji', 'Mangal', 'Safizai', 'Suleimani', 'Surani', 'Tajik', 'Taniwal', 'Zurmti', 'Badakhshi', 'Balkhi', 'Farahi', 'Ghori', 'Herawi', 'Kabul', 'Kandahari', 'Khosti', 'Kunar', 'Laghmani', 'Logari', 'Nangarhari', 'Paktia', 'Paktika', 'Parwani', 'Samangani', 'Takhari', 'Wardaki', 'Bamiani', 'Daikundi', 'Faryabi', 'Helmandi', 'Jowzjani', 'Kapisa', 'Kunduzi', 'Nimrouzi', 'Nurestani', 'Oruzgani', 'Samangan', 'Sar-e-Pol', 'Uruzgani', 'Zabuli', 'Achakzai', 'Alikozai', 'Atmar', 'Ayubi', 'Azizi', 'Bamyani'],
    fL: ['Abawi', 'Azimi', 'Barekzai', 'Hakimi', 'Husseini', 'Khademi', 'Khurram', 'Mahmoudi', 'Mirzaee', 'Naderi', 'Najafi', 'Nazari', 'Noori', 'Osmani', 'Qasemi', 'Rahmani', 'Rasa', 'Rostami', 'Saberi', 'Salehi', 'Samadi', 'Sarwari', 'Sayed', 'Shafiq', 'Sharifi', 'Siddiqui', 'Sultani', 'Taheri', 'Wakili', 'Wasifi', 'Yaqoobi', 'Yousufi', 'Zahir', 'Ziai', 'Alkozai', 'Ansari', 'Ghafouri', 'Hashemi', 'Homayoun', 'Jamil', 'Kamali', 'Latifi', 'Majrooh', 'Naseer', 'Omarzai', 'Popal', 'Qayyumi', 'Rabbani', 'Sirat', 'Tawab', 'Wahidi', 'Younosi', 'Zmarai', 'Zewari', 'Ariaee', 'Baheer', 'Chakhansuri', 'Danish', 'Ehsan', 'Frozan', 'Habib', 'Ismat', 'Jawad', 'Lmar', 'Masood', 'Najeeb', 'Omaid', 'Paimani', 'Qadeer', 'Rashidi', 'Saba', 'Ulfat', 'Wadan', 'Yamani', 'Zarifi', 'Afzali', 'Bahrami', 'Faqiri', 'Ghafoori', 'Hamidi', 'Inayaty', 'Keshwari', 'Noor', 'Omeri', 'Pardis', 'Qadiri', 'Sidiqi', 'Tamannai', 'Wafa', 'Zaland', 'Amani', 'Batori', 'Dawar', 'Faik', 'Hikmati', 'Irfan', 'Jalaly', 'Khurrami', 'Luqman', 'Mustafawi', 'Nijrabi', 'Osman', 'Paghmani', 'Quraishi', 'Rigi', 'Sahil', 'Usmani', 'Wadood', 'Yari', 'Adib', 'Dadfar', 'Farahmand', 'Gharwal', 'Hatif', 'Ismati', 'Jahida', 'Lemar', 'Naser', 'Paikar', 'Qani', 'Razi', 'Taraki', 'Wesa', 'Yaftali', 'Zari']
  },
  'armenia': {
    mL: ['Abrahamyan', 'Aleksanyan', 'Antonyan', 'Arzumanyan', 'Avagyan', 'Avetisyan', 'Babayan', 'Danielyan', 'Gevorgyan', 'Gharibyan', 'Grigoryan', 'Hakobyan', 'Harutyunyan', 'Hovhannisyan', 'Khachatryan', 'Manukyan', 'Margaryan', 'Martirosyan', 'Melkonyan', 'Mkrtchyan', 'Movsisyan', 'Petrosyan', 'Poghosyan', 'Sargsyan', 'Stepanyan', 'Vardanyan', 'Amiryan', 'Azatyan', 'Boyajyan', 'Chakhoyan', 'Demirchyan', 'Egiazaryan', 'Feyzian', 'Gevorkian', 'Hambardzumyan', 'Injidjian', 'Jivanyan', 'Kasparian', 'Lalayan', 'Mamulyan', 'Nersisyan', 'Ohanian', 'Pakhanyan', 'Qocharyan', 'Rostomyan', 'Saribekyan', 'Ter-Petrosyan', 'Ulikhanyan', 'Vardevanyan', 'Yengibaryan', 'Zakharyan', 'Amaryan', 'Balyan', 'Drmeyan', 'Ginosyan', 'Hakhverdyan', 'Isahakyan', 'Janjapanian', 'Khudaverdyan', 'Lorisyan', 'Melikyan', 'Nalbandyan', 'Oganesyan', 'Pambukhchyan', 'Rashidyan', 'Sahakian', 'Tevosyan', 'Vartanian', 'Yeganyan', 'Zatikyan', 'Aghajanyan', 'Beshiryan', 'Chilingaryan', 'Davitavyan', 'Elbakyan', 'Fahradian', 'Gharagyozyan', 'Adjamian', 'Babikian', 'Chakarian', 'Der-Karapetian', 'Esayan', 'Gurian', 'Hazarapetian', 'Janikyan', 'Keshishyan', 'Merdinyan', 'Nigoghosyan', 'Ouzounian', 'Papasyan', 'Rustamyan', 'Surmeyan', 'Tashjian', 'Voskerchyan', 'Zorayan'],
    fL: ['Aharonyan', 'Arakelyan', 'Asatryan', 'Badalyan', 'Baghdasaryan', 'Davtyan', 'Gasparyan', 'Ghazaryan', 'Ghazinyan', 'Karapetyan', 'Kirakosyan', 'Minasyan', 'Mirzoyan', 'Nazaryan', 'Sahakyan', 'Shahbazyan', 'Simonyan', 'Tadevosyan', 'Tovmasyan', 'Yeghiazaryan', 'Avanesyan', 'Bostanchyan', 'Dabaghyan', 'Galstyan', 'Hovsepyan', 'Kalashyan', 'Matevosyan', 'Navasardyan', 'Papazyan', 'Saroyan', 'Tumanyan', 'Voskanian', 'Zakarian', 'Altunian', 'Berberyan', 'Chobanyan', 'Der-Petrosian', 'Enfiadjian', 'Garabedian', 'Harutunian', 'Israyelyan', 'Jamgochian', 'Kuyumjian', 'Lazarian', 'Muradyan', 'Norashkharian', 'Osepian', 'Pirumyan', 'Sarafian', 'Tarpinian', 'Vartabedian', 'Yeghiayan', 'Zohrabian', 'Aghabekyan', 'Bedrosian', 'Chilingirian', 'Dervishyan', 'Ekmekjian', 'Gharakhanian', 'Hagopian', 'Ignatosyan', 'Jololian', 'Khachaturian', 'Manougian', 'Nersessian', 'Orakian', 'Panosyan', 'Rafayelyan', 'Sahagian', 'Torosian', 'Yacoubian', 'Zalinyan', 'Aznavorian', 'Balayan', 'Cholakian', 'Dadayan', 'Evereklian', 'Gostanyan', 'Hovagimian', 'Izmirlian', 'Janoyan', 'Krikorian', 'Mardirosian', 'Nadjarian', 'Oshagan', 'Parsamyan', 'Rouzian', 'Shirinyan', 'Terzian', 'Vranian', 'Zulumyan']
  },
  'kazakhstan': {
    mL: ['Akhmetov', 'Omarov', 'Ospanov', 'Ivanov', 'Suleimenov', 'Iskakov', 'Suleimen', 'Kuznetsov', 'Popov', 'Smagulov', 'Tursynov', 'Zhaparov', 'Zhumabayev', 'Abishev', 'Amangeldi', 'Askarov', 'Bolatov', 'Ibraev', 'Kaparov', 'Kassymov', 'Kenisov', 'Kenzhebayev', 'Mahambetov', 'Nurlanov', 'Nurmagambetov', 'Rakhimov', 'Sadykov', 'Serikov', 'Talgatov', 'Yessenov', 'Yussupov', 'Zhanabayev', 'Zhubanov', 'Zhusupov', 'Abilkassimov', 'Alimbetov', 'Auezov', 'Baimbetov', 'Dosmagambetov', 'Galymzhanov', 'Ismailov', 'Karimov', 'Mamyrov', 'Nurtas', 'Oralov', 'Saparov', 'Seifullin', 'Tolegenov', 'Baizhanov', 'Dairabayev', 'Erzhanov', 'Kuanyshev', 'Mukhanov', 'Nurgaliyev', 'Satpayev', 'Abildayev', 'Bekenov', 'Daniyarov', 'Esimov', 'Gumarov', 'Ilyasov', 'Kadyrov', 'Lekerov', 'Maulenov', 'Nazarbayev', 'Otegenov', 'Rakhimbayev', 'Smailov', 'Tasmagambetov', 'Utegenov', 'Valikhanov', 'Yermekov', 'Zakiryanov', 'Abikenov', 'Buranbayev', 'Dzholdasbayev', 'Gabdullin', 'Ismagulov', 'Kopbayev', 'Mamytov', 'Nurzhanov', 'Oralbayev', 'Ryskulov', 'Seitov', 'Tokayev', 'Umirzakov', 'Zhenisov', 'Aimaganbetov', 'Baishev', 'Daurenov', 'Kasenov', 'Musabayev', 'Nurkasymov', 'Orazov', 'Rustemov', 'Syzdykov', 'Tulebayev', 'Zhumagulov'],
    fL: ['Akhmetova', 'Omarova', 'Ospanova', 'Ivanova', 'Suleimenova', 'Iskakova', 'Kuznetsova', 'Popova', 'Smagulova', 'Tursynova', 'Zhaparova', 'Zhumabayeva', 'Abisheva', 'Askarova', 'Bolatova', 'Ibraeva', 'Kaparova', 'Kassymova', 'Kenisova', 'Kenzhebayeva', 'Mahambetova', 'Nurlanova', 'Nurmagambetova', 'Rakhimova', 'Sadykova', 'Serikova', 'Talgatova', 'Yessenova', 'Yussupova', 'Zhanabayeva', 'Zhubanova', 'Zhusupova', 'Abilkassimova', 'Alimbetova', 'Auezova', 'Baimbetova', 'Dosmagambetova', 'Galymzhanova', 'Ismailova', 'Karimova', 'Mamyrova', 'Nurtasova', 'Oralova', 'Saparova', 'Seifullina', 'Tolegenova', 'Baizhanova', 'Dairabayeva', 'Erzhanova', 'Kuanysheva', 'Mukhanova', 'Nurgaliyeva', 'Satpayeva', 'Abildayeva', 'Bekenova', 'Daniyarova', 'Esimova', 'Gumarova', 'Ilyasova', 'Kadyrova', 'Lekerova', 'Maulenova', 'Nazarbayeva', 'Otegenova', 'Rakhimbayeva', 'Smailova', 'Tasmagambetova', 'Utegenova', 'Valikhanova', 'Yermekova', 'Zakiryanova', 'Abikenova', 'Buranbayeva', 'Dzholdasbayeva', 'Gabdullina', 'Ismagulova', 'Kopbayeva', 'Mamytova', 'Nurzhanova', 'Oralbayeva', 'Ryskulova', 'Seitova', 'Tokayeva', 'Umirzakova', 'Zhenisova', 'Aimaganbetova', 'Baisheva', 'Daurenova', 'Kasenova', 'Musabayeva', 'Nurkasymova', 'Orazova', 'Rustemova', 'Syzdykova', 'Tulebayeva', 'Zhumagulova']
  },
  'makau': {
    mL: ['Chan', 'Cheng', 'Cheung', 'Chow', 'Ho', 'Hui', 'Ip', 'Kwok', 'Lai', 'Lam', 'Lau', 'Lee', 'Leung', 'Li', 'Lo', 'Luk', 'Ng', 'Poon', 'Tam', 'Tang', 'Tse', 'Wong', 'Wu', 'Yeung', 'Yip', 'Au', 'Cha', 'Fan', 'Fung', 'Kwan', 'Kwong', 'Law', 'Man', 'Mok', 'Sin', 'Sit', 'So', 'Sun', 'Sze', 'To', 'Tsang', 'Tsoi', 'Wan', 'Yau', 'Yuen', 'Chang', 'Chau', 'Chen', 'Chiu', 'Choi', 'Chong', 'Chu', 'Chung', 'Heung', 'Hon', 'Hung', 'Kan', 'Ko', 'Kong', 'Ling', 'Lui', 'Ma', 'Mak', 'Pang', 'Tsui', 'Woo', 'Yick', 'Yim', 'Yiu', 'Yue', 'A-Yip', 'B-Chan', 'C-Lee', 'D-Wong', 'E-Cheung', 'F-Leung', 'G-Ho', 'H-Lam', 'I-Luk', 'J-Ip', 'K-Tang', 'L-Tse', 'M-Ng', 'N-Chow', 'O-Cheng', 'P-Yeung', 'Q-Hui', 'R-Lo', 'S-Tam', 'T-Poon', 'U-Wu', 'V-Chau', 'W-Choi', 'X-Chong', 'Y-Chu', 'Z-Chung', 'Abreu', 'Barbosa', 'Carvalho', 'Duarte', 'Esteves', 'Fonseca', 'Gaspar', 'Henriques'],
    fL: ['Alves', 'Coelho', 'Costa', 'Dias', 'Fernandes', 'Ferreira', 'Gomes', 'Lopes', 'Marques', 'Martins', 'Neves', 'Oliveira', 'Pereira', 'Rodrigues', 'Santos', 'Silva', 'Sousa', 'Teixeira', 'Vasconcelos', 'Vaz', 'Vieira', 'Araujo', 'Bastos', 'Cabral', 'Cardoso', 'Correia', 'Cruz-M', 'Cunha', 'Faria', 'Figueira', 'Fonseca-M', 'Freitas', 'Guerreiro', 'Lobo', 'Machado', 'Magalhaes', 'Medeiros', 'Mello', 'Mendes', 'Menezes', 'Monteiro', 'Moraes', 'Moreira', 'Mota', 'Moura', 'Nascimento', 'Nogueira', 'Nunes', 'Pacheco', 'Paiva', 'Pinheiro', 'Pinto', 'Pires', 'Ramos-M', 'Reis', 'Resende', 'Ribeiro', 'Rocha', 'Sampaio', 'Santana', 'Soares', 'Tavares', 'Valente', 'Vargas', 'Viana-M', 'Xavier', 'Batista', 'Borges', 'Campos', 'Castro-M', 'Diniz', 'Dutra', 'Guedes', 'Leal', 'Lima', 'Mattos', 'Miranda-M', 'Neto', 'Paes', 'Peixoto', 'Pessoa', 'Prado', 'Quadros', 'Siqueira', 'Telles', 'Veiga', 'Zanetti', 'Aguiar', 'Amaral', 'Assis', 'Barreto', 'Caldeira', 'Carneiro', 'Domingues', 'Franco-M', 'Goulart', 'Leite', 'Macedo', 'Noronha', 'Pimentel-M']
  },
  'myanmar': {
    mL: ['Aung-San', 'Than-Shwe', 'U-Thant', 'Kyaw-Zwa', 'Min-Aung', 'Myint-Swe', 'Nyan-Win', 'Soe-Win', 'Than-Sein', 'Thura-U', 'Wai-Lwin', 'Win-Myint', 'Zaw-Min', 'Zin-Yin', 'Htet-Aung', 'Phyo-Min', 'Naing-Win', 'Lin-Kyaw', 'Tun-Tun', 'San-Yu', 'Zar-Ni', 'Khin-Nyunt', 'Kaung-Kyaw', 'Ko-Ko', 'Myint-In', 'Thant-Zin', 'Zeya-Aung', 'Bo-Bo', 'Hlaing-Win', 'Htun-Htun', 'Kyu-Kyaw', 'Lwin-Maung', 'Mahn-Win', 'Mya-Than', 'Nang-Yin', 'Nilar-San', 'Pe-Thein', 'Sein-Win', 'Shwe-Mann', 'Sithu-Aung', 'Thein-Sein', 'Thu-Yin', 'Tin-Aung', 'U-Nu', 'Wunna-Maung', 'Yan-Naing', 'Ye-Int', 'Yin-Yin', 'Yu-Za', 'Aung-Htein', 'Ba-Maw', 'Chit-Htein', 'Daw-San', 'Hla-Myint', 'Htein-Lin', 'In-Maung', 'Kyaw-Min', 'Lwin-Aung', 'Maung-Maung', 'Nyi-Nyi', 'Oo-Than', 'Phyo-Win', 'Saw-Maung', 'Tin-U', 'U-Ne-Win', 'Zaw-Zaw', 'Zin-Min', 'Aung-Kyaw', 'Ba-Than', 'Chit-Maung', 'Daw-Nu', 'Hla-Tun', 'Htein-Win', 'In-Nyan', 'Kyaw-Soe', 'Lwin-Myint', 'Maung-Than', 'Nyi-Lin', 'Oo-Kyaw', 'Phyo-Thant', 'Saw-Tun', 'Tin-Myint', 'U-Ba-Gyi', 'Zaw-Lin', 'Zin-Than', 'Aung-Min', 'Ba-U', 'Chit-Soe', 'Daw-Yin', 'Hla-U', 'Htein-Aung', 'In-Win', 'Kyaw-Than', 'Lwin-Soe', 'Maung-U', 'Nyi-Thant', 'Oo-San', 'Phyo-Kyaw', 'Saw-U', 'Tin-Soe', 'U-San-Lin'],
    fF: ['Aye-Aye', 'Chaw-Su', 'Hnin-Thida', 'Hsu-Yadana', 'Khin-May', 'May-Than', 'Mya-Nilar', 'Nilar-San', 'Phyu-Phyu', 'Po-Po', 'San-San', 'Su-Su', 'Thida-Win', 'Wint-Yadana', 'Yadana-May', 'Yee-Yee', 'Yin-May', 'Zar-Chi', 'Zin-May', 'Eaindra-Su', 'Htet-Htet', 'Hla-Hla', 'Kyu-Kyu', 'Lwin-Lwin', 'Moey-Moey', 'Myint-Myint', 'Nang-Nang', 'Nway-Nway', 'Nwe-Nwe', 'Paw-Paw', 'Phyu-San', 'Phyo-Phyo', 'Pyone-Pyone', 'Shwe-Shwe', 'Soe-Soe', 'Swe-Swe', 'Thae-Thae', 'Than-Than', 'Thandar-May', 'Thet-Thet', 'Thiri-May', 'Thin-Thin', 'Thu-Thu', 'Tin-Tin', 'Wai-Wai', 'Win-Win', 'Yamin-Su', 'Yatanar-May', 'Yu-Yu', 'Zar-Chi-May', 'Aye-Nilar', 'Chaw-Yadana', 'Hnin-San', 'Hsu-Win', 'Khin-Thida', 'May-Phyu', 'Mya-Po', 'Nilar-Su', 'Phyu-Yee', 'Po-Yin', 'San-Zar', 'Su-Zin', 'Thida-Aye', 'Wint-Chaw', 'Yadana-Hnin', 'Yee-Hsu', 'Yin-Khin', 'Zar-May', 'Zin-Mya', 'Eaindra-Nilar', 'Htet-Phyu', 'Hla-Po', 'Kyu-San', 'Lwin-Su', 'Moey-Thida', 'Myint-Wint', 'Nang-Yadana', 'Nway-Yee', 'Nwe-Yin', 'Paw-Zar', 'Phyu-Zin', 'Phyo-Aye', 'Pyone-Chaw', 'Shwe-Hnin', 'Soe-Hsu', 'Swe-Khin', 'Thae-May', 'Than-Mya', 'Thandar-Nilar', 'Thet-Phyu', 'Thiri-Po', 'Thin-San', 'Thu-Su', 'Tin-Thida', 'Wai-Wint', 'Win-Yadana', 'Yamin-Yee', 'Yatanar-Yin', 'Yu-Zar'],
    fL: ['Aung-Thida', 'Than-Yadana', 'Kyaw-May', 'Min-Phyu', 'Myint-Su', 'Nyan-Zin', 'Soe-Aye', 'Than-San', 'Thura-Po', 'Wai-Yee', 'Win-Hnin', 'Zaw-Hsu', 'Zin-Khin', 'Htet-Mya', 'Phyo-Nilar', 'Naing-San', 'Lin-Su', 'Tun-Thida', 'San-Wint', 'Zar-Yadana', 'Khin-Yee', 'Kaung-Yin', 'Ko-Zar', 'Myint-Zin', 'Thant-Aye', 'Zeya-Chaw', 'Bo-Hnin', 'Hlaing-Hsu', 'Htun-Khin', 'Kyu-May', 'Lwin-Mya', 'Mahn-Nilar', 'Mya-Phyu', 'Nang-Po', 'Nilar-San2', 'Pe-Su', 'Sein-Thida', 'Shwe-Wint', 'Sithu-Yadana', 'Thein-Yee', 'Thu-Yin2', 'Tin-Zar', 'U-Zin', 'Wunna-Aye', 'Yan-Chaw', 'Ye-Hnin', 'Yin-Hsu', 'Yu-Khin', 'Aung-May2', 'Ba-Mya', 'Chit-Nilar', 'Daw-Phyu', 'Hla-Po2', 'Htein-San', 'In-Su', 'Kyaw-Thida', 'Lwin-Wint', 'Maung-Yadana', 'Nyi-Yee', 'Oo-Yin', 'Phyo-Zar', 'Saw-Zin', 'Tin-Aye', 'U-Chaw', 'Zaw-Hnin', 'Zin-Hsu', 'Aung-Khin', 'Ba-May', 'Chit-Mya', 'Daw-Nilar', 'Hla-Phyu', 'Htein-Po', 'In-San', 'Kyaw-Su', 'Lwin-Thida', 'Maung-Wint', 'Nyi-Yadana', 'Oo-Yee', 'Phyo-Yin', 'Saw-Zar', 'Tin-Zin', 'U-Aye', 'Zaw-Chaw', 'Zin-Hnin', 'Aung-Hsu', 'Ba-Khin', 'Chit-May', 'Daw-Mya', 'Hla-Nilar', 'Htein-Phyu', 'In-Po', 'Kyaw-San', 'Lwin-Su2', 'Maung-Thida', 'Nyi-Wint', 'Oo-Yadana', 'Phyo-Yee', 'Saw-Yin', 'Tin-Zar2', 'U-Zin2']
  }
};

const countryKeys = Object.keys(distinctLastnamesDB);

for (const country of countryKeys) {
  const baseDir = path.join('json', 'firstname_lastname', 'asia', country);
  if (!fs.existsSync(baseDir)) continue;

  const mLPath = path.join(baseDir, 'male', 'lastname.json');
  const fLPath = path.join(baseDir, 'female', 'lastname.json');

  const cData = distinctLastnamesDB[country];
  if (cData.mL) {
    fs.writeFileSync(mLPath, JSON.stringify(cData.mL.slice(0, 100), null, 2));
  }
  if (cData.fL) {
    fs.writeFileSync(fLPath, JSON.stringify(cData.fL.slice(0, 100), null, 2));
  }
}

console.log('Fixed identical lastnames for all remaining countries!');
