const fs = require('fs');
const path = require('path');

// Target 18 countries in Asia: irak to pakistan
const countries18 = [
  'irak', 'iran', 'israel', 'jepang', 'kamboja',
  'kazakhstan', 'kirgizstan', 'korea selatan', 'korea utara', 'kuwait',
  'laos', 'lebanon', 'makau', 'malaysia', 'maldives',
  'mongolia', 'myanmar', 'nepal', 'oman', 'pakistan'
];

function pool100(arr) {
  const set = new Set();
  const res = [];
  for (const item of arr) {
    if (!set.has(item) && item.trim().length > 0) {
      set.add(item.trim());
      res.push(item.trim());
    }
  }
  let idx = 0;
  const base = Array.from(set);
  while (res.length < 100 && base.length > 0) {
    const item = base[idx % base.length];
    if (res.length < 100) res.push(item);
    idx++;
  }
  return res.slice(0, 100);
}

const db = {
  'irak': {
    mF: pool100(['Ali', 'Ahmed', 'Hassan', 'Hussein', 'Mustafa', 'Omar', 'Mohammed', 'Ibrahim', 'Mahmoud', 'Tariq', 'Zaid', 'Youssef', 'Amir', 'Bilal', 'Haider', 'Hamza', 'Karrar', 'Murtadha', 'Nabeel', 'Qasim', 'Saad', 'Sajjad', 'Salam', 'Waleed', 'Yasser', 'Abbas', 'Adel', 'Alaa', 'Amar', 'Bashar', 'Fahad', 'Faris', 'Fouad', 'Hadi', 'Hakim', 'Hazem', 'Hikmat', 'Hikmatullah', 'Imad', 'Jafar', 'Jalal', 'Jamal', 'Kamel', 'Karim', 'Khaled', 'Layth', 'Luay', 'Majid', 'Marwan', 'Mazin']),
    fF: pool100(['Zainab', 'Fatima', 'Zahra', 'Mariam', 'Aya', 'Noor', 'Sara', 'Huda', 'Rania', 'Mona', 'Laila', 'Hala', 'Dalia', 'Reem', 'Abeer', 'Amal', 'Asma', 'Basma', 'Dina', 'Eman', 'Ghada', 'Hanan', 'Hiam', 'Hind', 'Inas', 'Jawaher', 'Khulood', 'Lina', 'Maha', 'Manal', 'Nada', 'Najat', 'Najwa', 'Noura', 'Rasha', 'Rawan', 'Sahar', 'Salma', 'Samira', 'Shatha', 'Wafa', 'Yasmin', 'Yousra', 'Ahlam', 'Alia', 'Amina', 'Areej', 'Arwa', 'Bayan', 'Bushra']),
    mL: pool100(['Al-Iraqi', 'Al-Baghdadi', 'Al-Basri', 'Al-Tikriti', 'Al-Mousawi', 'Al-Hashemi', 'Al-Obaidi', 'Al-Dulaimi', 'Al-Janabi', 'Al-Zubaidi', 'Al-Tamimi', 'Al-Jibouri', 'Al-Saadi', 'Al-Maliki', 'Al-Khafaji', 'Al-Bayati', 'Al-Shimari', 'Al-Sudani', 'Al-Sadr', 'Al-Hakim', 'Al-Ameri', 'Al-Attar', 'Al-Kadhimi', 'Al-Mahdawi', 'Al-Nuaimi', 'Al-Qaisi', 'Al-Rubaie', 'Al-Shammari', 'Al-Waili', 'Al-Zaidi', 'Al-Asadi', 'Al-Drafti', 'Al-Fadhli', 'Al-Ghurabi', 'Al-Hamdani', 'Al-Husseini', 'Al-Issa', 'Al-Kaabi', 'Al-Karkhi', 'Al-Khazaali', 'Al-Lami', 'Al-Majidi', 'Al-Mansouri', 'Al-Mutar', 'Al-Najafi', 'Al-Naseri', 'Al-Quraishi', 'Al-Rifaie', 'Al-Saffar', 'Al-Shawi']),
    fL: pool100(['Al-Husseini', 'Al-Hashemi', 'Al-Attar', 'Al-Bayati', 'Al-Basri', 'Al-Baghdadi', 'Al-Tikriti', 'Al-Obaidi', 'Al-Janabi', 'Al-Zubaidi', 'Al-Tamimi', 'Al-Jibouri', 'Al-Saadi', 'Al-Maliki', 'Al-Khafaji', 'Al-Shimari', 'Al-Sudani', 'Al-Sadr', 'Al-Hakim', 'Al-Ameri', 'Al-Kadhimi', 'Al-Mahdawi', 'Al-Nuaimi', 'Al-Qaisi', 'Al-Rubaie', 'Al-Shammari', 'Al-Waili', 'Al-Zaidi', 'Al-Asadi', 'Al-Drafti', 'Al-Fadhli', 'Al-Ghurabi', 'Al-Hamdani', 'Al-Issa', 'Al-Kaabi', 'Al-Karkhi', 'Al-Khazaali', 'Al-Lami', 'Al-Majidi', 'Al-Mansouri', 'Al-Mutar', 'Al-Najafi', 'Al-Naseri', 'Al-Quraishi', 'Al-Rifaie', 'Al-Saffar', 'Al-Shawi', 'Al-Draft', 'Al-Halali', 'Al-Rawi'])
  },
  'iran': {
    mF: pool100(['Ali', 'Amir', 'Mohammad', 'Reza', 'Hossein', 'Mehdi', 'Saeed', 'Alireza', 'Hamid', 'Farhad', 'Kaveh', 'Arash', 'Darius', 'Cyrus', 'Shahram', 'Babak', 'Navid', 'Pejman', 'Payam', 'Ramin', 'Saman', 'Sina', 'Sohrab', 'Behnam', 'Ehsan', 'Iman', 'Kamran', 'Kian', 'Mahdi', 'Milad', 'Nima', 'Pouya', 'Soroush', 'Yashar', 'Arman', 'Aria', 'Behrouz', 'Bijan', 'Farzad', 'Ghasem', 'Javad', 'Keyvan', 'Maziar', 'Omid', 'Parviz', 'Rashid', 'Siamak', 'Vahid', 'Youssef', 'Zaman']),
    fF: pool100(['Fatemeh', 'Zahra', 'Maryam', 'Narges', 'Shirin', 'Anahita', 'Arezoo', 'Azadeh', 'Bahar', 'Elham', 'Farnaz', 'Ghazal', 'Golnar', 'Leila', 'Mahnaz', 'Marjan', 'Mina', 'Nasrin', 'Niloufar', 'Parisa', 'Roxana', 'Sadaf', 'Sahar', 'Sanaz', 'Sara', 'Sepideh', 'Shahrzad', 'Simin', 'Soraya', 'Tara', 'Yasaman', 'Yeganeh', 'Ziba', 'Aida', 'Atrin', 'Behnaz', 'Darya', 'Elaheh', 'Farideh', 'Giti', 'Hasti', 'Iran', 'Katayoun', 'Ladan', 'Mahsa', 'Neda', 'Parvin', 'Roya', 'Shahnaz', 'Zohreh']),
    mL: pool100(['Hosseini', 'Rezai', 'Mohammadi', 'Ahmadi', 'Ebrahimi', 'Ghasemi', 'Ghorbani', 'Karimi', 'Mousavi', 'Najafi', 'Rahimi', 'Rostami', 'Sadeghi', 'Taheri', 'Zarei', 'Abbasi', 'Azizi', 'Bahrami', 'Fathi', 'Haideri', 'Jafari', 'Kazemi', 'Mahmoudi', 'Mirzai', 'Naderi', 'Noori', 'Pirouz', 'Rezaei', 'Saberi', 'Salehi', 'Samadi', 'Sarwari', 'Shafiq', 'Sharifi', 'Siddiqui', 'Sultani', 'Wakili', 'Yaqoobi', 'Yousufi', 'Zahir', 'Asgari', 'Bagheri', 'Dehghan', 'Faraji', 'Gholami', 'Habibi', 'Hashemi', 'Khani', 'Maleki', 'Moradi']),
    fL: pool100(['Ahmadi', 'Hosseini', 'Rezai', 'Mohammadi', 'Ebrahimi', 'Ghasemi', 'Ghorbani', 'Karimi', 'Mousavi', 'Najafi', 'Rahimi', 'Rostami', 'Sadeghi', 'Taheri', 'Zarei', 'Abbasi', 'Azizi', 'Bahrami', 'Fathi', 'Haideri', 'Jafari', 'Kazemi', 'Mahmoudi', 'Mirzai', 'Naderi', 'Noori', 'Pirouz', 'Rezaei', 'Saberi', 'Salehi', 'Samadi', 'Sarwari', 'Shafiq', 'Sharifi', 'Siddiqui', 'Sultani', 'Wakili', 'Yaqoobi', 'Yousufi', 'Zahir', 'Asgari', 'Bagheri', 'Dehghan', 'Faraji', 'Gholami', 'Habibi', 'Hashemi', 'Khani', 'Maleki', 'Moradi'])
  },
  'israel': {
    mF: pool100(['David', 'Yossi', 'Ariel', 'Daniel', 'Noam', 'Eitan', 'Omer', 'Itai', 'Ido', 'Uri', 'Amit', 'Yonatan', 'Moshe', 'Eli', 'Avraham', 'Ben', 'Guy', 'Nir', 'Roey', 'Shai', 'Tal', 'Yair', 'Yuval', 'Bar', 'Dor', 'Gal', 'Gil', 'Lior', 'Matan', 'Or', 'Ran', 'Tom', 'Yael', 'Adam', 'Amir', 'Asaf', 'Chen', 'Dror', 'Eran', 'Erez', 'Gadi', 'Ilan', 'Kobi', 'Liron', 'Nadav', 'Ofer', 'Oren', 'Ronen', 'Sagi', 'Ziv']),
    fF: pool100(['Noa', 'Maya', 'Tamar', 'Shira', 'Yael', 'Adiel', 'Agam', 'Avigail', 'Ella', 'Inbar', 'Lian', 'Michal', 'Noga', 'Roni', 'Shani', 'Tal', 'Yuval', 'Adi', 'Amit', 'Bar', 'Chen', 'Gal', 'Gali', 'Gil', 'Lior', 'May', 'Noy', 'Or', 'Ofir', 'Ofri', 'Rotem', 'Shir', 'Shuri', 'Stav', 'Yaara', 'Zohar', 'Alma', 'Anat', 'Dana', 'Daphna', 'Einat', 'Hadas', 'Keren', 'Limor', 'Naama', 'Neta', 'Nitzan', 'Orly', 'Roni', 'Sharon']),
    mL: pool100(['Cohen', 'Levi', 'Mizrahi', 'Peretz', 'Biton', 'Dahan', 'Avraham', 'Friedman', 'Malka', 'Azoulay', 'Katz', 'Yosef', 'David', 'Amar', 'Odessky', 'Klein', 'Shapiro', 'Golan', 'Levin', 'Stern', 'Gross', 'Weiss', 'Schwartz', 'Green', 'Rosenberg', 'Fischer', 'Feldman', 'Ginzburg', 'Hirsch', 'Kaplan', 'Kogan', 'Novak', 'Rabinowitz', 'Segal', 'Shulman', 'Goldberg', 'Silver', 'Spector', 'Zimmerman', 'Adler', 'Bernstein', 'Eisenberg', 'Epstein', 'Frankel', 'Gottesman', 'Heller', 'Kaufman', 'Lustig', 'Nussbaum', 'Reich']),
    fL: pool100(['Cohen', 'Levi', 'Mizrahi', 'Peretz', 'Biton', 'Dahan', 'Avraham', 'Friedman', 'Malka', 'Azoulay', 'Katz', 'Yosef', 'David', 'Amar', 'Odessky', 'Klein', 'Shapiro', 'Golan', 'Levin', 'Stern', 'Gross', 'Weiss', 'Schwartz', 'Green', 'Rosenberg', 'Fischer', 'Feldman', 'Ginzburg', 'Hirsch', 'Kaplan', 'Kogan', 'Novak', 'Rabinowitz', 'Segal', 'Shulman', 'Goldberg', 'Silver', 'Spector', 'Zimmerman', 'Adler', 'Bernstein', 'Eisenberg', 'Epstein', 'Frankel', 'Gottesman', 'Heller', 'Kaufman', 'Lustig', 'Nussbaum', 'Reich'])
  },
  'jepang': {
    mF: pool100(['Ren', 'Haruto', 'Sora', 'Yuto', 'Touma', 'Riku', 'Minato', 'Itsuki', 'Kaito', 'Asahi', 'Hinata', 'Yamato', 'Sousuke', 'Yuma', 'Ryusei', 'Kouki', 'Tatsuk', 'Hayato', 'Takumi', 'Daiki', 'Kazuki', 'Kenji', 'Kenta', 'Naoki', 'Ryota', 'Shota', 'Takuya', 'Yuki', 'Yuta', 'Yuma', 'Akira', 'Daisuke', 'Hiroshi', 'Jun', 'Ken', 'Makoto', 'Satoshi', 'Shin', 'Tatsuya', 'Yuji', 'Atsushi', 'Fumio', 'Hideki', 'Isamu', 'Kiyoshi', 'Masato', 'Osamu', 'Shigeru', 'Takashi', 'Yasushi']),
    fF: pool100(['Himari', 'Hina', 'Yui', 'Akari', 'Ichika', 'Kanna', 'Rio', 'Mei', 'Yuna', 'Sakura', 'Aoi', 'Rin', 'Mio', 'Yuka', 'Misaki', 'Nana', 'Honoka', 'Ayaka', 'Haruka', 'Miyu', 'Nanami', 'Riko', 'Saki', 'Yui', 'Yuka', 'Yuri', 'Asuka', 'Emi', 'Hana', 'Hikari', 'Kana', 'Maki', 'Mana', 'Mayu', 'Megumi', 'Naoko', 'Rie', 'Sayaka', 'Tomoko', 'Yoko', 'Chie', 'Fumiko', 'Hiroko', 'Junko', 'Kazuko', 'Keiko', 'Michiko', 'Sachiko', 'Toko', 'Yoshiko']),
    mL: pool100(['Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato', 'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Saito', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Yamazaki', 'Mori', 'Abe', 'Ikeda', 'Hashimoto', 'Yamashita', 'Ishikawa', 'Nakajima', 'Maeda', 'Fujita', 'Ogawa', 'Goto', 'Okada', 'Hasegawa', 'Murakami', 'Kondo', 'Ishii', 'Saito', 'Sakata', 'Nakai', 'Takeda', 'Fukuda', 'Ueno', 'Miura', 'Fujii', 'Nishimura', 'Fujiwara', 'Okamoto', 'Matsuda', 'Nakagawa']),
    fL: pool100(['Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato', 'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Saito', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Yamazaki', 'Mori', 'Abe', 'Ikeda', 'Hashimoto', 'Yamashita', 'Ishikawa', 'Nakajima', 'Maeda', 'Fujita', 'Ogawa', 'Goto', 'Okada', 'Hasegawa', 'Murakami', 'Kondo', 'Ishii', 'Saito', 'Sakata', 'Nakai', 'Takeda', 'Fukuda', 'Ueno', 'Miura', 'Fujii', 'Nishimura', 'Fujiwara', 'Okamoto', 'Matsuda', 'Nakagawa'])
  },
  'kamboja': {
    mF: pool100(['Sok', 'Sao', 'Chan', 'Chea', 'Heng', 'Keo', 'Kim', 'Khem', 'Long', 'Mao', 'Meng', 'Phan', 'Rith', 'Sam', 'Sen', 'Seng', 'Sokha', 'Vann', 'Vichai', 'Visal', 'Bora', 'Bunthoeun', 'Chhay', 'Dara', 'Kosal', 'Makara', 'Narith', 'Norith', 'Phirun', 'Rath', 'Rithy', 'Samnang', 'Sophal', 'Sovann', 'Vibol', 'Virak', 'Vuthy', 'Chamroeun', 'Chann', 'Cheat', 'Chheng', 'Khemra', 'Kimsour', 'Mony', 'Pros', 'Phala', 'Phanna', 'Rathanak', 'Ratanak', 'Rotana']),
    fF: pool100(['Bopha', 'Channary', 'Chantara', 'Chhayya', 'Davi', 'Kalliyan', 'Kravann', 'Kunthea', 'Kolab', 'Maly', 'Neary', 'Nimol', 'Phoung', 'Rachana', 'Rithy', 'Romchang', 'Sophea', 'Sorphea', 'Sopheak', 'Soriya', 'Sothy', 'Srey', 'Sreypov', 'Sreymom', 'Thida', 'Vannak', 'Voleak', 'Chenda', 'Chhorvy', 'Kesa', 'Kha', 'Kravan', 'Leakhana', 'Lina', 'Makara', 'Melea', 'Montha', 'Nary', 'Nisay', 'Pech', 'Phalla', 'Phally', 'Phea', 'Pheakdei', 'Phka', 'Pisey', 'Rani', 'Rasmey', 'Ratha', 'Rattana']),
    mL: pool100(['Hun', 'Sam', 'Sok', 'Kem', 'Kheng', 'Tep', 'Meas', 'Kha', 'Khieu', 'Ung', 'Nguon', 'Peng', 'Son', 'Nhek', 'Ly', 'Lim', 'Tan', 'Eang', 'Ou', 'Chhay', 'Pen', 'In', 'Sar', 'Tioulong', 'Sann', 'Chan', 'Chea', 'Heng', 'Keo', 'Kim', 'Long', 'Mao', 'Phan', 'Seng', 'Vann', 'Bora', 'Chann', 'Chheng', 'Chhay', 'Kosal', 'Kimsour', 'Phala', 'Phanna', 'Rath', 'Rotana', 'Sophal', 'Sovann', 'Vibol', 'Virak', 'Vuthy']),
    fL: pool100(['Hun', 'Sam', 'Sok', 'Kem', 'Kheng', 'Tep', 'Meas', 'Kha', 'Khieu', 'Ung', 'Nguon', 'Peng', 'Son', 'Nhek', 'Ly', 'Lim', 'Tan', 'Eang', 'Ou', 'Chhay', 'Pen', 'In', 'Sar', 'Tioulong', 'Sann', 'Chan', 'Chea', 'Heng', 'Keo', 'Kim', 'Long', 'Mao', 'Phan', 'Seng', 'Vann', 'Bora', 'Chann', 'Chheng', 'Chhay', 'Kosal', 'Kimsour', 'Phala', 'Phanna', 'Rath', 'Rotana', 'Sophal', 'Sovann', 'Vibol', 'Virak', 'Vuthy'])
  },
  'kazakhstan': {
    mF: pool100(['Alihan', 'Nurislam', 'Amir', 'Ramazan', 'Aldiyar', 'Aisultan', 'Arsen', 'Alan', 'Sanzhar', 'Islam', 'Nurasyl', 'Dias', 'Daniyal', 'Danial', 'Miras', 'Abylai', 'Alen', 'Arman', 'Bakhtiyar', 'Doszhan', 'Erlan', 'Kairat', 'Kanat', 'Marat', 'Murat', 'Nurlan', 'Ruslan', 'Serik', 'Talgat', 'Yernar', 'Abzal', 'Adilet', 'Aidos', 'Akzhol', 'Alisher', 'Anuar', 'Askar', 'Azamat', 'Bauyrzhan', 'Berik', 'Dauren', 'Eldar', 'Galymzhan', 'Ilyas', 'Kazybek', 'Medet', 'Nurbek', 'Olzhas', 'Samat', 'Zhandos']),
    fF: pool100(['Medina', 'Aisulu', 'Rayana', 'Ailu', 'Ayala', 'Aisha', 'Amina', 'Asylay', 'Inkar', 'Kausar', 'Adiya', 'Aiym', 'Aruzhan', 'Alina', 'Dana', 'Diana', 'Zere', 'Aida', 'Aigerim', 'Akerke', 'Akmaral', 'Aliya', 'Alma', 'Anar', 'Arailym', 'Asel', 'Balzhan', 'Daniya', 'Dinara', 'Elmira', 'Gulnar', 'Gulzhan', 'Kuralay', 'Laura', 'Madina', 'Malika', 'Mariya', 'Nazerke', 'Nurgul', 'Roza', 'Saltanat', 'Samal', 'Saule', 'Sholpan', 'Togzhan', 'Zhaniya', 'Zhansaya', 'Zharas', 'Zhibek', 'Zulkhia']),
    mL: pool100(['Akhmetov', 'Omarov', 'Kim', 'Ospanov', 'Ivanov', 'Suleimenov', 'Iskakov', 'Suleimen', 'Kuznetsov', 'Popov', 'Smagulov', 'Tursynov', 'Zhaparov', 'Zhumabayev', 'Abishev', 'Amangeldi', 'Askarov', 'Bolatov', 'Ibraev', 'Kaparov', 'Kassymov', 'Kenisov', 'Kenzhebayev', 'Mahambetov', 'Nurlanov', 'Nurmagambetov', 'Rakhimov', 'Sadykov', 'Serikov', 'Talgatov', 'Yessenov', 'Yussupov', 'Zhanabayev', 'Zhubanov', 'Zhusupov', 'Abilkassimov', 'Alimbetov', 'Auezov', 'Baimbetov', 'Dosmagambetov', 'Galymzhanov', 'Ismailov', 'Kalieva', 'Karimov', 'Mamyrov', 'Nurtas', 'Oralov', 'Saparov', 'Seifullin', 'Tolegenov']),
    fL: pool100(['Akhmetova', 'Omarova', 'Kim', 'Ospanova', 'Ivanova', 'Suleimenova', 'Iskakova', 'Kuznetsova', 'Popova', 'Smagulova', 'Tursynova', 'Zhaparova', 'Zhumabayeva', 'Abisheva', 'Askarova', 'Bolatova', 'Ibraeva', 'Kaparova', 'Kassymova', 'Kenisova', 'Kenzhebayeva', 'Mahambetova', 'Nurlanova', 'Nurmagambetova', 'Rakhimova', 'Sadykova', 'Serikova', 'Talgatova', 'Yessenova', 'Yussupova', 'Zhanabayeva', 'Zhubanova', 'Zhusupova', 'Abilkassimova', 'Alimbetova', 'Auezova', 'Baimbetova', 'Dosmagambetova', 'Galymzhanova', 'Ismailova', 'Karimova', 'Mamyrova', 'Nurtasova', 'Oralova', 'Saparova', 'Seifullina', 'Tolegenova', 'Zulkhiaeva', 'Zereva', 'Aisulueva'])
  },
  'kirgizstan': {
    mF: pool100(['Umar', 'Ali', 'Nurislam', 'Amir', 'Bilal', 'Ramazan', 'Elkhan', 'Alikhan', 'Muhammed', 'Emir', 'Adilet', 'Aibek', 'Akylbek', 'Asan', 'Azamat', 'Bakai', 'Bekzhan', 'Dastan', 'Erlan', 'Kairat', 'Kanat', 'Kuban', 'Marat', 'Mirbek', 'Murat', 'Nurlan', 'Ruslan', 'Samat', 'Talgat', 'Ulan', 'Abdykalyk', 'Adylbek', 'Almaz', 'Argen', 'Askar', 'Bakyt', 'Berik', 'Chingiz', 'Eldar', 'Ilyas', 'Kanybek', 'Kalybek', 'Manas', 'Medet', 'Nurbek', 'Omurbek', 'Sanzhar', 'Talant', 'Zholdosh', 'Zhumabek']),
    fF: pool100(['Rayana', 'Amina', 'Medina', 'Ailin', 'Fatima', 'Aruuzhan', 'Safiya', 'Aisha', 'Kausar', 'Sumaya', 'Aida', 'Aigerim', 'Aizhan', 'Akmaral', 'Altynai', 'Anara', 'Asel', 'Baktygul', 'Cholpon', 'Dinara', 'Elmira', 'Gulnara', 'Gulzhan', 'Jyldyz', 'Kanykei', 'Khadicha', 'Lazzat', 'Madina', 'Meerim', 'Nurgul', 'Nurzhan', 'Roza', 'Saltanat', 'Samara', 'Nazira', 'Syimyk', 'Tattibubu', 'Zhamilya', 'Zhanyl', 'Zhibek', 'Adiya', 'Aiym', 'Aruuke', 'Dariya', 'Eliza', 'Kamila', 'Malika', 'Sabina', 'Sezim', 'Zarina']),
    mL: pool100(['Ismailov', 'Abdullayev', 'Jumabayev', 'Sadykov', 'Askarov', 'Akhmetov', 'Kim', 'Orozobekov', 'Ivanov', 'Tursunov', 'Usenov', 'Zhusupov', 'Abdykadyrov', 'Asanov', 'Bakirov', 'Bolotov', 'Eraliyev', 'Ibraimov', 'Kaparov', 'Kenzhebayev', 'Mamytov', 'Nurlanov', 'Rakhmanov', 'Serikov', 'Suleymanov', 'Talgatov', 'Tashiyev', 'Toktobev', 'Turusbekov', 'Yusupov', 'Abdyrakhmanov', 'Alimov', 'Aytmatov', 'Baimatov', 'Djumagulov', 'Isakov', 'Karimov', 'Kasymov', 'Mambetov', 'Niyazov', 'Omurov', 'Saparov', 'Sydykov', 'Tursunbekov', 'Zhaparov', 'Zholoshev', 'Zulpykarov', 'Abdykerimov', 'Adylov', 'Akmatov']),
    fL: pool100(['Ismailova', 'Abdullayeva', 'Jumabayeva', 'Sadykova', 'Askarova', 'Akhmetova', 'Kim', 'Orozobekova', 'Ivanova', 'Tursunova', 'Usenova', 'Zhusupova', 'Abdykadyrova', 'Asanova', 'Bakirova', 'Bolotova', 'Eraliyeva', 'Ibraimova', 'Kaparova', 'Kenzhebayeva', 'Mamytova', 'Nurlanova', 'Rakhmanova', 'Serikova', 'Suleymanova', 'Talgatova', 'Tashiyeva', 'Toktobeva', 'Turusbekova', 'Yusupova', 'Abdyrakhmanova', 'Alimova', 'Aytmatova', 'Baimatova', 'Djumagulova', 'Isakova', 'Karimova', 'Kasymova', 'Mambetova', 'Niyazova', 'Omurova', 'Saparova', 'Sydykova', 'Tursunbekova', 'Zhaparova', 'Zholosheva', 'Zulpykarova', 'Abdykerimova', 'Adylova', 'Akmatova'])
  },
  'korea selatan': {
    mF: pool100(['Seo-jun', 'Ha-joon', 'Do-yun', 'Eun-woo', 'Si-woo', 'Ji-ho', 'Min-jun', 'Ye-jun', 'Joo-won', 'Yu-jun', 'Hyun-woo', 'Ji-hoon', 'Jun-seo', 'Geon-woo', 'Woo-jin', 'Do-hyun', 'Jung-woo', 'Seung-hyun', 'Ji-woo', 'Min-jae', 'Jun-young', 'Seung-woo', 'Dong-hyun', 'Sung-min', 'Jae-hyun', 'Hyun-jun', 'Min-seok', 'Sang-woo', 'Tae-yang', 'Myung-soo', 'Chan-woo', 'Dae-hyun', 'Jin-woo', 'Kyung-soo', 'Seong-jin', 'Tae-hyun', 'Yong-jun', 'Byung-hun', 'Dong-wook', 'Ho-seok', 'Jae-beom', 'Jong-in', 'Kwang-soo', 'Min-ho', 'Seok-jin', 'Tae-hyung', 'Won-bin', 'Young-jae', 'Yoon-gi', 'Kyu-hyun']),
    fF: pool100(['Ji-an', 'Seo-ah', 'Ha-yoon', 'Seo-yun', 'Ha-eun', 'Ji-woo', 'Ji-yoo', 'A-rin', 'So-yul', 'Ji-a', 'Chae-won', 'Seo-yeon', 'Eun-seo', 'Da-eun', 'Yuna', 'Min-seo', 'Ha-rin', 'So-eun', 'Ye-eun', 'Si-ah', 'Su-bin', 'Ji-min', 'Yae-ji', 'So-hee', 'Hye-jin', 'Eun-ji', 'Min-ji', 'Bo-young', 'So-young', 'Sun-hee', 'Ji-young', 'Hyo-jin', 'Mi-rae', 'Seul-gi', 'Yu-jin', 'Ah-young', 'Chae-young', 'Da-hyun', 'Ga-eun', 'Hee-jin', 'Na-young', 'Seo-jin', 'Su-jin', 'Yoon-ah', 'Eun-ha', 'Ji-eun', 'Kyung-ah', 'So-jin', 'Ye-won', 'Yoona']),
    mL: pool100(['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim', 'Han', 'Shin', 'Seo', 'Kwon', 'Son', 'Hwang', 'Ahn', 'Song', 'Ryu', 'Hong', 'Goo', 'Ko', 'Moon', 'Yang', 'Bae', 'Baek', 'Heo', 'Yoo', 'Nam', 'Sim', 'No', 'Ha', 'Kwak', 'Sung', 'Cha', 'Woo', 'Joo', 'Woo', 'Na', 'Jin', 'Ji', 'Eom', 'Chae', 'Won', 'Chun', 'Bang', 'Gong', 'Hyun', 'Ham', 'Byun']),
    fL: pool100(['Kim', 'Lee', 'Park', 'Choi', 'Jung', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim', 'Han', 'Shin', 'Seo', 'Kwon', 'Son', 'Hwang', 'Ahn', 'Song', 'Ryu', 'Hong', 'Goo', 'Ko', 'Moon', 'Yang', 'Bae', 'Baek', 'Heo', 'Yoo', 'Nam', 'Sim', 'No', 'Ha', 'Kwak', 'Sung', 'Cha', 'Woo', 'Joo', 'Woo', 'Na', 'Jin', 'Ji', 'Eom', 'Chae', 'Won', 'Chun', 'Bang', 'Gong', 'Hyun', 'Ham', 'Byun'])
  },
  'korea utara': {
    mF: pool100(['Kim-Il', 'Kwang-sun', 'Chol-soo', 'Myong-ho', 'Yong-nam', 'Ri-yong', 'Sung-gol', 'Jong-un', 'Jong-il', 'Jong-nam', 'Kwang-hyok', 'Pak-sung', 'Hyok-chol', 'Sung-nam', 'Yong-ho', 'Chol-jin', 'Myong-chol', 'Kwang-chol', 'Yong-chol', 'Sung-chol', 'Kwang-ho', 'Sung-ho', 'Myong-jin', 'Jong-chol', 'Chol-ho', 'Pak-chol', 'Sung-il', 'Yong-il', 'Kwang-il', 'Myong-il', 'Jong-il', 'Chol-min', 'Sung-min', 'Yong-min', 'Kwang-min', 'Myong-min', 'Jong-min', 'Pak-min', 'Hyok-min', 'Chol-ryong', 'Sung-ryong', 'Yong-ryong', 'Kwang-ryong', 'Myong-ryong', 'Jong-ryong', 'Pak-ryong', 'Hyok-ryong', 'Chol-won', 'Sung-won', 'Yong-won']),
    fF: pool100(['Sun-hee', 'Un-hyang', 'Myong-suk', 'Kwang-ok', 'Yong-hi', 'Chol-ok', 'Sung-hee', 'Jong-suk', 'Hyang-mi', 'Ryo-sim', 'Ok-byol', 'Un-byol', 'Myong-hi', 'Kwang-hi', 'Sung-hi', 'Jong-hi', 'Pak-hi', 'Hyok-hi', 'Chol-hi', 'Un-hi', 'Myong-a', 'Kwang-a', 'Sung-a', 'Jong-a', 'Pak-a', 'Hyok-a', 'Chol-a', 'Un-a', 'Myong-wa', 'Kwang-wa', 'Sung-wa', 'Jong-wa', 'Pak-wa', 'Hyok-wa', 'Chol-wa', 'Un-wa', 'Myong-ran', 'Kwang-ran', 'Sung-ran', 'Jong-ran', 'Pak-ran', 'Hyok-ran', 'Chol-ran', 'Un-ran', 'Myong-suk', 'Kwang-suk', 'Sung-suk', 'Jong-suk', 'Pak-suk', 'Hyok-suk']),
    mL: pool100(['Kim', 'Ri', 'Pak', 'Han', 'Jang', 'Choe', 'Yun', 'An', 'Jon', 'Sin', 'Kang', 'Kye', 'So', 'Kwon', 'Hwang', 'Hong', 'Ryu', 'Ro', 'Pang', 'Ko', 'Cha', 'Song', 'Kong', 'Sim', 'Pyo', 'Myong', 'Tak', 'Mun', 'Im', 'Pae', 'Om', 'Chae', 'Hyon', 'Yu', 'No', 'Ha', 'Kwak', 'Soh', 'Joo', 'Chun', 'Bang', 'Gong', 'Ham', 'Byun', 'Kil', 'Ji', 'Ma', 'Eom', 'Puk', 'San']),
    fL: pool100(['Kim', 'Ri', 'Pak', 'Han', 'Jang', 'Choe', 'Yun', 'An', 'Jon', 'Sin', 'Kang', 'Kye', 'So', 'Kwon', 'Hwang', 'Hong', 'Ryu', 'Ro', 'Pang', 'Ko', 'Cha', 'Song', 'Kong', 'Sim', 'Pyo', 'Myong', 'Tak', 'Mun', 'Im', 'Pae', 'Om', 'Chae', 'Hyon', 'Yu', 'No', 'Ha', 'Kwak', 'Soh', 'Joo', 'Chun', 'Bang', 'Gong', 'Ham', 'Byun', 'Kil', 'Ji', 'Ma', 'Eom', 'Puk', 'San'])
  },
  'kuwait': {
    mF: pool100(['Abdullah', 'Abdulaziz', 'Fahad', 'Faisal', 'Mohammed', 'Youssef', 'Ahmad', 'Ali', 'Bader', 'Hamad', 'Jaber', 'Khalid', 'Mubarak', 'Nasser', 'Nawaf', 'Omar', 'Saad', 'Salem', 'Saud', 'Sultan', 'Adel', 'Bander', 'Dhari', 'Ebrahim', 'Ghanim', 'Hassan', 'Hussain', 'Ibrahim', 'Jasem', 'Khalifah', 'Majed', 'Mansour', 'Meshal', 'Meshal', 'Mohannad', 'Nabil', 'Nayef', 'Rakan', 'Rashid', 'Sami', 'Tariq', 'Turki', 'Waleed', 'Yahya', 'Yasser', 'Zaid', 'Ziyad', 'Abdulrahman', 'Abdelkarim', 'Abdulla']),
    fF: pool100(['Fatima', 'Mariam', 'Noura', 'Sara', 'Reem', 'Aisha', 'Danah', 'Fatimah', 'Hessa', 'Lulwa', 'Mona', 'Munira', 'Nada', 'Noor', 'Shaikha', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Basma', 'Dalia', 'Deema', 'Ghada', 'Hadeel', 'Hala', 'Hanan', 'Haya', 'Jawaher', 'Joud', 'Lama', 'Lujain', 'Maha', 'Malak', 'Manal', 'May', 'Najla', 'Nouf', 'Rana', 'Rania', 'Ruba', 'Sahar', 'Salma', 'Shahad', 'Shatha', 'Wafa', 'Yara', 'Zainab']),
    mL: pool100(['Al-Sabah', 'Al-Ghanim', 'Al-Mutawa', 'Al-Kharafi', 'Al-Anzi', 'Al-Mutairi', 'Al-Ajmi', 'Al-Roudhan', 'Al-Shammari', 'Al-Hashem', 'Al-Hajri', 'Al-Otaibi', 'Al-Dihani', 'Al-Kandari', 'Al-Fadhl', 'Al-Rashidi', 'Al-Awadhi', 'Al-Saad', 'Al-Mulla', 'Al-Bahar', 'Al-Marzouq', 'Al-Khatib', 'Al-Salem', 'Al-Shaheen', 'Al-Sayer', 'Al-Sabah', 'Al-Muzaini', 'Al-Subaie', 'Al-Torki', 'Al-Zayd', 'Al-Ahmad', 'Al-Amiri', 'Al-Bader', 'Al-Dosari', 'Al-Furaih', 'Al-Hammadi', 'Al-Jarallah', 'Al-Majed', 'Al-Nafisi', 'Al-Othman', 'Al-Qattan', 'Al-Rashed', 'Al-Saleh', 'Al-Sulaiman', 'Al-Tuwaijri', 'Al-Wasel', 'Al-Yousef', 'Al-Zayani', 'Ba-Mahmood', 'Bin-Zagr']),
    fL: pool100(['Al-Sabah', 'Al-Ghanim', 'Al-Mutawa', 'Al-Kharafi', 'Al-Anzi', 'Al-Mutairi', 'Al-Ajmi', 'Al-Roudhan', 'Al-Shammari', 'Al-Hashem', 'Al-Hajri', 'Al-Otaibi', 'Al-Dihani', 'Al-Kandari', 'Al-Fadhl', 'Al-Rashidi', 'Al-Awadhi', 'Al-Saad', 'Al-Mulla', 'Al-Bahar', 'Al-Marzouq', 'Al-Khatib', 'Al-Salem', 'Al-Shaheen', 'Al-Sayer', 'Al-Sabah', 'Al-Muzaini', 'Al-Subaie', 'Al-Torki', 'Al-Zayd', 'Al-Ahmad', 'Al-Amiri', 'Al-Bader', 'Al-Dosari', 'Al-Furaih', 'Al-Hammadi', 'Al-Jarallah', 'Al-Majed', 'Al-Nafisi', 'Al-Othman', 'Al-Qattan', 'Al-Rashed', 'Al-Saleh', 'Al-Sulaiman', 'Al-Tuwaijri', 'Al-Wasel', 'Al-Yousef', 'Al-Zayani', 'Ba-Mahmood', 'Bin-Zagr'])
  },
  'laos': {
    mF: pool100(['Kham', 'Som', 'Boun', 'Phou', 'Keo', 'Nou', 'Kone', 'Thong', 'Phone', 'Phout', 'Seng', 'Vong', 'Vilay', 'Phay', 'Sith', 'Chanth', 'Phim', 'Man', 'Inth', 'Outh', 'Khamsing', 'Somboun', 'Phoukhong', 'Keomany', 'Nourack', 'Thonglith', 'Phouthone', 'Sengchanh', 'Vongphachanh', 'Vilayvanh', 'Phayvanh', 'Sithon', 'Chanthavong', 'Phimmasone', 'Manisone', 'Inthavong', 'Outhavong', 'Khamtay', 'Somsavat', 'Bounnhang', 'Phankham', 'Thongloun', 'Phousi', 'Keosaychana', 'Phouthong', 'Sengduean', 'Vongdeuan', 'Vilayout', 'Siphanta', 'Chanthone']),
    fF: pool100(['Champa', 'Maly', 'Dok', 'Keo', 'Kham', 'Mani', 'Phim', 'Noy', 'Som', 'Boua', 'Dao', 'Lat', 'Mai', 'Nee', 'Phet', 'Phai', 'Seng', 'Thip', 'Vieng', 'Vone', 'Champathong', 'Malivan', 'Dokkeo', 'Keomany', 'Khamsy', 'Manichanh', 'Phimpha', 'Noymany', 'Sombath', 'Bouaphanh', 'Daovone', 'Latsamy', 'Maimany', 'Neethong', 'Phetmany', 'Phaivanh', 'Sengmaly', 'Thiphaphone', 'Viengxay', 'Vonemany', 'Chanthaly', 'Khamla', 'Malyvanh', 'Phimchanh', 'Souvanh', 'Thipphavanh', 'Vongdeuane', 'Vongsavanh', 'Soukkhy', 'Manivone']),
    mL: pool100(['Vongphakdy', 'Chanthavong', 'Phommachanh', 'Inthavong', 'Soukhaseum', 'Keomany', 'Phimmasone', 'Vongsavanth', 'Sengchanh', 'Outhavong', 'Ratsamy', 'Sayasane', 'Sisoulith', 'Thammavong', 'Vorachith', 'Xayasone', 'Khamvongsa', 'Phanthavong', 'Sounthone', 'Vongsamphanh', 'Vongxay', 'Phomsouvanh', 'Keosavang', 'Phoutthavong', 'Siphandone', 'Souphanouvong', 'Thongdeuane', 'Vongkot', 'Phimvongsa', 'Soukhavong', 'Chanthalangsy', 'Keobounphanh', 'Phomvihane', 'Sayavong', 'Vongsay', 'Inthasorn', 'Phaxayaseng', 'Souvanhness', 'Thipphavong', 'Vongdara', 'Khammanivong', 'Phrasavath', 'Sengmani', 'Vongkhamchanh', 'Chanthala', 'Keopraseuth', 'Phanthanouvong', 'Souvannakhily', 'Thammavongsa', 'Vongsouthi']),
    fL: pool100(['Vongphakdy', 'Chanthavong', 'Phommachanh', 'Inthavong', 'Soukhaseum', 'Keomany', 'Phimmasone', 'Vongsavanth', 'Sengchanh', 'Outhavong', 'Ratsamy', 'Sayasane', 'Sisoulith', 'Thammavong', 'Vorachith', 'Xayasone', 'Khamvongsa', 'Phanthavong', 'Sounthone', 'Vongsamphanh', 'Vongxay', 'Phomsouvanh', 'Keosavang', 'Phoutthavong', 'Siphandone', 'Souphanouvong', 'Thongdeuane', 'Vongkot', 'Phimvongsa', 'Soukhavong', 'Chanthalangsy', 'Keobounphanh', 'Phomvihane', 'Sayavong', 'Vongsay', 'Inthasorn', 'Phaxayaseng', 'Souvanhness', 'Thipphavong', 'Vongdara', 'Khammanivong', 'Phrasavath', 'Sengmani', 'Vongkhamchanh', 'Chanthala', 'Keopraseuth', 'Phanthanouvong', 'Souvannakhily', 'Thammavongsa', 'Vongsouthi'])
  },
  'lebanon': {
    mF: pool100(['Charbel', 'Elie', 'Fadi', 'Jad', 'Karim', 'Michel', 'Nadim', 'Omar', 'Pierre', 'Rami', 'Sami', 'Tarek', 'Wael', 'Ziad', 'Antoine', 'Bassam', 'Georges', 'Hadi', 'Ibrahim', 'Jean', 'Khalil', 'Maroun', 'Nabil', 'Rabih', 'Tony', 'Walid', 'Youssef', 'Zouhair', 'Abdo', 'Adel', 'Alain', 'Amine', 'Bernard', 'Dany', 'Edouard', 'Fouad', 'Gaby', 'Hassan', 'Issam', 'Joseph', 'Kamel', 'Lucien', 'Mazen', 'Naji', 'Osama', 'Paul', 'Rizk', 'Salim', 'Toufic', 'Wajih']),
    fF: pool100(['Nour', 'Rania', 'Yara', 'Maya', 'Léa', 'Rhea', 'Tala', 'Cynthia', 'Elissa', 'Hiba', 'Joelle', 'Lara', 'Mirna', 'Nadine', 'Rita', 'Sarah', 'Zeina', 'Aline', 'Carole', 'Dalia', 'Ghania', 'Hala', 'Inas', 'Joumana', 'Katia', 'Lina', 'Mona', 'Nayla', 'Olga', 'Paula', 'Rima', 'Sandra', 'Tania', 'Vanessa', 'Wafa', 'Yasmina', 'Zahra', 'Amy', 'Brigitte', 'Chantal', 'Diane', 'Evelyne', 'Farah', 'Giselle', 'Hélène', 'Isabelle', 'Jessica', 'Karen', 'Lyne', 'Magalie']),
    mL: pool100(['Khoury', 'Haddad', 'Nassar', 'El-Khoury', 'Chahine', 'Saliba', 'Ghanem', 'Saad', 'Khalil', 'Hariri', 'Aoun', 'Gemayel', 'Geagea', 'Joumblatt', 'Berri', 'Mikati', 'Frangieh', 'Sleiman', 'Siniora', 'Salam', 'Bassil', 'Tueni', 'Helou', 'Chamoun', 'Pharaon', 'Abou-Jaoude', 'Bitar', 'Chaaban', 'Daher', 'El-Hage', 'Fakhoury', 'Ghosn', 'Habib', 'Itani', 'Jaber', 'Karam', 'Lteif', 'Matar', 'Najjar', 'Osseiran', 'Rizk', 'Sarkis', 'Tawk', 'Wakim', 'Yammine', 'Zeytoun', 'Abdel-Nour', 'Boustany', 'Corm', 'Dahdah']),
    fL: pool100(['Khoury', 'Haddad', 'Nassar', 'El-Khoury', 'Chahine', 'Saliba', 'Ghanem', 'Saad', 'Khalil', 'Hariri', 'Aoun', 'Gemayel', 'Geagea', 'Joumblatt', 'Berri', 'Mikati', 'Frangieh', 'Sleiman', 'Siniora', 'Salam', 'Bassil', 'Tueni', 'Helou', 'Chamoun', 'Pharaon', 'Abou-Jaoude', 'Bitar', 'Chaaban', 'Daher', 'El-Hage', 'Fakhoury', 'Ghosn', 'Habib', 'Itani', 'Jaber', 'Karam', 'Lteif', 'Matar', 'Najjar', 'Osseiran', 'Rizk', 'Sarkis', 'Tawk', 'Wakim', 'Yammine', 'Zeytoun', 'Abdel-Nour', 'Boustany', 'Corm', 'Dahdah'])
  },
  'makau': {
    mF: pool100(['Alex', 'Alan', 'Alfred', 'Andrew', 'Andy', 'Bernard', 'Calvin', 'Chun-Hang', 'Daniel', 'Dickson', 'Dominic', 'Eason', 'Edison', 'Eric', 'Felix', 'Francis', 'Gary', 'Gordon', 'Ho-Yin', 'Ivan', 'Jacky', 'Jackson', 'Jason', 'Jeffrey', 'Jonathan', 'Kenneth', 'Kevin', 'Kin-Ming', 'Kwok-Keung', 'Lau-Ching', 'Lok-Tin', 'Michael', 'Nicholas', 'Patrick', 'Raymond', 'Ronald', 'Sam', 'Simon', 'Stephen', 'Steven', 'Tsz-Kin', 'Tsz-Lok', 'Wai-Man', 'Wing-Kit', 'Antonio', 'Carlos', 'Fernando', 'Henrique', 'Joao', 'Jose', 'Luiz', 'Manuel', 'Miguel', 'Paulo', 'Pedro', 'Rui']),
    fF: pool100(['Ada', 'Alice', 'Amanda', 'Angel', 'Angela', 'Charmaine', 'Ching-Yee', 'Gigi', 'Grace', 'Hoi-Ching', 'Hoi-Yan', 'Ivy', 'Jacqueline', 'Janice', 'Jessica', 'Joey', 'Joyce', 'Karen', 'Kelly', 'Kiki', 'Kristy', 'Maggie', 'Man-Yee', 'May', 'Michelle', 'Nancy', 'Nicole', 'Rainbow', 'Sammie', 'Sharon', 'Shirley', 'Tsz-Ching', 'Tsz-Yau', 'Vicky', 'Wai-Ying', 'Wing-Shan', 'Yuki', 'Ana', 'Beatriz', 'Carla', 'Diana', 'Ines', 'Joana', 'Luisa', 'Maria', 'Rita', 'Sofia', 'Teresa']),
    mL: pool100(['Chan', 'Cheng', 'Cheung', 'Chow', 'Ho', 'Hui', 'Ip', 'Kwok', 'Lai', 'Lam', 'Lau', 'Lee', 'Leung', 'Li', 'Lo', 'Luk', 'Ng', 'Poon', 'Tam', 'Tang', 'Tse', 'Wong', 'Wu', 'Yeung', 'Yip', 'Alves', 'Coelho', 'Costa', 'Dias', 'Fernandes', 'Ferreira', 'Gomes', 'Lopes', 'Marques', 'Martins', 'Neves', 'Oliveira', 'Pereira', 'Rodrigues', 'Santos', 'Silva', 'Sousa', 'Teixeira', 'Vasconcelos', 'Vaz', 'Vieira', 'Au', 'Cha', 'Fan', 'Fung', 'Kwan']),
    fL: pool100(['Chan', 'Cheng', 'Cheung', 'Chow', 'Ho', 'Hui', 'Ip', 'Kwok', 'Lai', 'Lam', 'Lau', 'Lee', 'Leung', 'Li', 'Lo', 'Luk', 'Ng', 'Poon', 'Tam', 'Tang', 'Tse', 'Wong', 'Wu', 'Yeung', 'Yip', 'Alves', 'Coelho', 'Costa', 'Dias', 'Fernandes', 'Ferreira', 'Gomes', 'Lopes', 'Marques', 'Martins', 'Neves', 'Oliveira', 'Pereira', 'Rodrigues', 'Santos', 'Silva', 'Sousa', 'Teixeira', 'Vasconcelos', 'Vaz', 'Vieira', 'Au', 'Cha', 'Fan', 'Fung', 'Kwan'])
  },
  'malaysia': {
    mF: pool100(['Adam', 'Ahmad', 'Aiman', 'Amir', 'Amirul', 'Ariff', 'Azhar', 'Azman', 'Danial', 'Faris', 'Hafiz', 'Hakim', 'Harith', 'Hazim', 'Ibrahim', 'Irfan', 'Izwan', 'Khairul', 'Luqman', 'Muhammad', 'Nabil', 'Nazmi', 'Rafiq', 'Razak', 'Rizal', 'Saiful', 'Shah', 'Shahrul', 'Syakir', 'Zulhilmi', 'Chong', 'Goh', 'Khoo', 'Lee', 'Lim', 'Liew', 'Ng', 'Tan', 'Teoh', 'Wong', 'Anand', 'Devan', 'Ganesh', 'Karthik', 'Kumar', 'Pravin', 'Ramesh', 'Sanjay', 'Venkatesh', 'Vijay']),
    fF: pool100(['Aina', 'Aisyah', 'Aliah', 'Amira', 'Anis', 'Aqilah', 'Athirah', 'Atiqah', 'Farah', 'Fatin', 'Izzati', 'Maysarah', 'Nadia', 'Nabilah', 'Nadiah', 'Najwa', 'Nur', 'Nurul', 'Rania', 'Siti', 'Syafiqah', 'Syahira', 'Syazwana', 'Wardah', 'Zulaikha', 'Cheah', 'Chin', 'Fong', 'Ho', 'Khor', 'Lau', 'Leong', 'Loh', 'Ooi', 'Teh', 'Yap', 'Yeoh', 'Anusha', 'Deepa', 'Divya', 'Kavitha', 'Lakshmi', 'Meena', 'Nisha', 'Priya', 'Shanti', 'Thila', 'Uma', 'Vimala']),
    mL: pool100(['Abdullah', 'Ahmad', 'Ali', 'Ariffin', 'Aziz', 'Bakar', 'Hassan', 'Hamid', 'Harun', 'Hashim', 'Ibrahim', 'Ismail', 'Jamil', 'Kamal', 'Karim', 'Kassim', 'Latif', 'Mahmud', 'Majid', 'Muhammad', 'Mustapa', 'Naim', 'Nasir', 'Omar', 'Osman', 'Othman', 'Rahman', 'Ramli', 'Rashid', 'Sabli', 'Saiful', 'Salleh', 'Suhaili', 'Sulaiman', 'Tahir', 'Wahab', 'Yaakub', 'Yusof', 'Zain', 'Zakaria', 'Tan', 'Lee', 'Wong', 'Lim', 'Ng', 'Chin', 'Goh', 'Chong', 'Liew', 'Yap']),
    fL: pool100(['Abdullah', 'Ahmad', 'Ali', 'Ariffin', 'Aziz', 'Bakar', 'Hassan', 'Hamid', 'Harun', 'Hashim', 'Ibrahim', 'Ismail', 'Jamil', 'Kamal', 'Karim', 'Kassim', 'Latif', 'Mahmud', 'Majid', 'Muhammad', 'Mustapa', 'Naim', 'Nasir', 'Omar', 'Osman', 'Othman', 'Rahman', 'Ramli', 'Rashid', 'Sabli', 'Saiful', 'Salleh', 'Suhaili', 'Sulaiman', 'Tahir', 'Wahab', 'Yaakub', 'Yusof', 'Zain', 'Zakaria', 'Tan', 'Lee', 'Wong', 'Lim', 'Ng', 'Chin', 'Goh', 'Chong', 'Liew', 'Yap'])
  },
  'maldives': {
    mF: pool100(['Ali', 'Ahmed', 'Hassan', 'Hussain', 'Ibrahim', 'Mohamed', 'Abdulla', 'Adam', 'Ismail', 'Moosa', 'Umar', 'Usman', 'Yoosuf', 'Azim', 'Faris', 'Fayaz', 'Hameed', 'Imran', 'Jamsheed', 'Labeeb', 'Maumoon', 'Niyaz', 'Qasim', 'Rashad', 'Sameer', 'Shaheem', 'Shareef', 'Shiyam', 'Solih', 'Thoriq', 'Waheed', 'Yameen', 'Zahir', 'Zaki', 'Ziyad', 'Amir', 'Aslam', 'Faisal', 'Haider', 'Hamdan', 'Hilmy', 'Ilyas', 'Jameel', 'Latheef', 'Munavvar', 'Najeeb', 'Rasheed', 'Saeed', 'Shafeeq', 'Shahid']),
    fF: pool100(['Aishath', 'Aminath', 'Fatimat', 'Mariyam', 'Hawwa', 'Fathimath', 'Khadheeja', 'Zahira', 'Zuleikha', 'Ameena', 'Asiyath', 'Dheena', 'Dunya', 'Fazeela', 'Haleemath', 'Hisaan', 'Ilham', 'Jeeshan', 'Khadeeja', 'Leela', 'Moomina', 'Naashida', 'Niuma', 'Qureisha', 'Raodha', 'Rozaina', 'Saeeda', 'Shaheeda', 'Shifa', 'Thilmeeza', 'Vazira', 'Yumna', 'Zaheena', 'Zulaikha', 'Aafa', 'Ananiya', 'Dheema', 'Farah', 'Ganiya', 'Hasna', 'Inasha', 'Jazly', 'Lana', 'Mizna', 'Nadha', 'Rifa', 'Sabeeha', 'Shiuna', 'Zara', 'Zeeniya']),
    mL: pool100(['Rasheed', 'Saeed', 'Shareef', 'Waheed', 'Zahir', 'Latheef', 'Jameel', 'Hilmy', 'Fayaz', 'Niyaz', 'Shafeeq', 'Shahid', 'Shiyam', 'Solih', 'Thoriq', 'Yameen', 'Zaki', 'Ziyad', 'Amir', 'Aslam', 'Faisal', 'Haider', 'Hamdan', 'Ilyas', 'Munavvar', 'Najeeb', 'Didi', 'Maniku', 'Fulhu', 'Kilege', 'Trofim', 'Adnan', 'Afif', 'Arshad', 'Asif', 'Azeez', 'Farih', 'Ghayyoom', 'Habib', 'Haneef', 'Hassan-MV', 'Husny', 'Ibrahim-MV', 'Jalal', 'Mubeen', 'Musthafa', 'Naseer', 'Riza', 'Shakir', 'Shukury']),
    fL: pool100(['Rasheed', 'Saeed', 'Shareef', 'Waheed', 'Zahir', 'Latheef', 'Jameel', 'Hilmy', 'Fayaz', 'Niyaz', 'Shafeeq', 'Shahid', 'Shiyam', 'Solih', 'Thoriq', 'Yameen', 'Zaki', 'Ziyad', 'Amir', 'Aslam', 'Faisal', 'Haider', 'Hamdan', 'Ilyas', 'Munavvar', 'Najeeb', 'Didi', 'Maniku', 'Fulhu', 'Kilege', 'Trofim', 'Adnan', 'Afif', 'Arshad', 'Asif', 'Azeez', 'Farih', 'Ghayyoom', 'Habib', 'Haneef', 'Hassan-MV', 'Husny', 'Ibrahim-MV', 'Jalal', 'Mubeen', 'Musthafa', 'Naseer', 'Riza', 'Shakir', 'Shukury'])
  },
  'mongolia': {
    mF: pool100(['Bat-Erdene', 'Otgonbayar', 'Ganzorig', 'Enkhbold', 'Bold', 'Bayar', 'Tseren', 'Tumur', 'Altangerel', 'Batzorig', 'Erdene', 'Khurelbaatar', 'Munkh-Erdene', 'Nyamdorj', 'Sukhbaatar', 'Tsogtbaatar', 'Zorigt', 'Amarsaikhan', 'Badarch', 'Batbayar', 'Batzaya', 'Chimediin', 'Davaa', 'Enkhtuvshin', 'Ganbaatar', 'Jargalsaikhan', 'Lkhagvasuren', 'Myagmarsuren', 'Natsagdorj', 'Ochirbat', 'Purevsuren', 'Sainbayar', 'Tserenbat', 'Urtnasan', 'Yundendorj', 'Amarbayasgalan', 'Bayanmunkh', 'Boldbaatar', 'Chuluunbaatar', 'Enkhbaatar', 'Ganbold', 'Jambyn', 'Khaltmaa', 'Luvsannamsrai', 'Munkhbat', 'Naranbaatar', 'Oyuun-Erdene', 'Sukhbold', 'Tserendash', 'Zorig']),
    fF: pool100(['Enkhtuya', 'Otgonjargal', 'Altanchimeg', 'Bayarmaa', 'Bolormaa', 'Erdenechimeg', 'Ganchimeg', 'Khulan', 'Munkhtsetseg', 'Narantsetseg', 'Oyuntsetseg', 'Sarangerel', 'Tsetsegmaa', 'Tungalag', 'Uranchimeg', 'Amarjargal', 'Batuya', 'Chuluuntsetseg', 'Dulamsuren', 'Enkhjargal', 'Ganzul', 'Jargalmaa', 'Khaliun', 'Lkhagvajargal', 'Myagmarjav', 'Narangoo', 'Oyun-Erdene', 'Purevjav', 'Solongo', 'Tserendulam', 'Uyangaa', 'Yanjindulam', 'Altantuya', 'Bayartsetseg', 'Boldmaa', 'Chingun', 'Enkhmaa', 'Gantuya', 'Javkhlan', 'Kherlen', 'Lkhagvadulam', 'Munkhjargal', 'Naranchimeg', 'Oyuun', 'Saran', 'Tsevelmaa', 'Tuul', 'Uuriintuya', 'Zaya', 'Zolzaya']),
    mL: pool100(['Bat-Erdene', 'Otgonbayar', 'Ganzorig', 'Enkhbold', 'Bold', 'Bayar', 'Tseren', 'Tumur', 'Altangerel', 'Batzorig', 'Erdene', 'Khurelbaatar', 'Munkh-Erdene', 'Nyamdorj', 'Sukhbaatar', 'Tsogtbaatar', 'Zorigt', 'Amarsaikhan', 'Badarch', 'Batbayar', 'Batzaya', 'Chimediin', 'Davaa', 'Enkhtuvshin', 'Ganbaatar', 'Jargalsaikhan', 'Lkhagvasuren', 'Myagmarsuren', 'Natsagdorj', 'Ochirbat', 'Purevsuren', 'Sainbayar', 'Tserenbat', 'Urtnasan', 'Yundendorj', 'Amarbayasgalan', 'Bayanmunkh', 'Boldbaatar', 'Chuluunbaatar', 'Enkhbaatar', 'Ganbold', 'Jambyn', 'Khaltmaa', 'Luvsannamsrai', 'Munkhbat', 'Naranbaatar', 'Oyuun-Erdene', 'Sukhbold', 'Tserendash', 'Zorig']),
    fL: pool100(['Bat-Erdene', 'Otgonbayar', 'Ganzorig', 'Enkhbold', 'Bold', 'Bayar', 'Tseren', 'Tumur', 'Altangerel', 'Batzorig', 'Erdene', 'Khurelbaatar', 'Munkh-Erdene', 'Nyamdorj', 'Sukhbaatar', 'Tsogtbaatar', 'Zorigt', 'Amarsaikhan', 'Badarch', 'Batbayar', 'Batzaya', 'Chimediin', 'Davaa', 'Enkhtuvshin', 'Ganbaatar', 'Jargalsaikhan', 'Lkhagvasuren', 'Myagmarsuren', 'Natsagdorj', 'Ochirbat', 'Purevsuren', 'Sainbayar', 'Tserenbat', 'Urtnasan', 'Yundendorj', 'Amarbayasgalan', 'Bayanmunkh', 'Boldbaatar', 'Chuluunbaatar', 'Enkhbaatar', 'Ganbold', 'Jambyn', 'Khaltmaa', 'Luvsannamsrai', 'Munkhbat', 'Naranbaatar', 'Oyuun-Erdene', 'Sukhbold', 'Tserendash', 'Zorig'])
  },
  'myanmar': {
    mF: pool100(['Aung', 'Kyaw', 'Min', 'Myo', 'Nyan', 'Soe', 'Than', 'Thura', 'Wai', 'Win', 'Zaw', 'Zin', 'Htet', 'Phyo', 'Naing', 'Lin', 'Tun', 'San', 'Zar', 'Khin', 'Kaung', 'Ko', 'Myint', 'Thant', 'Zeya', 'Bo', 'Hlaing', 'Htun', 'Kyu', 'Lwin', 'Mahn', 'Mya', 'Nang', 'Nilar', 'Pe', 'Sein', 'Shwe', 'Sithu', 'Thein', 'Thu', 'Tin', 'U', 'Wunna', 'Yan', 'Ye', 'Yin', 'Yu', 'Aung-San', 'Than-Shwe', 'U-Thant']),
    fF: pool100(['Aye', 'Chaw', 'Hnin', 'Hsu', 'Khin', 'May', 'Mya', 'Nilar', 'Phyu', 'Po', 'San', 'Su', 'Thida', 'Wint', 'Yadana', 'Yee', 'Yin', 'Zar', 'Zin', 'Eaindra', 'Htet', 'Hla', 'Kyu', 'Lwin', 'Moey', 'Myint', 'Nang', 'Nway', 'Nwe', 'Paw', 'Phyu-Phyu', 'Phyo', 'Pyone', 'Shwe', 'Soe', 'Swe', 'Thae', 'Than', 'Thandar', 'Thet', 'Thiri', 'Thin', 'Thu', 'Tin', 'Wai', 'Win', 'Yamin', 'Yatanar', 'Yu', 'Zar-Chi']),
    mL: pool100(['Aung', 'Kyaw', 'Min', 'Myo', 'Nyan', 'Soe', 'Than', 'Thura', 'Wai', 'Win', 'Zaw', 'Zin', 'Htet', 'Phyo', 'Naing', 'Lin', 'Tun', 'San', 'Zar', 'Khin', 'Kaung', 'Ko', 'Myint', 'Thant', 'Zeya', 'Bo', 'Hlaing', 'Htun', 'Kyu', 'Lwin', 'Mahn', 'Mya', 'Nang', 'Nilar', 'Pe', 'Sein', 'Shwe', 'Sithu', 'Thein', 'Thu', 'Tin', 'U', 'Wunna', 'Yan', 'Ye', 'Yin', 'Yu', 'Aung-San', 'Than-Shwe', 'U-Thant']),
    fL: pool100(['Aung', 'Kyaw', 'Min', 'Myo', 'Nyan', 'Soe', 'Than', 'Thura', 'Wai', 'Win', 'Zaw', 'Zin', 'Htet', 'Phyo', 'Naing', 'Lin', 'Tun', 'San', 'Zar', 'Khin', 'Kaung', 'Ko', 'Myint', 'Thant', 'Zeya', 'Bo', 'Hlaing', 'Htun', 'Kyu', 'Lwin', 'Mahn', 'Mya', 'Nang', 'Nilar', 'Pe', 'Sein', 'Shwe', 'Sithu', 'Thein', 'Thu', 'Tin', 'U', 'Wunna', 'Yan', 'Ye', 'Yin', 'Yu', 'Aung-San', 'Than-Shwe', 'U-Thant'])
  },
  'nepal': {
    mF: pool100(['Aarav', 'Abhishek', 'Aditya', 'Ajay', 'Aman', 'Amit', 'Anil', 'Anup', 'Arjun', 'Ashok', 'Bikram', 'Bimal', 'Bipul', 'Bishal', 'Deepak', 'Dinesh', 'Dipendra', 'Ganesh', 'Gaurav', 'Gopal', 'Hari', 'Hemant', 'Kiran', 'Kishan', 'Krishna', 'Lalit', 'Madhav', 'Mahesh', 'Manish', 'Manoj', 'Mohan', 'Mukesh', 'Nabin', 'Nirajan', 'Niraj', 'Pradeep', 'Prakash', 'Prashant', 'Rabin', 'Ramesh', 'Roshan', 'Sachin', 'Sameer', 'Sandeep', 'Sanjib', 'Santosh', 'Sharad', 'Shiva', 'Siddhartha', 'Subash']),
    fF: pool100(['Aarati', 'Aashika', 'Aditi', 'Alisha', 'Amrita', 'Anjali', 'Ankita', 'Anushka', 'Archana', 'Asmita', 'Bhawana', 'Bipana', 'Deepa', 'Deepika', 'Devaki', 'Divya', 'Gita', 'Isha', 'Janaki', 'Kalpana', 'Kavita', 'Kripa', 'Kusum', 'Laxmi', 'Manju', 'Manisha', 'Meena', 'Melina', 'Nisha', 'Pooja', 'Prashna', 'Pratima', 'Priya', 'Priyanka', 'Pramila', 'Rachana', 'Radha', 'Roshani', 'Sabina', 'Sadhana', 'Saraswati', 'Sharmila', 'Shreya', 'Sneha', 'Sujata', 'Sunita', 'Sushma', 'Usha', 'Yashoda', 'Zenisha']),
    mL: pool100(['Shrestha', 'Adhikari', 'Thapa', 'Karki', 'Gurung', 'Tamang', 'Rai', 'Bhattarai', 'Giri', 'Poudel', 'Basnet', 'Gautam', 'Koirala', 'Maharjan', 'Regmi', 'Sharma', 'Subedi', 'Acharya', 'Bhandari', 'Bista', 'Chaudhary', 'Dahal', 'Devkota', 'Ghimire', 'Khadka', 'Lama', 'Magar', 'Neupane', 'Pandey', 'Pokhrel', 'Pradhan', 'Rana', 'Rijal', 'Sapkota', 'Shah', 'Sherpa', 'Subba', 'Tiwari', 'Upadhyaya', 'Yadav', 'Aryal', 'Baral', 'Bhatta', 'Bhusal', 'Jha', 'Kandel', 'Khanal', 'Mainali', 'Parajuli', 'Tripathi']),
    fL: pool100(['Shrestha', 'Adhikari', 'Thapa', 'Karki', 'Gurung', 'Tamang', 'Rai', 'Bhattarai', 'Giri', 'Poudel', 'Basnet', 'Gautam', 'Koirala', 'Maharjan', 'Regmi', 'Sharma', 'Subedi', 'Acharya', 'Bhandari', 'Bista', 'Chaudhary', 'Dahal', 'Devkota', 'Ghimire', 'Khadka', 'Lama', 'Magar', 'Neupane', 'Pandey', 'Pokhrel', 'Pradhan', 'Rana', 'Rijal', 'Sapkota', 'Shah', 'Sherpa', 'Subba', 'Tiwari', 'Upadhyaya', 'Yadav', 'Aryal', 'Baral', 'Bhatta', 'Bhusal', 'Jha', 'Kandel', 'Khanal', 'Mainali', 'Parajuli', 'Tripathi'])
  },
  'oman': {
    mF: pool100(['Abdullah', 'Abdulaziz', 'Ahmad', 'Ali', 'Fahad', 'Faisal', 'Hamad', 'Hassan', 'Hussain', 'Ibrahim', 'Khalid', 'Majed', 'Mohammed', 'Nasser', 'Nawaf', 'Omar', 'Rashid', 'Saad', 'Said', 'Saud', 'Sultan', 'Tariq', 'Turki', 'Waleed', 'Yahya', 'Yasser', 'Youssef', 'Ziyad', 'Adnan', 'Bader', 'Dhari', 'Ghanim', 'Haitham', 'Hamdan', 'Hesham', 'Jaber', 'Jalal', 'Jamal', 'Jameel', 'Khalifah', 'Mansour', 'Meshal', 'Mubarak', 'Muhanad', 'Munir', 'Murad', 'Musa', 'Mustafa', 'Nabil', 'Naji']),
    fF: pool100(['Fatima', 'Mariam', 'Aisha', 'Mona', 'Sara', 'Reem', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Basma', 'Dalia', 'Danah', 'Deema', 'Fatimah', 'Ghada', 'Hadeel', 'Hala', 'Hanan', 'Haya', 'Hessa', 'Jawaher', 'Joud', 'Lama', 'Lujain', 'Maha', 'Malak', 'Manal', 'May', 'Munira', 'Nada', 'Najla', 'Nouf', 'Noura', 'Rana', 'Rania', 'Ruba', 'Sahar', 'Salma', 'Shahad', 'Shatha', 'Wafa', 'Yara', 'Zainab', 'Jokha', 'Raya', 'Salima']),
    mL: pool100(['Al-Busaidi', 'Al-Mamari', 'Al-Hinai', 'Al-Balushi', 'Al-Rawahi', 'Al-Ghafri', 'Al-Zadjali', 'Al-Harasi', 'Al-Nabhani', 'Al-Kindi', 'Al-Shukaili', 'Al-Abri', 'Al-Habsi', 'Al-Mashani', 'Al-Harthi', 'Al-Siyabi', 'Al-Riyami', 'Al-Lawati', 'Al-Wahaibi', 'Al-Bahrani', 'Al-Ghani', 'Al-Mahrouqi', 'Al-Nomani', 'Al-Outaibi', 'Al-Qasimi', 'Al-Rahbi', 'Al-Saadi', 'Al-Salmi', 'Al-Shamsi', 'Al-Toubi', 'Al-Yahyaei', 'Al-Zaabi', 'Al-Aamri', 'Al-Farsi', 'Al-Gassani', 'Al-Hassani', 'Al-Ismaili', 'Al-Jabri', 'Al-Khalili', 'Al-Maawali', 'Al-Naabi', 'Al-Omari', 'Al-Qatabi', 'Al-Rashdi', 'Al-Sarmi', 'Al-Tami', 'Al-Wahshi', 'Al-Yaarubi', 'Al-Zadjali', 'Al-Zubair']),
    fL: pool100(['Al-Busaidi', 'Al-Mamari', 'Al-Hinai', 'Al-Balushi', 'Al-Rawahi', 'Al-Ghafri', 'Al-Zadjali', 'Al-Harasi', 'Al-Nabhani', 'Al-Kindi', 'Al-Shukaili', 'Al-Abri', 'Al-Habsi', 'Al-Mashani', 'Al-Harthi', 'Al-Siyabi', 'Al-Riyami', 'Al-Lawati', 'Al-Wahaibi', 'Al-Bahrani', 'Al-Ghani', 'Al-Mahrouqi', 'Al-Nomani', 'Al-Outaibi', 'Al-Qasimi', 'Al-Rahbi', 'Al-Saadi', 'Al-Salmi', 'Al-Shamsi', 'Al-Toubi', 'Al-Yahyaei', 'Al-Zaabi', 'Al-Aamri', 'Al-Farsi', 'Al-Gassani', 'Al-Hassani', 'Al-Ismaili', 'Al-Jabri', 'Al-Khalili', 'Al-Maawali', 'Al-Naabi', 'Al-Omari', 'Al-Qatabi', 'Al-Rashdi', 'Al-Sarmi', 'Al-Tami', 'Al-Wahshi', 'Al-Yaarubi', 'Al-Zadjali', 'Al-Zubair'])
  },
  'pakistan': {
    mF: pool100(['Muhammad', 'Ali', 'Ahmed', 'Hassan', 'Hussain', 'Hamza', 'Usman', 'Bilal', 'Omar', 'Zaid', 'Tariq', 'Fahad', 'Faisal', 'Imran', 'Kamran', 'Rizwan', 'Salman', 'Shahid', 'Shoaib', 'Waqas', 'Abid', 'Adnan', 'Asad', 'Asif', 'Babar', 'Danish', 'Farhan', 'Fawad', 'Haris', 'Irfan', 'Junaid', 'Kashif', 'Nabeel', 'Noman', 'Rashid', 'Saad', 'Saim', 'Sajid', 'Sami', 'Shahzaib', 'Sufyan', 'Tahir', 'Umer', 'Waseem', 'Yasir', 'Zain', 'Zeeshan', 'Zia', 'Zohaib', 'Zubair']),
    fF: pool100(['Fatima', 'Ayesha', 'Zainab', 'Maryam', 'Sana', 'Sadia', 'Hira', 'Anum', 'Fariha', 'Farzana', 'Iqra', 'Khadija', 'Laiba', 'Maha', 'Mehwish', 'Nida', 'Noreen', 'Rabia', 'Saba', 'Sidra', 'Tayyaba', 'Urooj', 'Uzma', 'Yumna', 'Zoya', 'Alina', 'Amna', 'Anam', 'Areeba', 'Asma', 'Bisma', 'Bushra', 'Dua', 'Eman', 'Fiza', 'Ghazala', 'Habiba', 'Hania', 'Iman', 'Jaeria', 'Kinza', 'Mahnoor', 'Manahil', 'Natasha', 'Nimra', 'Raimah', 'Samreen', 'Shazia', 'Sumaira', 'Tahira']),
    mL: pool100(['Khan', 'Chaudhry', 'Malik', 'Qureshi', 'Shaikh', 'Syed', 'Bhatti', 'Raja', 'Jutt', 'Gondal', 'Rehman', 'Ahmed', 'Ali', 'Hussain', 'Shah', 'Mirza', 'Baig', 'Abbasi', 'Farooqi', 'Hashmi', 'Siddiqui', 'Zaidi', 'Ansari', 'Dar', 'Gill', 'Gujjar', 'Iqbal', 'Jan', 'Khattak', 'Lodi', 'Mian', 'Niazi', 'Pasha', 'Rana', 'Rizvi', 'Sharif', 'Tareen', 'Wattoo', 'Yousafzai', 'Zia', 'Afridi', 'Alvi', 'Bajwa', 'Cheema', 'Durrani', 'Ghauri', 'Kakakhel', 'Laghari', 'Mengal', 'Tarar']),
    fL: pool100(['Khan', 'Chaudhry', 'Malik', 'Qureshi', 'Shaikh', 'Syed', 'Bhatti', 'Raja', 'Jutt', 'Gondal', 'Rehman', 'Ahmed', 'Ali', 'Hussain', 'Shah', 'Mirza', 'Baig', 'Abbasi', 'Farooqi', 'Hashmi', 'Siddiqui', 'Zaidi', 'Ansari', 'Dar', 'Gill', 'Gujjar', 'Iqbal', 'Jan', 'Khattak', 'Lodi', 'Mian', 'Niazi', 'Pasha', 'Rana', 'Rizvi', 'Sharif', 'Tareen', 'Wattoo', 'Yousafzai', 'Zia', 'Afridi', 'Alvi', 'Bajwa', 'Cheema', 'Durrani', 'Ghauri', 'Kakakhel', 'Laghari', 'Mengal', 'Tarar'])
  }
};

let count = 0;
for (const country of countries18) {
  const cData = db[country];
  if (!cData) continue;
  const baseDir = path.join('json', 'firstname_lastname', 'asia', country);

  fs.mkdirSync(path.join(baseDir, 'male'), { recursive: true });
  fs.mkdirSync(path.join(baseDir, 'female'), { recursive: true });

  fs.writeFileSync(path.join(baseDir, 'male', 'firstname.json'), JSON.stringify(cData.mF, null, 2));
  fs.writeFileSync(path.join(baseDir, 'male', 'lastname.json'), JSON.stringify(cData.mL, null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'firstname.json'), JSON.stringify(cData.fF, null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'lastname.json'), JSON.stringify(cData.fL, null, 2));

  count++;
}

console.log('Successfully generated clean 100 names for ' + count + ' countries!');
