const fs = require('fs');
const path = require('path');

// Master Real Human Name Pools for South America (SA) - 100% Real Human Names, ZERO Synthetic Tag/Country Prefix Strings!

const saAuthenticPools = {
  'chile': {
    mF: ['Benjamin', 'Vicente', 'Martin', 'Matias', 'Joaquin', 'Agustin', 'Maximilian', 'Lucas', 'Santiago', 'Mateo', 'Gaspar', 'Alonso', 'Tomas', 'Felipe', 'Nicolas', 'Diego', 'Sebastian', 'Ignacio', 'Bautista', 'Francisco', 'Gabriel', 'Franco', 'Cristobal', 'Renato', 'Emilio', 'Esteban', 'Ramiro', 'Julian', 'Damian', 'Gonzalo', 'Lautaro', 'Valentino', 'Santino', 'Ezekiel', 'Manuel', 'Mariano', 'Bruno', 'Emiliano', 'Dante', 'Lorenzo', 'Simon', 'Luciano', 'Gaston', 'Leandro', 'Marcos', 'Iván', 'Federico', 'Nahuel', 'Alan', 'Rodrigo', 'Adriel', 'Alex', 'Axel', 'Ciro', 'Enzo', 'Gael', 'Gino', 'Ian', 'Iker', 'Jonas', 'Leon', 'Luka', 'Milo', 'Noah', 'Oliver', 'Tiziano', 'Valentin', 'Vito', 'Alejo', 'Braian', 'Cristian', 'Elias', 'Fernando', 'Guillermo', 'Hector', 'Javier', 'Kevin', 'Lisandro', 'Mauricio', 'Nelson', 'Orlando', 'Pablo', 'Renzo', 'Sergio', 'Tobias', 'Uriel', 'Victor', 'Walter', 'Xavier', 'Yamil', 'Lucio', 'Patricio', 'Raul', 'Ruben', 'Tadeo', 'Wilfredo', 'Yael', 'Zacarias', 'Abel', 'Adolfo', 'Aldo', 'Alfonso'],
    fF: ['Sofia', 'Isabella', 'Emilia', 'Maite', 'Isidora', 'Agustina', 'Antonella', 'Mia', 'Florence', 'Valentina', 'Catalina', 'Trinidad', 'Josefina', 'Emma', 'Martina', 'Lucia', 'Victoria', 'Delfina', 'Elena', 'Juana', 'Renata', 'Alma', 'Olivia', 'Camila', 'Paula', 'Abril', 'Lola', 'Brisa', 'Zoe', 'Malena', 'Guadalupe', 'Candela', 'Agostina', 'Jazmin', 'Lara', 'Micaela', 'Rocio', 'Morena', 'Sol', 'Clara', 'Francisca', 'Milagros', 'Constanza', 'Pilar', 'Bianca', 'Margarita', 'Carolina', 'Julietta', 'Florencia', 'Carla', 'Magali', 'Belen', 'Celeste', 'Luciana', 'Aitana', 'Ambar', 'Chloe', 'Giana', 'Gemma', 'Iara', 'Kiara', 'Luna', 'Melina', 'Naiara', 'Paloma', 'Quirina', 'Romina', 'Sabrina', 'Tiziana', 'Uma', 'Violeta', 'Wendy', 'Ximena', 'Yara', 'Alicia', 'Beatriz', 'Cecilia', 'Daniela', 'Estefania', 'Gabriela', 'Ines', 'Julia', 'Karina', 'Lorena', 'Marina', 'Natalia', 'Patricia', 'Raquel', 'Silvia', 'Teresa', 'Valeria', 'Yolanda', 'Ariadna', 'Brenda', 'Diana', 'Evelyn', 'Giselle', 'Ivanna', 'Jacqueline', 'Lourdes', 'Noelia'],
    mL: ['Gonzalez', 'Munoz', 'Rojas', 'Diaz', 'Perez', 'Soto', 'Contreras', 'Silva', 'Martinez', 'Sepulveda', 'Morales', 'Rodriguez', 'Lopez', 'Fuentes', 'Hernandez', 'Torres', 'Araya', 'Flores', 'Espinoza', 'Valenzuela', 'Castillo', 'Tapia', 'Reyes', 'Gutierrez', 'Castro', 'Pizarro', 'Alvarez', 'Vásquez', 'Carrasco', 'Herrera', 'Cárdenas', 'Aguilera', 'Gomez', 'Vergara', 'Figueroa', 'Jara', 'Nuñez', 'Godoy', 'San Martin', 'Vargas', 'Orellana', 'Bravo', 'Mendoza', 'Pena', 'Cáceres', 'Navarro', 'Salinas', 'Bustos', 'Rios', 'Guzman', 'Miranda', 'Peralta', 'Correa', 'Garrido', 'Paredes', 'Leiva', 'Avila', 'Molina', 'Vega', 'Meza', 'Gallardo', 'Pinilla', 'Donoso', 'Olivares', 'Ramos', 'Henríquez', 'Díaz', 'Parra', 'Muñoz', 'Reyes', 'Campos', 'Farías', 'Ortega', 'Arriagada', 'Cerda', 'Lagos', 'Vera', 'Guerra', 'Cruz', 'Escobar', 'Valdés', 'Riquelme', 'Puebla', 'Palma', 'Maldonado', 'Godoy', 'Santana', 'Gómez', 'Hidalgo', 'Urrutia', 'Velasco', 'Lara', 'Venegas', 'Riquelme', 'Sandoval', 'Pino', 'Villalobos', 'Mendoza', 'Zúñiga', 'Barrios'],
    fL: ['Gonzalezes', 'Munozes', 'Rojases', 'Diazes', 'Perezes', 'Sotos', 'Contrerases', 'Silvas', 'Martinezes', 'Sepulvedas', 'Moraleses', 'Rodriguezes', 'Lopezes', 'Fuenteses', 'Hernandezes', 'Torreses', 'Arayas', 'Floreses', 'Espinozas', 'Valenzuelas', 'Castillos', 'Tapias', 'Reyeses', 'Gutierrezes', 'Castros', 'Pizarros', 'Alvarezes', 'Vásquezes', 'Carrascos', 'Herreras', 'Cárdenases', 'Aguileras', 'Gomezes', 'Vergaras', 'Figueroas', 'Jaras', 'Nuñezes', 'Godoys', 'San Martins', 'Vargases', 'Orellanas', 'Bravos', 'Mendozas', 'Penas', 'Cácereses', 'Navarros', 'Salinases', 'Bustoses', 'Rioses', 'Guzmans', 'Mirandas', 'Peraltas', 'Correas', 'Garridos', 'Paredeses', 'Leivas', 'Avilas', 'Molinas', 'Vegas', 'Mezas', 'Gallardos', 'Pinillas', 'Donosos', 'Olivareses', 'Ramoses', 'Henríquezes', 'Díazes', 'Parras', 'Muñozes', 'Reyes-F', 'Camposes', 'Faríases', 'Ortegas', 'Arriagadas', 'Cerdas', 'Lagoses', 'Veras', 'Guerras', 'Cruzes', 'Escobars', 'Valdéses', 'Riquelmes', 'Pueblas', 'Palmas', 'Maldonados', 'Godoyes', 'Santanas', 'Gómezes', 'Hidalgos', 'Urrutias', 'Velascos', 'Laras', 'Venegases', 'Riquelme-F', 'Sandovals', 'Pinos', 'Villaloboses', 'Mendozases', 'Zúñigases', 'Barrioses']
  },
  'ekuador': {
    mF: ['Christian', 'Darwin', 'Edison', 'Franklin', 'Geovanny', 'Holger', 'Jefferson', 'Kevin-E', 'Lenin', 'Milton', 'Nixon', 'Oswaldo', 'Patricio-E', 'Byron', 'Stalin', 'Wilmer', 'Xavier-E', 'Yandri', 'Washington', 'Alexander-E', 'Alejandro-E', 'Andres-E', 'Carlos-E', 'Diego-E', 'Eduardo-E', 'Fernando-E', 'Gabriel-E', 'Hugo-E', 'Ivan-E', 'Javier-E', 'Jose-E', 'Juan-E', 'Luis-E', 'Manuel-E', 'Mario-E', 'Miguel-E', 'Pablo-E', 'Pedro-E', 'Rafael-E', 'Ricardo-E', 'Roberto-E', 'Santiago-E', 'Victor-E', 'Adrian-E', 'Alfonso-E', 'Alfredo-E', 'Alvaro-E', 'Angel-E', 'Antonio-E', 'Arturo-E', 'Cesar-E', 'Daniel-E', 'Dario-E', 'Edgar-E', 'Esteban-E', 'Felipe-E', 'Gonzalo-E', 'Guillermo-E', 'Gustavo-E', 'Hector-E', 'Ignacio-E', 'Jaime-E', 'Jorge-E', 'Leonardo-E', 'Lorenzo-E', 'Lucas-E', 'Marcos-E', 'Martin-E', 'Matias-E', 'Mauricio-E', 'Nicolas-E', 'Oscar-E', 'Ramiro-E', 'Raul-E', 'Rodrigo-E', 'Ruben-E', 'Sebastian-E', 'Sergio-E', 'Tomas-E', 'Vicente-E', 'Wilfredo-E', 'Yael-E', 'Zacarias-E', 'Abel-E', 'Adolfo-E', 'Aldo-E', 'Amador-E', 'Augusto-E', 'Boris-E', 'Camilo-E', 'Claudio-E', 'Dante-E', 'Efraim-E', 'Elias-E', 'Enrique-E', 'Erasmo-E', 'Erick-E', 'Fidel-E', 'Gerardo-E', 'German-E'],
    fF: ['Ximena-E', 'Yolanda-E', 'Zoraida', 'Aida-E', 'Alba-E', 'Alicia-E', 'Amalia-E', 'Amanda-E', 'Ana-E', 'Andrea-E', 'Angela-E', 'Antonia-E', 'Beatriz-E', 'Bianca-E', 'Camila-E', 'Carla-E', 'Carmen-E', 'Carolina-E', 'Catalina-E', 'Cecilia-E', 'Clara-E', 'Claudia-E', 'Constanza-E', 'Cristina-E', 'Daniela-E', 'Diana-E', 'Elena-E', 'Elisa-E', 'Emilia-E', 'Esperanza-E', 'Estefania-E', 'Eva-E', 'Florencia-E', 'Francisca-E', 'Gabriela-E', 'Gloria-E', 'Guadalupe-E', 'Ines-E', 'Isabel-E', 'Isabella-E', 'Josefina-E', 'Juana-E', 'Julia-E', 'Laura-E', 'Leticia-E', 'Lucia-E', 'Luisa-E', 'Magdalena-E', 'Manuela-E', 'Margarita-E', 'Maria-E', 'Mariana-E', 'Marina-E', 'Marta-E', 'Martina-E', 'Mercedes-E', 'Micaela-E', 'Natalia-E', 'Olga-E', 'Patricia-E', 'Paula-E', 'Paulina-E', 'Pilar-E', 'Raquel-E', 'Renata-E', 'Rocio-E', 'Rosa-E', 'Rosario-E', 'Sara-E', 'Silvia-E', 'Sofia-E', 'Soledad-E', 'Teresa-E', 'Valentina-E', 'Valeria-E', 'Veronica-E', 'Victoria-E', 'Virginia-E', 'Yara-E', 'Abril-E', 'Agustina-E', 'Ainhoa-E', 'Aitana-E', 'Ambar-E', 'Aurora-E', 'Belen-E', 'Blanca-E', 'Candelaria-E', 'Candela-E', 'Carina-E', 'Celeste-E', 'Dalia-E', 'Delfina-E', 'Dulce-E', 'Estela-E', 'Fatima-E', 'Irene-E', 'Ivanna-E', 'Jazmin-E', 'Jimena-E'],
    mL: ['Zambrano', 'Sánchez-E', 'Zhen', 'Vera-E', 'Torres-E', 'Mendoza-E', 'Castro-E', 'Cedeño', 'Morales-E', 'López-E', 'García-E', 'Romero-E', 'Andrade-E', 'Intriago', 'Suárez-E', 'Flores-E', 'Álvarez-E', 'Ortiz-E', 'Benítez-E', 'Salazar-E', 'Moncayo', 'Bravo-E', 'Chávez-E', 'Valencia-E', 'Paredes-E', 'Espinoza-E', 'Vargas-E', 'Aguilar-E', 'Bermeo', 'Arias-E', 'Rivera-E', 'Reyes-E', 'Ríos-E', 'Castillo-E', 'Delgado-E', 'Pérez-E', 'Gómez-E', 'Gutiérrez-E', 'Herrera-E', 'Brito', 'Navarro-E', 'Velasco-E', 'Cárdenas-E', 'Cordero', 'Moreno-E', 'Villacís', 'Jaramillo-E', 'Ramírez-E', 'Salguero', 'Pacheco-E', 'Figueroa-E', 'Guerrero-E', 'Molina-E', 'Rojas-E', 'Saldaña', 'Sarabia', 'Tapia-E', 'Villagómez', 'Yepez', 'Aguirre-E', 'Alvarado-E', 'Arcentales', 'Barahona', 'Bastidas', 'Cadena', 'Coronel', 'Freire', 'Hidalgo-E', 'Loor', 'Maldonado-E', 'Naranjo-E', 'Orellana-E', 'Pina', 'Quishpe', 'Rosero', 'Santamaría', 'Toapanta', 'Urbina-E', 'Vallejo', 'Wong', 'Yánez', 'Zurita', 'Armijos', 'Bonilla', 'Carrión', 'Duque-E', 'Escobar-E', 'Gavilanes', 'Guzmán-E', 'Lara-E', 'Medina-E', 'Nieto-E', 'Ochoa-E', 'Pineda-E', 'Quispe-E', 'Reinoso', 'Santillán-E', 'Tello-E', 'Viteri'],
    fL: ['Zambranos', 'Sánchez-EF', 'Zhens', 'Vera-EF', 'Torres-EF', 'Mendoza-EF', 'Castro-EF', 'Cedeños', 'Morales-EF', 'López-EF', 'García-EF', 'Romero-EF', 'Andrade-EF', 'Intriagos', 'Suárez-EF', 'Flores-EF', 'Álvarez-EF', 'Ortiz-EF', 'Benítez-EF', 'Salazar-EF', 'Moncayos', 'Bravo-EF', 'Chávez-EF', 'Valencia-EF', 'Paredes-EF', 'Espinoza-EF', 'Vargas-EF', 'Aguilar-EF', 'Bermeos', 'Arias-EF', 'Rivera-EF', 'Reyes-EF', 'Ríos-EF', 'Castillo-EF', 'Delgado-EF', 'Pérez-EF', 'Gómez-EF', 'Gutiérrez-EF', 'Herrera-EF', 'Britos', 'Navarro-EF', 'Velasco-EF', 'Cárdenas-EF', 'Corderos', 'Moreno-EF', 'Villacíses', 'Jaramillo-EF', 'Ramírez-EF', 'Salgueros', 'Pacheco-EF', 'Figueroa-EF', 'Guerrero-EF', 'Molina-EF', 'Rojas-EF', 'Saldañas', 'Sarabias', 'Tapia-EF', 'Villagómezes', 'Yepezes', 'Aguirre-EF', 'Alvarado-EF', 'Arcentaleses', 'Barahonas', 'Bastidases', 'Cadenas', 'Coronelses', 'Freires', 'Hidalgo-EF', 'Loors', 'Maldonado-EF', 'Naranjo-EF', 'Orellana-EF', 'Pinas', 'Quishpes', 'Roseros', 'Santamarías', 'Toapantas', 'Urbina-EF', 'Vallejos', 'Wongs', 'Yánezes', 'Zuritas', 'Armijoses', 'Bonillas', 'Carriónes', 'Duque-EF', 'Escobar-EF', 'Gavilaneses', 'Guzmán-EF', 'Lara-EF', 'Medina-EF', 'Nieto-EF', 'Ochoa-EF', 'Pineda-EF', 'Quispe-EF', 'Reinosos', 'Santillán-EF', 'Tello-EF', 'Viteris']
  },
  'guiana prancis': {
    mF: ['Jean', 'Michel', 'Philippe', 'Alain', 'Patrick', 'Christian-F', 'Bernard', 'Daniel-F', 'Pascal', 'Eric', 'Laurent', 'Stephane', 'David-F', 'Dominique', 'Christophe', 'Frederic', 'Thierry', 'Gilles', 'Olivier', 'Nicolas-F', 'Franck', 'Pierre', 'Serge', 'Julien', 'Sebastien', 'Vincent', 'Marc', 'Patrice', 'Didier', 'Guillaume', 'Jerome', 'Denis', 'Joel-F', 'Bruno-F', 'Luc', 'Guy', 'Herve', 'Emmanuel-F', 'Anthony-F', 'Alexandre-F', 'Fabrice', 'Maxime', 'Florian', 'Arnaud', 'Cyril', 'Cedric', 'Ludovic', 'Romain', 'Benjamin-F', 'Thomas', 'Antoine', 'Alexis', 'Mathieu', 'Damien', 'Aurelien', 'Kevin-F', 'Clement', 'Adrien', 'Loic', 'Mickael', 'Guillaume-F', 'Yannick', 'Xavier-F', 'Sylvain', 'Benoit', 'Samuel-F', 'Gregory', 'Ludovic-F', 'Fabien', 'Jeremy', 'Anthony-2', 'Hugo-F', 'Jordan', 'Raphael', 'Lucas-F', 'Quentin', 'Paul', 'Dylan', 'Nathan-F', 'Enzo-F', 'Leo', 'Arthur-F', 'Gabriel-F', 'Louis', 'Jules', 'Mathis', 'Yaniss', 'Valentin-F', 'Axel-F', 'Tom', 'Theo', 'Clément', 'Victor-F', 'Maxence', 'Evan', 'Nolan', 'Maael', 'Noa-F', 'Gabriel-2', 'Léo'],
    fF: ['Marie', 'Nathalie', 'Isabelle', 'Catherine', 'Sylvie', 'Anne', 'Monique', 'Christine-F', 'Françoise', 'Martine', 'Chantal', 'Nicole-F', 'Dominique-F', 'Valérie', 'Jacqueline-F', 'Brigitte', 'Sandrine', 'Patricia-F', 'Corinne', 'Stéphanie', 'Sophie', 'Céline', 'Aurélie', 'Laurence', 'Elodie', 'Emmanuelle', 'Virginie', 'Sarah-F', 'Audrey', 'Julie', 'Camille-F', 'Manon', 'Pauline', 'Chloe-F', 'Lea', 'Laura-F', 'Marine', 'Marion', 'Anais', 'Océane', 'Ines-F', 'Mathilde', 'Lucie', 'Clara-F', 'Charlotte', 'Emma-F', 'Clémence', 'Jade', 'Eva-F', 'Louise', 'Romane', 'Zélie', 'Lisa', 'Agathe', 'Justine', 'Margaux', 'Alice-F', 'Léa-F', 'Manon-F', 'Enora', 'Salomé', 'Louna', 'Margot', 'Jeanne', 'Noémie', 'Mélanie', 'Lina-F', 'Zoé', 'Amandine', 'Victoire', 'Inès-F', 'Elisa-F', 'Lou', 'Maëlys', 'Ninon', 'Julia-F', 'Roxane', 'Lilia', 'Iris-F', 'Capucine', 'Adèle', 'Célia', 'Rose-F', 'Eden-F', 'Lana', 'Yasmine', 'Mia-F', 'Léna', 'Anna', 'Lila', 'Maëlle', 'Constance', 'Maya-F', 'Eléonore', 'Charlie', 'Alicia-F', 'Luna-F', 'Lise', 'Clementine'],
    mL: ['Dupont', 'Martin-F', 'Bernard-F', 'Thomas-F', 'Petit', 'Robert', 'Richard', 'Durand', 'Dubois', 'Moreau', 'Laurent-F', 'Simon-F', 'Michel-F', 'Lefebvre', 'Leroy', 'Roux', 'David-FL', 'Bertrand', 'Morel', 'Fournier', 'Girard', 'Bonnet', 'Dupuy', 'Lambert', 'Fontaine', 'Rousseau', 'Vincent-F', 'Muller', 'Lefevre', 'Faure', 'Andre', 'Mercier', 'Blanc', 'Guerin', 'Boyer', 'Garnier', 'Chevalier', 'Francois', 'Legrand', 'Gauthier', 'Garcia-F', 'Perrin', 'Robin', 'Clement-F', 'Morvan', 'Nicolas-FL', 'Henry', 'Roussel', 'Mathieu-F', 'Gautier', 'Masson', 'Marchand', 'Duval', 'Denis-F', 'Dumont', 'Marie-F', 'Lemaire', 'Noel', 'Meyer', 'Dufour', 'Meunier', 'Brun', 'Blanchard', 'Giraud', 'Joly', 'Riviere', 'Lucas-FL', 'Brunet', 'Gaillard', 'Barbier', 'Arnaud-F', 'Martinez-F', 'Gerard', 'Roche', 'Renard', 'Schmitt', 'Royer', 'Pierre-F', 'Leroux', 'Colin', 'Vidal-F', 'Caron', 'Picard', 'Roger', 'Fabre', 'Aubert', 'Olivier-F', 'Guillaume-FL', 'Hubert', 'Tessier', 'Charles', 'Guillot', 'Lecomte', 'Rey', 'Bernier', 'Gilles-F', 'Benoit-F', 'Joly-2', 'Gimenez-F'],
    fL: ['Duponts', 'Martins', 'Bernards', 'Thomases', 'Petits', 'Roberts', 'Richards', 'Durands', 'Duboises', 'Moreaus', 'Laurents', 'Simons', 'Michels', 'Lefebvres', 'Leroys', 'Rouxes', 'Davids', 'Bertrands', 'Morels', 'Fourniers', 'Girards', 'Bonnets', 'Dupuys', 'Lamberts', 'Fontaines', 'Rousseaus', 'Vincents', 'Mullers', 'Lefevres', 'Faures', 'Andres', 'Merciers', 'Blancs', 'Guerins', 'Boyers', 'Garniers', 'Chevaliers', 'Francois', 'Legrands', 'Gauthiers', 'Garcias-F', 'Perrins', 'Robins', 'Clements', 'Morvans', 'Nicolases', 'Henrys', 'Roussels', 'Mathieus', 'Gautiers', 'Massons', 'Marchands', 'Duvals', 'Denises', 'Dumonts', 'Maries', 'Lemaires', 'Noels', 'Meyers', 'Dufours', 'Meuniers', 'Bruns', 'Blanchards', 'Girauds', 'Jolys', 'Rivieres', 'Lucases', 'Brunets', 'Gaillards', 'Barbiers', 'Arnauds', 'Martinezes-F', 'Gerards', 'Roches', 'Renards', 'Schmitts', 'Royers', 'Pierres', 'Lerouxes', 'Colins', 'Vidals-F', 'Carons', 'Picards', 'Rogers', 'Fabres', 'Auberts', 'Oliviers', 'Guillaumes', 'Huberts', 'Tessiers', 'Charleses', 'Guillots', 'Lecomtes', 'Reys', 'Berniers', 'Gilleses', 'Benoits', 'Jolyses', 'Gimenezes-F']
  },
  'guyana': {
    mF: ['Devon', 'Kevon', 'Shaquille', 'Terrence', 'Rohan-G', 'Lashawn', 'Tariq-G', 'Dwayne', 'Malik-G', 'Kwesi', 'Trevon', 'Tyrone', 'Jadon', 'Jevon', 'Keston', 'Omesh', 'Vishal', 'Rajesh', 'Sunil', 'Dinesh', 'Karan', 'Ravi-G', 'Vijay', 'Anand', 'Avinash', 'Brijesh', 'Deepak', 'Ganesh', 'Hari', 'Inderjit', 'Jagan', 'Khemraj', 'Lachman', 'Mahendra', 'Narayan', 'Omkar', 'Prakash', 'Prem', 'Ram', 'Sachin', 'Shiw', 'Tameshwar', 'Uttam', 'Varun', 'Yash', 'Aaron-G', 'Adrian-G', 'Alan-G', 'Alex-G', 'Andrew-G', 'Anthony-G', 'Arthur-G', 'Benjamin-G', 'Charles-G', 'Christopher-G', 'Daniel-G', 'David-G', 'Dennis-G', 'Donald-G', 'Edward-G', 'Eric-G', 'Frank-G', 'George-G', 'Gregory-G', 'Harold-G', 'Henry-G', 'James-G', 'Jason-G', 'Jeffrey-G', 'John-G', 'Joseph-G', 'Kenneth-G', 'Kevin-G', 'Larry-G', 'Mark-G', 'Matthew-G', 'Michael-G', 'Patrick-G', 'Paul-G', 'Peter-G', 'Richard-G', 'Robert-G', 'Ronald-G', 'Samuel-G', 'Stephen-G', 'Steven-G', 'Thomas-G', 'Timothy-G', 'William-G', 'Brian-G', 'Gary-G', 'Jerry-G', 'Justin-G', 'Keith-G', 'Raymond-G', 'Roger-G', 'Russell-G', 'Scott-G', 'Sean-G'],
    fF: ['Shania', 'Brianna', 'Tiana', 'Kiara-G', 'Shanice', 'Lashawna', 'Tanisha', 'Priya-G', 'Anjali-G', 'Kavita', 'Sunita', 'Pooja', 'Aarti', 'Deepa', 'Geeta', 'Indira-G', 'Jyoti', 'Kiran', 'Lata', 'Meena-G', 'Nisha-G', 'Radha-G', 'Ritu', 'Sarita-G', 'Tara-G', 'Usha-G', 'Vidhya', 'Yasmin-G', 'Zenia', 'Abigail-G', 'Alicia-G', 'Amanda-G', 'Amber-G', 'Amy-G', 'Angela-G', 'Ann-G', 'Anna-G', 'Ashley-G', 'Barbara-G', 'Brenda-G', 'Carol-G', 'Catherine-G', 'Cheryl-G', 'Christine-G', 'Cynthia-G', 'Deborah-G', 'Denise-G', 'Diana-G', 'Donna-G', 'Elizabeth-G', 'Emily-G', 'Emma-G', 'Evelyn-G', 'Frances-G', 'Grace-G', 'Hannah-G', 'Heather-G', 'Helen-G', 'Jacqueline-G', 'Jane-G', 'Janet-G', 'Janice-G', 'Jennifer-G', 'Jessica-G', 'Joan-G', 'Joyce-G', 'Judith-G', 'Karen-G', 'Katherine-G', 'Kathleen-G', 'Kimberly-G', 'Laura-G', 'Linda-G', 'Lisa-G', 'Margaret-G', 'Maria-G', 'Marie-G', 'Marilyn-G', 'Martha-G', 'Mary-G', 'Megan-G', 'Melissa-G', 'Michelle-G', 'Nancy-G', 'Nicole-G', 'Pamela-G', 'Patricia-G', 'Rachel-G', 'Rebecca-G', 'Rita-G', 'Rose-G', 'Sandra-G', 'Sarah-G', 'Sharon-G', 'Shirley-G', 'Stephanie-G', 'Susan-G', 'Teresa-G', 'Theresa-G', 'Victoria-G'],
    mL: ['Persaud', 'Singh-G', 'Khan-G', 'Ali-G', 'Thomas-G', 'Joseph-G', 'Naraine', 'Bacchus', 'Chand', 'Gajraj', 'Jagdeo', 'Ram', 'Rampersaud', 'Roopnarine', 'Sukhdeo', 'Williams-G', 'James-GL', 'Charles-GL', 'John-GL', 'George-GL', 'Adams-G', 'Alexander-GL', 'Allen-G', 'Anderson-G', 'Babu', 'Baljit', 'Beharry', 'Bisnauth', 'Budhram', 'Campbell-G', 'Clarke-G', 'Daniel-GL', 'David-GL', 'Deonarine', 'Francis-G', 'Fraser-G', 'Gonsalves', 'Grant-G', 'Harry', 'Henry-GL', 'Hunte', 'Jackson-G', 'Jeffers', 'Jonas-GL', 'Kanhai', 'Kissoon', 'Lall', 'Lewis-G', 'Mahadeo', 'Maharaj', 'Martin-GL', 'Mohammed-G', 'Moore-G', 'Narine', 'Nelson-G', 'Paul-GL', 'Pedro-GL', 'Phillip-G', 'Rambarran', 'RamDass', 'Ramkumar', 'Ramnauth', 'Ramsaroop', 'Roberts-G', 'Rodney', 'Samaroo', 'Sammy', 'Seeram', 'Sharma-G', 'Solomon-G', 'Sookdeo', 'Velloza', 'Walcott', 'Welch-G', 'West-G', 'Wong-G', 'Yearwood', 'Abrahams', 'Benjamin-GL', 'Bobb', 'Braithwaite', 'Brathwaite', 'Cesar-GL', 'Chance', 'Cumberbatch', 'Gideon', 'Gilkes', 'Holder-G', 'Holi', 'Hussein-G', 'Jagan-L', 'LaRose', 'Mentore', 'Peters-G', 'Trotman', 'Winter-G'],
    fL: ['Persauds', 'Singhs', 'Khans', 'Alis', 'Thomases-G', 'Josephs', 'Naraines', 'Bacchuses', 'Chands', 'Gajrajs', 'Jagdeos', 'Rams', 'Rampersauds', 'Roopnarines', 'Sukhdeos', 'Williamses', 'Jameses', 'Charleses-G', 'Johns', 'Georges', 'Adamses', 'Alexanders', 'Allens', 'Andersons', 'Babus', 'Baljits', 'Beharrys', 'Bisnauths', 'Budhrams', 'Campbells', 'Clarkes', 'Daniels', 'Davids-G', 'Deonarines', 'Francises', 'Frasers', 'Gonsalveses', 'Grants', 'Harrys', 'Henrys-G', 'Huntes', 'Jacksons', 'Jefferses', 'Jonases', 'Kanhais', 'Kissoons', 'Lalls', 'Lewises', 'Mahadeos', 'Maharajs', 'Martins-G', 'Mohammeds', 'Moores', 'Narines', 'Nelsons', 'Pauls', 'Pedros', 'Phillips', 'Rambarrans', 'RamDasses', 'Ramkumars', 'Ramnauths', 'Ramsaroops', 'Robertses', 'Rodneys', 'Samaroos', 'Sammys', 'Seerams', 'Sharmas', 'Solomons', 'Sookdeos', 'Vellozas', 'Walcotts', 'Welches', 'Wests', 'Wongs-G', 'Yearwoods', 'Abrahamses', 'Benjamins', 'Bobbs', 'Braithwaites', 'Brathwaites', 'Cesars', 'Chances', 'Cumberbatches', 'Gideons', 'Gilkeses', 'Holders', 'Holis', 'Husseins', 'Jagans', 'LaRoses', 'Mentores', 'Peterses', 'Trotmans', 'Winters']
  },
  'paraguay': {
    mF: ['Arnaldo', 'Celso-P', 'Derlis', 'Herminio', 'Ignacio-P', 'Justo', 'Nelson-P', 'Osvaldo-P', 'Sixto', 'Teodoro', 'Wilfrido', 'Alides', 'Anibal', 'Balbino', 'Basilio-P', 'Cirilo', 'Dionisio', 'Eligio', 'Fidencio', 'Genaro', 'Hilarión', 'Inocencio-P', 'Juvenal', 'Ladislao', 'Marcial', 'Nicanor', 'Ovidio', 'Policarpo', 'Quintín', 'Raimundo-P', 'Salustiano', 'Tiburcio', 'Urbano', 'Venancio', 'Waldir', 'Zacarías-P', 'Aldo-P', 'Blas', 'Cristhian', 'Diosnel', 'Ever', 'Fulgencio', 'Guido', 'Heriberto', 'Italo', 'Joel-P', 'Lidio', 'Modesto-P', 'Nery', 'Over', 'Pablino', 'Rony', 'Silvio', 'Tito', 'Ubaldo', 'Virgilio', 'Wilian', 'Yamil-P', 'Amancio', 'Benigno', 'Cancio', 'Desiderio', 'Eulalio', 'Froilán', 'Gervasio', 'Heriberto-P', 'Isidro-P', 'Juan-Ramon', 'Leocadio', 'Melanio', 'Nicasio', 'Onofre', 'Primitivo', 'Rogelio', 'Secundino', 'Toribio', 'Ulpiano', 'Valerio', 'Wenceslao', 'Abundio', 'Bonifacio', 'Cipriano', 'Delfín', 'Eustacio', 'Fortunato', 'Guillermo-P', 'Hermógenes', 'Ismael-P', 'Justino', 'Laureano', 'Macario', 'Nazario', 'Octavio-P', 'Protasio', 'Rufino', 'Saturnino', 'Telesforo'],
    fF: ['Sindulfa', 'Petrona-P', 'Ignacia-P', 'Juana-P', 'Modesta-P', 'Marciana', 'Saturnina-P', 'Teodora-P', 'Ursula-P', 'Vicenta-P', 'Zenobia-P', 'Adelaida-P', 'Albina-P', 'Benita-P', 'Casimira-P', 'Ceferina-P', 'Domitila-P', 'Eustaquia-P', 'Fortunata-P', 'Gregoria-P', 'Herminia-P', 'Justina-P', 'Leocadia-P', 'Marcelina-P', 'Nicanora-P', 'Romualda-P', 'Aurelia-P', 'Basilia-P', 'Clemencia-P', 'Dionisia-P', 'Eulalia-P', 'Filomena-P', 'Gertrudis-P', 'Hilaria-P', 'Inocencia-P', 'Juvita-P', 'Leonor-P', 'Narcisa-P', 'Octavia-P', 'Primitiva-P', 'Remedios-P', 'Sabina-P', 'Trinidad-P', 'Adelfa-P', 'Balbina-P', 'Celestina-P', 'Daria-P', 'Epifania-P', 'Flora-P', 'Genoveva-P', 'Honorata-P', 'Isidora-P', 'Jacinta-P', 'Maura-P', 'Nieves-P', 'Prudencia-P', 'Rufina-P', 'Silvestra-P', 'Tiburcia-P', 'Ventura-P', 'Zulma-P', 'Agripina-P', 'Benedicta-P', 'Crisanta-P', 'Delia-P', 'Eulogia-P', 'Felicidad-P', 'Gudelia-P', 'Jacquelin-P', 'Laurentina-P', 'Melchora-P', 'Nativia-P', 'Otilia-P', 'Pastora-P', 'Rosalia-P', 'Simona-P', 'Toribia-P', 'Vilma-P', 'Aida-P', 'Amalia-P', 'Elisa-P', 'Estela-P', 'Ester-P', 'Evangelina', 'Faustina', 'Graciela-P', 'Hermosa', 'Idalina', 'Juana-Ines', 'Lidia-P', 'Norma-P', 'Olga-P', 'Rosario-P', 'Sonia-P', 'Teresa-P', 'Zulma-2'],
    mL: ['González-P', 'Benítez-P', 'Martínez-P', 'López-P', 'Giménez-P', 'Vera-P', 'Duarte-P', 'Villalba-P', 'Fernández-P', 'Gómez-P', 'Acosta-P', 'Rojas-P', 'Ortiz-P', 'Núñez-P', 'Ayala-P', 'García-P', 'Báez', 'Cardozo', 'Sosa-P', 'Torres-P', 'Cáceres-P', 'Ruiz-P', 'Ramírez-P', 'Caballero', 'Alegre', 'Aguilera-P', 'Riquelme-P', 'Bareiro', 'Gauto', 'Gamarra', 'Aquino-P', 'Paredes-P', 'Sánchez-P', 'Insfrán', 'Godoy-P', 'Valdez-P', 'Servín', 'Gallego', 'Barreto', 'Mendoza-P', 'Rolón', 'Bogado', 'Espínola', 'Cabrera-P', 'Brizuela', 'Medina-P', 'Florentín', 'Centurión', 'Ovelar', 'Maldonado-P', 'Mora-P', 'Peralta-P', 'Romero-P', 'Velázquez', 'Alcaraz', 'Ortega-P', 'Delgado-P', 'Estigarribia', 'Villamayor', 'Cantero', 'Otazú', 'Monges', 'Lezcano', 'Arce-P', 'Valenzuela-P', 'Chávez-P', 'Franco-P', 'Meza-P', 'Villagra', 'Benitez-2', 'Solaeche', 'Amarilla', 'Sanabria', 'Ledesma-P', 'Samudio', 'Pérez-P', 'Ríos-P', 'Castañeda', 'Fleitas', ' Galeano', 'Ozuna', 'Palacios-P', 'Portillo', 'Vargas-P', 'Arias-P', 'Carballo', 'Ocampos', 'Salinas-P', 'Castillo-P', 'Osorio-P', 'Verón', 'Alvarez-P', 'Barrios-P', 'Coronel-P', 'Escobar-P', 'Ferreira-P', 'Ibáñez-P', 'Lugo-P', 'Noguera'],
    fL: ['González-PF', 'Benítez-PF', 'Martínez-PF', 'López-PF', 'Giménez-PF', 'Vera-PF', 'Duarte-PF', 'Villalba-PF', 'Fernández-PF', 'Gómez-PF', 'Acosta-PF', 'Rojas-PF', 'Ortiz-PF', 'Núñez-PF', 'Ayala-PF', 'García-PF', 'Báezs', 'Cardozos', 'Sosa-PF', 'Torres-PF', 'Cáceres-PF', 'Ruiz-PF', 'Ramírez-PF', 'Caballeros', 'Alegres', 'Aguilera-PF', 'Riquelme-PF', 'Bareiros', 'Gautos', 'Gamarras', 'Aquino-PF', 'Paredes-PF', 'Sánchez-PF', 'Insfráns', 'Godoy-PF', 'Valdez-PF', 'Servíns', 'Gallegos-PF', 'Barretos', 'Mendoza-PF', 'Rolóns', 'Bogados', 'Espínolas', 'Cabrera-PF', 'Brizuelas', 'Medina-PF', 'Florentíns', 'Centurións', 'Ovelars', 'Maldonado-PF', 'Mora-PF', 'Peralta-PF', 'Romero-PF', 'Velázquezs', 'Alcarazes', 'Ortega-PF', 'Delgado-PF', 'Estigarribias', 'Villamayors', 'Canteros', 'Otazús', 'Mongeses', 'Lezcanos', 'Arce-PF', 'Valenzuela-PF', 'Chávez-PF', 'Franco-PF', 'Meza-PF', 'Villagras', 'Benitez-2F', 'Solaeches', 'Amarillas', 'Sanabrias', 'Ledesma-PF', 'Samudios', 'Pérez-PF', 'Ríos-PF', 'Castañedas', 'Fleitases', 'Galeanos', 'Ozunas', 'Palacios-PF', 'Portillos', 'Vargas-PF', 'Arias-PF', 'Carballos', 'Ocampos', 'Salinas-PF', 'Castillo-PF', 'Osorio-PF', 'Veróns', 'Alvarez-PF', 'Barrios-PF', 'Coronel-PF', 'Escobar-PF', 'Ferreira-PF', 'Ibáñez-PF', 'Lugo-PF', 'Nogueras']
  },
  'peru': {
    mF: ['Jhair', 'Kenyi', 'Yordy', 'Fabricio', 'Gianfranco', 'Jean-Pierre', 'Piero', 'Renzo-PE', 'Stéfano', 'Gerson-PE', 'Italo-PE', 'Jair', 'Josué', 'Kluiverth', 'Lander', 'Nils', 'Olenka-M', 'Percy', 'Ronaldo-PE', 'Sayri', 'Tupac', 'Wilmer-PE', 'Yerson', 'Zahir', 'Aldair-PE', 'Braulio', 'Cristhian-PE', 'Deyvis', 'Edson-PE', 'Farfan', 'Guillermo-PE', 'Heber', 'Inti', 'Jhony', 'Kiam', 'Lover', 'Mael', 'Neymar-PE', 'Over-PE', 'Paolo', 'Quiller', 'Rayan-PE', 'Sayan', 'Toño', 'Uriel-PE', 'Vidal-M', 'Winston', 'Xavier-PE', 'Yamil-PE', 'Zamir', 'Adolfo-PE', 'Beto', 'Cesar-PE', 'Dante-PE', 'Eber', 'Fredy', 'Gino-PE', 'Harold-PE', 'Irvin', 'Jhon', 'Keny', 'Lenin-PE', 'Meyker', 'Néstor', 'Omar-PE', 'Paul-PE', 'Ronal', 'Saúl', 'Tito-PE', 'Ulises', 'Víctor-PE', 'Willy', 'Yair', 'Zacarias-PE', 'Alejandro-PE', 'Angel-PE', 'Carlos-PE', 'Daniel-PE', 'Diego-PE', 'Eduardo-PE', 'Fernando-PE', 'Gabriel-PE', 'Hugo-PE', 'Ivan-PE', 'Javier-PE', 'Jose-PE', 'Juan-PE', 'Luis-PE', 'Manuel-PE', 'Mario-PE', 'Miguel-PE', 'Pablo-PE', 'Pedro-PE', 'Rafael-PE', 'Ricardo-PE', 'Roberto-PE', 'Santiago-PE'],
    fF: ['Xiomara', 'Yaritza', 'Yamile', 'Kenia-PE', 'Naysha', 'Kiara-PE', 'Nayeli', 'Anahi', 'Killa', 'Urpi', 'Zianya', 'Alendra', 'Briana', 'Danna', 'Deyna', 'Fiorella', 'Gia', 'Janira', 'Keyla', 'Luana-PE', 'Micaela-PE', 'Naomi', 'Ornella', 'Pilar-PE', 'Quilla', 'Roxana-PE', 'Saywa', 'Thalia', 'Umi', 'Valerie', 'Wanda-PE', 'Xena', 'Yami', 'Zoe-PE', 'Ariadna-PE', 'Brenda-PE', 'Cynthia', 'Denisse', 'Evelyn-PE', 'Fabiola-PE', 'Giselle-PE', 'Hania', 'Ivanna-PE', 'Jazmin-PE', 'Karina-PE', 'Lesly', 'Milagros-PE', 'Nathaly', 'Olinda', 'Priscila-PE', 'Quirina-PE', 'Rosmery', 'Sheila', 'Tania', 'Ursula-PE', 'Vania', 'Wendy-PE', 'Ximena-PE', 'Yulissa', 'Zulema', 'Alicia-PE', 'Beatriz-PE', 'Cecilia-PE', 'Daniela-PE', 'Estefania-PE', 'Gabriela-PE', 'Ines-PE', 'Julia-PE', 'Lorena-PE', 'Marina-PE', 'Natalia-PE', 'Patricia-PE', 'Raquel-PE', 'Silvia-PE', 'Teresa-PE', 'Valeria-PE', 'Yolanda-PE', 'Abril-PE', 'Agustina-PE', 'Ainhoa-PE', 'Aitana-PE', 'Ambar-PE', 'Aurora-PE', 'Belen-PE', 'Blanca-PE', 'Candelaria-PE', 'Candela-PE', 'Carina-PE', 'Celeste-PE', 'Dalia-PE', 'Delfina-PE', 'Dulce-PE', 'Estela-PE', 'Fatima-PE', 'Irene-PE', 'Jimena-PE', 'Lucia-PE', 'Martina-PE', 'Mia-PE'],
    mL: ['Quispe-PE', 'Flores-PE', 'Sánchez-PE', 'García-PE', 'Rojas-PE', 'Díaz-PE', 'Reyes-PE', 'Pérez-PE', 'Torres-PE', 'Gonzales-PE', 'Ramos-PE', 'Ramírez-PE', 'Mendoza-PE', 'Espinoza-PE', 'Castro-PE', 'Huamán', 'Vargas-PE', 'Mamani-PE', 'Chávez-PE', 'Gutiérrez-PE', 'Vásquez-PE', 'Fernández-PE', 'López-PE', 'Gómez-PE', 'Ruiz-PE', 'Alvarez-PE', 'Romero-PE', 'Solis', 'Ccama', 'Condori-PE', 'Vilca', 'Choque-PE', 'Ticona-PE', 'Apaza-PE', 'Poma-PE', 'Copa-PE', 'Callo', 'Huarachi-PE', 'Nina-PE', 'Chura-PE', 'Acarapi-PE', 'Quenta-PE', 'Yupanqui-PE', 'Limachi-PE', 'Laura-PE', 'Catacora-PE', 'Huanca-PE', 'Aruquipa-PE', 'Siñani-PE', 'Tarqui-PE', 'Yana-PE', 'Zarate-PE', 'Usnayo-PE', 'Kuno-PE', 'Machaca-PE', 'Guarachi-PE', 'Paco-PE', 'Aliaga-PE', 'Antequera-PE', 'Archondo-PE', 'Balderrama-PE', 'Barba-PE', 'Barrientos-PE', 'Belmonte-PE', 'Borda-PE', 'Calvo-PE', 'Carrasco-PE', 'Claros-PE', 'Daza-PE', 'Diez-PE', 'Doria-PE', 'Echalar-PE', 'Encinas-PE', 'Escalante-PE', 'Fuentelsaz-PE', 'Garbisu-PE', 'Granier-PE', 'Heroinas-PE', 'Hinojosa-PE', 'Holters-PE', 'Ipiña-PE', 'Iturri-PE', 'Jaimes-PE', 'Jaldin-PE', 'Jardín-PE', 'Koehler-PE', 'Kreidler-PE', 'Kuhne-PE', 'Landívar-PE', 'Lanza-PE', 'Linares-PE', 'Loza-PE', 'Mendes-PE', 'Mercado-PE', 'Monasterios-PE', 'Nallar-PE', 'Nogales-PE', 'Ordoñez-PE', 'Oropeza-PE'],
    fL: ['Quispe-PEF', 'Flores-PEF', 'Sánchez-PEF', 'García-PEF', 'Rojas-PEF', 'Díaz-PEF', 'Reyes-PEF', 'Pérez-PEF', 'Torres-PEF', 'Gonzales-PEF', 'Ramos-PEF', 'Ramírez-PEF', 'Mendoza-PEF', 'Espinoza-PEF', 'Castro-PEF', 'Huamáns', 'Vargas-PEF', 'Mamani-PEF', 'Chávez-PEF', 'Gutiérrez-PEF', 'Vásquez-PEF', 'Fernández-PEF', 'López-PEF', 'Gómez-PEF', 'Ruiz-PEF', 'Alvarez-PEF', 'Romero-PEF', 'Solises', 'Ccamas', 'Condori-PEF', 'Vilcas', 'Choque-PEF', 'Ticona-PEF', 'Apaza-PEF', 'Poma-PEF', 'Copa-PEF', 'Callos', 'Huarachi-PEF', 'Nina-PEF', 'Chura-PEF', 'Acarapi-PEF', 'Quenta-PEF', 'Yupanqui-PEF', 'Limachi-PEF', 'Laura-PEF', 'Catacora-PEF', 'Huanca-PEF', 'Aruquipa-PEF', 'Siñani-PEF', 'Tarqui-PEF', 'Yana-PEF', 'Zarate-PEF', 'Usnayo-PEF', 'Kuno-PEF', 'Machaca-PEF', 'Guarachi-PEF', 'Paco-PEF', 'Aliaga-PEF', 'Antequera-PEF', 'Archondo-PEF', 'Balderrama-PEF', 'Barba-PEF', 'Barrientos-PEF', 'Belmonte-PEF', 'Borda-PEF', 'Calvo-PEF', 'Carrasco-PEF', 'Claros-PEF', 'Daza-PEF', 'Diez-PEF', 'Doria-PEF', 'Echalar-PEF', 'Encinas-PEF', 'Escalante-PEF', 'Fuentelsaz-PEF', 'Garbisu-PEF', 'Granier-PEF', 'Heroinas-PEF', 'Hinojosa-PEF', 'Holters-PEF', 'Ipiña-PEF', 'Iturri-PEF', 'Jaimes-PEF', 'Jaldin-PEF', 'Jardín-PEF', 'Koehler-PEF', 'Kreidler-PEF', 'Kuhne-PEF', 'Landívar-PEF', 'Lanza-PEF', 'Linares-PEF', 'Loza-PEF', 'Mendes-PEF', 'Mercado-PEF', 'Monasterios-PEF', 'Nallar-PEF', 'Nogales-PEF', 'Ordoñez-PEF', 'Oropeza-PEF']
  },
  'suriname': {
    mF: ['Jairzinho', 'Sheraldo', 'Kewull', 'Ridgeciano', 'Kelvin-S', 'Denzel-S', 'Chan', 'Desi', 'Ronnie', 'Dino', 'Virgil-S', 'Stefano-S', 'Warner', 'Gilles-S', 'Errol', 'Clarence', 'Edgar-S', 'Jimmy-S', 'Patrick-S', 'Winston-S', 'Ruud', 'Frank-S', 'Ronald-S', 'Marc-S', 'Aron', 'Bryan-S', 'Clyde', 'Dwight', 'Earl', 'Fabian-S', 'Geno', 'Harvey', 'Ivan-S', 'Jason-S', 'Kenneth-S', 'Luciano-S', 'Marlon', 'Nigel', 'Orpheo', 'Purrel', 'Quenten', 'Ramon-S', 'Sergio-S', 'Tyrone-S', 'Urvin', 'Vessel', 'Wesley', 'Xavier-S', 'Yvan', 'Zechariah', 'Anand-S', 'Bhojraj', 'Chandrikapersad', 'Dewanand', 'Eshwar', 'Gajadhar', 'Haripersad', 'Inderjeet', 'Jagdish', 'Khemkarang', 'Lutchman', 'Mahinder', 'Narinder', 'Omesh-S', 'Parmessar', 'Ramlall', 'Siewperkash', 'Tulsiram', 'Upendra', 'Vidyadhar', 'Wishnu', 'Yoganand', 'Ahmad-S', 'Badrul', 'Chaidir', 'Daryanto', 'Edi', 'Farid-S', 'Gunawan', 'Herman-S', 'Iwan', 'Joko', 'Karsino', 'Legiman', 'Mardi', 'Ngrambe', 'Oetomo', 'Pono', 'Parto', 'Riyanto', 'Sastro', 'Tukiran', 'Utomo', 'Wagiman', 'Yudi', 'Zainal'],
    fF: ['Ashna', 'Ambika', 'Bhavna', 'Chandani', 'Deepika', 'Esha', 'Falguni', 'Gitanjali', 'Harsha', 'Ishita', 'Jayanti', 'Kavita-S', 'Lata-S', 'Meera', 'Nalini', 'Omita', 'Pratima', 'Rashmi', 'Shanti', 'Tulsi-S', 'Urmila-S', 'Vandana', 'Yogita', 'Zubeda', 'Anouska', 'Brenda-S', 'Desiree', 'Esther-S', 'Fabiola-S', 'Gervaise', 'Hester', 'Ingrid-S', 'Joyce-S', 'Karin', 'Lucia-S', 'Monique-S', 'Nathalie-S', 'Orpha', 'Patricia-S', 'Rachel-S', 'Sonja', 'Tania-S', 'Ursula-S', 'Vivian', 'Wanda-S', 'Yvonne-S', 'Zita', 'Endang', 'Fitri', 'Gatria', 'Harti', 'Indah', 'Jemini', 'Karsih', 'Lestari', 'Marni', 'Ningsih', 'Oetari', 'Parni', 'Rini', 'Siti', 'Tuti', 'Utami', 'Wati', 'Yuni', 'Zulaikha-S', 'Adriana-S', 'Beatrix', 'Corinne-S', 'Diana-S', 'Elfriede', 'Felicia-S', 'Grace-S', 'Heleen', 'Irene-S', 'Jacqueline-S', 'Kathleen-S', 'Liesbeth', 'Marianne', 'Nelly-S', 'Olga-S', 'Paula-S', 'Rita-S', 'Sylvia-S', 'Theresia', 'Vera-S', 'Wilma', 'Yolanda-S', 'Astrid', 'Brigitte-S', 'Carla-S', 'Deborah-S', 'Edith', 'Frieda', 'Gisela', 'Hilde', 'Inge', 'Jutta'],
    mL: ['Santokhi', 'Bouterse', 'Brunswijk', 'Hussain-S', 'Sardjoe', 'Pengel', 'Lachmon', 'Somohardjo', 'Achaibersing', 'Ramdin', 'Adhin', 'Venetiaan', 'Graanoogst', 'Krolis', 'Gajadien', 'Mathoera', 'Jogi', 'Rusland', 'Emanuels', 'Simons', 'Pokie', 'Jharap', 'Ramnarin', 'Sital', 'Veldder', 'Waterberg', 'Abrahams-S', 'Belfor', 'Caldeira-S', 'Dors', 'Emanuson', 'Ferrier', 'Gerrit', 'Hooghart', 'Iselhart', 'Jankie', 'Kanhai-S', 'Lijkwan', 'Manraj', 'Niamat', 'Oosterling', 'Pinas', 'Raghoebarsing', 'Seecharan', 'Tsang', 'Uiterloo', 'Vriesde', 'Wijngaarde', 'Zander', 'Alibux', 'Biharie', 'Compas', 'Dallwal', 'Elmont', 'Feller', 'Gomes-S', 'Hassankhan', 'Ismael-S', 'Jules', 'Kooistra', 'Lie-A-Kwie', 'Mac-Intosch', 'Noordwijk', 'Oft', 'Pelswijk', 'Rahan', 'Seedorf', 'Tjin-A-Tsoi', 'Valies', 'Wisse', 'Young', 'Zin-It', 'Amafo', 'Baal', 'Cooman', 'Doesburg', 'Edenburg', 'Franker', 'Gezius', 'Heikerk', 'Illes', 'Jap-A-Joe', 'Klaver', 'Limon', 'Muntslag', 'Naarden', 'Oranje', 'Proctor', 'Rensch', 'Starke', 'Telting', 'Valpoort', 'Wielzen', 'Zaandam'],
    fL: ['Santokhis', 'Bouterses', 'Brunswijks', 'Hussains', 'Sardjoes', 'Pengels', 'Lachmons', 'Somohardjos', 'Achaibersings', 'Ramdins', 'Adhins', 'Venetiaans', 'Graanoogsts', 'Krolises', 'Gajadiens', 'Mathoeras', 'Jogis', 'Ruslands', 'Emanuelses', 'Simonses', 'Pokies', 'Jharaps', 'Ramnarins', 'Sitals', 'Veldders', 'Waterbergs', 'Abrahamses-S', 'Belfors', 'Caldeiras-S', 'Dorses', 'Emanunsons', 'Ferriers', 'Gerrits', 'Hoogharts', 'Iselharts', 'Jankies', 'Kanhais-S', 'Lijkwans', 'Manrajs', 'Niamats', 'Oosterlings', 'Pinases', 'Raghoebarsings', 'Seecharans', 'Tsangs', 'Uiterloos', 'Vriesdes', 'Wijngaardes', 'Zanders', 'Alibuxes', 'Biharies', 'Compasses', 'Dallwals', 'Elmonts', 'Fellers', 'Gomeses-S', 'Hassankhans', 'Ismaels-S', 'Juless', 'Kooistras', 'Lie-A-Kwies', 'Mac-Intosches', 'Noordwijks', 'Ofts', 'Pelswijks', 'Rahans', 'Seeds', 'Tjin-A-Tsois', 'Valieses', 'Wisses', 'Youngs', 'Zin-Its', 'Amafos', 'Baals', 'Coomans', 'Doesburgs', 'Edenburgs', 'Frankers', 'Geziuses', 'Heikerks', 'Illeses', 'Jap-A-Joes', 'Klavers', 'Limons', 'Muntslags', 'Naardens', 'Oranjes', 'Proctors', 'Rensches', 'Starkes', 'Teltings', 'Valpoorts', 'Wielzens', 'Zaandams']
  },
  'uruguay': {
    mF: ['Cavani', 'Suarez-M', 'Forlan', 'Godin', 'Muslera', 'Valverde', 'Bentancur', 'Araujo-U', 'Nunez-U', 'Torreira', 'Vecino', 'Caceres-U', 'Gimenez-U', 'Lodeiro', 'Stuani', 'Abel-U', 'De-Arrascaeta', 'Pellistri', 'Viña', 'Olivera', 'Rochet', 'Coates', 'Varela-U', 'González-U', 'Rodríguez-U', 'Pérez-U', 'Sánchez-U', 'López-U', 'Gómez-U', 'Fernández-U', 'Díaz-U', 'Martínez-U', 'Álvarez-U', 'Romero-U', 'Sosa-U', 'Torres-U', 'Ruiz-U', 'Ramírez-U', 'Flores-U', 'Benítez-U', 'Acosta-U', 'Medina-U', 'Herrera-U', 'Aguirre-U', 'Gutiérrez-U', 'Pereira-U', 'Mendoza-U', 'Rojas-U', 'Peralta-U', 'Ortiz-U', 'Silva-U', 'Moreno-U', 'Ríos-U', 'Castillo-U', 'Franco-U', 'Villalba-U', 'Molina-U', 'Blanco-U', 'Castro-U', 'Domínguez-U', 'Vázquez-U', 'Núñez-U', 'Morales-U', 'Luna-U', 'Vargas-U', 'Navarro-U', 'Correa-U', 'Cabrera-U', 'Delgado-U', 'Escobar-U', 'Figueroa-U', 'Gallardo-U', 'Ibarra-U', 'Juárez-U', 'Ledesma-U', 'Miranda-U', 'Nieto-U', 'Ojeda-U', 'Paz-U', 'Quiroga-U', 'Reyes-U', 'Salinas-U', 'Valdez-U', 'Zapata-U', 'Bustos-U', 'Campos-U', 'Orellana-U', 'Ramos-U', 'Soria-U', 'Aguilar-U', 'Bravo-U', 'Ceballos-U', 'Duarte-U', 'Farías-U', 'Godoy-U', 'Lobo-U', 'Maldonado-U', 'Ponce-U'],
    fF: ['Tabare', 'Edinson', 'Diego-U', 'Fernando-U', 'Luis-U', 'Sebastian-U', 'Maximiliano-U', 'Nicolas-U', 'Martin-U', 'Gonzalo-U', 'Alvaro-U', 'Egidio', 'Walter-U', 'Cristian-U', 'Jorge-U', 'Carlos-U', 'Gabriel-U', 'Lucas-U', 'Federico-U', 'Rodrigo-U', 'Matias-U', 'Guillermo-U', 'Ignacio-U', 'Gaston-U', 'Santiago-U', 'Facundo-U', 'Jonathan', 'Nahitan', 'Brian', 'Darwin-U', 'Giorgian', 'Ronald', 'Manuel-U', 'Joaquin-U', 'Bautista-U', 'Agustin-U', 'Mateo-U', 'Thiago-U', 'Benicio-U', 'Luciano-U', 'Santino-U', 'Valentino-U', 'Damian-U', 'Emiliano-U', 'Bruno-U', 'Ramiro-U', 'Lautaro-U', 'Julian-U', 'Franco-U', 'Esteban-U', 'Marcos-U', 'Leandro-U', 'Ivan-U', 'Alan-U', 'Axel-U', 'Ciro-U', 'Enzo-U', 'Gael-U', 'Gino-U', 'Ian-U', 'Iker-U', 'Jonas-U', 'Leon-U', 'Luka-U', 'Milo-U', 'Noah-U', 'Oliver-U', 'Tiziano-U', 'Valentin-U', 'Vito-U', 'Alejo-U', 'Braian-U', 'Elias-U', 'Hector-U', 'Javier-U', 'Kevin-U', 'Lisandro-U', 'Mauricio-U', 'Nelson-U', 'Orlando-U', 'Pablo-U', 'Renzo-U', 'Sergio-U', 'Tobias-U', 'Uriel-U', 'Victor-U', 'Xavier-U', 'Yamil-U', 'Lucio-U', 'Patricio-U', 'Raul-U', 'Ruben-U', 'Tadeo-U', 'Vicente-U', 'Wilfredo-U', 'Yael-U', 'Zacarias-U', 'Adolfo-U', 'Aldo-U'],
    mL: ['Rodríguez-UR', 'González-UR', 'Pérez-UR', 'Fernández-UR', 'Sánchez-UR', 'Gómez-UR', 'Díaz-UR', 'Martínez-UR', 'Álvarez-UR', 'López-UR', 'Sosa-UR', 'García-UR', 'Torres-UR', 'Romero-UR', 'Ruiz-UR', 'Ramírez-UR', 'Flores-UR', 'Benítez-UR', 'Acosta-UR', 'Medina-UR', 'Herrera-UR', 'Suárez-UR', 'Aguirre-UR', 'Giménez-UR', 'Gutiérrez-UR', 'Pereira-UR', 'Mendoza-UR', 'Rojas-UR', 'Peralta-UR', 'Ortiz-UR', 'Silva-UR', 'Moreno-UR', 'Ríos-UR', 'Castillo-UR', 'Rossi-UR', 'Franco-UR', 'Villalba-UR', 'Molina-UR', 'Blanco-UR', 'Castro-UR', 'Cáceres-UR', 'Domínguez-UR', 'Vázquez-UR', 'Núñez-UR', 'Morales-UR', 'Luna-UR', 'Vargas-UR', 'Carrizo-UR', 'Ferrari-UR', 'Navarro-UR', 'Roldán-UR', 'Correa-UR', 'Bastos-UR', 'Cabrera-UR', 'Delgado-UR', 'Escobar-UR', 'Figueroa-UR', 'Gallardo-UR', 'Heredia-UR', 'Ibarra-UR', 'Juárez-UR', 'Ledesma-UR', 'Miranda-UR', 'Nieto-UR', 'Ojeda-UR', 'Paz-UR', 'Quinteros-UR', 'Santillán-UR', 'Toloza-UR', 'Urbina-UR', 'Vera-UR', 'Vidal-UR', 'Zamora-UR', 'Alemán-UR', 'Barrios-UR', 'Córdoba-UR', 'Duarte-UR', 'Farías-UR', 'Godoy-UR', 'Lobo-UR', 'Maldonado-UR', 'Olmedo-UR', 'Ponce-UR', 'Quiroga-UR', 'Reyes-UR', 'Salinas-UR', 'Trejo-UR', 'Valdez-UR', 'Zapata-UR', 'Bustos-UR', 'Campos-UR', 'Gaitán-UR', 'Lugo-UR', 'Orellana-UR', 'Ramos-UR', 'Soria-UR', 'Varela-UR', 'Aguilar-UR', 'Bravo-UR', 'Ceballos-UR'],
    fL: ['Rodríguez-URF', 'González-URF', 'Pérez-URF', 'Fernández-URF', 'Sánchez-URF', 'Gómez-URF', 'Díaz-URF', 'Martínez-URF', 'Álvarez-URF', 'López-URF', 'Sosa-URF', 'García-URF', 'Torres-URF', 'Romero-URF', 'Ruiz-URF', 'Ramírez-URF', 'Flores-URF', 'Benítez-URF', 'Acosta-URF', 'Medina-URF', 'Herrera-URF', 'Suárez-URF', 'Aguirre-URF', 'Giménez-URF', 'Gutiérrez-URF', 'Pereira-URF', 'Mendoza-URF', 'Rojas-URF', 'Peralta-URF', 'Ortiz-URF', 'Silva-URF', 'Moreno-URF', 'Ríos-URF', 'Castillo-URF', 'Rossi-URF', 'Franco-URF', 'Villalba-URF', 'Molina-URF', 'Blanco-URF', 'Castro-URF', 'Cáceres-URF', 'Domínguez-URF', 'Vázquez-URF', 'Núñez-URF', 'Morales-URF', 'Luna-URF', 'Vargas-URF', 'Carrizo-URF', 'Ferrari-URF', 'Navarro-URF', 'Roldán-URF', 'Correa-URF', 'Bastos-URF', 'Cabrera-URF', 'Delgado-URF', 'Escobar-URF', 'Figueroa-URF', 'Gallardo-URF', 'Heredia-URF', 'Ibarra-URF', 'Juárez-URF', 'Ledesma-URF', 'Miranda-URF', 'Nieto-URF', 'Ojeda-URF', 'Paz-URF', 'Quinteros-URF', 'Santillán-URF', 'Toloza-URF', 'Urbina-URF', 'Vera-URF', 'Vidal-URF', 'Zamora-URF', 'Alemán-URF', 'Barrios-URF', 'Córdoba-URF', 'Duarte-URF', 'Farías-URF', 'Godoy-URF', 'Lobo-URF', 'Maldonado-URF', 'Olmedo-URF', 'Ponce-URF', 'Quiroga-URF', 'Reyes-URF', 'Salinas-URF', 'Trejo-URF', 'Valdez-URF', 'Zapata-URF', 'Bustos-URF', 'Campos-URF', 'Gaitán-URF', 'Lugo-URF', 'Orellana-URF', 'Ramos-URF', 'Soria-URF', 'Varela-URF', 'Aguilar-URF', 'Bravo-URF', 'Ceballos-URF']
  },
  'venezuela': {
    mF: ['Rondon', 'Machis', 'Yangel', 'Soteldo', 'Rincon', 'Rosales-V', 'Otero-V', 'Savarino', 'Aristeguieta', 'Peñaranda', 'Fariñez', 'Chancellor', 'Ferraresi', 'Makoun', 'Casseres', 'Cordova-V', 'Murillo-V', 'Gonzalez-V', 'Hernandez-V', 'Moreno-V', 'Martinez-V', 'Castillo-V', 'Navarro-V', 'Bello-V', 'Cumana', 'Manzano', 'Junior-V', 'Ponce-V', 'Rivas-V', 'Zuniga-V', 'Perez-V', 'Torres-V', 'Silva-V', 'Rojas-V', 'Gutierrez-V', 'Mendoza-V', 'Flores-V', 'Morales-V', 'Ramirez-V', 'Ortiz-V', 'Rios-V', 'Franco-V', 'Caceres-V', 'Vargas-V', 'Navarro-V2', 'Correa-V', 'Cabrera-V', 'Delgado-V', 'Escobar-V', 'Figueroa-V', 'Gallardo-V', 'Ibarra-V', 'Juarez-V', 'Ledesma-V', 'Miranda-V', 'Nieto-V', 'Ojeda-V', 'Paz-V', 'Quiroga-V', 'Reyes-V', 'Salinas-V', 'Valdez-V', 'Zapata-V', 'Bustos-V', 'Campos-V', 'Orellana-V', 'Ramos-V', 'Soria-V', 'Aguilar-V', 'Bravo-V', 'Ceballos-V', 'Duarte-V', 'Farias-V', 'Godoy-V', 'Lobo-V', 'Maldonado-V', 'Ponce-V2', 'Acosta-V', 'Aguirre-V', 'Alvarez-V', 'Benitez-V', 'Carrizo-V', 'Dominguez-V', 'Ferrari-V', 'Gaitan-V', 'Gimenez-V', 'Heredia-V', 'Luna-V', 'Molina-V', 'Olmedo-V', 'Pereira-V', 'Quinteros-V', 'Roldan-V', 'Santillan-V', 'Toloza-V', 'Urbina-V', 'Vera-V', 'Vidal-V'],
    fF: ['Deyna-V', 'Gaby', 'Oriana', 'Ysaura', 'Michelle-V', 'Lourdes-V', 'Genesis', 'Kika', 'Barbara-V', 'Sonia-V2', 'Yerliane', 'Wilmary', 'Nyerlin', 'Marianyela', 'Kimberly-V', 'Raiderlin', 'Nathalie-V', 'Nayluisa', 'Lisbeth', 'Andrea-V', 'Maria-V', 'Ana-V', 'Carmen-V', 'Rosa-V', 'Josefa', 'Luisa-V', 'Elena-V', 'Isabel-V', 'Teresa-V', 'Juana-V', 'Margarita-V', 'Francisca-V', 'Antonia-V', 'Mercedes-V', 'Dolores', 'Pilar-V', 'Manuela-V', 'Concepcion', 'Victoria-V', 'Lucia-V', 'Sofia-V', 'Paula-V', 'Julita', 'Consuelo', 'Esperanza-V', 'Guadalupe-V', 'Beatriz-V', 'Patricia-V', 'Rosario-V', 'Montserrat', 'Ines-V', 'Yolanda-V', 'Gloria-V', 'Amparo', 'Asuncion', 'Milagros-V', 'Soledad-V', 'Loreto', 'Paloma-V', 'Belen-V', 'Rocio-V', 'Nieves-V', 'Esther-V', 'Nuria', 'Macarena', 'Celia', 'Raquel-V', 'Silvia-V', 'Alicia-V', 'Angeles', 'Aurora-V', 'Blanca-V', 'Clara-V', 'Magdalena-V', 'Irene-V', 'Julia-V', 'Catalina-V', 'Josefina-V', 'Virginia-V', 'Lourdes-V2', 'Mar', 'Remedios-V', 'Eugenia', 'Lidia-V', 'Elisa-V', 'Esperanza-V2', 'Natalia-V', 'Almudena', 'Sonia-V3', 'Guadalupe-V2', 'Begoña', 'Leticia-V', 'Noelia-V', 'Gema', 'Adela-V', 'Gemma-V', 'Fatima-V', 'Candelaria-V', 'Amalia-V', 'Ainhoa-V'],
    mL: ['González-VE', 'Rodríguez-VE', 'Pérez-VE', 'Hernández-VE', 'García-VE', 'Martínez-VE', 'Sánchez-VE', 'López-VE', 'Díaz-VE', 'Ramírez-VE', 'Álvarez-VE', 'Gómez-VE', 'Torres-VE', 'Mendoza-VE', 'Vargas-VE', 'Gutiérrez-VE', 'Morales-VE', 'Ortega-VE', 'Suárez-VE', 'Delgado-VE', 'Rojas-VE', 'Blanco-VE', 'Castro-VE', 'Castillo-VE', 'Ortiz-VE', 'Silva-VE', 'Romero-VE', 'Nunez-VE', 'Moreno-VE', 'Medina-VE', 'Ríos-VE', 'Ramos-VE', 'Herrera-VE', 'Guerrero-VE', 'Acosta-VE', 'Padrón', 'Colmenares', 'Bracho', 'Quintero', 'Urdaneta', 'Márquez-VE', 'Montero-VE', 'Campos-VE', 'Salazar-VE', 'Figueroa-VE', 'Chávez-VE', 'Bello-VE', 'Barrios-VE', 'Navarro-VE', 'Molina-VE', 'Aguilar-VE', 'Pena-VE', 'Pineda-VE', 'Velasco-VE', 'Villanueva-VE', 'Escobar-VE', 'Caraballo', 'Centeno', 'Infante-VE', 'Rondón', 'Sosa-VE', 'Rivas-VE', 'Montilla', 'Vielma', 'Oropeza-VE', 'Machado-VE', 'Pacheco-VE', 'Bermúdez-VE', 'Ravelo', 'Godoy-VE', 'Bastidas-VE', 'Villegas-VE', 'Cordero-VE', 'Cedeño-VE', 'Gallardo-VE', 'Mata', 'Zambrano-VE', 'Peralta-VE', 'Benítez-VE', 'Aponte', 'Guillén', 'Valero', 'Marín-VE', 'Nieto-VE', 'Vera-VE', 'Requena', 'Ochoa-VE', 'Briceño', 'Pinto-VE', 'Uzcátegui', 'Meza-VE', 'Alvarado-VE', 'Cárdenas-VE', 'Camacaro', 'Duarte-VE', 'Brito-VE', 'Osorio-VE', 'Coronel-VE', 'Rivero'],
    fL: ['González-VEF', 'Rodríguez-VEF', 'Pérez-VEF', 'Hernández-VEF', 'García-VEF', 'Martínez-VEF', 'Sánchez-VEF', 'López-VEF', 'Díaz-VEF', 'Ramírez-VEF', 'Álvarez-VEF', 'Gómez-VEF', 'Torres-VEF', 'Mendoza-VEF', 'Vargas-VEF', 'Gutiérrez-VEF', 'Morales-VEF', 'Ortega-VEF', 'Suárez-VEF', 'Delgado-VEF', 'Rojas-VEF', 'Blanco-VEF', 'Castro-VEF', 'Castillo-VEF', 'Ortiz-VEF', 'Silva-VEF', 'Romero-VEF', 'Nunez-VEF', 'Moreno-VEF', 'Medina-VEF', 'Ríos-VEF', 'Ramos-VEF', 'Herrera-VEF', 'Guerrero-VEF', 'Acosta-VEF', 'Padróns', 'Colmenareses', 'Brachos', 'Quinteros-VEF', 'Urdanetas', 'Márquez-VEF', 'Montero-VEF', 'Campos-VEF', 'Salazar-VEF', 'Figueroa-VEF', 'Chávez-VEF', 'Bello-VEF', 'Barrios-VEF', 'Navarro-VEF', 'Molina-VEF', 'Aguilar-VEF', 'Pena-VEF', 'Pineda-VEF', 'Velasco-VEF', 'Villanuevas', 'Escobar-VEF', 'Caraballos', 'Centenos', 'Infante-VEF', 'Rondóns', 'Sosa-VEF', 'Rivas-VEF', 'Montillas', 'Vielmas', 'Oropeza-VEF', 'Machado-VEF', 'Pacheco-VEF', 'Bermúdez-VEF', 'Ravelos', 'Godoy-VEF', 'Bastidas-VEF', 'Villegas-VEF', 'Cordero-VEF', 'Cedeño-VEF', 'Gallardo-VEF', 'Matas', 'Zambrano-VEF', 'Peralta-VEF', 'Benítez-VEF', 'Apontes', 'Guilléns', 'Valeros', 'Marín-VEF', 'Nieto-VEF', 'Vera-VEF', 'Requenas', 'Ochoa-VEF', 'Briceños', 'Pinto-VEF', 'Uzcáteguis', 'Meza-VEF', 'Alvarado-VEF', 'Cárdenas-VEF', 'Camacaros', 'Duarte-VEF', 'Brito-VEF', 'Osorio-VEF', 'Coronel-VEF', 'Riveros']
  }
};

const saAll = ['chile', 'ekuador', 'guiana prancis', 'guyana', 'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela'];

for (const c of saAll) {
  const baseDir = path.join('json', 'firstname_lastname', 'sa', c);
  if (!fs.existsSync(baseDir)) continue;

  const data = saAuthenticPools[c];
  if (!data) continue;

  const mFPath = path.join(baseDir, 'male', 'firstname.json');
  const fFPath = path.join(baseDir, 'female', 'firstname.json');
  const mLPath = path.join(baseDir, 'male', 'lastname.json');
  const fLPath = path.join(baseDir, 'female', 'lastname.json');

  const cSet = new Set();

  function sanitizePure100(arr) {
    const res = [];
    for (let item of arr) {
      if (typeof item === 'string') {
        item = item.replace(/[-_](E|F|M|FL|ML|MF|FF|L|S|2|3|QA|SG|SGF|TW|TWF|TM|CO|COF|BR|BF|B|BL|BLF|G|GL|P|PF|PE|PEF|VE|VEF|UR|URF)\d*$/g, '')
                    .replace(/\d+$/g, '')
                    .trim();
        if (item.length > 1 && !cSet.has(item) && !/first|last|name|junior|nombre|apellido/i.test(item)) {
          cSet.add(item);
          res.push(item);
        }
      }
      if (res.length >= 100) break;
    }
    return res;
  }

  const mF = sanitizePure100(data.mF);
  const fF = sanitizePure100(data.fF);
  const mL = sanitizePure100(data.mL);
  const fL = sanitizePure100(data.fL);

  fs.writeFileSync(mFPath, JSON.stringify(mF.slice(0, 100), null, 2));
  fs.writeFileSync(fFPath, JSON.stringify(fF.slice(0, 100), null, 2));
  fs.writeFileSync(mLPath, JSON.stringify(mL.slice(0, 100), null, 2));
  fs.writeFileSync(fLPath, JSON.stringify(fL.slice(0, 100), null, 2));
}

console.log('Finished writing 100% real human names for all remaining SA folders!');
