const fs = require('fs');
const path = require('path');

// Completely unique, non-overlapping 100 entries per file for each of the 13 South American countries!

const uniqueSAData = {
  'argentina': {
    mF: ['Mateo', 'Thiago', 'Benicio', 'Joaquin', 'Bautista', 'Santiago', 'Agustin', 'Francisco', 'Tomas', 'Ignacio', 'Nicolas', 'Lucas', 'Benjamin', 'Gonzalo', 'Lautaro', 'Valentino', 'Santino', 'Gabriel', 'Ezekiel', 'Martin', 'Ramiro', 'Facundo', 'Julian', 'Manuel', 'Mariano', 'Bruno', 'Emiliano', 'Dante', 'Lorenzo', 'Simon', 'Matias', 'Luciano', 'Esteban', 'Gaston', 'Damian', 'Sebastian', 'Leandro', 'Franco', 'Marcos', 'Iván', 'Federico', 'Nahuel', 'Alan', 'Diego', 'Rodrigo', 'Adriel', 'Alex', 'Axel', 'Ciro', 'Enzo', 'Gael', 'Gino', 'Ian', 'Iker', 'Jonas', 'Leon', 'Luka', 'Milo', 'Noah', 'Oliver', 'Tiziano', 'Valentin', 'Vito', 'Alejo', 'Braian', 'Cristian', 'Elias', 'Fernando', 'Guillermo', 'Hector', 'Javier', 'Kevin', 'Lisandro', 'Mauricio', 'Nelson', 'Orlando', 'Pablo', 'Renzo', 'Sergio', 'Tobias', 'Uriel', 'Victor', 'Walter', 'Xavier', 'Yamil', 'Lucio', 'Patricio', 'Raul', 'Ruben', 'Tadeo', 'Vicente', 'Zacarias', 'Abel', 'Adolfo', 'Aldo', 'Alfonso', 'Alfredo', 'Amador', 'Augusto', 'Boris', 'Camilo'],
    fF: ['Sofia', 'Emma', 'Valentina', 'Isabella', 'Martina', 'Lucia', 'Victoria', 'Catalina', 'Delfina', 'Mia', 'Elena', 'Juana', 'Renata', 'Emilia', 'Alma', 'Josefina', 'Olivia', 'Antonella', 'Camila', 'Paula', 'Abril', 'Lola', 'Brisa', 'Zoe', 'Maite', 'Malena', 'Guadalupe', 'Candela', 'Agostina', 'Jazmin', 'Lara', 'Micaela', 'Rocio', 'Morena', 'Sol', 'Clara', 'Francisca', 'Milagros', 'Constanza', 'Pilar', 'Bianca', 'Margarita', 'Carolina', 'Julietta', 'Florencia', 'Carla', 'Magali', 'Belen', 'Celeste', 'Luciana', 'Aitana', 'Ambar', 'Chloe', 'Giana', 'Gemma', 'Iara', 'Kiara', 'Luna', 'Melina', 'Naiara', 'Paloma', 'Quirina', 'Romina', 'Sabrina', 'Tiziana', 'Uma', 'Violeta', 'Wendy', 'Ximena', 'Yara', 'Alicia', 'Beatriz', 'Cecilia', 'Daniela', 'Estefania', 'Gabriela', 'Ines', 'Julia', 'Karina', 'Lorena', 'Marina', 'Natalia', 'Patricia', 'Raquel', 'Silvia', 'Teresa', 'Valeria', 'Yolanda', 'Ariadna', 'Brenda', 'Diana', 'Evelyn', 'Giselle', 'Ivanna', 'Jacqueline', 'Lourdes', 'Noelia', 'Priscila', 'Roxana'],
    mL: ['Gonzalez', 'Rodriguez', 'Gomez', 'Fernandez', 'Lopez', 'Diaz', 'Martinez', 'Perez', 'Romero', 'Sánchez', 'Sosa', 'Torres', 'Alvarez', 'Ruiz', 'Ramirez', 'Flores', 'Benitez', 'Acosta', 'Medina', 'Herrera', 'Suarez', 'Aguirre', 'Gimenez', 'Gutierrez', 'Pereira', 'Mendoza', 'Rojas', 'Peralta', 'Ortiz', 'Silva', 'Moreno', 'Rios', 'Castillo', 'Rossi', 'Franco', 'Villalba', 'Molina', 'Blanco', 'Castro', 'Caceres', 'Dominguez', 'Vazquez', 'Nunez', 'Morales', 'Luna', 'Vargas', 'Carrizo', 'Ferrari', 'Navarro', 'Roldan', 'Correa', 'Bastos', 'Cabrera', 'Delgado', 'Escobar', 'Figueroa', 'Gallardo', 'Heredia', 'Ibarra', 'Juarez', 'Ledesma', 'Miranda', 'Nieto', 'Ojeda', 'Paz', 'Quinteros', 'Santillan', 'Toloza', 'Urbina', 'Vera', 'Vidal', 'Zamora', 'Alemán', 'Barrios', 'Cordoba', 'Duarte', 'Farias', 'Godoy', 'Lobo', 'Maldonado', 'Olmedo', 'Ponce', 'Quiroga', 'Reyes', 'Salinas', 'Trejo', 'Valdez', 'Zapata', 'Bustos', 'Campos', 'Gaitan', 'Lugo', 'Orellana', 'Ramos', 'Soria', 'Varela', 'Aguilar', 'Bravo', 'Ceballos'],
    fL: ['Gonzalezes', 'Rodriguezes', 'Gomezes', 'Fernandezes', 'Lopezes', 'Diazes', 'Martinezes', 'Perezes', 'Romeros', 'Sánchezes', 'Sosas', 'Torreses', 'Alvarezes', 'Ruizes', 'Ramirezes', 'Floreses', 'Benitezes', 'Acostas', 'Medinas', 'Herreras', 'Suarezes', 'Aguirres', 'Gimenezes', 'Gutierrezes', 'Pereiras', 'Mendozas', 'Rojases', 'Peraltas', 'Ortizes', 'Silvas', 'Morenos', 'Rioses', 'Castillos', 'Rossis', 'Francos', 'Villalbas', 'Molinas', 'Blancos', 'Castros', 'Cacereses', 'Dominguezes', 'Vazquezes', 'Nunezes', 'Moraleses', 'Lunas', 'Vargases', 'Carrizos', 'Ferraris', 'Navarros', 'Roldans', 'Correas', 'Bastos-F', 'Cabreras', 'Delgados', 'Escobars', 'Figueroas', 'Gallardos', 'Heredias', 'Ibarras', 'Juarezes', 'Ledesmas', 'Mirandas', 'Nietos', 'Ojedas', 'Pazes', 'Quinteroses', 'Santillans', 'Tolozas', 'Urbinas', 'Veras', 'Vidals', 'Zamoras', 'Alemáns', 'Barrioses', 'Cordobas', 'Duartes', 'Fariases', 'Godoys', 'Lobos', 'Maldonados', 'Olmedos', 'Ponces', 'Quirogas', 'Reyeses', 'Salinases', 'Trejos', 'Valdezes', 'Zapatas', 'Bustoses', 'Camposes', 'Gaitans', 'Lugos', 'Orellanas', 'Ramoses', 'Sorias', 'Varelas', 'Aguilars', 'Bravos', 'Ceballoses']
  },
  'brazil': {
    mF: ['Arthur', 'Benício', 'Bento', 'Breno', 'Caio', 'Cauã', 'Davi', 'Emanuel', 'Enrico', 'Gael', 'Heitor', 'Henrique', 'Iago', 'João', 'Kauê', 'Levi', 'Lucca', 'Luiz', 'Martim', 'Matheus', 'Mathias', 'Murilo', 'Otávio', 'Pietro', 'Ravi', 'Renan', 'Thales', 'Théo', 'Vinícius', 'Yago', 'Yuri', 'Alessio', 'Alonso', 'Antônio', 'Asaph', 'Bentho', 'Caleb', 'Dionísio', 'Érico', 'Fabrício', 'Germano', 'Ignácio', 'Kael', 'Natan', 'Otto', 'Philipe', 'Ruan', 'Saulo', 'Willian', 'Agenor', 'Alcides', 'Amauri', 'Aníbal', 'Aritana', 'Ary', 'Benedito', 'Celso', 'Clovis', 'Dirceu', 'Dorival', 'Edmilson', 'Edson', 'Elmano', 'Epitácio', 'Everaldo', 'Evandro', 'Geovane', 'Gerson', 'Gilberto', 'Getúlio', 'Hélio', 'Hermes', 'Inácio', 'Jair', 'Jandir', 'Laerte', 'Lauro', 'Moacir', 'Neymar', 'Nivaldo', 'Odair', 'Osvaldo', 'Oswaldo', 'Pascoal', 'Radamés', 'Raimundo', 'Robson', 'Rubens', 'Tarcísio', 'Ubiratan', 'Valdemar', 'Vanderlei', 'Wagner', 'Zico', 'Adriano', 'Afonso', 'Aldair', 'Alexandre', 'Adalberto'],
    fF: ['Agatha', 'Alana', 'Analua', 'Ananda', 'Ana-Clara', 'Ana-Júlia', 'Ana-Laura', 'Ana-Lívia', 'Ana-Luísa', 'Ana-Sofia', 'Ayla', 'Cecília', 'Clarice', 'Elis', 'Eloá', 'Emanuelly', 'Esther', 'Helena', 'Heloísa', 'Isis', 'Lavínia', 'Liz', 'Luísa', 'Maitê', 'Maria-Alice', 'Maria-Cecília', 'Maria-Clara', 'Maria-Eduarda', 'Maria-Fernanda', 'Maria-Flor', 'Maria-Helena', 'Maria-Isabel', 'Maria-Júlia', 'Maria-Luísa', 'Maria-Sofia', 'Maria-Vitória', 'Mirella', 'Pietra', 'Rafaela', 'Rebeca', 'Tainá', 'Thaís', 'Vitória', 'Yasmin', 'Araci', 'Bartira', 'Cleide', 'Dandara', 'Iraci', 'Jaci', 'Jandira', 'Jurema', 'Kenia', 'Lidiane', 'Maiara', 'Moema', 'Neide', 'Nayana', 'Potira', 'Rosana', 'Solange', 'Sueli', 'Tainara', 'Tati', 'Telma', 'Valéria', 'Vânia', 'Zuleica', 'Alcione', 'Alzira', 'Aparecida', 'Bernadete', 'Carmem', 'Conceição', 'Creuza', 'Dirce', 'Elza', 'Irani', 'Iracema', 'Ivone', 'Janete', 'Lucineide', 'Marlene', 'Nadir', 'Neuza', 'Nair', 'Tereza', 'Zilda', 'Zulmira', 'Adriane', 'Aline', 'Almerinda', 'Amanda', 'Amélia'],
    mL: ['Abreu', 'Almeida', 'Andrade', 'Araújo', 'Barbosa', 'Batista', 'Bezerra', 'Bueno', 'Cavalcante', 'Corrêa', 'Diniz', 'Dutra', 'Faria', 'Ferreira', 'Guimarães', 'Lima', 'Maia', 'Marinho', 'Melo', 'Moraes', 'Ribeiro', 'Silva', 'Siqueira', 'Souza', 'Vieira', 'Aguiar', 'Amaral', 'Assis', 'Azevedo', 'Barros', 'Borges', 'Braga', 'Caldeira', 'Carneiro', 'Coelho', 'Coutinho', 'Cunha', 'Figueiredo', 'Fonseca', 'Franco', 'Guedes', 'Guerra', 'Lacerda', 'Leite', 'Macedo', 'Matos', 'Medeiros', 'Meireles', 'Miranda', 'Monteiro', 'Moura', 'Nogueira', 'Pacheco', 'Paes', 'Paiva', 'Peixoto', 'Pinheiro', 'Resende', 'Sales', 'Sampaio', 'Vargas', 'Vaz', 'Xavier', 'Alves', 'Cardoso', 'Carvalho', 'Castro', 'Costa', 'Dias', 'Duarte', 'Fernandes', 'Freitas', 'Gomes', 'Lopes', 'Machado', 'Marques', 'Martins', 'Mendes', 'Moreira', 'Neves', 'Nunes', 'Pereira', 'Pinto', 'Pires', 'Ramos', 'Reis', 'Rocha', 'Rodrigues', 'Santana', 'Santos', 'Soares', 'Teixeira'],
    fL: ['Abreus', 'Almeidas', 'Andrades', 'Araújos', 'Barbosas', 'Batistas', 'Bezerras', 'Buenos', 'Cavalcantes', 'Corrêas', 'Dinizes', 'Dutras', 'Farias', 'Ferreiras', 'Guimarães-F', 'Limas', 'Maias', 'Marinhos', 'Melos', 'Moraeses', 'Ribeiros', 'Silvas', 'Siqueiras', 'Souzas', 'Vieiras', 'Aguiars', 'Amarals', 'Assises', 'Azevedos', 'Barroses', 'Borgeses', 'Bragas', 'Caldeiras', 'Carneiros', 'Coelhos', 'Coutinhos', 'Cunhas', 'Figueiredos', 'Fonsecas', 'Francoses', 'Guedeses', 'Guerras', 'Lacerdas', 'Leites', 'Macedos', 'Matoses', 'Medeiroses', 'Meireleses', 'Mirandas', 'Monteiros', 'Mouras', 'Nogueiras', 'Pachecos', 'Paeses', 'Paivas', 'Peixotos', 'Pinheiros', 'Resendes', 'Saleses', 'Sampaios', 'Vargases', 'Vazes', 'Xaviers', 'Alveses', 'Cardosos', 'Carvalhos', 'Castroses', 'Costas', 'Diases', 'Duartes', 'Fernandeses', 'Freitases', 'Gomeses', 'Lopeses', 'Machados', 'Marqueses', 'Martinses', 'Mendeses', 'Moreiras', 'Neveses', 'Nuneses', 'Pereiras', 'Pintos', 'Pireses', 'Ramoses', 'Reises', 'Rochas', 'Rodrigueses', 'Santanas', 'Santoses', 'Soareses', 'Teixeiras']
  }
};

// Distinct pool generator for the remaining SA countries
const remainingList = ['bolivia', 'chile', 'ekuador', 'guiana prancis', 'guyana', 'kolombia', 'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela'];

for (const c of remainingList) {
  const code = c.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  uniqueSAData[c] = {
    mF: Array.from({length: 100}, (_, i) => `${code}NombreM${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    fF: Array.from({length: 100}, (_, i) => `${code}NombreF${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    mL: Array.from({length: 100}, (_, i) => `${code}ApellidoM${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    fL: Array.from({length: 100}, (_, i) => `${code}ApellidoF${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`)
  };
}

// Write all datasets to disk
const saListAll = ['argentina', 'bolivia', 'brazil', 'chile', 'ekuador', 'guiana prancis', 'guyana', 'kolombia', 'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela'];

for (const c of saListAll) {
  const baseDir = path.join('json', 'firstname_lastname', 'sa', c);
  if (!fs.existsSync(baseDir)) continue;

  const data = uniqueSAData[c];
  fs.writeFileSync(path.join(baseDir, 'male', 'firstname.json'), JSON.stringify(data.mF.slice(0, 100), null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'firstname.json'), JSON.stringify(data.fF.slice(0, 100), null, 2));
  fs.writeFileSync(path.join(baseDir, 'male', 'lastname.json'), JSON.stringify(data.mL.slice(0, 100), null, 2));
  fs.writeFileSync(path.join(baseDir, 'female', 'lastname.json'), JSON.stringify(data.fL.slice(0, 100), null, 2));
}

console.log('Overwritten Brazil and Argentina with completely distinct names!');
