const fs = require('fs');
const path = require('path');

const targetFixes = {
  'armenia': {
    mL: ['Abrahamyan', 'Aleksanyan', 'Antonyan', 'Arzumanyan', 'Avagyan', 'Avetisyan', 'Babayan', 'Danielyan', 'Gevorgyan', 'Gharibyan', 'Grigoryan', 'Hakobyan', 'Harutyunyan', 'Hovhannisyan', 'Khachatryan', 'Manukyan', 'Margaryan', 'Martirosyan', 'Melkonyan', 'Mkrtchyan', 'Movsisyan', 'Petrosyan', 'Poghosyan', 'Sargsyan', 'Stepanyan', 'Vardanyan', 'Amiryan', 'Azatyan', 'Boyajyan', 'Chakhoyan', 'Demirchyan', 'Egiazaryan', 'Feyzian', 'Gevorkian', 'Hambardzumyan', 'Injidjian', 'Jivanyan', 'Kasparian', 'Lalayan', 'Mamulyan', 'Nersisyan', 'Ohanian', 'Pakhanyan', 'Qocharyan', 'Rostomyan', 'Saribekyan', 'Ter-Petrosyan', 'Ulikhanyan', 'Vardevanyan', 'Yengibaryan', 'Zakharyan', 'Amaryan', 'Balyan', 'Drmeyan', 'Ginosyan', 'Hakhverdyan', 'Isahakyan', 'Janjapanian', 'Khudaverdyan', 'Lorisyan', 'Melikyan', 'Nalbandyan', 'Oganesyan', 'Pambukhchyan', 'Rashidyan', 'Sahakian', 'Tevosyan', 'Vartanian', 'Yeganyan', 'Zatikyan', 'Aghajanyan', 'Beshiryan', 'Chilingaryan', 'Davitavyan', 'Elbakyan', 'Fahradian', 'Gharagyozyan', 'Adjamian', 'Babikian', 'Chakarian', 'Der-Karapetian', 'Esayan', 'Gurian', 'Hazarapetian', 'Janikyan', 'Keshishyan', 'Merdinyan', 'Nigoghosyan', 'Ouzounian', 'Papasyan', 'Rustamyan', 'Surmeyan', 'Tashjian', 'Voskerchyan', 'Zorayan', 'Arakelyan', 'Asatryan', 'Badalyan', 'Baghdasaryan', 'Davtyan'],
    fL: ['Aharonyan', 'Arakelyan', 'Asatryan', 'Badalyan', 'Baghdasaryan', 'Davtyan', 'Gasparyan', 'Ghazaryan', 'Ghazinyan', 'Karapetyan', 'Kirakosyan', 'Minasyan', 'Mirzoyan', 'Nazaryan', 'Sahakyan', 'Shahbazyan', 'Simonyan', 'Tadevosyan', 'Tovmasyan', 'Yeghiazaryan', 'Avanesyan', 'Bostanchyan', 'Dabaghyan', 'Galstyan', 'Hovsepyan', 'Kalashyan', 'Matevosyan', 'Navasardyan', 'Papazyan', 'Saroyan', 'Tumanyan', 'Voskanian', 'Zakarian', 'Altunian', 'Berberyan', 'Chobanyan', 'Der-Petrosian', 'Enfiadjian', 'Garabedian', 'Harutunian', 'Israyelyan', 'Jamgochian', 'Kuyumjian', 'Lazarian', 'Muradyan', 'Norashkharian', 'Osepian', 'Pirumyan', 'Sarafian', 'Tarpinian', 'Vartabedian', 'Yeghiayan', 'Zohrabian', 'Aghabekyan', 'Bedrosian', 'Chilingirian', 'Dervishyan', 'Ekmekjian', 'Gharakhanian', 'Hagopian', 'Ignatosyan', 'Jololian', 'Khachaturian', 'Manougian', 'Nersessian', 'Orakian', 'Panosyan', 'Rafayelyan', 'Sahagian', 'Torosian', 'Yacoubian', 'Zalinyan', 'Aznavorian', 'Balayan', 'Cholakian', 'Dadayan', 'Evereklian', 'Gostanyan', 'Hovagimian', 'Izmirlian', 'Janoyan', 'Krikorian', 'Mardirosian', 'Nadjarian', 'Oshagan', 'Parsamyan', 'Rouzian', 'Shirinyan', 'Terzian', 'Vranian', 'Zulumyan', 'Abrahamyan', 'Aleksanyan', 'Antonyan', 'Arzumanyan', 'Avagyan', 'Avetisyan', 'Babayan', 'Danielyan', 'Gevorgyan']
  },
  'kazakhstan': {
    mL: ['Akhmetov', 'Omarov', 'Ospanov', 'Ivanov', 'Suleimenov', 'Iskakov', 'Suleimen', 'Kuznetsov', 'Popov', 'Smagulov', 'Tursynov', 'Zhaparov', 'Zhumabayev', 'Abishev', 'Amangeldi', 'Askarov', 'Bolatov', 'Ibraev', 'Kaparov', 'Kassymov', 'Kenisov', 'Kenzhebayev', 'Mahambetov', 'Nurlanov', 'Nurmagambetov', 'Rakhimov', 'Sadykov', 'Serikov', 'Talgatov', 'Yessenov', 'Yussupov', 'Zhanabayev', 'Zhubanov', 'Zhusupov', 'Abilkassimov', 'Alimbetov', 'Auezov', 'Baimbetov', 'Dosmagambetov', 'Galymzhanov', 'Ismailov', 'Karimov', 'Mamyrov', 'Nurtas', 'Oralov', 'Saparov', 'Seifullin', 'Tolegenov', 'Baizhanov', 'Dairabayev', 'Erzhanov', 'Kuanyshev', 'Mukhanov', 'Nurgaliyev', 'Satpayev', 'Abildayev', 'Bekenov', 'Daniyarov', 'Esimov', 'Gumarov', 'Ilyasov', 'Kadyrov', 'Lekerov', 'Maulenov', 'Nazarbayev', 'Otegenov', 'Rakhimbayev', 'Smailov', 'Tasmagambetov', 'Utegenov', 'Valikhanov', 'Yermekov', 'Zakiryanov', 'Abikenov', 'Buranbayev', 'Dzholdasbayev', 'Gabdullin', 'Ismagulov', 'Kopbayev', 'Mamytov', 'Nurzhanov', 'Oralbayev', 'Ryskulov', 'Seitov', 'Tokayev', 'Umirzakov', 'Zhenisov', 'Aimaganbetov', 'Baishev', 'Daurenov', 'Kasenov', 'Musabayev', 'Nurkasymov', 'Orazov', 'Rustemov', 'Syzdykov', 'Tulebayev', 'Zhumagulov', 'Baitursynov'],
    fL: ['Akhmetova', 'Omarova', 'Ospanova', 'Ivanova', 'Suleimenova', 'Iskakova', 'Kuznetsova', 'Popova', 'Smagulova', 'Tursynova', 'Zhaparova', 'Zhumabayeva', 'Abisheva', 'Askarova', 'Bolatova', 'Ibraeva', 'Kaparova', 'Kassymova', 'Kenisova', 'Kenzhebayeva', 'Mahambetova', 'Nurlanova', 'Nurmagambetova', 'Rakhimova', 'Sadykova', 'Serikova', 'Talgatova', 'Yessenova', 'Yussupova', 'Zhanabayeva', 'Zhubanova', 'Zhusupova', 'Abilkassimova', 'Alimbetova', 'Auezova', 'Baimbetova', 'Dosmagambetova', 'Galymzhanova', 'Ismailova', 'Karimova', 'Mamyrova', 'Nurtasova', 'Oralova', 'Saparova', 'Seifullina', 'Tolegenova', 'Baizhanova', 'Dairabayeva', 'Erzhanova', 'Kuanysheva', 'Mukhanova', 'Nurgaliyeva', 'Satpayeva', 'Abildayeva', 'Bekenova', 'Daniyarova', 'Esimova', 'Gumarova', 'Ilyasova', 'Kadyrova', 'Lekerova', 'Maulenova', 'Nazarbayeva', 'Otegenova', 'Rakhimbayeva', 'Smailova', 'Tasmagambetova', 'Utegenova', 'Valikhanova', 'Yermekova', 'Zakiryanova', 'Abikenova', 'Buranbayeva', 'Dzholdasbayeva', 'Gabdullina', 'Ismagulova', 'Kopbayeva', 'Mamytova', 'Nurzhanova', 'Oralbayeva', 'Ryskulova', 'Seitova', 'Tokayeva', 'Umirzakova', 'Zhenisova', 'Aimaganbetova', 'Baisheva', 'Daurenova', 'Kasenova', 'Musabayeva', 'Nurkasymova', 'Orazova', 'Rustemova', 'Syzdykova', 'Tulebayeva', 'Zhumagulova', 'Baitursynova']
  }
};

for (const country in targetFixes) {
  const baseDir = path.join('json', 'firstname_lastname', 'asia', country);
  const mLPath = path.join(baseDir, 'male', 'lastname.json');
  const fLPath = path.join(baseDir, 'female', 'lastname.json');

  const mL = Array.from(new Set(targetFixes[country].mL)).slice(0, 100);
  const fL = Array.from(new Set(targetFixes[country].fL)).slice(0, 100);

  fs.writeFileSync(mLPath, JSON.stringify(mL, null, 2));
  fs.writeFileSync(fLPath, JSON.stringify(fL, null, 2));
}

console.log('Finished Armenia and Kazakhstan precision fixes!');
