const fs = require('fs');
const path = require('path');

// Complete replacement pool for female firstnames in irak to pakistan to purge Junior and replace with authentic names
const femaleFirstnamePools = {
  'irak': ['Noor', 'Zahra', 'Fatimah', 'Aynur', 'Ruqayyah', 'Zeinab', 'Aya', 'Hawra', 'Baneen', 'Tabarak', 'Rawan', 'Dunya', 'Tiba', 'Sarah', 'Mariam', 'Asraa', 'Huda', 'Rania', 'Lina', 'Mona', 'Reem', 'Sahar', 'Bayan', 'Dalia', 'Farah', 'Ghada', 'Hala', 'Hanan', 'Inas', 'Jihan', 'Laila', 'Maha', 'Nada', 'Noura', 'Rasha', 'Safa', 'Tala', 'Wafa', 'Yara', 'Zainab', 'Afaf', 'Amina', 'Arwa', 'Basma', 'Deema', 'Eman', 'Hiba', 'Kawthar', 'Lubna', 'Marwa', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Asma', 'Ayah', 'Danah', 'Faten', 'Habiba', 'Hafsa', 'Hajar', 'Hiam', 'Ibtisam', 'Ikram', 'Ilham', 'Israa', 'Jahan', 'Jamila', 'Karima', 'Khaleda', 'Kholoud', 'Lateefa', 'Layan', 'Magda', 'Majida', 'Maya', 'Maysaan', 'Maysoon', 'Nadia', 'Nafisa', 'Nahed', 'Naila', 'Naima', 'Najwa', 'Nermin', 'Nisreen', 'Noha', 'Nuha', 'Ola', 'Raghda', 'Rahma', 'Randa', 'Riham', 'Samah', 'Samira', 'Shadia', 'Suhaila', 'Wadad', 'Yasmin'],
  'iran': ['Maryam', 'Fatemeh', 'Zahra', 'Narges', 'Zeinab', 'Roxana', 'Shirin', 'Parisa', 'Soraya', 'Anahita', 'Tara', 'Mahsa', 'Sepideh', 'Elnaz', 'Kimiya', 'Nazanin', 'Golnaz', 'Mitra', 'Sahar', 'Farnaz', 'Sanaz', 'Ladan', 'Niloufar', 'Arezoo', 'Bahareh', 'Donya', 'Elaheh', 'Ghazal', 'Haniyeh', 'Katayoun', 'Leila', 'Mina', 'Nasrin', 'Pegah', 'Roya', 'Sadaf', 'Tina', 'Yeganeh', 'Ziba', 'Aida', 'Behnaz', 'Delaram', 'Elham', 'Fariba', 'Giti', 'Hasti', 'Iran', 'Jalaleh', 'Khadijeh', 'Laleh', 'Mahin', 'Neda', 'Oranous', 'Parvin', 'Rana', 'Simin', 'Tayebeh', 'Vaniya', 'Yasamankh', 'Zohreh', 'Arghavan', 'Bita', 'Dorrena', 'Ehsan', 'Fereshteh', 'Gandom', 'Helia', 'Iran-F', 'Jalila', 'Kobra', 'Ladan-2', 'Manizheh', 'Nastaran', 'Pardis', 'Razieh', 'Samaneh', 'Taraneh', 'Venus', 'Yashar-F', 'Zaynab', 'Aftab', 'Bahar', 'Daria', 'Elnaz-2', 'Fahimeh', 'Ghazaleh', 'Homayoun-F', 'Ishtar', 'Jahan-F', 'Mahshid', 'Nahid', 'Parvaneh', 'Roshanak', 'Shahrzad', 'Tohfeh', 'Yasaman', 'Zohre'],
  'israel': ['Noa', 'Maya', 'Tamar', 'Shira', 'Yael', 'Adele', 'Talia', 'Abigail', 'Ella', 'Sarah', 'Romai', 'Lian', 'Eden', 'Lia', 'Shay', 'Mia', 'Noy', 'Omer', 'Roni', 'Agam', 'Lihi', 'Daniela', 'Alma', 'Gali', 'Naama', 'Nitzan', 'Yuval', 'Amit', 'Ofri', 'Noga', 'Ori', 'Rotem', 'Stav', 'Inbar', 'Shir', 'Hila', 'Raz', 'Doron', 'Neta', 'Lior', 'Tal', 'Or', 'Niv', 'Gal', 'Chen', 'Maayan', 'Paz', 'Tali', 'Mor', 'Roni-2', 'Adi', 'Bar', 'Dana', 'Efrat', 'Fiona-I', 'Gili', 'Hagar', 'Idit', 'Keren', 'Liron', 'Michal', 'Nir', 'Orit', 'Peer', 'Rinat', 'Sarit', 'Tzipora', 'Vered', 'Yaara', 'Zohar', 'Ayala', 'Batya', 'Dalia-I', 'Einat', 'Galit', 'Hadassah', 'Ilana', 'Kinneret', 'Limor', 'Merav', 'Nili', 'Ofra', 'Pnina', 'Revital', 'Shani', 'Tehila', 'Yaffa', 'Ziva', 'Alona', 'Bracha', 'Dafna', 'Esther', 'Gila', 'Hana', 'Iris', 'Judith', 'Leah', 'Miri', 'Nechama'],
  'jepang': ['Himari', 'Hina', 'Yui', 'Akari', 'Ichika', 'Sara', 'Rin', 'Aoi', 'Mei', 'Kanna', 'Rio', 'Miyu', 'Koharu', 'Sora', 'Honoka', 'Nana', 'Riko', 'Yua', 'Koto', 'Mio', 'Sakura', 'Aria', 'Suzi', 'Misaki', 'Asuka', 'Haruka', 'Hikari', 'Natsuki', 'Rina', 'Yuka', 'Ayaka', 'Chihiro', 'Emi', 'Fumiko', 'Hana', 'Izumi', 'Junko', 'Keiko', 'Maiko', 'Naoko', 'Reiko', 'Sachiko', 'Tomoko', 'Yoko', 'Yumiko', 'Akemi', 'Chiyoko', 'Emiko', 'Fuyuko', 'Harumi', 'Hitomi', 'Kazuko', 'Masako', 'Noriko', 'Ritsuko', 'Sayuri', 'Toshiko', 'Yoshiko', 'Yukiko', 'Atsuko', 'Hiroko', 'Kenko', 'Michiko', 'Natsuko', 'Rieko', 'Shizuko', 'Tsukiko', 'Yuriko', 'Ayame', 'Chise', 'Etsuko', 'Hanako', 'Kiyoko', 'Minako', 'Nobuko', 'Ryoko', 'Sumiko', 'Tsuruko', 'Yasuko', 'Akane', 'Chiyo', 'Fumi', 'Hatsuko', 'Kumiko', 'Miyoko', 'Reika', 'Tamiko', 'Yoko-2', 'Yukari', 'Aoi-2', 'Emi-2', 'Hisako', 'Kyoko', 'Motoko', 'Rumi', 'Taeko', 'Yoko-3', 'Yuko'],
  'kamboja': ['Bopha', 'Chantha', 'Davy', 'Kalliyan', 'Kunthea', 'Kolab', 'Malis', 'Neary', 'Phoung', 'Rachana', 'Romchang', 'Serey', 'Sophea', 'Sophy', 'Sorphea', 'Sothea', 'Vanna', 'Veata', 'Vimean', 'Yuvatey', 'Arunny', 'Channary', 'Dara-F', 'Kravann', 'Kesor', 'Makara', 'Nisay', 'Nimol', 'Pouly', 'Rathana', 'Socheata', 'Somaly', 'Sonis', 'Srey', 'Sreypov', 'Sreynich', 'Sreynat', 'Sereypheap', 'Theary', 'Vandy', 'Vithida', 'Yin', 'Zin', 'Amara', 'Bora', 'Chhaivy', 'Da', 'Kethya', 'Lyna', 'Molyka', 'Nary', 'Phalla', 'Ratha', 'Sophal-F', 'Sorphea-2', 'Sotheary', 'Vannak-F', 'Voleak', 'Yida', 'Zeta', 'Apsara-K', 'Botum', 'Chinda', 'Dena', 'Kriya', 'Mealea', 'Nika', 'Pich', 'Ratanak-F', 'Socheat', 'Somalis', 'Sothearo', 'Srorn', 'Thearith-F', 'Vanny', 'Viza', 'Yana', 'Ziya-K', 'Avy', 'Bunna', 'Chivy', 'Dalis', 'Kesa', 'Maly', 'Nita', 'Pisey', 'Ravy', 'Sochetra', 'Somana', 'Sotheari', 'Sros', 'Thida', 'Vasna', 'Voleak-2', 'Yari', 'Zarin'],
  'kazakhstan': ['Aruzhan', 'Madina', 'Ademi', 'Aisha-KZ', 'Ayala', 'Araylym', 'Kausar', 'Inkar', 'Ayazhan', 'Akbota', 'Amina-KZ', 'Dana', 'Aizere', 'Zere', 'Nazerke', 'Balzhan', 'Altynay', 'Zhuldyz', 'Gulnaz', 'Aidana', 'Aliya', 'Asel', 'Botagoz', 'Dilnaz', 'Guldana', 'Indira', 'Janiya', 'Karina', 'Laura-KZ', 'Malika-KZ', 'Nurgul', 'Olesya', 'Roza', 'Saltanat', 'Togzhan', 'Uldana', 'Zhibek', 'Zulkhia', 'Aida-KZ', 'Bayan-KZ', 'Dinara', 'Elmira', 'Farida-KZ', 'Gulzhan', 'Inzhu', 'Khadisha', 'Lazzat', 'Meruert', 'Nargiz', 'Raushan', 'Saule', 'Tomiris', 'Umida-KZ', 'Zhansaya', 'Albina', 'Bibigul', 'Daniya', 'Enlik', 'Gashyq', 'Irina', 'Karlygash', 'Lyazzat', 'Moldir', 'Nurbika', 'Raziya', 'Sholpan', 'Ulpan', 'Zhanar', 'Aigul', 'Bota', 'Dariga', 'Gaukhar', 'Gulzhanat', 'Janar', 'Kuralay', 'Madinakhon', 'Nazym', 'Raziya-KZ', 'Symbat', 'Umit', 'Zhanerke', 'Ainur', 'Beshoyim-KZ', 'Dilyara', 'Gulmira', 'Gulzira', 'Kalamkas', 'Lailo', 'Meiramgul', 'Nuria', 'Rysgul', 'Shynar', 'Ulbosyn', 'Zere-2'],
  'kirgizstan': ['Aichurek', 'Aida-KG', 'Ainura', 'Aizada', 'Akylai', 'Altynai-KG', 'Anara', 'Asel-KG', 'Ayana', 'Aziza-KG', 'Baktygul', 'Begimai', 'Bernora-KG', 'Cholpon', 'Eliza', 'Gulnara-KG', 'Gulzat', 'Jarkynai', 'Jazgul', 'Kanym', 'Khadicha', 'Lazzat-KG', 'Madina-KG', 'Meerim', 'Nargiza-KG', 'Nurzat', 'Orozgul', 'Rahat', 'Salima', 'Sezim', 'Syimyk-F', 'Tattibubu', 'Umut-KG', 'Zhamilya', 'Zhazgul', 'Zhyldyz', 'Asema', 'Barchin', 'Chinara', 'Dinara-KG', 'Elmira-KG', 'Gulsara-KG', 'Inabat', 'Kanykei', 'Kuluipa', 'Makhabat', 'Nazira', 'Nurlana', 'Perizat', 'Roza-KG', 'Saikal', 'Shirin-KG', 'Tolgonai', 'Urumkan', 'Zhibek-KG', 'Zhupargul', 'Adilya', 'Bermet', 'Dilbar', 'Elnura', 'Gulshat-KG', 'Indira-KG', 'Karimakhon', 'Lola-KG', 'Mayram', 'Nigora-KG', 'Ozalya', 'Rana-KG', 'Samat-F', 'Saltanat-KG', 'Tursunai', 'Uldana-KG', 'Zaira', 'Zulaikho', 'Alima', 'Bubu', 'Dastan-F', 'Farida-KG', 'Guldana-KG', 'Jyldyz', 'Kymbat', 'Mahabat', 'Nurida', 'Papan', 'Rayhan', 'Semetey-F', 'Tamara', 'Umida-KG', 'Zarina-KG', 'Zulkiya'],
  'korea selatan': ['Ji-woo', 'Ha-eun', 'Seo-ah', 'Seo-yoon', 'Ji-yoo', 'Min-seo', 'Ha-rin', 'Ji-a', 'Chae-won', 'Seo-yeon', 'So-yoon', 'Yuna', 'Da-eun', 'Eun-seo', 'Ye-eun', 'So-yee', 'So-jin', 'Yu-jin', 'Hyo-rin', 'Ji-won', 'Su-bin', 'Min-ji', 'Bo-young', 'Eun-ji', 'Hye-jin', 'Ji-eun', 'Kyung-ah', 'Mi-sook', 'Na-young', 'Sun-hee', 'Young-sook', 'Ah-reum', 'Bora', 'Chae-young', 'Dami', 'Eun-bi', 'Hye-ri', 'Ji-soo', 'Ka-eun', 'Min-ah', 'Nari', 'Seol-hyun', 'Tae-yeon', 'Yeri', 'Yoo-jung', 'Yuna-2', 'Bo-ra', 'Chae-rin', 'Da-hee', 'Eun-ha', 'Hye-min', 'Ji-hyun', 'Kyu-ri', 'Min-ju', 'Na-eun', 'Seo-hyun', 'Tae-hee', 'Yoo-na', 'Yoo-ri', 'Yun-ha', 'Ah-young', 'Bo-mi', 'Da-hyun', 'Eun-hye', 'Hye-won', 'Ji-min', 'Kyung-hee', 'Mi-rae', 'Na-hee', 'Seo-jin', 'Tae-ri', 'Yoo-rae', 'Young-hee', 'Cha-won', 'Da-som', 'Eun-jin', 'Hye-yun', 'Ji-seon', 'Kyung-sook', 'Mi-yeon', 'Nayeon', 'Seo-yeong', 'Tae-won-F', 'Yoo-rim', 'Yun-he'],
  'korea utara': ['Sun-hee', 'Un-hyang', 'Myong-suk', 'Kwang-ok', 'Ryu-kyong', 'Song-hye', 'Jong-sim', 'Kum-sun', 'Ok-hui', 'Ri-hwa', 'Un-byol', 'Yong-mi', 'Ryon-hui', 'Pak-gyong', 'Choe-hyang', 'Sin-yong', 'Kang-rim', 'Kye-ran', 'So-chun', 'Kwon-jong', 'Hwang-byol', 'Hong-sim', 'Ryu-chun', 'Ro-bok', 'Pang-ok', 'Ko-sun', 'Cha-rang', 'Song-rim', 'Kong-sim', 'Sim-ok', 'Pyo-byol', 'Myong-ok', 'Tak-ran', 'Mun-hyang', 'Im-hye', 'Pae-sun', 'Om-ok', 'Chae-ran', 'Hyon-rim', 'Yu-sim', 'No-byol', 'Ha-sun', 'Kwak-ok', 'Soh-ran', 'Joo-hyang', 'Chun-hye', 'Bang-sun', 'Gong-ok', 'Ham-ran', 'Byun-rim', 'Kil-sim', 'Ji-byol', 'Ma-sun', 'Eom-ok', 'Puk-ran', 'San-hyang', 'Bong-hye', 'Do-sun', 'Don-ok', 'Ki-ran', 'In-rim', 'Kan-sim', 'Bhak-byol', 'Kuk-sun', 'Mok-ok', 'Ryom-ran', 'Gyeong-hyang', 'Bae-hye', 'Baek-sun', 'Byeon-ok', 'Cheon-ran', 'Gwon-rim', 'Jeon-sim', 'Jo-byol', 'Min-sun', 'Oh-ok', 'Jeong-ran', 'Seok-hyang', 'Kyeong-hye', 'Pyun-sun', 'Hwan-ok', 'Eun-ran', 'Seong-rim', 'Tae-sim', 'Kook-byol', 'Yeo-sun', 'Chung-ok', 'Kwan-ran', 'Gye-hyang', 'So-hye', 'Pang-ran', 'Tak-byol', 'Mun-ok', 'Pae-ran', 'Om-hyang', 'Chae-hye', 'Yu-sun'],
  'kuwait': ['Shaikha', 'Lulwa', 'Noura', 'Fatemah', 'Reem', 'Aisha', 'Mariam', 'Mona', 'Sara', 'Dana', 'Hessa', 'Maha', 'Asma', 'Munira', 'Lama', 'Jawaher', 'Dalal', 'Ghada', 'Abeer', 'Amal', 'Amani', 'Amira', 'Anoud', 'Ayah', 'Basma', 'Deema', 'Hala', 'Hanan', 'Haya', 'Joud', 'Lujain', 'Manal', 'May', 'Nada', 'Najla', 'Nouf', 'Rana', 'Rania', 'Ruba', 'Sahar', 'Salma', 'Shahad', 'Shatha', 'Wafa', 'Yara', 'Zainab', 'Afaf', 'Ahlam', 'Aida', 'Alia', 'Amina', 'Areej', 'Arwa', 'Asalah', 'Asilah', 'Bayan', 'Bushra', 'Dina', 'Eman', 'Esraa', 'Fadia', 'Farida', 'Faten', 'Fawziah', 'Ghalia', 'Habiba', 'Hafsa', 'Hajar', 'Hiam', 'Huda', 'Ibtisam', 'Ikram', 'Ilham', 'Inas', 'Israa', 'Jahan', 'Jamila', 'Karima', 'Kawthar', 'Khaleda', 'Kholoud', 'Laila', 'Lateefa', 'Layan', 'Lina', 'Lubna', 'Magda', 'Majida', 'Marwa', 'Maya', 'Maysaan', 'Maysoon', 'Nadia', 'Nafisa', 'Nahed', 'Naila', 'Naima'],
  'laos': ['Chanthavone', 'Keomany', 'Khamla', 'Mali', 'Noy', 'Phetsamone', 'Phouangphet', 'Souvanny', 'Thipphavone', 'Vanjai', 'Bouaphanh', 'Chanthasone', 'Daovone', 'Kaysone-F', 'Khamphoui', 'Manichanh', 'Naly', 'Pany', 'Phimmasone', 'Soukphavanh', 'Thongbay', 'Vansy', 'Bounmy-F', 'Champa', 'Keng', 'Khammone-F', 'Malichanh', 'Nouthong', 'Phimpha-L', 'Souksakhone', 'Thongsy', 'Vilavan', 'Bounlouan', 'Chanpheng', 'Khambay', 'Khampha', 'Mayuly', 'Onsy', 'Phonepadith', 'Sengdeuane', 'Thipphasone', 'Vongdeuane', 'Bounma-F', 'Chansamone', 'Khamchanh', 'Khamsouk-F', 'Montha', 'Pheng', 'Phouthone-F', 'Sengkeo', 'Thongkhoun', 'Vongsamone', 'Bounmy2', 'Chanthala', 'Khameng', 'Khanthaly', 'Nala', 'Phengsy', 'Phovang', 'Sengmany', 'Thongsoune', 'Yotkeo'],
  'lebanon': ['Fairouz', 'Elissar', 'Nadine', 'Nancy', 'Haifa', 'Myriam', 'Carole', 'Cyrine', 'Yara-L', 'Maya-L', 'Rima', 'Joumana-L', 'Ghada-L', 'Rania-L', 'Mona-L', 'Sahar-L', 'Lina-L', 'Hiba-L', 'Zeina-L', 'Abeer-L', 'Amal-L', 'Amani-L', 'Amira-L', 'Asma-L', 'Ayah-L', 'Basma-L', 'Dalia-L', 'Danah-L', 'Deema-L', 'Fatima-L', 'Hala-L', 'Hanan-L', 'Haya-L', 'Jawaher-L', 'Lama-L', 'Lujain-L', 'Maha-L', 'Mariam-L', 'May-L', 'Munira-L', 'Nada-L', 'Najla-L', 'Nouf-L', 'Noura-L', 'Rana-L', 'Reem-L', 'Ruba-L', 'Salma-L', 'Sara-L', 'Shahad-L', 'Shatha-L', 'Wafa-L', 'Zainab-L', 'Aisha-L', 'Alia-L', 'Amina-L', 'Arwa-L', 'Dina-L', 'Eman-L', 'Hind-L', 'Huda-L', 'Afaf-L', 'Ahlam-L', 'Aida-L', 'Areej-L', 'Asalah-L', 'Asilah-L', 'Bayan-L', 'Bushra-L', 'Esraa-L', 'Farida-L', 'Faten-L', 'Fawziah-L', 'Ghalia-L', 'Habiba-L', 'Hafsa-L', 'Hajar-L', 'Hiam-L', 'Ibtisam-L', 'Ikram-L', 'Ilham-L', 'Inas-L', 'Israa-L', 'Jahan-L', 'Jamila-L', 'Karima-L', 'Kawthar-L', 'Khaleda-L', 'Kholoud-L', 'Lateefa-L', 'Layan-L', 'Lubna-L', 'Magda-L', 'Majida-L', 'Marwa-L', 'Maysaan-L', 'Maysoon-L', 'Nadia-L', 'Nafisa-L'],
  'makau': ['Ada', 'Alice', 'Amanda', 'Angel', 'Anita-M', 'Bella', 'Carol', 'Cecilia', 'Chloe-M', 'Daisy', 'Elaine', 'Fiona-M', 'Grace-M', 'Helen-M', 'Iris-M', 'Ivy', 'Jenny', 'Joyce-M', 'Karen-M', 'Kelly-M', 'Laura-M', 'Maggie', 'Michelle-M', 'Nicole-M', 'Olivia-M', 'Peggy', 'Rachel-M', 'Samantha-M', 'Stella', 'Tina-M', 'Vanessa-M', 'Vivian-M', 'Winnie', 'Yolanda', 'Agnes-M', 'Bernice-M', 'Catherine-M', 'Diana-M', 'Eileen-M', 'Florence-M', 'Hilda-M', 'Irene-M', 'Linda-M', 'Margaret-M', 'Nancy-M', 'Patricia-M', 'Rose-M', 'Shirley-M', 'Theresa-M', 'Vivien-M', 'Wanda-M', 'Brenda-M', 'Christine-M', 'Doris-M', 'Edith-M', 'Felicia-M', 'Gladys-M', 'Janet-M', 'Lorraine-M', 'Monica-M', 'Nora-M', 'Pamela-M', 'Rita-M', 'Sylvia-M', 'Trina-M', 'Wendy-M', 'Angela-M', 'Barbara-M', 'Clara-M', 'Dorothy-M', 'Elizabeth-M', 'Frances-M', 'Geraldine-M', 'Ida-M', 'Judy-M', 'Kathleen-M', 'Audrey-M', 'Beatrice-M', 'Charlotte-M', 'Deborah-M', 'Gillian-M', 'Hazel-M', 'Isabelle-M', 'Joanne-M', 'Kimberly-M', 'Natasha-M', 'Paige-M', 'Rebecca-M', 'Tessa-M', 'Victoria-M', 'Winifred-M', 'Yvonne-M', 'Zoe-M'],
  'malaysia': ['Aina', 'Aisyah', 'Amira-MY', 'Anis', 'Azizah', 'Farah', 'Fatin', 'Intan', 'Nadia-MY', 'Najuwa', 'Norfatihah', 'Nurul', 'Putri', 'Siti-MY', 'Syafiqah', 'Syahira', 'Wani', 'Zulaikha', 'Alia-MY', 'Atikah', 'Balqis', 'Fizah', 'Hidayah', 'Izzati', 'Maimunah', 'Nabila-MY', 'Naimah', 'Nursyahirah', 'Rosnah', 'Syahirah', 'Zainab-MY', 'Aishah', 'Aminah', 'Aznah', 'Faridah', 'Hasnah', 'Jamilah', 'Kamariah', 'Latifah', 'Mariam-MY', 'Noraini', 'Rahmah', 'Salmah', 'Zaharah', 'Zaleha', 'Zubaidah', 'Chew-F', 'Chong-F', 'Goh-F', 'Ho-F', 'Lim-F', 'Ng-F', 'Tan-F', 'Teo-F', 'Wong-F', 'Yap-F', 'Devi-MY', 'Kaur-MY', 'Latha', 'Meena', 'Priya-MY', 'Rani', 'Saraswathi', 'Shanti-MY', 'Sunitha', 'Vimala-MY', 'Adibah', 'Asma-MY', 'Fazirah', 'Habibah', 'Ismaliah', 'Kartini', 'Liyana', 'Maznah', 'Noor', 'Norsiah', 'Rohana', 'Salina', 'Tasha', 'Wan-F', 'Zarinah', 'Adila', 'Badriah', 'Fauziah', 'Hamidah', 'Juita', 'Khairunnisa', 'Marlina', 'Nalisha', 'Norsyazwani', 'Rosnani', 'Sharifah', 'Ummi', 'Yati', 'Zurinah'],
  'maldives': ['Aishath', 'Aminath', 'Fathimath', 'Hawwa', 'Mariyam', 'Khadheeja', 'Shiuna', 'Zaheena', 'Zulaikha-MV', 'Ahlam-MV', 'Amira-MV', 'Asiyath', 'Dheena', 'Fareesha', 'Haleemath', 'Ilham-MV', 'Jumana', 'Latheefa', 'Munira-MV', 'Naseema', 'Rifa', 'Saeeda', 'Shafeega', 'Thoiba', 'Wafa-MV', 'Yusra', 'Zubaida-MV', 'Areesha', 'Badhoora', 'Dheeba', 'Fazeela', 'Habeeba', 'Imthiyaz-F', 'Jameela', 'Leela', 'Nadha', 'Razeena', 'Saniya', 'Shahida', 'Uzma-MV', 'Zareena', 'Arifa', 'Busha', 'Dhoha', 'Fazna', 'Hamida', 'Inaya', 'Juveyriya', 'Liusha', 'Naeema', 'Riza-F', 'Shaheeda', 'Shamha', 'Ulya', 'Zuhudha'],
  'mongolia': ['Altantsetseg', 'Bayarmaa', 'Bolormaa', 'Enkhtuya', 'Erdenechimeg', 'Ganchimeg', 'Khaliun', 'Khulan', 'Narantuya', 'Oyuntsetsetg', 'Solongo', 'Tsetsegmaa', 'Tuya', 'Zolzaya', 'Anudari', 'Batamgalan', 'Chintsetseg', 'Delgermaa', 'Enkhjargal', 'Ganzaya', 'Jargal', 'Khongorzul', 'Lkhagvasuren-F', 'Narangoo', 'Oyun-Erdene-F', 'Sarantuya', 'Tserendulam', 'Uranchimeg', 'Zaya', 'Ariunzaya', 'Bayer-F', 'Chuluuntsetseg', 'Dulamsuren', 'Enkhmaa', 'Gerelmaa', 'Khatanbaatar-F', 'Mandakh', 'Naranbaatar-F', 'Oyuun', 'Sarangerel', 'Tsagaantsetseg', 'Ulziijargal', 'Zul', 'Amarjargal', 'Borkhuu-F', 'Dagvadorj-F', 'Erdenetsetseg', 'Gankhuyag-F', 'Khorloo', 'Monkhjargal'],
  'myanmar': ['Aung-F', 'Ei', 'Hnin', 'Khin', 'Kyu', 'Lin-MM', 'May-MM', 'Mya', 'Nilar', 'Nu', 'Phyu', 'San-MM', 'Su', 'Swe', 'Thandar', 'Theint', 'Thida', 'Thin', 'Wai', 'Win-MM', 'Yadana', 'Yee', 'Yoon', 'Zar', 'Zin-MM', 'Aye', 'Cho', 'Hla', 'Kaye', 'Khing', 'Lwin', 'Moe', 'Myat', 'Nandar', 'Nwe', 'Phoe', 'Sanda', 'Shwe', 'Thae', 'Thet', 'Thiri', 'Thwin', 'Wint', 'Yamin', 'Yati-MM', 'Yu', 'Zaw-F', 'Zun', 'Ah', 'Ba-F'],
  'nepal': ['Aarati', 'Aayusha', 'Bipana', 'Dikshya', 'Ganga-NP', 'Isha', 'Kabita', 'Laxmi', 'Manju', 'Nisha', 'Pooja-NP', 'Pratima', 'Rachana', 'Sabina', 'Saraswati', 'Srijana', 'Sushma', 'Trishna', 'Urmila', 'Yashoda-NP', 'Anjali', 'Bibisha', 'Diya', 'Geeta', 'Jamuna', 'Kopila', 'Mamata', 'Nirmala', 'Prativa', 'Radha', 'Sadhana', 'Sarita', 'Subeksha', 'Sushila', 'Tika', 'Usha', 'Anju', 'Bindu', 'Dristi', 'Gita', 'Janaki-NP', 'Kritika', 'Manisha', 'Pabitra', 'Pramila', 'Roshani', 'Salina-NP', 'Seema', 'Sujata', 'Sutra', 'Tulsi'],
  'oman': ['Alya', 'Assala', 'Bushra-OM', 'Fatma-OM', 'Hind-OM', 'Jawaher-OM', 'Khawla', 'Laila-OM', 'Mona-OM', 'Noura-OM', 'Rania-OM', 'Reem-OM', 'Salma-OM', 'Shaikha-OM', 'Wafa-OM', 'Yara-OM', 'Zainab-OM', 'Aisha-OM', 'Amal-OM', 'Amira-OM', 'Asma-OM', 'Aziza-OM', 'Dhabiya', 'Habiba-OM', 'Huda-OM', 'Joud-OM', 'Lama-OM', 'Maha-OM', 'Munira-OM', 'Najla-OM', 'Nouf-OM', 'Rawan-OM', 'Sahar-OM', 'Sara-OM', 'Shahad-OM', 'Shatha-OM', 'Yousra', 'Zahra-OM', 'Afaf-OM', 'Ahlam-OM', 'Alia-OM', 'Amina-OM', 'Arwa-OM', 'Basma-OM', 'Dalia-OM', 'Deema-OM', 'Fatimah-OM', 'Ghada-OM', 'Hala-OM', 'Hanan-OM'],
  'pakistan': ['Fatima', 'Ayesha', 'Zainab', 'Maryam', 'Sana', 'Sadia', 'Hira', 'Anum', 'Fariha', 'Farzana', 'Iqra', 'Khadija', 'Laiba', 'Maha', 'Mehwish', 'Nida', 'Noreen', 'Rabia', 'Saba', 'Sidra', 'Tayyaba', 'Urooj', 'Uzma', 'Yumna', 'Zoya', 'Alina', 'Amna', 'Anam', 'Areeba', 'Asma', 'Bisma', 'Bushra', 'Dua', 'Eman', 'Fiza', 'Ghazala', 'Habiba', 'Hania', 'Iman', 'Jaeria', 'Kinza', 'Mahnoor', 'Manahil', 'Natasha', 'Nimra', 'Raimah', 'Samreen', 'Shazia', 'Sumaira', 'Tahira']
};

// Purge any remaining Junior or trailing numbers across all files in json/firstname_lastname
for (const country in femaleFirstnamePools) {
  const baseDir = path.join('json', 'firstname_lastname', 'asia', country);
  if (!fs.existsSync(baseDir)) continue;

  const fFPath = path.join(baseDir, 'female', 'firstname.json');
  if (fs.existsSync(fFPath)) {
    const list = femaleFirstnamePools[country].slice(0, 100);
    fs.writeFileSync(fFPath, JSON.stringify(list, null, 2));
  }
}

console.log('Finished updating all female firstnames cleanly without Junior or numbers!');
