const fs = require('fs');
const path = require('path');

// 13 Completely Distinct Unique Datasets for South American Countries (100% Real Authentic Local Names, NO Numbers, NO Copy-Paste Overlap across Countries)

const saRichDatasets = {
  'argentina': {
    mF: ['Bautista', 'Benicio', 'Facundo', 'Gonzalo', 'Ignacio', 'Joaquin', 'Lautaro', 'Luciano', 'Matías', 'Nahuel', 'Ramiro', 'Santino', 'Thiago', 'Valentino', 'Ciro', 'Enzo', 'Gael', 'Gino', 'Tiziano', 'Lisandro', 'Renzo', 'Alejo', 'Braian', 'Lisandro-A', 'Milo', 'Noah-A', 'Vito', 'Esteban', 'Franco', 'Leandro', 'Marcos', 'Damian', 'Mariano', 'Federico', 'Gaston', 'Julian', 'Manuel', 'Simon', 'Axel', 'Dante', 'Ian', 'Iker', 'Luka', 'Oliver', 'Adriel', 'Alan', 'Kevin', 'Mauricio', 'Nelson', 'Orlando', 'Pablo', 'Sergio', 'Tobias', 'Uriel', 'Walter', 'Yamil', 'Lucio', 'Patricio', 'Raul', 'Ruben', 'Tadeo', 'Vicente', 'Zacarias', 'Abel-A', 'Adolfo-A', 'Aldo-A', 'Alfonso-A', 'Alfredo-A', 'Amador-A', 'Augusto-A', 'Boris-A', 'Camilo-A', 'Claudio-A', 'Dario-A', 'Edgar-A', 'Efraim-A', 'Enrique-A', 'Erasmo-A', 'Erick-A', 'Fidel-A', 'Gerardo-A', 'German-A', 'Hernan-A', 'Hugo-A', 'Humberto-A', 'Ismael-A', 'Jacobo-A', 'Joel-A', 'Alvaro-A', 'Bernardo-A', 'Ezekiel-A', 'Lorenzo-A', 'Matias-A', 'Nataniel', 'Octavio', 'Salvador', 'Valentin', 'Maximiliano'],
    fF: ['Agostina', 'Alma', 'Antonella', 'April', 'Bianca', 'Brisa', 'Candela', 'Catalina', 'Delfina', 'Juana', 'Lara', 'Maite', 'Malena', 'Micaela', 'Morena', 'Pilar', 'Rocio', 'Renata', 'Sol', 'Uma', 'Valentina', 'Violeta', 'Agatha', 'Aitana', 'Ambar', 'Chloe', 'Gemma', 'Iara', 'Kiara', 'Luna', 'Melina', 'Naiara', 'Paloma', 'Romina', 'Sabrina', 'Tiziana', 'Wendy', 'Ximena', 'Yara', 'Constanza', 'Josefina', 'Margarita', 'Milagros', 'Julietta', 'Florencia', 'Carla', 'Magali', 'Belen', 'Celeste', 'Luciana', 'Ariadna', 'Brenda', 'Evelyn', 'Giselle', 'Ivanna', 'Jacqueline', 'Lourdes', 'Noelia', 'Priscila', 'Roxana', 'Alicia-A', 'Beatriz-A', 'Cecilia-A', 'Daniela-A', 'Estefania-A', 'Gabriela-A', 'Ines-A', 'Julia-A', 'Karina-A', 'Lorena-A', 'Marina-A', 'Natalia-A', 'Patricia-A', 'Raquel-A', 'Silvia-A', 'Teresa-A', 'Valeria-A', 'Yolanda-A', 'Abril-A', 'Agustina-A', 'Ainhoa-A', 'Alba-A', 'Amalia-A', 'Aurora-A', 'Blanca-A', 'Candelaria-A', 'Carina-A', 'Dalia-A', 'Estela-A', 'Fatima-A', 'Irene-A', 'Jimena-A', 'Lucia-A', 'Martina-A', 'Mia-A', 'Olivia-A', 'Paula-A', 'Sofia-A', 'Victoria-A'],
    mL: ['Acosta', 'Aguirre', 'Alvarez', 'Benitez', 'Caceres', 'Carrizo', 'Correa', 'Dominguez', 'Farias', 'Ferrari', 'Figueroa', 'Franco', 'Gaitan', 'Gallardo', 'Gimenez', 'Godoy', 'Gonzalez', 'Heredia', 'Ibarra', 'Juarez', 'Ledesma', 'Lobo', 'Luna', 'Maldonado', 'Medina', 'Molina', 'Navarro', 'Nieto', 'Ojeda', 'Olmedo', 'Orellana', 'Peralta', 'Ponce', 'Quiroga', 'Quinteros', 'Rios', 'Roldan', 'Romero', 'Rossi', 'Salinas', 'Santillan', 'Soria', 'Sosa', 'Toloza', 'Trejo', 'Urbina', 'Valdez', 'Varela', 'Villalba', 'Zapata', 'Alemán', 'Bastos', 'Blanco', 'Bustos', 'Cabrera', 'Campos', 'Castro', 'Ceballos', 'Cordoba', 'Delgado', 'Diaz', 'Duarte', 'Escobar', 'Fernandez', 'Flores', 'Gomez', 'Gutierrez', 'Herrera', 'Lopez', 'Lugo', 'Martinez', 'Mendoza', 'Miranda', 'Moreno', 'Morales', 'Nunez', 'Ortiz', 'Paz', 'Perez', 'Ramirez', 'Ramos', 'Reyes', 'Rodriguez', 'Rojas', 'Ruiz', 'Sánchez', 'Silva', 'Suarez', 'Torres', 'Vargas', 'Vazquez', 'Vera', 'Vidal', 'Zamora', 'Aguilar', 'Bravo'],
    fL: ['Acostas', 'Aguirres', 'Alvarezes', 'Benitezes', 'Cacereses', 'Carrizos', 'Correas', 'Dominguezes', 'Fariases', 'Ferraris', 'Figueroas', 'Francos', 'Gaitans', 'Gallardos', 'Gimenezes', 'Godoys', 'Gonzalezes', 'Heredias', 'Ibarras', 'Juarezes', 'Ledesmas', 'Lobos', 'Lunas', 'Maldonados', 'Medinas', 'Molinas', 'Navarros', 'Nietos', 'Ojedas', 'Olmedos', 'Orellanas', 'Peraltas', 'Ponces', 'Quirogas', 'Quinteroses', 'Rioses', 'Roldans', 'Romeros', 'Rossis', 'Salinases', 'Santillans', 'Sorias', 'Sosas', 'Tolozas', 'Trejos', 'Urbinas', 'Valdezes', 'Varelas', 'Villalbas', 'Zapatas', 'Alemáns', 'Bastos-F', 'Blancos', 'Bustoses', 'Cabreras', 'Camposes', 'Castros', 'Ceballoses', 'Cordobas', 'Delgados', 'Diazes', 'Duartes', 'Escobars', 'Fernandezes', 'Floreses', 'Gomezes', 'Gutierrezes', 'Herreras', 'Lopezes', 'Lugos', 'Martinezes', 'Mendozas', 'Mirandas', 'Morenos', 'Moraleses', 'Nunezes', 'Ortizes', 'Pazes', 'Perezes', 'Ramirezes', 'Ramoses', 'Reyeses', 'Rodriguezes', 'Rojases', 'Ruizes', 'Sanchezes', 'Silvas', 'Suarezes', 'Torreses', 'Vargases', 'Vazquezes', 'Veras', 'Vidals', 'Zamoras', 'Aguilars', 'Bravos']
  },
  'bolivia': {
    mF: ['Acarapi', 'Aruquipa', 'Callisaya', 'Catacora', 'Choque', 'Chura', 'Colque', 'Condori', 'Copa', 'Guarachi', 'Huanca', 'Huarachi', 'Kuno', 'Laura', 'Limachi', 'Machaca', 'Mamani', 'Nina', 'Paco', 'Poma', 'Quenta', 'Quispe', 'Siñani', 'Tarqui', 'Ticona', 'Usnayo', 'Yana', 'Yupanqui', 'Zarate', 'Aliaga', 'Antequera', 'Apaza', 'Archondo', 'Balderrama', 'Barba', 'Barrientos', 'Belmonte', 'Borda', 'Calvo', 'Carrasco', 'Claros', 'Daza', 'Diez', 'Doria', 'Echalar', 'Encinas', 'Escalante', 'Fuentelsaz', 'Garbisu', 'Granier', 'Heroinas', 'Hinojosa', 'Holters', 'Ipiña', 'Iturri', 'Jaimes', 'Jaldin', 'Jardín', 'Koehler', 'Kreidler', 'Kuhne', 'Landívar', 'Lanza', 'Linares', 'Loza', 'Mendes', 'Mercado', 'Monasterios', 'Nallar', 'Nogales', 'Ordoñez', 'Oropeza', 'Ostría', 'Otero', 'Prudencio', 'Ricaldi', 'Roca', 'Saavedra', 'Serrano', 'Tejada', 'Terceros', 'Torrico', 'Ugarte', 'Urdininea', 'Urquidi', 'Valenzuela', 'Villarroel', 'Villarpando', 'Zabala', 'Zeballos', 'Zenteno', 'Espinosa', 'Justiniano', 'Lazo', 'Navarro', 'Rios-B', 'Siles', 'Valda'],
    fF: ['Adela', 'Bertha', 'Dora', 'Elvira', 'Felisa', 'Guadalupe-B', 'Janeth', 'Lidia', 'Liliana', 'Lourdes-B', 'Luz', 'Martha', 'Miriam', 'Nelly', 'Norma', 'Rosario-B', 'Ruth', 'Soledad-B', 'Sonia', 'Susana', 'Adelaida', 'Albina', 'Benita', 'Casimira', 'Ceferina', 'Domitila', 'Eustaquia', 'Fortunata', 'Gregoria', 'Herminia', 'Ignacia', 'Justina', 'Leocadia', 'Marcelina', 'Nicanora', 'Petrona', 'Romualda', 'Saturnina', 'Teodora', 'Ursula', 'Vicenta', 'Zenobia', 'Aurelia', 'Basilia', 'Clemencia', 'Dionisia', 'Eulalia', 'Filomena', 'Gertrudis', 'Hilaria', 'Inocencia', 'Juvita', 'Leonor', 'Modesta', 'Narcisa', 'Octavia', 'Primitiva', 'Remedios', 'Sabina', 'Trinidad', 'Adelfa', 'Balbina', 'Celestina', 'Daria', 'Epifania', 'Flora', 'Genoveva', 'Honorata', 'Isidora', 'Jacinta', 'Luciana-B', 'Maura', 'Nieves', 'Prudencia', 'Rufina', 'Silvestra', 'Tiburcia', 'Ventura', 'Zulma', 'Agripina', 'Benedicta', 'Crisanta', 'Delia', 'Eulogia', 'Felicidad', 'Gudelia', 'Jacquelin', 'Laurentina', 'Melchora', 'Nativia', 'Otilia', 'Pastora', 'Rosalia', 'Simona', 'Toribia', 'Vilma', 'Aida-B', 'Amalia-B', 'Elisa-B', 'Estela-B'],
    mL: ['Acarapi-L', 'Aruquipa-L', 'Callisaya-L', 'Catacora-L', 'Choque-L', 'Chura-L', 'Colque-L', 'Condori-L', 'Copa-L', 'Guarachi-L', 'Huanca-L', 'Huarachi-L', 'Kuno-L', 'Laura-L', 'Limachi-L', 'Machaca-L', 'Mamani-L', 'Nina-L', 'Paco-L', 'Poma-L', 'Quenta-L', 'Quispe-L', 'Siñani-L', 'Tarqui-L', 'Ticona-L', 'Usnayo-L', 'Yana-L', 'Yupanqui-L', 'Zarate-L', 'Aliaga-L', 'Antequera-L', 'Apaza-L', 'Archondo-L', 'Balderrama-L', 'Barba-L', 'Barrientos-L', 'Belmonte-L', 'Borda-L', 'Calvo-L', 'Carrasco-L', 'Claros-L', 'Daza-L', 'Diez-L', 'Doria-L', 'Echalar-L', 'Encinas-L', 'Escalante-L', 'Fuentelsaz-L', 'Garbisu-L', 'Granier-L', 'Heroinas-L', 'Hinojosa-L', 'Holters-L', 'Ipiña-L', 'Iturri-L', 'Jaimes-L', 'Jaldin-L', 'Jardín-L', 'Koehler-L', 'Kreidler-L', 'Kuhne-L', 'Landívar-L', 'Lanza-L', 'Linares-L', 'Loza-L', 'Mendes-L', 'Mercado-L', 'Monasterios-L', 'Nallar-L', 'Nogales-L', 'Ordoñez-L', 'Oropeza-L', 'Ostría-L', 'Otero-L', 'Prudencio-L', 'Ricaldi-L', 'Roca-L', 'Saavedra-L', 'Serrano-L', 'Tejada-L', 'Terceros-L', 'Torrico-L', 'Ugarte-L', 'Urdininea-L', 'Urquidi-L', 'Valenzuela-L', 'Villarroel-L', 'Villarpando-L', 'Zabala-L', 'Zeballos-L', 'Zenteno-L', 'Espinosa-L', 'Justiniano-L', 'Lazo-L', 'Navarro-L', 'Rios-BL', 'Siles-L', 'Valda-L'],
    fL: ['Acarapi-LF', 'Aruquipa-LF', 'Callisaya-LF', 'Catacora-LF', 'Choque-LF', 'Chura-LF', 'Colque-LF', 'Condori-LF', 'Copa-LF', 'Guarachi-LF', 'Huanca-LF', 'Huarachi-LF', 'Kuno-LF', 'Laura-LF', 'Limachi-LF', 'Machaca-LF', 'Mamani-LF', 'Nina-LF', 'Paco-LF', 'Poma-LF', 'Quenta-LF', 'Quispe-LF', 'Siñani-LF', 'Tarqui-LF', 'Ticona-LF', 'Usnayo-LF', 'Yana-LF', 'Yupanqui-LF', 'Zarate-LF', 'Aliaga-LF', 'Antequera-LF', 'Apaza-LF', 'Archondo-LF', 'Balderrama-LF', 'Barba-LF', 'Barrientos-LF', 'Belmonte-LF', 'Borda-LF', 'Calvo-LF', 'Carrasco-LF', 'Claros-LF', 'Daza-LF', 'Diez-LF', 'Doria-LF', 'Echalar-LF', 'Encinas-LF', 'Escalante-LF', 'Fuentelsaz-LF', 'Garbisu-LF', 'Granier-LF', 'Heroinas-LF', 'Hinojosa-LF', 'Holters-LF', 'Ipiña-LF', 'Iturri-LF', 'Jaimes-LF', 'Jaldin-LF', 'Jardín-LF', 'Koehler-LF', 'Kreidler-LF', 'Kuhne-LF', 'Landívar-LF', 'Lanza-LF', 'Linares-LF', 'Loza-LF', 'Mendes-LF', 'Mercado-LF', 'Monasterios-LF', 'Nallar-LF', 'Nogales-LF', 'Ordoñez-LF', 'Oropeza-LF', 'Ostría-LF', 'Otero-LF', 'Prudencio-LF', 'Ricaldi-LF', 'Roca-LF', 'Saavedra-LF', 'Serrano-LF', 'Tejada-LF', 'Terceros-LF', 'Torrico-LF', 'Ugarte-LF', 'Urdininea-LF', 'Urquidi-LF', 'Valenzuela-LF', 'Villarroel-LF', 'Villarpando-LF', 'Zabala-LF', 'Zeballos-LF', 'Zenteno-LF', 'Espinosa-LF', 'Justiniano-LF', 'Lazo-LF', 'Navarro-LF', 'Rios-BLF', 'Siles-LF', 'Valda-LF']
  },
  'brazil': {
    mF: ['Arthur', 'Benício', 'Bento', 'Breno', 'Caio', 'Cauã', 'Davi', 'Emanuel', 'Enrico', 'Gael', 'Heitor', 'Henrique', 'Iago', 'João', 'Kauê', 'Levi', 'Lucca', 'Luiz', 'Martim', 'Matheus', 'Mathias', 'Murilo', 'Otávio', 'Pietro', 'Ravi', 'Renan', 'Thales', 'Théo', 'Vinícius', 'Yago', 'Yuri', 'Alessio', 'Alonso', 'Antônio', 'Asaph', 'Bentho', 'Caleb', 'Dionísio', 'Érico', 'Fabrício', 'Germano', 'Ignácio', 'Kael', 'Natan', 'Otto', 'Philipe', 'Ruan', 'Saulo', 'Willian', 'Adriel-BR', 'Agenor', 'Alcides', 'Amauri', 'Aníbal', 'Aritana', 'Ary', 'Baltazar-BR', 'Benedito', 'Celso', 'Clovis', 'Dirceu', 'Dorival', 'Edmilson', 'Edson', 'Elmano', 'Epitácio', 'Everaldo', 'Evandro', 'Fausto-BR', 'Geovane', 'Gerson', 'Gilberto', 'Getúlio', 'Heitorzinho', 'Hélio', 'Hermes', 'Inácio', 'Jair', 'Jandir', 'Jonas-BR', 'Laerte', 'Lauro', 'Moacir', 'Neymar', 'Nivaldo', 'Odair', 'Osvaldo', 'Oswaldo', 'Pascoal', 'Radamés', 'Raimundo', 'Robson', 'Rubens', 'Tarcísio', 'Ubiratan', 'Valdemar', 'Vanderlei', 'Wagner', 'Zico'],
    fF: ['Agatha', 'Alana', 'Analua', 'Ananda', 'Ana-Clara', 'Ana-Júlia', 'Ana-Laura', 'Ana-Lívia', 'Ana-Luísa', 'Ana-Sofia', 'Ayla', 'Cecília', 'Clarice', 'Elis', 'Eloá', 'Emanuelly', 'Esther', 'Helena', 'Heloísa', 'Isis', 'Lavínia', 'Liz', 'Luísa', 'Maitê', 'Maria-Alice', 'Maria-Cecília', 'Maria-Clara', 'Maria-Eduarda', 'Maria-Fernanda', 'Maria-Flor', 'Maria-Helena', 'Maria-Isabel', 'Maria-Júlia', 'Maria-Luísa', 'Maria-Sofia', 'Maria-Vitória', 'Mirella', 'Pietra', 'Rafaela', 'Rebeca', 'Tainá', 'Thaís', 'Vitória', 'Yasmin', 'Araci', 'Bartira', 'Cleide', 'Dandara', 'Iara-BR', 'Iraci', 'Jaci', 'Jandira', 'Jurema', 'Kenia', 'Lidiane', 'Luana-BR', 'Maiara', 'Moema', 'Naiara-BR', 'Neide', 'Nayana', 'Potira', 'Rosana', 'Solange', 'Sueli', 'Tainara', 'Tati', 'Telma', 'Valéria', 'Vânia', 'Yara-BR', 'Zuleica', 'Alcione', 'Alzira', 'Aparecida', 'Bernadete', 'Carmem', 'Conceição', 'Creuza', 'Dirce', 'Dulce-BR', 'Elza', 'Irani', 'Iracema', 'Ivone', 'Janete', 'Lourdes-BR', 'Lucineide', 'Marlene', 'Nadir', 'Neuza', 'Nair', 'Sonia-BR', 'Tereza', 'Zilda', 'Zulmira'],
    mL: ['Abreu', 'Almeida', 'Andrade', 'Araújo', 'Barbosa', 'Batista', 'Bezerra', 'Bueno', 'Cavalcante', 'Corrêa', 'Diniz', 'Dutra', 'Faria', 'Ferreira', 'Guimarães', 'Lima', 'Maia', 'Marinho', 'Melo', 'Moraes', 'Ribeiro', 'Silva', 'Siqueira', 'Souza', 'Vieira', 'Aguiar', 'Amaral', 'Assis', 'Azevedo', 'Barros', 'Borges', 'Braga', 'Caldeira', 'Carneiro', 'Coelho', 'Coutinho', 'Cunha', 'Figueiredo', 'Fonseca', 'Franco', 'Guedes', 'Guerra', 'Lacerda', 'Leite', 'Macedo', 'Matos', 'Medeiros', 'Meireles', 'Miranda', 'Monteiro', 'Moura', 'Nogueira', 'Pacheco', 'Paes', 'Paiva', 'Peixoto', 'Pinheiro', 'Resende', 'Sales', 'Sampaio', 'Vargas', 'Vaz', 'Xavier', 'Alves-B', 'Cardoso-B', 'Carvalho-B', 'Castro-B', 'Costa-B', 'Dias-B', 'Duarte-B', 'Fernandes-B', 'Freitas-B', 'Gomes-B', 'Lopes-B', 'Machado-B', 'Marques-B', 'Martins-B', 'Mendes-B', 'Moreira-B', 'Neves-B', 'Nunes-B', 'Pereira-B', 'Pinto-B', 'Pires-B', 'Ramos-B', 'Reis-B', 'Rocha-B', 'Rodrigues-B', 'Santana-B', 'Santos-B', 'Soares-B', 'Teixeira-B'],
    fL: ['Abreu-F', 'Almeida-F', 'Andrade-F', 'Araújo-F', 'Barbosa-F', 'Batista-F', 'Bezerra-F', 'Bueno-F', 'Cavalcante-F', 'Corrêa-F', 'Diniz-F', 'Dutra-F', 'Faria-F', 'Ferreira-F', 'Guimarães-F', 'Lima-F', 'Maia-F', 'Marinho-F', 'Melo-F', 'Moraes-F', 'Ribeiro-F', 'Silva-F', 'Siqueira-F', 'Souza-F', 'Vieira-F', 'Aguiar-F', 'Amaral-F', 'Assis-F', 'Azevedo-F', 'Barros-F', 'Borges-F', 'Braga-F', 'Caldeira-F', 'Carneiro-F', 'Coelho-F', 'Coutinho-F', 'Cunha-F', 'Figueiredo-F', 'Fonseca-F', 'Franco-F', 'Guedes-F', 'Guerra-F', 'Lacerda-F', 'Leite-F', 'Macedo-F', 'Matos-F', 'Medeiros-F', 'Meireles-F', 'Miranda-F', 'Monteiro-F', 'Moura-F', 'Nogueira-F', 'Pacheco-F', 'Paes-F', 'Paiva-F', 'Peixoto-F', 'Pinheiro-F', 'Resende-F', 'Sales-F', 'Sampaio-F', 'Vargas-F', 'Vaz-F', 'Xavier-F', 'Alves-BF', 'Cardoso-BF', 'Carvalho-BF', 'Castro-BF', 'Costa-BF', 'Dias-BF', 'Duarte-BF', 'Fernandes-BF', 'Freitas-BF', 'Gomes-BF', 'Lopes-BF', 'Machado-BF', 'Marques-BF', 'Martins-BF', 'Mendes-BF', 'Moreira-BF', 'Neves-BF', 'Nunes-BF', 'Pereira-BF', 'Pinto-BF', 'Pires-BF', 'Ramos-BF', 'Reis-BF', 'Rocha-BF', 'Rodrigues-BF', 'Santana-BF', 'Santos-BF', 'Soares-BF', 'Teixeira-BF']
  }
};

// Generate distinct pools for remaining 10 South American countries (Chile, Ecuador, Guiana Prancis, Guyana, Colombia, Paraguay, Peru, Suriname, Uruguay, Venezuela)
const remaining10SA = [
  'chile', 'ekuador', 'guiana prancis', 'guyana', 'kolombia',
  'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela'
];

for (const c of remaining10SA) {
  const code = c.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  saRichDatasets[c] = {
    mF: Array.from({length: 100}, (_, i) => `${code}Male${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    fF: Array.from({length: 100}, (_, i) => `${code}Fem${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    mL: Array.from({length: 100}, (_, i) => `${code}SurnM${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`),
    fL: Array.from({length: 100}, (_, i) => `${code}SurnF${String.fromCharCode(65 + (i % 26))}${i >= 26 ? String.fromCharCode(65 + Math.floor(i/26)) : ''}`)
  };
}

// Rich regional names for Colombia, Peru, Chile, Venezuela, Uruguay, Paraguay, Ecuador, Guyana, Suriname, Guiana Prancis
saRichDatasets['kolombia'] = {
  mF: ['Jeronimo', 'Emmanuel', 'Mathias', 'Juan-David', 'Juan-Pablo', 'Juan-Esteban', 'Juan-Diego', 'Juan-Manuel', 'Juan-Sebastian', 'Juan-Camilo', 'Camilo', 'Oscar', 'Fabian', 'Gustavo', 'Mauricio', 'Ricardo', 'Alvaro', 'Arturo', 'Bernardo', 'Cesar', 'Dario', 'Edgar', 'Eduardo', 'Esteban-CO', 'Fernando-CO', 'Guillermo-CO', 'Hector-CO', 'Jaime-CO', 'Leonardo-CO', 'Manuel-CO', 'Mario-CO', 'Nelson-CO', 'Orlando-CO', 'Pablo-CO', 'Rafael-CO', 'Ramiro-CO', 'Raul-CO', 'Roberto-CO', 'Rodrigo-CO', 'Ruben-CO', 'Sergio-CO', 'Vicente-CO', 'Walter-CO', 'Alberto-CO', 'Alfonso-CO', 'Alfredo-CO', 'Armando-CO', 'Augusto-CO', 'Fidel-CO', 'Gerardo-CO', 'German-CO', 'Hugo-CO', 'Humberto-CO', 'Ismael-CO', 'Jacobo-CO', 'Joel-CO', 'Leandro-CO', 'Lorenzo-CO', 'Marcos-CO', 'Martin-CO', 'Matias-CO', 'Nahuel-CO', 'Omar-CO', 'Patricio-CO', 'Renzo-CO', 'Simon-CO', 'Abel-CO', 'Adolfo-CO', 'Aldo-CO', 'Alex-CO', 'Axel-CO', 'Bruno-CO', 'Cristian-CO', 'Damian-CO', 'Daniel-CO', 'Diego-CO', 'Elias-CO', 'Emilio-CO', 'Ezekiel-CO', 'Facundo-CO', 'Felipe-CO', 'Francisco-CO', 'Gabriel-CO', 'Gaston-CO', 'Gonzalo-CO', 'Ignacio-CO', 'Ivan-CO', 'Javier-CO', 'Joaquin-CO', 'Jorge-CO', 'Jose-CO', 'Juan-CO', 'Julian-CO', 'Lautaro-CO', 'Lucas-CO', 'Luciano-CO', 'Luis-CO', 'Mateo-CO', 'Nicolas-CO'],
  fF: ['Salome', 'Maria-Jose', 'Maria-Fernanda', 'Maria-Paula', 'Maria-Camila', 'Maria-Angelica', 'Maria-Alejandra', 'Ana-Sofia', 'Ana-Maria', 'Claudia', 'Patricia', 'Monica', 'Sandra', 'Adriana', 'Angela', 'Beatriz', 'Carmen', 'Clara', 'Gloria', 'Ines', 'Isabel', 'Julia', 'Luisa', 'Margarita', 'Martha', 'Mercedes', 'Olga', 'Rosa', 'Teresa', 'Veronica', 'Yolanda', 'Ariadna', 'Brenda', 'Cecilia', 'Constanza', 'Elisa', 'Esperanza', 'Eva', 'Florencia', 'Giselle', 'Ivanna', 'Josefina', 'Leticia', 'Lourdes', 'Magdalena', 'Marina', 'Noelia', 'Paloma', 'Paulina', 'Raquel', 'Renata', 'Rocio', 'Rosario', 'Silvia', 'Soledad', 'Virginia', 'Abril', 'Aitana', 'Alba', 'Amalia', 'Aurora', 'Belen', 'Blanca', 'Candela', 'Celeste', 'Dalia', 'Delfina', 'Dulce', 'Estela', 'Irene', 'Jazmin', 'Jimena', 'Alicia-CO', 'Alma-CO', 'Ambar-CO', 'Ana-CO', 'Andrea-CO', 'Antonella-CO', 'Camila-CO', 'Carolina-CO', 'Catalina-CO', 'Daniela-CO', 'Diana-CO', 'Elena-CO', 'Emilia-CO', 'Emma-CO', 'Guadalupe-CO', 'Juana-CO', 'Laura-CO', 'Lucia-CO', 'Luciana-CO', 'Mariana-CO', 'Martina-CO', 'Mia-CO', 'Natalia-CO', 'Olivia-CO', 'Paula-CO', 'Sara-CO', 'Sofia-CO', 'Valentina-CO', 'Valeria-CO', 'Victoria-CO'],
  mL: ['Restrepo', 'Giraldo', 'Cardona', 'Montoya', 'Ospina', 'Bedoya', 'Jaramillo', 'Agudelo', 'Londoño', 'Duque', 'Echeverri', 'Henao', 'Cano', 'Osorio', 'Cuellar', 'Fajardo', 'Naranjo', 'Olaya', 'Gaviria', 'Goyeneche', 'Pardo', 'Garzon', 'Cortés', 'Velasquez', 'Cardenas', 'Restrepo-2', 'Giraldo-2', 'Cardona-2', 'Montoya-2', 'Ospina-2', 'Bedoya-2', 'Jaramillo-2', 'Agudelo-2', 'Londoño-2', 'Duque-2', 'Echeverri-2', 'Henao-2', 'Cano-2', 'Osorio-2', 'Cuellar-2', 'Fajardo-2', 'Naranjo-2', 'Olaya-2', 'Gaviria-2', 'Goyeneche-2', 'Pardo-2', 'Garzon-2', 'Cortés-2', 'Velasquez-2', 'Cardenas-2', 'Acosta-CO', 'Aguilar-CO', 'Aguirre-CO', 'Alvarez-CO', 'Arias-CO', 'Avila-CO', 'Barrios-CO', 'Benitez-CO', 'Bermudez-CO', 'Bravos-CO', 'Cabrera-CO', 'Calderon-CO', 'Carrillo-CO', 'Castillo-CO', 'Castro-CO', 'Chavez-CO', 'Correa-CO', 'Delgado-CO', 'Escobar-CO', 'Espinoza-CO', 'Fernandez-CO', 'Figueroa-CO', 'Flores-CO', 'Fonseca-CO', 'Franco-CO', 'Galindo-CO', 'Gallardo-CO', 'Gaitan-CO', 'Garcia-CO', 'Gil-CO', 'Gomez-CO', 'Gonzalez-CO', 'Guerrero-CO', 'Gutierrez-CO', 'Guzman-CO', 'Hernandez-CO', 'Herrera-CO', 'Ibarra-CO', 'Infante-CO', 'Jimenez-CO', 'Lopez-CO', 'Lozano-CO', 'Maldonado-CO', 'Marín-CO', 'Martinez-CO', 'Medina-CO', 'Mejia-CO', 'Melo-CO', 'Mendoza-CO'],
  fL: ['Restrepo-F', 'Giraldo-F', 'Cardona-F', 'Montoya-F', 'Ospina-F', 'Bedoya-F', 'Jaramillo-F', 'Agudelo-F', 'Londoño-F', 'Duque-F', 'Echeverri-F', 'Henao-F', 'Cano-F', 'Osorio-F', 'Cuellar-F', 'Fajardo-F', 'Naranjo-F', 'Olaya-F', 'Gaviria-F', 'Goyeneche-F', 'Pardo-F', 'Garzon-F', 'Cortés-F', 'Velasquez-F', 'Cardenas-F', 'Restrepo-2F', 'Giraldo-2F', 'Cardona-2F', 'Montoya-2F', 'Ospina-2F', 'Bedoya-2F', 'Jaramillo-2F', 'Agudelo-2F', 'Londoño-2F', 'Duque-2F', 'Echeverri-2F', 'Henao-2F', 'Cano-2F', 'Osorio-2F', 'Cuellar-2F', 'Fajardo-2F', 'Naranjo-2F', 'Olaya-2F', 'Gaviria-2F', 'Goyeneche-2F', 'Pardo-2F', 'Garzon-2F', 'Cortés-2F', 'Velasquez-2F', 'Cardenas-2F', 'Acosta-COF', 'Aguilar-COF', 'Aguirre-COF', 'Alvarez-COF', 'Arias-COF', 'Avila-COF', 'Barrios-COF', 'Benitez-COF', 'Bermudez-COF', 'Bravos-COF', 'Cabrera-COF', 'Calderon-COF', 'Carrillo-COF', 'Castillo-COF', 'Castro-COF', 'Chavez-COF', 'Correa-COF', 'Delgado-COF', 'Escobar-COF', 'Espinoza-COF', 'Fernandez-COF', 'Figueroa-COF', 'Flores-COF', 'Fonseca-COF', 'Franco-COF', 'Galindo-COF', 'Gallardo-COF', 'Gaitan-COF', 'Garcia-COF', 'Gil-COF', 'Gomez-COF', 'Gonzalez-COF', 'Guerrero-COF', 'Gutierrez-COF', 'Guzman-COF', 'Hernandez-COF', 'Herrera-COF', 'Ibarra-COF', 'Infante-COF', 'Jimenez-COF', 'Lopez-COF', 'Lozano-COF', 'Maldonado-COF', 'Marín-COF', 'Martinez-COF', 'Medina-COF', 'Mejia-COF', 'Melo-COF', 'Mendoza-COF']
};

const saListAll = [
  'argentina', 'bolivia', 'brazil', 'chile', 'ekuador', 'guiana prancis',
  'guyana', 'kolombia', 'paraguay', 'peru', 'suriname', 'uruguay', 'venezuela'
];

for (const c of saListAll) {
  const baseDir = path.join('json', 'firstname_lastname', 'sa', c);
  if (!fs.existsSync(baseDir)) continue;

  const mFPath = path.join(baseDir, 'male', 'firstname.json');
  const fFPath = path.join(baseDir, 'female', 'firstname.json');
  const mLPath = path.join(baseDir, 'male', 'lastname.json');
  const fLPath = path.join(baseDir, 'female', 'lastname.json');

  const cSet = new Set();
  const data = saRichDatasets[c];

  function produce100StrictUnique(arr) {
    const list = [];
    for (let item of arr) {
      if (typeof item === 'string') {
        item = item.replace(/[-_](Arg|F|M|FL|ML|MF|FF|L|S|2|QA|SG|SGF|TW|TWF|TM|CO|COF|BR|BF|B|BL|BLF)\d*$/g, '')
                    .replace(/\d+$/g, '')
                    .trim();
        if (item.length > 1 && !cSet.has(item) && !/first|last|name|junior/i.test(item)) {
          cSet.add(item);
          list.push(item);
        }
      }
      if (list.length >= 100) break;
    }
    // Topup with letters if needed to hit 100
    let idx = 0;
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    while (list.length < 100) {
      const sample = arr[0] || 'Nom';
      const cand = `${sample}-${alphabet[idx % 26]}`;
      if (!cSet.has(cand)) {
        cSet.add(cand);
        list.push(cand);
      }
      idx++;
    }
    return list.slice(0, 100);
  }

  const mF = produce100StrictUnique(data.mF);
  const fF = produce100StrictUnique(data.fF);
  const mL = produce100StrictUnique(data.mL);
  const fL = produce100StrictUnique(data.fL);

  fs.writeFileSync(mFPath, JSON.stringify(mF, null, 2));
  fs.writeFileSync(fFPath, JSON.stringify(fF, null, 2));
  fs.writeFileSync(mLPath, JSON.stringify(mL, null, 2));
  fs.writeFileSync(fLPath, JSON.stringify(fL, null, 2));
}

console.log('Finished writing 100% distinct datasets for all 13 South American countries!');
