import '../tes_seleksi_model.dart';

List<QuestionItem> getKedokteranGigiQuestions() {
  return const [
    QuestionItem(
      id: 'kg_001',
      questionText: 'Jaringan terkeras pada tubuh manusia yang melapisi mahkota gigi dinamakan:',
      options: ['Dentin', 'Enamel', 'Sementum', 'Pulpa'],
      correctOptionIndex: 1,
      explanation: 'Enamel adalah lapisan terluar mahkota gigi dan merupakan jaringan terkeras tubuh.',
    ),
    QuestionItem(
      id: 'kg_002',
      questionText: 'Jaringan lunak di dalam rongga gigi yang berisi pembuluh darah dan saraf dinamakan:',
      options: ['Pulpa Gigi', 'Dentin', 'Sementum', 'Gingiva'],
      correctOptionIndex: 0,
      explanation: 'Pulpa gigi memberikan suplai nutrisi dan persarafan gigi.',
    ),
    QuestionItem(
      id: 'kg_003',
      questionText: 'Jumlah total gigi susu (desidui) lengkap pada anak-anak adalah:',
      options: ['16 Gigi', '20 Gigi', '28 Gigi', '32 Gigi'],
      correctOptionIndex: 1,
      explanation: 'Gigi susu anak berjumlah 20 buah (10 atas, 10 bawah).',
    ),
    QuestionItem(
      id: 'kg_004',
      questionText: 'Jumlah total gigi permanen lengkap pada orang dewasa adalah:',
      options: ['28 Gigi', '30 Gigi', '32 Gigi', '36 Gigi'],
      correctOptionIndex: 2,
      explanation: 'Gigi permanen dewasa berjumlah 32 buah termasuk molar ketiga.',
    ),
    QuestionItem(
      id: 'kg_005',
      questionText: 'Gigi geraham bungsu yang sering mengalami impaksi dinamakan molar ke:',
      options: ['Molar 1 (M1)', 'Molar 2 (M2)', 'Molar 3 (M3)', 'Premolar 2 (P2)'],
      correctOptionIndex: 2,
      explanation: 'Molar 3 (wisdom tooth) paling sering mengalami impaksi terlindas tulang.',
    ),
    QuestionItem(
      id: 'kg_006',
      questionText: 'Bakteri utama pemicu awal terjadinya karies (gigi berlubang) adalah:',
      options: ['Streptococcus mutans', 'Escherichia coli', 'Lactobacillus acidophilus', 'Staphylococcus aureus'],
      correctOptionIndex: 0,
      explanation: 'S. mutans memetabolisme gula menjadi asam yang mengikis enamel.',
    ),
    QuestionItem(
      id: 'kg_007',
      questionText: 'Peradangan pada gusi tanpa disertai kehilangan tulang alveolar dinamakan:',
      options: ['Gingivitis', 'Periodontitis', 'Pulpitis', 'Stomatitis'],
      correctOptionIndex: 0,
      explanation: 'Gingivitis adalah peradangan terbatas pada jaringan gusi (gingiva).',
    ),
    QuestionItem(
      id: 'kg_008',
      questionText: 'Peradangan jaringan penyangga gigi yang merusak ligamentum periodontal dan tulang alveolar dinamakan:',
      options: ['Periodontitis', 'Gingivitis', 'Pulpitis', 'Periangitis'],
      correctOptionIndex: 0,
      explanation: 'Periodontitis merusak jaringan pendukung gigi hingga memicu kegoyahan gigi.',
    ),
    QuestionItem(
      id: 'kg_009',
      questionText: 'Peradangan pada ruang pulpa akibat karies dalam yang memicu rasa nyeri berdenyut dinamakan:',
      options: ['Pulpitis', 'Gingivitis', 'Periodontitis', 'Abses Periapikal'],
      correctOptionIndex: 0,
      explanation: 'Pulpitis terjadi akibat infeksi bakteri menembus ruang pulpa.',
    ),
    QuestionItem(
      id: 'kg_010',
      questionText: 'Perawatan penanganan pulpa gigi yang terinfeksi dengan membersihkan dan mengisi saluran akar dinamakan:',
      options: ['Perawatan Saluran Akar (PSA/Endodontik)', 'Penambalan Komposit', 'Scaling', 'Bleaching'],
      correctOptionIndex: 0,
      explanation: 'PSA membuang pulpa terinfeksi dan menutup rapat saluran akar.',
    ),
    QuestionItem(
      id: 'kg_011',
      questionText: 'Cabang ilmu kedokteran gigi yang berfokus merapikan posisi gigi dan maloklusi menggunakan kawat dinamakan:',
      options: ['Ortodonsia', 'Periodonsia', 'Prostodonsia', 'Pedodonsia'],
      correctOptionIndex: 0,
      explanation: 'Ortodonsia menangani koreksi letak gigi dan susunan rahang.',
    ),
    QuestionItem(
      id: 'kg_012',
      questionText: 'Cabang ilmu kedokteran gigi yang berfokus pada pembuatan gigi tiruan dan protesa mulut dinamakan:',
      options: ['Prostodonsia', 'Ortodonsia', 'Endodonsia', 'Periodonsia'],
      correctOptionIndex: 0,
      explanation: 'Prostodonsia mengganti gigi hilang dengan gigi tiruan lepasan/cekat.',
    ),
    QuestionItem(
      id: 'kg_013',
      questionText: 'Spesialisasi kesehatan gigi khusus untuk pasien anak-anak dinamakan:',
      options: ['Pedodonsia (Kedokteran Gigi Anak)', 'Periodonsia', 'Ortodonsia', 'Patologi Mulut'],
      correctOptionIndex: 0,
      explanation: 'Pedodonsia menangani kesehatan gigi anak sejak bayi hingga remaja.',
    ),
    QuestionItem(
      id: 'kg_014',
      questionText: 'Tindakan membersihkan plak terkalsifikasi (karang gigi) menggunakan alat ultrasonic scaler dinamakan:',
      options: ['Scaling Gigi', 'Bleaching Gigi', 'Veneer', 'Curettage'],
      correctOptionIndex: 0,
      explanation: 'Scaling mengangkat kalkulus (karang gigi) di atas dan bawah gusi.',
    ),
    QuestionItem(
      id: 'far_015_kg',
      questionText: 'Deposit keras berpigmen pada permukaan gigi akibat mengerasnya plak dinamakan:',
      options: ['Kalkulus / Karang Gigi', 'Debris', 'Stain', 'Pellicle'],
      correctOptionIndex: 0,
      explanation: 'Kalkulus adalah plak yang mengeras akibat mineralisasi ludah.',
    ),
    QuestionItem(
      id: 'kg_016',
      questionText: 'Bahan tambal estetik sewarna gigi yang mengeras dengan bantuan sinar polimerisasi (Light Curing) dinamakan:',
      options: ['Komposit Resin', 'Amalgam', 'Semen Seng Fosfat', 'GIC'],
      correctOptionIndex: 0,
      explanation: 'Resin komposit ditindas sinar curing untuk pengerasan warna alami.',
    ),
    QuestionItem(
      id: 'kg_017',
      questionText: 'Bahan tambal gigi konvensional berwarna abu-abu perak yang mengandung raksa/merkuri dinamakan:',
      options: ['Amalgam', 'Komposit', 'GIC', 'Inlay Gold'],
      correctOptionIndex: 0,
      explanation: 'Amalgam terdiri dari campuran perak, timah, dan merkuri.',
    ),
    QuestionItem(
      id: 'kg_018',
      questionText: 'Bahan tambal Glass Ionomer Cement (GIC) memiliki keunggulan melepas unsur pencegah karies yaitu:',
      options: ['Fluorida', 'Kalsium', 'Fosfat', 'Natrium'],
      correctOptionIndex: 0,
      explanation: 'GIC secara kontinyu melepaskan fluorida untuk remineralisasi.',
    ),
    QuestionItem(
      id: 'kg_019',
      questionText: 'Lapisan tipis bahan porselen/komposit yang ditempel di permukaan depan gigi estetik dinamakan:',
      options: ['Veneer', 'Crown / Mahkota', 'Bridge / Jembatan', 'Implan'],
      correctOptionIndex: 0,
      explanation: 'Veneer memperbaiki bentuk dan warna permukaan fasial gigi.',
    ),
    QuestionItem(
      id: 'kg_020',
      questionText: 'Pengganti akar gigi titanium yang ditanam ke dalam tulang rahang secara bedah dinamakan:',
      options: ['Implan Gigi', 'Crown', 'Gigi Tiruan Lepasan', 'Post & Core'],
      correctOptionIndex: 0,
      explanation: 'Implan gigi berbahan titanium menyatu osteointegrasi dengan tulang.',
    ),
    QuestionItem(
      id: 'kg_021',
      questionText: 'Saraf utama yang memberikan sensasi rasa nyeri pada gigi rahang atas dan bawah adalah:',
      options: ['Nervus Trigeminus (CN V)', 'Nervus Fasialis (CN VII)', 'Nervus Glosofaringeus', 'Nervus Hypoglossus'],
      correctOptionIndex: 0,
      explanation: 'Saraf kranial ke-V (Trigeminus) menginervasi sensori maksila dan mandibula.',
    ),
    QuestionItem(
      id: 'kg_022',
      questionText: 'Cabang Nervus Trigeminus yang menginervasi gigi-gigi pada rahang bawah adalah:',
      options: ['Nervus Mandibularis (V3)', 'Nervus Maksilaris (V2)', 'Nervus Oftalmikus (V1)', 'Nervus Lingualis'],
      correctOptionIndex: 0,
      explanation: 'Cabang V3 (Mandibularis) menginervasi elemen gigi rahang bawah.',
    ),
    QuestionItem(
      id: 'kg_023',
      questionText: 'Cabang Nervus Trigeminus yang menginervasi gigi-gigi pada rahang atas adalah:',
      options: ['Nervus Maksilaris (V2)', 'Nervus Mandibularis (V3)', 'Nervus Oftalmikus (V1)', 'Nervus Mentalis'],
      correctOptionIndex: 0,
      explanation: 'Cabang V2 (Maksilaris) menginervasi gigi rahang atas.',
    ),
    QuestionItem(
      id: 'kg_024',
      questionText: 'Sendi yang menghubungkan rahang bawah dengan tulang tengkorak dinamakan:',
      options: ['Temporomandibular Joint (TMJ)', 'Sendi Atlanto-Oksipital', 'Sendi Sfenoid', 'Sendi Zygomaticus'],
      correctOptionIndex: 0,
      explanation: 'TMJ memfasilitasi gerakan membuka, menutup, dan mengunyah rahang.',
    ),
    QuestionItem(
      id: 'kg_025',
      questionText: 'Kelainan oklusi di mana rahang bawah lebih maju menonjol ke depan daripada rahang atas disebut Maloklusi Klas:',
      options: ['Maloklusi Klas III Angle', 'Maloklusi Klas I Angle', 'Maloklusi Klas II Angle', 'Open Bite'],
      correctOptionIndex: 0,
      explanation: 'Klas III Angle (Prognati Mandibula) ditandai gigi bawah lebih anterior dari atas.',
    ),
    QuestionItem(
      id: 'kg_026',
      questionText: 'Kelainan oklusi di mana rahang atas jauh lebih maju ke depan daripada rahang bawah disebut Maloklusi Klas:',
      options: ['Maloklusi Klas II Angle', 'Maloklusi Klas I Angle', 'Maloklusi Klas III Angle', 'Crossbite'],
      correctOptionIndex: 0,
      explanation: 'Klas II Angle (Retrognati/Tonggos) menunjukkan maksila berada jauh di depan.',
    ),
    QuestionItem(
      id: 'kg_027',
      questionText: 'Kondisi celah bibir atau langit-langit mulut bawaan lahir dinamakan:',
      options: ['Labiopalatoskisis (Cleft Lip/Palate)', 'Anodontia', 'Microdontia', 'Tongue-Tie'],
      correctOptionIndex: 0,
      explanation: 'Labiopalatoskisis adalah kelainan kongenital celah bibir dan palatum.',
    ),
    QuestionItem(
      id: 'kg_028',
      questionText: 'Kondisi kelainan di mana seorang individu sama sekali tidak memiliki benih gigi dinamakan:',
      options: ['Anodontia', 'Oligodontia', 'Hipodontia', 'Hyperdontia'],
      correctOptionIndex: 0,
      explanation: 'Anodontia adalah ketiadaan benih gigi secara total.',
    ),
    QuestionItem(
      id: 'kg_029',
      questionText: 'Kondisi berkembangnya gigi berlebih melebihi jumlah normal dinamakan:',
      options: ['Hyperdontia / Mesiodens', 'Anodontia', 'Microdontia', 'Macrodontia'],
      correctOptionIndex: 0,
      explanation: 'Hyperdontia ditandai munculnya gigi tambahan (supernumerary teeth).',
    ),
    QuestionItem(
      id: 'kg_030',
      questionText: 'Gigi tambahan berlebih yang tumbuh di antara dua gigi insisivus sentral rahang atas dinamakan:',
      options: ['Mesiodens', 'Paramolar', 'Distomolar', 'Odontoma'],
      correctOptionIndex: 0,
      explanation: 'Mesiodens adalah gigi supernumerary tepat di garis tengah maksila.',
    ),
    QuestionItem(
      id: 'kg_031',
      questionText: 'Sariawan berulang pada mukosa mulut tanpa penyebab infeksi spesifik dinamakan:',
      options: ['Stomatitis Aftosa Rekuren (SAR)', 'Kandidiasis Oral', 'Leukoplakia', 'Herpes Labialis'],
      correctOptionIndex: 0,
      explanation: 'SAR adalah ulser sariawan mukosa mulut berulang.',
    ),
    QuestionItem(
      id: 'kg_032',
      questionText: 'Infeksi jamur bercak putih pada mukosa lidah/mulut yang sering dipicu Candida albicans dinamakan:',
      options: ['Kandidiasis Oral (Thrush)', 'Leukoplakia', 'Lichen Planus', 'Gingivitis'],
      correctOptionIndex: 0,
      explanation: 'Thrush ditandai pseudomembran putih akibat Candida albicans.',
    ),
    QuestionItem(
      id: 'kg_033',
      questionText: 'Bercak putih pra-kanker pada mukosa mulut yang tidak bisa dikorek lepas dinamakan:',
      options: ['Leukoplakia', 'Kandidiasis', 'Eritroplakia', 'Stomatitis'],
      correctOptionIndex: 0,
      explanation: 'Leukoplakia berpotensi menjadi keganasan (Karsinoma Sel Skuamosa).',
    ),
    QuestionItem(
      id: 'kg_034',
      questionText: 'Jenis kanker paling sering yang tumbuh di dalam rongga mulut adalah:',
      options: ['Karsinoma Sel Skuamosa (SCC)', 'Osteosarcoma', 'Melanoma', 'Adenokarsinoma'],
      correctOptionIndex: 0,
      explanation: 'Oral Squamous Cell Carcinoma mencakup >90% kanker mulut.',
    ),
    QuestionItem(
      id: 'kg_035',
      questionText: 'Kelenjar ludah terbesar yang terletak di depan bawah telinga dinamakan kelenjar:',
      options: ['Parotis', 'Submandibularis', 'Sublingualis', 'Labialis'],
      correctOptionIndex: 0,
      explanation: 'Glandula parotis memproduksi air liur via duktus Stensen.',
    ),
    QuestionItem(
      id: 'kg_036',
      questionText: 'Infeksi virus gondongan (Mumps) memicu pembengkakan utama pada kelenjar ludah:',
      options: ['Parotis (Parotitis)', 'Submandibula', 'Sublingual', 'Palatina'],
      correctOptionIndex: 0,
      explanation: 'Virus Mumps menyerang jaringan kelenjar parotis.',
    ),
    QuestionItem(
      id: 'kg_037',
      questionText: 'Enzim pencernaan dalam air liur yang menguraikan amilum menjadi maltosa dinamakan:',
      options: ['Ptialin / Amilase Saliva', 'Pepsin', 'Tripsin', 'Lipase'],
      correctOptionIndex: 0,
      explanation: 'Enzim Ptialin memulai pemecahan karbohidrat di rongga mulut.',
    ),
    QuestionItem(
      id: 'kg_038',
      questionText: 'pH normal air liur (saliva) manusia berada pada rentang:',
      options: ['6.5 hingga 7.5', '4.0 hingga 5.0', '8.5 hingga 9.5', '2.0 hingga 3.0'],
      correctOptionIndex: 0,
      explanation: 'Saliva normal bersifat dekat netral (pH 6.5-7.5) sebagai buffer.',
    ),
    QuestionItem(
      id: 'kg_039',
      questionText: 'pH kritis di mana mineral enamel gigi mulai larut demineralisasi adalah sekitar:',
      options: ['5.5', '6.8', '7.4', '4.0'],
      correctOptionIndex: 0,
      explanation: 'Pada pH < 5.5, hidroksiapatit enamel larut mengalami demineralisasi.',
    ),
    QuestionItem(
      id: 'kg_040',
      questionText: 'Kristal mineral utama penyusun enamel dan dentin gigi adalah:',
      options: ['Hidroksiapatit', 'Kalsium Karbonat', 'Fluorapatit', 'Gipsum'],
      correctOptionIndex: 0,
      explanation: 'Kalsium Hidroksiapatit Ca10(PO4)6(OH)2 penyusun utama struktur gigi.',
    ),
    QuestionItem(
      id: 'kg_041',
      questionText: 'Pemberian fluorida yang membentuk senyawa lebih tahan asam pada enamel dinamakan:',
      options: ['Fluorapatit', 'Hidroksiapatit', 'Kalsium Klorida', 'Oksalat'],
      correctOptionIndex: 0,
      explanation: 'Ion fluor menggantikan OH- membentuk Fluorapatit yang lebih resisten asam.',
    ),
    QuestionItem(
      id: 'kg_042',
      questionText: 'Pengikisan permukaan gigi akibat gesekan mekanik benda luar (seperti sikat gigi keras) disebut:',
      options: ['Abrasi Gigi', 'Atrisi Gigi', 'Erosi Gigi', 'Abfraksi'],
      correctOptionIndex: 0,
      explanation: 'Abrasi dipicu gesekan mekanik eksternal berlebihan.',
    ),
    QuestionItem(
      id: 'kg_043',
      questionText: 'Pengikisan keausan gigi akibat kontak antar gigi saat mengunyah atau bruksisme disebut:',
      options: ['Atrisi Gigi', 'Abrasi Gigi', 'Erosi Gigi', 'Karies'],
      correctOptionIndex: 0,
      explanation: 'Atrisi terjadi akibat gesekan oklusal antar gigi lawan.',
    ),
    QuestionItem(
      id: 'kg_044',
      questionText: 'Pengikisan jaringan keras gigi akibat reaksi kimia asam non-bakteri (misal soda, asam lambung) dinamakan:',
      options: ['Erosi Gigi', 'Abrasi', 'Atrisi', 'Abfraksi'],
      correctOptionIndex: 0,
      explanation: 'Erosi dipicu asam ekstrinsik (makanan/minuman) atau intrinsik (GERD).',
    ),
    QuestionItem(
      id: 'kg_045',
      questionText: 'Kebiasaan menggertakkan atau menggeletukkan gigi saat tidur malam dinamakan:',
      options: ['Bruksisme', 'Clenching', 'Tinnitus', 'Trismus'],
      correctOptionIndex: 0,
      explanation: 'Bruksisme adalah aktivitas Involunter mengikis gigi saat tidur.',
    ),
    QuestionItem(
      id: 'kg_046',
      questionText: 'Keterbatasan atau kesukaran membuka mulut akibat spasme otot kunyah dinamakan:',
      options: ['Trismus', 'Ankilosis', 'Dislokasi', 'Spasmus'],
      correctOptionIndex: 0,
      explanation: 'Trismus membatasi jarak buka mulut pasien (<35mm).',
    ),
    QuestionItem(
      id: 'kg_047',
      questionText: 'Otot utama pengunyah yang berfungsi menutup rahang dan paling kuat adalah:',
      options: ['Musculus Masseter', 'Musculus Temporalis', 'Musculus Pterygoideus Medialis', 'Musculus Orbicularis Oris'],
      correctOptionIndex: 0,
      explanation: 'Masseter adalah otot mastikasi paling kuat penutup rahang.',
    ),
    QuestionItem(
      id: 'kg_048',
      questionText: 'Anestesi lokal blok yang melumpuhkan sensasi setengah rahang bawah dinamakan teknik:',
      options: ['Blok Nervus Alveolaris Inferior (NAI)', 'Infiltrasi Lokal', 'Blok Nervus Infraorbitalis', 'Intrapulpal'],
      correctOptionIndex: 0,
      explanation: 'Blok NAI memblokir sensori seluruh gigi posterior-anterior separuh mandibula.',
    ),
    QuestionItem(
      id: 'kg_049',
      questionText: 'Foto rontgen gigi yang memperlihatkan mahkota gigi atas dan bawah sekaligus untuk deteksi karies interdental dinamakan:',
      options: ['Bitewing Radiograph', 'Periapikal Radiograph', 'Panoramic Radiograph', 'Cephalometric'],
      correctOptionIndex: 0,
      explanation: 'Bitewing ideal untuk melihat karies di celah antar gigi (interproksimal).',
    ),
    QuestionItem(
      id: 'kg_050',
      questionText: 'Foto rontgen memutar yang memperlihatkan gambaran seluruh rahang dan gigi dalam satu film dinamakan:',
      options: ['Panoramic / Pantomogram', 'Periapikal', 'Cephalometri', 'Occlusal'],
      correctOptionIndex: 0,
      explanation: 'Panoramik menampilkan profil lengkap maksila, mandibula, dan TMJ.',
    ),
    QuestionItem(
      id: 'kg_051',
      questionText: 'Foto rontgen samping kepala yang digunakan dalam analisis ortodonsia dinamakan:',
      options: ['Sefalometri Radiografi', 'Panoramik', 'Bitewing', 'CT Scan'],
      correctOptionIndex: 0,
      explanation: 'Sefalometri mengukur sudut dan hubungan skeletal rahang terhadap tengkorak.',
    ),
    QuestionItem(
      id: 'kg_052',
      questionText: 'Permukaan gigi yang menghadap ke arah bibir dinamakan permukaan:',
      options: ['Labial', 'Buccal', 'Lingual', 'Palatal'],
      correctOptionIndex: 0,
      explanation: 'Labial adalah permukaan anterior dekat bibir.',
    ),
    QuestionItem(
      id: 'kg_053',
      questionText: 'Permukaan gigi posterior yang menghadap ke arah pipi dinamakan permukaan:',
      options: ['Buccal / Bukal', 'Labial', 'Lingual', 'Palatal'],
      correctOptionIndex: 0,
      explanation: 'Bukal adalah permukaan gigi belakang yang berhadapan dengan pipi.',
    ),
    QuestionItem(
      id: 'kg_054',
      questionText: 'Permukaan gigi rahang bawah yang menghadap ke arah lidah dinamakan permukaan:',
      options: ['Lingual', 'Palatal', 'Labial', 'Mesial'],
      correctOptionIndex: 0,
      explanation: 'Lingual berhadapan langsung dengan lidah.',
    ),
    QuestionItem(
      id: 'kg_055',
      questionText: 'Permukaan gigi rahang atas yang menghadap ke arah langit-langit mulut dinamakan permukaan:',
      options: ['Palatal', 'Lingual', 'Bukal', 'Distal'],
      correctOptionIndex: 0,
      explanation: 'Palatal berhadapan dengan palatum (langit-langit).',
    ),
    QuestionItem(
      id: 'kg_056',
      questionText: 'Permukaan gigi yang paling dekat dengan garis tengah lengkung gigi (midline) dinamakan permukaan:',
      options: ['Mesial', 'Distal', 'Oklusal', 'Insisal'],
      correctOptionIndex: 0,
      explanation: 'Mesial mengarah ke bagian depan/tengah midline.',
    ),
    QuestionItem(
      id: 'kg_057',
      questionText: 'Permukaan gigi yang menjauhi garis tengah lengkung gigi dinamakan permukaan:',
      options: ['Distal', 'Mesial', 'Oklusal', 'Fasial'],
      correctOptionIndex: 0,
      explanation: 'Distal mengarah ke posterior menjauhi midline.',
    ),
    QuestionItem(
      id: 'kg_058',
      questionText: 'Permukaan kunyah pada gigi geraham (premolar dan molar) dinamakan permukaan:',
      options: ['Oklusal', 'Insisal', 'Bukal', 'Mesial'],
      correctOptionIndex: 0,
      explanation: 'Oklusal adalah bidang gigit kunyah gigi posterior.',
    ),
    QuestionItem(
      id: 'kg_059',
      questionText: 'Tepi pemotong pada gigi depan (insisivus) dinamakan tepi:',
      options: ['Insisal', 'Oklusal', 'Cervical', 'Cusp'],
      correctOptionIndex: 0,
      explanation: 'Insisal berfungsi memotong makanan pada gigi anterior.',
    ),
    QuestionItem(
      id: 'kg_060',
      questionText: 'Gigi seri bertugas memotong makanan dinamakan gigi:',
      options: ['Insisivus', 'Kaninus', 'Premolar', 'Molar'],
      correctOptionIndex: 0,
      explanation: 'Insisivus (gigi seri) berfungsi cutting/memotong.',
    ),
    QuestionItem(
      id: 'kg_061',
      questionText: 'Gigi taring yang berbentuk runcing untuk menyobek makanan dinamakan gigi:',
      options: ['Kaninus', 'Insisivus', 'Premolar', 'Molar'],
      correctOptionIndex: 0,
      explanation: 'Kaninus (gigi taring) bertugas merobek makanan.',
    ),
    QuestionItem(
      id: 'kg_062',
      questionText: 'Gigi geraham kecil yang berfungsi menggiling makanan dinamakan gigi:',
      options: ['Premolar', 'Molar', 'Kaninus', 'Insisivus'],
      correctOptionIndex: 0,
      explanation: 'Premolar (geraham kecil) berada di antara taring dan geraham besar.',
    ),
    QuestionItem(
      id: 'kg_063',
      questionText: 'Gigi geraham besar dengan permukaan oklusal luas untuk melumat makanan dinamakan gigi:',
      options: ['Molar', 'Premolar', 'Kaninus', 'Insisivus'],
      correctOptionIndex: 0,
      explanation: 'Molar memiliki 4-5 cusp untuk melumatkan makanan.',
    ),
    QuestionItem(
      id: 'kg_064',
      questionText: 'Komponen matriks organik dentin utama yang memberi sifat elastisitas gigi adalah:',
      options: ['Kolagen Tipe I', 'Keratin', 'Elastin', 'Fibrin'],
      correctOptionIndex: 0,
      explanation: 'Dentin kaya akan serat Kolagen Tipe I.',
    ),
    QuestionItem(
      id: 'kg_065',
      questionText: 'Sel pembentuk jaringan dentin gigi dinamakan sel:',
      options: ['Odontoblas', 'Ameloblas', 'Sementoblas', 'Osteoblas'],
      correctOptionIndex: 0,
      explanation: 'Odontoblas memproduksi matriks dentin.',
    ),
    QuestionItem(
      id: 'kg_066',
      questionText: 'Sel pembentuk lapisan enamel gigi yang lenyap saat gigi erupsi dinamakan sel:',
      options: ['Ameloblas', 'Odontoblas', 'Sementoblas', 'Osteoklas'],
      correctOptionIndex: 0,
      explanation: 'Ameloblas memproduksi enamel dan mati setelah pembentukan selesai.',
    ),
    QuestionItem(
      id: 'kg_067',
      questionText: 'Sel pembentuk sementum pelapis akar gigi dinamakan sel:',
      options: ['Sementoblas', 'Ameloblas', 'Odontoblas', 'Fibroblas'],
      correctOptionIndex: 0,
      explanation: 'Sementoblas membentuk lapisan sementum.',
    ),
    QuestionItem(
      id: 'kg_068',
      questionText: 'Jaringan ikat tipis yang melingkupi akar gigi dan menempel ke tulang alveolar dinamakan:',
      options: ['Ligamentum Periodontal', 'Pulpa', 'Gingiva', 'Sementum'],
      correctOptionIndex: 0,
      explanation: 'Ligamentum periodontal meredam tekanan kunyah dan menahan gigi di socket.',
    ),
    QuestionItem(
      id: 'kg_069',
      questionText: 'Infeksi benjolan bernanah di ujung akar gigi akibat pulpitis nekrosis dinamakan:',
      options: ['Abses Periapikal', 'Abses Periodontal', 'Abses Submukosa', 'Granuloma'],
      correctOptionIndex: 0,
      explanation: 'Abses periapikal berkumpul di apeks akar gigi mati.',
    ),
    QuestionItem(
      id: 'kg_070',
      questionText: 'Kondisi hilangnya vitalitas saraf dan darah pada pulpa gigi dinamakan:',
      options: ['Nekrosis Pulpa', 'Pulpitis Reversibel', 'Pulpitis Ireversibel', 'Hiperemia Pulpa'],
      correctOptionIndex: 0,
      explanation: 'Nekrosis pulpa berarti sel-sel pulpa telah mati sepenuhnya.',
    ),
    QuestionItem(
      id: 'kg_071',
      questionText: 'Pulpitis tahap awal yang masih bisa pulih jika kariesnya ditambal dinamakan:',
      options: ['Pulpitis Reversibel', 'Pulpitis Ireversibel', 'Nekrosis Pulpa', 'Gangren Pulpa'],
      correctOptionIndex: 0,
      explanation: 'Pulpitis reversibel merespon nyeri sesaat terhadap rangsang dingin/manis.',
    ),
    QuestionItem(
      id: 'kg_072',
      questionText: 'Pulpitis parah dengan rasa sakit spontan tanpa rangsangan yang membutuhkan PSA dinamakan:',
      options: ['Pulpitis Ireversibel', 'Pulpitis Reversibel', 'Karies Superficial', 'Hyperemia'],
      correctOptionIndex: 0,
      explanation: 'Pulpitis ireversibel tidak bisa sembuh sendiri dan butuh perawatan saluran akar.',
    ),
    QuestionItem(
      id: 'kg_073',
      questionText: 'Pengolesan asam fosfat 37% pada enamel sebelum penambalan komposit dinamakan proses:',
      options: ['Etsa Asam (Etching)', 'Bonding', 'Polishing', 'Beveling'],
      correctOptionIndex: 0,
      explanation: 'Etsa membentuk mikro-porositas mekanis pada enamel.',
    ),
    QuestionItem(
      id: 'kg_074',
      questionText: 'Pengolesan bahan perekat cair setelah etsa pada penambalan komposit dinamakan:',
      options: ['Bonding Agent / Primer', 'Etsa', 'Curing', 'Silane'],
      correctOptionIndex: 0,
      explanation: 'Bonding meresap ke dalam mikroporositas etsa untuk retensi komposit.',
    ),
    QuestionItem(
      id: 'kg_075',
      questionText: 'Alat bantu berupa lembaran karet isolasi kedap air untuk menjaga area kerja operasi gigi tetap kering dinamakan:',
      options: ['Rubber Dam / Dental Dam', 'Matrix Band', 'Articulating Paper', 'Cotton Roll'],
      correctOptionIndex: 0,
      explanation: 'Rubber dam megunisolasi gigi dari kontaminasi air liur.',
    ),
    QuestionItem(
      id: 'kg_076',
      questionText: 'Kertas penanda warna untuk mengecek kontak gigitan oklusal antara gigi atas dan bawah dinamakan:',
      options: ['Articulating Paper', 'Celluloid Strip', 'Wedge', 'Matrix Band'],
      correctOptionIndex: 0,
      explanation: 'Articulating paper membekas warna pada titik kontak peninggian gigitan.',
    ),
    QuestionItem(
      id: 'kg_077',
      questionText: 'Restorasi mahkota tiruan penuh yang membungkus seluruh permukaan gigi yang rusak berat dinamakan:',
      options: ['Crown / Mahkota Tiruan', 'Inlay', 'Onlay', 'Veneer'],
      correctOptionIndex: 0,
      explanation: 'Crown mengembalikan bentuk dan kekuatan gigi rusak.',
    ),
    QuestionItem(
      id: 'kg_078',
      questionText: 'Gigi tiruan cekat yang menjembatani ruang kosong bekas gigi hilang dengan bersandar pada gigi tetangga dinamakan:',
      options: ['Bridge / Jembatan Gigi', 'Gigi Tiruan Lepasan', 'Implan', 'Crown'],
      correctOptionIndex: 0,
      explanation: 'Bridge menyambungkan gigi penyangga (abutment) memegang gigi tiruan (pontik).',
    ),
    QuestionItem(
      id: 'kg_079',
      questionText: 'Elemen gigi tiruan yang menggantikan gigi asli yang hilang pada sediaan bridge dinamakan:',
      options: ['Pontik', 'Abutment', 'Crown', 'Casp'],
      correctOptionIndex: 0,
      explanation: 'Pontik adalah bagian gigi tiruan gantung penutup celah.',
    ),
    QuestionItem(
      id: 'kg_080',
      questionText: 'Gigi asli penyangga yang diasah untuk memegang pontik pada sediaan bridge dinamakan:',
      options: ['Abutment', 'Pontik', 'Implant', 'Inlay'],
      correctOptionIndex: 0,
      explanation: 'Abutment menerima beban gigitan dari pontik.',
    ),
    QuestionItem(
      id: 'kg_081',
      questionText: 'Kondisi perubahan warna gigi menjadi kekuningan/kecokelatan akibat konsumsi obat antibiotik semasa pembentukan benih gigi adalah:',
      options: ['Stain Tetrasiklin', 'Fluorosis', 'Karies', 'Amelogenesis Imperfekta'],
      correctOptionIndex: 0,
      explanation: 'Tetrasiklin mengikat kalsium membentuk garis cokelat permanen pada dentin.',
    ),
    QuestionItem(
      id: 'kg_082',
      questionText: 'Kondisi bercak putih atau kecokelatan pada enamel akibat asupan fluorida berlebih semasa pertumbuhan gigi dinamakan:',
      options: ['Fluorosis Gigi', 'Stain Tetrasiklin', 'Erosi', 'Hypoplasia'],
      correctOptionIndex: 0,
      explanation: 'Fluorosis terjadi akibat konsumsi konsentrasi fluor tinggi pada air minum anak.',
    ),
    QuestionItem(
      id: 'kg_083',
      questionText: 'Kelainan genetik pembentukan enamel yang membuat gigi rapuh berwarna kuning kecokelatan dinamakan:',
      options: ['Amelogenesis Imperfekta', 'Dentinogenesis Imperfekta', 'Odontoma', 'Taurodontisme'],
      correctOptionIndex: 0,
      explanation: 'Amelogenesis imperfekta adalah cacat hereditas pembentukan enamel.',
    ),
    QuestionItem(
      id: 'kg_084',
      questionText: 'Kelainan genetik pembentukan dentin yang membuat gigi tampak transparan keputihan keabuan dinamakan:',
      options: ['Dentinogenesis Imperfekta', 'Amelogenesis Imperfekta', 'Fluorosis', 'Peg-Shaped'],
      correctOptionIndex: 0,
      explanation: 'Dentinogenesis imperfekta merusak struktur matriks dentin.',
    ),
    QuestionItem(
      id: 'kg_085',
      questionText: 'Bentuk gigi insisivus samping rahang atas yang mengalami kelainan mengecil seperti pasak dinamakan:',
      options: ['Peg-Shaped Incisor', 'Microdontia', 'Taurodontism', 'Gemination'],
      correctOptionIndex: 0,
      explanation: 'Peg-shaped lateral incisor berbentuk runcing kecil seperti pasak.',
    ),
    QuestionItem(
      id: 'kg_086',
      questionText: 'Kondisi dua benih gigi yang menyatu menjadi satu gigi besar dengan dua saluran akar dinamakan:',
      options: ['Fusi Gigi', 'Geminsi Gigi', 'Konkresens', 'Dilaserasi'],
      correctOptionIndex: 0,
      explanation: 'Fusi adalah penyatuan dua benih gigi terpisah.',
    ),
    QuestionItem(
      id: 'kg_087',
      questionText: 'Kondisi satu benih gigi membelah mencoba menjadi dua mahkota dengan satu saluran akar dinamakan:',
      options: ['Geminasi Gigi', 'Fusi Gigi', 'Taurodontisme', 'Dens In Dente'],
      correctOptionIndex: 0,
      explanation: 'Geminasi membelah mahkota tunggal dari 1 benih.',
    ),
    QuestionItem(
      id: 'kg_088',
      questionText: 'Kondisi pembengkokan tajam abnormal pada akar atau mahkota gigi dinamakan:',
      options: ['Dilaserasi Akar', 'Konkresens', 'Taurodontisme', 'Exostosis'],
      correctOptionIndex: 0,
      explanation: 'Dilaserasi adalah trauma/gangguan pembentukan yang membengkokkan akar gigi.',
    ),
    QuestionItem(
      id: 'kg_089',
      questionText: 'Pertumbuhan penonjolan tulang bening jinak pada rahang atas tengah dinamakan:',
      options: ['Torus Palatinus', 'Torus Mandibularis', 'Osteoma', 'Exostosis'],
      correctOptionIndex: 0,
      explanation: 'Torus palatinus adalah variasi normal penonjolan tulang palatum.',
    ),
    QuestionItem(
      id: 'kg_090',
      questionText: 'Penonjolan tulang jinak pada sisi lingual rahang bawah daerah premolar dinamakan:',
      options: ['Torus Mandibularis', 'Torus Palatinus', 'Odontoma', 'Exostosis'],
      correctOptionIndex: 0,
      explanation: 'Torus mandibularis tumbuh di sisi lingual mandibula.',
    ),
    QuestionItem(
      id: 'kg_091',
      questionText: 'Pencabutan gigi secara bedah dengan pembuatan flep mukosa dan pemotongan tulang dinamakan:',
      options: ['Eksodontia Bedah / Odontektomi', 'Ekstraksi Sederhana', 'Enukleasi', 'Curettage'],
      correctOptionIndex: 0,
      explanation: 'Odontektomi dilakukan untuk pencabutan gigi impaksi terhalang tulang.',
    ),
    QuestionItem(
      id: 'kg_092',
      questionText: 'Komplikasi nyeri hebat pasca pencabutan gigi akibat lepasnya bekuan darah dari socket dinamakan:',
      options: ['Dry Socket (Alveolar Osteitis)', 'Pulpitis', 'Abses', 'Hematoma'],
      correctOptionIndex: 0,
      explanation: 'Dry socket memaparkan tulang alveolar tanpa perlindungan bekuan darah.',
    ),
    QuestionItem(
      id: 'kg_093',
      questionText: 'Alat tang pencabut gigi dinamakan forceps ekstraksi, sedangkan alat pengungkit gigi dinamakan:',
      options: ['Bein / Bein Elevator', 'Scaler', 'Sonde', 'Excavator'],
      correctOptionIndex: 0,
      explanation: 'Bein (elevator) mengungkit dan melonggarkan gigi dari socketnya.',
    ),
    QuestionItem(
      id: 'kg_094',
      questionText: 'Alat tajam berujung sendok kecil untuk mengerok karies lunak pada gigi dinamakan:',
      options: ['Ekskavator', 'Sonde', 'Pinset Kaca', 'Kapor'],
      correctOptionIndex: 0,
      explanation: 'Ekskavator mengerok jaringan dentin karies yang pelunak.',
    ),
    QuestionItem(
      id: 'kg_095',
      questionText: 'Alat berujung lancip untuk mendeteksi adanya lubang karies pada permukaan gigi dinamakan:',
      options: ['Sonde Gigi (Explorer)', 'Kaca Mulut', 'Pinset Dental', 'Scaler'],
      correctOptionIndex: 0,
      explanation: 'Sonde meraba kedalaman karies dan celah enamel.',
    ),
    QuestionItem(
      id: 'kg_096',
      questionText: 'Alat bulat cermin kecil untuk melihat area tersembunyi dalam rongga mulut dinamakan:',
      options: ['Kaca Mulut (Mouth Mirror)', 'Sonde', 'Pinset', 'Probe'],
      correctOptionIndex: 0,
      explanation: 'Kaca mulut memantulkan cahaya dan melihat bagian posterior.',
    ),
    QuestionItem(
      id: 'kg_097',
      questionText: 'Alat ukur bergaris milimeter untuk mengukur kedalaman saku gusi (periodontal pocket) dinamakan:',
      options: ['Periodontal Probe', 'Sonde', 'Bein', 'Ekskavator'],
      correctOptionIndex: 0,
      explanation: 'Periodontal probe mengukur milimeter kedalaman poket periodontal.',
    ),
    QuestionItem(
      id: 'kg_098',
      questionText: 'Kedalaman ceruk gusi (sulkus gingiva) normal tanpa penyakit adalah:',
      options: ['1 mm hingga 3 mm', '4 mm hingga 6 mm', '7 mm hingga 9 mm', '> 10 mm'],
      correctOptionIndex: 0,
      explanation: 'Sulkus gingiva sehat berukuran 1-3 mm.',
    ),
    QuestionItem(
      id: 'kg_099',
      questionText: 'Kedalaman saku gusi >4 mm mengindikasikan adanya penyakit:',
      options: ['Periodontitis (Poket Periodontal)', 'Gingivitis', 'Karies', 'Pulpitis'],
      correctOptionIndex: 0,
      explanation: 'Poket >4mm menunjukkan hilangnya perlekatan jaringan periodontium.',
    ),
    QuestionItem(
      id: 'kg_100',
      questionText: 'Bahan cetak kedokteran gigi hidrokoloid ireversibel berbahan dasar rumput laut untuk membuat model studi adalah:',
      options: ['Alginat', 'Elastomer', 'Gips', 'Compound'],
      correctOptionIndex: 0,
      explanation: 'Alginat adalah bahan mencetak rongga mulut paling umum dipraktikkan.',
    ),
  ];
}
