import '../tes_seleksi_model.dart';

List<QuestionItem> getFarmasiQuestions() {
  return const [
    QuestionItem(
      id: 'far_001',
      questionText: 'Singkatan ADME dalam bidang Farmakokinetika adalah singkatan dari:',
      options: ['Absorpsi, Distribusi, Metabolisme, Eksresi', 'Analisis, Dosis, Mutu, Efek', 'Aplikasi, Diagnosa, Medis, Evaluasi', 'Akumulasi, Difusi, Membran, Eliminasi'],
      correctOptionIndex: 0,
      explanation: 'ADME singkatan dari Absorpsi, Distribusi, Metabolisme, dan Eksresi.',
    ),
    QuestionItem(
      id: 'far_002',
      questionText: 'Proses masuknya obat dari tempat pemberian ke dalam sirkulasi sistemik darah dinamakan:',
      options: ['Absorpsi', 'Distribusi', 'Metabolisme', 'Eksresi'],
      correctOptionIndex: 0,
      explanation: 'Absorpsi adalah perpindahan obat dari site of administration ke aliran darah.',
    ),
    QuestionItem(
      id: 'far_003',
      questionText: 'Organ utama tempat berlangsungnya biotransformasi (metabolisme) obat adalah:',
      options: ['Ginjal', 'Hati (Hepar)', 'Paru-paru', 'Usus Halus'],
      correctOptionIndex: 1,
      explanation: 'Hati adalah organ metabolizing utama yang kaya enzim Sitokrom P450.',
    ),
    QuestionItem(
      id: 'far_004',
      questionText: 'Organ ekskresi utama untuk mengeliminasi sisa obat terlarut dalam air adalah:',
      options: ['Ginjal', 'Hati', 'Kulit', 'Empedu'],
      correctOptionIndex: 0,
      explanation: 'Ginjal mengeluarkan metabolit obat via urin.',
    ),
    QuestionItem(
      id: 'far_005',
      questionText: 'Buku standar resmi farmasi di Indonesia yang berisi persyarakatan mutu bahan obat dinamakan:',
      options: ['Farmakope Indonesia', 'ISO Indonesia', 'MIMS Indonesia', 'Formularium Nasional'],
      correctOptionIndex: 0,
      explanation: 'Farmakope Indonesia (FI) adalah pedoman kompedial resmi mutu obat.',
    ),
    QuestionItem(
      id: 'far_006',
      questionText: 'Persentase fraksi obat aktif yang berhasil mencapai sirkulasi darah sistemik dinamakan:',
      options: ['Bioavailabilitas (Ketersediaan Hayati)', 'Bioekivalensi', 'Klirens', 'Volume Distribusi'],
      correctOptionIndex: 0,
      explanation: 'Bioavailabilitas mengukur laju & jumlah obat mencapai sirkulasi sistemik.',
    ),
    QuestionItem(
      id: 'far_007',
      questionText: 'Rute pemberian obat yang menghasilkan bioavailabilitas 100% adalah:',
      options: ['Intra Vena (IV)', 'Oral', 'Subkutan', 'Intra Muskular'],
      correctOptionIndex: 0,
      explanation: 'Rute IV langsung masuk ke sirkulasi darah tanpa eliminasi pintas pertama.',
    ),
    QuestionItem(
      id: 'far_008',
      questionText: 'Efek metabolisme lintasan pertama (First-Pass Effect) terjadi terutama saat obat diberikan secara:',
      options: ['Oral', 'Intra Vena', 'Sublingual', 'Transdermal'],
      correctOptionIndex: 0,
      explanation: 'Obat oral diserap usus dan langsung melewati hati via vena porta.',
    ),
    QuestionItem(
      id: 'far_009',
      questionText: 'Kelompok enzim utama di hati yang memetabolisme sebagian besar zat obat adalah:',
      options: ['Sitokrom P450 (CYP450)', 'Amilase', 'Lipase', 'Polimerase'],
      correctOptionIndex: 0,
      explanation: 'CYP450 memetabolisme mayoritas obat asing dalam tubuh (xenobiotik).',
    ),
    QuestionItem(
      id: 'far_010',
      questionText: 'Bahan tambahan farmasi yang berfungsi memadatkan dan memberikan bentuk pada tablet dinamakan:',
      options: ['Pengisi (Diluent)', 'Pengikat (Binder)', 'Penghancur (Disintegrant)', 'Pelicin (Lubricant)'],
      correctOptionIndex: 0,
      explanation: 'Pengisi (misal laktosa, avicel) menambah bobot volume tablet.',
    ),
    QuestionItem(
      id: 'far_011',
      questionText: 'Bahan eksipien tablet yang membantu tablet pecah di dalam lambung adalah:',
      options: ['Penghancur (Disintegrant)', 'Pengikat', 'Pengisi', 'Pelicin'],
      correctOptionIndex: 0,
      explanation: 'Disintegrant (misal amylum) membantu disintegrasi sediaan tablet.',
    ),
    QuestionItem(
      id: 'far_012',
      questionText: 'Sediaan obat cair yang mengandung zat aktif tidak larut dan terdispersi dalam fase cair dinamakan:',
      options: ['Suspesi', 'Emulsi', 'Sirup', 'Eliksir'],
      correctOptionIndex: 0,
      explanation: 'Suspensi adalah sistem heterogen partikel padat tidak larut dalam cairan.',
    ),
    QuestionItem(
      id: 'far_013',
      questionText: 'Sediaan heterogen yang terdiri dari dua cairan tak tercampur (minyak dan air) dinamakan:',
      options: ['Emulsi', 'Suspensi', 'Larutan', 'Infus'],
      correctOptionIndex: 0,
      explanation: 'Emulsi membutuhkan emulgator untuk menstabilkan fase minyak dan air.',
    ),
    QuestionItem(
      id: 'far_014',
      questionText: 'Zat pembawa atau emulgator yang menstabilkan emulsi dinamakan:',
      options: ['Surfaktan', 'Pengawet', 'Antioksidan', 'Buffering agent'],
      correctOptionIndex: 0,
      explanation: 'Surfaktan menurunkan tegangan antarmuka minyak-air.',
    ),
    QuestionItem(
      id: 'far_015',
      questionText: 'Ilmu yang mempelajari obat-obatan dari bahan alam (tumbuhan, hewan, mineral) dinamakan:',
      options: ['Farmakognosi', 'Farmakologi', 'Farmasi Fisik', 'Toksikologi'],
      correctOptionIndex: 0,
      explanation: 'Farmakognosi mengkaji sifat fisika, kimia, dan biologi bahan alam obat.',
    ),
    QuestionItem(
      id: 'far_016',
      questionText: 'Senyawa metabolit sekunder tanaman berupa zat pahit beratom nitrogen yang bersifat basa adalah:',
      options: ['Alkaloid', 'Flavonoid', 'Tanin', 'Saponin'],
      correctOptionIndex: 0,
      explanation: 'Alkaloid mengandung nitrogen dan umumnya berasa pahit (misal kafein, morfin).',
    ),
    QuestionItem(
      id: 'far_017',
      questionText: 'Senyawa bahan alam tanaman yang membentuk busa atau buih saat dikocok dalam air dinamakan:',
      options: ['Saponin', 'Flavonoid', 'Alkaloid', 'Minyak Atsiri'],
      correctOptionIndex: 0,
      explanation: 'Saponin memiliki sifat seperti sabun yang berbusa.',
    ),
    QuestionItem(
      id: 'far_018',
      questionText: 'Kelarutan obat yang bersifat asam lemah akan meningkat pada suasana pH:',
      options: ['Basa / Alkalis', 'Sangat Asam', 'Netral 7.0', 'Tidak terpengaruh pH'],
      correctOptionIndex: 0,
      explanation: 'Asam lemah terionisasi pada pH basa, sehingga kelarutannya naik.',
    ),
    QuestionItem(
      id: 'far_019',
      questionText: 'Waktu yang diperlukan kadar obat dalam darah untuk berkurang menjadi separuh nilai awalnya dinamakan:',
      options: ['Waktu Paruh (t 1/2)', 'Onset of Action', 'Duration of Action', 'Steady State'],
      correctOptionIndex: 0,
      explanation: 'Waktu paruh eliminasi (t 1/2) adalah durasi penurunan konsentrasi 50%.',
    ),
    QuestionItem(
      id: 'far_020',
      questionText: 'Reaksi obat yang berikatan dengan reseptor dan memicu respon biologis penuh dinamakan:',
      options: ['Agonis', 'Antagonis', 'Inhibitor', 'Placebo'],
      correctOptionIndex: 0,
      explanation: 'Agonis mengaktifkan reseptor memicu efek biologis.',
    ),
    QuestionItem(
      id: 'far_021',
      questionText: 'Obat yang memblokir atau menghalangi kerja reseptor tanpa menghasilkan efek dinamakan:',
      options: ['Antagonis', 'Agonis', 'Synergist', 'Prodrug'],
      correctOptionIndex: 0,
      explanation: 'Antagonis menduduki reseptor dan menghalangi penempelan agonis.',
    ),
    QuestionItem(
      id: 'far_022',
      questionText: 'Bentuk sediaan padat berbentuk meluru/lonjong yang dimasukkan melalui rektum dinamakan:',
      options: ['Supositoria', 'Ovula', 'Kaplet', 'Pil'],
      correctOptionIndex: 0,
      explanation: 'Supositoria meleleh pada suhu tubuh di dalam rektum.',
    ),
    QuestionItem(
      id: 'far_023',
      questionText: 'Sediaan padat steril yang mengandung zat cair yang dimasukkan melalui vagina dinamakan:',
      options: ['Ovula', 'Supositoria', 'Pessari / Ovula', 'Bolus'],
      correctOptionIndex: 2,
      explanation: 'Ovula/Pessari adalah sediaan rute vaginal.',
    ),
    QuestionItem(
      id: 'far_024',
      questionText: 'Indeks terapi obat (Therapeutic Index) yang sempit berarti obat tersebut:',
      options: ['Memiliki batas keamanan dosis yang sangat ketat dan rawan toksik', 'Sangat aman digunakan tanpa resep', 'Tidak memiliki efek samping', 'Memiliki durasi kerja sangat panjang'],
      correctOptionIndex: 0,
      explanation: 'Indeks terapi sempit (misal Digoksin, Fenitoin) membutuhkan monitoring dosis ketat.',
    ),
    QuestionItem(
      id: 'far_025',
      questionText: 'Istilah "Prodrug" dalam ilmu farmasi mengacu pada:',
      options: ['Senyawa tak aktif yang akan dikonversi menjadi obat aktif di dalam tubuh', 'Obat ilegal', 'Obat generasi pertama', 'Obat herbal terstandar'],
      correctOptionIndex: 0,
      explanation: 'Prodrug aktif setelah dimetabolisme di organ (misal enalapril jadi enalaprilat).',
    ),
    QuestionItem(
      id: 'far_026',
      questionText: 'Singkatan "o.d" atau "q.d" pada penulisan resep dokter berarti:',
      options: ['Sekali sehari (Omni die / quaque die)', 'Dua kali sehari', 'Tiga kali sehari', 'Sebelum makan'],
      correctOptionIndex: 0,
      explanation: 'omni die (o.d) artinya tiap hari / 1x sehari.',
    ),
    QuestionItem(
      id: 'far_027',
      questionText: 'Singkatan "t.i.d" (ter in die) pada aturan pakai resep berarti:',
      options: ['Tiga kali sehari', 'Dua kali sehari', 'Empat kali sehari', 'Jika perlu'],
      correctOptionIndex: 0,
      explanation: 'ter in die = 3 kali sehari.',
    ),
    QuestionItem(
      id: 'far_028',
      questionText: 'Singkatan "p.r.n" (pro re nata) pada resep obat berarti:',
      options: ['Jika diperlukan / bila perlu', 'Segera (Cito)', 'Sebelum makan (Ante Coenam)', 'Sesudah makan (Post Coenam)'],
      correctOptionIndex: 0,
      explanation: 'pro re nata artinya obat diminum jika gejala muncul/bila perlu.',
    ),
    QuestionItem(
      id: 'far_029',
      questionText: 'Singkatan "a.c" (ante coenam) dalam aturan minum obat berarti:',
      options: ['Sebelum makan', 'Setelah makan', 'Saat makan', 'Sebelum tidur'],
      correctOptionIndex: 0,
      explanation: 'ante coenam = sebelum makan.',
    ),
    QuestionItem(
      id: 'far_030',
      questionText: 'Singkatan "p.c" (post coenam) dalam aturan minum obat berarti:',
      options: ['Setelah makan', 'Sebelum makan', 'Saat makan', 'Tiap malam'],
      correctOptionIndex: 0,
      explanation: 'post coenam = setelah makan.',
    ),
    QuestionItem(
      id: 'far_031',
      questionText: 'Metode ekstraksi bahan alam tanaman menggunakan pelarut yang mendidih secara kontinyu dinamakan:',
      options: ['Maserasi', 'Sokletasi', 'Perkolasi', 'Infus'],
      correctOptionIndex: 1,
      explanation: 'Sokletasi ekstraksi kontinu menggunakan alat Soxhlet.',
    ),
    QuestionItem(
      id: 'far_032',
      questionText: 'Metode ekstraksi dingin dengan merendam simplisia tanaman dalam pelarut selama beberapa hari dinamakan:',
      options: ['Maserasi', 'Dekok', 'Refluks', 'Destilasi'],
      correctOptionIndex: 0,
      explanation: 'Maserasi merendam tanaman tanpa pemanasan.',
    ),
    QuestionItem(
      id: 'far_033',
      questionText: 'Golongan obat analgesik antiinflamasi non-steroid (OAINS/NSAID) bekerja menghambat enzim:',
      options: ['Siklooksigenase (COX-1 & COX-2)', 'Lipoksigenase', 'HMG-CoA Reduktase', 'ACE'],
      correctOptionIndex: 0,
      explanation: 'NSAID (seperti Ibuprofen, Asam Mefenamat) menghambat sintesis prostaglandin via COX.',
    ),
    QuestionItem(
      id: 'far_034',
      questionText: 'Obat penurun kolesterol golongan Statin bekerja dengan cara menghambat enzim:',
      options: ['HMG-CoA Reduktase', 'Siklooksigenase', 'Angiotensin Converting Enzyme', 'Xantin Oksidase'],
      correctOptionIndex: 0,
      explanation: 'Statin (Simvastatin, Atorvastatin) memblokir HMG-CoA reduktase.',
    ),
    QuestionItem(
      id: 'far_035',
      questionText: 'Golongan antibiotik Penisilin dan Sefalosporin bekerja mematikan bakteri dengan mekanisme:',
      options: ['Menghambat sintesis dinding sel bakteri', 'Menghambat sintesis protein 30S', 'Menghambat replikasi DNA', 'Merusak membran sel'],
      correctOptionIndex: 0,
      explanation: 'Beta-laktam merusak cincin peptidoglikan dinding sel.',
    ),
    QuestionItem(
      id: 'far_036',
      questionText: 'Golongan antibiotik Kuinolon (misal Siprofloksasin) bekerja menghambat enzim bakteri:',
      options: ['DNA Girase / Topoisomerase IV', 'Beta-laktamase', 'Dihidrofolat Reduktase', 'RNA Polimerase'],
      correctOptionIndex: 0,
      explanation: 'Kuinolon menghambat DNA girase mencegah replikasi DNA.',
    ),
    QuestionItem(
      id: 'far_037',
      questionText: 'Penggunaan antibiotik berlebihan tanpa resep memicu ancaman kesehatan global berupa:',
      options: ['Resistensi Antibiotik', 'Ketergantungan Psikologis', 'Toleransi Obat', 'Alergi Sistemik'],
      correctOptionIndex: 0,
      explanation: 'Resistensi antimikroba (AMR) membuat bakteri kebal terhadap obat.',
    ),
    QuestionItem(
      id: 'far_038',
      questionText: 'Kondisi di mana dosis obat yang sama memberikan respon yang semakin menurun dari waktu ke waktu disebut:',
      options: ['Toleransi Obat', 'Takifilaksis', 'Adiksi', 'Resistensi'],
      correctOptionIndex: 0,
      explanation: 'Toleransi membutuhkan desensitisasi reseptor atau peningkatan dosis.',
    ),
    QuestionItem(
      id: 'far_039',
      questionText: 'Toleransi cepat yang terjadi dalam waktu sangat singkat setelah pemberian beberapa dosis obat dinamakan:',
      options: ['Takifilaksis', 'Toleransi Kronis', 'Resistensi', 'Idiosinkrasi'],
      correctOptionIndex: 0,
      explanation: 'Takifilaksis adalah penurunan respon obat yang sangat cepat.',
    ),
    QuestionItem(
      id: 'far_040',
      questionText: 'Simbol lingkaran hijau dengan garis tepi hitam pada kemasan obat menandakan golongan:',
      options: ['Obat Bebas', 'Obat Bebas Terbatas', 'Obat Keras', 'Narkotika'],
      correctOptionIndex: 0,
      explanation: 'Lingkaran hijau melambangkan Obat Bebas tanpa resep.',
    ),
    QuestionItem(
      id: 'far_041',
      questionText: 'Simbol lingkaran biru dengan garis tepi hitam pada kemasan obat menandakan golongan:',
      options: ['Obat Bebas Terbatas', 'Obat Bebas', 'Obat Keras', 'Obat Psikotropika'],
      correctOptionIndex: 0,
      explanation: 'Lingkaran biru adalah Obat Bebas Terbatas disertai tanda peringatan P.No 1 - 6.',
    ),
    QuestionItem(
      id: 'far_042',
      questionText: 'Simbol lingkaran merah dengan huruf K di tengahnya menandakan golongan:',
      options: ['Obat Keras & Psikotropika', 'Obat Bebas', 'Obat Bebas Terbatas', 'Jamu'],
      correctOptionIndex: 0,
      explanation: 'Lingkaran merah huruf K adalah Obat Keras wajib resep dokter.',
    ),
    QuestionItem(
      id: 'far_043',
      questionText: 'Simbol Palang Merah dalam lingkaran putih dengan tepi merah menandakan golongan obat:',
      options: ['Narkotika', 'Obat Keras', 'Obat Tradisional', 'Fitofarmaka'],
      correctOptionIndex: 0,
      explanation: 'Tanda palang merah menggolongkan obat Narkotika.',
    ),
    QuestionItem(
      id: 'far_044',
      questionText: 'Obat tradisional Indonesia yang telah dibuktikan keamanan dan khasiatnya secara ilmiah melalui uji klinis dinamakan:',
      options: ['Fitofarmaka', 'Obat Herbal Terstandar (OHT)', 'Jamu', 'Ekstrak Herbal'],
      correctOptionIndex: 0,
      explanation: 'Fitofarmaka merupakan kasta tertinggi obat tradisional dengan uji klinis manusia.',
    ),
    QuestionItem(
      id: 'far_045',
      questionText: 'Obat tradisional yang telah dibuktikan khasiatnya melalui uji praklinis pada hewan coba dinamakan:',
      options: ['Obat Herbal Terstandar (OHT)', 'Fitofarmaka', 'Jamu', 'Suplemen'],
      correctOptionIndex: 0,
      explanation: 'OHT lolos standarisasi bahan baku dan uji pra-klinis hewan.',
    ),
    QuestionItem(
      id: 'far_046',
      questionText: 'Obat tradisional yang bukti khasiatnya berdasarkan pengalaman empiris turun-temurun dinamakan:',
      options: ['Jamu', 'OHT', 'Fitofarmaka', 'Homeopati'],
      correctOptionIndex: 0,
      explanation: 'Jamu berbasis bukti empiris historis.',
    ),
    QuestionItem(
      id: 'far_047',
      questionText: 'Pengujian calon obat baru pada sukarelawan manusia sehat untuk menilai keamanan dan tolerabilitas masuk fase:',
      options: ['Uji Klinis Fase 1', 'Uji Klinis Fase 2', 'Uji Klinis Fase 3', 'Uji Klinis Fase 4'],
      correctOptionIndex: 0,
      explanation: 'Fase 1 menguji toksisitas & pharmacokinetics pada subjek sehat (20-100 orang).',
    ),
    QuestionItem(
      id: 'far_048',
      questionText: 'Uji klinis fase berapa yang bertujuan mengevaluasi efikasi terapi obat pada sampel pasien sakit terbatas?',
      options: ['Uji Klinis Fase 2', 'Uji Klinis Fase 1', 'Uji Klinis Fase 3', 'Uji Praklinis'],
      correctOptionIndex: 0,
      explanation: 'Fase 2 menguji efikasi pada skala pasien terbatas (100-300 orang).',
    ),
    QuestionItem(
      id: 'far_049',
      questionText: 'Pengawasan keamanan obat setelah resmi dipasarkan di masyarakat (Post-Marketing Surveillance) merupakan uji:',
      options: ['Uji Klinis Fase 4', 'Uji Klinis Fase 3', 'Uji Praklinis', 'Uji Toksisitas Akut'],
      correctOptionIndex: 0,
      explanation: 'Fase 4 melacak efek samping langka pasca edar (Pharmacovigilance).',
    ),
    QuestionItem(
      id: 'far_050',
      questionText: 'Kondisi ketidaksesuaian sifat fisika atau kimia saat dua obat dicampurkan dalam sediaan dinamakan:',
      options: ['Inkompatibilitas', 'Intersosialisasi', 'Synergisme', 'Potensiasi'],
      correctOptionIndex: 0,
      explanation: 'Inkompatibilitas memicu endapan, perubahan warna, atau inaktivasi bahan.',
    ),
    QuestionItem(
      id: 'far_051',
      questionText: 'Suatu senyawa aktif obat yang dipatenkan dan diproduksi produsen penemu dinamakan obat:',
      options: ['Obat Paten', 'Obat Generik Berlogo', 'Obat Generik Bermerek', 'Obat Esensial'],
      correctOptionIndex: 0,
      explanation: 'Obat Paten memiliki perlindungan hak paten eksklusif.',
    ),
    QuestionItem(
      id: 'far_052',
      questionText: 'Obat yang menggunakan nama resmi zat aktif sesuai International Nonproprietary Name dinamakan obat:',
      options: ['Obat Generik', 'Obat Paten', 'Obat Tradisional', 'Obat Lisensi'],
      correctOptionIndex: 0,
      explanation: 'Obat generik menggunakan nama zat aktif resminya (misal Parasetamol).',
    ),
    QuestionItem(
      id: 'far_053',
      questionText: 'Interaksi obat di mana efek gabungan dua obat lebih besar daripada jumlah efek masing-masing dinamakan:',
      options: ['Sinergisme / Potensiasi', 'Antagonisme', 'Toleransi', 'Inaktivasi'],
      correctOptionIndex: 0,
      explanation: 'Sinergisme/Potensiasi melipatgandakan efek obat.',
    ),
    QuestionItem(
      id: 'far_054',
      questionText: 'Antidotum spesifik yang digunakan untuk menangani keracunan/overdosis obat opioid (seperti Morfin/Heroin) adalah:',
      options: ['Nalokson', 'Atropin', 'N-Asetilsistein', 'Flumazenil'],
      correctOptionIndex: 0,
      explanation: 'Nalokson adalah antagonis spesifik reseptor opioid.',
    ),
    QuestionItem(
      id: 'far_055',
      questionText: 'Antidotum spesifik yang digunakan untuk penanganan keracunan parasetamol (asetaminofen) adalah:',
      options: ['N-Asetilsistein (NAC)', 'Nalokson', 'Atropin', 'Dimerkaprol'],
      correctOptionIndex: 0,
      explanation: 'N-Asetilsistein meregenerasi glutation pencegah hepatotoksik parasetamol.',
    ),
    QuestionItem(
      id: 'far_056',
      questionText: 'Antidotum untuk keracunan pestisida organofosfat adalah:',
      options: ['Atropin & Pralidoksim', 'Nalokson', 'Kalsium Glukonat', 'Protamin Sulfat'],
      correctOptionIndex: 0,
      explanation: 'Atropin memblokir kelebihan asetilkolin akibat penghambatan kolinesterase.',
    ),
    QuestionItem(
      id: 'far_057',
      questionText: 'Antidotum untuk menetralkan efek berlebih dari antikoagulan Heparin adalah:',
      options: ['Protamin Sulfat', 'Vitamin K', 'Nalokson', 'Deferoksamin'],
      correctOptionIndex: 0,
      explanation: 'Protamin sulfat mengikat dan membatalkan kerja heparin.',
    ),
    QuestionItem(
      id: 'far_058',
      questionText: 'Antidotum untuk menetralkan racun antikoagulan Warfarin adalah:',
      options: ['Vitamin K1 (Fitomenadion)', 'Protamin Sulfat', 'Atropin', 'Asetilsistein'],
      correctOptionIndex: 0,
      explanation: 'Vitamin K merangsang kembali sintesis faktor pembekuan darah.',
    ),
    QuestionItem(
      id: 'far_059',
      questionText: 'Bentuk sediaan cair khusus untuk dioleskan pada kulit tanpa digosok keras dinamakan:',
      options: ['Lotion', 'Linimentum', 'Unguentum', 'Pasta'],
      correctOptionIndex: 0,
      explanation: 'Lotion merupakan suspensi/emulsi cair kulit.',
    ),
    QuestionItem(
      id: 'far_060',
      questionText: 'Sediaan setengah padat yang mengandung persentase serbuk padat tinggi (>50%) dinamakan:',
      options: ['Pasta', 'Salep (Unguentum)', 'Krim', 'Gel'],
      correctOptionIndex: 0,
      explanation: 'Pasta memiliki konsistensi kental karena serbuk padat yang melimpah.',
    ),
    QuestionItem(
      id: 'far_061',
      questionText: 'Salep berbasis air yang transparan dan jernih mengandalkan bahan gelling agent dinamakan:',
      options: ['Gel / Jelly', 'Krim', 'Pasta', 'Cerata'],
      correctOptionIndex: 0,
      explanation: 'Gel menggunakan polimer hidrofilik membentuk matriks jernih.',
    ),
    QuestionItem(
      id: 'far_062',
      questionText: 'Pemberian obat dengan cara diselipkan di bawah lidah dinamakan rute:',
      options: ['Sublingual', 'Bukal', 'Oral', 'Inhalasi'],
      correctOptionIndex: 0,
      explanation: 'Sublingual diserap cepat oleh pembuluh darah bawah lidah tanpa perantara pencernaan.',
    ),
    QuestionItem(
      id: 'far_063',
      questionText: 'Pemberian obat dengan disisipkan di antara pipi dan gusi dinamakan rute:',
      options: ['Bukal', 'Sublingual', 'Topikal', 'Transdermal'],
      correctOptionIndex: 0,
      explanation: 'Bukal diserap melalui mukosa pipi.',
    ),
    QuestionItem(
      id: 'far_064',
      questionText: 'Uji disolusi obat tablet bertujuan untuk mengukur:',
      options: ['Kecepatan pelepasan dan melarutnya zat aktif dalam media cair', 'Kekerasan mekanik tablet', 'Kerapuhan tablet saat pengiriman', 'Keseragaman bobot tablet'],
      correctOptionIndex: 0,
      explanation: 'Uji disolusi menentukan laju kelarutan zat aktif obat.',
    ),
    QuestionItem(
      id: 'far_065',
      questionText: 'Alat pengukur kerapuhan tablet akibat gesekan dinamakan:',
      options: ['Friabilites Tester / Friabilator', 'Hardness Tester', 'Disintegration Tester', 'Dissolution Tester'],
      correctOptionIndex: 0,
      explanation: 'Friabilator mengukur persentase kehilangan bobot tablet akibat gesekan.',
    ),
    QuestionItem(
      id: 'far_066',
      questionText: 'Kategori kehamilan risiko obat skala FDA di mana uji pada manusia menunjukkan bukti risiko pada janin namun manfaatnya dapat diterima dinamakan Kategori:',
      options: ['Kategori D', 'Kategori A', 'Kategori B', 'Kategori X'],
      correctOptionIndex: 0,
      explanation: 'Kategori D ada bukti risiko janin manusia namun ada indikasi penanganan darurat.',
    ),
    QuestionItem(
      id: 'far_067',
      questionText: 'Kategori obat kehamilan FDA yang mutlak dikontraindikasikan karena terbukti kontradiktif memicu cacat janin adalah Kategori:',
      options: ['Kategori X', 'Kategori D', 'Kategori C', 'Kategori B'],
      correctOptionIndex: 0,
      explanation: 'Kategori X terbukti teratogenik dan dilarang untuk wanita hamil.',
    ),
    QuestionItem(
      id: 'far_068',
      questionText: 'Kategori kehamilan FDA yang paling aman bagi wanita hamil tanpa risiko janin adalah Kategori:',
      options: ['Kategori A', 'Kategori B', 'Kategori C', 'Kategori D'],
      correctOptionIndex: 0,
      explanation: 'Kategori A terbukti aman melalui studi terkontrol pada wanita hamil.',
    ),
    QuestionItem(
      id: 'far_069',
      questionText: 'Proses sterilisasi sediaan farmasi menggunakan uap air bertekanan tinggi dilakukan pada alat:',
      options: ['Autoklaf', 'Oven Udara Panas', 'Filter Membran', 'Radiasi Gamma'],
      correctOptionIndex: 0,
      explanation: 'Autoklaf memanaskan uap air bertekanan 121°C selama 15 menit.',
    ),
    QuestionItem(
      id: 'far_070',
      questionText: 'Suhu dan waktu standar sterilisasi panas basah dengan autoklaf adalah:',
      options: ['121°C selama 15 menit', '160°C selama 2 jam', '100°C selama 1 jam', '180°C selama 30 menit'],
      correctOptionIndex: 0,
      explanation: 'Standard autoklaf uap jenuh adalah 121°C, 15 psi, 15 menit.',
    ),
    QuestionItem(
      id: 'far_071',
      questionText: 'Metode sterilisasi panas kering (Dry Heat) untuk alat gelas lab dilakukan menggunakan:',
      options: ['Oven (Hot Air Oven)', 'Autoklaf', 'Inkubator', 'Waterbath'],
      correctOptionIndex: 0,
      explanation: 'Oven udara panas digunakan untuk peralatan gelas bebas kelembaban (160-170°C).',
    ),
    QuestionItem(
      id: 'far_072',
      questionText: 'Ukuran pori filter membran steril yang mampu menahan mikroorganisme bakteri adalah:',
      options: ['0.22 mikrometer', '0.45 mikrometer', '1.0 mikrometer', '5.0 mikrometer'],
      correctOptionIndex: 0,
      explanation: 'Membran 0.22 µm standar penyaringan larutan peka panas.',
    ),
    QuestionItem(
      id: 'far_073',
      questionText: 'Senyawa kimia pembawa demam yang dihasilkan mikroba dan wajib diuji pada sediaan injeksi dinamakan:',
      options: ['Pirogen / Endotoksin', 'Histamin', 'Antigen', 'Sterol'],
      correctOptionIndex: 0,
      explanation: 'Pirogen (lipopolisakarida endotoksin) memicu reaksi demam hebat jika terinjeksi.',
    ),
    QuestionItem(
      id: 'far_074',
      questionText: 'Uji pirogenitas pada obat suntik secara in vitro modern mengandalkan ekstrak darah kepiting dinamakan uji:',
      options: ['LAL Test (Limulus Amebocyte Lysate)', 'Rabbit Test', 'ELISA Test', 'PCR Test'],
      correctOptionIndex: 0,
      explanation: 'LAL test mendeteksi endotoksin menggunakan sampel darah kepiting Limulus polyphemus.',
    ),
    QuestionItem(
      id: 'far_075',
      questionText: 'Tekanan osmotik sediaan injeksi yang sama dengan tekanan osmotik darah/cairan tubuh dinamakan:',
      options: ['Isotonis', 'Hipertonis', 'Hipotonis', 'Isohidris'],
      correctOptionIndex: 0,
      explanation: 'Sediaan isotonis mencegah lisis atau kerutan sel darah merah.',
    ),
    QuestionItem(
      id: 'far_076',
      questionText: 'Efek samping pecahnya sel darah merah akibat injeksi sediaan hipotonis dinamakan:',
      options: ['Hemolisis', 'Krenasi', 'Plasmolisis', 'Aglutinasi'],
      correctOptionIndex: 0,
      explanation: 'Cairan hipotonis menyebabkan air masuk ke eritrosit hingga pecah (hemolisis).',
    ),
    QuestionItem(
      id: 'far_077',
      questionText: 'Efek pengerutan sel darah merah akibat penyuntikan sediaan hipertonis dinamakan:',
      options: ['Krenasi', 'Hemolisis', 'Lisis', 'Nekrosis'],
      correctOptionIndex: 0,
      explanation: 'Cairan hipertonis menarik air keluar dari eritrosit sehingga mengkerut (krenasi).',
    ),
    QuestionItem(
      id: 'far_078',
      questionText: 'Penyesuaian pH sediaan injeksi agar sesuai dengan pH fisiologis tubuh (7.4) dinamakan:',
      options: ['Isohidris', 'Isotonis', 'Isothermis', 'Isokorik'],
      correctOptionIndex: 0,
      explanation: 'Isohidris adalah penyelarasan pH sediaan mendekati pH jaringan tubuh.',
    ),
    QuestionItem(
      id: 'far_079',
      questionText: 'Kelompok obat hipertensi penurun tekanan darah yang bekerja merelaksasi pembuluh darah dengan memblokir saluran kalsium adalah:',
      options: ['CCB (Calcium Channel Blocker)', 'ACE Inhibitor', 'Beta Blocker', 'Diuretik'],
      correctOptionIndex: 0,
      explanation: 'CCB (Amlodipin, Nifedipin) memblok masukan ion kalsium ke otot polos pembuluh.',
    ),
    QuestionItem(
      id: 'far_080',
      questionText: 'Obat hipertensi golongan ACE Inhibitor (misal Captopril) memiliki efek samping khas berupa:',
      options: ['Batuk Kering', 'Gusi Berdarah', 'Penglihatan Kabur', 'Rambut Rontok'],
      correctOptionIndex: 0,
      explanation: 'ACE Inhibitor meningkatkan bradikinin yang sering merangsang batuk kering.',
    ),
    QuestionItem(
      id: 'far_081',
      questionText: 'Diuretik hemat kalium yang sering digunakan pada hipertensi dan gagal jantung adalah:',
      options: ['Spironolakton', 'Furosemid', 'Hidroklorotiazid (HCT)', 'Manitol'],
      correctOptionIndex: 0,
      explanation: 'Spironolakton memblokir aldosteron dan mengekskresikan Na+ tanpa membuang K+.',
    ),
    QuestionItem(
      id: 'far_082',
      questionText: 'Diuretik kuat (Loop Diuretic) yang bekerja pada Ansa Henle ginjal adalah:',
      options: ['Furosemid', 'Spironolakton', 'Acetazolamid', 'HCT'],
      correctOptionIndex: 0,
      explanation: 'Furosemid memblok reabsorpsi Na/K/2Cl di ansa Henle ascendant.',
    ),
    QuestionItem(
      id: 'far_083',
      questionText: 'Obat antidiabetes oral golongan Biguanida yang merupakan lini pertama diabetes tipe 2 adalah:',
      options: ['Metformin', 'Glibenklamid', 'Akarbosa', 'Pioglitazon'],
      correctOptionIndex: 0,
      explanation: 'Metformin menekan gluconeogenesis hati dan meningkatkan sensitivitas insulin.',
    ),
    QuestionItem(
      id: 'far_084',
      questionText: 'Obat antidiabetes Sulfonilurea (misal Glibenklamid) bekerja memicu efek:',
      options: ['Merangsang sekresi insulin dari sel beta pankreas', 'Menghambat penyerapan glukosa usus', 'Meningkatkan ekskresi glukosa di urin', 'Menghambat glukagon'],
      correctOptionIndex: 0,
      explanation: 'Sulfonilurea merangsang pelepasan insulin pankreas.',
    ),
    QuestionItem(
      id: 'far_085',
      questionText: 'Obat antidiabetes Akarbosa bekerja dengan cara menghambat enzim pencernaan:',
      options: ['Alfa-Glukosidase', 'Dipeptidyl Peptidase-4', 'SGLT-2', 'Amilase Pankreas'],
      correctOptionIndex: 0,
      explanation: 'Akarbosa menghambat alfa-glukosidase menunda pemecahan karbohidrat usus.',
    ),
    QuestionItem(
      id: 'far_086',
      questionText: 'Reaksi alergi obat fatal yang ditandai dengan ruam melepuh parah pada kulit dan mukosa dinamakan:',
      options: ['Sindrom Stevens-Johnson (SJS)', 'Anafilaksis', 'Urtikaria', 'Eritema'],
      correctOptionIndex: 0,
      explanation: 'SJS adalah reaksi mukokutan akut hipersensitivitas obat berat.',
    ),
    QuestionItem(
      id: 'far_087',
      questionText: 'Obat analgesik bebas parasetamol jika dikonsumsi dalam dosis sangat tinggi (>10 gram) rawan memicu kerusakan:',
      options: ['Hati (Hepatotoksik)', 'Ginjal (Nefrotoksik)', 'Jantung (Kardiotoksik)', 'Paru-paru'],
      correctOptionIndex: 0,
      explanation: 'Metabolit NAPQI berlebih merusak sel parenkim hati.',
    ),
    QuestionItem(
      id: 'far_088',
      questionText: 'Obat pengencer darah (Antikoagulan) oral yang memerlukan pemantauan nilai INR secara rutin adalah:',
      options: ['Warfarin', 'Aspirin', 'Clopidogrel', 'Heparin'],
      correctOptionIndex: 0,
      explanation: 'Warfarin membutuhkan monitor INR (International Normalized Ratio).',
    ),
    QuestionItem(
      id: 'far_089',
      questionText: 'Antiplatelet golongan penghambat COX-1 dosis rendah yang digunakan untuk cegah stroke/serangan jantung adalah:',
      options: ['Aspirin (Asam Asetilsalisilat)', 'Parasetamol', 'Ibuprofen', 'Tramadol'],
      correctOptionIndex: 0,
      explanation: 'Aspirin dosis rendah menghambat agregasi trombosit via Tromboksan A2.',
    ),
    QuestionItem(
      id: 'far_090',
      questionText: 'Prinsip Good Manufacturing Practice (GMP) dalam industri farmasi Indonesia dikenal dengan istilah:',
      options: ['CPOB (Cara Pembuatan Obat yang Baik)', 'CDOB', 'CPOTB', 'CPKB'],
      correctOptionIndex: 0,
      explanation: 'CPOB adalah standar jaminan mutu pabrik pembuat obat.',
    ),
    QuestionItem(
      id: 'far_091',
      questionText: 'Pedoman standar distribusi obat yang baik dari distributor ke apotek dinamakan:',
      options: ['CDOB (Cara Distribusi Obat yang Baik)', 'CPOB', 'CPOTB', 'GDP'],
      correctOptionIndex: 0,
      explanation: 'CDOB menjamin mutu obat terjaga selama rantai distribusi.',
    ),
    QuestionItem(
      id: 'far_092',
      questionText: 'Sistem rantai dingin (Cold Chain System) untuk penyimpanan vaksin berada pada rentang suhu:',
      options: ['2°C hingga 8°C', '15°C hingga 25°C', '0°C hingga 4°C', '-20°C'],
      correctOptionIndex: 0,
      explanation: 'Suhu penyimpanan vaksin cold chain standar adalah 2-8°C.',
    ),
    QuestionItem(
      id: 'far_093',
      questionText: 'Cairan pelarut steril bebas pirogen yang digunakan untuk melarutkan serbuk injeksi dinamakan:',
      options: ['Water for Injection (WFI)', 'Aqua Destilata', 'Aqua Demineralisata', 'Saline 0.9%'],
      correctOptionIndex: 0,
      explanation: 'WFI adalah air steril bebas pirogen khusus untuk sediaan parenteral.',
    ),
    QuestionItem(
      id: 'far_094',
      questionText: 'Obat antimikroba yang membunuh bakteri secara langsung dinamakan bersifat:',
      options: ['Bakterisid', 'Bakteriostatik', 'Bakteriolitik', 'Fungisid'],
      correctOptionIndex: 0,
      explanation: 'Bakterisid mematikan kuman (contoh: Penisilin, Aminoglikosida).',
    ),
    QuestionItem(
      id: 'far_095',
      questionText: 'Obat antimikroba yang menghambat pertumbuhan dan perkembangbiakan bakteri dinamakan bersifat:',
      options: ['Bakteriostatik', 'Bakterisid', 'Virosid', 'Sporosid'],
      correctOptionIndex: 0,
      explanation: 'Bakteriostatik menahan populasi kuman (contoh: Tetrasiklin, Kloramfenikol).',
    ),
    QuestionItem(
      id: 'far_096',
      questionText: 'Zat anestesi lokal golongan amida yang sering digunakan pada operasi kecil atau kedokteran gigi adalah:',
      options: ['Lidokain', 'Prokain', 'Kokain', 'Benzokain'],
      correctOptionIndex: 0,
      explanation: 'Lidokain adalah anestesi lokal amida yang populer dan stabil.',
    ),
    QuestionItem(
      id: 'far_097',
      questionText: 'Obat maag golongan Proton Pump Inhibitor (PPI) yang menekan asam lambung adalah:',
      options: ['Omeprazol', 'Ranitidin', 'Antasida', 'Sukralfat'],
      correctOptionIndex: 0,
      explanation: 'Omeprazol memblokir pompa H+/K+ ATPase di sel parietal lambung.',
    ),
    QuestionItem(
      id: 'far_098',
      questionText: 'Obat maag antagonis reseptor H2 yang menekan sekresi asam lambung adalah:',
      options: ['Ranitidin / Famotidin', 'Omeprazol', 'Lansoprazol', 'Misoprostol'],
      correctOptionIndex: 0,
      explanation: 'Ranitidin menghambat reseptor Histamin H2 di lambung.',
    ),
    QuestionItem(
      id: 'far_099',
      questionText: 'Bahan aktif antasida yang sering dikombinasikan untuk menetralkan asam lambung adalah:',
      options: ['Aluminium Hidroksida & Magnesium Hidroksida', 'Kalsium Karbonat & Natrium Bikarbonat', 'Bismut Subsalisilat', 'Simetikon'],
      correctOptionIndex: 0,
      explanation: 'Kombinasi Al(OH)3 dan Mg(OH)2 menetralkan pH dan meminimalkan efek diare/konstipasi.',
    ),
    QuestionItem(
      id: 'far_100',
      questionText: 'Tempat fasilitas pelayanan kefarmasian di mana apoteker melakukan praktik pelayanan obat dinamakan:',
      options: ['Apotek', 'Pabrik Farmasi', 'Distributor Obat', 'Laboratorium Klinik'],
      correctOptionIndex: 0,
      explanation: 'Apotek adalah saran pelayanan kefarmasian langsung kepada masyarakat.',
    ),
  ];
}
