import '../tes_seleksi_model.dart';

List<QuestionItem> getGiziIlmuPanganQuestions() {
  return const [
    QuestionItem(
      id: 'gizi_001',
      questionText: 'Tiga zat gizi makro (makronutrien) penghasil energi utama tubuh manusia adalah:',
      options: ['Karbohidrat, Protein, dan Lemak', 'Vitamin, Mineral, dan Air', 'Protein, Vitamin, dan Mineral', 'Karbohidrat, Serat, dan Air'],
      correctOptionIndex: 0,
      explanation: 'Karbohidrat, protein, dan lemak adalah makronutrien metabolisme energi.',
    ),
    QuestionItem(
      id: 'gizi_002',
      questionText: 'Jumlah energi kalori yang dihasilkan oleh 1 gram Karbohidrat adalah:',
      options: ['4 kkal', '9 kkal', '7 kkal', '2 kkal'],
      correctOptionIndex: 0,
      explanation: 'Karbohidrat dan protein menghasilkan 4 kkal per gram.',
    ),
    QuestionItem(
      id: 'gizi_003',
      questionText: 'Jumlah energi kalori yang dihasilkan oleh 1 gram Lemak adalah:',
      options: ['9 kkal', '4 kkal', '7 kkal', '12 kkal'],
      correctOptionIndex: 0,
      explanation: 'Lemak menghasilkan energi tertinggi yaitu 9 kkal per gram.',
    ),
    QuestionItem(
      id: 'gizi_004',
      questionText: 'Jumlah energi kalori yang dihasilkan oleh 1 gram Protein adalah:',
      options: ['4 kkal', '9 kkal', '7 kkal', '5 kkal'],
      correctOptionIndex: 0,
      explanation: 'Protein memberikan 4 kkal per gram.',
    ),
    QuestionItem(
      id: 'gizi_005',
      questionText: 'Indeks Massa Tubuh (IMT / BMI) dihitung dengan membagi berat badan (kg) dengan:',
      options: ['Tinggi badan kuadrat dalam meter (m²)', 'Tinggi badan dalam cm', 'Umur dalam tahun', 'Lingkar pinggang dalam m'],
      correctOptionIndex: 0,
      explanation: 'BMI = Berat Badan (kg) / (Tinggi Badan (m))².',
    ),
    QuestionItem(
      id: 'gizi_006',
      questionText: 'Kategori IMT orang dewasa Indonesia menurut Kemenkes RI untuk ambang batas "Normal" adalah:',
      options: ['18.5 - 25.0 kg/m²', '15.0 - 18.4 kg/m²', '25.1 - 27.0 kg/m²', '> 30.0 kg/m²'],
      correctOptionIndex: 0,
      explanation: 'IMT normal berkisar 18.5 - 25.0 kg/m².',
    ),
    QuestionItem(
      id: 'gizi_007',
      questionText: 'Kondisi kegemukan ekstrem dengan nilai IMT > 30.0 kg/m² dinamakan:',
      options: ['Obesitas', 'Overweight', 'Gizi Kurang', 'Stunting'],
      correctOptionIndex: 0,
      explanation: 'IMT > 30 tergolong Obesitas.',
    ),
    QuestionItem(
      id: 'gizi_008',
      questionText: 'Kondisi gagal tumbuh pada anak akibat kekurangan gizi kronis ditandai badan pendek dinamakan:',
      options: ['Stunting', 'Wasting', 'Underweight', 'Kwashiorkor'],
      correctOptionIndex: 0,
      explanation: 'Stunting ditandai TB/U (Tinggi Badan menurut Umur) < -2 SD.',
    ),
    QuestionItem(
      id: 'gizi_009',
      questionText: 'Kondisi anak kurus ekstrem akibat gizi buruk akut ditandai BB/TB rendah dinamakan:',
      options: ['Wasting', 'Stunting', 'Marasmus', 'Obese'],
      correctOptionIndex: 0,
      explanation: 'Wasting ditandai indikator Berat Badan menurut Tinggi Badan (BB/TB) amat rendah.',
    ),
    QuestionItem(
      id: 'gizi_010',
      questionText: 'Bentuk gizi buruk protein berat yang ditandai dengan edema (busung lapar) dan perut buncit dinamakan:',
      options: ['Kwashiorkor', 'Marasmus', 'Stunting', 'Rickets'],
      correctOptionIndex: 0,
      explanation: 'Kwashiorkor dipicu defisiensi protein parah ditandai edema.',
    ),
    QuestionItem(
      id: 'gizi_011',
      questionText: 'Bentuk gizi buruk energi total berat yang ditandai dengan tubuh sangat kurus seperti tulang dibalut kulit adalah:',
      options: ['Marasmus', 'Kwashiorkor', 'Obesitas', 'Skorbut'],
      correctOptionIndex: 0,
      explanation: 'Marasmus adalah defisiensi kalori & energi parah tanpa edema.',
    ),
    QuestionItem(
      id: 'gizi_012',
      questionText: 'Vitamin yang larut dalam air (water-soluble) adalah:',
      options: ['Vitamin B kompleks dan Vitamin C', 'Vitamin A, D, E, K', 'Vitamin A dan B', 'Vitamin C dan E'],
      correctOptionIndex: 0,
      explanation: 'Vitamin B dan C larut dalam air dan dibuang via urin jika berlebih.',
    ),
    QuestionItem(
      id: 'gizi_013',
      questionText: 'Mineral mikronutrien yang menjadi komponen utama pembentuk hemoglobin darah adalah:',
      options: ['Zat Besi (Fe)', 'Kalsium (Ca)', 'Iodium (I)', 'Seng (Zn)'],
      correctOptionIndex: 0,
      explanation: 'Zat besi pembentuk heme hemoglobin.',
    ),
    QuestionItem(
      id: 'gizi_014',
      questionText: 'Kekurangan asupan zat besi kronis dapat memicu timbulnya penyakit:',
      options: ['Anemia Defisiensi Besi', 'Gondok', 'Gizi Buruk', 'Osteoporosis'],
      correctOptionIndex: 0,
      explanation: 'Defisiensi Fe adalah penyebab anemia tersering di dunia.',
    ),
    QuestionItem(
      id: 'gizi_015',
      questionText: 'Defisiensi mineral Iodium (Iodine) pada kelenjar tiroid dapat memicu pembengkakan:',
      options: ['Gondok (Goiter)', 'Skorbut', 'Beri-beri', 'Rickets'],
      correctOptionIndex: 0,
      explanation: 'Kurang iodium memicu hipertrofi tiroid (gondok).',
    ),
    QuestionItem(
      id: 'gizi_016',
      questionText: 'Kekurangan Vitamin A (Retinol) kronis dapat menyebabkan gangguan penglihatan malam yaitu:',
      options: ['Rabun Senja (Xerophthalmia)', 'Katarak', 'Glaukoma', 'Presbiopi'],
      correctOptionIndex: 0,
      explanation: 'Vit A penting untuk rhodopsin sel batang retina.',
    ),
    QuestionItem(
      id: 'gizi_017',
      questionText: 'Defisiensi Vitamin B1 (Tiamin) dapat memicu penyakit gangguan saraf dan pembengkakan yaitu:',
      options: ['Beri-Beri', 'Pellagra', 'Skorbut', 'Rickets'],
      correctOptionIndex: 0,
      explanation: 'Beri-beri dipicu defisiensi vitamin B1.',
    ),
    QuestionItem(
      id: 'gizi_018',
      questionText: 'Defisiensi Vitamin B3 (Niasin) memicu penyakit 3D (Dermatitis, Diarrhea, Dementia) yaitu:',
      options: ['Pellagra', 'Beri-Beri', 'Anemia Pernisiosa', 'Scurvy'],
      correctOptionIndex: 0,
      explanation: 'Pellagra ditandai gejala khas 3D akibat kurang Niasin.',
    ),
    QuestionItem(
      id: 'gizi_019',
      questionText: 'Asam lemak tak jenuh ganda esensial yang penting untuk perkembangan otak anak adalah:',
      options: ['Omega-3 (DHA & EPA)', 'Asam Palmitat', 'Asam Stearat', 'Trans Fat'],
      correctOptionIndex: 0,
      explanation: 'Omega-3 (DHA/EPA) membentuk jaringan lipid membran sel otak.',
    ),
    QuestionItem(
      id: 'gizi_020',
      questionText: 'Jenis lemak paling berbahaya yang meningkatkan kolesterol jahat LDL dan menurunkan HDL adalah:',
      options: ['Lemak Trans (Trans Fat)', 'Lemak Tak Jenuh Tunggal', 'Omega-9', 'Lemak Laurat'],
      correctOptionIndex: 0,
      explanation: 'Lemak trans buatan (minyak hidrogenasi) sangat meningkatkan risiko penyakit jantung.',
    ),
    QuestionItem(
      id: 'gizi_021',
      questionText: 'Metode pengawetan pangan menggunakan suhu tinggi di atas 100°C untuk membunuh seluruh mikroba beserta sporanya adalah:',
      options: ['Sterilisasi Pangan (Komersial)', 'Pasteurisasi', 'Blanching', 'Fermetasi'],
      correctOptionIndex: 0,
      explanation: 'Sterilisasi membunuh spora dan mikroba pembusuk.',
    ),
    QuestionItem(
      id: 'gizi_022',
      questionText: 'Pemanasan susu pada suhu 72°C selama 15 detik untuk membunuh patogen tanpa merusak rasa dinamakan:',
      options: ['Pasteurisasi HTST', 'Sterilisasi UHT', 'Blanching', 'Evaporasi'],
      correctOptionIndex: 0,
      explanation: 'Pasteurisasi HTST (High Temperature Short Time) membunuh patogen susu.',
    ),
    QuestionItem(
      id: 'gizi_023',
      questionText: 'Proses pemanasan susu suhu tinggi ultra 135-150°C selama 2-4 detik dinamakan sterilisasi:',
      options: ['UHT (Ultra High Temperature)', 'Pasteurisasi', 'Freeze Drying', 'Pengeringan'],
      correctOptionIndex: 0,
      explanation: 'Susu UHT steril dan tahan disimpan lama pada suhu ruang sebelum dibuka.',
    ),
    QuestionItem(
      id: 'gizi_024',
      questionText: 'Pemanasan singkat sayuran dalam air mendidih untuk menginaktifkan enzim pembusuk sebelum dibekukan dinamakan:',
      options: ['Blanching', 'Pasteurisasi', 'Sterilisasi', 'Thawing'],
      correctOptionIndex: 0,
      explanation: 'Blanching mematikan enzim oksidatif pada jaringan sayur.',
    ),
    QuestionItem(
      id: 'gizi_025',
      questionText: 'Pengeringan beku pada suhu sublimasi dingin untuk produk pangan peka panas dinamakan:',
      options: ['Freeze Drying (Liofilisasi)', 'Spray Drying', 'Sun Drying', 'Oven Drying'],
      correctOptionIndex: 0,
      explanation: 'Freeze drying mengeringkan lewat sublimasi es tanpa merusak nutrisi.',
    ),
    QuestionItem(
      id: 'gizi_026',
      questionText: 'Bakteri asam laktat yang digunakan dalam pembuatan keju dan yoghurt adalah:',
      options: ['Lactobacillus bulgaricus & Streptococcus thermophilus', 'Escherichia coli', 'Bacillus subtilis', 'Acetobacter aceti'],
      correctOptionIndex: 0,
      explanation: 'Lactobacillus & Streptococcus memfermentasi laktosa menjadi asam laktat.',
    ),
    QuestionItem(
      id: 'gizi_027',
      questionText: 'Kapang ragi yang digunakan dalam pembuatan tempeh dari kedelai adalah:',
      options: ['Rhizopus oligosporus / Rhizopus oryzae', 'Saccharomyces cerevisiae', 'Aspergillus oryzae', 'Neurospora sitophila'],
      correctOptionIndex: 0,
      explanation: 'Rhizopus membentuk hifa putih mengikat biji kedelai jadi tempe.',
    ),
    QuestionItem(
      id: 'gizi_028',
      questionText: 'Khamir mikroba yang memfermentasi gula menjadi alkohol dan CO2 pada roti dan bir adalah:',
      options: ['Saccharomyces cerevisiae', 'Rhizopus oryzae', 'Penicillium notatum', 'Lactobacillus'],
      correctOptionIndex: 0,
      explanation: 'Saccharomyces cerevisiae meragikan adonan roti memicu pengembangan gas CO2.',
    ),
    QuestionItem(
      id: 'gizi_029',
      questionText: 'Sistem manajemen jaminan keamanan pangan internasional berbasis pencegahan bahaya dinamakan:',
      options: ['HACCP (Hazard Analysis Critical Control Point)', 'ISO 9001', 'GMP', 'SSOP'],
      correctOptionIndex: 0,
      explanation: 'HACCP mengidentifikasi dan mengontrol bahaya biologis, kimia, dan fisik pangan.',
    ),
    QuestionItem(
      id: 'gizi_030',
      questionText: 'Bakteri penyebab keracunan pangan mematikan akibat racun botulinum pada makanan kaleng rusak adalah:',
      options: ['Clostridium botulinum', 'Salmonella enterica', 'Staphylococcus aureus', 'Vibrio cholerae'],
      correctOptionIndex: 0,
      explanation: 'C. botulinum menghasilkan neurotoksin botulinum pada kondisi anaerob makanan kaleng.',
    ),
    QuestionItem(
      id: 'gizi_031',
      questionText: 'Bakteri penyebab keracunan makanan telur dan daging ayam tidak matang adalah:',
      options: ['Salmonella spp.', 'Listeria monocytogenes', 'Campylobacter', 'E. coli'],
      correctOptionIndex: 0,
      explanation: 'Salmonella sering mencemari olahan unggas dan telur mentah.',
    ),
    QuestionItem(
      id: 'gizi_032',
      questionText: 'Racun mikotoksin berbahaya yang dihasilkan jamur Aspergillus flavus pada kacang tanah lembab adalah:',
      options: ['Aflatoksin', 'Botulinum', 'Tetrodotoksin', 'Solanin'],
      correctOptionIndex: 0,
      explanation: 'Aflatoksin bersifat karsinogenik memicu kanker hati.',
    ),
    QuestionItem(
      id: 'gizi_033',
      questionText: 'Racun alami yang terdapat pada bagian kentang berwarna hijau atau bertunas dinamakan:',
      options: ['Solanin', 'Sianida', 'Oksalat', 'Gitosida'],
      correctOptionIndex: 0,
      explanation: 'Solanin adalah glikoalkaloid beracun pada kentang terpapar cahaya.',
    ),
    QuestionItem(
      id: 'gizi_034',
      questionText: 'Racun asam sianida (HCN) yang terdapat pada singkong racun dapat dihilangkan dengan cara:',
      options: ['Pencucian, Perendaman air, dan Perebusan matang', 'Pendinginan', 'Pembekuan', 'Penambahan garam'],
      correctOptionIndex: 0,
      explanation: 'HCN larut air dan menguap saat perebusan/pengolahan.',
    ),
    QuestionItem(
      id: 'gizi_035',
      questionText: 'Zat aditif makanan pewarna sintetik merah berbahaya yang dilarang penggunaannya adalah:',
      options: ['Rhodamin B', 'Tartrazin', 'Kurkumin', 'Karamel'],
      correctOptionIndex: 0,
      explanation: 'Rhodamin B adalah pewarna tekstil karsinogenik yang dilarang untuk pangan.',
    ),
    QuestionItem(
      id: 'gizi_036',
      questionText: 'Zat aditif bahan pengawet mayat industri yang sering disalahgunakan pada mie/tahu adalah:',
      options: ['Formalin (Formaldehida)', 'Boraks', 'Benzoat', 'Nitrit'],
      correctOptionIndex: 0,
      explanation: 'Formalin beracun merusak organ pencernaan dan karsinogenik.',
    ),
    QuestionItem(
      id: 'gizi_037',
      questionText: 'Bahan pengenyal berbahaya yang dilarang untuk pembuatan bakso dan lontong adalah:',
      options: ['Boraks (Asam Borat / Bleng)', 'STPP', 'Gelatin', 'Agar-agar'],
      correctOptionIndex: 0,
      explanation: 'Boraks berbahaya memicu toksisitas kronis pada ginjal dan hati.',
    ),
    QuestionItem(
      id: 'gizi_038',
      questionText: 'Zat aditif penguat rasa gurih umami yang populer adalah:',
      options: ['Monosodium Glutamat (MSG)', 'Aspartam', 'Sodium Benzoat', 'Lesitin'],
      correctOptionIndex: 0,
      explanation: 'MSG memberikan rasa umami dari garam asam glutamat.',
    ),
    QuestionItem(
      id: 'gizi_039',
      questionText: 'Komponen karbohidrat pangan yang tidak dapat dicerna enzim pencernaan manusia namun penting untuk usus dinamakan:',
      options: ['Serat Pangan (Dietary Fiber)', 'Pektin', 'Pati', 'Glikogen'],
      correctOptionIndex: 0,
      explanation: 'Serat membantu peristaltik usus dan mencegah konstipasi.',
    ),
    QuestionItem(
      id: 'gizi_040',
      questionText: 'Serat larut air (Soluble Fiber) seperti Pektin dan Beta-Glukan memiliki manfaat:',
      options: ['Menurunkan kadar kolesterol dan memperlambat lonjakan gula darah', 'Mempercepat pengosongan lambung', 'Meningkatkan kalori makanan', 'Membunuh bakteri baik'],
      correctOptionIndex: 0,
      explanation: 'Serat larut mengikat asam empedu dan memperlambat absorpsi glukosa.',
    ),
    QuestionItem(
      id: 'gizi_041',
      questionText: 'Bentuk simpanan karbohidrat pada jaringan hati dan otot manusia dinamakan:',
      options: ['Glikogen', 'Pati', 'Amilosa', 'Selulosa'],
      correctOptionIndex: 0,
      explanation: 'Glikogen adalah polisakarida cadangan gula manusia/hewan.',
    ),
    QuestionItem(
      id: 'gizi_042',
      questionText: 'Proses pembentukan glukosa baru dari bahan non-karbohidrat (seperti asam amino/gliserol) dinamakan:',
      options: ['Glukoneogenesis', 'Glikolisis', 'Glikogenolisis', 'Glikogenesis'],
      correctOptionIndex: 0,
      explanation: 'Glukoneogenesis membuat glukosa saat pasokan karbohidrat habis.',
    ),
    QuestionItem(
      id: 'gizi_043',
      questionText: 'Proses pemecahan molekul glukosa menjadi asam piruvat untuk menghasilkan ATP dinamakan:',
      options: ['Glikolisis', 'Siklus Krebs', 'Fosforilasi Oksidatif', 'Glukoneogenesis'],
      correctOptionIndex: 0,
      explanation: 'Glikolisis menguraikan 1 glukosa menjadi 2 piruvat di sitosol sel.',
    ),
    QuestionItem(
      id: 'gizi_044',
      questionText: 'Nilai yang menunjukkan seberapa cepat makanan berkarbohidrat meningkatkan kadar gula darah dinamakan:',
      options: ['Indeks Glikemik (IG)', 'Beban Glikemik', 'Kalori Spesifik', 'Kadar Laktat'],
      correctOptionIndex: 0,
      explanation: 'Indeks Glikemik mengukur skala 0-100 dampak gula makanan terhadap glukosa darah.',
    ),
    QuestionItem(
      id: 'gizi_045',
      questionText: 'Makanan dengan Indeks Glikemik rendah (IG < 55) sangat disarankan untuk penderita:',
      options: ['Diabetes Melitus', 'Hipertensi', 'Gagal Ginjal', 'Osteoporosis'],
      correctOptionIndex: 0,
      explanation: 'IG rendah mencegah lonjakan drastis gula darah diabetisi.',
    ),
    QuestionItem(
      id: 'gizi_046',
      questionText: 'Protein sempurna atau berlayak cerna tinggi mengandung seluruh jenis:',
      options: ['Asam Amino Esensial', 'Asam Lemak Jenuh', 'Vitamin B Kompleks', 'Mineral Makro'],
      correctOptionIndex: 0,
      explanation: 'Protein bernilai biologi tinggi (misal telur, susu, daging) kaya asam amino esensial lengkap.',
    ),
    QuestionItem(
      id: 'gizi_047',
      questionText: 'Jumlah asam amino esensial yang tidak dapat disintesis tubuh dan wajib diperoleh dari makanan adalah:',
      options: ['9 Asam Amino', '5 Asam Amino', '15 Asam Amino', '20 Asam Amino'],
      correctOptionIndex: 0,
      explanation: 'Ada 9 asam amino esensial bagi tubuh manusia dewasa.',
    ),
    QuestionItem(
      id: 'gizi_048',
      questionText: 'Reaksi pencokelatan non-enzimatis antara gula pereduksi dan asam amino saat pemanasan pangan dinamakan:',
      options: ['Reaksi Maillard', 'Karamelisasi', 'Oksidasi Enzimatis', 'Gelatinisasi'],
      correctOptionIndex: 0,
      explanation: 'Reaksi Maillard memberi warna cokelat dan aroma khas masakan memanggang/menggoreng.',
    ),
    QuestionItem(
      id: 'gizi_049',
      questionText: 'Reaksi pencokelatan gula akibat pemanasan suhu tinggi tanpa melibatkan protein dinamakan:',
      options: ['Karamelisasi', 'Reaksi Maillard', 'Fermentasi', 'Inversi Gula'],
      correctOptionIndex: 0,
      explanation: 'Karamelisasi memanaskan gula murni di atas titik lelehnya.',
    ),
    QuestionItem(
      id: 'gizi_050',
      questionText: 'Perubahan pembengkakan granula pati saat dipanaskan dalam air hingga membentuk gel kental dinamakan:',
      options: ['Gelatinisasi Pati', 'Retrogradasi', 'Dekstrinisasi', 'Sineresis'],
      correctOptionIndex: 0,
      explanation: 'Gelatinisasi memicu granula pati menyerap air dan mengembang kental.',
    ),
    QuestionItem(
      id: 'gizi_051',
      questionText: 'Pengeluaran air dari gel pati akibat penataan kembali molekul amilosa saat pendinginan dinamakan:',
      options: ['Sineresis / Retrogradasi', 'Gelatinisasi', 'Emulsifikasi', 'Karbonasi'],
      correctOptionIndex: 0,
      explanation: 'Sineresis merembeskan cairan dari gel pati yang mengeras basi.',
    ),
    QuestionItem(
      id: 'gizi_052',
      questionText: 'Ketidakmampuan tubuh mencerna gula susu akibat defisiensi enzim laktase dinamakan:',
      options: ['Intoleransi Laktosa', 'Alergi Susu Sapi', 'Galaktosemia', 'Celiac Disease'],
      correctOptionIndex: 0,
      explanation: 'Intoleransi laktosa memicu kram dan diare saat minum susu sapi.',
    ),
    QuestionItem(
      id: 'gizi_053',
      questionText: 'Reaksi sistem imun terhadap protein susu sapi (seperti kasein/whey) dinamakan:',
      options: ['Alergi Susu Sapi', 'Intoleransi Laktosa', 'Defisiensi Laktase', 'Celiac'],
      correctOptionIndex: 0,
      explanation: 'Alergi susu melibatkan respon antibodi IgE imunologis.',
    ),
    QuestionItem(
      id: 'gizi_054',
      questionText: 'Penyakit autoimun intoleransi protein Gluten yang terdapat pada gandum/terigu dinamakan:',
      options: ['Celiac Disease (Penyakit Seliac)', 'Intoleransi Laktosa', 'IBS', 'Kolesistitis'],
      correctOptionIndex: 0,
      explanation: 'Celiac merusak vili usus halus jika mengonsumsi gluten.',
    ),
    QuestionItem(
      id: 'gizi_055',
      questionText: 'Protein utama penyusun tepung terigu yang memberikan sifat elastisitas adonan roti adalah:',
      options: ['Gluten (Gliadin & Glutenin)', 'Kasein', 'Albumin', 'Aktin'],
      correctOptionIndex: 0,
      explanation: 'Gluten terperangkap gas CO2 membuat adonan roti mengembang elastis.',
    ),
    QuestionItem(
      id: 'gizi_056',
      questionText: 'Program panduan gizi seimbang pengganti 4 Sehat 5 Sempurna dari Kemenkes RI dinamakan:',
      options: ['Isi Piringku & Gizi Seimbang', 'Tumpeng Gizi', 'Piramida Makanan', 'Pedoman Diet RI'],
      correctOptionIndex: 0,
      explanation: 'Isi Piringku membagi porsi 50% buah/sayur dan 50% makanan pokok/lauk.',
    ),
    QuestionItem(
      id: 'gizi_057',
      questionText: 'Dalam panduan "Isi Piringku", porsi makanan pokok berbanding sayuran adalah:',
      options: ['Sebanding (Masing-masing 2/3 dari setengah piring)', 'Makanan pokok 80%', 'Sayur 10%', 'Tanpa buah'],
      correctOptionIndex: 0,
      explanation: 'Isi piringku: 1/3 makanan pokok, 1/3 sayuran, 1/6 lauk pauk, 1/6 buah-buahan.',
    ),
    QuestionItem(
      id: 'gizi_058',
      questionText: 'Batas maksimum konsumsi Gula, Garam, dan Lemak (GGL) per orang per hari menurut Kemenkes adalah:',
      options: ['4 Sendok Makan Gula, 1 Sendok Teh Garam, 5 Sendok Makan Lemak', '10 Sendok Makan Gula', '2 Sendok Teh Garam', 'Bebas'],
      correctOptionIndex: 0,
      explanation: 'Anjuran G4-G1-L5: Gula max 4 sdm (50g), Garam max 1 sdt (2000mg Na), Lemak max 5 sdm (67g).',
    ),
    QuestionItem(
      id: 'gizi_059',
      questionText: 'Mineral Natrium (Sodium) dalam garam dapur berlebih berkorelasi kuat dengan penyakit:',
      options: ['Hipertensi (Tekanan Darah Tinggi)', 'Diabetes', 'Asam Urat', 'Rickets'],
      correctOptionIndex: 0,
      explanation: 'Natrium menahan air di pembuluh darah memicu lonjakan tekanan darah.',
    ),
    QuestionItem(
      id: 'gizi_060',
      questionText: 'Penyakit metabolik penumpukan kristal asam urat pada persendian dipicu konsumsi makanan tinggi:',
      options: ['Purin (seperti jeroan, seafood)', 'Glukosa', 'Kolesterol', 'Kalsium'],
      correctOptionIndex: 0,
      explanation: 'Purin diubah menjadi asam urat di dalam tubuh.',
    ),
    QuestionItem(
      id: 'gizi_061',
      questionText: 'Terapi diet khusus penderita penyakit ginjal kronis berfokus pada pembatasan asupan:',
      options: ['Protein, Kalium, Fosfor, dan Cairan', 'Karbohidrat murni', 'Serat', 'Vitamin C'],
      correctOptionIndex: 0,
      explanation: 'Gagal ginjal membatasi filtrasi sisa nitrogen protein dan kalium.',
    ),
    QuestionItem(
      id: 'gizi_062',
      questionText: 'Diet DASH (Dietary Approaches to Stop Hypertension) direkomendasikan untuk menekan:',
      options: ['Tekanan Darah Tinggi', 'Asam Urat', 'Batu Ginjal', 'Diare Kronis'],
      correctOptionIndex: 0,
      explanation: 'DASH kaya K, Mg, Ca serta rendah natrium menurunkan hipertensi.',
    ),
    QuestionItem(
      id: 'gizi_063',
      questionText: 'Nutrien antioksidan penangkap radikal bebas paling kuat pada sayuran dan buah adalah:',
      options: ['Vitamin C, Vitamin E, Beta-Karoten, dan Flavonoid', 'Zat Besi dan Seng', 'Laktosa', 'Asam Stearat'],
      correctOptionIndex: 0,
      explanation: 'Vit C, E, carotenoid menetralkan stres oksidatif radikal bebas.',
    ),
    QuestionItem(
      id: 'gizi_064',
      questionText: 'Pigmen warna merah alami pada tomat dan semangka yang kaya antioksidan prostat dinamakan:',
      options: ['Likopen (Lycopene)', 'Beta-Karoten', 'Antosianin', 'Klorofil'],
      correctOptionIndex: 0,
      explanation: 'Likopen adalah karotenoid merah penangkal radikal bebas.',
    ),
    QuestionItem(
      id: 'gizi_065',
      questionText: 'Pigmen warna ungu atau biru alami pada buah beri dan terong dinamakan:',
      options: ['Antosianin', 'Klorofil', 'Kurkumin', 'Xantofil'],
      correctOptionIndex: 0,
      explanation: 'Antosianin memancarkan pigmen merah-biru-ungu antioksidan.',
    ),
    QuestionItem(
      id: 'gizi_066',
      questionText: 'Pigmen hijau utama tanaman yang berperan fotosintesis dinamakan:',
      options: ['Klorofil', 'Karoten', 'Fikobilin', 'Melanin'],
      correctOptionIndex: 0,
      explanation: 'Klorofil menangkap energi cahaya matahari pada daun hijau.',
    ),
    QuestionItem(
      id: 'gizi_067',
      questionText: 'Bakteri menguntungkan (hidup) yang dikonsumsi untuk menjaga keseimbangan flora usus dinamakan:',
      options: ['Probiotik', 'Prebiotik', 'Sinbiotik', 'Antibiotik'],
      correctOptionIndex: 0,
      explanation: 'Probiotik adalah mikroorganisme hidup penguat mikrobioma usus.',
    ),
    QuestionItem(
      id: 'gizi_068',
      questionText: 'Makanan tak tercerna (seperti serat inulin) yang menjadi suplemen nutrisi bagi bakteri baik usus dinamakan:',
      options: ['Prebiotik', 'Probiotik', 'Postbiotik', 'Antibiotik'],
      correctOptionIndex: 0,
      explanation: 'Prebiotik adalah substrat nutrisi bagi probiotik.',
    ),
    QuestionItem(
      id: 'gizi_069',
      questionText: 'Kombinasi formulasi campuran antara Probiotik dan Prebiotik dinamakan:',
      options: ['Sinbiotik', 'Postbiotik', 'Probiotik Plus', 'Multibiotik'],
      correctOptionIndex: 0,
      explanation: 'Sinbiotik menyatukan mikroba probiotik dan serat makanan prebiotik.',
    ),
    QuestionItem(
      id: 'gizi_070',
      questionText: 'Penyakit tulang keropos pasca menopause akibat penurunan Kalsium dan Estrogen dinamakan:',
      options: ['Osteoporosis', 'Osteomalasia', 'Rickets', 'Artritis'],
      correctOptionIndex: 0,
      explanation: 'Osteoporosis mengurangi kepadatan massa tulang lansia/wanita menopause.',
    ),
    QuestionItem(
      id: 'gizi_071',
      questionText: 'Pelunakan tulang pada orang dewasa akibat defisiensi berat Vitamin D dinamakan:',
      options: ['Osteomalasia', 'Rakitis', 'Osteoporosis', 'Osteofit'],
      correctOptionIndex: 0,
      explanation: 'Osteomalasia adalah kegagalan mineralisasi tulang dewasa.',
    ),
    QuestionItem(
      id: 'gizi_072',
      questionText: 'Proses penambahan zat gizi spesifik pada bahan pangan umum (misal Iodium pada garam) dinamakan:',
      options: ['Fortifikasi Pangan', 'Enrichment', 'Supplementasi', 'Biofortifikasi'],
      correctOptionIndex: 0,
      explanation: 'Fortifikasi menambahkan mikronutrien penting mencegah defisiensi populasi.',
    ),
    QuestionItem(
      id: 'gizi_073',
      questionText: 'Pengayaan kembali zat gizi yang hilang selama proses pengolahan bahan pangan dinamakan:',
      options: ['Enrichment (Pengayaan)', 'Fortifikasi', 'Aditif', 'Substitusi'],
      correctOptionIndex: 0,
      explanation: 'Enrichment mengembalikan kadar nutrisi awal yang sempat susut.',
    ),
    QuestionItem(
      id: 'gizi_074',
      questionText: 'Alat ukur lingkar lengan atas untuk penapisan status gizi Kurang Energi Kronis (KEK) ibu hamil dinamakan:',
      options: ['Pita LiLA (Lingkar Lengan Atas)', 'Metlin', 'Stadiometer', 'Caliper skinfold'],
      correctOptionIndex: 0,
      explanation: 'LiLA < 23.5 cm mengindikasikan ibu hamil mengalami KEK.',
    ),
    QuestionItem(
      id: 'gizi_075',
      questionText: 'Batas ambang LiLA (Lingkar Lengan Atas) risik KEK pada wanita usia subur/ibu hamil adalah:',
      options: ['23.5 cm', '18.0 cm', '30.0 cm', '15.5 cm'],
      correctOptionIndex: 0,
      explanation: 'LiLA di bawah 23.5 cm berisiko melahirkan bayi BBLR.',
    ),
    QuestionItem(
      id: 'gizi_076',
      questionText: 'Bayi Baru Lahir Rendah (BBLR) ditandai dengan berat badan lahir di bawah:',
      options: ['2500 gram (2.5 kg)', '3000 gram', '1500 gram', '2000 gram'],
      correctOptionIndex: 0,
      explanation: 'BBLR didefinisikan jika berat lahir <2500g.',
    ),
    QuestionItem(
      id: 'gizi_077',
      questionText: 'Alat pengukur tinggi badan presisi tegak dinamakan:',
      options: ['Stadiometer / Microtoise', 'Timbangan Dacin', 'Infantometer', 'Pita LiLA'],
      correctOptionIndex: 0,
      explanation: 'Stadiometer/Microtoise mengukur tinggi badan berdiri.',
    ),
    QuestionItem(
      id: 'gizi_078',
      questionText: 'Alat pengukur panjang badan telentang khusus untuk bayi berusia di bawah 2 tahun dinamakan:',
      options: ['Infantometer', 'Stadiometer', 'Microtoise', 'Metlin'],
      correctOptionIndex: 0,
      explanation: 'Infantometer mengukur panjang badan bayi berbaring.',
    ),
    QuestionItem(
      id: 'gizi_079',
      questionText: 'Bahan makanan tambahan MP-ASI (Makanan Pendamping ASI) mulai diperkenalkan pada bayi usia:',
      options: ['6 Bulan', '2 Bulan', '4 Bulan', '12 Bulan'],
      correctOptionIndex: 0,
      explanation: 'MP-ASI dimulai tepat usia 6 bulan saat ASI tidak mencukupi energi.',
    ),
    QuestionItem(
      id: 'gizi_080',
      questionText: 'Asam folat (Vitamin B9) sangat krusial bagi ibu hamil untuk mencegah cacat tabung saraf janin yaitu:',
      options: ['Neural Tube Defects (NTDs / Anensefali / Spina Bifida)', 'Stunting', 'BBLR', 'Down Syndrome'],
      correctOptionIndex: 0,
      explanation: 'Asam folat mencegah kelainan penutupan bumbung saraf janin.',
    ),
    QuestionItem(
      id: 'gizi_081',
      questionText: 'Metode analisis penentuan kadar protein bahan pangan berbasis kadar nitrogen total dinamakan:',
      options: ['Metode Kjeldahl', 'Metode Soxhlet', 'Metode Gravimetri', 'Metode Titrasi Formol'],
      correctOptionIndex: 0,
      explanation: 'Metode Kjeldahl mendestruksi sampel mengukur N total dikali faktor konversi 6.25.',
    ),
    QuestionItem(
      id: 'gizi_082',
      questionText: 'Faktor konversi nitrogen murni menjadi kadar protein kasar bahan makanan umum adalah:',
      options: ['6.25', '4.25', '9.00', '5.70'],
      correctOptionIndex: 0,
      explanation: 'Standard konversi N ke protein adalah 6.25 (karena protein rata-rata mengandung 16% N).',
    ),
    QuestionItem(
      id: 'gizi_083',
      questionText: 'Metode ekstrasi laboratorium untuk menentukan kadar lemak total bahan pangan dinamakan:',
      options: ['Metode Soxhlet', 'Metode Kjeldahl', 'Metode Oven', 'Metode Spectro'],
      correctOptionIndex: 0,
      explanation: 'Soxhlet meng-ekstraksi lemak dengan pelarut non-polar (n-heksan/eter).',
    ),
    QuestionItem(
      id: 'gizi_084',
      questionText: 'Penentuan kadar air bahan pangan secara konvensional dilakukan mengandalkan alat:',
      options: ['Oven Pengering 105°C', 'Autoklaf', 'Desikator', 'Muffle Furnace'],
      correctOptionIndex: 0,
      explanation: 'Sampel dikeringkan di oven 105°C hingga bobot konstan.',
    ),
    QuestionItem(
      id: 'gizi_085',
      questionText: 'Penentuan kadar abu (total mineral) bahan pangan dilakukan pembakaran suhu tinggi 550-600°C di dalam:',
      options: ['Tanur Pengabuan (Muffle Furnace)', 'Oven Pengering', 'Waterbath', 'Hotplate'],
      correctOptionIndex: 0,
      explanation: 'Furnace membakar habis bahan organik memisahkan sisa anorganik (abu).',
    ),
    QuestionItem(
      id: 'gizi_086',
      questionText: 'Aktivitas air (Water Activity / Aw) menunjukkan:',
      options: ['Jumlah air bebas dalam pangan yang dapat digunakan untuk pertumbuhan mikroba', 'Kadar air total', 'Kelembaban udara', 'Berat jenis air'],
      correctOptionIndex: 0,
      explanation: 'Nilai Aw (0.0 - 1.0) menentukan daya simpan dan batas tumbuh mikroba.',
    ),
    QuestionItem(
      id: 'gizi_087',
      questionText: 'Batas nilai Aw minimum agar sebagian besar bakteri pembusuk dapat tumbuh subur adalah sekitar:',
      options: ['Aw > 0.90', 'Aw > 0.60', 'Aw > 0.30', 'Aw = 0.10'],
      correctOptionIndex: 0,
      explanation: 'Bakteri butuh Aw tinggi (>0.90) untuk berkembang biak.',
    ),
    QuestionItem(
      id: 'gizi_088',
      questionText: 'Kapang/jamur dapat tumbuh pada pangan dengan nilai Aw yang relatif lebih rendah yaitu:',
      options: ['Aw > 0.70 - 0.80', 'Aw > 0.95', 'Aw > 0.99', 'Aw < 0.10'],
      correctOptionIndex: 0,
      explanation: 'Kapang lebih toleran terhadap lingkungan agak kering (Aw 0.70).',
    ),
    QuestionItem(
      id: 'gizi_089',
      questionText: 'Pengemasan pangan atmosfer termodifikasi dengan menggantikan O2 menggunakan CO2/N2 dinamakan:',
      options: ['MAP (Modified Atmosphere Packaging)', 'Vacuum Packaging', 'Canning', 'Aseptic'],
      correctOptionIndex: 0,
      explanation: 'MAP menekan reaksi oksidasi dan pertumbuhan mikroba aerob.',
    ),
    QuestionItem(
      id: 'gizi_090',
      questionText: 'Reaksi kerusakan lemak berminyak akibat oksidasi udara yang menghasilkan bau tengik dinamakan:',
      options: ['Ransiditas Oksidatif (Ketengikan)', 'Hidrolisis', 'Saponifikasi', 'Esterifikasi'],
      correctOptionIndex: 0,
      explanation: 'Oksidasi ikatan rangkap asam lemak memicu peroksida berbau tengik.',
    ),
    QuestionItem(
      id: 'gizi_091',
      questionText: 'Zat pencegah ketengikan lemak yang sering ditambahkan pada minyak goreng adalah:',
      options: ['Antioksidan (BHA, BHT, Tokoferol)', 'Emulgator', 'Pengawet Benzoat', 'Pemanis Aspartam'],
      correctOptionIndex: 0,
      explanation: 'Antioksidan (seperti BHA/BHT/Vit E) menghambat autooksidasi lemak.',
    ),
    QuestionItem(
      id: 'gizi_092',
      questionText: 'Pengujian organoleptik sensori pangan menggunakan indera manusia meliputi evaluasi:',
      options: ['Rasa, Aroma, Warna, Tekstur, dan Penampilan', 'Kadar Nitrogen', 'Berat Molekul', 'Kadar Air'],
      correctOptionIndex: 0,
      explanation: 'Uji organoleptik mengukur parameter sensori penerimaan panelis.',
    ),
    QuestionItem(
      id: 'gizi_093',
      questionText: 'Uji organoleptik beda nyata untuk membandingkan dua sampel pangan dinamakan uji:',
      options: ['Uji Duo-Trio / Uji Segitiga (Triangle Test)', 'Uji Hedonik', 'Uji Skoring', 'Uji Deskriptif'],
      correctOptionIndex: 0,
      explanation: 'Triangle test dan Duo-Trio menguji diferensiasi sensori dua produk.',
    ),
    QuestionItem(
      id: 'gizi_094',
      questionText: 'Uji sensori organoleptik untuk mengukur tingkat kesukaan panelis terhadap produk dinamakan uji:',
      options: ['Uji Hedonik (Tingkat Kesukaan)', 'Uji Segitiga', 'Uji Diferensiasi', 'Uji Ambang'],
      correctOptionIndex: 0,
      explanation: 'Uji Hedonik memakai skala tingkat kesukaan (sangat suka s/d sangat tidak suka).',
    ),
    QuestionItem(
      id: 'gizi_095',
      questionText: 'Laju Metabolisme Basal (BMR / Basal Metabolic Rate) adalah:',
      options: ['Kebutuhan energi minimal tubuh untuk menjalankan fungsi vital saat istirahat total', 'Energi saat berolahraga', 'Energi mencerna makanan', 'Kalori harian maksimum'],
      correctOptionIndex: 0,
      explanation: 'BMR adalah energi minimal untuk bernapas, detak jantung, dan kerja sel saat istirahat.',
    ),
    QuestionItem(
      id: 'gizi_096',
      questionText: 'Peningkatan laju metabolisme tubuh pasca mengonsumsi makanan dinamakan:',
      options: ['SDE / TEF (Thermic Effect of Food)', 'BMR', 'PAL', 'REE'],
      correctOptionIndex: 0,
      explanation: 'TEF adalah energi yang terpakai untuk mencerna dan mengabsorpsi nutrisi.',
    ),
    QuestionItem(
      id: 'gizi_097',
      questionText: 'Nutrien yang memiliki Thermic Effect of Food (TEF) paling tinggi (20-30%) adalah:',
      options: ['Protein', 'Karbohidrat', 'Lemak', 'Air'],
      correctOptionIndex: 0,
      explanation: 'Protein membutuhkan energi cerna paling besar dibanding lemak/karbohidrat.',
    ),
    QuestionItem(
      id: 'gizi_098',
      questionText: 'Singkatan AKG dalam pedoman gizi Indonesia adalah:',
      options: ['Angka Kecukupan Gizi', 'Analisis Kadar Gizi', 'Asupan Kalori Gizi', 'Ambang Kecukupan Gula'],
      correctOptionIndex: 0,
      explanation: 'AKG adalah acuan standar kecukupan nutrisi rata-rata harian masyarakat.',
    ),
    QuestionItem(
      id: 'gizi_099',
      questionText: 'Hormon utama pembakar lemak dan pemicu rasa lapar saat lambung kosong adalah:',
      options: ['Ghrelin', 'Leptin', 'Insulin', 'Kolesistokinin'],
      correctOptionIndex: 0,
      explanation: 'Ghrelin disekresi lambung memberi sinyal lapar ke otak.',
    ),
    QuestionItem(
      id: 'gizi_100',
      questionText: 'Hormon penekan rasa lapar yang diproduksi oleh jaringan lemak (adiposa) dinamakan:',
      options: ['Leptin', 'Ghrelin', 'Glukagon', 'Kortisol'],
      correctOptionIndex: 0,
      explanation: 'Leptin memberi sinyal kenyang dan kecukupan energi sel adiposa.',
    ),
  ];
}
