import '../tes_seleksi_model.dart';

List<QuestionItem> getKeperawatanQuestions() {
  return const [
    QuestionItem(
      id: 'kep_001',
      questionText: 'Urutan 5 tahap Proses Keperawatan secara sistematis adalah:',
      options: ['Pengkajian, Diagnosa, Perencanaan, Implementasi, Evaluasi', 'Diagnosa, Pengkajian, Evaluasi, Implementasi, Rencana', 'Pengkajian, Implementasi, Rencana, Evaluasi, Diagnosa', 'Evaluasi, Rencana, Pengkajian, Diagnosa, Implementasi'],
      correctOptionIndex: 0,
      explanation: 'Tahap proses keperawatan: Pengkajian -> Diagnosa -> Rencana (NCP) -> Implementasi -> Evaluasi.',
    ),
    QuestionItem(
      id: 'kep_002',
      questionText: 'Rentang nilai denyut nadi normal pada orang dewasa sehat saat beristirahat adalah:',
      options: ['60 - 100 kali per menit', '40 - 60 kali per menit', '100 - 120 kali per menit', '120 - 140 kali per menit'],
      correctOptionIndex: 0,
      explanation: 'Nadi normal dewasa saat rest adalah 60-100 bpm.',
    ),
    QuestionItem(
      id: 'kep_003',
      questionText: 'Frekuensi pernapasan (Respiration Rate) normal pada orang dewasa beristirahat adalah:',
      options: ['12 - 20 kali per menit', '5 - 10 kali per menit', '25 - 35 kali per menit', '40 - 50 kali per menit'],
      correctOptionIndex: 0,
      explanation: 'RR normal dewasa adalah 12-20 napas per menit.',
    ),
    QuestionItem(
      id: 'kep_004',
      questionText: 'Suhu tubuh inti manusia normal berkisar pada rentang:',
      options: ['36.5°C - 37.5°C', '34.0°C - 35.5°C', '38.0°C - 39.0°C', '39.5°C - 40.5°C'],
      correctOptionIndex: 0,
      explanation: 'Suhu tubuh normal berada di kisaran 36.5°C - 37.5°C.',
    ),
    QuestionItem(
      id: 'kep_005',
      questionText: 'Kondisi frekuensi denyut nadi di bawah 60 kali per menit dinamakan:',
      options: ['Bradikardia', 'Takikardia', 'Aritmia', 'Takipnea'],
      correctOptionIndex: 0,
      explanation: 'Bradikardia ditandai denyut nadi <60 bpm.',
    ),
    QuestionItem(
      id: 'kep_006',
      questionText: 'Kondisi frekuensi denyut nadi di atas 100 kali per menit pada dewasa dinamakan:',
      options: ['Takikardia', 'Bradikardia', 'Hipertensi', 'Bradipnea'],
      correctOptionIndex: 0,
      explanation: 'Takikardia ditandai denyut nadi >100 bpm.',
    ),
    QuestionItem(
      id: 'kep_007',
      questionText: 'Frekuensi pernapasan cepat di atas 20 kali per menit dinamakan:',
      options: ['Takipnea', 'Bradipnea', 'Apnea', 'Dispnea'],
      correctOptionIndex: 0,
      explanation: 'Takipnea adalah laju pernapasan yang cepat.',
    ),
    QuestionItem(
      id: 'kep_008',
      questionText: 'Sensasi kesulitan bernapas atau sesak napas dinamakan:',
      options: ['Dispnea', 'Apnea', 'Ortopnea', 'Sianosis'],
      correctOptionIndex: 0,
      explanation: 'Dispnea adalah istilah medis keluhan sesak napas.',
    ),
    QuestionItem(
      id: 'kep_009',
      questionText: 'Kondisi penghentian napas sementara dinamakan:',
      options: ['Apnea', 'Dispnea', 'Takipnea', 'Kusmaul'],
      correctOptionIndex: 0,
      explanation: 'Apnea adalah terhentinya udara pernapasan.',
    ),
    QuestionItem(
      id: 'kep_010',
      questionText: 'Warna kebiruan pada kulit dan membran mukosa akibat kekurangan oksigen (hipoksia) dinamakan:',
      options: ['Sianosis', 'Eritema', 'Ikterus', 'Pucat'],
      correctOptionIndex: 0,
      explanation: 'Sianosis dipicu oleh tingginya konsentrasi deoksiglobin dalam darah.',
    ),
    QuestionItem(
      id: 'kep_011',
      questionText: 'Warna kekuningan pada kulit dan sklera mata akibat penumpukan bilirubin dinamakan:',
      options: ['Ikterus (Jaundice)', 'Sianosis', 'Eritema', 'Melanoma'],
      correctOptionIndex: 0,
      explanation: 'Ikterus muncul saat kadar bilirubin serum meningkat.',
    ),
    QuestionItem(
      id: 'kep_012',
      questionText: 'Posisi pasien berbaring telentang dengan kepala dan dada ditinggikan 45 - 60 derajat dinamakan posisi:',
      options: ['Fowler', 'Semi-Fowler', 'High-Fowler', 'Trendelenburg'],
      correctOptionIndex: 0,
      explanation: 'Posisi Fowler memfasilitasi ekspansi paru pada pasien sesak.',
    ),
    QuestionItem(
      id: 'kep_013',
      questionText: 'Posisi pasien berbaring dengan kaki dan pinggul ditinggikan lebih tinggi daripada posisi kepala dinamakan:',
      options: ['Trendelenburg', 'Fowler', 'Litotomi', 'Sims'],
      correctOptionIndex: 0,
      explanation: 'Trendelenburg digunakan untuk meningkatkan venous return saat syok.',
    ),
    QuestionItem(
      id: 'kep_014',
      questionText: 'Posisi berbaring miring ke kiri dengan lutut kanan ditekuk (biasa untuk pemberian enema/huknah) dinamakan posisi:',
      options: ['Sims', 'Litotomi', 'Genu Pektoral', 'Dorsal Recumbent'],
      correctOptionIndex: 0,
      explanation: 'Posisi Sims memfasilitasi akses rektal.',
    ),
    QuestionItem(
      id: 'kep_015',
      questionText: 'Posisi telentang dengan lutut ditekuk dan paha dibuka (biasa untuk persalinan atau pemeriksaan ginekologi) dinamakan posisi:',
      options: ['Litotomi', 'Sims', 'Fowler', 'Prone'],
      correctOptionIndex: 0,
      explanation: 'Litotomi digunakan untuk persalinan dan tindakan ginekologis.',
    ),
    QuestionItem(
      id: 'kep_016',
      questionText: 'Suatu tindakan pemasangan selang melalui hidung menuju lambung untuk pemberian nutrisi dinamakan:',
      options: ['NGT (Nasogastric Tube)', 'Kateter Urin', 'ET (Endotracheal Tube)', 'Kanula Nasal'],
      correctOptionIndex: 0,
      explanation: 'NGT dimasukkan dari hidung ke gaster untuk feeding atau dekompresi.',
    ),
    QuestionItem(
      id: 'kep_017',
      questionText: 'Pemberian oksigen konsentrasi rendah (1-6 Liter/menit) pada pasien biasa mengandalkan alat:',
      options: ['Nasal Kanula', 'Masker Rebreathing', 'Masker Non-Rebreathing (NRM)', 'Venturi Mask'],
      correctOptionIndex: 0,
      explanation: 'Nasal kanula memberikan aliran O2 low-flow 1-6 L/min.',
    ),
    QuestionItem(
      id: 'kep_018',
      questionText: 'Masker oksigen yang dilengkapi kantung reservoir dan katup satu arah untuk memberikan O2 konsentrasi tinggi (up to 95%) adalah:',
      options: ['Non-Rebreathing Mask (NRM)', 'Simple Mask', 'Nasal Kanula', 'Rebreathing Mask'],
      correctOptionIndex: 0,
      explanation: 'NRM memberikan aliran 10-15 L/min dengan FiO2 mencapai 90-100%.',
    ),
    QuestionItem(
      id: 'kep_019',
      questionText: 'Luka tekan akibat tekanan terus menerus pada area tulang menonjol pasien tirah baring dinamakan:',
      options: ['Dekubitus (Pressure Ulcer)', 'Ulkus Diabetikum', 'Luka Bakar', 'Laserasi'],
      correctOptionIndex: 0,
      explanation: 'Dekubitus terjadi akibat iskemia jaringan pada tonjolan tulang pasien baring lama.',
    ),
    QuestionItem(
      id: 'kep_020',
      questionText: 'Pencegahan luka dekubitus pada pasien immobilized tirah baring dilakukan dengan alih baring setiap:',
      options: ['2 Jam sekali', '4 Jam sekali', '6 Jam sekali', '12 Jam sekali'],
      correctOptionIndex: 0,
      explanation: 'Mobilisasi alih baring (miring kanan-kiri) rutin setiap 2 jam mencegah nekrosis jaringan.',
    ),
    QuestionItem(
      id: 'kep_021',
      questionText: 'Skala yang digunakan perawat untuk menilai risiko kejadian dekubitus pada pasien adalah:',
      options: ['Skala Braden', 'Skala Norton / Braden', 'Skala Morse', 'Skala Humpty Dumpty'],
      correctOptionIndex: 0,
      explanation: 'Skala Braden menilai persepsi sensori, kelembaban, aktivitas, mobilitas, nutrisi, gesekan.',
    ),
    QuestionItem(
      id: 'kep_022',
      questionText: 'Skala penilai risiko jatuh (Fall Risk) pada pasien dewasa di rumah sakit adalah:',
      options: ['Morse Fall Scale (MFS)', 'Humpty Dumpty Scale', 'GCS', 'APGAR'],
      correctOptionIndex: 0,
      explanation: 'Skala Morse digunakan mengukur derajat risiko jatuh pasien dewasa.',
    ),
    QuestionItem(
      id: 'kep_023',
      questionText: 'Skala penilai risiko jatuh khusus pada pasien anak-anak (Pediatric Fall Risk) dinamakan:',
      options: ['Humpty Dumpty Scale', 'Morse Fall Scale', 'Braden Scale', 'Wong-Baker Scale'],
      correctOptionIndex: 0,
      explanation: 'Humpty Dumpty Scale mengukur risiko jatuh pediatrik.',
    ),
    QuestionItem(
      id: 'kep_024',
      questionText: 'Skala penilaian intensitas nyeri berupa pilihan ekspresi wajah kartun dinamakan skala:',
      options: ['Wong-Baker FACES Scale', 'NRS (Numeric Rating Scale)', 'VAS', 'FLACC'],
      correctOptionIndex: 0,
      explanation: 'Wong-Baker FACES ideal untuk pasien anak atau keterbatasan bahasa.',
    ),
    QuestionItem(
      id: 'kep_025',
      questionText: 'Skala pengukuran nyeri pediatrik non-verbal (Face, Legs, Activity, Cry, Consolability) dinamakan:',
      options: ['Skala FLACC', 'Skala NRS', 'Skala VAS', 'Skala CPOT'],
      correctOptionIndex: 0,
      explanation: 'FLACC menilai respon nyeri bayi/anak yang belum dapat bicara.',
    ),
    QuestionItem(
      id: 'kep_026',
      questionText: 'Metode triase gawat darurat sistem kode warna merah mengindikasikan kategori pasien:',
      options: ['Prioritas 1 (Gawat Darurat Mengancam Nyawa)', 'Prioritas 2 (Darurat Tidak Gawat)', 'Prioritas 3 (Non-Urgent / Hijau)', 'Prioritas 0 (Meninggal / Hitam)'],
      correctOptionIndex: 0,
      explanation: 'Warna MERAH menandakan kasus prioritas utama butuh penanganan segera.',
    ),
    QuestionItem(
      id: 'kep_027',
      questionText: 'Kode warna kuning pada triase IGD menandakan kategori:',
      options: ['Prioritas 2 (Urgent / Darurat Tidak Mengancam Nyawa Segera)', 'Gawat Darurat Utama', 'Non-Urgent', 'Meninggal Dunia'],
      correctOptionIndex: 0,
      explanation: 'Kuning butuh perawatan medis tapi dapat ditunda beberapa waktu.',
    ),
    QuestionItem(
      id: 'kep_028',
      questionText: 'Kode warna hijau pada triase IGD menandakan kategori:',
      options: ['Prioritas 3 (Non-Urgent / Cedera Ringan)', 'Gawat Darurat', 'Darurat Tidak Gawat', 'Meninggal'],
      correctOptionIndex: 0,
      explanation: 'Hijau untuk korban rawat jalan / luka ringan (walking wounded).',
    ),
    QuestionItem(
      id: 'kep_029',
      questionText: 'Kode warna hitam pada triase gawat darurat menandakan korban:',
      options: ['Meninggal Dunia / Ekspektan Tidak Tertolong', 'Gawat Darurat', 'Luka Berat', 'Luka Ringan'],
      correctOptionIndex: 0,
      explanation: 'Hitam menandakan korban telah meninggal dunia atau cedera fatal tanpa respon.',
    ),
    QuestionItem(
      id: 'kep_030',
      questionText: 'Standar 6 Langkah Cuci Tangan menurut WHO (World Health Organization) menggunakan durasi berbasis handrub alcohol sekitar:',
      options: ['20 - 30 Detik', '5 - 10 Detik', '60 - 90 Detik', '3 Menit'],
      correctOptionIndex: 0,
      explanation: 'Cuci tangan handrub alcohol berdurasi 20-30 detik.',
    ),
    QuestionItem(
      id: 'kep_031',
      questionText: 'Durasi cuci tangan 6 langkah WHO menggunakan air mengalir dan sabun (Handwash) adalah sekitar:',
      options: ['40 - 60 Detik', '10 - 20 Detik', '2 Menit', '5 Menit'],
      correctOptionIndex: 0,
      explanation: 'Handwash sabun dan air direkomendasikan 40-60 detik.',
    ),
    QuestionItem(
      id: 'kep_032',
      questionText: 'Lima Momen Kebersihan Tangan (5 Moments for Hand Hygiene) WHO mencakup sebelum dan sesudah kontak dengan:',
      options: ['Pasien dan Lingkungan Sekitar Pasien', 'Dokter saja', 'Baju Perawat', 'Kantin'],
      correctOptionIndex: 0,
      explanation: '5 Moments: Sebelum kontak pasien, sebelum tindakan aseptik, sesudah cairan tubuh, sesudah kontak pasien, sesudah lingkungan pasien.',
    ),
    QuestionItem(
      id: 'kep_033',
      questionText: 'Infeksi yang diperoleh pasien selama menjalani perawatan di rumah sakit dinamakan infeksi:',
      options: ['Nosokomial / HAIs (Healthcare-Associated Infections)', 'Opportunistik', 'Kongenital', 'Iatrogenik'],
      correctOptionIndex: 0,
      explanation: 'HAIs adalah infeksi yang muncul >48 jam setelah masuk rawat inap rumah sakit.',
    ),
    QuestionItem(
      id: 'kep_034',
      questionText: 'Komunikasi antar perawat dan tim kesehatan profesional yang berfokus pada kesembuhan pasien dinamakan komunikasi:',
      options: ['Terapeutik', 'Sosial', 'Formal', 'Transaksional'],
      correctOptionIndex: 0,
      explanation: 'Komunikasi terapeutik dirancang membina hubungan saling percaya dan menyembuhkan.',
    ),
    QuestionItem(
      id: 'kep_035',
      questionText: 'Empat fase komunikasi terapeutik perawat-pasien secara berurutan adalah:',
      options: ['Prainteraksi, Orientasi, Kerja, Terminasi', 'Orientasi, Kerja, Evaluasi, Terminasi', 'Prainteraksi, Kerja, Evaluasi, Penutup', 'Orientasi, Prainteraksi, Kerja, Terminasi'],
      correctOptionIndex: 0,
      explanation: 'Fase: Prainteraksi (persiapan) -> Orientasi (perkenalan) -> Kerja (tindakan) -> Terminasi (penutupan).',
    ),
    QuestionItem(
      id: 'kep_036',
      questionText: 'Metode komunikasi serah terima pasien (Handover/Timbang Terima) antar perawat dinamakan SBAR, singkatan dari:',
      options: ['Situation, Background, Assessment, Recommendation', 'Status, Body, Action, Result', 'Summary, Bed, Assessment, Report', 'Symptom, Blood, Activity, Response'],
      correctOptionIndex: 0,
      explanation: 'SBAR: Situation, Background, Assessment, Recommendation.',
    ),
    QuestionItem(
      id: 'kep_037',
      questionText: 'Suatu bentuk instruksi tertulis persetujuan medis dari pasien pasca menerima informasi lengkap dinamakan:',
      options: ['Informed Consent', 'Informed Refusal', 'Discharge Planning', 'Nursing Care Plan'],
      correctOptionIndex: 0,
      explanation: 'Informed consent persetujuan tindakan medis berdasar penjelasan.',
    ),
    QuestionItem(
      id: 'kep_038',
      questionText: 'Prinsip etika keperawatan yang menekankan kewajiban melakukan hal baik dan menguntungkan pasien dinamakan:',
      options: ['Beneficence', 'Non-maleficence', 'Autonomy', 'Justice'],
      correctOptionIndex: 0,
      explanation: 'Beneficence berbuat baik demi keselamatan dan kesejahteraan pasien.',
    ),
    QuestionItem(
      id: 'kep_039',
      questionText: 'Prinsip etika keperawatan yang mengharuskan tindakan perawat tidak mencederai atau merugikan pasien dinamakan:',
      options: ['Non-maleficence', 'Beneficence', 'Fidelity', 'Veracity'],
      correctOptionIndex: 0,
      explanation: 'Non-maleficence (Do No Harm) yaitu tidak mencelakakan pasien.',
    ),
    QuestionItem(
      id: 'kep_040',
      questionText: 'Prinsip etika keperawatan yang menghormati hak otonomi pasien dalam menentukan keputusannya sendiri dinamakan:',
      options: ['Autonomy', 'Justice', 'Veracity', 'Fidelity'],
      correctOptionIndex: 0,
      explanation: 'Autonomy menghargai hak dan kebebasan pilihan pasien.',
    ),
    QuestionItem(
      id: 'kep_041',
      questionText: 'Prinsip etika keperawatan untuk berlaku jujur dan menyampaikan kebenaran dinamakan:',
      options: ['Veracity', 'Fidelity', 'Confidentiality', 'Justice'],
      correctOptionIndex: 0,
      explanation: 'Veracity berarti menyampaikan kebenaran secara jujur.',
    ),
    QuestionItem(
      id: 'kep_042',
      questionText: 'Prinsip etika keperawatan untuk memegang janji dan setia pada komitmen profesional dinamakan:',
      options: ['Fidelity', 'Veracity', 'Justice', 'Autonomy'],
      correctOptionIndex: 0,
      explanation: 'Fidelity adalah kesetiaan memegang janji pelayanan.',
    ),
    QuestionItem(
      id: 'kep_043',
      questionText: 'Prinsip etika keperawatan yang menekankan keadilan tanpa membeda-bedakan pasien dinamakan:',
      options: ['Justice', 'Beneficence', 'Autonomy', 'Non-maleficence'],
      correctOptionIndex: 0,
      explanation: 'Justice bertindak adil pada setiap pasien.',
    ),
    QuestionItem(
      id: 'kep_044',
      questionText: 'Prinsip etika merahasikan seluruh informasi medis medis pasien dinamakan:',
      options: ['Confidentiality', 'Veracity', 'Fidelity', 'Justice'],
      correctOptionIndex: 0,
      explanation: 'Confidentiality menjaga kerahasiaan data pasien.',
    ),
    QuestionItem(
      id: 'kep_045',
      questionText: 'Penghitungan tetesan infus (Drop Factor) standar mikro adalah:',
      options: ['60 Tetes per mililiter', '20 Tetes per mililiter', '15 Tetes per mililiter', '10 Tetes per mililiter'],
      correctOptionIndex: 0,
      explanation: 'Set infus mikro memiliki faktor tetes 60 gtt/mL (biasa untuk anak/pediatrik).',
    ),
    QuestionItem(
      id: 'kep_046',
      questionText: 'Penhitungan tetesan infus makro standar dewasa umumnya memiliki faktor tetes:',
      options: ['20 Tetes per mililiter', '60 Tetes per mililiter', '100 Tetes per mililiter', '5 Tetes per mililiter'],
      correctOptionIndex: 0,
      explanation: 'Infus set makro dewasa standar adalah 20 gtt/mL (atau 15 gtt/mL pada merek tertentu).',
    ),
    QuestionItem(
      id: 'kep_047',
      questionText: 'Cairan infus kristaloid isotonis yang umum digunakan untuk resusitasi cairan kehilangan darah/dehidrasi adalah:',
      options: ['Ringer Laktat (RL) / NaCl 0.9%', 'Dextrose 50%', 'Manitol 20%', 'Albumin'],
      correctOptionIndex: 0,
      explanation: 'RL dan NaCl 0.9% (Normal Saline) adalah kristaloid isotonis pilihan resusitasi.',
    ),
    QuestionItem(
      id: 'kep_048',
      questionText: 'Komplikasi peradangan vena tempat lokasi penusukan jarum infus dinamakan:',
      options: ['Flebitis', 'Infiltrasi', 'Extravasasi', 'Hematoma'],
      correctOptionIndex: 0,
      explanation: 'Flebitis ditandai kemerahan, bengkak, dan nyeri sepanjang jalur vena infus.',
    ),
    QuestionItem(
      id: 'kep_049',
      questionText: 'Kondisi bocornya cairan infus vesikan/iritan keluar dari pembuluh darah ke jaringan sekitar dinamakan:',
      options: ['Ekstravasasi', 'Infiltrasi', 'Flebitis', 'Trombosis'],
      correctOptionIndex: 0,
      explanation: 'Ekstravasasi terjadi bila cairan vesikan (misal obat kemoterapi) merembes merusak jaringan.',
    ),
    QuestionItem(
      id: 'kep_050',
      questionText: 'Kondisi masuknya udara ke dalam pembuluh darah vena saat pemberian infus dinamakan:',
      options: ['Emboli Udara', 'Pneumotoraks', 'Flebitis', 'Atelektasis'],
      correctOptionIndex: 0,
      explanation: 'Emboli udara berisiko membahayakan sirkulasi ke jantung.',
    ),
    QuestionItem(
      id: 'kep_051',
      questionText: 'Metode pemberian obat suntik di dalam jaringan otot dinamakan injeksi:',
      options: ['Intramuskular (IM)', 'Intravena (IV)', 'Subkutan (SC)', 'Intrakutan (IC)'],
      correctOptionIndex: 0,
      explanation: 'IM disuntikkan tegak lurus 90 derajat ke dalam massa otot.',
    ),
    QuestionItem(
      id: 'kep_052',
      questionText: 'Sudut penusukan jarum pada penyuntikan Intramuskular (IM) adalah:',
      options: ['90 Derajat', '45 Derajat', '15 Derajat', '30 Derajat'],
      correctOptionIndex: 0,
      explanation: 'Penyuntikan IM tegak lurus 90°.',
    ),
    QuestionItem(
      id: 'kep_053',
      questionText: 'Sudut penusukan jarum pada penyuntikan Subkutan (SC) adalah:',
      options: ['45 Derajat', '90 Derajat', '15 Derajat', '10 Derajat'],
      correctOptionIndex: 0,
      explanation: 'Penyuntikan SC (misal insulin) sudut 45° (atau 90° untuk jarum pendek).',
    ),
    QuestionItem(
      id: 'kep_054',
      questionText: 'Penyuntikan Intrakutan (IC) untuk uji alergi skin test dilakukan pada sudut:',
      options: ['10 - 15 Derajat', '45 Derajat', '90 Derajat', '60 Derajat'],
      correctOptionIndex: 0,
      explanation: 'IC dilakukan sangat dangkal di lapisan dermis dengan sudut 10-15°.',
    ),
    QuestionItem(
      id: 'kep_055',
      questionText: 'Lokasi penyuntikan Intramuskular (IM) pada paha luar anak/bayi dinamakan otot:',
      options: ['Vastus Lateralis', 'Deltoid', 'Gluteus Maximus', 'Ventrogluteal'],
      correctOptionIndex: 0,
      explanation: 'Vastus lateralis paha adalah lokasi teraman iminisasi anak/bayi.',
    ),
    QuestionItem(
      id: 'kep_056',
      questionText: 'Suatu tindakan penghisapan lendir/sekret dari saluran napas pasien dinamakan:',
      options: ['Suction / Pengisapan Lendir', 'Nebulizer', 'Chest Physiotherapy', 'Batuk Efektif'],
      correctOptionIndex: 0,
      explanation: 'Suction membersihkan sekret pada pasien tak mampu batuk mandiri.',
    ),
    QuestionItem(
      id: 'kep_057',
      questionText: 'Pemberian obat hirup dalam bentuk uap halus menggunakan alat penghasil aerosol dinamakan:',
      options: ['Nebulizer', 'Inhaler Dose Terukur', 'Suction', 'Humidifier'],
      correctOptionIndex: 0,
      explanation: 'Nebulizer mengubah cairan obat bronkodilator menjadi uap halus.',
    ),
    QuestionItem(
      id: 'kep_058',
      questionText: 'Teknik latihan napas dalam dan dorongan dada untuk melepaskan dahak dinamakan:',
      options: ['Latihan Batuk Efektif', 'Postural Drainage', 'Fisioterapi Dada', 'Spirometri'],
      correctOptionIndex: 0,
      explanation: 'Batuk efektif menghemat energi pasien sambil mengeluarkan dahak.',
    ),
    QuestionItem(
      id: 'kep_059',
      questionText: 'Tindakan miring menungging untuk mengalirkan sekret paru berbasis gravitasi dinamakan:',
      options: ['Postural Drainage', 'Suction', 'Nebulizer', 'Pursed-lip Breathing'],
      correctOptionIndex: 0,
      explanation: 'Postural drainage memanfaatkan gravitasi mengalirkan dahak dari lobus paru.',
    ),
    QuestionItem(
      id: 'kep_060',
      questionText: 'Pemeriksaan saturasi oksigen darah perifer non-invasif mengandalkan alat:',
      options: ['Pulse Oximeter', 'Tensimeter', 'EKG', 'Glukometer'],
      correctOptionIndex: 0,
      explanation: 'Pulse oximeter dipasang di jari mengukur SpO2 %.',
    ),
    QuestionItem(
      id: 'kep_061',
      questionText: 'Nilai saturasi oksigen (SpO2) normal pada udara bebas adalah:',
      options: ['95% - 100%', '85% - 90%', '70% - 80%', '< 90%'],
      correctOptionIndex: 0,
      explanation: 'SpO2 normal berkisar antara 95% sampai 100%.',
    ),
    QuestionItem(
      id: 'kep_062',
      questionText: 'Suatu alat kateter urin menetap yang memiliki balon pengunci di kandung kemih dinamakan:',
      options: ['Foley Catheter', 'Nelaton Catheter', 'Condom Catheter', 'Suprapubic Catheter'],
      correctOptionIndex: 0,
      explanation: 'Foley catheter memiliki balon yang diisi akuades pengunci di vesika urinaria.',
    ),
    QuestionItem(
      id: 'kep_063',
      questionText: 'Jumlah urine output normal pada orang dewasa adalah sekitar:',
      options: ['0.5 - 1 mL/kgBB/Jam', '0.1 mL/kgBB/Jam', '3 mL/kgBB/Jam', '5 mL/kgBB/Jam'],
      correctOptionIndex: 0,
      explanation: 'Urine output normal berkisar 0.5 - 1 mL/kgBB/jam.',
    ),
    QuestionItem(
      id: 'kep_064',
      questionText: 'Kondisi produksi urin berkurang drastis di bawah 400 mL dalam 24 jam dinamakan:',
      options: ['Oliguria', 'Anuria', 'Poliuria', 'Disuria'],
      correctOptionIndex: 0,
      explanation: 'Oliguria adalah produksi urin <400 mL/24 jam.',
    ),
    QuestionItem(
      id: 'kep_065',
      questionText: 'Kondisi ketiadaan produksi urin sama sekali (<100 mL dalam 24 jam) dinamakan:',
      options: ['Anuria', 'Oliguria', 'Poliuria', 'Nokturia'],
      correctOptionIndex: 0,
      explanation: 'Anuria adalah kegagalan pembentukan urin <100 mL/hari.',
    ),
    QuestionItem(
      id: 'kep_066',
      questionText: 'Kondisi produksi urin yang sangat berlebihan (>2500 mL dalam 24 jam) dinamakan:',
      options: ['Poliuria', 'Oliguria', 'Anuria', 'Enuresis'],
      correctOptionIndex: 0,
      explanation: 'Poliuria sering ditemukan pada pasien diabetes melitus/insipidus.',
    ),
    QuestionItem(
      id: 'kep_067',
      questionText: 'Sensasi nyeri atau panas saat buang air kecil dinamakan:',
      options: ['Disuria', 'Poliuria', 'Hematuria', 'Inkontinensia'],
      correctOptionIndex: 0,
      explanation: 'Disuria adalah nyeri/rasa terbakar saat miksi akibat infeksi ISK.',
    ),
    QuestionItem(
      id: 'kep_068',
      questionText: 'Kondisi adanya darah di dalam urin dinamakan:',
      options: ['Hematuria', 'Proteinuria', 'Glukosuria', 'Ketosis'],
      correctOptionIndex: 0,
      explanation: 'Hematuria mengindikasikan adanya eritrosit pada urin.',
    ),
    QuestionItem(
      id: 'kep_069',
      questionText: 'Ketidakmampuan mengontrol pengeluaran urin secara mandiri dinamakan:',
      options: ['Inkontinensia Urin', 'Retensi Urin', 'Disuria', 'Anuria'],
      correctOptionIndex: 0,
      explanation: 'Inkontinensia adalah kebocoran urin involuntir.',
    ),
    QuestionItem(
      id: 'kep_070',
      questionText: 'Penumpukan urin di kandung kemih akibat ketidakmampuan untuk mengosongkan urin dinamakan:',
      options: ['Retensi Urin', 'Inkontinensia Urin', 'Oliguria', 'Disuria'],
      correctOptionIndex: 0,
      explanation: 'Retensi urin menyebabkan pembengkakan distensi vesika urinaria.',
    ),
    QuestionItem(
      id: 'kep_071',
      questionText: 'Pemeriksaan fisik perawat yang menggunakan indera penglihatan untuk mengamati kondisi pasien dinamakan:',
      options: ['Inspeksi', 'Palpasi', 'Perkusi', 'Auskultasi'],
      correctOptionIndex: 0,
      explanation: 'Inspeksi adalah langkah pengamatan visual pertama.',
    ),
    QuestionItem(
      id: 'kep_072',
      questionText: 'Pemeriksaan fisik dengan cara meraba menggunakan telapak dan ujung jari tangan dinamakan:',
      options: ['Palpasi', 'Inspeksi', 'Perkusi', 'Auskultasi'],
      correctOptionIndex: 0,
      explanation: 'Palpasi menilai tekstur, kehangatan, kontur, dan nyeri tekan.',
    ),
    QuestionItem(
      id: 'kep_073',
      questionText: 'Pemeriksaan fisik dengan cara mengetuk permukaan tubuh untuk mendengar batas jaringan dinamakan:',
      options: ['Perkusi', 'Palpasi', 'Inspeksi', 'Auskultasi'],
      correctOptionIndex: 0,
      explanation: 'Perkusi menghasilkan bunyi sonor, redup, timpani, atau pekak.',
    ),
    QuestionItem(
      id: 'kep_074',
      questionText: 'Pemeriksaan fisik dengan cara mendengarkan suara dalam tubuh menggunakan stetoskop dinamakan:',
      options: ['Auskultasi', 'Perkusi', 'Palpasi', 'Inspeksi'],
      correctOptionIndex: 0,
      explanation: 'Auskultasi mendengarkan bunyi jantung, paru, dan bising usus.',
    ),
    QuestionItem(
      id: 'kep_075',
      questionText: 'Urutan pemeriksaan fisik perut (abdomen) yang tepat agar tidak mengubah bising usus adalah:',
      options: ['Inspeksi, Auskultasi, Perkusi, Palpasi', 'Inspeksi, Palpasi, Perkusi, Auskultasi', 'Auskultasi, Inspeksi, Palpasi, Perkusi', 'Palpasi, Perkusi, Auskultasi, Inspeksi'],
      correctOptionIndex: 0,
      explanation: 'Khusus abdomen: Inspeksi -> Auskultasi -> Perkusi -> Palpasi (supaya tidak merangsang peristaltik sebelum didengar).',
    ),
    QuestionItem(
      id: 'kep_076',
      questionText: 'Bising usus normal peristaltik usus didengarkan pada auskultasi abdomen dengan frekuensi:',
      options: ['5 - 35 kali per menit', '1 - 2 kali per menit', '50 - 60 kali per menit', 'Tidak terdengar sama sekali'],
      correctOptionIndex: 0,
      explanation: 'Bising usus normal adalah 5-35 kali per menit.',
    ),
    QuestionItem(
      id: 'kep_077',
      questionText: 'Kondisi hilangnya peristaltik usus (bising usus negatif) pasca operasi abdomen dinamakan:',
      options: ['Ileus Paralitik', 'Obstipasi', 'Peritonitis', 'Apendisitis'],
      correctOptionIndex: 0,
      explanation: 'Ileus paralitik ditandai kelumpuhan motilitas usus.',
    ),
    QuestionItem(
      id: 'kep_078',
      questionText: 'Penghitungan Usia Kehamilan berbasis Hari Pertama Haid Terakhir (HPHT) menggunakan Rumus:',
      options: ['Rumus Naegele', 'Rumus Parkland', 'Rumus APGAR', 'Rumus Broca'],
      correctOptionIndex: 0,
      explanation: 'Rumus Naegele menghitung Hari Perkiraan Lahir (HPL) (+7 hari, -3 bulan, +1 tahun).',
    ),
    QuestionItem(
      id: 'kep_079',
      questionText: 'Rumus penghitungan kebutuhan cairan resusitasi 24 jam pada pasien luka bakar dinamakan:',
      options: ['Rumus Parkland (4 mL x kgBB x %Luka Bakar)', 'Rumus Naegele', 'Rumus Darrow', 'Rumus Evans'],
      correctOptionIndex: 0,
      explanation: 'Rumus Parkland: 4 mL RL x kgBB x % Total Luas Luka Bakar (TBSA).',
    ),
    QuestionItem(
      id: 'kep_080',
      questionText: 'Pembagian persentase luas luka bakar tubuh pada pasien dewasa mengandalkan aturan:',
      options: ['Rule of Nines (Aturan Sembilan Wallace)', 'Rule of Tens', 'Skala Lund-Browder', 'Skala Braden'],
      correctOptionIndex: 0,
      explanation: 'Rule of Nines membagi area tubuh dewasa dalam kelipatan 9%.',
    ),
    QuestionItem(
      id: 'kep_081',
      questionText: 'Luas luka bakar satu lengan penuh (depan dan belakang) pada orang dewasa menurut Rule of Nines adalah:',
      options: ['9%', '18%', '4.5%', '13.5%'],
      correctOptionIndex: 0,
      explanation: 'Satu lengan penuh dinilai 9% (4.5% depan, 4.5% belakang).',
    ),
    QuestionItem(
      id: 'kep_082',
      questionText: 'Luas luka bakar satu tungkai kaki penuh (depan dan belakang) pada dewasa menurut Rule of Nines adalah:',
      options: ['18%', '9%', '36%', '12%'],
      correctOptionIndex: 0,
      explanation: 'Satu kaki penuh dinilai 18% (9% depan, 9% belakang).',
    ),
    QuestionItem(
      id: 'kep_083',
      questionText: 'Pendarahan bercak ringan yang dialami wanita saat penempelan embrio ke dinding rahim dinamakan:',
      options: ['Implantasi', 'Menstruasi', 'Abortus', 'Lochia'],
      correctOptionIndex: 0,
      explanation: 'Pendarahan implantasi muncul saat nidasi janin di endometrium.',
    ),
    QuestionItem(
      id: 'kep_084',
      questionText: 'Cairan vagina yang keluar pada masa nifas pasca persalinan dinamakan:',
      options: ['Lochia', 'Keputihan', 'Amnion', 'Kolostrum'],
      correctOptionIndex: 0,
      explanation: 'Lochia adalah sekresi rahim pasca melahirkan (Rubra, Serosa, Alba).',
    ),
    QuestionItem(
      id: 'kep_085',
      questionText: 'Lochia berwarna merah segar yang keluar pada hari 1-3 pasca persalinan dinamakan:',
      options: ['Lochia Rubra', 'Lochia Serosa', 'Lochia Alba', 'Lochia Purulenta'],
      correctOptionIndex: 0,
      explanation: 'Lochia Rubra didominasi darah segar pada hari pertama nifas.',
    ),
    QuestionItem(
      id: 'kep_086',
      questionText: 'Pemberian ASI eksklusif menurut rekomendasi medis dilakukan selama:',
      options: ['6 Bulan Pertama', '2 Bulan Pertama', '1 Tahun', '2 Tahun'],
      correctOptionIndex: 0,
      explanation: 'ASI Eksklusif diberikan penuh tanpa tambahan makanan/minuman lain selama 6 bulan.',
    ),
    QuestionItem(
      id: 'kep_087',
      questionText: 'Refleks bayi baru lahir yang menoleh dan membuka mulut saat pipinya disentuh dinamakan:',
      options: ['Rooting Reflex', 'Sucking Reflex', 'Moro Reflex', 'Babinski Reflex'],
      correctOptionIndex: 0,
      explanation: 'Rooting reflex membantu bayi mencari puting susu ibu.',
    ),
    QuestionItem(
      id: 'kep_088',
      questionText: 'Refleks terkejut pada bayi dengan merentangkan kedua tangan dan kaki dinamakan:',
      options: ['Moro Reflex', 'Grasp Reflex', 'Babinski Reflex', 'Stepping Reflex'],
      correctOptionIndex: 0,
      explanation: 'Moro reflex adalah respon terkejut bayi terhadap suara atau perubahan mendadak.',
    ),
    QuestionItem(
      id: 'kep_089',
      questionText: 'Refleks dorongan dorsofleksi jempol kaki saat telapak kaki bayi digores dinamakan:',
      options: ['Babinski Reflex', 'Moro Reflex', 'Rooting Reflex', 'Grasp Reflex'],
      correctOptionIndex: 0,
      explanation: 'Refleks Babinski positif normal pada bayi di bawah 1-2 tahun.',
    ),
    QuestionItem(
      id: 'kep_090',
      questionText: 'Penurunan berat badan fisiologis pada bayi baru lahir dalam seminggu pertama maksimal berkisar:',
      options: ['5% - 10%', '20% - 30%', '15% - 25%', '0%'],
      correctOptionIndex: 0,
      explanation: 'Penurunan BB hingga 10% di minggu pertama normal akibat pelepasan cairan ekstra.',
    ),
    QuestionItem(
      id: 'kep_091',
      questionText: 'Upaya pencegahan penyakit sebelum gejala timbul melalui imunisasi/edukasi dinamakan pencegahan:',
      options: ['Primer', 'Sekunder', 'Tersier', 'Kuartener'],
      correctOptionIndex: 0,
      explanation: 'Pencegahan primer bertujuan mencegah onset penyakit (promotif & preventif).',
    ),
    QuestionItem(
      id: 'kep_092',
      questionText: 'Upaya penemuan kasus dini dan pengobatan segera (Early Diagnosis & Prompt Treatment) dinamakan pencegahan:',
      options: ['Sekunder', 'Primer', 'Tersier', 'Rehabilitatif'],
      correctOptionIndex: 0,
      explanation: 'Pencegahan sekunder mencakup skrening dan intervensi dini.',
    ),
    QuestionItem(
      id: 'kep_093',
      questionText: 'Upaya pemulihan dan meminimalkan kecacatan akibat penyakit kronis dinamakan pencegahan:',
      options: ['Tersier', 'Sekunder', 'Primer', 'Deteksi Dini'],
      correctOptionIndex: 0,
      explanation: 'Pencegahan tersier memfokuskan rehabilitasi pasien.',
    ),
    QuestionItem(
      id: 'kep_094',
      questionText: 'Tindakan perawatan paliatif pada pasien penyakit terminal berfokus pada:',
      options: ['Peningkatan kualitas hidup dan kenyamanan bebas nyeri', 'Penyembuhan total penyakit', 'Tindakan bedah agresif', 'Uji coba obat baru'],
      correctOptionIndex: 0,
      explanation: 'Perawatan paliatif meredakan nyeri dan gejala stadium akhir.',
    ),
    QuestionItem(
      id: 'kep_095',
      questionText: 'Kondisi kaku mayat yang muncul beberapa jam pasca kematian dinamakan:',
      options: ['Rigor Mortis', 'Algor Mortis', 'Livor Mortis', 'Decomposisi'],
      correctOptionIndex: 0,
      explanation: 'Rigor mortis adalah kekakuan otot pasca kematian.',
    ),
    QuestionItem(
      id: 'kep_096',
      questionText: 'Penurunan suhu tubuh jenazah menyesuaikan suhu lingkungan dinamakan:',
      options: ['Algor Mortis', 'Rigor Mortis', 'Livor Mortis', 'Autolisis'],
      correctOptionIndex: 0,
      explanation: 'Algor mortis adalah pendinginan suhu mayat.',
    ),
    QuestionItem(
      id: 'kep_097',
      questionText: 'Lebam mayat akibat pengendapan sel darah merah pada posisi terendah tubuh dinamakan:',
      options: ['Livor Mortis', 'Rigor Mortis', 'Algor Mortis', 'Sianosis'],
      correctOptionIndex: 0,
      explanation: 'Livor mortis adalah warna kebiruan/kebunguan akibat gravitasi darah jenazah.',
    ),
    QuestionItem(
      id: 'kep_098',
      questionText: 'Standar universal pengikatan fisik pasien gelisah berisiko membahayakan (Restraint) wajib dievaluasi minimal setiap:',
      options: ['2 Jam sekali', '8 Jam sekali', '12 Jam sekali', '24 Jam sekali'],
      correctOptionIndex: 0,
      explanation: 'Pemasangan restraint fisik memerlukan monitor dan rilis sirkulasi per 2 jam.',
    ),
    QuestionItem(
      id: 'kep_099',
      questionText: 'Tindakan pemenuhan nutrisi melalui selang langsung menembus dinding lambung dinamakan:',
      options: ['PEG (Percutaneous Endoscopic Gastrostomy)', 'NGT', 'OGT', 'TPN'],
      correctOptionIndex: 0,
      explanation: 'PEG adalah selang gastrostomi permanen di lambung.',
    ),
    QuestionItem(
      id: 'kep_100',
      questionText: 'Organisasi profesi perawat resmi yang menaungi perawat di seluruh Indonesia adalah:',
      options: ['PPNI (Persatuan Perawat Nasional Indonesia)', 'IDI', 'IBI', 'IAI'],
      correctOptionIndex: 0,
      explanation: 'PPNI adalah organisasi profesi resmi perawat Indonesia.',
    ),
  ];
}
