import '../tes_seleksi_model.dart';

List<QuestionItem> getSeniMusikQuestions() {
  return const [
    QuestionItem(
      id: 'msk_001',
      questionText: 'Elemen dasar musik yang berkaitan dengan tinggi rendahnya suatu bunyi dinamakan:',
      options: ['Nada (Pitch)', 'Dinamika', 'Timbre', 'Birama'],
      correctOptionIndex: 0,
      explanation: 'Nada (pitch) adalah frekuensi getaran bunyi yang menentukan tinggi atau rendahnya suara.',
    ),
    QuestionItem(
      id: 'msk_002',
      questionText: 'Rangkaian nada-nada yang disusun secara teratur dan berurutan serta memiliki irama dinamakan:',
      options: ['Melodi', 'Harmoni', 'Akord', 'Tempo'],
      correctOptionIndex: 0,
      explanation: 'Melodi adalah susunan linear nada-nada yang menjadi wujud utama nyanyian.',
    ),
    QuestionItem(
      id: 'msk_003',
      questionText: 'Pengaturan panjang pendek dan ketukan bunyi nada dalam durasi waktu dinamakan:',
      options: ['Ritme (Rhythm)', 'Melodi', 'Harmoni', 'Kadens'],
      correctOptionIndex: 0,
      explanation: 'Ritme mengontrol pola alur ketukan waktu bunyi musik.',
    ),
    QuestionItem(
      id: 'msk_004',
      questionText: 'Kombinasi gabungan tiga atau lebih nada yang dibunyikan secara bersamaan sehingga terdengar selaras dinamakan:',
      options: ['Akord (Chord)', 'Melodi', 'Kadens', 'Unisono'],
      correctOptionIndex: 0,
      explanation: 'Akord adalah gabungan beberapa nada yang membentuk harmoni simultan.',
    ),
    QuestionItem(
      id: 'msk_005',
      questionText: 'Karakter atau warna khas bunyi yang membedakan suara satu instrumen dengan instrumen lainnya dinamakan:',
      options: ['Timbre', 'Pitch', 'Dinamika', 'Resonansi'],
      correctOptionIndex: 0,
      explanation: 'Timbre (color tone) membedakan warna suara unik tiap instrumen.',
    ),
    QuestionItem(
      id: 'msk_006',
      questionText: 'Tingkat keras dan lembutnya volume bunyi yang dimainkan dalam karya musik dinamakan:',
      options: ['Dinamika', 'Tempo', 'Birama', 'Harmoni'],
      correctOptionIndex: 0,
      explanation: 'Dinamika mengontrol tingkat volume ekspresi keras-lembutnya musik.',
    ),
    QuestionItem(
      id: 'msk_007',
      questionText: 'Lima garis sejajar mendatar yang digunakan sebagai tempat menuliskan notasi balok dinamakan:',
      options: ['Garis Paranada (Stave)', 'Garis Birama', 'Ledger Line', 'Barline'],
      correctOptionIndex: 0,
      explanation: 'Paranada (staff) adalah 5 garis horizontal tempat meletakkan simpul notasi balok.',
    ),
    QuestionItem(
      id: 'msk_008',
      questionText: 'Tanda kunci nada pada paranada yang melingkar pada garis kedua dan melambangkan nada G dinamakan:',
      options: ['Kunci G (Treble Clef)', 'Kunci F (Bass Clef)', 'Kunci C (Alto Clef)', 'Kunci Neutral'],
      correctOptionIndex: 0,
      explanation: 'Treble Clef (Kunci G) melingkari garis kedua paranada.',
    ),
    QuestionItem(
      id: 'msk_009',
      questionText: 'Tanda kunci nada pada paranada yang melingkari garis keempat dan melambangkan nada F dinamakan:',
      options: ['Kunci F (Bass Clef)', 'Kunci G (Treble Clef)', 'Kunci C', 'Kunci Tenor'],
      correctOptionIndex: 0,
      explanation: 'Bass Clef (Kunci F) menandai letak nada F pada garis keempat.',
    ),
    QuestionItem(
      id: 'msk_010',
      questionText: 'Tanda kromatis yang berfungsi menaikkan nilai nada sebesar setengah (1/2) laras dinamakan:',
      options: ['Kres (Sharp / #)', 'Mol (Flat / ♭)', 'Pugar (Natural / ♮)', 'Mol Ganda'],
      correctOptionIndex: 0,
      explanation: 'Tanda Kres (#) menaikkan pitch nada sebesar 1/2 semitone.',
    ),
    QuestionItem(
      id: 'msk_011',
      questionText: 'Tanda kromatis yang berfungsi menurunkan nilai nada sebesar setengah (1/2) laras dinamakan:',
      options: ['Mol (Flat / ♭)', 'Kres (Sharp / #)', 'Pugar (Natural)', 'Forte'],
      correctOptionIndex: 0,
      explanation: 'Tanda Mol (♭) menurunkan pitch nada sebesar 1/2 semitone.',
    ),
    QuestionItem(
      id: 'msk_012',
      questionText: 'Tanda kromatis yang berfungsi mengembalikan nada yang sudah dinaikkan/diturunkan ke nada aslinya dinamakan:',
      options: ['Pugar (Natural / ♮)', 'Kres', 'Mol', 'Accent'],
      correctOptionIndex: 0,
      explanation: 'Tanda Pugar (Natural) membatalkan efek kres atau mol pada baris lagu.',
    ),
    QuestionItem(
      id: 'msk_013',
      questionText: 'Nilai ketukan untuk not penuh (whole note) pada birama 4/4 adalah sebesar:',
      options: ['4 Ketuk', '2 Ketuk', '1 Ketuk', '1/2 Ketuk'],
      correctOptionIndex: 0,
      explanation: 'Not penuh bernilai 4 ketuk penuh dalam birama 4/4.',
    ),
    QuestionItem(
      id: 'msk_014',
      questionText: 'Nilai ketukan untuk not setengah (half note) pada birama 4/4 adalah sebesar:',
      options: ['2 Ketuk', '4 Ketuk', '1 Ketuk', '1/2 Ketuk'],
      correctOptionIndex: 0,
      explanation: 'Not setengah bernilai 2 ketukan.',
    ),
    QuestionItem(
      id: 'msk_015',
      questionText: 'Nilai ketukan untuk not seperempat (quarter note) pada birama 4/4 adalah sebesar:',
      options: ['1 Ketuk', '2 Ketuk', '4 Ketuk', '1/2 Ketuk'],
      correctOptionIndex: 0,
      explanation: 'Not seperempat bernilai 1 ketukan utama.',
    ),
    QuestionItem(
      id: 'msk_016',
      questionText: 'Pola susunan jarak antar-nada (interval) 1 - 1 - 1/2 - 1 - 1 - 1 - 1/2 merupakan pola tangga nada:',
      options: ['Diatonis Mayor', 'Diatonis Minor Harmonis', 'Pentatonis Pelog', 'Pentatonis Salendro'],
      correctOptionIndex: 0,
      explanation: 'Diatonis Mayor memiliki formula interval baku 1 - 1 - 1/2 - 1 - 1 - 1 - 1/2.',
    ),
    QuestionItem(
      id: 'msk_017',
      questionText: 'Tangga nada yang umumnya menghasilkan nuansa musik riang gembira dan bersemangat adalah:',
      options: ['Diatonis Mayor', 'Diatonis Minor', 'Pentatonis Sedih', 'Kromatis'],
      correctOptionIndex: 0,
      explanation: 'Tangga nada mayor identik dengan kesan cerah dan gembira.',
    ),
    QuestionItem(
      id: 'msk_018',
      questionText: 'Tangga nada yang memiliki nuansa musik cenderung sedih atau syahdu dengan interval 1 - 1/2 - 1 - 1 - 1/2 - 1 - 1 dinamakan:',
      options: ['Diatonis Minor Natural', 'Diatonis Mayor', 'Pentatonis', 'Debussy Scale'],
      correctOptionIndex: 0,
      explanation: 'Tangga nada minor natural memberikan nuansa syahdu/sedih.',
    ),
    QuestionItem(
      id: 'msk_019',
      questionText: 'Tangga nada yang hanya terdiri dari 5 nada pokok dalam satu oktaf dinamakan tangga nada:',
      options: ['Pentatonis', 'Diatonis', 'Kromatis', 'Heksatonis'],
      correctOptionIndex: 0,
      explanation: 'Pentatonis (penta = lima) terdiri dari 5 nada pokok.',
    ),
    QuestionItem(
      id: 'msk_020',
      questionText: 'Jarak tinggi rendahnya antara satu nada dengan nada yang lain dinamakan:',
      options: ['Interval', 'Birama', 'Kadens', 'Harmoni'],
      correctOptionIndex: 0,
      explanation: 'Interval adalah ukuran jarak pitch antar dua nada.',
    ),
    QuestionItem(
      id: 'msk_021',
      questionText: 'Simbol dinamika "f" (Forte) dalam notasi musik memberi petunjuk untuk dimainkan secara:',
      options: ['Keras', 'Lembut', 'Sangat Lembut', 'Sedang'],
      correctOptionIndex: 0,
      explanation: 'Forte (f) berarti dimainkan secara keras/loud.',
    ),
    QuestionItem(
      id: 'msk_022',
      questionText: 'Simbol dinamika "p" (Piano) dalam notasi musik memberi petunjuk untuk dimainkan secara:',
      options: ['Lembut', 'Keras', 'Sangat Keras', 'Cepat'],
      correctOptionIndex: 0,
      explanation: 'Piano (p) berarti dimainkan secara lembut/soft.',
    ),
    QuestionItem(
      id: 'msk_023',
      questionText: 'Petunjuk perubahan dinamika yang menginstruksikan tingkat volume musik makin lama makin keras dinamakan:',
      options: ['Crescendo', 'Decrescendo', 'Diminuendo', 'Rallentando'],
      correctOptionIndex: 0,
      explanation: 'Crescendo ditandai simbol (<) menginstruksikan bertambah keras bertahap.',
    ),
    QuestionItem(
      id: 'msk_024',
      questionText: 'Petunjuk perubahan dinamika yang menginstruksikan volume musik makin lama makin lembut dinamakan:',
      options: ['Decrescendo / Diminuendo', 'Crescendo', 'Accelerando', 'Staccato'],
      correctOptionIndex: 0,
      explanation: 'Decrescendo (>) menandakan penurunan volume secara berangsur lembut.',
    ),
    QuestionItem(
      id: 'msk_025',
      questionText: 'Istilah petunjuk tempo musik yang menandakan tempo sangat lambat dan megah/anggun adalah:',
      options: ['Largo', 'Allegro', 'Presto', 'Vivace'],
      correctOptionIndex: 0,
      explanation: 'Largo bernilai tempo sangat lambat (sekitar 40-60 BPM).',
    ),
    QuestionItem(
      id: 'msk_026',
      questionText: 'Istilah tempo musik sedang yang setara dengan laju kecepatan orang berjalan santai dinamakan:',
      options: ['Andante', 'Allegro', 'Largo', 'Presto'],
      correctOptionIndex: 0,
      explanation: 'Andante (walking pace) berkecepatan sedang (76-108 BPM).',
    ),
    QuestionItem(
      id: 'msk_027',
      questionText: 'Istilah petunjuk tempo musik yang menandakan laju permaian cepat dan riang gembira dinamakan:',
      options: ['Allegro', 'Andante', 'Adagio', 'Lento'],
      correctOptionIndex: 0,
      explanation: 'Allegro bernilai tempo cepat dan gembira (120-156 BPM).',
    ),
    QuestionItem(
      id: 'msk_028',
      questionText: 'Alat pengukur atau pengatur kecepatan tempo ketukan lagu secara konstan dinamakan:',
      options: ['Metronom', 'Tuning Fork', 'Synthesizer', 'Equalizer'],
      correctOptionIndex: 0,
      explanation: 'Metronom mengeluarkan detak tempo stabil untuk latihan musik.',
    ),
    QuestionItem(
      id: 'msk_029',
      questionText: 'Klasifikasi instrumen musik Hornbostel-Sachs yang sumber bunyinya dari getaran kolom udara dinamakan:',
      options: ['Aerofon', 'Kordofon', 'Idiofon', 'Membranofon'],
      correctOptionIndex: 0,
      explanation: 'Aerofon menghasilkan suara lewat getaran kolom udara (seperti flute, suling, trompet).',
    ),
    QuestionItem(
      id: 'msk_030',
      questionText: 'Klasifikasi instrumen musik yang sumber bunyinya berasal dari getaran dawai/senar dinamakan:',
      options: ['Kordofon', 'Aerofon', 'Idiofon', 'Elektrofon'],
      correctOptionIndex: 0,
      explanation: 'Kordofon menghasilkan suara dari petikan/gesekan senar (seperti biola, gitar, kecapi).',
    ),
    QuestionItem(
      id: 'msk_031',
      questionText: 'Klasifikasi instrumen musik yang sumber bunyinya berasal dari getaran selaput kulit/membran dinamakan:',
      options: ['Membranofon', 'Kordofon', 'Idiofon', 'Aerofon'],
      correctOptionIndex: 0,
      explanation: 'Membranofon bersumber dari kulit/selaput terentang (seperti kendang, drum, timbales).',
    ),
    QuestionItem(
      id: 'msk_032',
      questionText: 'Klasifikasi instrumen musik yang sumber bunyinya berasal dari getaran tubuh fisik alat itu sendiri dinamakan:',
      options: ['Idiofon', 'Membranofon', 'Aerofon', 'Elektrofon'],
      correctOptionIndex: 0,
      explanation: 'Idiofon menghasilkan pendaran bunyi dari bahan fisik utamanya (seperti gong, angklung, kolintang).',
    ),
    QuestionItem(
      id: 'msk_033',
      questionText: 'Alat musik tradisional berbahan pipa bambu asal Jawa Barat yang dimainkan dengan digoyangkan dinamakan:',
      options: ['Angklung', 'Suling', 'Calung', 'Kecapi'],
      correctOptionIndex: 0,
      explanation: 'Angklung terbuat dari bambu yang berbunyi ketika digoyang.',
    ),
    QuestionItem(
      id: 'msk_034',
      questionText: 'Alat musik petik tradisional khas Pulau Rote (NTT) yang terbuat dari daun lontar dinamakan:',
      options: ['Sasando', 'Kecapi', 'Sampe', 'Gamelan'],
      correctOptionIndex: 0,
      explanation: 'Sasando dipetik halus dengan tabung bambu dilingkupi daun lontar.',
    ),
    QuestionItem(
      id: 'msk_035',
      questionText: 'Alat musik pukul tradisional berbahan susunan bilah kayu khas Sulawesi Utara dinamakan:',
      options: ['Kolintang', 'Gambang', 'Gamelan', 'Tifa'],
      correctOptionIndex: 0,
      explanation: 'Kolintang terdiri dari bilah kayu telur yang dipukul menggunakan pemukul khusus.',
    ),
    QuestionItem(
      id: 'msk_036',
      questionText: 'Alat musik perkusi pukul sejenis kendang silinder khas daerah Papua dan Maluku dinamakan:',
      options: ['Tifa', 'Kendang', 'Gendang Beleq', 'Rebana'],
      correctOptionIndex: 0,
      explanation: 'Tifa adalah instrumen perkusi membranofon khas Indonesia timur.',
    ),
    QuestionItem(
      id: 'msk_037',
      questionText: 'Perangkat musik tradisional Nusantara yang terdiri atas Gong, Saron, Bonang, dan Kenong dinamakan:',
      options: ['Gamelan', 'Kolintang', 'Tanjidor', 'Arumba'],
      correctOptionIndex: 0,
      explanation: 'Gamelan adalah perangkat instrumen karawitan tradisional Jawa/Bali/Sunda.',
    ),
    QuestionItem(
      id: 'msk_038',
      questionText: 'Alat musik gesek terbesar dalam orkes simfoni yang menghasilkan nada terendah dinamakan:',
      options: ['Kontrabas (Double Bass)', 'Cello', 'Viola', 'Biola'],
      correctOptionIndex: 0,
      explanation: 'Kontrabas (double bass) adalah anggota terbesar dan bernada paling bas pada keluarga biola.',
    ),
    QuestionItem(
      id: 'msk_039',
      questionText: 'Instrumen gesek terkecil dengan nada tertinggi pada keluarga string orchestra adalah:',
      options: ['Biola (Violin)', 'Viola', 'Cello', 'Harp'],
      correctOptionIndex: 0,
      explanation: 'Violin (biola) berlaras nada soprano paling tinggi.',
    ),
    QuestionItem(
      id: 'msk_040',
      questionText: 'Alat musik tiup kayu berbahan logam halus yang dimainkan memanjang kesamping dinamakan:',
      options: ['Flute', 'Klarinet', 'Oboe', 'Saxophone'],
      correctOptionIndex: 0,
      explanation: 'Flute dimainkan dengan ditiup mendatar menyamping.',
    ),
    QuestionItem(
      id: 'msk_041',
      questionText: 'Alat musik tiup logam yang menggunakan mekanisme pipa geser (slide) untuk mengubah pitch nada adalah:',
      options: ['Trombone', 'Trumpet', 'French Horn', 'Tuba'],
      correctOptionIndex: 0,
      explanation: 'Trombone mengubah panjang pipa udara lewat geseran pipa slide.',
    ),
    QuestionItem(
      id: 'msk_042',
      questionText: 'Perkusi berlaras yang terdiri dari bejana logam tembaga besar berselaput kulit yang distem pedal dinamakan:',
      options: ['Timpani', 'Snare Drum', 'Cymbal', 'Xylophone'],
      correctOptionIndex: 0,
      explanation: 'Timpani adalah perkusi tembaga bernada pasti dalam orkes simfoni.',
    ),
    QuestionItem(
      id: 'msk_043',
      questionText: 'Jangkauan wilayah suara tertinggi untuk kelompok wanita dalam paduan suara dinamakan:',
      options: ['Sopran', 'Mezzo-Sopran', 'Alto', 'Tenor'],
      correctOptionIndex: 0,
      explanation: 'Sopran adalah tipe suara wanita tertinggi.',
    ),
    QuestionItem(
      id: 'msk_044',
      questionText: 'Jangkauan wilayah suara rendah untuk kelompok wanita dalam paduan suara dinamakan:',
      options: ['Alto', 'Sopran', 'Tenor', 'Bariton'],
      correctOptionIndex: 0,
      explanation: 'Alto (kontralto) adalah register nada rendah vokal wanita.',
    ),
    QuestionItem(
      id: 'msk_045',
      questionText: 'Jangkauan wilayah suara tinggi untuk kelompok pria dalam paduan suara dinamakan:',
      options: ['Tenor', 'Bass', 'Bariton', 'Alto'],
      correctOptionIndex: 0,
      explanation: 'Tenor adalah jenis suara vokal tinggi pria.',
    ),
    QuestionItem(
      id: 'msk_046',
      questionText: 'Jangkauan wilayah suara terendah untuk kelompok pria dalam paduan suara dinamakan:',
      options: ['Bass', 'Tenor', 'Bariton', 'Sopran'],
      correctOptionIndex: 0,
      explanation: 'Bass adalah wilayah jangkauan vokal terendah pria.',
    ),
    QuestionItem(
      id: 'msk_047',
      questionText: 'Kelompok pemusik/penyanyi yang terdiri dari empat orang pemain dinamakan:',
      options: ['Kuartet', 'Trio', 'Kuintet', 'Duet'],
      correctOptionIndex: 0,
      explanation: 'Kuartet merupakan format sajian 4 orang penyaji musik.',
    ),
    QuestionItem(
      id: 'msk_048',
      questionText: 'Grup besar penyanyi vokal yang menyanyikan lagu secara bersama-sama dalam pembagian suara dinamakan:',
      options: ['Paduan Suara (Choir)', 'Band', 'Orkestra', 'Ensemble'],
      correctOptionIndex: 0,
      explanation: 'Paduan suara (choir) menyanyikan gabungan harmonis SATB.',
    ),
    QuestionItem(
      id: 'msk_049',
      questionText: 'Keahlian merespons atau menciptakan alur nada secara langsung tanpa petunjuk tertulis naskah partitur dinamakan:',
      options: ['Improvisasi', 'Aransemen', 'Transposisi', 'Komposisi'],
      correctOptionIndex: 0,
      explanation: 'Improvisasi adalah ekspresi nada spontan saat bermain musik.',
    ),
    QuestionItem(
      id: 'msk_050',
      questionText: 'Kegiatan menyusun atau mengubah kembali bentuk penyajian karya musik tanpa menghilangkan jiwa lagu aslinya dinamakan:',
      options: ['Aransemen', 'Transposisi', 'Kritik Musik', 'Notasi'],
      correctOptionIndex: 0,
      explanation: 'Aransemen mengolah kembali instrumen dan warna musik suatu lagu.',
    ),
    QuestionItem(
      id: 'msk_051',
      questionText: 'Proses memindahkan nada dasar suatu lagu ke tangga nada lain yang lebih tinggi atau rendah dinamakan:',
      options: ['Transposisi', 'Modulasi', 'Improvisasi', 'Kadens'],
      correctOptionIndex: 0,
      explanation: 'Transposisi mengubah tangga nada keseluruhan lagu ke kunci lain.',
    ),
    QuestionItem(
      id: 'msk_052',
      questionText: 'Komposer Barok Jerman ternama pembuat karya monumental "Toccata and Fugue in D minor" adalah:',
      options: ['Johann Sebastian Bach', 'Antonio Vivaldi', 'George Frideric Handel', 'Claudio Monteverdi'],
      correctOptionIndex: 0,
      explanation: 'J.S. Bach adalah maestro terbesar era musik Barok.',
    ),
    QuestionItem(
      id: 'msk_053',
      questionText: 'Komposer jenius era Klasik asal Austria yang menciptakan ratusan karya simfoni sejak masa kecilnya adalah:',
      options: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Franz Joseph Haydn', 'Franz Schubert'],
      correctOptionIndex: 0,
      explanation: 'W.A. Mozart adalah komposer prodigy era Klasik.',
    ),
    QuestionItem(
      id: 'msk_054',
      questionText: 'Komposer Jerman era transisi Klasik-Romantik pencipta Simfoni No. 9 yang tetap menggubah karya walau mengalami ketulian adalah:',
      options: ['Ludwig van Beethoven', 'J.S. Bach', 'Johannes Brahms', 'Richard Wagner'],
      correctOptionIndex: 0,
      explanation: 'Beethoven tetap mahakarya menggubah musik meskin kehilangan pendengarannya.',
    ),
    QuestionItem(
      id: 'msk_055',
      questionText: 'Komposer era Romantik asal Polandia berjuluk "Penyair Piano" pembuat karya-karya piano virtuoso adalah:',
      options: ['Frédéric Chopin', 'Franz Liszt', 'Pyotr Ilyich Tchaikovsky', 'Felix Mendelssohn'],
      correctOptionIndex: 0,
      explanation: 'Frédéric Chopin terkenal dengan komposisi piano yang sangat puitis.',
    ),
    QuestionItem(
      id: 'msk_056',
      questionText: 'Genre musik Amerika awal abad ke-20 berkarakter irama sinkopasi dan improvisasi melodi yang lahir di New Orleans adalah:',
      options: ['Jazz', 'Rock and Roll', 'Country', 'Disco'],
      correctOptionIndex: 0,
      explanation: 'Jazz kaya akan ritme syncopation dan kecakapan improvisasi.',
    ),
    QuestionItem(
      id: 'msk_057',
      questionText: 'Genre musik ekspresi kesedihan berlatar pola harmoni 12-bar asal Amerika Serikat dinamakan:',
      options: ['Blues', 'Reggae', 'Pop', 'Ska'],
      correctOptionIndex: 0,
      explanation: 'Blues berdasar pada struktur 12-bar blues progressions.',
    ),
    QuestionItem(
      id: 'msk_058',
      questionText: 'Genre musik populer khas Indonesia yang memadukan unsur musik Melayu, India, dan Arab dengan cengkok vokal khas adalah:',
      options: ['Dangdut', 'Keroncong', 'Gambus', 'Campursari'],
      correctOptionIndex: 0,
      explanation: 'Dangdut adalah genre musik populer khas Indonesia.',
    ),
    QuestionItem(
      id: 'msk_059',
      questionText: 'Perangkat lunak komputer yang digunakan untuk merekam, mengedit, dan merancang musik digital dinamakan:',
      options: ['DAW (Digital Audio Workstation)', 'MIDI Controller', 'Plugin VST', 'Soundcard'],
      correctOptionIndex: 0,
      explanation: 'DAW (seperti Cubase, Logic Pro, Ableton) memfasilitasi produksi musik digital.',
    ),
    QuestionItem(
      id: 'msk_060',
      questionText: 'Standar protokol komunikasi sinyal data digital antar-instrumen musik elektronik dengan komputer dinamakan:',
      options: ['MIDI (Musical Instrument Digital Interface)', 'WAV', 'MP3', 'ASIO'],
      correctOptionIndex: 0,
      explanation: 'MIDI mengirimkan data notasi dan kontrol musik antar perangkat.',
    ),
    QuestionItem(
      id: 'msk_061',
      questionText: 'Alat musik elektronik yang menghasilkan dan memanipulasi sinyal gelombang bunyi sintetis buatan dinamakan:',
      options: ['Synthesizer', 'Sampler', 'Amplifier', 'Mixer'],
      correctOptionIndex: 0,
      explanation: 'Synthesizer merancang pendaran suara elektrik buatan.',
    ),
    QuestionItem(
      id: 'msk_062',
      questionText: 'Pahlawan nasional komposer lagu kebangsaan "Indonesia Raya" adalah:',
      options: ['W.R. Supratman', 'Ismail Marzuki', 'Cornel Simanjuntak', 'Kusbini'],
      correctOptionIndex: 0,
      explanation: 'Wage Rudolf Supratman menciptakan lagu kebangsaan Indonesia Raya.',
    ),
    QuestionItem(
      id: 'msk_063',
      questionText: 'Komposer maestro Indonesia pencipta lagu-lagu perjuangan seperti "Rayuan Pulau Kelapa" dan "Gugur Bunga" adalah:',
      options: ['Ismail Marzuki', 'W.R. Supratman', 'Gesang', 'Iwan Fals'],
      correctOptionIndex: 0,
      explanation: 'Ismail Marzuki menciptakan banyak lagu perjuangan legendaris Indonesia.',
    ),
    QuestionItem(
      id: 'msk_064',
      questionText: 'Pencipta lagu keroncong legendaris terkemuka "Bengawan Solo" yang terkenal di mancanegara adalah:',
      options: ['Gesang', 'Bing Slamet', 'Titiek Puspa', 'Waldjinah'],
      correctOptionIndex: 0,
      explanation: 'Gesang Martohartono adalah maestro keroncong pencipta Bengawan Solo.',
    ),
    QuestionItem(
      id: 'msk_065',
      questionText: 'Conductor / konduktor kenamaan Indonesia yang memimpin orkes "Twilite Orchestra" adalah:',
      options: ['Addie MS', 'Erwin Gutawa', 'Avip Priatna', 'Purwacaraka'],
      correctOptionIndex: 0,
      explanation: 'Addie MS memimpin Twilite Orchestra.',
    ),
    QuestionItem(
      id: 'msk_066',
      questionText: 'Penata musik simfoni ternama Indonesia yang mendirikan Erwin Gutawa Orchestra adalah:',
      options: ['Erwin Gutawa', 'Addie MS', 'Yockie Suryo Prayogo', 'Yovie Widianto'],
      correctOptionIndex: 0,
      explanation: 'Erwin Gutawa adalah komponis dan aranser orkestra papan atas Indonesia.',
    ),
    QuestionItem(
      id: 'msk_067',
      questionText: 'Struktur akord paling dasar yang terdiri dari susunan tiga nada (alas, ters, dan kuint) dinamakan:',
      options: ['Triad', 'Septim', 'Extended Chord', 'Power Chord'],
      correctOptionIndex: 0,
      explanation: 'Triad adalah kombinasi 3 nada pembentuk dasar akord.',
    ),
    QuestionItem(
      id: 'msk_068',
      questionText: 'Jarak nada antara nada pertama hingga nada kedelapan (seperti dari Do rendah ke Do tinggi) dinamakan interval:',
      options: ['Oktaf (Octave)', 'Kuint', 'Sekond', 'Septim'],
      correctOptionIndex: 0,
      explanation: 'Oktaf murni berjarak 8 tingkatan nada.',
    ),
    QuestionItem(
      id: 'msk_069',
      questionText: 'Jarak nada yang berjarak 5 tingkatan nada (seperti dari C ke G) dinamakan interval:',
      options: ['Kuint (Quint / Fifth)', 'Kuart', 'Ters', 'Seks'],
      correctOptionIndex: 0,
      explanation: 'Kuint adalah interval murni berselisih 5 nada.',
    ),
    QuestionItem(
      id: 'msk_070',
      questionText: 'Jarak nada yang berjarak 3 tingkatan nada (seperti dari C ke E) dinamakan interval:',
      options: ['Ters (Third)', 'Kuart', 'Kuint', 'Prima'],
      correctOptionIndex: 0,
      explanation: 'Ters (Third) menentukan kualitas mayor atau minor suatu akord.',
    ),
    QuestionItem(
      id: 'msk_071',
      questionText: 'Istilah pertunjukan bernyanyi kelompok vokal tanpa iringan musik alat apa pun dinamakan:',
      options: ['Acappella', 'Unisono', 'Lip-sync', 'Canon'],
      correctOptionIndex: 0,
      explanation: 'Acappella disajikan murni hanya oleh harmoni olah suara vokal.',
    ),
    QuestionItem(
      id: 'msk_072',
      questionText: 'Gelar bagi pemusik yang memiliki kemahiran dan kelincahan teknik bermain instrumen luar biasa dinamakan:',
      options: ['Virtuoso', 'Maestro', 'Arranger', 'Composer'],
      correctOptionIndex: 0,
      explanation: 'Virtuoso adalah penyebutan bagi pemain instrumen berkeahlian teknik tinggi.',
    ),
    QuestionItem(
      id: 'msk_073',
      questionText: 'Alat pemetik kecil berujung pipih yang digunakan untuk memetik senar gitar dinamakan:',
      options: ['Plektrum / Pick', 'Bow', 'Capo', 'Slide'],
      correctOptionIndex: 0,
      explanation: 'Pick (plektrum) membantu memetik senar gitar.',
    ),
    QuestionItem(
      id: 'msk_074',
      questionText: 'Tongkat penggesek berbahan rambut ekor kuda yang dipakai menggesek senar biola dinamakan:',
      options: ['Bow (Penggesek)', 'Plektrum', 'Stick', 'Rosin'],
      correctOptionIndex: 0,
      explanation: 'Bow (penggesek biola) menggunakan helai rambut ekor kuda tebal.',
    ),
    QuestionItem(
      id: 'msk_075',
      questionText: 'Pengaturan penempatan sebaran audio ke spiker kanal kiri dan kanan dinamakan:',
      options: ['Panning Audio', 'Gain Staging', 'Equalization', 'Normalization'],
      correctOptionIndex: 0,
      explanation: 'Panning menentukan posisi letak stereo kiri-kanan bunyi.',
    ),
    QuestionItem(
      id: 'msk_076',
      questionText: 'Efek audio yang menciptakan gema dan kesan pantulan ruang pada bunyi dinamakan:',
      options: ['Reverb', 'Delay', 'Chorus', 'Flanger'],
      correctOptionIndex: 0,
      explanation: 'Reverb menyimulasikan akustik pendaran pantulan suara di dalam ruang.',
    ),
    QuestionItem(
      id: 'msk_077',
      questionText: 'Alat pemroses audio yang berfungsi meratakan dinamika kejutan volume suara dinamakan:',
      options: ['Compressor', 'Equalizer', 'Limiter', 'Noise Gate'],
      correctOptionIndex: 0,
      explanation: 'Compressor menekan sinyal audio yang terlalu keras agar volume seimbang.',
    ),
    QuestionItem(
      id: 'msk_078',
      questionText: 'Proses mengatur dan menyeimbangkan spektrum frekuensi audio (bass, mid, treble) dinamakan:',
      options: ['Equalization (EQ)', 'Compression', 'Panning', 'Mastering'],
      correctOptionIndex: 0,
      explanation: 'EQ memotong atau menaikkan rentang frekuensi tertentu.',
    ),
    QuestionItem(
      id: 'msk_079',
      questionText: 'Jenis mikrofon studio peka tinggi yang membutuhkan daya listrik tambahan Phantom Power 48V dinamakan:',
      options: ['Mikrofon Condenser', 'Mikrofon Dynamic', 'Mikrofon Ribbon', 'Mikrofon Carbon'],
      correctOptionIndex: 0,
      explanation: 'Mikrofon Condenser membutuhkan phantom power 48V untuk beroperasi.',
    ),
    QuestionItem(
      id: 'msk_080',
      questionText: 'Instrumen tiup kayu berlidah getar ganda (double-reed) yang bersuara khas meliuk dramatis dinamakan:',
      options: ['Oboe', 'Klarinet', 'Flute', 'Saxophone'],
      correctOptionIndex: 0,
      explanation: 'Oboe menggunakan double-reed yang menghasilkan timbre meliuk khas.',
    ),
    QuestionItem(
      id: 'msk_081',
      questionText: 'Alat musik tiup logam berbentuk pipa melingkar dengan corong mengarah ke belakang dinamakan:',
      options: ['French Horn', 'Trompet', 'Trombone', 'Tuba'],
      correctOptionIndex: 0,
      explanation: 'French Horn melingkar dengan corong suara dihadapkan ke belakang.',
    ),
    QuestionItem(
      id: 'msk_082',
      questionText: 'Instrumen tiup logam paling besar yang menghasilkan nada terendah dalam orkestra dinamakan:',
      options: ['Tuba', 'Trombone', 'Euphonium', 'Cornet'],
      correctOptionIndex: 0,
      explanation: 'Tuba adalah instrumen terbesar pada kelompok tiup logam (brass).',
    ),
    QuestionItem(
      id: 'msk_083',
      questionText: 'Alat musik perkusi bernada yang terdiri dari jajaran bilah-bilah kayu dinamakan:',
      options: ['Marimba / Xylophone', 'Glockenspiel', 'Vibraphone', 'Chimes'],
      correctOptionIndex: 0,
      explanation: 'Marimba dan Xylophone memiliki bilah berbahan kayu.',
    ),
    QuestionItem(
      id: 'msk_084',
      questionText: 'Alat musik perkusi bernada yang terdiri dari bilah-bilah logam berkilau dinamakan:',
      options: ['Glockenspiel', 'Marimba', 'Xylophone', 'Angklung'],
      correctOptionIndex: 0,
      explanation: 'Glockenspiel menggunakan bilah-bilah baja/logam.',
    ),
    QuestionItem(
      id: 'msk_085',
      questionText: 'Birama 3/4 dalam petunjuk musik memiliki makna dalam tiap satu baris birama terdapat:',
      options: ['3 ketukan dengan nilai tiap ketukan 1/4', '4 ketukan dengan nilai tiap ketukan 1/3', '3/4 ketukan saja', '6 ketukan cepat'],
      correctOptionIndex: 0,
      explanation: 'Birama 3/4 terdiri dari 3 ketukan bernilai not seperempat.',
    ),
    QuestionItem(
      id: 'msk_086',
      questionText: 'Birama 6/8 tergolong ke dalam jenis kelompok birama:',
      options: ['Birama Campuran (Compound Time)', 'Birama Tunggal', 'Birama Asimetris', 'Birama Bebas'],
      correctOptionIndex: 0,
      explanation: 'Birama 6/8 mengelompokkan ketukan dalam dua denyut triplet (compound duple).',
    ),
    QuestionItem(
      id: 'msk_087',
      questionText: 'Garis tegak lurus penyekat antar-birama pada garis paranada dinamakan:',
      options: ['Garis Birama (Barline)', 'Garis Paranada', 'Garis Penutup', 'Garis Bantu'],
      correctOptionIndex: 0,
      explanation: 'Barline membagi paranada menjadi ruas-ruas birama.',
    ),
    QuestionItem(
      id: 'msk_088',
      questionText: 'Dua garis tegak lurus tebal di akhir lagu yang menunjukkan bahwa komposisi musik telah selesai dinamakan:',
      options: ['Garis Penutup (Double Barline)', 'Garis Birama', 'Garis Ulang', 'Clef'],
      correctOptionIndex: 0,
      explanation: 'Double Barline mengindikasikan akhir partitur lagu.',
    ),
    QuestionItem(
      id: 'msk_089',
      questionText: 'Tanda notasi musik yang menginstruksikan pemain mengulang lagu dari awal dinamakan:',
      options: ['Da Capo (D.C.)', 'Dal Segno (D.S.)', 'Fine', 'Coda'],
      correctOptionIndex: 0,
      explanation: 'Da Capo (D.C.) memerintahkan pengulangan lagu dari awal (head).',
    ),
    QuestionItem(
      id: 'msk_090',
      questionText: 'Petunjuk tempo yang memerintahkan laju lagu diperlambat secara bertahap dinamakan:',
      options: ['Ritardando / Rallentando', 'Accelerando', 'A tempo', 'Presto'],
      correctOptionIndex: 0,
      explanation: 'Ritardando (rit.) memperlambat tempo secara gradual.',
    ),
    QuestionItem(
      id: 'msk_091',
      questionText: 'Petunjuk tempo yang memerintahkan laju musik makin lama makin cepat dinamakan:',
      options: ['Accelerando', 'Ritardando', 'Fermata', 'Rubato'],
      correctOptionIndex: 0,
      explanation: 'Accelerando (accel.) mempercepat laju tempo secara gradual.',
    ),
    QuestionItem(
      id: 'msk_092',
      questionText: 'Teknik membunyikan atau menyanyikan nada-nada secara pendek, tegas, dan terputus-putus dinamakan:',
      options: ['Staccato', 'Legato', 'Tenuto', 'Glissando'],
      correctOptionIndex: 0,
      explanation: 'Staccato ditandai titik di atas/bawah not untuk nada terputus tegas.',
    ),
    QuestionItem(
      id: 'msk_093',
      questionText: 'Teknik menyanyikan atau memainkan nada-nada secara tersambung halus tanpa terputus dinamakan:',
      options: ['Legato', 'Staccato', 'Marcato', 'Vibrato'],
      correctOptionIndex: 0,
      explanation: 'Legato mengikat nada-nada mengalir secara halus tersambung.',
    ),
    QuestionItem(
      id: 'msk_094',
      questionText: 'Ornamen keluk vokal meliuk melayang khas pada penyanyi musik Dangdut atau Melayu dinamakan:',
      options: ['Cengkok', 'Falsetto', 'Vibrato', 'Groove'],
      correctOptionIndex: 0,
      explanation: 'Cengkok adalah hiasan ornamen vokal khas dalam musik Melayu/Dangdut.',
    ),
    QuestionItem(
      id: 'msk_095',
      questionText: 'Ensembel musik tradisional khas Betawi yang kental dengan tiupan trompet dan trombon dinamakan:',
      options: ['Tanjidor', 'Gambang Kromong', 'Marawis', 'Keroncong'],
      correctOptionIndex: 0,
      explanation: 'Tanjidor adalah orkes tiup tradisional Betawi.',
    ),
    QuestionItem(
      id: 'msk_096',
      questionText: 'Alat musik tiup bambu tradisional khas Minangkabau yang ditiup secara melintang dinamakan:',
      options: ['Saluang', 'Seruling', 'Srampat', 'Tarompet'],
      correctOptionIndex: 0,
      explanation: 'Saluang adalah alat musik tiup khas Minangkabau.',
    ),
    QuestionItem(
      id: 'msk_097',
      questionText: 'Alat musik petik tradisional mirip gitar khas Suku Dayak Kalimantan Timur dinamakan:',
      options: ['Sampe', 'Hasapi', 'Japen', 'Kecapi'],
      correctOptionIndex: 0,
      explanation: 'Sampe adalah alat musik petik khas Kalimantan Timur.',
    ),
    QuestionItem(
      id: 'msk_098',
      questionText: 'Genre musik Jamaika dipelopori Bob Marley yang identik dengan ritme aksen off-beat dinamakan:',
      options: ['Reggae', 'Ska', 'Dub', 'Calypso'],
      correctOptionIndex: 0,
      explanation: 'Reggae berkarakteristik ritme off-beat (skank).',
    ),
    QuestionItem(
      id: 'msk_099',
      questionText: 'Genre musik populer yang lahir era 1950-an dengan ciri khas distorsi gitar listrik dan ketukan drum energik dinamakan:',
      options: ['Rock', 'Jazz', 'Pop', 'Country'],
      correctOptionIndex: 0,
      explanation: 'Rock identik dengan raungan gitar distorsi dan beat drum bertenaga.',
    ),
    QuestionItem(
      id: 'msk_100',
      questionText: 'Disiplin ilmu dan cabang seni yang mengolah media bunyi/suara menjadi karya nada yang indah dinamakan:',
      options: ['Seni Musik', 'Seni Rupa', 'Seni Tari', 'Seni Teater'],
      correctOptionIndex: 0,
      explanation: 'Seni Musik adalah cabang seni yang memanfaatkan media media nada dan bunyi.',
    ),
  ];
}
