import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraMandarinQuestions() {
  return const [
    QuestionItem(
      id: 'sas_man_001',
      questionText: 'Empat Mahakarya Klasik Sastra Tiongkok (Si Da Ming Zhu / 四大名著) terdiri dari novel-novel berikut, KECUALI:',
      options: ['Jin Ping Mei (金瓶梅)', 'San Guo Yan Yi (Kisah Tiga Kerajaan)', 'Xi You Ji (Perjalanan ke Barat)', 'Hong Lou Meng (Impian Paviliun Merah)'],
      correctOptionIndex: 0,
      explanation: 'Empat Karya Agung Klasik adalah San Guo Yan Yi, Shui Hu Zhuan, Xi You Ji, dan Hong Lou Meng. Jin Ping Mei tergolong karya klasik lain.',
    ),
    QuestionItem(
      id: 'sas_man_002',
      questionText: 'Novel sejarah monumental "San Guo Yan Yi" (Kisah Tiga Kerajaan / 三國演義) ditulis oleh pengarang Dinasti Ming bernama:',
      options: ['Luo Guanzhong (罗贯中)', 'Shi Nai\'an (施耐庵)', 'Wu Cheng\'en (吴承恩)', 'Cao Xueqin (曹雪芹)'],
      correctOptionIndex: 0,
      explanation: 'Luo Guanzhong mengarang San Guo Yan Yi pada abad ke-14 menceritakan perpecahan Wei, Shu, dan Wu.',
    ),
    QuestionItem(
      id: 'sas_man_003',
      questionText: 'Novel Xi You Ji (Perjalanan ke Barat / 西遊記) menceritakan petualangan Pendeta Xuanzang ke India ditemani tokoh kera sakti bernama:',
      options: ['Sun Wukong (孙悟空)', 'Zhu Bajie (猪八戒)', 'Sha Wujing (沙悟净)', 'Nezha (哪吒)'],
      correctOptionIndex: 0,
      explanation: 'Sun Wukong (Raja Kera / Qitian Dasheng) adalah pendamping utama Xuanzang ciptaan Wu Cheng\'en.',
    ),
    QuestionItem(
      id: 'sas_man_004',
      questionText: 'Novel "Hong Lou Meng" (Impian Paviliun Merah / 红楼梦) karya Cao Xueqin menceritakan kemerosotan klan keluarga bangsawan Jia dan kisah cinta antara:',
      options: ['Jia Baoyu (贾宝玉) dan Lin Daiyu (林黛玉)', 'Sun Wukong dan Guanyin', 'Song Jiang dan Li Kui', 'Liu Bei dan Sun Shangxiang'],
      correctOptionIndex: 0,
      explanation: 'Hong Lou Meng menggambarkan tragedi cinta Baoyu dan Daiyu di tengah kejayaan dan kemunduran keluarga Jia.',
    ),
    QuestionItem(
      id: 'sas_man_005',
      questionText: 'Novel "Shui Hu Zhuan" (Batas Air / Outlaws of the Marsh / 水滸傳) mengisahkan perlawanan 108 pahlawan di Gunung Liang (Liangshan) dipimpin oleh:',
      options: ['Song Jiang (宋江)', 'Lu Zhishen (鲁智深)', 'Wu Song (武松)', 'Lin Chong (林冲)'],
      correctOptionIndex: 0,
      explanation: 'Song Jiang (Timely Rain) adalah pemimpin 108 pendekar Liangshan Po tulisan Shi Nai\'an.',
    ),
    QuestionItem(
      id: 'sas_man_006',
      questionText: 'Penyair terbesar Dinasti Tang yang dijuluki "Dewa Puisi" (Shi Xian / 诗仙) dan terkenal akan gaya romantis bebasnya adalah:',
      options: ['Li Bai (李白)', 'Du Fu (杜甫)', 'Bai Juyi (白居易)', 'Wang Wei (王维)'],
      correctOptionIndex: 0,
      explanation: 'Li Bai (701–762) adalah pujangga legendaris Tang berjuluk Shi Xian (Poet Immortal).',
    ),
    QuestionItem(
      id: 'sas_man_007',
      questionText: 'Penyair Dinasti Tang yang dijuluki "Santo Puisi" (Shi Sheng / 诗圣) dan menulis puisi-puisi realisme kepedihan rakyat adalah:',
      options: ['Du Fu (杜甫)', 'Li Bai (李白)', 'Li Shangyin (李商隐)', 'Meng Haoran (孟浩然)'],
      correctOptionIndex: 0,
      explanation: 'Du Fu (712–770) merekam penderitaan perang Pemberontakan An Lushan dalam puisi-puisinya.',
    ),
    QuestionItem(
      id: 'sas_man_008',
      questionText: 'Penyair dan pelukis Tang yang terkenal dengan puisi alam dan meditasi Zen-Buddhisme (Shi Zhong You Hua, Hua Zhong You Shi) adalah:',
      options: ['Wang Wei (王维)', 'Li Bai (李白)', 'Du Mu (杜牧)', 'Liu Zongyuan (柳宗元)'],
      correctOptionIndex: 0,
      explanation: 'Su Shi memuji Wang Wei: "Dalam puisinya ada lukisan, dalam lukisannya ada puisi".',
    ),
    QuestionItem(
      id: 'sas_man_009',
      questionText: 'Sastrawan dan negarawan agung Dinasti Song yang mempopulerkan genre puisi Ci (Song Ci) seperti "Chibi Fu" dan "Shui Tiao Ge Tou" adalah:',
      options: ['Su Shi / Su Dongpo (苏轼)', 'Xin Qiji (辛弃疾)', 'Li Qingzhao (李清照)', 'Lu You (陆游)'],
      correctOptionIndex: 0,
      explanation: 'Su Dongpo (1037–1101) adalah seniman serba bisa pemuncak sastra Dinasti Song.',
    ),
    QuestionItem(
      id: 'sas_man_010',
      questionText: 'Penyair wanita paling terkenal dalam sejarah Tiongkok dari era Dinasti Song yang mengarang ci lirik melankolis adalah:',
      options: ['Li Qingzhao (李清照)', 'Cai Yan (蔡琰)', 'Shangguan Wan\'er (上官婉儿)', 'Zhu Shuzhen (朱淑真)'],
      correctOptionIndex: 0,
      explanation: 'Li Qingzhao (1084–1155) dijuluki penyair wanita nomor satu Tiongkok (Yi An Ju Shi).',
    ),
    QuestionItem(
      id: 'sas_man_011',
      questionText: 'Bapak Sastra Tiongkok Modern yang mengarang novel pendek pertama beraksara vernakular "A Q Zheng Zhuan" (Kisah Nyata A Q) dan "Kuangren Riji" (Catatan Harian Orang Gila) adalah:',
      options: ['Lu Xun (鲁迅)', 'Mao Dun (茅盾)', 'Lao She (老舍)', 'Ba Jin (巴金)'],
      correctOptionIndex: 0,
      explanation: 'Lu Xun (Zhou Shuren) memelopori Sastra Modern Tiongkok lewat gerakan 4 Mei 1919.',
    ),
    QuestionItem(
      id: 'sas_man_012',
      questionText: 'Pengarang novel modern "Luotuo Xiangzi" (Rickshaw Boy / 骆驼祥子) dan drama "Teahouse" (Cha Guan / 茶馆) adalah:',
      options: ['Lao She (老舍)', 'Lu Xun (鲁迅)', 'Shen Congwen (沈从文)', 'Cao Yu (曹禺)'],
      correctOptionIndex: 0,
      explanation: 'Lao She mengisahkan penarik becak Xiangzi dan problematika sosial Beijing modern.',
    ),
    QuestionItem(
      id: 'sas_man_013',
      questionText: 'Dramawan modern Tiongkok yang dijuluki "Shakespeare-nya Tiongkok" dan mengarang drama tragedi monumental "Lei Yu" (Thunderstorm / 雷雨, 1934) adalah:',
      options: ['Cao Yu (曹禺)', 'Lao She (老舍)', 'Tian Han (田汉)', 'Guo Moruo (郭沫若)'],
      correctOptionIndex: 0,
      explanation: 'Cao Yu menulis "Lei Yu" yang menjadi tonggak drama realisme panggung modern Tiongkok.',
    ),
    QuestionItem(
      id: 'sas_man_014',
      questionText: 'Penulis asal Tiongkok pertama yang memenangkan Nobel Sastra pada tahun 2012 dengan karya novel hallucinatory realism seperti "Red Sorghum" (Hong Gao Liang) adalah:',
      options: ['Mo Yan (莫言)', 'Gao Xingjian (高行健)', 'Yu Hua (余华)', 'Su Tong (苏童)'],
      correctOptionIndex: 0,
      explanation: 'Mo Yan memenangkan Nobel Sastra 2012 atas gaya realisme halusinasi gabungan cerita rakyat dan sejarah.',
    ),
    QuestionItem(
      id: 'sas_man_015',
      questionText: 'Penulis kelahiran Tiongkok berbahasa Prancis penerima Nobel Sastra 2000 yang mengarang novel "Ling Shan" (Soul Mountain / 灵山) adalah:',
      options: ['Gao Xingjian (高行健)', 'Mo Yan (莫言)', 'Ha Jin (哈金)', 'Bei Dao (北岛)'],
      correctOptionIndex: 0,
      explanation: 'Gao Xingjian adalah sastrawan berbahasa Mandarin pertama yang meraih Nobel Sastra tahun 2000.',
    ),
    QuestionItem(
      id: 'sas_man_016',
      questionText: 'Novelis kontemporer terkenal pengarang novel "Huo Zhe" (To Live / 活着) dan "Xu Sanguan Mai Xie Ji" (Chronicle of a Blood Merchant) adalah:',
      options: ['Yu Hua (余华)', 'Mo Yan (莫言)', 'Yan Lianke (阎连科)', 'Wang Xiaobo (王小波)'],
      correctOptionIndex: 0,
      explanation: 'Yu Hua mengisahkan keteguhan Fugui bertahan hidup melewati dekade-dekade ujian sejarah Tiongkok modern.',
    ),
    QuestionItem(
      id: 'sas_man_017',
      questionText: 'Bahasa Mandarin Standar (Putonghua / 普通话) didasarkan pada fonologi dialek kota mana dan tata bahasa vernakular apa?',
      options: ['Fonologi dialek Beijing dan tata bahasa Baihua (白话)', 'Dialek Shanghai dan Wenyuan', 'Dialek Guangzhou (Kanton) dan Classical Chinese', 'Dialek Fujian dan Minnan'],
      correctOptionIndex: 0,
      explanation: 'Putonghua menggunakan pengucapan Beijing sebagai standar fonetik dan Baihua modern sebagai standar sintaksis.',
    ),
    QuestionItem(
      id: 'sas_man_018',
      questionText: 'Sistem alih aksara fonetik resmi Latin untuk bahasa Mandarin yang disahkan ISO pada tahun 1982 dinamakan:',
      options: ['Hanyu Pinyin (汉语拼音)', 'Wade-Giles', 'Bopomofo (Zhuyin Fuhao)', 'Postal Romanization'],
      correctOptionIndex: 0,
      explanation: 'Hanyu Pinyin dikembangkan oleh Zhou Youguang dan disahkan pemerintah PRC pada 1958.',
    ),
    QuestionItem(
      id: 'sas_man_019',
      questionText: 'Berapa jumlah Nada (Tone / 声调) standar dalam bahasa Mandarin Putonghua (di luar nada netral / Qing Sheng)?',
      options: ['4 nada utama (Yinping, Yangping, Shangsheng, Qusheng)', '5 nada', '6 nada', '9 nada'],
      correctOptionIndex: 0,
      explanation: 'Putonghua memiliki 4 nada kontur: Nada 1 (datar tinggi), Nada 2 (naik), Nada 3 (turun-naik), dan Nada 4 (turun tajam).',
    ),
    QuestionItem(
      id: 'sas_man_020',
      questionText: 'Aturan perubahan nada (Tone Sandhi) untuk kata "Bu" (不) menyatakan bahwa "Bu" ber-nada ke-4 akan berubah menjadi nada ke-2 jika diikuti kata ber-nada:',
      options: ['Nada ke-4 (Qusheng)', 'Nada ke-1', 'Nada ke-2', 'Nada ke-3'],
      correctOptionIndex: 0,
      explanation: 'Perubahan "Bu": 不 (bù) + nada ke-4 berubah jadi bú (contoh: 不是 bú shì, 不要 bú yào).',
    ),
    QuestionItem(
      id: 'sas_man_021',
      questionText: 'Aturan Tone Sandhi untuk dua karakter berturut-turut yang masing-masing ber-nada ke-3 (Shang Sheng + Shang Sheng) adalah:',
      options: ['Karakter pertama berubah menjadi nada ke-2 (contoh: 你好 nǐ hǎo -> ní hǎo)', 'Karakter kedua berubah jadi nada ke-1', 'Keduanya jadi nada ke-4', 'Tidak ada perubahan'],
      correctOptionIndex: 0,
      explanation: 'Nada ke-3 + Nada ke-3 diucapkan sebagai Nada ke-2 + Nada ke-3 (3+3 -> 2+3).',
    ),
    QuestionItem(
      id: 'sas_man_022',
      questionText: 'Struktur dasar karakter Hanzi dibangun berdasarkan berapa jenis metode pembentukan kata (Liu Shu / 六书)?',
      options: ['6 metode (Xiangxing, Zhishi, Huiyi, Xingsheng, Zhuanzhu, Jiajie)', '4 metode', '8 metode', '10 metode'],
      correctOptionIndex: 0,
      explanation: 'Xu Shen merumuskan 6 prinsip pembentukan karakter Hanzi dalam kamus Shuowen Jiezi.',
    ),
    QuestionItem(
      id: 'sas_man_023',
      questionText: 'Metode pembentukan Hanzi terbesar (sekitar 80-90% karakter) yang menggabungkan radikal makna dan petunjuk bunyi dinamakan:',
      options: ['Xingsheng (形声 / Picto-phonetic compound)', 'Xiangxing (象形 / Pictogram)', 'Huiyi (会意 / Ideogram compound)', 'Zhishi (指事 / Ideogram)'],
      correctOptionIndex: 0,
      explanation: 'Karakter Xingsheng memiliki komponen unsur makna (Xing) dan unsur sebutan bunyi (Sheng).',
    ),
    QuestionItem(
      id: 'sas_man_024',
      questionText: 'Komponen dasar karakter Hanzi yang berfungsi untuk pengelompokan kata dalam kamus dan pengidentifikasi makna dinamakan:',
      options: ['Radikal / Bushou (部首)', 'Pinyin', 'Pianpang', 'Bishun'],
      correctOptionIndex: 0,
      explanation: 'Bushou (Radikal) adalah kunci pengklasifikasian Hanzi (misalnya radikal air 氵, radikal kayu 木).',
    ),
    QuestionItem(
      id: 'sas_man_025',
      questionText: 'Urutan penulisan goresan Hanzi (Bishun / 笔顺) mengikuti aturan umum berikut, KECUALI:',
      options: ['Dari bawah ke atas (先下后上)', 'Dari atas ke bawah (先上后下)', 'Dari kiri ke kanan (先左后右)', 'Dari luar ke dalam (先外后内)'],
      correctOptionIndex: 0,
      explanation: 'Aturan goresan Hanzi adalah dari atas ke bawah dan kiri ke kanan, BUKAN dari bawah ke atas.',
    ),
    QuestionItem(
      id: 'sas_man_026',
      questionText: 'Koleksi puisi klasik tertua Tiongkok (abad 11-6 SM) yang dihimpun dan disunting oleh Konfusius berjudul:',
      options: ['Shi Jing (Kitab Puisi / 诗经)', 'Chu Ci (Nyanyian Chu / 楚辞)', 'Yue Fu (乐府)', 'Tang Shi (唐诗)'],
      correctOptionIndex: 0,
      explanation: 'Shi Jing berisi 305 puisi kuno yang dikelompokkan dalam Feng, Ya, dan Song.',
    ),
    QuestionItem(
      id: 'sas_man_027',
      questionText: 'Penyair patriotik kuno Negeri Chu yang mengarang epos "Li Sao" (离骚) dan diperingati pada Perahu Naga (Duanwu Jie) adalah:',
      options: ['Qu Yuan (屈原)', 'Song Yu (宋玉)', 'Jia Yi (贾谊)', 'Sima Xiangru (司马相如)'],
      correctOptionIndex: 0,
      explanation: 'Qu Yuan (340–278 SM) menyeburkan diri ke Sungai Miluo; hari wafatnya diperingati sebagai Festival Peh Cun.',
    ),
    QuestionItem(
      id: 'sas_man_028',
      questionText: 'Bapak Sejarah Tiongkok yang mengarang mahakarya historiografi "Shi Ji" (Catatan Sejarah Agung / 史记) pada Dinasti Han adalah:',
      options: ['Sima Qian (司马迁)', 'Ban Gu (班固)', 'Sima Guang (司马光)', 'Liu Xiang (刘向)'],
      correctOptionIndex: 0,
      explanation: 'Sima Qian mengarang Shi Ji sebagai karya sejarah komprehensif pertama berbentuk biografi (Jiz传体).',
    ),
    QuestionItem(
      id: 'sas_man_029',
      questionText: 'Partikel aspek gramatikal "Le" (了) dalam bahasa Mandarin berfungsi menunjukkan:',
      options: ['Perubahan keadaan atau tindakan yang telah selesai (Completed Action / Change of State)', 'Tindakan yang sedang berlangsung', 'Pengandaian masa depan', 'Pengalaman masa lalu tanpa batasan waktu'],
      correctOptionIndex: 0,
      explanation: '了 (le) menandai aspek perfektif atau perubahan situasi.',
    ),
    QuestionItem(
      id: 'sas_man_030',
      questionText: 'Partikel aspek "Guo" (过) dalam kalimat Mandarin menyatakan:',
      options: ['Pengalaman masa lalu yang pernah dilakukan (Experiential Aspect)', 'Tindakan sedang terjadi', 'Keadaan bertahan (Durative)', 'Tindakan mendesak'],
      correctOptionIndex: 0,
      explanation: '过 (guo) menyatakan pernah mengalami sesuatu (misal: 我去过中国 I have been to China).',
    ),
    QuestionItem(
      id: 'sas_man_031',
      questionText: 'Partikel aspek "Zhe" (着) berfungsi menunjukkan:',
      options: ['Keadaan atau tindakan yang terus berlangsung/bertahan (Durative Aspect)', 'Tindakan yang belum mulai', 'Penolakan', 'Perintah formal'],
      correctOptionIndex: 0,
      explanation: '着 (zhe) menandai duratif (misal: 门开着 The door is open).',
    ),
    QuestionItem(
      id: 'sas_man_032',
      questionText: 'Struktur konstruksi kalimat disposisi "Ba" (把字句) digunakan untuk:',
      options: ['Menekankan dampak atau perlakuan terhadap objek yang sudah diketahui (Subjek + 把 + Objek + Verba + Pelengkap)', 'Membuat kalimat pasif', 'Menanyakan pertanyaan', 'Menyatakan perbandingan'],
      correctOptionIndex: 0,
      explanation: 'Kalimat 把 menggeser objek ke depan kata kerja untuk menunjukkan pengolahan/dampak pada objek.',
    ),
    QuestionItem(
      id: 'sas_man_033',
      questionText: 'Struktur pasif formal "Bei" (被字句) digunakan untuk menunjukkan:',
      options: ['Subjek menerima tindakan / dikenai perbuatan (Subjek + 被 + Pelaku + Verba)', 'Keinginan masa depan', 'Perbandingan', 'Kepemilikan'],
      correctOptionIndex: 0,
      explanation: '被 (bèi) menandai kalimat pasif (misal: 苹果被他吃了 Apple was eaten by him).',
    ),
    QuestionItem(
      id: 'sas_man_034',
      questionText: 'Kata penggolong / kata ukur (Classifier / Measure Word / Liangci / 量词) untuk benda berupa buku, majalah, atau kamus adalah:',
      options: ['Ben (本)', 'Zhi (只)', 'Zhang (张)', 'Tiao (条)'],
      correctOptionIndex: 0,
      explanation: '一本书 (yì běn shū) menggunakan kata penggolong 本 (běn).',
    ),
    QuestionItem(
      id: 'sas_man_035',
      questionText: 'Kata ukur (Liangci) untuk benda yang berupa lembaran datar (kertas, meja, tempat tidur, foto) adalah:',
      options: ['Zhang (张)', 'Tiao (条)', 'Zhi (支)', 'Ge (个)'],
      correctOptionIndex: 0,
      explanation: '一张纸, 一张桌子, 一张照片 menggunakan 张 (zhāng).',
    ),
    QuestionItem(
      id: 'sas_man_036',
      questionText: 'Kata ukur (Liangci) untuk benda yang berbentuk panjang dan meliuk-liuk (ikan, sungai, jalan, celana) adalah:',
      options: ['Tiao (条)', 'Ge (个)', 'Kuai (块)', 'Jian (件)'],
      correctOptionIndex: 0,
      explanation: '一条鱼, 一条路, 一条裤子 menggunakan 条 (tiáo).',
    ),
    QuestionItem(
      id: 'sas_man_037',
      questionText: 'Kata ukur (Liangci) untuk pakaian atasan (baju, kemeja, jas) dan urusan/masalah adalah:',
      options: ['Jian (件)', 'Tiao (条)', 'Shuang (双)', 'Suo (所)'],
      correctOptionIndex: 0,
      explanation: '一件衣服, 一件事 menggunakan 件 (jiàn).',
    ),
    QuestionItem(
      id: 'sas_man_038',
      questionText: 'Empat Kitab Konfusianisme Klasik (Si Shu / 四书) terdiri dari buku-buku berikut, KECUALI:',
      options: ['Yi Jing (Kitab Perubahan / 易经)', 'Lun Yu (Analek Konfusius / 论语)', 'Mengzi (Mencius / 孟子)', 'Da Xue (Ajaran Agung) dan Zhong Yong (Tengah Sempurna)'],
      correctOptionIndex: 0,
      explanation: 'Yi Jing termasuk dalam 5 Kitab (Wu Jing / 五经). Empat Kitab (Si Shu) adalah Lun Yu, Mengzi, Da Xue, Zhong Yong.',
    ),
    QuestionItem(
      id: 'sas_man_039',
      questionText: 'Kumpulan ujaran dan ajaran Konfusius yang dicatat oleh murid-muridnya berjudul:',
      options: ['Lun Yu (Analek / 论语)', 'Dao De Jing', 'Zhuangzi', 'Xunzi'],
      correctOptionIndex: 0,
      explanation: 'Lun Yu adalah sumber utama ajaran Ru Jia (Konfusianisme).',
    ),
    QuestionItem(
      id: 'sas_man_040',
      questionText: 'Kitab fondasi filsafat Taoisme "Dao De Jing" (道德经) ditulis oleh tokoh bijak legendaris:',
      options: ['Laozi (老子)', 'Zhuangzi (庄子)', 'Liezi (列子)', 'Han Feizi (韩非子)'],
      correctOptionIndex: 0,
      explanation: 'Laozi dianggap sebagai pendiri filsafat Taoisme (Dao Jia).',
    ),
    QuestionItem(
      id: 'sas_man_041',
      questionText: 'Tokoh filsuf Taoisme yang terkenal dengan cerita alegori "Bermimpi Menjadi Kupu-kupu" (Zhuang Zhou Meng Die) adalah:',
      options: ['Zhuangzi (庄子)', 'Laozi (老子)', 'Mozi (墨子)', 'Gongsun Long'],
      correctOptionIndex: 0,
      explanation: 'Zhuangzi mempertanyakan batas antara realitas dan mimpi dalam alegori kupu-kupu.',
    ),
    QuestionItem(
      id: 'sas_man_042',
      questionText: 'Tokoh utama pendiri aliran Legalisme (Fa Jia / 法家) Tiongkok Kuno yang menekankan hukum tegas dan kekuasaan absolut raja adalah:',
      options: ['Han Feizi (韩非子)', 'Shang Yang (商鞅)', 'Li Si (李斯)', 'Semua jawaban benar'],
      correctOptionIndex: 3,
      explanation: 'Shang Yang, Li Si, dan Han Feizi adalah arsitek utama filsafat Legalisme Qin.',
    ),
    QuestionItem(
      id: 'sas_man_043',
      questionText: 'Filsuf kuno pemrakarsa aliran Mohisme (Mo Jia / 墨家) yang mengusung doktrin Cinta Universal (Jian \'Ai / 兼爱) dan Anti-Perang (Fei Gong) adalah:',
      options: ['Mozi (墨子)', 'Xunzi (荀子)', 'Mengzi (孟子)', 'Zengzi (曾子)'],
      correctOptionIndex: 0,
      explanation: 'Mozi mengajarkan Jian \'Ai (kasih tanpa membeda-bedakan) dan pasifisme militer.',
    ),
    QuestionItem(
      id: 'sas_man_044',
      questionText: 'Bentuk puisi populer Dinasti Tang (Tang Shi) terbagi menjadi dua struktur utama berdasarkan jumlah baris yaitu 4 baris dan 8 baris, yang masing-masing disebut:',
      options: ['Jueju (绝句 4 baris) dan Lushi (律诗 8 baris)', 'Song Ci dan Yuan Qu', 'Fu dan Shi', 'Paiju dan Changshi'],
      correctOptionIndex: 0,
      explanation: 'Jueju berstruktur 4 baris, sedangkan Lushi berstruktur 8 baris berima ketat.',
    ),
    QuestionItem(
      id: 'sas_man_045',
      questionText: 'Bentuk sastra opera drama nyanyian yang sangat berkembang pesat pada Dinasti Yuan (contoh: karya Guan Hanqing) dinamakan:',
      options: ['Yuan Qu / Zaju (杂剧 / 元曲)', 'Peking Opera (Jingju)', 'Chuanju', 'Kunqu'],
      correctOptionIndex: 0,
      explanation: 'Yuan Qu / Zaju memuncak pada abad ke-13-14 dengan dramawan Guan Hanqing dan Ma Zhiyuan.',
    ),
    QuestionItem(
      id: 'sas_man_046',
      questionText: 'Drama tragedi Yuan Qu karya Guan Hanqing tentang ketidakadilan wanita suci yang dihukum mati hingga mengakibatkan salju turun di musim panas berjudul:',
      options: ['Dou E Yuan (Ketidakadilan Dou E / 窦娥冤)', 'Xi Xiang Ji (Kisah Paviliun Barat)', 'Mu Dan Ting (Paviliun Peony)', 'Chang Sheng Dian'],
      correctOptionIndex: 0,
      explanation: 'Dou E Yuan adalah mahakarya drama tragedi klasik Yuan Zaju.',
    ),
    QuestionItem(
      id: 'sas_man_047',
      questionText: 'Drama romantis klasik Dinasti Ming karya Tang Xianzu yang mengisahkan cinta sejati Du L娘 dan Liu Mengmei hingga melintasi kematian berjudul:',
      options: ['Mudan Ting (Paviliun Peony / 牡丹亭)', 'Xi Xiang Ji', 'Taohua Shan (Kipas Bunga Persik)', 'Dou E Yuan'],
      correctOptionIndex: 0,
      explanation: 'Mudan Ting adalah puncak drama Kunqu opera karya Tang Xianzu (1598).',
    ),
    QuestionItem(
      id: 'sas_man_048',
      questionText: 'Pelopor Gerakan Kebudayaan Baru (May Fourth Movement 1919) yang menerbitkan majalah "Xin Qingnian" (Pemuda Baru / 新青年) adalah:',
      options: ['Chen Duxiu (陈独秀)', 'Hu Shi (胡适)', 'Lu Xun (鲁迅)', 'Li Dazhao (李大钊)'],
      correctOptionIndex: 0,
      explanation: 'Chen Duxiu mendirikan majalah New Youth pada 1915 sebagai obor pembaharuan modern.',
    ),
    QuestionItem(
      id: 'sas_man_049',
      questionText: 'Tokoh intelektual yang memelopori penggantian Bahasa Tionghoa Klasik (Wenyanwen) dengan Bahasa Vernakular Modern (Baihua) dalam tulisan adalah:',
      options: ['Hu Shi (胡适)', 'Lu Xun', 'Cai Yuanpei', 'Lin Yutang'],
      correctOptionIndex: 0,
      explanation: 'Hu Shi menerbitkan esai reformasi sastra 1917 mendorong penggunaan Baihua.',
    ),
    QuestionItem(
      id: 'sas_man_050',
      questionText: 'Novel saga keluarga modern "Jia" (Family / 家, 1931) yang mengkritik feodalisme patriarki ditulis oleh pengarang terkenal:',
      options: ['Ba Jin (巴金)', 'Mao Dun (茅盾)', 'Lao She (老舍)', 'Ding Ling (丁玲)'],
      correctOptionIndex: 0,
      explanation: 'Ba Jin (Li Yaotang) mengarang Trilogi "Ji Liu" (Turbulence) yang diawali dengan "Jia".',
    ),
    QuestionItem(
      id: 'sas_man_051',
      questionText: 'Novelis wanita yang memelopori sastra feminis modern Tiongkok lewat karya "Shafei Nüshi De Riji" (Catatan Harian Miss Sophie, 1928) adalah:',
      options: ['Ding Ling (丁玲)', 'Zhang Ailing (Eileen Chang)', 'Xiao Hong (萧红)', 'Bing Xin (冰心)'],
      correctOptionIndex: 0,
      explanation: 'Ding Ling mengeksplorasi emosi dan eksistensi wanita modern di Tiongkok.',
    ),
    QuestionItem(
      id: 'sas_man_052',
      questionText: 'Pengarang wanita legendaris asal Shanghai yang mengarang novel romansa tragis "Qing Cheng Zhi Lian" (Love in a Fallen City) dan "Se, Jie" (Lust, Caution) adalah:',
      options: ['Eileen Chang / Zhang Ailing (张爱玲)', 'Xiao Hong (萧红)', 'San Mao (三毛)', 'Wang Anyi (王安忆)'],
      correctOptionIndex: 0,
      explanation: 'Eileen Chang adalah salah satu penulis fiksi kota paling jenius abad ke-20.',
    ),
    QuestionItem(
      id: 'sas_man_053',
      questionText: 'Novel "Wei Cheng" (Fortress Besieged / 围城, 1947) yang terkenal dengan kutipan "Pernikahan seperti benteng terkepung" ditulis oleh:',
      options: ['Qian Zhongshu (钱锺书)', 'Lin Yutang (林语堂)', 'Shen Congwen (沈从文)', 'Su Tong (苏童)'],
      correctOptionIndex: 0,
      explanation: 'Qian Zhongshu mengarang novel satir intelektual paling cemerlang dalam sastra modern Tiongkok.',
    ),
    QuestionItem(
      id: 'sas_man_054',
      questionText: 'Novel pastoral indah "Bian Cheng" (Border Town / 边城, 1934) yang berlatar di Xiangxi diciptakan oleh:',
      options: ['Shen Congwen (沈从文)', 'Qian Zhongshu', 'Lu Xun', 'Ba Jin'],
      correctOptionIndex: 0,
      explanation: 'Shen Congwen mengisahkan gadis desa Cuicui dan ketulusan hidup masyarakat pedesaan Hunan.',
    ),
    QuestionItem(
      id: 'sas_man_055',
      questionText: 'Kelompok penyair modern yang muncul pasca Revolusi Kebudayaan (seperti Bei Dao, Shu Ting, Gu Cheng) dikenal sebagai aliran:',
      options: ['Menglong Shi (Misty Poets / 朦胧诗)', 'Xinyue Pai (Crescent Moon)', 'Chuangzao She', 'Feiming Pai'],
      correctOptionIndex: 0,
      explanation: 'Menglong Shi (Penyair Kabur/Misty) menyuarakan ketidaktentuan dan introspeksi diri.',
    ),
    QuestionItem(
      id: 'sas_man_056',
      questionText: 'Penyair Misty Gu Cheng sangat terkenal dengan dua baris puisinya "Heiye Gei Le Wo Heise De Yanjing..." yang berarti:',
      options: ['"Malam gelap memberiku mata hitam, tetapi aku menggunakannya untuk mencari cahaya"', '"Malam gelap menutupi kesedihanku"', '"Bintang-bintang menerangi jiwaku"', '"Aku berjalan di bawah rembulan"'],
      correctOptionIndex: 0,
      explanation: 'Puisi "Yiduo" (一代人) karya Gu Cheng menjadi moto generasi muda Tiongkok pasca-1970-an.',
    ),
    QuestionItem(
      id: 'sas_man_057',
      questionText: 'Dalam ilmu tata bahasa Mandarin, kata sambung "Suiru... Danshi..." (虽然……但是……) berfungsi menyatakan hubungan:',
      options: ['Konsesif / Konsesi (Meskipun... namun...)', 'Sebab-akibat', 'Pengandaian', 'Pilihan'],
      correctOptionIndex: 0,
      explanation: '虽然...但是... menghubungkan klausa konsesif.',
    ),
    QuestionItem(
      id: 'sas_man_058',
      questionText: 'Kata sambung "Yinwei... Suoyi..." (因为……所以……) menyatakan hubungan:',
      options: ['Sebab - Akibat (Because... therefore...)', 'Pengandaian', 'Bertolak belakang', 'Urutan waktu'],
      correctOptionIndex: 0,
      explanation: '因为...所以... menghubungkan alasan dan hasil.',
    ),
    QuestionItem(
      id: 'sas_man_059',
      questionText: 'Bentuk perbandingan "A Geng... B" atau "A Bi B + Kata Sifat" (A 比 B ...) digunakan untuk:',
      options: ['Menyatakan A lebih daripada B (A is more... than B)', 'Menyatakan A sama dengan B', 'Menyatakan A kurang dari B', 'Menyatakan A bukan B'],
      correctOptionIndex: 0,
      explanation: 'Kata 比 (bǐ) adalah penanda komparatif (contoh: 他比我高 He is taller than me).',
    ),
    QuestionItem(
      id: 'sas_man_060',
      questionText: 'Bentuk perbandingan kesamaan "A Gen B Yiyang..." (A 跟 B 一样……) berarti:',
      options: ['A sama ...-nya dengan B (A is the same as B)', 'A lebih dari B', 'A tidak sama dengan B', 'A adalah bagian dari B'],
      correctOptionIndex: 0,
      explanation: '跟...一样... menyatakan kesamaan dua objek.',
    ),
    QuestionItem(
      id: 'sas_man_061',
      questionText: 'Pelengkap Hasil (Resultative Complement / Jieguobu) dalam kalimat Mandarin ditempatkan:',
      options: ['Tepat setelah kata kerja utama (Verb + Resultative Complement)', 'Sebelum subjek', 'Di akhir kalimat setelah objek', 'Sebelum kata kerja'],
      correctOptionIndex: 0,
      explanation: 'Pelengkap hasil menempel langsung di belakang verba (contoh: 看完 read finished, 吃饱 eat full).',
    ),
    QuestionItem(
      id: 'sas_man_062',
      questionText: 'Pelengkap Arah (Directional Complement / Quxiangbu) menggunakan kata kerja arah seperti:',
      options: ['Lai (来 datang) dan Qu (去 pergi)', 'Zai (在)', 'Gei (给)', 'Dao (到)'],
      correctOptionIndex: 0,
      explanation: '来 (mendekati pembicara) dan 去 (menjauhi pembicara) membentuk pelengkap arah (contoh: 进来 come in, 出去 go out).',
    ),
    QuestionItem(
      id: 'sas_man_063',
      questionText: 'Pelengkap Potensial (Potential Complement / Ke\'nengbu) dibentuk dengan menyelipkan kata apa di antara verba dan pelengkapnya?',
      options: ['De (得 untuk positif) atau Bu (不 untuk negatif)', 'Le (了)', 'Guo (过)', 'Zhe (着)'],
      correctOptionIndex: 0,
      explanation: 'Contoh: 看得懂 (can understand by reading) vs 看不懂 (cannot understand by reading).',
    ),
    QuestionItem(
      id: 'sas_man_064',
      questionText: 'Di antara tiga partikel homofon "De" (的, 地, 得), partikel "De" (地) berfungsi sebagai:',
      options: ['Penanda Adverbial (Penghubung kata keterangan dengan kata kerja: Adverb + 地 + Verb)', 'Penanda Kepemilikan (的)', 'Penanda Pelengkap Gelombang/Tingkat (得)', 'Partikel tanya'],
      correctOptionIndex: 0,
      explanation: '地 menghubungkan adverbia dengan verba (contoh: 慢慢地走 walk slowly).',
    ),
    QuestionItem(
      id: 'sas_man_065',
      questionText: 'Partikel "De" (得) digunakan untuk menghubungkan kata kerja dengan pelengkap tingkat/derajat (Degree Complement), contohnya:',
      options: ['Ta Pao De Hen Kuai (他跑得很快 He runs very fast)', 'Wo De Shu (我的书)', 'Man Man De Zou (慢慢地走)', 'Ta De Yi Sheng'],
      correctOptionIndex: 0,
      explanation: 'Verb + 得 + Adjective/Degree Complement (他跑得很快).',
    ),
    QuestionItem(
      id: 'sas_man_066',
      questionText: 'Karakter Hanzi Tradisional (Fan Ti Zi / 繁体字) saat ini masih digunakan secara resmi di wilayah:',
      options: ['Taiwan, Hong Kong, dan Makau', 'Tiongkok Daratan', 'Singapura', 'Malaysia'],
      correctOptionIndex: 0,
      explanation: 'Taiwan, Hong Kong, dan Makau menggunakan Hanzi Tradisional (Fantizi), sedangkan Tiongkok Daratan dan Singapura menggunakan Hanzi Sederhana (Jiantizi).',
    ),
    QuestionItem(
      id: 'sas_man_067',
      questionText: 'Kebijakan penyederhanaan karakter Hanzi (Jiantizi / 简体字) pertama kali dipublikasikan secara resmi oleh Pemerintah PRC pada tahun:',
      options: ['1956', '1912', '1989', '2000'],
      correctOptionIndex: 0,
      explanation: 'Tiongkok mengundangkan Skema Penyederhanaan Hanzi pada 1956 untuk meningkatkan angka melek huruf nasional.',
    ),
    QuestionItem(
      id: 'sas_man_068',
      questionText: 'Gaya kaligrafi Tionghoa kuno yang diukir pada cangkang kura-kura dan tulang belikat lembu dari Dinasti Shang (1600-1046 SM) dinamakan:',
      options: ['Jiaguwen (Oracle Bone Script / 甲骨文)', 'Jinwen (Bronze Script / 金文)', 'Zhuanshu (Seal Script / 篆书)', 'Lishu (Clerical Script / 隶书)'],
      correctOptionIndex: 0,
      explanation: 'Jiaguwen yang ditemukan di Anyang adalah bentuk tulisan Hanzi paling awal yang teridentifikasi.',
    ),
    QuestionItem(
      id: 'sas_man_069',
      questionText: 'Gaya kaligrafi yang ditulis pada bejana perunggu Dinasti Shang dan Zhou dinamakan:',
      options: ['Jinwen / Zhongdingwen (金文 / 钟鼎文)', 'Jiaguwen', 'Kaishu', 'Caoshu'],
      correctOptionIndex: 0,
      explanation: 'Jinwen diukir atau dicetak pada peralatan perunggu ritus feodal.',
    ),
    QuestionItem(
      id: 'sas_man_070',
      questionText: 'Kaisar Pertama Dinasti Qin (Qin Shi Huang) menyatukan aksara Tiongkok di bawah satu standar resmi bernama:',
      options: ['Xiao Zhuan (Small Seal Script / 小篆)', 'Jiaguwen', 'Kaishu', 'Xingshu'],
      correctOptionIndex: 0,
      explanation: 'Perdana Menteri Li Si membakukan aksara 小篆 (Small Seal Script) untuk seluruh wilayah Qin.',
    ),
    QuestionItem(
      id: 'sas_man_071',
      questionText: 'Gaya aksara kaligrafi standar modern (Regular Script) yang digunakan sebagai acuan cetak Hanzi dewasa ini dinamakan:',
      options: ['Kaishu (楷书)', 'Lishu (隶书)', 'Caoshu (草书)', 'Xingshu (行书)'],
      correctOptionIndex: 0,
      explanation: 'Kaishu dikembangkan pada Dinasti Han Akhir/Wei-Jin dan menjadi bentuk standar baku.',
    ),
    QuestionItem(
      id: 'sas_man_072',
      questionText: 'Gaya kaligrafi "Cursive Script" (Rumput) yang ditulis sangat cepat dan menyambung bebas dinamakan:',
      options: ['Caoshu (草书)', 'Kaishu (楷书)', 'Lishu (隶书)', 'Zhuanshu (篆书)'],
      correctOptionIndex: 0,
      explanation: 'Caoshu mengutamakan ekspresi artistik dan kecepatan gerakan kuas.',
    ),
    QuestionItem(
      id: 'sas_man_073',
      questionText: 'Kaligrafer terbesar dalam sejarah Tiongkok dari Dinasti Jin yang dijuluki "Dewa Kaligrafi" (Shu Sheng / 书圣) dan mengarang "Lanting Xu" adalah:',
      options: ['Wang Xizhi (王羲之)', 'Yan Zhenqing (颜真卿)', 'Liu Gongquan (柳公权)', 'Ouyang Xun (欧阳询)'],
      correctOptionIndex: 0,
      explanation: 'Wang Xizhi (303–361) mengarang Lantingji Xu yang dianggap karya kaligrafi Xingshu nomor 1 di dunia.',
    ),
    QuestionItem(
      id: 'sas_man_074',
      questionText: 'Empat Harta Karun Ruang Belajar (Wen Fang Si Bao / 文房四宝) tradisional Tiongkok terdiri dari:',
      options: ['Kuas (Bi), Tinta (Mo), Kertas (Zhi), dan Batu Tinta (Yan)', 'Buku, Meja, Kursi, Kuas', 'Pena, Cat, Kain, Meja', 'Stempel, Lilin, Benang, Kertas'],
      correctOptionIndex: 0,
      explanation: 'Wen Fang Si Bao adalah 笔 (bǐ), 墨 (mò), 纸 (zhǐ), 砚 (yàn).',
    ),
    QuestionItem(
      id: 'sas_man_075',
      questionText: 'Kertas tradisional Tiongkok berkualitas tinggi yang khusus digunakan untuk lukisan dan kaligrafi dinamakan:',
      options: ['Xuan Zhi (宣纸 / Rice Paper)', 'Kertas HVS', 'Kertas Koran', 'Kertas Papirus'],
      correctOptionIndex: 0,
      explanation: 'Xuanzhi dari Xuancheng, Anhui sangat menyerap tinta dan tahan ratusan tahun.',
    ),
    QuestionItem(
      id: 'sas_man_076',
      questionText: 'Mitologi penciptaan alam semesta Tiongkok menceritakan sesosok raksasa yang membelah langit dan bumi bernama:',
      options: ['Pangu (盘古)', 'Nüwa (女娲)', 'Fuxi (伏羲)', 'Shennong (神农)'],
      correctOptionIndex: 0,
      explanation: 'Pangu memisahkan Yin (Bumi) dan Yang (Langit) dari telur kekacauan primordial.',
    ),
    QuestionItem(
      id: 'sas_man_077',
      questionText: 'Dewi mitologi Tiongkok yang menciptakan manusia dari lumpur dan menambal langit yang bocor dengan batu lima warna bernama:',
      options: ['Nüwa (女娲)', 'Chang\'e (嫦娥)', 'Xi Wangmu (西王母)', 'Mazu (妈祖)'],
      correctOptionIndex: 0,
      explanation: 'Nüwa adalah dewi pencipta dan pelindung manusia dalam mitologi Tiongkok.',
    ),
    QuestionItem(
      id: 'sas_man_078',
      questionText: 'Mitologi pahlawan pemanah yang memanah jatuh 9 dari 10 matahari di langit adalah:',
      options: ['Hou Yi (后羿)', 'Kuafu (夸父)', 'Jingwei (精卫)', 'Yu Yang-ren'],
      correctOptionIndex: 0,
      explanation: 'Hou Yi memanah 9 matahari dan istrinya Chang\'e meminum obat keabadian melayang ke Bulan.',
    ),
    QuestionItem(
      id: 'sas_man_079',
      questionText: 'Festival Musim Gugur (Zhongqiu Jie / 中秋节) dirayakan pada tanggal 15 bulan ke-8 imlek identik dengan tradisi:',
      options: ['Makan Kue Bulan (Yuebing) dan menikmati indahnya bulan purnama', 'Makan Bacang (Zongzi)', 'Menyalakan Mercon Tahun Baru', 'Ziarah Kubur (Cheng Beng)'],
      correctOptionIndex: 0,
      explanation: 'Zhongqiu Jie dirayakan saat bulan paling bulat beriringan dengan kisah Chang\'e.',
    ),
    QuestionItem(
      id: 'sas_man_080',
      questionText: 'Festival Perahu Naga (Duanwu Jie / 端午节) identik dengan tradisi makan bacang (Zongzi / 粽子) untuk mengenang penyair:',
      options: ['Qu Yuan (屈原)', 'Li Bai', 'Du Fu', 'Su Dongpo'],
      correctOptionIndex: 0,
      explanation: 'Zongzi dilemparkan ke sungai Miluo agar ikan tidak memakan jasad Qu Yuan.',
    ),
    QuestionItem(
      id: 'sas_man_081',
      questionText: 'Seni pertunjukan Teater Opera Beijing (Jingju / 京剧) membagi peran karakter utama menjadi empat kategori yaitu:',
      options: ['Sheng (生 pria), Dan (旦 wanita), Jing (净 wajah cat), dan Chou (丑 badut)', 'Guan, Dan, Mo, Jing', 'Wusheng, Wudan, Hualian, Xiaosheng', 'King, Queen, Jack, Joker'],
      correctOptionIndex: 0,
      explanation: 'Sheng, Dan, Jing, Chou adalah 4 pilar peran panggung Jingju.',
    ),
    QuestionItem(
      id: 'sas_man_082',
      questionText: 'Wajah berkarakter merah (Red Painted Face) dalam Opera Beijing melambangkan sifat:',
      options: ['Kesetiaan, keberanian, dan kejujuran (contoh: Guan Yu)', 'Pengkhianatan dan kekejaman', 'Kelicikan', 'Ketakutan'],
      correctOptionIndex: 0,
      explanation: 'Riasan merah menandai tokoh jujur dan setia seperti Guan Yu.',
    ),
    QuestionItem(
      id: 'sas_man_083',
      questionText: 'Wajah berkarakter putih (White Painted Face / Cao Cao) melambangkan sifat:',
      options: ['Kelicikan, pengkhianatan, dan kejahatan', 'Kesetiaan', 'Kebaikan hati', 'Ketidakberdayaan'],
      correctOptionIndex: 0,
      explanation: 'Topeng putih menandai tokoh jahat dan licik.',
    ),
    QuestionItem(
      id: 'sas_man_084',
      questionText: 'Genre fiksi silat Tiongkok (Wuxia Xiaoshuo / 武侠小说) memuncak pada abad ke-20 dengan "Tiga Maestro Wuxia" yaitu:',
      options: ['Jin Yong (金庸), Liang Yusheng (梁羽生), dan Gu Long (古龙)', 'Mo Yan, Yu Hua, Su Tong', 'Lu Xun, Ba Jin, Lao She', 'Luo Guanzhong, Shi Nai\'an, Wu Cheng\'en'],
      correctOptionIndex: 0,
      explanation: 'Jin Yong (Louis Cha), Gu Long, dan Liang Yusheng adalah rajanya fiksi Wuxia.',
    ),
    QuestionItem(
      id: 'sas_man_085',
      questionText: 'Mahakarya fiksi silat Jin Yong yang membentuk "Trilogi Rajawali" (She Diao San Bu Qu) terdiri dari novel-novel berikut, KECUALI:',
      options: ['Tian Long Ba Bu (Demi-Gods and Semi-Devils)', 'She Diao Ying Xiong Zhuan (Legenda Pendekar Pemanah Rajawali)', 'Shen Diao Xia Lü (Kembalinya Pendekar Rajawali)', 'Yi Tian Tu Long Ji (Kisah Membunuh Naga)'],
      correctOptionIndex: 0,
      explanation: 'Trilogi Rajawali Jin Yong adalah She Diao, Shen Diao, dan Yi Tian Tu Long Ji.',
    ),
    QuestionItem(
      id: 'sas_man_086',
      questionText: 'Karakter "Shi" (是) dalam tata bahasa Mandarin berfungsi sebagai kata kerja penghubung (Copula) untuk menyatakan:',
      options: ['Identitas atau kesamaan (A 是 B / A is B)', 'Kepemilikan (Have)', 'Keberadaan lokasi (Exist)', 'Tindakan aktif'],
      correctOptionIndex: 0,
      explanation: '是 menghubungkan dua nomina yang identik (contoh: 我是学生 I am a student).',
    ),
    QuestionItem(
      id: 'sas_man_087',
      questionText: 'Kata "You" (有) digunakan untuk menyatakan:',
      options: ['Kepemilikan (Have) dan Keberadaan (Exist / There is)', 'Identitas (is)', 'Tujuan (To go)', 'Alasan (Because)'],
      correctOptionIndex: 0,
      explanation: '有 menyatakan milik (我有书) atau eksistensi (桌 story 有书).',
    ),
    QuestionItem(
      id: 'sas_man_088',
      questionText: 'Bentuk negasi penolakan untuk kata kerja "You" (有) adalah:',
      options: ['Mei You (没有)', 'Bu You (不有)', 'Fei You (非有)', 'Wu You (无有)'],
      correctOptionIndex: 0,
      explanation: 'Negasi untuk 有 SELALU menggunakan 没有 (méi yǒu), TIDAK BOLEH 不有.',
    ),
    QuestionItem(
      id: 'sas_man_089',
      questionText: 'Bentuk negasi "Bu" (不) digunakan untuk:',
      options: ['Negasi kebiasaan sehari-hari, masa depan, atau keadaan kata sifat (Present / Future / Habitual)', 'Negasi masa lalu', 'Negasi kata 有', 'Negasi perintah'],
      correctOptionIndex: 0,
      explanation: '不 digunakan untuk kebiasaan/sekarang/masa depan (我不去 I don\'t go / I won\'t go).',
    ),
    QuestionItem(
      id: 'sas_man_090',
      questionText: 'Bentuk negasi "Mei" (没 / 没有) digunakan untuk:',
      options: ['Negasi tindakan di masa lalu atau tindakan yang belum terjadi (Past / Incomplete action)', 'Negasi masa depan', 'Negasi kata sifat', 'Negasi kebiasaan'],
      correctOptionIndex: 0,
      explanation: '没 (méi) menyangkal tindakan perfektif/masa lalu (我没去 I didn\'t go).',
    ),
    QuestionItem(
      id: 'sas_man_091',
      questionText: 'Konstruksi "Chule... Yiwai, Hai/Ye..." (除了……以外，还/也……) berarti:',
      options: ['Selain ... , juga ... (In addition to ...)', 'Hanya ... ', 'Tidak ada ... ', 'Meskipun ... '],
      correctOptionIndex: 0,
      explanation: '除了...以外 menyajikan inklusi (selain A, juga B).',
    ),
    QuestionItem(
      id: 'sas_man_092',
      questionText: 'Struktur penekanan waktu, tempat, atau cara tindakan di masa lalu menggunakan pola "Shi... De" (是……的), contohnya:',
      options: ['Wo Shi Zuo Feiji Lai De (我是坐飞机来的 It was by plane that I came)', 'Wo Shi Xue Sheng', 'Wo De Shu', 'Wo Shi Mai Feiji'],
      correctOptionIndex: 0,
      explanation: 'Polan 是...的 menyoroti rincian keadaan dari kejadian yang sudah berlalu.',
    ),
    QuestionItem(
      id: 'sas_man_093',
      questionText: 'Sebanyak berapa ujian kemampuan bahasa Mandarin internasional resmi yang diselenggarakan oleh Hanban / CTI dikenal dengan singkatan:',
      options: ['HSK (Hanyu Shuiping Kaoshi / 汉语水平考试)', 'TOFL', 'JLPT', 'TOPIK'],
      correctOptionIndex: 0,
      explanation: 'HSK adalah Ujian Standar Kemampuan Bahasa Mandarin Internasional.',
    ),
    QuestionItem(
      id: 'sas_man_094',
      questionText: 'Ujian kemampuan kemahiran berbicara (Speaking Test) standar Mandarin dinamakan:',
      options: ['HSKK (Hanyu Shuiping Kouyu Kaoshi)', 'BCT', 'YCT', 'TOCFL'],
      correctOptionIndex: 0,
      explanation: 'HSKK mengevaluasi kemahiran lisan (lisan/kouyu).',
    ),
    QuestionItem(
      id: 'sas_man_095',
      questionText: 'Idiom empat karakter Tionghoa yang kaya makna sejarah dan sastra dinamakan:',
      options: ['Chengyu (成语)', 'Yanyu (谚语)', 'Xiehouyu (歇后语)', 'Guanyanyu (惯用語)'],
      correctOptionIndex: 0,
      explanation: 'Chengyu adalah ungkapan idiomatis 4 karakter (misal: 守株待兔, 画蛇添足).',
    ),
    QuestionItem(
      id: 'sas_man_096',
      questionText: 'Idiom Chengyu "Hua She Tian Zu" (画蛇添足 / Melukis Ular Menambah Kaki) mengandung nasehat moral:',
      options: ['Melakukan hal sia-sia yang berlebihan hingga justru merusak hasil', 'Bekerja keras pantang menyerah', 'Belajar dari pengalaman', 'Menolong sesama'],
      correctOptionIndex: 0,
      explanation: 'Hua She Tian Zu berarti merusak pekerjaan karena tindakan ekstra yang tidak perlu.',
    ),
    QuestionItem(
      id: 'sas_man_097',
      questionText: 'Ungkapan teka-teki rakyat dua bagian di mana bagian pertama adalah kiasan dan bagian kedua adalah jawaban tersembunyi dinamakan:',
      options: ['Xiehouyu (歇后语)', 'Chengyu', 'Yanyu', 'Gequ'],
      correctOptionIndex: 0,
      explanation: 'Xiehouyu adalah idiom kelakar humor khas (contoh: 竹篮打水 —— 一场空).',
    ),
    QuestionItem(
      id: 'sas_man_098',
      questionText: 'Satu-satunya kaisar wanita dalam sejarah Tiongkok dari Dinasti Zhou/Tang yang mendukung perkembangan puisi Tang dan ujian kerajaan adalah:',
      options: ['Wu Zetian (武则天)', 'Cixi Taihou (慈禧太后)', 'Lü Zhi (吕后)', 'Daji'],
      correctOptionIndex: 0,
      explanation: 'Kaisar Wu Zetian memerintah 690-705 M dan mempromosikan penyair berbakat lewat ujian Gwago.',
    ),
    QuestionItem(
      id: 'sas_man_099',
      questionText: 'Karya novel fiksi sains modern Tiongkok "San Ti" (The Three-Body Problem / 三体) yang memenangkan Hugo Award 2015 ditulis oleh:',
      options: ['Liu Cixin (刘慈欣)', 'Hao Jingfang (郝景芳)', 'Han Song (韩松)', 'Wang Jinkang'],
      correctOptionIndex: 0,
      explanation: 'Liu Cixin adalah maestro fiksi sains Tiongkok pencipta trilogi Trisolaris San Ti.',
    ),
    QuestionItem(
      id: 'sas_man_100',
      questionText: 'Pernyataan tata bahasa Mandarin yang BENAR mengenai urutan waktu (Time Phrase) dalam kalimat adalah:',
      options: ['Keterangan waktu diletakkan SEBELUM kata kerja (di awal kalimat atau setelah subjek)', 'Keterangan waktu selalu di akhir kalimat', 'Keterangan waktu diletakkan setelah objek', 'Urutan bebas'],
      correctOptionIndex: 0,
      explanation: 'Dalam bahasa Mandarin, keterangan waktu SELALU diletakkan sebelum verba (Subject + Time + Verb + Object).',
    ),
  ];
}
