import '../../../tes_seleksi_model.dart';

List<QuestionItem> getTesSastraIndonesiaQuestions() {
  return const [
    QuestionItem(
      id: 'sas_indo_001',
      questionText: 'Angkatan sastra Indonesia pertama yang diterbitkan oleh balai pustaka milik pemerintah kolonial Belanda (seperti novel "Siti Nurbaya") dinamakan Angkatan:',
      options: ['Balai Pustaka (Angkatan 20-an)', 'Pujangga Baru', 'Angkatan 45', 'Angkatan 66'],
      correctOptionIndex: 0,
      explanation: 'Angkatan Balai Pustaka berdiri sekitar tahun 1920-an.',
    ),
    QuestionItem(
      id: 'sas_indo_002',
      questionText: 'Novel legendaris karya Marah Rusli yang menjadi lambang roman adat Angkatan Balai Pustaka adalah:',
      options: ['Siti Nurbaya', 'Salah Asuhan', 'Tenggelamnya Kapal Van der Wijck', 'Layar Terkembang'],
      correctOptionIndex: 0,
      explanation: 'Siti Nurbaya karya Marah Rusli terbit tahun 1922.',
    ),
    QuestionItem(
      id: 'sas_indo_003',
      questionText: 'Novel karya Abdul Muis yang mengisahkan pertentangan barat dan timur melalui tokoh Hanafi adalah:',
      options: ['Salah Asuhan', 'Siti Nurbaya', 'Atheis', 'Belenggu'],
      correctOptionIndex: 0,
      explanation: 'Salah Asuhan karya Abdul Muis menceritakan romantika Hanafi dan Corrie.',
    ),
    QuestionItem(
      id: 'sas_indo_004',
      questionText: 'Angkatan sastra Indonesia yang memuat semangat kebangsaan dan modernisme yang dipelopori Sutan Takdir Alisjahbana (STA) dinamakan Angkatan:',
      options: ['Pujangga Baru (Angkatan 30-an)', 'Balai Pustaka', 'Angkatan 45', 'Angkatan 50'],
      correctOptionIndex: 0,
      explanation: 'Pujangga Baru berdiri tahun 1933 dengan majalah sastra Pujangga Baru.',
    ),
    QuestionItem(
      id: 'sas_indo_005',
      questionText: 'Novel karya Sutan Takdir Alisjahbana yang mengisahkan emansipasi wanita melalui tokoh Tuti dinamakan:',
      options: ['Layar Terkembang', 'Belenggu', 'Dian yang Tak Kunjung Padam', 'Sukreni Gadis Bali'],
      correctOptionIndex: 0,
      explanation: 'Layar Terkembang karya STA menggambarkan semangat wanita baru.',
    ),
    QuestionItem(
      id: 'sas_indo_006',
      questionText: 'Novel psikologis karya Armijn Pane yang menggemparkan karena mengangkat problematika rumah tangga Sukartono dan Tini adalah:',
      options: ['Belenggu', 'Layar Terkembang', 'Salah Asuhan', 'Atheis'],
      correctOptionIndex: 0,
      explanation: 'Belenggu karya Armijn Pane pelopor novel psikologis modern.',
    ),
    QuestionItem(
      id: 'sas_indo_007',
      questionText: 'Angkatan sastra yang bersemboyan "Surat Kepercayaan Gelanggang" dan dipelopori oleh Chairil Anwar dinamakan Angkatan:',
      options: ['Angkatan 45', 'Pujangga Baru', 'Angkatan 66', 'Angkatan 80-an'],
      correctOptionIndex: 0,
      explanation: 'Angkatan 45 membawa kebebasan ekspresi dan vitalisme.',
    ),
    QuestionItem(
      id: 'sas_indo_008',
      questionText: 'Penyair pelopor Angkatan 45 yang dijuluki "Si Binatang Jalang" melalui puisinya yang berjudul "Aku" adalah:',
      options: ['Chairil Anwar', 'Asrul Sani', 'Rivai Apin', 'H.B. Jassin'],
      correctOptionIndex: 0,
      explanation: 'Chairil Anwar mengarang puisi ikonik "Aku" (1943).',
    ),
    QuestionItem(
      id: 'sas_indo_009',
      questionText: 'Kritikus sastra terbesar Indonesia yang dijuluki "Paus Sastra Indonesia" adalah:',
      options: ['H.B. Jassin (Hans Bague Jassin)', 'Sutan Takdir Alisjahbana', 'A. Teeuw', 'Ajip Rosidi'],
      correctOptionIndex: 0,
      explanation: 'H.B. Jassin mendirikan Pusat Dokumentasi Sastra H.B. Jassin.',
    ),
    QuestionItem(
      id: 'sas_indo_010',
      questionText: 'Sastrawan Angkatan 45 pengarang kumpulan cerpen "Dari Ave Maria ke Jalan Lain ke Roma" adalah:',
      options: ['Idrus', 'Chairil Anwar', 'Pramoedya Ananta Toer', 'Mochtar Lubis'],
      correctOptionIndex: 0,
      explanation: 'Idrus pelopor prosa realisme Angkatan 45.',
    ),
    QuestionItem(
      id: 'sas_indo_011',
      questionText: 'Novel karya Achdiat Karta Mihardja tentang pergolakan keyakinan tokoh Hasan dinamakan:',
      options: ['Atheis', 'Jalan Tak Ada Ujung', 'Surabaya', 'Keluarga Gerilya'],
      correctOptionIndex: 0,
      explanation: 'Atheis karya Achdiat K. Mihardja terbit 1949.',
    ),
    QuestionItem(
      id: 'sas_indo_012',
      questionText: 'Sastrawan besar Indonesia pengarang mahakarya Tetralogi Buru (Bumi Manusia, Anak Semua Bangsa, dll) adalah:',
      options: ['Pramoedya Ananta Toer', 'Mochtar Lubis', 'Y.B. Mangunwijaya', 'Rendra'],
      correctOptionIndex: 0,
      explanation: 'Pramoedya Ananta Toer maestro novelis Indonesia.',
    ),
    QuestionItem(
      id: 'sas_indo_013',
      questionText: 'Tokoh utama pemuda pergerakan nasional dalam novel "Bumi Manusia" karya Pramoedya Ananta Toer bernama:',
      options: ['Minke', 'Nyai Ontosoroh', 'Annelies', 'Robert Suurhof'],
      correctOptionIndex: 0,
      explanation: 'Minke adalah tokoh utama terinspirasi Tirto Adhi Soerjo.',
    ),
    QuestionItem(
      id: 'sas_indo_014',
      questionText: 'Angkatan sastra yang ditandai protes sosial dan politik Orde Lama dipelopori oleh Taufiq Ismail dan H.B. Jassin dinamakan Angkatan:',
      options: ['Angkatan 66', 'Angkatan 45', 'Angkatan 50', 'Reformasi'],
      correctOptionIndex: 0,
      explanation: 'Angkatan 66 mengangkat puisi perlawanan dan kritik sosial.',
    ),
    QuestionItem(
      id: 'sas_indo_015',
      questionText: 'Penyair Angkatan 66 pengarang kumpulan puisi perlawanan "Tirani" dan "Benteng" adalah:',
      options: ['Taufiq Ismail', 'W.S. Rendra', 'Sapardi Djoko Damono', 'Gerson Poyk'],
      correctOptionIndex: 0,
      explanation: 'Taufiq Ismail penyair penting Angkatan 66.',
    ),
    QuestionItem(
      id: 'sas_indo_016',
      questionText: 'Penyair legendaris yang dijuluki "Si Burung Merak" pendiri Bengkel Teater Jogja adalah:',
      options: ['W.S. Rendra (Willibrordus Surendra Rendra)', 'Sitor Situmorang', 'Subagio Sastrowardoyo', 'Gojan'],
      correctOptionIndex: 0,
      explanation: 'W.S. Rendra dijuluki Si Burung Merak.',
    ),
    QuestionItem(
      id: 'sas_indo_017',
      questionText: 'Penyair lirik Indonesia pengarang puisi "Hujan Bulan Juni" dan "Aku Ingin" adalah:',
      options: ['Sapardi Djoko Damono', 'Goenawan Mohamad', 'Sutardji Calzoum Bachri', 'Joko Pinurbo'],
      correctOptionIndex: 0,
      explanation: 'Sapardi Djoko Damono maestro puisi lirik romantis.',
    ),
    QuestionItem(
      id: 'sas_indo_018',
      questionText: 'Penyair yang dijuluki "Presiden Penyair Indonesia" pengarang kredo puisi membebaskan kata dari makna adalah:',
      options: ['Sutardji Calzoum Bachri', 'Rendra', 'Remy Sylado', 'Afrizal Malna'],
      correctOptionIndex: 0,
      explanation: 'Sutardji Calzoum Bachri pencetus kredo pembebasan kata.',
    ),
    QuestionItem(
      id: 'sas_indo_019',
      questionText: 'Sastrawan pengarang Catatan Pinggir majalah Tempo dan pendiri Komunitas Salihara adalah:',
      options: ['Goenawan Mohamad', 'Arief Budiman', 'Ignas Kleden', 'Nirwan Dewanto'],
      correctOptionIndex: 0,
      explanation: 'Goenawan Mohamad sastrawan dan esais terkemuka.',
    ),
    QuestionItem(
      id: 'sas_indo_020',
      questionText: 'Novel sejarah monumental karya Y.B. Mangunwijaya yang memenangkan Hadiah Sastra SEA Write Award adalah:',
      options: ['Burung-Burung Manyar', 'Roro Mendut', 'Durga Umayi', 'Ikan-Ikan Hiu, Ijo, Teh'],
      correctOptionIndex: 0,
      explanation: 'Burung-Burung Manyar karya Romo Mangun.',
    ),
    QuestionItem(
      id: 'sas_indo_021',
      questionText: 'Sastrawan pengarang Trilogi Ronggeng Dukuh Paruk (Dukuh Paruk, Lantik, Jantera) adalah:',
      options: ['Ahmad Tohari', 'Kuntowijoyo', 'Umar Kayam', 'Danarto'],
      correctOptionIndex: 0,
      explanation: 'Ahmad Tohari mengarang Ronggeng Dukuh Paruk dengan latar Srintil.',
    ),
    QuestionItem(
      id: 'sas_indo_022',
      questionText: 'Novel karya Umar Kayam yang mengisahkan kehidupan priyayi Jawa dan perubahan zaman adalah:',
      options: ['Priyayi (Para Priyayi)', 'Jalan Menikung', 'Bawuk', 'Sri Sumarah'],
      correctOptionIndex: 0,
      explanation: 'Para Priyayi karya Umar Kayam.',
    ),
    QuestionItem(
      id: 'sas_indo_023',
      questionText: 'Sastrawan dan sejarawan pengarang novel "Khotbah di Atas Bukit" dan cerpen "Dilarang Mencintai Bunga-Bunga" adalah:',
      options: ['Kuntowijoyo', 'A.A. Navis', 'Danarto', 'Budi Darma'],
      correctOptionIndex: 0,
      explanation: 'Kuntowijoyo cendekiawan dan sastrawan profetik.',
    ),
    QuestionItem(
      id: 'sas_indo_024',
      questionText: 'Sastrawan Sumatera Barat pengarang cerpen satire terkenal "Robohnya Surau Kami" adalah:',
      options: ['A.A. Navis (Ali Akbar Navis)', 'Mochtar Lubis', 'Chairul Harun', 'Gerson Poyk'],
      correctOptionIndex: 0,
      explanation: 'A.A. Navis mengarang cerpen Robohnya Surau Kami (1956).',
    ),
    QuestionItem(
      id: 'sas_indo_025',
      questionText: 'Novelis wanita Indonesia pengarang novel "Pada Sebuah Kapal", "La Barka", dan "Namaku Hiroko" adalah:',
      options: ['Nh. Dini (Nurhayati Sri Hardini)', 'Saman', 'Ayu Utami', 'Dee Lestari'],
      correctOptionIndex: 0,
      explanation: 'Nh. Dini sastrawan wanita pengarang romansa feminisme.',
    ),
    QuestionItem(
      id: 'sas_indo_026',
      questionText: 'Novel karangan Ayu Utami terbit tahun 1998 yang menandai lahirnya Angkatan Reformasi dalam sastra Indonesia adalah:',
      options: ['Saman', 'Larung', 'Manjali', 'Maya'],
      correctOptionIndex: 0,
      explanation: 'Saman karya Ayu Utami memenangkan Sayembara DKJ 1998.',
    ),
    QuestionItem(
      id: 'sas_indo_027',
      questionText: 'Sastrawan wanita pengarang kumpulan novel "Supernova" (Ksatria, Puteri, dan Bintang Jatuh, dll) adalah:',
      options: ['Dee Lestari (Dewi Lestari)', 'Leila S. Chudori', 'Djenar Maesa Ayu', 'Intan Paramaditha'],
      correctOptionIndex: 0,
      explanation: 'Dee Lestari pengarang seri novel sains-fiksi Supernova.',
    ),
    QuestionItem(
      id: 'sas_indo_028',
      questionText: 'Novelis pengarang "Laut Bercerita" dan "Pulang" yang mengisahkan tragedi sejarah Indonesia adalah:',
      options: ['Leila S. Chudori', 'Ayu Utami', 'Nh. Dini', 'Laksmi Pamuntjak'],
      correctOptionIndex: 0,
      explanation: 'Leila S. Chudori mengarang Laut Bercerita.',
    ),
    QuestionItem(
      id: 'sas_indo_029',
      questionText: 'Sastrawan pengarang novel "Cantik Itu Luka" dan "Lelaki Harimau" yang diterjemahkan ke puluhan bahasa dunia adalah:',
      options: ['Eka Kurniawan', 'A.S. Laksana', 'Budi Darma', 'Puthut EA'],
      correctOptionIndex: 0,
      explanation: 'Eka Kurniawan meraih nominasi The Man Booker International Prize.',
    ),
    QuestionItem(
      id: 'sas_indo_030',
      questionText: 'Sastrawan pengarang novel megah "Laskar Pelangi" yang mengangkat kisah anak-anak Belitung adalah:',
      options: ['Andrea Hirata', 'Habiburrahman El Shirazy', 'Ahmad Fuadi', 'Tere Liye'],
      correctOptionIndex: 0,
      explanation: 'Andrea Hirata mengarang Tetralogi Laskar Pelangi.',
    ),
    QuestionItem(
      id: 'sas_indo_031',
      questionText: 'Aliran sastra yang menggambarkan kenyataan secara jujur dan apa adanya dinamakan realisme:',
      options: ['Realisme', 'Romantisme', 'Surealisme', 'Ekspresionisme'],
      correctOptionIndex: 0,
      explanation: 'Realisme menyajikan fakta realita objektif.',
    ),
    QuestionItem(
      id: 'sas_indo_032',
      questionText: 'Aliran sastra yang mengutamakan ungkapan perasaan, emosi jiwa, dan keindahan imajinasi dinamakan:',
      options: ['Romantisme', 'Realisme', 'Naturalisme', 'Impresionisme'],
      correctOptionIndex: 0,
      explanation: 'Romantisme menonjolkan emosi dan keindahan jiwa.',
    ),
    QuestionItem(
      id: 'sas_indo_033',
      questionText: 'Aliran sastra yang menyajikan dunia mimpi, alam bawah sadar, dan hal-hal yang tidak masuk akal dinamakan:',
      options: ['Surealisme', 'Realisme Sosialis', 'Klasisisme', 'Existensialisme'],
      correctOptionIndex: 0,
      explanation: 'Surealisme menggabungkan mimpi dan fantasi bawah sadar.',
    ),
    QuestionItem(
      id: 'sas_indo_034',
      questionText: 'Aliran sastra yang menggambarkan kenyataan pahit secara telanjang tanpa polesan etika dinamakan:',
      options: ['Naturalisme', 'Romantisme', 'Symbolisme', 'Idealisme'],
      correctOptionIndex: 0,
      explanation: 'Naturalisme menekankan fakta biologis dan lingkungan secara tajam.',
    ),
    QuestionItem(
      id: 'sas_indo_035',
      questionText: 'Majelis gaya bahasa pembandingan langsung dua hal tanpa kata pembanding (seperti "Dewi malam") dinamakan:',
      options: ['Metafora', 'Simile', 'Personifikasi', 'Hiperbola'],
      correctOptionIndex: 0,
      explanation: 'Metafora menyamakan dua hal secara analogis.',
    ),
    QuestionItem(
      id: 'sas_indo_036',
      questionText: 'Gaya bahasa pembandingan yang menggunakan kata tugas pembanding seperti "bagaikan", "seperti", "laksana" dinamakan:',
      options: ['Simile (Asosiasi)', 'Metafora', 'Personifikasi', 'Metonimia'],
      correctOptionIndex: 0,
      explanation: 'Simile eksplisit menggunakan kata pembanding.',
    ),
    QuestionItem(
      id: 'sas_indo_037',
      questionText: 'Majelis gaya bahasa yang menggunakan merk atau nama barang untuk menyebutkan benda secara keseluruhan (misal: "naik Honda") dinamakan:',
      options: ['Metonimia', 'Sinekdoke', 'Alegori', 'Parabola'],
      correctOptionIndex: 0,
      explanation: 'Metonimia menggunakan merk/atribut khas untuk benda.',
    ),
    QuestionItem(
      id: 'sas_indo_038',
      questionText: 'Gaya bahasa yang menyebutkan sebagian untuk keseluruhan (Pars pro toto) atau keseluruhan untuk sebagian (Totem pro parte) dinamakan:',
      options: ['Sinekdoke', 'Metonimia', 'Ironi', 'Litotes'],
      correctOptionIndex: 0,
      explanation: 'Sinekdoke dibedakan menjadi Pars pro toto dan Totem pro parte.',
    ),
    QuestionItem(
      id: 'sas_indo_039',
      questionText: 'Unsur intrinsik fiksi berupa ide pokok yang menjadi dasar pengembangan cerita dinamakan:',
      options: ['Tema', 'Alur', 'Latar', 'Amanat'],
      correctOptionIndex: 0,
      explanation: 'Tema adalah pilar gagasan utama cerita.',
    ),
    QuestionItem(
      id: 'sas_indo_040',
      questionText: 'Sudut pandang di mana pencerita menyebut dirinya dengan kata "Aku" dinamakan sudut pandang:',
      options: ['Orang Pertama Tokoh Utama / Sampingan', 'Orang Ketiga Serba Tahu', 'Orang Kedua', 'Pengamat'],
      correctOptionIndex: 0,
      explanation: 'Sudut pandang orang pertama menggunakan persona "Aku".',
    ),
    QuestionItem(
      id: 'sas_indo_041',
      questionText: 'Sudut pandang di mana pencerita berada di luar cerita dan mengetahui seluruh isi pikiran tokoh dinamakan:',
      options: ['Orang Ketiga Serba Tahu (Omniscient)', 'Orang Pertama', 'Orang Kedua', 'Campuran'],
      correctOptionIndex: 0,
      explanation: 'Orang ketiga serba tahu mengisahkan seluruh rahasia batin tokoh.',
    ),
    QuestionItem(
      id: 'sas_indo_042',
      questionText: 'Alur cerita yang bergerak dari masa depan kembali mengisahkan masa lalu dinamakan alur:',
      options: ['Mundur (Sorot Balik / Flashback)', 'Maju (Progresif)', 'Campuran', 'Sirkular'],
      correctOptionIndex: 0,
      explanation: 'Alur sorot balik menceritakan ingatan masa lalu.',
    ),
    QuestionItem(
      id: 'sas_indo_043',
      questionText: 'Karya sastra drama yang berakhir dengan duka cita dan kesedihan mendalam dinamakan drama:',
      options: ['Tragedi', 'Komedi', 'Tragikomedi', 'Melodrama'],
      correctOptionIndex: 0,
      explanation: 'Tragedi menyajikan penderitaan dan kehancuran tokoh.',
    ),
    QuestionItem(
      id: 'sas_indo_044',
      questionText: 'Karya sastra drama yang penuh dengan kelucuan dan berakhir bahagia dinamakan drama:',
      options: ['Komedi', 'Tragedi', 'Farce', 'Opera'],
      correctOptionIndex: 0,
      explanation: 'Komedi menghibur dengan gelak tawa.',
    ),
    QuestionItem(
      id: 'sas_indo_045',
      questionText: 'Bentuk puisi lama melayu berunsur 4 baris yang setiap barisnya terdiri dari 8-12 suku kata dan berima a-b-a-b adalah:',
      options: ['Pantun', 'Syair', 'Gurindam', 'Seloka'],
      correctOptionIndex: 0,
      explanation: 'Pantun karya puisi melayu berpasangan sampiran-isi.',
    ),
    QuestionItem(
      id: 'sas_indo_046',
      questionText: 'Dua baris pertama pada pantun dinamakan:',
      options: ['Sampiran', 'Isi', 'Koda', 'Bait'],
      correctOptionIndex: 0,
      explanation: 'Baris 1-2 pantun berfungsi sebagai sampiran penyiap rima.',
    ),
    QuestionItem(
      id: 'sas_indo_047',
      questionText: 'Dua baris terakhir (baris 3 dan 4) pada pantun dinamakan:',
      options: ['Isi', 'Sampiran', 'Prolog', 'Pengantar'],
      correctOptionIndex: 0,
      explanation: 'Baris 3-4 pantun memuat pesan inti cerita/isi.',
    ),
    QuestionItem(
      id: 'sas_indo_048',
      questionText: 'Majalah sastra monumental yang didirikan pada tahun 1966 oleh Mochtar Lubis dan H.B. Jassin dinamakan Majalah:',
      options: ['Horison', 'Pujangga Baru', 'Kiswah', 'Basis'],
      correctOptionIndex: 0,
      explanation: 'Majalah Horison benteng terbitan sastra Indonesia abad 20.',
    ),
    QuestionItem(
      id: 'sas_indo_049',
      questionText: 'Sayembara penulisan novel paling bergengsi di Indonesia yang banyak melahirkan karya besar diselenggarakan oleh:',
      options: ['Dewan Kesenian Jakarta (DKJ)', 'Badan Bahasa', 'Kementerian Pendidikan', 'Kompas'],
      correctOptionIndex: 0,
      explanation: 'Sayembara Novel DKJ tradisi tahunan melahirkan maestro novelis.',
    ),
    QuestionItem(
      id: 'sas_indo_050',
      questionText: 'Bentuk kritik sastra yang berfokus pada analisis struktur internal karya (tema, plot, latar, perwatakan) tanpa melihat latar belakang penulis dinamakan pendekatan:',
      options: ['Strukturalisme', 'Sosiologi Sastra', 'Psikologi Sastra', 'Mimetik'],
      correctOptionIndex: 0,
      explanation: 'Strukturalisme mengkaji teks murni sebagai sistem otonom.',
    ),
    QuestionItem(
      id: 'sas_indo_051',
      questionText: 'Pendekatan kritik sastra yang mengkaji hubungan antara karya sastra dan kondisi sosial masyarakat dinamakan pendekatan:',
      options: ['Sosiologi Sastra', 'Strukturalisme', 'Pragmatik', 'Ekspresif'],
      correctOptionIndex: 0,
      explanation: 'Sosiologi sastra meneliti cerminan realita sosial dalam teks.',
    ),
    QuestionItem(
      id: 'sas_indo_052',
      questionText: 'Pendekatan kritik sastra yang mengkaji kondisi kejiwaan dan penciptaan tokoh dinamakan pendekatan:',
      options: ['Psikologi Sastra', 'Mimetik', 'Strukturalisme', 'Semiotika'],
      correctOptionIndex: 0,
      explanation: 'Psikologi sastra menerapkan teori psikoanalisis pada karakter.',
    ),
    QuestionItem(
      id: 'sas_indo_053',
      questionText: 'Ilmu kritik sastra yang mengkaji tanda-tanda dan makna simbolik (tanda, petanda, penanda) dinamakan:',
      options: ['Semiotika / Semiolingua', 'Hermeneutika', 'Filologi', 'Etimologi'],
      correctOptionIndex: 0,
      explanation: 'Semiotika adalah ilmu analisis sistem tanda (Charles Peirce/Saussure).',
    ),
    QuestionItem(
      id: 'sas_indo_054',
      questionText: 'Ilmu yang mempelajari penafsiran dan pemaknaan mendalam teks sastra dinamakan:',
      options: ['Hermeneutika', 'Filologi', 'Dialektologi', 'Grafologi'],
      correctOptionIndex: 0,
      explanation: 'Hermeneutika adalah teori seni interpretasi makna teks.',
    ),
    QuestionItem(
      id: 'sas_indo_055',
      questionText: 'Ilmu yang mempelajari manuskrip naskah-naskah kuno Nusantara dinamakan:',
      options: ['Filologi', 'Paleografi', 'Arkeologi', 'Epigrafi'],
      correctOptionIndex: 0,
      explanation: 'Filologi meneliti teks naskah lama (manuskrip tulisan tangan).',
    ),
    QuestionItem(
      id: 'sas_indo_056',
      questionText: 'Penulis skenario drama panggung "Malam Biadab" dan "Awal dan Mira" adalah:',
      options: ['Utuy Tatang Sontani', 'W.S. Rendra', 'Arifin C. Noer', 'Putu Wijaya'],
      correctOptionIndex: 0,
      explanation: 'Utuy Tatang Sontani pelopor drama realisme Indonesia.',
    ),
    QuestionItem(
      id: 'sas_indo_057',
      questionText: 'Tokoh teater absurd Indonesia pimpinan Teater Mandiri pengarang drama "Aduh" dan "Gim" adalah:',
      options: ['Putu Wijaya', 'Arifin C. Noer', 'N. Riantiarno', 'W.S. Rendra'],
      correctOptionIndex: 0,
      explanation: 'Putu Wijaya adalah maestro teater absurd bertema "terror mental".',
    ),
    QuestionItem(
      id: 'sas_indo_058',
      questionText: 'Pendiri Teater Koma pengarang lakon populer "Opera Kecoa" dan "Sampek Engtay" adalah:',
      options: ['N. Riantiarno (Norbertus Riantiarno)', 'Putu Wijaya', 'Arifin C. Noer', 'Nano Riantiarno'],
      correctOptionIndex: 0,
      explanation: 'N. Riantiarno mendirikan Teater Koma Jakarta.',
    ),
    QuestionItem(
      id: 'sas_indo_059',
      questionText: 'Sutradara teater dan film pengarang lakon "Sumur Tanpa Dasar" dan film "G30S/PKI" adalah:',
      options: ['Arifin C. Noer', 'Teuku Rifnu', 'Teguh Karya', 'Sjumandjaja'],
      correctOptionIndex: 0,
      explanation: 'Arifin C. Noer seniman teater dan sutradara kawakan.',
    ),
    QuestionItem(
      id: 'sas_indo_060',
      questionText: 'Kumpulan puisi religi karya Amir Hamzah sang "Raja Penyair Pujangga Baru" bertajuk:',
      options: ['Nyanyi Sunyi & Buah Rindu', 'Percantikan', 'Kerikil Tajam', 'Tirani'],
      correctOptionIndex: 0,
      explanation: 'Amir Hamzah mengarang himpunan puisi Nyanyi Sunyi.',
    ),
    QuestionItem(
      id: 'sas_indo_061',
      questionText: 'Penyair Angkatan 45 pengarang kumpulan puisi "Tiga Menguak Takdir" bersama Chairil Anwar dan Rivai Apin adalah:',
      options: ['Asrul Sani', 'Sitor Situmorang', 'Mochtar Lubis', 'Usmar Ismail'],
      correctOptionIndex: 0,
      explanation: 'Asrul Sani sastrawan dan sutradara Pelopor 45.',
    ),
    QuestionItem(
      id: 'sas_indo_062',
      questionText: 'Penyair pengarang puisi ikonik "Malam Lebaran" yang hanya terdiri dari satu baris "Bulan di atas kuburan" adalah:',
      options: ['Sitor Situmorang', 'Chairil Anwar', 'Subagio', 'Ajip Rosidi'],
      correctOptionIndex: 0,
      explanation: 'Sitor Situmorang pencipta puisi kilat "Malam Lebaran".',
    ),
    QuestionItem(
      id: 'sas_indo_063',
      questionText: 'Sastrawan Sunda-Indonesia pendiri Yayasan Kebudayaan Rancage penyerah Hadiah Sastra Rancage adalah:',
      options: ['Ajip Rosidi', 'Ramadhan K.H.', 'Ayatrohaedi', 'Ahmad Tohari'],
      correctOptionIndex: 0,
      explanation: 'Ajip Rosidi pelestari sastra daerah dan nasional.',
    ),
    QuestionItem(
      id: 'sas_indo_064',
      questionText: 'Sastrawan pengarang novel "Harimau! Harimau!" dan "Senja di Jakarta" yang gigih membela kebebasan pers adalah:',
      options: ['Mochtar Lubis', 'Pramoedya', 'Rosihan Anwar', 'B.M. Diah'],
      correctOptionIndex: 0,
      explanation: 'Mochtar Lubis jurnalis dan novelis pejuang.',
    ),
    QuestionItem(
      id: 'sas_indo_065',
      questionText: 'Sastrawan pengarang novel eksistensialisme "Olenka" yang berlatar kota Chicago adalah:',
      options: ['Budi Darma', 'Danarto', 'Kuntowijoyo', 'Sutarji'],
      correctOptionIndex: 0,
      explanation: 'Prof. Budi Darma mengarang novel Olenka.',
    ),
    QuestionItem(
      id: 'sas_indo_066',
      questionText: 'Sastrawan magis Indonesia pengarang kumpulan cerpen "Godlob" dan "Adam Ma\'rifat" adalah:',
      options: ['Danarto', 'Budi Darma', 'Kuntowijoyo', 'Arifin C. Noer'],
      correctOptionIndex: 0,
      explanation: 'Danarto pelopor cerpen sufistis magis.',
    ),
    QuestionItem(
      id: 'sas_indo_067',
      questionText: 'Novel komedi religius pengarang "Kembalinya Kurawa" dan novelis humor "Kalatidha" adalah:',
      options: ['Umar Kayam', 'Ahmad Tohari', 'Seno Gumira Ajidarma', 'Remy Sylado'],
      correctOptionIndex: 0,
      explanation: 'Remy Sylado (Japi Tambajong) pelopor puisi mbeling.',
    ),
    QuestionItem(
      id: 'sas_indo_068',
      questionText: 'Gerakan penulisan puisi humor jenaka mengkritik keformalan sastra pada era 1970-an dinamakan Puisi:',
      options: ['Mbeling', 'Bebas', 'Konkret', 'Gelanggang'],
      correctOptionIndex: 0,
      explanation: 'Puisi Mbeling dipelopori Remy Sylado di majalah Aktuil.',
    ),
    QuestionItem(
      id: 'sas_indo_069',
      questionText: 'Sastrawan pengarang kumpulan cerpen "Saksi Mata" dan "Iblis Tidak Pernah Mati" dengan motto "Ketika jurnalisme dibungkam, sastra harus bicara" adalah:',
      options: ['Seno Gumira Ajidarma (SGA)', 'Nirwan Dewanto', 'Eka Kurniawan', 'A.S. Laksana'],
      correctOptionIndex: 0,
      explanation: 'Seno Gumira Ajidarma sastrawan esais terkemuka.',
    ),
    QuestionItem(
      id: 'sas_indo_070',
      questionText: 'Kumpulan cerpen karya Seno Gumira Ajidarma yang memenangkan SEA Write Award bertema tragedi Dili Timor Timur bertajuk:',
      options: ['Saksi Mata', 'Pengantin Iblis', 'Manusia Kamar', 'Dilarang Menyanyi di Kamar Mandi'],
      correctOptionIndex: 0,
      explanation: 'Saksi Mata memuat cerpen-cerpen perlawanan pembungkaman pers.',
    ),
    QuestionItem(
      id: 'sas_indo_071',
      questionText: 'Novel sastra populer fenomenal karya Habiburrahman El Shirazy yang berlatar kehidupan mahasiswa Indonesia di Kairo adalah:',
      options: ['Ayat-Ayat Cinta', 'Ketika Cinta Bertasbih', 'Pudarnya Pesona Cleopatra', 'Bumi Cinta'],
      correctOptionIndex: 0,
      explanation: 'Ayat-Ayat Cinta memicu demam novel islami modern.',
    ),
    QuestionItem(
      id: 'sas_indo_072',
      questionText: 'Penulis novel populer Islami "Rembulan Tenggelam di Wajahmu", "Hujan", dan "Pulang" adalah:',
      options: ['Tere Liye (Darwis)', 'Andrea Hirata', 'Ahmad Fuadi', 'Asma Nadia'],
      correctOptionIndex: 0,
      explanation: 'Tere Liye novelis paling produktif Indonesia.',
    ),
    QuestionItem(
      id: 'sas_indo_073',
      questionText: 'Novel karangan Ahmad Fuadi yang mengisahkan kehidupan santri di Pesantren Modern Gontor bermotto "Man Jadda Wajada" bertajuk:',
      options: ['Negeri 5 Menara', 'Ranah 3 Warna', 'Rantau 1 Muara', 'Anak Rantau'],
      correctOptionIndex: 0,
      explanation: 'Negeri 5 Menara karya Ahmad Fuadi.',
    ),
    QuestionItem(
      id: 'sas_indo_074',
      questionText: 'Bentuk puisi yang mementingkan tata letak visual huruf dan bentuk grafik di atas kertas dinamakan Puisi:',
      options: ['Konkret', 'Lirik', 'Epik', 'Mbeling'],
      correctOptionIndex: 0,
      explanation: 'Puisi konkret memanfaatkan bentuk tipografi gambar.',
    ),
    QuestionItem(
      id: 'sas_indo_075',
      questionText: 'Puisi yang berisi kisah narasi kepahlawanan atau sejarah besar dinamakan Puisi:',
      options: ['Epik / Balada', 'Elegi', 'Romansa', 'Satir'],
      correctOptionIndex: 0,
      explanation: 'Puisi epik/balada menceritakan kepahlawanan (seperti Balada Orang-Orang Rantau).',
    ),
    QuestionItem(
      id: 'sas_indo_076',
      questionText: 'Puisi yang berisi luapan kesedihan, duka cita, atau ratapan dinamakan Puisi:',
      options: ['Elegi', 'Epik', 'Ode', 'Hymne'],
      correctOptionIndex: 0,
      explanation: 'Elegi adalah puisi duka cita.',
    ),
    QuestionItem(
      id: 'sas_indo_077',
      questionText: 'Puisi yang berisi pujian dan penghormatan puji-pujian kepada Tuhan, bangsa, atau pahlawan dinamakan:',
      options: ['Hymne / Ode', 'Elegi', 'Satir', 'Epigram'],
      correctOptionIndex: 0,
      explanation: 'Hymne/Ode memuat puji-pujian keagungan.',
    ),
    QuestionItem(
      id: 'sas_indo_078',
      questionText: 'Puisi yang berisi sindiran atau kritik terhadap kezaliman sosial dinamakan Puisi:',
      options: ['Satir', 'Romansa', 'Ode', 'Elegi'],
      correctOptionIndex: 0,
      explanation: 'Satir memuat sindiran kritikal.',
    ),
    QuestionItem(
      id: 'sas_indo_079',
      questionText: 'Pengulangan bunyi konsonan yang sama pada bait puisi dinamakan aliterasi, sedangkan pengulangan bunyi vokal dinamakan:',
      options: ['Asonansi', 'Aliterasi', 'Rima', 'Ritme'],
      correctOptionIndex: 0,
      explanation: 'Asonansi adalah persetujuan bunyi vokal.',
    ),
    QuestionItem(
      id: 'sas_indo_080',
      questionText: 'Unsur ekstrinsik fiksi mencakup latar belakang penciptaan karya berikut KECUALI:',
      options: ['Jumlah Halaman Buku dan Jenis Kertas', 'Biografi Penulis', 'Kondisi Sosial Budaya Saat Karya Dibuat', 'Pandangan Hidup Pengarang'],
      correctOptionIndex: 0,
      explanation: 'Fisik kertas bukan unsur ekstrinsik sastra.',
    ),
    QuestionItem(
      id: 'sas_indo_081',
      questionText: 'Struktur fiksi drama yang berisi penjelasan latar tempat dan pengenalan karakter sebelum dialog dimulai dinamakan:',
      options: ['Prolog', 'Epilog', 'Kramagung', 'Wawancang'],
      correctOptionIndex: 0,
      explanation: 'Prolog adalah kata pembuka pertunjukan drama.',
    ),
    QuestionItem(
      id: 'sas_indo_082',
      questionText: 'Petunjuk tindakan gerak fisik tokoh dalam naskah drama yang ditulis dalam tanda kurung dinamakan:',
      options: ['Kramagung (Petunjuk Laku)', 'Wawancang', 'Prolog', 'Epilog'],
      correctOptionIndex: 0,
      explanation: 'Kramagung memandu ekspresi dan gerak pemeran.',
    ),
    QuestionItem(
      id: 'sas_indo_083',
      questionText: 'Dialog yang harus diucapkan oleh pemeran drama di atas panggung dinamakan:',
      options: ['Wawancang', 'Kramagung', 'Monolog', 'Solilokui'],
      correctOptionIndex: 0,
      explanation: 'Wawancang adalah ujaran dialog naskah.',
    ),
    QuestionItem(
      id: 'sas_indo_084',
      questionText: 'Cerita rakyat fiksi dari Sumatera Utara tentang pembentukan danau tempat anak ikan jelmaan berada dinamakan Legenda:',
      options: ['Danau Toba', 'Tangkuan Perahu', 'Malin Kundang', 'Roro Jonggrang'],
      correctOptionIndex: 0,
      explanation: 'Legenda Danau Toba latar kisah Toba dan ikan emas.',
    ),
    QuestionItem(
      id: 'sas_indo_085',
      questionText: 'Cerita rakyat Minangkabau tentang anak durhaka yang dikutuk ibunya menjadi batu dinamakan Legenda:',
      options: ['Malin Kundang', 'Siti Nurbaya', 'Cindelaras', 'Bawang Merah Bawang Putih'],
      correctOptionIndex: 0,
      explanation: 'Malin Kundang legenda anak durhaka.',
    ),
    QuestionItem(
      id: 'sas_indo_086',
      questionText: 'Cerita rakyat Jawa Barat tentang pemuda yang ingin menikahi ibunya sendiri (Dayang Sumbi) hingga menendang perahu dinamakan Legenda:',
      options: ['Tangkuban Perahu (Sangkuriang)', 'Ciung Wanara', 'Lutung Kasarung', 'Nyi Roro Kidul'],
      correctOptionIndex: 0,
      explanation: 'Sangkuriang legenda Sangkuriang dan Gunung Tangkuban Perahu.',
    ),
    QuestionItem(
      id: 'sas_indo_087',
      questionText: 'Cerita rakyat Yogyakarta tentang pembentukan candi 1000 buah dalam semalam oleh Bandung Bondowoso dinamakan Legenda:',
      options: ['Roro Jonggrang (Candi Prambanan)', 'Roro Mendut', 'Ken Arok', 'Nyai Ageng Serang'],
      correctOptionIndex: 0,
      explanation: 'Roro Jonggrang dikutuk menjadi patung ke-1000.',
    ),
    QuestionItem(
      id: 'sas_indo_088',
      questionText: 'Konsep nilai moral profetik dalam sastra Indonesia menurut Kuntowijoyo menekankan 3 pilar yaitu Humanisasi, Liberasi, dan:',
      options: ['Transendensi (Ketuhanan)', 'Kapitalisme', 'Sekularisme', 'Modernisme'],
      correctOptionIndex: 0,
      explanation: 'Sastra profetik Kuntowijoyo: Humanisasi, Liberasi, Transendensi.',
    ),
    QuestionItem(
      id: 'sas_indo_089',
      questionText: 'Studi Sastra Bandingan (Comparative Literature) dalam sastra Indonesia mempelajari:',
      options: ['Perbandingan karya sastra Indonesia dengan karya sastra asing/daerah lain', 'Menghitung kata novel', 'Menilai harga buku', 'Penerjemahan murni'],
      correctOptionIndex: 0,
      explanation: 'Sastra Bandingan meneliti interteks karya melintasi batas bangsa.',
    ),
    QuestionItem(
      id: 'sas_indo_090',
      questionText: 'Peristiwa pembakaran dan pelarangan buku-buku sastra karya Pramoedya Ananta Toer pada masa Orde Baru dikategorikan sebagai bentuk:',
      options: ['Censorship (Penyensoran & Pembungkaman Sastra)', 'Kritik Sastra', 'Apresiasi Sastra', 'Resensi'],
      correctOptionIndex: 0,
      explanation: 'Sensor sastra membelenggu kebebasan berkarya.',
    ),
    QuestionItem(
      id: 'sas_indo_091',
      questionText: 'Sastrawan pengarang novel "Keluarga Gerilya" dan "Perburuan" yang ditulis saat dalam penjara adalah:',
      options: ['Pramoedya Ananta Toer', 'Mochtar Lubis', 'Chairil Anwar', 'Utuy Tatang Sontani'],
      correctOptionIndex: 0,
      explanation: 'Pramoedya mengarang Perburuan dan Keluarga Gerilya.',
    ),
    QuestionItem(
      id: 'sas_indo_092',
      questionText: 'Penyair pengarang puisi "Tapi" yang terkenal dengan ekspresi kata berulang "tapi" adalah:',
      options: ['Sutardji Calzoum Bachri', 'Rendra', 'Sapardi', 'Joko Pinurbo'],
      correctOptionIndex: 0,
      explanation: 'Sutardji Calzoum Bachri pencipta puisi "Tapi".',
    ),
    QuestionItem(
      id: 'sas_indo_093',
      questionText: 'Penyair kontemporer Indonesia pengarang kumpulan puisi "Celana" dan "Baju Bulan" yang unik humoris adalah:',
      options: ['Joko Pinurbo (Jokpin)', 'Afrizal Malna', 'Aan Mansyur', 'M. Aan Mansyur'],
      correctOptionIndex: 0,
      explanation: 'Joko Pinurbo khas dengan puisi celana dan kritik keseharian.',
    ),
    QuestionItem(
      id: 'sas_indo_094',
      questionText: 'Penyair pengarang kumpulan puisi "Tidak Ada New York Hari Ini" yang menjadi soundtrack film AADC 2 adalah:',
      options: ['M. Aan Mansyur', 'Joko Pinurbo', 'Adimas Immanuel', 'Fiersa Besari'],
      correctOptionIndex: 0,
      explanation: 'M. Aan Mansyur penyair Makassar pengarang antologi New York.',
    ),
    QuestionItem(
      id: 'sas_indo_095',
      questionText: 'Karya sastra Melayu klasik yang berisi silsilah raja-raja Melayu karangan Tun Sri Lanang adalah Kitab:',
      options: ['Sulalatus Salatin (Sejarah Melayu)', 'Hikayat Hang Tuah', 'Bustanus Salatin', 'Tajus Salatin'],
      correctOptionIndex: 0,
      explanation: 'Sulalatus Salatin atau Sejarah Melayu.',
    ),
    QuestionItem(
      id: 'sas_indo_096',
      questionText: 'Kitab sastrwan klasik Aceh karangan Nuruddin ar-Raniri tentang sejarah dan etika pemerintahan dinamakan:',
      options: ['Bustanus Salatin (Taman Raja-Raja)', 'Tajus Salatin', 'Hikayat Aceh', 'Gurindam 12'],
      correctOptionIndex: 0,
      explanation: 'Bustanus Salatin karya Nuruddin ar-Raniri.',
    ),
    QuestionItem(
      id: 'sas_indo_097',
      questionText: 'Pujangga besar Riau pengarang mahakarya "Gurindam Twelve" (Gurindam Dua Belas) pada tahun 1847 adalah:',
      options: ['Raja Ali Haji', 'Hamzah Fansuri', 'Tun Sri Lanang', 'Ranggawarsita'],
      correctOptionIndex: 0,
      explanation: 'Raja Ali Haji Pahlawan Nasional pengarang Gurindam 12.',
    ),
    QuestionItem(
      id: 'sas_indo_098',
      questionText: 'Pujangga besar Keraton Surakarta pengarang Kitab "Kalatidha" yang meramalkan "Zaman Edan" adalah:',
      options: ['Raden Ngabehi Ranggawarsita', 'Yosodipuro', 'Mangkunegara IV', 'Paku Buwono IV'],
      correctOptionIndex: 0,
      explanation: 'Ranggawarsita pujangga penutup Jawa klasik.',
    ),
    QuestionItem(
      id: 'sas_indo_099',
      questionText: 'Sastrawan sufi klasik Melayu pengarang puisi "Syair Perahu" dan "Syair Burung Pingai" adalah:',
      options: ['Hamzah Fansuri', 'Raja Ali Haji', 'Syamsuddin Sumatrani', 'Nuruddin ar-Raniri'],
      correctOptionIndex: 0,
      explanation: 'Hamzah Fansuri pelopor puisi sufi Melayu abad 16/17.',
    ),
    QuestionItem(
      id: 'sas_indo_100',
      questionText: 'Tujuan utama mempelajari Sastra Indonesia pada tingkat pendidikan tinggi adalah untuk:',
      options: ['Mengembangkan apresiasi kritis, melestarikan kekayaan estetika bangsa, dan menganalisis dinamika kebudayaan Indonesia melalui teks', 'Sekadar membaca novel fiksi', 'Menghafal nama sastrawan', 'Menulis cerita tanpa teori'],
      correctOptionIndex: 0,
      explanation: 'Studi Sastra Indonesia membentuk pemikiran kritis kognitif dan identitas estetika kebangsaan.',
    ),
  ];
}
